### ISSUE TITLE
Query Validation

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#10]
- [x] Arguments of correct type
- [x] [Default values of correct type](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/DefaultValuesOfCorrectType.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/DefaultValuesOfCorrectType-test.js)
- [x] [Fields on correct type](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/FieldsOnCorrectType.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/FieldsOnCorrectType-test.js)
- [x] [Fragments on composite type](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/FragmentsOnCompositeTypes.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/FragmentsOnCompositeTypes-test.js)
- [x] [Known argument names](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/KnownArgumentNames.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/KnownArgumentNames-test.js)
- [x] [Known directives](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/KnownDirectives.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/KnownDirectives-test.js)
- [x] [Known fragment names](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/KnownFragmentNames.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/KnownFragmentNames-test.js)
- [x] [Known type names](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/KnownTypeNames.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/KnownTypeNames-test.js)
- [x] Lone anonymous operations
- [x] [No fragment cycle](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/NoFragmentCycles.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/NoFragmentCycles-test.js)
- [x] [No undefined variables](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/NoUndefinedVariables.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/NoUndefinedVariables-test.js)
- [x] [No unused fragments](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/NoUnusedFragments.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/NoUnusedFragments-test.js)
- [x] [No unused variables](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/NoUnusedVariables.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/NoUnusedVariables-test.js)
- [x] [Possible fragment spreads](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/PossibleFragmentSpreads.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/PossibleFragmentSpreads-test.js)
- [x] [Provide non-null arguments](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/ProvidedNonNullArguments.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/ProvidedNonNullArguments-test.js)
- [x] Scalar leafs
- [x] [Unique argument names](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/UniqueArgumentNames.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/UniqueArgumentNames-test.js)
- [x] [Unique fragment names](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/UniqueFragmentNames.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/UniqueFragmentNames-test.js)
- [x] [Unique input field names](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/UniqueInputFieldNames.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/UniqueInputFieldNames-test.js)
- [x] Unique operation names
- [x] [Unique variable names](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/UniqueVariableNames.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/UniqueVariableNames-test.js)
- [x] [Variables are input types](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/VariablesAreInputTypes.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/VariablesAreInputTypes-test.js)
- [x] Variables in allowed position

**Comment by moserware** [comment]
Here's a rough sketch of what this might take:

1. Create a `GraphQL.Validation.Rules` namespace (and folder) that has one class per rule as defined in [Section 5 of the GraphQL spec](http://facebook.github.io/graphql/#sec-Validation). It's probably a good idea to pattern off of the [graphql-js](https://github.com/graphql/graphql-js/tree/master/src/validation/rules) implementation. It might also be nice to provide a way of generating a link back to the spec itself for each validation error.
2. Update `GraphQL.Validation.DocumentValidator` to go through each rule and aggregate errors into the final `ValidationResult`
3. It could make sense to write a command line tool that extracted the test cases from the [graphql-js](https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__) test suite and converted them into a C# test (with proper license attribution)

**Comment by bryanerayner** [comment]
I have a pull request which implements 1, but that was written before I saw this post. It could be modified easily though to pattern after the JS implementation

**Comment by Henrik-R** [comment]
Hi 

Would you be interested in some help for this issue? 

Regards, Henrik

**Comment by joemcbride** [comment]
@Henrik-R Indeed I would.  Items without a checkmark is available to work on.  I have been using the JavaScript project implementation and test suite as examples.

**Comment by joemcbride** [comment]
The master branch has all of the latest validation infrastructure and rules, so you can just create a PR branch off of master.  A lot of work had to go into creating the infrastructure for the rules, though now that that base is there most of the other rules should go fairly quickly.  There could however be more work needed in the `TypeInfo` or `ValidationContext` classes, though it should be fairly minimal compared to the previous work.

I can only commit to 1-2 rules a week right now.

1. Post here what rule is being worked on.  Provide a separate PR per rule, if possible.
2. Create new rule, naming it the same as the JS project, add it to the Validation folder.
3. Add the rule to the [list of `CoreRules`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/DocumentValidator.cs#L53) in the `DocumentValidator`.
4. Translate all of the JS tests for the given rule to their C# equivalent.

I would start with the rules that are most important to you, I personally have no preference.

If you have a rule completed, though other tests are failing and you're not sure why, feel free to push up what you have and we can figure it out.  There are some core tests that purposefully are sending invalid queries which we may have to "turn off" rules for.

There is a `ValidationTestBase` that includes helper assertions for passing/failing rules.

```
public class ScalarLeafTests : ValidationTestBase<ValidationSchema>
{
    private readonly ScalarLeafs _rule;

    public ScalarLeafTests()
    {
        _rule = new ScalarLeafs();
    }

    [Test]
    public void valid_scalar_selection()
    {
        var query = @"
            fragment scalarSelection on Dog {
              barks
            }
            ";

        ShouldPassRule(_ =>
        {
            _.Query = query;
            _.Rule(_rule);
        });
    }

    [Test]
    public void interface_type_missing_selection()
    {
        var query = @"{
              human {
                pets
              }
            }
            ";

        ShouldFailRule(_ =>
        {
            _.Query = query;
            _.Rule(_rule);
            _.Error(
                message: _rule.RequiredSubselectionMessage("pets", "[Pet]"),
                line: 3,
                column: 21);
        });
    }
}
```

**Comment by jaymitchell** [comment]
I've got the "Unique variable names" rule ready to push. How do you decide where it fits in the list of core rules?

**Comment by joemcbride** [comment]
Awesome!  I go off of the list from the JS project:

https://github.com/graphql/graphql-js/blob/master/src/validation/specifiedRules.js#L90-L115

**Comment by joemcbride** [comment]
I decided to create a new issue for the "Overlapping fields" rule so I can pronounce this one complete.  All rules save that one are merged to master!

Overlapping Fields: https://github.com/graphql-dotnet/graphql-dotnet/issues/160

**Comment by joemcbride** [comment]
Last of these were published in https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.10.3.478
