### ISSUE TITLE
How to set a custom directive on field?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1002]
## Summary

I want to build this schema programmatically:

```graphql
directive @isAuthenticated on FIELD_DEFINITION
directive @hasScope(scope: [String]) on FIELD_DEFINITION
type Product {
  id: ID!
  sku: String
  qty: Int
  price: Int
  parrot: String
  rating: Int @hasScope(scope: ["read:rating"])
}
type Query {
  product: Product @isAuthenticated
}
```

I know about `RegisterDirective` method on Schema but I don't undestand how I can set this directive to a **specific field**:

```csharp
public class ProductType : ObjectGraphType<Product>
    {
        public ProductType()
        {
            Name = "Product";

            Field(p => p.Id);
            Field(p => p.Qty, nullable: true);
            Field(p => p.Price, nullable: true);
            .....
            Field(p => p.Rating).Description("blablabla");
            // what I want to specify
            // Field(p => p.Rating).Description("blablabla").AddDirective(somedirective);
        }
    }
``` 

How can I add a directive to a field when building a schema?

**[UPDATE]** 
I tried to build a scheme not programmatically, but reading its contents from a SDL file using `Schema.For`. I see that the directives are read from the file and added to the `Schema._directives` field, but I don’t see that they somehow associated with the fields.

Also I checked if the directives are read by the downstream parser using this code:
```csharp
 var lexer = new GraphQLParser.Lexer();
 var parser = new GraphQLParser.Parser(lexer);
 var ast = parser.Parse(new GraphQLParser.Source(File.ReadAllText(PATH_TO_FILE)));
```
Inside the AST, those directives are associated with the relevant fields and their parameters are filled. This information simply does not fall into the `Schema` object.

Do I understand correctly that the object `FieldType` does not yet have support for the directives placed on it (also I checked `FieldType.Metadata` property and it is empty)?

**Comment by BilyachenkoOY** [comment]
Directives is something common which is shared between whole schema, which means, API user can apply it to any field.

**Comment by joemcbride** [comment]
There are two aspects to this.  Directives used when defining a Schema and Directives used when executing a Query/Mutation/Subscription.  This project currently supports the directives defined in the specification - `@skip` `@include` and `@deprecated`.  `@skip` and `@include` are used on execution.  `@deprecated` is used on definition.  Today you can provide your own custom directives for use on execution, however there isn't currently an easy way to provide custom directives when defining a schema.

If you look at how `graphql-tag` does it, they wrap the field resolver with a new one that first checks the defined directives.  There is no alteration to the existing Fields to add a Directives property.

https://github.com/apollographql/graphql-tools/blob/b345486fe2b11a35a2d431e6429d44e01f9ee8a3/src/generate/attachDirectiveResolvers.ts#L29-L38

```javascript
field.resolve = (...args: any[]) => {
    const [source /* original args */, , context, info] = args;
    return resolver(
        async () => originalResolver.apply(field, args),
        source,
        directiveArgs,
        context,
        info,
    );
};
```

**Comment by joemcbride** [comment]
#1172 Adds support for custom directives, which can alter the resolver, on schema definition.

**Comment by sungam3r** [comment]
Very happy about this feature! But do I understand correctly that these custom directives now still do not fall into the results of the introspection request? My need is to provide knowledge about available custom directives **to client**. I am using a client generator and directives will affect the look of the resulting client code. I think that for this we need to somehow modify `__Field`/`__EnumValue` classes. I think in the right direction?

**Comment by joemcbride** [comment]
@sungam3r `__Field` and `__EnumValue` are defined by the spec so those can't be altered directly.  The values they return can though.  Can you provide an example of what you want to do?

**Comment by joemcbride** [comment]
@sungam3r Maybe you can add what you need to `extensions` like metrics does?

https://graphql-dotnet.github.io/docs/getting-started/metrics

**Comment by mikelneo** [comment]
@joemcbride 
There are directives like [GraphQLDeprecatedDirective](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/DirectiveGraphType.cs#L121), that affect `FieldDefinition`. Is there a way to register this type of directive in `ObjectGraphType`? Like:
```c#
public class SomeType : ObjectGraphType<Some>
{
	public SomeType()
	{
		Name = "Some";

		// Field(p => p.SomeField).Description("Test").AddDirective(DirectiveGraphType.Deprecated);
	}
}
```

**Comment by joemcbride** [comment]
@mikelneo no, there is not currently a way to set a directive on field definition using GraphType first syntax.  You can deprecate a field by setting the deprecation text.

**Comment by mikelneo** [comment]
Thanks for answer. 
> You can deprecate a field by setting the deprecation text

`GraphQLDeprecatedDirective` was just an example of directive type I want to use. Actually, I want to create my own Schema directive, as in the example https://github.com/graphql-dotnet/graphql-dotnet/issues/1002#issue-404767386. So is there any way (not through GraphType first syntax) to create custom directive on field definition?

**Comment by joemcbride** [comment]
@mikelneo Yes - you can do it using Schema First syntax.  See this PR:  https://github.com/graphql-dotnet/graphql-dotnet/pull/1172

**Comment by sungam3r** [comment]
Guys, I just noticed that I made a mistake in my original question. I incorrectly specified the location of the directives. I talked about _TypeSystemDirectiveLocation_, not _ExecutableDirectiveLocation_. I fixed the text of the original question.

**Comment by mac2000** [comment]
Seems like solving this is also required for #1308 e.g. somehow we should be able to tell something like:

```
Field(p => p.SomeField).Description("Test").AddDirective(DirectiveGraphType.External);
```

but the question then how should additional params be passed to such directives and how to deal with directives which may be repeated

**Comment by sungam3r** [comment]
@mac2000 You are asking the right questions. I use #1329 as an experimental solution to the directives problem. So far, everything is going well. We attach directives in the code, we can use different parameters for them. And most importantly - we get information about directives through introspection.

I will make a small correction to your example:
```c#
Field(p => p.SomeField).Description("Test").AddDirective(new ExternalDirectiveVisitor());
```
`DirectiveGraphType` - is a **declaration** of directive itself.
`Visitor` - is a implementation of directive **behavior**. You apply the directive to the field, but applying the directive is not the directive itself.

I must admit that in #1329 not everything is so smooth. There are several issues that need to be addressed. The question of the lifetime of visitors has not yet been resolved. On the one hand, they seem to be singleton (@joemcbride insists on that). On the other hand, in this case it is harder to operate with the parameters, because they need to be stored somewhere and somehow transferred into visitor.

But the main thing for me is the ability to provide information on directives applied to fields (and not only to fields). See graphql/graphql-spec#300 . I believe that the spec will one day expand to support this.

**Comment by sungam3r** [comment]
Regarding my comment https://github.com/graphql-dotnet/graphql-dotnet/issues/1002#issuecomment-552145336 - I got all my questions answered. Well, actually I just added directive support myself 😄 

#1329 was refactored and merged. Also see #2276. It will be included into v4. We are now at the stage of reviewing and writing documentation. I am closing this task. The release should appear from day to day. Ping @joemcbride @mikelneo @mac2000 @Shane32 .
