### ISSUE TITLE
Deserialize Json to Dynamic 

### ISSUE THREAD

**Issue by W2K** [graphql-dotnet/graphql-dotnet#1006]
## Summary
I am trying to pass Json string as input field, then I am trying to deserialize it to dynamic type in resolver.
The problem is that after resolving I don't get the expected deserialized object but JsonString. What am I donig wrong ?
## Relevant information
The  type definition. There I would like to deserialize the value received (json string) as dynamic 
``` 
public class InputIntegrationParameters : InputObjectGraphType<DomainMetadataDefinition>
    {
        public InputIntegrationParameters()
        {
            Field(p => p.IsActive);
            Field(p => p.MetadataSource);
            Field<StringGraphType>("configurationParameters", resolve: p =>
            {
                var data = JsonConvert.DeserializeObject<dynamic>(p.GetPropertyValue<string>());
                return p.Source;
            });
        }
    }

```
Type usage:
```
class InputGame : InputObjectGraphType<GameDefinition>
    {
        public InputGame()
        {
            Field<InputIntegrationParameters>("gameMetadata", resolve: ctx=>ctx.Source.GameMetadata);
            Field<ListGraphType<InputGameStage>>("gameStages", resolve: ctx => ctx.Source.GameStages);
        }
    }
```
Mutation:
```
           FieldAsync<BFF.Admin.Game.Model.Game>("createGame", arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<InputGame>>() {Name = "game"}),
                resolve: async context =>
                {
                    var commandParams = context.GetArgument<GameDefinition>("game");
                    var result = await gameService.CreateGame(commandParams,context.CancellationToken);
                    return result;
                });
```
As the result in commandParameters i would like to receive deserialized dynamic. Instead I get encoded string that was received from FE.

**Comment by OpenSpacesAndPlaces** [comment]
Not sure if this is what you mean, but this worked fine for me to output first full child data:
https://github.com/graphql-dotnet/graphql-dotnet/issues/474

Then loading via:
	`		schema.RegisterValueConverter(new JsonGraphTypeConverter());`

**Comment by sungam3r** [comment]
@W2K Is this issue still actual for you?

**Comment by sungam3r** [comment]
@W2K  See #1176 and related issues. Resolvers are ignored for fields inside inputs. But now you **can** use custom deserializer inside `context.GetArgument<GameDefinition>("game");`. Use `ValueConverter.Register` APIs.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
