### ISSUE TITLE
ABCModel cannot be coerced effectively to a GraphQL type

### ISSUE THREAD

**Issue by MagenicJB** [graphql-dotnet/graphql-dotnet#1009]
Good Morning,

I am running into this error and failing to find / understand what I am seeing on Google and the Star Wars example. Here is my setup. I'm thinking you don't need to see the models but if so I can post. 

```
public class IType : ObjectGraphType<IModel>
    {
        public IType()
        {
            Field(x => x.iD);
            Field(x => x.fullName);
            Field(x => x.email);            
        }
    }

public class PType : ObjectGraphType<PModel>
    {
        public PType()
        {
            Field(x => x.PID);
            Field(x => x.PValue);
            Field<ListGraphType<SType>>("SKS");          
        }
    }

public class SType : ObjectGraphType<SModel>
    {
        public SType()
        {
            Field(x => x.SID);
            Field(x => x.Name);   
        }
    }
```

Now I created a model and a type that combines all of the above into one complex object.

```
public class IPModel
    {
        public string iD {get;set;}
        public string fullName{get;set;}
        public string email{get;set;}
        public PModel PWS{get;set;}
    }

public class PModel
    {
        public int id {get;set;}
        public List<SModel> SKS{get;set;}=new List<SModel>();
    }


public class IPType : ObjectGraphType<IPModel>
    {
        public IPType()
        {
            Field(x => x.iD);
            Field(x => x.fullName);
            Field(x => x.email);
            Field<PModel>(x => x.PWS);   //Error occurs resolving this type
        }
    }
```

My error occurs on the line with the comment above.

> Innermost exception 	 System.ArgumentOutOfRangeException : The type: PModel cannot be coerced effectively to a GraphQL type.

Now I'm sure this is not a bug but a lack of knowledge / understanding on my part so if you could post links to documentation / examples as well as instruction as to what I am doing wrong I would greatly appreciate it.

**Comment by bogdancice** [comment]
@MagenicJB I think you have to specify the GraphQL type.

Try it this way: `Field(x => x.PWS, nullable:true, type:typeof(PType));`

**Comment by MagenicJB** [comment]
@bogdancice I cross posted [here](https://stackoverflow.com/questions/54595778/net-graphql-type-abcmodel-cannot-be-coerced-effectively-to-a-graphql-type/54635139#54635139) and stumbled upon this "solution" a couple days ago. 

Field<PModel>("PWS"); //NOTE:replaced lamda above with string value for name

So it really seems to have something to do with complex types not being able to "get everything needed" from the lambda and you need to explicitly declaring the type. 

I do like your way better and refactored to that.

Thanks
