### ISSUE TITLE
Required access to query ComplexityResult for telemetry purposes

### ISSUE THREAD

**Issue by shivangbansal** [graphql-dotnet/graphql-dotnet#1012]
Hi, 

I am looking for the access of query ComplexityResult (Complexity & TotalQueryDepth) for the telemetry purposes, which is being calculated in `Analyze` method inside `ComplexityAnalyzer` class.

As the class `AnalysisContext` is currently private, I cannot find any way to access the same.

Is there any way to get the access for `ComplexityResult` or any plans to expose it out?

**Comment by shivangbansal** [comment]
@joemcbride If you think this could be the part of Complexity Analyzer, I can raise a PR for the same. 
Please let me know your inputs on this.

**Comment by sungam3r** [comment]
@shivangbansal #1281 solves this problem by providing a virtual `Analyzed` method. You can override it and pass your instance into `DocumentExecuter` ctor.
