### ISSUE TITLE
How do I... Full Subfields?

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/graphql-dotnet#1014]
I have a complex object structure defined - that's all working great (very basic example below).

```
parent {
id : int,
child  : object
}

child {
id : int,
value : string
}
```

The trouble I'm running into is that I want to be able to look at the ResolveFieldContext.SubFields.Keys - hierarchically.  

e.g.

```
parent {
id,
child  {
value
}
}
```

If I queried 10 items from the database, each with one child. That would be 11 resolvers and 11 queries.

At level one I would see:
```
 {
id,
child  
}
```

At level two I would see:
```
 {
value
}
```

The end goal is I want to be able pull the full hierarchy and run everything from one resolver.
(Full disclosure I'll still need to work out the lambda expression trees for EF Core, but this should be doable).

Any help here would be appreciated!

**Comment by joemcbride** [comment]
If I'm understanding what you're needing, using a Dataloader may help you solve this issue.  It can help transform those 11 resolvers into a single query to the database.

Docs: https://graphql-dotnet.github.io/docs/guides/dataloader
Blog post: http://fiyazhasan.me/graphql-with-asp-net-core-part-x-data-loader-series-finale/

**Comment by OpenSpacesAndPlaces** [comment]
Thanks @joemcbride !

That gets me closer to something reasonable (I coded out a demo app to play with it) - it's at least down to one database call per level. (which is way better that way).
It's still kind of heavy given that it still has to run a resolver per item.

----

I think in a perfect world "ResolveFieldContext.FieldAst.SelectionSet" would have the types and I'd be able to-do everything from one resolver.

**Comment by OpenSpacesAndPlaces** [comment]
@joemcbride When I switched over to "ResolveAsync" from "AddField(new FieldType" - I keep getting null for the result of the sub-field resolver. (no errors).

Any ideas for debugging?

Rough example of how I have this laid out below:

```
FieldBuilder<object, dynamic> fb = Field<ObjectGraphType<object>, dynamic>(ColumnName)
				.ResolveAsync(rfc =>
				{
					return TestMe<T, KParent, KChild>.ResolveOne(rfc,);
				});
```

	 ```
   public static Task<dynamic> ResolveOne(ResolveFieldContext<object> rfc)
	    {
		    IDataLoader<KParent, dynamic> loader = Accessor.Context.GetOrAddBatchLoader<KParent, dynamic>(name,
            fetchFunc: (keys, token) => { return LoadOne(rfc,keys,token); },
		    keyComparer: EqualityComparer<KParent>.Default
			);
		    return loader.LoadAsync(AutoMapper.Mapper.Map<KParent>(rfc.Source));
	    }
```
```

    private static Task<IDictionary<KParent, dynamic>> LoadOne(ResolveFieldContext<object> rfc
IEnumerable<KParent> keys, CancellationToken cancellationToken)
	    {
		   List<dynamic> lst = RunData(rfc,  keys);

		    IDictionary<KParent, dynamic> d = lst.ToDictionary(k => (KParent) k[nameof(BaseEntity.Parent)], v =>v);

		    return Task.FromResult(d);
	    }
```

**Comment by OpenSpacesAndPlaces** [comment]
@joemcbride 

I think this can be closed.

I was able to work out the problems by copying some of the source code classes over and setting up debug points.

---

Generically I think my feedback/suggestion would be to consider some kind of warning/unlikely data cases system, especially around data-loaders, given all the layers of abstraction.

As simple example of what I mean:
` LoadAsync` in `CollectionBatchDataLoader`

loads data like
`result[key];`

Expect that if for example your `IEqualityComparer` needs adjusted (or some other related problem) that method, buried three classes deep inside dlls just returns "[]". As a first time user it turns into a needle haystack problem of:  is there something out of alignment with the overall architecture of my graph classes or some obfuscated user error? It's generally hard to tell.

I certainly wouldn't expect not to have to my own digging, but at the same time it seems there may be an enhancement possible somewhere in process that reduces the need to drop in source code to figure out why something isn't resolving.
