### ISSUE TITLE
Nullable types ObjectGraphType

### ISSUE THREAD

**Issue by LuizHenriqueCezar** [graphql-dotnet/graphql-dotnet#1016]
Can I force a field to return null with a model non-null like this?

```
public class Model
{
    public int fieldInt{get; set;}
}

Field(a => a.fieldInt, nullable: true)
   .Resolve(context =>
  {
     return null;
  });
```

This is throwing to me an error:
`Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicity convertible to the delegate return type.`

**Comment by LuizHenriqueCezar** [comment]
I solved my problem using something like this.

```
Field<IntGraphType>(
               "fieldInt",
               resolve: context => null);
```

**Comment by joemcbride** [comment]
This may or may not be a bug, in that I can see that being a bit confusing.  I'm not sure if that would be possible though with the generics in use.  You can define your field like such in the meantime:

```
Field<IntGraphType>("fieldInt", context => null);
```

**Comment by SimonCropp** [comment]
@LuizHenriqueCezar is this still an issue for you?

**Comment by sungam3r** [comment]
@LuizHenriqueCezar Could you change your model like that?
```c#
public class Model
{
    public int? fieldInt{get; set;}
}
```

**Comment by sungam3r** [comment]
Closed due to inactivity.
