### ISSUE TITLE
Invalid data when retrieving large list

### ISSUE THREAD

**Issue by aslamhadi** [graphql-dotnet/graphql-dotnet#1018]
First of all, thank you for creating this library. it helps me a lot.

## Description
I have this query 
```
query($limit:Limit) {
  projects(limit:$limit) {
    items {
      id
      roles {
        id
        name
        people {
          id
          email
        }
      }
    }
  }
}
```
```
{
  "limit": {
    "first": 100,
    "offset": 0
  }
}
```

projects have X roles. and each role has Y people. The issue here is that whenever several projects have the same roles, it will always results in the same people.

This issue only happens when retrieving multiple projects. 

However if I retrieve a single project it returns correct people with roles.

### Expected result

It should filter the people based on project and role. 

### Actual result

it returns the same `people` data whenever same role appears.

### Environment
Version: 2.4.0
OS: Windows (I also tried in Ubuntu )

### Screenshots
Project id `1a728cc8-1bad-4422-bde5-3f5d95dd1af9` and `49aeb07c-41be-4670-b6a2-039535cf92c2`
should have different people even though it has the same roles. Perhaps it cache the results? If so, how do I do to disable the cache?

![image](https://user-images.githubusercontent.com/2888253/53064689-52acc200-34fb-11e9-9ef9-581c991b8840.png)
![image](https://user-images.githubusercontent.com/2888253/53064703-5d675700-34fb-11e9-8b3d-1481457324e5.png)

**Comment by huysentruitw** [comment]
The problem will be in the code behind, please share a snippet that shows how the roles are resolved inside the project item class.

**Comment by joemcbride** [comment]
Just to re-iterate what @huysentruitw mentioned, this will be an issue in your code.  There is nothing built-into this framework that does any filtering or paging.  So I would double check that the data you are returning in your resolver is correct.

**Comment by OpenSpacesAndPlaces** [comment]
@aslamhadi  Dataloaders do have an in-memory cache, but as others said, this would still be a user problem. ( ran into something like that and needed to sideload some source code classes to track it down.)

If that's the case, I'd check your usage of TKey and IEqualityComparer - the data loader doesn't validate your keys, and you could end with bad data/no data.

**Comment by aslamhadi** [comment]
Hi everyone, thanks for all the replies! I fixed this issue by changing graphql structure.

**Before**:
I resolve `projects`. `projects` contain `roles` resolver, and `roles` contain `people` resolver. 
`projects -> roles -> people`.

```
public class ProjectQL : ObjectGraphType<Project>
{
    public ProjectQL(RoleService roleService)
    {
        Field(x => x.Id).Description("Project Id");
        Field<ListGraphType<RoleQL>, List<Role>>()
            .Name("roles")
            .Resolve(ctx =>
            {
                return roleService.GetRolesByProjectId(ctx.Source.Id);
            });
    }
}

public class RoleQL : ObjectGraphType<Role>
{

    public RoleQL(PersonService personService)
    {
        Field<ListGraphType<PersonQL>, List<PersonWithPlainPasswordDTO>>()
            .Name("people")
            .Description("People in role")
            .ResolveAsync(ctx =>
            {
                return personService.GetPeopleByProjectAndRole(ctx.Source.ProjectId, ctx.Source.Id);
            });
    }
}

public class PersonQL : ObjectGraphType<PersonWithPlainPasswordDTO>
{
    public PersonQL()
    {
        Field(x => x.Id).Description("Person's Id");
        Field(x => x.FName, nullable: true).Description("Person's First Name");
        Field(x => x.LName, nullable: true).Description("Person's Last Name");
    }
}
```

**After**:
I created a new type, `projectUserRoles` for this specific usage. `projectUserRoles` contains project definition, roles, and people. So this will resolve all required data in one call and the result data is valid when I cross check it with the database.

```
public class ProjectUserRolesQL : ObjectGraphType<Project>
{
    public ProjectUserRolesQL()
    {
        Field(x => x.Id).Description("Project Id");
        Field<ListGraphType<RolePeopleQL>>("RolePeople", resolve: x => x.Source.RolePeople);
    }
}

// role people definition
public class RolePeopleQL : ObjectGraphType<RolePeople>
{
    public RolePeopleQL()
    {
        Field(x => x.Id);
        Field(x => x.Name);
        Field<ListGraphType<PersonQL>>("People", resolve: x => x.Source.People);
    }
}
```

again, thanks for creating this great library! it helps me a lot :)
have a great day!
