### ISSUE TITLE
Field Middleware Dependencies

### ISSUE THREAD

**Issue by bugged84** [graphql-dotnet/graphql-dotnet#1020]
Field middleware constructor parameters do not seems to get resolved by the Schema dependency resolver. Is there way to inject dependencies into field middleware?

**Comment by OpenSpacesAndPlaces** [comment]
Generally, and this is my experience using Framework without any DI, most things can either be passed through and/or you can reference a public static class.

I've yet to run into anything that "required' DI.

---

That said, someone with more DI experience may be able to chime in.

**Comment by joemcbride** [comment]
@bugged84 Not at this time.  Right now the field middleware is created using `Activator.CreateInstance`.

**Comment by bugged84** [comment]
> Generally, and this is my experience using Framework without any DI, most things can either be passed through and/or you can reference a public static class.
> 
> I've yet to run into anything that "required' DI.
> 
> That said, someone with more DI experience may be able to chime in.

How would you get runtime dependencies such as an HTTP request context by using only static classes?

**Comment by bugged84** [comment]
> @bugged84 Not at this time. Right now the field middleware is created using `Activator.CreateInstance`.

How do you feel about something like this instead? There would need to be some fail checks of course.

```
var args = new List<object>();

foreach (var c in typeof(MyMiddleware).GetConstructors(BindingFlags.Public))
{
   foreach (var p in c.GetParameters())
   {
      args.Add(_dependencyResolver.Resolve(p.ParameterType));
   }
}

Activator.CreateInstance(typeof(object), args);
```

**Comment by joemcbride** [comment]
@bugged84 I would be fine with something like that, though the field middleware would need to have a heavy refactoring to support that.

Overall, field middleware needs a big overhaul.  Right now field middleware is applied individually to each field.  I would like to change that so you could have both "global" middleware and field specific middleware.  Right now the middleware is basically global, though it is applied once to each field.  I think we could save some processing cycles by changing that.

**Comment by OpenSpacesAndPlaces** [comment]
@bugged84 

> How would you get runtime dependencies such as an HTTP request context by using only static classes?

For something like request context I use:
```
_executer.ExecuteAsync(_ =>
		{
			_.UserContext = HttpContext.Current;
		});
```
UserContext is available from anything in the "ResolveFieldContext" flow. (or whatever you want to pass through).

Otherwise there is a "Metadata" property on most GraphTypes/Field Types you can define at runtime.

Likewise any statics I'm using are runtime defined, so I can stick whatever I need in them for look-ups.

----

If you have no other options for your use case, then likely you could write something relatively using "System.Collections.Concurrent" statically that should be problem free (but I wouldn't do that as a first line solution).

**Comment by bugged84** [comment]
> @bugged84
> 
> > How would you get runtime dependencies such as an HTTP request context by using only static classes?
> 
> For something like request context I use:
> 
> ```
> _executer.ExecuteAsync(_ =>
> 		{
> 			_.UserContext = HttpContext.Current;
> 		});
> ```
> UserContext is available from anything in the "ResolveFieldContext" flow. (or whatever you want to pass through).
> 
> Otherwise there is a "Metadata" property on most GraphTypes/Field Types you can define at runtime.
> 
> Likewise any statics I'm using are runtime defined, so I can stick whatever I need in them for look-ups.
> 
> If you have no other options for your use case, then likely you could write something relatively ok using "System.Collections.Concurrent" statically that should be problem free (but I wouldn't do that as a first line solution).
> 
> It's also possible to leverage "HttpContext.Current.Items" if that helps your use case too.

**Comment by SimonCropp** [comment]
@bugged84 is this answered to your satisfaction?

**Comment by bugged84** [comment]
@OpenSpacesAndPlaces 

> UserContext is available from anything in the "ResolveFieldContext" flow. (or whatever you want to pass through).

Hmm. That's interesting that you put whatever you want in `UserContext`. I had forgotten that this was just an `object` on `ResolveFieldContext`. This is probably the best workaround given the current version of the library, despite the name of the property being misleading. In other words, you can inject dependencies into the `GraphQLController` and then assign those services to properties on the `UserContext` of the `ExecutionOptions`.

```
... new ExecutionOptions
{
    Schema = m_schema,
    Query = request.Query,
    Inputs = request.Variables.ToInputs(),
    UserContext = new MyContext {
        User = m_claimsPrincipalProvider.User,
        MyService1 = m_myService1,
        MyService2 = m_myService2,
        etc ...
    }
}
...
```

> Otherwise there is a "Metadata" property on most GraphTypes/Field Types you can define at runtime.

Sure, but it seems awkward to inject "dependencies" into a graph type just to set metadata for another class to use. The injected "dependency" would not be a true dependency of the graph type.

> Likewise any statics I'm using are runtime defined, so I can stick whatever I need in them for look-ups.

I don't like static dependencies in general due to complications that they impose on unit testing.

> If you have no other options for your use case, then likely you could write something relatively ok using "System.Collections.Concurrent" statically that should be problem free (but I wouldn't do that as a first line solution).

This seems like overkill when IoC is the expected standard for modern .NET libraries.

> It's also possible to leverage "HttpContext.Current.Items" if that helps your use case too.

`HttpContext.Current` was removed from ASP.NET Core.

**Comment by bugged84** [comment]
> @bugged84 is this answered to your satisfaction?

Yes, I think the `UserContext` workaround is sufficient.

**Comment by OpenSpacesAndPlaces** [comment]
> It's also possible to leverage "HttpContext.Current.Items" if that helps your use case too.
> 
> HttpContext.Current was removed from ASP.NET Core.

I referenced "HttpContext.Current" since I'm using DI free .Net Framework build.

.Net core still has that property though:
```
HttpContext ctx = 'grab context from your middleware or DI';
ctx.Items;
```

I bring that up because if your use case would be helped by it - Items is going be available on the whole stack vs. UserContext only being in the GraphQL layer.

In my use case UserContext was fine given I'm only referencing it for `IAuthorizationRequirement`.

**Comment by bugged84** [comment]
> I referenced "HttpContext.Current" since I'm using DI free .Net Framework build.
> 
> .Net core still has that property though:

That's just it, though, that static property literally does not exist in ASP.NET Core. Of course, you can still get the `HttpContext` through an `IHttpContextAccessor` that can be injected like any other dependency, but there is no static reference to the current `HttpContext` like in ASP.NET.

That being said, it is specifically the GraphQL `FieldMiddleware` to which my question refers, so the fact that you can't inject anything made it difficult to get a reference to the `HttpContext`. However, passing it to the `FieldResolutionContext` of the `FieldMiddleware` `Invoke` method by using the `UserContext` seems like a decent workaround.

**Comment by hundreder** [comment]
To add FieldMiddleware I am using custom GraphQLExecutor which you can see in this template project
[InstrumentingGraphQLExecutor](https://github.com/Dotnet-Boxed/Templates/blob/a5c351a76248b7708c2d685c638cd483639cebaa/Source/Content/GraphQLTemplate/InstrumentingGraphQLExecutor.cs)

Instead of "registering" field middleware in line 62 
`options.FieldMiddleware.Use<InstrumentFieldsMiddleware>();`
, you can use delegate that would represent that middleware. You can extend InstrumentingGraphQLExecutor's constructor to add whatever dependency you want, so you would end up with something like
`options.FieldMiddleware.Use(next =>
{
  return context =>
  {
    fooDependency.Bar();
    return next(context);
  };
});`

Hope this helps somehow.

**Comment by sergeykotelnikov78** [comment]
The problem is actual. 
In our project we use the follow workaround:
1) Added 
```
public interface IFieldMiddleware
{
    Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next);
}
```
2) In ExecutionOptions added collection of IFieldMiddleware instances to FieldMiddleware property:
```
IEnumerable<IFieldMiddleware> _fieldMiddlewares;
...
foreach (var middleware in _fieldMiddlewares)
                    options.FieldMiddleware.Use(next => context => middleware.Resolve(context, next));
...
```

So we use DI to init all field middlewares with their dependencies.

I think it or the similar should be add to the library.

**Comment by sungam3r** [comment]
>  I would be fine with something like that, though the field middleware would need to have a heavy refactoring to support that. Overall, field middleware needs a big overhaul. Right now field middleware is applied individually to each field. I would like to change that so you could have both "global" middleware and field specific middleware. Right now the middleware is basically global, though it is applied once to each field. I think we could save some processing cycles by changing that.

It seems to me that the middleware mechanism no longer makes sense to change a lot. Yes, they are global. If you need to locally change the behavior for individual fields, it is easier to use directives. We can say that the directives are something like _local middlwares_.

**Comment by sungam3r** [comment]
Nevertheless, I am sure that the middlewares should receive DI support.

**Comment by sungam3r** [comment]
@sergeykotelnikov78 Please look at #1537 . I hope this is what you need.
