### ISSUE TITLE
Expected non-null value, resolve delegate return null for GuidGraphType

### ISSUE THREAD

**Issue by Alexcei88** [graphql-dotnet/graphql-dotnet#1024]
I have a definion like below

    `Field<GuidGraphType>("Guid",  resolve: context => context.Source.Id);

in my `ObjectGraphType` class.

The property `context.Source.Id` has Guid type.

I always has error:

> {
>   "errors": [
>     {
>       "message": "GraphQL.ExecutionError: Expected non-null value, resolve delegate return null for \"$GraphQL.Types.GuidGraphType\" ---> System.InvalidOperationException: Expected non-null value, resolve delegate return null for \"$GraphQL.Types.GuidGraphType\"\r\n   в GraphQL.GraphQLExtensions.BuildNamedType(Type type, Func`2 resolve)\r\n   в GraphQL.Types.GraphTypesLookup.HandleField(Type parentType, FieldType field, TypeCollectionContext context)\r\n   в GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context)\r\n   в GraphQL.Types.GraphTypesLookup.AddTypeIfNotRegistered(Type type, TypeCollectionContext context)\r\n   в GraphQL.Types.GraphTypesLookup.HandleField(Type parentType, FieldType field, TypeCollectionContext context)\r\n   в GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context)\r\n   в GraphQL.Types.GraphTypesLookup.Create(IEnumerable`1 types, IEnumerable`1 directives, Func`2 resolveType, IFieldNameConverter fieldNameConverter)\r\n   в System.Lazy`1.CreateValue()\r\n   в System.Lazy`1.LazyInitValue()\r\n   в GraphQL.Types.Schema.get_AllTypes()\r\n   в GraphQL.Instrumentation.FieldMiddlewareBuilder.ApplyTo(ISchema schema)\r\n   в GraphQL.DocumentExecuter.<ExecuteAsync>d__8.MoveNext()\r\n   --- Конец трассировки внутреннего стека исключений ---",
>       "extensions": {
>         "code": "INVALID_OPERATION"
>       }
>     }
>   ]
> }

Where is the my error? How Can I define a field with guid type?

I do not see a call  of AddType method for the GuidGraphType type in the  [GraphTypesLookup class](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/GraphTypesLookup.cs)

**Comment by OpenSpacesAndPlaces** [comment]
There's no built-in value converter.

Your option is to either make one and register it:
`schema.RegisterValueConverter`

Or just use it as a string. (that's what I currently do).

----

I believe the reason for missing converters is that there isn't as JSON type of guid - so while string is the logical conversion ( and what many other libraries do) - I think the goal in this project wasn't to have things auto-magically happen.

**Comment by sungam3r** [comment]
See #1074. It is no longer necessary to manually register anything for the `Guid` type.

**Comment by sungam3r** [comment]
@Alexcei88 Did you manage to solve this problem? The latest preview nuget package should solve it.

**Comment by sungam3r** [comment]
Closed as resolved. Feel free to reopen if not.
