### ISSUE TITLE
How to hide fields

### ISSUE THREAD

**Issue by dojo90** [graphql-dotnet/graphql-dotnet#1027]
I have a `field` inside of a `mutation` which should not be used by any customer. Is it possible to hide it? Or must I protect it by authentication?

**Comment by joemcbride** [comment]
There is currently no way to hide fields, so yes it would have to be authentication today.

**Comment by sungam3r** [comment]
If this field should not be used by anyone, then why is it declared? You can also use the deprecated directive.

**Comment by dojo90** [comment]
> 
> 
> If this field should not be used by anyone, then why is it declared?

I have a `field` ... which should not be used by any customer...

**Comment by sungam3r** [comment]
Ok. How and by whom then should it be used?

**Comment by dojo90** [comment]
Software developer and internal process communication between `client` and `server` application.

**Comment by sungam3r** [comment]
That is, you actually have two api - external and internal? Maybe then separate them and provide explicitly relevant api to different types of customers?

**Comment by sungam3r** [comment]
@dojo90 I think #1179 is what you need.

**Comment by sungam3r** [comment]
Closed as answered. @dojo90 Now you can use schema filter to solve this issue.
