### ISSUE TITLE
How to use it in a multi-module application,for example simplcommerce or npmcommerce

### ISSUE THREAD

**Issue by Anberm** [graphql-dotnet/graphql-dotnet#1038]
## Summary
In many application systems have achieved modularization, module can be installed and uninstalled, in GraphQL.NET Schema, Query, Mutation only allow a root, how should I realize modular GraphQL?

**Comment by Anberm** [comment]
I get multiple instances inside the root with dependency injection and reassemble them， which is not elegant

**Comment by SimonCropp** [comment]
uploading a small solution that illustrates your problem would be helpful
