### ISSUE TITLE
Filter graphql response

### ISSUE THREAD

**Issue by ArcaneTSGK** [graphql-dotnet/graphql-dotnet#1041]
## Summary
I am trying to simply filter schema on the frontend from a response provided by a custom GraphQL endpoint implementation of this repository. Specifically I want to only return data for a specific page sorted by name. 

## Relevant information
The schema returned is as follows

```
schema {
  query: ManagedContentQuery
}

type ManagedContentQuery{
  managedContent(managedContentRequest: managedContentRequest!): managedContent
}

type Content {
  layout: Layout
  page: [Page]
}

type Page {
  hero: Hero
  marketingTile: [MarketingTile]
  metaContent: MetaContent
  name: String!
  promotion: [Promotion]
  seoTile: [SeoTile]
  title: String!
}
```
The query I want to use is 
```
{
  ManagedContentQuery{
    managedContent(managedContentRequest:{brandId:1}){
      content
      {
        page(filter: {name: "Home"}){
          name
          metaContent{
            description
            title
            keywords
          }
        }
      }
    }
  }
}
```

The error I receive is

`"message": "Unknown argument \"filter\" on field \"page\"`

The resolver

```
Field<ManagedContentType>(
                "managedContent",
                arguments: new QueryArguments(new QueryArgument<NonNullGraphType<ManagedContentRequestType>> {Name = "managedContentRequest"}),
                resolve: context => contentService.GetManagedContentAsync(context.GetArgument<ManagedContentRequest>("managedContentRequest")));

```

Any help would be much appreciated, thanks.

**Comment by jeffw-wherethebitsroam** [comment]
You haven't included `ManagedContent` or `ManagedContentRequest` in your schema, which makes it harder. But I assume that the `content` field of  `ManagedContent` is of type `Content`.

Your Content type is currently

```
type Content {
  layout: Layout
  page: [Page]
}
```

If you want `page` to support a filter, it would need to be something like:

```
type Content {
  layout: Layout
  page(filter: Filter): [Page]
}
```

Jeff
