### ISSUE TITLE
Get list of Query Variables in GraphQL dot net

### ISSUE THREAD

**Issue by sangeethasunkari** [graphql-dotnet/graphql-dotnet#1043]
In my resolve I have 
var args = context.Arguments;
Quick watch in debug mode shows this for args.Values
![image](https://user-images.githubusercontent.com/42580191/53822239-f606c980-3f34-11e9-94c9-da691324146f.png)
How can I get to my fields (vendorId, description, isEnabled)?

**Comment by joemcbride** [comment]
Here's the documentation for arguments.

https://graphql-dotnet.github.io/docs/getting-started/arguments

```csharp
var id = context.GetArgument<int>("vendorId");
var desc = context.GetArgument<string>("description");
var isEnabled = context.GetArgument<bool>("isEnabled");
```

You could also use an Input type instead of individual fields.  Shown in the mutation documentation.

https://graphql-dotnet.github.io/docs/getting-started/mutations

**Comment by sangeethasunkari** [comment]
I am already using InputType and context.GetArgument in my Resolve. Here is my Resolve function
Field<VendorType, Vendor>()
                .Name("updateVendor")
                .Argument<VendorUpdateInputType>("vendor", "vendor input to update")
                .ResolveAsync(context =>
                {
                    var vendorinput = context.GetArgument<Vendor>("vendor");
                    var vendorid = vendorinput.VendorId;
                    var args = context.Arguments;
                    return vendors.UpdateVendorAsync(vendorid, vendorinput);
                }
});
Is there a way to get the the query variables via a loop dynamically... like args.Values.Items[0].Key and args.Values.Items[0].Value... something like that? But Values does not contain a definition for Items[0].

**Comment by joemcbride** [comment]
The `Arguments` property on `ResolveFieldContext` is just a C# Dictionary.  So you can use it like any other Dictionary.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/ResolveFieldContext.cs#L23
