### ISSUE TITLE
Resolving GraphQL Types to Data types for Input Objects

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [graphql-dotnet/graphql-dotnet#1045]
Hi,

For most operations in GraphQL, we are taking data objects and turning them into object graph types. If any transformation needs to happen on a field, we can use resolve to do that.

However, for Input objects we are receiving object graph types and converting them to data objects. Is there a method similar to resolve that can be used for doing transformations in this direction?

For a specific example, I encode int Id's to be opaque global string ids. This is easy via resolve when converting from data type to graph type.

For the input object, I would like to decode the id from the InputObjectGraphType into an int id in the underlying data object. I can't work out where to do this.

Code example:

```c#
public class Person
{
  public int Id { get; set; }
  public string Name { get; set; }
  public int PartnerId { get; set; }
}

public class PersonType : ObjectGraphType<Person>
{
  public PersonType()
  {
    Field<NonNullGraphType<IdGraphType>>("id", resolve: x => ToGloablID(x.Source.Id));
    Field(x => x.Name);
    Field<NonNullGraphType<IdGraphType>>("partnerId", resolve: x => ToGloablID(x.Source.PartnerId));
  }
}

public class PersonInput
{
  public string Name { get; set; }
  public int PartnerId { get; set; }
}

public class PersonInputType : InputObjectGraphType<PersonInput>
{
  public PersonInputType()
  {
    Field(x => x.Name);
    // Should be able to use FromGlobalId(string id) somewhere here
    Field<NonNullGraphType<IdGraphType>>("partnerId", ???);
  }
}
```

Jeff

**Comment by sungam3r** [comment]
Do not use resolver for inputs, this just not work. See linked issues. Call `context.GetArgument<YourDataObject>("argname")` inside field resolver to get argument. If you want custom deserialization for `YourDataObject` you may registed custom converter, for example `ValueConverter.Register<YourDataObject>(values => YourDataObject.Build(values))`
