### ISSUE TITLE
Bad exception text on wrong return type in field resolver

### ISSUE THREAD

**Issue by pavel-usachev** [graphql-dotnet/graphql-dotnet#1047]
## Description

When resolve field function returns unexpected type I got not really straightforward exception message.

### Steps to reproduce

Using following schema configuration:

```C#
public sealed class BugSchema : Schema
{
    public BugSchema()
    {
        var query = new ObjectGraphType();
        query.Field<BugType>("query", resolve: _ => new TypeB()); // Here's a misuse
        Query = query;
    }
}

public sealed class TypeA { }

public sealed class TypeB{ }

public sealed class BugType : ObjectGraphType<TypeA>
{
    public BugType()
    {
        Field<StringGraphType>("test", resolve: _ => null);
    }
}
```
Send query: `{ query { test } }`

### Expected result

I expect to see following exception message:

`Expected value of type \"GraphQL.Tests.Bugs.WrongExceptionText+TypeA\" for \"BugType\" but got: GraphQL.Tests.Bugs.WrongExceptionTextTest+TypeB.`

### Actual result

I got exception like this:

`Expected value of type \"BugType\" for \"BugType\" but got: GraphQL.Tests.Bugs.WrongExceptionTextTest+TypeB.`

**Comment by joemcbride** [comment]
To expand on this a bit, what type is "allowed" is determined by `IsTypeOf` or `ResolveType`.

https://graphql-dotnet.github.io/docs/getting-started/interfaces#istypeof
https://graphql-dotnet.github.io/docs/getting-started/interfaces#resolvetype

Either of those functions could be checking multiple Domain types.  So the intent is not to be checking a specific Domain type, but to determine which GraphType to use.  So the messaging should probably be updated to reference that vs. trying to guess at what types are valid.

**Comment by pavel-usachev** [comment]
Thank you! That's way better.
