### ISSUE TITLE
is there a sample project that showcases this library 

### ISSUE THREAD

**Issue by yon86** [graphql-dotnet/graphql-dotnet#105]

**Comment by JarnoNijboer** [comment]
This repository contains a working sample project:
* [Starwars sample project](https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.StarWars)
* [GraphQL server using the sample project](https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.GraphiQL)

The unittests we're also a great learning resource for me, when exploring this project

**Comment by yon86** [comment]
thank you
