### ISSUE TITLE
GraphQL as API gateway?

### ISSUE THREAD

**Issue by ildoc** [graphql-dotnet/graphql-dotnet#1057]
Can I use graphql-dotnet to set up a gateway for multiple web services?
If yes, is there any example available?

**Comment by SimonCropp** [comment]
> Can I use graphql-dotnet to set up a gateway for multiple web services

can u clarify what you mean by that?

**Comment by A360JMaxxgamer** [comment]
Of course you can do that. Basically it is done by schema stitching or remote schemas. I dont know whether this package supports schema stitching yet.

If it doesnt your api service could use the hotchocolate package. It supports schema stitching. But it it lacks a support for supscriptions on a stitched schema.

Or you do the stitching by yourself. ;)

**Comment by michaelstaib** [comment]
@A360JMaxxgamer we will have subscription stitching with the upcoming version.

**Comment by sungam3r** [comment]
Closed as answered.
