### ISSUE TITLE
GraphQL and .NET Core

### ISSUE THREAD

**Issue by cRUSHER-HLG** [graphql-dotnet/graphql-dotnet#1060]
Hello guys,

Do you have any plans to port this project also to .net core?

**Comment by SimonCropp** [comment]
@cRUSHER-HLG this project already supports .net core

**Comment by cRUSHER-HLG** [comment]
Okey nice, then i will help you by contributing :D.

**Comment by cRUSHER-HLG** [comment]
Something like the dataloader or caching and so on will be very nice i think. Better sayed apollo graphql not in shitty node.js :D.

**Comment by SimonCropp** [comment]
so we can close this?

**Comment by cRUSHER-HLG** [comment]
yes
