### ISSUE TITLE
Resolvers returning wrong values for scalars ignore schema validation rules

### ISSUE THREAD

**Issue by pavel-usachev** [graphql-dotnet/graphql-dotnet#1064]
## Description

Hi, I suddenly stumbled upon strange execution result for the schema below.

### Steps to reproduce

Schema definition:
```c#
public sealed class TestSchema : Schema
{
    public TestSchema ()
    {
        var query = new ObjectGraphType();
        query.Field<NonNullable<IntGraphType>>("int", resolve: _ => "someString");
        Query = query;
    }
}
```
Schema as it was expected

```
...

schema {
  query: ObjectGraphType
}

type ObjectGraphType {
  int: Int!
}

...
```

Query:

`{ int } `

### Expected result

Some exception, like "non-nullable field expects some value" or "string type resolved into `IntGraphType` field".

### Actual result

Returns:
```json
{
  "data": {
    "int": null
  }
}
```

Also, is this ok that `ParseValue` methods in `ScalarGraphType`s are not throwing anything like `FormatException`?

**Comment by sungam3r** [comment]
Indeed, `ExecutionStrategy.ValidateNodeResult` do nothing with that type mismatch.

**Comment by Shane32** [comment]
The code sample above now throws a `FormatException`, which is caught by the `UnhandledExceptionDelegate`, if any, and returned in the result like this:
```json
    {
      "errors": [
        {
          "message": "Error trying to resolve field \u0027int\u0027.",
          "locations": [
            {
              "line": 1,
              "column": 3
            }
          ],
          "path": [
            "int"
          ],
          "extensions": {
            "code": "FORMAT",
            "codes": [
              "FORMAT"
            ]
          }
        }
      ]
    }
```

**Comment by Shane32** [comment]
The code pertaining to this was worked on in #1773 but I think it had been fixed prior to that.
