### ISSUE TITLE
Any plans to migrate to C# 7.3 / 8.0 ?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1072]
I see that the language version is fixed at 7.1 in GraphQL package

```xml
<LangVersion>7.1</LangVersion>
```

Any plans to upgrade to use new language features?

**Comment by SimonCropp** [comment]
@sungam3r that only effects people who want to contribute to this project. Consumers of the nuget can use any c# version they want

**Comment by sungam3r** [comment]
I understand. I was talking exactly about contributors. For example, I wanted to use enum type constraint which is only available in version 7.3.

**Comment by sungam3r** [comment]
The tests do not pass apparently due to the fact that the interconnected changes were merged into the master branch. In failed tests you can replace 24 by 29. This is due to the appearance of new scalar types.
