### ISSUE TITLE
Why there are no [Guid,Short,UInt,ULong,UShort]GraphType in GraphTypesLookup ctor?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1073]
Do I understand correctly that all known types of scalars should be initialized there?
Alse why `GuidGraphType`, `ShortGraphType`, `UIntGraphType`, `ULongGraphType` types do not have name set in the constructor? All other scalars have their name set in the constructor.

**Comment by joemcbride** [comment]
See this PR:  
https://github.com/graphql-dotnet/graphql-dotnet/pull/917

It has some merge issues that need to be resolved.

**Comment by sungam3r** [comment]
Thanks! How can I get a package with these changes now? These errors are blocking our work now. I see on nuget.org only package with version 3.0.0-preview-1107 builded 17 days ago.

**Comment by joemcbride** [comment]
I pushed 3.0.0-preview-1141 to nuget.org.  For immediate builds you can connect to the myget.org feed.

https://www.myget.org/feed/Packages/graphql-dotnet

**Comment by WhippetsAintDogs** [comment]
@joemcbride I've tried the 3.0.0-preview-1141, but the using a field builder with an expression parameter returning a property with the `uint` type causes this error inside an `InputObjectGraphType<>`: 
```
The GraphQL type for Field: FIELD_NAME on parent type: PARENT_GRAPH_TYPE could not be derived implicitly.
``` 
If I try to specify the type to be `typeof(UIntGraphType)` in the `type` parameter of the field builder, I got this error instead with a numeric or string value (e.g. `10` or `"10"`) passed as an UInt argument: 
```
Argument ARGUMENT_NAME has invalid value {FIELD_NAME: 10 or \"10\"}.\nIn field FIELD_NAME: Expected type \"UInt\", found 10 or \"10\".
```

**Comment by sungam3r** [comment]
Can you give an example of your schema configuration?

**Comment by WhippetsAintDogs** [comment]
Yes, there it's is :)

![image](https://user-images.githubusercontent.com/9271409/55160388-99fd2280-5139-11e9-98bf-04c5dc6676d1.png)

![image](https://user-images.githubusercontent.com/9271409/55160415-ada88900-5139-11e9-822e-f75cb3cec530.png)

Code:

![image](https://user-images.githubusercontent.com/9271409/55160496-d761b000-5139-11e9-8555-4290fe6f41d3.png)

![image](https://user-images.githubusercontent.com/9271409/55160529-ec3e4380-5139-11e9-964d-7871a5baefef.png)

**Comment by WhippetsAintDogs** [comment]
It works inside ObjectGraphType<> (query), but not as input (mutation).

**Comment by WhippetsAintDogs** [comment]
Could it be because there is no `Config<UIntValue/ULongValue/UShortValue>` inside the `AstPrinter` ? (graphql-dotnet/src/GraphQL/Utilities/AstPrinter.cs)

**Comment by WhippetsAintDogs** [comment]
Changing the `ParseLiteral` method to:
```
public override object ParseLiteral(IValue value) {
    UIntValue uintValue;

    try {
        uintValue = new UIntValue(Convert.ToUInt32(value.Value));
    } catch {
        uintValue = null;
    }

    return uintValue?.Value;
}
```

fixes the problem. @joemcbride Could you update the preview-1141 with the fix please :) ?

**Comment by WhippetsAintDogs** [comment]
Moreover, with that fix, the type specification `type : typeof(UIntGraphType)` becomes optional. The expression auto-maps the `uint` property to `NonNullGraphType<UIntGraphType>`.

**Comment by sungam3r** [comment]
I'm doing fixes now. The problem is a little wider.

**Comment by WhippetsAintDogs** [comment]
Great, keep me in touch ! :)

**Comment by sungam3r** [comment]
The problem was that translation from `IntGraphType` type is needed for many other types of scalars not only `uint`. Also added `Byte` and `SByte` scalars to complete the picture.

**Comment by WhippetsAintDogs** [comment]
For referencing !1090
