### ISSUE TITLE
Populate ExecutionError.Locations for syntax errors.

### ISSUE THREAD

**Issue by chescock** [graphql-dotnet/graphql-dotnet#1078]
## Summary

Please populate `ExecutionError.Locations` for syntax errors.  

### Basic example

```csharp
var executor = new DocumentExecuter();
var executionOptions = new ExecutionOptions
{
    Schema = new Schema(),
    Query = "badQuery",
};
var result = await executor.ExecuteAsync(executionOptions);
var error = result.Errors.Single();
Debug.Assert(error.Locations != null && error.Locations.Any());
```

The parsing code seems to have the `Line` and `Column` available, because `error.Message` includes them (as `(1:1)`): 

```
Syntax Error GraphQL (1:1) Unexpected Name "badQuery"
1: badQuery
   ^
```

But they are not exposed in the `Locations`.

### Motivation

This would make it easier for client tools to report error information on syntax errors.  It also seems more consistent with other GraphQL servers.  For example, https://developer.github.com/v4/explorer/ and https://graphql.github.io/swapi-graphql/ report `line` and `column` when given a query with a syntax error.

**Comment by sungam3r** [comment]
@Shane32 Did we fix it already?

**Comment by Shane32** [comment]
Yes this has been completed
