### ISSUE TITLE
How use stored procedure or dataset in graphql

### ISSUE THREAD

**Issue by anomepani** [graphql-dotnet/graphql-dotnet#1084]
Is it possible to use stored procedure which return multiple datatable in single sp and display(resolve) result from them in graphql dotnet.

**Comment by SimonCropp** [comment]
yes

**Comment by anomepani** [comment]
Do you have or anyone have demo project how we can do it? It would be great if some demo will be there. 
Thanks

**Comment by denisedelbando** [comment]
hello @anomepani. its the same as any regular table. Your return type should be the model of your stored procedure. This answer is based on if you are using EF.

We have been using stored procedures and views with graphql. saves us resolve issues with on demand properties like created by info

**Comment by sungam3r** [comment]
Graphql does not tied to any data source technology. You can do everything you want in your resolvers to fetch data from. Feel free to post a new issue if you have any questions.
