### ISSUE TITLE
IntGraphType description doesn't take into account the fact that it could be a long

### ISSUE THREAD

**Issue by WhippetsAintDogs** [graphql-dotnet/graphql-dotnet#1089]
## Description

When reading the description of the Int type from the schema, I've noticed that even if the Int type could be a value between -(2^53 - 1) and 2^53 - 1 (because of the `long` parsing fallback), the description only says that it could be a value between -(2^31) and 2^31 - 1. 

### Expected result

The description should be updated.

**Comment by sungam3r** [comment]
Also see #1022

**Comment by sungam3r** [comment]
`IntGraphType ` have no description at all. And searching the repository for '2^31' does not produce results. Do you mean description from GraphQL Playground?
![изображение](https://user-images.githubusercontent.com/21261007/57574972-9bb14a00-744a-11e9-878a-c58ed502fb23.png)

**Comment by joemcbride** [comment]
Closing this as a duplicate of #1022
