### ISSUE TITLE
Support Connection fields of TConnection, TEdge, TNode

### ISSUE THREAD

**Issue by benmccallum** [graphql-dotnet/graphql-dotnet#1093]
## Summary, example, motivation

Currently the ConnectionBuilder assumes we only ever want to use the framework's `Connection<TNode>` and `Edge<TNode>` classes.

In reality it's common to want to have custom Edge types with additional domain-defined properties like `FriendedAt` if describing the Edge between a User and another User.

Or even a custom Connection type with some aggregation properties that summarise the entire connection or the page subset, like `avg`, `sum`, etc.

I'm happy to fork and work on this, shouldn't be too hard, just creating the issue now in anticipation of any feedback.

**Comment by Shane32** [comment]
As of the time of writing, `ConnectionType`, `EdgeType`, and `PageInfoType` are not tied to `Connection<TNode>` or `Edge<Node>` and may be used with any class that has the necessary properties.  I am hoping to change this for v8, so it is tied to those classes (or perhaps interfaces), for faster execution and AoT compilation support.  Nevertheless, those graph types contain almost no code and it is easy to rewrite them as-needed in your own codebase.  You can even use `AutoRegisteringObjectGraphType<T>` to build graph types from connection types.  It does not seem to be necessary to add additional support into the GraphQL.NET base library to allow for extending these types.

Note that it is true you cannot use the existing connection builders; you will need to add the connection field manually.

As this topic is 4 years old, I'm closing this issue now.  Please respond if you have additional comments.
