### ISSUE TITLE
Generate Schema dynamically with duplicate ObjectGraphType names.

### ISSUE THREAD

**Issue by TheRubble** [graphql-dotnet/graphql-dotnet#1095]
I'm generating a schema from a third party JSON schema and I've run into a slight issue. If the types have the same name e.g:

```
schemaRoot.AddField(new FieldType()
{
    ResolvedType = owner,
    Name = "owner", /* this actually is dynamic I've put a sample here */
    Resolver = new AsyncFieldResolver<IDictionary<string, object>>(context =>
    {
        var values = new Dictionary<string, object>
        {
            { "name", capturedRoot.Owner.Name },
            { "email", capturedRoot.Owner.Email }
        };
        return Task.FromResult<IDictionary<string, object>>(values);
     })
});
```

If the above is registered more than once only the first object to be registered will resolve when requesting the data. I've verified this by uniquely generating the name.

I thought about creating a map, but unfortunately this isn't always going to work due the types potentially have a different set of attributes but the same name. Think bounded contexts here (DDD).

I can't change the schema as it's provided via a third party. 

I'm not super keen on changing the naming to be unique across the board as it makes the whole query process feel very alien.

Looking for ideas.....

**Comment by sungam3r** [comment]
Do you mean that two fields in a type have the same name or two types in a schema? In any case, the GraphQL specification does not allow either the first or the second.

**Comment by sungam3r** [comment]
Relates to #1284

**Comment by sungam3r** [comment]
Relates to #1156

**Comment by sungam3r** [comment]
@TheRubble Can you check if the problem persists?
