### ISSUE TITLE
GraphQL.Net in Asp.Net Web API 2  vs .Net core Web API

### ISSUE THREAD

**Issue by IT-Mohsin** [graphql-dotnet/graphql-dotnet#1096]
I tried GraphQL.Net in Asp.Net web API 2 and I tried same thing in .Net core web API.
In .Net Web API i don't need to register (in container to inject) Types ( for example PersonType : ObjectGraphType<Person>)
But when using same code in .Net core I had to register those types otherwise during startup application throw exception.
Not only Type need to be registered few more dependencies need to be registered when using .Net core.
Please see below screen shot with red marker. This is what .Net core is demanding extra not sure why? Thanks
<img width="1160" alt="GraphQL Net" src="https://user-images.githubusercontent.com/28638708/55269150-5cde8080-525e-11e9-8699-259fc4571cee.PNG">
 
Can you please help t to understand why both behaving differently.

**Comment by sungam3r** [comment]
I see that you use two different Ioc-containers - Ninject and its Kernel object vs Microsoft and its IServiceCollection object. Generally speaking, they are completely different in their behavior containers. Ninject DI does a little more than Microsoft.DependencyInjection (MS DI). MS DI requires explicit mapping types in the container. Ninject, as I recall, does not require type registration, if this type has a default constructor and can be created. Some time ago we migrated our .NET Framework projects from Niject DI to .NET Core and MS DI and just faced with such behavior.

In addition, pay attention to the correct setting of the lifetime (scope) of your objects.

**Comment by IT-Mohsin** [comment]
Thanks sungam3r!

**Comment by sungam3r** [comment]
Closed as answered.
