### ISSUE TITLE
Passing complex types in as variables

### ISSUE THREAD

**Issue by scott-mac** [graphql-dotnet/graphql-dotnet#1098]
I can't get this working for some reason. I tested it first with a single Int! variable defined and it worked just as expected. But then I tried adding a complex type to the mix so my query looks like:

```
{
  "query": query fooQuery($id:Int!,$foo:FooInput!) {
	fooQuery (id:$id,foo:$foo){
		fooId
		fooName
   }
},
  "variables": {
	"id":"2",
	"foo":{"prop1":"val1","prop2":"val2"}
  }              
}


```
FooInput is declared simply as:

```
public FooInput() {
    Name = "FooInput";
    Field<StringGraphType>("Prop1");
    Field<StringGraphType>("Prop2");
}
```

And the query declared as:

 ```
Field<FooType>(
"fooQuery",
arguments: new QueryArguments(new QueryArgument<IntGraphType> { Name = "id" }, 
new QueryArgument<NonNullGraphType<FooInput>> { Name = "foo" }),
resolve: context => {
    return repo.Get(context.GetArgument<int>("id"), context.GetArgument<Foo>("foo"));
});

```

It fails with "Expected non-null value, resolve delegate return null for FooInput"

It looks like the call to ToInputs() call is to blame but I'm not sure why, what am I doing wrong here?

**Comment by joemcbride** [comment]
Yes you will need to use `ToInputs` to pass the variables to the execution engine.  Does `FooInput` inherit from `InputGraphType`?

**Comment by scott-mac** [comment]
Yes FooInput inherits from InputGraphType so that wasn't it. But your question did lead me to the problem. 

Since all my types are in the same namepace, in my Startup, I register them all in a  loop using reflection on that namespace. But this FooInput class I had added to a different namespace just for quick testing so it was never getting injected properly.

Thanks for the quick reply and helping me get pointed in the correct direction.
