### ISSUE TITLE
Do I have to create types for each of my hundreds of models?

### ISSUE THREAD

**Issue by kernel-coder** [graphql-dotnet/graphql-dotnet#1099]

**Comment by kernel-coder** [comment]
Hello, Say I have a few hundreds of data models (yeah, that's right), do I have to create Graph QL types inheriting from ObjectGraphType? Is there any other way, e.g. marking all my data models through attributes to generate types for them or something like that?

**Comment by joemcbride** [comment]
Yes you can generate them.

Here's a link to a few projects that do that:  https://graphql-dotnet.github.io/docs/guides/schema-generation

If you have hundreds of data models, you may want to just build that generation yourself so you can customize it to your needs.

Building a dynamic schema in code is relatively simple:

https://github.com/graphql-dotnet/graphql-dotnet/blob/e877973fb4bc324e9d45c2e693a9cf3a082d82cc/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L55-L80

Here's the source for the `SchemaBuilder` that uses the GraphQL schema language and wire up resolvers to the fields:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaBuilder.cs

```gql
type Droid {
  id: String!
  name: String!
}

type Query {
  hero: Droid
}
```

**Comment by kernel-coder** [comment]
Thanks a lot @joemcbride  for your quick reply and help! I'll check them this weekend.  Probably I'll be knocking you just to give you my update or with more questions ;) 

Thanks again for the quick help!

**Comment by sungam3r** [comment]
If hundreds of your models need to have special logic for getting data (resolvers), then in any case you will have to describe it anyway. Otherwise, if it is a direct mapping from .NET classes to GraphQL entities then you can use `AutoRegisteringObjectGraphType<T>` which will do most of the work for you. You can not even create its subclasses. I think your case is a great case to test its capabilities. Perhaps we will see what functionality it lacks.

**Comment by Diaskhan** [comment]
There posible few approaches!

If we using ef core we could generate it from class structure ! 
Imodel from dbcontext!

Or generate from relations of dataprovider !

Or some metadata repository! 

In my vision is best to use dbcontext.imodel as source of true !

**Comment by Diaskhan** [comment]
Finded Here
https://hackernoon.com/how-to-implement-generic-queries-by-combining-entityframework-core-and-graphql-net-77ac8faf4a22

**Comment by igorvuleta** [comment]
> Finded Here
> 
> How to implement Generic Queries by combining EntityFramework Core and GraphQL.NET?
> 
> https://hackernoon.com/how-to-implement-generic-queries-by-combining-entityframework-core-and-graphql-net-77ac8faf4a22

This approach is bad when using it with multiple models, I have done this with a very big database the ammounts of memory consumption are insane, and I couldn't still find where the leaks are happening. There must be a more clean approach to this.

**Comment by sungam3r** [comment]
@igorvuleta Does your schema exist in singleton scope or created on each request?

**Comment by igorvuleta** [comment]
> @igorvuleta Does your schema exist in singleton scope or created on each request?

it exists in singleton scope, should I perhaps make the schema Transient?

**Comment by igorvuleta** [comment]
> > @igorvuleta Does your schema exist in singleton scope or created on each request?
> 
> it exists in singleton scope, should I perhaps make the schema Transient?

Perhaps it's solved, the graphql playground was fault that I had almost 1,5 GB more of memory consumption because of polling and schema refreshing which as I see aren't that useful when doing code first approach.

**Comment by sungam3r** [comment]
So you are talking about client memory consumption, not server, do you?

**Comment by sungam3r** [comment]
Closed as resolved.
