### ISSUE TITLE
Unions

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#11]

**Comment by moserware** [comment]
Further details can be found in the [GraphQL spec](https://facebook.github.io/graphql/#sec-Type-Definitions.Union) and [graphql-js implementation](https://github.com/graphql/graphql-js/blob/f9a287754898faf850101045f7d63000ea1b2159/src/type/definition.js#L612)

**Comment by mwilliamson-firefly** [comment]
We're looking at using GraphQL, and having support for unions would be quite handy. Do you have any idea much work adding support for unions might involve, or whether anybody has already started that work?

**Comment by joemcbride** [comment]
@mwilliamson-firefly As far as I'm aware, no work has be started on this.  There are a few things that could potentially cause issues, though I think its a few days of work.

**Comment by AdamLynamFirefly** [comment]
Thanks @joemcbride, it looks pretty likely we will end up needing to implement Unions to properly represent the data we intend to expose via our GraphQL endpoint; as @mwilliamson-firefly mentioned.

Any direction on where to begin would be extremely valuable. As would a heads up about any "gotchas" you anticipate we might encounter along the way.

**Comment by joemcbride** [comment]
@AdamLynamFirefly I pushed up a start to union support, https://github.com/graphql-dotnet/graphql-dotnet/pull/51.  The route I have been taking is copying over the test cases from the JS project and then altering the document executor until the tests pass.  If you pull down that branch and run the tests it should give you a better idea on what needs to be accomplished.  Looks to be a bug or two in fragment support.  Will also need to be a few changes to `__Type`'s `possibleTypes` to support Unions.  That's all I'm seeing so far ...

**Comment by joemcbride** [comment]
I was able to fix up the last of the Union support.  I'll pull this in tomorrow and push out a refreshed nuget.

**Comment by AdamLynamFirefly** [comment]
Hi @joemcbride, oh wow, ok. That is awesome.

graphql-dotnet is really great work, we appreciate your effort.

**Comment by joemcbride** [comment]
Merged to master and pushed to nuget.  https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.5.0
