### ISSUE TITLE
System.Uri to UriGraphType auto hookup

### ISSUE THREAD

**Issue by benmccallum** [graphql-dotnet/graphql-dotnet#1106]
## Summary

`System.Uri` source type should auto-map to a UriGraphType graph type.

It should also not need manual registering in DI container.

### Basic example

`Field(FieldNames.WebsiteUrl, o => o.WebsiteUrl, nullable: true);` where o.WebsiteUrl is of type `System.Uri`. 

### Motivation

Reduce boilerplate so we don't have to do:
`Field(FieldNames.WebsiteUrl, o => o.WebsiteUrl, nullable: true, type: typeof(UriGraphType));`

In fact, even putting in above I'm still getting an exception that the type isn't registered...
```
"GraphQL.ExecutionError: No service for type 'GraphQL.Types.UriGraphType' has been registered. ---> System.InvalidOperationException: No service for type 'GraphQL.Types.UriGraphType' has been registered.
```

I'm using the server project, which has a helper to register graph types (albeit only in the calling assembly it appears, so is Uri missing from the default resolution in this repo?

Note: Maybe this is already done just not for the nullable case like I have... or in master but not in a public release.

**Comment by benmccallum** [comment]
I can PR this when I get a sec to find where the mapping is. I *think* it would be backwards compat, right?

**Comment by sungam3r** [comment]
> Maybe this is already done just not for the nullable case like I have... or in master but not in a public release.

Yes, it is in [master](https://github.com/graphql-dotnet/graphql-dotnet/blob/cfc764b5adf95e36ef0048146a032285f7c0e53f/src/GraphQL/Types/GraphTypesLookup.cs#L29). You can try [last preview](https://www.nuget.org/packages/GraphQL/3.0.0-preview-1141).

**Comment by sungam3r** [comment]
@benmccallum Is this issue still actual?

**Comment by benmccallum** [comment]
If it's in master, I guess not. Doesn't help those of us stuck on V2 tho...

**Comment by sungam3r** [comment]
In fact, you can quite successfully work on the preview version. We use it in production for quite some time.

**Comment by benmccallum** [comment]
Are there any docs on the upgrade process? I don't mind doing it, but don't want any gotchas.

**Comment by sungam3r** [comment]
No, but no public api changes that would require serious work. There are some changes in UserContext, options - nothing serious, just single line edits. I am ready to help if difficulties arise. By the way, you need to update both projects - graphql-dotnet itself and server. I am sure that it is also used by you.

**Comment by benmccallum** [comment]
Alright well let's close this then as it's in master and I'd much prefer we focus on the master branch and cutting a v3 release at some stage.

I'll talk to my team about updating to the preview version and if I do it I'll write up some upgrade notes on the changes I needed to make that can be put in the docs.

**Comment by sungam3r** [comment]
Ok
