### ISSUE TITLE
How to map nested complex types in my 'Input' type class?

### ISSUE THREAD

**Issue by scott-mac** [graphql-dotnet/graphql-dotnet#1110]
I have a json feed I'm consuming that comes in like this:

```
{
  "dimensions": [
      ["12","12","12","35"],
      ["15","10","14","45"],
   ],
   "specifications": [
         ["1800","2400"],
         ["2000","2800"]
   ],
   "price": 99.99
}

```
Since the internal arrays are anonymous, I created subclasses of List< string > so I could index off them and give them meaningful property names, like this:

    public class ProductData {
        public List<Dimension> Dimensions { get; set; }
        public List<Specification> Specifications { get; set; }
        public double Price { get; set; }
    }

    public class Dimension : List<string> {
        public string Length { get { return this[0]; } set { this[0] = value; } }
        public string Width { get { return this[1]; } set { this[1] = value; } }
        public string Height { get { return this[2]; } set { this[2] = value; } }
        public string Weight { get { return this[3]; } set { this[3] = value; } }
    }

    public class Specification : List<string> {
        public string MaxCapacity { get { return this[0]; } set { this[0] = value; } }
        public string MaxOutput { get { return this[1]; } set { this[1] = value; } }
    }

But I can't figure out how to describe this in my 'input type' class, so far all the variations I've tried failed to parse the object our correctly. I tested this with JSON .NET and it deserializes correctly so it's got to be my graph type definitions that are incorrect. What am I doing wrong? I tried

    Field<ListGraphType<StringGraphType>>
    Field<ListGraphType<ObjectGraphType>>
    Field<ListGraphType<ListGraphType<StringGraphType>>>

and any other permutation I could think of but I'm not able to get it to work. Is this even possible?

**Comment by sungam3r** [comment]
See [this issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/1013) and [this PR](https://github.com/graphql-dotnet/graphql-dotnet/pull/1104).

Now you can use it like this:
```c#
public class ProductData {
    public string[][] Dimensions { get; set; }
    public string[][] Specifications { get; set; }
    public double Price { get; set; }
}
```

Arrays of arrays should work for both output types and inputs.

**Comment by scott-mac** [comment]
OK I updated to the latest pre-release (3.0.0-preview 1141) and changed my properties to be string [ ] [ ] but it's still not mapping to a ProductData object, I just get the default System.Collections.Generic types that it gives you when it can't deserialize properly. 

My input definition is using

Field<ListGraphType<ListGraphType<StringGraphType>>>

Is that what it should be? Thanks for your help guys

**Comment by joemcbride** [comment]
Can you provide a failing test that demonstrates the issue?

**Comment by sungam3r** [comment]
Yes, a failing test will be the best source data for detecting errors.

**Comment by scott-mac** [comment]
@joemcbride Joe, I'm not sure there is much else I could include that might be helpful. This is part of a larger client project so unfortunately I can't just share the solution here. But I can share the basic classes I'm using since they're just stubbed out for dev testing at this point, hopefully that will help. I think that other than these specific array properties I'm using, everything else I'm doing is pretty much textbook, this is the last piece of the puzzle I need to get working. Thank you

[testobjects.zip](https://github.com/graphql-dotnet/graphql-dotnet/files/3080581/testobjects.zip)

**Comment by sungam3r** [comment]
I have prepared an example to demonstrate your schema. The test is successful.

**Comment by scott-mac** [comment]
I see the issue now!

The first part of the query where the argument is specified is:

new QueryArgument<NonNullGraphType<**ProductDataInput**>> { Name = "obj" }),

but in the resolve: context section just below that it is:

var arg = context.GetArgument<**ProductData**>("obj");

I had the same type (ProductDataInput) for both and since it didn't throw any exception I didn't even notice the error I was making. 

When I changed the context.GetArgument to request type ProductData it correctly deserializes everything. In fact I don't even have to declare those fields as string[ ][ ], I can declare them as I had them defined in my initial question and it works fine

```
public class Dimension : List<string> {
    public string Length { get { return this[0]; } set { this[0] = value; } }
    public string Width { get { return this[1]; } set { this[1] = value; } }
    public string Height { get { return this[2]; } set { this[2] = value; } }
    public string Weight { get { return this[3]; } set { this[3] = value; } }
}

```

Sorry for this, but hopefully it will help someone else who makes a similar error

thank you very much Ivan

**Comment by sungam3r** [comment]
> In fact I don't even have to declare those fields as string[ ][ ]

Yes, many classes that inherit `IEnumerable<T>` are actually supported, not only arrays.

I am glad to help.
