### ISSUE TITLE
Dynamically registering fields in Query?

### ISSUE THREAD

**Issue by scott-mac** [graphql-dotnet/graphql-dotnet#1114]
I have some shared logic that I want to implement for ALL my GraphQL types. But as I have it written now I need to manually add each of these definitions like this:

 ```
Field<ListGraphType<ProductType>>(
	"products_dynamic",
	arguments: new QueryArguments(new QueryArgument<NonNullGraphType<DynamicInput>> { Name = "input" }),
	resolve: context => {
	    DynamicInput dyn = context.GetArgument<DynamicInput>("input");
	    return contextServiceLocator.Repository.Get(dyn);
	});
```

so I wind up defining:

products_dynamic with type ListGraphType < ProductType >
orders_dynamic with type ListGraphType < OrderType >
suppliers_dynamic with type ListGraphType < SupplierType >
etc etc.

Is there any mechanism to define a single query method that can handle any of these dynamically? in otherwords something like this idea:

 ```
Field<ListGraphType<T>>(
	"alltypes_dynamic",
	arguments: new QueryArguments(new QueryArgument<NonNullGraphType<DynamicInput>> { Name = "input" }),
	resolve: context => {
	    DynamicInput dyn = context.GetArgument<DynamicInput>("input");
	    return contextServiceLocator.Repository.Get(dyn);
	});
```

thank you

**Comment by joemcbride** [comment]
Have you looked at using a Union type?

https://graphql.org/learn/schema/#union-types
https://graphql-dotnet.github.io/docs/getting-started/unions

You could return a Union'd type from `alltypes_dynamic`.

You would need to implement [ResolveType](https://graphql-dotnet.github.io/docs/getting-started/interfaces#resolvetype) to return the required specific GraphType based on your dynamic type.

**Comment by scott-mac** [comment]
@joemcbride OK, reading up on those that seems promising. As I understand it, if you have similar objects that have many of the same fields you go the interface path, if they are disparate objects with different fields then a union is more suitable. 

I got my union defined like this:

```
 public class MyUnion : UnionGraphType
    {
        public MyUnion() {
            Type<ProductType >();
            Type<OrderType>();
            Type<SupplierType>();
        }
    }
```

But what does my ResolveType implementation look like here? Does that get defined in my Union class itself or can I do that in my field declaration? Because I think what would work well for me would be if that DynamicInput parameter I'm passing in contained the means to determine the type...something like this might work?

```
Field<ListGraphType<MyUnion>>(
   "alltypes_dynamic",
   arguments: new QueryArguments(new QueryArgument<NonNullGraphType<DynamicInput>> { Name = "input" }),
   resolve: context => {
       DynamicInput dyn = context.GetArgument<DynamicInput>("input");

       var myType= dyn.MyType; //??? then use this to correctly resolve 
       //whether it is Product, order or Supplier and tell the repository what query to fetch data?

       return contextServiceLocator.Repository.Get(dyn);
   });
```

thanks Joe

**Comment by joemcbride** [comment]
`ResolveType` will get the resulting object returned from the field resolver.  So in this case, it will get whatever object is returned from `contextServiceLocator.Repository.Get(dyn)`.  You can then look at that object to determine what GraphType to use.  If those were concrete classes, it could look something like this:

```csharp
public class MyUnion : UnionGraphType
{
    public MyUnion(
        ProductType productType,
        OrderType orderType,
        SupplierType supplierType)
    {
        Name = "MyUnion";

        Type<ProductType >();
        Type<OrderType>();
        Type<SupplierType>();

        ResolveType = obj =>
        {
            if (obj is Product)
            {
                return productType;
            }

            if (obj is Order)
            {
                return orderType;
            }

            if (obj is Supplier)
            {
                return supplierType;
            }

            throw new ArgumentOutOfRangeException($"Could not resolve graph type for {obj.GetType().Name} in {this.Name}");
        };
    }
}
```

**Comment by scott-mac** [comment]
OK I tried that but I'm still missing something. 

My call to contextServiceLocator.Repository.Get(dyn) returns an IEnumerable (i.e. IEnumerable < Product >, IEnumerable< Order > etc).

So I thought it would be declared like

`Field<ListGraphType<MyUnion>>(`

But when I run that I get:

Cannot query field "productID" on type "MyUnion". Did you mean to use an inline fragment on "ProductType"
Cannot query field "productName" on type "MyUnion". Did you mean to use an inline fragment on "ProductType"

What am I missing?

**Comment by joemcbride** [comment]
See the graphql docs on Unions:  https://graphql.org/learn/schema/#union-types

You need to use a fragment in your query.

```gql
{
  search(text: "an") {
    __typename
    ... on Human {
      name
      height
    }
    ... on Droid {
      name
      primaryFunction
    }
    ... on Starship {
      name
      length
    }
  }
}
```

**Comment by scott-mac** [comment]
So I have to modify the query from the client too? I'm trying to avoid making the calls any more complicated than they have to be because of the learning curve for our team so I don't this is going to be a good solution for us. Thanks for your help though.
