### ISSUE TITLE
System.InvalidOperationException: Synchronous operations are disallowed.

### ISSUE THREAD

**Issue by corstian** [graphql-dotnet/graphql-dotnet#1116]
## Description

System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
   at System.IO.StreamReader.ReadSpan(Span`1 buffer)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.Deserialize[T](Stream s)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context, ICorsPolicyProvider corsPolicyProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

Upgrade to .NET Core 3.0 preview 3 or newer.

### Expected result

Synchronous IO will be made asynchronous.

### Actual result

Synchronous IO is still synchronous.

### Workaround

Put this in the `ConfigureServices` section of Startup.cs.

```csharp
// kestrel
services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});

// IIS
 services.Configure<IISServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
```

### Environment

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2
```

**Comment by RehanSaeed** [comment]
If you want to use JSON.NET then I believe you need to have `AllowSynchronousIO` set to `true`. One of the things the new JSON API's in .NET Core 3.0 solves is to add asyncronous JSON IO. The long term solution is to switch to the new JSON API's.

**Comment by ronMilne** [comment]
I have the same problem with .Net Core 3 Preview 5 (hosted in Kestral), even if I apply the above I still get the error.

**Comment by joemcbride** [comment]
Related to #1148

**Comment by elken** [comment]
Even with `
            services.Configure<KestrelServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });` this still occurs.

**Comment by Eilon** [comment]
Just ran into this as well in .NET Core 3.0 Preview 7.

BTW the workaround above is Kestrel-specific. If you're running on IIS, this is the workaround:

```c#
            services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });
```

**Comment by joemcbride** [comment]
@Eilon Thanks for the assist!

**Comment by Eilon** [comment]
The real MVP is @Tratcher who I went to when I had the problem. He *actually* knows this stuff (and wrote much of it!) and found the error 😄

**Comment by sungam3r** [comment]
Closed in favor of #1326

**Comment by Jonatthu** [comment]
@joemcbride Is this resolved if we use 3.0 preview?

**Comment by sungam3r** [comment]
@Jonatthu There is nothing to do with it in this project. You can configure aforementioned settings for IIS or Kestrel.

**Comment by Tratcher** [comment]
The IIS and Kestrel settings should be avoided if possible. Data should be asynchronously buffered before parsing.

**Comment by sungam3r** [comment]
Well, we need to choose a lesser evil. When/if Newtonsoft.Json package provides a method for asynchronous deserialization then we can use it. Although honestly I believe that this will never happen. Probably Newtonsoft.Json will just be replaced in future by a serializer from System.Text.Json.

**Comment by Tratcher** [comment]
That doesn't preclude async buffering before passing the stream to Newtonsoft.Json. That's what MVC did.

**Comment by Jonatthu** [comment]
I think this project will need to solve it and replace the package if is necessary since this project has dependencies that are going against the framework rules. I set up the configs for Krestel and IIS as a workaround but it should be fix on this project without doing it on a future release.

**Comment by sungam3r** [comment]
> That doesn't preclude async buffering before passing the stream to Newtonsoft.Json. That's what MVC did.

Yes. But too much fuss.

@Jonatthu You can open a new issue about migration to System.Text.Json so it will be more focused on **new features** and not on aforementioned errors.

**Comment by sungam3r** [comment]
> that are going against the framework rules

By the way, what framework rules? ASP.NET Core rules? These rules are not an absolute truth, they relate to a specific runtime environment and they cannot be tried to forcefully apply to absolutely everything. Although I understand the essence of your thought.

**Comment by Jonatthu** [comment]
@sungam3r My answer was based on this issue:
https://github.com/aspnet/AspNetCore/issues/7644
🤓

**Comment by sungam3r** [comment]
I guessed about it.

**Comment by breynolds** [comment]
I wanted to add another reason for why it's not as simple as as using the new JSON framework from Microsoft. I have GraphQL and other regular REST web APIs on the same server. The new JSON framework from Microsoft doesn't yet handle circular dependencies, so I still need to use JSON.Net.

**Comment by sungam3r** [comment]
Where do you have circular dependencies? GraphQL queries?

**Comment by breynolds** [comment]
Not in the GraphQL queries, in the controllers that handle the REST API requests. We have some entities that have circular references when we expand the tree of child entities. 

We had to add these lines to ConfigureServices inside of Startup.cs:

```
services.AddMvc()
      .AddNewtonsoftJson(options =>
      {
        options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
        options.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.Objects;
      });
```

I assume that's why we were receiving the same error that @corstian was getting. Is it possible to use the Microsoft JSON libraries for the GraphQL endpoints and use the Newtonsoft JSON.Net libraries for our REST web API endpoints?

**Comment by sungam3r** [comment]
It is possible since we add our serialization abstraction.

**Comment by breynolds** [comment]
Is there any documentation on how to use separate JSON parsers for GraphQL and regular REST controllers? It's working as is right now, but I'd like to try making the change to use the Microsoft parser for GraphQL to see how that works.

**Comment by sungam3r** [comment]
I have to correct my comment. It **will be** possible as soon as we add our serialization abstraction. There is no documentation on thuis topic.

**Comment by breynolds** [comment]
OK, I'll try that out when it's available. Thanks @sungam3r

**Comment by benmccallum** [comment]
I've been able to solve this issue in the graphql-dotnet server project, proven by tests, as the exception is actually on reading the request body synchronously in the middleware. PR is [here](https://github.com/graphql-dotnet/server/pull/299). Once merged, you won't need to AllowSynchronousIO anymore.

As far as I know, the PRs active on the core project here will just improve performance.
