### ISSUE TITLE
DataLoader context is null

### ISSUE THREAD

**Issue by scott-mac** [graphql-dotnet/graphql-dotnet#1126]
I tried to resurrect an [old issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/866) discussing this but got no response, so I'm creating a formal bug report.

The DataLoader functionality is some of the most critical for building a fully scalable application. But the [current documentation ](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/src/dataloader.md) is incomplete and/or incorrect. 

I tried every suggestion I could track down on how to get this working but the context is always null. What would be most helpful would be a simple standalone working sample project with all the correct config (Startup.cs, the schema, query, listerners etc)

I've tried this with both the latest stable (2.4.0) and the latest 3.0 preview release. I'm on .NET Core 2.1 but it seems this is also still an issue in 2.2. Thanks

**Comment by ZakMiller** [comment]
I'm facing the same issue.

The only piece I haven't completed from the linked docs is this bit:
```
var result = executer.ExecuteAsync(opts => {

	...

	opts.Listeners.Add(listener);
});
```

But I don't really get that as it seems like it would only affect one use of the executor and I modeleted my implementation from other sample code I've seen and injected the executer like this:
```
services.addSingleton<iDocumentExecuter, DocumentExecuter>();
```

**Comment by johnrutherford** [comment]
@scott-mac Sorry for the late response. I finally opened a PR to improve the documentation: #1137. See if that helps.

The easiest way to get everything set up correctly is to use [graphql-dotnet/server](https://github.com/graphql-dotnet/server). It handles registering the dependencies and adding the `DataLoaderDocumentListener` to the executer.

@ZakMiller The `DataLoaderDocumentListener` needs to be added to the `Listeners` on the `DocumentExecuter` for each execution. This is essential. As I said above, the [graphql-dotnet/server](https://github.com/graphql-dotnet/server) handles all of this for you.

**Comment by nandel** [comment]
I'm having a similar issue.

My case i made a service class to make easy calling using dataloader like that: 

```
public class EntityLoader<T> : IEntityLoader<T>
        where T: Entity
    {
        protected readonly IRepository<T> _repository;
        protected readonly IDataLoaderContextAccessor _dataLoader;

        protected static string GetKey(string sufix)
        {
            return $"{typeof(T).Name}.{sufix}";
        }

        public EntityLoader(IRepository<T> repository, IDataLoaderContextAccessor dataLoader)
        {
            _repository = repository;
            _dataLoader = dataLoader;
        }

        public Task<T> LoadByIdAsync(long id)
        {
            var loader = _dataLoader.Context.GetOrAddBatchLoader<long, T>(
                GetKey(nameof(LoadByIdAsync)), 
                _repository.FindAsync);

            return loader.LoadAsync(id);
        }
    }
```

What i noticed is: i'm getting nulls only on child calls. 

Exemple query:
main(i: 1) { child(i:2) }

**Comment by SimonCropp** [comment]
@johnrutherford seems this one is answered? should be closed?
