### ISSUE TITLE
Default Values for inputs?

### ISSUE THREAD

**Issue by scott-mac** [graphql-dotnet/graphql-dotnet#1127]
Many of my input types share the same fields (Created and LastModifed). So I created a base class for my input types to inherit from. I'm trying to set the default values on these fields as follows:

 ```
public class BaseInputType : InputObjectGraphType {
        public BaseInputType() {
            Field<DateTimeGraphType>("Created");
            Field<DateTimeGraphType>("LastModified");

            this.Fields.SingleOrDefault(f => f.Name == "Created").DefaultValue = DateTime.UtcNow;
            this.Fields.SingleOrDefault(f => f.Name == "LastModified").DefaultValue = DateTime.UtcNow;

    }
```

If the user doesn't pass in values for Created and LastModified then I'd like to have default values set but it doesn't seem to honor this. Is there something else I need to tweak? Thanks

**Comment by sungam3r** [comment]
Please show how you read such input argument from query arguments in your resolver.

**Comment by sungam3r** [comment]
@scott-mac, it seems to me that the fix relates specifically to the problem you are describing.
