### ISSUE TITLE
How to translate graphql type field names to model field names

### ISSUE THREAD

**Issue by bppn** [graphql-dotnet/graphql-dotnet#1131]
## Summary
We have developed a graphql api on top of an entity framework data layer.

We want to implement a generic solution for filtering and sorting the data.  The current idea is to pass "field name" and filters and sort orders in the arguments.

But to make graphql generic, we want to translate these arguments back to entity model names and build the sql queries using generic code.

I have been searching for a solution to easily translate the name of a graphql field to the mapped field of the entity framework model. 

Thanks!

**Comment by sungam3r** [comment]
1. Your GraphQL fields names do not match mapped entity framework fields names?

2. Every field type implements `IProvideMetadata` interface. There is a dictionary in which you can write down anything, including matching information, which you can then use. Perhaps this will help you.

**Comment by bppn** [comment]
Thanks, yes in most cases the name is the same.

I'am trying to make a generic nested filter solution.

I have a datalayer that is made of Entity Framework (relation sql db).

The biggest issue I have is how to filter nested types. The resolvers are now quite simple and only handle loading data for one type of entity.

like
query test {
   order {
    name,
    totalPrice,
    customer {
      id,
      name
    }
  }
}

I want to filter the orders by customer name, without having to load every possible join (to for example customer) in the order resolver.

**Comment by sungam3r** [comment]
That is, the question is not so much in the comparison of names, it is much broader. I think that if you ask such questions, you should contact here - https://github.com/SimonCropp/GraphQL.EntityFramework. I myself have tasks in current projects that require automatic translation of graphql requests to the EF queries, but still can’t get to that.

**Comment by sungam3r** [comment]
@bppn Is this issue still actual for you?

**Comment by bppn** [comment]
We worked around the problem in another way, no this issue is not actual any more
