### ISSUE TITLE
How to manage JWT token login/refres in mutations

### ISSUE THREAD

**Issue by PayteR** [graphql-dotnet/graphql-dotnet#1132]
Hi, is there some example for login, registration, refresh token and log out in mutations? I want to manage JWT tokens by GraphQL, not REST API. I already tried it by OpenIddict package:

https://github.com/openiddict/openiddict-core/issues/743

but it's not possible this way. Thank you.

**Comment by joemcbride** [comment]
By its nature, you won't be able to implement OpenID Connect (OIDC) in GraphQL.  You could certainly create your own JWT tokens in a GraphQL endpoint, though that wouldn't be using the OIDC protocol.  Depending on your application, using actual OIDC with an Identity Provider could be the better route to go.  Then you GraphQL api would just accept a JWT for authentication but the actual Identity of the User is handled by the Identity Provider.

**Comment by PayteR** [comment]
Yes, i want to handle tokens in GraphQL mutation, but authorization/authentication will be handled in GraphQL controller for example. 

Is it a viable solution, or should i better bet on classic JSON API way like OpenIddict provide? What's your opinion?

**Comment by joemcbride** [comment]
> Yes, i want to handle tokens in GraphQL mutations

What does this mean?  Can you add more specifics of what you're trying to do?  Are you just trying to get access to the claims within the JWT to check them within the mutation?

Right now I read your question as generic:  "Can I mutate and return data from GraphQL?" - so the answer is yes, yes you can mutate and return data from GraphQL.

OpenIddict is an OIDC server.  OIDC has a specific specification that servers have to conform to. 
 GraphQL has its own different specification.  GraphQL will never behave like an OIDC server.  They can't really be compared.

**Comment by PayteR** [comment]
I want no REST API in my application, i want all communication done by GraphQL queries/mutations. Is it a good idea or should i better stick to conventional OIDC server specification (REST API for authorization/authentication)?

**Comment by Shane32** [comment]
You ** can ** write mutations to provide equivalent functionality to an authorization API.  Realize that a GraphQL API is just another form of a REST API.  You'd have to be sure that the GraphQL endpoint is exposed with no authentication requirement inside the controller.  You'd probably also want to be sure you only allow HTTPS access to the endpoint, or throw an exception inside the mutation if the call is not made via HTTPS.

I wouldn't, but you certainly could.  For my SPA application, I wrote a REST API to handle the few login and change/reset password, basing my code on the OpenID 2.0 password grant type, and utilizing refresh tokens in a manner similar to the Quickbooks API.  Then the GraphQL API just handles the data.  But it would be a simple matter to move the authentication functions into the GraphQL API.

**Comment by sungam3r** [comment]
Closed as answered.
