### ISSUE TITLE
U*GraphType and ShortGraphType are not working with recent versions of graphql-dotnet

### ISSUE THREAD

**Issue by Patrick-Spiegel** [graphql-dotnet/graphql-dotnet#1133]
## Description

In GraphQL 2.4.0 you cannot use UIntGraphType and ShortGraphType

### Steps to reproduce

- Checkout GraphQL-Dotnet examples
- Open AspNetCore
- Update Nuget Packages
- Add Field to Droid class with type uint or short
- Add Field to DroidType referencing the added field and specify type UIntGraphType
- Start Webserver and connect with Playground

### Expected result

No errors in console and querying the droid type should not return an error

### Actual result

```
{
  "errors": [
    {
      "message": "GraphQL.ExecutionError: No service for type 'GraphQL.Types.UIntGraphType' has been registered. ---> System.InvalidOperationException: No service for type 'GraphQL.Types.UIntGraphType' has been registered.\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)\r\n   at GraphQL.Types.Schema.<CreateTypesLookup>b__56_2(Type type)\r\n   at GraphQL.Types.GraphTypesLookup.AddTypeIfNotRegistered(Type type, TypeCollectionContext context)\r\n   at GraphQL.Types.GraphTypesLookup.HandleField(Type parentType, FieldType field, TypeCollectionContext context)\r\n   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context)\r\n   at GraphQL.Types.GraphTypesLookup.HandleField(Type parentType, FieldType field, TypeCollectionContext context)\r\n   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context)\r\n   at GraphQL.Types.GraphTypesLookup.Create(IEnumerable`1 types, IEnumerable`1 directives, Func`2 resolveType, IFieldNameConverter fieldNameConverter)\r\n   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Lazy`1.CreateValue()\r\n   at GraphQL.Types.Schema.get_AllTypes()\r\n   at GraphQL.Instrumentation.FieldMiddlewareBuilder.ApplyTo(ISchema schema)\r\n   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)\r\n   --- End of inner exception stack trace ---",
      "extensions": {
        "code": "INVALID_OPERATION"
      }
    }
  ]
}
```

**Comment by sungam3r** [comment]
See #1091.
In latest 3.0.0-preview-xxx versions there is support for many new scalar types.
See [current list](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/GraphTypesLookup.cs#L16) of built-in scalars.

**Comment by sungam3r** [comment]
@Patrick-Spiegel Is this issue still actual?

**Comment by phucthaidoan** [comment]
Is there any work-around for this in GraphQL 2.4.0?

**Comment by sungam3r** [comment]
You can copy and register all those scalars manually.

**Comment by sungam3r** [comment]
@Patrick-Spiegel , @phucthaidoan Did you manage to solve this problem?

**Comment by phucthaidoan** [comment]
I am done with it.

Thanks,

**Comment by breynolds** [comment]
How did you solve this? I had just pulled in 2.4.0 and am seeing the same error with short fields in my schema.

**Comment by sungam3r** [comment]
Try 3.0.0-preview versions.

**Comment by breynolds** [comment]
OK, I briefly tried pulling in the 3.0.0-preview-1352 nuget package and my code wouldn't compile any more . Compiler said IDependencyResolver was no longer available. That's pretty fundamental in how I'm wiring everything up. Are you far enough along with 3.0 that you have docs on any breaking changes? Are there also docs on 3.0.0 that I could look at? I won't have enough time to read through all of the code to figure it out that way.

**Comment by sungam3r** [comment]
Yes, 3.0.0 has breaking changes. Current documentation https://graphql-dotnet.github.io/ targets the latest preview version. See https://graphql-dotnet.github.io/docs/getting-started/dependency-injection for DI.

**Comment by breynolds** [comment]
OK, thanks @sungam3r
