### ISSUE TITLE
How to pass a dynamic query argument to mutation

### ISSUE THREAD

**Issue by scott-mac** [graphql-dotnet/graphql-dotnet#1134]
Most of our queries & mutations follow the standard use case where we have a defined Input Type that mirrors our model. But a few of them need to pass in an additional dynamic parameter that can have any number of random fields. 

I found this thread that seemed to be asking the same thing: https://github.com/graphql-dotnet/graphql-dotnet/issues/527 

In particular, @joemcbride noted that you could extract this using JSON.NET like this:

```
var obj = JObject.FromObject(context.Arguments);
var obj = JObject.FromObject(context.Arguments["human"]);
```

But how do I define the QueryArgument in my mutation for this so that I can do this?

So for example, assume I want to pass a new argument named 'extra' like this:

`extra:{val:1,val2:22,val3:333}`

`new QueryArgument<???> { Name = "extra" } //what is this type???`

I tried ObjectGraphType but I get the dreaded "Expected non-null value, resolve delegate return null for \"$GraphQL.Types.ObjectGraphType"

**Comment by sungam3r** [comment]
It is `StringGraphType`. I understand that in the case of the transfer of a dynamic object (which means a dynamic set of properties), when it is impossible to specify its scheme in advance, then you can always do with the **string** type. The calling code serializes its object into a string and passes in the argument, the server deserializes it into a `JObject` and takes the necessary actions. In fact, the GraphQL itself is not a place for knowledge of a such dynamic things. It is the responsibility of the processing client code.

**Comment by scott-mac** [comment]
@sungam3r  Thanks for the reply. I tested this some more this morning and it just doesn't seem to be serializing that 'extra' object correctly if I specify it like this:

`extra:{val:1,val2:22,val3:333}`

If I treat the value as a raw string then yeah I can do it as you say:

`extra:"{val:1,val2:22,val3:333}"`

That is a workable solution, it's just not the behavior I expected. I thought it would deserialize to JObject by default.

**Comment by sungam3r** [comment]
> I thought it would deserialize to JObject by default.

No. GraphQL stores all input argument as `Dictionary<string, object>` in `ResolveFieldContext.Arguments`, where object value may be inner `Dictionary<string, object>`.

**Comment by sungam3r** [comment]
@scott-mac Now you can use custom deserializer with `context.GetArgument<>` API. First call `ValueConverter.Register<>`. Feel free to ask questions if this issue is still actual for you.
