### ISSUE TITLE
Define complex args (might be bug?)

### ISSUE THREAD

**Issue by MakaBuka** [graphql-dotnet/graphql-dotnet#1136]
Hi guys,

Got very wierd bug, maybe you can give me a hint or might be really bug

Anyway, I've defined complex field that calls orderBy (which gonna use to order resultset in resolver):

	public class GraphqlSort {
		public string FieldName { get; set; }
		public string Direction { get; set; }
	}

	public class GraphqlSortType : InputObjectGraphType<IEnumerable<GraphqlSort>> {

		public GraphqlSortType(SortOptions settings) {
			Name = settings.Key;
			Field<StringGraphType>("field");
			Field<StringGraphType>("direction");
		}
	}

then adding it as arg to defined field (part of code):
			var objType = new GraphqlSortType();
			var listType = new ListGraphType(objType);
			var arg = new QueryArgument(listType);
                       arg.Name = "sortBy";
TableArgs = new QueryArguments(
					arg
				);

GraphQL query, as an example:

query {

clients: customers(sortBy:{field:"id", direction: "ASC"}) {
  id
}
}

but got next an error:

"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in n:\\Projects\\GD.GraphQL\\GraphQL\\GraphQLExtensions.cs:line 196\r\n   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in n:\\Projects\\GD.GraphQL\\GraphQL\\GraphQLExtensions.cs:line 186\r\n   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in n:\\Projects\\GD.GraphQL\\GraphQL\\GraphQLExtensions.cs:line 157\r\n   at GraphQL.Validation.Rules.ArgumentsOfCorrectType.<>c__DisplayClass0_0.<Validate>b__1(Argument argAst) in n:\\Projects\\GGraphQL\\GraphQL\\Validation\\Rules\\ArgumentsOfCorrectType.cs:line 26\r\n   at GraphQL.Validation.MatchingNodeVisitor`1.GraphQL.Validation.INodeVisitor.Enter(INode node) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\MatchingNodeVisitor.cs:line 28\r\n   at GraphQL.Validation.EnterLeaveListener.GraphQL.Validation.INodeVisitor.Enter(INode node) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\EnterLeaveListener.cs:line 26\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\BasicVisitor.cs:line 30\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\BasicVisitor.cs:line 37\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\BasicVisitor.cs:line 37\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\BasicVisitor.cs:line 37\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\BasicVisitor.cs:line 37\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\BasicVisitor.cs:line 37\r\n   at GraphQL.Validation.DocumentValidator.Validate(String originalQuery, ISchema schema, Document document, IEnumerable`1 rules, Object userContext, Inputs inputs) in n:\\Projects\\GD.GraphQL\\GraphQL\\Validation\\DocumentValidator.cs:line 59\r\n   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in n:\\Projects\\GD.GraphQL\\GraphQL\\Execution\\DocumentExecuter.cs:line 147\r\n  

Debugged it and found that in GraphQL\GraphQLExtensions.cs --> IsValidLiteralValue static method we have next code (line 186):  var result = IsValidLiteralValue(field.ResolvedType, fieldAst?.Value, schema);
and in my case, somehow, field.ResolvedType == null, so, since we have recursion here, we will definately got an exception on line 196

PS I check tests that cover this method and they are ok, but bug constatly appears.

And I don't have any ideas why ResolvedType is null (maybe I defined it wrong or missed something??)

Im using latest stable version of GraphQL lib v2.4
Run it on VM (Windows 7 x32, VS 2017)

Thx, Dima

**Comment by sungam3r** [comment]
Honestly, the example is not complete, but I will try to guide you:
1. Change 
`public class GraphqlSortType : InputObjectGraphType<IEnumerable<GraphqlSort>>`
to
`public class GraphqlSortType : InputObjectGraphType<GraphqlSort> {`

2. Change
```
query {

clients: customers(sortBy:{field:"id", direction: "ASC"}) {
id
}
}
```
to
```
query {

clients: customers(sortBy:[{field:"id", direction: "ASC"}]) {
id
}
}
```

**Comment by MakaBuka** [comment]
> Honestly, the example is not complete, but I will try to guide you:

First of all, thanks for the prompt reply
public class GraphqlSortType : InputObjectGraphType<GraphqlSort> {

Done but still having same error

> the example is not complete,

well, Im defining fields dynamically, means, not base on class, but when application starting (all examples based on defining class itself)

gonna try to reproduce it via tests...

**Comment by joemcbride** [comment]
You will need to use:

`public class GraphqlSortType : InputObjectGraphType<GraphqlSort> {}`

But then you need to wrap GraphQlSortType in a ListGraphType to have a list.


```
Field<ListGraphType<CustomerGraphType>>(
      "customers",
      arguments: new QueryArguments(
        new QueryArgument<ListGraphType<GraphQlSortType>> { Name = "sortBy" }
      ),
      resolve: context =>
      {
        var sortBy = context.GetArgument<List<GraphQlSort>>("sortBy");
        ...
      }
    );
```

**Comment by sungam3r** [comment]
Exactly. Missed to write this part in the answer.

**Comment by MakaBuka** [comment]
Thx, looks like issue fixed.
