### ISSUE TITLE
Roadmap for 3.0

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/graphql-dotnet#1138]
@joemcbride Is there a roadmap for 3.0? 

I have several ideas for changes for 3.0, some of which I could do.

Also, are 3.0 changes going on the master branch?

**Comment by benmccallum** [comment]
+1
Would be good to get a project up and have some high level tasks for discussion.

**Comment by sungam3r** [comment]
+1
Since the last stable version, master branch has received many fixes and new features.

**Comment by joemcbride** [comment]
There is not much there at present, thought this is currently the 3.0 milestones:  https://github.com/graphql-dotnet/graphql-dotnet/milestone/4

There may have been a couple more merges with breaking changes or enhancements that were not tagged in the 3.0 milestone.  master branch is currently 3.0.

If you have ideas for 3.0 I think it would be fine to add those issues and tag them 3.0.  I don't have any specific timeframe for 3.0.  I have at least 1-2 items I would like to complete that would be breaking changes to go into 3.0.

**Comment by DaniilSokolyuk** [comment]
would be nice to add support dataloader multiple awaits in resolvers

**Comment by johnrutherford** [comment]
@joemcbride sounds good
@DaniilSokolyuk I'll have to look at how it's been implemented in hotchocolate. I wasn't able to come up with a solution that I was happy with, but I agree it would be nice.

**Comment by sungam3r** [comment]
duplicate #1321
