### ISSUE TITLE
Update validation rules to support Task<T>

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#1140]
Today validation rules `Validate` method do not return `Task<INodeVisitor>`.  Update this interface so that you can return a `Task` to support async validation.

```csharp
public interface IValidationRule
{
    Task<INodeVisitor> ValidateAsync(ValidationContext context);
}
```

**Comment by johnrutherford** [comment]
Should the method name be changed to "ValidateAsync"?

**Comment by sungam3r** [comment]
This topic is a subject of many disputes. I made it a rule to name all methods returning `Task` with the `Async` suffix.

**Comment by joemcbride** [comment]
I'm on board with the `Async` suffix.

**Comment by carlwoodhouse** [comment]
+1 would be awesome :)

**Comment by sungam3r** [comment]
Maybe it will be better to use `ValueTask<T>`?

**Comment by Jetski5822** [comment]
+1

**Comment by cime** [comment]
Would you like to have two separated interfaces, one for sync and one for async version?

```
public interface IValidationRule
{
    INodeVisitor Validate(ValidationContext context);
}

public interface IAsyncValidationRule
{
    Task<INodeVisitor> ValidateAsync(ValidationContext context, CancellationToken cancellationToken);
}
```

 Change the current one to always return Task? Or did you have something else in mind?

**Comment by sungam3r** [comment]
Having separate interfaces for sync and async way is a bad design choice. I am for changing existing interface.
