### ISSUE TITLE
Use IServiceProvider for dependency injection

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/graphql-dotnet#1144]
I think dependency injection in the `Schema` class should be based on `System.IServiceProvider`.

This interface is part of .NET Standard and is what Microsoft.Extensions.DependencyInjection uses. So this would make it easier for users to integrate with various IoC containers.

**Comment by sungam3r** [comment]
In fact, the presence of `FuncDependencyResolver` completely solves the problem of integration with third-party containers.

**Comment by johnrutherford** [comment]
Yes, but with `IServiceProvider` you could plug into the DI in a ASP.NET application with out having to do anything. 

It's a very similar interface to `IDependencyResolver`. The advantage is that it's already in the base class libraries and can plug into Microsoft.Extensions.DependencyInjection without having to write an adapter class or delegate at all.

**Comment by sungam3r** [comment]
Yes, it is clear that the interfaces are equivalent. Well, should not be worse.

**Comment by sungam3r** [comment]
Fixed in #1172 ?

**Comment by joemcbride** [comment]
Yep, fixed in #1172
