### ISSUE TITLE
Error trying to start GraphiQL web project

### ISSUE THREAD

**Issue by CCarminati** [graphql-dotnet/graphql-dotnet#115]
Hi Joe, thanks for this great project, 
I'm trying to run the web project and it's throwing an exception related to dependency injection with System.Web.Http.Metadata.ModelMetadataProvider assembly. 
Some reference can be missing?

Thanks in advance

**Comment by joemcbride** [comment]
I haven't seen this before and it is working for me locally (F5 through Visual Studio).  Can you provide a bit more info?

* The full stacktrace
* Did you restore the nuget packages?
* How did you run the web project?

**Comment by CCarminati** [comment]
Hi Joe, thanks for your quick response.
It was my mistake because I was confused about instruction under GraphiQL to emit 
> npm install
> webpack --progress
doing it in GraphiQL folder, not in the root of the project as you say. :(
Sorry about this.

Regards

**Comment by joemcbride** [comment]
Ah, no worries.  I'll perhaps change that wording to be "at the root of the repo".
