### ISSUE TITLE
Add support for execution services

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/graphql-dotnet#1151]
I originally posted this suggestion on issue #648. I think this would be a good addition to v3.0. It's not necessary, but I think it would be good to implement #1144 first.

> Allow for a dependency resolver instance to be passed in through the `ExecutionOptions`. This would allow you to wrap `HttpContext.RequestServices` in ASP.NET Core and pass that in. If you're not using ASP.NET Core, this would still allow you to create a custom scope for execution and pass that in. If this is not set at all, it should probably default to the dependency resolver on the schema.
> 
> Expose this as an `ExecutionServices` property on the `ResolveFieldContext` class.
> Then implement some field resolvers with 1-3 additional type parameters that handle the dependency resolution. Like this:
> 
> ``` csharp
> public class FuncFieldResolver<TServiceType, TReturnType> : IFieldResolver<TReturnType>
> {
>     private readonly Func<ResolveFieldContext, TServiceType, TReturnType> _resolver;
> 
>     public FuncFieldResolver(Func<ResolveFieldContext, TServiceType, TReturnType> resolver)
>     {
>         _resolver = resolver;
>     }
> 
>     public TReturnType Resolve(ResolveFieldContext context)
>     {
>         var service1 = context.ExecutionServices.Resolve<TServiceType>();
>         return _resolver(context, service1);
>     }
> 
>     object IFieldResolver.Resolve(ResolveFieldContext context) => Resolve(context);
> }
> ```
> 
> And then set up extension methods so fields could be created like this:
> 
> ``` csharp
> Field<FooType, Foo>()
>     .Name("foo")
>     .ResolveAsync<IMyService>((context, myService) =>
>     {
>         return myService.GetFooAsync();
>     });
> ```
> 
> So this would be equivalent to injecting parameters into a controller action in MVC.

**Comment by sungam3r** [comment]
It is ServiceLocator antipattern.
> Then implement some field resolvers with 1-3 additional type parameters that handle the dependency resolution.

This is a leaky abstraction, the DI container should deal with dependency resolution when introducing them into the class constructor (of query type). Also what if resolver use 4, 5, 10 dependencies? There will be too much noise in public API of resolvers and extension methods.

**Comment by benmccallum** [comment]
I'm all for this approach, we've discussed a bit on the linked PR. Definitely would like see this in 3.0!

**Comment by sungam3r** [comment]
It agree, it is possible to make implementation as resolver injection. In general, nothing prevents you from using both - ctor and resolver injection - at the same time.

**Comment by Shane32** [comment]
Completed via #1730

**Comment by sungam3r** [comment]
We should not forget about resolvers injection proposal. @Shane32  Are you implemented this in another PR?

**Comment by Shane32** [comment]
I support that in #1376 but it should be a separate project from the base graphql library most likely. It is a bit like the conventions project I think. Sometime we should have a separate discussion if or how #1376 should be included in the project.

**Comment by Shane32** [comment]
I would like to add the resolver injection proposal but it’s not practical with extension methods. I will review again.

**Comment by sungam3r** [comment]
OK
