### ISSUE TITLE
Logging handler for exceptions

### ISSUE THREAD

**Issue by mgkeen** [graphql-dotnet/graphql-dotnet#1152]
## Summary

A way to configure a logging delegate for exceptions

### Basic example

Naming here is probably terrible, but just to give an idea:

```
_schema.Execute(configure =>
            {
                configure.Query = request.Query;

                configure.ExceptionEvent(exception => _logger.Log(LogLevel.Error, exception));
            });
```

### Motivation

Currently I only have a couple of options for how to deal with exceptions:

- normal behaviour swallows stack traces
- expose stack traces via API
- `ThrowOnUnhandledExceptions` to bubble them up to the calling code

Currently i've got `ThrowOnUnhandledExceptions` set to `true` so that I can log the errors, and have to pass back a 5xx response. Ideally I would have the normal behaviour from the API, but be able to trigger a logging function when there's an issue so that I can keep on top of errors in production but also present a proper GraphQL endpoint.

Side note (/ bug?): It also appears that `ThrowOnUnhandledExceptions` is throwing all exceptions including `ExecutionError` ones? Perhaps due to https://github.com/graphql-dotnet/graphql-dotnet/blob/38a85611aabcabc2344b91d92760ca3dbb00fddb/src/GraphQL/Execution/DocumentExecuter.cs#L206 ?

Happy to put up a PR for this feature if it's thought to be a good idea / there's not a better alternative.

**Comment by sungam3r** [comment]
Is it not possible to take a set of errors from `ExecutionResult.Errors` and log them after execution?

Anyway I like idea about exception delegate in `ExecutionOptions`.

**Comment by mgkeen** [comment]
Thanks @sungam3r i had been using `Schema.Execute` rather than a `DocumentExecuter` so that's where I had been going wrong! Should have read the documentation closer. You've saved me quite a bit of hassle 😄 

In case anyone else comes along here having got stuck in the same way as me, this is the code i've come up with:

```
var executor = new DocumentExecuter();
            var executionResults = executor.ExecuteAsync(configure =>
            {
                configure.Schema = _schema;

                configure.Query = request.Query;
            }).Result;

            foreach (var executionError in executionResults.Errors)
            {
                if (!(executionError.InnerException is ExecutionError))
                {
                    _logger.LogError(executionError.InnerException, "An unexpected error occured during GraphQL execution.");
                }
            }

            return new DocumentWriter(indent:true).Write(executionResults);
```
That logs out any non `ExecutionError` errors without exposing stack traces in the JSON response.

It might still be nice to have the delegate for doing this in a cleaner way, so I won't close the issue with this.

**Comment by sungam3r** [comment]
@mgkeen our projects also needed such logging.

**Comment by mgkeen** [comment]
Sweet. Thanks @sungam3r!

**Comment by sungam3r** [comment]
Experience using this new API has shown that some information is missing. I will make another change to provide more information to the delegate.
