### ISSUE TITLE
Can I use graphql-dotnet in Asp.Net core 3 preview 5 project?

### ISSUE THREAD

**Issue by vlada-ns** [graphql-dotnet/graphql-dotnet#1161]
First I tested GraphQL-DotNet 2.4.0 in Asp.Net core 2.2 project and it worked perfectly.
Link to project --> https://github.com/vlada-ns/GraphQL-Test-1

Then I tested GraphQL-DotNet 2.4.0 in Asp.Net core 3.0.0 preview 5 project and I have problem. When I try GraphQL-DotNet 2.4.0 with GraphQL.Server.Ui.Playground 3.4.0 it report:
"Server cannot be reached"
"{
  "error": "Unexpected token S in JSON at position 0"
}"
Link to project --> https://github.com/vlada-ns/GraphQL-DotNet-2.4.0_in_AspNetCore-3.0.0-preview5

Why is that? Is there any way that I use GraphQL-DotNet in Asp.Net core 3 preview 5 project?
If there is a way, can someone show me example?

Thank you
Vladimir

**Comment by vlada-ns** [comment]
Ok, I found what was problem.
Problem was just with GraphQL.Server.Ui.Playground, it wont cooperate with GraphQL-DotNet in Asp.Net core 3.0.0 preview 5 without registering and allowing synchronous operations in Startup.cs
-->
services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });

Link to project example --> https://github.com/vlada-ns/GraphQL-DotNet-2.4.0_in_AspNetCore-3.0.0-preview5

**Comment by jtkech** [comment]
Just for infos, in `OrchardCore` we are using graphQL and we are doing the migration to aspnetcore 3.0. To fix the async read /write without using `AllowSynchronousIO`, we are using this kind of code.

                        using (var sr = new StreamReader(context.Request.Body))
                        {
                            // Asynchronous read is mandatory.
                            var json = await sr.ReadToEndAsync();
                            request = JObject.Parse(json).ToObject<GraphQLRequest>();
                        }

Note: here, for writing the response body we don't use the document writer because through `Newtonsoft` some sync writes are done.

        internal static readonly Encoding _utf8Encoding = new UTF8Encoding(false);
        ...

            // Asynchronous write to the response body is mandatory.
            var encodedBytes = _utf8Encoding.GetBytes(JObject.FromObject(result).ToString());
            await context.Response.Body.WriteAsync(encodedBytes, 0, encodedBytes.Length);

**Comment by sungam3r** [comment]
@vlada-ns Is this issue still actual?

**Comment by vlada-ns** [comment]
> @vlada-ns Is this issue still actual?

No, it is not.

**Comment by WilldelaVega777** [comment]
I can say it is actual, I have tried the code of the Pluralsight video course on GraphQL by Roland Guijt and I had the issue with Core 3 in Visual Studio 16.3.3 and Core 3.0.100 with GraphQL 2.4.0.  I then tried with:

            services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });

I have now the same error only that now it is complaining about the first character in the JSON token not being "s", but "<".  I can also see on the right side of the address bar of the playground: "Server cannot be reached". I know this is not SO but if anyone would have an idea would be greatly appreciated.

**Comment by sungam3r** [comment]
@WilldelaVega777 Please try the latest preview package (3.0.0-preview-1271) of graphql-dotnet.

**Comment by WilldelaVega777** [comment]
Hi sungam3r, thanks for your reply, I have installed the package, also the latest previews for GraphQL.Client and GraphQL.Server.Transports.AspNetCore but now I have underlined in red this line:

            services.AddScoped<IDependencyResolver>(x =>
                new FuncDependencyResolver(x.GetRequiredService));

I have tried and searched for a couple of hours now and it seems like IDependencyResolver and FuncDependencyResolver no longer apply or even exist in ASP.NET Core 3.  What is the right way to configure the middleware now?  This is my current configuration:

            // AutoMapper
            services.AddAutoMapper(typeof(Startup));

            // GraphQL Config
            services.AddScoped<GraphQLTestSchema>();

            services.AddGraphQL(
            options => {
                options.ExposeExceptions = true;
            })
            .AddGraphTypes(ServiceLifetime.Scoped);

            services.AddScoped<IDependencyResolver>(x =>
                new FuncDependencyResolver(x.GetRequiredService));

I also tried searching the documentation and the Github site for the project with no success. 
How do you configure GraphQL.NET in Startup.cs for a Core 3 project now?  I appreciate your help.

**Comment by sungam3r** [comment]
Just remove this
```c#
services.AddScoped<IDependencyResolver>(x =>
            new FuncDependencyResolver(x.GetRequiredService));
```

You can find actual docs about DI [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/dependency-injection.md).

**Comment by sungam3r** [comment]
Relates to #1326

**Comment by sungam3r** [comment]
Relates to #1321

**Comment by darrylwolfaardt** [comment]
@WilldelaVega777 , if you are still struggling and need to get ready for your demo use this guide to get setup https://putridparrot.com/blog/writing-a-graphql-service-using-graphql-dotnet-and-asp-net-core/. Follow the versions in the project setup and use dotnet 2.1. I have just done the setup and it works (after experiencing the same problem you posted about)

**Comment by WilldelaVega777** [comment]
Thanks Darryl, I actually have to demo this in a Core 3 app. I am already trying the solution by sungam3r, I hope I can make this work in Core 3 as from it depends on that my client may accept to use graphQL in his project, which would benefit a lot from its features.
Has anybody successfully made work GraphQL.NET with Core 3 w/o issues?  just one more question, when do you think the final release of GraphQL.NET for Core 3 (stable) will be publicly available?
Thanks a lot for your help.

**Comment by sungam3r** [comment]
> Has anybody successfully made work GraphQL.NET with Core 3 w/o issues? 

We will migrate all our backend on Core 3 only after Core 3.1 release (november).

> when do you think the final release of GraphQL.NET for Core 3 (stable) will be publicly available?

After completion of documentation and migration guide.

**Comment by noufionline** [comment]
Any updates on this please?

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server contains full functionining graphql server built on netcoreapp3.0

**Comment by johnnyoshika** [comment]
As @WilldelaVega777  suggested, in order for me to get GraphQL.Net to work in .Net Core 3.1, I had to add this in Startup's `ConfigureServices`. This should be sufficient in a demo application, but I probably won't want to do this in production:

```
            services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });
```

For reference, this is what my csproj file looks like:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.4.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0" />
  </ItemGroup>

</Project>
```

**Comment by sungam3r** [comment]
#1448 and #1449 in progress

**Comment by benmccallum** [comment]
I've been able to solve this issue in the graphql-dotnet server project, as the exception is actually on reading the request body synchronously in the middleware. PR is [here](https://github.com/graphql-dotnet/server/pull/299).
