### ISSUE TITLE
Deal with multidimensional array

### ISSUE THREAD

**Issue by mimescua** [graphql-dotnet/graphql-dotnet#1162]
## Summary
Hi, I'm triying to retrieve and use this array as a single "object" for geospatial purposes:

"coordinates":
[[[
      [-118.407, 33.749],
      [-118.407, 33.749],
      [-118.407, 33.749],
      [-118.407, 33.749],
      [-118.407,33.749]
]]]
## Relevant information
How to build a custom scalar type for this array?

I will consume this as is, not each coordinate numbers. For now I'm saving this as a large string (Oracle's CLOB type). Tried the same succesfully on Node.Js with a "Custom Scalar Type":

//SCHEMA.JS
`const typeDefs =
  scalar Coordinates
  type PolygonGeometry {
    type: String!
    coordinates: Coordinates!
  }
;`

//RESOLVERS.JS
`export const resolvers = {
    Coordinates: new GraphQLScalarType({
        name: 'Coordinates',
        description: 'City coordinates',
        parseValue(value) {
          return value;
        },
        serialize(value) {
          return value;
        },
        parseLiteral(ast) {
          return ast.value;
        },
    }),
    PolygonGeometry: {
        coordinates(item) {
          return item.coordinates;
        },
    },
};`

### Environment (if relevant)
Using GraphQL-Dotnet 2.4, Asp.Net coren 2.2 and Oracle 12.2

**Comment by corstian** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/1008 could be helpful for you.

Otherwise if you want the same format you could use a field which is defined as follows:

```csharp
Field<ListGraphType<ListGraphType<DecimalGraphType>>>()
    .Name("coordinates")
    .ResolveAsync(async context => { /* your code */ });
```

**Comment by sungam3r** [comment]
@mimescua Is this issue still actual for you?

**Comment by mimescua** [comment]
> 
> 
> @mimescua Is this issue still actual for you?

Dear @sungam3r thanks for your interest.
I solved it as follows(using parse with Newtonsoft):
`public async Task<IDictionary<int, Site>> GetSitesById(IEnumerable<int> siteIds, CancellationToken token)
        {
            return await _dbContext.SITE.Where(i => siteIds.Contains(i.Id)).Select(t => new Site
            {
                Id = t.Id,
                Type = t.Type,
                Coordinates = JsonConvert.DeserializeObject<List<List<List<List<double>>>>>(t.CoordinateString)
            }).ToDictionaryAsync(x => x.Id, cancellationToken: token);
        }`
