### ISSUE TITLE
troubleshooting running in docker

### ISSUE THREAD

**Issue by BasHamer** [graphql-dotnet/graphql-dotnet#1165]
## Description

app is .netcore 2.2 works in debug and release, graphiql is added, when I run on docker I get the following errors; Data send to the server is identical.

for a mutation (sessionStart)
{"errors":[{"message":"Schema is not configured correctly to fetch sessionStart.  Are you missing a root type?","extensions":{"code":"EXECUTION_ERROR"}}]}

graphiql has this returned as part of it's error.

"errors":[{"message":"Cannot return null for non-null type. Field: queryType, Type: __Type!.","locations":[{"line":4,"column":7}],"path":["__schema","queryType"]}]}

none of my types are showing up in the response.

I'd take any suggestions on how to troubleshoot this

**Comment by sungam3r** [comment]
I think, that this problem is not specific to docker. Your schema must have query type (mutation is optional) to fit the specification. See this -  https://graphql.github.io/graphql-spec/June2018/#sec-Schema-Introspection

**Comment by BasHamer** [comment]
It was an IOC registration by convention breaking on Docker. 
This is because it found different DLL's, something went sideways and the graph types were not loaded.

Added some documentation on the IOC package., nothing to do w/ graphql.
