### ISSUE TITLE
Autogenerated schema from CQRS Commands and Queries

### ISSUE THREAD

**Issue by cime** [graphql-dotnet/graphql-dotnet#1166]
I'm trying to autogenerate GraphQL schema from Commands and Queries but I'm stuck on how to register types at runtime and adding fields to root mutation/query objects.

What I would like to achive is:
- [x] get all commands/queries (handlers)
- [ ] for each command add new mutation, which takes command instance as argument and returns result of that command
- [ ] for each query add new query, which takes query instance as argument and returns result of that query (can be ignored - it's very similar to step above)

To keep it simplier we can ignore nested complex types and assume there is only one complex type for input and one for output and both are unique for each command/query.

Can someone look at the code and point me into the right direction? Thanks.

CqrsSchema - https://github.com/cime/graphql-dotnet-cqrs/blob/master/GraphQLTest/CqrsSchema.cs#L54

Repository - https://github.com/cime/graphql-dotnet-cqrs/

**Comment by BenjaBobs** [comment]
You need to specify your resolvers here:
https://github.com/cime/graphql-dotnet-cqrs/blob/master/GraphQLTest/CqrsSchema.cs#L101-L108

**Comment by cime** [comment]
@BenjaBobs thank you for your suggestions but types are still not generated. There is not type definition in the scheme for TestCommand and TestCommandResult.

    {
        "name": "test",
        "description": null,
        "args": [
        {
            "name": "command",
            "description": null,
            "type": {
            "kind": "INPUT_OBJECT",
            "name": "TestCommand",
            "ofType": null
            },
            "defaultValue": "null"
        }
        ],
        "type": {
        "kind": "OBJECT",
        "name": "TestCommandResult",
        "ofType": null
        },
        "isDeprecated": false,
        "deprecationReason": null
    }

CommandResolver (not sure if it would work it's not called) - https://github.com/cime/graphql-dotnet-cqrs/blob/master/GraphQLTest/CqrsSchema.cs#L136

**Comment by BenjaBobs** [comment]
Your GQL types for `TestCommand` and `TestCommandResult` are basic ones, that don't translate each field of their generic parameter. Try looking up `AutoRegisteringGraphType` (I think that's its name), which will do exactly that.

Also, when creating your field, you don't nees to set voth `Type` and `ResolvedType` properties, only one of them should be necessary. :)

**Comment by cime** [comment]
I removed the redundant Type on new fields. I changed the result type to AutoRegisteringObjectGraphType<> but still those two types are not defined in schema. Call to RegisterType doesn't change anything.

https://github.com/cime/graphql-dotnet-cqrs/commit/48bc1c685b786820561c5abc6d10063e8c603aad

**Comment by BenjaBobs** [comment]
I'm not sure why it's not registering, maybe it's an order thing. I'd try registering a simple hand coded HelloWorld mutation, and then afterwards convert that into a command and then afterwards do the generic approach.

**Comment by cime** [comment]
Turned out the problem was that I called FindType before creating new graphql type for commands/results which in turned called Create on GraphTypesLookup... Thank you @BenjaBobs  for your help.

https://github.com/cime/graphql-dotnet-cqrs/commit/97e01ab3d408a39690ec2c6e046660f33e7305e7
