### ISSUE TITLE
Field name parameter not work properly

### ISSUE THREAD

**Issue by belizar** [graphql-dotnet/graphql-dotnet#1167]
## Description

When I change the field name in Field() method, in GraphiQL I do not see the same name I set and I cannot query with name configured in Field() method .

![2019-06-02 20_18_40-Tesis API (Running) - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/37871475/58768577-0a7a5280-8574-11e9-8dbd-d4f0114c0f5c.png)

![2019-06-02 20_19_15-localhost_50319_graphql_](https://user-images.githubusercontent.com/37871475/58768581-10703380-8574-11e9-8c7e-1370bfac2181.png)

### Expected result

view the same field name in Field method and in GraphiQL explorer.

### Actual result

The field name is not the same.

### Environment

GraphQL 2.4.0
GraphiQL 1.2.0
.Net Core 2.2.0
Visual Studio 2019
Windows10

**Comment by KreativJos** [comment]
It could be because of casing (the api usually parses everything into camelcase starting with a lowercase letter).

We currently use the .Name("") function, which seems to work fine. For example:
`this.Field(m => m.Text, nullable: true).Name("text").Description("The text value for this item");`

**Comment by belizar** [comment]
Thank you, I will check it with that
when you say the api, you mean the graphQL api? or .net api

**Comment by KreativJos** [comment]
> Thank you, I will check it with that
> when you say the api, you mean the graphQL api? or .net api

The GraphQL.NET api, this repository.

**Comment by belizar** [comment]
> It could be because of casing (the api usually parses everything into camelcase starting with a lowercase letter).

but Why if I want to use the .NET naming convention ( PascalCasing ) ?

**Comment by PascalSenn** [comment]
Have a look at 
https://github.com/graphql-dotnet/graphql-dotnet/issues/248

**Comment by belizar** [comment]
ah ok!, then I should write my own PascalFieldNameConverter implementing IFieldNameConverter,
Thank you!

**Comment by joemcbride** [comment]
@belizar There is one available already so don't need to write your own!  🎉   Going to close this but feel free to re-open if you have any issues.

https://github.com/graphql-dotnet/graphql-dotnet/blob/0559a48e9251784028f7ca11045919c758fd6658/src/GraphQL/Conversion/IFieldNameConverter.cs#L40-L58

**Comment by belizar** [comment]
oh great! Thanks @joemcbride!
