### ISSUE TITLE
Support Apollo Federation

### ISSUE THREAD

**Issue by Patrick-Spiegel** [graphql-dotnet/graphql-dotnet#1169]
## Summary

Apollo released a new feature called federations. It would be awesome if graphql-dotnet supported this out of the box. 

### Basic example

https://blog.apollographql.com/apollo-federation-f260cf525d21

### Specification

https://www.apollographql.com/docs/apollo-server/federation/federation-spec/#federation-schema-specification

### Motivation

This feature would be essentials for services running on a distributed architecture (e.g. Service Fabric). This allows us to comine multiple seperate graph services into a single graph.

**Comment by PascalSenn** [comment]
Schema stitching is a feature that has been discussed a few times before. 
Have a look at
Remote Schema: 
https://github.com/graphql-dotnet/graphql-dotnet/issues/955
https://github.com/graphql-dotnet/graphql-dotnet/issues/1057


First try of a implementation :
https://github.com/graphql-dotnet/graphql-dotnet/pull/592

We move to competing solution because we highly rely on schema stitching.

**Comment by Patrick-Spiegel** [comment]
@PascalSenn what I mean is actually slightly different. Your linked tickets want graphql-dotnet to be able to be the proxy. 

Apollo released their own gateway which should be compatible with every plattform. The graphql endpoints must solely implement [this](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/#federation-schema-specification) and then they can be used by the apollo gateway. 

It would be awesome, if there was a unified implementation here in graphql-dotnet where you can enable those extra fields with e.g. ```EnableFederation()```  in the constructor of a class extending ```ObjectGraphType```.

**Comment by joemcbride** [comment]
Somewhat related - #1172 adds support for custom directives in Schema First, so that would make this easier to implement.

**Comment by kryptonianson** [comment]
For my work this is critical to implement. Hope it makes it in.

**Comment by stubbz** [comment]
My team is also interested in support for this.

**Comment by CyrilleFormont** [comment]
Any update on schema federation ?

**Comment by sungam3r** [comment]
Nope.

**Comment by d-led** [comment]
I guess, now one can simply use the GraphQL Mesh to transform an existing endpoint into a Federation-conforming one https://graphql-mesh.com/docs/transforms/federation/

**Comment by mac2000** [comment]
Nope, mesh wont help here very much (yes you will be able to run in as a simple proxy over your services and all you clients suddenly will have single entry point but it wont help you at all connecting all types between each other), project used underneath https://github.com/0xR/graphql-transform-federation is what your are looking for if you wish to somehow make everything work together

Meanwhile without solving #1002 first we wont be able to have federation in this project :( one provided here https://github.com/graphql-dotnet/graphql-dotnet/pull/1233 is not enough and wont work with code first even if you will try hack around with printing your schema and then parsing in FederatedSchemaBuilder everything will just blow up

**Comment by d-led** [comment]
@mac2000 indeed, there's the federation transform, but it doesn't allow the `resolveReference` config to be useful. However, I've successfully used their schema extensions and stitching

**Comment by d-led** [comment]
@mac2000 I've created an example her with the schema extension: https://github.com/d-led/graphql_mesh_federation_test
I'd expect the federation transform to be able to do that out of configuration

**Comment by joemcbride** [comment]
Just adding a note here that Apollo Federation _is_ currently supported in Schema First.  This was merged in #1233 and is available in [GraphQL >= 3.0.0](https://www.nuget.org/packages/GraphQL/3.0.0).

GraphType / Code First support will be added in the near future.

**Comment by mac2000** [comment]
BTW: we already using federation in production with all features like managed schema, schema evolution, monitoring, alerting all from apollo federation - everything works well

If anyone wish to to have code first federated service here is a PR - #1669 which might be used to achieve this
