### ISSUE TITLE
Question. Can you define custom mapping between model and type

### ISSUE THREAD

**Issue by TLogik** [graphql-dotnet/graphql-dotnet#117]
Is it possible to define the mapping between a field on a ObjectGraphType to an internal model representation?

So if you have an EF entity as the internal model it would make sense that fieldnames between entity and GraphQl ObjectGraphType are not equal.

On solution is to have an internal mapping model: EfType -> MappedModel -> ObjectGraphType
but i was just wondering if the framework had a way to map manually rather than the automated/automagic mapping that is currently happing by fieldnames.

Regards

**Comment by joemcbride** [comment]
If I'm understanding you correctly, yes you can manually map field names.

```csharp
public class PersonEFObject
{
  public string FirstName { get; set; }
  public string LastName { get; set; }
}

public class PersonObjectGraphType
{
  public PersonObjectGraphType()
  {
    Field<StringGraphType>(
      "name",
      resolve: ctx =>
      {
        var person = ctx.SourceAs<PersonEFObject>();
        return string.format("{0} {1}", person.FirstName, person.LastName);
      });
  }
}

public class RootQuery
{
  public PersonObjectGraphType()
  {
    Field<PersonObjectGraphType>(
      "person",
      resolve: ctx => new PersonEFObject { FirstName = "Fred", LastName = "Flinstone" }
  }
}
```

Query / Result:
```
query {
  person {
    name
  }
}

{
  "data": {
    "name":  "Fred Flinstone"
  }
}
```

**Comment by TLogik** [comment]
Yes. Spot on👍
Thanks.
