### ISSUE TITLE
Trying to use Generics in inheritance is causing schema issues

### ISSUE THREAD

**Issue by katrinamsnyder** [graphql-dotnet/graphql-dotnet#1174]
I have a graphType that I'm trying to inherit from another, and it seems to be blowing up the schema.

Base Graph Type:

``` csharp
public class DataModelDefinitionDetailsGraphType<T> : ObjectGraphType<T> where T : DataModelDefinitionDetails
    {
        public DataModelDefinitionDetailsGraphType()
        {
            Field(t => t.DataModelDefinitionDetailId, type: typeof(IdGraphType));
            Field(t => t.Description);
            Field(t => t.Status, type: typeof(ByteGraphType));
            Field(t => t.Owner);
        }
    }
```

Graph Type inheriting:
``` csharp
public class MyClassGraphType : DataModelDefinitionDetailsGraphType<MyClass>
    {
        public MyClassGraphType()
        {
            Field(t => t.DataModelDefinitionConfigurationId, type: typeof(IdGraphType));
        }
    }
```

The queries run and return the desired data, but the schema will not load.

GraphQL 2.4.0, code in C#/.NET

**Comment by joemcbride** [comment]
> The queries run and return the desired data, but the schema will not load.

Do you mean an introspection query?  Is there a specific tool you're using to look at the schema, such as GraphiQL?  Can you post any errors you're seeing?

You can expose error stacktraces by setting `ExposeExceptions = true` on `ExecutionOptions`.

https://graphql-dotnet.github.io/docs/getting-started/errors

**Comment by katrinamsnyder** [comment]
After you mentioned this, trying in GraphiQL it works fine. This seems to be an issue with UiPlayground, not with GraphQL.

**Comment by sungam3r** [comment]
Is this issue still actual?

**Comment by diego81b** [comment]
on generic class adding something like this

`Name = $"DataModelDefinitionDetails{typeof(T).Name}";`

do the job and Voyager renders correctly

hope can help
regards

**Comment by sungam3r** [comment]
@katrinamsnyder The problem was that the graph types had the same name. This is fixed. Now a shems cannot be created with such types. You can try the latest preview.
