### ISSUE TITLE
 convert long to string 

### ISSUE THREAD

**Issue by samchenws** [graphql-dotnet/graphql-dotnet#1177]
Hello, I have a problem. How can I change the long type to string?
![image](https://user-images.githubusercontent.com/37535153/59250052-c87a9c00-8c58-11e9-9889-86aabc43094d.png)
 
![image](https://user-images.githubusercontent.com/37535153/59250111-ec3de200-8c58-11e9-95b9-f04c03b94195.png)

**Comment by joemcbride** [comment]
Wow!  This is actually a bug.  I'm a bit surprised it hasn't been reported yet.

**Comment by samchenws** [comment]
Ok,Looking forward to the new version,Thank you for your efforts.Best Wishes
