### ISSUE TITLE
Sign GraphQL lib (A strongly-named assembly is required)

### ISSUE THREAD

**Issue by MakaBuka** [graphql-dotnet/graphql-dotnet#1181]
Hi @joemcbride ,

We're using signed lib that has refs on GraphQL and under .NET 4.5 got an error (because under .net framework we can't use unsigned lib in signed lib):

![image](https://user-images.githubusercontent.com/5338043/59355039-f5997e00-8d2e-11e9-86cb-fa9988380998.png)

Could you please sign GraphQL lib (v2.4.0) to resolve this issue?

**UPD:** solution from https://github.com/graphql-dotnet/graphql-dotnet/issues/234 doesn't work for me

In my case, when .NET4.5 app has ref signed DLL, which has ref on unsigned GraphQL lib

Note: Web.api, framework 4.5x, mvc

Thx, D.

**Comment by scottdallamura** [comment]
a signed version would be great...

**Comment by SimonCropp** [comment]
@sungam3r @joemcbride i have no opinion either way. I think strong naming is broken and most people use it since they think it provides security. the argument of "but think of the GAC" is pretty much moot now. but having said all that i currently SN all my libraries since i was fed up with fielding "please SN this" issues. 

but either way there should be an answer to this one. Do we close with "still not SNing"?

**Comment by sungam3r** [comment]
This question was always a PITA. Yes, people think that the signature makes the assembly more secure, but it is not. The signature only makes the assembly uniquely identifiable. It has pros and cons. Even if we begin to sign this assembly now, it will cause many errors when updating it in other projects where there are transitive dependencies. If the application (or lib) simultaneously refers to a package using an unsigned assembly and to another package using a signed version, a conflict will arise - assembly loading error. **Therefore, it is common advice when moving to signed assemblies to give the signed version a new name.**

In fact, in aforementioned situation, signing is a somewhat artificial requirement, caused only by the fact that signed assemblies cannot refer to unsigned ones. I would recommend to use https://github.com/dsplaisted/strongnamer.

So my answer is **not SNing**.

**Comment by sungam3r** [comment]
By the way we have to have all the dependencies signed, for example, GraphQLParser. Parent packages will also require retargeting or creating a new signed version of the package. All this is a huge amount of work. And this is not worth it.

**Comment by sungam3r** [comment]
Well, after reading  https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/strong-naming.md, I doubted again.

**Comment by SimonCropp** [comment]
"removes the main downside of strong naming."  while also removing the benefit of strong naming

**Comment by sungam3r** [comment]
The whole story is somewhat reminiscent of trying to sit on two chairs at the same time.

**Comment by sungam3r** [comment]
It's time to close this as wontfix.
