### ISSUE TITLE
IDGraphType returns integer property in quotations.  Is there a way to change this?

### ISSUE THREAD

**Issue by grounzero** [graphql-dotnet/graphql-dotnet#1183]
I changed my GraphTypes from integer to IDGraphType now when I do a query like this 

```
query {
  players(id: 61359) {
    id
  }
}
```

I get 

```
{
  "data": {
    "players": [
      {
        "id": "61359"
      }
    ]
  }
}
```

When before there were no quotations around "id":.  Is there a way to get the IDGraphType to return the type as it is defined on the underlying model?

**Comment by sungam3r** [comment]
See the [spec](http://spec.graphql.org/June2018/#sec-ID):
> The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. **The ID type is serialized in the same way as a String**; however, it is not intended to be human‐readable. While it is often numeric, **it should always serialize as a String**.

It is one of the built-in scalars with specific behavior requirements. If you need a different behavior then just don't use `ID`, use your own scalar.
