### ISSUE TITLE
Dynamic input type

### ISSUE THREAD

**Issue by temofeychik** [graphql-dotnet/graphql-dotnet#1185]
Can I use dynamic type in graph input type? My input type this :
```        
    public class UserInputType : InputObjectGraphType<User>
    {
        public UserInputType()
        {
            Name = "User";
            Field(x => x.UserName).Description("");
        }
   }
```
But in mutation I need this :
```
mutation {
  UserPost(
    User: {
      UserName: "UserName"
      CustomProperty1: "first"
      CustomProperty2 "second"
    }
  }
}
```
and I need to resolve this custom properties. Please help me

**Comment by sungam3r** [comment]
Can you provide an example of `User` class?

**Comment by temofeychik** [comment]
For example it is full class, I need provide to mutation custom fields, for example CustomProperty1 and CustomProperty2. And I don't know how many it will be

**Comment by sungam3r** [comment]
From topic I thought that one way or another the `dynamic` keyword is concerned.
Try using `AutoRegisteringObjectGraphType<T>`.

**Comment by temofeychik** [comment]
> From topic I thought that one way or another the `dynamic` keyword is concerned.
> Try using `AutoRegisteringObjectGraphType<T>`.

Thanks
