### ISSUE TITLE
Call scoped service in resolver

### ISSUE THREAD

**Issue by t0x1c123** [graphql-dotnet/graphql-dotnet#1190]
Hi, after hours of setting up the project I managed to figure out, that I can't call my scoped service in resolver, because service in resolver is transformed to singleton. And because my services work with database (Entity framework) I can’t have them registered as singleton. I saw a few issues here but there is no simple solution. So what is the purpose of this package if I can’t work with database and data in resolver? Or am I missing something? Is there any normal way to do that? Or I need to hack it?

**Comment by joemcbride** [comment]
There are a lot of issues posted related to this.  See #648, #1151,  #1160.

**Comment by t0x1c123** [comment]
> There are a lot of issues posted related to this. See #648, #1151, #1160.

Yeah I know. But all of them are just hacks and that's not really cool. So the answer here is there is no "official" way to do this if I get it right.
