### ISSUE TITLE
Custom Directives

### ISSUE THREAD

**Issue by ronMilne** [graphql-dotnet/graphql-dotnet#1193]
Is there by any chance documentation, a step by step guide on how one goes about writing custom directives. I'm looking to attempt to add @Take @TakeWhile on ListGraphType as a start.

Any help greatly appreciated,
Ron.

**Comment by joemcbride** [comment]
This comment should point you in the right direction.

https://github.com/graphql-dotnet/graphql-dotnet/issues/860#issuecomment-479661336

**Comment by joemcbride** [comment]
Also related: #1002 #1172

**Comment by ronMilne** [comment]
Didn't want to raise a new question. The directives I'm creating need to be against a ListGraphType only. How do I ensure that this is handled, through validation? If so I how do I attach a custom validator?

**Comment by sungam3r** [comment]
@ronMilne I do not think that this is possible. [Spec](https://graphql.github.io/graphql-spec/June2018/#sec-Type-System.Directives) defines certain elements of the schema on which directives can be placed. I don’t see that the place of use could be somehow tied to the ListGraphType only.
