### ISSUE TITLE
InputObjectGraphType - dynamic list on resolve

### ISSUE THREAD

**Issue by LewisGoldstone** [graphql-dotnet/graphql-dotnet#1194]
Is it possible to resolve a dynamic list of options on a InputObjectGraphType field?

So far I've got something like so:

`Field<ListGraphType<StringGraphType>> (
                "name",
                resolve: context => new[] { "test" }
            );`

But it looks the resolve function gets ignored completely, not even an error thrown.

**Comment by sungam3r** [comment]
> resolve function gets ignored completely

Does the control go there? This repository has a lot of tests which use `ListGraphType<StringGraphType>` fields with custom resolvers, so most likely the problem is in another place. Can you give a complete example?

**Comment by LewisGoldstone** [comment]
A lot of those tests, at least the ones I've seen, seem to be for ObjectGraphTypes rather than InputObjectGraphTypes.

My class looks like this:
`
public class DerivedContentTypesInputObjectType : InputObjectGraphType
    {
        public DerivedContentTypesInputObjectType()
        {
            Name = "DerivedContentTypes";
            Description = "Retrieves list of derived content types.";

            Field<ListGraphType<StringGraphType>> (
                "name",
                resolve: context => new[] { "test" }
            );
        }
    }
`
Where it's being passed in as an argument in the Schema Builder (removed any excess code)
`
public Task<IChangeToken> BuildAsync(ISchema schema)
        {
            var where = new ThingPartInputObjectType();

            schema.Query.AddField(new FieldType
            {
                Name = "thingPart",
                Arguments = new QueryArguments(
                    new QueryArgument<DerivedContentTypesInputObjectType>
                    {
                        Name = "contentType",
                        Description = $"filter by derived content type",
                        ResolvedType = new DerivedContentTypesInputObjectType()
                    }
                ),
                Description = T[$"Represents any type that is a thing part"],
                Type = typeof(ListGraphType<ThingInterface>),
                Resolver = new AsyncFieldResolver<IEnumerable<ContentItem>>(ResolveAsync<ThingPart>)
            });

            schema.RegisterType(where);
            return Task.FromResult<IChangeToken>(null);
        }
`

**Comment by joemcbride** [comment]
Resolve is not currently called on input objects.  There are actually a number of issues already opened asking this same thing.  There is no specific plans or timeframe to support a resolve function on input objects.

**Comment by sungam3r** [comment]
Relates to #1176
