### ISSUE TITLE
Subscription filter

### ISSUE THREAD

**Issue by t0x1c123** [graphql-dotnet/graphql-dotnet#1197]
Hi,

I have a question. I need to somehow filter subscription response by user. So for example I need to send specific subscription response to specific user by his ID from authentication header. Now I'm sending userId via subscription argument and returning null if notification is not for this specific user. But this is not cool beacause everyone subscribed are getting null response except the user with right userId. Also i need to mention that I'm using this https://github.com/graphql-dotnet/graphql-dotnet/pull/1160 (scoped dependencies).

So is there any option to filter subscription response by authenticated user id? For example like in apollo-graphql-server function with Filter?

Thanks :)

**Comment by Shane32** [comment]
With [System.Reactive](https://www.nuget.org/packages/System.Reactive/) it is easy to write `.Where(predicate)` to filter data events.  So within the source stream resolver, just use `.Where` to filter the events that match the proper user ID (typically passed within `IResolveFieldContext.User`).

Please ask if you have further questions.
