### ISSUE TITLE
Mapping Nullable fields in Graphql-dotnet

### ISSUE THREAD

**Issue by kktam** [graphql-dotnet/graphql-dotnet#1199]
## Summary
In GraphQL.dotNet, how is nullable database fields supported? (such as int?, float?).
Currently there seemed to be no support or way to map a int? field. If IntGraphType is used, the following compile time error will result

```

Error	CS0029	Cannot implicitly convert type 'int?' to 'GraphQL.Types.IntGraphType'	

```

## Relevant information
According to ApolloQL, the GraphQL Specifications does have sections that cover nullable fields.

[https://blog.apollographql.com/using-nullability-in-graphql-2254f84c4ed7](https://blog.apollographql.com/using-nullability-in-graphql-2254f84c4ed7)

### Environment (if relevant)

OS : Windows 10 Professional
DotNetCore: 2.1 or above
Compiler:  Visual Studio 2019 Community or Enterprise

**Comment by joemcbride** [comment]
How are you registering your field?  There are a few ways to do it.

```csharp
public class MyClass
{
    public int? MyField { get; set; }
}

public class MyGraphType : ObjectGraphType<MyClass>
{
    public MyGraphType()
    {
        Field(x => x.MyField, nullable: true, type: typeof(IntGraphType));
        Field<IntGraphType>("MyField");
    }
}
```

**Comment by kktam** [comment]
In Visual Studio 2019, I get an compile time error code (CS0411) with message on this pattern

```
The type arguments for method 'ComplexGraphType<MyClass>.Field<TProperty>(Expression<Func<MyClass, TProperty>>, bool Type)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

How to fix this particular error?

**Comment by kktam** [comment]
I found the correct version for version 2.4.0 and .net core 2.2.3 is

```
public class MyClass
{
    public int? MyField { get; set; }
}

public class MyGraphType : ObjectGraphType<MyClass>
{
    public MyGraphType()
    {
        Field("MyField", x => x.MyField, nullable: true, type: typeof(IntGraphType));
    }
}
```
