### ISSUE TITLE
Input Objects

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#12]

**Comment by moserware** [comment]
For details, see [graphql-js implementation](https://github.com/graphql/graphql-js/blob/f9a287754898faf850101045f7d63000ea1b2159/src/type/definition.js#L863) and the [GraphQL spec](https://facebook.github.io/graphql/#sec-Input-Object-Values)

**Comment by joemcbride** [comment]
Marking this as done for now.
