### ISSUE TITLE
Is it possible to translate the query to just requested fields in T-SQL?

### ISSUE THREAD

**Issue by unosbaghaie** [graphql-dotnet/graphql-dotnet#1203]
I just profiling T-SQL queries, generated by GraphQL 
Query is : 
```
{
  product(id: 37) {
    id
    productCategory {
      id
    }
  }
}
```

and the repose is 

```
{
  "data": {
    "product": {
      "id": "37",
      "productCategory": [
        {
          "id": "58"
        }
      ]
    }
  }
}
```

in sql profiler  the generated query is:

```
exec sp_executesql N'SELECT TOP(1) [i].[Id], [i].[ProductCategoryId], [i].[ProductName]
FROM [Products] AS [i]
WHERE [i].[Id] = @__id_0',N'@__id_0 int',@__id_0=37

and 

exec sp_executesql N'SELECT [pc].[Id], [pc].[Name]
FROM [ProductCategories] AS [pc]
WHERE [pc].[Id] = @__productCategoryId_0',N'@__productCategoryId_0 int',@__productCategoryId_0=58

``` 
In product I didn't request `ProductName` field and in ProductCategories its `Name` field, although  my query contains all columns.  

Is it possible in GraphQL to translate the query to just requested fields in query?

for example have this 
```
exec sp_executesql N'SELECT TOP(1) [i].[Id], [i].[ProductCategoryId]
FROM [Products] AS [i]
WHERE [i].[Id] = @__id_0',N'@__id_0 int',@__id_0=37
```

**Comment by sungam3r** [comment]
> Is it possible in GraphQL to translate the query to just requested fields in query?

This custom translation is out of graphql-dotnet scope. See https://github.com/SimonCropp/GraphQL.EntityFramework
