### ISSUE TITLE
Nullable int type does not work in graphql-dotnet

### ISSUE THREAD

**Issue by kktam** [graphql-dotnet/graphql-dotnet#1208]
## Description

Nullable int does not work with graphql-dotnet. 

The following pattern that was provided in documentation causes compile time error in Visual Studio 2019.

```
The type arguments for method 'ComplexGraphType<MyClass>.Field<TProperty>(Expression<Func<MyClass, TProperty>>, bool Type)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

### Steps to reproduce

Use the following pattern to create a Entity object with a nullable int type, and maps to IntGraphType.

```
public class MyClass
{
    public int? MyField { get; set; }
}

public class MyGraphType : ObjectGraphType<MyClass>
{
    public MyGraphType()
    {
        Field(x => x.MyField, nullable: true, type: typeof(IntGraphType));
        Field<IntGraphType>("MyField");
    }
}
```

### Expected result

Compile success, and GraphQL and GraphQL playground test will show the data correctly maps to the field.

### Actual result

This code does not compile in Visual Studio 2019, and causes the following exception (error code (CS0411) )

```
The type arguments for method 'ComplexGraphType<MyClass>.Field<TProperty>(Expression<Func<MyClass, TProperty>>, bool Type)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

### Environment

OS : Windows 10 Professional
DotNetCore: Tested with .net core from 2.1 to 2.2.3
Compiler: Visual Studio 2019 Community or Enterprise
Browser: IE 11 or Edge
Library:   asp.net core 2.2.x, entity framework core 2.2.x

**Comment by sungam3r** [comment]
I use this example
```c#
public class MyClass
{
    public int? MyField { get; set; }
}

public class MyGraphType : ObjectGraphType<MyClass>
{
    public MyGraphType()
    {
        Field(x => x.MyField, nullable: true, type: typeof(IntGraphType));
        Field<IntGraphType>("MyField");
    }
}
```
on master branch and it compiles well both in VS2017 and VS2019.

**Comment by kktam** [comment]
I was using GraphQ for .NET 2.4.0 from Nuget Package manager. What is the highest version released in NuGet that has the feature fixed?

**Comment by sungam3r** [comment]
Try this
![изображение](https://user-images.githubusercontent.com/21261007/60743993-91a85500-9f7c-11e9-9309-373f81ef9a86.png)

**Comment by kktam** [comment]
I finally got this compiled with version 2.4.0 in Nuget. But running this example with real data will result in a run-time exception

```
Exception thrown: 'System.ArgumentOutOfRangeException' in GraphQL.dll
An exception of type 'System.ArgumentOutOfRangeException' occurred in GraphQL.dll but was not handled in user code
A field with the name: MyField is already registered for GraphType: MyGraphType
```

**Comment by kktam** [comment]
I found the correct version for version 2.4.0 and .net core 2.2.3 is

```
public class MyClass
{
    public int? MyField { get; set; }
}

public class MyGraphType : ObjectGraphType<MyClass>
{
    public MyGraphType()
    {
        Field("MyField", x => x.MyField, nullable: true, type: typeof(IntGraphType));
    }
}
```

**Comment by sungam3r** [comment]
Duplicates #1199
