### ISSUE TITLE
Azure Functions Support

### ISSUE THREAD

**Issue by StefanSchoof** [graphql-dotnet/graphql-dotnet#1209]
## Summary

Have a easy and documented way how to use graphql-dotnet in a Azure Function.

### Basic example

There is a blog post at https://www.tpeczek.com/2019/05/serverless-graphql-with-azure-functions.html with code at https://github.com/tpeczek/Demo.Azure.Functions.GraphQL/blob/master/Demo.Azure.Functions.GraphQL/Infrastructure/GraphQLExecuterExtensions.cs how to wire a azure function with graphql-dotnet.

### Motivation

Azure Functions are a cheap way to set up a scalable service, with a growing developer base. Having a single source of the wrapping code from the project itself would make it easier to use and put it to single place to optimize and add features to the code.

**Comment by sungam3r** [comment]
Please clarify the problem. Do you propose to add documentation about graphql integration in Azure Functions to this project? Or do you propose to bring all the code itself from the aforementioned repository into graphql-dotnet repo? I understand that the first.

**Comment by StefanSchoof** [comment]
Im unsure which is the best way to integrate. I want to use graphql-dotnet in an azure function. I think having in the documentation the best way would be good. If the way from the blog post is good way, having this code inside a nuget package would be beneficial. But maybe a good way is to start with a documentation and see if this need much code.

**Comment by sungam3r** [comment]
Notice that graphql-dotnet repo doesn’t concern how transport will be carried out. I read the mentioned article and looked at the demo repo code. Now I can say with confidence that it is worth contacting this problem in the [server repo](https://github.com/graphql-dotnet/server). The purpose and structure of server project (particular asp net core transport, websockets transport) is much closer for aforementioned azure functions. However, in a good way, it still needs to be a separate repository (maybe in the graphql project family).

**Comment by StefanSchoof** [comment]
Thanks I will open a issue there.

**Comment by StefanSchoof** [comment]
open the issue: https://github.com/graphql-dotnet/server/issues/232
