### ISSUE TITLE
Cadena vacia al publicar proyecto de GraphQL y C#

### ISSUE THREAD

**Issue by areyes21** [graphql-dotnet/graphql-dotnet#1210]
Buen dia tengo una aplicacion hecha en Visual Studio con C#, .Net Core y GraphQL

En la solucion todo anda bien, la ejecuto y puedo consultar los datos... Pero cuando la publico ejecuto una query y me retorna una cadena vacía 

Imagen de la API GraphQL Publicada
![imagen](https://user-images.githubusercontent.com/37639639/60826220-9fbbc880-a16a-11e9-8064-59aacad147e9.png)

Imagen de la API GraphQL cuando la ejecuto en la Solucion
![imagen](https://user-images.githubusercontent.com/37639639/60826235-a5b1a980-a16a-11e9-81a4-403a67717cb6.png)

**Comment by sungam3r** [comment]
What version of graphql-dotnet do you use?

1. Try to see the server response in the browser debugger (F12).
2. Turn on / add server side logs to find a problem.

**Comment by Jonatthu** [comment]
@areyes21 Tienes el proyecto en github? O parte del código?

**Comment by SimonCropp** [comment]
closing due to lack of response
