### ISSUE TITLE
Multi-tenant usage

### ISSUE THREAD

**Issue by phatcher** [graphql-dotnet/graphql-dotnet#1212]
Any examples/suggested approaches for a multi-tenant project i.e. single endpoint delivering same conceptual schema but the details may vary per tenant.

Given that ISchema is a singleton, I can't see an obvious way around delivering multiple schemas from the same endpoint.

**Comment by sungam3r** [comment]
See #1160, there are some thoughts about it.

**Comment by sungam3r** [comment]
Actually you **can** expose multiple schemas from the same endpoint. [GraphQL-over-HTTP spec](https://github.com/graphql/graphql-over-http/blob/master/spec/GraphQLOverHTTP.md#url) talks about it:
> The schema on a single URL MAY not be the same for every client. For example, certain fields could be restricted to authenticated users or alpha testers.

Also see `Schema.Filter` to return different intrspection results to clients.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
