### ISSUE TITLE
What's the best way to return error response from mutation ?

### ISSUE THREAD

**Issue by rahulpandey8920** [graphql-dotnet/graphql-dotnet#1215]
I have created a mutation which will create a user with the following schema:

```javascript
type User {
  id: String!
  name: String!
}

input UserInputType {
  name: String!
}

type Mutation {
  createUser(userInput: userInputType!): User!
}
```
I am trying to understand what is the best way to return an error response with which the client can understand that the username already exists.

**Comment by sungam3r** [comment]
Maybe not the best way but you can use unions:
```
union CreateUserResult = User | Error

type Error {
   text: String!
}

type Mutation {
  createUser(userInput: userInputType!): CreateUserResult!
}
```

See [this article](https://medium.com/the-graphqlhub/graphql-tour-interfaces-and-unions-7dd5be35de0d)

**Comment by draganjovanovic1** [comment]
Standard defines `data` and `errors` properties for GraphQL response. I would set mutation return type to `User` instead of `User!` and return `null` for `data` and list of errors in `errors`. Makes sense?

**Comment by sungam3r** [comment]
@draganjovanovic1 Yes. The difference with my example is that my example describes the error as data (a different kind of data, but still data).

@rahulpandey8920 Is this issue still actual for you?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
