### ISSUE TITLE
Fragment generating INVALID_CAST error

### ISSUE THREAD

**Issue by laird** [graphql-dotnet/graphql-dotnet#1217]
## Description

Issuing a query with a fragment generates a "INVALID_CAST" error and the message "Error trying to resolve...". Issuing the same query expressed without the fragment returns data properly. NB: example query compacted to a trivial case to illustrate the error.

### Steps to reproduce

```
query {
    usedvehicles(vin:"1FTEW1EFG" mileage:120000 state:"NY")
        {
          	error_count warning_count
        }
}
```

returns expected result below.

Issuing query:

```
fragment responseFields on UsedVehicleResultType {error_count warning_count}

query {
    usedvehicles(vin:"1FTEW1EFG" mileage:120000 state:"NY")
        {
          	...responseFields
        }
}
```

returns the error below (actual result)

Both queries validate in Insomnia against the schema exposed by the GraphQL endpoint.

### Expected result

```
{
  "data": {
    "usedvehicles": {
      "error_count": 0,
      "warning_count": 0
    }
  }
}
```

### Actual result

```
{
  "data": {
    "usedvehicles": null
  },
  "errors": [
    {
      "message": "Error trying to resolve usedvehicles.",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "usedvehicles"
      ],
      "extensions": {
        "code": "INVALID_CAST"
      }
    }
  ]
}

```
### Environment

ASP.Net Web API 2 version 5.2.7, running in AWS on Windows 2012.

**Comment by joemcbride** [comment]
What is the full error you are getting?  You can see this by exposing the exceptions in the response.

https://graphql-dotnet.github.io/docs/getting-started/errors

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
