### ISSUE TITLE
Input enum validation

### ISSUE THREAD

**Issue by stephenlautier** [graphql-dotnet/graphql-dotnet#1219]
## Summary

We have a mutation with an enum as a parameter e.g. `Gender`. Is it possible to add some kind of validation instead of the following error:
`Variable '$input.gender' is invalid. Invalid Scalar value for input field.` using our custom logic (e.g. FluentValidator). When passing invalid data e.g. `"x", "" or so`

## Relevant information
We tried to add it here but it never triggers (even when valid)

```cs
// # RegistrationInputGraphType

  Field<GenderEnum>("gender", resolve: ctx =>
  {
	// it never breaks here
	return (int)ctx.Source.Gender;
  });

// gender enum graphtype
public class GenderEnum : EnumerationGraphType
{
	public GenderEnum()
	{
		AddValue("male", "gender type", (int)Gender.Male);
		AddValue("female", "gender type", (int)Gender.Female);
	}
}
```

**Comment by sungam3r** [comment]
Relates to #1176

**Comment by sungam3r** [comment]
Also see `IVariableVisitor` from #2276

**Comment by sungam3r** [comment]
@stephenlautier Now you can use Input Object Custom Deserializers (aka resolver) . See https://github.com/graphql-dotnet/graphql-dotnet/blob/develop/docs2/site/docs/migrations/migration4.md#input-object-custom-deserializers-aka-resolver . Override `ParseDictionary` to be able to return calculated value for your `RegistrationInputGraphType`.
