### ISSUE TITLE
Is it possible to use graphql-dotnet without defining types?

### ISSUE THREAD

**Issue by hnafar** [graphql-dotnet/graphql-dotnet#1220]
## Summary

I have an application where schema are defined in a DSL, and data is loaded dynamically. e.g.
a schema definition looks like:

```json
{
  "type": "person",
  "properties": [
    { "id": "id", "type": "string" },
    { "id": "firstName", "type": "string" },
    { "id": "age", "type": "int" },
  ]
}
```
and the data can be loaded from a document db, which will look like:

```json
{
  "id": "1",
  "firstName": "foo"
}
```

the schema and the data can be modified by application users.
Is it possible for me to utilize graphql without creating corresponding c# classes, to

- generate a graphql-dotnet schema from my schema defined in DSL
- resolve queries using graphql-dotnet facilities, but retrieve requested type info, etc. from context

is it possible to create schema and resolve queries without defining any types?

**Comment by joemcbride** [comment]
> is it possible to create schema and resolve queries without defining any types?

It is possible without specific C# classes, but you do have to define the Graph Types.  GraphQL is a typed query language.

You will need to write a "Schema Builder" that can build a schema based off of your data.

```csharp
var root = new ObjectGraphType { Name = "Root" };
root.Field("name", new GraphQLTypeReference("String"), resolve: ctx => "A Name");
var schema = new Schema { Query = root };

var result = schema.Execute(_ =>
{
    _.Query = "{ name }";
});
```

(This utilizes an extension method defined [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/f4ba7cb97f1da453bceab6d61cb5632015a22490/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L330-L348))

There is an example `SchemaBuilder` you can look at that is used for the Schema Syntax.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaBuilder.cs

**Comment by sungam3r** [comment]
@hnafar Yes, this is a supported use case. You still have to create a schema object (to execute it) and fill it with types and their fields, but these will be ready-made basic object types (`ObjectGraphType` etc).

**Comment by sungam3r** [comment]
Closed as resolved.
