### ISSUE TITLE
Constructor injection is failing if i use GraphQL controller with Asp.Net Core.

### ISSUE THREAD

**Issue by f2002642** [graphql-dotnet/graphql-dotnet#1222]
as per https://github.com/graphql-dotnet/graphql-dotnet/issues/788, we have 3 different approaches of using GraphQL controller with Asp.Net Core..

1. services.AddGraphQL(No controller or middleware)
2. using middleware
3. Controller, mostly in Asp.Net web API 2

If use approach 3, constructor injection always fails for me.
Any pointers will help.

**Comment by sungam3r** [comment]
What kind of error do you have?

**Comment by f2002642** [comment]
I noticed that constructor is not even being called...
I doubt that default constructor is being called

**Comment by sungam3r** [comment]
Read this https://github.com/graphql-dotnet/graphql-dotnet/blob/73189c11cce05b96b6f29f0dfb184e9d339f7a80/docs2/site/docs/getting-started/dependency-injection.md

**Comment by f2002642** [comment]
I noticed that constructor is not even being called...
I doubt that default constructor is being called

**Comment by joemcbride** [comment]
@f2002642 it is literally impossible for us to debug your code for you.  Unless you post code and/or error messages all we can do is point you to existing code that works (which we have done).  You’re going to have to dig deeper into the issue yourself unless you provide more information.  If constructor injection isn’t working, then you need to find what error you’re getting and fix it.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
