### ISSUE TITLE
Custom datetime format not working

### ISSUE THREAD

**Issue by FlutterIODev** [graphql-dotnet/graphql-dotnet#1226]
## Description

I'm trying to customize the DateTime format from the startup class by adding this code:

```
.AddJsonOptions(options =>
            {
                var settings = options.SerializerSettings;
                settings.DateFormatHandling = DateFormatHandling.IsoDateFormat;
                settings.DateTimeZoneHandling = DateTimeZoneHandling.Utc;
                settings.DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss";                
            })
```

### Expected result

Date formatted with my custom format "yyyy'-'MM'-'dd'T'HH':'mm':'ss"

### Actual result

The default format "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK"

### Could be the cause

I think this [line ](https://github.com/graphql-dotnet/graphql-dotnet/blob/757486fd9206f49d7666938b506fd13beaef60ed/src/GraphQL/Http/DocumentWriter.cs#L29) should be changed in such a way that takes the customization that I put at the startup class.

**Comment by joemcbride** [comment]
That _can_ be changed.  Change how you register the `DocumentWriter` to use the other constructor instead of the default.

https://github.com/graphql-dotnet/graphql-dotnet/blob/757486fd9206f49d7666938b506fd13beaef60ed/src/GraphQL/Http/DocumentWriter.cs#L33-L37

That being said, do use a different date format it may be easier for you to use your own GraphType so you can fully control that there.

**Comment by sungam3r** [comment]
> Change how you register the DocumentWriter to use the other constructor instead of the default.

Exactly. @FlutterIODev see how it is done in [server project](https://github.com/graphql-dotnet/server/blob/develop/src/Core/ServiceCollectionExtensions.cs#L36).

**Comment by FlutterIODev** [comment]
Thanks you for your help, Adding this line as you suggested solve my problem.

```
 services.AddSingleton<IDocumentWriter>(x =>
            {
                JsonSerializerSettings jsonSerializerSettings = x.GetRequiredService<IOptions<JsonSerializerSettings>>().Value;
                jsonSerializerSettings.DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFF'Z'";
                return new DocumentWriter(Formatting.None, jsonSerializerSettings);
            });
```

**Comment by FlutterIODev** [comment]
Thanks you for your help, Adding this line as you suggested solve my problem.

```
 services.AddSingleton<IDocumentWriter>(x =>
            {
                JsonSerializerSettings jsonSerializerSettings = x.GetRequiredService<IOptions<JsonSerializerSettings>>().Value;
                jsonSerializerSettings.DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFF'Z'";
                return new DocumentWriter(Formatting.None, jsonSerializerSettings);
            });
```

**Comment by FlutterIODev** [comment]
Thank you for your help, Adding this line as you suggested solve my problem.

```
 services.AddSingleton<IDocumentWriter>(x =>
            {
                JsonSerializerSettings jsonSerializerSettings = x.GetRequiredService<IOptions<JsonSerializerSettings>>().Value;
                jsonSerializerSettings.DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFF'Z'";
                return new DocumentWriter(Formatting.None, jsonSerializerSettings);
            });
```
