### ISSUE TITLE
GraphQLUserContext need to implments  IDictionary<string, object>

### ISSUE THREAD

**Issue by FlutterIODev** [graphql-dotnet/graphql-dotnet#1227]
## Summary
In my application, I'm using JwtBearer authentication, and I found that I need to call httpContext.AuthenticateAsync at AddUserContextBuilder to access my protected schema by using this code.

```
                .AddUserContextBuilder(
                async (httpContext) =>
                {
                    GraphQLUserContext userContext = new GraphQLUserContext
                    {
                        User = httpContext.User
                    };
                    if (!httpContext.User.Identity.IsAuthenticated)
                    {
                        var result = await httpContext.AuthenticateAsync(JwtBearerDefaults.AuthenticationScheme);
                        if (result.Succeeded)
                        {
                            userContext.User = result.Principal;
                            httpContext.User = result.Principal;
                        }
                    }
                    return userContext;
                })
```

Today I have updated to the latest version of graphql-dotnet, Before the update my GraphQLUserContext was short:

```
 public class GraphQLUserContext : GraphQL.Authorization.IProvideClaimsPrincipal
        {
            public ClaimsPrincipal User { get; set; }
        }
```
After the update I have forced to implement IDictionary<string, object> in my GraphQLUserContext class, so the class now is too long with not implemnetd methods.

```
public class GraphQLUserContext : GraphQL.Authorization.IProvideClaimsPrincipal, IDictionary<string, object>
        {
            public object this[string key] { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

            public ClaimsPrincipal User { get; set; }

            public ICollection<string> Keys => throw new NotImplementedException();

            public ICollection<object> Values => throw new NotImplementedException();

            public int Count => throw new NotImplementedException();

            public bool IsReadOnly => throw new NotImplementedException();

            public void Add(string key, object value)
            {
                throw new NotImplementedException();
            }

            public void Add(KeyValuePair<string, object> item)
            {
                throw new NotImplementedException();
            }

            public void Clear()
            {
                throw new NotImplementedException();
            }

            public bool Contains(KeyValuePair<string, object> item)
            {
                throw new NotImplementedException();
            }

            public bool ContainsKey(string key)
            {
                throw new NotImplementedException();
            }

            public void CopyTo(KeyValuePair<string, object>[] array, int arrayIndex)
            {
                throw new NotImplementedException();
            }

            public IEnumerator<KeyValuePair<string, object>> GetEnumerator()
            {
                throw new NotImplementedException();
            }

            public bool Remove(string key)
            {
                throw new NotImplementedException();
            }

            public bool Remove(KeyValuePair<string, object> item)
            {
                throw new NotImplementedException();
            }

            public bool TryGetValue(string key, out object value)
            {
                throw new NotImplementedException();
            }

            IEnumerator IEnumerable.GetEnumerator()
            {
                throw new NotImplementedException();
            }
        }
```

## Question

Is it safe to keep these methods not implemented? and why I need to implement IDictionary<string, object> in my GraphQLUserContext class?

**Comment by joemcbride** [comment]
The `UserContext` was changed from `object` to `IDictionary<string, object>` in the latest alpha to make it easier to provide more than a single context value in a request.  Instead of implementing the interface directly, you could have your class inherit from `Dictionary<string, object>`.  `UserContext` will be expected to be a functioning Dictionary.

The Authorization project will most likely be updated to not rely upon the `UserContext` directly to retrieve the user, but a factory/service to fetch it.  Example idea here:  https://github.com/graphql-dotnet/authorization/pull/19

**Comment by FlutterIODev** [comment]
> The `UserContext` was changed from `object` to `IDictionary<string, object>` in the latest alpha to make it easier to provide more than a single context value in a request. Instead of implementing the interface directly, you could have your class inherit from `Dictionary<string, object>`. `UserContext` will be expected to be a functioning Dictionary.
> 
> The Authorization project will most likely be updated to not rely upon the `UserContext` directly to retrieve the user, but a factory/service to fetch it. Example idea here: [graphql-dotnet/authorization#19](https://github.com/graphql-dotnet/authorization/pull/19)

Thanks for your clarification :)
