### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by silkfire** [graphql-dotnet/graphql-dotnet#1228]
Are there any plans to update NuGet with the latest version of the repository?

Our project requires some of the fixes implemented since the last NuGet version (November 2018) and we're not very keen on having to import the graphql-dotnet project into the solution.

**Comment by sungam3r** [comment]
I'm waiting for it myself, but now I just use myget nuget feed.

**Comment by joemcbride** [comment]
@silkfire The latest of the repository is the 3.0 preview.  There won't be any 2.x maintenance releases unless there is some security issue.

GraphQL 3.0.0-preview-1194 is pushed to NuGet.org, may take a while for it to show up.

More "daily" builds can be downloaded from here:

https://www.myget.org/F/graphql-dotnet/api/v3/index.json

**Comment by StefH** [comment]
Are there also release notes for this 3.0.0 preview?

**Comment by joemcbride** [comment]
@StefH you can check the closed issues on the 3.0 milestone.

https://github.com/graphql-dotnet/graphql-dotnet/milestone/4?closed=1

**Comment by sungam3r** [comment]
Closed as resolved. The latest versions of packages are periodically published on nuget.
