### ISSUE TITLE
handling N + 1 problem just like Prisma

### ISSUE THREAD

**Issue by aammfe** [graphql-dotnet/graphql-dotnet#1230]
Hello ! 
Is its possible to have a wrapper around ef or something that can be learn from [prisma](https://www.prisma.io Web result with site links Prisma) for solving n + 1.

yes we have data loaders but those have to be created for each case. 

something like EF + builtin wrapper. 

Thanx

**Comment by techniq** [comment]
See: https://github.com/SimonCropp/GraphQL.EntityFramework
