### ISSUE TITLE
AutoRegisteringObjectGraphType with enum

### ISSUE THREAD

**Issue by diego81b** [graphql-dotnet/graphql-dotnet#1231]
## Description

Using AutoRegisteringObjectGraphType on an object that has properties of type enum (even if derived to EnumerationGraphType) are not correctly registered

### Expected result

The same as scalar property

### Actual result

An error is thrown

```
"The type: TireSeasonEnum cannot be coerced effectively to a GraphQL type\r\nParameter name: type"
```

### Environment

Windows 10

**Comment by sungam3r** [comment]
What version do you use? Try latest preview version. If the problem persists, give an example of your schema.

**Comment by sungam3r** [comment]
Also see [this test]

**Comment by diego81b** [comment]
I've tried the preview version but with no luck beacuse there are other breaking changes that i'm not able to solve (for example schema recognition).

i watch the test but i'm using the class version and i don't know if something change

just an additional info: i use the [server package](https://github.com/graphql-dotnet/server)

thank you very much for the support
bye

**Comment by diego81b** [comment]
i use the latest stable version of all the packages

**Comment by sungam3r** [comment]
What is _class version_ ?

**Comment by sungam3r** [comment]
It seems to me that the fixes you need are made in the preview version. Version 2.4.0 is rather old.

**Comment by diego81b** [comment]
With class version i mean that i use a class derived from ObjectGraphType .
2.4.0 it's old but first, it's the stable version, second i don't find any documentation how to port from that version to preview.
I'm pretty sure that u address me to the right solution but if u provide me some example on how to use preview version will be cool
Thanks a lot

**Comment by sungam3r** [comment]
Please, provide a minimal example of your schema/type which causes the problem.

**Comment by furier** [comment]
You need to register a mapping between the enum type and the graph type, i use this method.

        private static void AddEnumType<T>(IServiceCollection services)
        {
            GraphTypeTypeRegistry.Register(typeof(T), typeof(EnumerationGraphType<T>));
            services.AddSingleton<EnumerationGraphType<T>>();
        }

        private static void RegisterEnumGraphTypes(IServiceCollection service)
        {
            AddEnumType<ProductEnum>(service);
        }

**Comment by sungam3r** [comment]
Since #1180 it is no longer required.

**Comment by sungam3r** [comment]
@diego81b Is this issue still actual?

**Comment by diego81b** [comment]
@sungam3r i can't switch to the preview version so i stiil have this problem.
Anyway you can close i maybe i re-open with detailed information further on

**Comment by sungam3r** [comment]
@diego81b Ok. Feel free to reopen.

Closed since this issue was fixed in current version.
