### ISSUE TITLE
mapping only certain fields from graphql to entity framework

### ISSUE THREAD

**Issue by nmarun** [graphql-dotnet/graphql-dotnet#1232]
## Summary
Pass specific column names to EF than 'SELECT *'
## Relevant information
I'm playing with a sample application that has graphql - EF - MS SQL setup. When I query for say 

```
{
  properties {
    name
    id
    city
  }
}
```
The query I see in the console output is:
```
SELECT [p].[Id], [p].[City], [p].[Family], [p].[Name], [p].[Street], [p].[Value]
RealEstate.API>       FROM [Properties] AS [p]
```
Though I only queried for a subset of the fields, all columns were projected in the query. To avoid this, I'm passing the SubFields from the context:
```
public PropertyQuery(IPropertyRepository propertyRepository)
{
    Field<ListGraphType<PropertyType>>(
        "properties",
        resolve: context => propertyRepository.GetFields(context.SubFields));
}

public class PropertyRepository : IPropertyRepository
    {
       ....
        public IEnumerable<Property> GetFields(IDictionary<string, GraphQL.Language.AST.Field> subFields)
        {
            return _db.Properties.Select(p => new Property
            {
                Name = subFields.ContainsKey("name") ? p.Name : null,
                Family = subFields.ContainsKey("family") ? p.Family : null,
                City = subFields.ContainsKey("city") ? p.City : null
            });
        }
```
Instead of having to write these individual conditions, is there a way I can convert the SubFields into an appropriate Property instance either in the Field<> definition or somewhere else?
### Environment (if relevant)
asp.net core 2.0

**Comment by sungam3r** [comment]
This may help you https://github.com/SimonCropp/GraphQL.EntityFramework

**Comment by nmarun** [comment]
Thanks @sungam3r. You helped me on a [related](https://github.com/graphql-dotnet/graphql-dotnet/issues/1234) thread.
