### ISSUE TITLE
How to structure big queries?

### ISSUE THREAD

**Issue by yhnavein** [graphql-dotnet/graphql-dotnet#1235]
# Summary

There are a lot of examples of really simple Queries for domains like StarWars characters and it's nice and easy. But how I am supposed to structurize/organize query where are dozens of different fields defined?

I thought that there can be multiple queries, which would make a lot of sense, but no. It is not possible. Then how it should be done?

The thing I am concerned is that I don't want to end with 1000 lines of code Query class.

**Comment by joemcbride** [comment]
I suggest to use data modeling techniques like Domain Driven Design to split up your Graph Types.

Specifically for organizing queries, yes there is only one root Query, but you can still organize them into different types.

See these docs:  https://graphql-dotnet.github.io/docs/getting-started/query-organization

**Comment by SimonCropp** [comment]
closing this as it seems to be answered

**Comment by sungam3r** [comment]
@yhnavein Also you can define query fragments and reuse them around codebase.
