### ISSUE TITLE
Custom data loader

### ISSUE THREAD

**Issue by johnfg2610** [graphql-dotnet/graphql-dotnet#1236]
## Summary
Hey, I'm trying to implement a data loader for MongoDB. Ive read a couple of issues relating to this and read [this](https://graphql-dotnet.github.io/docs/guides/dataloader) several times. I could be missing something but how do i implement this? because as i understand it were meant to either use IDataLoader, as in the tests and simpledataloader. but how do we know what to load in the load async method? because it only accepts one value so do we just return a random value or the first or is there some context object i should be getting somehow. Ive got my own implementation on top of mongodb [here](https://github.com/johnfg10/JRepo).
## Relevant information
Version 2.4.0

**Comment by OpenSpacesAndPlaces** [comment]
The parent object from IResolveFieldContext.Source.

IDataLoader<KParent, KChild>

So when you fire LoadAsync(KParent) - so it knows which child objects to load.

**Comment by Shane32** [comment]
@johnfg2610 Data loader implementation is documented here: https://graphql-dotnet.github.io/docs/guides/dataloader

There are setup instructions and samples; everything you should need to have a working data loader implementation.

Also you can write your own data loader implementation from scratch as long as data loader nodes return an object that implements `IDataLoaderResult`.  Please refer to the source of the reference data loader implementation to work from.

Please let me know if you have further questions in this regard.
