### ISSUE TITLE
StackOverflow expection if two interface types referencing each other has the same name

### ISSUE THREAD

**Issue by zlepper** [graphql-dotnet/graphql-dotnet#1237]
## Description
So I just spend most of today debugging this one: If i have two interfaces refencing each other as fields, GraphQL causes a stackoverflow exception (which kills the dotnet process). 

### Steps to reproduce

Use the following models:
```csharp

 public class TestSchema : Schema
    {
        public TestSchema(RootQuery rootQuery)
        {
            RegisterType<GraphTypeA>();
            RegisterType<GraphTypeB>();
            RegisterType<InterfaceA>();
            RegisterType<InterfaceB>();
            Query = rootQuery;
        }
    }

    public class RootQuery : ObjectGraphType<object>
    {
        public RootQuery()
        {
            Field<InterfaceA>("a");
            Field<InterfaceB>("b");
        }
    }

    public class TestA
    {
        public string Foo { get; set; }
    }

    public class TestB
    {
        public string Bar { get; set; }
    }

    public class InterfaceA : InterfaceGraphType<TestA>
    {
        public InterfaceA()
        {
            Name = "a";
            Field<NonNullGraphType<InterfaceB>>("toB", "Links to b");
        }
    }

    public class InterfaceB : InterfaceGraphType<TestB>
    {
        public InterfaceB()
        {
            Name = "a";
            Field<NonNullGraphType<ListGraphType<NonNullGraphType<InterfaceA>>>>("toA", "Links to a");
        }
    }

    public class GraphTypeA : ObjectGraphType<TestA>
    {
        public GraphTypeA()
        {
            Field<NonNullGraphType<GraphTypeB>>("toB", "Links to b");
            Interface<InterfaceA>();
        }
    }

    public class GraphTypeB : ObjectGraphType<TestB>
    {
        public GraphTypeB()
        {
            Field<NonNullGraphType<ListGraphType<NonNullGraphType<GraphTypeA>>>>("toA", "Links to a");
            Interface<InterfaceB>();
        }
    }
```

And make graphql generate a schema => 💥
### Expected result
It should error out, and tell me that I have a double type registration. 

### Actual result

Stackoverflow exception.

Seems to be a chain of 
```
AddTypeIfNotRegistered
HandleField
AddType
AddTypeIfNotRegistered
```

### Environment
dotnetcore 2.2
Graphql: 2.4.0
Graphql-server: 3.4.0

### Note
It can be fixed by the developer by simply fixing the interface name, however it took me quite a while to notice it was wrong. In the above example change the name of `InterfaceB` to "b", and everything works. 
I have attached a full project where the bug is present just in case. 
[GraphqlBug.zip](https://github.com/graphql-dotnet/graphql-dotnet/files/3493776/GraphqlBug.zip)

**Comment by sungam3r** [comment]
Relates to #1156 and #1139 

I will duplicate my comment here:

> Now there are many opportunities for carelessness to create such a schema that will be invalid. I'm sure this is the subject of a separate task. In general, now API of schema classes (GraphTypes) allows you to set any properties you like, and the problems will be revealed already at the stage of request execution.

**Comment by zlepper** [comment]
Perfectly fine with me, I wanted to create the issue mostly as help for other people that might encounter the same issue, so they at least have an idea of what might be going wrong :)
We wrap the graphql classes internally, so I'll just add a safety check on startup in our code for now :)

**Comment by sungam3r** [comment]
@zlepper Can you check if the problem persists?

**Comment by zlepper** [comment]
Tested using 
````xml
<PackageReference Include="GraphQL" Version="3.0.0-preview-1268" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0027" />
```

And it works as intended (Gives an error preventing the schema from being created, and it doesn't kill the process :D)
