### ISSUE TITLE
GraphQL Client

### ISSUE THREAD

**Issue by acjackman** [graphql-dotnet/graphql-dotnet#124]
Does this library provide a client interface for an remote GraphQL endpoint? If so, is there any examples of using GraphQL to get data for a .NET Client application?

**Comment by JarnoNijboer** [comment]
There is an official browser client for any GraphQL endpoint: [GraphiQL](https://github.com/graphql/graphiql). It is the same one that's used in the sample app in this repo.

**Comment by JarnoNijboer** [comment]
There isn't a client api in this library. It's fairly simple to create one; the query is just a string literal, that is part of the query request.

A sample of a GraphQL query, which you can sent as JSON object to an GraphQL(.NET) endpoint:
```csharp
public class GraphQLQuery
{
    public string OperationName { get; set; }
    public string Query { get; set; }
    public string Variables { get; set; }
}
```

**Comment by joemcbride** [comment]
Basically just what @JarnoNijboer mentioned.  There isn't a client api, though its as simple as making an http request to the endpoint.  The exact structure of that request depends on the implementation of that endpoint.

The [sample GraphQL endpoint](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Controllers/GraphQLController.cs) expects a structure like the above.

**Comment by acjackman** [comment]
Thanks @JarnoNijboer and @joemcbride!

**Comment by bkniffler** [comment]
I've been looking for the same in this repo, but it doesn't really seem to be the purpose of this library. If someone is interested, I created a very simple example graphql client here, maybe it will help you get started with your clients: https://github.com/bkniffler/graphql-net-client
