### ISSUE TITLE
"error": "Unexpected token S in JSON at position 0" errors after updating to ASP.NET CORE 3.0 preview 8 

### ISSUE THREAD

**Issue by Jjaszkowiak** [graphql-dotnet/graphql-dotnet#1240]
## Description

We have a project that we are attempting to update to .NET Core preview 8 and after the update we no longer can access the graph in playground. Instead we get the error "Server cannot be reached" and "error": "Unexpected token S in JSON at position 0". We attempted to update all nuget packages to the latest but still get this error.

**Comment by joemcbride** [comment]
Have you tried hitting the service directly outside of the playground?  What does the response look like?  What version of the JavaScript GraphQL package is the Playground using?

Try exposing errors in your GraphQL server configuration, described here:

https://graphql-dotnet.github.io/docs/getting-started/errors

**Comment by Jjaszkowiak** [comment]
Thanks for the suggestions.

I tested on both 3.4 of the playground and 3.5.0 alpha0014 with the same results. I am not fully sure what version of GraphQL the playground is using. Looking at their source I believe this is the version:
<add key="myget-graphql-dotnet" value="https://myget.org/F/graphql-dotnet/api/v3/index.json" />

Here is the full error I get from our production client:

useAllCommandsQuery.js:26 useAllCommandsQuery.error: {"graphQLErrors":[],"networkError":{"name":"ServerParseError","response":{},"statusCode":500,"bodyText":"System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)\r\n   at System.IO.StreamReader.ReadSpan(Span`1 buffer)\r\n   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)\r\n   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)\r\n   at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)\r\n   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.Deserialize[T](Stream s)\r\n   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)\r\n\r\nHEADERS\r\n=======\r\nContent-Type: application/json\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: en-US\r\nAuthorization: Bearer MyToken\r\nHost: localhost:5001\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) MySweetApp/1.0.0 Chrome/69.0.3497.106 Electron/4.0.0 Safari/537.36\r\nOrigin: null\r\nContent-Length: 150\r\n:method: POST\r\n:authority: localhost:5001\r\n:scheme: https\r\n:path: /graphql\r\n"},"message":"Network error: Unexpected token S in JSON at position 0"}

**Comment by joemcbride** [comment]
Ah, this is a known issue with newer versions of .NET Core.  See this issue for a fix:  https://github.com/graphql-dotnet/graphql-dotnet/issues/1116#issue-435502721

**Comment by Jjaszkowiak** [comment]
That was definitely an issue and that has resolved most of my errors. Unfortunately it appears that I have multiple issues causing the Unexpected token S in JSON at position 0 errors.

Here is the error I am still getting:

`useComponentsQuery.js:23 useComponentsQuery.error: {"graphQLErrors":[],"networkError":{"name":"ServerParseError","response":{},"statusCode":500,"bodyText":"System.InvalidOperationException: Unable to resolve service for type 'GraphQL.IDependencyResolver' while attempting to activate 'MyApp.Service.GraphServiceDefinition.SchemaDefinition'.\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)\r\n   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)\r\n\r\nHEADERS\r\n=======\r\nContent-Type: application/json\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: en-US\r\nAuthorization: Bearer Token\r\nHost: localhost:5001\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) MyApp/1.0.0 Chrome/69.0.3497.106 Electron/4.0.0 Safari/537.36\r\nOrigin: null\r\nContent-Length: 99\r\n:method: POST\r\n:authority: localhost:5001\r\n:scheme: https\r\n:path: /graphql\r\n"},"message":"Network error: Unexpected token S in JSON at position 0"}`

**Comment by joemcbride** [comment]
> Unable to resolve service for type 'GraphQL.IDependencyResolver' while attempting to activate 'MyApp.Service.GraphServiceDefinition.SchemaDefinition'

This means that it can't find `GraphQL.IDependencyResolver` in your DI container.  `GraphQL.IDependencyResolver` is deprecated in favor of `IServiceProvider`, though you should still be able to use `GraphQL.IDependencyResolver`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/2138bf42576b723d86eef8e401ae63c1e00df279/src/GraphQL/Types/Schema.cs#L69-L75

**Comment by Jjaszkowiak** [comment]
That was my mistake. I updated to the latest` graphql-dotnet` preview and broke the DI container attempting to update to `IServiceProvider`.

I am good to go now. Thanks for your help!!!

**Comment by tolgacakir** [comment]
I've got this error message from the playground when executing a query. It is solved like below:

 `services.AddSingleton<ISchema, MySchema>();` changed to this line `services.AddSingleton<MySchema>();`
 
 [see also](https://stackoverflow.com/questions/64873917/unable-to-resolve-service-for-type-xxxschema-while-attempting-to-activate-gra/64890478#64890478)
