### ISSUE TITLE
graphqlPath is not defined

### ISSUE THREAD

**Issue by nmarun** [graphql-dotnet/graphql-dotnet#1243]
## Summary
Error: graphqlPath is not defined
## Relevant information
I have my repo at https://github.com/nmarun/customergraph. When I run the application, I don't see any schemas in the document explorer. Instead I get an error message as shown in the attachment.

![image](https://user-images.githubusercontent.com/5554175/63091458-05764e00-bf7c-11e9-80ec-22867f1d0054.png)

**Comment by nmarun** [comment]
The app is working through Postman calls, but graphiql is failing. I'll open a ticket in that space.

**Comment by aldd-dpulidog** [comment]
Did you solve it?
