### ISSUE TITLE
Subscription Authentication using Authorization Bearer Header

### ISSUE THREAD

**Issue by kmanev073** [graphql-dotnet/graphql-dotnet#1244]
Hi guys!

I am using JWT tokens with Role based authentication. It all works just fine for mutations and queiries but not for sucbsciptions. My frontend is an Angular app and there I just inject the jwt token in every request. How could I do the same for subscriptions? Maybe I have to authenticate using anoter method?

There is no user context inside my Authorization Validator when I receive a subscription.

You can check this issue too: [(https://github.com/graphql-dotnet/graphql-dotnet/issues/733)]

Hope someone can help :)

Regards,
Kaloyan Manev

**Comment by rs-anders-agren** [comment]
Hi!
We're having the same issue here. What we can see is that the token is sent during the WebSocket "upgrade process": `{"type":"connection_init","payload":{"Authorization":"Bearer eyJhbGciOiJIUzI..."}}`.
But we're missing a callback from the lib to actually verify the token, or the actual token inside some context.

Thoughts anyone?

Regards,
Anders

**Comment by pekkah** [comment]
Would have pointed to this but.. https://github.com/graphql-dotnet/server/blob/develop/samples/Samples.Server/AddAuthenticator.cs

**Comment by rs-anders-agren** [comment]
Thanks pekkah!
We've looked at that but haven't tested it yet. The note at the top of the file, and the fact that it hasn't been touched for more than a year, mislead us a bit...

Regards,
Anders

**Comment by kmanev073** [comment]
Any other more elegant solution?

**Comment by DavidKiff** [comment]
If the subscription is over web sockets, then the handshake is over HTTP, sadly that handshake doesnt allow authorization headers.  You will need to send the token another way (i.e. perhaps in the URL as a query string, assuming you have SSL!).

**Comment by rs-anders-agren** [comment]
I see now that I wrote "upgrade process" but that part is actually done when the `connection_init` message is sent. My bad.

But the real problem (at least for us) was to hook in to the subscription initialization process. Turned out it was pretty simple after all. Just sub-class `IOperationMessageListener` and check if the init process has kicked in:
```c#
public class AuthListener : IOperationMessageListener
{
  public AuthListener ()
  {
  }

  public Task BeforeHandleAsync(MessageHandlingContext context)
  {
    if (context.Message.Type == MessageType.GQL_CONNECTION_INIT)
    {
      // Extract the auth header and validate it.
      // Then get the user and store it in the httpContext (or something) 
    }
    return Task.FromResult(true);
  }

  public Task HandleAsync(MessageHandlingContext context)
  {
    return Task.CompletedTask;
  }

  public Task AfterHandleAsync(MessageHandlingContext context)
  {
    return Task.CompletedTask;
  }
}
```

Then you just add the listener as a transient and you're good to go.

**Comment by sungam3r** [comment]
@rs-anders-agren You're right. I added this issue to the list of known issues.

**Comment by georgiosd** [comment]
This doesn't seem to be there any more and the docs still point to the old interface. Any poitners?

**Comment by Shane32** [comment]
GraphQL.NET Server version 7 has been mostly rewritten, and extensively supports authentication, including over subscriptions from a browser.  To perform authentication for WebSocket connections from a browser, you'll need to write a class that implements `IWebSocketAuthenticationService` and register it via ` .AddWebSocketAuthentication<T>()`.  There is a complete sample of JWT authenticated located here:

https://github.com/graphql-dotnet/server/tree/master/samples/Samples.Jwt

If you have a specific question, I suggest opening an issue over at https://github.com/graphql-dotnet/server and I would be happy to answer.

**Comment by Shane32** [comment]
I’d suggest also reading the new documentation for the Server project and in particular the bit regarding authentication over websockets. 

https://github.com/graphql-dotnet/server#authentication-for-websocket-requests

**Comment by georgiosd** [comment]
So the https://graphql-dotnet.github.io/docs/getting-started/introduction/ docs are obsolete?

**Comment by Shane32** [comment]
Certainly the FAQ item that discusses subscription authentication is obsolete and does not work.  I am removing that documentation now in #3490 .

The documentation in the introduction attempts to provide the simplest use of GraphQL.NET, without the server repo.  While the documentation may not be inaccurate, I would recommend following the instructions and samples in the server repo for configuration of GraphQL.NET over ASP.NET Core.

Of also note, the server repo does not attempt to demonstrate the various ways of creating a schema.  The schema samples are the simplest possible, using "type-first" schemas.  You can also create schema-first and code-first schemas.  It is common for codebases to use a combination of code-first and type-first to create a schema.  Unfortunately there is not much documentation yet regarding type-first schemas.
