### ISSUE TITLE
EF Core Race Condition on Async Fields

### ISSUE THREAD

**Issue by aaronjedwards** [graphql-dotnet/graphql-dotnet#1253]
## Summary
I am accessing an EF core DB context through my own services that I am resolving within my graph types like so:

```csharp
public Query(IDependencyResolver resolver)
{
    var myService = resolver.Resolve<IMyService>();

    Field<ListGraphType<MyType>>()
    .Name("type1")
    .ResolveAsync(async context => {
        var list = await myService.GetMyTypeList();
        return list;
    });

    Field<ListGraphType<MyOtherType>>()
    .Name("type2")
    .ResolveAsync(async context => {
        var list = await myService.GetMyOtherTypeList();
        return list;
    });

...
```

where `IMyService` and `IDependencyResolver` are registered as scoped services and my implementation for `IDependencyResolver` is like so:

```csharp
internal sealed class ServiceProviderAdapter : IDependencyResolver
{
    private readonly IServiceProvider services;

    public ServiceProviderAdapter(IServiceProvider services)
    {
        this.services = services.CreateScope().ServiceProvider;
    }

    public T Resolve<T>() => services.GetRequiredService<T>();

    public object Resolve(Type type) => services.GetService(type);
}
```

For a query that access both fields as listed above, I am getting the following error and believe it is as a result of a race condition when accessing the DB context within `IMyService` from both fields, but am not sure how to get around it:

`The connection was not closed. The connection's current state is connecting`

Would simply resolving the service within each Field solve the problem? Or do I need to register/resolve my services in a different way? Forgive my limited knowledge of DI containers and Dependency Injection in general. 

This library is fantastic by the way. Any help is appreciated!

Edit: Im thinking that if I make `IMyService` Transient and resolve it in each field where it is needed, then that might solve the issue. Thoughts?

**Comment by joemcbride** [comment]
This is a well known issue with Entity Framework.  Instead of accessing your DataContext directly,  a decent pattern would be to use a factory method to fetch your DataContext (or your dependency which uses your DataContext).

> Im thinking that if I make IMyService Transient and resolve it in each field where it is needed, then that my solve the issue. Thoughts?

Yes, that would work.

Here is one example of doing it, with lots of discussion around it.  https://github.com/graphql-dotnet/graphql-dotnet/pull/1160

**Comment by aaronjedwards** [comment]
@joemcbride thanks for the quick response! I did see #1160 and was starting to read into it.

>  Yes, that would work.

Is that to say that when the transient service is resolved (and a new instance is created), that the DBContext instance that it is injected with is now new as well and not shared? (And therefore shouldn't suffer from the current race condition I am experiencing?).

**Comment by joemcbride** [comment]
Yes, if you use a Factory or Service Locator.  GraphType's take on the lifetime of the Schema.  So if your Schema, or your GraphType are not also transient, you can have a scoping mis-match.  Factory pattern is typically preferred over Service Locator, but that is up to you.

```csharp
// service locator
public Query(IDependencyResolver resolver)
{
    Field<ListGraphType<MyType>>()
    .Name("type1")
    .ResolveAsync(async context => {
       var myService = resolver.Resolve<IMyService>();
        var list = await myService.GetMyTypeList();
        return list;
    });

    Field<ListGraphType<MyOtherType>>()
    .Name("type2")
    .ResolveAsync(async context => {
        var myService = resolver.Resolve<IMyService>();
        var list = await myService.GetMyOtherTypeList();
        return list;
    });
```

```csharp
// factory pattern
public Query(Func<IMyService> factory)
{
    Field<ListGraphType<MyType>>()
        .Name("type1")
        .ResolveAsync(async context => {
            var myService = factory();
            var list = await myService.GetMyTypeList();
            return list;
        });

    Field<ListGraphType<MyOtherType>>()
        .Name("type2")
        .ResolveAsync(async context => {
            var myService = factory();
            var list = await myService.GetMyOtherTypeList();
            return list;
        });
```

**Comment by aaronjedwards** [comment]
thanks for your help @joemcbride! I appreciate the examples as well. While these are both fairly new patterns to me, I will look into them and post back on which one worked for me.

**Comment by aaronjedwards** [comment]
For anyone that was having a similar issue, I ended up going with the Service Locator pattern and used this example as a guide. https://github.com/mmacneil/ASPNetCoreGraphQL
