### ISSUE TITLE
Mark objects not to cause impact during complexity analysis

### ISSUE THREAD

**Issue by SDLionas** [graphql-dotnet/graphql-dotnet#1254]
Is there a way to mark custom types and/or fields to be ignored in complexity analysis?

We have a complex structure like this:
```
price {
  value
  currency {
      identifier
  }
  units {
      identifier
      category {
          identifier
      }
  }
}
```
The problem we are facing is the fact that currency and units (plus their category) are cached and we just pick up and ID from the DB alongside value and then just get those from the cache.
However, all this nesting is calculated in both depth and complexity of the query. Is there a way to avoid this without implementing our analyzer?

**Comment by sungam3r** [comment]
Now default complexity analyzer is very limited in its capabilities.

> Is there a way to avoid this without implementing our analyzer?

Not yet.
