### ISSUE TITLE
Use Total records count under Extensions

### ISSUE THREAD

**Issue by petrdicp** [graphql-dotnet/graphql-dotnet#1264]
Query implementation look like this:
```csharp
   public class ContactQuery : ObjectGraphType
    {
        public ContactQuery(ContactContext contactContext)
        {
            FieldAsync<ListGraphType<ContactType>>("contacts",
                arguments: new QueryArguments(new List<QueryArgument>
                {
                     //other arguments
  
                    new QueryArgument<IntGraphType> { Name = "limit", DefaultValue = 10 },
                    new QueryArgument<IntGraphType> { Name = "offset", DefaultValue = 0 }
                }),
                resolve: async context =>
                {
                    var query = contactContext.Contacts
                        .Include(x => x.ContactAddresses)
                        .Include(x => x.PhoneNumbers)
                        .AsQueryable();

                  // other query logic using passed arguments

                    var totalRecordsCount = query.AsQueryable().Count();
                    var offset = context.GetArgument<int>("offset");
                    var limit = context.GetArgument<int>("limit");

                  return await query
                        .Skip(offset)
                        .Take(limit)
                        .ToListAsync();
                });
     }
}
```
At the end of query logic i am using ```var totalRecordsCount = query.AsQueryable().Count();```
for getting total records count. How to save this count number and use it outside this context?
I want to put this number under Extensions.

**Comment by sungam3r** [comment]
You can use `ResolveFieldContext.UserContext` to store any value. Then you can get this value in `DocumentExecuter.ExecuteAsync` (you may want to copy ExecuteAsync method into your own `CustomDocumentExecuter`) and write it into `ExecutionResult.Extensions`. I see that now there is only one application of extensions - `EnrichWithApolloTracing`. Extensions in general are an external entity with respect to GraphQL, and they will have to be recorded in the middleware layer.

**Comment by barryhagan** [comment]
What is the purpose of adding it to Extensions?  If that is for the client to consume, it would probably be better to return an object graph that includes count information in addition to the results (look at the Relay Connection concept, or make your own return type that has both count and results in it).

It is perfectly valid to have more than one query in a request using aliasing, so you will have problems if it is just thrown into an extension field:
```
{
  firstTen: contacts(limit: 10) {
    name
  }
  firstTwenty: contacts(limit: 20) {
    name
  }
}
```

vs.

```
{
  firstTen: contacts(limit: 10) {
    totalCount
    items { name }
  }
  firstTwenty: contacts(limit: 20) {
    totalCount
    items { name }
  }
}
```

I'd rather have `totalCount` as a property in the graph, and then I can use the `items` instead of trying to figure it out in the extensions.

**Comment by sungam3r** [comment]
@barryhagan completely agree with you

**Comment by sungam3r** [comment]
@petrdicp Is this issue still actual for you?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
