### ISSUE TITLE
DataLoader as a separate library

### ISSUE THREAD

**Issue by shoe-diamente** [graphql-dotnet/graphql-dotnet#1266]
## Summary

The [dataloader package](https://github.com/graphql/dataloader) for the [original graphql implementation](https://github.com/graphql/graphql-js) has been put into a separate generic library because caching seems orthogonal to graphql.

Would it be possible to separate the dataloader API into a separate package?

### Motivation

Data caching utilities are useful mostly within the data fetching layer. The data fetching layer could be deployed as a separate DLL from the GraphQL server. It would therefore be optimal to only include the dataloader library for the data fetching layer and the GraphQL library for the GraphQL server.

**Comment by sungam3r** [comment]
In principle, this is feasible but will inevitably lead to some complication when making changes due to the fact that these parts will be in different repositories.

**Comment by MisterJimson** [comment]
The caching is only per request. One of graphql main benefits is solving n+1 for nested queries. So a basic per request caching seems to align with the main strategy of graphql. I think it should stay in the same package.

**Comment by SimonCropp** [comment]
I dont understand the Motivation here?

> Data caching utilities are useful mostly within the data fetching layer. The data fetching layer could be deployed as a separate DLL from the GraphQL server. It would therefore be optimal to only include the dataloader library for the data fetching layer and the GraphQL library for the GraphQL server.

Either way the dlls are loaded in an app domain that uses the full GraphQL lib? so being able to ref a subset of functionality in this case would seem cosmetic?

**Comment by sungam3r** [comment]
Another option is independent versioning. But I also think that this is all cosmetics.

**Comment by Shane32** [comment]
All of the data loader code, apart from `IDataLoaderResult` (and the code within the execution strategy), can easily be separated into a separate nuget package, @sungam3r .  v4 or v5?

`IDataLoaderResult` is only:

```cs
    public interface IDataLoaderResult
    {
        Task<object> GetResultAsync(CancellationToken cancellationToken = default);
    }
```

Again, all code for data loaders within the execution strategy only needs this interface to operate, and all data loader implementation details can be separated with no ill effects.  Further, other data loader (or data-loader-like) implementations can be constructed from scratch if desired.  The execution strategy just needs this one interface to identify data loader nodes and to execute them at the appropriate time.

**Comment by sungam3r** [comment]
Let's move it into new project/package for v4 - `GraphQL.DataLoader`

**Comment by Shane32** [comment]
I’ll do a PR
