### ISSUE TITLE
Wrap all Mutations in TransactionScope

### ISSUE THREAD

**Issue by DavidKuennen** [graphql-dotnet/graphql-dotnet#1280]
I couldn't find anything in the docs or existing issues so I'm asking away. 

I want to wrap all my Mutations in a TransactionScrope, but only the Transactions (not the Queries) and only if there's more than one Mutation. 

Is there a way to achieve this?

**Comment by sungam3r** [comment]
Yes. You can use custom `DocumentExecuter`. After [this line](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L98) you have a `Document` - an object representing parsed graphql query. It can be inspected for mutations count. Then before [actual execution](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L182) you can establish transaction scope if required.

This method assumes that you copy all code from the existing `DocumentExecuter` and augment it with your changes. Not very good, but it should work.

**Comment by SimonCropp** [comment]
we execute the graphql query from a aspnet controller. so we put the transaction scope in the controller.

@DavidKuennen can we close this one?

**Comment by sungam3r** [comment]
@DavidKuennen I hope you could solve the problem.

**Comment by armaniehs** [comment]
I implemented a new ExecutionStrategy for it

```csharp
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;

namespace GraphQL.Execution
{
    public class TransactionalSerialExecutionStrategy : SerialExecutionStrategy
    {
        // Copied and modified from GraphQL.Execution.ExecutionStrategy
        public override async Task<ExecutionResult> ExecuteAsync(ExecutionContext context)
        {
            var rootType = ExecutionHelper.GetOperationRootType(context.Document, context.Schema, context.Operation);
            var rootNode = BuildExecutionRootNode(context, rootType);

            if (context.Operation.OperationType == Language.AST.OperationType.Mutation && rootNode.SubFields.Count > 0)
            {
                using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                {
                    var result = await Execute(context, rootNode);
                    if (result.Errors?.Any() ?? false == false)
                    {
                        scope.Complete();
                    }
                    return result;
                }
            }

            return await Execute(context, rootNode);
        }

        public async Task<ExecutionResult> Execute(ExecutionContext context, RootExecutionNode rootNode)
        {
            await ExecuteNodeTreeAsync(context, rootNode)
                .ConfigureAwait(false);

            // After the entire node tree has been executed, get the values
            var data = rootNode.ToValue();

            return With(new ExecutionResult
            {
                Data = data
            }, context);
        }

        public static ExecutionResult With(ExecutionResult result, ExecutionContext context)
        {
            result.Query = context.Document.OriginalQuery;
            result.Document = context.Document;
            result.Operation = context.Operation;
            result.Extensions = context.Extensions;

            return result;
        }
    }
}
```

You could be done better however GraphQL.Execution.ExecutionResultExtensions is internal hence I copied it.
