### ISSUE TITLE
Error when pass null to an array field

### ISSUE THREAD

**Issue by diouxis** [graphql-dotnet/graphql-dotnet#1285]
## Description

Value coverter has an issue when trying converting a null value to an array.

### Steps to reproduce

1. Include a Array property in the InputObjectType, e.g. int[].
2. Pass null for this field from GraphQL query.

### Expected result

Get a null value for this array.

### Actual result

Throw an exception says
> Object of type 'System.Collections.Generic.List`1[System.Int32]' cannot be converted to type 'System.Int32[]'.

### Reason
GetPropertyValue function will return empty List of element, if the value is null, but PropertyInfo.SetValue cannot set List<T> to T[].

**Comment by sungam3r** [comment]
@diouxis I added test to verify your issue but it passed. Feel free to modify it if I made something wrong. What version of package do you use?

**Comment by diouxis** [comment]
@sungam3r Thanks for the reply, I checked the test you built, we should explicitly pass null in the query to make this issue happen. 
In your test example, it should be
`getsome(input: { name: ""value"", ints: null })` 

Because this request will generate a null element in the dictionary of the related argument, and then it will drop into the following code.
https://github.com/graphql-dotnet/graphql-dotnet/blob/954ea4644295e6f34be68a73a1d8ee4bf27afe2a/src/GraphQL/ObjectExtensions.cs#L77-L87

as we can see, these process will generate an empty List<T> for _newArray_, and will directly return this empty list at Line 87 because _propertyValue_ is null. After that, will trigger the exception we finally can see.

**Comment by sungam3r** [comment]
>  process will generate an empty List for newArray, and will directly return this empty list 

This is fixed. No more unnecessary `List<T>` generation

**Comment by sungam3r** [comment]
@diouxis Can you please check it again with new nuget package?

**Comment by diouxis** [comment]
@sungam3r  sorry for the late reply, I was busy last month. Yes it does work well now with new preview package.
