### ISSUE TITLE
Mutations: How to map alternative name of a Field back to its original property

### ISSUE THREAD

**Issue by pulla2908** [graphql-dotnet/graphql-dotnet#1287]
Scenario: a property on a node was renamed from "FirstName" to "FName". To not break the interface I want to keep the old name for a certain time of periode. Because of that I apply an alternative name "FirstName" on the InputType, see sample below:

```
public class HumanInputType : InputObjectGraphType<Human>
{
        public HumanInputType()
        {
            Name = "HumanInput";
            Field(x => x.Name);
            Field(x => x.FName).Name("FirstName");
        }
}
```

From the client perspective it is working as expected. For above sample I get "Name" and "FirstName" as parameter.

From the resolver perspective I would have expected that "FirstName" gets mapped to "FName" on type "Human". But it is not. Further in the context.Arguments of "human" I see keys for "Name" and "FirstName" (same here). 

```
resolve: context =>
{
            var human = context.GetArgument<Human>("human");
            return data.AddHuman(human);
});
```

How can I map from "FirstName" to "FName" in a generic way? I thought this is done by the field configuration on the HumandInputType automatically.

**Comment by sungam3r** [comment]
Relates to #1107 ?

**Comment by sungam3r** [comment]
@pulla2908 merged!
