### ISSUE TITLE
Provide dynamically Input type and query type

### ISSUE THREAD

**Issue by temofeychik** [graphql-dotnet/graphql-dotnet#1288]
I need your help with solving my problem. I have simple object, like "Car" with only two fields "Id, Name". But in query and in mutation I need to provide dynamically fields which not in class.
```
   public class Car
   {
        public int Id { get; set; }
        public string Name { get; set; }
   }

   public class CarInputType : InputObjectGraphType<Car>
   {
        public CarInputType()
        {
            Name = "CarInput";
            Field(x => x.Id).Description("");
            Field(x => x.Name).Description("");
        }
   }
    public class CarType : ObjectGraphType<Car>
    {
        public CarType()
        {
            Name = nameof(Car);

            Field(x => x.Id, nullable: true).Description("");
            Field(x => x.Name, nullable: true).Description("");
        }
    }
```
mutation and query like this
```
mutation {
  CarPost(
    CarInput: {
      Name: "Vehicle"
      Wheels: 4
      Manufacture: "BMW"
        }
     )
  {
      Id
  }
}
```
```
query {
    CarInput: {
      Name: "Vehicle"
      Wheels: 4
      Manufacture: "BMW"
  }
}
```
Now I can't do it because I have validation error
```
{
  "error": {
    "errors": [
      {
        "message": "GraphQL.Validation.ValidationError: Argument "Car" has invalid value { 
         Name: "Vehicle", Wheels: "4", Manufacture: "BMW"}. In field "Wheels" and 
          "Manufacture": Unknown fields."
       }
      ]
   }
}
```
I need to put this fields by graphQl, resolve it and write to document-like DB.
For now I haven't found any solutions except turning off ArgumentsOfCorrectType() rule.
But this solution doesn't look fot me like a good one. Could you please provide me any advice how to reach my goal. Thanks for any help!

**Comment by sungam3r** [comment]
GraphQL API has no _dynamic fields_. You fully describe API. However, you can always use a field/argument of type `String` to pass any data structure in it, usually JSON.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
