### ISSUE TITLE
Providing JSON converter for ExecutionResult

### ISSUE THREAD

**Issue by gkfischer** [graphql-dotnet/graphql-dotnet#1292]
The docs about Error Handling (https://graphql-dotnet.github.io/docs/getting-started/errors/) say that the JSON formatter for ExecutionResult can be overwritten. Alas, I can't figure out how to do that. Are there any hints or docs available about that?

**Comment by sungam3r** [comment]
I also did not understand how to change it.

**Comment by sungam3r** [comment]
#1448 lets you do it!

**Comment by sungam3r** [comment]
@gkfischer After #1448 being merged you allowed to use your own JSON settings (resolver, converters). More info in #1495
