### ISSUE TITLE
where clause for NonNullGraphType<T>

### ISSUE THREAD

**Issue by diouxis** [graphql-dotnet/graphql-dotnet#1296]
https://github.com/graphql-dotnet/graphql-dotnet/blob/580af9e60b2fc2756a71d8c525b92a033f257ed4/src/GraphQL/Types/NonNullGraphType.cs#L5-L12

Can we update the where clause for this from GraphType to IGraphType? I think it is supported for the NonNullGraphType.
The reason is because I created some interface, and use DI to control to register different instance. However, I can't make these graph types to be non-nullable because of the where clause, they work fine with ListGraphType.

**Comment by sungam3r** [comment]
Can you show an example of your registration?

**Comment by diouxis** [comment]
I want to achieve something like **Schema stitching**, so I created following GatewayGraphType
```csharp
    public class GatewayGraphType<TSrouceGraphType>
         : ObjectGraphType<JObject>, IComplexGraphType<TSrouceGraphType>
         where TSrouceGraphType : IComplexGraphType
    {
        public GatewayGraphType()
        {
            TSrouceGraphType srouce = Activator.CreateInstance<TSrouceGraphType>();

            Name = srouce.Name;
            Description = srouce.Description;

            foreach (var field in srouce.Fields)
            {
                var midField = Field(field.Type,
                    name: field.Name,
                    description: field.Description,
                    deprecationReason: field.DeprecationReason,
                    resolve: ctx => ctx.Source.GetValue(field.Name, StringComparison.OrdinalIgnoreCase).ConvertFor(field.Type));
                midField.Metadata = field.Metadata;
            }
        }
    }
```
Then I just register  the following into internal api and gateway
```csharp
services.AddSingleton<IComplexGraphType<T>, TGraphType>();
```
```csharp
services.AddSingleton<IComplexGraphType<T>, GatewayGraphType<TGraphType>>();
```

I knew about I can create another converter in the GatewayGraphType, to make it able to handle object type when handle with IComplexGraphType field, but this will change a lot on current system, so for now I just update `NonNullGraphType<T>` to make it allow `IGraphType` as `T`

**Comment by Shane32** [comment]
Changed as requested for v4 @diouxis
