### ISSUE TITLE
ResolveFieldContext

### ISSUE THREAD

**Issue by eddyjl077** [graphql-dotnet/graphql-dotnet#1298]
Hi,

Is there any reason why we can't resolve service from the ResolveFieldContext.
Im trying to add dynamic type (CMS) for my project and dont like the fact i must resolve all my services in advance before event knowing what will be the query, maybe i dont get it at all.

Also, IFieldResolver could be async?

**Comment by sungam3r** [comment]
Actually you can. See #1160 and related discussions. 

Also now `Schema` explicitly implements `IServiceProvider` so you can do comething like 
```
((IServiceProvider)context.Schema).GetRequiredService<ISomething>()
```

> Also, IFieldResolver could be async?

I do not understand.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
