### ISSUE TITLE
Errors don't bubble up

### ISSUE THREAD

**Issue by acoder999** [graphql-dotnet/graphql-dotnet#1306]
Hi,

I am building an GraphQL API which uses as NonNullGraphType field. When the field resolver throws an ExecutionError (or adding an error to context.Errors) the field is null in the response. As far as I understand it, it should not allowed to be null, but the null should bubble up to the nearest nullable field. Am I doing something wrong, or is this just not implemented in the library?

Thank you for your help!

**Comment by sommarlov** [comment]
We are having this issue as well, seem to be fixed in 3.0!

**Comment by sungam3r** [comment]
@acoder999 , @sommarlov Can you please provide an example or (which is better) write a unit test to expose the problem?

**Comment by SimonCropp** [comment]
closing due to no response.
