### ISSUE TITLE
How to implement union field in .Net

### ISSUE THREAD

**Issue by dashapaster** [graphql-dotnet/graphql-dotnet#1307]
Hi, I an new in QraphQL, Help me please to understand how to implement union. 
 I created a NodeData class:
  ```
class NodeData : UnionGraphType
  {
      public NodeData() {
      Type<ConditionNodeType>();
      Type<DeviceNodeType>();
      ResolveType = value => null;
    }
  }
```
And NodeType, that use field NodeData : 

   ```
 public class NodeType : ObjectGraphType<Node>
    {
        public NodeType()
        {
            Field(x => x.NodeId);
            Field(x => x.Type);
            Field<NodeData>();
    }
    }
```
My question is: What kind of variable i need to add to class Node ? Is it Object type? Or I need to add two variables ConditionNode  and DeviceNode 
 
```
public class Node
    {
       public string Type { get; set; }
       public string NodeId { get; set; }
       public object NodeData{ get; set; }
OR:
       public ConditionNode ConditionNode { get; set; }
       public DeviceNode DevceNode { get; set; }
    }
```

**Comment by sungam3r** [comment]
Agree that [this docs](https://graphql-dotnet.github.io/docs/getting-started/unions) can not be called exhaustive.

`NodeData` should implement `ResolveType` or both `ConditionNodeType` and `DeviceNodeType` should implement `IsTypeOf`. Note that `IsTypeOf` is already [implemented](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/ObjectGraphType.cs#L23) for `ObjectGraphType<TSourceType>`.

I recommend you to read [IsTypeOf](https://graphql-dotnet.github.io/docs/getting-started/interfaces#istypeof) and [ResolveType](https://graphql-dotnet.github.io/docs/getting-started/interfaces#resolvetype) sections.

Also see [this union test](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Execution/UnionInterfaceTests.cs) as example. I hope this helps.

**Comment by sungam3r** [comment]
@dashapaster Did you manage to solve the problem?

**Comment by Pets** [comment]
Hi @sungam3r,

It would be awesome to put the link of the test in the documentation to help others find an example!

**Comment by sungam3r** [comment]
@Pets Done.
