### ISSUE TITLE
Help as I am stuck on implementing a generic wrapper (graphQL type) type that contains a ListGraphType (Generic)

### ISSUE THREAD

**Issue by shimuel** [graphql-dotnet/graphql-dotnet#1309]
## Summary
GraphQL - 2.4.0

Schema is generated as expected but the query returns a error,
"Expected value of type "Expected value of type..." at run time
Code posted @ [https://github.com/shimuel/GraphQLTest](https://github.com/shimuel/GraphQLTest)

Schema from Graphiql
-------------------------------------
orders(index: Int = nullsize: Int = null): PageIdGraphType

schema of PageIdGraphType in Graphiql,
count: Int!
hasNext: Boolean!
hasPrevious: Boolean!
index: Int!
items: [OrderType]
size: Int!

query ($index:Int!,$size:Int!) {
  orders(index:$index, size:$size){
    items{
      orderId,
      orderDate
    }
    index,
    size,
    count
  }
}

variables
-----------
{
  "index": 1,
  "size": 4
}

**Comment by sungam3r** [comment]
First try to do the same with the [latest preview](https://www.nuget.org/packages/GraphQL/3.0.0-preview-1268) graphql-dotnet package. Also please provide a full exception message text.

**Comment by shimuel** [comment]
Appreciate the response,

I ve updated the [project](https://github.com/shimuel/GraphQLTest) with GraphQL 3.0.0-preview-1268,

But still get the error,
`{
  "data": {
    "orders": null
  },
  "errors": [
    {
      "message": "Expected value of type \"PageIdGraphType\" for \"PageIdGraphType\" but got: System.Collections.Generic.List`1[GraphQLTest.Order].",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "orders"
      ]
    }
  ]
}`

**Comment by sungam3r** [comment]
I think you lost one level of data in the return type. How does `PageIdGraphType` look like? You return `List< Order>` instead of it in your resolver. Orders is not a list. Orders contains items field which is a list.

> Schema is generated as expected

Please provide your schema preferably in GraphTypes with appropriate resolvers or in SDL.

**Comment by sungam3r** [comment]
@shimuel Is this issue still actual for you?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
