### ISSUE TITLE
Ambiguous match found

### ISSUE THREAD

**Issue by flieks** [graphql-dotnet/graphql-dotnet#1313]
when overriding a base class ('question') which contains an enum called DataType
![image](https://user-images.githubusercontent.com/5032389/65603863-ba9e1c00-dfa6-11e9-87a3-b53694762584.png)
but then you would get an error
Ambiguous match found.
when casting the input type
var question = context.GetArgument<QuestionInput>("questionCreate");

**Comment by sungam3r** [comment]
@flieks I could not reproduce the error. What package version do you use? Try the latest preview package.

**Comment by flieks** [comment]
@sungam3r  i am using 2.4.0
i dont see latest preview in releases tab. How do i get it ? Is it stable ?

**Comment by sungam3r** [comment]
If you talk about Visual Studio nuget tab then set prerelease checkbox in UI. Current prerelease versions of graphql-dotnet and server projects are under active development.

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/GraphQL/3.0.0-preview-1268

**Comment by flieks** [comment]
@sungam3r but that package is for net core 3 ?
i am using net core 2.2

**Comment by sungam3r** [comment]
No, it is targeted for netstandard2.0

**Comment by flieks** [comment]
@sungam3r thanks alot
indeed with the latest preview it works fine and no issues upgrading
