### ISSUE TITLE
Consider being less strict with dependency versions

### ISSUE THREAD

**Issue by wirmar** [graphql-dotnet/graphql-dotnet#1316]
## Summary

In the newer versions of this library you increased the minimum version of it's dependencies (NewtonSoft.Json, System.Buffers, System.Reactive...). However as far as I can tell these upgrades are not needed for the code to function.
If a consumer of the GraphQL library wants the higher versions (for better performance etc.) they can always override the version that is being used by requiring the dependency with a higher on the root of the nuget dependency tree.
However a consumer of the GraphQL package might not want to upgrade the dependency all over their application, if they use it in other parts of the application in a different version. This is however not possible, since nuget will throw an error.

Therefore it would be nice if you would consider using a lower "minimum version" (https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards) for the dependencies where it is possible.

### Motivation

It would be include to use this library in existing applications.
Additionally I am facing some issues with the System.Buffers reference, related to the namespace also being in the .net core Framework, but in a lower version than requested by the GraphQL.dll (depending on the version of the .net core framework that it is being used). (I'm not completely sure with that problem, since I can't reproduce it in a simple example. However the problem went away when I built the GraphQL.dll myself with a lower minimum version for the System.Buffers nuget reference.)

**Comment by sungam3r** [comment]
> However as far as I can tell these upgrades are not needed for the code to function.

This is a very controversial issue, it is far from always known whether it should or should not be updated.

> If a consumer of the GraphQL library wants the higher versions (for better performance etc.) they can always override the version that is being used by requiring the dependency with a higher on the root of the nuget dependency tree.

In the same way, you can lower the version by explicitly installing the required dependency. The main thing is that later in the runtime there should be no errors (which is possible both when upgrading and when downgrading).

>  This is however not possible, since nuget will throw an error.

What error are you talking for? I specifically conducted an experiment with decreasing dependency and got error `NU1605` because the `TreatWarningAsErrors` setting was turned on. I suppressed this error using `NoWarn` and was able to publish the project. After that, I made sure that the output folder contains downgraded dll.

> Therefore it would be nice if you would consider using a lower "minimum version" for the dependencies **where it is possible**.

But how to determine this condition?

----
I understand what you are trying to achieve. But in reality the situation will not get better. In general, I do not think that trying to keep to the minimal versions of dependencies is of any tangible benefit.

**Comment by wirmar** [comment]
> What error are you talking for? I specifically conducted an experiment with decreasing dependency and got error NU1605 because the TreatWarningAsErrors setting was turned on. I suppressed this error using NoWarn and was able to publish the project. After that, I made sure that the output folder contains downgraded dll.

That is the error I was talking about. Simply ignoring all nuget errors/warnings does not seem like the wisest option to me.

> But how to determine this condition?

By running the unit tests, to see if they still work as intended?

#

The problem with System.Buffers is a special case in addition to the problems I mentioned, since it is a framework dependency. For reasons unknown to me this results in the GraphQL.dll wanting a different Version (4.0.2.0) of the System.Buffers.dll than is referenced via nuget (4.0.3.0):
![2019-09-26_13h08_21](https://user-images.githubusercontent.com/9307361/65767030-f2cf6700-e12c-11e9-99b8-0a4c5c87a99b.png)
In my application this leads to an error, when the Version 4.0.3.0 is put into the build folder (since that is the Version referenced from nuget), but the Application wants to load the Version 4.0.2.0.
This error might be somewhat obscure, since I cannot reproduce it in a simple example solution. However, I have already spent a day trying to work around the error and the only solution I have is ignoring the nuget errors and manually downgrading the System.Buffers package.

From my internet searches I can't really find a lot of information on how to reference System.* packages via nuget or otherwise and how the resolution of the DLL that includes the referenced System.* namespace work.. However, it seems that the way you reference System.Buffers isn't quite correct? Do you have more knowledge on that topic?

**Comment by sungam3r** [comment]
You can always use bindingredirects for assemblies. I repeat that such sort of errors can happen both with upgrade and downgrade. In general, the problem has no solution. The application may have different modules that present **conflicting requirements** for the versions of their dependencies.

> By running the unit tests, to see if they still work as intended?
The problem may be not with our code itself but in another library which is integrated in the final app.

So as you can always lower the version by explicitly installing the required dependency I think that it makes no sense to change something now.

**Comment by sungam3r** [comment]
> Simply ignoring all nuget errors/warnings does not seem like the wisest option to me.

I talked about only one.

**Comment by wirmar** [comment]
I added the System.Buffers downgrade in the following way (in case anyone else is facing the issue):
```
    <PackageReference Include="System.Buffers" Version="4.4.0">
      <!-- This downgrade is necessary to avoid runtime errors, when loading the assembly, see: https://github.com/graphql-dotnet/graphql-dotnet/issues/1316 -->
      <NoWarn>NU1605</NoWarn>
    </PackageReference>
```

This prevented the runtime errors when loading the System.Buffers reference I was facing before.

**Comment by wirmar** [comment]
Since a manual downgrade leads to having to supress a warning/error and a manual upgrade does not (see https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards, just specifying the version means "at least this version", not "exactly this version"), maybe you could consider at least being slower with upgrading in the future, when it is not for new features that make a dependency upgrade necessary?

**Comment by sungam3r** [comment]
> when it is not for new features that make a dependency upgrade **necessary**

Let's do a thought experiment. Imagine that the dependency version of some XXX package has changed from 1.0.0 to 1.0.1. No new functions have appeared, the author of the package just fixed the NRE in some method that occurs with some combination of factors. Is it worth our package, which depends on XXX, to update the dependency on version 1.0.1? Ask yourself what pros and cons we get by updating or not updating the dependency.

Pay attention to the emphasis on the word `necessary`. Necessity is quite difficult to determine. This concept can be interpreted in different ways.

**Comment by wirmar** [comment]
Yes it's not always obvious if an upgrade is necessary. I would just ask that you consider the implications that users of your library might face, when you upgrade a dependency.
I will close the issue then, thanks for your help with my issue :)

**Comment by sungam3r** [comment]
>  I would just ask that you consider the implications that users of your library might face, when you upgrade a dependency.

I keep this in mind, among other things.
