### ISSUE TITLE
HttpResponseStreamWriter presence

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1322]
This comes from #1318 

@joemcbride I see that `HttpResponseStreamWriter` class was copied from [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.httpresponsestreamwriter?view=aspnetcore-2.2). I do not know if there are any changes in the copied version. It seems to me that no. But in general it seems strange to see the mention of HTTP in this library, which is independent of any transport. I understand that the class has an auxiliary role, in fact, there is nothing specific for HTTP but only naming. Maybe rename it? I understand that it would be foolish to make dependency from one of ASP.NET Core assemblies. Copying a single small auxiliary class is certainly better.

I also discovered `namespace GraphQL.Http`:
\src\GraphQL\Http\DocumentWriter.cs
\src\GraphQL\Http\HttpResponseStreamWriter.cs
\src\GraphQL\Http\JsonArrayPool.cs

I suggest changing this namespace to `GraphQL` so as not to mislead anyone. The listed classes do not have any specific HTTP logic.

**Comment by joemcbride** [comment]
I agree with the `Http` verbiage, that could be removed.

**Comment by sungam3r** [comment]
**[reminder]** : close this issue after merging #1448

**Comment by sungam3r** [comment]
Resolved in #1448
