### ISSUE TITLE
Known issues documentation

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1326]
Add documentation (maybe like FAQ) about known issues:
1. ~AllowSynchronousIO: #1116, #1299, #1325, graphql-dotnet/server#271, #1317, graphql-dotnet/server#277~
2. ~DI: Scoped services issue: #1345, #1160 and related issues~
3. ~Auto generating classes and other stuff #576~
4. ~Auto registering output and input types #897~
5. Using derived graph types and cyclic dependencies #1010  -   **too narrow to document, cancelled**
6. ~File downloading #511~
7. ~Note about two authorization models - generic and ASP.NET Core graphql-dotnet/authorization#68 graphql-dotnet/authorization#74~
8. ~Note about descriptions inheritance #1004~ 
9. ~Recommendations to always use singleton schema and graph types over scoped ones #1011~
10. ~Many to many with dataLoader #1625~j
11. ~Subscription Authentication #1244~
12. ~Flags enums #1666~
13. ~`null` in scalars #1542~

**Comment by corstian** [comment]
On a related note; is there someone who can trigger a rebuild of the documentation? I have the feeling the currently published docs are several months behind.

**Comment by sungam3r** [comment]
Yes, docs are outdated. I think this is done intentionally so that the documentation matches the latest stable version 2.4.0.

**Comment by joemcbride** [comment]
>  I think this is done intentionally so that the documentation matches the latest stable version 2.4.0.

No, I would be fine deploying the latest.  The gatsby website needs to be updated before it can be deployed.

**Comment by sgebhardt** [comment]
> > I think this is done intentionally so that the documentation matches the latest stable version 2.4.0.
> No, I would be fine deploying the latest. The gatsby website needs to be updated before it can be deployed.

Can you tell what version the Docs are targeting? At least the part about `[dependency-injection](https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#dependency-injection)` seems not to target version 2.4.0.

**Comment by sungam3r** [comment]
Documentation targets `develop` branch, version 3.0.0-preview-xxxx.

**Comment by SimonCropp** [comment]
@sungam3r would a possible (more maintainable) solution to this be a GH label and point to a search query for open issues with that label?

**Comment by sungam3r** [comment]
I thought about it, but chose the option with a separate issue with a small description on each item.

**Comment by sungam3r** [comment]
I will be grateful if someone can contribute. @Shane32 ?

**Comment by Shane32** [comment]
Thank you yes. I will be working on this as well. Any pointers to issues that should be included in the upgrade guide, release notes, and known issues will be helpful

**Comment by sungam3r** [comment]
I tried to initially include them all in the summary. Of course there are many others, but it was simply unrealistic to track them all.

**Comment by sungam3r** [comment]
@Shane32 I think it should be in 3.0 milestone.

**Comment by Shane32** [comment]
I plan to push a draft of the documentation next weekend.  We just need to merge the data loaders by then.

**Comment by Shane32** [comment]
Flag enums has been added to the known issues list

**Comment by Shane32** [comment]
@sungam3r I think you will need to write a paragraph for each of the two remaining topics.  I don't understand them well enough.

**Comment by sungam3r** [comment]
OK but I won't have access to my PC all next week.

**Comment by sungam3r** [comment]
Finally!

**Comment by Shane32** [comment]
Ok to close this issue?

**Comment by sungam3r** [comment]
Oops. It seemed to me that I had already closed it. Work at night affects.
