### ISSUE TITLE
Schema Directives in GraphType first

### ISSUE THREAD

**Issue by mikelneo** [graphql-dotnet/graphql-dotnet#1328]
## Support of Schema Directives in GraphType first

Currently there is support of this directives in Schema First syntax (See this PR: #1172). But there is no way to set a directive on field definition using GraphType first syntax (https://github.com/graphql-dotnet/graphql-dotnet/issues/1002#issuecomment-537559320).

### Basic example

It can be implemented in a way:
```C#
public class SomeType : ObjectGraphType<Some>
{
	public SomeType()
	{
		Name = "Some";

		Field(p => p.SomeField).Description("Test").ApplySchemaDirective(...);
	}
}
```

**Comment by sungam3r** [comment]
@mikelneo Done. Use `ApplyDirective()` overloads on any schema element (any `IProvideMetadata`). This feature will be in v4. We are currently preparing the documentation and are going to release v4 within a week.
