### ISSUE TITLE
ObjectGraphType meaning

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1331]
I wonder about the need for an `ObjectGraphType` type:
```c#
public class ObjectGraphType : ObjectGraphType<object>
{
}
```
It is a degenerate type that does not carry any logic, the so-called type-alias. In general, such types are not recommended. Is there any reason to have this type explicitly given? I see that the vast majority of its use is in the test project. Is it possible to move it there, and in the main project use `ObjectGraphType<object>` instead?

**Comment by sungam3r** [comment]
@joemcbride Any thoughts?

**Comment by sungam3r** [comment]
Also the same thoughts about `InputObjectGraphType`.

**Comment by joemcbride** [comment]
Those types were the original ones provided by this project.  The generic type came later.  There are a lot of cases where you don’t care about the type, as proved by all those tests that don’t use one.  Removing those types is not a breaking change I want to make at this time.

**Comment by sungam3r** [comment]
> Those types were the original ones provided by this project. The generic type came later. 

Ah, now I get the point. Yes, in this case, of course, they must be preserved.
