### ISSUE TITLE
Schema directives and Introspection

### ISSUE THREAD

**Issue by mikelneo** [graphql-dotnet/graphql-dotnet#1332]
## Summary
There are directives wich affects schema (FIELD_DEFINITION, ARGUMENT_DEFINITION, etc.).
In spec https://graphql.github.io/graphql-spec/June2018/#sec-Type-System.Directives one of the reasons for its use is:
> Directives can also be used to annotate the type system definition language as well, which can be a useful tool **for supplying additional metadata** in order to generate GraphQL execution services, produce client generated runtime code, or many other useful extensions of the GraphQL semantics.

But there is currently no way of getting this type of directives in Introspection queries. For example I can define Schema:
```
type Query {
	hello: String @upper
}
```
But in `__Field` type there is no place for directives. Thus, the knowledge about which directive is applied to the field disappears.

There is discussion in progress https://github.com/graphql/graphql-spec/issues/300 about adding directives via introspection.

Is it possible to add directives info to `__Field` introspection type in graphql-dotnet? I don't see any restrictions about extending introspection types in spec (https://graphql.github.io/graphql-spec/June2018/#sec-Introspection).

### Environment (if relevant)

**Comment by sungam3r** [comment]
I agree. Introspection itself is a subset of the GraphQL schems and so has the same properties, namely the **possibility of evolution** - expanding the set of fields without disrupting existing clients. I still have to study this issue more carefully, re-read the specification and related tasks, but now I’m sure that we are on the right way. I will be back in a while with new comments.

**Comment by sungam3r** [comment]
Relates to #1328

**Comment by sungam3r** [comment]
Done in GraphQL.NET v4 and will be published in a week. See migration guide soon.
