### ISSUE TITLE
Graphql runtime schema with relationships

### ISSUE THREAD

**Issue by igorvuleta** [graphql-dotnet/graphql-dotnet#1334]
Hey there, I have previously on gitter searched for a dynamich schema solution, the thing is that I don't really want a dynamic schema instead I want a schema generated on runtime, which is in a generic fashion, 1 GraphqlType, 1 or more case resolvers and thats it. Essentially I have made it so far that I have a graphql schema running but the problems are navigational properties from my models, I can't get them to work properly whatever I do. 

I tried to isolate the problem and I found I am having type conversion mismatches when I spin up the schema. Essentially the schema is made out of metadata: 

Here I have the column metadata,
`
  //public class ColumnMetadata

    {
        public string ColumnName { get; set; }
        public string DataType { get; set; }
        public FieldBaseType BaseType { get; set; }
        public object Relation { get; set; }
    }
`
Q: should I perhaps change the DataType to a object? Is the Relation object actually wrong implemented?
The TableType constructor is looking like this, I am using some TableMetadata and essentially looping through fields to initalise the fields from the GraphType, later on in a method I create graphqType fields, i.e. :

` 
     

            if (field.Relation != null)
            {

                var relatedObject = Tabledict[field.DataType];
                var relatedTable = new TableType(relatedObject, Tabledict);
                var listType = new ListGraphType(relatedTable);
                graphqlType = relatedTable.GetType();

                FieldType columnField = Field(
                    graphqlType,
                    relatedObject.TableName
                    );

                columnField.Resolver = new NameFieldResolver();

            }
            else
            {
                var graphQLType = (ResolveColumnMetaType(field.BaseType)).GetGraphTypeFromType(true);
                var columnField = Field(
                    graphQLType,
                    field.ColumnName
                );

                columnField.Resolver = new NameFieldResolver();
                FillArgs(field.ColumnName);
            }
            
        } `
in this method the magic happens, the else block works like a charm, but the if part is a little bit mystery to me, I can access it but when I get to making a new tableType I just get a null returned, and I don't know why, I only speculate it's a bad type conversion somwhere and thats why it's not working. Note I don't work with any popular orm so any also any pure reader writer advices are welcome(for type conversion that is)

**Comment by isaksky** [comment]
I'm also constructing a schema at runtime, and was able to get it to work. I did it in 3 phases:

- Phase 1 - just register the type containers without members (because they may point to things that have not been initialized yet)
- Phase 2 - add members (e.g., fields) to the types
- Phase 3 - add all top level fields. (All types are now initialized.)

You also need to add "Query" and "Mutation" fields to the schema at the beginning, (and register them), or it will not work (bug).

**Comment by sungam3r** [comment]
> You also need to add "Query" and "Mutation" fields to the schema at the beginning, (and register them), or it will not work (bug).

Can you show in more detail what you call a bug?

**Comment by isaksky** [comment]
@sungam3r I hade code like this:

```fsharp
  let schema = new GraphQL.Types.Schema()

  // 1 -  Create ObjectTypes, Enums, etc
  // ...
  
  // 2 - Set up the root fields
  let query = GraphQL.Types.ObjectGraphType(Name = "Query")
  schema.RegisterType(query)
  schema.Query <- query
  let mutation = GraphQL.Types.ObjectGraphType(Name = "Mutation")
  schema.RegisterType(mutation)
  schema.Mutation <- mutation

  for f in fields do
    let f = createField f schema
    query.AddField(f) |> ignore
      
  for f in mut_fields do
    let f = createField f schema
    mutation.AddField(f) |> ignore
```

That kind of code led to this error upon starting GraphiQL:

```
Error: Invalid or incomplete schema, unknown type: Query. Ensure that a full introspection query is used in order to build a client schema.
```

Moving 2 before 1 fixed that problem.

**Comment by sungam3r** [comment]
Roughly understandable. It is better to make a separate issue to keep this issue focused on relationships. To use introspection, one can write a unit test and try to reproduce the error without GraphiQL.

**Comment by sungam3r** [comment]
Closed due to inactivity. I hope v4 release will fix some bugs mentioned here.
