### ISSUE TITLE
Unmapped selection Field

### ISSUE THREAD

**Issue by ksyDeveloper** [graphql-dotnet/graphql-dotnet#1335]
## Summary
I tried to run the example (Hello World) but I could able get the result and the error is Unmapped selection field.  
## Relevant information
But when I used the code from github (graphql-dotnet), there is no error for Hello World Example. But that didn't work with [API Development in .NET with GraphQL example ](https://www.lynda.com/NET-tutorials/API-Development-NET-GraphQL/664823-2.html) from Glenn Block. It has unfound IDependencyResolver error.

### Environment (if relevant)
Windows 10,
VS 2019
Installed GraphQL 2.4 from nuget.

**Comment by sungam3r** [comment]
@ksyDeveloper Is this issue still actual for you? You can check GraphQL.Harness example in this repo or one in the [server repo](https://github.com/graphql-dotnet/server).

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
