### ISSUE TITLE
FuncDependencyResolver / .net core 3.0

### ISSUE THREAD

**Issue by StefanKoenigMUC** [graphql-dotnet/graphql-dotnet#1336]
Hi all,

i'm trying to setup GraphQl with .net core 3.0, unfortunately I'm failing during setup of singletons/services, as I'm not able to setup my schema.

 ´´´
services.AddSingleton(s => new FundsSchema(new FuncDependencyResolver(type => (IGraphType)s.GetRequiredService(type))));
´´´

As there is no available import for FuncDependencyResolver (and I'm unable to locate a package containing it).

Do you have any advice, how to setup Graphql with .net core 3.?

Thanks in advance!

**Comment by sungam3r** [comment]
You can find actual docs about DI [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/dependency-injection.md). Just remove aforementioned line of code.

**Comment by StefanKoenigMUC** [comment]
thanks - finally found a solution :-) [used preview version instead of stable]
