### ISSUE TITLE
LifetimeScope middleware

### ISSUE THREAD

**Issue by dietergoetelen** [graphql-dotnet/graphql-dotnet#1346]
I'm using `Mediatr` together with `Graphql.NET`. I've faced some issues regarding lifetimeScope which I could solve by creating a new scope within each Field I resolve:

```
FieldAsync<Type, Type>("property")
   .ResolveAsync(async ctx => 
   {
      using (var scope = lifetimeScope.BeginLifetimeScope()) 
      {
         var mediator = scope.Resolve<IMediator>();
         // use mediator
      } 
   })
```

Next to this I also need to set the `UserContext` to a service I use in my application: 
```
FieldAsync<Type, Type>("property")
   .ResolveAsync(async ctx => 
   {
      using (var scope = lifetimeScope.BeginLifetimeScope()) 
      {
         var mediator = scope.Resolve<IMediator>();
         var userService = scope.Resolve<ISetUser>();
         userService.SetUser(ctx.UserContext);
         // use mediator
      } 
   })
```

I was hoping I could abstract the above logic by using `FieldMiddleware`. The problem with the `FieldMiddleware` is that my scope is disposed on the second run. I thought it would share the same `Scope` as the `ResolveAsync` method, but it looks like it's not..

```
executionOptions.FieldMiddleware.Use(next =>
{
    return async context =>
    {
        using (var scope = _scope.BeginLifetimeScope())
        {
                var mediator = scope.Resolve<IMediator>();
                var userService = scope.Resolve<ISetUser>();

                if (context.FieldDefinition.Metadata == null)
                {
                    context.FieldDefinition.Metadata = new Dictionary<string, object>();
                }

                if (!context.FieldDefinition.Metadata.ContainsKey("Mediator"))
                {
                    context.FieldDefinition.Metadata.Add("Mediator", mediator);
                }
                ...
        }
    }
}
```

If I run the above code once, everything is working fine. If I run it for the second time `_scope.BeginLifetimeScope()` throws an exception. `Scope already disposed`.

Any idea or help to create a middleware for a new lifetimescope would be appreciated.

**Comment by sungam3r** [comment]
What is `_scope`? What is result of `BeginLifetimeScope()`? You can do anything in your middleware. This is designed as arbitrary user code that executes when resolving each field.

> The problem with the FieldMiddleware is that my scope is disposed on the second run.

I understand that the control over the creation and destruction of your scopes is completely in your hands. If so, then you just have to choose the appropriate way to manage your scopes.

**Comment by dietergoetelen** [comment]
Hi @sungam3r thanks for the answer,

I'm using `Autofac` as container. `_scope` is of type `ILifetimeScope`. I basically do the same in the middleware as in the resolve function. 

If I move the scope creation from the resolve function to the middleware I get scope already disposed error.

**Comment by sungam3r** [comment]
>  I thought it would share the same Scope as the ResolveAsync method

Middleware wraps ResolveAsync method. It is how it was designed.

**Comment by sungam3r** [comment]
It is from FieldMiddlewareBuilder:
```c#
public void ApplyTo(ISchema schema)
        {
            // allocation free optimization if no middlewares are defined
            if (!Empty)
            {
                foreach (var complex in schema.AllTypes.OfType<IComplexGraphType>())
                {
                    foreach (var field in complex.Fields)
                    {
                        var resolver = new MiddlewareResolver(field.Resolver);

                        FieldMiddlewareDelegate app = Build(resolver.Resolve);

                        field.Resolver = new FuncFieldResolver<object>(app.Invoke);
                    }
                }
            }
        }
```

**Comment by sungam3r** [comment]
@dietergoetelen Now FieldMiddleware supports DI and scopes. See [documentation](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/field-middleware.md).
