### ISSUE TITLE
Auto Registering graph type for input types

### ISSUE THREAD

**Issue by jonathan82** [graphql-dotnet/graphql-dotnet#1353]
Hi, I was wondering how I can have an auto-registering graph type for input types?  I see there's a type for AutoRegisteringObjectGraphType<> but nothing for the input side.  Thanks

**Comment by joemcbride** [comment]
You can look at the code of `AutoRegisteringObjectGraphType<>` as an example and write your own class that does the same thing for input types.

**Comment by jonathan82** [comment]
That's what I ended up doing. Thanks!
