### ISSUE TITLE
NameFieldResolver throws when source is a value type.

### ISSUE THREAD

**Issue by andykernahan** [graphql-dotnet/graphql-dotnet#1354]
## Description

An exception is thrown when attempting to resolve a property of a value type as the signature of the delegate created by `DelegateHelper` does not match that of the target method; this is because the type of the hidden this parameter is actually `TTarget&` (i.e. `IsByRef`).

This issue is inadvertently fixed by graphql-dotnet#1330.

### Steps to reproduce

```csharp
public sealed class ValueTypeTests : QueryTestBase<ValueTypeSchema>
{
    [Fact]
    public void can_resolve_property_on_value_type()
    {
        var query = "query { seconds }";
        var expected = "{ seconds: 42 }";
        AssertQuerySuccess(query, expected, root: TimeSpan.FromSeconds(42));
    }
}

public sealed class ValueTypeSchema : Schema
{
    public ValueTypeSchema()
    {
        var query = new ObjectGraphType<TimeSpan>();
        query.Field<IntGraphType>(
            name: "seconds"
        );
        Query = query;
    }
}
```

### Expected result

Should resolve property value.

### Actual result

Throws:
> System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type. 

### Environment

GraphQL v2.4.0 (and present in 02874de), macOS 10.14.6

**Comment by sungam3r** [comment]
@andykernahan Thanks for the test.
