### ISSUE TITLE
DateGraphType as Argument

### ISSUE THREAD

**Issue by alexmcmillan** [graphql-dotnet/graphql-dotnet#136]
The [description](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/DateGraphType.cs#L14) says to use ISO-8601 timestamps to represent `Date`s but it doesn't appear possible to pass a `Date` as an argument to a query.

EG: this Query (using GraphiQL)

```graphql
query ($authorId: String!, $fromUtc: Date!, $untilUtc: Date!) {
  author(id: $authorId) {
    id
    posts(fromUtc: $fromUtc, untilUtc: $untilUtc) {
      id
    }
  }
}
```

with the arguments 

```json
{
  "authorId": "879461",
  "fromUtc":"2016-06-27T00:00:00.000Z",
  "untilUtc":"2016-06-29T00:00:00.000Z"
}
```

produces the result

```json
{
  "errors": [
    {
      "message": "Variable '$fromUtc' expected value of type 'Date'."
    }
  ]
}
```

With a `Field` on my `Author` like so:

```cs
Field<ListGraphType<PostType>>(
    "posts",
    "Posts made by this Author",
    new QueryArguments(
        new QueryArgument<DateGraphType>
        {
            Name = "fromUtc",
            Description = "The inclusive lower-bound DateTime of the posts to retrieve."
        },
        new QueryArgument<DateGraphType>
        {
            Name = "untilUtc",
            Description = "The exclusive upper-bound DateTime of the posts to retrieve."
        }
    ),
    context => p.Post.GetPosts(
        (Author)context.Source,
        context.Argument<DateTime>("fromUtc"),
        context.Argument<DateTime>("untilUtc")
    )
);
```

I believe it is failing [this check](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L467) in the `DocumentExecuter`.

**Comment by tlil87** [comment]
It seems to be because you're mixing non-nullable and nullable types. I.e. the argument is of type (nullable) `Date`, but you're passing in `Date!`. Could you try changing one of the two so that they are consistent and see if that works?

**Comment by alexmcmillan** [comment]
Sorry that was an artifact of my mucking around - changing from `Date!` to `Date` in the query makes no difference..

**Comment by alexmcmillan** [comment]
The request body generated by GraphiQL - you can see the `fromUtc` and `untilUtc` fields contain valid ISO8601 strings

```json
{
    "query" : "query ($authorId: String! $fromUtc:Date $untilUtc:Date) {\n  author(id: $authorId) {\n    id\n    posts(fromUtc: $fromUtc, untilUtc: $untilUtc) {\n      id\n    }\n  }\n}\n",
    "variables" : "{\n  \"authorId\": \"879461\",\n  \"fromUtc\":\"2016-06-27T00:00:00.000Z\",\n  \"untilUtc\":\"2016-06-29T00:00:00.000Z\"\n}"
}
```

**Comment by joemcbride** [comment]
Seeing if I can write a unit test to confirm this.

**Comment by joemcbride** [comment]
@alexmcmillan Test I wrote is passing, so I may have something different than your setup.  Couple questions for you:

1. What version you are using?
2. How are you passing the input variables to the executor?  Are you using the `.ToInputs()` extension method?
3. Are you able to write a unit test that exhibits this behavior?

**Comment by alexmcmillan** [comment]
1. I'm working with a clone of your current master branch
2. I am just incrementally modifying the types in `GraphQL.StarWars` (learn by doing!)
3. I added this field to `HumanType` (on a freshly-checked-out copy of master without any of my changes):

```c#
Field<StringGraphType>(
    "datetest",
    "Testing whether a date can be passed as an argument",
    arguments: new QueryArguments(
        new QueryArgument<DateGraphType>
        {
            Name = "theDate",
            Description = "French Toast"
        }
    ),
    resolve: context => "I am a lineman for the county!!!  " + context.Argument<DateTime>("theDate").ToString()
);
```

then fired the query 

```graphql
query getHuman($idValue: String! $theDate: Date) {
  human(id: $idValue) {
    datetest(theDate: $theDate)
  }
}
```

with arguments

```json
{
  "idValue": "3",
  "theDate": "2016-08-16T22:51:10.762Z"
}
```

and received the response:

```json
{
  "errors": [
    {
      "message": "Variable '$theDate' expected value of type 'Date'."
    }
  ]
}
```

**Comment by joemcbride** [comment]
Yes, that doesn't fail for me.  Are you sure you are running the latest master?

This seems similar to https://github.com/graphql-dotnet/graphql-dotnet/issues/118

**Comment by alexmcmillan** [comment]
It does seem similar - but that appears to have been resolved?

I am working in `Visual Studio 2015` v14.0.25123.00 u2 with `.net` v4.6.01038 on a Windows 10 machine.

1. Destroyed my local copy of `graphql-dotnet`
2. Freshly cloned `git@github.com:graphql-dotnet/graphql-dotnet.git`
3. Built the frontend with `npm install` and `npm start` (using `Node` v6.3.1, `npm` v3.10.3)
4. Opened `GraphQL.sln` in Visual Studio, set the startup project to `GraphQL.GraphiQL`
5. Started the solution in debug mode, GraphiQL opened in `Chrome` v52.0.2743.116 m (latest) with the default query showing (droid with id 3 etc)
6. Ran the default query and saw the expected results
7. Stopped Visual Studio
8. Added the `Field` from above to `HumanType`
9. Started the Solution again, `GraphiQL` appeared in Chrome
10. Updated the query and the arguments to those above
11. Ran the query and got the exact same (failing) result

Can you see anything that could be amiss?  How does your environment differ from mine?

**Comment by joemcbride** [comment]
I didn't go through GraphiQL, so I will test it that way.

**Comment by alexmcmillan** [comment]
The problem is [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/DateGraphType.cs#L36).  

Passing `CultureInfo.InvariantCulture` causes the date string (which by this stage is in the form `"16/08/2016 10:51:10 PM"`) to fail to parse.

Changing this to `null` or `CultureInfo.CurrentCulture` fixes the issue.

I am in New Zealand, and my timezone is NZST (GMT + 12)... I wonder if that has something to do with it?

**Comment by joemcbride** [comment]
That would do it, and would explain why it doesn't fail for me - I'm running in PST.

**Comment by alexmcmillan** [comment]
Is changing the second argument to `CultureInfo.CurrentCulture` an acceptable solution?  I can issue a PR

**Comment by joemcbride** [comment]
That works in my time zone as well, so seems like that should be acceptable.  Thanks for tracking that down!

**Comment by alexmcmillan** [comment]
No problem!  Glad I could contribute to this awesome project :)
