### ISSUE TITLE
Code Style Rules

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1361]
There is already .editorconfig file in this repo. This issue is about defining a clear set of formatting rules (and there are a lot of available rules) and stick to it.

 As an example (starting point), we can take [this](https://github.com/DbUp/DbUp/blob/master/src/.editorconfig).

**Comment by RehanSaeed** [comment]
I maintain a very generic `.editorconfig` file for .NET developers. Check it out:

https://github.com/RehanSaeed/EditorConfig

**Comment by joemcbride** [comment]
Is there a way to enforce those rules at build time?

**Comment by sungam3r** [comment]
It is a good question. That was the first question I had when I looked at editorconfig docs.
Possibly relates to dotnet/roslyn#33558
