### ISSUE TITLE
Hide requested type by client

### ISSUE THREAD

**Issue by gabrielemilan** [graphql-dotnet/graphql-dotnet#1365]
Hi, there is a way to remove the requested fields by client?

**example**
request:
`query {
  users {
    id
    name
  }
}`

response:
`{
  "data": {
    "users": [
      {
       "name": "User 1"
      },
      {
       "name": "User 2"
      }
    ]
  }
}`

Thanks.

**Comment by sungam3r** [comment]
I did not understand you. What does it mean to "remove"?

**Comment by gabrielemilan** [comment]
> I did not understand you. What does it mean to "remove"?

I mean that if the client make the request with the "id" and "name", I want to return only name, based on authorization for example.

**Comment by sungam3r** [comment]
You can just return `null` if your `name` field is nullable. You cannot remove field at all, this will break the client request schema. Also you can return specific error message about authorization in `errors`. See this section of spec: https://graphql.github.io/graphql-spec/June2018/#sec-Errors-and-Non-Nullability

**Comment by sungam3r** [comment]
Closed as answered.
