### ISSUE TITLE
Dynamically creating ListGraphType<T> Causes NRE

### ISSUE THREAD

**Issue by floyd-may** [graphql-dotnet/graphql-dotnet#1369]
## Description

In a situation where I need to dynamically generate and instantiate a `ListGraphType<T>`, its `ResolvedType` property winds up being null and causing a `NullReferenceException` [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/v2.4.0/src/GraphQL/Types/GraphTypesLookup.cs#L314).

It seems that the mutability of the `FieldType` class and its interplay with `TypeCollectionContext` is falling down somehow?

### Steps to reproduce

When creating a `ComplexGraphType`, set the `ResolvedType` of one of its `FieldType` instances dynamically to something like `(IGraphType)Activator.CreateInstance(typeof(ListGraphType<>).MakeGenericType(typeof(NonNullGraphType<IntGraphType>)))`.

The lib that uses this is open-source; the commit that I used to work around this problem is here:
https://github.com/asemio/otto-the-geek/blob/efbff44ae1488a9645bcf562efb8058776140524/OttoTheGeek/Internal/PreloadedListResolverConfiguration.cs#L22-L26

### Expected result

This works

### Actual result

NRE on line referenced above

### Environment

Version 2.4.0

**Comment by sungam3r** [comment]
Could you please try to reproduce the error using the latest preview version of the package? Or even better if you can create a minimal unit test to confirm bug.

**Comment by floyd-may** [comment]
It appears that the issue is not present in 3.0.0-preview-1271; however, I did see some inconsistencies in places where sometimes the `name` field for the `NotNull` type comes back as `"NotNull"` and sometimes as `null`. Similar issue for `List`. Until that can get worked out, I don't feel comfortable about upgrading to 3.0 yet.

**Comment by sungam3r** [comment]
Both `NotNull` and `List` modificator types must not have a name (it always should be `null`). Spec explicitly requires that. This naming issue was fixed in #1340. Try the latest preview version from myget feed: https://github.com/graphql-dotnet/server/blob/develop/nuget.config

**Comment by floyd-may** [comment]
Confirmed working as expected against master branch (b13b1ef). Thanks!
