### ISSUE TITLE
Send Tracing Data

### ISSUE THREAD

**Issue by CyrilleFormont** [graphql-dotnet/graphql-dotnet#1372]
Hi guys,

Regarding this topic : 
https://github.com/graphql-dotnet/graphql-dotnet/issues/381

And this documentation : 
https://www.apollographql.com/docs/references/setup-analytics/#graph-manager-reporting-endpoint

We tried to enable the tracing for GraphQL .NET Project on Apollo Engine. 
Did somebody already achieve it ? We are using the package 2.4.0.

**Comment by joemcbride** [comment]
Have you followed these docs for this project?

https://graphql-dotnet.github.io/docs/getting-started/metrics

**Comment by sungam3r** [comment]
@CyrilleFormont Yes, I use it. Use preview packages for this project and server. Several bugs have been fixed since version 2.4.0.

**Comment by CyrilleFormont** [comment]
Thanks for your quick answers.

Indeed @joemcbride , I followed it and now my Perf Array is now correctly populated , I tried to send via HTTP Post the content of this array by GZipping it, to Apollo Engine without success.

Thanks @sungam3r for your suggestion but as the project must be in production soon we prefer to work with Release version, we avoid to use any Preview. Does it means that we can't use 2.4.0 to send our metrics to Apollo Engine ?

**Comment by sungam3r** [comment]
> we prefer to work with Release version

If you only knew how many bugs there are! And they were fixed in the preview versions. I have been using the preview version in the production for a very long time. No problems. In version 2.4.0 I encountered errors at almost every step. I admit that in the preview version quite often backward incompatible changes occur.

> Does it means that we can't use 2.4.0 to send our metrics to Apollo Engine ?

I can only say that this version will not be patched. All work is going on master branch of 3.0.0 version.

**Comment by CyrilleFormont** [comment]
Hi @sungam3r , 
I understand your point of view, we'll try to stick with the 2.4 (at least for our first release). However, did you manage to send your metrics to Apollo Server ? If "Yes", how did you do it ? Through an HTTP Request post with the Perf array as body ?

**Comment by sungam3r** [comment]
@CyrilleFormont Excuse me. I read the link that you gave and realized that I did not answer at all about what you asked. We really use metrics, they are enabled by default but these metrics are in no way aggregated or sent to the Apollo Engine cloud service. They are for internal use only. GraphQL-dotnet has support for these metrics, also you can use [server project](https://github.com/graphql-dotnet/server) with ASP.NET Core middleware. But note that some errors [were also fixed](graphql-dotnet/server#254) there and it is in the 3.5.0-preview version too. You can extend `DefaultGraphQLExecuter` or `GraphQLHttpMiddleware` to intercept `ExecutionResult` with metrics inside and buffer/send them to external Apollo endpoint.
