### ISSUE TITLE
Few questions about DataLoader

### ISSUE THREAD

**Issue by jsp-up** [graphql-dotnet/graphql-dotnet#1375]
**This issue participates in bounty program, see https://github.com/graphql-dotnet/graphql-dotnet/blob/master/BOUNTY.md**

**bounty amount: $60**

Tasks to be done:
1. Add documentation in dataloader.md addressing https://github.com/graphql-dotnet/graphql-dotnet/issues/1375#issuecomment-785427086.

[ORIGINAL POST BELOW]

## Summary
Hello, I've got 2 little questions (I didn't find the answers in the doc.)

1. I'd like to know if it's possible to pass some parameters to the dataloader like this :
```
accessor.Context.GetOrAddCollectionBatchLoader<decimal, MyEntity>("FuncName", repository.FuncName(myFilters));
return loader.LoadAsync(context.Source.Id);
```

2. When do you have to use _GetOrAddCollectionBatchLoader_ and _GetOrAddBatchLoader_ ? 
Is _GetOrAddCollectionBatchLoader_ used for one to many relationships and _GetOrAddBatchLoader_ for one to one relationships ?

Sorry if these are obvious questions but i'm relatively new to GraphQL and C# ^^

**Comment by jsp-up** [comment]
Thanks, still waiting an answer for the second question :+1:

**Comment by sungam3r** [comment]
I must say that I don’t have an answer, because I didn’t understand the DataLoader implementation well enough.

**Comment by STRATZ-Ken** [comment]
Your answer to number 2 is correct.  One to many relationships or one to one.

**Comment by flieks** [comment]
And what about many to many relations (with join table). How can this be achieved? 

For example i have a model `Contact` that can have multiple Companies and a Company can have multiple contacts.
Going from CompanyGraphType:
```
Field<ListGraphType<ContactGraph>, IEnumerable<Contact>>()
                 .Name("Contacts")
                .ResolveAsync(context =>
                {
                   try
                   {
                       var userContext = context.UserContext as MyUserContext;
                       var loader = accessor.Context.GetOrAddCollectionBatchLoader<Guid, Contact>("GetContactsFromCompanyBatch", userContext.ContactManager.GetContactsFromCompanyBatchAsync);

                       return loader.LoadAsync(context.Source.Id);
                   }
                   catch (Exception ex)
                   {
                       throw ex;
                   }
               });
```
but i have no companyId i can return in the lookup because there are multiple:
![image](https://user-images.githubusercontent.com/5032389/77480087-53f89e80-6e21-11ea-9161-7a4004dc9493.png)

**Comment by sungam3r** [comment]
@Shane32 Does our documentation answer these questions?

**Comment by Shane32** [comment]
I can take a look. I did not modify the data loader accessor with my overhaul, or add any documentation pertaining to its use. (Nor do I use it in my code.)

**Comment by Shane32** [comment]
There does not appear to be sufficient documentation to explain the difference between `GetOrAddCollectionBatchLoader` and `GetOrAddBatchLoader`.

The former is for a dataloader that returns a list of values for each key (one-to-many relationship).  The second returns a single value for each key (one-to-one or many-to-one relationship).

**Comment by sungam3r** [comment]
Maybe rename ?

**Comment by kieranbenton** [comment]
Just to agree - right now its hard to find any reference to how all of the different GetOrAddXXX extension methods are different to each other.

**Comment by macco3k** [comment]
I've opened a PR (it's my first ever PR on github, so bear with me) to at least explain the difference reported by @Shane32. Hopefully this helps 👍

**Comment by Shane32** [comment]
Congrats on your first PR @macco3k 🥇  and thanks for issuing a PR towards fixing our documentation!  I've marked this bounty as 'in progress' pursuant to our bounty program.  Please see further comments within the PR.

**Comment by Shane32** [comment]
Thanks @macco3k for your assistance in closing this issue!  Please submit an expense for $60 through OpenCollective via this link to collect this bounty:

- https://opencollective.com/graphql-net/expenses/new

**Comment by Shane32** [comment]
@macco3k Please confirm your username of Daniele on OpenCollective so I can approve the expense.

**Comment by macco3k** [comment]
How do I do that?

**Comment by Shane32** [comment]
Just verbally confirm — say yes here

**Comment by macco3k** [comment]
Yes I confirm my username on OpenCollective is Daniele
