### ISSUE TITLE
FieldAsync on GetOrAddBatchLoader with EntityFramework

### ISSUE THREAD

**Issue by STRATZ-Ken** [graphql-dotnet/graphql-dotnet#1377]
Hello,

I have a very complex method that takes a lot of time to run. (1 sec).  This data is share among a GraphQL Field.  Some data here, some there.  I am trying to us `GetOrAddBatchLoader` to `LoadAsync` then take the results and return it.

Example

```
var dataTask = loader.LoadAsync(fieldContext.Source.Id);
var data = await dataTask;
return data.SomeObjectWithin;
```

The issue is, if I call it within a `FieldAsync` with a Scoped EntityFramework DbContext, I am getting a the common EntityFramework DbContext threading error.  If I run it in a `Field` and then use `dataTask.Result`, well, bad idea and it just does not work.

Is there another way?

**Comment by sungam3r** [comment]
In fact, the question boils down to how to use single `DbContext` in a parallel access scenario.
The answer is - it is impossible. Either use different instances of `DbContext` (transient/create manually), or execute the code sequentially, or don’t use `DbContext` at all.

**Comment by STRATZ-Ken** [comment]
I mean ya we could switch to a transient subcontract, but not sure that should be needed. 

Is there any examples of how to execute it sequentially out there?  Would it be the same if we have multiple fields doing the same thing?

**Comment by sungam3r** [comment]
You need to set up your custom `DocumentExecuter ` and override method which select execution strategy - https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L276

Change `ParallelExecutionStrategy` to `SerialExecutionStrategy`.

**Comment by STRATZ-Ken** [comment]
No other way to go about it though?  Seems like switching this could add a lot of un-needed time.  I think it would be better to switch to Transient if it came switching to SerialExecution.

**Comment by sungam3r** [comment]
Of course, sequential execution will be slower than parallel.
