### ISSUE TITLE
Subscriptions Do Not Resolve All Fields Like Queries/Mutations

### ISSUE THREAD

**Issue by kmanev073** [graphql-dotnet/graphql-dotnet#1381]
To make it easier to understand I am directly posting some code. 

Suppose I have this class:

```
    public class ProductionPlan
    {        
        public Guid OrderId { get; set; }

        public int ModelIndex { get; set; }
        
        public double ModelExecutorPrice { get; set; }
    }
```
That's fine, just a simple class named ProductionPlan that has some primitive properties.
I have this GraphQL Type that I use for my queries and mutations:

```
    public ProductionPlanType(IOrderRepository orderRepository)
        {
            Name = "ProductionPlan";
            Description = "ProductionPlan model.";

            this.Field<OrderType>(
                name: "Order",
                resolve: context =>
                {
                    return orderRepository.ReadByIdAsync(context.Source.OrderId);
                });

            this.Field(cp => cp.ModelIndex, true)
                .Description("The index of the production plan's model'.");
            
            this.Field(cp => cp.ModelExecutorPrice, true)
                .Description("The price of the production plan's model executor'.");
        }
```
That's also super cool, I have my primitive properties, and I also included one extra property that is resolved at the time of querying.

When I make a query or mutation that **Order** property works just fine and I get my order.

**However** when I create a subscription, that **Order** propery is always **null**. For example: Everytime when there is a new ProductionPlan created, I want to send it with that **Order** field resolved but the resolve method in the type is not called...

This is how I create my subscriptions:

```
    public Subscription()
        {
            Name = "Subscription";
            Description = "Subscription.";

           this.FieldSubscribe<ProductionPlanType>(
                "productionPlanCreated",
                "New production plan created!",
                resolve: context => context.Source,
                subscribe: context => this.messageService.GetMessage());
        }
```
where messageService is implementing this interface:
```
    public interface ISubscriptionMessageService
    {
        ProductionPlan AddMessage(ProductionPlan model);

        IObservable<ProductionPlan> GetMessage();
    }
```

Hope that this can fixed or if we can find a workaround. Any help or suggestion is appreciated.

**Comment by sungam3r** [comment]
@Shane32 This one may be related to our latest changes. Do you have any comments?

**Comment by Shane32** [comment]
This is likely due to attempting a subscription request over HTTP GET/POST rather than WebSockets.  In versions prior to GraphQL.NET Server 7, this was allowed, but not functional and would return `null` as seen above.  In GraphQL.NET Server v7, an error message will be returned to the caller explaining the error.

See:
- https://github.com/graphql-dotnet/server/blob/master/src/Transports.AspNetCore/HttpGetValidationRule.cs
- https://github.com/graphql-dotnet/server/blob/master/src/Transports.AspNetCore/HttpPostValidationRule.cs

There could be other reasons of course, but it would be hard to diagnose without further information.  Please re-open if needed.
