### ISSUE TITLE
Unwanted `(= null)` for QueryArguments

### ISSUE THREAD

**Issue by isaksky** [graphql-dotnet/graphql-dotnet#1386]
## Description

GraphQL.Net is adding a default value (null) to an argument when none has been asked for.

### Steps to reproduce

I don't think this matters, but I constructed the schema at runtime, using code like this:

```
let f = GraphQL.Types.FieldType(Name = "someFieldName")
let a = GraphQL.Types.QueryArgument(typ)
a.Name <- "someArgName"
f.Arguments <- GraphQL.Types.QueryArguments([ a ])
```

### Expected result

I expected to be able to construct schemas like this, like I can with the reference implementation of GraphQL, graphql-js:

![image](https://user-images.githubusercontent.com/607986/68243288-6d629080-ffcf-11e9-8f81-7e5e7aa5a210.png)

### Actual result

![image](https://user-images.githubusercontent.com/607986/68243333-853a1480-ffcf-11e9-9101-587674cd9fdd.png)

### Environment

Windows 10, Version 2.4.0 (latest stable).

**Comment by isaksky** [comment]
I read what the spec had to say about this, and could not see that this is a clear violation.

But here is a test from graphql-js, which seems to suggest this is wrong:

https://github.com/graphql/graphql-js/blob/6609d3942e2ce129ff44c3be24eb7917de444583/src/execution/__tests__/executor-test.js#L910-L937

```js
 it('does not include arguments that were not set', () => { 
   const schema = new GraphQLSchema({ 
     query: new GraphQLObjectType({ 
       name: 'Type', 
       fields: { 
         field: { 
           type: GraphQLString, 
           resolve: (data, args) => inspect(args), 
           args: { 
             a: { type: GraphQLBoolean }, 
             b: { type: GraphQLBoolean }, 
             c: { type: GraphQLBoolean }, 
             d: { type: GraphQLInt }, 
             e: { type: GraphQLInt }, 
           }, 
         }, 
       }, 
     }), 
   }); 
   const document = parse('{ field(a: true, c: false, e: 0) }'); 
  
   const result = execute({ schema, document }); 
   expect(result).to.deep.equal({ 
     data: { 
       field: '{ a: true, c: false, e: 0 }', 
     }, 
   }); 
 }); 
```

**Comment by isaksky** [comment]
I found [this part](https://graphql.github.io/graphql-spec/draft/#sec-Input-Objects.Input-Coercion) of the spec:

> In other words, there is a semantic difference between the explicitly provided value null versus having not provided a value.

This library doesn't allow distinguishing between these, so I think it is fair to call this a bug.

**Comment by dysi-hmusgrave** [comment]
> I found [this part](https://graphql.github.io/graphql-spec/draft/#sec-Input-Objects.Input-Coercion) of the spec:
> 
> > In other words, there is a semantic difference between the explicitly provided value null versus having not provided a value.
> 
> This library doesn't allow distinguishing between these, so I think it is fair to call this a bug.

Depending on your exact needs, you can distinguish between explicitly providing a null value vs not providing a value by, e.g., examining the AST of an executing query. I don't think you can fix the graph introspection so easily though, and I also think this is a bug in any case.

**Comment by sungam3r** [comment]
Relates to #1055

**Comment by sungam3r** [comment]
I should say that this problem only applies to nullable arguments.

**Comment by sungam3r** [comment]
@isaksky I think you are facing the same problem as me (#1055). Then I still did not understand how GraphQL functions, now everything more or less fell into place.

**Comment by isaksky** [comment]
@sungam3r I'm referring to stuff that works in graphql-js (the reference implementation for GraphQL). I just want to be able to do the same in graphql-dotnet. 

Either the reference implementation is wrong, or graphql-dotnet has a problem. Considering the test case I showed above, the latter seems more likely.

**Comment by sungam3r** [comment]
@isaksky You may try the latest preview from myget to see the desired behavior.

**Comment by isaksky** [comment]
@sungam3r Is it this version?  ( I added myget as a source)

![image](https://user-images.githubusercontent.com/607986/71920414-ea32f780-3143-11ea-99a3-dc393272db1f.png)

I just that one, but get the same behavior.

**Comment by joemcbride** [comment]
Latest on myget is 1392.

```
dotnet add package GraphQL --version 3.0.0-preview-1392 --source https://www.myget.org/F/graphql-dotnet/api/v3/index.json
```

**Comment by isaksky** [comment]
Thanks @joemcbride. I tried 1392 now, but I get the same result.

**Comment by sungam3r** [comment]
OK, I will add some test to see what went wrong.

**Comment by joemcbride** [comment]
I believe part of this issue is that JavaScript has the notion of `undefined`, as well as `null`.  There is no such thing in .NET.  At present, I don't think there will be a way to make the determination between "optional" with no default value and a default value of `null`.  They are slightly different, but in practical terms, mean the same thing and are handled the same way in .NET.

**Comment by sungam3r** [comment]
I suspected it is indeed `undefined`. But in general, two problems are described here. The first is the display of the result of introspection. The second is the perception of the passed values of the arguments. I will check both.

**Comment by isaksky** [comment]
@sungam3r wait, I just noticed I made a mistake with the update, it was actually still on 1352. (I confused myself using nuget.exe, sorry 😬!.)

With your change, I get this, which is what I was hoping for:

![image](https://user-images.githubusercontent.com/607986/71928065-09d21c00-3154-11ea-9359-b74d0d63c8e0.png)

Thanks!

**Comment by sungam3r** [comment]
Honestly, I guessed that it would be so. Therefore, I postponed this work a little and took up other issues ;) I'm glad the problem is resolved.
