### ISSUE TITLE
DateGraphType bug strips "Kind" (Utc / Local) information

### ISSUE THREAD

**Issue by alexmcmillan** [graphql-dotnet/graphql-dotnet#139]
Related to #136 

Arguments are being deserialized using JSON.Net, which converts ISO8601 strings into `DateTime` objects.  When passed through the `DocumentExecuter`, these `DateTime`s are re-serialized using `.ToString()`.  This process strips information about the `Kind` of `DateTime` (ie: `Local` or `Utc`)

For example, consider this ISO8601 string (which [specifies UTC](https://en.wikipedia.org/wiki/ISO_8601#UTC)):

    "2016-06-27T00:00:00.000Z"

This gets [deserialized](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L25) via `StringExtensions.ToInputs()` into a `DateTime` with a `.Kind` of `"Utc"`, before being [re-serialized](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L459) by `DocumentExecuter.AstFromValue()` into

    "27/06/2016 12:00:00 AM"

This is the value passed to `ScalarGraphType`s (eg: [DateGraphType](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/DateGraphType.cs#L36) for parsing.  There is no way to know at this time whether the original timestamp was Utc or Local.

Also, the current implementation of `DateGraphType.ParseValue()`, if receiving a `DateTime` object, actually round-trips it for no apparent reason:

```cs
    if (value is DateTime)
    {
        inputValue = ((DateTime)value).ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFF'Z'");
    }

...

    if (DateTime.TryParse(inputValue, CultureInfo.CurrentCulture, DateTimeStyles.AdjustToUniversal,
        out dateTime))
    {
        return dateTime;
    }
```

**Comment by joemcbride** [comment]
Thanks - another good find.  I think the `StringValue` will still need to be handled in the `DateGraphType` because it would be possible to pass the date directly as an argument parameter and not through a variable.  Such as:

```
{
  something(date: "2016-06-27T00:00:00.000Z")
}
```

In such a case it does not get serialized with JSON.NET.

**Comment by alexmcmillan** [comment]
Okay I will update for that and fix the failing test case tomorrow.
