### ISSUE TITLE
Get an error with DbNull value

### ISSUE THREAD

**Issue by MakaBuka** [graphql-dotnet/graphql-dotnet#1394]
Hi there,

Im got weird an exception when fetching nullable data from db.
I marked those fields (datatime) as "nullable: true" (based on example), but still getting that error:

>       An unhandled exception has occurred while executing the request.
> System.InvalidOperationException: Could not find conversion from 'System.DBNull'
>  to 'System.DateTime'
>    at GraphQL.ValueConverter.GetConversion(Type valueType, Type targetType) in n
> :\Projects\graphql-dotnet\src\GraphQL\ValueConverter.cs:line 135
>    at GraphQL.ValueConverter.ConvertTo(Object value, Type targetType) in n:\Proj
> ects\graphql-dotnet\src\GraphQL\ValueConverter.cs:line 121
>    at GraphQL.Types.DateGraphType.ParseValue(Object value) in n:\Projects\graphq
> l-dotnet\src\GraphQL\Types\DateGraphType.cs:line 29
>    at GraphQL.Types.DateGraphType.Serialize(Object value) in n:\Projects\graphql
> -dotnet\src\GraphQL\Types\DateGraphType.cs:line 17
>    at GraphQL.Execution.ValueExecutionNode.ToValue() in n:\Projects\graphql-dotn
> et\src\GraphQL\Execution\ExecutionNode.cs:line 157
>    at GraphQL.Execution.ObjectExecutionNode.ToValue() in n:\Projects\graphql-dot
> net\src\GraphQL\Execution\ExecutionNode.cs:line 96

So, I'll try to debugg it locally and found that in this converter (line 119 - ConvertTo):
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/ValueConverter.cs

there we have logic that check value on null but if we have an object that is DBNull - will be an error.

Btw, when I added checking on DBNull an issue fixed and I got result:

> "data": {
>     "orders": [
>       {
>         "OrderDate": "1996-07-04",
>         "RequiredDate": null
>       }
>     ]

Could you tell me - maybe I did something wrong on defining schema  or it's an issue itself in GraphQL?

Using stable version GraphQL 2.4.0

**Comment by sungam3r** [comment]
`DbNull` is a special _magic_ value in ADO.NET which serves null semantics. graphql-dotnet knows nothing about databases and about `DbNull`. It is just some value other than `null`. So your fix is correct since `DateTime?` resolver should return either valid `DateTime` value or `null`.

**Comment by MakaBuka** [comment]
Yes, you are right. I added on my side additional logic that fixed this issue.
Anyways, thanks for the reply.
