### ISSUE TITLE
Return custom model from mutation

### ISSUE THREAD

**Issue by jsp-up** [graphql-dotnet/graphql-dotnet#1395]
## Summary
Hello, I'd like to know how the fields are mapped with a given model because I've got this error when i'm trying to do a mutation :
`"GraphQL.ExecutionError: Expected value of type \"BearerType\" for \"BearerType\" but got: Bearer.\r\n`
Is there any problem with my mutation or my objects ?

## Relevant information
**Mutation.cs**
``` 
this.FieldAsync<BearerType>(
                "login",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<MyInputType>> { Name = "credentials" }
                ),
                resolve: async context => {
                    return new Bearer { ... };
                });
```
**BearerType.cs**
``` 
    public class BearerType : ObjectGraphType<Bearer>
    {
        public BearerType()
        {
            this.Field(b => b.Token).Name("accessToken");
            this.Field(b => b.TokenType).Name("tokenType");
            this.Field(b => b.TokenLifetime).Name("expiresIn");
            this.Field(b => b.UserId, type: typeof(IdGraphType)).Name("userId");
        }
    }
```
**Bearer.cs**
``` 
    public class Bearer
    {
        public string Token { get; set; }
        public string TokenType { get; set; }
        public int TokenLifetime { get; set; }
        public int UserId{ get; set; }
    }
```

**Comment by sungam3r** [comment]
First of all please try to use the latest preview version of graphql-dotnet. Not so long ago I corrected the text of the error message that you see.

**Comment by SimonCropp** [comment]
@sungam3r propose we close this given the lack of response?

**Comment by sungam3r** [comment]
@jsp-up I hope you have solved this problem. In any case, I am always happy to answer your questions.
