### ISSUE TITLE
Odd That link in github does not agree with link in docs

### ISSUE THREAD

**Issue by pkellner** [graphql-dotnet/graphql-dotnet#1396]
If you look at the link at the bottom of this page

https://graphql-dotnet.github.io/docs/guides/dataloader

"blog series", it points to 

http://fiyazhasan.me/graphql-with-asp-net-core-part-x-data-loader-series-finale/

But the github repo at this url points correctly. I don't get how those two things can be ut of sync, but they are give me a bad link when I browse the doc.

https://github.com/graphql-dotnet/graphql-dotnet/edit/master/docs2/site/docs/guides/dataloader.md

BTW, thanks for all the great work!

Small suggestion: It would be nice if in your docs, you linked to real examples. It can sometimes be hard for newbies like me go from docs files that have lot's of "..." to the real code.

**Comment by sungam3r** [comment]
Updating docs site is a manual process. It is a known issue.

**Comment by joemcbride** [comment]
I’ll see if I can get that sorted today.

**Comment by sungam3r** [comment]
If it’s not difficult for you, can you write a little documentation on how to update the documentation? :)

**Comment by joemcbride** [comment]
@sungam3r The docs for publishing the docs are in the docs folder.

https://github.com/graphql-dotnet/graphql-dotnet/tree/master/docs2#publishing

Which just calls:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/publish_docs.sh

**Comment by sungam3r** [comment]
OK

**Comment by joemcbride** [comment]
This is fixed and latest docs are deployed.  I'm not sure what caused the last docs deploy to fail, but this latest one worked (may have been an outdated version of `gh-pages` or something like that).

**Comment by pkellner** [comment]
Your docs are great.  Nice to see you stay on top of them
