### ISSUE TITLE
Convention-based approach leveraging .NET's type system

### ISSUE THREAD

**Issue by moserware** [graphql-dotnet/graphql-dotnet#14]
This project looks interesting!

What do you think about supporting a convention-based approach mapping Plain Old CLR Objects (with optional attribute annotations) using .NET's existing type system where possible?

I'm just starting to look into this approach, but I thought I'd get your feedback early before getting too deep into a possible implementation.

Here's a rough sketch of the idea:

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace GraphQLPlayground {
    class Program {
        static void Main(string[] args) {
            var repository = new StarWarsRepository();
            var endpoint = new GraphQLWrapper<StarWarsSchema>(new StarWarsSchema(repository));
            var query = endpoint.ExecuteAsync(@"query HeroNameAndFriendsQuery {
                  hero {
                    id
                    name
                    friends {
                      name
                    }
                  }
                }");
        }
    }

    public class GraphQLWrapper<TSchema> {
        // TODO: can use reflection to recursively examine the TSchema to generate an internal representation if needed

        public GraphQLWrapper(TSchema schema) {
        }

        public async Task<ExecutionResult> ExecuteAsync(string query) {
            throw new NotImplementedException();
        }
    }

    public class StarWarsSchema {
        private readonly StarWarsRepository _Repository;

        public StarWarsSchema(StarWarsRepository repository) {
            _Repository = repository;
        }

        // Although we follow .NET's convention of PascalCasing, these names 
        // can get automatically converted to lowerCamelCase in a similiar
        // mechanism as JSON.NET's CamelCasePropertyNamesContractResolver:
        public async Task<StarWarsCharacter> Hero() {
            return await _Repository.GetDroidAsync(3);
        }

        // Function arguments would get automatically mapped.
        // Note the use of System.ComponentModel.DescriptionAttribute to tag things;
        // this would automatically be extracted by the GraphQLWrapper.
        public async Task<Human> Human([Description("id of the human")] int id) {
            return await _Repository.GetHumanAsync(id);
        }

        public async Task<Droid> Droid([Description("id of the droid")] int id) {
            return await _Repository.GetDroidAsync(id);
        }
    }

    // Abstract classes (and interfaces) can be mapped to a GraphQL interface:
    public abstract class StarWarsCharacter {
        private readonly StarWarsRepository _Repository;
        protected StarWarsCharacter(StarWarsRepository repository) {
            _Repository = repository;
        }

        // Fields can be either simple properties or functions.

        [NotNull]
        [Description("The id of the character.")]
        public int Id { get; set; }

        [Description("The name of the character.")]
        public string Name { get; set; }

        // If the function returns a Task, the executor will execute it asynchronously
        public async Task<IList<StarWarsCharacter>> Friends() {
            return await _Repository.GetFriendsForIdAsync(Id);
        }

        [Description("Which movie they appear in.")]
        public async Task<IList<Episode>> AppearsIn() {
            return await _Repository.GetAppearsInById(Id);
        }
    }

    public class Human : StarWarsCharacter {
        public Human(StarWarsRepository repository) : base(repository) {
        }

        [Description("The home planet of the human.")]
        public string HomePlanet { get; set; }
    }

    public class Droid : StarWarsCharacter {
        public Droid(StarWarsRepository repository) : base(repository) {
        }

        [Description("The primary function of the droid.")]
        public string PrimaryFunction { get; set; }
    }

    [Description("One of the films in the Star Wars Trilogy.")]
    public enum Episode {
        // These could automatically get converted to SCREAMING_CAPS in the generated schema if needed:

        [Description("Released in 1977.")]
        NewHope = 4,

        [Description("Released in 1980.")]
        Empire = 5,

        [Description("Released in 1983.")]
        Jedi = 6
    }

    // Likely defined elsewhere:

    public class StarWarsRepository {
        private readonly JsonSerializerSettings _JsonSerializerSettings = new JsonSerializerSettings {
            ContractResolver = new CamelCasePropertyNamesContractResolver()
        };

        public async Task<Human> GetHumanAsync(int id) {
            return await GetCharacterFromServerAsync<Human>("/humans/" + id);
        }

        public async Task<Droid> GetDroidAsync(int id) {
            return await GetCharacterFromServerAsync<Droid>("/droids/" + id);
        }

        public async Task<IList<StarWarsCharacter>> GetFriendsForIdAsync(int id) {
            // TODO: implement real logic
            return new[] { await GetDroidAsync(3) };
        }

        public async Task<IList<Episode>> GetAppearsInById(int id) {
            // TODO: implement real logic
            await Task.Delay(200);
            return new[] {
                Episode.Empire,
                Episode.Jedi,
                Episode.NewHope
            };
        }

        private async Task<T> GetCharacterFromServerAsync<T>(string relativePath) where T : StarWarsCharacter {
            // TODO: implement real logic
            await Task.Delay(200);
            var json = @"{
                id: 3,
                name: ""R2-D2"",                
                primaryFunction: ""Astromech""
            }";
            var result = new Droid(this);
            JsonConvert.PopulateObject(json, result, _JsonSerializerSettings);
            return result as T;
        }
    }

    public class ExecutionResult {
        // TODO
    }

    public class NotNullAttribute : Attribute {
        // TODO
    }
}
```

**Comment by moserware** [comment]
We could also use a conventions-based approach to automatically generate TypeScript definitions that could be used by React/Relay components in their respective JSX/TSX.

**Comment by joemcbride** [comment]
I think this is a pretty good idea and I think there will be a demand for this.  Are you thinking the wrapper would just build up a traditional Schema and pass that to the Executor?

**Comment by moserware** [comment]
Exactly! For at least the first iteration, the wrapper would build a traditional `Schema` and then pass it to the Executor. Down the road, I could imagine lots of optimizations like those done in [Dapper](https://github.com/StackExchange/dapper-dot-net) and [Jil](https://github.com/kevin-montrose/Jil) to possibly eliminate the need for the intermediate Schema.

I'm still very early on in my thinking on this, so it's possible I could be missing something big that will make it not work, but I think this "POCO" approach could make it a bit easier for people to create GraphQL backends in .NET.

I welcome any suggestions and warnings of possible "gotchas" with this approach.

**Comment by zhech2** [comment]
I'm curious of how this is progressing.  I started writing code similar to what you describe until I noticed this issue.  It currently works against the star wars example.  

@moserware are you still working on it?  I would be interested in helping out.

**Comment by moserware** [comment]
@zhech2 I'm not currently working on this. We've decided at work to put further Relay work on pause for at least a few months.

**Comment by tlil87** [comment]
I'd be interested in looking into this / contributing to this. Will see if I can set off some time taking a stab at it next week.

**Comment by tlil87** [comment]
Just as an FYI, I've got some basic bits up and running for this. Will open a PR at some point, but probably won't be for another couple of weeks due to the holidays.

**Comment by tlil87** [comment]
@joemcbride @moserware @zhech2: I have a fully working implementation of this with support for dependency injection. Our fork has diverted a bit from the public one though, so I will copy across the relevant parts and create a PR for it here early next week.

**Comment by joemcbride** [comment]
@tlil87 Thinking on this, I'm not sure if I want the convention-based approach in the core repo.  I was thinking that could be a separate Nuget package in it's own repo.  I can create a new repo for that project under the graphql-dotnet org and give you access to it.  I'm sure there needs to be changes to the core project for it to work, though I'm hoping it can be an "add on".  This is thinking to the future of also having a MS-SQL centric one, Postgres, etc.  Thoughts on that?

**Comment by tlil87** [comment]
@joemcbride Yep, makes sense to me. Most/all of this should pretty much be extensions to the existing library anyway. The current implementation is mostly a wrapper on top, except for a couple of very minor modifications I needed to make in the core library. If you set up a new repo, I can transition it over to there and try to get around those core modifications so that it becomes completely independent. :+1:

**Comment by joemcbride** [comment]
@tlil87 Do you have a suggestion for repo name?  Hardest part - naming things.  `conventions`?

**Comment by tlil87** [comment]
Ditto.. `Conventions` could work. Let me have a think about it and get back to you tomorrow. On my way out here atm.

**Comment by tlil87** [comment]
@joemcbride Yes, let's go for `conventions` - I quite like that. I think it makes a lot of sense, and that it is a natural name for utilities and helpers for upholding GraphQL conventions. Seeing it like that, the library could naturally hold the Relay extensions etc. too (instead of maintaining those in the core library). So my suggestion is that we:

 * Set up the repository `graphql-dotnet/conventions`
 * I can transition over the non-standard GraphQL types that I added to core over to `conventions` (i.e., the Relay ones, `PageInfo`, `Edge` and `Connection`; and `Date`)
 * Consequently, `ConnectionBuilder` and its dependencies would be transitioned across too
 * `FieldBuilder` can remain in `graphql-dotnet`

PS: I might need to implement a couple of minor changes to the main library to enable the type wrappers to live in a separate repository. If so, I'll submit a separate PR for that obviously.

Any thoughts on the above?

**Comment by joemcbride** [comment]
@tlil87  Sounds good on the name.

As per the Relay items ... I'm much more comfortable with those being in the core repo since I think a high percentage of people who use GraphQL will also use Relay.  I do think having those in a separate namespace though is helpful - `GraphQL.Relay`.  Perhaps even moving those to a different project inside the core project would be good.  Could break `Relay` into a separate NuGet if it gets too big though just ILMerge it for now.  As for `Date`, I for sure want to keep that in the core repo.  That is such a common type I think it makes sense to be there.

Created [conventions](https://github.com/graphql-dotnet/conventions) and added you as a team member.  Should have read/write access.

**Comment by tlil87** [comment]
Okay, cool. I'm happy with that. I was just thinking if you wanted to keep the core library as closely related to the GraphQL spec as possible. On a side note, completely agree re `Date` (a bit baffled that it's not in the official spec).

Will move the Relay types into a separate namespace then for now. `GraphQL.Relay` sounds good. Hope to update the PR with those changes over the weekend, so please wait with merging that one :)

Thanks for creating the other repo - is it set up with AppVeyor at all?

**Comment by joemcbride** [comment]
> is it set up with AppVeyor at all?

Is now!

**Comment by tlil87** [comment]
Awesome, thanks! Appreciate it

**Comment by scmccart** [comment]
Any progress here, or anything I can help with? 

I'm running into the same issues that @plecong mentions in #3, e.g. the use of GraphType.Field<T> at runtime is difficult due the generic. This makes it difficult to plug any convention based approach on top of the library.

**Comment by tlil87** [comment]
@scmccart Yes, I expect to have a branch out some time over the weekend. Sorry for the delay on this; I've been pretty swamped lately.

**Comment by zhech2** [comment]
@tlil87 we have made significant progress on this issue as well. I would love to compare approaches to get the best solution.

**Comment by tlil87** [comment]
Absolutely, would be good to touch base on that @zhech2. My week is pretty packed, but we can talk later, either this week, or next..?

**Comment by tlil87** [comment]
We have have a fully operative solution for it at the moment that we're using in production. I just need to migrate it across to graphql-dotnet. @zhech2, are you on Slack?

**Comment by SpencerMacKinnon** [comment]
I'd be interested in participating in this conversation as well, I've been working on something to map types to GraphQL type definitions. I'm on the GraphQL dotnet channel as smackin.

**Comment by zhech2** [comment]
@SpencerMacKinnon What team is the GraphQL dotnet channel under?

**Comment by joemcbride** [comment]
@zhech2 The team is `GraphQL`.

**Comment by tlil87** [comment]
Guys, I need a couple of extra days to finish this off, but getting there. Just tidying up a few lose ends, and didn't have as much time this weekend as I first anticipated. Will keep you posted.

**Comment by zhech2** [comment]
My username is zhech on the GraphQL dotnet channel.

**Comment by tlil87** [comment]
I've pushed the initial version of [graphql-dotnet/conventions](https://www.github.com/graphql-dotnet/conventions) - i will provide more documentation and examples soon. per now, the tests and example project are the best sources of information.

cc @zhech2 @SpencerMacKinnon @scmccart @moserware

**Comment by jusefb** [comment]
Does anyone have any more examples as it is currently difficult to understand how to migrate from the classic graphql-dotnet to conventions based graphql-dotnet.

**Comment by joemcbride** [comment]
@jusefb Here is a sample: https://github.com/graphql-dotnet/conventions/tree/master/samples

**Comment by jusefb** [comment]
thanks

**Comment by joemcbride** [comment]
I'm going to close this as there are some projects out there that do this now.
