### ISSUE TITLE
Should addDataLoader Be Added to Docs?

### ISSUE THREAD

**Issue by pkellner** [graphql-dotnet/graphql-dotnet#1408]
I can't find any mention of it besides in an issue.  Am I correct in understanding that  code like this:

```
services.AddGraphQL(o => { o.ExposeExceptions = _env.IsDevelopment(); })
                .AddGraphTypes(ServiceLifetime.Scoped).AddUserContextBuilder(httpContext => httpContext.User)
                .AddDataLoader();
```

is the same as doing what is in the docs at this page:  https://graphql-dotnet.github.io/docs/guides/dataloader/

```
services.AddSingleton<IDataLoaderContextAccessor, DataLoaderContextAccessor>();
services.AddSingleton<DataLoaderDocumentListener>();

var listener = Services.GetRequiredService<DataLoaderDocumentListener>();

var executer = new DocumentExecuter();
var result = executer.ExecuteAsync(opts => {

	...

	opts.Listeners.Add(listener);
});
```

**Comment by sungam3r** [comment]
Sorry, I do not quite understand your question. The first block of code you cited performs the registration of dependencies inside the DI-container. The second block of code also handles the execution of the request.

**Comment by pkellner** [comment]
I think I'm getting confused between the "master" and the "develop" branches.  The example code I've been using is from a Pluralsight course and it does not add the services ContextAccessor or DocumentListener. It also does not have any middleware in it, yet it still works.  All it does have is the AddGraphQL method call and that seems register all the needed services and middleware.  I assume I must be using a new version then what is in the master branch which I assume what the docs are for.

What I have now is working well enough that I can move on to testing the client side of my app with graphql-dotnet and wait for the dust to settle around core 3.0 which is what I really want to be using.

Am I totally lost? (sorry for the newbie questions and confusion)

**Comment by sungam3r** [comment]
Yes, the documentation reflects the state of the develop branch. You are not lost. It’s just that the project is in beta for a long time without the release of the next stable version - 3.0.0.
