### ISSUE TITLE
Empty path in field resolver and using aliases in path

### ISSUE THREAD

**Issue by juleswijt** [graphql-dotnet/graphql-dotnet#1411]
## Summary

Hello, i've been working on a project with this implementation of GraphQL for dotnet and there are 2 things that I would like to know: 

1. Why is the `path` empty when retrieving it from the `ResolveFieldContext<T>` in a field resolver?
2. When working with aliases, should the full path be available from the context with aliases or is this so specific that I should implement this myself? 

## Relevant information

1. Below is some example code to show where the path is empty
```
    public class FooType : ObjectGraphType<Foo>
    {
        public FooType()
        {
            Field(x => x.Bar)
                .ResolveAsync(async context =>
                {
                    var path = context.Path; // This is empty
                    // more code ...
                });
        }
    }
```
I know that we can get the path by using the field middleware, but we need it after/during the resolving and (correct me if im wrong) the field middleware is executed before. So now we use some 'hacky' thing to get the path from the middleware in the context from the resolver.

2. Given the following query
```
    {
      A: foo(id: 1){
        Aa: bar
      }
      B: foo(id: 2){
        Bb: bar
      }
    }
```
The given path's for the above query are both
```
    path: [
        "foo"
        "bar"
    ]
```
What I expect is the following paths
```
    path: [
        "A"
        "Aa"
    ]
    path: [
        "B"
        "Bb"
    ]
```
So hence the question should can I retrieve this somewhere or should I implement this myself?

I hope I've given enough description for you to answers these questions thanks in advance.

**Comment by sungam3r** [comment]
Do you use 2.4.0 version or latest 3.0.0-prerelease?

**Comment by juleswijt** [comment]
Sorry, forgot to mention that, but I use 2.4.0.

**Comment by sungam3r** [comment]
The preview version is much ahead. Its behavior may be different for the better. Please try first to reproduce error with one of the latest preview versions:  https://www.nuget.org/packages/GraphQL/3.0.0-preview-1271

**Comment by juleswijt** [comment]
Aight, thanks for these quick response. I quickly validated it and the first question I had is no longer an issue within the preview version, but the second question still stands.

**Comment by sungam3r** [comment]
> 2. When working with aliases, should the full path be available from the context with aliases or is this so specific that I should implement this myself?

See https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionNode.cs#L63

Now `Path` uses field [name](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionNode.cs#L83), not alias. I think that's what it's intended as field name is "more stable" than alias. You can get alias though: `ExecutionNode.Field.Alias`, `IResolveFieldContext.FieldAst.Alias`.

@juleswijt  If you still have questions please ask.
