### ISSUE TITLE
Internal working of DataLoader Caching Mechanism Without any Primary key

### ISSUE THREAD

**Issue by nirajbhattad** [graphql-dotnet/graphql-dotnet#1412]
## Summary
From the official documents, it's been specified that GetOrAddLoader() call provides a caching mechanism without batching. But usually, an id or primary key is provided in the LoadAsync() function. So how does caching work if my data for the loader comes from an external API call without any primary key? 

## Relevant information

  Field<XYZType, XYZ>()
        .Name("xyz")
        .Argument<NonNullGraphType<StringGraphType>>("param1", "desc")//Query parameter
        .Argument<NonNullGraphType<StringGraphType>>("param2", "desc")//Query parameter
        .Description("Get all data")
          .ResolveAsync(ctx =>
          {
              IDataLoader<XYZ> loader = accessor.Context.GetOrAddLoader("xyz",
              () => APiCall(param1, param2);
              return loader.LoadAsync();
          });

**Comment by OpenSpacesAndPlaces** [comment]
Nothing stops you from making up a static value if that meets your use case - but this just a basic requirement of any in-memory system - there needs to be a reference value to which data to pull back out with or for reference to an sub-queries you might do.

Nothing says you have to use a dataloader - any number of ways to-do this in a more basic way - here's one:
https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/

**Comment by Shane32** [comment]
The `SimpleDataLoader` is probably the right answer if you are not providing any ids to the data loader.  `GetOrAddLoader` maps to the `SimpleDataLoader`.

Please let me know if you have further questions regarding this.
