### ISSUE TITLE
Error when comments exist after query in GraphiQL

### ISSUE THREAD

**Issue by josephmarksjr** [graphql-dotnet/graphql-dotnet#1415]
## Description

When running a simple query in GraphiQL I receive the below error.

```
{
  "errors": [
    {
      "message": "GraphQL.ExecutionError: ParserContext has 1 not applied comments. ---> System.ApplicationException: ParserContext has 1 not applied comments.\n   at GraphQLParser.ParserContext.Dispose()\n   at GraphQLParser.Parser.Parse(ISource source)\n   at GraphQL.Execution.GraphQLDocumentBuilder.Build(String body)\n   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)\n   --- End of inner exception stack trace ---",
      "extensions": {
        "code": "APPLICATION",
        "codes": [
          "APPLICATION"
        ],
        "data": {
        }
      }
    }
  ]
}
```

### Steps to reproduce

Run any query or mutation in GraphiQL with a comment **below** the query.

### Expected result

The query should run without issue.

### Actual result

The error pasted above occurred.

**Comment by sungam3r** [comment]
I will not transfer this issue to the parser repository, it will still need to update its dependency.

**Comment by sungam3r** [comment]
@josephmarksjr Done!

**Comment by MarkRogersEx** [comment]
@sungam3r - I get this error sometimes, what does it mean?

**Comment by sungam3r** [comment]
It means that parser has invalid state. Could you provide the query which produces error?

**Comment by MarkRogersEx** [comment]
> It means that parser has invalid state. Could you provide the query which produces error?

It was my mistake, I was posting to the graphql endpoint without any params.  I was just confused by the error, thinking i had configured the seutp wrong.  Thanks for the response.
