### ISSUE TITLE
GraphType First Approach As Close to POCO 

### ISSUE THREAD

**Issue by aammfe** [graphql-dotnet/graphql-dotnet#1418]
I think after c# 8 GraphType First Approach classes can be made Close to POCO

```
 public class StarWarsMutation : ObjectGraphType
    {
        public StarWarsMutation(StarWarsData data)
        {
            Name = "Mutation";

            Field<HumanType>(
                "createHuman",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<HumanInputType>> {Name = "human"}
                ),
                resolve: context =>
                {
                    var human = context.GetArgument<Human>("human");
                    return data.AddHuman(human);
                });
        }
    }
```
 ```
public class HumanInputType : InputObjectGraphType<Human>
    {
        public HumanInputType()
        {
            Name = "HumanInput";
            Field(x => x.Name);
            Field(x => x.HomePlanet, nullable: true);
        }
    }
```
its declaring more or less these things 

1. types and their fields
2. mutations/queries arguments and its types
3. type is nullable, or non nullable
4. types, fields name and description
5. mutations/queries resolver 

**Possible Solutions** 
**3** after C# 8 non nullable  reference types it could be resolve.

**1, 2, 5** it seems like
type = class
field = property
mutation/query = function
mutation/query params = function params

and **4th** one can be resolve by c# [documentation-comments](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments)
Like this 

```
/// <summary>This constructor initializes the new Point to
///    (<paramref name="xor"/>,<paramref name="yor"/>).</summary>
/// <param name="xor">the new Point's x-coordinate.</param>
/// <param name="yor">the new Point's y-coordinate.</param>

public Point(int xor, int yor) {
    X = xor;
    Y = yor;
}
```
 
What I m trying to say is
if we use c# full features we can simplify Graphql just to simple class, property and function. 

I m opening this Issue bcs I think it was not as clear it should be.
this is actual link of actual comment,  
[Discussion](https://github.com/graphql-dotnet/graphql-dotnet/issues/1229#issuecomment-522177282)

**Comment by sungam3r** [comment]
Your suggestion is clear. However, it only reflects one of the simplest applications of graphql and involves the use of one-to-one conventions. Sure, some conventions can be used. Moreover, they are already being used, for example, for `EnumerationGraphType<T>` / `AutoRegisteringObjectGraphType` / `AutoRegisteringInputObjectGraphType`. It is already possible to use xml documentation for GraphType First Approach. In addition, projects already exist that solve similar problems - https://github.com/graphql-dotnet/conventions.

I think it’s worth considering individual features that can complement this project and not try to make a swiss knife out of it.

**Comment by aammfe** [comment]
Thanks I did not know about [https://github.com/graphql-dotnet/conventions](https://github.com/graphql-dotnet/conventions)
