### ISSUE TITLE
New projects in graphql-dotnet org

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1424]
Regarding these comments:
https://github.com/graphql-dotnet/graphql-dotnet/issues/576#issuecomment-554796129
https://github.com/graphql/graphql-spec/issues/127#issuecomment-543053902

From time to time, the question arises of generating code for graphql clients, in particular for C# clients.

I received confirmation from my colleagues that I can open the source code generator. In fact, there are two generators. One generates SDL, and the second generates C# client. Both are written as .NET Core Global Tool.

@joemcbride The question is, can I host these generators as separate repositories in graphql-dotnet org? I could do this also under my account. But if this can be done here, then it would be good. As I understand it, special permissions are needed to create repositories in graphql-dotnet org.

1. https://github.com/sungam3r/graphql-sdl-exporter
2. https://github.com/sungam3r/graphql-introspection-model
3. CSharp client generator [WIP]

**Comment by sungam3r** [comment]
1. https://www.nuget.org/packages/dotnet-sdlexport/
2. https://www.nuget.org/packages/GraphQL.IntrospectionModel/
3. [awaiting]

**Comment by bezoar17** [comment]
Is there a package which can convert a `GraphQL.Types.Schema` object from [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) package to a SDL file.

Maybe we can then have a `ToSDL` method on the Schema object itself ?

**Comment by Shane32** [comment]
I’m not sure but doesn’t the SchemaPrinter class provide this functionality?

**Comment by joemcbride** [comment]
Yes, the `SchemaPrinter` prints the SDL.

```csharp
var schema = Schema.For(@"
  type Query {
    hello: String
  }
");
var printer = new SchemaPrinter(schema);
var sdl = printer.Print();
```

**Comment by bezoar17** [comment]
Thanks, perhaps this could be mentioned in the documentation somewhere.

**Comment by Shane32** [comment]
We would be happy to review a PR.

**Comment by Shane32** [comment]
> I received confirmation from my colleagues that I can open the source code generator. In fact, there are two generators. One generates SDL, and the second generates C# client. Both are written as .NET Core Global Tool.

See also:
- #576 

@sungam3r Status of this issue?  Can we close one?

**Comment by sungam3r** [comment]
Yes, I'm fine to close since I do not know 
1) if/when I can open-source CSharp client generator
2) what an advantage from the fact that repositories will be located here, and not in another place.
