### ISSUE TITLE
How get the GraphQL schema from ISchema?

### ISSUE THREAD

**Issue by Orwel** [graphql-dotnet/graphql-dotnet#1425]
I need add a endpoint in API to display the GraphQL schema.
The GraphQL UI playground display the schema, then I think a can retrieve and return it.

I try this code but this action display the name class :
```csharp
    [ApiController]
    [Route("Schema")]
    public class SchemaController : ControllerBase
    {
        private readonly ISchema schema;

        public SchemaController(ISchema schema)
        {
            this.schema = schema;
        }

        [HttpGet]
        public ActionResult Get()
        {
            return Ok(schema.ToString());
        }
    }
```

How can I do retrieve the GraphQL schema from `ISchema`?

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/b8d0e8b3e5f6c09b664353ff98a28bc340045b2a/src/GraphQL/Utilities/SchemaPrinter.cs#L41
