### ISSUE TITLE
Passing Arguments Down The Tree Confusing Me

### ISSUE THREAD

**Issue by pkellner** [graphql-dotnet/graphql-dotnet#1426]
I have a query that I've written list this below and I don't want to have to mention year: in the sessions attribute.  Just get it from the speakers query on the top. I feel like this must be simple but can't figure it out.  My speakers attributes does not include a year as part of the result so I don't have it on my context.source.

```
{
    speakers(year: "2019") {
    id,
    email
    sessions(year: "2019") {
      title
    }
  }
}
```

I'm sure I don't need to pass the year again to the sessions attribute but can't figure out how to pass it.  My SpeakerType class is as follows. I keep thinking there must be a way to get access to the full query (4th parameter of resolver?) but can't find it.,

```
   public class SpeakerType : ObjectGraphType<Attendees>
    {
        public SpeakerType(SessionRepository sessionRepository)
        {
            Field(t => t.Id);
            Field(t => t.Email).Description("users unique email");
            Field<ListGraphType<SessionType>>(
                "sessions",
                arguments: new QueryArguments(
                    new QueryArgument<StringGraphType>
                    {
                        Name = "year"
                    }
                ),
                resolve: context =>
                {
                    var year = context.GetArgument<string>("year");
                    return sessionRepository.getSessionsBySpeakerId(context.Source.Id,year);
                });
        }
    }
```

My SessionType is this:

```
public class SessionType : ObjectGraphType<Sessions>
    {
        public SessionType()
        {
            Field(t => t.Id);
            Field(t => t.Title);
        }
    }
```

and, in my top level speakers query, I have the top level arguments passed in.

```
            query.Field<ListGraphType<SpeakerType>>("speakers",
                arguments: new QueryArguments(
                    new QueryArgument<StringGraphType>
                    {
                        Name = "year"
                    }
                ),
                resolve: context =>
                {
                    var year = context.GetArgument<string>("year");
              
                    return _speakerRepository.GetByYear(year);
                });
```

**Comment by sungam3r** [comment]
This is one of those questions that interest me myself, since they came from my colleagues. I put it aside for now. However, you can use the query variable to not mention the value twice.

**Comment by pkellner** [comment]
It seems like in the JavaScript verison, there is a 4th param passed into resolve that has all that on it. Is there an equivalent here?

**Comment by joemcbride** [comment]
In this case, `speakers` and `sessions` are at the same "level" of the tree, so there would be no way to pass information between them.  Also, since it is a query, those fields are typically executed in parallel.

Have you looked at the docs for variables?

https://graphql-dotnet.github.io/docs/getting-started/variables

You can use a variable and that variable can get referenced in both places.

```gql
query MyQuery($year: String!) {
    speakers(year: $year) {
    id,
    email
    sessions(year: $year) {
      title
    }
  }
}
```

> 4th param passed into resolve

Going off of these docs: https://www.apollographql.com/docs/graphql-tools/resolvers/#resolver-function-signature

The 4th param is an `info` object.  In this project, all of that info is available on the `ResolveFieldContext`.

**Comment by pkellner** [comment]
Thanks @joemcbride   I've got a lot to learn here.  Thanks for the tips (and I do get it)

**Comment by sungam3r** [comment]
> In this case, speakers and sessions are at the same "level" of the tree

Oh, I didn’t notice.
