### ISSUE TITLE
Enable Metrics - Memory Leak in 3.5.0-alpha0027 

### ISSUE THREAD

**Issue by DavidKiff** [graphql-dotnet/graphql-dotnet#1428]
## Description
Memory ever increasing and never being released.

Profiler shows a ConcurrentBag+WorkStealingQueue<PerfRecord> being the culprit.

### Steps to reproduce
Run a Graph QL instance with EnableMetrics = true and call the endpoint over and over again to see memory increase.

### Expected result
Memory should be released eventually.

### Actual result
Memory is never released

### Environment
Windows 10, .NET Core 3 - running in HTTP Sys in a console x64

**Comment by sungam3r** [comment]
Duplicate of #1324
