### ISSUE TITLE
Using custom scalars with variables

### ISSUE THREAD

**Issue by spcoleman** [graphql-dotnet/graphql-dotnet#1432]
### Description

I have created custom scalar ISO8601DateTime which on input converts a UTC time to local time and on output converts local time to UTC. The resolvers require local date/times but the gql input/output dates are in UTC.  

This scalar works as excepted when values are passed within the mutation but when I use variables to pass values to the mutation is doesn't. When using variables, Serialize is called passing the original UTC datetime, even though before this call ParseLiteral is called which returns the local time. Serialize is only called on input when using variables. 

    public class ISO8601DateTime : ValueNode<DateTime>
    {
        public ISO8601DateTime(DateTime value)
        {
            
            Value = value;
        }

        protected override bool Equals(ValueNode<DateTime> other)
        {
            return Value == other.Value;
        }
    }

    public class ISO8601DateTimeValueConverter : IAstFromValueConverter
    {
        public bool Matches(object value, IGraphType type)
        {
            return value is DateTime;
        }

        public IValue Convert(object value, IGraphType type)
        {
            return new ISO8601DateTime((DateTime)value);
        }
    }

    public class ISO8601DateTimeGraphType : ScalarGraphType
    {
        public ISO8601DateTimeGraphType()
        {
            Name = "ISO8601DateTime";
        }

        public override object Serialize(object value)
        {
            // Output dates to UTC 
            if (value is DateTime datevalue)
            {
                return datevalue.ToUniversalTime();
            }
            else
            {
                return ParseValue(value);
            }
        }

        public override object ParseValue(object value)
        {
            return ValueConverter.ConvertTo<DateTime>(value);
        }

        public override object ParseLiteral(IValue value)
        {
            if (value is ISO8601DateTime ISO8601DateTimeValue)
            {
                return ISO8601DateTimeValue.Value;
            }

            if (value is DateTimeValue timeValue)
            {
                return timeValue.Value;
            }
            
            if (value is StringValue stringValue)
            {
                // Input date. This should deal with local and UTC time
                // formats to return a local date.
                return DateTimeOffset.Parse(stringValue.Value).LocalDateTime;
            }

            return null;

        }
    }

Registering the type

           schema.RegisterTypes(new[] { typeof(ISO8601DateTimeGraphType) } );
           schema.RegisterValueConverter(new ISO8601DateTimeValueConverter());

### Steps to reproduce

This doesn't work:

```
mutation addportfoliomovement2($input: AddTradeMovementInput!) {
  addBuyTradePortfolioMovement(input: $input) {
    id
    movementDate
  }
}
```

```
{
 "input": 
  {"fees": [{"feeType": "urn_feeType_brokerage", "value": {"value": 29, "currency": "NZD"}}],
"instrument": {"id": "SPK.NZX", "symbol": "SPK"},
"movementDate": "2019-11-21T23:06:37.973Z",
"movementvalue": {"value": 500, "currency": "NZD"},
"quantity": 100,
"tradingParty": {"id": "112233.01"},
"unitCost": {"price": 5, "priceCurrency": "NZD"}}
}
```

This does work has expected:

```
mutation addportfoliomovement {
  addBuyTradePortfolioMovement(input: {tradingParty: {id: "112233.01"}, instrument: {id: "AIA.NZX", symbol: "AIA"}, movementDate: "2019-11-21T23:06:37.973Z", unitCost: {price: 1.92, maxPrice: null, minPrice: null, priceCurrency: "NZD"}, quantity: 55, fxRate: null, fees: [{feeType: urn_feeType_brokerage, value: {value: 22.5, currency: "NZD"}}], movementvalue: {value: 105.6, currency: "NZD"}}) {
    id
    movementDate
  }
}
```

### Expected result

Movement date passed to resolver would be local date/time as returned by the ParseLiteral.

### Actual result

Movement date passed to resolver is the UTC movement date being passed on input, and not the local datetime 22/11/2019 12:06:37 p.m. from ParseLiteral. This is only an issue when using variables. 

Anyone have any thoughts on how I might get this to work, or if how I'm trying to do this is simply not the right way.

Thanks.

**Comment by sungam3r** [comment]
`ParseLiteral` is for inputs "embedded" into the query text while `ParseValue` is for inputs from variables, [docs](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/custom-scalars.md). 
Try to appropriate override `ParseValue` method. It think it should be something like
```c#
    public override object ParseValue(object value)
    {
        return ValueConverter.ConvertTo<DateTime>(value).LocalDateTime;
    }
```

**Comment by RehanSaeed** [comment]
It should be noted that ISO 8601 does not mandate that the time should be UTC, so naming this `ISO8601UTCDateTime` might be more appropriate.

**Comment by sungam3r** [comment]
Closed due to the lack of feedback.
