### ISSUE TITLE
Nested complex type as an input argument

### ISSUE THREAD

**Issue by gmcelhanon** [graphql-dotnet/graphql-dotnet#1433]
Am I correct in my understanding that GraphQL .NET only support input arguments with scalar members? I've been trying to emulate the syntax provided by the Hasura GraphQL engine. It provides a complex object as an input argument to queries to apply rich filtering capabilities to queries.

In the following example, there is a `where` argument on `author` that is not scalar -- rather it contains "column expressions" for each property of `author`, each of which allow the selection of an operator and the associated value.

For example, in the query below, the equality operator (`_eq`) with the value of "Sidney" is the column expression to be applied to the `name` property.
```graphql
query {
  author(
    where: {name: {_eq: "Sidney"}}
  ) {
    id
    name
  }
}
```
This use of complex object arguments allows for much more flexibility (e.g. explicitly applying `_and` and `_or` to multiple criteria), including nested filter criteria, like so:
```graphql
   query {
     article (where: {author: {name: {_eq: "Sidney"}}}) {
       id
       title
     }
   }
```
Am I correct that GraphQL does not support this sort of structure on query input arguments?

**Comment by joemcbride** [comment]
Nested complex input objects are supported.  Here is a basic example with a mutation, but you should be able to nest InputObjects.

https://graphql-dotnet.github.io/docs/getting-started/mutations

**Comment by gmcelhanon** [comment]
So, I've reviewed that example already, but the `HumanInputType` class only defines _scalar_ value fields:

```csharp
public class HumanInputType : InputObjectGraphType
{
  public HumanInputType()
  {
    Name = "HumanInput";
    Field<NonNullGraphType<StringGraphType>>("name");
    Field<StringGraphType>("homePlanet");
  }
}
```
What I really want to do is to define a `StringColumnExpressionType` as follows:
```csharp
    public class StringColumnExpressionType : ObjectGraphType
    {
        public StringColumnExpressionType()
        {
            Field(typeof(StringGraphType), "_eq");
            Field(typeof(StringGraphType), "_neq");
        }
    }
```
... and then define my input argument as follows:
```csharp
    public class AuthorQueryArgumentType : InputObjectGraphType
    {
        public AuthorQueryArgumentType()
        {
            Field(typeof(StringColumnExpressionType), "firstName", resolve: o => o);
            Field(typeof(StringColumnExpressionType), "lastSurname", resolve: o => o);
        }
    }
```
This would allow me to write something like this (supported by Hasura):
```graphql
{
  students(where: { firstName: { _eq: "Bob" } }) {
    firstName
    lastSurname
  }
}
```
The [unit tests](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Types/InputObjectGraphTypeTests.cs) for `InputObjectGraphType` actually explicitly prevent `ObjectGraphType` from being used in field definitions, and if I switch it to use the `ComplexGraphType<object>`, as done by the tests, I get a runtime cast exception (trying to convert to `ScalarGraphType`).

```csharp
        [Fact]
        public void should_throw_an_exception_if_input_object_graph_type_contains_object_graph_type_field()
        {
            var type = new InputObjectGraphType();
            var exception = Should.Throw<ArgumentException>(() => type.Field<ObjectGraphType>().Name("test"));

            exception.Message.ShouldContain("InputObjectGraphType cannot have fields containing a ObjectGraphType.");
        }
```
So am I completely misunderstanding something, or is this just not currently possible?

**Comment by joemcbride** [comment]
> So am I completely misunderstanding something, or is this just not currently possible?

Yes you are misunderstanding. Don’t use ObjectGraphType.  You have to use InputObjectGraphType for input objects (StringColumnExpressionType is an input object), ObjectGraphType is not allowed.  So change StringColumnExpressionType to inherit from InputObjectGraphType.

**Comment by gmcelhanon** [comment]
Thought I had tried that before, but that worked and that's all that matters now.

Thanks for the quick replies!

**Comment by joemcbride** [comment]
Welcome!

**Comment by sungam3r** [comment]
Relates to #1434
