### ISSUE TITLE
System.MissingMethodException: No parameterless constructor defined for type 'GraphQLSample.GraphQLTypes.RootQuery'

### ISSUE THREAD

**Issue by Naveen512** [graphql-dotnet/graphql-dotnet#1435]
RootQuery:
```
public class RootQuery:ObjectGraphType
    {
        private readonly IPlayerRepository _playerRepository;
        public RootQuery(IPlayerRepository playerRepository)
        {
            _playerRepository = playerRepository;
            Field<ListGraphType<PlayerType>>("players", resolve: context =>
             {
                 return _playerRepository.GetAll();
             });
        }
    }
```
Startup.cs:
```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<IPlayerRepository, PlayerRepository>();
            services.AddScoped<RootQuery>();

            services.AddSingleton<ISchema, RootSchema>();
            services.AddSingleton<IDocumentExecuter, DocumentExecuter>();
            services.AddControllers();
        }
```
I'm Unable to inject my repositories into ObjectGraphQLType, when i run api i'm getting error as below
```
System.Exception: Failed to call Activator.CreateInstance. Type: GraphQLSample.GraphQLTypes.RootQuery
 ---> System.MissingMethodException: No parameterless constructor defined for type 'GraphQLSample.GraphQLTypes.RootQuery'.
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at GraphQL.DefaultDependencyResolver.Resolve(Type type)
```

**Comment by joemcbride** [comment]
This is expected if you have not configured your Schema to support Dependency Injection.

It looks like you are using version 2.x?  Here are the docs for that version:

https://github.com/graphql-dotnet/graphql-dotnet/blob/73189c11cce05b96b6f29f0dfb184e9d339f7a80/docs2/site/docs/getting-started/dependency-injection.md

**Comment by Naveen512** [comment]
Yeah it works, after registering GraphQl 'IDependencyResolver' and My custom ObjectGraphType 'PlayerType' as below

```
services.AddSingleton<IDependencyResolver>(_ => new FuncDependencyResolver(_.GetRequiredService));
 services.AddSingleton<PlayerType>();
```

**Comment by Daniel-Khodabakhsh** [comment]
Another way to enable dependency injection when using Asp.NET-Core (not mentioned above but in some of the examples) is to pass the dependency injected [`System.IServiceProvider`](https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider?view=netcore-3.1) from the schema's constructor into the base constructor. No need to inject `IDependencyResolver`:

```cs
namespace ...
{
	public class RootSchema : Schema
	{
		public RootSchema(IServiceProvider serviceProvider, RootQuery query, ...)
			: base(serviceProvider)
		{
			Query = query;
			...
		}
	}
}
```

**Comment by Shane32** [comment]
`IDependencyResolver` is required for use in 2.x versions, but has been removed in the current 3.0 beta version, and replaced with `IServiceProvider` as in the sample provided by @Daniel-Khodabakhsh .  The applicable documentation for version 3.0 is here:

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection
