### ISSUE TITLE
Add IResolveFieldContext<T> and IResolveFieldContext classes

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1437]
## Summary, Motivation & Benefits

Currently, `ResolveFieldContext<TSource>` does not inherit from `ResolveFieldContext`, but rather the reverse.  So custom methods cannot be configured to accept a `ResolveFieldContext` parameter, but rather must rely on generics in order to allow for a context with unknown source type to be passed to it.  I would like to suggest that `IResolveFieldContext` and `IResolveFieldContext<TSource>` interfaces be added, so that code that does not care about the typing of TSource can be written without requiring generic typing on the method.

An alternative route would be to change the inheritance tree, but C# does not allow hidden members to be overridden.  So I believe it would be best just to add interfaces so that methods parameters can be typed `IResolveFieldContext` or `IResolveFieldContext<TSource>` as desired.

Once interfaces are added, `GetArgument` and `HasArgument` can be written as extension functions, so that they can operate on any class that supports `IResolveFieldContext`, irrespective of TSource.

Another benefit is that `ResolveFieldContext.As` could be written to simply type-check the source property and then return an class that implements `IResolveFieldContext<T>` where the members reference the original `ResolveFieldContext`, with no need to copy all of the properties.  It would probably be faster overall, by some immeasurable amount.

I can post a pull request if desired.

### Basic example

Here is what the interfaces would look like:
``` C#
    public interface IResolveFieldContext : IProvideUserContext
    {
        public string FieldName { get; }
        public Field FieldAst { get; }
        public FieldType FieldDefinition { get; }
        public IGraphType ReturnType { get; }
        public IObjectGraphType ParentType { get; }
        public Dictionary<string, object> Arguments { get; }
        public object RootValue { get; }
        public IDictionary<string, object> UserContext { get; }
        public object Source { get; }
        public ISchema Schema { get; }
        public Document Document { get; }
        public Operation Operation { get; }
        public Fragments Fragments { get; }
        public Variables Variables { get; }
        public CancellationToken CancellationToken { get; }
        public Metrics Metrics { get; }
        public ExecutionErrors Errors { get; }
        public IEnumerable<string> Path { get; }
        public IDictionary<string, Field> SubFields { get; }
    }

    public interface IResolveFieldContext<TSource> : IResolveFieldContext
    {
        public new TSource Source { get; }
    }
```

Here is a sample of how the As function could be written: (or it could be left as-is)

``` C#
    internal class ResolveFieldContextProxy<TSource> : IResolveFieldContext<TSource>
    {
        private readonly IResolveFieldContext _context;

        public ResolveFieldContextProxy(IResolveFieldContext context)
        {
            if (context == null) throw new ArgumentNullException(nameof(context));
            if (context.Source != null || !(context.Source is TSource))
                throw new InvalidOperationException("Source property is wrong type");
            _context = context;
        }

        public TSource Source => (TSource)_context.Source;
        public string FieldName => _context.FieldName;
        public Field FieldAst => _context.FieldAst;
        public FieldType FieldDefinition => _context.FieldDefinition;
        public IGraphType ReturnType => _context.ReturnType;
        public IObjectGraphType ParentType => _context.ParentType;
        public Dictionary<string, object> Arguments => _context.Arguments;
        public object RootValue => _context.RootValue;
        public IDictionary<string, object> UserContext => _context.UserContext;
        public ISchema Schema => _context.Schema;
        public Document Document => _context.Document;
        public Operation Operation => _context.Operation;
        public Fragments Fragments => _context.Fragments;
        public Variables Variables => _context.Variables;
        public CancellationToken CancellationToken => _context.CancellationToken;
        public Metrics Metrics => _context.Metrics;
        public ExecutionErrors Errors => _context.Errors;
        public IEnumerable<string> Path => _context.Path;
        public IDictionary<string, Field> SubFields => _context.SubFields;
        object IResolveFieldContext.Source => _context.Source;
    }
    public static class ResolveFieldContextExtensions
    {
        public static IResolveFieldContext<TSource> As<TSource>(this IResolveFieldContext context)
        {
            if (context is IResolveFieldContext<TSource> ret) return ret;
            return new ResolveFieldContextProxy<TSource>(context);
        }
    }
```

**Comment by sungam3r** [comment]
Need some time to investigate.

**Comment by sungam3r** [comment]
> Another benefit is that ResolveFieldContext.As could be written to simply type-check the source property and then return an class that implements IResolveFieldContext<T> where the members reference the original ResolveFieldContext, with no need to copy all of the properties.

Your implementation is no different from the current one. First check. If it failed, then create a new object.

Nevertheless, it seems to me that the point is not at all in the new interfaces. It is worthwhile to carefully study the current design and understand what caused this inheritance. The situation is similar to that for `ObjectGraphType`and `ObjectGraphType<TSourceType>`. It is possible that we can invert inheritance, although a lot of things will have to be changed because of this. What benefits will it bring? First, as you noted, it will be possible to write methods targeted for basic `ResolveFieldContext` without generics. Secondly, I think that it will be possible to completely get rid of context copying in the `As` method. I looked at the code and it seems to me that `ExecutionStrategy` does not have to create `ResolveFieldContext`, so that later it is converted to the context of the desired type in the resolver (see `AsyncFieldResolver<TSourceType, TReturnType>` or `FuncFieldResolver<TSourceType, TReturnType>`). I believe that we can find a solution to immediately create the context of the desired type, because this information is already exist inside the field definition. In other words, I think that in the end the `As` method should be removed.

**Comment by Shane32** [comment]
I already tested ResolveFieldContext code with inverted inheritance (which works fine).  I can post it if you'd like to review.  There was one issue I really didn't like: `object ResolveFieldContext.Source` was hidden by `T ResolveFieldContext<T>.Source`, which then would have to cast the original `object Source` property to T every time Source is accessed.  Not only that, someone can access the underyling `ResolveFieldContext.Source` property and set it to an object with improper type.  Due to the fact that hidden members cannot be overridden, the only way around this is to override ResolveFieldContext multiple times, which seemed like a hack.  I'm guessing that this is the reason behind the current design.  There's just no super clean way to invert inheritance.

However, I suggested interfaces not because of the above issue, but rather because they can be applied wider, as shown in this example: Suppose that inheritance was inverted.  You could create a `ResolveConnectionContext` that inherits from `ResolveFieldContext` -- or a `ResolveConnectionContext<T>` that inherits from `ResolveFieldContext<T>` (and in turn `ResolveFieldContext`) -- but `ResolveConnectionContext<T>` cannot inherit from both `ResolveFieldContext<T>` and `ResolveConnectionContext`.  There's just no way around this without using interfaces.

I know that `ResolveConnectionContext` does not exist in the code, but my application code uses custom resolvers and custom "context" classes, which is why I would like to have interfaces added to ResolveFieldContext.  It's not a big deal, but it would be very convenient.

Regarding As:

> Your implementation is no different from the current one. First check. If it failed, then create a new object.

True.

> I believe that we can find a solution to immediately create the context of the desired type, because this information is already exist inside the field definition. In other words, I think that in the end the As method should be removed.

I'm sure it's possible with reflection.  I'm not sure if it's possible without reflection.  Perhaps if this happened during schema initialization, it would not affect runtime performance.  Maybe we should open another issue regarding optimizing away As.

**Comment by Shane32** [comment]
Maybe if the proxy was a struct, then it would eliminate the performance impact of creating an object during As ...

**Comment by Shane32** [comment]
... nope.  Structs cast as interfaces get boxed to reference types.

**Comment by sungam3r** [comment]
> There was one issue I really didn't like: object ResolveFieldContext.Source was hidden by T ResolveFieldContext<T>.Source, which then would have to cast the original object Source property to T every time Source is accessed. 

But what if we think that `Source` is not needed at all in the base class - neither in the form of a generic, nor in the form of an object? We can try to consider this option.

**Comment by sungam3r** [comment]
We might also consider using a generic method in context instead of a TSource property to move generic parameter from type declaration to method declaration. In this case, the ResolveFieldContext<T> may not be required.

**Comment by Shane32** [comment]
> But what if we think that `Source` is not needed at all in the base class - neither in the form of a generic, nor in the form of an object? We can try to consider this option.

I like that idea.  Although that brings us back to manufacturing a typed `ResolveFieldContext` in the `ExecutionStrategy` so it can be passed to resolvers.

> We might also consider using a generic method in context instead of a TSource property to move generic parameter from type declaration to method declaration. In this case, the ResolveFieldContext may not be required.

So like `context.GetSource<T>()` to retrieve the source?  I'm a bit confused

**Comment by sungam3r** [comment]
> So like context.GetSource<T>() to retrieve the source?

Yes, like this. Just like an idea. Now I do not like the fact that the ResolveFieldContext is strongly associated with the type of Source (and Source object at all). I discuss whether this is correct and look at the options and their consequences.

**Comment by Shane32** [comment]
Ok so I've spent hours and hours working at the concepts you outlined, but I have not yet been able to bring it to the goal line.  So here's where I'm at:

First, I added covariant interfaces so that when the `ResolveFieldContext<T>` was created, it could be cast to any compatible resolver even if the resolver used a type that wasn't exactly the ACTUAL type of the source object.  This seemed to be both desired and required, given that the desired type of the source object isn't retrievable from the stored return value of field resolver of the parent.  Then I changed all the resolvers and stuff throughout the source code to work with this design.  But then I attempted to change the `ExecutionStrategy` to create a `ResolveFieldContext<T>` rather than a simple `ResolveFieldContext`.  However, if the source is null, the code cannot deduce which type of `ResolveFieldContext` was desired.  Let's assume that it just picks object type for nulls.  Then when the class is cast to the proper interface within the resolver, the cast will fail due to `IResolveFieldContext<object>` being unable to be cast to `IResolveFieldContext<T>`.

The only way to fix this would seem to be to store the type of `IFieldResolver<T>` passed to the resolve function.  "Easy enough", I suppose ... however, the code is so far from the original code now that any custom IFieldResolver implementation would need a major rework to operate with this design philosophy.  Features like middleware needs to be re-thought entirely, as there was no easy way to port it to the new design.  Is this really desired?  I feel like I'm wasting time on this unless it's truly desired that the project undertake this major of a design change.

I thought about `GetSource<T>()`, but this presents a couple issues: if the goal is to eliminate a typed ResolveFieldContext, then that means that there are no such thing as source-typed resolvers anymore, so TSourceType in the FieldBuilder goes away, and you cannot write `(context) => context.Source.Name` anymore; it would have to be `(context) => context.GetSource<Person>().Name`.  I can't imagine this being desirable in any way from a usability perspective, and again would require a major rewrite of any implementations of this code, as almost every resolver would need to be rerwritten.  Of course it could proxy/copy the ResolveFieldContext to a typed class, but that defeats the entire purpose of the code rewrite -- what exists now would be equivalent.

Thoughts?

**Comment by Shane32** [comment]
To be clear, the idea I've been working on is changing `IFieldResolver.Resolve` to `IFieldResolver.Resolve<TSourceType>`.

**Comment by Shane32** [comment]
Then you agree I should drop those ideas?  (1) Change `IFieldResolver.Resolve` to `IFieldResolver.Resolve<TSourceType>` and (2) Change `ResolveFieldContext.Source` to `ResolveFieldContext.GetSource<T>`

As to swapping inheritance: While I agree with this change (and indeed already tested it when I posted my original issue), it does not change the fact that there are no interfaces, and does not solve my issue.  I don't really care if the inheritance is swapped, since a class cannot inherit from two different classes.  For instance, `ResolveEventStreamContext<T>` still will not be able to inherit from both `ResolveFieldContext<T>` (which could inherit from `ResolveFieldContext`) and `ResolveEventStreamContext`.

As a side bonus, the interface will be covariant, which may not have a lot of practical value at the moment, but is worth mentioning.

Note that if we add interfaces, then ResolveFieldContext can be written with or without swapped inheritance, as it will not matter to implementers.

**Comment by sungam3r** [comment]
> So custom methods cannot be configured to accept a ResolveFieldContext parameter, but rather must rely on generics in order to allow for a context with unknown source type to be passed to it. 

I understood what you said. Now it has been solved. One could add interfaces, but not every type needs an interface. Take the `Stream` as an example or `CustomAttributeData`. Aforementioned `ResolveEventStreamContext` can also be changed, but first we need to understand the purpose of the change. Now `ResolveEventStreamContext` inherits from the base `ResolveFieldContext`.

>  For instance, ResolveEventStreamContext<T> still will not be able to inherit from both ResolveFieldContext<T> (which could inherit from ResolveFieldContext) and ResolveEventStreamContext.

Is that necessary?

In any case, I proceed not to introduce new entities into the design.

> 1) Change IFieldResolver.Resolve to IFieldResolver.Resolve\<TSourceType>

Do you mean this?
```c#
public interface IFieldResolver
{
     object Resolve<TSourceType>(ResolveFieldContext context);
}
```
As I understand it, the point of a generic resolver is to give the resolver body to work conveniently with an object of `TSource` type: `context => context.Source.MyProperty`, etc. What will give an additional type parameter?

> (2) Change ResolveFieldContext.Source to ResolveFieldContext.GetSource\<T>

It seems like a dead end.

**Comment by sungam3r** [comment]
The last questions I asked are no longer relevant. I am OK with changes in #1441 and I’ll look it carefully again before merge.
