### ISSUE TITLE
Classes derived from InputObjectGraphType *sometimes* return error when given a name and a field is given a description.

### ISSUE THREAD

**Issue by bigbizze** [graphql-dotnet/graphql-dotnet#1445]
After a ton of testing to figure out exactly why my mutations were sometimes working and sometimes not I've finally isolated the problem down to whether or not the InputObjectGraphType class has been given a name and a field in that class has a description but this only seems to matter _sometimes_ as bizarre as that is.

For example, this
```
    public class WololoInputType : InputObjectGraphType
    {
        public WololoInputType()
        {
            Name = "Enemies are red, allies are blue, WOLOLO, now you're blue too.";
            /// Attribute Fields
            FieldAsync<NonNullGraphType<EntityReferenceInputType>, EntityReferenceType>("customerid").Description == "PepperoniPizza";
        }
    }
```

Gives me this error:

```
{
    "errors": [
        {
            "message": "GraphQL.Validation.ValidationError: Variable \"salesorder\" cannot be non-input type \"SalesOrderCreateInput\".",
            "locations": [
                {
                    "line": 1,
                    "column": 10
                }
            ],
            "extensions": {
                "code": "5.7.3"
            }
        },
        {
            "message": "GraphQL.Validation.ValidationError: Unknown type SalesOrderCreateInput.",
            "locations": [
                {
                    "line": 1,
                    "column": 23
                }
            ],
            "extensions": {
                "code": "5.4.1.2"
            }
        }
    ]
}
```

However this:

```
    public class WololoInputType : InputObjectGraphType
    {
        public WololoInputType()
        {
            /// Attribute Fields
            FieldAsync<NonNullGraphType<EntityReferenceInputType>, EntityReferenceType>("customerid");
        }
    }
```

Will perform the mutation as expected.

The _strangest_ part about this error is that if I delete just the field description, rebuild the solution and run it, I still get the above error. However, if I delete both of them, rebuild it and then _add name back to class_ it runs fine, only failing yet again if I add Description back to any field.

**Comment by sungam3r** [comment]
Name is a GraphType's name, not description. Name must have only alphanumeric symbols. Try the latest preview version and you will see runtime error about that when schema is built.

**Comment by bigbizze** [comment]
Ah, this makes sense then why it would often confuse one input type for another. Good to know, not sure how I mixed up the name and description properties so thoroughly, thank you!
