### ISSUE TITLE
Programmatically injecting Arguments into a query

### ISSUE THREAD

**Issue by amoore-incomm** [graphql-dotnet/graphql-dotnet#1447]
## Summary
Is there a simple way to do query manipulation on a previously constructed query at runtime?
## Relevant information

Lets assume that i have some schema of Star wars characters. An example query could look like the following
```
{
    character(race: "human")
    {
        name
    }
}
```
Which returns me something along the lines of 
```
{
    characters: [
    {
        name: "Luke"
    },
    {
        name: "Leia"
    },
    {
        name: "Han"
    }
    ]
}
```
Now lets say i also have the character query allow the argument of `gender`, and to allow it to be used in conjuction with our race argument, like
```
{
    character(race: "human", gender: "male")
    {
        name
    }
}
```
I want to be able to dynamically add in the `gender:"male"` portion at runtime so that the user doesn't have any control over it.  

(The actual use case is restricting data sets based on authorization claims/roles)

The way i am familiar with executing various queries all flows through an `ExecutionOptions` object and passing it off to a `DocumentExecutor`, which despite the name, still requires the `ExecutionObjects` query to be filled out and present.  This seems to suggest i would need to do string manipulation in order to get the appropriate argument into the query prior to passing it off to validation/execution.  Is there a more straightforward way of doing this?

**Comment by sungam3r** [comment]
Maybe you can use default arguments? Then the user will not be required to specify additional arguments. And if you want to determine the value of the argument yourself (some restrictions), you can do it in the resolver using either the passed value or your own.

**Comment by sungam3r** [comment]
@amoore-incomm Is this issue still actual for you?

**Comment by amoore-incomm** [comment]
@sungam3r, thanks for the above response. I believe i did use something similar to that, although my memory escapes me now.   Issue can be closed...thank you!
