### ISSUE TITLE
Add GraphQL.SystemTextJson project

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1449]
Relates to #1148, #1448

**Comment by sungam3r** [comment]
https://aloiskraus.wordpress.com/2019/09/29/net-serialization-benchmark-2019-roundup/

**Comment by benmccallum** [comment]
Let me know if you need help, or if we need to do something in the server project. Happy to split the workload.

**Comment by benmccallum** [comment]
Perhaps we should create an issue over on that repo and lay out the plan?

**Comment by sungam3r** [comment]
I will not be engaged in this task in near future. There are several other bugs on my todo list that need to be worked on. I also need to open source csharp graphql generator. All this will take quite a while. You can work on PR if you wish.

**Comment by benmccallum** [comment]
@sungam3r, I'll do this in the next day or so. Please assign the issue to me. Cheers

**Comment by sungam3r** [comment]
Fixed by #1512 , thanks to @benmccallum .
