### ISSUE TITLE
Query variables into traces.

### ISSUE THREAD

**Issue by Aitorsc7** [graphql-dotnet/graphql-dotnet#1453]
## Summary

Add the query variables to the traces.

### Basic example

When looking at the graphql traces I can see the query string, but the variables are not there so I can just see the name of the variable not its actual value.

### Motivation

It will be very useful for diagnose problems using tracing. Sometimes the problem is just a not correct variable and will be good to have all in the same place.

**Comment by sungam3r** [comment]
What traces are you talking about? Can you give an example?

**Comment by Aitorsc7** [comment]
I'm talking about Apollo traces.

**Comment by sungam3r** [comment]
> When looking at the graphql traces I can see the query string

What is `query string` ? Trace contains only the names of the fields and return types along with their paths and processing time. Example:
```json
 "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2020-01-08T22:33:40.3100402Z",
      "endTime": "2020-01-08T22:33:40.3100402Z",
      "duration": 487600,
      "parsing": {
        "startOffset": 1700,
        "duration": 30200
      },
      "validation": {
        "startOffset": 34900,
        "duration": 344400
      },
      "execution": {
        "resolvers": [
          {
            "path": [
              "hero"
            ],
            "parentType": "Query",
            "fieldName": "hero",
            "returnType": "Character",
            "startOffset": 411700,
            "duration": 6400
          },
          {
            "path": [
              "hero",
              "friends"
            ],
            "parentType": "Droid",
            "fieldName": "friends",
            "returnType": "[Character]",
            "startOffset": 439800,
            "duration": 8599
          },
          {
            "path": [
              "hero",
              "friends",
              0,
              "name"
            ],
            "parentType": "Human",
            "fieldName": "name",
            "returnType": "String",
            "startOffset": 468000,
            "duration": 1699
          },
          {
            "path": [
              "hero",
              "friends",
              1,
              "name"
            ],
            "parentType": "Droid",
            "fieldName": "name",
            "returnType": "String",
            "startOffset": 474400,
            "duration": 899
          }
        ]
      }
    }
  }
}
```

In addition, there is a [specification](https://github.com/apollographql/apollo-tracing) for this format. Could you please clarify what exactly and in what part of this format do you want to receive?

**Comment by sungam3r** [comment]
This issue will be closed after month of inactivity. Waiting feedback from @Aitorsc7 .

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
