### ISSUE TITLE
How to get data from multiple sources from a single query

### ISSUE THREAD

**Issue by Ian-ResDiary** [graphql-dotnet/graphql-dotnet#1455]
## Summary

We're currently investigating using GraphQL for a new API that will sit as a proxying layer to various other GraphQL back end services.  Ideally we'd like to make the source of the data transparent to our API consumers by having it appear as a single query.  An example of one of our queries might be:

```
query {
   booking {
      id   
      reference
   }
   customer(id: 3) {
        name        
    }
}
```

where booking comes from one GraphQL back-end service and customer another.  Our thoughts for how we achieve this would be to call out to the relevant back-end service from the `resolve` method of each Field definition but we're having some issues with getting the part of the query we'd like to pass on.  As an example for the customer we'd like to be able to extract 

```
customer(id: 3) {
   name        
}
```

so we can pass that query to the relevant service.  However, we can't seem to get access to the part of the query we need from the `ResolveFieldContext` passed into the `resolve` method.  Is there any way we can extract this fragment of the query so we can pass it on to the relevant service?

**Comment by sungam3r** [comment]
Did you look at federared schemas?

**Comment by Ian-ResDiary** [comment]
Thanks for the response.  Federated schemas does seem interesting but I can't really see any information about it in your documentation.  Does it require using Apollo?

If we weren't to use federated schemas do you know if there's a way to get the part of the query from the `ResolveFieldContext` that it is using?  If we could do that I think we could then at least pass the GraphQL query on to our sources.

**Comment by sungam3r** [comment]
Unfortunately I can not help with advice, I myself have not yet figured out how federated schemas work.

**Comment by Ian-ResDiary** [comment]
Ok, I guess our alternative will be either to look into parsing and splitting the string manually or potentially using something like gRPC for our inter-service communications.  Thanks for the responsive and if you don't think the framework supports this already or is likely to then feel free to close this ticket.

**Comment by joemcbride** [comment]
There is a class called `Document` which represents the Abstract Syntax Tree (AST) of the query.  This is available on `ResolveFieldContext`, though you can also build that class yourself and add it to the `ExecutionOptions` that are passed to the `DocumentExecutor`.  You can use that to find the requested field.

Yes you would have to use the Apollo engine to get the full use of federated schemas, unless you want to try to re-write that functionality yourself (not really recommended).

Here’s a full example of federated schemas, with a few node based schemas and one in .NET.

https://github.com/joemcbride/gql-presentation/tree/master/demos/6%20-%20federation
https://github.com/joemcbride/gql-presentation/tree/master/demos/6%20-%20federation/services/accounts

**Comment by joemcbride** [comment]
```
var query = “query { ... }”;
var builder = new GraphQLDocumentBuilder();
var document = builder.Build(query);
```

**Comment by nbarbettini** [comment]
@Ian-ResDiary Sorry if I'm dumbing down your question too far, but it _is_ possible to do this with just a resolver if you only need the `id: 3` argument and not the `{ name }` sub-selector:

```csharp
Field<CustomerType>("customer")
    .Argument<int>("id")
    .ResolveAsync(async context =>
    {
        var idArg = context.GetArgument<int>("id");
        return await customerService.GetAsync(id);
    });
```

If I've misunderstood and what you're trying to do is construct a "smart" query to the customer system that only retrieves the Name field because the GraphQL request was `{ name }`, then you do need the AST parsing stuff that @joemcbride mentioned. 🙂

**Comment by sungam3r** [comment]
Answered in https://github.com/graphql-dotnet/graphql-dotnet/issues/1455#issuecomment-566575816
