### ISSUE TITLE
Code for 3.0.0-preview-1352

### ISSUE THREAD

**Issue by DavidKiff** [graphql-dotnet/graphql-dotnet#1458]
# Summary
Two questions: 
1. I can't find the code for 3.0.0-preview-1352.  There's no "release" for this in git hub or any tags on any branch for this version.  Where can I find this code?

2. How do I intercept (and time) messages sent to Graph QL over sockets?  I intercepted in middleware for HTTP, but the middleware doesn't see the socket frames.  I cant find any documentation on this.

Thanks in advance.

### Environment (if relevant)
Windows
.NET Core 3

**Comment by joemcbride** [comment]
1) the 3.0 code is in the master branch
2) are you using the Server project or writing your own middleware with websockets?  The code for the server project websockets is found here: https://github.com/graphql-dotnet/server/tree/develop/src/Transports.Subscriptions.WebSockets

**Comment by DavidKiff** [comment]
Perfect, thanks!  I am using the web sockets project, will dig through that!  Thanks a lot!

**Comment by StefanSchoof** [comment]
Is https://github.com/dotnet/sourcelink a idea to provide a good link between the nuget packages and the source code?

**Comment by sungam3r** [comment]
Integration with sourcelink is in my personal todo list.

**Comment by SimonCropp** [comment]
@sungam3r hows this https://github.com/graphql-dotnet/graphql-dotnet/pull/1475

**Comment by sungam3r** [comment]
@SimonCropp Thanks. You got ahead of me. I've always been approaching new things for quite some time, after studying the documentation first.

**Comment by Shane32** [comment]
Relating to the original question, is there a way to tell exactly which commit was used to build a specific 3.0 preview nuget package?  The releases tab here on github doesn't show anything newer than 2.4.

**Comment by SimonCropp** [comment]
did u check tags?

**Comment by joemcbride** [comment]
@Shane32 

1) Browse to https://github.com/graphql-dotnet/graphql-dotnet/commits/master
2) Click on one of the green checkboxes for a commit.  That will take you to the build on AppVeyor.
3) Look a the build number in the top right.
4) Click on the `Artifacts` tab and you can see the created nuget packages

**Comment by shani117** [comment]
Hi @joemcbride , while we are on the 3.0 preivew topic, what is the roadmap for its release? We are planning to take our app to production but would love to have a official released package for reference instead of preview. Thoughts on that? 

Thanks,
Shahnaz.

**Comment by andrewpaulicek** [comment]
I would also like to ask @joemcbride if there are any plans on making `GraphQL.NewtonsoftJson` with async writing capabilities. 

Thanks!
Andrew

**Comment by sungam3r** [comment]
Relates to #1321

**Comment by sungam3r** [comment]
SourceLink support was added, closing.
