### ISSUE TITLE
Is there a published roadmap?

### ISSUE THREAD

**Issue by Sacrilege** [graphql-dotnet/graphql-dotnet#1459]
I see there has been at least some support added for Apollo federation in master. It's been a while since there has been a new release and I'm very interested in knowing when that might be released. I need to know if I should take the project I'm working on in a different direction or not.

**Comment by joemcbride** [comment]
This is the roadmap for an official 3.0 release, though there have been several pre-releases of 3.0.

https://github.com/graphql-dotnet/graphql-dotnet/milestone/4

Once all or most of those items are complete, 3.0 will be officially released.  Several people are using 3.0 pre-releases in production.  The only reason for not officially releasing 3.0 are some planned breaking changes in that list still (overall they will be minor, with perhaps the exception of changes to how serialization is handled with trying to support `System.Text.Json`).

**Comment by robotrick** [comment]
hi @joemcbride  , do you already know when the release will be finished?

**Comment by robotrick** [comment]
@joemcbride : our company would like to contribute, to get the 3.0 release ready as soon as possible. We are round about 25 senior .net developer, if you need manpower...?!

**Comment by sungam3r** [comment]
@robotrick Some issues from https://github.com/graphql-dotnet/graphql-dotnet/milestone/4 require not so much implementation as understanding, #1151 for example. PRs are always welcome.
