### ISSUE TITLE
From NameValidator.cs, restriction of "__" (double underscore) to restrictive?

### ISSUE THREAD

**Issue by jan-johansson-mr** [graphql-dotnet/graphql-dotnet#1465]
## Summary
Some reserved keywords exists in the implementation, e.g. `__typename` used by GraphQL introspection (maybe the only reserved keyword?). The keyword is prefixed by double underscore characters. It seems that because the keyword starts with double underscore that double underscore prefix is prohibited for others to use.

## Restrictiveness
Some restrictiveness may be warranted, as reserved keywords, but if prefixes gets lumped into the same category, then it might be too restrictive. E.g. I want to follow the same pattern and start other keywords with underscore (cohesive pattern of keywords). But the restriction of double underscore forces me to use either one single underscore or more than two.

I can still introduce keywords, as long as they don't have double underscore. Why is there a restriction of double underscore? I have looked for justification at [GraphQL org](https://graphql.org/) but can't find it.

**Comment by joemcbride** [comment]
See the last paragraph of this section:

https://graphql.github.io/graphql-spec/draft/#sec-Schema

> All types and directives defined within a schema must not have a name which begins with "__" (two underscores), as this is used exclusively by GraphQL’s introspection system.

**Comment by sungam3r** [comment]
> E.g. I want to follow the same pattern and start other keywords with underscore

As @joemcbride said you cannot create new keywords as the specification prohibits this explicitly. But you can always create your own fork and try to implement what you intended there.

**Comment by jan-johansson-mr** [comment]
Thanks for clarification, however, this issue can be viewed as regarding two separate concerns. I'm not talking about GraphQL keywords, these ofcourse are reserved for GraphQL. I'm talking about metadata attached to models that are produced by queries to GraphQL. I don't find that creating keywords are prohibited, but the restriction of double underscore is there (it is a strange restriction, but okay, no problems).

**Comment by joemcbride** [comment]
> I'm talking about metadata attached to models that are produced by queries to GraphQL.

Can you provide an example?  Do you mean field and type names or something else?

**Comment by jan-johansson-mr** [comment]
Absolutely, a quick glance :-)

Let's assume polymorphic type `Person` that can be either `PrivatePerson` or `PublicPerson`. Then the returned response from a query can be:

```
[
{
  "_type": "PublicPerson",
  "name": "Foo"
},
{
  "_type": "PrivatePerson",
  "name": "Bar"
}
]

```

The client can then resolve what to do with the types. In my case I've written a plugin to `System.Text.Json` that acts on this and resolve to proper type out-of-the-box neat and smooth!

Again, there is no problem with specification stating that anything that starts with double underscore is prohibited. I simply let it start with single underscore and it works fine. But it would have been neat to call it `__xxx` something (not colliding with reserved GraphQL keywords though).

Thanks,
//Jan

**Comment by pekkah** [comment]
Spec already includes __typename for that purpose

**Comment by jan-johansson-mr** [comment]
Nope, it returns GraphQL types for __typename, not the types in the payload.

Den mån 30 dec. 2019 08:59Pekka Heikura <notifications@github.com> skrev:

**Comment by sungam3r** [comment]
@jan-johansson-mr I did the same thing you want for `Newtonsoft.Json`. I used `__typename` to achive this.

> Nope, it returns GraphQL types for __typename, not the types in the payload.

What is the **payload type** ? The response is deserialized on the side that does not know anything about server implementation. You have access to GraphQL types only (via introspection). You can generate the necessary classes and use them. I wrote a special generator for these purposes, which also supports polymorphic output types. We actively use it in production in dozens of microservices. I’m going to open source it for a long time. I just don’t have enough time for this. I think that the upcoming holidays will help to find time.

**Comment by jan-johansson-mr** [comment]
No worries, I used `__typename` first, it produced GraphQL type (introspection), not the typename of the actual type in the payload. I'm going to make another go, and maybe you're right. However, it didn't work for me. But as I said, going to look to it one more time. Thanks for your time.

**Comment by jan-johansson-mr** [comment]
Hi again, now I think I know what is going on...

To the example of `Person` as given above. Let's assume we define the person GraphQL type as the following:

`public class PersonType : ObjectGraphType<Person>...`

Again, the `Person` type is generic and can be either `PrivatePerson` or `PublicPerson`.

Quering our GraphQL endpoint with something like `...{__typename,name}...` yields the result `{..."__typename":"PersonType","name":"foo"...}`, and not (e.g.) `{..."__typename":"PublicPerson","name":"foo"...}` (instantiated generic type in the `ObjectGraphType<Person>` declaration).

I'm using version `3.0.0-preview-1352` of this excellent project!

Thanks

**Comment by sungam3r** [comment]
> not the typename of the actual type in the payload. 

For you there **should not be** such a thing as the _type of payload_. You are probably trying to use the same .NET library on the client side. By doing so, you are tied tightly to implementation details, bypassing the public api side. If you have `PrivatePerson` / `PublicPerson` types in your *implementation*, but they are not represented in any way in your public GraphQL API, then this is the same as they do not exist. In order to use these types at least somehow, they must be represented as graph types. This may help - https://github.com/graphql-dotnet/examples/blob/master/src/StarWars/Types/DroidType.cs#L22

**Comment by jan-johansson-mr** [comment]
Closing this now. I liked the link to the graphql standard, thanks!
