### ISSUE TITLE
GraphQL.Utilities.GetRequiredService vs. Microsoft.Extensions.DependencyInjection.GetRequiredService

### ISSUE THREAD

**Issue by StefanSchoof** [graphql-dotnet/graphql-dotnet#1467]
## Summary

Graphql has a own GetRequiredService Extension Method 
https://github.com/graphql-dotnet/graphql-dotnet/blob/111c5da3080ed55c21779093075ad5bd19967bc0/src/GraphQL/Utilities/ServiceProviderExtensions.cs#L12

There is a method with the same name in dotnet https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderserviceextensions.getrequiredservice?view=dotnet-plat-ext-3.1

## Relevant information

I find it odd that a library has a function with the same name (and as far I can see with the same purpose) as in dotnet.
I found no documentation when I should use the graphql-dotnet Version? Is there a reason to have this with the same name in graphql-dotnet or is this an mistake.

**Comment by sungam3r** [comment]
This is done on purpose so as not to have an unnecessary dependency. I will add a comment to the method.

**Comment by StefanSchoof** [comment]
Thanks, for the info.
