### ISSUE TITLE
Roadmap Page here for graphql-dotnet?

### ISSUE THREAD

**Issue by pkellner** [graphql-dotnet/graphql-dotnet#1472]
I'd love to have some idea of what's might be coming when. I've got a project I've been working with that is in asp.net core 2.2 and I'd love to at some point move to a full release version with asp.net core 3.1. I keep checking the nuget packages to see if there is a released 3.1 version but don't see it.

I do know there are pre-release versions but at the moment my plate is pretty full and really want to move when you all think it's really ready for full release.

Thanks -Peter

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/milestone/4

GraphQL-dotnet is transport-agnostic package and will continue to target netstandard (2.0/2.1), it is not ASP.NET Core 2.2/3.0/3.1 specific.

**Comment by pkellner** [comment]
Thanks @sungam3r . When I look at the graphql dependencies page
https://www.nuget.org/packages/GraphQL/
It's not clear to me what version of netstandard goes with graphql-dotnet
When I look at asp.net core 3.0 on this page
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
it shows netstandard 2.1 is needed for asp.net core 3.0
Can you help me understand what the timing goals are for netstandard 2.1 or where that is tracked? I don't see anything about netstandard on the milestone page you mention (sorry if I'm just missing it).
I'm also not understanding what "Milestone 3" means.  Does that correspond to netstandard 2 or 2.1?

**Comment by sungam3r** [comment]
> It's not clear to me what version of netstandard goes with graphql-dotnet

1.3 and 2.0 for 2.4.0 and 2.0 for 3.0.0-preview

> netstandard 2.1 is needed for asp.net core 3.0

Yes, for asp.net core 3.0, but graphql-dotnet itself has nothing that requires netstandard2.1 (yet).

> Can you help me understand what the timing goals are for netstandard 2.1 or where that is tracked?

I do not understand. What goals for netstandard2.1? New version of netstandard is required if package use some specific APIs that available only in new version. We do not use those APIs (yet).

@joemcbride created all milestones and I honestly don’t stick to work on the tasks inside milestones. I take to work those tasks that interest me.
