### ISSUE TITLE
What about JSON columns in SQL Server?

### ISSUE THREAD

**Issue by wdamaral** [graphql-dotnet/graphql-dotnet#1490]
So, I'm researching about graphql + core + sql server.
The reason is that I'm trying to understand possibilities so my team and I can decide which technologies we're going to use on a new project.

The company today is pretty much dependent on Microsoft. The plan is to move from a local software (VB.NET + C#) to web. The database is internal, SQL Server (it could be either 2016 or 2019 - not decided yet). Today it's 2012.
One of the points that came up is to have a database with mixed columns - _JSON and regular_ - because for some of the products, it's impossible to know their structure of data.
The suggestion that came from the team is to have a stack where we can implement **GraphQL**.
The initial plan is to have **React + ASP Core + GraphQL + SQL Server 2016.**

I found good information about this library as well as some tutorials but none of them mentions the JSON columns (Or I couldn't find them).

My question is: Can I have relational + JSON columns mapped with this library so that I'll be able to filter them?
Is there any tutorial/documentation that show example of such implementation?
If you have anything to share, I'd be very happy with your help!

**Comment by sungam3r** [comment]
1. This is the **core** repo and it is DB-agnostic. GraphQL itself is DB-agnostic. There is no code and never will be any code interacting with databases anyway.
2. You can do anything you want **manually** - filtering, graphql-sql mappings, json support, etc.
3. There are a number of projects to solve GraphQL-DB translations. You may look at https://github.com/SimonCropp/GraphQL.EntityFramework or https://github.com/chkimes/graphql-net for example. See the documentation in the relevant projects.

**Comment by wdamaral** [comment]
I see your point but no quite understood what you meant.
So, let's say I have a table products, with id, name, description, and another json column called specification.

The specification could be anything in a JSON format.

I've read on your documentation about custom SCALAR fields. Would I have to create one that would receive that serialized object from the database? So the logic of serializing and deserializing is up to me?

**Comment by sungam3r** [comment]
Yes, it is up to you.

Relates to #474
