### ISSUE TITLE
Allow interfaces to implement other interfaces

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1497]
New feature from graphql spec: graphql/graphql-spec#373

**Comment by darrenhull** [comment]
Any info on this being implemented? Its not great that this framework is lagging this far behind the specification.

**Comment by sungam3r** [comment]
Not yet. Maybe in v5.

**Comment by sungam3r** [comment]
Parser v8 (dev) supports that feature. @Shane32 it may be a challenge to support it here.
