### ISSUE TITLE
Apollo Graph Manager - metrics agent

### ISSUE THREAD

**Issue by mac2000** [graphql-dotnet/graphql-dotnet#1502]
If I understand everything correct there is apollo compatible metrics provided out of the box but no agent to stream them to apollo graph manager?

Wondering if this is on a roadmap or can we somehow participiate in providing this?

**Comment by sungam3r** [comment]
> but no agent to stream them to apollo graph manager?

I don't know about such feature. Could you provire additional info/specs?

**Comment by joemcbride** [comment]
Previously Apollo had their own proxy that you would run in front of your GraphQL server.  It looks like they have changed that and have it just built-in to the Apollo Server, as well as documented how to just push to it directly.

https://www.apollographql.com/docs/graph-manager/setup-analytics/

**Comment by mac2000** [comment]
After looking around found few places:

- document execution listeners - will not work, `AfterExecutionAsync` is being called before `metrics.Finish()` 
- `RequestExecutedAsync` virtual method in `GraphQLHttpMiddleware` seems to be a good staring point inside it we have performance metrics so can try to do something with them

**Comment by sungam3r** [comment]
If so then this issue can be moved to server project.

**Comment by mac2000** [comment]
Yes, seems like so, I'm closing this one in favor to [#305](https://github.com/graphql-dotnet/server/issues/305), thank you
