### ISSUE TITLE
How to construct stored procedure parameters from the root node.

### ISSUE THREAD

**Issue by jparaya** [graphql-dotnet/graphql-dotnet#1504]
We have a complex object (Sales) with several properties. To reduce the DB calls, we also have a stored procedure. This SP just returns all the required data (via flags) and then on runtime we map the call back to our model. This stored procedure has several boolean parameters, like "@includeEquipments", "@includeCustomerInformatoin", etc. Depending on those values the SP queries more, or less data, depending on the flags.

I want to use graphQL to construct that SP, because now we are just abusing it. No matter what the data we need, we have a lot of Web API to get all the data, to then filter on runtime. 

Is it possible to traverse over the root query and its children nodes to check how many of this boolean values need to be active? Something like:

  ```
  public class MySalesQuery : ObjectGraphType
    {
        public MySalesQuery(my_service_to_call_the_store_procedure the_sp)
        {
            FieldAsync<Types.SalesType>(
                "Sales",
                arguments: new QueryArguments(new QueryArgument<IdGraphType> { Name = "id" }),
                resolve: async context => 
                {
                    // initial flags for the stored procedure
                    var the_flags = new {
                        includeSale: true 
                        includeEquipments: false
                        includeSomethingElse: false
                    }

                    // Here somehow analize each field in the query to get the flags:
                    // calling the already constructed graph of required fields and subfields
                    context.ThisField.SubFields.Foreach(subField => subField.MarkQuery(the_flags));

                    return the_sp.MyMappedStoredProcedure<Sales>(the_flags);
                });
        }
    }
```
I can extend the `ObjectGraphType` to implement the MarkQuery. I just need access to the list of fields and subfields to identify them in each type.

Is it possible? or is better to just pre-analize the JSON query and define the SP flags before executing the query?

I checked the DataLoader implementation, but it's not exactly what I need. I need to go to the database only once. While reviewing the codes, I noticed you construct the root node and then start executing from it. Then, you go over the subfields to executed them, to then go over the root.ChildNodes() (example: `ParallelExecutionStrategy.ExecuteNodeTreeAsync`).  That means at some point you constructed the graph. Can I use that graph to get the flags?

**Comment by sungam3r** [comment]
You can inspect `context.Document` with `INodeVisitor`. See validation rules as examples:
https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL/Validation/Rules

**Comment by jparaya** [comment]
Works like a charm. Thanks!

I can resolve the flags at the first level of the queries. Didn't try with inner levels, but I guess the approach is similar. Here is how I did it, just for the record:

```
foreach (var item in context.SubFields)
{
    var fieldDefinition = ExecutionHelper.GetFieldDefinition(context.Document, context.Schema, (IObjectGraphType)context.FieldDefinition.ResolvedType, item.Value);

     // I added to each Field that requires to set the flags an Action<SalesQueryParams>
    if(fieldDefinition.Metadata.ContainsKey("queryParams"))
    {
        ((Action<SalesQueryParams>)fieldDefinition.Metadata["queryParams"])(theStoredProcedureParams);
    }
}

myService.TheSPCall(theStoredProcedureParams);

```
Thanks again!
