### ISSUE TITLE
Updated Roadmap w/Timeline

### ISSUE THREAD

**Issue by drobertson123** [graphql-dotnet/graphql-dotnet#151]
I have been watching this closely and it looks like everyone has been extremely busy. BTW great work.

Is there any chance you feel like you are getting close enough to a V1 to update us on when we can look forward to a Go Live version of this? 

I understand the variability of open source dev projects, but some further guidance would be very welcome.

**Comment by joemcbride** [comment]
Thanks for watching the project!

As per timeline, I don't have an exact answer for you unfortunately.  The last part of what I would would think of a `1.0` release would be the completion of validation.  There are 5 validation rules left out of 24.  4 of those should take an hour or less each (PRs welcome!).  The 5th could take several days of dev time ([merge overlapping fields](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/OverlappingFieldsCanBeMerged.js)).  After those 4 rules are done I would basically consider that 1.0.

I have plans for [a new parser](https://github.com/graphql-dotnet/graphql-dotnet/pull/127).  That will probably get merged before the overlapping fields validation.

I also have plans for [a drastic api change](https://github.com/graphql-dotnet/graphql-dotnet/pull/91).  That won't happen anytime soon, maybe next year sometime.  Maybe never.

I do know that some people have this in production already (some for 8+ months).  You'll have to make the choice yourself on when it is ready enough for you.

### Now (over the next month)
* 4 remaining validation rules

### Near future (2-3 months)
* New Parser (dropping Antlr)
* dotnet core support
* PCL support

### End of year, early next year
* Overlapping fields validation

### Far into the future, maybe never
* Instance-based vs. Type-based api

**Comment by drobertson123** [comment]
I understand that timelines are tough, especially on open source projects, but the details you just gave are very helpful. Thanks for that and keep up the good work.

I was hoping the new parser would replace Antlr before I got going but that isn't a huge deal. It will be nice to have that dependency gone.

I will be using graphql-dotnet in a prototype project over the next 3-4 weeks. My goal is to create a test replacement of a current API that is a mix of ASP.NET MVC and Razor. I would really like to move to a React.js front end and GraphQL-dotnet on the backend. 

If I can get a better handle on how everything works and free some time I would be happy to pitch in. This project does a great job of meeting a specific need I have. Thanks.

**Comment by joemcbride** [comment]
Good news for you, you can use the new parser today with a nuget built from the branch!  I have been keeping the new parser branch up to date with master.

Point your nuget package file or Visual Studio to:

https://ci.appveyor.com/nuget/graphql-dotnet

And choose a nuget from that branch.  Latest version for that branch is 0.10.2.444.

Or, you can download the nuget directly: https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/build/0.10.2.444/artifacts

**Comment by joemcbride** [comment]
One thing of note - the project currently ILMerge's the Antlr runtime, so you pretty much shouldn't notice a difference between the two packages.  You would only notice a difference if for some reason you were using the `AntlrDocumentBuilder` directly.  The current New Parser branch ships with both Antlr and the new one, for compatibility for a release or two.

**Comment by drobertson123** [comment]
great, I will work from that one. Thanks.

**Comment by joemcbride** [comment]
Going to close this as this is pretty out of date.  Thanks!
