### ISSUE TITLE
How to use GraphQL in .net framework with ADO.NET

### ISSUE THREAD

**Issue by yaswanth25938** [graphql-dotnet/graphql-dotnet#1514]
I can see lot of articles about using graphql in .net core with Entity Framework. But I want to use the GraphQL in with ADO.NET. Is there any way to connect the GraphQL resolver to the ADO.NET??

**Comment by sungam3r** [comment]
You can do anything in your resolver.  You can execute an arbitrary ADO.NET request to your database and return data through GraphQL API.

**Comment by yaswanth25938** [comment]
Do you have any example/sample code of ado.net setup and connecting it to graphql.

**Comment by sungam3r** [comment]
We do not have such an example in the example repositories. The fact is that GraphQL is in no way database specific, so in the resolver you can use the same ADO.NET (or other technology) code as you would use without GraphQL. Also you may ask @SimonCropp about ADO.NET usage/examples and look at https://github.com/SimonCropp/GraphQL.EntityFramework . In any case, this repository is not the place where database access issues are resolved.

**Comment by sungam3r** [comment]
@yaswanth25938 I advise you to ask this question in https://github.com/SimonCropp/GraphQL.EntityFramework

As I said earlier this repository is not the place where database access issues are resolved.
