### ISSUE TITLE
null is returned for NonNullGraphType when there's an error

### ISSUE THREAD

**Issue by johnnyoshika** [graphql-dotnet/graphql-dotnet#1516]
## Description

null is returned for NonNullGraphType if there's an error in the resolver. This is a follow-up to this question on StackOverflow: https://stackoverflow.com/q/59971333/188740

### Steps to reproduce

Define a query field like this:

```
            Field<NonNullGraphType<WidgetType>>(
                "exception",
                resolve: context =>
                {
                    throw new ExecutionError("Something went wrong!");
                }
            );
```

Then send a request like this:
```
{
  exception{
    id
  }
}
```

The response you'll see will contain a null value for the `exception` field, even though it's a non-nullable type.
```
{
  "data": {
    "exception": null
  },
  "errors": [
    {
      "message": "Something went wrong!",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "exception"
      ]
    }
  ]
}
```

Alternatively, clone this repo and run the project that demonstrates this problem: https://github.com/johnnyoshika/graphql-dotnet-null

### Expected result

According to [the spec](http://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability), null should not be returned for non-null types.
Excerpt:

> Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.

So the expected result would be:
```
{
  "data": null,
  "errors": [
    {
      "message": "Something went wrong!",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "exception"
      ]
    }
  ]
}
```

### Actual result

```
{
  "data": {
    "exception": null
  },
  ...
}
```

### Environment

GraphQL.Server.Transports.AspNetCore version 3.4.0

**Comment by sungam3r** [comment]
Please first try the latest GraphQL.Server.Transports.AspNetCore preview version.

**Comment by johnnyoshika** [comment]
@sungam3r  Will do!

Can you please advise what the replacement for this is in the preview version of `GraphQL.Server.Transports.AspNetCore`? It looks like `IDependencyResolver` is obsolete and I should be using `IServiceProvider`.

```
services.AddScoped<IDependencyResolver>(s => new FuncDependencyResolver(s.GetRequiredService));
```

Thanks!

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/dependency-injection.md

**Comment by johnnyoshika** [comment]
@sungam3r I can't seem to get version `3.5.0-alpha0027` working. I tried different combinations of registering dependencies, but I keep getting an empty 500 response.

The [documentation](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/dependency-injection.md) points to an outdated [See this example](https://github.com/graphql-dotnet/examples/blob/8d5b7544006902f45b818010585b1ffa86ef446b/src/AspNetCoreCustom/Example/Startup.cs#L16-L34) example.

Can you please look at my Startup here and let me know what I'm doing wrong?
https://github.com/johnnyoshika/graphql-dotnet-null/blob/graphql-net-3.5-prerelease/Startup.cs

I also tried manually registering IDocumentExecuter, IDocumentWriter, and all of the graph types as singletons, but the response was the same (i.e. empty 500 response).

Thanks!

**Comment by sungam3r** [comment]
> The documentation points to an outdated See this example example.

You look not at master branch.

Here your working example:  
[graphql-dotnet-null-master1.zip](https://github.com/graphql-dotnet/graphql-dotnet/files/4135194/graphql-dotnet-null-master1.zip)

I changed this
```c#
 public MySchema(IServiceProvider resolver) : base(resolver)
        {
            Query = resolver.GetRequiredService<MyQuery>();
        }
```
\+
```c#
 services.Configure<KestrelServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });
```
and removed this
```c#
     services.AddScoped<IDependencyResolver>(s => new FuncDependencyResolver(s.GetRequiredService));
```

**Comment by johnnyoshika** [comment]
@sungam3r Excellent! I tested it and everything behaves as expected in v3.5 prerelease. `data` is no longer returned when there's an error and the return type is NonNullGraphType.

## Example

### Request
```
{
  exception {
    id
  }
}
```

### Response
```
{
  "errors": [
    {
      "message": "Something went wrong!",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "exception"
      ]
    }
  ],
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2020-01-30T17:26:44.9888177Z",
      "endTime": "2020-01-30T17:26:44.9908177Z",
      "duration": 2128500,
      "parsing": {
        "startOffset": 1630100,
        "duration": 26999
      },
      "validation": {
        "startOffset": 1666000,
        "duration": 71700
      },
      "execution": {
        "resolvers": [
          {
            "path": [
              "exception"
            ],
            "parentType": "MyQuery",
            "fieldName": "exception",
            "returnType": "WidgetType!",
            "startOffset": 1765200,
            "duration": 152899
          }
        ]
      }
    }
  }
}
```

**Comment by sungam3r** [comment]
I saw it.

**Comment by sungam3r** [comment]
Closed as resolved.
