### ISSUE TITLE
How to get dependency into ObjectGraphtype

### ISSUE THREAD

**Issue by RedEyedDog** [graphql-dotnet/graphql-dotnet#1517]
## Summary
Using Field<AccountGroupType>() is throwing a error, need a parameter less constructor.
How do i get the dependencies into AccountGroupType?

I have implemented IDependencyResolver in the startup.cs and is used when creating schema 

What am i doing wrong?

**Comment by sungam3r** [comment]
You should specify dependencies as constructor arguments.

**Comment by RedEyedDog** [comment]
Hi sorry for the late reply.. the answer was, i wasn't passing the IDependencyResolver to the base schema.. which meant it couldn't use it to resolve the field types
