### ISSUE TITLE
generate schema file at runtime

### ISSUE THREAD

**Issue by furesoft** [graphql-dotnet/graphql-dotnet#1518]
can i generate a schema file at runtime for my api?

**Comment by michal-ciechan** [comment]
Did this ever get an answer? I am trying to figure out the same. Trawling through the docs last half hour, no luck... Need a `schema` file/definition to pass into relay-compiler

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs

**Comment by michal-ciechan** [comment]
Shall I write a section for it in docs and PR? I think it is worth adding a "Print Schema" with a sample of using this code, in case someone else has this issue. It seems like more and more tools are using these schemas to scaffold client-side code.

**Comment by michal-ciechan** [comment]
Just for anyone stumbling upon this, I ended up using `graphql-cli get-schema` in the node world.

See this SO Answer [Get GraphQL whole schema query](https://stackoverflow.com/a/42010467)

Might potentially be easier if you are using GraphQL in the node/web world anyway (e.g. I am using react-relay)

**Comment by sungam3r** [comment]
@michal-ciechan PRs are welcome. Just make sure this is not really in the current documentation.
