### ISSUE TITLE
How to use schema first approach to recreate the Star Wars example

### ISSUE THREAD

**Issue by TWry** [graphql-dotnet/graphql-dotnet#1519]
Let's suppose I have .graphql definition files for all of the types in my project and also a file defining the query and mutations. (In this case the happen to be generated by the OpenAPI generator.) I wonder how I can use those to setup a GraphQL API similar to the Star Wars example. I'm struggling because the Star Wars example follows the GraphType first approach and I can't seem to find documentation or examples showing how to create an API using the schema first approach. Can someone please point me in the right direction or provide a code snippet?

**Comment by sungam3r** [comment]
You can find examples and tests in this repo by search `Schema.For(` and `Types.Include<`.

**Comment by TWry** [comment]
Thanks for the quick reply. I saw the Schema.For and Types.Include in the documentation, but I have no clue to assemble this to create the API. The introductory examples only show how to construct an immediately executed query against a schema. I'd like to set up an API like in the Star Wars example where the types, schema, query, mutations and data providers are added in the Startup.cs file.

**Comment by joemcbride** [comment]
For this example:

Remove all these lines: https://github.com/graphql-dotnet/examples/blob/e127634f684470f1bcc7fa11e9912a7aee4ae9af/src/AspNetCore/Example/Startup.cs#L16-L24

Add this line:

```csharp
services.AddSingleton<ISchema>(s => Schema.For("query { ... }"));
```

For defining the Schema.

You would also have to write your own handler classes in the Schema First way (Query, Droid, etc.) as shown in the intro docs:

https://graphql-dotnet.github.io/docs/getting-started/introduction#schema-first-nested-types

**Comment by TWry** [comment]
Many thanks for your help. I've now been able to add the types and schema. 

I'm still unclear though about the latter part concerning the handler classes. Could you please provide a minimalistic code snippet for this as well?

**Comment by joemcbride** [comment]
These are the "handler" classes, or, the classes which implement the Resolvers for each of your Fields on your Types.

```csharp
public class Query
{
  [GraphQLMetadata("hero")]
  public Droid GetHero()
  {
    return new Droid { Id = "1", Name = "R2-D2" };
  }
}

[GraphQLMetadata("Droid", IsTypeOf=typeof(Droid))]
public class DroidType
{
  public string Id(Droid droid) => droid.Id;
  public string Name(Droid droid) => droid.Name;

  // these two parameters are optional
  // ResolveFieldContext provides contextual information about the field
  public Character Friend(ResolveFieldContext context, Droid source)
  {
    return new Character { Name = "C3-PO" };
  }
}
```

**Comment by TWry** [comment]
Ok, got it now, many thanks again. 

Now, I'm sorry to have to ask another follow-up question , but I can't figure out how to hook up a store or dataloader to the query/schema. Could you explain how dependency injection works in this case?

**Comment by valorad** [comment]
How does the `Query` class handle dependency injection?

I get this exception if `Query` class has a dependency:

```
System.MissingMethodException: No parameterless constructor defined for type 'App.Controllers.Graphs.Query'.\r\n
at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)\r\n
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)\r\n
at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)\r\n 
at System.Activator.CreateInstance(Type type)\r\n  
at GraphQL.DefaultServiceProvider.GetService(Type serviceType)\r\n
```

**Comment by sungam3r** [comment]
DI does not work in your case since you don't use it:
![изображение](https://user-images.githubusercontent.com/21261007/83955209-18cf0e80-a859-11ea-9008-aa666004a737.png)

Set `SchemaBuilder.ServiceProvider` in `configure` parameter:
```c#
public static ISchema For(string typeDefinitions, Action<SchemaBuilder> configure = null)
```

**Comment by sungam3r** [comment]
Closing this as answered.
