### ISSUE TITLE
How to resolve the InputGraphType to correct domain type

### ISSUE THREAD

**Issue by RedEyedDog** [graphql-dotnet/graphql-dotnet#1522]
## Summary
I need to take the inputtype and build the correct domain class to save
## Relevant information
Lets say i have a 

```
CreateActionGraphInputType {
CreateActionGraphInputType (){
Field<StringGraphType>()
Field<StringGraphType>()
Field<ListGraphType<IntGraphType>>() # How to resolve this 
}

Action {
public String Name {get;set;}
public String Description {get;set;}
public List<Reference> References {get;set;} # To This
}

```
What is the best way of getting the CreateActionInputtype  to resolve to the domain class? 
The resolver on the CreateActionGraphInputType.References dosent work like i excpected .i.e when the converter finds a property of the same name it dosent call resolve..

**Comment by sungam3r** [comment]
It seems that you are looking for `ResolveFieldContext.GetArgument<T>("name")` method.

**Comment by RedEyedDog** [comment]
Really what i want to do is:

```
var input = ResolveFieldContext.GetArgument<CreateActionGraphInputType>("input")
var domain = new Action{
Name = input.Name;
Description = input.Description;
References = input.References .Select(id => new Refrence{ID: id});
}
```

i want to get rid of the need for DTOs.. so i don't want to ```
have to create a CreateActionInput {
public String Name {get;set;}
public String Description {get;set;}
public List<int> References {get;set;} 
}
```

Thanks for your help

**Comment by sungam3r** [comment]
Do you mean you want to "deserialize" input argument into your Input**GraphType**, not InputDTO ?

**Comment by sungam3r** [comment]
If so actually you **can** since `GetArgument<T>` api from _master_ looks like that:
```c#
 /// <summary>
        /// Creates a new instance of the indicated type, populating it with the dictionary.
        /// Can use any constructor of the indicated type, provided that there are keys in the
        /// dictionary that correspond (case sensitive) to the names of the constructor parameters.
        /// </summary>
        /// <param name="source">The source of values.</param>
        /// <param name="type">The type to create.</param>
        public static object ToObject(this IDictionary<string, object> source, Type type)
        {
            // attempt to use the most specific constructor sorting in decreasing order of number of parameters
            var ctorCandidates = type.GetConstructors(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance).OrderByDescending(ctor => ctor.GetParameters().Length);

            ConstructorInfo targetCtor = null;
            ParameterInfo[] ctorParameters = null;

            foreach (var ctor in ctorCandidates)
            {
                var parameters = ctor.GetParameters();
                if (parameters.All(p => source.ContainsKey(p.Name)))
                {
                    targetCtor = ctor;
                    ctorParameters = parameters;
                    break;
                }
            }

            if (targetCtor == null)
                throw new ArgumentException($"Type '{type}' does not contain a constructor that could be used for current input arguments.", nameof(type));

            object[] ctorArguments = ctorParameters.Length == 0 ? Array.Empty<object>() : new object[ctorParameters.Length];

            for (int i = 0; i < ctorParameters.Length; ++i)
            {
                var arg = GetPropertyValue(source[ctorParameters[i].Name], ctorParameters[i].ParameterType);
                ctorArguments[i] = arg;
            }

            var obj = targetCtor.Invoke(ctorArguments);

            foreach (var item in source)
            {
                // these parameters have already been used in the constructor
                if (ctorParameters.Any(p => p.Name == item.Key))
                    continue;

                var propertyInfo = type.GetProperty(item.Key, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);
                if (propertyInfo != null && propertyInfo.CanWrite)
                {
                    var value = GetPropertyValue(item.Value, propertyInfo.PropertyType);
                    propertyInfo.SetValue(obj, value, null); //issue: this works even if propertyInfo is ValueType and value is null
                }
            }

            return obj;
        }
```

Thus you can "deserialize" input argument in any type you want. The main thing is that in this type there are properties that are writable with the corresponding names.

**Comment by RedEyedDog** [comment]
I did think that, but there is an issue with having the same property names as on the ObjectGraphType,  Name for example is already on the ObjectGraphType? i know it will get overwritten but will this have side effects?

What would be nice is something like this:

```csharp
.FieldAsync<BoardGraphType>(
                "createBoard",
                arguments: new QueryArguments(new QueryArgument<NonNullGraphType<CreateBoardInputGraphType>> { Name = "board" }),
                resolve: async context =>
                {
                    var board = context.GetArgument<Board>("board");
                    return await _addBoardService.Create(board);
                }
                );
```


```csharp
    public class CreateBoardInputGraphType : InputObjectGraphType<CreateBoardInput>
    {
        public CreateBoardInputGraphType()
        {
            Name = "CreateBoardInputType";
            //Mandatory
            Field<NonNullGraphType<StringGraphType>>("Name");
            Field<NonNullGraphType<TimePeriodEnumGraphType>>("TimePeriod");
            Field<NonNullGraphType<ListGraphType<IntGraphType>>>("BoardCards",
            resolve: o =>
            {
                var argument = o.GetArgument<List<int>>("BoardCards");
                return argument.Select(id => new BoardCard { CardId = id });
            });
        }
    }
```
```csharp
    public class Board : IdClass
    {
        public string Name { get; set; }

        public TimePeriod TimePeriod { get; set; }

        public virtual ICollection<BoardCard> BoardCards { get; set; }

    }
```

When the de-serialise comes to the BoardCards property, if it cant straight convert it, then it should call the resolve method on the CreateBoardInputGraphType.BoardCards which will fill it out?

**Comment by sungam3r** [comment]
Although I told you that you _can_ deserialize an input argument into a InputGraphType, it’s not worth it. GraphTypes are designed to solve their problems, and for arguments it is better to use DTOs.

>  i know it will get overwritten but will this have side effects?

Of course. Changing the GraphType name in runtime leads to unpredictable consequences.

> When the de-serialise comes to the BoardCards property, if it cant straight convert it, then it should call the resolve method on the CreateBoardInputGraphType.BoardCards which will fill it out?

Unfortunately, this is a common topic for misconceptions. For input types, resolvers are not called. See #1358, #1045, #1176 for more info.

**Comment by sungam3r** [comment]
GraphTypes describe the schema, they are metainformation that should not change.

**Comment by RedEyedDog** [comment]
would you suggest its better to create  BoardCardInputGraphType with a CardId Field which could be resolved to a BoardCard.. this way you dont need the DTO but you do need an extra graphtype. It acts like a DTO and exposes that property as a leaf on the graph?

P.S i hope i have the correct terminology ;)

**Comment by RedEyedDog** [comment]
Like this 

```csharp
    public class CreateBoardInputGraphType : InputObjectGraphType
    {

        public CreateBoardInputGraphType()
        {
            Name = "CreateBoardInputType";
            //Mandatory
            Field<NonNullGraphType<StringGraphType>>("Name");
            Field<NonNullGraphType<TimePeriodEnumGraphType>>("TimePeriod");
            Field<NonNullGraphType<ListGraphType<IntGraphType>>>("ElementIds");
            Field<NonNullGraphType<ListGraphType<BoardCardInputGraphType>>>("BoardCards");
        }
    }

    public class BoardCardInputGraphType : InputObjectGraphType
    {

        public BoardCardInputGraphType()
        {
            Name = "BoardCardInputType";
            //Mandatory
            Field<NonNullGraphType<IdGraphType>>("CardId");
        }
    }
```

Makes the query a bit more cumbersome but it works

**Comment by sungam3r** [comment]
I suggest to not use graphtypes in getargument api at all.

**Comment by sungam3r** [comment]
> would you suggest its better to create BoardCardInputGraphType with a CardId Field which could be resolved to a BoardCard.. this way you dont need the DTO but you do need an extra graphtype. It acts like a DTO and exposes that property as a leaf on the graph?

No.

**Comment by RedEyedDog** [comment]
Ok thanks for your help. I feel this could be a DTO killer for some apps. Just need to resolve properties independently etc querying works fine but feel the mutations need improving to be Abit more flexible.

**Comment by RedEyedDog** [comment]
P.s if you could guide me on how to get started I'd love to contribute

**Comment by sungam3r** [comment]
Get started for what exactly?

**Comment by RedEyedDog** [comment]
I feel like I want to contribute to this repo.. and understand Abit more under the hood. I'd like to look at how it resolves the input types ;) i should be able to figure it out if im pointed in the right direction

**Comment by sungam3r** [comment]
Well, the thing is that input types do not resolve in any way. Resolvers are called only for output types. And in input types they are only because input and output types are inherited from a common base class. This can be considered a design flaw. You may look to `ExecutionStrategy` class, `CollectFields` method.
