### ISSUE TITLE
New preview release on nuget

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1531]
@joemcbride Could we have a new preview release on nuget?  The current preview release is about 3 months old and doesn't contain #1441 .

If there's a chance that #1511 will be merged (or reviewed) soon, I'd be happy to wait for that.

I'd also like to suggest that the commit be tagged within github so it's easy to find the commit used to build this preview version, similar to how the 2.0 prerelease versions were done.

Thanks!!

**Comment by sungam3r** [comment]
Blocked by graphql-dotnet/server#299 as core packages must be in sync with server packages.

**Comment by carlwoodhouse** [comment]
is there any plans to have a new stable release at any point soon, or at least a milestone for it ? .. last one was 2018 heh (is it the 3.0 milestone ?)

**Comment by sungam3r** [comment]
Now many PRs have backward incompatible changes and affect more than one repository. Even if we assume that a stable version will be released soon, then with 100% probability the next change will require a transition to the long time development of version 4. I want to say that releasing a "stable" version without a preview suffix does not really make it stable.

**Comment by sungam3r** [comment]
What prevents the use of version previews? I understand that there is only a psychological barrier.

**Comment by Shane32** [comment]
When there are multiple third party extensions for a framework, there's a very real benefit, as it allows for certain points in time for everyone to upgrade their extensions to the new version.  Otherwise if one extension was built for preview 1352 and another for 1195, it's very possible that they could not be used together.  Not all third party developers wish to spend the resources required to constantly update their solution and publish their nuget package to be compatible with the latest graphql version, when the current version is updated regularly with breaking changes.

There's also a _hope_ by the extension developers and users that the authors will continue to support the 'release' version, issuing patches for bugs found after release - rather than a future version containing breaking changes - and a _fear_ that a preview version may contain unfinished, buggy features or is not completely tested. 

Finally, it provides a point in time for the framework to be documented properly, including documenting the breaking changes from the prior major version, and users can assist each other within a release more easily.

If you're not using extensions and don't need updated documentation (or if the documentation was always kept up to date), then a preview version should work just as well here, as the project is decently tested before a preview is released, and can be updated if a bug is found and patched.

**Comment by carlwoodhouse** [comment]
All of the above; especially re publication of breaking changes, etc

and even in terms of discover-ability; most people aren't going to find/update to preview versions; or corporate policy may prevent them from using them!

**Comment by sungam3r** [comment]
Anyway, I do not have access to publish this package to nuget. @joemcbride can do this.

**Comment by BenjaBobs** [comment]
Maybe some automatic CD should be setup for the master branch?

**Comment by joemcbride** [comment]
CD is setup on the master branch, but it purposefully does not auto-publish to nuget.org due to the number of packages.  Just in January-Feb there would be roughly 50 different versions.

It has always published every package to the MyGet feed, listed in the [README](https://github.com/graphql-dotnet/graphql-dotnet#installation).

[These have been the 3.0 milestones](https://github.com/graphql-dotnet/graphql-dotnet/milestone/4).  As always with OSS, people work on what they chose.  So we've had a _lot_ of features added that weren't in the 3.0 milestone (and probably aren't marked as such).

I would be happy to cut a 3.0 release if someone wants to write up the release notes and an upgrade guide.

**Comment by joemcbride** [comment]
I believe I got all of the latest packages published to nuget.org.  Let me know if I missed one.

**Comment by Shane32** [comment]
@joemcbride  Thanks !!

**Comment by sungam3r** [comment]
@joemcbride I completely agree with you regarding CD and a lot of preview packages and this one
> As always with OSS, people work on what they chose

I am sure that for a long time we will not release version 3. I'm not a pessimist, my experience just says that. therefore, I don’t see a better solution in just once a few months to publish the latest preview packages on nuget, as you did. Thanks.

**Comment by Shane32** [comment]
I’d like to work on the release notes and upgrade documentation so we can get version 3 released. I’m just not sure when I’ll have the time so didn’t want to commit to it yet.
