### ISSUE TITLE
Subscriptions in .NET Framework

### ISSUE THREAD

**Issue by dillanmann** [graphql-dotnet/graphql-dotnet#1532]
## Summary
Are there any examples or efforts available to enable subscriptions on .NET Framework? All of the GraphQL middleware for WebSockets and subscriptions is written with ASPNET Core in mind and is not transferrable to .NET Framework. This unfortunately means that it looks like it's not possible to use subscriptions with GraphQL.net in NFX.

Any info would be great, thanks.

## Relevant information
N/a

### Environment (if relevant)
FYI I am using OWIN Self-Host on .NET Framework 4.7.2

**Comment by sungam3r** [comment]
This is transport agnostic package. It is worth posting that issue to the server project.

**Comment by dillanmann** [comment]
> This is transport agnostic package. It is worth posting that issue to the server project.

Will do, thank you!
