### ISSUE TITLE
Input type with RowVersion is not working

### ISSUE THREAD

**Issue by noufionline** [graphql-dotnet/graphql-dotnet#1534]
## Description

I  want to update a small table which has Timestamp column.

### Steps to reproduce

```csharp
public class LookUpItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] RowVersion { get; set; }
      
    }



public async Task<LookUpItem> UpdateAsync(string operationName, LookUpItem item)
        {
            var query = $@" 
              mutation($lookup: bankInput!){{
                   lookUpItem:{operationName}(lookup: $lookup)
            {{
                id
                name
                rowVersion
            }}
            }}";

            var request = new GraphQLRequest
            {
                Query = query,
                Variables = new {Lookup=item}
            };
            var response = await _client.SendMutationAsync<UpdateMutation>(request);

            return response.Data.LookUp;
        }


 public class BankInputType : InputObjectGraphType<Bank>
    {
        public BankInputType()
        {
            Name = "bankInput";
            Field(x => x.Id);
            Field(x => x.Name);
            Field(x => x.RowVersion);

            //Field<NonNullGraphType<IdGraphType>>("id");
            //Field<NonNullGraphType<StringGraphType>>("name");
        }
    }

   FieldAsync<BankType>("updateBank",
                 arguments:new QueryArguments(new QueryArgument<BankInputType>{Name = "lookup"}),
                resolve: async context =>
                     {
                         var lookup = context.GetArgument<Bank>("lookup");

                         return await context.TryAsyncResolve(
                             async c =>
                             {
                                 var lookupItem = await repository.UpdateAsync(lookup);
                                 notificationService?.AddLookupItemAddedMessage("banks", lookupItem);
                                 return lookupItem;
                             });
                     });




```

### Expected result

Saves and returns the saved entity

What should happen?

### Actual result

Error:

GraphQL.ExecutionError: Input string was not in a correct format.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Byte.Parse(String s, IFormatProvider provider)
   at GraphQL.ValueConverter.<>c.<.cctor>b__1_1(Object value)
   at GraphQL.ValueConverter.ConvertTo(Object value, Type targetType)
   at GraphQL.Types.ByteGraphType.ParseValue(Object value)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.GetVariableValue(Document document, ISchema schema, VariableDefinition variable, Object input)
   at GraphQL.Execution.ExecutionHelper.GetVariableValues(Document document, ISchema schema, VariableDefinitions variableDefinitions, Inputs inputs)
   at GraphQL.DocumentExecuter.BuildExecutionContext(ISchema schema, Object root, Document document, Operation operation, Inputs inputs, IDictionary`2 userContext, CancellationToken cancellationToken, Metrics metrics, IEnumerable`1 listeners, Boolean throwOnUnhandledException, Action`1 unhandledExceptionDelegate, Nullable`1 maxParallelExecutionCount)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
   --- End of inner exception stack trace ---

What happened.

RowVersion (byte[] array) not working as expected.

**Comment by pekkah** [comment]
You need a custom scalar type for byte[].

**Comment by noufionline** [comment]
@pekkah 
I understand and created a custom scalar type as well. But there is already a ByteGraphType included so its not allowing me to register my custom one.

```csharp

using GraphQL.Language.AST;

namespace GraphQL.Types
{
  public class ByteGraphType : ScalarGraphType
  {
    public override object ParseLiteral(IValue value)
    {
      switch (value)
      {
        case ByteValue byteValue:
          return (object) byteValue.Value;
        case IntValue intValue:
          return 0 <= intValue.Value && intValue.Value <= (int) byte.MaxValue ? (object) (byte) intValue.Value : (object) null;
        default:
          return (object) null;
      }
    }

    public override object ParseValue(object value)
    {
      return ValueConverter.ConvertTo(value, typeof (byte));
    }

    public override object Serialize(object value)
    {
      return this.ParseValue(value);
    }
  }
}

```

**Comment by sungam3r** [comment]
@noufionline Please show your request text on server side, after client did all transformations.

**Comment by sungam3r** [comment]
> its not allowing me to register my custom one

You can post another issue about overwriting built-in .NET scalar types.

**Comment by noufionline** [comment]
Finally I managed to solve it!

```csharp
 public class BankInputType : InputObjectGraphType<Bank>
    {
        public BankInputType()
        {
            Name = "bankInput";
            Field(x => x.Id);
            Field(x => x.Name);
            Field<NonNullGraphType<ByteGraphType>>("rowVersion");
        }
    }

  

    public class ByteGraphType : ScalarGraphType
    {
        public ByteGraphType()
        {
            Name = "ByteArray";
            Description = "ByteGraphType";
        }

        public override object Serialize(object value)
        {
            return ParseValue(value);
        }

        public override object ParseValue(object value)
        {
            if (value is byte[])
                return value;

            byte[] result = Convert.FromBase64String(value.ToString());
            return result;
        }

        public override object ParseLiteral(IValue value)
        {
            if (value is ByteValue stringValue)
            {
                return ParseValue(stringValue.Value);
            }

            return null;
        }
    }

    public sealed class ByteArrayConverter : IAstFromValueConverter
    {
        public bool Matches(object value, IGraphType type)
        {
            return value is byte[];
        }

        public IValue Convert(object value, IGraphType type)
        {
            return new ByteValue(value as byte[]);
        }
    }


    internal class ByteValue : ValueNode<byte[]>
    {
        public ByteValue(byte[] value)
        {
            Value = value;
        }

        protected override bool Equals(ValueNode<byte[]> node)
        {
            return Value == node.Value;
        }
    }


 public class AbsCoreSchema:Schema
    {
        public JCoreSchema(IServiceProvider provider) : base(provider)
        {
            Query = provider.GetRequiredService<JCoreQuery>();
            Mutation = provider.GetRequiredService<JCoreMutation>();
            Subscription = provider.GetRequiredService<JCoreSubscription>();

            RegisterValueConverter(new ByteArrayConverter());
        }
    }
```

Any suggestions or improvements please feel free to post it here

**Comment by sungam3r** [comment]
Honestly, you solved the problem in a completely different way than you should have.

@noufionline Please show your request text on the server side, after client did all transformations.

**Comment by noufionline** [comment]
Hi @sungam3r 

```csharp

  FieldAsync<BankType>("createBank", arguments: new QueryArguments(new QueryArgument<NonNullGraphType<BankInputType>> { Name = "lookup" }),
                resolve: async context =>
                {
                    var bank = context.GetArgument<Bank>("lookup");
                    return await context.TryAsyncResolve(
                        async c =>
                        {
                            var lookupItem = await repository.CreateAsync(bank);
                            notificationService?.AddLookupItemAddedMessage("banks", lookupItem);
                            return lookupItem;
                        });
                });

            FieldAsync<BankType>("updateBank",
                 arguments:new QueryArguments(new QueryArgument<BankInputType>{Name = "lookup"}),
                resolve: async context =>
                     {
                         var lookup = context.GetArgument<Bank>("lookup");

                         return await context.TryAsyncResolve(
                             async c =>
                             {
                                 var lookupItem = await repository.UpdateAsync(lookup);
                                 notificationService?.AddLookupItemAddedMessage("banks", lookupItem);
                                 return lookupItem;
                             });
                     });


  public async Task<LookUpItem> CreateAsync(string operationName, LookUpItem lookup)
        {
            var query = $@" 
              mutation($lookup: bankInput!){{
                   lookUpItem:{operationName}(lookup: $lookup)
            {{
                id
                name
                rowVersion
            }}
            }}";
            var request = new GraphQLRequest
            {
                Query = query,
                Variables = new { Lookup = lookup }
            };

            var response = await _client.SendMutationAsync<Data>(request);

            return response.Data.LookUpItem;
        }

   public async Task<LookUpItem> UpdateAsync(string operationName, LookUpItem item)
        {
            var query = $@" 
              mutation($lookup: bankInput!){{
                   lookUpItem:{operationName}(lookup: $lookup)
            {{
                id
                name
                rowVersion
            }}
            }}";

            var request = new GraphQLRequest
            {
                Query = query,
                Variables = new {Lookup=item}
            };
            var response = await _client.SendMutationAsync<UpdateMutation>(request);

            return response.Data.LookUp;
        }



 public class BankInput
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] RowVersion { get; set; }

    }

 public class UpdateMutation
        {
            public LookUpItem LookUp { get; set; }
        }

```

**Comment by sungam3r** [comment]
What version do you use? Please first try the latest preview.

**Comment by noufionline** [comment]
@sungam3r 
On the server I am using the following versions

GraphQL Version=3.0.0-preview-1352
GraphQL.Authorization Version=3.0.39-preview-39
GraphQL.Server.Transports.AspNetCore Version=3.5.0-alpha0027
GraphQL.Server.Transports.WebSockets Version=3.5.0-alpha0027
GraphQL.Server.Ui.GraphiQL Version=3.5.0-alpha0027
GraphQL.Server.Ui.Playground Version=3.5.0-alpha0027



Client side :
GraphQL.Client Version=2.0.0
GraphQL.Common Version=1.0.3

Can you please help me with correct way to do this. I am a bit lost

**Comment by noufionline** [comment]
I have gone a bit further with my experiments.

When I debug I can see that Built in ByteGraphType receives rowversion (byte[]) as List<object> and conversion fails. So I modified the code this way.

````csharp

 public class RowVersionGraphType : ScalarGraphType
    {
        public RowVersionGraphType()
        {
            Name = "RowVersion";
            Description = "Timestamp Byte Array";
        }

        public override object Serialize(object value)
        {
            return ParseValue(value);
        }

        public override object ParseValue(object value)
        {

            switch (value)
            {
                case ByteValue byteValue:
                    return (object)byteValue.Value;
                case IntValue intValue:
                    return 0 <= intValue.Value && intValue.Value <= (int)byte.MaxValue ? (object)(byte)intValue.Value : (object)null;
                case List<object> list:
                    return list.Select(l => Convert.ToByte((int)l)).ToArray();
                case byte[] byteArray:
                    return byteArray;
                case string str:
                    return Convert.FromBase64String(value.ToString());
                default:
                    return (object)null;
            }
        }

        public override object ParseLiteral(IValue value)
        {

            if (value is ByteArrayValue stringValue)
            {
                return ParseValue(stringValue.Value);
            }

            return null;
        }
    }


  public class BankInputType : InputObjectGraphType<Bank>
    {
        public BankInputType()
        {
            Name = "bankInput";
            Field(x => x.Id);
            Field(x => x.Name);
            Field(x => x.RowVersion,type:typeof(RowVersionGraphType));
        }
    }


 public sealed class ByteArrayConverter : IAstFromValueConverter
    {
        public bool Matches(object value, IGraphType type)
        {
            return value is byte[];
        }

        public IValue Convert(object value, IGraphType type)
        {
            return new ByteArrayValue(value as byte[]);
        }
    }


 internal class ByteArrayValue : ValueNode<byte[]>
    {
        public ByteArrayValue(byte[] value)
        {
            Value = value;
        }

        protected override bool Equals(ValueNode<byte[]> node)
        {
            return Value == node.Value;
        }
    }

@sungam3r 

Please help me with the correct way. I am not sure about the above code.
````

**Comment by sungam3r** [comment]
@noufionline No one `ScalarGraphType` needs to receive/handle arrays. There is something wrong with how you configure your schema. Please check [`ScalarsInputTest`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Bugs/ScalarsInputTest.cs). There are many properties of arrays of primitive types, compare with your configuration.

**Comment by noufionline** [comment]
@sungam3r 
Thanks for your help. I followed your instruction and checked the ScalarsInputTest. 

Now Server side is working perfectly with graphql playground. But on the client side row version is getting converted to Base64String while sending to the server I guess.

````csharp
  var request = new GraphQLRequest
            {
                Query = query,
                Variables = new {Lookup=item}
            };
            var response = await _client.SendMutationAsync<Data>(request); // Here I am getting the error

            return response.Data.LookUpItem;
````


Error:

GraphQL.ExecutionError: Input string was not in a correct format.
---> System.FormatException: Input string was not in a correct format.
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
at System.Byte.Parse(String s, IFormatProvider provider)
at GraphQL.ValueConverter.<>c.<.cctor>b__1_1(Object value)
at GraphQL.Types.ByteGraphType.ParseValue(Object value)
at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
at GraphQL.Execution.ExecutionHelper.GetVariableValue(Document document, ISchema schema, VariableDefinition variable, Object input)
at GraphQL.Execution.ExecutionHelper.GetVariableValues(Document document, ISchema schema, VariableDefinitions variableDefinitions, Inputs inputs)
at GraphQL.DocumentExecuter.BuildExecutionContext(ISchema schema, Object root, Document document, Operation operation, Inputs inputs, IDictionary2 userContext, CancellationToken cancellationToken, Metrics metrics, IEnumerable1 listeners, Boolean throwOnUnhandledException, Action1 unhandledExceptionDelegate, Nullable1 maxParallelExecutionCount)
at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
--- End of inner exception stack trace ---

**Comment by sungam3r** [comment]
I'm glad that you localized the problem and it is not on the server side.

**Comment by noufionline** [comment]
@sungam3r 
Sorry for the confusion caused.

**Comment by sungam3r** [comment]
Not related to this project, see graphql-dotnet/graphql-client#163
