### ISSUE TITLE
Schema first approach and dependency injection

### ISSUE THREAD

**Issue by TWry** [graphql-dotnet/graphql-dotnet#1536]
I'd like to use the schema first approach in my project. I am struggling to use dependency injection though. 

I found a [gist](https://gist.github.com/joemcbride/2632fd81fabe87cff8a71377058863b5) that shows how to enable it by setting `new FuncDependencyResolver(type => container.Get(type))` on the SchemaBuilder passed when creating the schema using `Schema.For`. This solution, however, does not seem to available any longer. How can I enable dependency injection when using schema first?

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/12a2f078243e300ebb3293656c01cfb107cb18ed/src/GraphQL/Utilities/SchemaBuilder.cs#L19 initialize this property

**Comment by TWry** [comment]
> initialize this property

Thanks for the hint. What do I need to initialize it with, assuming the use of the default MS DI container? 

I would like to use constructor injection in the handler classes for each type. This would enable me to connect to a data source which I can change easily in Startup.cs.

**Comment by sungam3r** [comment]
Initialize it just as you do before - `new FuncDependencyResolver(type => container.Get(type))`

**Comment by TWry** [comment]
`FuncDependencyResolver` is not defined anywhere as it seems. I thought it was defined in a prior version of GraphQL, wasn't it?

**Comment by TWry** [comment]
`services.BuildServiceProvider();` seems to work. Thanks!

**Comment by sungam3r** [comment]
You can use `FuncServiceProvider` with latest versions.

**Comment by sungam3r** [comment]
I do not advise you to call `services.BuildServiceProvider()` on your own.

**Comment by TWry** [comment]
Ok, so what version do I need to use `FuncServiceProvider`? I currently have `3.0.0-preview-1352` installed.

**Comment by TWry** [comment]
I hate to ask again, but I can't figure it out. How would I initialize it in `ConfigureServices`? 

`services.AddSingleton<ISchema>(s => Schema.For("type Query { hello: String}",  _ => {
      _.Types.Include<Query>();
      _.ServiceProvider = new FuncServiceProvider( ??? );
  });`

**Comment by TWry** [comment]
For the record - I ended up with this: 

`            services.AddSingleton<ISchema>(provider => Schema.For("type Query {hello: String}", _ =>
            {
                _.Types.Include<ResolverQuery>();
                _.ServiceProvider = new FuncServiceProvider(provider.GetService);
            }));
`

**Comment by sungam3r** [comment]
Right.

**Comment by basvandriel** [comment]
This seems to be outdated, any update on here @sungam3r ?

    public class Query
    {
        [GraphQLMetadata("hero")]
        public Droid Hero()
        {
            return new Droid { Name = "R2-D2" };
        }
    }

And when registering the schema;

    services.AddSingleton<ISchema>(provider => Schema.For(definitions, _ =>
    {
        _.Types.Include<Query>();
        _.ServiceProvider = new FuncServiceProvider(provider.GetService);
    }));

I get the following error:

```
{
  "errors": [
    {
      "message": "Error trying to resolve field 'hero'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "hero"
      ],
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ]
      }
    }
  ],
  "data": {
    "hero": null
  }
}
```

**Comment by Shane32** [comment]
`DateTime` is not a built-in GraphQL type, although it is one of the types included with GraphQL.NET.  Do you need `scalar DateTime` in the definition?  And/or something to link the 'DateTime' type to `DateTimeGraphType`?  

I'm not sure, since I don't use the schema-first syntax, so I may be all wrong.

**Comment by basvandriel** [comment]
I got somewhat further; I added `.AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true);` to trace the problem and got this;

` "message": "GraphQL.Execution.UnhandledError: Error trying to resolve field 'hero'.\n ---> System.InvalidOperationException: Could not resolve an instance of Query to execute Query.hero\n   at GraphQL.Reflection.AccessorFieldResolver.Resolve(IResolveFieldContext context) in /_/src/GraphQL/Reflection/AccessorFieldResolver.cs:line 28\n   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 429\n   --- End of inner exception stack trace ---"`

Could the `Query`  instance not be loaded at all?

**Comment by sungam3r** [comment]
Try set `ExposeExceptionStackTrace` to `true` to see error happened - https://graphql-dotnet.github.io/docs/guides/serialization/#error-serialization

**Comment by sungam3r** [comment]
Well, `FuncServiceProvider` as is gives you nothing. It's just a wrapper around delegate. If you have `IServiceProvider` then just pass it directly. The root cause of error that you didn't register your graph types in the DI container.

**Comment by basvandriel** [comment]
Let's continue in #2765
