### ISSUE TITLE
Writing a string consisting of a single doublequote character doesnt work

### ISSUE THREAD

**Issue by wastaz** [graphql-dotnet/graphql-dotnet#154]
If you have a field declared as a stringgraphtype and the value of this field is only a single " character then that field will not get output correctly.

I suspect that the bug is in this method in `StringGraphType.cs` and that the fix is to add a length check in the if-statement (since such a string would both begin and end with the "-character but would have length = 1 which would cause problems in the subsequent call to Substring).

```
        private string ProcessString(string value)
        {
            value = value.Replace("\\\"", "\"");
            if (value.StartsWith("\"") && value.EndsWith("\""))
            {
                value = value.Substring(1, value.Length - 2);
            }
            return value;
        }
```

So this is probably how that method should look

```
        private string ProcessString(string value)
        {
            value = value.Replace("\\\"", "\"");
            if (value.StartsWith("\"") && value.EndsWith("\"") && value.Length > 1)
            {
                value = value.Substring(1, value.Length - 2);
            }
            return value;
        }
```

**Comment by joemcbride** [comment]
Thanks for the report - I think perhaps we should be using `Trim` here.

```
private string ProcessString(string value)
{
    value = value.Replace("\\\"", "\"");
    return value.Trim('"');
}
```

**Comment by joemcbride** [comment]
That would probably remove the single occurrence of `"` ... so would need to include that length check.
