### ISSUE TITLE
Custom scalars that are parsed as null for non null inputs throw

### ISSUE THREAD

**Issue by kapiljain-128** [graphql-dotnet/graphql-dotnet#1542]
## Summary
I've implemented a custom scalar which needs to be parsed as null if an empty string is provided by the client for it in a mutation. However, this doesn't work because of the following code which asserts that the value of a scalar field after parsing is correct and is treating the null value that the parser of my custom scalar returns as invalid.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionHelper.cs#L146 

Is there a workaround that I can use? Or is it expected behavior that a null value is considered invalid for custom scalars and if a use case requires certain non null inputs to be treated as null then it should be handled in the client side?

I'm having form fields in my client that would have empty string values if they're optional and nothing is entered in them. I'm not sure if it would be a good idea to have for my client to check if a field belongs to a specific custom scalar, then while passing that field in a mutation, it should convert the empty string value into a null.
## Steps to reproduce:
- Follow the steps in https://graphql-dotnet.github.io/docs/getting-started/custom-scalars/
- Modify the code to return a null from the `ParseVector3` function.
- Create a mutation which accepts a field of type `Vector3`.
- When calling the mutation, an InvalidValueException is thrown.

**Comment by pekkah** [comment]
At least in the example the field is marked non null. Have you tried making it nullable?

**Comment by kapiljain-128** [comment]
Yes, even if the field is marked nullable it still throws the same exception.

**Comment by pekkah** [comment]
Yep, looks like a bug to me.

**Comment by kapiljain-128** [comment]
Attaching mutation query/variables and output:

Query:
```
mutation ($salary: SalaryInput!, $salarySection_salary_index: Int) {
  updateSalary(salary: $salary, index: $salarySection_salary_index) {
    nameOfEmployer
    salaryAsPerSec17
  }
}
```
Variables:
```
{
  "salary": {
    "nameOfEmployer":"Test",
    "salaryAsPerSec17":""
  },
  "salarySection_salary_index":1
}
```
Output:
```
{
  "errors": [
    {
      "message": "GraphQL.ExecutionError: Variable '$salary.salaryAsPerSec17' is invalid. Invalid Scalar value for input field.\r\n ---> GraphQL.Execution.InvalidValueException: Variable '$salary.salaryAsPerSec17' is invalid. Invalid Scalar value for input field.\r\n   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)\r\n   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)\r\n   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)\r\n   at GraphQL.Execution.ExecutionHelper.GetVariableValue(Document document, ISchema schema, VariableDefinition variable, Object input)\r\n   at GraphQL.Execution.ExecutionHelper.GetVariableValues(Document document, ISchema schema, VariableDefinitions variableDefinitions, Inputs inputs)\r\n   at GraphQL.DocumentExecuter.BuildExecutionContext(ISchema schema, Object root, Document document, Operation operation, Inputs inputs, IDictionary`2 userContext, CancellationToken cancellationToken, Metrics metrics, IEnumerable`1 listeners, Boolean throwOnUnhandledException, Action`1 unhandledExceptionDelegate, Nullable`1 maxParallelExecutionCount)\r\n   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)\r\n   --- End of inner exception stack trace ---",
      "extensions": {
        "code": "INVALID_VALUE",
        "codes": [
          "INVALID_VALUE"
        ]
      }
    }
  ],
  "extensions": {}
}
```
Expected output: 
```
{
  "data": {
    "updateSalary": {
      "nameOfEmployer": "Test",
      "salaryAsPerSec17": null
    }
  },
  "extensions": {}
}
```

**Comment by sungam3r** [comment]
> Yes, even if the field is marked nullable it still throws the same exception.

It throws because you pass non-null input value (empty string I suppose) and not because argument nullable or not. I think that returning `null` for non-null scalar input is wrong. `null` has special meaning, this means the input coercion failed.

> I've implemented a custom scalar which **needs to** be parsed as null if an empty string is provided by the client for it in a mutation. 

Why? You probably don't need this. Most likely you need some condition instead to do some processing later. You still need to create an instance of your scalar. It looks like `DbNull.Value`. If you worked with ADO.NET, you will immediately understand what it is about. So you will have scalar graph type with `Serialize` method like this
```c#
 public override object Serialize(object value) => return value == MyNull.Value ? null : somethingElse;
```

**Comment by sungam3r** [comment]
@Shane32 It is possible that after checking the behavior it is worth making an explicit comment in the documentation. If you want, you can write a test and documentation. Otherwise I will do it someday myself.

**Comment by Shane32** [comment]
I'm a bit swamped at work right now.  And if I have free time, I'd like to spend it working on the upgrade documentation.  This should probably be noted alongside the docs you pushed recently ( #1616 ).

Personally, I'd also put this feature on a wish list, and consider changing the functionality if someone posts a reasonable PR.

**Comment by sungam3r** [comment]
Closed due to inactivity.
