### ISSUE TITLE
DefaultFieldNameConverter question

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1545]
@sungam3r I'm trying to understand the `DefaultFieldNameConverter` and `PascalCaseFieldNameConverter`.  It appears to only apply camel case to "instrospection types".  However, this is searching a private fixed array, always containing a single static type `SchemaIntrospection`.  As a private array, it can't be changed.  And static types can't be created.  Am I missing something or does this make no sense at all?

**Comment by sungam3r** [comment]
You have the same question that I once had. In fact, everything is simple - the **parent** type is checked. And the converter is applied to **child** fields. Also look into `GraphTypesLookup`:
```c#
 var introspectionType = typeof(SchemaIntrospection);

            lookup.HandleField(introspectionType, SchemaIntrospection.SchemaMeta, ctx);
            lookup.HandleField(introspectionType, SchemaIntrospection.TypeMeta, ctx);
            lookup.HandleField(introspectionType, SchemaIntrospection.TypeNameMeta, ctx);
```

```c#
 private void HandleField(Type parentType, FieldType field, TypeCollectionContext context)
```

**Comment by Shane32** [comment]
Thanks. I felt it must have made sense somehow but couldn’t figure it out!

**Comment by Shane32** [comment]
But ... the introspection types start with `__` -- so this code still actually does nothing, right???

**Comment by sungam3r** [comment]
Why nothing?

**Comment by Shane32** [comment]
The `Name` property of `SchemaMetaFieldType` is set to `"__schema"`.  `HandleField` passes the parent type and the `Name` property of the field to the `IFieldConverter`.  If this then ran this through `StringExtensions.ToPascalCase` (it doesn't currently), it would grab the first character and try to capitalize it.  The first character is `'_'`.  So it would return the original string `"__schema"`.  Same with `TypeMetaFieldType` and `TypeNameMetaFieldType`, the only three types this code applies to.  Right?  So it would seem that you could run any field name through `ToPascalCase` without the name of those introspection type names being affected.  And they certainly don't need to run through `ToCamelCase` as they are predefined with the correct case.

**Comment by Shane32** [comment]
Maybe there's more I'm not seeing.  I'll run some tests.

**Comment by sungam3r** [comment]
I think I understood your question.

>  it would grab the first character and try to capitalize it. The first character is '_'

First, you confuse the parent field and the child field. The converter converts the names of child fields, for example `types`, `args`. However, the current code indeed can be simplified because all introspection fields are lowercase:
```c#
public class PascalCaseFieldNameConverter : IFieldNameConverter
    {
        private static readonly Type[] IntrospectionTypes = { typeof(SchemaIntrospection) };

        public static readonly PascalCaseFieldNameConverter Instance = new PascalCaseFieldNameConverter();

        public string NameFor(string field, Type parentType) => isIntrospectionType(parentType) ? field : field.ToPascalCase();

        private bool isIntrospectionType(Type type) => IntrospectionTypes.Contains(type);
    }
```

and

```c#
 public class DefaultFieldNameConverter : IFieldNameConverter
    {
        public static readonly DefaultFieldNameConverter Instance = new DefaultFieldNameConverter();

        public string NameFor(string field, Type parentType) => field;
    }
```

**Comment by sungam3r** [comment]
The basic idea is not to affect the name of the introspection fields so I think you are right that code into `DefaultFieldNameConverter` does nothing although it seemed to me your explanation was not entirely true.

**Comment by Shane32** [comment]
Making more sense now.  I tried switching to the PascalNameConverter but the default json writer in DocumentWriter is forcing the result to camelcase.  Is this an error?

**Comment by Shane32** [comment]
Or is that expected behavior?

**Comment by Shane32** [comment]
I'm still researching; I'll figure it out.

**Comment by sungam3r** [comment]
`DocumentWriter` is "external" component with additional "formatter" function. You **can** configure it as you want. Yes, by default we forced the result to camelCase.

**Comment by sungam3r** [comment]
So in other words if you want to have PascalCase you should enable this on two levels - schema and document writer.

**Comment by sungam3r** [comment]
By the way, I think that it was wrong to convert introspection field names to lowercase (even with no effect). The point is that the names of these fields should not change and no matter what their original name is. So I think that `CamelCaseFieldNameConverter` should be changed too to follow this pattern. And of course (as you might have already guessed) all these discussions should be noted in the comments.

**Comment by Shane32** [comment]
I think I found my answer.  The `GraphTypesLookup` constructor runs before the `GraphTypesLookup.FieldNameConverter` property is set, so all the introspection fields always get configured with the `CamelCaseNameConverter` (the default value of `GraphTypesLookup.FieldNameConverter`), no matter how `Schema.FieldNameConverter` or `ExecutionOptions.FieldNameConverter` is set.

I've proven this by three steps:
1. Change CamelCaseFieldNameConverter.cs to the following:
``` C#
using System;
using System.Linq;
using GraphQL.Introspection;

namespace GraphQL.Conversion
{
    public class CamelCaseFieldNameConverterOld : IFieldNameConverter
    {
        public static readonly CamelCaseFieldNameConverterOld Instance = new CamelCaseFieldNameConverterOld();

        public string NameFor(string field, Type parentType) => field.ToCamelCase();
    }
    public class CamelCaseFieldNameConverter : IFieldNameConverter
    {
        private static readonly Type[] IntrospectionTypes = { typeof(SchemaIntrospection) };

        public static readonly CamelCaseFieldNameConverter Instance = new CamelCaseFieldNameConverter();

        public string NameFor(string field, Type parentType)
        {
            if (isIntrospectionType(parentType) && field != "__schema" && field != "__type" && field != "__typename")
                throw new Exception();
            return field.ToCamelCase();
        }

        private bool isIntrospectionType(Type type) => IntrospectionTypes.Contains(type);
    }
}
```
2. Change the GraphTypesLookup constructor to set `FieldNameConverter` to `CamelCaseFieldNameConverterOld.Instance` at the start of the function, and back to the default of `CamelCaseFieldNameConverter.Instance` at the end of the function
3. Run all tests -- which all pass showing that no exception is thrown

**Comment by sungam3r** [comment]
Well, OK, this does not change the essence of the matter - `CamelCaseFieldNameConverter` does nothing with introspection fields.

**Comment by Shane32** [comment]
Found one bug: `GetArgument`, used within some introspection types, does not work with pascal case due to it transforming the argument name to pascal case, which is incorrect for the introspection types.  Posting a PR for it.
