### ISSUE TITLE
GraphQL.SystemTextJson not published

### ISSUE THREAD

**Issue by bgoerdt** [graphql-dotnet/graphql-dotnet#1546]
## Description

The GraphQL.SystemTextJson package is referenced in the README, but it doesn't look like it is published to Nuget

**Comment by sungam3r** [comment]
It is a known issue. You can get preview versions from myget feed. @joemcbride could you please push this to nuget or give me permissions to do this myself?

**Comment by dirkesquire** [comment]
The following works for the time being:
`dotnet add package GraphQL.SystemTextJson -v 3.0.0-preview-1490`

**Comment by sungam3r** [comment]
Published.
