### ISSUE TITLE
Error with Union _Entity when trying to use FederatedSchema

### ISSUE THREAD

**Issue by bgoerdt** [graphql-dotnet/graphql-dotnet#1548]
## Description

When trying to setup a Federated Schema, I am getting the following error:
```
{
  "errors": [
    {
      "message": "GraphQL.ExecutionError: Must provide types for Union _Entity.
 ---> GraphQL.ExecutionError: Must provide types for Union _Entity.
   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.GraphTypesLookup.Create(IEnumerable`1 types, IEnumerable`1 directives, Func`2 resolveType, IFieldNameConverter fieldNameConverter, Boolean seal)
   at GraphQL.Types.Schema.CreateTypesLookup()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)\n   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GraphQL.Types.Schema.FindType(String name)
   at GraphQL.Types.Schema.Initialize()
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
   --- End of inner exception stack trace ---",
      "extensions": {
        "code": "EXECUTION_ERROR"
      }
    }
  ]
}
```

### Steps to reproduce
Startup.cs (some details removed)
```
services.AddSingleton<IDocumentExecuter, DocumentExecuter>();
services.AddSingleton<IDocumentWriter, DocumentWriter>();

services.AddSingleton<AnyScalarGraphType>();
services.AddSingleton<ServiceGraphType>();

services.AddSingleton<Query>();
services.AddSingleton<ISchema>(
     serviceProvider =>
        {
            var schema = FederatedSchema.For(
                @"
                    extend type Query {
                         myQuery(param1: String!): MyType
                     }

                      type MyType {
                          myData: DateTime!
                       }
                   ",
                    builder =>
                        {
                            builder.ServiceProvider = serviceProvider;
                            builder.Types.Include<Query>();
                        });

    return schema;
});
```

### Expected result

Should be able to successfully start the API and get data back.

### Actual result

I am getting an error on every request.

### Environment
```
    <TargetFramework>netcoreapp3.1</TargetFramework>
...
    <PackageReference Include="GraphQL" Version="3.0.0-preview-1352" />
```

**Comment by bgoerdt** [comment]
I created a completely stripped down version of the project to try to figure out what is going on. I found out that a federated graph will throw the above error if there is not a type that uses the `@key` directive in the schema. Once I added a type with the `@key` directive it started working. I'm guessing this has something to do with how the union type is built in the [FederatedSchemaBuilder.BuildEntityGraphType](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/Federation/FederatedSchemaBuilder.cs#L135) method.

**Comment by Joelgullander** [comment]
@bgoerdt can you show an example on what you did to resolve it? We have the same issue, and after adding a @key it says it has no @external : `A @key directive specifies the `id` field which has no matching @external field.`

**Comment by bgoerdt** [comment]
@Joelgullander I was referencing a type from another service like this:
```
extend type Foo @key(fields: "fooId") {
    fooId: ID! @external
}
```

**Comment by Shane32** [comment]
Federation 2 support is available for schema-first, code-first, and type-first schemas in GraphQL.NET 8.0 (still in beta at the time of writing). See:

- https://github.com/graphql-dotnet/graphql-dotnet/pull/3921

This includes proper support for schemas which contain no resolvable entities.
