### ISSUE TITLE
Error in View

### ISSUE THREAD

**Issue by cmiagika** [graphql-dotnet/graphql-dotnet#155]
Hey

I've tried to install the example of your .NET GraphiQl. After pulling the repository and installing the npm packages, I generated the bundle.js file with "npm start". Then I tried to run it from my Visual Strudio and saw something horrible...
![image](https://cloud.githubusercontent.com/assets/17830309/17932130/e1bb0872-6a0e-11e6-9238-e4553c3f3448.png)
At least it works :wink: 

Here is also my bundle.js file as txt.
[bundle.txt](https://github.com/graphql-dotnet/graphql-dotnet/files/434796/bundle.txt)
Maybe I did something wrong?

Thank you for your help :smiley:

**Comment by joemcbride** [comment]
It looks like this is due to a change in GraphiQL css.

https://github.com/graphql/graphiql/pull/153

Our example will need to be updated to compensate.

**Comment by joemcbride** [comment]
Updated our sample to just pull the css from the node module, so this should be less-likely to happen next time.
