### ISSUE TITLE
Get requested fields

### ISSUE THREAD

**Issue by fenomeno83** [graphql-dotnet/graphql-dotnet#1560]
Hi.
In node version you can access to "info" field of GraphQLResolveInfo, to get what fields are requested in query.

How can you do in graphql .net core?
It can be usefull to decide what sql queries I need to do to resolve all requested fields.

Thanks

**Comment by sungam3r** [comment]
`IResolveFieldContext.SubFields`, `IResolveFieldContext.Path`

**Comment by fenomeno83** [comment]
Can you give me example?

This is a my test query

public class TestGroupQueries : ObjectGraphType
    {
        public TestGroupQueries(ITestOperations testOperations)
        {
            Name = "testQueries";

            FieldAsync<StringGraphType>(
            "test",
                resolve: async context => await testOperations.Test<object>());

        }
    }

How can I get query requested fields

**Comment by sungam3r** [comment]
`context.SubFields`

**Comment by sungam3r** [comment]
or `context.Document` in case of the whole query text

**Comment by fenomeno83** [comment]
thanks!

**Comment by sungam3r** [comment]
@fenomeno83 Is this issue still actual for you?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
