### ISSUE TITLE
Current recommendation for implementing GraphQL.Net with Entity Framework

### ISSUE THREAD

**Issue by ztrobinson777** [graphql-dotnet/graphql-dotnet#1562]
## Summary
So there's a lot of discussion about how to deal with the dependency injection scoping of GraphQL.Net and Entity Framework with many different suggestions of various age. 

In the project that I'm currently working on, I have been running with a service locator for using the EF dbContext in resolvers and it works, but there's so much documentation out there suggesting that this pattern should be avoided I'm trying to find an ideal alternative.

## Questions
What is the current recommendation for using a "scoped" Entity Framework dbContext with a "singleton" GraphQL setup? 

Should I feel bad about the service locator implementation? 

Would an injectable dbContext factory with singleton scope be a better solution?

**Comment by sungam3r** [comment]
For all three questions you will get different answers from different people, there is no single ideal solution. Relates to #1310

**Comment by sungam3r** [comment]
Closed in favor of #1310
