### ISSUE TITLE
Remove pattern-based middleware

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1566]
@sungam3r  We discussed removing pattern-based middleware previously, and the thought was that we were trying to maintain compatibility with older third-party middleware libraries.

I've been working on the upgrade guide, and realized that middleware designed for 2.x will not work with 3.0 due to the signature of the Resolve method having changed (`ResolveFieldContext` changed to `IResolveFieldContext`).

I suggest that we either:
- Remove the pattern-based middleware approach entirely, or
- Change the pattern-based middleware approach to scan only for a `Resolve` method with a `ResolveFieldContext` parameter - which exists for backwards-compatibility purposes only

Either way, I believe we should update the documentation to only document the current recommended technique using `IFieldMiddleware`.  The upgrade guide can cover backwards compatibility, if we choose to support it.

Please let me know what you think.

**Comment by Shane32** [comment]
`FieldMiddlewareDelegate` also changed, again due to `IResolveFieldContext`, so in order to maintain backwards compatibility, we would also need to be sure the `next` parameter has the correct signature.  I'm not sure if we need to retain the name of `FieldMiddlewareDelegate` or if we can simply use a `Func<ResolveFieldContext, Task<object>>` for older compiled code to interoperate.

For reference these are the two signatures we are discussing:
``` C#
// version 2.4.0
public Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next);
// version 3.0
public Task<object> Resolve(IResolveFieldContext context, FieldMiddlewareDelegate next);

// version 2.4.0
public delegate Task<object> FieldMiddlewareDelegate(ResolveFieldContext context);
// version 3.0
public delegate Task<object> FieldMiddlewareDelegate(IResolveFieldContext context);
```

**Comment by sungam3r** [comment]
I was expecting this issue. Well, let's go ahead and get rid of the pattern-based case.

**Comment by Shane32** [comment]
Do you want me to write a PR or do you want to?

**Comment by sungam3r** [comment]
PR is welcome.
