### ISSUE TITLE
MiddlewareResolver and SyncToAsyncResolverAdapter are nearly identical

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1573]
`MiddlewareResolver` and `SyncToAsyncResolverAdapter` are nearly identical.  Should one be deleted?

* `SyncToAsyncResolverAdapter` was added since 2.4.0, so deleting it would not be a breaking change from 2.4.0
* It functions almost identical to MiddlewareResolver, except it does not change a null inner `IFieldResolver` to the default `NameFieldResolver.Instance`
* `BaseSchemaNodeVisitor.WrapResolver` is the **only** function to use `SyncToAsyncResolverAdapter`, and does change a null inner `IFieldResolver` to the default `NameFieldResolver.Instance`, thereby **making the function of both resolvers the same**, when used in this function
* Currently, `WrapResolver` returns a `SyncToAsyncResolverAdapter` class, which could be changed to an `IFieldResolver<Task<object>>` signature.  However, the former has a `ResolveAsync` method, where the latter would just be called `Resolve`.  So there's a slight signature difference.

Proposals:
1. Delete `SyncToAsyncResolverAdapter` and make `WrapResolver` return an `IFieldResolver<Task<object>>`, which is a `MiddlewareResolver` (breaking change since the `ResolveAsync` method is now called `Resolve`, although not breaking compared to 2.4.0)
2. Delete `MiddlewareResolver` and change references to it to point to `SyncToAsyncResolverAdapter`. Middleware changed plenty since 2.4.0 anyway, so if this is breaking, it doesn't matter much.
3. Have one of the two classes inherit from the other.  Nothing breaking from current branch.
4. Leave it alone.

**Comment by sungam3r** [comment]
Good that you touched on this topic. I had questions for these classes.

`SyncToAsyncResolverAdapter` is used only in `AsyncUppercaseDirectiveVisitor` for awaiting `inner.ResolveAsync(context);`. No separate class is needed for this, an extension method will be enough. In fact this is nothing more than helper method to check if `Resolve` returns Task:
```c#
 public static class Extensions
    {
        public static async Task<object> ResolveAsync(this IFieldResolver r, IResolveFieldContext context)
        {
            object result = r.Resolve(context);

            if (result is Task task)
            {
                await task.ConfigureAwait(false);
                result = task.GetResult();
            }

            return result;
        }
    }
```

Then
```c#
 public class AsyncUppercaseDirectiveVisitor : SchemaDirectiveVisitor
    {
        public override string Name => "upper";

        public override void VisitFieldDefinition(FieldType field)
        {
            base.VisitFieldDefinition(field);

            field.Resolver = new AsyncFieldResolver<object>(async context =>
            {
                var result = await field.Resolver.ResolveAsync(context);

                if (result is string str)
                {
                    return str.ToUpperInvariant();
                }

                return result;
            });
        }
    }
```

And finally:
```c#
  public void ApplyTo(ISchema schema)
        {
            // allocation free optimization if no middlewares are defined
            if (!Empty)
            {
                foreach (var complex in schema.AllTypes.OfType<IComplexGraphType>())
                {
                    foreach (var field in complex.Fields)
                    {
                        var fieldMiddlewareDelegate = Build(context => field.Resolver.ResolveAsync(context), schema);

                        field.Resolver = new FuncFieldResolver<object>(fieldMiddlewareDelegate.Invoke);
                    }
                }
            }
        }
```

So I prefer option 5.

5. Delete both, convert to extension method.

**Comment by sungam3r** [comment]
@Shane32 Finally done! What do you think about #1582 ? I plan to review your PRs one more time after that tomorrow.

**Comment by Shane32** [comment]
Sorry I can’t look at it now. Maybe tonight.
