### ISSUE TITLE
How can I pass object defined in constructor to query and mutation file?

### ISSUE THREAD

**Issue by ooo2003003v2** [graphql-dotnet/graphql-dotnet#1575]
I have defined a object for accessing the request and response header in constructor but can i pass it to the query and mutation file?

**Comment by sungam3r** [comment]
Mutation _file_? What do you mean?

**Comment by ooo2003003v2** [comment]
> Mutation _file_? What do you mean?
like this
![image](https://user-images.githubusercontent.com/55082067/75404096-7f808a00-5944-11ea-8032-d7f7041a2410.png)

**Comment by sungam3r** [comment]
OK.

> a object for accessing the request and response header in _constructor_

Constructor of which class?

```c#
public class MySchema : Schema
{
  public MySchema(MyParamClass param1, IServiceProvider provider) : base(provider)
  {
    Mutation = new MyMutation(param1);
  }
}
```

Did you mean that?

**Comment by sungam3r** [comment]
@ooo2003003v2 Did you solve this issue?

**Comment by ooo2003003v2** [comment]
> @ooo2003003v2 Did you solve this issue?

Not really but I managed to pass what i need into a Singleton class so it's fine now. Thank you for the help
