### ISSUE TITLE
Document deprecation support

### ISSUE THREAD

**Issue by benmccallum** [graphql-dotnet/graphql-dotnet#1576]
###  Summary

~I'd like to know if it's possible to deprecate a particular value in an enum. Quick Google shows a ruby graphql implementation supports it, so it's definitely a schema-supported thing (and I later found we support it via `EnumerationGraphType::AddValue`.~

In my search I couldn't find any general docs on deprecation of fields/args. I know it's simple enough, but worth documenting in another page ~along with any enum value deprecation support we come up with.~

<details>
  <summary>Scratch this, it's already supported.</summary>
  ### Basic example

  I construct enum graph types by using `EnumerationGraphType<TEnum>`. I notice the base 
  `EnumerationGraphType` supports `AddValue(..., string deprecationReason)` but could we support 
  something like:
  
  ```c#
  public enum MyEnum
  {
      SomeValue,
  
      [Obsolete("Some reason")]
      ObsoleteValue
  }
  
  services.AddSingleton<EnumerationGraphType<MyEnum>>();
  ```

  ### Motivation

  Support obsolete api for enum values when using `EnumerationGraphType<TEnum>`.
</details>

**Comment by benmccallum** [comment]
Had a feeling it would have been done. See [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/f72b07a530f67086efd57cf7933552b10b936f8d/src/GraphQL/Types/Scalars/EnumerationGraphType.cs#L72). Should've looked further. So maybe this issue is just to document it.

**Comment by sungam3r** [comment]
See #924 .

**Comment by benmccallum** [comment]
Haha funny. That's awesome. Closing. Thanks @andrewtyped !
