### ISSUE TITLE
"Virtual member call in constructor" warning when defining fields

### ISSUE THREAD

**Issue by prcdpr** [graphql-dotnet/graphql-dotnet#1579]
I have a lot of "Virtual member call in constructor" warnings in my code since upgrading to v3

![image](https://user-images.githubusercontent.com/43776797/75445806-73a5bf80-5966-11ea-85ef-8dc55f4f344f.png)

![image](https://user-images.githubusercontent.com/43776797/75445814-79030a00-5966-11ea-90ea-0999351f9c6e.png)

Is it something to worry about?

**Comment by sungam3r** [comment]
No. There are a lot of warnings from various analyzers, each of which needs to be treated critically. There are even those that are mutually exclusive 😄

**Comment by sungam3r** [comment]
By the way, could you provide full error text with rule code from your output?

**Comment by prcdpr** [comment]
https://www.jetbrains.com/help/rider/VirtualMemberCallInConstructor.html

It disappears when make my graph type class "sealed"

**Comment by sungam3r** [comment]
You can suppress or ignore this warning.

**Comment by prcdpr** [comment]
OK thanks

**Comment by pekkah** [comment]
There are few field methods marked as virtual. Virtual methods shouldn't be called from ctor without sealing the class as that could lead to weird behavior. I think those Field methods should not be virtual.

**Comment by sungam3r** [comment]
>  Virtual methods shouldn't be called from ctor without sealing the class as that could lead to weird behavior.

Any code could lead to weird behavior. These methods were made virtual intentionally to allow redefinition/tuning of behavior. I understand what the recommendations say. But I also perfectly understand that each recommendation has its limits of applicability. For a long time I have seen enough of the recommendations of various analyzers. You can’t blindly follow them.

And in general, let's carefully read what the rule says. It does not say "your method should not be virtual". It says "do not call it from the constructor". If you want to follow the rule - follow, call this method from somewhere else..

**Comment by pekkah** [comment]
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214

**Comment by sungam3r** [comment]
I am well aware of this.

**Comment by sungam3r** [comment]
I also saw a lot of rules of this analyzer, which in practice do not make sense in 99% of cases.

**Comment by sungam3r** [comment]
For clarification - I constantly use this analyzer together with others in production. I am not against analyzers. I am in favor of a critical approach to the application of their rules.

**Comment by prcdpr** [comment]
@sungam3r analyzers are pretty popular, for example this one from Rider is built-in and I didn't even have to enable it.

You're right about being sensible about application of their rules, but everyone who uses them will be forced either to:
- seal the class
- move field definitions to other method
- disable inspection probably for every class that extends ObjectGraph

This is a lot of unnecessary work for everyone who uses graphql-net and want to make their codebase "green" without warnings (either by disabling rule or fixing it, doesn't matter).

**Comment by sungam3r** [comment]
> disable inspection probably for every class that extends ObjectGraph
> This is a lot of unnecessary work for everyone

Really? Perhaps for those who use Rider. We use GraphQL in more than a hundred microservices with analyzers enabled by default, including FxCopAnalyzers. So far no problems. And of course, we turn off many rules, some more often some less, because the harm from following them is more than good. 

I would not want to delve into the numerous examples. I will give just one example
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007?view=vs-2019

Blindly following this rule everywhere for the "green build" achievement only litter the code. For ASP.NET Core apps, following this rule by the developer only shows his lack of understanding of the environment in which he works.

Summarizing. I prefer when the dog wags its tail, but not vice versa.

**Comment by pekkah** [comment]
Why this leads to a discussion about rules? Some are good and some are bad but you should try to understand what it's trying to tell you. I this case where most people inherit their custom graph types "forcing" people to call virtual methods in ctor can lead to issues when field etc. initialization order is not what would be expected. I would think it would be beneficial to try to design around the issue.

**Comment by sungam3r** [comment]
> Some are good and some are bad but you should try to understand what it's trying to tell you.

I understand what you're trying to say.

> I this case where most people inherit their custom graph types "forcing" people to call virtual methods in ctor can lead to issues when field etc. initialization order is not what would be expected. 

Most people inherit custom graph types but not most people write their own overrides for `ComplexGraphType.Field` virtual method. You are trying to deal with a problem that does not exist.

**Comment by sungam3r** [comment]
See #1351 for more context.

**Comment by sungam3r** [comment]
Closed due to inactivity.
