### ISSUE TITLE
Introspection does not include interface implementations unless implementation directly used

### ISSUE THREAD

**Issue by BillBaird** [graphql-dotnet/graphql-dotnet#1580]
## Description

When defining a GraphQL interface with multiple types implementing it, only those types which are explicitly used in a query or mutation are included in introspection even those those not explicitly used can be returned.

### Steps to reproduce

Consider this set of poco types:

```c#
    public interface Inter
    {
        string InterfaceField { get; set; }
    }
    public class T1 : Inter
    {
        public string InterfaceField { get; set; }
        public string T1Value { get; set; }
    }
    public class T2 : Inter
    {
        public string InterfaceField { get; set; }
        public string T2Value { get; set; }
    }
```
And this corresponding schema-first GraphQL definition
 ```c#
    public class InterType : InterfaceGraphType<Inter>
    {
        public InterType()
        {
            Name = "Inter";
            Field(x => x.InterfaceField);
        }
    }
    public class T1Type : ObjectGraphType<T1>
    {
        public T1Type()
        {
            Name = "T1";
            Interface<InterType>();

            Field(x => x.InterfaceField);
            Field(x => x.T1Value);
        }
    }
    public class T2Type : ObjectGraphType<T2>
    {
        public T2Type()
        {
            Name = "T2";
            Interface<InterType>();

            Field(x => x.InterfaceField);
            Field(x => x.T2Value);
        }
    }
```
And expose them through some trivial queries
```c#
    public partial class SomeQueries : QueryGraphType
    {
        private void RegisterSomeQueries(IService service)
        {
            Field<InterType>(
                "getInter",
                // Type T2 will not be exposed
                resolve: context => return new T2{InterfaceField = "IFaceT2", T2Value = "T2Value"};
            );

            Field<T1Type>(
                "getT1",
                 resolve: context => return new T1{InterfaceField = "IFaceT1", T1Value = "T1Value"}
            );
        }
   }
```
Add them to dependency injection
```c#
    services.AddSingleton<InterType>();
    services.AddSingleton<T1Type>();
    services.AddSingleton<T2Type>();
```
### Expected result

This query should return the interface and both types
```graphql
query t {
  inter: __type(name:"Inter"){name, kind}
  t1:    __type(name:"T1"){name, kind, interfaces{name}}
  t2:    __type(name:"T2"){name, kind, interfaces{name}}
}
```
One would expect:
```json
{
  "data": {
    "inter": {
      "name": "Inter",
      "kind": "INTERFACE"
    },
    "t1": {
      "name": "T1",
      "kind": "OBJECT",
      "interfaces": [
        {
          "name": "Inter"
        }
      ]
    },
    "t2": {
      "name": "T2",
      "kind": "OBJECT",
      "interfaces": [
        {
          "name": "Inter"
        }
      ]
    }
  }
}
```

### Actual result

But the actual result is missing type T2
```json
{
  "data": {
    "inter": {
      "name": "Inter",
      "kind": "INTERFACE"
    },
    "t1": {
      "name": "T1",
      "kind": "OBJECT",
      "interfaces": [
        {
          "name": "Inter"
        }
      ]
    },
    "t2": null
  }
}
```

### Discussion
It appears that the set of possible types is somehow computed for introspection.  Even though the type has been duly created and registered, it is not available for use unless it is explicitly used in a query, mutation, or subscription.  The fact that it could be returned as a concrete implementation of "Inter" is not recognized.

I've looked to see if there is some way to mark the type so that it is recognized as being a type that could be returned (perhaps ResolvedInterfaces or something in MetaData?) but have been unsuccessful.

### Workaround
The addition of a query which explicitly uses or returns type T2 avoids this issue, although the query does not belong in the schema and only serves to polute the schema.  I've taken to declaring a "WorkAround" type, which includes fields for each possible concrete implementation of the interface and then adding a "SchemaTypeWorkaround" query which is declared to return and instance of that type.  This limits the workaround to a single multi-field type addition and a single query.

### Environment

GraphQL 3.0.0-preview-1271 (.net core)

**Comment by sungam3r** [comment]
See docs https://graphql-dotnet.github.io/docs/getting-started/interfaces#registertype

**Comment by BillBaird** [comment]
Thanks.  I knew it should be simple.  I was expecting something on the Type itself rather than the Schema, although this makes sense.  Closing this with egg on my face 😕
