### ISSUE TITLE
Update documentation for ValueConverter

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1581]
- Update documentation in `schema-types.md`
- Add some xml comments
- Note in migration guide

See: https://github.com/graphql-dotnet/graphql-dotnet/pull/1577#discussion_r384824634

Please assign to me; I will issue a PR when I have the time.

**Comment by sungam3r** [comment]
@Shane32 was it included in the migration guide?

**Comment by Shane32** [comment]
I can’t remember. I’ll check tonight or tomorrow.

**Comment by Shane32** [comment]
Yes.  I believe this has been completed.
