### ISSUE TITLE
How to get the parent argument

### ISSUE THREAD

**Issue by Mcaldentey** [graphql-dotnet/graphql-dotnet#1585]
Hi!

I have a query like this:
`{
  rules(provider:"TST"){
    ruleA(client:"A"){
      value
    }
    ruleB(client:"B"){
      value
    }
  }
}`

Someone requested 2 rules of a provider, for different clients.
How can I access to the parent argument (provider) in the ruleA resolver?

In my code i have something like:

```
public class BaseQuery : ObjectGraphType<object>
{
	public BaseQuery()
	{            
		Name = "Query";

		Field<Rules>("rules",
			arguments: new QueryArguments(new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "provider", Description = "Provider" }),
			resolve: context => new Rules());
	}
}
```

```
public class Rules : ObjectGraphType<object>
{
	public Rules()
	{
		Name = "Rules";

		//---- Rule A ----------------------------------
		Field<BoolValueInterface>("ruleA",
			arguments: new QueryArguments(new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "client" , Description = "Client" }),
			
			resolve: context => {          
				//Here I need to get the Provider from Parent query
				return RulesService.GetRuleDummy(/*Send Provider*/);
			}
		);
	}
}
```

The only way I achieved this, was using query variables to send the provider.

Thanks!

**Comment by sungam3r** [comment]
You can use `context.Document` to obtain entire AST of incoming request. Now there is no reference to parent field from `GraphQL.Language.AST.Field`. I myself miss this feature for some projects, while I have to manually parse the document.

**Comment by Mcaldentey** [comment]
Thank you!
