### ISSUE TITLE
How to effectively map all the properties of DTO class to the FiledType class using GraphQL.NET?

### ISSUE THREAD

**Issue by santoshpatro** [graphql-dotnet/graphql-dotnet#1586]
Any help on the below mentioned request is much helpful

https://stackoverflow.com/questions/60496639/how-to-effectively-map-all-the-properties-of-dto-class-to-the-filedtype-class-us

**Comment by sungam3r** [comment]
`AutoRegisteringObjectGraphType<TSourceType>`

**Comment by santoshpatro** [comment]
@sungam3r  : I looking for some reference examples. Can you please help me with sample example containing its implemntation

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/aed5298a435012d41d42dd0a9accebdb3cff1de3/src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs#L85

**Comment by sungam3r** [comment]
Closed as answered.
