### ISSUE TITLE
How can I gain access to the HttpRequest object in n ObjectGraphType Field Resolve Function

### ISSUE THREAD

**Issue by monkeyTrainer** [graphql-dotnet/graphql-dotnet#1591]
This is the code for my GraphQL controller;

    [Route("[controller]")]
    public class GraphQLController : Controller
    {
        private readonly IDocumentExecuter _documentExecuter;
        private readonly ISchema _schema;

        public GraphQLController(ISchema schema, IDocumentExecuter documentExecuter)
        {
            _schema = schema;
            _documentExecuter = documentExecuter;
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
        {
            if (query == null) { throw new ArgumentNullException(nameof(query)); }
            var inputs = query.Variables.ToInputs();
            //I can get the Request Object here
            var executionOptions = new ExecutionOptions
            {
                Schema = _schema,
                Query = query.Query,
                Inputs = inputs
            };

            var result = await _documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);

            if (result.Errors?.Count > 0)
            {       
                return BadRequest(result);
            }

            return Ok(result);
        }
    }

I would like to be able to access the HttpRequest object (obtained in the controller action) in a resolve function of am ObjectGraphType field;

            Field<FooGraphType>(
                "baz",
                resolve: context =>
                {
                    //Get the Request here
                });

More generally, is there a method for including additional information in the "context" or by some other means, so that it can be accessed in the resolve function?

**Comment by sungam3r** [comment]
1. Inject `IHttpContextAccessor`
or
2. Store something into `UserContext` property, it's dictionary of user defined additional information.

**Comment by monkeyTrainer** [comment]
Thanks @sungam3r that'll do nicely.
