### ISSUE TITLE
Is it possible to includes more than one query or mutation class in Schema?

### ISSUE THREAD

**Issue by ooo2003003v2** [graphql-dotnet/graphql-dotnet#1596]
Hello there I have encounter a problem when i need include more than one query file. Is it possible to include more than one in schema?

```c#
this._schema = GraphQL.Types.Schema.For(
                @"type Query {
         hello:String
}      ", _ =>
            {
              
                _.Types.Include<Query>();
                _.Types.Include<GeneralQuery>();
            });
```

**Comment by sungam3r** [comment]
What behavior do you expect to get?

**Comment by ooo2003003v2** [comment]
I am not sure I am doing the right thing because I've split each topic having it's own controllers(eq: push msg, device etc ) instead of one controllers for everything. I have a general response object which can be access by each topic query. So i split it into a general query file but it's not working.

**Comment by sungam3r** [comment]
Query is one of the root GraphQL types. I see you use schema first way where methods from .NET type are mapped to GraphQL **fields**, 1 method of .NET type - 1 field of corresponding GraphQL type. Do you want to combine methods from many .NET types into one GraphQL root Query type?

**Comment by ooo2003003v2** [comment]
Yes. I would love to do that. 
Response Query file

` 


       [GraphQLMetadata("response")] public Response GetResponse()

        {

            Response res = new Response();

            return res;
        }
`

**Comment by ooo2003003v2** [comment]
Yes. I would love to do that. The result I want is that localhost/topic and localhost/device can share the response type.

localhost/topic
query getTopics{
topic
response
}

localhost/device
query getDevices{
device
response
}
`
Device Query file
`

        [GraphQLMetadata("topic")]
        public Response GetTopics(){

            List<GetTopic> res = new List<GetTopic>();
           ...
            return res;

        }
`
Device Query file
`

        [GraphQLMetadata("devices")]
        public Response GetDevices(){

            List<Device> res = new List<Device>();
          ...
            return res;

        }
`
Response Query file
`

        [GraphQLMetadata("response")]
        public Response GetResponse(){

            Response res = new Response();
          ...
            return res;

        }

**Comment by sungam3r** [comment]
Now this feature is not supported.

**Comment by sungam3r** [comment]
I don't think it's worth doing support for this feature, because it will complicate the implementation. Now in the schema first approach, 1 CLR type corresponds to one GraphType. See `TypeConfig.Type` property and its usages. If we allow the aggregation of GraphTypes from several CLR types, then this convention system will need to be completely changed. I am not saying that this is not possible. This is possible, but the benefits are out of proportion to the complexity involved. Closing.
