### ISSUE TITLE
Generate enums as graphqlenumtype in the schema with descriptions

### ISSUE THREAD

**Issue by togakangaroo** [graphql-dotnet/graphql-dotnet#1597]
We have enums with attached descriptions:
```
    public enum DiseaseType
    {
        [Description("Brucellosis")]
        BR,
        [Description("Chronic Wasting Disease")] 
        CWD,
        [Description("Scrapie")]
        SCR,
        [Description("Tuberculosis")]
        TB,
        [Description("Avian Influenza")]
        AI,
        ...
```

I assumed that when I looked in my schema I'd see all that in a [`GraphqlEnumType`](https://graphql.org/graphql-js/type/#graphqlenumtype) but instead see the following in the schema in my graphql playground

```
enum DiseaseType {
  BR
  CWD
  SCR
  TB
  AI
```

we do have this registered via IoC
```
graphQLBuilder.Services.AddSingleton(typeof(DiseaseType), _ => new EnumerationGraphType<DiseaseType>());
```

So is it possible to include descriptions along with the values?

**Comment by sungam3r** [comment]
What version do you use? Try the latest preview.

**Comment by sungam3r** [comment]
Also see docs https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/schema-types.md#enumerations

**Comment by togakangaroo** [comment]
Interesting, I'm on 3.0.0-preview-1352 released 3 months ago, @sungam3r are you saying that what I'm seeing above in the schema is not what I should be seeing?

**Comment by sungam3r** [comment]
> I assumed that when I looked in my schema I'd see all that in a GraphqlEnumType but instead see the following in the schema in my graphql playground

GraphQL Playground has 2 tabs - one for schema (without descriptions) and one for docs. Where are you looking for descriptions?
![изображение](https://user-images.githubusercontent.com/21261007/76184276-62697800-61dc-11ea-9490-16ee387ea90b.png)

**Comment by togakangaroo** [comment]
Hmm, I see - I was looking under schema. So the issue is that we generate Typescript types from our front end using the Apollo generators. As best as I know, these use the schema and are missing any descriptions. My task is to figure out how to include the descriptions in there since they become labels for selectors (I know, but in this case localization is not an issue).

**Comment by sungam3r** [comment]
Actually GraphQL schema (SDL - Schema Definition Language) has descriptions. GraphQL Playground is just UI. You should change GraphQL Playground settings to enable descriptions: 
![изображение](https://user-images.githubusercontent.com/21261007/76222053-14c82c00-622b-11ea-8824-6d93b2117ab2.png)

**Comment by togakangaroo** [comment]
Hmm, I just realized that `GraphEnumType` link I included above was to the graph-js library, not the spec.

What I'm seeing now is
```
enum ActivityResultType {
  # Blood Drawn
  DRAWN
  # Vaccinated
  VACC
  # Injected
  INJ
  # Negative
  NEG
  # Not Treated
  NO
```

I was thinking there was something in the spec itself that actually would put descriptions in enum definitions but it sounds like that is not the case 😢

**Comment by sungam3r** [comment]
Can I help you with something else?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
