### ISSUE TITLE
Query Batching multi threaded?

### ISSUE THREAD

**Issue by adarisGmbH** [graphql-dotnet/graphql-dotnet#1599]
Hi
I'm wondering, how does GraphQL.NET handle batch queries under the hood? Does it execute each query in parallel using separate .NET tasks/threads ? Or sequential? And: Can this behavior be configured somehow? 

In my opinion the following strategy would be ideal:
- Queries should execute in parallel 
- Mutations shold execute sequentially in the order they were specified in the request (allows a mutation to depend on a preceeding mutation)

Thanks for clarifying.
Marco

**Comment by sungam3r** [comment]
Each query (fields inside this query) is executed in parallel. Each mutation sequentially. It meets the GraphQL specification.

For request batching no behavior described. Howewer [this issue](https://github.com/APIs-guru/graphql-over-http/issues/5) was posted. Now batched queries are executed sequentially but this topic specific to [server repo](https://github.com/graphql-dotnet/server/blob/develop/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L145), not to this project.

**Comment by sungam3r** [comment]
> Can this behavior be configured somehow?

Yes. You can override `DocumentExecuter.SelectExecutionStrategy`. For request batching there are no (yet) options in the server repo to configure parallel/sequential behaviour.

**Comment by adarisGmbH** [comment]
Thanks a lot for your answer!
