### ISSUE TITLE
Support async cancellation / timeout

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#16]

**Comment by scmccart** [comment]
If you like, I can take on adding cancellation support. I think timeout should be handled by the caller of the library, though it can be baked in easily on top of the cancellation.

**Comment by moserware** [comment]
@scmccart that'd be great! It should be a matter of adding a `CancellationToken cancellationToken = default(CancellationToken)` as a final optional parameter to `ExecuteAsync` and then flow that to the `ExecutionContext` where resolve methods can optionally use it. There might also be places where ` cancellationToken.ThrowIfCancellationRequested();` calls might make sense or doing some minor optimizations by checking if the token is non-default by looking at the [CanBeCanceled](https://msdn.microsoft.com/en-us/library/system.threading.cancellationtoken.canbecanceled(v=vs.110).aspx) property. 

Timeouts would then be trivial:

```
var cancelSource = new CancellationTokenSource();
cancelSource.CancelAfter(TimeSpan.FromSeconds(30));
var result = await executer.ExecuteAsync(..., cancelSource.Token);
```

**Comment by joemcbride** [comment]
Marking this as done with the changes made.
