### ISSUE TITLE
Add Overlapping fields can be merged validation rule

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#160]
Since this is a massive rule, I moved it from #10 to its own issue.
- [ ] [Overlapping fields can be merged](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/OverlappingFieldsCanBeMerged.js) / [tests](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js)

**Comment by KoditkarVedant** [comment]
@joemcbride I would like to take a shot at it. I have started the initial work.
