### ISSUE TITLE
Schema exception when using interfaces

### ISSUE THREAD

**Issue by adarisGmbH** [graphql-dotnet/graphql-dotnet#1600]
Consider the following scenario:

- GraphQL Interface "Animal"
- One GraphQL Type "Dog" and another called "Cat"
- query { animals { items { name } } } -> returns a Connection to interface Animal

Now, when using GraphQL with this scenario, I get an exception in some cases:

> Schema is not configured correctly to fetch name.  Are you missing a root type?

I suspect the reason is that I don't have explicit Connections to Dog and Cat in my schema. I am, however, using GraphTypeTypeRegistry.Register<Cat, CatGraphType>(), but that doesn't seem to help.

I've been able to resolve the issue by adding a pseudo top level query like so:

```Field<CatGraphType>("Ignore", resolve: i => null);```

Is there a proper way to solve this? I don't want to expose the types Cat and Dog in separate queries, they are only used as subtypes whithin the Animal connection.

Thanks!

**Comment by adarisGmbH** [comment]
PS: I seem to have solved the problem likes this:
```csharp
schema = new Schema { Query = new AppQuery(), Mutation = new AppMutation() };
schema.RegisterType<CatGraphType>();
schema.RegisterType<DogGraphType>();
```

Could you confirm if this is the correct way to do it?

**Comment by sungam3r** [comment]
Probably. It’s hard for me to say without seeing the schema definition. Also see this https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/interfaces.md

**Comment by adarisGmbH** [comment]
@sungam3r Thanks a lot, that confirmed my assumption. I must have missed that part of the documentation.
