### ISSUE TITLE
graphql-parser comments are lost when I call CoreToVanillaConverter.Convert(string body, GraphQLDocument source)

### ISSUE THREAD

**Issue by vincent-duret** [graphql-dotnet/graphql-dotnet#1603]
I am using graphql-dotnet v3-preview1490 and graphql-parser v5.1.0.
I did notice that the comments are well-parsed and present in the GraphQLDocument source parameter, but I have no way to get access to them through the Document returned by the CoreToVanillaConverter.Convert(string body, GraphQLDocument source) method.
Is it a well-known bug/limitation? Any clue to workaround this?

By the way, what is the justification to maintain two different ASTs? One inside graphql-dotnet and the other inside graphql-parser. It forces to stay in sync when the parser evolves for instance.

Thanks by advance
Vincent

**Comment by sungam3r** [comment]
> By the way, what is the justification to maintain two different ASTs? One inside graphql-dotnet and the other inside graphql-parser. It forces to stay in sync when the parser evolves for instance.

@joemcbride ?

**Comment by sungam3r** [comment]
Do you mean input request document?

**Comment by vincent-duret** [comment]
Not sure to get your question but if it might help, here is the document I am trying to parse:
#id: id of the employee
query _($id: ID = "00000000-0000-0000-0000-000000000000") {
  DummyEmp(_where: {idDummyEmp: {_eq: $id}}) {
    #comment for id
    id: idDummyEmp
    name: strName
    email: Email
    phone: Phone
    address: Address
    city: City
  }
}

**Comment by vincent-duret** [comment]
I did have a look to the source of the CoreToVanillaConverter class.
For instance, in the method Field Field(GraphQLFieldSelection source), the Comment property from the source parameter is not copied in the field variable returned by that function.

**Comment by sungam3r** [comment]
Yes, it is input query document. I see that comments are not used anywhere in the `CoreToVanillaConverter`. @joemcbride is this done on purpose?

**Comment by vincent-duret** [comment]
@sungam3r @joemcbride maybe you should have a way to access the underlying type from the parser. E.g. Field.Source

**Comment by sungam3r** [comment]
What underlying type from the parser?

**Comment by vincent-duret** [comment]
For instance, in the method `public Field Field(GraphQLFieldSelection source)` you build a field from the source parameter.
In the method, we could have:
`field.Source = source` where Source is of type GraphQLFieldSelection

It would allow to access all the properties coming from the graphql-parser node.
