### ISSUE TITLE
Mutation arguments: Is there any compile-time connection between GraphType and actual class used in the resolver?

### ISSUE THREAD

**Issue by GrangerAts** [graphql-dotnet/graphql-dotnet#1605]
## Summary
While writing a mutation, I noticed that there's no compile-time/strongly-typed connection between the GraphType used as the mutation's argument and the class you use when you call `context.GetArgument<T>()`. 

For example, 
[The Gql.Net example](https://graphql-dotnet.github.io/docs/getting-started/mutations/) has no compile-time/strongly-typed connection between `Human` and `HumanInputType`. And [Fiyaz's tutorial](https://github.com/fiyazbinhasan/GraphQLCore/tree/Part_VII_Mutation) also has no compile-time/strongly-typed connection between the `Item` and `ItemInputType` classes.

`GetArgument` ultimately just runs through an IDictionary<string, object> and tries to cast the data it finds into the properties of the type that was specified when it was called. This is very brittle and I'd like to know the best way to avoid it. Is there anything coming up in Gql.Net 3.x that's going to help resolve this?

**Comment by sungam3r** [comment]
You are right. There's no strongly-typed connection between the GraphType and .NET argument type. This is by design and I don’t think that anything will change in the near future.

> This is very brittle

On the other hand it is rather flexible.

Gql.Net version 3 has many improvements over all codebase including better `GetArgument<T>` experience: parametrized ctors for arguments, custom converters, correct mapping for explicitly set fields names. Here is some of PRs:  #1107, #1577, #1582

**Comment by GrangerAts** [comment]
OK, thanks. That's good to know; I can proceed. And looking at those referenced PRs, it appears I'm planning on going the same direction as other have already gone. 

The plan continues to be to tie the InputGraphType's fields to the backing ViewModel/DTO as best as possible, then rely on naming/code conventions and training to get others to keep a consistent paradigm. (Pretty much the same thing that @benmccallum had in [this example](https://github.com/graphql-dotnet/graphql-dotnet/pull/1582#issuecomment-592432406) from #1582)

**Comment by benmccallum** [comment]
In my example, you can see how I use `nameof` to protect me from graph type field name or dto property name changes. For more complicated scenarios though unit tests would close the gap if you were worried. Something simple that ensure GetArgument<T> from a context does what you expected 100%.

**Comment by sungam3r** [comment]
The original question not only about argument name but also about all argument structure.
