### ISSUE TITLE
Can't find extension method 'AddSystemTextJson' 

### ISSUE THREAD

**Issue by ibramn** [graphql-dotnet/graphql-dotnet#1607]
**Error**: 'IGraphQLBuilder' does not contain a definition for 'AddSystemTextJson' and no accessible extension method 'AddSystemTextJson' accepting a first argument of type 'IGraphQLBuilder' could be found (are you missing a using directive or an assembly reference?)

I already installed package **GraphQL.SystemTextJson**,
I'm using dotnetcore 3.1
Thank you.

**Comment by sungam3r** [comment]
Read this https://github.com/graphql-dotnet/server 
 GraphQL.SystemTextJson <> GraphQL.Server.Transports.AspNetCore.SystemTextJson

**Comment by ibramn** [comment]
Thank you for your fast reply,
I added the package using
`Install-Package GraphQL.Server.Transports.AspNetCore -Version 3.5.0-alpha0046`
 and it worked.
