### ISSUE TITLE
Does graphql-dotnet support apollo federation for .NET Framework 4.6.1/4.6.2/4.7.1 ?

### ISSUE THREAD

**Issue by rvtarig7** [graphql-dotnet/graphql-dotnet#1608]
Hi,
We already have an existing graph that uses apollo federation principle and we would like to know if we can use graphql-dotnet for developing federated graphql service using  .NET framework so that we can integrate this federated graph.

**We have a limitation to stick with .NET framework and not to use .NET Core 3.X**

So wondering if we can achieve the aforementioned requirement using .NET Framework and dotnet-graphql.

**Comment by sungam3r** [comment]
I know that subscriptions are a limiting factor (.NET Core only), everything else should work.

**Comment by sungam3r** [comment]
Closed as answered.
