### ISSUE TITLE
Issues with Scoped DbContext since switch to 3.0

### ISSUE THREAD

**Issue by julienFlexsoft** [graphql-dotnet/graphql-dotnet#1610]
## Summary
Hi!
Yesterday I updated my project to .NET Core 3.1. I then updated all my dependencies to the latest version. I then switched to graphql-dotnet 3.0. But now I have the classic EfCore "A second operation started on this context before a previous operation completed" error. Which is weird because I didn't have this issue before the update. And when I switch back to my not-yet-updated branch it all still works.

After researching this issue I found a potential solution which is to changed my query execution to work in series instead of the default parallel. The thing is, I have no idea where to do that. Is it somewhere in Startup.cs, or in my schema, or somewhere else? I can't find any examples so I'm quite lost.

## Relevant information
`
GraphQL - 3.0.0-preview-1490
GraphQL-Parser - 5.1.0
GraphQL.Authorization - 3.0.39-preview-39
GraphQL.Server.Transports.AspNetCore - 3.5.0-alpha0046
GraphQL.Server.Transports.AspNetCore.SystemTextJson - 3.5.0-alpha0046
GraphQL.Server.Transports.WebSockets - 3.5.0-alpha0046
GraphQL.Server.Ui.Playground - 3.5.0-alpha0046
GraphQL.SystemTextJson - 3.0.0-preview-1490`

**Comment by pekkah** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues?q=is%3Aissue+is%3Aopen+DbContext

**Comment by julienFlexsoft** [comment]
Thank you for taking the time to answer me! I've looked at those related issues but none can be applied to my problem.

1. It all worked (and it still does) before the switch to 3.0
2. My DbContext must stay scoped, my business logic layer manipulates the data from a lot of different places and the result is only saved a the end. All the separate components must work on the same DbContext

**Comment by sungam3r** [comment]
@julienFlexsoft Version 3.0.0 became "more parallel" so now you **may** see errors where they were not before. To understand the conceptual problem with `DbContext`, please read #1310 .

Short answer for you now is
```c#
ExecutionOptions.MaxParallelExecutionCount = 1;
```

**Comment by julienFlexsoft** [comment]
> Version 3.0.0 became "more parallel"

Aha! Thanks, that already explains a lot!

> ExecutionOptions.MaxParallelExecutionCount = 1;

I read #1310 but I can't find where to set that option. I feel stupid but I really have no idea.
Is it in the Startup.cs? 

`
                services.AddGraphQL(o => { o.ExposeExceptions = false; })
                    .AddGraphTypes(ServiceLifetime.Scoped)
                    .AddSystemTextJson(deserializerSettings => { }, serializerSettings => { })
                    .AddDataLoader()
                    .AddWebSockets()
                    .AddUserContextBuilder(context => new GraphQLUserContext { User = context.User });`

**Comment by sungam3r** [comment]
My bad, wait a little for PR.

**Comment by sungam3r** [comment]
Let me know if the error is gone.

**Comment by julienFlexsoft** [comment]
Alright thanks!
How can I test it? Do I simply update GraphQL.Server.Transports.AspNetCore?
The latest version I see is 3.5.0-alpha0046 which I already have. Do I have to wait some time? Or do I have to get the code from the github develop branch without going through Nuget?

I've never done this before and I kind of feel out of my depth. Is there a resource I can read to understand it?
