### ISSUE TITLE
Enum values end up with underscores in name when they shouldn't

### ISSUE THREAD

**Issue by togakangaroo** [graphql-dotnet/graphql-dotnet#1618]
I have an enum exposed that contains the value `BR454` - graphql-dotnet seems to be converting it automatically to `BR_454`. This is not correct and I can't seem to find where this is configured. I tried the `FieldNameConverter` option but that quixotically seems to affect everything *except* enum fields.

Is this configured elsewhere?

```
    <PackageReference Include="GraphQL" Version="3.0.0-preview-1352" />
```

**Comment by togakangaroo** [comment]
Ok, so I kind of have an answer to this myself. The solution is to create *your own* `EnumerationGraphType<>` and override the casing feature

```
    public class NoCasingNonsenseEnumerationGraphType<TEnum> : EnumerationGraphType<TEnum> where TEnum : Enum
    {
        protected override string ChangeEnumCase(string val) => val;
    }
```

then register that as an `EnumerationGraphType<>` in the graphql inversion of control container.

                graphQLBuilder.Services.AddSingleton(typeof(EnumerationGraphType<Foo>), _ => new NoCasingNonsenseEnumerationGraphType<Foo>());

For the project team - can I offer up the suggestion of either changing it so that this *does* go through the `FieldNameConverter` or making it very clear in both documentation and doc comments for where to look for enum value conversion. I understand that enum values aren't technically "fields" but that's really not what anyone running into this issue is going to be thinking about at the time.

Also, consider just not changing the casing at all...

**Comment by sungam3r** [comment]
> I understand that enum values aren't technically "fields" but that's really not what anyone running into this issue is going to be thinking about at the time.

Right. Enum values are not fields. Anyone?

> making it very clear in both documentation and doc comments for where to look for enum value conversion. 

Already there. https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/schema-types.md#enumerations

> Also, consider just not changing the casing at all..

Official  graphql spec explicitly recommends CONSTANT_CASE for enum values so this is default behavior and will not change.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
