### ISSUE TITLE
🐛 Upgrading to 5.1 causes method not found

### ISSUE THREAD

**Issue by denisedelbando** [graphql-dotnet/graphql-dotnet#1620]
## Description
I am getting this issue in version 5.1 but not with previous versions. 

```"message": "GraphQL.ExecutionError: Method not found: 'System.Collections.Generic.IEnumerable`1<GraphQLParser.AST.ASTNode> GraphQLParser.AST.GraphQLDocument.get_Definitions()'. ---> System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<GraphQLParser.AST.ASTNode> GraphQLParser.AST.GraphQLDocument.get_Definitions()'.\r\n   at GraphQL.Language.CoreToVanillaConverter.AddDefinitions(GraphQLDocument source, Document target)\r\n   at GraphQL.Language.CoreToVanillaConverter.Convert(String body, GraphQLDocument source)\r\n   at GraphQL.Execution.GraphQLDocumentBuilder.Build(String body)\r\n   at GraphQL.DocumentExecuter.<ExecuteAsync>d__8.MoveNext()\r\n   --- End of inner exception stack trace ---",
      "extensions": {```

## Other info

- I am using latest Autofac version
- I just created a really simple query (no dependencies)
- Ioc config:
```
builder.RegisterInstance(new DocumentExecuter()).As<IDocumentExecuter>();
            builder.RegisterInstance(new DocumentWriter(true)).As<IDocumentWriter>();

            #region Dataloaders
            builder.RegisterInstance(new DataLoaderContextAccessor()).As<IDataLoaderContextAccessor>();
            builder.RegisterType<DataLoaderDocumentListener>().As<IDocumentExecutionListener>();
            #endregion

            #region types (inputs and enums), query and schema here

            builder.RegisterType<GraphQLQueries>().AsSelf();
            builder.RegisterType<GraphQLSchema>().As<ISchema>().InstancePerLifetimeScope();
            #endregion

            builder.Register<IDependencyResolver>(c =>
            {
                var context = c.Resolve<IComponentContext>();
                return new FuncDependencyResolver(type => context.Resolve(type));
            });
```

### Steps to reproduce

Upgrade to 5.1

### Environment

Version 5.1, Windows, localhost

**Comment by sungam3r** [comment]
Upgrade to 5.1 from what version?
What version of graphql-dotnet do you use?

**Comment by denisedelbando** [comment]
> Upgrade to 5.1 from what version?
> What version of graphql-dotnet do you use?

Sorry. from 4.1.2 to 5.1

**Comment by sungam3r** [comment]
And graphql-dotnet version?

**Comment by denisedelbando** [comment]
> And graphql-dotnet version?
Parser - 4.1.2 to 5.1
Graphql dotnet - Version 2.4 (didn't change it)

Also not using dot net core

**Comment by sungam3r** [comment]
4.1.2 -> 5.1 migration has breaking changes as well as any major version bump. The graphql-dotnet version that you are using now was compiled for 3.0.0 parser, so it’s natural to expect run-time errors with the version 5.1 (even with 4.x.x). You can upgrade graphql-dotnet to the latest preview or downgrade parser back to 4.1.2.

**Comment by denisedelbando** [comment]
ok. i will check. if it fixes, then i will wait for the stable version and just use 4.1.2 for now. thank you.

**Comment by sungam3r** [comment]
Stable release will not be available soon.

**Comment by sungam3r** [comment]
@denisedelbando I'm closing this issue. If you cannot solve the problem, please contact again.

**Comment by denisedelbando** [comment]
> @denisedelbando I'm closing this issue. If you cannot solve the problem, please contact again.

this is fine. using 5.1 was the issue
