### ISSUE TITLE
Why have separate repos with dependencies to each other?

### ISSUE THREAD

**Issue by BenjaBobs** [graphql-dotnet/graphql-dotnet#1624]
## Summary
Currently [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) and [server](https://github.com/graphql-dotnet/server) are two different repositories.
**graphql-dotnet** is the core repo, and **server** provides ASP.NET Core implementations to stand up a server easily.
Each are published to their own NuGet packages.
Each have dependencies to each other. **server** uses all core things from **graphql-dotnet** and the `Harness` project in **graphql-dotnet** uses everything in **server**.

At this point they are so intertwined that I think there is benefit to merging the repositories, and maybe the solutions.

Possible benefits to this approach:
* Easier cross-project tests.
* Faster releases for **server** projects.

Downsides
* A lot of work to get done
* Solution size can affect loading time in IDE.

I'm sure I missed some good points, but I'm hoping to start a discussion about it. 😃

**Comment by sungam3r** [comment]
Yes, you missed some things.

1. [not important] There are even more repos - parser repo too.
2. [important] 
> Each have dependencies to each other. server uses all core things from graphql-dotnet and the Harness project in graphql-dotnet uses **everything** in server.

Wrong. First, Harness is a **test** sample project. Second, Harness uses **only auxiliary** packages:
- `GraphQL.Server.Ui.Altair`
- `GraphQL.Server.Ui.GraphiQL`
- `GraphQL.Server.Ui.Playground`
- `GraphQL.Server.Ui.Voyager`

They are added there for ease of testing and experimentation. And by the way, these packages can just be moved to a separate repository from server repo. These are just ASP.NET Core middlewares with some html templates inside to startup corresponding ui apps, no additional dependencies.

I can say with great certainty that graphql-dotnet and server repos should not be merged. Vice versa - server repo should be split for moving UI thing out.

**Comment by BenjaBobs** [comment]
> Yes, you missed some things. ...things
Ah, good point. I missed that, I must admit I didn't look enough into the Harness project, just had a quick look at the csproj and assumed it was a sample project using **GraphQL.Server**, my bad.

This leads me to another question: Why isn't it? Why not use **GraphQL.Server**? It essentially provides a subset of the same features.

> I can say with great certainty that graphql-dotnet and server repos should not be merged. Vice versa - server repo should be splitted for moving UI thing out.

I like the idea of separating the UI middlewares, as they are standalone, good point.

What do you think about the point of keeping the **server** project more aligned with the **graphql-dotnet** though?
Looking back at the issues I think there is a lot of activity that is different forms of "**graphql-dotnet** got an update, when can we see it in **server**"?

**Comment by sungam3r** [comment]
> This leads me to another question: Why isn't it? Why not use GraphQL.Server? It essentially provides a subset of the same features.

To show how this can be done **manually** without external packages. It is by design.

>   there is a lot of activity that is different forms of "graphql-dotnet got an update, when can we see it in server"?

Has there ever been such a problem? I regularly update dependencies.

**Comment by BenjaBobs** [comment]
> To show how this can be done manually without external packages. This is by design.

Would that not advocate not adopting the server package? 
When talking about ASP.NET Core web api, ideally the **server** packages would be used since they implement so much and are well tested.
Or am I missing something? Are you using custom web api code for your projects?
I could see the idea for non-ASP.Net Core web api's though. Console apps and such.

> Has there ever been such a problem? I regularly update dependencies.

It seems mostly issues regarding when the next release to NuGet will be actually. For the **server** repo, that is.

**Comment by sungam3r** [comment]
> Would that not advocate not adopting the server package?

No, necause server package samples are in server repo :)

> Are you using custom web api code for your projects?

No, I use server project nugets.

> It seems mostly issues regarding when the next release to NuGet will be actually. 

This is totally different problem. All dev packages are always available from myget feed. From time to time (once a month or two) they are published to nuget feed. People are often wondering when the 3.0.0 release will be. The answer is - the work in progress, PRs are welcome.

**Comment by BenjaBobs** [comment]
> This is totally different problem.

I guess that answers the last of my questions, an this issue can be closed. 😄
