### ISSUE TITLE
Many to many with dataLoader

### ISSUE THREAD

**Issue by flieks** [graphql-dotnet/graphql-dotnet#1625]
How can we achieve many to many with dataLoader?

Lets say i want to fetch the companies with there contacts (and a contact can have multiple companies).
I have a companyLinks as midde table (with companyId/contactId).

I have this which works when there is only 1 contact for a company:

``` 
public async Task<ILookup<Guid, Contact>> GetContactsFromCompanyBatchAsync(IEnumerable<Guid> companyIds)    
{
  var contacts = _entities.Include(c => c.CompanyLinks).Where(contact => contact.CompanyLinks.Any(cl => companyIds.Contains(cl.CompanyId)));
  return contacts.ToLookup(cont => {
       var res = cont.CompanyLinks.Any() ? cont.CompanyLinks.ElementAt(0).CompanyId : Guid.Empty;
       return res;
  });
}
```
But what if a contact has more then 1 company? How can i know the correct companyId ?

[stackoverflow](https://stackoverflow.com/questions/60877199/many-to-many-with-dataloader-in-graphql-dotnet)

**Comment by flieks** [comment]
Is there any workaround for this issue ?
Will it be available in the next version ?

**Comment by sungam3r** [comment]
I understand that dataloader utility makes it possible to group requests by key, then to call the delegate 1 time with the array of keys. Dataloader makes no assumptions about what is going on inside the delegate and how you group your data inside it. It is out of dataloader's scope.

**Comment by flieks** [comment]
@sungam3r great, your hint put me to think about how to solve it in the delegate. I just have to start from the join-table (connecting both tables).
Solution for the above query: 
```
 public async Task<ILookup<Guid, Contact>> GetContactsFromCompanyBatchCollectionAsync(IEnumerable<Guid> companyIds)
        {
            var companyContacts = _salesNoteContext.CompanyContact
               .Where(contactCompany => companyIds.Contains(contactCompany.CompanyId))
               .Include(contactCompany => contactCompany.Company);
            return companyContacts.ToLookup(inter => inter.CompanyId, inter => inter.Contact);
        }
```
