### ISSUE TITLE
GraphQL.ObjectExtensions.ToObject(this source, type) does not consider properties having "new" keyword

### ISSUE THREAD

**Issue by bugged84** [graphql-dotnet/graphql-dotnet#1626]
## Description

When calling `GetArgument<T>("name")`, internally the `GraphQL.ObjectExtensions.ToObject(this source, type)` method is called to deserialize the specified argument into an object of type `T`. However, that method internally calls `type.GetProperty("name")` which raises an `AmbiguousMatchException` when type `T` is a type having the specified property decorated with the `new` keyword _and_ derived from a base type having a property of the same name.

### Steps to reproduce

```
public class MyBaseType
{
    public MyChildBaseType MyChildProperty { get; set; }
}

public class MyDerivedType : MyBaseType
{
    public new MyChildDerivedType MyChildProperty { get; set; }
}

public class MyChildBaseType
{
    public string MyProperty { get; set; }
}

public class MyChildDerivedType
{
}

ctx.GetArgument<MyDerivedType>("MyProperty");
```

### Expected result

Property decorated with `new` keyword should be deserialized.

### Actual result

`AmbiguousMatchException` is raised.

### Source

![image](https://user-images.githubusercontent.com/23638686/77954180-e1117c80-7293-11ea-9ffe-29a689faa19e.png)

### Suggested Fix

```
PropertyInfo property =
     type
    .GetProperties(BindingFlags.IgnoreCase | BindingFlags.Instance | BindingFlags.Public)
    .FirstOrDefault(x => x.Name == keyValuePair.Key && x.DeclaringType == type);
```

**Comment by sungam3r** [comment]
The code you provided in the picture does not correspond to the master branch. I added a test demonstrating that everything already works the way you want. Nevertheless, the way to get the property remains the same as in the picture, so I don’t understand why you get such an error.

**Comment by bugged84** [comment]
@sungam3r the code provided in the picture corresponds to the latest version of the Nuget package that is available (i.e. 2.4.0).

Here is the stack trace evidence of error.

```
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at GraphQL.ObjectExtensions.ToObject(IDictionary`2 source, Type type)
   at GraphQL.Types.ResolveFieldContext`1.GetArgument[TType](String name, TType defaultValue)
   ...
   --- End of inner exception stack trace ---
```

**Comment by bugged84** [comment]
@sungam3r I've updated the "steps to reproduce" in the issue description to make your test fail.

**Comment by sungam3r** [comment]
What is inside `ctx.Arguments` ?

**Comment by sungam3r** [comment]
>  the code provided in the picture corresponds to the latest version of the Nuget package that is available (i.e. 2.4.0).

It is the last _stable_ (and rather old) version. There are many preview versions not only on myget feed but also on nuget.

**Comment by sungam3r** [comment]
What is your runtime?

**Comment by bugged84** [comment]
@sungam3r I'm not going to use a preview version. If the latest stable version is "rather old" as you say then maybe it's time for a new release of the library.

`<TargetFramework>netcoreapp2.2</TargetFramework>`

**Comment by sungam3r** [comment]
> What is inside ctx.Arguments ?

I need this to write test.

**Comment by sungam3r** [comment]
Regarding your example. `MyChildDerivedType` does not inherit `MyChildBaseType`. Is that what you intended?

**Comment by sungam3r** [comment]
Nevermind, I reproduced the error.

**Comment by sungam3r** [comment]
I fixed the error, the fix will appear in the next preview version.

Regarding pathing bugs in 2.4.0. We do not release patched verions for 2.4.0 and it will remain as it is.

**Comment by sungam3r** [comment]
Published as 3.0.0-preview-1627

**Comment by bugged84** [comment]
For anyone interested in a workaround for the latest stable version (2.4.0) you can add the following extension method to your code. It uses Newtonsoft.Json to deserialize the specified context argument on a case by case basis (by default it will use GraphQL.NET to deserialize the context argument).

```
public static TType GetArgument<TType>(
    this ResolveFieldContext<object> context
  , string name
  , TType defaultValue = default
  , bool useInternalResolver = false
 )
{
    return useInternalResolver
        ? context.HasArgument(name)
            ? JObject.FromObject(context.Arguments[name]).ToObject<TType>()
            : defaultValue
        : context.GetArgument(name, defaultValue);
}
```

**Comment by bugged84** [comment]
Thanks @sungam3r
