### ISSUE TITLE
Add DataModel First support for FederatedSchema

### ISSUE THREAD

**Issue by dillanmann** [graphql-dotnet/graphql-dotnet#1628]
## Summary

Make it possible for consumers of graphql dotnet to create a federated schema using the model first approach. Currently it is only possible to create a federated schema using the 'Schema First' approach.

#1233 provided the initial support for FederatedSchema but this only works for Schema First.

### Basic example
Currently the FederatedSchema is created by doing:
`FederatedSchema.For(<schema string>, <types>);`

I am unsure how a new API for this would look.

### Motivation

The current implementation using 'schema first' has a number of limitations, including:
- No C# data modelling of schema
- Some levels of authentication are not supported when doing schema first
- If schema is very large it can become cumbersome to update

Advantages of implementing this would be:
- Can define the entire GraphQL schema using InputType implementations with C# code
- Can properly make use of net core dependency injection (which schema first does not seem to leverage)

**Comment by mastery-preeti-bhambhani** [comment]
With reference to the example given in [#1233](url) (Accounts service in .Net), I have a few questions: 
1. Querying data fails when class Query is renamed to something different. Is this a mandatory requirement?
2. This part of code is never executed. When is this required?
```
       return FederatedSchema.For(
        ...
           _.Types.For("User").ResolveReferenceAsync(context =>
                    {
                        var id = (string)context.Arguments["id"];
                        return store.GetUserById(id);
                    });
          ...
         )
```

3. How can I implement a query method with arguments to run the below query
```
query {
   me(id:"1"){
    name
    username
  }
}
```

**Comment by Shane32** [comment]
Related:
- #3144

**Comment by Shane32** [comment]
Federation 2 support is available for schema-first, code-first, and type-first schemas in GraphQL.NET 8.0 (still in beta at the time of writing). See:

- https://github.com/graphql-dotnet/graphql-dotnet/pull/3921
