### ISSUE TITLE
How do I register a generic base interface without name collisions?

### ISSUE THREAD

**Issue by andrejohansson** [graphql-dotnet/graphql-dotnet#1630]
## Summary

I want to do the following:

- Register an ``InterfaceGraphType<T> where T: IBaseEntity`` where ``IBaseEntity`` contains some very generic fields (Id, Created and Updated)
- Create an abstract generic base object to inherit from so that my object types does not have to implement the same fields over and over again
- Inherit this base object class from different types 
- I want the interface be the same for all objects implementing it. That is, i want them all to implement ``BaseEntityInterface`` and not ``BaseEntityInterface<TypeName>``.
    - I want to be able to click on the ``BaseEntityInterface`` in a documentation explorer and list all the types implementing this interface. That will not happen if a generic typename is generated for each implementation. Then there will be only one per interface.
  
Right now, if I use this approach I get a name collision telling me that the name is already registered (if I don´t generate unique names). So I guess I'm going about this in the wrong way...any hints? 

And I do, of course want to use the benefits of having generics so things get typechecked by the compiler.

I think the actions in #510, and #1284 prevents my use case (which I think is legit)?

## Relevant information

```csharp
 public class BaseEntityInterface<T> : InterfaceGraphType<T> where T: IBaseEntity
    {
        public BaseEntityInterface()
        {
            this.Description = "An entity with a id and created/updated timestamps";

            this.Field(x => x.Id)
                .Description("The unique identifier of the entitity.");
            this.Field(x => x.Created)
                .Description("Timestamp when the entity was first created.");
            this.Field(x => x.Updated)
                .Description("Timestamp when the entity was last updated.");
        }
    }

 public abstract class BaseEntityObject<T> : ObjectGraphType<T> where T: IBaseEntity
    {
        public BaseEntityObject()
        {
            this.Description = "An entity with a id and created/updated timestamps";


            this.Field(x => x.Id)
                .Description("The unique identifier of the entity.");
            this.Field(x => x.Created)
                .Description("Timestamp when the entity was first created.");
            this.Field(x => x.Updated)
                .Description("Timestamp when the entity was last updated.");

            this.Interface<BaseEntityInterface<T>>();
            this.IsTypeOf = obj => obj is IBaseEntity;
        }
    }

// Sample implementation type
public class InvoiceArticleObject: BaseEntityObject<InvoiceArticle>
    {
        public InvoiceArticleObject()
        {
            this.Description = "Invoice article.";

           // ...

            this.Interface<BaseEntityInterface<InvoiceArticle>>();
            this.IsTypeOf = obj => obj is InvoiceArticle;
        }
    }
   
```

**Comment by BenjaBobs** [comment]
With the current code the interface is being registered multiple times due to the generics. What you could do is interface with the base type instead:
`this.Interface<BaseEntityInterface<IBaseEntity>>()`

That way, the type being registered will be the same, so it will only be registered once, and that should solve your name collision problem while still allowing you to access the needed fields, provided that they are present on `IBaseEntity`.

**Comment by sungam3r** [comment]
All types in GraphQL **must have unique names**. Which ones? You choose yourself. I see that you do not specify them, so the names are inferred by default from the type are used. You can set type name with just `Name = "blablabla";` to avoid any conflicts. For a better understanding of what schemа you have (names), you can open it with GraphQL Playgroud, GraphiQL, Altair or any other UI tool.

**Comment by andrejohansson** [comment]
@BenjaBobs tips was the right for me, setting the BaseInterface solved my issue. Thank you both for your response!
