### ISSUE TITLE
Is there any package that autogenerates filters and mutations?

### ISSUE THREAD

**Issue by andrejohansson** [graphql-dotnet/graphql-dotnet#1631]
## Summary

I have been working with graphql in Rust for a while, and there is a nice package called [wundergraph](https://github.com/weiznich/wundergraph). When using that package I can define three models:

- My entity
- An input model for a new entity (which may have less/other fields and the complete entity)
- A changeset model which essentially is the entity with all optional fields (so that partial updates can be made)

That´s all i have to do, then  wundergraph will generate the following

- Filters for the entity
- Ordering parameters for the entity
- Querying for a single entity and a collection
- Mutation for create
- Mutation for update
- Mutation for delete

See images below, all that is generated from the models. 

Now my question is  if there is some similar package for graphql-net that can generate the filters, orderables and basic mutations?

I know [relay](https://github.com/graphql-dotnet/relay) exists that helps with paging etc. but I have not found anything for the other cases.

### Rust sample

```rust
#[derive(Clone, Debug, Identifiable, Queryable, Associations, WundergraphEntity)]
#[table_name = "persons"]
pub struct Person {
    pub id: i32,
    pub firstname: String,
    pub lastname: Option<String>,
    pub gender: GenderEnum,
    pub side: SideEnum,
    pub year_of_birth: Option<i32>,
    pub address_id: Option<i32>,
    #[column_name = "address_id"]
    pub address: HasOne<i32, Address>,
    pub parties: HasMany<PartyPerson, rel_persons_parties::person_id>,
    pub invitations: HasMany<Invitation, invitations::person_id>,
    pub user_id: Option<String>,
    pub profile_image_url: Option<String>,
}

// GraphQL Mutation Entities


#[derive(Insertable, GraphQLInputObject, Clone, Debug)]
#[table_name = "persons"]
pub struct NewPerson {
    pub firstname: String,
    pub lastname: Option<String>,
    pub gender: GenderEnum,
    pub side: SideEnum,
    pub year_of_birth: Option<i32>,
    pub address_id: Option<i32>,
    pub user_id: Option<String>,
    pub profile_image_url: Option<String>,
}

#[derive(AsChangeset, GraphQLInputObject, Identifiable, Debug)]
#[table_name = "persons"]
pub struct PersonChangeset {
    pub id: i32,
    pub firstname: Option<String>,
    pub lastname: Option<String>,
    pub gender: Option<GenderEnum>,
    pub side: Option<SideEnum>,
    pub year_of_birth: Option<i32>,
    pub address_id: Option<i32>,
    pub user_id: Option<String>,
    pub profile_image_url: Option<String>,
}
```

### Resulting filters and queries
![image](https://user-images.githubusercontent.com/2828428/78125185-f2cc5e80-7410-11ea-81d3-770236bb14e3.png)

![image](https://user-images.githubusercontent.com/2828428/78125235-0972b580-7411-11ea-8222-7d8a02e0202a.png)

![image](https://user-images.githubusercontent.com/2828428/78126393-c6b1dd00-7412-11ea-8dc7-e60ca3dd88a9.png)

![image](https://user-images.githubusercontent.com/2828428/78126430-d4fff900-7412-11ea-9759-214612d61e55.png)

![image](https://user-images.githubusercontent.com/2828428/78125301-1c858580-7411-11ea-9567-ff9136fc167d.png)

**Comment by sungam3r** [comment]
Are you generate schema from code?

**Comment by andrejohansson** [comment]
Yes, I create the types in [code first](https://graphql-dotnet.github.io/docs/getting-started/introduction#graphtype-first-approach).

**Comment by sungam3r** [comment]
Generally there are a number of graphql code generators. See #1424 , #576 and others. The main scenario that interests people is graphql **client** code generation from the graphql schema obtained from introspection/SDL. I understand that you have a different situation. You want to generate a GraphTypes **for server** from the DTO / Entities / Models. Do you? If so, then I do not know such generators.

**Comment by BenjaBobs** [comment]
Iirc most people around here that use such generators haven't open sourced them. In my company we use such a generator to generate pretty much the whole schema based on classes that derives from `Entity` or `Relation` and attributes on their properties.

**Comment by sungam3r** [comment]
>  haven't open sourced them

Yes, the same situation. But this is due only to the great work that needs to be done, and there is always not enough time.

**Comment by sungam3r** [comment]
I think this issue may be clised. Also see https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/guides/known-issues.md
