### ISSUE TITLE
Sort `errors` first in serialized result

### ISSUE THREAD

**Issue by benmccallum** [graphql-dotnet/graphql-dotnet#1637]
## Summary

Spec recommends errors (if present) should come first to help notice them. I just had a situation where I didn't notice errors were happening as they were showing after the data.
http://spec.graphql.org/June2018/#sec-Response-Format

### Motivation

Improve DX. 

### Implementation

Would need to take a look, but I image the `IDocumentWriter` impls would need to do this and we'd need to implement it for the Newtonsoft and S.T.Json impls.

**Comment by benmccallum** [comment]
Gonna quickly look at doing this now. Feel free to assign to me @sungam3r

**Comment by sungam3r** [comment]
Interesting observation. I didn’t notice.
