### ISSUE TITLE
decimal precission issue in graphql

### ISSUE THREAD

**Issue by PoorDesigner** [graphql-dotnet/graphql-dotnet#1639]
I am using GraphQL nuget package in one of my project. The version is 2.4.0.

When I am passing the decimal value as 12.10 the graphql is somehow transforming that into 12.1
If i send something like 12.11 then its coming as 12.11 but not when the last digit is zero. Is there something that i need to change in my code to get it working?

GraphQL decleration

`            Field(x => x.percentage, nullable: true).Name("percentage");`

Decleration

`public decimal? percentage{ get; set; }`

**Comment by sungam3r** [comment]
Please read warning section first https://github.com/graphql-dotnet/graphql-dotnet#installation

**Comment by sungam3r** [comment]
@PoorDesigner Did you manage to solve this issue?
