### ISSUE TITLE
Different resolution contexts

### ISSUE THREAD

**Issue by jquense** [graphql-dotnet/graphql-dotnet#164]
:wave: Thanks for the excellent library. 

I had a question about why there are two different "context" types depending on which `Field()` overload used. I've found myself tripping over the differences, especially when trying to wrap up some conventions and extensions around the context objects, not the least of which being that `ResolutionArgument`s isn't actually extensible. From where i'm looking it seems like these two concepts could be consolidated into ResolutionContext, with properties like `Object` being handled `Source` (maybe `Field<TSource, TFieldType>()` overload). 

Forgive me if my intuitions make no sense, I don't send a lot of time with C#

**Comment by joemcbride** [comment]
I think you're spot on.  This is the fluent api vs. the non-fluent api.  Once upon a time they had more differences (which caused other issues) and I agree they should come together.

**Comment by joemcbride** [comment]
Closed in #166
