### ISSUE TITLE
Resolving InputObject Field with Different Name

### ISSUE THREAD

**Issue by Teletraan1** [graphql-dotnet/graphql-dotnet#1644]
##Summary
Quick note: I did my best to search the issues list, and the docs. The "Aliases" section of the docs seems to indicate this is possible, but I may be missing something.

I am trying to provide a complex input object that contains a field with an aliased name from what the POCO property is named; however, it seems to only map correctly if the name is the same as the property.

## Relevant information

This is a stripped-down example of the setup I have:

```
public class Stereo()
{
  public Guid StereoKey { get; set; }
}

public class StereoInput : InputObjectType<Stereo>
{
  Field(f => f.StereoKey, type: typeof(GuidGraphType)).Name("key");
}

public class Items()
{
  public Stereo Stereo { get; set; }
}

public class ItemsInput : InputObjectType<Items>
{
  Field<StereoInput>("Stereo");
}
```

What I would expect is that I could provide the user with a field called "key" that would map to `StereoKey`; however, this doesn't seem to be the case. Is there additional info that I am missing when creating this relationship?

**Comment by sungam3r** [comment]
Try the latest preview from myget feed. This issue has been fixed.

**Comment by Teletraan1** [comment]
This did the trick. Thanks for the quick reply!
