### ISSUE TITLE
FederatedSchemaPrinter: directive is missing when printing extended type.

### ISSUE THREAD

**Issue by MartynasZilinskas** [graphql-dotnet/graphql-dotnet#1645]
## Description

When extending specific type that's in another service, it loses directive.

### Steps to reproduce

```schema
extend type User @key(fields: "id") {
  id: ID! @external
  isPhotographer: Boolean!
}
```

Repro repo: https://github.com/MartynasZilinskas/graphql-dotnet-repro-2020

### Expected result

It should leave directives as it is.

### Actual result
FederatedSchemaPrinter prints without directive, because the type is extended.
```
extend type User {
  id: ID! @external
  isPhotographer: Boolean!
}
```

### Environment

- GraphQL version: 3.0.0-preview-1633
- GraphQL.SystemTextJson: 3.0.0-preview-1633

**Comment by MartynasZilinskas** [comment]
I think the problem is in this line:
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/Federation/FederatedSchemaPrinter.cs#L45

Because `User` type has `__EXTENSION_AST_MetaField__` instead of `__AST_MetaField__`, so that line returns null.

**Comment by ShadyNawara** [comment]
How would you actually resolve the field in this extended type. I have the same use case but I cant seem to be able to figure it out.

**Comment by ShadyNawara** [comment]
> @MartynasZilinskas How would you actually resolve the field in this extended type. I have the same use case but I cant seem to be able to figure it out.

For anybody's future reference here is how you can extend a type created in a different service

startup.cs
```
services.AddScoped<Query>();
services.AddScoped<UserType>();
services.AddTransient<ISchema>(s =>
            {
    return FederatedSchema.For(@"
              type Query {
                photo(id: String!): Photo
            }

            extend type User @key(fields: ""id"") {
              id: ID! @external
              isPhotographer: Boolean!
            }

            type Photo @key(fields: ""id"") {
               id: ID!
              url: String!
            }
                ", _ =>
                {
                    _.ServiceProvider = s;
                    _.Types.Include<Query>();
                    _.Types.Include<UserType>();
                });
            });
```

User.cs
```
    public class User
    {
        public string id { get; set; }
        public bool isPhotographer { get; set; }
    }
    [GraphQLMetadata("User", IsTypeOf = typeof(User))]
    public class UserType
    {
        public string id(User user) => user.id;
        public bool  isPhotographer(ResolveFieldContext context, User user)
        {
            return true // or false
        }
    }
```
