### ISSUE TITLE
GraphQL Unit Testing of MUTATION

### ISSUE THREAD

**Issue by mikehkk** [graphql-dotnet/graphql-dotnet#1646]
Hello,

Have been writing a lot of QUERY ut's successfully around this sample pattern:

      [Fact]  
      public async Task hero()  
      {  
          await run(_ =>  
          {  
              var input = new GraphQLRequest  
              {  
                  Query = @"{ hero { name} }"  
              };  
              _.Post.Json(input).ToUrl("/api/graphql");  
              _.StatusCodeShouldBe(HttpStatusCode.OK);  
              _.GraphQL().ShouldBeSuccess(@"{ ""hero"": { ""name"": ""R2-D2"" }}");  
          });  
      }  

(this is a sample for https://github.com/graphql-dotnet/graphql-dotnet/issues/800)

My question is how to format a MUTATION query string that would be part of GraphQLRequest?  I need to subject the mutation{} element AND the VARIABLE element of the query.  How to do you format that correctly for submission as part of the GraphQLRequest?  The specific syntax.

Really appreciate the help!

Thanks.

**Comment by sungam3r** [comment]
Just append `mutation`: 
```c#
Query = "mutation { dosomething { field1 field2 } }" 
```

**Comment by mikehkk** [comment]
Thanks, but the above doesn't include a VARIABLE definition.  Give you and idea, here's a representation of what I'm trying to pass (it's the MUTATION instruction and the companion VARIABLE that informs it:

mutation($newItem: ItemType!) {
  createItem(item: $newItem) {
    name
    model
    number
  }
}

{
  "newItem": {
    "name": "itemName",
    "model": "itemModel",
    "number": 500001
  }
}

What is the correct syntax for passing both?

**Comment by sungam3r** [comment]
See for example this test https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/StarWars/StarWarsBasicQueryTests.cs#L321

**Comment by sungam3r** [comment]
@mikehkk Do you need more help?

**Comment by sungam3r** [comment]
Feel free to reopen if you need more help.
