### ISSUE TITLE
maxRecursionCount in ComplexityAnalyzer is not configurable

### ISSUE THREAD

**Issue by cronin101** [graphql-dotnet/graphql-dotnet#1648]
We're seeing some complex queries failing with `Query is too complex to validate`, triggered in this validation path:
```C#
        private void AssertRecursion(AnalysisContext context)
        {
            if (context.LoopCounter++ > _maxRecursionCount)
            {
                throw new InvalidOperationException("Query is too complex to validate.");
            }
        }
```

In `ComplexityAnalyzer`'s constructor, this is set to 250 and says "adjust as needed":

```C#
        /// <summary>
        /// Creates a new instance of ComplexityAnalyzer
        /// </summary>
        /// <param name="maxRecursionCount">
        /// Max. number of times to traverse tree nodes. GraphiQL queries take ~95 iterations, adjust as needed.
        /// </param>
        public ComplexityAnalyzer(int maxRecursionCount = 250)
        {
            _maxRecursionCount = maxRecursionCount;
        }
```

However, [only the default constructor for `DocumentExecuter` is called](https://github.com/graphql-dotnet/graphql-dotnet/search?p=1&q=%22new+DocumentExecuter%22&unscoped_q=%22new+DocumentExecuter%22), so the `ComplexityAnalyzer` constructor is never called with any arguments and therefore this is not user-configurable (through, e.g. `ComplexityConfiguration`):
```C#
        public DocumentExecuter()
            : this(new GraphQLDocumentBuilder(), new DocumentValidator(), new ComplexityAnalyzer())
        {
        }
```

It seems unlikely that nobody else in the world is hitting this arbitrary parsing limit. (We are using lots of fragments in our query, but nothing pathological).

I suggest that there is some codepath introduced to allow this recursion limit to be adjusted through `ComplexityConfiguration`.

**Comment by cronin101** [comment]
On further debugging, it seems this is only an issue when a `ComplexityConfiguration` has been provided. So a workaround for anyone else suffering this (Hello search engine results! 👋) is to remove any custom `ComplexityConfiguration` setting and leave this null, then the query will not be validated at all.

It still makes sense to allow this value to be tuned though, for use-cases requiring validation.

**Comment by sungam3r** [comment]
> However, only the default constructor for DocumentExecuter is called

Well, you can always call parametrized ctor. Moreover, `DocumentExecuter` is "DI ready" for injecting custom analyzers. See [this](https://github.com/graphql-dotnet/server/blob/develop/src/Core/ServiceCollectionExtensions.cs#L30) - you can configure your DI container with custom `IDocumentBuilder`, `IDocumentValidator` and `IComplexityAnalyzer`. In your case first and second will be just default ones.

However, I would like to track this issue further to provide an easier way to configure `maxRecursionCount`.

**Comment by sungam3r** [comment]
@cronin101 You can try the latest preview.
