### ISSUE TITLE
How to access UserContext in Query with Schema First approach

### ISSUE THREAD

**Issue by aaron-c2** [graphql-dotnet/graphql-dotnet#1649]
Hi, sorry if this is a simple question but I haven't been able to find an answer in the examples. I've used this library before and had a Controller with a snippet similar to the below to pass the User Context. 
```
var result = await _documentExecuter.ExecuteAsync(_ => {
            _.Schema = _schema;
            _.Query = query.Query;
            _.OperationName = query.OperationName;
            _.Inputs = inputs;
            _.UserContext = HttpContext.User;
        });
```
Then the user context is visible on the field resolver. 
I've recently picked up an API which is using the Schema first approach, so no controllers at all and I don't understand how to access the UserContext in my query - the rest of the context comes through but the UserContext on the resolve field context is always empty. 
```
public async Task<MyResult> MyQuery(ResolveFieldContext context) {                                    
  var userContext = context.UserContext //always count =0                                             
}
```
I have added the following to the Startup.cs as the docs suggest but don't see how this works?
```
services.AddGraphQL.AddUserContextBuilder(httpContext => new GraphQlUserContext { User = httpContext.User });
```

**Comment by DiogoVCS** [comment]
I dont think you need that last line in the Startup.cs....

Try to create a context class as follows:

```java
    public class GraphQlUserContextDictionary : Dictionary<string, object>
    {
        public ClaimsPrincipal User { get; set; }

        public GraphQlUserContextDictionary(ClaimsPrincipal User)
        {
            this.User = User;
        }
    }
```
and then in the controller create a new context: GraphQlUserContextDictionary

```java
var graphQlUserContext = new GraphQlUserContextDictionary(User);
```
and then pass it to the _.UserContext in the ExecutionResult.
For accessing it from the Query do the following: 

```java
Field<SomeType>(
      "something",
      resolve: context =>
      {
          var userName = (context.UserContext as GraphQlUserContextDictionary).User.Identity.Name;
          return repository.getAll()
      }
  );
```

**Comment by sungam3r** [comment]
@aaron-c2 Did you manage to solve this issue?

**Comment by aaron-c2** [comment]
Hi sungam3r. Yes, I've solved the problem now, apologies for leaving this hanging.

**Comment by itabaiyu** [comment]
I'm actually running into this same issue and can't quite resolve it. @DiogoVCS what you described uses the GraphType first approach and doesn't solve the problem that was initially posted. Here is some mock code to describe what I'm facing:

Schema:
```
public ISchema GetSchema()
{
    return Schema.For(@"
        type Book {
            id: ID
            name: String,
            genre: String
        }

        type Query {
            book: Book
        }",
        _ =>
        {
            _.Types.Include<Query>();
        }
    );
}
```

Query.cs:
```
[GraphQLMetadata("Query")]
public class Query
{
    [GraphQLMetadata("book")]
    public async Task<Book> GetBook(ResolveFieldContext context, int bookId)
    {
        var userContext = context.UserContext; // <- this is currently always null

        // do work with userContext and bookId to get a book
    }
}
```

Controller code:
```
var result = await _documentExecuter.ExecuteAsync(_ => {
            _.Schema = _schema;
            _.Query = query.Query;
            _.OperationName = query.OperationName;
            _.Inputs = inputs;
            _.UserContext = HttpContext.User;
        });
```

With the above code, `ResolveFieldContext` is always null. Am I missing anything here?

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Reflection/ReflectionHelper.cs#L85

Change `ResolveFieldContext` to `IResolveFieldContext`. Some time ago we introduced this interface and split context to different implementation types.

**Comment by sungam3r** [comment]
I mean that actual resolve context type **is not** `ResolveFieldContext`. It is likely `ReadonlyResolveFieldContext` so changing argument type to `ReadonlyResolveFieldContext` should work too.

**Comment by itabaiyu** [comment]
Thanks @sungam3r  that worked. It would be great if someone could update the docs with an example of getting context into resolver methods for the schema-first approach. I looked through them and wasn't able to find anything. Apologies if it's already there and I missed it somehow.

**Comment by sungam3r** [comment]
@Shane32 Would you like to update docs with that info?

**Comment by Shane32** [comment]
Well, I've never used the schema-first approach.  I'd feel better if you updated the existing docs, and I'll see what you changed and include applicable notes in the upgrade docs.

**Comment by Shane32** [comment]
Or if you want to give me a little direction as to where you feel the additional documentation should be added, I can take a stab at it.

**Comment by itabaiyu** [comment]
@Shane32 I can make a PR to update the docs tonight, if I have permission to do so.

There should be a schema-first example side by side with the other user context info [here](https://graphql-dotnet.github.io/docs/getting-started/user-context/).

**Comment by sungam3r** [comment]
> Change ResolveFieldContext to IResolveFieldContext. Some time ago we introduced this interface and split context to different implementation types.

@Shane32  I mean document that there are more than one form of resolve context. You may place it here https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/introduction.md#schema-first-approach.
