### ISSUE TITLE
Support netstandard in the GraphQL.SystemTextJson package

### ISSUE THREAD

**Issue by wirmar** [graphql-dotnet/graphql-dotnet#1661]
## Summary

Currently, the `GraphQL.SystemTextJson` package can only be used in dotnetcore3.0/3.1. However the `System.Text.Json` nuget package (https://www.nuget.org/packages/System.Text.Json/) supports netstandard as well. Would it be possible to allow netstandard (and framework) as target frameworks of the `GraphQL.SystemTextJson` package?

**Comment by sungam3r** [comment]
@benmccallum It is strange that we did not notice this before.

**Comment by benmccallum** [comment]
Oh wow. I didn't know that package even existed... Nice one. And thanks for the suggestion @wirmar !

**Comment by sungam3r** [comment]
I moved to netstandard2.1 from netcoreapp3.0.

**Comment by sungam3r** [comment]
Oops, reverted.
