### ISSUE TITLE
Is there a way to resolve a GraphQl type by referencing another type?

### ISSUE THREAD

**Issue by DiogoVCS** [graphql-dotnet/graphql-dotnet#1662]
Im using the Graphql .Net library to build a GraphQl API. The following is a domain example of what we currently have, where, the area has a list of sampling point identifiers:

```java
public class AreaRoot {
   public String Id { get; set; }
   public List<String > SamplingPointIds { get; set; }
}

public class SamplingPointRoot {
   public String Id { get; set; }
   public String Description { get; set; }
}
```

And the types are defined as follow:

```java
public class AreaType : ObjectGraphType<AreaRoot>
{
    public AreaType()
    {
        Name = "Area";
        Field(x => x.Id, type: typeof(IdGraphType));
        Field(x => x.SamplingPointIds, type: typeof(ListGraphType<StringGraphType>));
    }
}

public class SamplingPointType : ObjectGraphType<SamplingPointRoot>
{
    public SamplingPointType()
    {
        Name = "SamplingPoint";
        Field(x => x.Id, type: typeof(IdGraphType));
        Field(x => x.description, type: typeof(StringGraphType));
    }
}
```

Is there any way to retrieving everything from the sampling point without changing the domain classes? there is an example in the conference [GraphQL vs Traditional Rest API](https://www.youtube.com/watch?v=hWJ77LMRX_w) in the 25:41 min, but this example is in java, and we could not make the same using the graphQl .net.

The next example illustrates the type of query we want to make:

```java
query GetAreas(){
    areas(){
        Id
        samplingPoints{
           Id
           description
        }
    }
}
```
So the question is: Is there a way to this as in the video above, as we pass the samplingPoints, and resolve it, retrieving the samplingPoints for that area (in some query)?

**Comment by sungam3r** [comment]
Thanks for the example, but from it I don’t understand what you want. I see two independent classes.

**Comment by DiogoVCS** [comment]
From the example in the video, which is in java, he can make a resolver for the class domain Post which has the authorId that made the post:

```java
public class Post {
     private final string id;
     private final authorId;
     private final title;
     private final body;
}
```
```java
public class PostResolver implements GraphQlResolver<Post>{
     private final authorRepository AuthorRepository;

     public Author createdBy(Post post){
          return authorRepository.findById(post.getAuthorId()).orElseThrow(() => new NotFoundException)
     }
}
```
And he defines the type Post as: 

```java
type Post {
     id: ID!
     title: String!
     body: String
     createdBy: Author!
}
```
and without changing the query and nothing on the domain (if there's a solution for this by altering the query, its fine, but the domain classes, must not be changed), i wonder if there's something similar that can be done with GraphQl .net....

an area has a list of samplingPointsIds, and instead of "createdBy: Author!" it would be something like "areaSamplingPoints: [SamplingPoint]", this is the comparison i wanted to make, and ask if is doable in GraphQl .net.

**Comment by sungam3r** [comment]
Yes. You can always use any `Field()` overload on your GraphType, even if it is `ObjectGraphType<T>`. For example see [this](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Introspection/__EnumValue.cs#L18).

**Comment by DiogoVCS** [comment]
That was a really good example, @sungam3r , thank you that was exactly what i needed.
