### ISSUE TITLE
New NuGet Release

### ISSUE THREAD

**Issue by jhoward321** [graphql-dotnet/graphql-dotnet#1664]
## Summary
Are there any plans soon to publish a new NuGet preview release? I am trying to use [this ](https://github.com/SimonCropp/GraphQL.Validation)library which requires a version that is only available via the MyGet feed. Unfortunately due to my build pipeline, it will not be an easy change to switch to using the MyGet feed. A new version (>= preview-1630) would make my life much easier and would be very much appreciated.

## Relevant information

The NuGet feed has not been updated in months.

**Comment by sungam3r** [comment]
@joemcbride Could you please publish the latest preview or core package and both serializers?
![изображение](https://user-images.githubusercontent.com/21261007/81017740-cec6c780-8e6b-11ea-8960-d83c38b2486e.png)
Probably it's time.

**Comment by joemcbride** [comment]
This is done, should show up on Nuget.org after they fully upload + index.
