### ISSUE TITLE
publish GraphQL-Parser 5.1.2

### ISSUE THREAD

**Issue by wirmar** [graphql-dotnet/graphql-dotnet#1667]
## Description

The latest `GraphQL` version 3.0.0-preview-1648 (https://www.nuget.org/packages/GraphQL/3.0.0-preview-1648) depends on `GraphQL-Parser` >=5.1.2. However, the latest version of `GraphQL-Parser` is only 5.1.0.

### Actual result

`GraphQL` version 3.0.0-preview-1648 cannot be installed.

Relates to #1664

**Comment by sungam3r** [comment]
Really. Either this version has never been published on nuget, or was unlisted.

@joemcbride Could you please publish? If you do not mind, then I myself could solve such issues if you give me the appropriate rights to publish.

**Comment by joemcbride** [comment]
Published that package.

**Comment by joemcbride** [comment]
@sungam3r I added you (through email) to MyGet.  Let me know if that access works.

**Comment by sungam3r** [comment]
Thanks. I received an email and logged into my account. There i see graphql-dotnet packages.
