### ISSUE TITLE
Inheritance of graph types

### ISSUE THREAD

**Issue by kenewbie** [graphql-dotnet/graphql-dotnet#1668]
I have a question about inheritance of graph types that I have been unable to solve. Imagine the following scenario:
```csharp
public class Foo
{ 
    public int FooProp { get; set; }
}

public class Bar : Foo
{ 
    public int BarProp { get; set; }
}

public class FooGraphType : ObjectGraphType<Foo>
{
    public FooGraphType()
    {
        Field(p => p.FooProp);
     }
}

public class BarGraphType : ObjectGraphType<Bar>
{
    public BarGraphType()
    {
        Field(p => p.FooProp);
        Field(p => p.BarProp);
     }
}
```

My issue is that I have to redeclare the FooProp field in BarGraphType, which is just a minor annoyance in this example but when Foo has a lot of fields with resolver code etc it gets very attractive to have them in Foo only and not duplicate them in Bar.

So my question is, is there some way for BarGraphType to inherit from FooGraphType, get all the fields defined there, and still be able to use it's own model for additional fields?

I've been looking through the docs and examples but unable to find anything, so I thought I would ask here.

**Comment by sungam3r** [comment]
If you want to inherit from two different generic types the answer is NO. This is a limitation of the .NET type system, not GraphQL.NET. But you can always move field declarations inside some method and use this method in your type hierarchy. Also you can inherit from `AutoRegisteringObjectGraphType`.

**Comment by kenewbie** [comment]
Yes I am aware of the limitations on multiple inheritance. I was hoping that there might be some variation of `ObjectGraphType<T>` that looks at the base of T, and if a GraphType is found that uses the base as a model then the fields from that are applied to the GraphType of T as well. 

I'll take a look at the AutoRegistering version and see if that helps me.

**Comment by sungam3r** [comment]
Given `TDerived : TBase`

`ObjectGraphType<TDerived>` and `ObjectGraphType<TBase>` are not connected in any way. Generic parameter is only needed to provide expression configuration capabilities and typed resolvers.

**Comment by KreativJos** [comment]
Wouldn't your problem be solved if you'd make a generic base class, like this (note: written in free-hand, not tested):
`
public class Foo
{ 
    public int FooProp { get; set; }
}

public class Bar : Foo
{ 
    public int BarProp { get; set; }
}

public abstract class BaseFooGraphType : ObjectGraphType<T>
    where T : Foo
{
    protected BaseFooGraphType()
    {
        Field(p => p.FooProp);
    }
}

public class FooGraphType : BaseFooGraphType<Foo>
{
    public FooGraphType()
        : base()
    { }    
}

public class BarGraphType : BaseFooGraphType<Bar>
{
    public BarGraphType()
        : base()
    {
        Field(p => p.BarProp);
    }
}
`

**Comment by kenewbie** [comment]
Nice, I did not think of that. 
Thanks for the feedback, I'll try that approach.

**Comment by sungam3r** [comment]
Closed as answered.

**Comment by aguirmrc** [comment]
Tanks! Very helpfull, its works to me!!!!
