### ISSUE TITLE
Batching Queries

### ISSUE THREAD

**Issue by alfechner** [graphql-dotnet/graphql-dotnet#1670]
Our frontend is React based and uses Apollo Client.

For performance reasons we wanted to leverage a feature called [batch processing](https://www.apollographql.com/docs/react/v3.0-beta/api/link/apollo-link-batch-http/). It basically batches together queries and sends them in one request to the server.

However, our graphql-dotnet based server seems not to be able to deserialize the JSON from the request. I was wondering (1) if query batching is supported at all, (2) if I might need to setup the server in a certain way or (3) if the format of the JSON needs to be different.

The default format send from the Apollo Client is an array of so called operations. Every operation holds it's query. It looks something like this:

```js
[
  {
    "operationName": "my-operation",
    "query": "query ..."
  }
  ...
]


```

**Comment by alfechner** [comment]
This feature seems to be available in the non-stable branch.

**Comment by sungam3r** [comment]
Right.
