### ISSUE TITLE
Nested input graphtypes

### ISSUE THREAD

**Issue by Oliver2301** [graphql-dotnet/graphql-dotnet#1671]
Hello,
Is there any documentation about create a mutation based a nested input graph types ?
{
     data {
        name,
        child {
        }
     }
}

**Comment by sungam3r** [comment]
Nesting for inputs no different from nesting for outputs. I see more information in your initial post which I received on my email:
```c#
public class EventDateTimeType : ObjectGraphType<EventDateTime>
{
    public EventDateTimeType()
    {
        this.Name = "EventDateTime";

        this.Field(e => e.StartingDateTime).Description("The start of the Event");
        this.Field(e => e.EndingDateTime).Description("The end of the Event");
    }
```

`EventDateTimeType` **must** be input graph type too. Also I think that you use version 2.4.0. In one of the latest previews we added some checks to warn user about input/output inconsistency in nested types. Please read README.md and try the latest preview.

**Comment by sungam3r** [comment]
Closed due to the lack of feedback.
