### ISSUE TITLE
how to see loaded schemas

### ISSUE THREAD

**Issue by markus27183** [graphql-dotnet/graphql-dotnet#1673]
I just started working on a project that uses GraphQL, and I'm getting the error that a InsertSpecification class is not marked as InputType, but it is.  I'd like a way to query graphQL to get all the loaded schemas and their types.

**Comment by sungam3r** [comment]
Do you mean introspection? You can use GraphQL Playground, GraphiQL, Altair or any other UI tool. See here - https://github.com/graphql-dotnet/server
![изображение](https://user-images.githubusercontent.com/21261007/81573858-bac02000-93ad-11ea-8ef9-fed4f72aeb75.png)

**Comment by markus27183** [comment]
I'll try this, which one is best?

**Comment by sungam3r** [comment]
All of them work well. You can install all and compare, it is just one line of code for each.

**Comment by sungam3r** [comment]
Closed as answered.
