### ISSUE TITLE
2.4 to Preview 1648 - AddField() Error

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/graphql-dotnet#1676]
System.ArgumentOutOfRangeException: 'Output type 'Query' can have fields only of output types: ScalarGraphType, ObjectGraphType, InterfaceGraphType, UnionGraphType or EnumerationGraphType. (Parameter 'fieldType')'

Previously this was working:
```
var listType = new ListGraphType(tableType);
AddField(new FieldType
 {
   Name = $"{friendlyTableName}_list", 
   Type = listType.GetType(), //CLR Type of Graph Type
   ResolvedType = listType, //Graph Type
   Resolver = dyQueryFieldResolver
 });
```

What should I be doing differently?

**Comment by sungam3r** [comment]
Everything is correct, additional checks were added in 3.0.0 to match the GraphQL specifications and  avoid unpredictable behavior in runtime.

**Comment by sungam3r** [comment]
See #1678

**Comment by sungam3r** [comment]
> What should I be doing differently?

Because previous behavior was wrong.

**Comment by OpenSpacesAndPlaces** [comment]
I'm not sure if/when I'll get a chance to circle back to testing the preview version.
Closing this thread so it doesn't become a zombie.
