### ISSUE TITLE
Branch with 2.4 source code

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/graphql-dotnet#1677]
Is it possible to post a branch with the GraphQL 2.4 source as well as a compatible copy of GraphQL.Authorization? I tried pulling master, but it's the preview version.

I'm trying to track down a bug inside the resolver  (returning [{}], but AsyncFieldResolver has data returning in the delegate).

Similar to this one from awhile ago where resolver errors need source code to trace down underlying problems:
https://github.com/graphql-dotnet/graphql-dotnet/issues/1014

**Comment by sungam3r** [comment]
I don’t think that someone will have the desire and time to do this and support two branches. You can fix the error in the preview version. Yes, migration is required.

**Comment by OpenSpacesAndPlaces** [comment]
Maybe I'm misunderstanding something, but wouldn't there be a copy of whatever the final source was used to create the 2.4 nuget package?

**Comment by joemcbride** [comment]
@OpenSpacesAndPlaces Here's the 2.4 tagged release.

https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v2.4.0

**Comment by sungam3r** [comment]
@OpenSpacesAndPlaces I meant that hardly anyone will be engaged in constant support of old versions. But you can fetch commit tagged as 2.4.0, fix something and build your private version.

**Comment by OpenSpacesAndPlaces** [comment]
That's what I was looking for - thanks much!
