### ISSUE TITLE
Convert input object graph type directly from json string

### ISSUE THREAD

**Issue by groege** [graphql-dotnet/graphql-dotnet#1682]
Is there a way to directly convert a json string using a InputObjectGraphType

Lets say I have an InputObjectGraph type:

DummyType : InputObjectGraphType<Dummy> 
{
... omitted for simplicity
}

I want to do something like this:

string raw = '..some json data..';
Dummy dummy = XXX.Deserialize<Dummy, DummyType>(raw);

Or what is the fastest way to do something like this?

Cheers and thanks for the good work!

**Comment by sungam3r** [comment]
What is `Dummy` and how does it correlate with `DummyType` ?

**Comment by sungam3r** [comment]
Closed due to the lack of feedback.

**Comment by contactsamie** [comment]
@scmccart   I think whats asked here is like need to set  _.Root  when all i have is a json string. I dont have a type but i have the 'correct' json 

for example , below new { Hello="Hello world"}; works fine, but not sure  if there is any option where 
I'm guessing if there is a way to directly convert a json string to InputObjectGraphType that  will help. The intent is just to be able to set Root when all i have is json string

```
 var schema = Schema.For(@"
                  type Query {
                        hello: String
                      }
                ");
            var writer = new GraphQL.SystemTextJson.DocumentWriter(options =>
            {
                options.PropertyNamingPolicy = null;
            });
            var result = schema.ExecuteAsync(writer, _ =>
            {
                _.Query = @" { hello }";
                _.Root =  "{Hello : \"Hello World!\"}";//<==  in my use case I don't have a type, and can't create anonymous type, this string comes from the client. new { Hello="Hello world"}; works fine
            }).Result;
            // {"errors":[{"message":"Error trying to resolve field \u0027hello\u0027.","locations":[{"line":1,"column":4}],"path":["hello"],"extensions":{"code":"INVALID_OPERATION","codes":["INVALID_OPERATION"]}}],"data":{"hello":null}}
```
    @groege  any insight  @Shane32  Thank you

**Comment by contactsamie** [comment]
Seem like something similar is going on here [](https://github.com/graphql-dotnet/graphql-dotnet/pull/2522)

**Comment by Shane32** [comment]
The Newtonsoft and SystemTextJson GraphQL nuget packages contain extension methods to convert json text to Inputs objects, which double as dictionaries. They can’t convert to a dynamic or anonymous object type. Of course if you knew the type then you could use the deserializers directly. So not sure how to answer this one. Personally I use code first, and in that case it would be simple enough to write fields that pull from a source of a dictionary type. (I’ve done that in the past, although not with inputs from a json string like is proposed above.

**Comment by contactsamie** [comment]
@Shane32  thank you. My use case is such that client decide the 'type' and data, so everything is pretty much dynamic.
I tried this and it worked , but like you said , its not to anonymous and the query is clunky but this is the closest equivalent.


```
 var schema = Schema.For(@"
                type D{
                     key:String,
                     value:[D]
                }
                  type Query {
                        hello: [D]
                      }
                ");
            var d = GraphQL.NewtonsoftJson.StringExtensions.ToInputs("{Hello : \"Hello World!\"}");
            ;
            var writer = new GraphQL.SystemTextJson.DocumentWriter(options =>
            {
                options.PropertyNamingPolicy = null;
            });
            var result = schema.ExecuteAsync(writer, _ =>
            {
                _.Query = @" { hello { key } }";
                _.Root = new { Hello = d};
            }).Result;
```

**Comment by Shane32** [comment]
If you are simply trying to return arbitrary json data back to the client, I suggest reviewing this: https://github.com/graphql-dotnet/graphql-dotnet/issues/474

**Comment by contactsamie** [comment]
@Shane32  will look more into that, for now to get things working I just found a way to convert json to proper anonymous object dynamically that worked with _.Root . not performant atm but once i figure out  #474 it should be much faster
