### ISSUE TITLE
Authorized query fields fail before query directives are evaluated

### ISSUE THREAD

**Issue by bugged84** [graphql-dotnet/graphql-dotnet#1683]
The documented implementation for authorization in GraphQL .NET uses an `IValidationRule`. These rules are, of course, invoked before the execution strategy is invoked and, therefore, before the query directives are evaluated.

A client-side developer attempted to use the `@skip` directive to avoid fields which are not relevant to the current user. However, GraphQL .NET fails the query anyway since the authorization policy fails before the query executor even notices the `@skip` directive.

I understand the technical reasons for why this scenario fails, but the issue appears to be a design oversight. Am I missing something obvious with either the authorization feature or the directives feature provided by GraphQL .NET?

**Comment by KreativJos** [comment]
It seems to me the validation rule should check for directives, if they should be skipped?

**Comment by sungam3r** [comment]
It seems so. `ValidationContext.GetRecursiveVariables` may help.

**Comment by sungam3r** [comment]
@Shane32 This is 100% work for the new variables validation feature.

**Comment by sungam3r** [comment]
Waiting for v4 release. This issue relates to other repos - server and authorization. But let's keep it here.

**Comment by Shane32** [comment]
The new authorization rule within GraphQL.NET Server 7 respects `@skip` and `@include`.

Note that for GraphQL.NET 8, we hope to make it much easier for validation rules to inspect directives and other values passed into the query.  This will reduce the complexity of third-party code to respect `@skip` and `@include`.

@sungam3r Please re-open if you think there is anything else to do here.
