### ISSUE TITLE
performance issue in creation of json Graphql

### ISSUE THREAD

**Issue by nivedhauswin** [graphql-dotnet/graphql-dotnet#1686]
I have created an author class and Graphtype. I have a list of authors on the server-side. If the client requests, I need to send all the authors. for now, I have created a dummy list of authors. I have added the code below.

**Question 1:**
I have some performance issues in JSON creation. JSON creation takes more time than creating dummy data. Is this possible? How to avoid such performance issues.

**Question 2:** How to create a Unit test for GraphQl Object or queries in server-side

**Author.cs**
```
 public class Author
 {
      public int Id { get; set; }
      public string Name { get; set; }
      public int Age { get; set; }        
 }
```
**AuthorType.cs**
```
class AuthorType : ObjectGraphType<Author>
{
    public AuthorType()
    {
        Field(x => x.Id);
        Field(x => x.Name);
        Field(x => x.Age);
    }
}
```

**RootQueryType.cs**
```
class RootQueryType : ObjectGraphType
{
    public RootQueryType(List<Author> authors)
    {
        Field<ListGraphType<AuthorType>>(
            "authors",
             resolve: context => authors
        );
    }
}
```
**program.cs**
```
class Program
    {
        static public List<Author> GetData()
        {
            List<Author> a = new List<Author>();
            for(int i = 0; i < 1000000; i++)
            {
                a.Add(new Author() { Id = i, Name = "hi", age = 21 });
            }
            return a;
        }

        static void Main(string[] args)
        {
            var watch = System.Diagnostics.Stopwatch.StartNew();
            var schema = new Schema { Query = new RootQueryType(GetData()) };
            watch.Stop();
            Console.WriteLine("Data creation Time : "+ watch.ElapsedMilliseconds);

            watch = System.Diagnostics.Stopwatch.StartNew();
            var json = schema.Execute(_ =>
            {
                _.Query = "{authors { id name age } }";
                 
            });
            watch.Stop();
            Console.WriteLine("Json creation Time : "+watch.ElapsedMilliseconds);            
            Console.ReadKey();
        }
    }
```
**Output:**

       Data creation Time : 402

       Json creation Time : 29226

**Comment by sungam3r** [comment]
>  JSON creation takes more time than creating dummy data. Is this possible? 

Your test measures not just the time it took to create the json data (serialization), it measures the total query execution time. Without a doubt it is several times longer than the creation of author objects in memory.

>  How to avoid such performance issues.

In one of the latest 3.0.0-preview-XXXX versions we have added support for custom jsom serializers. Please, read README.md for details. System.Text.Json works better in most cases. See [benchmarks](https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.Benchmarks).

**Comment by nivedhauswin** [comment]
@sungam3r So should I use ScalarGraphType?

**Comment by sungam3r** [comment]
I do not understand your question.

**Comment by nivedhauswin** [comment]
```
class AuthorType : ScalarGraphType
    {
        public override object ParseLiteral(IValue value)
        {
            throw new System.NotImplementedException();
        }

        public override object ParseValue(object value)
        {
            throw new System.NotImplementedException();
        }

        public override object Serialize(object value)
        {
            Author author = value as Author;  
            Utf8Json.JsonSerializer.SetDefaultResolver(
                                        Utf8Json.Resolvers.StandardResolver.AllowPrivateExcludeNullSnakeCase);
            return Utf8Json.JsonSerializer.ToJsonString(author);
        }
    }
```
I tried this. There is improvement in performance. In this how can I make Subselections?. like

```
public AuthorType()
{
      Field<IntGraphType>("id",
                resolve: context =>
                {
                    return context.Source.Id;
                }
       );
      Field<IntGraphType>("age",
                resolve: context =>
                {
                    return context.Source.Age;
                }
       );

}
```

**Comment by nivedhauswin** [comment]
```
class AuthorType : ScalarGraphType
    {
        public override object ParseLiteral(IValue value)
        {
            throw new System.NotImplementedException();
        }

        public override object ParseValue(object value)
        {
            throw new System.NotImplementedException();
        }

        public override object Serialize(object value)
        {
            
            Author author = value as Author;
            Utf8Json.JsonSerializer.SetDefaultResolver(Utf8Json.Resolvers.StandardResolver.AllowPrivateExcludeNullSnakeCase);
            return Utf8Json.JsonSerializer.ToJsonString(author);
        }
    }
```
I tried this. There is an improvement in performance. is this what you meant?

**Comment by nivedhauswin** [comment]
@sungam3r actually I am new to this. I have just started learning graphQl. my question might be silly.

**Comment by sungam3r** [comment]
> is this what you meant?

No. I mean you can use S.T.J. for the whole server serialization/deserialization activity, not inside custom scalars. See [this](https://github.com/graphql-dotnet/server/blob/develop/samples/Samples.Server/Startup.cs#L56) example.

**Comment by nivedhauswin** [comment]
sorry. But I am just a beginner. I have started practicing Grapgql in a normal console application only. I have to not created API till now. could you please tell who to do in console application.

**Comment by sungam3r** [comment]
Use [this class](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.SystemTextJson/DocumentWriter.cs) to obtain json response from `ExecutionResult`.

**Comment by nivedhauswin** [comment]
```.AddSystemTextJson(deserializerSettings => { }, serializerSettings => { })```
Error : 'IGraphQlBuilder' does not contain a definition 'AddSystemTextJson' ad no accessible extension method 'AddSystemTextJson' accepting a first argument of type 'IGraphQlBuilder' could be found.
And use ```GraphQL.SystemTextJson```
To avoid this the only way I should install .net core 3 right? for both the case?

**Comment by nivedhauswin** [comment]
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<GraphQLapi.Data.DataBase>();
            services.AddScoped<GraphQLapi.GraphQlSchema.GraphSchema>();
            services.AddGraphQL()
                .AddDataLoader()
               .AddSystemTextJson(deserializerSettings => { }, serializerSettings => { })
                 .AddGraphTypes(ServiceLifetime.Scoped);
        }
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseGraphQL<GraphQLapi.GraphQlSchema.GraphSchema>("/graphql");
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions());
        }
```

```
public class GraphSchema : Schema
    {
        private DataBase _dataBase;
        public GraphSchema(IDependencyResolver resolver) : base(resolver)
        {
            _dataBase = new DataBase();
            Query = resolver.Resolve<RootQueryType>();
        }
    }
```

> .AddSystemTextJson(deserializerSettings => { }, serializerSettings => { })

It shows error. which is I should use .net core 3. right? where should I add SystemTextJson.SchemaExtensions in the code? That will return the System.Text.Json serialization right?

**Comment by nivedhauswin** [comment]
```
static void Main(string[] args)
        {           
            var schema = new Schema { Query = new GraphRoot() };
            var result = new DocumentExecuter().ExecuteAsync(doc =>
            {
                doc.Schema = schema;
                doc.Query = @"
                            query {
                                author{id name}
                            }
                        ";
            });
            var json = new GraphQL.SystemTextJson.DocumentWriter(indent: true).WriteAsync(result);
            Console.WriteLine(result);
            Console.ReadKey();
        }
```
Is this correct? 

> WriteAsync(result);

Error : Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'value' of 'DocumentWriter.WriteAsync<T>(Stream, T, CancellationToken)'

**Comment by sungam3r** [comment]
I see `IDependencyResolver` in your sample. That means you use **old** version 2.4.0. Please use the latest 3.0.0-preview-XXXX.

**Comment by sungam3r** [comment]
Closed due to the lack of feedback.
