### ISSUE TITLE
Cannot find constructor for Types.Schema that accepts IServiceProvider

### ISSUE THREAD

**Issue by DrLeh** [graphql-dotnet/graphql-dotnet#1688]
Using the latest package in NuGet for GraphQL, I'm trying to use dependency injection with my Schema like so:
```
    public class ContactSchema : Schema
    {
        public ISchema GraphQLSchema { get; }

        public ContactSchema(IServiceProvider sp)
            : base(sp) //error here
        {
```

However, I get an error that there is no overload accepting IServiceProvider. When I step into the definition of Types.Schema, I see the following definitions. 

```

#region Assembly GraphQL, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null
// C:\Users\...\.nuget\packages\graphql\2.4.0\lib\netstandard2.0\GraphQL.dll
#endregion

namespace GraphQL.Types
{
    public class Schema : ISchema, IDisposable
    {
        public Schema();
        [Obsolete("The Func<Type, IGraphType> constructor has been deprecated in favor of using IDependencyResolver.  Use FuncDependencyResolver to continue using a Func.  This constructor will be removed in a future version.")]
        public Schema(Func<Type, IGraphType> resolveType);
        public Schema(IDependencyResolver dependencyResolver);

```

Do I have the wrong nuget package? Where can I find this overload?

**Comment by sungam3r** [comment]
> Using the latest package in NuGet for GraphQL

latest _stable_ you mean

![изображение](https://user-images.githubusercontent.com/21261007/82590115-d1345b80-9ba5-11ea-8fee-250a2685eb8a.png)

Use the latest preview and please read README.md

**Comment by DrLeh** [comment]
Thanks. Every google search I found was saying to provide that. Wasn't expecting official documentation to talk about unreleased versions.

**Comment by sungam3r** [comment]
This is not unreleased versions, this is preview published versions.
