### ISSUE TITLE
To use GraphiQL without CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by Matthias-Hess** [graphql-dotnet/graphql-dotnet#169]
I hooked up GraphiQl to my graphql-dotnet enabled server. This works, but only if I use a JsonSerializerSettings with a CamelCasePropertyNamesContractResolver().

If I omit the CamelCasePropertyNamesContractResolver, then I can still submit Queries from GraphiQL, but I can no longer display the Documentation tab on the right side. Instead, I only see a loading indicator...

![doghnut](https://cloud.githubusercontent.com/assets/6832176/18231365/88379b46-72b8-11e6-9646-00a9e5a4f4a3.gif)

I would prefer if I could my own property names in PascalCase which are also used in my classes (like FirstName, FamiliyName) instead of changing them to CamelCase (like firstName, familyName). 

Does the GraphQl spec say the names must be in camelCase? If not, is this a bug in GraphiQl?

**Comment by joemcbride** [comment]
Yes, the root "data" and "errors" must be camelCase and that is part of the spec.  Some of the other introspection may need to be camelCase for GraphiQL to work, though I'm not sure if that's part of the spec.  Right now there could be other issues with the json serialization because in all versions besides the .NET Core alpha Nuget I'm ILMerging JSON.NET.  That could be another issue unless you're using that alpha Nuget.

**Comment by joemcbride** [comment]
Right now this project has been relying upon the camelCase property names, so additional changes may have to be made to support other property name styles.

**Comment by Matthias-Hess** [comment]
Thanks a lot for your help!

If I understood you correctly, the spec does not dictate that the property names of my domain models fields names are camelCased, right? If possible, I would like to stick with PascalCase property names for "my" properties.

I tried the following hacky ContractResolver, which did the trick:

```csharp
public class CamelCasePropertyNamesResolverExceptDataAndError : DefaultContractResolver
    {
        protected override string ResolvePropertyName(string propertyName)
        {
            return propertyName.ToLowerInvariant() == "errors" || propertyName.ToLowerInvariant() == "data"
                ? propertyName.ToLowerInvariant()
                : propertyName;
        }
    }
```

Now I have my PascalCase propertyNames and GraphiQl works! 

But of couse, this solution is not very elegant. Wouldn't it be best if GraphQl for .NET could make sure that the property names of the important properties like "errors" and "data" are always camelCased (as the spec dicates), while just leaving the names of the Fields just as the user of the library entered them?

**Comment by joemcbride** [comment]
> the spec does not dictate that the property names of my domain models fields names are camelCased

As far as I'm aware, yes that is correct.

> Wouldn't it be best if GraphQl for .NET could make sure that the property names of the important properties like "errors" and "data" are always camelCased (as the spec dicates), while just leaving the names of the Fields just as the user of the library entered them

That is a fine goal though could be harder than it sounds.  Mostly, I'm not sure what the best route to take yet is, as well as ensuring which properties are required to be camelCased and which ones are not.  I am also biased towards camelCase so that is not helping you.  I can sympathize that you want to go that route though it is just not a high priority feature currently.  With the move to .NET Core it is easier to make changes like you did (before it was impossible with the ILMerging).  As other updates progress I have been keeping this feature request in mind (you're not the first to ask), though I can't say when it will be a fully supported feature.

**Comment by Matthias-Hess** [comment]
This was the straw that broke ~~the camel's~~ Pascals back!
We have discussed the topic on our team. We decided to use camelCase in javaScript..
The whole PascalCase mindset was a result of our .NET roots. But because in javaScript, camelCase is more common, we think it is better to use that idiom. Thanks for your thoughts!

**Comment by drobertson123** [comment]
Just an odd side note. Seeing this same conversation about casing happening in multiple disparate repositories. I guess casing is the new Tabs vs Spaces fight.  :-)

**Comment by pravinhabbu4u** [comment]
@joemcbride  Thanks for the information. I was looking for a hack that would be an extension to what @Matthias-Hess was trying to do. I am actually able to use the names in custom cases using below hacks:

1. Prefix all field names with a standard string - In my case I am trying with Field_ (example: Field_Id, Field_Name etc) and then using below hacks in code
+
2. Modify ToCamelCase function from StringExtensions as: <This allows me to prevent accidental overriding of any standard graphql fields?>
        public static string ToCamelCase(this string s)
        {
            if (string.IsNullOrWhiteSpace(s))
            {
                return string.Empty;
            }
            if(s.StartsWith("Field_") && s.Length > 6)
            {
                return s.Substring(6);
            }
             return $"{char.ToLowerInvariant(s[0])}{s.Substring(1)}";
        }
+
3. Overridign CamelCasePropertyNamesContractResolver with CustomCaseResolver (as done by @Matthias-Hess )

    public class CustomCaseResolver : DefaultContractResolver
    {
        protected override string ResolvePropertyName(string propertyName)
        {
            string s = propertyName;

            return propertyName.ToLowerInvariant() == "errors" || propertyName.ToLowerInvariant() == "data"
                ? propertyName.ToLowerInvariant()
                : propertyName;
        }
    }


I am now trying to see if the same overrides can be applied while using nuget GraphQL package .

**Comment by pravinhabbu4u** [comment]
[https://github.com/graphql-dotnet/graphql-dotnet/issues/275#issuecomment-278042241](url)

**Comment by pravinhabbu4u** [comment]
#275

**Comment by jusefb** [comment]
Can anyone help to understand how to use GraphiQL with graphql-dotnet?
