### ISSUE TITLE
Enum Argument types don't seem to be supported.

### ISSUE THREAD

**Issue by RoarkeRandall** [graphql-dotnet/graphql-dotnet#1692]
## Description

Unable to use enumeration type as query argument

### Steps to reproduce

Create an enum type:

```
public class TemplateTypeEnum : EnumerationGraphType<Content.TemplateType>
{ }
```

referencing an actual enum:

```
namespace ZG.Concierge.Content
{
    public enum TemplateType
    {
        Unknown = 0,
        RepScript = 1,
        Sms = 2,
        Email = 3
    }
}
```

try to use it in a query:

```
        Field<ListGraphType<TemplateType>>(
                "templates",
                "templates",
                arguments: new QueryArguments(
                    new QueryArgument<EnumerationGraphType<TemplateTypeEnum>> { Name = "type" },
                    new QueryArgument<ListGraphType<StringGraphType>> { Name = "searchTerms" }
                ),
                resolve: ctx =>
                {
                    var templateType = ctx.GetArgument<Content.TemplateType>("type");
                    var searchTerms = ctx.GetArgument<List<String>>("searchTerms");
                    return ctx.GetDataContext().SearchTemplates(templateType, searchTerms);
                }
            );
```

### Expected result

graphiql should be able to get schema information

### Actual result

The following error occurs when inspecting the schema:

```
 ---> StructureMap.Building.StructureMapBuildException: Error while building type EnumerationGraphType<TemplateTypeEnum>.  See the inner exception for details
1.) new EnumerationGraphType`1()
2.) EnumerationGraphType<TemplateTypeEnum>
3.) Instance of EnumerationGraphType<TemplateTypeEnum>
4.) Container.GetInstance(EnumerationGraphType<TemplateTypeEnum>)
 ---> System.ArgumentException: Type provided must be an Enum.
Parameter name: enumType
   at System.RuntimeType.GetEnumNames()
   at GraphQL.Types.EnumerationGraphType`1..ctor()
```

### Environment

version 2.2.0 on dotnet core (on mac)

**Comment by joemcbride** [comment]
It looks like you're doubling up on `EnumerationGraphType<T>`.  Try the following change:

```diff
- new QueryArgument<EnumerationGraphType<TemplateTypeEnum>> { Name = "type" },
+ new QueryArgument<TemplateTypeEnum> { Name = "type" },
```

**Comment by RoarkeRandall** [comment]
Thanks for the quick reply, trying that I get the following error:

```
Error: Introspection must provide input type for arguments.
```

Im unsure if that's a client side or server side error

**Comment by sungam3r** [comment]
What version of GraphQL.NET do you use? Please try to switch to the latest preview.

**Comment by RoarkeRandall** [comment]
I tried 2.2.0 & 2.4.0 with no luck. The previews don't build for me due to the breaking changes. It looks like some significant refactor work. Not sure if I'll be able to get to that now.

**Comment by sungam3r** [comment]
Well, I can say you with confidence that GraphQL.NET supports enum arguments. There are a lot of tests in solution to verify that. Now it will be problematic to deal with your question using 2.4.0 version.

Yes, 3.0.0 introduces some breaking changes. I can help you migrating to the latest preview. In fact, the current preview version is much more stable than 2.4.0, many bugs were fixed.

**Comment by RoarkeRandall** [comment]
<img width="1426" alt="Screen Shot 2020-05-27 at 12 07 02 PM" src="https://user-images.githubusercontent.com/6657263/83061973-b5501000-a012-11ea-83cd-0a8962fe2203.png">

Here's the errors I end up with after a bit of refactoring. It was mostly switching imports around and updating `ResolveFieldContext` to `IResolveFieldContext`

The main issue seems to be around how we were executing our query:

```
        private async Task<string> QueryInternal(string query, JObject variables)
        {

            var result = await _executer.ExecuteAsync(options =>
            {
                options.Schema = _schema;
                options.Query = query;
                options.Inputs = variables != null ? variables.ToInputs() : null;
                options.UserContext = _userContext;
            });

            CheckForErrors(result);



            var json = new DocumentWriter(true).Write(result);
            return json;
        }
```

I should be able to handle the dependency resolver stuff. The main issue is I don't know what documentation to work off of.

**Comment by sungam3r** [comment]
Change `IDependencyResolver` to `IServiceProvider`. Existing documentation contains it.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/dependency-injection.md

**Comment by RoarkeRandall** [comment]
Sorry, my comment wasn't clear. I can handle the DI stuff. I was looking for advice about the removal of `DocumentWriter`. The examples show doing something like this:

```
            var schema = new Schema
            {
                Query = new ConciergeQuery(_user)
            };

            var json = await schema.ExecuteAsync(_ =>
            {
                _.Query = query;
            });

            return json;
```

however, I get the following error: 

```
'Schema' does not contain a definition for 'ExecuteAsync' and the best extension method overload 'DocumentExecuterExtensions.ExecuteAsync(IDocumentExecuter, Action<ExecutionOptions>)' requires a receiver of type 'IDocumentExecuter' [Service]
```

**Comment by sungam3r** [comment]
You need a `IDocumentWriter` to write lson response back.
dotnet add package GraphQL.SystemTextJson 
or
dotnet add package GraphQL.NewtonsoftJson

Then use `DocumentWriter` class. The name is the same for both packages.

**Comment by sungam3r** [comment]
Closed due to the lack of feedback.
