### ISSUE TITLE
Extend IDataloader with metadata

### ISSUE THREAD

**Issue by JKamsker** [graphql-dotnet/graphql-dotnet#1696]
## Summary
Add optional metadata to each IDataLoader.Load for better queries.

### Basic example 
Copied from [Examples](https://graphql-dotnet.github.io/docs/guides/dataloader#examples)
```csharp
public class OrderType : ObjectGraphType<Order>
{
	// Inject the IDataLoaderContextAccessor to access the current DataLoaderContext
    public OrderType(IDataLoaderContextAccessor accessor, IUsersStore users)
    {
        ...

        Field<UserType, User>()
            .Name("User")
            .ResolveAsync(context =>
            {
		// List of required fields to load
            	var requiredFields = new[]{"Id", "Name"};
				
            	// Get or add a batch loader with the key "GetUsersById"
            	// The loader will call GetUsersByIdAsync for each batch of keys
                var loader = accessor.Context.GetOrAddBatchLoader<int, User>("GetUsersById", users.GetUsersByIdAsync);

                // Add this UserId to the pending keys to fetch
                // The task will complete once the GetUsersByIdAsync() returns with the batched results
                return loader.LoadAsync(context.Source.UserId, requiredFields);
            });
    }
}

public interface IUsersStore
{
	// This will be called by the loader for all pending keys
	// Note that fetch delegates can accept a CancellationToken parameter or not
	Task<IDictionary<int, User>> GetUsersByIdAsync(IEnumerable<int> userIds, IEnumerable<object> additionalData, CancellationToken cancellationToken);
}
```

### Motivation

Currently the Dataloader only supports keys to be added and queried to/from the queue. 
Additional query data can only be injected by creating a specific wrapper object which implements  "IComparable<HoursKey>" and "IEquatable<HoursKey>" for the real key. But that is only a hacky workaround as only one Wrapper for each key would be enqueued for the dataquery which could result in a corrupted result.

For this reason i need an overload/second optional parameter for IDataLoader.LoadAsync which accepts any kind of data. In this case the fetchFunc should be responsible for deduplication and further use of the additional data.

**Comment by Shane32** [comment]
Using a simple class as a key, without implementing `IComparable` or `IEquatable`, should always compare as not equal to any other object.  So the data loader's dictionary will load all of your custom key classes without any deduplication.  You can then feel free to run your own deduplication code within the data loader.

It might not be quite as efficient as a data loader based on a `List<>` vs a `Dictionary<>`, but it should work quite nicely.

**Comment by sungam3r** [comment]
@Shane32 Any work here?

**Comment by Shane32** [comment]
I suggest not.

**Comment by Shane32** [comment]
Also users can use a ValueTuple to inject data, which will be deduplicated properly, to the extent that the tuple types are comparable.

**Comment by Shane32** [comment]
@JKamsker Feel free to continue discussion if you'd like and we can discuss further.  Closing for now.
