### ISSUE TITLE
Documentation small mistake.

### ISSUE THREAD

**Issue by faketogosamogo** [graphql-dotnet/graphql-dotnet#1697]
(sorry, i am russian, and my english very bad/
in your documentation writen(https://graphql-dotnet.github.io/docs/getting-started/dependency-injection):
public class StarWarsSchema : GraphQL.Types.Schema
{
    public StarWarsSchema(IServiceProvider provider)
        : base(provider)
    {
        Query = provider.GetRequiredService<StarWarsQuery>();
        Mutation = provider.GetRequiredService<StarWarsMutation>();
    }
}

but package not contain constructor with IServiceProvider, only:
        public Schema();
        public Schema(Func<Type, IGraphType> resolveType);
        public Schema(IDependencyResolver dependencyResolver);

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet#documentation

**Comment by sungam3r** [comment]
I mean you use 2.4.0 version. Docs describe 3.0.0-preview.

**Comment by faketogosamogo** [comment]
thanks
