### ISSUE TITLE
Invalid enum values do not raise an exception

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1699]
When serializing an enumeration value that does not correspond to a enumeration member, no exception is raised, and the value gets serialized as null.  If it is a non-null graph, the parent object gets set to null without an exception getting raised.  Is there a way to incorporate validation into the serialization such that an exception is raised rather than incorrect data being returned?  Perhaps within `ValidateNodeResult`?  Note that if `null` was returned, an exception would be thrown, rather than the `null` value "bubbling up" to a nullable field.

See here where the enumeration serializer returns null for invalid members:

https://github.com/graphql-dotnet/graphql-dotnet/blob/1e2154d4885cd3a5415a46aca6be7e082c807d71/src/GraphQL/Types/Scalars/EnumerationGraphType.cs#L56

Note that this does not occur until the graph is serialized via this code, after all the resolvers have executed:

https://github.com/graphql-dotnet/graphql-dotnet/blob/1e2154d4885cd3a5415a46aca6be7e082c807d71/src/GraphQL/Execution/ExecutionStrategy.cs#L24

And here is the code that causes parent objects to return null if a non-null child (in this case a scalar) returns null:

https://github.com/graphql-dotnet/graphql-dotnet/blob/1e2154d4885cd3a5415a46aca6be7e082c807d71/src/GraphQL/Execution/ExecutionNode.cs#L166

Here is where the exception occurs if you attempt to return a null value from a resolver to a non-null graph:

https://github.com/graphql-dotnet/graphql-dotnet/blob/1e2154d4885cd3a5415a46aca6be7e082c807d71/src/GraphQL/Execution/ExecutionStrategy.cs#L251

I tried to alter `ExecutionStrategy` to throw an exception if a non-null child object returns null, but this breaks error situations where nulls are supposed to bubble up.  See this test:

https://github.com/graphql-dotnet/graphql-dotnet/blob/1e2154d4885cd3a5415a46aca6be7e082c807d71/src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs#L189

Changing the enumeration serializer causes similar issues.  Any suggestions?  This is a problem for my code.

**Comment by sungam3r** [comment]
I myself faced such a problem. At first I thought I needed to return an error, but then I realized that it would contradict nullability "bubbling up" logic. In general, this behavior applies to all types that return from GraphQL response not only enumerations. This behavior is described in the specification. In my thoughts, I settled on the fact that the server can just log this situation. I agree that simply returning null without additional information does not help to understand the cause of the error. However, we cannot go against the specification. I need time to rethink your case.

**Comment by sungam3r** [comment]
@joemcbride What do you think?

**Comment by Shane32** [comment]
@sungam3r I don't mind it bubbling up the null.  The problem is that a failed enum conversion does not trigger any error at all, which does not meet the specification.

> 3.9 GraphQL servers must return one of the defined set of possible values. If a reasonable coercion is not possible they must raise a field error

Once a field error is thrown, a null should be returned and an error should be added to the errors list.

> 6.6.4 If an error is thrown while resolving a field, it should be treated as though the field returned null, and an error must be added to the "errors" list in the response.

Strictly speaking, the current implementation goes against the specification in two different ways:

1. When an enumeration value provided by a resolver is out of range of the allowed values, null is returned and bubbled up (ok), but no error is added to the errors list in the response (fails rule 3.9).

2. When an out of range value is provided to a integer field (e.g. returning `long.MaxValue` to an `IntGraphType`), the entire `data` field is omitted and no 'null' bubbling occurs (fails 6.6.4).

I will be providing a PR to fix these issues and bring the functionality in alignment with the graphql specification.

**Comment by Shane32** [comment]
Also, the current implementation does not require input arguments to be valid.  Rather, the current implementation uses the default value for an argument when the input value cannot be parsed.  This is also explicitly against the specification, listed in multiple areas.  For instance:

> 3.5 Input Coercion: If a GraphQL server expects a scalar type as input to an argument, coercion is observable and the rules must be well defined. If an input value does not match a coercion rule, a query error must be raised.

> 3.9 Input Coercion: GraphQL has a constant literal to represent enum input values. GraphQL string literals must not be accepted as an enum input and instead raise a query error.

Also see 3.10 - Input Object Coercion Examples - where it shows that values that cannot be coerced to a valid value should raise a query error.

Note that within 3.5 (shown above), it is allowed for input value parsing to coerce values between types.  It's just that if the value cannot be coerced, a query error must be returned.
