### ISSUE TITLE
Validate schema at build time

### ISSUE THREAD

**Issue by MargaretKrutikova** [graphql-dotnet/graphql-dotnet#1700]
## Summary

We have run into several issues when there were no compile-time errors, but the graphql api threw exceptions at run-time when trying to execute queries. 

Is there any way schema can be validated at all? In the perfect scenario would be nice to fail at compile time or directly at startup if the schema definition is invalid.

## Relevant information

We have recently started using `graphql-dotnet` at work with GraphType First Approach. 
The examples on where we had runtime exceptions include:

1. Duplicate typenames. 

We have a lot unions in our underlying F# services, so we started using the same types  in our graphql api and ended up with `Name` being the same across some cases of different unions.
For example, type `AllProjectRestriction` had `Name="All"` and `AllUserRestriction` had also `Name="All"` because this is how we model it in the underlying logic.

This case a runtime error when trying to send queries to the API.

2. Using union types as input. This also gives a runtime error, because it is not supported on the specification level.

We might encounter more as we our queries get more complex. 

Thanks in advance 🙂

**Comment by sungam3r** [comment]
Try the latest preview, these problems were resolved.

**Comment by sungam3r** [comment]
Closed due to the lack of feedback.
