### ISSUE TITLE
Field and argument validations.

### ISSUE THREAD

**Issue by faketogosamogo** [graphql-dotnet/graphql-dotnet#1702]
(my english very bad). Hellow, i recently started work with this library, and not found analogs for DataAnnotations(Length, max, min). How i can raplace them for  GraphQLQueryArgument and GraphQLInputType. In issue 1460 (https://github.com/graphql-dotnet/graphql-dotnet/issues/1460) use directives, can I do without them?

**Comment by sungam3r** [comment]
I think directives is the only way.

**Comment by faketogosamogo** [comment]
Thanks, for example I havel:
 public TestInputType()
        {           
            Field<NonNullGraphType<StringGraphType>>("login");   
            Field<NonNullGraphType<StringGraphType>>("password");
            Field<NonNullGraphType<IntGraphType>>("number");     
        }
how i can in this fragment set max and min length password and max and min value number?

**Comment by sungam3r** [comment]
See https://github.com/graphql-dotnet/graphql-dotnet/issues/1460#issuecomment-568055977 and #1451

**Comment by sungam3r** [comment]
@faketogosamogo A lot of work was done to support directives in v4. See `LengthDirective` and `InputFieldsAndArgumentsOfCorrectLength` validation rule in `develop` branch. And [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/develop/docs2/site/docs/getting-started/directives.md) you can find updated documentation about directives. Closing. Feel free to ask further questions.
