### ISSUE TITLE
Question: ParallelExecutionStrategy and Task.WhenAll

### ISSUE THREAD

**Issue by kevklam** [graphql-dotnet/graphql-dotnet#1703]
Hi,
I was wondering about the reasoning for using Task.WhenAll to await node execution in ParallelExecutionStrategy. At first brush it looks like Task.WhenAny would make more sense to ensure full usage of the configured max parallelization, but I was wondering if that has some bad interactions with DataLoader or some other such issues.

Would appreciate any insight here!

**Comment by Shane32** [comment]
It is a problem with the current DataLoader implementation.  It would not be a problem if #1511 were pulled.

Also see #976

**Comment by sungam3r** [comment]
Closing as fixed. Ping @Shane32 . Right?

**Comment by Shane32** [comment]
Not exactly “fixed”. The new data loader could work with WhenAny but currently we still use WhenAll in the ParallelExecutionStrategy.
