### ISSUE TITLE
Aggregation types in schema

### ISSUE THREAD

**Issue by MakaBuka** [graphql-dotnet/graphql-dotnet#1705]
Hi guys,

Im working on aggregation functions feature and stuck with one issue (probably) 
In my project, I have two simple entities - customers and orders
I defined for each graphql type separate aggregation type which is including aggregation function type (with appropriate fields - "total" and "price") 
By some reason, GraphQL "detect" latest defined type - so, I got the same field in "sum" aggregation type.

So, Im trying to implement something like this:
> 
      customers {
           aggregation {
            sum {
               price --> should be "total" field, but instead of it - field from type defined for another entity - orders
             }
          }
       }
     orders{
       customerId
       aggregation {
          sum {
            price
           }
        }
      }

Maybe I did something wrong? might be because name of graphql type should be unique? Or it's known issue and somewhere exists workaround?

Version of GraphQL lib 2.4

Thanks, Dmytro.

**Comment by sungam3r** [comment]
> might be because name of graphql type should be unique?

Exactly. Try the latest 3.0.0-preview.

**Comment by MakaBuka** [comment]
@sungam3r thanks for your reply. As far as I understood, release of v3 is going to be soon? 
Anyways, thanks one more time - you save me one more night, cuz, I thought that i missed sth. will try to find temporary solution before v3 release

**Comment by sungam3r** [comment]
> As far as I understood, release of v3 is going to be soon?

Well, just read #1321 .

**Comment by sungam3r** [comment]
Closed as answered.
