### ISSUE TITLE
Automatically convert model to objectGraphType

### ISSUE THREAD

**Issue by nivedhauswin** [graphql-dotnet/graphql-dotnet#1707]
I recently started work with this library, now if I have a single model( author.cs ) I can manually create a ObjectGraphType for that. Now what if I have 100 models like that do i still have to create ObjectGraphType for all 100 models or there are ways to minimize it?

**Comment by BenjaBobs** [comment]
What you're looking for is [AutoRegisteringObjectGraphType](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs).

With that you can do `AutoRegisteringObjectGraphType<Author>` as type and it will manually register the properties of `Author`.

**Comment by nivedhauswin** [comment]
Thanks. I have another doubt. now what if we define the base class as ObjectGraphType or AutoRegisteringObjectGraphType and will the derive it use like the code below. I might sound silly.
```
    class BaseBaseAuthor
    {
        public string Name { get; set; }
    }
    class BaseAuthor : AutoRegisteringObjectGraphType<BaseBaseAuthor>
    {
        public int Age { get; set; }
    }
    class Author : BaseAuthor
    {
        public string Book { get; set; }
    }
   class RootQuery : ObjectGraphType
    {
        public RootQuery()
        {
            Field<Author>("author",
                resolve : context=> new Author() { Name="Nivedh", Age = 21, Book="own"}
            );
        }
    }
```

Input : { author{ name book age } }

**Comment by BenjaBobs** [comment]
I don't remember the exact syntax on the top of my mind, but I would do something like this:
```c#
public interface IEntity {}

public class Author : IEntity
{
	public string Name { get; set; }
	//...
}

public class Book : IEntity
{
	public string Name { get; set; }
	//...
}

public class RootQuery : ObjectGraphType
{
	public RootQuery()
	{
		var entityTypes = GetType().Assembly.GetTypes().Where(t => typeof(IEntity).IsAssignableFrom(t) && !t.IsInterface)

		foreach (var entityType in entityTypes)
		{
			Field(
				entityType.GraphQLName(),
				typeof(AutoRegisteringGraphType<>).MakeGeneric(entityType),
				resolve: context => { // fetch data or something }
			)
		}
	}
}
```

**Comment by nivedhauswin** [comment]
I tried 
```
var entityTypes = GetType().Assembly.GetTypes().Where(t => typeof(BaseBaseAuthor).IsAssignableFrom(t) && !t.IsInterface);
            foreach (Type entityType in entityTypes)
            {               
                Field(                    
                    typeof(AutoRegisteringObjectGraphType<>).MakeGenericType(entityType),
                    entityType.GraphQLName(),
                    resolve: context =>
                    {
                        return null;
                    }
                );               
            }
```

Error : {"Failed to call Activator.CreateInstance. Type: GraphQL.Types.AutoRegisteringObjectGraphType`1[[app.model.Author, Proposed, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"}

**Comment by BenjaBobs** [comment]
Interesting, definitely not the exception I expected to see.
@sungam3r Could you weigh in here? Is it perhaps because `AutoRegisteringObjectGraphType` has no empty constructor?
