### ISSUE TITLE
Subscription message are sent twice

### ISSUE THREAD

**Issue by ZeroKaa** [graphql-dotnet/graphql-dotnet#1708]
## Description

When I send a message from .net code into a subscriptiion. I see the mesage twice on the network (WS) tab

### Steps to reproduce

Just send a message using 
`
private readonly ISubject<NotificationEntity> _messageStream = new ReplaySubject<NotificationEntity>(1);

        public System.Reactive.Linq.IQbservable<NotificationEntity> Messages()
        {
            return _messageStream.AsQbservable();
        }

        public NotificationEntity SendMessage(NotificationEntity notification)
        {
            _messageStream.OnNext(notification);
            return notification;
        }
`

### Expected result

I expect the message to arrive only once

### Actual result

The message is sent twice

### Environment

Windows 10, .net 5, angular

**Comment by sungam3r** [comment]
@ZeroKaa I hope you managed to solve this issue. Subscriptions engine was completely rewritten over these years thought. Closing.
