### ISSUE TITLE
DataLoader gets exponentially slower when number of items increase

### ISSUE THREAD

**Issue by Mithras** [graphql-dotnet/graphql-dotnet#1710]
## Description

DataLoader itself introduces a huge overhead. Difference between 100 items and 10000 items is like 4 seconds not taking any DB round trips into account. Just delay between the very first call to GetOrAddCollectionBatchLoader() and call to fetchFunc() is about 4 seconds on a pretty fast dev machine (tested with 10k GetOrAddCollectionBatchLoader() calls).

### Steps to reproduce

Define a top level field with about 10k items, then define a nested field with DataLoader.GetOrAddCollectionBatchLoader(). Even if you hardcode something like Enumerable.Range(0, 10000).Select(...), it'll be 4+ seconds.

### Expected result

DataLoader overhead shouldn't be exponential.

### Actual result

It's about exponential.

### Environment

Version: 3.5.0-alpha0046

**Comment by Mithras** [comment]
![Annotation 2020-06-12 182944](https://user-images.githubusercontent.com/2098029/84556885-bc497480-acda-11ea-808c-84cfce4209e8.png)

**Comment by Mithras** [comment]
Here is an example app

```
using GraphQL;
using GraphQL.DataLoader;
using GraphQL.Types;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp7
{
    class Program
    {
        private static int _count;

        static async Task Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddSingleton<RootType>();
            serviceCollection.AddSingleton<ChildType>();
            serviceCollection.AddSingleton<IDataLoaderContextAccessor>(new DataLoaderContextAccessor
            {
                Context = new DataLoaderContext()
            });
            serviceCollection.AddSingleton<DataLoaderDocumentListener>();

            var serviceProviderFactory = new DefaultServiceProviderFactory();
            var serviceProvider = serviceProviderFactory.CreateServiceProvider(serviceCollection);

            var schema = new Schema(serviceProvider)
            {
                Query = new MyQuery()
            };

            var queryWithLoader = @"
query MyQuery {
    root {
        id
        name
        child {
            id
            name
        }
    }
}";
            var queryWithoutLoader = @"
query MyQuery {
    root {
        id
        name
    }
    child {
        id
        name
    }
}";

            _count = 100;
            var sw = new Stopwatch(); sw.Start();
            await schema.ExecuteAsync(new MyDocumentWriter(), _ =>
            {
                _.Query = queryWithLoader;
                _.EnableMetrics = false;
                _.Listeners.Add(serviceProvider.GetRequiredService<DataLoaderDocumentListener>());
            });
            sw.Stop();
            Console.WriteLine($"WithLoader (100 items): {sw.ElapsedMilliseconds}");

            _count = 10000;
            sw.Restart();
            await schema.ExecuteAsync(new MyDocumentWriter(), _ =>
            {
                _.Query = queryWithLoader;
                _.EnableMetrics = false;
                _.Listeners.Add(serviceProvider.GetRequiredService<DataLoaderDocumentListener>());
            });
            sw.Stop();
            Console.WriteLine($"WithLoader (10000 items): {sw.ElapsedMilliseconds}");

            _count = 100;
            sw.Restart();
            await schema.ExecuteAsync(new MyDocumentWriter(), _ =>
            {
                _.Query = queryWithoutLoader;
                _.EnableMetrics = false;
                _.Listeners.Add(serviceProvider.GetRequiredService<DataLoaderDocumentListener>());
            });
            sw.Stop();
            Console.WriteLine($"WithoutLoader (100 items): {sw.ElapsedMilliseconds}");

            _count = 10000;
            sw.Restart();
            await schema.ExecuteAsync(new MyDocumentWriter(), _ =>
            {
                _.Query = queryWithoutLoader;
                _.EnableMetrics = false;
                _.Listeners.Add(serviceProvider.GetRequiredService<DataLoaderDocumentListener>());
            });
            sw.Stop();
            Console.WriteLine($"WithoutLoader (10000 items): {sw.ElapsedMilliseconds}");

            Console.ReadKey();
        }


        public class MyDocumentWriter : IDocumentWriter
        {
            public Task WriteAsync<T>(Stream stream, T value, CancellationToken cancellationToken = default)
            {
                //JsonSerializer.Serialize(new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }), value);
                return Task.CompletedTask;
            }
        }

        public class MyQuery : ObjectGraphType
        {
            public static readonly Root[] Root = Enumerable.Range(0, 10000)
                .Select(x => new Root
                {
                    Id = x,
                    Name = x.ToString()
                })
                .ToArray();
            public static readonly Child[] Child = Enumerable.Range(0, 10000)
                .Select(x => new Child
                {
                    Id = x,
                    Name = x.ToString()
                })
                .ToArray();

            public MyQuery()
            {
                Field<ListGraphType<RootType>>("root", resolve: ctx => Root.Take(_count));
                Field<ListGraphType<ChildType>>("child", resolve: ctx => Child.Take(_count));
            }
        }

        public class RootType : ObjectGraphType<Root>
        {
            private static readonly Dictionary<int, Child> _child = MyQuery.Child.ToDictionary(x => x.Id);

            public RootType(IDataLoaderContextAccessor accessor)
            {
                Field(x => x.Id);
                Field(x => x.Name);
                Field(x => x.Child, type: typeof(ChildType))
                    .ResolveAsync(ctx =>
                    {
                        var loader = accessor.Context.GetOrAddBatchLoader<int, Child>("test", async items => _child);
                        return loader.LoadAsync(ctx.Source.Id);
                    });
            }
        }

        public class ChildType : ObjectGraphType<Child>
        {
            public ChildType()
            {
                Field(x => x.Id);
                Field(x => x.Name);
            }
        }

        public class Root
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public Child Child { get; set; }
        }

        public class Child
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }
    }
}
```

The result I'm getting is

> WithLoader (100 items): 502
> WithLoader (10000 items): 2398
> WithoutLoader (100 items): 1
> WithoutLoader (10000 items): 88

As you can see, DataLoader introduces huge delays even though results with and without DataLoader are about the same size.

**Comment by Mithras** [comment]
Some update.
It seems that FieldBuilder introduces the most of overhead in my example. Just to compare:
```
FieldAsync<ChildType>(nameof(Root.Child), resolve: ctx => Task.FromResult<object>(MyQuery.Child[ctx.Source.Id])); // 138ms
```
```
Field(x => x.Child, type: typeof(ChildType)).ResolveAsync(ctx => Task.FromResult(MyQuery.Child[ctx.Source.Id])); // 1127ms
```

**Comment by Mithras** [comment]
```
FieldAsync<ChildType>(nameof(Root.Child), resolve: async ctx =>
{
    // await Task.Yield(); // Uncommenting this adds almost 2 seconds on 10k items
    return MyQuery.Child[ctx.Source.Id];
});
```

**Comment by Shane32** [comment]
With PR #1511 this is not an issue, as individual `Task` objects are not created for each item.  Results on my machine (running the exact code from the sample above) is as follows:
```
WithLoader (100 items): 219
WithLoader (10000 items): 159
WithoutLoader (100 items): 0
WithoutLoader (10000 items): 95
```
The first entry is always slow because it is the first time the code is run.  If the code is modified to run `Main()` twice, the second loop through returns results like this:
```
WithLoader (100 items): 4
WithLoader (10000 items): 136
WithoutLoader (100 items): 1
WithoutLoader (10000 items): 103
```

**Comment by Mithras** [comment]
@Shane32 That's awesome! I'll take a look at the PR. Thank you!

>The first entry is always slow

I know, that's pretty much why I did 100 before 10k.

**Comment by Mithras** [comment]
@Shane32 I didn't spend a lot of time but from what I'm seeing the main changes are under src/GraphQL/DataLoader/* and src/GraphQL/Execution/*. Do you think it's possible to just copy paste  src/GraphQL/DataLoader/* and src/GraphQL/Execution/* from your branch locally and then create my own DocumentExecuter in order to override this https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L268 with your classes? Or there are more thing I'm not aware of?

**Comment by Shane32** [comment]
Are you asking if it's possible to use the nuget package plus the revised DataLoader code?

**Comment by Mithras** [comment]
Yes but I actually already tried it and everything seems to work.
I just copy-pasted classes from `Dataloder/` and a few classes from `Execution/` like this
<img width="191" alt="Annotation 2020-06-16 164336" src="https://user-images.githubusercontent.com/2098029/84838908-8d8c1080-aff0-11ea-9603-0f30a50ddcae.png">
Then defined MyDocumentExecuter like this
```
    public class MyDocumentExecuter : DocumentExecuter
    {
        protected override IExecutionStrategy SelectExecutionStrategy(ExecutionContext context)
        {
            // TODO: Should we use cached instances of the default execution strategies?
            return context.Operation.OperationType switch
            {
                OperationType.Query => new MyParallelExecutionStrategy(),
                OperationType.Mutation => new MySerialExecutionStrategy(),
                OperationType.Subscription => new SubscriptionExecutionStrategy(),
                _ => throw new InvalidOperationException($"Unexpected OperationType {context.Operation.OperationType}")
            };
        }
    }
```
And finally instead of .AddDataLoader() I did this
```
    services.AddSingleton<IDataLoaderContextAccessor, DataLoaderContextAccessor>();
    services.AddSingleton<IDocumentExecutionListener, DataLoaderDocumentListener>();
    services.AddSingleton<IDocumentExecuter, MyDocumentExecuter>();
```
pointing everything to the classes I copy-pasted.

**Comment by Mithras** [comment]
@Shane32 Have you thought about creating a separate NuGet package with just your DataLoader implementation? At least temporarily. Current DataLoader implementation is pretty much useless in real world because of the huge overhead it introduces. A separate NuGet package with actually working DataLoader would be huge.

**Comment by Shane32** [comment]
I would if @joemcbride doesn't want to merge my implementation; you’re the second person to use my data loader. It’s certainly true that the current implementation is so buggy that it’s nearly useless. I’d be interested to know what the real-world performance impact this is having on your code also.

**Comment by Mithras** [comment]
Well, I'm just looking into switching from REST to GraphQL in our project(s) so I don't really have real-world performance either but I definitely wouldn't use current DataLoader implementation which is adding 2 seconds overhead in 10k items case. I wouldn't be able to justify switching to GraphQL if it's a few times slower than REST.

**Comment by Shane32** [comment]
Overall you should see pretty good performance numbers with this implementation of GraphQL. There are some notable sacrifices in the code to favor performance over code design.

What ORM/data layer are you using?

**Comment by Mithras** [comment]
> Overall you should see pretty good performance numbers with this implementation of GraphQL. There are some notable sacrifices in the code to favor performance over code design.

Yes, it's much better now. Now it seems pretty close to REST in term of performance.

>What ORM/data layer are you using?

EF Core 3.1 + Automapper. I wrote a few extensions to simplify setup and I use Automapper Explicit expansion feature (https://docs.automapper.org/en/stable/Queryable-Extensions.html#explicit-expansion) to only select members from the query.

**Comment by Shane32** [comment]
Nice!  I had not thought of using Automapper.  I use a heavily-modified version of SimonCropp's GraphQL.EntityFramework layer to allow translation from GraphQL queries to LINQ and thereby SQL, including through navigational properties, only selecting the fields requested via GraphQL.  Plus, GraphQL arguments to fields are able to influence the produced LINQ query at any level.

The biggest issue I have with EF 2.x is that some queries are executed client side due to EF being unable to translate the resulting LINQ to SQL.  This results in very poor performance due to the often-hundreds of SQL calls, which data loaders can typically solve.  Also, EF 2.x does not recognize all join forms when a navigation property is not present.

The biggest issue (and benefit) with EF 3.x is that queries are never split over multiple SQL calls, requiring the use of data loaders to prevent cartesian results.  Hopefully with EF 5 both issues will be solved (they just released the `AsSplitQuery()` method in the latest preview), and then EF can handle what dataloaders are doing now (and will be much easier to code).

I'm actually testing my translation layer code on linq2db this week, and I'll have to see how well that works.
