### ISSUE TITLE
How to Implement DataLoader with the Schema-First Approach and GraphQL Federation

### ISSUE THREAD

**Issue by itabaiyu** [graphql-dotnet/graphql-dotnet#1711]
## Summary

Currently, there is no documentation or examples for how to implement DataLoader when using the schema-first approach or  with a federated schema. How does one implement DataLoader in these following scenarios?

Schema-first query resolver:

```
[GraphQLMetadata("Query")]
public class Query
{
    private readonly IProductService _service;

    public Query(IProductService service)
    {
        _service = service;
    }

    [GraphQLMetadata("products")]
    public async Task<IEnumerable<Product>> Products(ProductRequest request)
    {
        return await _service.GetProducts(request);
    }
}
```

`IFederatedResolver`:

```
public class ProductFederatedResolver : IFederatedResolver
{
    private readonly IProductService _service;

    public ProductFederatedResolver(IProductService service)
    {
        _service = service;
    }

    public async Task<object> Resolve(FederatedResolveContext context)
    {
        var arguments = context.Arguments;
        var sku = (string) arguments["sku"];

        return await _service.GetProduct(sku);
    }
}
```

## Relevant information

Existing DataLoader documentation: https://graphql-dotnet.github.io/docs/guides/dataloader/

### Environment (if relevant)

Package version: `v3.0.0-preview-1648`

**Comment by ShadyNawara** [comment]
take a look at: https://github.com/graphql-dotnet/graphql-dotnet/issues/1565 There is an examples on how to do this, it will fail with the current preview build but this PR fixes the issue: https://github.com/graphql-dotnet/graphql-dotnet/pull/1660
