### ISSUE TITLE
case insensitivity for GraphQL.Net

### ISSUE THREAD

**Issue by zivfuture** [graphql-dotnet/graphql-dotnet#1712]
The graphql api resource query is case sensitive. How to make a case-insensitive graphql query?     
Case-insensitive is important to clients.

for exsample:

query{
    droid(id:"3")   //case sensitive here
       {
            Id     //case sensitive here
            Name   //error   ,   it must be "name"
            primaryFunction
        }
}

As you see, We need pay attention to the case sensitive .   it's a horrible thing.

**Comment by vbornand** [comment]
Names in GraphQL are case-sensitive, as per the spec. Names include field names, type names, variable names etc.

Spec: http://spec.graphql.org/June2018/#sec-Names
"Names in GraphQL are case‐sensitive."

**Comment by sungam3r** [comment]
@vbornand You are right. Names **must** be case sensitive to comply spec.
