### ISSUE TITLE
schema.FindType("ID") causes other types to disappear from displayed schema

### ISSUE THREAD

**Issue by oconnor0** [graphql-dotnet/graphql-dotnet#1715]
## Description

I am using GraphQL.Net 3.0.0-preview-1648. I am attempting to programmatically generate a schema, but get weird side effects related to looking up the `ID` type for use.

### Steps to reproduce

1. Create a new project: `dotnet new console -o App`
2. `cd App`
3. Add GraphQL dependency: `dotnet add package GraphQL -v 3.0.0-preview-1648`
4. Modify Program.cs to:

```
using System;

namespace App
{
    class Program
    {
        static void Main(string[] args)
        {
            var schema = new GraphQL.Types.Schema();
            var query = new GraphQL.Types.ObjectGraphType { Name = "Query" };
            schema.RegisterType(query);
            schema.Query = query;

            Console.WriteLine($"id = {schema.FindType("ID")}");

            var jedi = new GraphQL.Types.ObjectGraphType { Name = "Jedi" };
            schema.RegisterType(jedi);

            var name = new GraphQL.Types.FieldType { Name = "name", ResolvedType = schema.FindType("String") };
            jedi.AddField(name);

            var side = new GraphQL.Types.FieldType { Name = "side", ResolvedType = schema.FindType("String") };
            jedi.AddField(side);

            var jediById = new GraphQL.Types.FieldType { Name = "jedi", ResolvedType = jedi };
            var id = new GraphQL.Types.QueryArgument(schema.FindType("ID")) { Name = "id" };
            jediById.Arguments = new GraphQL.Types.QueryArguments(id);
            query.AddField(jediById);

            var options = new GraphQL.Utilities.SchemaPrinterOptions {
                IncludeDescriptions = true,
                IncludeDeprecationReasons = true,
            };
            var printer = new GraphQL.Utilities.SchemaPrinter(schema, options);
            Console.WriteLine(printer.Print());
        }
    }
}
```

5. Run the program: `dotnet run`
6. Notice in the output no type `Jedi` is defined, though `Query` references it:

```
type Query {
  jedi(id: ID): Jedi
}
```

7. Comment line 14: `// Console.WriteLine($"id = {schema.FindType("ID")}");`
8. Rerun the program: `dotnet run`
9. Notice in the output that a type `Jedi` is defined:

```
type Jedi {
  name: String
  side: String
}
```

In my other tests, it appears that the schema is defined properly, in the sense that I can query `jedi(id: ID)` and get back a `Jedi` even though it doesn't show up in the output of `SchemaPrinter`. 

### Expected result

I expect that calling `schema.FindType("ID")` wouldn't change the schema.

### Actual result

But it appears to or at least to change what the schema displays as.

### Environment

Windows 10.
`dotnet --version` 3.1.301

**Comment by sungam3r** [comment]
This is because the schema has an initialization step. Calling `FindType` method results in schema initialization. I have added additional checks and test for this. You should now see a clear error message. Honestly, it would be worthwhile to think at all about how to redo the design so that such a situation does not arise, but so far I am not ready to do it.
