### ISSUE TITLE
DefaultValue gets lost after getArgument()

### ISSUE THREAD

**Issue by kaustubh-ex2** [graphql-dotnet/graphql-dotnet#1717]
I have a Dto with an integer partnerId
```csharp
public class Dto
{
        public int PartnerId { get; set; }
        public string Type { get; set; }
}
```

I made and input object from it

```csharp
public class DtoType: InputObjectGraphType<Dto>
{
        public DtoType()
        {
            Field(x => x.PartnerId, type: typeof(IntGraphType)).DefaultValue(9383);
            Field(x => x.Type, type: typeof(StringGraphType));
        }
}
```

In AppQuery i used it as an argument
```csharp
public AppQuery(ILocationRepository repository)
{
        Field<ListGraphType<LocationType>>(
               "location",
               arguments: new QueryArguments(
                   new QueryArgument<DtoType> { Name = "searchTerm" }
               ),
               resolve: context =>
               {
                   var arg = context.GetArgument<DtoType>("searchTerm"); // This has the default value 9383 present
                   return repository.GetAllLocations(context.GetArgument<Dto>("searchTerm")); // This does not
               }
        );
}
```

And my query looks like
```
query location(searchTerm: {
        Type: "foo"
}){
        name,
        id
}
```
It supposedly works with scalar types.
Am i using it wrong or is this behaviour intended ?

**OS**: Microsoft Windows 10
**GraphQL Package**: 2.4.0
**.Net Core 3.1**

**Comment by sungam3r** [comment]
Please first try the latest [3.0.0-preview-XXXX](https://github.com/graphql-dotnet/graphql-dotnet#graphql-for-net).

**Comment by kaustubh-ex2** [comment]
Hi, thank you for replying. I did as you said, and now i'm kind of lost in errors. First there was the dependency issue, which you mentioned in #1161 and it's gone. Now i'm stuck with
`System.TypeLoadException: 'Could not load type 'GraphQL.Http.IDocumentWriter' from assembly 'GraphQL, Version=3.0.0.1490, Culture=neutral, PublicKeyToken=null'` 
So i added `services.AddSingleton<IDocumentWriter, DocumentWriter>()` and it doesn't find `DocumentWriter`.
Can you point me in the right direction ?

I installed v 3.0.0 p 1490.

Also it warns me about installing GraphQL.Parser as well. If you could tell me what all packages are necessary for 1490 that'd be great.

**Comment by sungam3r** [comment]
P1648 is better. Also see readme with install instructions. GraphQL.Http.DocumentWriter was moved.
