### ISSUE TITLE
Getting error when I click on GraphQl link on admin page.

### ISSUE THREAD

**Issue by kandari7** [graphql-dotnet/graphql-dotnet#1718]
I am getting this error "A field with the name: ContentType is already registered for GraphType: KnowledgeHub (Parameter 'Name')"

**Comment by sungam3r** [comment]
What is _admin page_?

**Comment by kandari7** [comment]
from admin section i Mean. getting the below issue

![image](https://user-images.githubusercontent.com/65922707/86541357-92891380-bf4f-11ea-9124-866f7232a4be.png)

**Comment by sungam3r** [comment]
GraphQL server tries to add field with the same name _ContentType_ second time to graph type `KnowledgeHub`. It is valid check, see your server code which constructs graph type to fix this problem.

**Comment by sungam3r** [comment]
Closed due to the lack of feedback.
