### ISSUE TITLE
Nuget prerelease packages - request to update

### ISSUE THREAD

**Issue by bherila** [graphql-dotnet/graphql-dotnet#1719]
Could I humbly ask for these updated packages to be published to Nuget?

GraphQL.Server.Core 3.5.0-alpha0070
GraphQL 3.0.0-preview-1650

As I have run into some issues with the CLR failing to load `IFieldNameConverter`, which seems to be renamed to `INameConverter` since the current packages were published.

The MyGet packages do resolve the issue however like some other posters, it's difficult to add this feed in CI. 

Thank you very much for considering my request!

**Comment by sungam3r** [comment]
@joemcbride has access for publishing on nuget.

**Comment by sungam3r** [comment]
Done:
https://www.nuget.org/packages/GraphQL/3.0.0-preview-1719
https://www.nuget.org/packages/GraphQL.NewtonsoftJson/3.0.0-preview-1719
https://www.nuget.org/packages/GraphQL.SystemTextJson/3.0.0-preview-1719
\+ 3.5.0-alpha0073 for all server packages
