### ISSUE TITLE
How to list field errors?

### ISSUE THREAD

**Issue by undestroyer** [graphql-dotnet/graphql-dotnet#1724]
##  Summary
When I handle mutation like `registerUser`, I have to perform server-side validation on email and "not a robot" fields. Both of them can be invalid (email can already be taken, not a robot can be invalid). 
Frontend has to handle error messages and add label to inputs. In regular REST I used to return 422 response with JSON object like this:
```
{
 "email": ["This email is already taken."],
 "not_a_robot": ["Wrong captcha, try again."]
}
```
Frontend can easy define what was wrong and display UI errors. How can I list fields with errors for mutation in GraphQL? Or what is the concept about listing errors?

## Relevant information

I tried `ExecutionException`, but it provides errors without defining what property failed. Building large list of `HResult` enum doesn't look like good option because this enum is not listed in schema and I have to document it somewhere else.

**Comment by sungam3r** [comment]
GraphQL response contains errors. Each error has path property and message. You can expose your message.

**Comment by Shane32** [comment]
Might relate to #1740 

Validation rules inspect the input object to be sure it is of the correct type.  Assuming that your front-end validates that parameters are of the correct type, then it would be your mutation field resolver that is examining the inputs to be sure they are valid (e.g. email in correct format).  You can only throw a single `ExecutionError` from a single field resolver, but you have two options to return additional data:

1. You can add data to the `ExecutionError.Data` dictionary to return data along with the error message.  For example, you could execute something like:
```csharp
var error = new ExecutionError("Error adding account");
error.Data["email"] = new[] { "This email is already taken" };
error.Data["not_a_robot"] = new[] { "Wrong captcha, try again." };
throw error;
```
2. You can attach arbitrary information back with the execution result via the `IResolveFieldContext.Extensions` dictionary.  This is not specific to the particular field that caused the error, so it's both harder to use and not as preferred.

**Comment by sungam3r** [comment]
@undestroyer Did you manage to solve your issue?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
