### ISSUE TITLE
No service for type has been registered exception

### ISSUE THREAD

**Issue by aldd-dpulidog** [graphql-dotnet/graphql-dotnet#1737]
##  Summary
Hi, I'm following [this tutorial](https://volosoft.com/blog/Building-GraphQL-APIs-with-ASP.NET-Core) to create a GraphQL API using mysql and EntityFramework Core. I'm stucked with the following exception:

![image](https://user-images.githubusercontent.com/64615320/88196493-de51e300-cc06-11ea-896d-7d59b92b4f7e.png)

## Relevant information
This is how I have my classes:

UnitMeasurementSchema.cs
```
class UnitMeasurementSchema : GraphQL.Types.Schema
    {
        public UnitMeasurementSchema(UnitMeasurementQuery query, IDependencyResolver resolver) : base(resolver)
        {
            Query = query;
            DependencyResolver = resolver;
        }
    }
```

UnitMeasurement.cs (Graphql Type)
```
class UnitMeasurement : ObjectGraphType<UnitMeasurementModel>
    {
        public UnitMeasurement()
        {
            Field(c => c.Id);
            Field(c => c.UnitMeasurementName);
            Field(c => c.UnitMeasurementCode);
   }
```   

Also I have a class for the UnitMeasurement repository and query, I assume they are irrelevant for the issue, I'll add them if required. The important one is the following.

Startup.cs
```
public class Startup
    {
       // Configuration

        public void ConfigureServices(IServiceCollection services)
        {
            // Cors and DBContext

            // I had to add the following two lines due to an Exception not finding neither of them
            services.AddSingleton<IDocumentExecuter, DocumentExecuter>(); 
            services.AddSingleton<IDocumentWriter, DocumentWriter>();
            
            // Necessary to avoid the synchronous IO exception
            services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });

            #region GraphQL
            // Tried this but 'AddGraphQL' wasn't found
            //services.AddGraphQL(x =>
            //{
            //    x.ExposeExceptions = true; //set true only in development mode. make it switchable.
            //})
            //.AddGraphTypes(ServiceLifetime.Scoped);

            services.AddGraphiQl(x =>
            {
                x.GraphiQlPath = "/graphiql-ui";
                x.GraphQlApiPath = "/graphql";
            });
            
            // Changed this in many ways but couldn't fix the error
            services.AddSingleton<IDependencyResolver>(s => new FuncDependencyResolver(type => s.GetRequiredService(type)));
            //services.AddScoped<UnitMeasurement>();
            services.AddTransient<UnitMeasurementRepository>();
            services.AddScoped<UnitMeasurementQuery>();
            services.AddScoped<UnitMeasurementSchema>();
            //services.AddGraphQLHttp();
            //services.AddGraphQLWebSockets<>();
            #endregion

            // this goes in concordance with the below method but it changed nothing
            // foreach (var type in GetGraphQlTypes())
            // {
            //     services.AddScoped(type);
            //  }
            }

       // This didn't solve the problem 
        static IEnumerable<Type> GetGraphQlTypes()
        {
            return typeof(Startup).Assembly
                .GetTypes()
                .Where(x => !x.IsAbstract &&
                            (typeof(IObjectGraphType).IsAssignableFrom(x) ||
                             typeof(IInputObjectGraphType).IsAssignableFrom(x)));
        }


        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // app.UseWebSockets();
            // app.UseGraphQLWebSockets<UnitMeasurementSchema>();
            app.UseGraphQL<UnitMeasurementSchema>(); // I think the problem is here (tried debugging but it didn't reach anywhere)
            app.UseGraphiQl();
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions());

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
```
## Environment

```
<ItemGroup>
    <PackageReference Include="graphiql" Version="2.0.0" />
    <PackageReference Include="GraphQL" Version="2.4.0" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.4.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.4.0" />
  </ItemGroup>
```
To mention that I've already done a research in graphql-dotnet and graphql-dotnet/server, and github too but couldn't find something useful.
I highly appreciate any help as I've being in this for days.

**Comment by sungam3r** [comment]
Try the latest 3.0.0 preview.

**Comment by aldd-dpulidog** [comment]
> Try the latest 3.0.0 preview.

Thanks for your response but how can I use that version if Visual studio shows until v2.4.0?

**Comment by sungam3r** [comment]
Check _include prerelease_ checkbox.

**Comment by aldd-dpulidog** [comment]
It let me install the preview 1175 without errors but everything stills the same, what is the difference with the third version? Or what should I change?

**Comment by sungam3r** [comment]
Add [this](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/NuGet.config#L6) to your package feeds. It allows you to install fresh packages. 1175 is rather old.

**Comment by aldd-dpulidog** [comment]
I'm sorry what is that file? I have no XML in my project folder, it is just Api not Web Application

**Comment by aldd-dpulidog** [comment]
Okay I managed to install the last version but now it can't find the IDependencyResolver, any ideas?

**Comment by sungam3r** [comment]
https://graphql-dotnet.github.io/docs/getting-started/dependency-injection + https://github.com/graphql-dotnet/server/blob/develop/src/Transports.AspNetCore.NewtonsoftJson/GraphQLBuilderExtensions.cs#L27 or https://github.com/graphql-dotnet/server/blob/develop/src/Transports.AspNetCore.SystemTextJson/GraphQLBuilderExtensions.cs#L27 from server project. Serializers are external libs.

**Comment by sungam3r** [comment]
There is no more GraphQL.Http.IDocumentWriter interface, for some reason you use old version of library.

**Comment by aldd-dpulidog** [comment]
Thanks I'll check it ASAP

**Comment by aldd-dpulidog** [comment]
Okay, It finally runs I appreciate your help.

**Comment by aldd-dpulidog** [comment]
Hi @sungam3r as your recommendation I've been developing my API with the GrapQL version 3.0.0-preview-1648.
But this statement referenced [here](https://github.com/graphql-dotnet/examples/blob/529b530d7a6aad878b2757d776282fdc1cdcb595/src/AspNetCore/Example/Startup.cs#L44) is throwing me the following:

![image](https://user-images.githubusercontent.com/64615320/88555178-11bcb500-cfed-11ea-868b-a751aa03c12f.png)
_"IApplicationBuilder does not contain a definition for "UseGraphQL"..."_

I assume there's no 'UseGraphQL' in third version or maybe in the preview I'm using.

**Comment by sungam3r** [comment]
Just check examples in the server project.
