### ISSUE TITLE
Field documentation on InputObjectGraphTypes don't display

### ISSUE THREAD

**Issue by oconnor0** [graphql-dotnet/graphql-dotnet#1738]
## Description

I am using GraphQL.Net 3.0.0-preview-1648. I am attempting to programmatically generate a schema, but the schema printer doesn't display descriptions on fields on an input type.

### Steps to reproduce

1. Create a new project: `dotnet new console -o Input`
2. `cd Input`
3. Add GraphQL dependency: `dotnet add package GraphQL -v 3.0.0-preview-1648`
4. Modify Program.cs to:

```
using System;

namespace App
{
    class Program
    {
        static void Main(string[] args)
        {
            var schema = new GraphQL.Types.Schema();

            var input = new GraphQL.Types.InputObjectGraphType { Name = "Input", Description = "Input Type: Input" };
            schema.RegisterType(input);

            var input_name = new GraphQL.Types.FieldType { Name = "name", ResolvedType = schema.FindType("String"), Description = "Field: Name" };
            input.AddField(input_name);

            var options = new GraphQL.Utilities.SchemaPrinterOptions {
                IncludeDescriptions = true,
                IncludeDeprecationReasons = true,
            };
            var printer = new GraphQL.Utilities.SchemaPrinter(schema, options);
            Console.WriteLine(printer.Print());
        }
    }
}
```

5. Run the program: `dotnet run`
6. Notice in the output the `Input` type's field `name` has no description:

```
# Input Type: Input
input Input {
  name: String
}
```

### Expected result

I expect that setting `Description` on a `FieldType` will show up in the resultant schema whether or not the field is placed on an `InputObjectGraphType` or an `ObjectGraphType`.

### Actual result

I don't see the field description that I would expect. In certain situations I see the field descriptions when I set place those fields on an `ObjectGraphType` but am struggling to reproduce that now.

### Environment

Windows 10.
`dotnet --version` 3.1.301

**Comment by sungam3r** [comment]
I have reproduced the situation and can confirm that this is a bug. Small changes required in `SchemaPrinter but they do require careful indentation. I will try to fix it soon.
