### ISSUE TITLE
How to validate complete input values and get the error list

### ISSUE THREAD

**Issue by rajeshangappan** [graphql-dotnet/graphql-dotnet#1740]
I have one small query. In my input graphtype
 - i have mentioned all the properties are mandatory (nonnullgraphtype).(for ex:  xxx and yyy property is mandatory.)
- while sending the mutation query, i missed 2 properties (xxx and yyy)
- while excite the schema i got errors, in this i received only one error. property xxx is null pass non null property.. 
- once I added the xxx property, i received the next error like yyy property is missing.
- but my case, in single shot i have to receive both errors ( like xxx missing and yyy is missing).
- i need complete input values validation. And should be a list of errors for all property. Validation.

**Comment by sungam3r** [comment]
Maybe related to #1701

**Comment by Shane32** [comment]
Status @sungam3r ?

I believe this still is not possible -- due to the design of the variable validation algorithm, it is not practical to return more than a single error per variable.  However, it will validate all variables and arguments during the validation phase and return as many errors as possible (however, max of one per variable).

**Comment by sungam3r** [comment]
I'm 100% sure that validation rules return as many errors as they find, that is, many. In the initial comment, there is no talk of variables, although in the case of variables, as it is correctly said, most likely one error for each variable. But variable validation is a whole new feature. I suggest to close this issue. At least until the author gives an example to demonstrate the missing validation errors.

**Comment by sungam3r** [comment]
@rajeshangappan We will be happy to get an example.
