### ISSUE TITLE
How to access Field-level arguments in .Net code

### ISSUE THREAD

**Issue by dochoss** [graphql-dotnet/graphql-dotnet#1750]
In the documentation, I see how to access arguments and am doing that successfully.  However, I can't seem to find any guidance on how to access the field-level arguments in code.  For instance, I have the following:

```
public HoldType ()
        {
            Name = "Hold";

            Field(h => h.HoldId, type: typeof(LongGraphType)).Description("Id of the Hold");            
            Field(h => h.Status)
                .Argument<ListGraphType<IntGraphType>>("exclude", "List of status codes to exclude from the result")
                .Description("Current status of the Hold");
        }
```

Then in my Query definition, I have:
```
Field<ListGraphType<HoldType>>(
  "holds",
  arguments: new QueryArguments(
    new QueryArgument<ListGraphType<IntGraphType>> { Name = "exclude", DefaultValue = new int[] { 999 }, Description = "Status codes to exclude from the results" }
  ),
  resolve: context =>
  {
    var exclude = context.GetArgument<int[]>("exclude");  // this works for a parent-level argument - holds(exclude:999)
  });
```

I want to be able to pass in a list of values to exclude from the query on the status field.    So something like...

```
query {
  holds {
    holdId
    status(exclude:999,998,100)
  }
}
```

Am I going about this the right way?  If so, how do I access the values during resolution?  If I need to pass it at parent level, that's fine, but I know GQL supports field-level arguments so I'm wondering if that's possible.

**Comment by sungam3r** [comment]
> Am I going about this the right way?

Yes.

> If so, how do I access the values during resolution?

Use different field overload with custom resolver. Your current solution uses overload with expression which just returns property as is.

**Comment by dochoss** [comment]
Thanks for following up. I'm not sure I really understand what the field-level resolver is doing.  Is it applying the lambda to each record on retrieval?  If so, should I use something like this? 

```
Field(h => h.Status)
  .Resolve(resolver =>
  {
    var exclude = resolver.GetArgument<int[]>("exclude");
    var status = resolver.Source.Status;
                    
    return !exclude.Contains(status) 
      ? resolver.Source.Status 
      : -1;
    })
    .Argument<ListGraphType<IntGraphType>>("exclude", "List of status codes to exclude from the result")
    .Description("Current status of the Hold");
```

If not, how should I accomplish what I'm trying to do?

**Comment by sungam3r** [comment]
Resolver returns object used for subsequent resolution of inner fields in case of non-leaf parent (current) field. Does `Status` property have `List<int>` type?

**Comment by dochoss** [comment]
Status is an int, basically a code for the current status of an item.  `Exclude` will be a list of status codes to exclude from the result set.  

For clarity, here's an example...

Data set:
` ``
{ "holdId": 1, "status": 1 },  
{ "holdId": 2, "status": 5 }, 
{ "holdId": 3, "status": 999 } 
```

GQL query (desired state):
```
query {
  holds {
    holdId
    status(exclude:5,999)
  }
}
```

The query should only return the hold with holdId = 1

**Comment by sungam3r** [comment]
OK. So did you come up with a working solution?

**Comment by dochoss** [comment]
Sorry, computer had a little meltdown and ate part of my comment.  

I'm still not quite clear on how to use the data I get from the field resolver.  When I get the data into my query resolver, will the updated value from the field resolver be used in place of the raw data?

```
query {
  holds {
    holdId
    status(exclude:5,999)
  }
}
```

```
// query resolver
resolve: context => {
  var holds = database.Holds;
  foreach (var hold in holds) 
  {
    // what is the value of hold.Status here if Status == 999?
    // database value or -1? (does the field resolver execute first?)
  }
}
```

**Comment by dochoss** [comment]
I just tested with a breakpoint in the query resolver and in the field resolver.  The field resolver hits after the query, so it's not obvious how I can get an item to be excluded.  I can change the value of `Status` but that doesn't help me since the record is still sent in the output.

**Comment by sungam3r** [comment]
GraphQL yields data level by level from top to bottom. First top, then bottom. Your resolver return some object (or array/list/enumerable) which then will be passed to the next level of resolution process until the process comes to primitive values - scalars. If you want to filter some holds you should do it where you have access to them - in resolver for `holds`, not in resolver for `status` so move `exclude` argument to `holds` field.

**Comment by dochoss** [comment]
Got it.  Thanks for all your assistance.  

I decided to filter just based on my "deleted" status (which is 999), but I could still do an array of numbers to exclude (included code for this in the example below).  

My working solution for anyone who comes later:

```
Field<ListGraphType<HoldType>>(
    "holds",
    arguments: new QueryArguments(
        new QueryArgument<BooleanGraphType> { Name = "includeDeleted", DefaultValue = false, Description = "Include holds marked for deletion" }
/*
 OR
      new QueryArgument<ListGraphType<IntGraphType>> { Name = "statusesToExclude", DefaultValue = 999, Description = "Exclude all these status codes"
*/
    ),
    resolve: context =>
    {
        var includeDeleted = context.GetArgument<bool>("includeDeleted");

        var holds = db.Holds
        .AsNoTracking()
        .Where(h => h.Status != (includeDeleted ? -999 : 999))
        .Select(h => new ExtHold().FromHold(h))
        .ToList();

        AddHoldItemCounts(db, holds);

        return holds;
    });
```
