### ISSUE TITLE
Error when calling buildClientSchema with introspection query result

### ISSUE THREAD

**Issue by bdangh** [graphql-dotnet/graphql-dotnet#176]
I'm trying to generate .graphql file with javascript, based on result of introspection query, and I receive error when trying to call buildClientSchema.

Error is following:

> { [GraphQLError: Syntax Error GraphQL (1:4) Expected <EOF>, found Name "longer"
> 
> 1: No longer supported
>       ^
> ]
>   message: 'Syntax Error GraphQL (1:4) Expected <EOF>, found Name "longer"\n\n1: No longer supported\n      ^\n',
>   locations: [ { line: 1, column: 4 } ],
>   path: undefined }

Problem with default value in the following part of the schema. I have tried value without spaces ("Nolongersupported" or any other value without spaces) and it works.
```javascript
        {
          "name": "deprecated",
          "description": "Marks an element of a GraphQL schema as no longer supported.",
          "locations": [
            "FIELD_DEFINITION",
            "ENUM_VALUE"
          ],
          "args": [
            {
              "name": "reason",
              "description": "Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formatted in [Markdown](https://daringfireball.net/projects/markdown/).",
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "Boolean",
                  "ofType": null
                }
              },
              "defaultValue": "No longer supported"
            }
          ]
        }
```

**Comment by joemcbride** [comment]
Is that on the `GraphQLDeprecatedDirective`?  Can you list what version of `graphql-js` you are using?  That was added to mirror the following in the JS project, though it does seem to have an issue.  Either I did it wrong or something else is up.

https://github.com/graphql/graphql-js/blob/549a2fd1c3cb8acccb4dd0f82eb8e70b2b23346e/src/type/directives.js#L143-L169

**Comment by bdangh** [comment]
Yes, it is GraphQLDeprecatedDirective, and I use 0.7.0 version.

Can it be because of type: GraphQLString?

I've found another schema.json where it looks like this.
```javascript
        {
          "name": "deprecated",
          "description": "Marks an element of a GraphQL schema as no longer supported.",
          "locations": [
            "FIELD_DEFINITION",
            "ENUM_VALUE"
          ],
          "args": [
            {
              "name": "reason",
              "description": "Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formattedin [Markdown](https://daringfireball.net/projects/markdown/).",
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": "\"No longer supported\""
            }
          ]
        }
```

**Comment by joemcbride** [comment]
👍  Makes sense, that is probably the bug.

**Comment by joemcbride** [comment]
Just to clarify for my future self, I added the `reason` argument on `GraphQLDeprecatedDirective ` as a `BooleanGraphType` instead of a `StringGraphType`.

**Comment by joemcbride** [comment]
Crazily enough, that seemingly innocuous change led to a whole slew of changes that were needed to fix the behavior.  Think I got them all squashed though.

**Comment by bdangh** [comment]
👍 Thanks, Awesome! Keep up the good work!
