### ISSUE TITLE
Query Organisation Example not working - GraphQL.Validation.ValidationError: Cannot query field X on type Y

### ISSUE THREAD

**Issue by markmcgookin** [graphql-dotnet/graphql-dotnet#1761]
## Summary
My root objects are already starting to get a bit big for my liking, so I am trying to use [this](https://graphql-dotnet.github.io/docs/getting-started/query-organization/) example (which states that you can resolve an empty object in the root class, as long as the type points to your 'grouped' object that will contain the appropriate fields, allowing you to separate out the 'resolve' portion of your code from your root query object) from the documentation to do some query organisation. But when I try to run a query I get an error

`"message": "GraphQL.Validation.ValidationError: Cannot query field \"<any field I query>\" on type \"<any object>\".",`

## Relevant information

I have taken one of the fields in my query and organised it like the example stated, returning a blank object:

```
public Query(DatabaseContext database)
{
    Name = "Query";
    Field<OrganisationGroupGraphType>("organisations", resolve: context => new {});
    ....
```

Then I have another class with the code I used to have in there (of the type the above field is cast to)

```
public class OrganisationGroupGraphType : ObjectGraphType
{
    public OrganisationGroupGraphType(DatabaseContext database)
    {
        Name = "Organisation";
        Field<ListGraphType<OrganisationType>>(
               "organisations",
               resolve: context =>
               {
                   return database.Organisations();
               }
           ).AuthorizeWith(Constants.GraphQL.Policies.ACCESS);
           .....
```

But I get the "Cannot query field X on type Y" when I try to run it (as if it's just returning the empty object..) I can't see if there is a step I am missing, but that sort of makes sense to me, I can't quite figure out how this is trying the resolve empty object to get the type with the actual query resolution code in it (other than the Type you state that the field is)

**Running:** Dotnet Core 3.1
**OS:** macOS
**Packages:**
```
<PackageReference Include="GraphQL" Version="2.4.0" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.4.0" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="3.4.0" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.4.0" />
<PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="3.4.0" />
```

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet#installation

**Comment by markmcgookin** [comment]
> https://github.com/graphql-dotnet/graphql-dotnet#installation

Thanks, I've upgraded my packages to the following (including the required changes for serialisation etc) and still get the same error.

```
<PackageReference Include="GraphQL" Version="3.0.0-preview-1490" />
<PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1490" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="3.5.0-alpha0046" />
```

**Comment by BenjaBobs** [comment]
It seems you are still fetching packages from NuGet. Those packages are old. The newest versions can be found on MyGet.

![image](https://user-images.githubusercontent.com/8708965/89405045-3adef300-d71b-11ea-9804-91b0b15c044e.png)

Related issues:
#1321
#1664
#1228

**Comment by markmcgookin** [comment]
Is there any evidence that this is an issue that has been addressed in the bleeding edge version? I have now upgraded to the latest MyGet version and am _still_ getting the same error.

```
<PackageReference Include="GraphQL" Version="3.0.0-preview-1675" />
<PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1675" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0072" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="3.5.0-alpha0072" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="3.5.0-alpha0072" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.5.0-alpha0072" />
<PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="3.5.0-alpha0072" />
```

**Comment by BenjaBobs** [comment]
Hmm. I must admit I only commented on the versions. After closer inspecting the issue I'm not sure the version change will make a difference, I think the issue stems from the data structures.
My next step would be to use GraphQL Playground to inspect the generated schema to see if that sheds some light on the issue.

**Comment by markmcgookin** [comment]
> Hmm. I must admit I only commented on the versions. After closer inspecting the issue I'm not sure the version change will make a difference, I think the issue stems from the data structures.
> My next step would be to use GraphQL Playground to inspect the generated schema to see if that sheds some light on the issue.

Right... that was really all I needed. It looks like doing it like this 'nests' your query result a layer below where it was previously. I don't really want/need to be using such bleeding edge alpha release stuff in my code so I will probably roll that back.

I used the 'question' template to raise this issue, I was just after some advice.

```
# Write your query or mutation here
query OrganisationsInfo {
  organisations {
    organisations {
```

**Comment by BenjaBobs** [comment]
Glad you were able to solve the issue. 👍

**Comment by markmcgookin** [comment]
> Glad you were able to solve the issue. 👍

I'll create a PR for the documentation to make it a bit clearer that if you use query optimisation you will need to add another 'layer' to your query json
