### ISSUE TITLE
Exception types and codes need to be updated throughout project

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1768]
I would like to propose that the exception types and codes be reviewed throughout the project.  Below is a table of what revisions are proposed.

## Exceptions occurring during schema construction

These will not change, and consist of exceptions such as `ArgumentNullException`, `ArgumentOutOfRangeException`, and so forth.  An exception of type `ExecutionError` will not be thrown.

## Exceptions occurring prior to document execution

These exceptions are not wrapped into an `ExecutionResult`, but are thrown directly from `DocumentExecuter.ExecuteAsync` to its caller.

Description | Exception
-|-
options == null | ArgumentNullException
options.Schema == null | InvalidOperationException
options.FieldMiddleware == null | InvalidOperationException
options.Query == null | InvalidOperationException

## Validation errors

All validation errors return an exception of type ValidationError.

Rule | Code now | New code
-|-|-
ArgumentsOfCorrectType | 5.3.3.1 | 5.6.1
DefaultValuesOfCorrectType | 5.7.2 | 5.6.1
FieldsOnCorrectType | 5.2.1 | 5.3.1
FragmentsOnCompositeTypes | 5.4.1.3 | 5.5.1.3
KnownArgumentNames | 5.3.1 | 5.4.1
KnownDirectives | 5.6.1 | 5.7.1
KnownFragmentNames | 5.4.2.1 | 5.5.1.4
KnownTypeNames | 5.4.1.2 | 5.5.1.2
LoneAnonymousOperation | 5.1.2.1 | 5.2.2.1
NoFragmentCycles | 5.4 | 5.5.2.2
NoUndefinedVariables | 5.7.4 | 5.8.3
NoUnusedFragments |  5.4.1.4 | 5.5.1.4
NoUnusedVariables | 5.7.5 | 5.8.4
OverlappingFieldsCanBeMerged | 5.3.2 | 5.3.2
PossibleFragmentSpreads | 5.4.2.3 | 5.5.2.3
ProvidedNonNullArguments | 5.3.3.2 | 5.4.2.1
ScalarLeafs | 5.2.3 | 5.3.3
SingleRootFieldSubscriptions | 5.2.3.1 | 5.2.3.1
UniqueArgumentNames | 5.3.2 | 5.4.2
UniqueDirectivesPerLocation | 5.6.3 | 5.7.3
UniqueFragmentNames | 5.4.1.1 | 5.5.1.1
UniqueInputFieldNames | 5.5.1 | 5.6.3
UniqueOperationNames | 5.1.1.1 | 5.2.1.1
UniqueVariableNames | 5.7.1 | 5.8.1
VariablesAreInputTypes | 5.7.3 | 5.8.2
VariablesInAllowedPosition | 5.7.6 | 5.8.5

## Miscellaneous exceptions

Description | Exception | Code
-|-|-
options.Query == "" | NoOperationError | NO_OPERATION
options.OperationName is invalid | InvalidOperationException |
schema.Mutation == null | InvalidOperationError | INVALID_OPERATION
(query parsing error) | SyntaxError | SYNTAX_ERROR
(variable deserialization error) | InvalidVariableError | INVALID_VALUE
(unhandled error; rare) | UnhandledError | (dynamic)

## Exceptions occurring during document execution

Any errors below that are not of type `ExecutionError` get wrapped and returned to the caller unless intercepted by the `UnhandledExceptionDelegate`.  Since all errors here are due to programming errors, and not an invalid query, they should not be of type `ExecutionError` so that they can be intercepted and logged without exposing internals to callers.

Description | Exception
-|-
executionStrategy == null | InvalidOperationException
GetArgument of incompatible type | InvalidOperationException
GetArgument with failed conversion | OverflowException (or similar)
resolver returns null for non-null | InvalidOperationException
resolver returns invalid type | OverflowException (or similar)
resolver serialization returns null | InvalidOperationException
(unhandled errors, include those listed above) | wrapped in UnhandledError

## Inheritance tree

* Exception
  * ExecutionError
    * DocumentError
      * ValidationError
      * InvalidVariableError
      * SyntaxError
      * NoOperationError
      * InvalidOperationError
    * UnhandledError

#### Validation codes

Should the validation errors' code consist of only the validation error number?  This is subject to change every time the GraphQL spec is updated.  Perhaps it should be "VALIDATION_ERROR".  Perhaps `codes` should return both "VALIDATION_ERROR" and also the code.  Let's say it is changed to "VALIDATION_ERROR", and "INVALID_VALUE" stays the same.  Then the codes returned from DocumentExecuter will only ever be one of the following five errors:

* SYNTAX_ERROR
* NO_OPERATION
* INVALID_VALUE
* VALIDATION_ERROR
* INVALID_OPERATION

Or a custom response from a field resolver, of course.  I'm not sure that it would be a distinct benefit, however, since those errors should never occur from well-constructed clients either.  They are really only useful during debugging or manual querying of data.

#### Application Errors

Should we add a stub class for user defined errors - e.g. ApplicationError?  It would inherit from ExecutionError.

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/89790465-a44f6f00-db2a-11ea-9103-04ac55dcf97c.png)

```c#
 private void ValidateOptions(ExecutionOptions options)
        {
            if (options.Schema == null)
            {
                throw new ExecutionError("A schema is required.");
            }

            if (string.IsNullOrWhiteSpace(options.Query))
            {
                throw new ExecutionError("A query is required."); <---
            }
        }
```

**Comment by sungam3r** [comment]
This is a serious big topic. Some time ago, I also began to organize the error codes and bring them in line with those from the specification. But I didn't have time to finish this. I will come back to this issue from time to time to comment.

**Comment by Shane32** [comment]
> ![изображение](https://user-images.githubusercontent.com/21261007/89790465-a44f6f00-db2a-11ea-9103-04ac55dcf97c.png)

It is ignored at that time, and only checked after `try {`.  That is why I also listed it under "Miscellaneous exceptions", where it shows it is returning an `ExecutionError`. I think that particular check should be moved, as it should never be null.  If it is an empty string, it would be a query syntax error, but if it's null, that's different.

**Comment by sungam3r** [comment]
OK. I suggest that you keep more detailed descriptions in the table. It is also probably worth adding another checkbox column to mark the cases that we have already discussed. There are a lot of cases, I'll just forget what I have already watched. It will take a long time, I'm sure.

**Comment by sungam3r** [comment]
> And, changing these numbers could be a breaking change for clients if they are relying on the code in their front-end.

Changing these numbers is a natural process I think.

> I'd suggest that we replace all validation error codes with a simple VALIDATION_ERROR code. Or perhaps it returns VALIDATION_ERROR in code and both that and the number in codes like this: ["VALIDATION_ERROR", "5.2.3.1"].

This thought is not very good for me. I suggest using rule name as `code` property and paragraph number from the specification as `number`:
```json
{
  "extensions": {
    "code": "NO_UNUSED_FRAGMENTS",  # from NoUnusedFragments.cs
    "number": "5.4.1.4"
  }
}
```

Then the code should not change when adding new rules, though the numbering can change. It will be a backward incompatible change, although the renumbering will be a backward incompatible change anyway, so we don't have much to lose.

> I can also write individual classes for each type of validation error so that code within IErrorInfoProvider can return a customized result for each type of validation error. I would think this would be a good idea, regardless of our decision above, but it does create a bunch more classes (even if they only do contain a couple lines of code each).

This will allow to catch specific errors. You can try it, but I'm not sure if it's worth it. This can be done later. The main job is renumbering.
