### ISSUE TITLE
.net core 3.1 full example

### ISSUE THREAD

**Issue by fenomeno83** [graphql-dotnet/graphql-dotnet#1771]
Hi.
I've created a full graphql implementation in .net core 3.1.
It has some important features.

See here:
https://github.com/fenomeno83/graphql-dotnet-globalization-demo

**Comment by sungam3r** [comment]
Do you want to add / improve something in this repository?

**Comment by fenomeno83** [comment]
In my opinion is complete

**Comment by sungam3r** [comment]
Sorry but I don't understand you. PRs are welcome.

**Comment by fenomeno83** [comment]
@sungam3r 
Sorry for my missunderstanding.

In my opinion, a very useful part is this library written by me that creates a sort of "code first" approach.
You can define your dtos and then register graphtypes (input or output) using a line code 

Here library (maybe can be written better, but it save a lot of time, because you don't need to write a field per each dto class property)
https://github.com/fenomeno83/graphql-dotnet-auto-types

A similar approach exists by default  in hot chocolate library.

Instead on this post I've shown a mine project with a .net core 3.1 that uses graphql.
Maybe could be linked as example project in your project main guide.
Thanks

**Comment by sungam3r** [comment]
After a quick look at https://github.com/fenomeno83/graphql-dotnet-auto-types I found this code rather fragile, error prone and limited in use. I cannot recommend it for use, sorry. Closing this.
