### ISSUE TITLE
[Question] Is it possible to have an input type of Object.

### ISSUE THREAD

**Issue by markmcgookin** [graphql-dotnet/graphql-dotnet#1780]
## What I mean
We have tried to come up with a solution that will allow us to update properties on any object in our schema without having to write a mutation for each one. 

We have a dynamic input type, which contains a dictionary of string - object to update the properties provided. 

If this dictionary is string - string it works fine, but if I change the value to object type, it barfs. I am not sure what type to declare the field Value in the DynamicInputPropertyTyper object. I will handle parsing it out in my own code, I just need to be able to retrieve it as an object from the input. This just allows us to provide a string, int, bool, datetime etc...

The input type looks a bit like this:

```csharp
public class DynamicInput
{
    public Guid Id { get; set; }
    public string Type { get; set; }
    public Guid? DepartmentId { get; set; }
    public List<DynamicInputProperty> Properties { get; set; }
}

public class DynamicInputProperty
{
    public string Key { get; set; }
    public object Value { get; set; }
}

public class DynamicInputPropertyType : InputObjectGraphType<DynamicInputProperty>
{
    public DynamicInputPropertyType()
    {
        Description = "DynamicInputPropertyType";
        Field(x => x.Key);
        Field(x => x.Value, type: typeof(InputObjectGraphType<object>)); //Not sure if this is possible
    }
}
```

Pretty much using the latest versions of everything

```
<PackageReference Include="GraphQL" Version="3.0.0-preview-1675" />
<PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1675" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0072" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="3.5.0-alpha0072" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="3.5.0-alpha0072" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.5.0-alpha0072" />
<PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="3.5.0-alpha0072" />
```

**Comment by sungam3r** [comment]
> If this dictionary is string - string it works fine, but if I change the value to object type, it barfs.

What error do you see? I don't think you can achieve what you want with `InputObjectGraphType<object>`. Schema should declare all fields of your input type. `InputObjectGraphType<object>` has no fields. It is just like dummy.

**Comment by markmcgookin** [comment]
> What error do you see? I don't think you can achieve what you want with `InputObjectGraphType<object>`. Schema should declare all fields of your input type. `InputObjectGraphType<object>` has no fields. It is just like dummy.

If I don't explicitly define a type I get 

`An exception of type 'System.ArgumentException' occurred in GraphQL.dll but was not handled in user code: 'The GraphQL type for Field: 'Value' on parent type: 'DynamicInputPropertyType' could not be derived implicitly. '`

Is there any way of having a generic object as an input type? It would allow us to pass in whatever we want, then handle the casting in the update itself. I am aware this isn't exactly standard graphql but was hoping we could make it work. I suppose the only other option is to replace the whole input type with a string, and have clients serialize as json the object before posting. I would much rather be able to use some form of dynamic input type though.

**Comment by sungam3r** [comment]
It is likely you get this error from `IServiceProvider` which does not know how to create `InputObjectGraphType<T>`. How do you configure you DI?

**Comment by BenjaBobs** [comment]
If I were you I'd write an `EntityInputObjectGraphType<TEntity>` and then an `InputObjectGraphType` with a field for each entity. That way you can still have only a single mutation, all that changes is the variables you send to that mutation. The variables will have a complex and large type though, but you'll have type safety.

**Comment by Shane32** [comment]
I've not tried this, but might it be possible to have a scalar graph type with custom deserializer, which for variables can accept an object?  It wouldn't work for literals of course; it would have to be a variable.  Might have to skip a validation step to make it work, but my gut says it's possible, even if it doesn't quite meet spec.

As you already mentioned, another idea would be to simply accept a string, which you can intrepret as json.

Unfortunately unions are not valid as input types, so it's not really possible to define a mutation which accepts one of multiple graphql types.

**Comment by BenjaBobs** [comment]
> Unfortunately unions are not valid as input types, so it's not really possible to define a mutation which accepts one of multiple graphql types.

But you can accomplish a similar result without unions by having a field for each graphql type and having them be nullable.
The schema type would look like this:
```graphql
type CrazilyComplexMutationType {
	person: PersonMutationType
	house: HouseMutationType
	# and so on...
}
```

And be used like this:
```graphql
mutation {
	doAnything(change: {
		person: {
			id: 1234
			name: 'John Doe'
		}
	}) {
		id
	}
}
```

```graphql
mutation {
	doAnything(change: {
		house: {
			id: 16
			address: 'Road Street 5'
		}
	})
}
```

You can then make a variable to keep the request the same.
```graphql
mutation Generic($input: CrazilyComplexMutationType!) {
	doAnything(change: $input) {
		id
	}
}
```

All this being said though, I think this goes against the idea of GraphQL.

**Comment by sungam3r** [comment]
> All this being said though, I think this goes against the idea of GraphQL.

https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md

**Comment by markmcgookin** [comment]
Having read through the inputUnion.md @sungam3r referenced above, we are going to go with a string-string dictionary approach, and have a type converter class which will know the propertyinfo of the property to set using reflection, then attempt to convert the value to the appropriate type. 

We were going to go down a route of a T4 transform of our model class to produce partials for all our objects and create mutations for each of them, but then we still run into the well discussed partial update issues anyway, and as some of our objects have close to 300 properties, we decided to reduce the DTO size and go for something a bit smaller that we will be able to use for most objects. This way we have one "dynamic mutation" for updates, which will reduce the code base.

The rough outline of the dynamic update resolver that I'm going to use is as follows:

```
var genericTypeString = $"<our_namespace>.model.{input.Type}";
var genericType = Type.GetType(genericTypeString);

//Make sure that they have passed us a basic database object that we know
if (!typeof(BaseDBObject).IsAssignableFrom(genericType))
{
    //TODO ERROR
}

//Find the property the user is trying to set, cast it as is appropriate
var dataset = Database.ResolveCollection(genericType);
var entity = (dataset as IQueryable<BaseIdBasedDBObject>).FirstOrDefault(x => x.Id == input.Id);

if (entity == null)
{
    //TODO error
}

var itemAsType = Convert.ChangeType(entity, genericType);
foreach (var p in input.Properties)
{
    var prop = genericType.GetProperties().FirstOrDefault(x => x.Name == p.Key);
    if (prop != null)
    {
        prop.SetValue(itemAsType, TypeConverter.ConvertValueToPropertyType(prop, p.Value)); 
    }
}

Database.Update(itemAsType as BaseIdBasedDBObject);
var count = await Database.SaveChangesAsync();

return itemAsType;
```
