### ISSUE TITLE
3.0.0-preview-1352 only working version

### ISSUE THREAD

**Issue by dehlers1000** [graphql-dotnet/graphql-dotnet#1783]
The highest preview version I can get working (or ever seen working) is version 3.0.0-preview-1352. If I upgrade from the following version to latest version 1719, the code throws an error:

Unable to resolve service for type 'GraphQL.Server.Transports.AspNetCore.Common.IGraphQLRequestDeserializer' while attempting to activate 'GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1[VisionAPIGraphQL.GraphQL.GRaphQLSchema.CaseDataSchema]'.

source: Microsoft.AspNetCore.Http.Abstractions

Here are the packages I have working. My whole project is working perfectly.

    <PackageReference Include="GraphQL" Version="3.0.0-preview-1352" />
    <PackageReference Include="GraphQL.Authorization" Version="2.1.29" />
    <PackageReference Include="GraphQL.Server" Version="1.7.0.1" />
    <PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="3.5.0-alpha0020" />
    <PackageReference Include="GraphQL.Server.Core" Version="3.5.0-alpha0027" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0027" />
    <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="3.5.0-alpha0046" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="3.1.5" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.9.2" />

Here are the packages that cause the error. Basically all of the latest packages. 3.0.0-preview-1719 appears to be the breaking change.

    <PackageReference Include="GraphQL" Version="3.0.0-preview-1719" />
    <PackageReference Include="GraphQL-Parser" Version="5.3.0" />
    <PackageReference Include="GraphQL.Authorization" Version="3.0.40-preview-40" />
    <PackageReference Include="GraphQL.Server" Version="1.7.0.1" />
    <PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="3.5.0-alpha0073" />
    <PackageReference Include="GraphQL.Server.Core" Version="3.5.0-alpha0073" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0073" />
    <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="3.5.0-alpha0073" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1719" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="3.1.5" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.9.2" />

services.AddScoped<CaseDataSchema>();
            services.AddGraphQL(o => { o.ExposeExceptions = false; })
                .AddGraphTypes(ServiceLifetime.Scoped)
                .AddDataLoader();

app.UseGraphQL<CaseDataSchema>(path: "/graphql");

Is this a bug or is there a setting to fix the issue?

**Comment by sungam3r** [comment]
Please read [readme](https://github.com/graphql-dotnet/server#getting-started) carefully.
![изображение](https://user-images.githubusercontent.com/21261007/90455823-c1bea300-e0ff-11ea-882a-c038b4da5608.png)

**Comment by dehlers1000** [comment]
Thank you! The link that you included, provided me with the missing code I needed.

The following lines made the difference. Everything is working perfect now. 👍 

   services.AddGraphQL(o => { o.ExposeExceptions = false; })
                .AddSystemTextJson(deserializerSettings => { }, serializerSettings => { }) // For .NET Core 3+;
                .AddGraphTypes(typeof(CaseDataSchema));
