### ISSUE TITLE
Authorization for login and other queries 

### ISSUE THREAD

**Issue by ooo2003003v2** [graphql-dotnet/graphql-dotnet#1788]
Hello there. 
I came across a problem that I applied a jwt authorization in Startup.cs for my graphql api. However the api required login to use other queries (get data list, logout etc). 
So my question is what should I do to by pass the authorization for login query?

**Comment by markmcgookin** [comment]
If you include the package:
`GraphQL.Server.Authorization.AspNetCore`

You can add authorization to your mutations/queries etc easily by adding a policy to your startup with this:

```
 services.AddTransient<IValidationRule, AuthorizationValidationRule>()
                .AddAuthorization(options => 
                { 
                    options.AddPolicy(Constants.GraphQL.Policies.API_ACCESS, p => p.RequireAuthenticatedUser()
                                                                                    .RequireClaim("graphqlaccess", "true"));
                });
```

then when you declare a mutation/query you just add this to the end of the Field definition.

`.AuthorizeWith("graphqlaccess");`

**Comment by sungam3r** [comment]
Also see this https://github.com/graphql-dotnet/server/tree/develop/src/Authorization.AspNetCore
