### ISSUE TITLE
Nuget prerelease packages - request to update GraphQL-Parser #5.3.0

### ISSUE THREAD

**Issue by rbrodieari** [graphql-dotnet/graphql-dotnet#1792]
Could I ask for this updated package to be published to Nuget?

GraphQL-Parser 5.3.0

I am trying to upgrade GraphQL to 3.0.0-preview-1719 but I run into this error.  It looks like the parser package is a dependency and needs that latest version.

Error	NU1605	Detected package downgrade: GraphQL-Parser from 5.3.0 to 5.2.0. Reference the package directly from the project to select a different version. 
 OurProjectName -> GraphQL 3.0.0-preview-1719 -> GraphQL-Parser (>= 5.3.0) 
 OurProjectName -> GraphQL-Parser (>= 5.2.0)	OurProjectName	C:\OurProjectName.csproj	

I see the request to update Nuget for GraphQL 1719 here:
https://github.com/graphql-dotnet/graphql-dotnet/issues/1719

I would like this because our devops team cannot do a build from different Nuget source.

Thank you!

**Comment by sungam3r** [comment]
My bad 🤦 , I forgot about it. Done https://www.nuget.org/packages/GraphQL-Parser/5.3.0

**Comment by rbrodieari** [comment]
Thank you!
