### ISSUE TITLE
Different schema per client credential?

### ISSUE THREAD

**Issue by dorlandode** [graphql-dotnet/graphql-dotnet#1804]
Is there a way to easily swap the schema definition per calling client?  I want to identify who is calling the api by client credentials and change the schema depending on who is calling or who is authenticated.  The idea being that one client may be able to see a field by policy, while another client may not be authorized to see the same field.  Basically a way to add the equivalent of column based authorization.  Different clients could have different authorization to fields on the same objects.  The objects would not be structurally different in code only what is transmitted over the wire as defined by the graph schema.

I could inspect headers in the resolve method of the graph queries to determine the client and then use reflection to dynamically set the fields, but I would prefer to populate the objects and have the graph schema do the stripping of the data that is not authorized.

Ideally the schema would be accurately reflected in playground as well, as the schema would be determined by the headers when the playground page loads.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
