### ISSUE TITLE
Is it possible to not wrap response int a 'data' field?

### ISSUE THREAD

**Issue by koppa96** [graphql-dotnet/graphql-dotnet#1815]
Hi,

Whenever I execute a query like this:
```graphql
{
  users {
    id
    username
  }
}
```
The response is formatted like this:
```json
{
  "data": {
    "users": [
      {
        "id": 1,
        "username": "test"
      }
    ]
  }
}
```

Is it possible to receive the response without the "data" property like this?
(I am using a library that uses graphql but doesn't process the endpoint's response and I'm guessing that this might be the cause)
```json
{
  "users": [
    {
      "id": 1,
      "username": "test"
    }
  ]
}
```

**Comment by BenjaBobs** [comment]
It wouldn't follow the graphql spec then. I would suggest tackling this issue at the client library instead.

**Comment by koppa96** [comment]
Thank you, I'll try to do that.
