### ISSUE TITLE
Add minimum 1 field requirement to query argument of InputObjectGraphType

### ISSUE THREAD

**Issue by ovidiubuligan** [graphql-dotnet/graphql-dotnet#1817]
Hello ,

I have a complex input object graph type  as a query argument field. For example :
```
    myEntity(
      first:10000 
      filter:  { 
        year: {_gt:2000}
      }
    ){
```
If you add the filter argument , then you should add at least 1 entry/column  in the filter. So it can be caught at developer's qraphiQl.

Can this error be raised at graphiQL user typing like nullable types ? (I am guessing it cannot be done )
Can this be done at runtime? If it is done at runtime should I use validation rules or throw Argument exceptions whenever I see a missing expected value?

**Comment by sungam3r** [comment]
> Can this be done at runtime?

Yes.

> should I use validation rules or throw Argument exceptions whenever I see a missing expected value?

You can use both.

**Comment by sungam3r** [comment]
@ovidiubuligan if you were able to solve the problem then please close this issue.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
