### ISSUE TITLE
Schema Processing doesn't handle GQL String-Literal Descriptions

### ISSUE THREAD

**Issue by darthtrevino** [graphql-dotnet/graphql-dotnet#1819]
## Description

A part of the latest GraphQL Specification is string literal descriptions on schema elements. This is meant to aid developers grok a schema when using interactive tools (http://spec.graphql.org/June2018/#sec-Descriptions).

When processing a gql schema using `Schema.For(readSchemaGqlFile())`, the library throws an error on description fields. 

### Steps to reproduce

Use a description field in a GQL file

```gql
Query {
   """
   get the things
   """ 
   things: [Thing!]!
}
```

### Expected result

The descriptions should not cause the schema read to throw an exception.

### Actual result

An exception is thrown

### Environment

Windows 10, Azure Functions,  

<PackageReference Include="GraphQL" Version="3.0.0-preview-1719" />
<PackageReference Include="GraphQL.Conventions" Version="2.5.4" />
<PackageReference Include="GraphQL.Server.Core" Version="3.5.0-alpha0073" />
<PackageReference Include="GraphQL.NewtonsoftJson" Version="3.0.0-preview-1719" />

**Comment by sungam3r** [comment]
See https://github.com/graphql-dotnet/parser/issues/33

**Comment by darthtrevino** [comment]
Gotcha, thanks

**Comment by darthtrevino** [comment]
Feel free to close as dupe

**Comment by Shane32** [comment]
Duplicate of #1640
