### ISSUE TITLE
Introspection of input types

### ISSUE THREAD

**Issue by holm0563** [graphql-dotnet/graphql-dotnet#183]
First of all thanks everyone for the great work. The schema generator is able to pass all of its tests except for 1. There was several issues before so the new 0.12.0-alpha-538 build is looking great.

Still having one issue with a query like:

```
__type(name:""Input_SetRequest""){
                        name
}
```

This will return null even though the input type is in the schema. The quick fix is to modify _Type.cs as
https://github.com/holm0563/graphql-dotnet/commit/2258a6c4eaf99a7031d8d1eded735f4aa17a5bde

but it seems like the better solution would be to update InputObjectGraphType to adhere to the IObjectGraphType. This seems like it would need some work because truly it only needs the IsTypeOf method and not the IComplexGraphType, IImplementInterfaces?? It could be worth breaking these up and 	following more the interface segregation principle?

Any suggestions?

**Comment by joemcbride** [comment]
The way it currently works follows the reference implementation.  https://github.com/graphql/graphql-js/blob/master/src/type/introspection.js#L241-L253

You need to use `inputFields` to get info about input objects.

https://github.com/graphql/graphql-js/blob/master/src/type/introspection.js#L287-L294

`InputObjectGraphType` should not need `IsTypeOf` since it should not be used as a return type.

**Comment by holm0563** [comment]
Thanks that helped. I think i did find a bug but I'm not positive on the solution. See:

https://github.com/graphql-dotnet/graphql-dotnet/compare/master...holm0563:introspectionBug?expand=1

The issue lies with the __Type.cs checking two interfaces that then aren't being used. This prevents an inputobject from correctly displaying its fields.

**Comment by joemcbride** [comment]
You can't use `fields` to query the fields for an input object.  You have to use `inputFields`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Introspection/__Type.cs#L109-L113

```diff
{__type(name:""InputExample""){
    name
    kind
-    fields{
+    inputFields{
        name
        type{
            kind
            ofType{
                kind
            }
        }
    }
}}
```

**Comment by joemcbride** [comment]
That then returns a list of `__InputValue`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Introspection/__InputValue.cs

**Comment by joemcbride** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Introspection/SchemaIntrospection.cs

That file contains an example using fragments and such for introspection.

**Comment by holm0563** [comment]
Thanks so much @joemcbride. I was getting some weird issues with graphiql and introspection but I think I've found them now. I have the Schema generator fully working with this included as a nuget package and will work towards getting it setup as a nuget package of its own.

**Comment by joemcbride** [comment]
Awesome!  Going to close this.
