### ISSUE TITLE
EnumerationGraphType no longer supports mapping Enums of different names 3.0.0-preview-1719

### ISSUE THREAD

**Issue by asgerl** [graphql-dotnet/graphql-dotnet#1832]
Hey. 

I have encountered a change in behavior from 3.0.0-preview-1648 to 3.0.0-preview-1719 which I am not sure is intentional or whether it is a bug.

I could not find a similar issue - likely because 3.0.0-preview-1719 was released recently. 

## Summary

**3.0.0-preview-1648 behavior:**

FYI: This is not a real life example, it is just an example which boils down what the change in behavior is.

In 3.0.0-preview-1648 if I create an enum.

```
public enum IsSet
{
      NotSet = 0,
      Set = 1
}
```

I could then define a EnumerationGraphType like so.

```
public class AssignmentStateEnumType  : EnumerationGraphType {
    public AssignmentStateEnumType()
    {
      Name = "AssignmentState";
      Description = "State of assignment";

      AddValue(name: "NotAssigned", description: "There is no assignment", value: 0);
      AddValue(name: "Assigned", description: "There is an assignment", value: 1);
    }
}
```

Finally I could define the GraphQL field as such.

```
Field<AssignmentStateEnumType>("assignmentState", "State of assignment field", resolve: context => context.Source.IsSet);
```

The above assume that context.Source.IsSet is an instance of the IsSet enum. This field would resolve successfully, e.g. if the instance of IsSet has the value NotSet then my GraphQL API would return NotAssigned - since NotSet and NotAssigned both have the value 0.

To clarify, it was possible to map a C# enum to a EnumerationGraphType even if its values has different names.

**3.0.0-preview-1719 behavior:**

The above no longer resolves successfully, instead I get the following exception: _GraphQL.ExecutionError: Unable to serialize 'NotSet' to 'AssignmentState'_

I can work around this error by renaming 'NotSet' on the enum to 'NotAssigned' or vise versa. However I use GraphQL as a public API while my Enums are internal part of my server code - so for abstraction purposes I liked having the option to output GraphQL enums with different names.

**Question:**
Is this an intentional change? If so what was the reason behind changing the behavior?

## Relevant information

**Own investigation:**

I found [this pull request](https://github.com/graphql-dotnet/graphql-dotnet/pull/1701) for 3.0.0-preview-1719 which changes the behavior of ScalarGraphType from which EnumerationGraphType inherits from. Maybe these changes to ScalarGraphType was not meant to affect EnumerationGraphType like it did?

If it helps: here [is a permalink](https://github.com/graphql-dotnet/graphql-dotnet/blob/c957ffe8d7c630fc5abd3c1ca66e4a1333f8d152/src/GraphQL/Execution/ExecutionStrategy.cs#L124) to the newly added code with the new exception I get.

**Comment by Shane32** [comment]
The behavior change you noticed was not specifically intentional.  However, we did tighten type checking in the 3.0 release as compared to previously.  Since C# does not equate a enumeration member to its value (for instance, `IsSet.Set` does not equal the number `1`), it may cause problems with code that worked in older versions of the library.  The good news is that the fix is very easy: simply use the enumeration member as the value parameter to `AddValue` like this:

```csharp
AddValue(name: "NotAssigned", description: "There is no assignment", value: IsSet.NotSet);
```

I've tested the code and it works fine for both outputs and inputs including literals and variables.  I will be adding notes to the upgrade documentation and known issues documentation.

**Comment by joemcbride** [comment]
@Shane32 I recall specifically making it so you _could_ use numbers _or_ the enum type, if the enum had numerical values assigned, as I saw that as making it easier to use and the framework would "just work".  I don't disagree that just using the enum value could simplify some things, but I kind of liked that feature myself ...

**Comment by Shane32** [comment]
Good to know. I can write a PR to revert that behavior and we can review it. If the decision is that it is desired, we can patch it in 3.1 (or 3.0.1). I'm indifferent. We may still want to update the upgrade notes in the meantime unless we plan a quick fix.

**Comment by asgerl** [comment]
Just want to say that the discussion above answer my questions sufficiently.

I tested the fix Shane32 suggested and it works for me.

I will follow #1836 to see if the feature is re added again in later versions of GraphQL.

Closed this question as resolved.
