### ISSUE TITLE
Method not found: 'Void GraphQL.ExecutionOptions.set_ExposeExceptions(Boolean)

### ISSUE THREAD

**Issue by thefat32** [graphql-dotnet/graphql-dotnet#1834]
## Description

Execution error after updating deps:

Method not found: Void GraphQL.ExecutionOptions.set_ExposeExceptions(Boolean)

### Steps to reproduce

Updated deps from:

```
    <PackageReference Include="GraphQL" Version="3.0.0-preview-1352" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0027" />
```
to:

```
    <PackageReference Include="GraphQL" Version="3.0.0" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0073" />
```

Using option ExposeExceptions = true

```
            services.AddGraphQL(options =>
            {
                options.ExposeExceptions = true;
            });
```

### Expected result

Not to crash

### Actual result

Crash with:

Method not found: 'Void GraphQL.ExecutionOptions.set_ExposeExceptions(Boolean)

### Environment
Windows 10 64-bit
.NETCore 3.1

**Comment by Shane32** [comment]
The `3.5.0-alpha0073` preview of the GraphQL Server project needs to be used with `3.0.0-preview-1719` of GraphQL.  Version 3.0.0 of GraphQL was released yesterday, and final version 3.5.0 of the GraphQL Server project will follow shortly.
