### ISSUE TITLE
InputGraphType checks field types based on Resolved Type only.

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#1837]
## Description

When you add a field to an InputObjectGraphType it verifies if the type and field is also an input type. But it uses only the ResolvedType property for that. If you use the generic version of the types the ResolvedType is not resolved yet and therefore throws an exception.

### Steps to reproduce

```
public class InputDroidType : InputObjectGraphType
{
  public InputDroidType()
  {
    Field<NonNullGraphType<IdGraphType>>("id");
    Field<ListGraphType<StringGraphType>>("weapons");
  }
}
```

Version: 3.0.0

**Comment by Shane32** [comment]
Can you provide a PR with a failing test?  I was unable to reproduce the failure.  See this test code, which works fine:

https://github.com/graphql-dotnet/graphql-dotnet/blob/9c55e101670583841dc5c268891c0010b63666e5/src/GraphQL.Tests/Bugs/Issue1837.cs

In there you will see this definition:
```csharp
    public class Issue1837ArrayInputType : InputObjectGraphType
    {
        public Issue1837ArrayInputType()
        {
            Field<ListGraphType<IntGraphType>>("ints");
            Field<ListGraphType<NonNullGraphType<IntGraphType>>>("ints2");
            Field<ListGraphType<IntGraphType>>("intsList");
            Field<ListGraphType<NonNullGraphType<IntGraphType>>>("intsList2");
            Field<IntGraphType>("valueProp");
            Field<NonNullGraphType<IntGraphType>>("valueProp2");
            Field<NonNullGraphType<IdGraphType>>("IdProp");
        }
    }
```

**Comment by SebastianStehle** [comment]
You have to add a field like this:

```
            AddField(new FieldType
            {
                ResolvedType = new ListGraphType<IntGraphType>(),
                Name = "abc"
            });
```

**Comment by Shane32** [comment]
Oh, I've never added a field that way.

@sungam3r is that a supported method of adding fields?

@SebastianStehle Typically the `ResolvedType` properties are set when the schema is built, not before.  Can you use code like this instead?

```csharp
AddField(new FieldType
{
    Type = typeof(ListGraphType<IntGraphType>),
    Name = "abc"
});
```

**Comment by Shane32** [comment]
In my tests, this code sample also works:
```csharp
AddField(new FieldType
{
    Name = "IdProp",
    ResolvedType = new NonNullGraphType<IdGraphType>()
    {
        ResolvedType = new IdGraphType()
    },
});
```
However, I'm not sure if there are other consequences of setting the `ResolvedType` property manually.  I'd recommend setting only the `Type` property.

**Comment by SebastianStehle** [comment]
I have solved it with

```
AddField(new FieldType
{
    ResolvedType = new ListGraphType(new IntGraphType()),
    Name = "abc"
});
```

It is not an urgent bug.

**Comment by Shane32** [comment]
@SebastianStehle How did you solve it?  The code you provided is identical to the previous broken code that you provided.

**Comment by SebastianStehle** [comment]
How is this identical?

The difference is that I use only ResolvedType instead of a mix:

```ResolvedType = new ListGraphType(new IntGraphType())```

VS

```ResolvedType = new ListGraphType<IntGraphType>()```` 

The code checks if ResolvedType or field is not null. If this is the case it checks the last resolved type in the chain whether it is a scalar or input type. 

If you use ```ListGraphType<IntGraphType>``` the "last" resolved type is ListGraphType which is NOT a scalar or input type.

**Comment by Shane32** [comment]
I see - thanks!!!

**Comment by Shane32** [comment]
Did we solve this @sungam3r  ???  I can't remember.

**Comment by sungam3r** [comment]
Nope. It turns out that this is a very interesting bug.

**Comment by sungam3r** [comment]
I will publish PR soon.

**Comment by sungam3r** [comment]
@SebastianStehle Thanks for reporting such an interesting bug!
