### ISSUE TITLE
Detailed performance data with Azure Application Insights

### ISSUE THREAD

**Issue by julienFlexsoft** [graphql-dotnet/graphql-dotnet#1839]
##  Summary
Azure Application Insights automatically shows the performance of REST API's per endpoint (ex. /users, /settings/general, etc...) but with graphQL we only get one endpoint (/graphql) which makes sense, but has anyone found an easy way to track performance per GraphQL query?

For now my plan is to manually make custom telemetry measurements for each query type that I have. Which will be quite long to make. Do you know of any existing library or do you have a more efficient way?

Thanks!
If I find a better way I'll add it here below.

**Comment by BenjaBobs** [comment]
You could create a listener that hooks in after the execution and uses the apollo tracing data to synthesize the application insights data. You could do it as traces or dependencies or whatever you like.

**Comment by sungam3r** [comment]
@Shane32 I made a special label to better track such questions.

**Comment by julienFlexsoft** [comment]
Now that we are almost five years later, is there a better way to do this? For Azure Application Insights specifically?
