### ISSUE TITLE
Validate names after they are mapped with INameConverter

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#1840]
## Summary

At the moment the field name is validated when you add a field to a complex types, but with the `INameConverter` you can modify the name afterwards.

The current approach has two issues:

1. You cannot write a `INameConverter` that fixes invalidate graphql names.
2. You can write a buggy `INameConverter` that creates invalidate graphql names.

If you remove the name validation from the Complex Type and do it just after `INameConverter` is called you could fix both issues.

**Comment by Shane32** [comment]
Interesting idea!  The change could potentially fix a third bug in the present design: a name converter could create duplicate field or argument names for a type or field.

One difficulty is that the `NameConverter` is set on the `Schema` and therefore is inaccessible while the `GraphType` is constructed.  So with the proposed change, adding an invalid field name would not throw an error until the schema was built, making it more difficult to track down errors of that type.

**Comment by Shane32** [comment]
@sungam3r What do you think - can we do this in 3.2?

**Comment by sungam3r** [comment]
I do not understand the meaning of this "protection", since `FieldType.Name` has publis setter.

**Comment by sungam3r** [comment]
If the proposal is to call `NameValidator.ValidateName` after `NameConverter.NameForField(field.Name, parentType);` / `NameConverter.NameForArgument` then I propose to move this check inside name property setters for `FieldType`, `QueryArgument` etc. Now I see that the `ValidateName` protection resembles a locked gate without a fence.

**Comment by sungam3r** [comment]
And yes, it can be done in 3.2

> The change could potentially fix a third bug in the present design: a name converter could create duplicate field or argument names for a type or field.

Probably not. This is another task that requires access to the some context (in fact the whole schema). Checking the name in setter does not require any context, just regexp.

**Comment by Shane32** [comment]
> If the proposal is to call `NameValidator.ValidateName` after `NameConverter.NameForField(field.Name, parentType);` / `NameConverter.NameForArgument`

Right; just what I was thinking... (within `GraphTypesLookup.HandleField`)

> then I propose to move this check inside name property setters for `FieldType`, `QueryArgument` etc.

I don't understand - how do you call `INameConverter.NameForArgument` from a property setter for `FieldType` before the fieldtype has even been added to the schema?  I'm quite not following your train of thought.

Or did you mean "remove", not "move"?

**Comment by sungam3r** [comment]
I wrote incorrectly. I mean to move `NameValidator.ValidateName` into setters.

**Comment by sungam3r** [comment]
@SebastianStehle Could you provide a bit more context, please? Have you encountered aforementioned problems of name validation in practice? Please see these threads: https://github.com/graphql-dotnet/graphql-dotnet/pull/1964#discussion_r513819148 https://github.com/graphql-dotnet/graphql-dotnet/pull/1964#discussion_r514275928

**Comment by SebastianStehle** [comment]
About my use case:

I don't remember the exact scenario, but I am the main developer of Squidex: https://github.com/squidex/squidex

Squidex is a headless cms where the user defines a schema and from this schema a graphql schema is generated dynamically. Field names in user defined schemas are not necessarily valid graphql names and therefore I have to map them. They can start with a number, therefore I prefix them with `gql_` if needed. Or they can start with upper case, which is also not valid if I remember correctly.

But some users have `userName` and `UserName` as field names, which would map both to `userName`. My idea was to write a INameConverter which fixes all variable names but this is only possible if the names are validated after the name converter is executed.

I have solved it anyway, but I think it is a little bit weird design at the moment.

**Comment by sungam3r** [comment]
So https://github.com/graphql-dotnet/graphql-dotnet/pull/1964#discussion_r515177686  I see that you actually can have both cases - converting `valid->valid` and `invalid->valid`. Right?

Second question just for my understanding. Just for understanding. Can you map names _before_ the schema is created from user input and not in schema initialization process? We are currently considering two options for placing a name validation check. Either do it in the name setter or outside it - after calling the converter when the schema is initialized. Both options have advantages and disadvantages.

**Comment by SebastianStehle** [comment]
> Can you map names before the schema is created from user input and not in schema initialization process?

Yes, sure. This is what I do: https://github.com/Squidex/squidex/blob/master/backend/src/Squidex.Domain.Apps.Entities/Contents/GraphQL/Types/Extensions.cs#L20

As I said: This task is not that important for me.

**Comment by sungam3r** [comment]
@Shane32 By the way, there are no only fields and arguments. Also directives, enums and types have names. For them, the converter is simply not called. I believe this is an oversight.

**Comment by sungam3r** [comment]
#1964 was merged. Closing.
