### ISSUE TITLE
Extra field __typename appears but not defined in the schema and not possible to remove, and it increases size of the response.

### ISSUE THREAD

**Issue by SeletskySergey** [graphql-dotnet/graphql-dotnet#1842]
## Description

Extra field __typename appears but not defined in the schema and not possible to remove, and it increases the size of the response.

### Steps to reproduce

1. Prepare a simple query.
2. Do a query by any client.
3. The response contains unused __typename, it's increasing the size of the response by 2 times.

### Expected result

No unnecessary fields by default.
Optional configuration to enable it if somebody needs it.

### Actual result

The response contains unused __typename, it's increasing the size of the response by 2 times.
No way to disable it, nothing in config or docs.

### Environment

AspNetCore 3.1
Windows 10

**Comment by Shane32** [comment]
Typically clients send `__typename` in order that they can cache the result properly; it has nothing to do with the graphql server (like this repo).  I suggest you request this feature from the client library you are using.  See https://github.com/apollographql/apollo-feature-requests/issues/6 for the existing feature request for the apollo client.

**Comment by SeletskySergey** [comment]
I use graphql-dotnet/server and built-in playground to do a query. It returns a response with __typename.

**Comment by SeletskySergey** [comment]
just investigated, the playground sends __typename request in the payload.
looks like really a client related issue. I apologize, you can close this request.

**Comment by Shane32** [comment]
No problem! I use GraphiQL rather than Playground, which does not send the `__typename` field
