### ISSUE TITLE
Missing parameter in Hello World Example

### ISSUE THREAD

**Issue by visschersm** [graphql-dotnet/graphql-dotnet#1843]
## Description

https://graphql.org/code/#c-net

When starting with the Hello World example I got the error: "ISchema does not contain a definition for ExecuteAsync"
When looking more closely at the method signature I noticed that the extension method requires another parameter not mentioned in the tutorial. An IDocumentWriter.

### Steps to reproduce

`var json = await schema.ExecuteAsync(_ =>
            {
                _.Query = "{ hello }";
                _.Root = root;
            });`

Expected signature:
`public static Task<string> ExecuteAsync(this ISchema schema, IDocumentWriter documentWriter, Action<ExecutionOptions> configure);`

### Environment

Windows 10
Nuget package GraphQL --version 3.0.0

**Comment by sungam3r** [comment]
We changed a lot in version 3. https://graphql.org/code/#c-net contains obsolete documentation. Serialization was moved to separate packages, see https://github.com/graphql-dotnet/graphql-dotnet#installation. These packages contain extension methods with suitable signature.

@Shane32 We need to update docs in https://graphql.org/code/#c-net

**Comment by Shane32** [comment]
I’ll take a look if you can direct me to the file that needs updating @sungam3r

**Comment by visschersm** [comment]
Indeed, I can just insert a document writer to execute the sample. 
Using the GraphQL.SystemTextJson.DocumentWriter:

`
var writer = new GraphQL.SystemTextJson.DocumentWriter();
var json = await schema.ExecuteAsync(writer, _ =>
{
    _.Query = "{ hello }";
    _.Root = new { Hello = "Hello World!" };
});
`

Thank you for the quick response.

**Comment by sungam3r** [comment]
@Shane32 @visschersm I made a PR to graphql.github.io repo to fix the docs.

**Comment by sungam3r** [comment]
Closing this, I think the documentation site will update soon.

**Comment by JVimes** [comment]
@sungam3r Would you re-open this issue, and leave it open until the merge request passes? Thank you.

**Comment by sungam3r** [comment]
Our own documentation http://graphql-dotnet.github.io is now updated automatically after migrating to GitHub Actions. There is nothing I can do about when somebody decide to merge https://github.com/graphql/graphql.github.io/pull/914. In fact, this issue **does not apply to this repository**. It had to either be moved to graphql.github.io, or it was necessary to create another issue here. I chose the latter because I have no permissions to transfer issues to graphql.github.io. So I don't see the point in keeping the issue open, do you?

**Comment by Shane32** [comment]
The documentation within this library has been fixed in #1951.  There is an open PR at https://github.com/graphql/graphql.github.io/pull/914 to fix the documentation there.

**Comment by sungam3r** [comment]
graphql.github.io now has new design with our fixed example
