### ISSUE TITLE
Latest docs requires update in IValidationRule

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#1848]
https://graphql-dotnet.github.io/docs/getting-started/authorization

It shows a different implementation

From:
public INodeVisitor Validate(ValidationContext context)

To:
public Task<INodeVisitor> ValidateAsync(ValidationContext context)

How to implement this...

**Comment by Jonatthu** [comment]
I have noticed that internally you guys use EnterLeaveListener.ToTask();

But I am not able to call this extension method.

@joemcbride 
@Shane32

**Comment by Jonatthu** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/b7dbbc055808c41d100fb01b1c2fc864df386b02/src/GraphQL/Validation/TaskHelper.cs

This should not be internal @sungam3r

**Comment by Jonatthu** [comment]
To quickly unblock use:

public Task<INodeVisitor> ValidateAsync(ValidationContext context)
{
return Task.FromResult<INodeVisitor>(new EnterLeaveListener(_ => ...
}

**Comment by Shane32** [comment]
`ToTask` simply is a wrapper for `Task.FromResult`.  There is no need for it to be public; it does not contain any logic, and is merely a shortcut used internally within the codebase.  I wouldn't make it public unless there exists documentation demonstrating its use.

We do need to be sure the documentation (and possibly the 3.x upgrade guide) is correct with a working code sample.
