### ISSUE TITLE
Schema Stiching

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#1851]
It is important to include this into the roadmap.

https://hotchocolate.io/docs/stitching

Also I recommend to start improving the UI of our docs, I can volunteer to do so.

I believe this project should be the leading on all dotNET aspects instead of hotchocolate.

https://github.com/ChilliCream/hotchocolate/issues/392

Also where can I see the roadmap of this project?

**Comment by Shane32** [comment]
@Jonatthu Version 3.0 was just released; we have not discussed plans for 4.0 as of yet.  You can monitor the milestones within GitHub to track goals and progress.  We will probably add goals over the next couple weeks.

We welcome assistance with the project, but in this case I would check with @joemcbride as he set up the documentation site, I believe.  Do you have an idea of what you think needs improving or what you would do to the docs UI?  Perhaps you should start another issue or PR with a sample of what you are proposing.

If you would also like to work on the stitching feature, we can discuss it here, or just start a draft PR and we can look at what you're proposing.  It will also be important to consider if the stitching feature can be developed outside the main GraphQL.NET project as a separate nuget package, or if the design requires it to be an integrated component.  I have not investigated stitching or how it would work with this project.

**Comment by sungam3r** [comment]
Docs https://www.apollographql.com/docs/apollo-server/features/schema-stitching/

**Comment by sungam3r** [comment]
From https://tyk.io/blog/an-introduction-to-graphql-federation : 

![изображение](https://user-images.githubusercontent.com/21261007/153673004-f4528ddc-17ba-4fe9-9600-32fd40dd86bc.png)


Now I had to deal with federation (some refactoring , not a goal itself) and I can say with confidence that it makes no sense to move towards schema stithing. In addition, in official documents, it is reported that federation is a replacement of schema stiching. So I close this issue.
