### ISSUE TITLE
Field arguments not available on FieldConfig

### ISSUE THREAD

**Issue by adamjones1** [graphql-dotnet/graphql-dotnet#1867]
I'm using the `Action<SchemaBuilder>` parameter of `Schema.For` to customise some GraphQL types in a schema. In particular I'd like to set the descriptions of some field arguments this way, but it seems `FieldConfig` (from `builder.Types.For("myType").FieldFor("myField", services)`) doesn't have an `Arguments` field exposing this metadata. Is there a particular reason for this? It seems like an omission to me.

**Comment by sungam3r** [comment]
@adamjones1 Fixed and will be published in v4 soon.
