### ISSUE TITLE
GraphQL-dotnet 3.0 example

### ISSUE THREAD

**Issue by PoisnFang** [graphql-dotnet/graphql-dotnet#1879]
I made an small example project using the new 3.0 version of graphql-dotnet with EF Core and YesSql. If anyone is interested its [here](https://github.com/PoisnFang/Poisn.GraphQL) 

I was getting tripped up when I was looking at guides for this because they are all on v2.4, that's why I made my own. Hope it helps!

**Comment by pranav-manik** [comment]
where is AddDbProvider importing from in Startup.cs?
` services.AddDbProvider(options =>
            options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
`
I'm recieving this error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IServiceCollection' does not contain a definition for 'AddDbProvider' and no accessible extension method 'AddDbProvider' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)
`

**Comment by PoisnFang** [comment]
@pranav-manik Can you make an issue in the [github repo](https://github.com/PoisnFang/Poisn.GraphQL/issues) and I will respond there?

**Comment by chrisg2** [comment]
What you have found a Startup.cs file referring to a method named AddDbProvider? I don't think there is any method with that name in the normal Entity Framework. Maybe you mean [AddDbContext](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontext?view=efcore-3.1)?

**Comment by PoisnFang** [comment]
@chrisg2  He is referring to the code in my repo here: https://github.com/PoisnFang/Poisn.GraphQL

and this code: 

```csharp
            //Db Connection is in appsettings.json
            // this adds in EF Core Db
            services.AddDbContext<ApplicationDbContext>(options =>
               options.UseSqlServer(
                   Configuration.GetConnectionString("DefaultConnection")), ServiceLifetime.Scoped);

            // this add in YesSql Db
            services.AddDbProvider(options =>
            options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```

**Comment by sungam3r** [comment]
Fixed in https://github.com/graphql-dotnet/examples/pull/48
