### ISSUE TITLE
Connections and Edges should be able to contain interfaces and unions

### ISSUE THREAD

**Issue by rwg0** [graphql-dotnet/graphql-dotnet#188]
The relay spec states that edges may contain scalars, enums, objects, interfaces, unions and non-null wrappers of those types (https://facebook.github.io/relay/graphql/connections.htm#sec-Node). However the `EdgeType`, `ConnectionType` and `ConnectionBuilder` classes are restricted to accepting types derived from `IObjectGraphType` which means only objects can be used for a connection.

It looks like the `where` clause for each of those generics should be `where IGraphType` instead of `where IObjectGraphType`, but I'm not sure if this will introduce problems elsewhere.

**Comment by cdroulers** [comment]
I was going to create this issue today! Thanks! :D

**Comment by joemcbride** [comment]
Published a new version which I think should fix this.  Let me know if not.  https://www.nuget.org/packages/GraphQL/0.12.1-alpha-545

**Comment by rwg0** [comment]
I think you also need to change the where clause on 
`ObjectGraphType.ConnectionBuilder<TNodeType, object> Connection<TNodeType>() where TNodeType : IObjectGraphType`

fortunately can work around this by creating the ConnectionBuilder manually and that seems to work. Thanks :)

**Comment by joemcbride** [comment]
@rwg0 Thanks for the catch!  Will get that fixed.

**Comment by joemcbride** [comment]
0.12.2 should fix that
