### ISSUE TITLE
Allow to override built-in scalars

### ISSUE THREAD

**Issue by randyridge** [graphql-dotnet/graphql-dotnet#1885]
Upgrading from 2.x to 3.x our schema had a Uri type...  Is there a handy way to unregister the built in type?

**Comment by sungam3r** [comment]
I expected that sooner or later someone would make this request. I have long disliked that there is a conflict with custom scalars. I'll see what i can do.

**Comment by sungam3r** [comment]
@Shane32 What do you think about `GraphTypesLookup` and `GraphTypeTypeRegistry`? `GraphTypeTypeRegistry` alllows to override type, but I can't say that for `GraphTypesLookup`.

**Comment by Shane32** [comment]
Without looking at the code, going strictly from memory, perhaps we can provide a workaround in the form of removing the `UriGraphType` entry from the `GraphTypesLookup` before the schema gets initialized.  If there's no method to do so, perhaps we can add one for version 3.1.  Long term answer, maybe `GraphTypesLookup` should not add ANY ".NET custom scalars" automatically, but only add them in as needed just like any other graph type that is referenced by another graph type.  We can still leave the `GraphTypeTypeRegistry` links in place, but those can be overridden if needed already.

Side note: I don't see a registration within the `GraphTypeTypeRegistry` that maps `Uri` to `UriGraphType`.....

**Comment by randyridge** [comment]
I spent about an hour trying to make it happen, I tried everything I could think of, modifying the private types dictionary through a couple levels of reflection, and finally just decided to change our Uri type name...  yolo

**Comment by Shane32** [comment]
In order to do it now you will need to:
- Duplicate the static `GraphTypesLookup.Create` method
- After the first line of code that creates the class (`var lookup =`), before the rest of the code,
  - Use reflection to obtain the `_types` dictionary
  - Remove the entry corresponding to the `UriGraphType`
- Duplicate `Schema.CreateTypesLookup` in your own schema class
  - Have it call the new method you created above instead of the standard one
- In your schema class, either:
  1. Use reflection to change the private `_lookup` to a new instance of `Lazy<GraphTypesLookup>` which points to the new `CreateTypesLookup` function you created in the prior step; or
  2.  Create a new `_lookup` variable and override the following properties so they point to the new `_lookup` variable:
      - `Initialized`
      - `SchemaMetaFieldType`
      - `TypeMetaFieldType`
      - `TypeNameMetaFieldType`
      - `FindType`
      - `Dispose` (should call `base.Dispose` also)

**Comment by Shane32** [comment]
@sungam3r We could:
1. Make `Schema.CreateTypesLookup` a `virtual` method.  This allows someone to use a custom implementation of the `GraphTypesLookup` class.
2. Add a virtual `GraphTypesLookup.Initialize` function.  Move 99% of the code from `GraphTypesLookup.Create` into the initialize function.  So `Create` just calls `new` and `Initialize`.  (If we are not maintaining backwards compatibility, we could eliminate the static method altogether, moving the calls to `new` and `Initialize` into `Schema.CreateTypesLookup`.)
3. Maybe change/refactor some methods/fields/props of `GraphTypesLookup` to protected to allow for customizing behavior -- e.g. exposing `_types` via a protected readonly property, or adding a protected `AddDefaultGraphTypes` method.

With those edits, it would be simple to make the necessary change to remove `UriGraphType` from `_types` or customize other behavior as desired.

**Comment by randyridge** [comment]
Like I said it's non-trivial and relies on abusing reflection of privates or forking (I had a similar issue depending on GraphQL.Relay, it hasn't been touched in a couple year.  I plan on making a PR that fixes my build tomorrow). This is totally an edge case. With 2.x we had a need to make a UriType, (ours more closely matches .net's (relative or absolute path, scheme, etc) that this caught me out.  It forces a client schema generation for us, so that ended up being easier.

**Comment by Shane32** [comment]
Yes, but I think the library should be flexible enough to support any type of configuration that the GraphQL Spec would allow.  In this case, the UriGraphType is not part of the spec, so the library should not require it to be used.  (Or rather, it' shouldn't restrict custom implementations of a graph type with that name.)

**Comment by randyridge** [comment]
I don't disagree, but I understand the difficulties of running an OSS project....

**Comment by sungam3r** [comment]
I don't have a ready-made solution right now. Faced with a similar problem in my graphql client generator, I came to the conclusion that all custom scalars should be connected externally. The base library should only provide 5 built-in scalars. So it will be breaking change.

**Comment by sungam3r** [comment]
@randyridge I'm sure we can completely resolve this issue in [3.1](https://github.com/graphql-dotnet/graphql-dotnet/milestone/6)
