### ISSUE TITLE
The interface match check has break covariant interface returns

### ISSUE THREAD

**Issue by Elyhaka** [graphql-dotnet/graphql-dotnet#1889]
## Description

While migrating to v3, I've noticed a regression with the `IsValidInterfaceFor` method in the file `src/GraphQL/GraphQLExtensions.cs` (tracked to this specific commit: https://github.com/graphql-dotnet/graphql-dotnet/commit/9a7410e199de887d8ec436892ce642ae0910f19d#diff-4586aaacee7063d6089049fcfdae01a3R111).

When you have a GraphType that implement an interface field by returning a type that inherit from the base type of this field, the check in `if (found.Type != field.Type)` is too strict and throws an error.

### Steps to reproduce

Here is a dummy exemple:

```cs
class R {}
class SpecializedR : R {}

class A {
  public R methodUsedToGetRValue() {
    // returns a R object
  }
}
class SpecializedA : A {
  public SpecializedR methodUsedToGetSpecializedRValue() {
    // returns a SpecializedR object
  }
}

public class RGraphInterface : InterfaceGraphType<R> {
  public RGraphInterface() {
    Name = "RInterface";
  }
}

public class SpecializedRGraphType : ObjectGraphType<SpecializedR> {
  public SpecializedRGraphType() {
    Name = "SpecializedRGraphType";
    Interface<RGraphInterface>();
  }
}

public class AGraphInterface : InterfaceGraphType<A> {
  public AGraphInterface() {
    Name = "AInterface";

    Field<NonNullGraphType<RGraphInterface>>(
        "R",
        resolve: ctx => ctx.Source.methodUsedToGetRValue()
    );
  }
}

public class SpecializedAGraphInterface : ObjectGraphType<SpecializedA> {
  public SpecializedAGraphInterface() {
    Name = "SpecializedAGraphInterface";
    Interface<AGraphInterface>();

    Field<NonNullGraphType<SpecializedRGraphType>>(
        "R",
        resolve: ctx => ctx.Source.methodUsedToGetSpecializedRValue()
    );
  }
}
```

### Expected result

The contract specified by the interface is fulfilled since we do return a `R` object (just more specialized, but that should not be an issue as specified in the graphql spec here : https://github.com/graphql/graphql-spec/pull/123).

### Potential fix

The current implementation that just check the types with `==` is not enough, interfaces should be checked to ensure we're not returning a more specified type (thus, making the `==` fails while the contract being respected). Maybe something like `if(!field.Type.IsAssignableFrom(found.Type))` ?

EDIT: After some tests, the potential fix suggested is still not enough, if we use Composite types like `NonNullGraphType` the `IsAssignableFrom` would still fail.

**Comment by Shane32** [comment]
There's also `.GetNamedType()` which may be useful here.

It looks like we should add a suite of tests that test the functionality of `IsValidInterfaceFor`.  Might you be able to add a PR with tests demonstrating what works and doesn't with this function?  Even better, if you can also include a fix, then it will be easy to review and merge.

Thanks!!

**Comment by sungam3r** [comment]
Right. I think `IsAssignableFrom` (probably with `GetNamedType`) will fix the problem.

**Comment by Elyhaka** [comment]
Thanks for your answers!

@Shane32 I'm not sure at all where to start to fix it, I'm quite still struggling with how to handle the types and their implementation details. I've been able to make this check wrongfully crash with unions also, but I haven't isolated the implementation on my side that led to the crash.

**Comment by Shane32** [comment]
Just having failing tests would immensely help.  I don't use interfaces or unions, so my knowledge here is limited -- but if you can add a failing test, I should be able to figure it out.

**Comment by Elyhaka** [comment]
Here we are @Shane32 : https://github.com/graphql-dotnet/graphql-dotnet/pull/1890 :)

I've only added a reproduction for schema with covariant fields, I still need to add them for unions when I will have pinpoint the pattern to trigger it.

**Comment by sungam3r** [comment]
Thanks. I have reproduced it and will fix it.

**Comment by Shane32** [comment]
Thanks @sungam3r ! I’m sure you know more about this than me!

**Comment by Elyhaka** [comment]
@sungam3r Do you need a repro with unions (since it raises the same error) or the test with covariants are enough ?

**Comment by sungam3r** [comment]
OK, it won't hurt.
