### ISSUE TITLE
Shrink 3.1 milestone

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1895]
Relates to #1894 

@Shane32 Keep only #1831 and #1887 ?

**Comment by sungam3r** [comment]
But there is good news too - we have fixed a number of bugs that were not in 3.1 milestone.

**Comment by Shane32** [comment]
I think we need to review #344 and #298 "soon" but it won't make it into 3.1.  I'd move those to 3.2.  Likewise #1571 should be moved to 3.2

#1713 was recently assigned to 3.1 by @joemcbride but I don't know what needs to be done there.

You can assign #1002 as you please.

And yes this only leaves #1831 and #1887 for 3.1

I was going to update the milestones whenever we issue a release, but if you want to do it now, that's fine.

**Comment by sungam3r** [comment]
I know alwost nothing about federation (#1713). Agree on #344 and #298 . Alas, I still haven't used the analyzers.

#1002 is a very long story. I remember this issue very well because from time to time I have to rebuild the fork we use on our projects. I cannot say how soon it will be ready but it is 100% breaking changes.

**Comment by Shane32** [comment]
Then let's assign #1002 to 4.0, at least for now, and push #1713 to 3.2

**Comment by sungam3r** [comment]
OK

**Comment by Shane32** [comment]
I should set up analyzers sometime over the next year for my company's project.  I don't know when.  Just depends on what else is on the todo list.  I'm pretty sure #298 will be important at that time.

**Comment by Shane32** [comment]
Updated milestones as proposed.  3.2 deadline is set for another 45 days past 3.1, just as 3.1 is 45 days after 3.0.
