### ISSUE TITLE
How to deal with Dependabot alerts?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1898]
![изображение](https://user-images.githubusercontent.com/21261007/95675810-7afe9e00-0bc2-11eb-82d5-7ca7c8b69c08.png)

25 open alerts: https://github.com/graphql-dotnet/graphql-dotnet/network/alerts

It seems that yarn.lock file describes the packages used for node.js, I didn't work with node.js and have no experience in JS at all. I didn't even know what node.js is for in this project. I suppose for documentation generation. Just for this?

ping @joemcbride @Shane32 

Should we take any action? Update packages? Or just ignore/disable alerts? Probably better to do something.

**Comment by Shane32** [comment]
Correct node is only used for generating the docs. I’d disable dependabot for this project.

**Comment by sungam3r** [comment]
Dependabot Security Alerts is a special feature different from "regular" dependabot. I posted #1900 - this will automate the update of dependencies in csproj files. 

But even there is node.js only used to generate documentation, wouldn't it be useful to update all these "old" packages?

**Comment by Shane32** [comment]
I am not familiar with how the build process for the documentation is set up.  I do know that it would not build with the current version of node.  I wouldn't want to break the documentation-building process by updating packages - at least, without being sure that it still works.

If I add in build checks for the documentation, as I did in the `develop` branch, then we could review that the documentation is building properly before merging.

I'll add a PR for those build checks (same workflows as are used in the `develop` branch).

**Comment by sungam3r** [comment]
I merged some PRs generated from security alerts page but all others say "Dependabot cannot update to the required version". In general, this is not such a big problem. Let everything remain as it is. If someone with JS knowledge wants to make a PR, then good. Closing.

**Comment by Shane32** [comment]
@sungam3r I'm starting to get really annoyed at dependabot.  I'd get rid of it.  It makes a mess of PRs and a mess of emails in my inbox.  Just my 2 cents.  Once in a while, it's nice.... but when you have to live through all the garbage for that....

**Comment by sungam3r** [comment]
@dependabot ignore this major version


That will help

**Comment by sungam3r** [comment]
This is all due to .NET 5 release. So far I have closed all the PRs that raised the version of dependencies to 5.0.0. But I have plans to do the support for net5.
