### ISSUE TITLE
Field ordering in introspection queries

### ISSUE THREAD

**Issue by adamjones1** [graphql-dotnet/graphql-dotnet#1905]
Hi, I see that as of #594 the fields of a type in a schema are always ordered alphabetically. This is somewhat confusing with a schema-first approach to a server as the fields are all out of order from their originally shared schema. Could we please make this behaviour optional? It would make sense to me to control ordering by providing the user a setter for an `IComparer<FieldType>` which defaults to the original ordering and having a "ByName" implementation provided OOTB to smooth the common case.

Or at the very least can the behaviour be opt-out if not opt-in?

**Comment by adamjones1** [comment]
Hi, thanks for the quick turnaround on this! Would there be any chance this could be implemented with the "by-name" behaviour as opt-out prior to the 4.0 release (eg. 3.2), so there're no breaking changes, and then switched to opt-in in 4.0? It would be really useful for me to have the feature sooner even if I have to explicitly code it for a while on my end. Happy to contribute PRs for this if it makes it happen.

**Comment by sungam3r** [comment]
In theory I can remove `ISchema.Comparer` from public API so changes will become bacward compatible. But I would not want to do that so as not to complicate the implementation.

**Comment by adamjones1** [comment]
Hi, I just accidentally upgraded my GraphQL.Net version in dev and ran into a compilation error because `ISchema` was added to. Not a big deal for me, but due to the event I couldn't help but have my attention drawn to this new excerpt in the release notes:
> ### `ISchema` now implements `IProvideMetadata` (only for GraphQL.NET >= v3.2.0)
>
> Formally it is a breaking change but practically clients shouldn't run into problems, as hardly anyone creates their own `ISchema` implementations preferring to inherit from `Schema` class. 

Although a little ironically I'm apparently the exception to this rule...can this apply here too? 😄

**Comment by Shane32** [comment]
Valid point!  @sungam3r Thoughts?

@adamjones1 There is an outstanding PR #1907 for this feature.  From my look at the PR, it seems that it did not sufficiently cover the ability to _preserve ordering_ of the fields as defined in the schema, as seemed to be your intent.  I would expect the PR should have a test to cover that capability of the new code.  Perhaps you can test the PR on your end and determine if it meets your needs, provide commentary and/or tests, etc.

**Comment by sungam3r** [comment]
> can this apply here too?

It _can_. Then we'll move more and more to the dark side of the Force.

**Comment by adamjones1** [comment]
Sure I can do that. I just tested the PR on my side and it does (at least appear to) give the facility to preserve ordering by providing an `ISchemaComparer` with all properties nulled out. I can take a look at adding a unit test for that and documentation of the behaviour this evening.

**Comment by sungam3r** [comment]
> with all properties nulled out

Note that I use not-null comparer only for `FieldComparer(IGraphType parent)` for backward compatibility to preserve current bahavior. We _can_ change it if we want.

**Comment by adamjones1** [comment]
> We _can_ change it if we want.

Cool, all I'm personally really concerned about in the short term is being able to work around this, though my 2c is that it would make much more sense to have no reordering by default and provide syntactic sugar for the common case of sorting fields alphabetically. I don't really have a view on how significant a breaking change that is for the library but maybe it could be a 4.0 thing to switch.

I've submitted a PR (#2042) into this one to add a test and line of documentation. I stopped short of asserting the ordering is preserved for things other than fields because I noticed that types are preserved _except_ for scalar types, which for some reason are always brought to the top. I didn't manage to pick out why that was from a glance at the code. So for now I've just documented and tested it works for fields. Let me know if you need anything more!

**Comment by Shane32** [comment]
Are you saying....    2.4 = no ordering, 3.x = alphabetical, 4.x = no ordering    ???

I'm indifferent, but I would like to point out that's probably two main use cases here:
- Alphabetical ordering will provide a consistent introspection query if used for tests to determine if the query definition has changed, regardless of the order in which those fields were defined.
- Unordered results will match schema-first query definitions.

As such, the library should support both and test both of those specific scenarios.  There may be another use case for custom sorting, but I can't think of it.

I'm not sure which would be best to define as default.  A third option would be to have graphtype-first schemas use sorted ordering by default, while schema-first schemas use unsorted ordering by default, but I'm not necessarily suggesting that either.

**Comment by sungam3r** [comment]
> Are you saying.... 2.4 = no ordering, 3.x = alphabetical, 4.x = no ordering 

Yes. Those who need ordering just set the right comparer.

**Comment by sungam3r** [comment]
Fixed by #1907
