### ISSUE TITLE
Mutation with nested types/lists

### ISSUE THREAD

**Issue by ManuelRauber** [graphql-dotnet/graphql-dotnet#1911]
I'm currently trying to figure out how to make a mutation that has nested types/lists.

Consider the following setup for Entity Framework:

```csharp
public class Cfp {
  public Guid Id { get; set; }
  public string Name { get; set; }
  public ICollection<Material> Materials { get; set; }
}

public class Material {
  public Guid Id { get; set; }
  public string Url { get; set; }
  public string Name { get; set; }
}
```

I wonder, how I can model that for GraphQL to have a mutation to send the data like this (JSON-example, since I'm not sure about the correct syntax of the mutation):

```json
{
  "name": "Test 1",
  "materials": [
    {
      "url": "https://example.com",
      "name": "Mat 1"
    },
    {
      "url": "https://example-2.com",
      "name": "Mat 2"
    },
  ]
}
```

I started with a mutation like this here:

```csharp
    public class TfTStoreMutation : ObjectGraphType
    {
        public TfTStoreMutation(CfpRepository cfpRepository)
        {
            FieldAsync<CfpType>(
                "createCfp",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<CfpInputType>>() { Name = "cfp" }),
                resolve: async context => await cfpRepository.AddItem(context.GetArgument<Cfp>("cfp")));
        }
    }

    public class CfpInputType : InputObjectGraphType<Cfp>
    {
        public CfpInputType()
        {
            Field(i => i.Name);
        }
    }
```

Now, I'm not sure, if I need a second `QueryArgument` or if the `Materials` collection is a `Field`.

In my case, I want to store both entities via a transaction, so either both are saved to the database or none of them.

Is there any best practice for that?

**Comment by OpenSpacesAndPlaces** [comment]
There may be a better newer/way, but when I had to-do this in the past I attached the navigation as a custom built ScalarGraphType and then from there it's just making sure that your mutation resolver pulls that data in as needed and EF knows about the Navigations so that the will work.

See:
https://github.com/graphql-dotnet/graphql-dotnet/issues/474

**Comment by sungam3r** [comment]
@ManuelRauber Did you manage to solve this issue?

**Comment by ManuelRauber** [comment]
@sungam3r Nope, I've switched to HotChocolate in the meantime, sorry.
