### ISSUE TITLE
Pick and mark issues for 3.2 milestone

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1917]
Let's choose the ones that we want / can do for 3.2

**Comment by sungam3r** [comment]
At first glance, I propose to consider the following - #1879, #1496 , #885, #354

**Comment by Shane32** [comment]
#354 would actually be extremely useful for some of my existing code so 👍  on that!

I think the adding the other issues mentioned above sounds good.  If I have time I may spend some time on adding XML comments here and there (#1857) although I expect this to be an ongoing process, not completed in any one version of 3.x.  I'll update that issue with a breakdown of what needs XML comments when I get a chance.

I'm not sure exactly what the goal is for #1879 -- I don't think we should spend time on a EF Core sample with YesSQL as the underlying database provider, but it would be good to have a EF Core sample using a built-in database provider such as MS SQL.  I could be talked into MySQL.

I also think we should continue to maintain binary compatibility throughout the 3.x timeline, so as to maintain 100% compatibility with 3rd party packages which may not be updated as often as this project.  However, I would allow for feature improvements and bug fixes, including discretionary changes to functionality in our discretion.  (For instance, #1896 and #1887 both change functionality, but are determined to be improvements to the project.)

**Comment by sungam3r** [comment]
Regarding #1879 my motivation is for every minor release to add at least some documentation.

**Comment by sungam3r** [comment]
#1919

**Comment by sungam3r** [comment]
#1840

**Comment by sungam3r** [comment]
#1879 is done

**Comment by Shane32** [comment]
Why don’t we mark all these in the milestone and close this issue?

**Comment by sungam3r** [comment]
OK

**Comment by sungam3r** [comment]
done
