### ISSUE TITLE
Cannot have a ListGraphType on the root

### ISSUE THREAD

**Issue by ryanlewis** [graphql-dotnet/graphql-dotnet#194]
I'm pretty new to GraphQL, so please bear with me!

I'm trying to add a ListGraphType<> to my root query, but that is causing an error on [this line](https://github.com/graphql-dotnet/graphql-dotnet/blob/974655cb3dd9b1e85cfd33095b05bf5beb2978fb/src/GraphQL/Types/GraphTypesLookup.cs#L131). However, my business model has a collection on the root. I want to be able to ultimately retrieve a list of events based on search criteria.

Consider the following:

```
    public class RootQuery : ObjectGraphType<object>
    {
        public RootQuery(MyRepository repo)
        {
            Name = "Query";
            Field<EventsType>("events", "All events", resolve: ctx => repo.GetEvents());
        }
    }

    public class EventsType : ListGraphType<EventType>
    {
    }

    public class EventType : ObjectGraphType<Event>
    {
        public EventType()
        {
            Name = "Event";
            Field(e => e.Id).Description("The ID of the event");
            Field(e => e.Name).Description("The name of the event");
        }
    }
```

What am I missing here? Is there a reason why the ListGraphType is not allowed on the root?

**Comment by ryanlewis** [comment]
Looks like I got my root query definition wrong - problem went away when I just implemented ObjectGraphType, (possibly jiggling a number of other different things).

**Comment by joemcbride** [comment]
I think the issue is the use of EventsType.  ListGraphType should be sealed.
