### ISSUE TITLE
use sorting , filtering , paging in graphql-netcore  

### ISSUE THREAD

**Issue by MahdiElahi** [graphql-dotnet/graphql-dotnet#1943]
Hi 
i check this repository and search in web , i cant find complete tutorial or codes for use **paging , sorting , filtering** in graphql-net core

have graphql this features ?

**Comment by OpenSpacesAndPlaces** [comment]
That would be outside the scope of what it does inherently.

You would need to add the arguments for paging , sorting , filtering and then teach your data layer to use them.
Really the first step would be to look for examples of how you accomplish those with the data back end you have and the read up on adding arguments to your fields/graphs.
https://github.com/graphql-dotnet/graphql-dotnet/blob/edff6e96329bc1482464d2c82657044d6e32e1d1/docs2/site/docs/getting-started/arguments.md

**Comment by sungam3r** [comment]
Look at https://github.com/graphql-dotnet/relay . I have intentions to update and maintain this project, but specifically now there is no time for this.
