### ISSUE TITLE
add validation fields in .net core 

### ISSUE THREAD

**Issue by MahdiElahi** [graphql-dotnet/graphql-dotnet#1948]
hi 
Hi, 
i want use attributes property for validation fields ini .net core ? how to do it
i want use this attributes

   public int Poster_Id { get; set; }
**[Required]**
        public string Title { get; set; }
        **[EmailAddress]
        [StringLength(10,ErrorMessage ="title is required")]**
        public string  Email{ get; set; }
  

for example in add mutation when i send data if title is null return required message to client

**Comment by sungam3r** [comment]
You can write your own validation rule
```c#
public class MyRule : IValidationRule {...}
```

Then add this rule to `ExecutionOptions.ValidationRules`. Notice that there are default rules: `DocumentValidator.CoreRules` which should be concatenated with your new rule.

**Comment by MahdiElahi** [comment]
is there any way to use error message attributes **[Required(ErrorMessage = "{0} is Required")]**
or a simple way ??
@sungam3r

**Comment by sungam3r** [comment]
There is nothing like this out of the box and I think you should implement it by yourself in your custom rule.

**Comment by MahdiElahi** [comment]
well , please help and show me a simple example of use  validation rule for fields @sungam3r

**Comment by sungam3r** [comment]
```c#
 public class MyRule : IValidationRule
    {
        public Task<INodeVisitor> ValidateAsync(ValidationContext context)
        {
            return Task.FromResult((INodeVisitor)new EnterLeaveListener(_ =>
            {
                _.Match<Argument>(argAst =>
                {
                    var argDef = context.TypeInfo.GetArgument();
                    if (argDef == null)
                        return;

                    var type = argDef.ResolvedType;

                    // dtoType - yourType with Required / StringLength / etc annotations
                    var dtoTypeWithAnnotations = argDef.GetMetadata<System.Type>("SOME_STORED_MAPPED_DTO_TYPE_FOR_ARGUMENT");

                    if (dtoTypeWithAnnotations != null)
                    {
                        var value = argAst.Value;

                        foreach (var error in CheckAnnotations(dtoTypeWithAnnotations, argAst.Value))
                        {
                            context.ReportError(error);
                        }
                    }
                });
            }));
        }

        private IEnumerable<ValidationError> CheckAnnotations(System.Type typeWithAnnotations, IValue inputValue)
        {
            // TODO:
            yield break;
        }
    }
```

And add this rule in `ExecutionOptions`: `ExecutionOptions.ValidationRules = new[] { new MyRule() };`

Note that there is no direct connection between GraphType and some DTO which you _may or may not_ use when working with graph types.

**Comment by MahdiElahi** [comment]
@sungam3r 
thanks , but how to call MyRule  in startup.cs ??

**Comment by sungam3r** [comment]
Add this rule in `ExecutionOptions`: `ExecutionOptions.ValidationRules = new[] { new MyRule() }`;

**Comment by MahdiElahi** [comment]
@sungam3r 
 can't find ValidationRules 

`        services.AddGraphQL(opt =>
            {
                opt.EnableMetrics = true;

                **opt.ExposeExceptions = false;**
                
                opt.UnhandledExceptionDelegate = context =>
                {
                    Console.WriteLine("Error :" + context.OriginalException.Message);
                };
            }).AddUserContextBuilder(httpContext => new GraphQLUserContext { User = httpContext.User})
              .AddDataLoader().AddGraphTypes(typeof(PosterSchema));

         `

**Comment by MahdiElahi** [comment]
@sungam3r 

i use this in startup.cs

`            services.AddSingleton<IValidationRule,MyRule>();
`

it's true ??

**Comment by sungam3r** [comment]
yes, or
```c#
services.AddTransient<IValidationRule,MyRule>();
```

`DefaultGraphQLExecuter<TSchema>` in the server project uses injected rules:
```c#
  public DefaultGraphQLExecuter(
            TSchema schema,
            IDocumentExecuter documentExecuter,
            IOptions<GraphQLOptions> options,
            IEnumerable<IDocumentExecutionListener> listeners,
            IEnumerable<IValidationRule> validationRules)
        {
            Schema = schema;

            _documentExecuter = documentExecuter;
            _options = options.Value;
            _listeners = listeners;
            _validationRules = validationRules;
        }
```

**Comment by MahdiElahi** [comment]
@sungam3r 

id don't use GraphQlController(DefaultGraphQLExecuter.cs) In My Project 

how to use it without use graphqlcontroller ? it's necessary

**Comment by sungam3r** [comment]
GraphQlController? What is it? I can’t help you if you don’t show completely your GraphQL configuration code (Startup/Middleware/etc). GraphQL engine can be configured in several ways. See [examples](https://github.com/graphql-dotnet/examples) repo, [server](https://github.com/graphql-dotnet/server/tree/master/samples) project examples and one [harness sample](https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.Harness) in this repo.

**Comment by MahdiElahi** [comment]
[My Project](https://gitlab.com/elahi1mahdi/graphql)
@sungam3r

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/99902686-b8ca0880-2cd0-11eb-8827-5fcb09d29d22.png)

**Comment by MahdiElahi** [comment]
????
@sungam3r

**Comment by sungam3r** [comment]
You wanted to set up a custom validation rule. I showed it. I showed that it works. What exactly is not clear to you?

**Comment by MahdiElahi** [comment]
yes thanks for help you @sungam3r 
but when i set break point in validation rule and run project as debug (F5) the application comes to this breakpoint every second.
actually **the application call validation rule any time**

Check correctly defined custom validation rule ( **FieldValidator.cs** ) in this [startup.cs](https://gitlab.com/elahi1mahdi/graphql/-/blob/develope/Graph_2/Startup.cs) 

this is show call my validation every second, why , i **wrongly** defined rule  or this is **normal** ??

please see this gif to understand better my problem
[validation.gif](https://uupload.ir/files/0ngh_validation.gif)

**Comment by sungam3r** [comment]
Disable `schema.polling.enable` in GraphQL Playground UI settings (gear icon).

**Comment by MahdiElahi** [comment]
@sungam3r 
thanks a lot, so it's not problem ?
what schema polling enable?

**Comment by sungam3r** [comment]
https://medium.com/novvum/graphql-playground-v1-8-8-introducing-automatic-schema-reload-6c9da4bbd552

**Comment by sungam3r** [comment]
Closed as answered.
