### ISSUE TITLE
[Allow to replace built-in scalars] Different  behavior in data conversion and serialization between versions 2.4 and 3.1

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#1952]
## Summary
We have an old big solution based on GraphQL version 0.14.6 and trying to migrate to version 3.1.

Unfortunately we cannot fix the schema definition of the solution and need to make sure it is backward compatible.
Almost all issues have been resolved expect the one that I am going to describe here.

When returning the response, versions 0.14.6 and 2.4 just serialize the data based on the returned object type, however in version 3.1, the serlization is based on the used graph type of the query. Now if there is mismatch between POCO object and GraphType, the end result is different.

I know they should match, but as I mentioned since the code set that we have is very big, there is no way to manually check this, unless there is a recommendation on how to do that programmatically.

The following code shows the issue the way that the schema is defined and used in our code.
As you can see in the TestReponse class IsAvailable is boolean but in TestReponseType the field is StringGraphType (we have a lot of this bad setting in the code). 
Now version 2.4 returns isAvailable true (boolean) and version 3.1 returns "True" (string).

```

void Main()
{
	var schema = new Schema { Query = new TestQuery() };

	var exec = new DocumentExecuter();

	var result = exec.ExecuteAsync(options =>
			{
				options.Schema = schema;
				options.Root = null;
				options.Query = "{ test { name isAvaialble  } }";
				options.OperationName = "";
			}
	).Result;

	var json = JsonConvert.SerializeObject(result.Data);  
	/*
		version 0.14.6 and 2.4  --> {"test":{"name":"myName","isAvaialble":true}}
		version 3.1		--> {"test":{"name":"myName","isAvaialble":"True"}}
	*/
        

	

}

public class TestQuery : ObjectGraphType
{
	public TestQuery()
	{
		Name = "testQuery";
		Description = "Test description";

		Field<TestResponseType>(
			name: "test",
			description: "Test",
			resolve: context =>
			{
				return new TestResponse();
			}
		);
	}
}

public class TestResponseType : ObjectGraphType
{
	public TestResponseType()
	{
		Name = "TestReponse";
		Description = "Test Response Description";

		Field<StringGraphType>("isAvaialble");
		Field<StringGraphType>("name");

		IsTypeOf = value => value is TestResponse;
	}
}

public class TestResponse
{
	public bool IsAvaialble { get; set; }
	public string Name { get; set; }
	public TestResponse()
	{
		IsAvaialble = true;
		Name = "myName";
	}
}
```

We do have some unit tests and integration test that could be used to detect this issue if there is any way to make this validation programmatically.

Thanks.

**Comment by sungam3r** [comment]
See http://spec.graphql.org/June2018/#sec-Scalars, Result Coercion paragraph:
![изображение](https://user-images.githubusercontent.com/21261007/97364885-cd73d600-18b5-11eb-8fa8-e0497298a99b.png)

Therefore, we can say that versions before 3 did not meet the specification. I think you can do a hack - replace `StringGraphType` with you own type like this:
```c#
    public class MyStringGraphType : StringGraphType
    {
        public MyStringGraphType()
        {
            Name = "String";
        }

        public override object Serialize(object value) => value is bool ? value : base.Serialize(value);
    }
```

Most likely you will need to resort to reflection, because otherwise you will get an error
```
throw new InvalidOperationException($@"Unable to register GraphType '{type.GetType().FullName}' with the name '{typeName}';
the name '{typeName}' is already registered to '{existingGraphType.GetType().FullName}'.");
```

But I didn't have time to check it out.

@joemcbride @Shane32 Do we want to give the ability to replace graph types for standard scalars?

**Comment by rmeshksar** [comment]
Thanks for quick reply.
I know version 3 is doing it right. It was just one example and in our application we may have a lot more of this case with different types.

Is there any way that I can use reflection to find out these kinds of mismatch in the code?

**Comment by Shane32** [comment]
@sungam3r I am all for making the library flexible enough so when someone wants to do something extraordinary, they can, without resorting to reflection or copying large portions of code to do so.  However, I don't think we need to make it "easy", per se.  For example, we could make `Schema.CreateTypesLookup` to be a `protected` function, and then provide restructure `GraphTypesLookup` a bit so with some inheritance you can utilize a custom `GraphTypesLookup` implementation to override the built-in types as desired.  I was about to suggest this during #1887 but figured that it was outside the scope of the immediate issue, and could always be added later.

**Comment by Shane32** [comment]
As it is, with the changes in #1887, the new dictionaries are `private` so we still have the flexibility of making the necessary changes without breaking binary compatibility with prior versions.

**Comment by Shane32** [comment]
I can probably make a PR demonstrating these changes, and we can look it over and make a decision from there.  There's been a number of times that I've wanted to make changes to the inner workings of GraphQL.NET so I know how frustrating it can be when the codebase is locked down too tightly.

**Comment by Shane32** [comment]
> Is there any way that I can use reflection to find out these kinds of mismatch in the code?

Offhand, I'm not sure how that's possible.  Since `IFieldResolver.Resolve` returns a value of type `object`, there's no way to know what type of object will be returned with any time of runtime check, unless the resolver actually executes.

**Comment by sungam3r** [comment]
> For example, we could make Schema.CreateTypesLookup to be a protected function, 

Most likely it will not be required. Schema already has a bunch of `RegisterType` overloads. It only remains to check that they work with built-in scalars and maybe fix it a little.

**Comment by Shane32** [comment]
> Most likely it will not be required. Schema already has a bunch of `RegisterType` overloads. It only remains to check that they work with built-in scalars and maybe fix it a little.

Makes sense.  I think one of the challenges will be to be sure that when overriding built-in scalars, it does not affect built-in introspection types.

**Comment by rmeshksar** [comment]
I understand version 3 returns data according to the spec, but is it even possible to opt-out from that?
I spent some time on our application and since it is very big, it is not practical to just find these issues by looking at the source code.

**Comment by sungam3r** [comment]
We are thinking about to allow overwrite built-in scalars.

**Comment by Shane32** [comment]
@sungam3r We still do not allow overwriting of built-in scalars, do we?  Should we think about this for v4?

**Comment by sungam3r** [comment]
It is already possible to override clr-graph type mapping when using expression syntax on fields but the issue is about `StringGraphType` itself. I suggest to write `ISchemaNodeVisitor` and register it on schema. Something like that:
```csharp
public class ChangeTypeVisitor : BaseSchemaNodeVisitor
{
    public void VisitFieldDefinition(FieldType field, ISchema schema)
    {
        if (field.ResolvedType is StringGraphType)
            field.ResolvedType = new MyStringGraphType();
    }
}
```

See `MyStringGraphType` here https://github.com/graphql-dotnet/graphql-dotnet/issues/1952#issuecomment-717560093

**Comment by sungam3r** [comment]
@Shane32 You were right! I found my example above about replacing scalars. I completely forgot about it.

**Comment by Shane32** [comment]
Although I think the new solution in PR #2388 is rather elegant, this method is actually still necessary if a schema was created using graph type instances.  For instance, if they wrote code like `var f = new FieldType { ... , ResolvedType = new IntGraphType() };`.  I'm not sure if we need to include sample documentation within the migration docs for this special use case versus the simpler solution of `schema.RegisterType<new MyIntGraphType()>();` which works for more typical scenarios.

If we decide to also include documentation with the above sample, we should add a test for it as well, testing both input and output scenarios.

**Comment by sungam3r** [comment]
Both approaches work.

**Comment by sungam3r** [comment]
> If we decide to also include documentation with the above sample, we should add a test for it as well, testing both input and output scenarios.

#2388 contains tests for both input and output cases.

**Comment by sungam3r** [comment]
@rmeshksar In v4 (coming soon) you can "replace/override" built-in scalars. We provide two options for doing this - registering scalar before schema initialization or replacing scalar after initialization. Documentation is under development.
