### ISSUE TITLE
Releases do not attach nupkg files as assets to the release

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#1955]
Should be an easy fix.  See: https://github.com/actions/upload-release-asset

Just need to figure out the `upload_url` parameter, since the sample provided by GitHub does not quite apply.  Also, need to figure out if/how wildcards are supported.

In the meantime, we can download the assets from the workflow and manually attach them.

**Comment by Shane32** [comment]
Maybe see: https://github.com/actions/upload-release-asset/issues/47#issuecomment-659071145

**Comment by sungam3r** [comment]
OK. I will read tomorrow.

**Comment by Shane32** [comment]
It should also zip and include the compiled documentation
