### ISSUE TITLE
Business object to GQL automap

### ISSUE THREAD

**Issue by slottjj** [graphql-dotnet/graphql-dotnet#196]
FWIW: I've enjoyed using your library. I found that an AutoMapper class was useful in most cases of mapping business objects to GQL objects. Code attached. Feel free to scavenge anything you find useful.
[AutoQuery.cs.renamed.txt](https://github.com/graphql-dotnet/graphql-dotnet/files/534569/AutoQuery.cs.renamed.txt)

**Comment by huysentruitw** [comment]
How is this related to AutoMapper?

**Comment by slottjj** [comment]
Apologies. I've used incorrect terminology. Ignore AutoMapper. What I had intended to say is that I found it of use to utilize reflection against my transport objects in order to establish graphql schema information.

Sorry for the confusion.

**Comment by joemcbride** [comment]
Going to go ahead and close this.  Thanks!
