### ISSUE TITLE
Moving subscriptions stuff in the separate package

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1971]
Just an idea. No everyone uses subscriptions but they create additional burden on the main package and clients when dealing with versioning problems:
![изображение](https://user-images.githubusercontent.com/21261007/97608237-1e550d00-1a23-11eb-80d9-7d5c400ac803.png)
![изображение](https://user-images.githubusercontent.com/21261007/97608713-c10d8b80-1a23-11eb-9602-fa11c30043c0.png)

It is theoretically possible to take out all the things necessary for subscriptions in a separate package. This will require a careful approach. In the process, it may turn out that the subscription mechanism is too closely tied to the core of the project and the game is not worth the trouble.

**Comment by Shane32** [comment]
And the `Microsoft.CSharp` reference is only used by two lines of code...

**Comment by sungam3r** [comment]
I know :(

**Comment by sungam3r** [comment]
Done in #1973.
