### ISSUE TITLE
Lack of examples. What a way to proper implement GraphQL server for Relay?

### ISSUE THREAD

**Issue by alerdenisov** [graphql-dotnet/graphql-dotnet#200]
I'm very interesting how to proper implement connections, ids. Maybe someone can just share link on some repository with already implemented schemas and types?

**Comment by JarnoNijboer** [comment]
A good source I tend to use, are the [unit tests](https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.Tests) for this project.

**Comment by alerdenisov** [comment]
Thanks for advice. I found what I need 👍
