### ISSUE TITLE
Problem to resolve list with id

### ISSUE THREAD

**Issue by AAIING** [graphql-dotnet/graphql-dotnet#2004]
Hi, trying resolve list with id, return bad list.

**example.
First query its OK**
![image](https://user-images.githubusercontent.com/46494254/98940324-957dad00-24c9-11eb-95ec-a57efdca5041.png)
 **and second query launch bug**
![image](https://user-images.githubusercontent.com/46494254/98940411-b3e3a880-24c9-11eb-873f-8bd186bb678a.png)
in console the queries to database is OK
![image](https://user-images.githubusercontent.com/46494254/98940534-dfff2980-24c9-11eb-8ac3-a42608d12fc2.png)

my code:
```с#
 public class ServicioTicket : IServicioTicket
    {
        private readonly DataContext _dataContext;
        public ServicioTicket(DataContext dataContext)
        {
            this._dataContext = dataContext;
        }

        public List<Sub_problema> GetListSubProblemas(int idProblema)
        {
            return _dataContext.Sub_problema.Where(x => x.Id_problema == idProblema).ToList();
        }
}
```
**resolve field..**
```c#
      Field<ListGraphType<SubProblemaType>>("listaSubProblemas",
               arguments: new QueryArguments(new List<QueryArgument> { new QueryArgument<IntGraphType> { Name = "id_problema" } }),
               resolve: context => {
                   return servicioTicket.GetListSubProblemas(context.GetArgument<int>("id_problema"));
                   
               });
```

**Comment by sungam3r** [comment]
What does `context.GetArgument<int>("id_problema")` return?

**Comment by AAIING** [comment]
> What does `context.GetArgument<int>("id_problema")` return?

Return way ?

    public interface IServicioTicket 
    {
        List<Sub_problema> GetListSubProblemas(int idProblema);
       
    }

Im trying to direct to resolver and launch same error_

` public class TicketQuery : ObjectGraphType
    {
        private readonly DataContext _dataContext;
        public TicketQuery(DataContext dataContext, IServicioTicket servicioTicket)
        {
            _dataContext = dataContext;

            Name = nameof(TicketQuery);


            FieldAsync<ListGraphType<SubProblemaType>>("listaSubProblemas",
              arguments: new QueryArguments(new QueryArgument<IntGraphType> { Name = "id_problema" } ),
              resolve: async context => {
                  var idProblema = context.GetArgument<int>("id_problema");
                  var listaSubProblema = await _dataContext.Sub_problema.Where(x => x.Id_problema == idProblema).ToListAsync();      
                  return listaSubProblema;
            });
     }`

**Comment by AAIING** [comment]
> What does `context.GetArgument<int>("id_problema")` return?

Solved the problem, the error from to static data table assigned two primary keys and repeat the id key in the data
