### ISSUE TITLE
How to replace DispatchAllAsync

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/graphql-dotnet#2010]
After upgrading, I see that DataLoaderContext.DispatchAllAsync has [been removed](https://github.com/graphql-dotnet/graphql-dotnet/commit/966831278bee1ab3b52ad489f87549efb6933a7b#diff-f030ece7d283fb7aa3006f6dc075c5e36b96f04a756b0737f07d799c00312f71L52). How does this work currently? Do we no longer have to dispatch the loaders ourselves?

**Comment by Shane32** [comment]
The execution strategy detects return values of type `IDataLoaderResult<T>` and dispatches the data loader at the appropriate time.

**Comment by huysentruitw** [comment]
Alright, so I understand we no longer have to call the DispatchAllAsync method ourselves.

**Comment by Shane32** [comment]
Correct.  With the new design, deadlocks are impossible; you can chain data loaders or write asynchronous code before or after the data loader executes.  The execution strategy will always dispatch the data loaders at the appropriate time.

**Comment by huysentruitw** [comment]
> deadlocks are impossible

Is that an invitation? 😅

Anyway thanks for you quick reply, can close this.
