### ISSUE TITLE
I want to unit test the schema

### ISSUE THREAD

**Issue by jolienai** [graphql-dotnet/graphql-dotnet#2011]
Could you provide a way to unit test the schema or query? I don't want to create an integration test for it.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.Tests/Execution

**Comment by jolienai** [comment]
Hey @sungam3r ,  which file should I look into?

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/f6ad2eacd9e51b08fad6805e9226ec7326e1b5d7/src/GraphQL.Tests/Execution/MutationTests.cs#L279

**Comment by sungam3r** [comment]
Closed as answered.
