### ISSUE TITLE
Default constructor not found exception on IL2CPP builds

### ISSUE THREAD

**Issue by sidhants** [graphql-dotnet/graphql-dotnet#2013]
Hi,

I am trying to use this library with Unity3D + IL2CPP scripting. I have some simple code to execute a 'hello world!' query but it gives me the below mentioned errors when I build and run my apk on an Android device. The same code however works on a Windows build. What can cause this error ? Could it be related to using dynamics or any C# features, internally by this package, that are apparently not supported on IL2CPP mobile (Android/iOS) platforms?

UNITY C# CODE:
My 'Query' class has this method defined-

[GraphQLMetadata("hello")]
public String Hello()
{
  return "world!";
 }

QUERY CODE (works on Windows):
Query query = new Query();
string queryName = "hello";
var queryStr = "{" + queryName + "}";
var response = query.ExecuteQuery(queryStr).Result;
JObject json = JsonConvert.DeserializeObject(response) as JObject;
var result = json?.GetValue(queryName).Value<string>();
Debug.Log(result);

### Expected result

It should log "world!"

### Actual result

ERRORS:
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020-11-17 16:47:31.405 3321-3439/? I/Unity: Default constructor not found for type GraphQL.Types.NonNullGraphType`1[[GraphQL.Introspection.__TypeKind, GraphQL, Version=3.0.0.1490, Culture=neutral, PublicKeyToken=null]]
    <>c:<Hello>b__1_0()
    System.Net.Http.Headers.HttpHeaders:SetValue(String, T, Func`2)
    <>c:<Hello>b__1_0()
    System.Func`1:Invoke()
    System.Threading.Tasks.Task`1:InnerInvoke()
    System.Threading.Tasks.Task:Execute()
    System.Threading.ContextCallback:Invoke(Object)
    System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
    System.Threading.Tasks.Task:ExecuteWithThreadLocal(Task&)
    System.Threading.Tasks.Task:ExecuteEntry(Boolean)
    System.Threading.ThreadPoolWorkQueue:Dispatch()
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020-11-17 16:47:31.486 3321-3335/? E/Unity: JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
      at Newtonsoft.Json.JsonTextReader.ParseValue () [0x00000] in <00000000000000000000000000000000>:0 
      at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <00000000000000000000000000000000>:0 
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x00000] in <00000000000000000000000000000000>:0 
      at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0 
      at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <00000000000000000000000000000000>:0 
      at IL2CPPTest+<>c.<Hello>b__1_0 () [0x00000] in <00000000000000000000000000000000>:0 
      at System.Net.Http.Headers.HttpHea

### Environment
-GraphQL.3.0.0-preview-1490
-Unity 2019.1.8f1 (64-bit)
(Android Build with IL2CPP backend)

![image](https://user-images.githubusercontent.com/18451476/99473211-f90b3e80-28fe-11eb-91e8-be0e8ff3f3ac.png)

**Comment by Shane32** [comment]
I’m just thinking out loud here: If it’s an AOT compiler (ahead of time), it may need to know which types are required prior to compiling (not supporting generic types that are constructed at runtime), and so you couldn’t use schema first syntax at all but code first should work.

Or it could be something else entirely.

**Comment by sidhants** [comment]
> I’m just thinking out loud here: If it’s an AOT compiler (ahead of time), it may need to know which types are required prior to compiling (not supporting generic types that are constructed at runtime), and so you couldn’t use schema first syntax at all but code first should work.
> 
> Or it could be something else entirely.

That is possible. I will try giving code first a shot.

**Comment by sungam3r** [comment]
I've already seen such errors in other projects. Try this - https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347

**Comment by sidhants** [comment]
> I've already seen such errors in other projects. Try this - https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347
> 
> > The current asset is based on JSON .NET 8.0.3 with additional official fixes and Unity specific functionality added.

I tried the version from Asset Store but I still get the same error with the ctor not found. So it does seem like an AOT issue as @Shane32 mentioned. I will give the code first approach a shot next.

**Comment by Shane32** [comment]
If it turns out that code-first fixes the problem, and it is an AOT compilation issue, you probably won’t be able to use any of the field builders that rely on expression trees. Gut feeling is that with some time and effort you could work around whatever issues you come across, however.

**Comment by sidhants** [comment]
> If it turns out that code-first fixes the problem, and it is an AOT compilation issue, you probably won’t be able to use any of the field builders that rely on expression trees. Gut feeling is that with some time and effort you could work around whatever issues you come across, however.

Could you give me a basic example of a code first query for hello world?

public async void Hello()
    {
        ISchema schema = Schema.For(@"
          type Query {
            hello: String
          }
        ");

        var root = new { Hello = "Hello World!" };
        var result = await new DocumentExecuter().ExecuteAsync(_ =>
        {
            _.Schema = schema;
            _.Query = "{ hello }";
            _.Root = root;
        });
    }

**Comment by Shane32** [comment]
See “graphtype first approach” here : https://graphql-dotnet.github.io/docs/getting-started/introduction

**Comment by Shane32** [comment]
That sample has Field using expressions; you’ll need to use a Field overload that requires the name as a string along with a resolve parameter, passing in a field resolver.

**Comment by sidhants** [comment]
> That sample has Field using expressions; you’ll need to use a Field overload that requires the name as a string along with a resolve parameter, passing in a field resolver.

@Shane32  Thanks a lot for the info. I'm going to try this out and let you know if any issues.

**Comment by sungam3r** [comment]
@sidhants I believe that you have solved your problem.
