### ISSUE TITLE
migration 2.4->3.1.3 issue related to EnumerationGraphType

### ISSUE THREAD

**Issue by dBug404** [graphql-dotnet/graphql-dotnet#2014]
In 2.4. i wanted to enrich some enums with additional fields and had a graphtype which had an Enum as datasource and the same enum value as EnumerationGraphType<T> as field. This worked in 2.4. but in 3.1.3 it throws an InvalidOperationException.

Is this not supposed to be used like this anymore or is it a bug?

![image](https://user-images.githubusercontent.com/2844552/99520681-b2b3ef00-2993-11eb-9639-78d89f5350ed.png)

![image](https://user-images.githubusercontent.com/2844552/99520830-e5f67e00-2993-11eb-990d-8a2bbef0155a.png)

**Comment by dBug404** [comment]
The issue was that probably some default naming conventions changed and the Parent and the Field with the EnumerationGraphType now got the same name "ClassificationCategory". 

So an easy fix for me is to just set a custom name:
![image](https://user-images.githubusercontent.com/2844552/99526488-99af3c00-299b-11eb-9504-2d0d3536935f.png)

**Comment by sungam3r** [comment]
`GraphType` suffix from name is cut by default.

**Comment by dBug404** [comment]
Is there a way to disable that?

**Comment by sungam3r** [comment]
No, but you can always set your custom name in ctor.

**Comment by dBug404** [comment]
Thanks for your answers.

Yeah, it's easy to solve. But when you migrate a big codebase with a lot of graphs this is still a lot of work and risky, that still something will break.
Normally our client doesnt care about these name. But for the mutations the types of the parameters are specified in the client mutation and the are broke because of the suffix cut

![image](https://user-images.githubusercontent.com/2844552/99663448-eca1f580-2a66-11eb-8684-9a65eb4b5a50.png)

**Comment by sungam3r** [comment]
Done
