### ISSUE TITLE
 A field name must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but ..... does not.

### ISSUE THREAD

**Issue by MahdiElahi** [graphql-dotnet/graphql-dotnet#2015]
Hi 

i want set name for fields but cant set out of this pattern  **/^[_a-zA-Z][_a-zA-Z0-9]*$** 

`    Field(x=>x.Description).Name("حساب")`

my field name is : حساب 

how can i change this pattern ??

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/1949#issuecomment-716859165

**Comment by sungam3r** [comment]
Now you can set `NameValidator.Validation` and `NameValidator.ValidationOnSchemaInitialize` static properties.
