### ISSUE TITLE
Migrate a dictionnary from graphql 2.x to 3

### ISSUE THREAD

**Issue by Ramzidar85** [graphql-dotnet/graphql-dotnet#2018]
Hello,
I try to upgrade my project from 2.x to 3, i have a dictionnary field on my model

   ```
public Dictionary<string, bool> ShowBusinessLogo => new Dictionary<string, bool>() {
                                                                    { "main", this.IsLogoDisplayed(true) },
                                                                    { "other", this.IsLogoDisplayed(false) },
```

that i use on my type like this     
` Field(d => d.ShowBusinessLogo, nullable: true).Description("The BusinessLogo is show or not.");`

this field was serialized like  a string[] on the version 2 and return value like this:
![image](https://user-images.githubusercontent.com/74761436/99773650-0e55b800-2b0d-11eb-80c7-d1c59263770e.png)
![image](https://user-images.githubusercontent.com/74761436/99773227-6b9d3980-2b0c-11eb-98a0-e6a5ab681588.png)

In the version 3, this dictionnary is not supported . error: ``ArgumentOutOfRangeException: The type: Dictionary`2 cannot be coerced effectively to a GraphQL type ``
 how can i fix this if there's any workaround because i can't update all mobile applications versions to change the type from dictionnary to other type.

regards

**Comment by Shane32** [comment]
So it looks like although it may have been defined as a list of strings, it was actually returning a list of objects, each object containing a key and value.  So the "correct" way to fix the problem would be to define a graphtype for a `KeyValuePair<TKey, TValue>` (e.g. `KeyValuePairGraphType<TKey, TValue>`) and define `showBusinessLogo` to be a list of those graphs (e.g. `ListGraphType<KeyValuePairGraphType<string, bool>>`).  That should do the trick; returning data in exactly the same way as previously.  Of course the introspection query will be different now, but it was wrong before, as it didn't return a list of strings; it returned a list of objects.

**Comment by sungam3r** [comment]
Closed as answered.
