### ISSUE TITLE
Any way to debug schema builder?

### ISSUE THREAD

**Issue by alerdenisov** [graphql-dotnet/graphql-dotnet#202]
How can I debug my schema building process? I'm working on very huge and complicated schema with a lot of connections and union types and many times received exception such as: "Exception has been thrown by the target of an invocation". How can I know what exactly going wrong?

**Comment by joemcbride** [comment]
I am currently adding some instrumentation code, though you won't be able to use that yet.

Have you check for any inner exceptions in debug mode?  That sounds like some null references or something like that.

**Comment by alerdenisov** [comment]
I'm found "way" to debug. I just use DocumentValidator.Validate at begin of initializing my controller and throw Exception if document isn't valid. Work okay for me. 

But.. Let's return to DEBUG environment? If I'm throwing serialized exception I got detailed info (with InnerException), but as Response I just having message field. I guess, is it problem on my side?

**Comment by joemcbride** [comment]
The DocumentExecuter runs the DocumentValidator and does not execute if it is invalid.

Are you running into parse exceptions parsing a Query or errors trying to resolve a field?

The ExecutionResult has a list of exceptions that should have full stack traces.  Those stacktraces are not shown when serialized to JSON.

**Comment by joemcbride** [comment]
Going to close this, let me know if you have further questions.
