### ISSUE TITLE
NonNullable Connections

### ISSUE THREAD

**Issue by oliverlowbob** [graphql-dotnet/graphql-dotnet#2026]
Hey.
I'm working on a project, where we need to make non optional connections, and I can't really find anything on the subject.
I made the fields work with the NonNullableGraphType as shown beneath, but I have no luck getting the connections to be non nullable.
I've searched far and wide, and can't find anything about the issue, so I hope someone can help me here, as I'm completely lost.
The fields that are non nullable are written as such:

            Field<NonNullGraphType<OrderPresetGraphType>>(
                "preset",
                resolve: context => {
                    var loader = dataLoader.Context.GetOrAddBatchLoader<int, Base.Entities.Orders.OrderPreset>(
                        "OrderPresetById", orderPresetController.GetOrderPresetsByIdAsync
                    );

                    return loader.LoadAsync(context.Source.PresetId);
                }
            );
Sadly, the same method doesn't work with lists. 
Any help is much appreciated!

**Comment by Shane32** [comment]
What code are you using now for nullable connections?

**Comment by oliverlowbob** [comment]
> What code are you using now for nullable connections?

I've tried in the same way, as I got the Fields to work:

            Connection<NonNullGraphType<AssetFilterPresetFieldGraphType>>()
                .Name("fields")
                .Unidirectional()
                .Description("Returns a list of AssetFilterPresetFieldGraphType connected to this AsetFilterPresetGraphType")
                .ResolveAsync(async context =>
                {
                    var result = await assetFilterPresetController.GetFilterPresetFieldsByIdAsync(context.Source.Id)
                        .ConfigureAwait(false);

                    return ConnectionResolver.ToConnection(result.Data, context);
                });

**Comment by Shane32** [comment]
Looks good so far.  What problem are you seeing?

**Comment by oliverlowbob** [comment]
> Looks good so far. What problem are you seeing?

My front-end is not recieving the connection as non nullable, and I'm recieving errors, that the fields in the connection, that are set to non nullable, is returning null. Also, it's worth to mention that I'm working in .NET 4.7.2

**Comment by Shane32** [comment]
can you copy and paste the error message and stack trace?

**Comment by oliverlowbob** [comment]
The error I'm getting is from the fields, which are non nullable inside the connection:
Cannot return null for non-null type. Field: field, Type: AssetFilterPresetFieldGraphType!.

Type:
InvalidOperationException

Code:
-2146233079

Stack Trace:
ved GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) i /_/src/GraphQL/Execution/ExecutionStrategy.cs:linje 348
ved GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) i /_/src/GraphQL/Execution/ExecutionStrategy.cs:linje 251

Source:
GraphQL

Method:
Void ValidateNodeResult(GraphQL.Execution.ExecutionContext, GraphQL.Execution.ExecutionNode)

Base Exception:
System.InvalidOperationException: Cannot return null for non-null type. Field: field, Type: AssetFilterPresetFieldGraphType!.
ved GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) i /_/src/GraphQL/Execution/ExecutionStrategy.cs:linje 348
ved GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) i /_/src/GraphQL/Execution/ExecutionStrategy.cs:linje 251

I guess it's because it's parent is null, so it defaults to null as well.

My front-end needs to know, if its nullable or not, and with fields it gets the right information like this:
name: String! 

But with the connections, it doesn't, like this:
stages(after: String, first: Int): OrderPresetWorkflowStageConnection

And with the nonnullablegraphtype, it's only the items that becomes non-nullable, not the connection itself.

This is how it looks now:
type OrderPresetWorkflowGraphType {
  ...
  name: String!
  stages(after: String, first: Int): OrderPresetWorkflowStageConnection
}
type OrderPresetWorkflowStageActionConnection {
  totalCount: Int
  pageInfo: PageInfo!
  edges: [OrderPresetWorkflowStageActionEdge]
  items: [OrderPresetWorkflowStageActionGraphType]
}
type OrderPresetWorkflowStageActionEdge {
  cursor: String!
  node: OrderPresetWorkflowStageActionGraphType
}

And this is how I would want it to look:
type OrderPresetWorkflowGraphType {
  ...
  stages(after: String, first: Int): OrderPresetWorkflowStageConnection!
}
type OrderPresetWorkflowStageActionConnection {
  totalCount: Int!
  pageInfo: PageInfo!
  edges: [OrderPresetWorkflowStageActionEdge!]!
  items: [OrderPresetWorkflowStageActionGraphType!]!
}
type OrderPresetWorkflowStageActionEdge {
  cursor: String!
  node: OrderPresetWorkflowStageActionGraphType!
}

I hope it makes sense.

**Comment by Shane32** [comment]
You probably need to define your own connection types and logic. You can probably finesse the “stages” field to be non nullable, but I don’t think there’s a way to make “edges” and “items” and “totalCount” return the non nullable types you are looking for without rewriting the connection types.

**Comment by Shane32** [comment]
“node” should return the correct non nullable type.....

**Comment by oliverlowbob** [comment]
Ahh okay, thanks for the help! I'll look into it

**Comment by oliverlowbob** [comment]
I've tried to make my own connection type, and inject it, like I did with the one provided by GraphQL, through a ContainerBuilder, but I'm getting a ComponentNotRegisteredException. Do you have any idea how to solve this issue?

**Comment by sungam3r** [comment]
Register your GrtaphType in DI.

**Comment by oliverlowbob** [comment]
> Register your GraphType in DI.

If I understand what you're saying, then I've already done that, like this:
`        public class GraphQLEntityModule : Autofac.Module
        {
            protected override void Load(ContainerBuilder builder)
            {
                var assembly = Assembly.GetExecutingAssembly();

                builder.RegisterAssemblyTypes(assembly)
                   .Where(t => t.IsInNamespace("MediaCloud.API.GraphQL.Types"))
                   .SingleInstance();
            }
        }`

And I did it like this for the ConnectionType(McConnectionType) and EdgeType(McEdgeType), which works fine:
`            builder.RegisterGeneric(typeof(ConnectionType<>));
            builder.RegisterGeneric(typeof(EdgeType<>));`

But when I do the same for the new ConnectionType and EdgeType, I'm getting this:

_The requested service 'MediaCloud.API.GraphQL.Relay.McConnectionType`2[[MediaCloud.API.GraphQL.Types.Orders.OrderTerritoryGraphType, MediaCloudAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[MediaCloud.API.GraphQL.Relay.McEdgeType`1[[MediaCloud.API.GraphQL.Types.Orders.OrderTerritoryGraphType, MediaCloudAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], MediaCloudAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency._

**Comment by sungam3r** [comment]
Apparently there is some problem with registration in your container.

**Comment by oliverlowbob** [comment]
I figured it out.
I needed to add a , to the autofac registration like this:
```
builder.RegisterGeneric(typeof(McConnectionType<>)).SingleInstance();
builder.RegisterGeneric(typeof(McConnectionType<,>)).SingleInstance();
```

Thanks for the help!
