### ISSUE TITLE
Performance on graphql 3.1 vs graphql 2.4

### ISSUE THREAD

**Issue by Ramzidar85** [graphql-dotnet/graphql-dotnet#2027]
Hello,

i upgrated my project from graphql 2.4 to 3.1 and i tested both system.text.json and newtonsoft but i observed that the cpu increase and the response time increase too, so i decided to rollback after 1 hour it's a normal case?
Reponse time:
![image](https://user-images.githubusercontent.com/74761436/100254918-2aa98880-2f43-11eb-89ec-c42e6176ce10.png)
CPU:
![image](https://user-images.githubusercontent.com/74761436/100255214-883dd500-2f43-11eb-9740-808a73eb67f4.png)
![image](https://user-images.githubusercontent.com/74761436/100255292-a1468600-2f43-11eb-88ec-c24e4bb95521.png)

**Comment by Shane32** [comment]
Does not seem like it should be the case.  I thought that a number of performance improvements were made with 3.x, so I would expect it to be faster.  Everything else is the same I assume?  I might check that the same validation rules are running for both versions.  Do you use dataloaders?  Do you have any caching implementations for the parsing of queries?  Are you using the server project?

**Comment by sungam3r** [comment]
Are these graphs for newtonsoft.json or system.text.json?

**Comment by Ramzidar85** [comment]
These graph with the pic is system.text.json when i test with newtonsoft.json is a little bit worst.
Yes I use dataloaders, No cache for parsing queries. I don't use the server project:
this my startup conf:
```
 services.AddGraphQL(options =>
                         {
                             options.EnableMetrics = true;

                         })
                         .AddSystemTextJson()
                         .AddDataLoader(); 


```
`   // use HTTP middleware for ChatSchema at path /graphql
            app.UseGraphQL<ISchema>("/frontservices/navigation/graphql");

            // use graphql-playground at default url /ui/playground
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions { GraphQLEndPoint = "/frontservices/navigation/graphql" });
`

**Comment by sungam3r** [comment]
Just a note - GraphQL Playground polls graphql endpoint for schema by default. If someone opened browser it may affect tests. Check first if your clients request Playground endpoint. Also try to disable metrics (just to see if it give measurable effect).

Is your schema and types defined as singletons?

**Comment by Ramzidar85** [comment]
yes all my types as singletons:
`
            services.AddSingleton<IDocumentExecuter, SerialDocumentExecuter>();
            services.AddSingleton<IDocumentWriter, DocumentWriter>();
            services.AddScoped<ITracker, Tracker>();


            services.AddSingleton<CartType>();
            services.AddSingleton<LateralMenuSectionsType>();
            services.AddSingleton<HeaderType>();
            services.AddSingleton<LateralMenuSectionType>();
            services.AddSingleton<LateralMenuType>();`

**Comment by sungam3r** [comment]
Very strange.

**Comment by Ramzidar85** [comment]
seems Ok when i disable metrics

**Comment by sungam3r** [comment]
But your code using version 2.4 also worked with metrics? While disabling metrics certainly improves performance, the problem is still something else.

**Comment by Ramzidar85** [comment]
yes right!

**Comment by sungam3r** [comment]
Can you do the tracing with a performance profiler?

**Comment by Ramzidar85** [comment]
yes i try to profile

**Comment by sungam3r** [comment]
@Ramzidar85 Any news?

**Comment by sungam3r** [comment]
Closed as stale.
