### ISSUE TITLE
Can't run the web api project hosting the GraphiQL interface

### ISSUE THREAD

**Issue by geocine** [graphql-dotnet/graphql-dotnet#203]
This is what I did:

1. Clone the repository: 
   
		git clone git@github.com:graphql-dotnet/graphql-dotnet.git

2. From the `graphql-dotnet` root directory execute:

		npm install -g yarn
		
	Execute `yarn install`

		yarn install

	Output of `yarn install`

		yarn install v0.16.1
		info No lockfile found.
		[1/4] Resolving packages...
		warning eslint > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
		warning eslint-plugin-babel > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegEx
		p DoS issue
		[2/4] Fetching packages...
		warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
		info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
		[3/4] Linking dependencies...
		[4/4] Building fresh packages...
		[1/1] ⠠ fsevents: not ok
		[-/1] ⠐ waiting...
		[-/1] ⠐ waiting...
		[-/1] ⠐ waiting...
		error Error running install script for optional dependency: "C:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\node_m
		odules\\fsevents: Command failed.\nExit code: 1\nCommand: C:\\WINDOWS\\system32\\cmd.exe\nArguments: /d /s /c node-pre-g
		yp install --fallback-to-build\nDirectory: C:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\node_modules\\fsevents\n
		Output:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.29\nnode-pre-gyp info
		using node@6.6.0 | win32 | x64\nnode-pre-gyp info check checked for \"C:\\Users\\ACM\\Documents\\Projects\\graphql-dotne
		t\\node_modules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64\\fse.node\" (not found)\nnode-pre-gyp http GET http
		s://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-win32-x64.tar.gz\nnode-pre-gyp http 404 ht
		tps://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-win32-x64.tar.gz\nnode-pre-gyp ERR! Trie
		d to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-win32-x64.tar.gz \nnode
		-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.6.0 (node-v48 ABI) (falling back to source com
		pile with node-gyp) \nnode-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-bina
		ries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-win32-x64.tar.gz \n\r\nC:\\Users\\ACM\\Documents\\Projects\
		\graphql-dotnet\\node_modules\\fsevents>if not defined npm_config_node_gyp (node \"C:\\Users\\ACM\\AppData\\Roaming\\npm
		\\node_modules\\yarn\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" clean )  else (node  clean
		 ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.6.0 | win32 | x64\ngy
		p info ok \n\r\nC:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\node_modules\\fsevents>if not defined npm_config_no
		de_gyp (node \"C:\\Users\\ACM\\AppData\\Roaming\\npm\\node_modules\\yarn\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\nod
		e-gyp\\bin\\node-gyp.js\" configure --fallback-to-build --module=C:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\no
		de_modules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64\\fse.node --module_name=fse --module_path=C:\\Users\\ACM
		\\Documents\\Projects\\graphql-dotnet\\node_modules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64 )  else (node
		configure --fallback-to-build --module=C:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\node_modules\\fsevents\\lib\
		\binding\\Release\\node-v48-win32-x64\\fse.node --module_name=fse --module_path=C:\\Users\\ACM\\Documents\\Projects\\gra
		phql-dotnet\\node_modules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64 ) \r\ngyp info it worked if it ends with
		ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.6.0 | win32 | x64\ngyp ERR! configure error \ngyp ERR! stack Er
		ror: Can't find Python executable \"python\", you can set the PYTHON env variable.\ngyp ERR! stack     at failNoPython (
		C:\\Users\\ACM\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\lib\\configure.js:449:14)\ngyp ERR! s
		tack     at C:\\Users\\ACM\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\lib\\configure.js:404:11\
		ngyp ERR! stack     at C:\\Users\\ACM\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\graceful-fs\\polyfills.j
		s:264:29\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)\ngyp ERR! System Windows_NT 10.0.14393\ngyp ERR! com
		mand \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\ACM\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\
		yarn\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=C:\\\\Users\\\
		\ACM\\\\Documents\\\\Projects\\\\graphql-dotnet\\\\node_modules\\\\fsevents\\\\lib\\\\binding\\\\Release\\\\node-v48-win
		32-x64\\\\fse.node\" \"--module_name=fse\" \"--module_path=C:\\\\Users\\\\ACM\\\\Documents\\\\Projects\\\\graphql-dotnet
		\\\\node_modules\\\\fsevents\\\\lib\\\\binding\\\\Release\\\\node-v48-win32-x64\"\ngyp ERR! cwd C:\\Users\\ACM\\Document
		s\\Projects\\graphql-dotnet\\node_modules\\fsevents\ngyp ERR! node -v v6.6.0\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not
		ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback
		-to-build --module=C:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\node_modules\\fsevents\\lib\\binding\\Release\\n
		ode-v48-win32-x64\\fse.node --module_name=fse --module_path=C:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\node_mo
		dules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous>
		 (C:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\lib\\util\\co
		mpile.js:83:29)\nnode-pre-gyp ERR! stack     at emitTwo (events.js:106:13)\nnode-pre-gyp ERR! stack     at ChildProcess.
		emit (events.js:191:7)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)\nnode-pre-gyp ERR!
		stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)\nnode-pre-gyp ERR! System Windows_NT
		10.0.14393\nnode-pre-gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\ACM\\\\Documents\\\
		\Projects\\\\graphql-dotnet\\\\node_modules\\\\fsevents\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"insta
		ll\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd C:\\Users\\ACM\\Documents\\Projects\\graphql-dotnet\\node_modules\\f
		sevents\nnode-pre-gyp ERR! node -v v6.6.0\nnode-pre-gyp ERR! node-pre-gyp -v v0.6.29\nnode-pre-gyp ERR! not ok \nFailed
		success Saved lockfile.
		Done in 20.54s.

	Execute `yarn start`

		yarn start

	Output of `yarn start`

		yarn start v0.16.1
		$ webpack --progress                                                      Hash: aa06e1afa2caedd812c8
		Version: webpack 1.13.3
		Time: 3645ms
		    Asset     Size  Chunks             Chunk Names
		bundle.js  1.86 MB       0  [emitted]  bundle
		style.css    29 kB       0  [emitted]  bundle
		    + 299 hidden modules
		Child extract-text-webpack-plugin:
		        + 2 hidden modules
		Child extract-text-webpack-plugin:
		        + 2 hidden modules
		Done in 4.44s.

3. Open `graphql-dotnet\src\GraphQL.sln` and run it. I get the following error:

		Severity	Code	Description	Project	File	Line	Suppression State
		Error	CS0234	The type or namespace name 'Http' does not exist in the namespace 'GraphQL' (are you missing an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Bootstrapper.cs	2	Active
		Error	CS0234	The type or namespace name 'StarWars' does not exist in the namespace 'GraphQL' (are you missing an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Bootstrapper.cs	3	Active
		Error	CS0234	The type or namespace name 'Types' does not exist in the namespace 'GraphQL' (are you missing an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Bootstrapper.cs	6	Active
		Error	CS0246	The type or namespace name 'ISimpleContainer' could not be found (are you missing a using directive or an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Bootstrapper.cs	19	Active
		Error	CS0246	The type or namespace name 'IDocumentExecuter' could not be found (are you missing a using directive or an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Controllers\GraphQLController.cs	16	Active
		Error	CS0246	The type or namespace name 'IDocumentWriter' could not be found (are you missing a using directive or an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Controllers\GraphQLController.cs	17	Active
		Error	CS0246	The type or namespace name 'StarWarsSchema' could not be found (are you missing a using directive or an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Controllers\GraphQLController.cs	23	Active
		Error	CS0246	The type or namespace name 'ExecutionResult' could not be found (are you missing a using directive or an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Controllers\GraphQLController.cs	67	Active
		Error	CS0246	The type or namespace name 'ISchema' could not be found (are you missing a using directive or an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Controllers\GraphQLController.cs	68	Active
		Error	CS0246	The type or namespace name 'Inputs' could not be found (are you missing a using directive or an assembly reference?)	GraphQL.GraphiQL	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.GraphiQL\Controllers\GraphQLController.cs	72	Active
		Warning		The referenced component 'GraphQLParser' could not be found.	GraphQL.GraphiQL			
		Warning		Could not resolve this reference. Could not locate the assembly "GraphQL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	GraphQL.GraphiQL			
		Warning		The referenced component 'GraphQL' could not be found.	GraphQL.GraphiQL			
		Warning		Could not resolve this reference. Could not locate the assembly "GraphQL.StarWars". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	GraphQL.GraphiQL			
		Warning		The referenced component 'GraphQL.StarWars' could not be found.	GraphQL.GraphiQL			
		Warning		Could not resolve this reference. Could not locate the assembly "GraphQLParser". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	GraphQL.GraphiQL			
		Warning	NU1006	Dependencies in project.json were modified. Please run "dotnet restore" to generate a new lock file.	GraphQL.Tests	C:\Users\ACM\Documents\Projects\graphql-dotnet\src\GraphQL.Tests\project.lock.json	1	

Do I have to do some additional setup?

**Comment by joemcbride** [comment]
Sorry about that, yes it appears there are some reference issues in the GraphiQL web project.  I recently did a couple updates that broke this with a clean clone of the project.  It still worked on my machine due to how Visual Studio was referencing old DLLs in the bin folder.  I'll get this fixed.

**Comment by geocine** [comment]
@joemcbride  No worries. I do want to ask though if that yarn output is normal on windows?

**Comment by joemcbride** [comment]
This should be fixed on master now.

https://github.com/graphql-dotnet/graphql-dotnet/commit/3bc2f811d1f16f0e4e473cb3551ac11586c187d5

That is normal on windows with Yarn currently.  `fsevents` still fails if you use `npm install` it just doesn't give such a big error in the output.

**Comment by geocine** [comment]
Thank you

**Comment by joemcbride** [comment]
@geocine This looks like the related Yarn bug.  https://github.com/yarnpkg/yarn/issues/1285
