### ISSUE TITLE
Subscription with a controller

### ISSUE THREAD

**Issue by rayenmhamdi** [graphql-dotnet/graphql-dotnet#2038]
we have an existing project with graphql dotnet that contains queries and mutations.
we implement our controller to handle the requests and responses with a document execution.

and **we want to implement a hello world subscription via controller but with no luck**

I want to get the specif steps to up & run with subscription (PS i follow the documentation in https://graphql-dotnet.github.io/docs/getting-started/subscriptions but i doesn't help)

**Comment by sungam3r** [comment]
Did you see [server](https://github.com/graphql-dotnet/server/tree/master/src/Transports.Subscriptions.WebSockets) project?

**Comment by sungam3r** [comment]
Closed due to inactivity. @Shane32 may put some comments about using subscriptions from controllers. I think that it's better to use middle ware approach from the server project.

**Comment by Shane32** [comment]
This is a supported scenario for GraphQL.NET Server 7.x and documented here:

- https://github.com/graphql-dotnet/server#configuration-with-a-mvc-controller

There is a sample project using MVC controller here:

- https://github.com/graphql-dotnet/server/tree/master/samples/Samples.Controller

**Comment by sungam3r** [comment]
Ah, it's just a wrapper around middleware.

**Comment by Shane32** [comment]
Yes; it's the only practical way to support subscriptions via a MVC action.  We do have end-to-end tests that confirm that WebSocket connections are supported in this manner, so it does work for subscriptions.  Note that the middleware and options classes are instantiated for each request, so using the middleware may be slightly more performant.
