### ISSUE TITLE
Implicit field conversion from List<MyObject>

### ISSUE THREAD

**Issue by denis-troller** [graphql-dotnet/graphql-dotnet#2039]
## Summary
Using the following code:
```
public class AlarmsLog 
{
   public int TotalCount {get; set;}
   public List<AlarmLog> Alarms {get; set;}
}

public class AlarmLog {
  public Guid Id { get; set;}
  public bool Acknowledged {get; set;}
}

 public class AlarmsLogType : ObjectGraphType<AlarmsLog>
    {
        public AlarmsLogType()
        {
            Name = nameof(AlarmsLog);

            Field(c => c.TotalCount);
            Field(c => c.Alarms);
        }
    }

    public class AlarmLogType : ObjectGraphType<AlarmLog>
    {
        public AlarmLogType()
        {
            Name = nameof(AlarmLog);

            Field(c => c.Id);
            Field(c => c.Acknowledged);
        }
    }
```

If I have a  query exposing AlarmsLogType.
GraphQL reports a problem :
`The GraphQL type for Field: 'Alarms' on parent type: 'AlarmLog' could not be derived implicitly`

All my ObjectGraphType<> objects are registered as Singleton in the DI container.

I saw that GraphQL should be able to resolve fields of type List<T> from #336 and #359
 
Any idea why is it not working in my case ? 

### Environment (if relevant)

GraphQL nuget 3.1.6, .net5

**Comment by Shane32** [comment]
You'll need to register `AlarmLogType` in the `GraphTypeTypeRegistry`:
```cs
GraphTypeTypeRegistry.Register<AlarmLog, AlarmLogType>();
```

**Comment by denis-troller** [comment]
Aaaaaah perfect !
Just out of curiosity, is this mentioned anywhere in the docs ?
Anyway I'll close this issue, that will make my life much easier !

**Comment by Shane32** [comment]
It might not be; but it certainly should be.  @sungam3r do you know if it is?

If not, it would seem that we should add documentation to the linked page below, correct?

https://graphql-dotnet.github.io/docs/getting-started/schema-types

**Comment by sungam3r** [comment]
It will not be superfluous.

**Comment by Shane32** [comment]
Let's leave this issue open until we add documentation for this.  Thanks @denis-troller !

**Comment by sungam3r** [comment]
Let's make a note for it in v4 docs.

**Comment by Shane32** [comment]
Documentation has been added to https://graphql-dotnet.github.io/docs/getting-started/schema-types which will be updated once version 4.0 is published
