### ISSUE TITLE
Is there a way to be warned that a subscription was closed ?

### ISSUE THREAD

**Issue by denis-troller** [graphql-dotnet/graphql-dotnet#2040]
## Summary
I am trying to use the subscription, and it works wonderfully so far.
However, I need to know when the client closed the subscription (for whatever reason), so I can cleanup on the server side.
Is there a way to do that ?
I am not very familiar with the Reactive namespace...
I used SignalR in the past, which uses `ChannelWriter<T>` and `ChannelReader<T>` to model subscriptions, which does provide some signaling (including support for CancellationTokens) to handle that.

I found the HasObservers property on the ReplaySubject and managed to cobble something together, but it needs to account for publishing before the Observer has subscribed, which leads to ugly code...

Is there anything in GraphQL or Reactive for that problem ?

### Environment (if relevant)
.Net 5, GraphQL 3.1.6

**Comment by denis-troller** [comment]
Nevermind, 

I just realised I just need to implement my own `IObservable` / `IDisposable` object and all will be well.
Upon closing of the webSocket connection, GraphQL-Dotnet will dispose() the IObservable.

I will open a suggestion to add that to the docs though.

**Comment by Smiloh** [comment]
> Nevermind,
> 
> I just realised I just need to implement my own `IObservable` / `IDisposable` object and all will be well.
> Upon closing of the webSocket connection, GraphQL-Dotnet will dispose() the IObservable.
> 
> I will open a suggestion to add that to the docs though.

Hello,

Do you have any example?

Thank you

**Comment by flieks** [comment]
@denis-troller An example would be appreciated :). Tried implementing it but it is not an easy subject :)
