### ISSUE TITLE
Migrating a .net core 2.2 project to 3.1 causing problems in receiving request in the GraphQLController.

### ISSUE THREAD

**Issue by ankur4822** [graphql-dotnet/graphql-dotnet#2041]
Hey Guys I have been using GraphQL dotnet package for the last two years without any issue.

I am moving this API project from .net core-framework 2.2 to 3.1. I also updated the nuget package GraphQL to 3.2.0 and GraphiQL to 2.0.0.

There was a bunch of error that came which I was able to fix using this documentation link.https://graphql-dotnet.github.io/docs/migrations/migration3

However, I am stuck at one point.

The client for my GraphQL is a simple Frontend application built using React. The front end using Axios sends HTTP request to get the data from GraphQL.

On Backend Side All request comes to a controller which interprets the request based on the Query that is being supplied and calls the MapType and sends the response back.

My current controller

```
    [Route("api/[controller]")]
    public class GraphQLController : Controller
    {
        private readonly IDocumentExecuter _documentExecuter;
        private readonly ISchema _schema;
        private readonly CallContext _callContext;

        public GraphQLController(ISchema schema, IDocumentExecuter documentExecuter, CallContext callContext)
        {
            _schema = schema;
            _documentExecuter = documentExecuter;
            this._callContext = callContext;
        }


        [HttpPost]
        public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
        {
            if (query == null) { throw new ArgumentNullException(nameof(query)); }
            var inputs = query.Variables.ToInputs();


            var executionOptions = new ExecutionOptions
            {
                Schema = _schema,
                Query = query.Query,
                Inputs = inputs,
                Root = _callContext
            };

            var result = await _documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);

            if (result.Errors?.Count > 0)
            {
                return BadRequest(result);
            }

            return Ok(result);
        }
    }


```

The Query class:
```
 public class GraphQLQuery
    {
        public string OperationName { get; set; }
        public string NamedQuery { get; set; }
        public string Query { get; set; }
        public JObject Variables { get; set; }
    }

```
Schema

```
public class AppsSchema : Schema
    {
        public AppsSchema(IDependencyResolver resolver)
            : base(resolver)
        {
            Query = resolver.Resolve<AppsQuery>();
        }
    }

```

Another Query Class:

```
 public class AppsQuery : ObjectGraphType
    {
        public AppsQuery(
            ISdwanService sdwanService,
            IOptions<ApplicationConfiguration> config,
            ISolarwindsService solarwindsService,
            IHttpService httpService,
            IXcaService xcaService,
            IIntegrationLayerService integrationLayerService,
            CallContext callContext)
        {
            Field<ListGraphType<SiteMapType>>(
                "Sites",
                arguments: new QueryArguments(new QueryArgument<StringGraphType> { Name = "siteId" }),
                resolve: context =>
                {
                    var a = context.RootValue;
                    if (context.GetArgument<string>("siteId") == "")
                    {

                        return sdwanService.GetSitesByCustomer(callContext.AccountId);
                    }
                    else
                    {
                        List<SiteDTO> sites = new List<SiteDTO>();
                        sites.Add(new SiteDTO { SiteId = context.GetArgument<string>("siteId"), CallContext = (CallContext)context.RootValue });
                        return sites;
                    }
                });
}
}
```

Startup.cs 
```
var sp = services.BuildServiceProvider();
            services.AddSingleton<ISchema>(new AppsSchema(new FuncDependencyResolver(type => sp.GetService(type))));
```

All the changes that I was able to understand due to the framework upgrade I have done. I have the following problems

- **What should be the controller code looks like because I am getting an error on this line in the controller** 
`var inputs = query.Variables.ToInputs();`

**1. What should be the changes in stratup.cs file to support the changes for example to support the changes for Netwonsoft-library.**

I do want to make any changes on the front-end so the current way they send the request to the controller should be possible to make. 

A sample front end request where they send the query.

```
query: "{
	orders(orderId: 1234)
       {
           name,
           price,
          dateOfOrder
       }
}"
```

**Comment by sungam3r** [comment]
1. https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#aspnet-core

```c#
public class AppsSchema : Schema
    {
        public AppsSchema(IServiceProvider provider, AppsQuery query)
            : base(provider)
        {
            Query = query;
        }
    }
```

2.
```c#
var sp = services.BuildServiceProvider();
services.AddSingleton<ISchema>(new AppsSchema(new FuncDependencyResolver(type => sp.GetService(type))));
```
->
```c#
services.AddSingleton<ISchema, AppsSchema>();
```

GraphQL.NET 3.x does not have `IDependencyResolver` interface anymore. Probably you use https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.idependencyresolver?view=aspnet-mvc-5.2

3. 
> GraphiQL to 2.0.0

What is this?

**Comment by ankur4822** [comment]
@sungam3r  Thank you for your reply I have made changes suggested by you 
for startup.cs it should me this  which you correctly suggested.

 `services.AddSingleton<ISchema>(new AppsSchema(new FuncServiceProvider(type => sp.GetService(type))));`

**GraphiQL to 2.0.0 is the playground that I use to run my querys** 

Do you have any sample of how a controller should be after the migration I have added my current code in the question and I am stuck at that point? Please ask me if you need any clarification for the controller part.

**Comment by sungam3r** [comment]
> GraphiQL to 2.0.0 is the playground that I use to run my querys

Just provide a link to nuget package.

Samples repo: https://github.com/graphql-dotnet/examples/blob/master/src/AspNetWebApi/WebApi/Controllers/GraphQLController.cs

**Comment by ankur4822** [comment]
@sungam3r thank you for giving the sample of the controller.

Do we need to add in a startup.cs this AddSystemTextJson() or something else to enable the newton-soft-json extension.

**Comment by sungam3r** [comment]
DI approach: https://github.com/graphql-dotnet/server#configure
Manual: https://graphql-dotnet.github.io/docs/migrations/migration3#json-parsing-and-serialization
![изображение](https://user-images.githubusercontent.com/21261007/101748884-2605d800-3ade-11eb-905b-101e77a73c8a.png)

**Comment by Shane32** [comment]
@sungam3r This is the second question in a week that would help if we had a sample controller action in the codebase.  (The sample uses Asp.Net middleware.)  Also, I don't think the documentation covers typical integration with Asp.Net - either middleware or via controller action.  Unless I am missing some documentation that already exists, I think we should plan to add documentation describing how to integrate with Asp.Net Core, either via middleware or a controller action, and with Newtonsoft or System.Text.Json.

**Comment by sungam3r** [comment]
OK

**Comment by sungam3r** [comment]
You can supplement [these examples](https://github.com/graphql-dotnet/examples) and give a link to them from the main documentation.

**Comment by vikassharma5981** [comment]
@sungam3r  @ankur4822 , I followed the same steps as mentioned above in the example mentioned by the initiator of this thread, unfortunately, I am unable to run a query. I am getting a 404.
(index):113 POST http://localhost:55299/graphql 404 (Not Found)

Not sure what I am missing here, a hint can save a lot of time.

**Comment by sungam3r** [comment]
Closing.

**Comment by sungam3r** [comment]
@vikassharma5981 Post a new issue with a detailed description.

**Comment by joelmandell** [comment]
Doing this in a GraphQLController works fine for me:

```
[ApiController]
[Route("[controller]")]
public class GraphqlController : ControllerBase
{
    public async Task<IActionResult> Post([FromBody] GraphQLRequest q)
    {
      var schema = new GQLSchema();
      
      var queryResult = await new DocumentExecuter().ExecuteAsync(s => {
                s.Schema = schema;
                s.Query = q.Query;
                s.ValidationRules = validationRules;
                s.Listeners.Add(listener);
                s.Inputs = q.Variables.ToInputs();
                s.OperationName = q.OperationName;
      }).ConfigureAwait(false);
      
      var writer = new GraphQL.SystemTextJson.DocumentWriter();
      
      using (MemoryStream stream = new MemoryStream())
      {
          await writer.WriteAsync(stream, queryResult);
          var res = Encoding.UTF8.GetString(stream.ToArray());
          var jsonResult = JsonSerializer.Deserialize<dynamic>(res);
      
          return Ok(jsonResult);
      }
    }
}
```

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/examples/blob/master/src/AspNetWebApi/WebApi/Controllers/GraphQLController.cs#L37
