### ISSUE TITLE
Refactor ValueConverter usage from ScalarGraphTypes to avoid boxing

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2048]
Example:

```c#
 public class DecimalGraphType : ScalarGraphType
    {
        public override object ParseValue(object value) => ValueConverter.ConvertTo(value, typeof(decimal));

        public override object ParseLiteral(IValue value) => value switch
        {
            DecimalValue decimalValue => decimalValue.Value,
            StringValue stringValue => ParseValue(stringValue.Value),
            IntValue intValue => ParseValue(intValue.Value),  <-------- box int to object
            LongValue longValue => ParseValue(longValue.Value), <-------- box long to object
            FloatValue floatValue => ParseValue(floatValue.Value), <-------- box double to object
            BigIntValue bigIntValue => ParseValue(bigIntValue.Value), <-------- box BigInteger to object
            _ => null
        };
    }
```

ValueConverter uses direct explicit cast from one .NET type to other without boxing:
![изображение](https://user-images.githubusercontent.com/21261007/102024255-128a9380-3da2-11eb-8473-e0c75faf4faa.png)

Why is that? Is it possible to directly use explicit type casts in GraphTypes themselves? Surely yes. Do we still need `ValueConverter`?  Yes. Will using casts be a duplication of logic? I doubt it. I propose to use direct casts. See https://github.com/graphql-dotnet/graphql-dotnet/issues/2047#issuecomment-744063619

**Comment by Shane32** [comment]
I agree direct casts would be better here, and provide a performance benefit (as it would eliminate a dictionary lookup).  However, I fail to see how this has any effect on boxing.  `ParseLiteral` returns an `object`.  So it's going to get boxed sooner or later -- with the current code, within `ValueConverter.ConvertTo`, or with the suggested change, within `DecimalGraphType.ParseLiteral`.

**Comment by sungam3r** [comment]
We have typed `int` value in `IntValue`, then we pass it to `ParseValue` as `object`. I am talking about arguments, not about return values.

**Comment by sungam3r** [comment]
Of cource then this boxed value will be unboxed inside ValueConverter.

**Comment by Shane32** [comment]
I see.  This should be easy to fix.
