### ISSUE TITLE
resolve types using async method?

### ISSUE THREAD

**Issue by geocine** [graphql-dotnet/graphql-dotnet#205]
I could not use async

```
Field<CustomerType>(
    "customers",
    resolve: await context => //async method
);
```

The `resolve` parameter is defined

```
Func<ResolveFieldContext<TSourceType>, object> resolve = null
```

I need

```
Task<Func<ResolveFieldContext<TSourceType>, object>> resolve = null
```

Is there a way I could use async?

**Comment by joemcbride** [comment]
You could probably write your own extension method to allow this.

[Here's an example](https://github.com/graphql-dotnet/graphql-dotnet/blob/c5191c9b9db8090a411bf5026a8f87efe0066ee0/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L127-L141) of what one may look like.

**Comment by xplatsolutions** [comment]
Could you please elaborate on using async /await extending the Field<T> () method, it is very important in today's C# applications.

I tried the below but no luck of using it in my graphtype

'''
public static class ObjectGraphTypeExtensions
    {
        public static void Field<TGraphType>(
            this IObjectGraphType obj,
            string name,
            IGraphType type,
            Task<Func<ResolveFieldContext, object>> resolve = null)
        {
            var field = new FieldType();
            field.Name = name;
            field.Resolver = resolve != null ? new FuncFieldResolver<object>(context => resolve) : null;
            obj.AddField(field);
        }
    }
'''

**Comment by joemcbride** [comment]
Something like:

```
            var root = new ObjectGraphType();
            root.Name = "Root";
            root.FieldAsync("", null, resolve: async context =>
            {
                await Task.Run(()=> {});
                return new SomeObject();
            });
```

```
        public static void FieldAsync(
            this IObjectGraphType obj,
            string name,
            IGraphType type,
            Func<ResolveFieldContext, Task<object>> resolve = null)
        {
            var field = new FieldType();
            field.Name = name;
            field.ResolvedType = type;
            field.Resolver = resolve != null ? new FuncFieldResolver<object>(resolve) : null;
            obj.AddField(field);
        }
```

**Comment by xplatsolutions** [comment]
Thanks for the quick answer and great library.

I get compilation error in `field.ResolvedType = type;` looks like this property does not exist in FieldType in latest version, I'm using 0.13.0.562.

**Comment by joemcbride** [comment]
Sorry, that would be the "instance" based API I'm currently working on.  The following should work with what is currently published on Nuget.

```csharp
root.FieldAsync<StringGraphType, SomeObject>("name", resolve: async context =>
{
    await Task.Run(() => { });
    return context.Source.Name;
});
```

```csharp
public static FieldType FieldAsync<TGraphType, TSourceType>(
    this IObjectGraphType obj,
    string name,
    string description = null,
    QueryArguments arguments = null,
    Func<ResolveFieldContext<TSourceType>, Task<object>> resolve = null,
    string deprecationReason = null)
    where TGraphType : IGraphType
{
    return obj.AddField(new FieldType
    {
        Name = name,
        Description = description,
        DeprecationReason = deprecationReason,
        Type = typeof(TGraphType),
        Arguments = arguments,
        Resolver = resolve != null
            ? new FuncFieldResolver<TSourceType, Task<object>>(resolve)
            : null,
    });
}
```

It may not be apparent in the API, but you can return a `Task` from a resolver and the framework will `await` it.

```csharp
public class SomeObjectGraphType : ObjectGraphType<SomeObject>
{
    public SomeObjectGraphType()
    {
        Field<StringGraphType>("name", resolve: context =>
        {
            // this Task will get awaited
            return Task.Run(() => context.Source.Name);
        });
    }
}
```

**Comment by xplatsolutions** [comment]
Thanks, it worked now, I was very close, just my extension didn't appear until I add "this.", pff. I also noticed that somehow it was awaited because I was getting results, but, exceptions will be swallowed. 
Looks good now.

**Comment by geocine** [comment]
Thank you @joemcbride @xplatsolutions

**Comment by joemcbride** [comment]
> exceptions will be swallowed

@xplatsolutions  That doesn't sound good, I'll take a look at this.

**Comment by MisterJimson** [comment]
Sorry to comment on a closed issue, but do we still need to write our own extension method to support async/await in resolve?

**Comment by joemcbride** [comment]
FieldAsync has been added to the project.

**Comment by ajendrex** [comment]
Hello,

what about a `ConnectionAsync`? when defining a `NodeGraphType<MyClass>` class, I'd like aynchronously compute some connections; is that possible? how?

thanks
Hector.
