### ISSUE TITLE
Custom conversion of decimal to use , instead of .

### ISSUE THREAD

**Issue by NicolaiJee** [graphql-dotnet/graphql-dotnet#2054]
Hi
I just upgraded my GraphQL API to version 3.2.
In 2.40 we were using custom converter to handle decimal numbers with a comma instead of a dot.
But in the new version I am unable to register any converters.
And I just get this error.

GraphQL.Execution.UnhandledError: Error executing document.\r\n ---> System.FormatException: Input string was not in a correct format.\r\n   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)\r\n   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)\r\n   at System.Decimal.Parse(String s, NumberStyles style, IFormatProvider provider)\r\n   at GraphQL.ValueConverter.<>c.<.cctor>b__1_11(String value) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 39\r\n   at GraphQL.ValueConverter.<>c__DisplayClass7_0`2.<Register>b__0(Object v) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 219\r\n   at GraphQL.ValueConverter.TryConvertTo(Object value, Type targetType, Object& 

I have tried like this:
.AddJsonOptions(
                options => {
                    options.JsonSerializerOptions.Converters.Add(new JsonDecimal());
                    options.JsonSerializerOptions.Converters.Add(new JsonNullableDecimal());
                })
                
                ;
and like this 
  .AddSystemTextJson(
                options => {
                options.Converters.Add(new JsonDecimal());
                options.Converters.Add(new JsonNullableDecimal());
                }
                ) 
I have tried to google this problem but found no help.
I also checked the manuels and guide but found nothing.
I hope you guy can help me.

**Comment by sungam3r** [comment]
`ValueConverter.Register<string, decimal>(value => YOUR_CODE_HERE);`
![Uploading изображение.png…]()

**Comment by NicolaiJee** [comment]
It works, thank you.
