### ISSUE TITLE
Dynamic Schema Type Resolution

### ISSUE THREAD

**Issue by dbettin** [graphql-dotnet/graphql-dotnet#206]
I'm currently writing a DSL for schema creation. This DSL does not create any concrete types (e.g, DroidType, HumanType ...). It only creates object graph types and builds the fields directly on that type.

I can successfully create all of the types, but I am running into issues when the document executor tries to find these types on the schema because there is not a concrete type to lookup;  Essentially - I can not determine what instance to return when the `ResolveType` delegate is called on `Schema`.

Is there a way to return the correct object graph instance without relying on a concrete type?

**Comment by joemcbride** [comment]
With what is on Nuget and the master branch, no, there is not a way to do that.

I do have a branch where I believe you can do what you want though.  https://github.com/graphql-dotnet/graphql-dotnet/pull/192  That PR makes a core change to the engine to allow more dynamic types.

Does [this test](https://github.com/graphql-dotnet/graphql-dotnet/blob/c5191c9b9db8090a411bf5026a8f87efe0066ee0/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs) look like what you're trying to do?

**Comment by joemcbride** [comment]
The graph type still needs to be registered with the Schema, though you can create an instance of a type and register that with the Schema, vs. a concrete .NET Type.

**Comment by dbettin** [comment]
That looks great!  How does it do the instance resolution?

**Comment by dbettin** [comment]
Also, how close are you to merging this PR?

**Comment by joemcbride** [comment]
Right now it adds an additional field called `ResolvedType` in places that need it.  The core engine then uses that `ResolvedType` instance instead of the .NET Type.  Overall, it works just like it did before.  It still supports using .NET Types, the core engine is just smart enough to work with instances now.

I am pretty close to getting it merged, though you can use the nuget generated from CI:

Direct:  https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/build/0.13.0.573
Nuget feed: https://ci.appveyor.com/nuget/graphql-dotnet

**Comment by dlukez** [comment]
Here's something I've been working on:
https://github.com/dlukez/graphql-dotnet-annotations/

The more the merrier I suppose...

**Comment by tlil87** [comment]
@dbettin FYI:
>https://github.com/graphql-dotnet/conventions is up @drobertson123 @dlukez - i will provide more documentation for it soon. per now, the tests and example project are the best sources of information.

**Comment by joemcbride** [comment]
Closing this as the instance support is now in master.

**Comment by dbettin** [comment]
FYI - this worked wonderful for me.  Do you know when this will be published to nuget?

**Comment by dbettin** [comment]
I installed `0.13.1.601` and it is not finding `ResolvedType`.

**Comment by joemcbride** [comment]
Yes I haven't pushed a version to Nuget with these changes yet.  I will push a new nuget tomorrow.  It will be labeled 0.14.
