### ISSUE TITLE
Logging all queries and mutations

### ISSUE THREAD

**Issue by ninomllr** [graphql-dotnet/graphql-dotnet#2066]
I would like to add logging of all values that come to the GraphQL endpoint from any frontend and would like to have it on all fields (mutations, queries, subscriptions) and I would like to store all arguments that came from the frontend. Obviously there should be an option to turn it on/off depending on environments and so on. What is the best way to implement this with GraphQL.NET? 

I didn't really find a clear answer on what the best way to implement this on endpoint-level would be.

My guess is, that I would need to create a custom middleware. Is this correct? https://graphql-dotnet.github.io/docs/getting-started/field-middleware/

Another way that I found would be to add the code in UnhandledExceptionDelegate, but this would only log the errors and not all requests.

Before I start "hacking" something I would love to understand what the right way would be?

**Comment by Shane32** [comment]
On a simple level, all you need to do is log the incoming graphql request document string and variables string/object within your controller action or asp.Net middleware. I combined this functionality with a sliding cache for document AST representations (and sometimes query responses).

I don’t really think GraphQL.Net Middleware would work. It operates on a per-field level, rather than a per-request level. You could use a document listener, perhaps.

**Comment by sungam3r** [comment]
You can intercept request and graphql info in different ways:
1. ASP.NET (Core) custom middleware.
2. Inherit from `GraphQLHttpMiddleware` from [server](https://github.com/graphql-dotnet/server) project and override `RequestExecutingAsync`. See `GraphQLHttpMiddlewareWithLogs` fro mthe sample project.
3. Use custom document listener.
4. Use custom document executer, why not?

Most likely, this list can be continued further. I gave the most obvious options.

@Shane32 For option 4 we should make `DocumentExecuter.ExecuteAsync` virtual to allow override logic in descendants.

**Comment by Shane32** [comment]
> @Shane32 For option 4 we should make `DocumentExecuter.ExecuteAsync` virtual to allow override logic in descendants.

Good idea.  There's a number of methods within `ExecutionStrategy` that probably should also be virtual.

**Comment by ninomllr** [comment]
Sounds great, should I do a pull request for the `DocumentExecuter.ExecuteAsync` or do you want to do it?

**Comment by Shane32** [comment]
It would need to be against the `develop` branch as it changes the method signature.  (Correct, @sungam3r ?)  I can do it real quick.

**Comment by sungam3r** [comment]
> It would need to be against the develop branch as it changes the method signature. 

Well, making method virtual is not a breaking change. CLR makes `callvirt` call anyway.

**Comment by Shane32** [comment]
https://sriramsakthivel.wordpress.com/2015/03/07/c-compiler-doesnt-always-emits-a-virtual-call-callvirt/

**Comment by Shane32** [comment]
Even if the CLR does emit a `call`, it still probably wouldn't be a breaking change, since it would just run the same code it does now anyway.

**Comment by sungam3r** [comment]
> https://sriramsakthivel.wordpress.com/2015/03/07/c-compiler-doesnt-always-emits-a-virtual-call-callvirt/

Yes, I know it. I did not go into details so as not to complicate the discussion. In general, if we return to the discussion which branch (master/develop) this PR can be merged in, then I think the answer is both.

**Comment by sungam3r** [comment]
> Even if the CLR does emit a call, it still probably wouldn't be a breaking change, since it would just run the same code it does now anyway.

**Comment by Shane32** [comment]
Ok well I'll leave it just in the develop branch for now.  We should be near enough to 4.0 that it's of little consequence anyway.  And this isn't an immediate need, as far as I can tell, as it has multiple extremely easy workarounds.

If you think we should cherry-pick this into master, let me know and I'll handle the merge manually so it doesn't break anything.

**Comment by sungam3r** [comment]
Let's keep it as is. Regarding v4 I think New Year holidays will be the best time to work on delayed stuff. We can publish v4 in the middle of January.

**Comment by sungam3r** [comment]
Closed as answered.
