### ISSUE TITLE
IsTypeOf prioritize?

### ISSUE THREAD

**Issue by alerdenisov** [graphql-dotnet/graphql-dotnet#207]
How can I implement logic where some `ObjectGraphType` is the default and can be overridden by nested types?

I mean, I have the `BaseDocumentType` what must be returned if no one nested isn't fit to model object

**Comment by joemcbride** [comment]
I'm not sure I'm understanding what you're asking.  Can you elaborate and/or provide some code?

Would an [`InterfaceGraphType`](http://graphql.org/learn/schema/#interfaces) or [`UnionGraphType`](http://graphql.org/learn/schema/#union-types) fit your needs?

**Comment by alerdenisov** [comment]
Sure, I will. In few words I have `PublishedContentInterface : InterfaceGraphType<IPublishedContent>` and a default type: `PublishedContentType : ObjectGraphType<IPublishedContent>`. It works well as expected, but I want to provide way to create something like `PublishedWikiPageType : ObjectGraphType<IPublishedContent>` what will be returned if fit to model (`IsTypeOf = source => (source as IPublishedContent).Alias == "wikiPage"` for example) in any way it should return default `PublishedContentType` object

**Comment by alerdenisov** [comment]
Interface class 
```csharp
public class QLPublishedInterface : ExtendedInterfaceGraphType<IPublishedContent>
    {
        public QLPublishedInterface()
        {
            Name = "PublishedInterface";
            Description = "Published content graphql interface";
            // ... fields initialization
        }
    }
```

Default class
```csharp
    public class QLPublishedContentType : ObjectGraphType<QLPublishedContent>
    {
        public QLPublishedContentType()
        {
            Name = "PublishedContent";
            Description = "Published content graphql type";
            // ....fields 
            Interface<QLPublishedInterface>();
        }
    }
```

and for example special type:
```csharp

    public class PublishedWikiPageType :
        ObjectGraphType<QLPublishedContent>
    {
        public PublishedWikiPageType()
        {
            Name = "WikiPage";
            Description = "Wiki page type of the content";

            // ... base fields
            // extra wiki's fields

            Interface<QLPublishedInterface>();

            IsTypeOf = src =>
            {
                var published = (src as QLPublishedContent);
                if (published == null) return false;

                return published.DocumentTypeAlias == "wikiPage";
            };
        }
    }
```

**Comment by alerdenisov** [comment]
I need to something such as `LastChanceIsTypeOf` inside `QLPublishedContentType` or something such as `[TypePriority(int priority)]` and decide what type from list is best by attribute

**Comment by alerdenisov** [comment]
Right now I handle it by moving `RegisterType<PublishedWikiPageType>()` over base type registration, but it isn't' a perfect solution as I think.

**Comment by joemcbride** [comment]
`ResolveType` may work for you.  `IsTypeOf` is preferred in most cases since that makes it easier.  When you need more detailed logic, `ResolveType` may be a better choice.  The caveat is that `ResolveType` has to be exhaustive, so your Union or Interface has to know every possible type that it can be returned.

**Comment by joemcbride** [comment]
Going to close this, let me know if you have further questions.
