### ISSUE TITLE
New project is missing schema in GraphiQL and tries to query a field from the wrong query

### ISSUE THREAD

**Issue by olaf-svenson** [graphql-dotnet/graphql-dotnet#2070]
I want to create a GraphQL API with .NET Core using the GraphQL and GraphiQL package. First of all I created two entities

```cs
    public sealed class User
    {
        public Guid Id { get; set; }
    }

    public sealed class Task
    {
        public Guid Id { get; set; }
    }
```

Based on that I created the representing graph types

```cs
    public sealed class TaskType : ObjectGraphType<Task>
    {
        public TaskType()
        {
            Name = nameof(Task);
            Field(task => task.Id).Description("The task id.");
        }
    }

    public sealed class UserType : ObjectGraphType<User>
    {
        public UserType()
        {
            Name = nameof(User);
            Field(user => user.Id).Description("The user id.");
        }
    }
```

and sample queries without database access yet. In memory data is fine for testing purposes

```cs
    public sealed class UserQuery : ObjectGraphType
    {
        private List<User> users = new List<User>();

        public UserQuery()
        {
            Field<ListGraphType<UserType>>(
                "users",
                "Returns a collection of users.",
                resolve: context => users);
        }
    }

    public sealed class TaskQuery : ObjectGraphType
    {
        private List<Task> tasks = new List<Task>();

        public TaskQuery()
        {
            Field<ListGraphType<TaskType>>(
                "tasks",
                "Returns a collection of tasks.",
                resolve: context => tasks);
        }
    }
```

I simply assign those queries to the schema query

```cs
    public sealed class UserSchema : GraphQL.Types.Schema
    {
        public UserSchema(UserQuery userQuery)
        {
            Query = userQuery;
        }
    }

    public sealed class TaskSchema : GraphQL.Types.Schema
    {
        public TaskSchema(TaskQuery taskQuery)
        {
            Query = taskQuery;
        }
    }
```

The following class represents the request body

```cs
    public sealed class GraphQLRequest
    {
        public string OperationName { get; set; }
        public string Query { get; set; }

        [JsonConverter(typeof(ObjectDictionaryConverter))]
        public Dictionary<string, object> Variables { get; set; }
    }
```

In `Startup` I call `app.UseGraphiQl()` and register the services

```cs
    serviceCollection
        .AddSingleton<IDocumentExecuter, DocumentExecuter>()
        .AddSingleton<IDocumentWriter, DocumentWriter>()
        .AddSingleton<UserQuery>()
        .AddSingleton<TaskQuery>()
        .AddSingleton<ISchema, UserSchema>()
        .AddSingleton<ISchema, TaskSchema>();
```

For incoming requests I created a simple controller endpoint for testing purposes

```cs
    [ApiController]
    [Route("[controller]")]
    public sealed class GraphQLController : Controller
    {
        private readonly ISchema _schema;
        private readonly IDocumentExecuter _documentExecuter;

        public GraphQLController(ISchema schema, IDocumentExecuter documentExecuter)
        {
            _schema = schema;
            _documentExecuter = documentExecuter;
        }

        public async Task<IActionResult> Post([FromBody] GraphQLRequest graphQlRequest)
        {
            ExecutionOptions executionOptions = new ExecutionOptions()
            {
                Schema = _schema,
                Query = graphQlRequest.Query,
                Inputs = graphQlRequest.Variables?.ToInputs()
            };

            ExecutionResult executionResult = await _documentExecuter.ExecuteAsync(executionOptions);

            if (executionResult.Errors != null)
                return BadRequest(executionResult);

            return Ok(executionResult);
        }
    }
```

When running the application I see is this

![image](https://user-images.githubusercontent.com/69137963/103354047-cc744600-4aaa-11eb-9acf-53ed83f887f2.png)

There is no schema available, although I would expect it to load both schemas. When I run this

    query {
      users{
        id
      }
    }

I get the error message

> Failed to fetch

when debugging it the exception message is

> Cannot query field "users" on type "TaskQuery".

Does someone know what's wrong here or what I'm missing?

**Comment by sungam3r** [comment]
1. You for some reason registered two schemas. Why?
```
   .AddSingleton<ISchema, UserSchema>()
        .AddSingleton<ISchema, TaskSchema>()
```

2. Change ` public UserSchema(UserQuery userQuery)` to use additional `IServiceProvider` parameter and pass it to `base()` ctor.

**Comment by olaf-svenson** [comment]
@sungam3r thanks!

> You for some reason registered two schemas. Why?

How would I assign the UserQuery and the TaskQuery to one schema then?

> Change public UserSchema(UserQuery userQuery) to use additional IServiceProvider parameter and pass it to base() ctor.

Ok, I updated it to

```cs
        public UserSchema(UserQuery userQuery, IServiceProvider serviceProvider) : base(serviceProvider)
        {
            Query = userQuery;
        }
```

**Comment by sungam3r** [comment]
```
public sealed class Query : ObjectGraphType
    {
        private List<User> users = new List<User>();
        private List<Task> tasks = new List<Task>();
        
        public Query()
        {
            Field<ListGraphType<UserType>>(
                "users",
                "Returns a collection of users.",
                resolve: context => users);
            Field<ListGraphType<TaskType>>(
                "tasks",
                "Returns a collection of tasks.",
                resolve: context => tasks);        
       }
    }
```

**Comment by olaf-svenson** [comment]
As far as I understood each query is a definition of "endpoints". I wanted to split it because this query might get really big for real applications, no?

Do I really have to put all the fields from the whole API into this single query?

**Comment by sungam3r** [comment]
Please read https://graphql.org/learn/ and https://graphql.org/learn/best-practices/ first to do things right way.

**Comment by olaf-svenson** [comment]
@sungam3r yes, I tested some playgrounds and got to know about the fields. I know that the business logic should not exist in that  query class. But still, mixing the user resource with the task resource might get messy really quick, no?

**Comment by sungam3r** [comment]
You can organize your API as you like. You can have 2 or 200 fields. They can be located at the same level or in a complex hierarchy of 10 levels. It depends on you. But all this is a **single** schema. You can place business logic in other projects/files/modules. This is not important at all and is a matter of taste.

**Comment by sungam3r** [comment]
>  There is no schema available, although I would expect it to load both schemas

Once more time - you misconfigure your app.

```
.AddSingleton<ISchema, UserSchema>()
        .AddSingleton<ISchema, TaskSchema>()
```

Only the last schema works now for you - `TaskSchema` so of course you can not query `users` field.

**Comment by olaf-svenson** [comment]
@sungam3r yes, your second comment is clear.

But please let me ask once more, I have only one schema so I can have only one query as shown here

https://github.com/graphql-dotnet/graphql-dotnet/issues/2070#issuecomment-752636897

I can't have multiple queries, one per resource?

**Comment by sungam3r** [comment]
What does _query_ mean for you? `ObjectGraphType` is just ordinary graphq type which is used as _root query_ graphq type. It may have 1 field, 2 or 1000.
