### ISSUE TITLE
Add tests for SetSubFieldNodes and SetArrayItemNodes

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2073]
- Should verify that the generated child nodes have their values set correctly, specifically:
  - `Parent`
  - `GraphType`
  - `ResolvedType`
- Should verify operation with graphs containing lists of lists, and various combinations of nullable and non-nullable fields.

See #2064

**Comment by sungam3r** [comment]
@Shane32 Is it still actual?

**Comment by Shane32** [comment]
I'm sorry, I can't remember anymore.  Looking at my notes, it seemed that I thought I had fixed a bug, but the simple tests I had written couldn't verify that it had previously been a bug.  I'm fine with closing this.
