### ISSUE TITLE
Remove StatsReport?

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2076]
I suggest we remove `StatsReport` or at least mark it deprecated.  It is not used by any other code, there are no samples for it, and there are no tests for it.  It does not appear ever to even have been completed -- for instance, the `Types` property always returns `null` because of this code:

```cs
        public static Type[] TypesFromSchema(ISchema schema)
        {
            return null;
        }
```

It was first written by @joemcbride on Nov 16, 2016 and has never been updated since then.  It's only 130 lines of code if someone needs to copy it into their own project.

@sungam3r @joemcbride  do you know if this is used at all?  Can/should we remove it?

**Comment by sungam3r** [comment]
Agree. I have seen this code before and it seems to me that I even removed it in some of my PRs (possibly canceled).
