### ISSUE TITLE
Metrics does not record time within data loaders.

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2077]
Metrics for field resolvers is recorded via middleware, which is not data-loader aware.

Potential fix:
- Middleware calls original field resolver
- If of type IDataLoaderResult, postpones disposing of the `Marker` until the data loader completes, via `DataLoaderExtensions.Then`. Repeats process if another data loader is returned, etc.
- If not, or if an error has occurred, disposes of `Marker` object.

**Comment by sungam3r** [comment]
Looks reasonable. May be tracked as `bugfix`.

**Comment by Shane32** [comment]
Can be fixed in 4.1

**Comment by Shane32** [comment]
Fixed by:
- #3691
