### ISSUE TITLE
Connection.TotalCount is not nullable

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2084]
The description for `ConnectionType`'s `totalCount` field is as follows:

> A count of the total number of objects in this connection, ignoring pagination. This allows a client to fetch the first five objects by passing "5" as the argument to `first`, then fetch the total count so it could display "5 of 83", for example. In cases where we employ infinite scrolling or don't have an exact count of entries, this field will return `null`.

This field pulls from the `TotalCount` property of the source object. The object provided for this purpose is `Connection<TNode, TEdge>`, but it's `TotalCount` property is an `int`, not `int?`.  (It is of course possible to use `ConnectionType` with another source object.)

```cs
    public class Connection<TNode, TEdge>
        where TEdge : Edge<TNode>
    {
        public int TotalCount { get; set; }
        ...
    }
```

I propose to change the signature to an `int?` in version 4.0 so that it can allow null return values as the description says.

Note that while very useful, the relay spec doesn't appear to cover `totalCount` at all.  Maybe I'm looking in the wrong spot.

https://relay.dev/docs/en/graphql-server-specification.html

**Comment by sungam3r** [comment]
I haven't worked with relay yet. I have nothing to say.
