### ISSUE TITLE
Move IHaveDefaultValue.Type to IProvideResolvedType.Type?

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2090]
Why does `IHaveDefaultValue` have a property called `Type`?  This represents the .Net type of the graph type within `ResolvedType`.  I don't understand the connection.  Note that this is not the .Net type of the value stored within `DefaultValue`. (Unless I missed something.)

Perhaps the `Type` property should be moved to another interface.  I'll be doing more research on this later.

**Comment by sungam3r** [comment]
I also noticed this before, but left it as it is. I suspect this is one of the design flaws.
