### ISSUE TITLE
ExecutionContext.Errors is not thread safe

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2105]
This is pretty obvious since a single instance of `ExecutionContext` is passed to execution strategy (more specifically, parallel) and `ExecutionErrors` stores errors in the not thread safe `List<ExecutionError>`.

**Comment by Shane32** [comment]
This should be fixed in 3.3.0 for sure

**Comment by sungam3r** [comment]
The same for `Extensions`.

**Comment by sungam3r** [comment]
Well, actually it applies to any writable property in context. This does not mean that everything from context needs to be made thread safe. But something definitely needs to be done thread-safe and properly documented.

**Comment by sungam3r** [comment]
@Shane32 Regarding my comment
> The same for `Extensions`.

In #2327 I suggested to remove `Extensions` initialization.
