### ISSUE TITLE
Validate directive, enum and type names

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2123]
see https://github.com/graphql-dotnet/graphql-dotnet/issues/1840#issuecomment-719846988

**Comment by Shane32** [comment]
@sungam3r Done with this now?

**Comment by sungam3r** [comment]
No. We haven't done these checks yet.

**Comment by sungam3r** [comment]
I looked at my comment https://github.com/graphql-dotnet/graphql-dotnet/issues/1840#issuecomment-719846988 one more time and I think I was wrong. Name converter works with field names ang argument names but not with type names. The type names are already checked.
