### ISSUE TITLE
File Uploads with GraphQL endpoint

### ISSUE THREAD

**Issue by jlebensold** [graphql-dotnet/graphql-dotnet#213]
Hi there,

This library has been a joy to use! Just a quick question about how I can implement a file endpoint like so:
http://stackoverflow.com/questions/33060182/how-would-you-do-file-uploads-in-a-react-relay-app

I'm assuming that a special `FileGraphType` would need to be implemented along with the relevant mutation. Does anyone have a concrete example?

**Comment by jlebensold** [comment]
See http://stackoverflow.com/questions/40547164/file-upload-with-relay-and-graphql-dotnet/40553857#40553857

**Comment by hnviradiya** [comment]
what if I want to access files using graphql conventions?
