### ISSUE TITLE
Dynamic GraphObjectTypes

### ISSUE THREAD

**Issue by ninomllr** [graphql-dotnet/graphql-dotnet#2132]
I know that GraphQL is strongly-typed, so this is maybe impossible. I would still like to hear your feedback on how to handle our current use case.

We are wrapping a REST interface in our .NET Middleware and forward most of the data through GraphQL.NET to the frontend. The backend has some objects that look like this:

```
{ 
  "type": "hello-world",
  "value": "myValue"
}
```

Those can be inputs or outputs actually. Now the problem that we have is that the REST API used the value field to accept boolean, string or integer, meaning the way it is handled actually changes dynamically. It sometimes is used like this:

```
{ 
  "type": "hello-number",
  "value": 1000
}
```

Our current implementation always uses string for inputs/outputs on the value parameter, and we cast in the backend. It would be nicer though if we could accept inputs as either boolean, string or integer on the same field (meaning dynamic type). Is this possible in GraphQL at all? If yes, how would this be done?

**Comment by sungam3r** [comment]
I think that you just have to provide the desired conversion in your REST API if it wraps GraphQL.NET specific bits.

**Comment by sungam3r** [comment]
Closed due to inactivity.
