### ISSUE TITLE
“INVALID_OPERATION” error with GraphQL.Net library in .NET Core 3.0

### ISSUE THREAD

**Issue by galenam** [graphql-dotnet/graphql-dotnet#2140]
## Summary
I have a problem with GraphQL.Net library. I'm trying to see how it works and I created a simple class:0
```c#
public class Temp
{
    public int MyProperty { get; set; }
}


public class TempType : ObjectGraphType<Temp>
{
    public TempType()
    {
        Name = "TEmp";
        Field(t => t.MyProperty).Description("temp");
    }
}
public class SolDataQuery : ObjectGraphType
{
    public SolDataQuery(ISolDataFill sdFill)
    {
        Name = "Query";
        Field<IntGraphType>("soldata", resolve: context => 5);
        Field<TempType>("wheater", resolve: context => new Temp { MyProperty = 2 });
    }
}
```
After start in playground I requested a query : { wheather {myProperty}} and I saw: "message": "Error executing document.", "code": "INVALID_OPERATION". If I changed my code and comment line "Field("wheater", resolve: context => new Temp { MyProperty = 2 });" I requested a query {soldata} and saw the correct result "5". Could anybody tell me, please, where is my errors?
### Environment (if relevant)
I've used "GraphQL" Version="3.2.0", "GraphQL.Server.Ui.Playground" Version="4.4.0" and TargetFramework = netcoreapp3.0

**Comment by sungam3r** [comment]
> Field(t => t.MyProperty)

How does it compile? Your TempType is not generic.

**Comment by galenam** [comment]
@sungam3r  I'm sorry for my formatting. It's generic.

**Comment by sungam3r** [comment]
Please show your Schema derived type and startup.

**Comment by galenam** [comment]
Hello, @sungam3r . If I correct understand you comment, this is you asked for :
`public class Startup
    {
        public IConfiguration Configuration { get; set; }

        public Startup(IConfiguration conf)
        {
            Configuration = conf;
        }


        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<AppSettings>(Configuration.GetSection(AppSettings.SectionName));
            services.AddSingleton<ISolDataFill, SolDataFill>();
            services.AddSingleton<ISchema, SolSchema>();
            services.AddSingleton<SolDataQuery>();
            services.AddSingleton<SolDataMutation>();

            services.AddMemoryCache();
            services.AddHttpContextAccessor();

            services.Configure<KestrelServerOptions>(options =>
    {
        options.AllowSynchronousIO = true;
    });

            services.AddGraphQL(options =>
            {
                options.EnableMetrics = true;
            })
            .AddNewtonsoftJson(deserializerSettings => { }, serializerSettings => { })
            .AddUserContextBuilder(httpContext => new GraphQLUserContext { User = httpContext.User });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ISolDataFill sdf)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseGraphQL<ISchema>();
            app.UseGraphQLPlayground();
        }
    }`

`public class SolSchema : Schema
    {
        public SolSchema(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            Query = serviceProvider.GetRequiredService<SolDataQuery>();
            Mutation = serviceProvider.GetRequiredService<SolDataMutation>();
        }
    }`

`public class SolDataMutation : ObjectGraphType {
        public SolDataMutation() {
            Name = "Mutation";
        }
    }`

**Comment by sungam3r** [comment]
Add `.AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true)` after `AddGraphQL` call. It allows you to see the root cause of error.

**Comment by galenam** [comment]
@sungam3r  Thank you! I fotgot to add TempType to ServiseProvider
