### ISSUE TITLE
Subscription is not properly working for hot observables (IObservable collection)

### ISSUE THREAD

**Issue by MatheswaranSagadevan** [graphql-dotnet/graphql-dotnet#2142]
## Description

How to return list of observables immediately one by one using reactive programming.

### My sample Code:
```c#
 private readonly ISubject<PointData> pointDataSubject= new Subject<PointData>();
    private IObservable<PointData> WhenUpdated { get => this.pointDataSubject.AsObservable(); set { } }
 gtObj.AddField(
        new EventStreamFieldType
        {
.....
 Subscriber = new EventStreamResolver<PointData>(context =>
          {
            var subReq = context.GetArgument<SubscribeRequest>("subscribeReq");
   filterIds = ---some filter logic here ----
foreach (var point in filterIds  )
      {
        var pointData = new PointData
        {
          Id = point,
          Status = "UnAuthorized Point",
          Value = string.Empty
        };
        pointDataSubject.OnNext(pointData);       
      }     
return WhenUpdated ;
    }
}
```
### Expected result

All the list of points sent through OnNext() should return in response.

### Actual result

only one or very few is coming in response.

**Comment by Shane32** [comment]
There had been some issues with the prior version of GraphQL.NET Server which have been fixed now with a complete rewrite.  One issue, I believe, was related.  In any case, please open a new issue if this continues to be a problem with GraphQL.NET Server 7.
