### ISSUE TITLE
Document bypass validation feature

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2148]
See https://github.com/graphql-dotnet/graphql-dotnet/pull/1964

**Comment by Shane32** [comment]
@sungam3r Can we have a description added to this issue/feature request?

**Comment by sungam3r** [comment]
Honestly, I forgot. I think this one is about documentation only since I see nice-to-document tag. In #1964 we added static options in `NameValidator`:
![изображение](https://user-images.githubusercontent.com/21261007/233865585-e475d308-f5d0-437f-aebb-d817e4db0faf.png)


Perhaps this issue is not important and can be closed. Or you may add a little note about `NameValidator` into docs. As you see fit.
