### ISSUE TITLE
Fix for variable coercion

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2149]
See `Add test for variable coercion` (#1919)

**Comment by Shane32** [comment]
Has this been fixed with the new variable parsing code in #2165 @sungam3r ?

**Comment by Shane32** [comment]
I'm thinking we noted there was a bug about a week before I rewrote the variable parsing code, and forgot to close the issue.

**Comment by sungam3r** [comment]
Nope. Fix is needed. I will publish PR soon.

**Comment by sungam3r** [comment]
Fixed in #2341
