### ISSUE TITLE
Problems with the GraphQL.SystemTextJson package

### ISSUE THREAD

**Issue by olaf-svenson** [graphql-dotnet/graphql-dotnet#2155]
I created a new ASP .NET Core 5.0 Web API project and installed the packages GraphQL, GraphiQL and GraphQL.SystemTextJson.

I modified the launchSettings.json file to use `"launchUrl": "graphql"`.

I created a user entity

```cs
    public sealed class User
    {
        public Guid Id { get; set; }
    }
```

with a representing graph type

```cs
    public sealed class UserType : ObjectGraphType<User>
    {
        public UserType()
        {
            Name = nameof(User);
            Field(user => user.Id).Description("The user id.");
        }
    }
```

The `GraphQLQuery` holds one action for testing purposes

```cs
    public sealed class GraphQLQuery : ObjectGraphType
    {
        private readonly List<User> _users = new List<User>();

        public GraphQLQuery()
        {
            Field<ListGraphType<UserType>>(
                "users",
                "Returns a collection of users.",
                resolve: context => _users);
        }
    }
```

and the `GraphQLSchema` registers it

```cs
    public sealed class GraphQLSchema : GraphQL.Types.Schema
    {
        public GraphQLSchema(GraphQLQuery graphQLQuery, IServiceProvider serviceProvider) : base(serviceProvider)
        {
            Query = graphQLQuery;
        }
    }
```

In the startup file in the `ConfigureServices` I added this code to register all the required services before calling `services.AddControllers()`

```cs
        services
                .AddSingleton<IDocumentExecuter, DocumentExecuter>()
                .AddSingleton<IDocumentWriter, DocumentWriter>()
                .AddSingleton<ISchema, GraphQLSchema>()
                .AddSingleton<GraphQLQuery>();
```

and in the `Configure` method I call `app.UseGraphiQl()` at first.

I created a `GraphQLRequest` DTO for all the incoming requests

```cs
    public sealed class GraphQLRequest
    {
        public string OperationName { get; set; }
        public string Query { get; set; }

        [JsonConverter(typeof(ObjectDictionaryConverter))]
        public Dictionary<string, object> Variables { get; set; }
    }
```

and lastly I added the `GraphQLController` for requests

```cs
    [ApiController]
    [Route("[controller]")]
    public sealed class GraphQLController : Controller
    {
        private readonly ISchema _schema;
        private readonly IDocumentExecuter _documentExecuter;

        public GraphQLController(ISchema schema, IDocumentExecuter documentExecuter)
        {
            _schema = schema;
            _documentExecuter = documentExecuter;
        }

        public async Task<IActionResult> Post([FromBody] GraphQLRequest graphQlRequest)
        {
            ExecutionOptions executionOptions = new ExecutionOptions()
            {
                Schema = _schema,
                Query = graphQlRequest.Query,
                Inputs = graphQlRequest.Variables?.ToInputs()
            };

            ExecutionResult executionResult = await _documentExecuter.ExecuteAsync(executionOptions);

            if (executionResult.Errors != null)
                return BadRequest(executionResult);

            return Ok(executionResult);
        }
    }
```

When running the appliaction it opens this url

> https://localhost:44343/graphql/

but unfortunately I get the following error message

> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues. Path: $.Errors.InnerException.TargetSite.DeclaringType.
>  ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues.
>    at System.Text.Json.Serialization.Converters.TypeConverter.Write(Utf8JsonWriter writer, Type value, JsonSerializerOptions options)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonSerializer.WriteAsyncCore[TValue](Stream utf8Json, TValue value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
>    at GraphiQl.GraphiQlMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> 
> HEADERS
> =======
> Accept: application/json
> Accept-Encoding: br, gzip, deflate
> Accept-Language: en
> Connection: close
> Content-Length: 1554
> Content-Type: application/json
> Host: localhost:44343
> Referer: https://localhost:44343/
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
> sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"
> sec-ch-ua-mobile: ?0
> origin: https://localhost:44343
> sec-fetch-site: same-origin
> sec-fetch-mode: cors
> sec-fetch-dest: empty

does someone know what is wrong or missing?

**Comment by olaf-svenson** [comment]
never mind, I had to add the graph types to the DI container

**Comment by Shane32** [comment]
You need to serialize the result using the DocumentWriter instead of letting MVC serialize it with `Ok(executionResult)`.  Unfortunately we don't have a sample of doing so with a MVC controller action within the documentation.

You need something like this:

```cs
    HttpContext.Response.ContentType = "application/json";
    HttpContext.Response.StatusCode = 200; // OK
    var writer = new GraphQL.SystemTextJson.DocumentWriter();
    await writer.WriteAsync(HttpContext.Response.Body, executionResult);
```

The reason it may be working now is that there's no errors being serialized.  The first time your response contains an error, you'll be back to the same problem again.  Whereas the `DocumentWriter` has code to correctly serialize errors.

**Comment by priteshacharya** [comment]
@Shane32 Do you have the documentation to serialize the result using the DocumentWriter now or planning to add it in future? I'm running through serialization issue during exception.

**Comment by Shane32** [comment]
What is the scenario? ASP.Net Core MVC via a controller action?

**Comment by priteshacharya** [comment]
@Shane32 yes, ASP.NET CORE MVC. It's for a controller action for GraphQL. When I have exception in the controller action method, it throws `System.NotSupportedException: Serialization and deserialization of 'System.Type'` error. I have tried adding JsonConverter for most of the types, but it keeps giving me that error.

**Comment by Shane32** [comment]
(the entire controller action code, with sensitive information removed)
