### ISSUE TITLE
Add sample controller action to docs

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2157]
@sungam3r This is the second question in a week that would help if we had a sample controller action in the codebase.  (The sample uses Asp.Net middleware.)  Also, I don't think the documentation covers typical integration with Asp.Net - either middleware or via controller action.  Unless I am missing some documentation that already exists, I think we should plan to add documentation describing how to integrate with Asp.Net Core, either via middleware or a controller action, and with Newtonsoft or System.Text.Json.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/issues/2041#issuecomment-751131049_

**Comment by Shane32** [comment]
Also see #2155

**Comment by joelmandell** [comment]
Maybe something like this (obviously could be improved, but something to start with):

```
[ApiController]
[Route("[controller]")]
public class GraphqlController : ControllerBase
{
    public async Task<IActionResult> Post([FromBody] GraphQLRequest q)
    {
      var schema = new GQLSchema();
      
      var queryResult = await new DocumentExecuter().ExecuteAsync(s => {
                s.Schema = schema;
                s.Query = q.Query;
                s.Inputs = q.Variables.ToInputs();
                s.OperationName = q.OperationName;
      }).ConfigureAwait(false);
      
      var writer = new GraphQL.SystemTextJson.DocumentWriter();
      
      using (MemoryStream stream = new MemoryStream())
      {
          await writer.WriteAsync(stream, queryResult);
          var res = Encoding.UTF8.GetString(stream.ToArray());
          var jsonResult = JsonSerializer.Deserialize<dynamic>(res);
      
          return Ok(jsonResult);
      }
    }
}
```

**Comment by Shane32** [comment]
Thanks, @joelmandell !  I'll take a look.  Hopefully we can provide a sample that does not require the execution result to be serialized, deserialized, and reserialized again.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/examples/blob/master/src/AspNetWebApi/WebApi/Controllers/GraphQLController.cs#L37

**Comment by joelmandell** [comment]
@sungam3r I just have one question about the sample. Why does it return a BadRequest on errors?
  Can apollo-library get the errors correctly when its not a 200 ok with json body that has an error object?

**Comment by sungam3r** [comment]
Obviously because this is bad example 😕 . Or because it illustrates GraphQL integration into the classic REST design with many different HTTP codes. I don't know.

**Comment by Shane32** [comment]
Also #2161 requested proper sample.

**Comment by Shane32** [comment]
> https://github.com/graphql-dotnet/examples/blob/master/src/AspNetWebApi/WebApi/Controllers/GraphQLController.cs#L37

`WriteToStringAsync` is at least better.  But we should not have to write the data to a memory stream, then read into a string, and then converted by ASP.Net back to a UTF stream again.

**Comment by joelmandell** [comment]
Yeah. I did not know that the extension method WriteToStringAsync existed. So it seems I kinda did those steps on my own... Going to try it out tomorrow.

**Comment by Shane32** [comment]
@joelmandell Could you try this when you get a chance:

```cs
[ApiController]
[Route("[controller]")]
public class GraphqlController : ControllerBase
{
    public async Task<IActionResult> Post([FromBody] GraphQLRequest q)
    {
      var schema = new GQLSchema();
      
      var queryResult = await new DocumentExecuter().ExecuteAsync(s => {
                s.Schema = schema;
                s.Query = q.Query;
                s.Inputs = q.Variables.ToInputs();
                s.OperationName = q.OperationName;
                s.CancellationToken = HttpContext.RequestAborted;
      }).ConfigureAwait(false);
      
      Response.StatusCode = 200;
      Response.ContentType = "application/json";
      var writer = new GraphQL.SystemTextJson.DocumentWriter();
      await writer.WriteAsync(Response.Body, queryResult, HttpContext.RequestAborted).ConfigureAwait(false);
      await Response.Body.FlushAsync(HttpContext.RequestAborted).ConfigureAwait(false);
      return new EmptyResult();
    }
}
```
On a side note, you will gain immense performance improvements if you reconfigure your schema to be a singleton.  The document executer and document writer can also be registered as singletons.  See https://graphql-dotnet.github.io/docs/getting-started/dependency-injection

**Comment by sungam3r** [comment]
I would also remove two `ConfigureAwait(false)` calls.

**Comment by joelmandell** [comment]
@Shane32 Yes, I already register it as singleton in Startup. 
I tried your code below and it "feels" like it runs faster, haven't done any benchmark comparisions, yet...

@sungam3r Did that too now. Working great.

**Comment by Shane32** [comment]
See:
- https://github.com/graphql-dotnet/examples/pull/91

**Comment by Shane32** [comment]
We now have controller support documented within the server repo.  See:
- https://github.com/graphql-dotnet/server#configuration-with-a-mvc-controller

The server repo also includes a sample implementation, both (a) with custom code for execution, and (b) mapping to the middleware.  See:
- https://github.com/graphql-dotnet/server/tree/master/samples/Samples.Controller
