### ISSUE TITLE
Default values override supplying an argument literal of null

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2159]
See rule for input coercion for scalars:

> For all types below, with the exception of Non‐Null, **if the explicit value null is provided, then the result of input coercion is null.**

See rule for input objects:

> If no value is provided for a defined input object field and that field definition provides a default value, the default value should be used. If no default value is provided and the input object field’s type is non‐null, an error should be thrown. Otherwise, if the field is not required, then no entry is added to the coerced unordered map.
>
> **If the value null was provided for an input object field, and the field’s type is not a non‐null type, an entry in the coerced unordered map is given the value null**. In other words, there is a semantic difference between the explicitly provided value null versus having not provided a value.
>
> If a literal value is provided for an input object field, an entry in the coerced unordered map is given the result of coercing that value according to the input coercion rules for the type of that field.
>
> If a variable is provided for an input object field, the runtime value of that variable must be used. If the runtime value is null and the field type is non‐null, a field error must be thrown. If no runtime value is provided, the variable definition’s default value should be used. If the variable definition does not provide a default value, the input object field definition’s default value should be used.

Also see this pseudo-code for Coercing Field Arguments: https://spec.graphql.org/June2018/#sec-Coercing-Field-Arguments

> ...
> Let hasValue be true if argumentValues provides a value for the name argumentName.
> ...
> **If hasValue is not true** and defaultValue exists (including null):
> - Add an entry to coercedValues named argumentName with the value defaultValue.

Currently what happens is that the null value is overridden by the field default value.  This is incorrect according to the spec.

@sungam3r I assume we should fix in 3.3?

**Comment by sungam3r** [comment]
OK
