### ISSUE TITLE
Is there any plans to support the GraphQL over Websocket ("graphql-transport-ws") protocol?

### ISSUE THREAD

**Issue by Sakkyoku-Sha** [graphql-dotnet/graphql-dotnet#2170]
I'm currently using the latest version of the GraphQL.Server suite. Specifically for this post version 4.4.1 of GraaphQL.Server.Transports.WebSockets.

For a while it seems most JS web clients have used the NPM package [subscription-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) which defines it's protocol to be "graphql-ws". 

But even in it's code base [It seems like this protocol is about to be deprecated](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/protocol.ts)

The subscription-transport-ws npm is now deprecated itself and the new npm that is suggested is called [graphql-ws](https://github.com/enisdenjo/graphql-ws#readme) which has a specified sub protocol of ["graphql-transport-ws"](https://github.com/enisdenjo/graphql-ws/blob/master/src/protocol.ts)

As it stands now it seems that the most popular npm package to support GraphQL subscriptions today is not supported by this nuget package.

**Comment by sungam3r** [comment]
I have no such plans. More importantly, I don't have time.

**Comment by Sakkyoku-Sha** [comment]
All good, appreciate the response.
