### ISSUE TITLE
Separate benchmark graphql documents from code

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2172]
Let's keep all such requests in separate files like here:
![изображение](https://user-images.githubusercontent.com/21261007/104422353-b5932080-558d-11eb-8297-67f1e59586ff.png)

I moved them there to make it easier to edit them separately from the code. In addition, then syntax highlighting becomes available. Also no need in escaping like `""`.

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/graphql-dotnet/pull/2167#discussion_r556323681_

**Comment by sungam3r** [comment]
Done in #2241
