### ISSUE TITLE
How to overwrite any instance of ExecutionOptions?

### ISSUE THREAD

**Issue by ninomllr** [graphql-dotnet/graphql-dotnet#2178]
I try to get FluentValidation to work with GraphQL (https://github.com/SimonCropp/GraphQL.Validation) but run into some issues when I want to register something on the ExecutionOptions. Where can ExecutionOptions be added in GraphQL?

In the provided SampleWeb example in the repository they are adding a custom GraphQLController which throws an error for me, because I can't run queries anymore when I use it. So I was wondering is it really necessary to implement my own GraphQLController if I just want to add one option?

**Comment by ninomllr** [comment]
Ok, so I found a "solution" but it's not so nice. 

1. I created a copy of https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs and named it MyDocumentExecutor.
2. Added some lines to ExecuteAsync
```
ValidatorTypeCache validatorTypeCache = new();
validatorTypeCache.AddValidatorsFromAssembly(assemblyContainingValidators);
Schema schema = new();
DocumentExecuter executer = new();
```
3. I changed which DocumentExecutor I use in my Startup.cs

This works, but I don't like the solution, because I will not get the updates in that class anymore. I can't override ExecuteAsync because it's not virtual. Would it be possible to change that? That would exactly be what I need. 

Or if there is a better way on solving my issue, I would be happy to hear some suggestions.

**Comment by sungam3r** [comment]
> I can't override ExecuteAsync because it's not virtual.

`ExecuteAsync` has already been marked as `virtual` on `develop` branch. We plan release v4 at February 1st. Also see this https://github.com/graphql-dotnet/server/blob/master/src/Core/Internal/DefaultGraphQLExecuter.cs#L56

**Comment by sungam3r** [comment]
We delayed the v4 release for several weeks due to the need to make more fixes. Activity is tracked in #2171. Closing this.
