### ISSUE TITLE
Create custom directive being able to skip/include nodes other than existing "skip" and "include"

### ISSUE THREAD

**Issue by jeangsc** [graphql-dotnet/graphql-dotnet#2179]
## Summary

Currently, to skip/include fields, the code will check directive name and boolean argument's value for "if". My idea is to make the code being able to do this with new custom directives. My idea is to add a boolean virtual property to Field class to check if we do the "ignoreNode", this boolean would take into account the "if" argument for existing include and skip.

### Basic example

- We have a type "Character" with 1 scalar fields of type string: "name"
- We have 2 instances of Character. For user rights reason for example, the first has a "readonly" name (we cannot modify it), the second has a "readwrite" name (we can modify it)
- characters is an array fields returning all character

query
{
  characters
  {
    readonlyName: name @isReadOnly
    readwriteName: name @isReadWrite
  }
}

Expected: 
data: {
  characters: [ readonlyName: "Goku", readwriteName: "Vegeta" ]
}

readwriteName for the first character and readonlyName for the second would be skipped

### Motivation

It would be helpful to be able to do this with customized conditions, I could show my concrete idea by coding on the existing project on my computer with a pull request for example.

**Comment by sungam3r** [comment]
> Currently, to skip/include fields, the code will check directive name and boolean argument's value for "if".

Because that's exactly what it takes to meet the specification. What you describe can be done with custom directives. This feature is supported.

**Comment by jeangsc** [comment]
> > Currently, to skip/include fields, the code will check directive name and boolean argument's value for "if".
> 
> Because that's exactly what it takes to meet the specification. What you describe can be done with custom directives. This feature is supported.

When I've read the code, I've seen a "shouldIncludeNode" which take into account only directive "include" and "skip", but I want to add the possibility to create a custom directive which can do the same kind of work (maybe checking a passed function called at "shouldIncludeNode" with a parameter giving info about current context).

**Comment by sungam3r** [comment]
@jeangsc #2294 was merged and will be published in the v4 release.
