### ISSUE TITLE
Nullable Types Support

### ISSUE THREAD

**Issue by leandrozapata** [graphql-dotnet/graphql-dotnet#219]
Hi, is possible to use Nullable types in Field ?
Example:

Field(h => h.DebtToWin, nullable:true).Description("DebToWin");

DebToWin is the type Nullable Decimal and now i have the following exception

An exception of type 'System.ArgumentOutOfRangeException' occurred in GraphQL.dll but was not handled in user code.

Thanks for your help.

**Comment by joemcbride** [comment]
Not currently, no.  That behavior would [need to be added here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/TypeExtensions.cs#L68).

**Comment by jquense** [comment]
added in #222

**Comment by joemcbride** [comment]
#222 has been merged
