### ISSUE TITLE
ValidationOnSchemaInitialize is useless, and `Validation` comments is misleading

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2204]
`NameValidator.ValidationOnSchemaInitialize` is useless and misleading because if someone tried to use a field/argument name that has invalid characters, the parser library would not read a query with those fields.

`NameValidator.Validation` has misleading comments, because it only allows bypassing validation when there is an `INameConverter` which fixes the names to conform to the GraphQL specification (so that queries with those names can be read by the parser library).

I suggest making the former `internal` for now, and updating the comments on the latter.

**Comment by sungam3r** [comment]
I'm not sure. The validator works on objects that are not related to the parser. Although in general this issue makes sense.

**Comment by sungam3r** [comment]
I mean, for example, we can set the enum value as `my-enum-value` and return it in the response. The parser is not involved in this process.

**Comment by Shane32** [comment]
As of now, it is only used for field and argument names.  Having it validate other names is in #2123 .  However, this would certainly apply to directive names, enums, and input type names, and even to a lesser degree, output type names (like when a spread is specified for a certain type).

**Comment by Shane32** [comment]
> I mean, for example, we can set the enum value as `my-enum-value` and return it in the response. The parser is not involved in this process.

While that's true, it's a bad example.  Enums are only needed for inputs.  Output enum values are coerced to a string for json serialization.

**Comment by sungam3r** [comment]
But it is still GraphQL valid enum. I mean enum **name**, not enum **internal value** on the server.

**Comment by Shane32** [comment]
Right. It’s the graphql enum name that gets serialized, not the internal value

**Comment by Shane32** [comment]
@sungam3r Do you want to fix this for v4?  Otherwise I will add a note in the Known Issues, since in practical terms, overriding `ValidationOnSchemaInitialize` is completely useless.

**Comment by sungam3r** [comment]
I'm OK either way. I don't remember which is better.
