### ISSUE TITLE
Schema initialisation does not appear to be thread safe

### ISSUE THREAD

**Issue by acraven** [graphql-dotnet/graphql-dotnet#2208]
## Description

FieldMiddleware may execute multiple times for the same request unless the schema is allowed to be initialised with a single request. From digging it appears that Schema initialisation is not thread safe.

### Steps to reproduce

I have a GraphQLController which is executing my queries and mutations by creating an instance of ExecutionOptions and calling ExecuteAsync on a new instance of DocumentExecuter.

I am adding middleware that simple logs each execution and adding it via ExecutionOptions.

If I target my API with a known number of concurrent calls, I log more executions of the middleware than I do if I target the API with a single call first followed by the same number of concurrent calls.

### Expected result

For each incoming request the middleware should be executed once for each request (assuming the request only contains a single operation) and once for each field.

I would therefore expect to see the same number of middleware executions for a given number of requests, regardless of whether those requests are serialised or concurrent.

### Workaround

I am able to workaround this by using the field middleware builder to apply the middleware in the constructor of my Schema followed by a call to Initialize.

### Environment

GraphQL 3.3.1
Native Windows 10 & Dockerised Alpine Linux

**Comment by sungam3r** [comment]
Yeah, it's a known bug.

**Comment by Shane32** [comment]
We should have fixed it long ago, especially as it is such a simple fix, and such as serious problem if/when it occurs.

I will probably put in a PR for 4.0 that changes middleware to be configured within the schema, just like our other changes in 4.0.  So anything that configures the schema is set in the schema, not within ExecutionOptions.
