### ISSUE TITLE
EnumerationGraphType implementations not registered in DI container

### ISSUE THREAD

**Issue by corstian** [graphql-dotnet/graphql-dotnet#2211]
I get the following error during runtime;

```
GraphQL.Execution.UnhandledError: Error executing document.
 ---> System.InvalidOperationException: Required service for type GraphQL.Types.EnumerationGraphType`1[LaunchMethods] not found
```

It is one which can easily be resolved by registering the graphtype as follows;

```csharp
services.AddSingleton<EnumerationGraphType<LaunchMethods>, LaunchMethodsEnumType>();

public class LaunchMethodEnumType : EnumerationGraphType<LaunchMethods> { }
```

What's strange about this issue is that the `LaunchMethodEnumType` is not properly registered in the DI, something which previously seemed to work correctly.

**Comment by ViRuSTriNiTy** [comment]
The server part provides a [AddGraphTypes](https://github.com/graphql-dotnet/server/blob/22ff03f499c43cc31fc6308999b9929a8f6b35da/src/Core/Extensions/GraphQLBuilderCoreExtensions.cs#L161) extension method to harvest all GraphTypes from	he calling assembly but this seem to work in case of `EnumerationGraphType` only when you derive from `EnumerationGraphType` as only then the class is compiled into the calling assembly.

So in case of using `EnumerationGraphType<>` directly the variant used must be registered in DI manually.

**Comment by Shane32** [comment]
When using the IGraphQLBuilder provided in 4.6.0+ (I believe), the suggested registration will occur automatically. Note that the nuget package GraphQL.MicrosoftDI is required for the AddGraphQL extension method. This package is referenced by the current version of the server project and is the recommended approach to setting up DI, as listed in the “Dependency Injection” section of the documentation. 

See:
- https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/DI/GraphQLBuilderBase.cs
- https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#dependency-injection-registration-helpers

**Comment by Shane32** [comment]
The AddGraphTypes extension method does not add the registration again.

**Comment by sungam3r** [comment]
@Shane32 Anything to document here or close?

**Comment by Shane32** [comment]
No; we have added a lot to the DI docs since this was opened.
