### ISSUE TITLE
DataLoader with SimpleContainer

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#2220]
Hi,
In the documentation for [DataLoader](https://graphql-dotnet.github.io/docs/guides/dataloader/),  the first setup step is to register IDataLoaderContextAccessor and DataLoaderDocumentListener in IoC container.

I am wondering what would be the example if SimpleContainer is used.

**Comment by Shane32** [comment]
Pretty much the same.  `SimpleContainer` supports singletons.  Unfortunately it doesn't have a easy-to-use overload for singletons.

```cs
simpleContainer.Singleton<IDataLoaderContextAccessor>(() => new DataLoaderContextAccessor());
simpleContainer.Singleton<DataLoaderDocumentListener>(() => new DataLoaderDocumentListener(simpleContainer.Get<IDataLoaderContextAccessor>()));
```

**Comment by rmeshksar** [comment]
Thanks, it worked great.
