### ISSUE TITLE
Relay classes, and utilities

### ISSUE THREAD

**Issue by jquense** [graphql-dotnet/graphql-dotnet#224]
:wave: howdy. I've ended building a bunch of stuff to get GraphQL dontnet to play nicely with Relay, from extra graph types, mutation helpers and WebApi/MVC helpers making sure stuff is correctly deserialized across the wire. **I don't think most of that stuff is useful here** but maybe in it's own package in the same organization, like a a graphql-relay-js for dotnet? I'd be glad to maintain it if that seems amenable to you :)

**Comment by joemcbride** [comment]
👍 That sounds good to me.  I created this repo and invited you to it.  https://github.com/graphql-dotnet/relay

**Comment by joemcbride** [comment]
Also setup AppVeyor for it - https://github.com/graphql-dotnet/graphql-dotnet/blob/master/appveyor.yml
