### ISSUE TITLE
Benchmark for new version 4

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#2242]
I see in the issues and commits that you put a lot of time and energy into performance improvements for the version 4 and I appreciate this a lot. The HotChocolate teams has a provided numbers for their latest release. It would be great if you can showcase your effort as  well.

**Comment by sungam3r** [comment]
To give an objective comparison, we need the same data - schema, queries, scenarios.

**Comment by sungam3r** [comment]
What exactly is your question? We already have a special project dedicated to benchmarks and even a utility that makes it easier to compare them. We regularly check that our changes do not degrade (and ideally always improve) performance.

**Comment by sungam3r** [comment]
@Shane32 How do we deal with this issue?

**Comment by sungam3r** [comment]
Ping @SebastianStehle . https://github.com/graphql-dotnet/graphql-dotnet/blob/develop/docs2/site/docs/migrations/migration4.md#improved-performance
> GraphQL.NET 4.0 has been highly optimized, typically executing queries at least 50% faster while also providing a 75% memory reduction. Small queries have been measured to run twice as fast as they previously ran. A cached query executor is also provided, which can reduce execution time another 20% once the query has been parsed (disabled by default). Variable parsing is also improved to run about 50% faster, and schema build time is now about 20x faster than previously and requires 1/25th the amount of memory.

OK?

**Comment by SebastianStehle** [comment]
I will move the 4.0 anyway and I appreciate your effort, but when comparing performance I usually search for "X vs Y benchmark". This is what is interesting for me. But it is more about marketing, not a real feature request.

**Comment by sungam3r** [comment]
OK. So closing.
