### ISSUE TITLE
Query Variables

### ISSUE THREAD

**Issue by leandrozapata** [graphql-dotnet/graphql-dotnet#225]
Any example how to use query variables of custom type on server side query implementation?

Something like:

query Hero($episode: Episode) {
  hero(episode: $episode) {
    name,
  }
}

Thanks.

**Comment by joemcbride** [comment]
Those variables get passed through to the field resolver as arguments, so you can just access the value as an argument in your field resolver.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Execution/EnumAsInputsTests.cs#L236

```
Field<DroidType>(
  "hero",
  arguments: new QueryArguments(new QueryArgument<Episode> { Name = "episode" })
  resolve: context => {
    // direct access to the value
    context.Arguments["episode"];
    // this will attempt to coerce the from the original to the type given
    context.GetArgument<MyEpisodeClassOrEnum>();
    context.GetArgument<int>();
  }
);
```

**Comment by leandrozapata** [comment]
Thanks for your help!

**Comment by joemcbride** [comment]
Welcome!
