### ISSUE TITLE
DataLoaderContext Is Null

### ISSUE THREAD

**Issue by tjaskula** [graphql-dotnet/graphql-dotnet#2256]
I'm using GraphQL v 3.3.2 and I'm trying to make work the DataLoader but everytime I try to access the `Context` property inside the injected `IDataLoaderContextAccessor` instance, it is null. I've went through the documentation but didn't find anything useful so unstuck me. I'm not using directly in my code `DocumentExecuter` so the advice in the documentation doesn't seem to apply to my case

## Startup

There is nothing fancy here

```
services
                .AddGraphQL(o => { o.EnableMetrics = true; })
                .AddNewtonsoftJson()
                .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = _environment.IsDevelopment())
                .AddDataLoader() 
                .AddGraphTypes(ServiceLifetime.Scoped);
```

My type

```
public class FondsCatalogType : ObjectGraphType<CatalogFondsRepresentation>
    {
        public FondsCatalogType(IDataLoaderContextAccessor dataLoaderContextAccessor)
        {
            Field(t => t.Id, type: typeof(IdGraphType));

            // more irrelevant field declarations...                    
  
        }
    }
```

So I'm getting correctly the instance of `IDataLoaderContextAccessor` but the context is `null`

Is there something else to configure? 

If I understand correctly internally the  `DataLoaderDocumentListener` is added to the execution context.

**Comment by Shane32** [comment]
The context will only hold a value within a field resolver, not in the type constructor, Can you supply a sample of the field declaration whose results should come from the data loader?

**Comment by tjaskula** [comment]
My bad. I didn't understood that from the documentation

Checking this, it works. The Context is not null anymore inside the resolve operation

```
FieldAsync<StringGraphType>("testDataLoader", resolve: async context =>
            {
                var loader = dataLoaderContextAccessor.Context;
                return "OK";
            });
```
