### ISSUE TITLE
Running Kestrel and GraphQL layer on same box and on same application

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2265]
I am working on a project where I need to use `GraphQL` in my `asp.net core` 3.1 project and this is the first time I am working with `GraphQL`. I have a legacy application which already uses Kestrel server and all our GET and POST calls works fine. Now we are planning to add `GraphQL` layer in the same project and migrate each of our previous use case to this `GraphQL` layer. 

Below is my `Program` and `Startup` classes.

 ```
 public class Program : IWebApiServer
  {
      public void StartWebApiServer()
      {
          var host = new WebHostBuilder()
              .UseContentRoot(Directory.GetCurrentDirectory())
              .UseKestrel(o =>
              {
                  o.Limits.MaxResponseBufferSize = null;
                  o.Limits.MinResponseDataRate = null;
                  o.Limits.MaxConcurrentConnections = 1000;
                  o.Limits.MaxConcurrentUpgradedConnections = 1000;
                  o.AllowSynchronousIO = true;
              })
              .UseStartup<Startup>()
              .UseUrls("http://*:1335")
              .Build();
          host.Run();
      }
  }
```

This is what I see in my `Startup` class:

 ```
 public Startup(IHostingEnvironment env)
  {
      var builder = new ConfigurationBuilder()
          .SetBasePath(env.ContentRootPath)
          .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
          .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
          .AddEnvironmentVariables();
      Configuration = builder.Build();
  }

  public IConfigurationRoot Configuration { get; }

  public void ConfigureServices(IServiceCollection services)
  {
      // we doing some stuff here related to DI
  }

  public void Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime)
  {
      // some stuff here
  }
```

**Question**

Now I am thinking to integrate `GraphQL` layer in my above legacy project. I started learning `GraphQL` and played with some examples from this [project](https://github.com/graphql-dotnet/examples/tree/master/src/AspNetCore) and basis on that I modified my `Startup` file `ConfigureServices` and `Configure` method as shown below:

 ```
 public void ConfigureServices(IServiceCollection services)
  {
      // ... old legacy stuff here

      // .. graphql stuff here
      services.AddGraphQL(options =>
      {
          options.EnableMetrics = true;
      })
      .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true)
      .AddSystemTextJson()
      .AddUserContextBuilder(httpContext => new GraphQLUserContext { User = httpContext.User });
  }

  public void Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime)
  {
      // ... old legacy stuff here

      // .. graphql stuff here
      if (app.isDevelopment())
          app.UseDeveloperExceptionPage();

      // add http for Schema at default url /graphql
      app.UseGraphQL<ISchema>();

      // use graphql-playground at default url /ui/playground
      app.UseGraphQLPlayground();
  }
```

Also added these two dependencies as well - 

    <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="4.2.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="4.2.0" />

Now once I start the server, I am able to navigate to this link - http://localhost:1335/ui/playground and also my original legacy `GET`, `POST` calls are working fine through Kestrel server.

I can see `GraphQL` UI being loaded up. It is just that I don't have any schema defined yet so nothing works but as first step I can get `GraphQL` integrated fine looks like. Now I have few confusions on this as I am not sure if this is the right way to do or not - 

- Can I run both my legacy app which uses Kestrel server along with GraphQL layer on same application and on same box?
- Will there be any performance issues in production if I run it like this?
- Our plan is to keep running legacy kestrel server as it is and migrate use cases one by one to this graphql layer. And once everything is migrated, remove Kestrel dependency after that.

Is there any problem with this approach? Since I recently started working with asp.net core and graphql both so trying to make sure if this is the right way to go or not?

**Comment by sungam3r** [comment]
GraphQL endpoint shouldn't interfere with the rest of the application. You can gradually migrate your application to it. I do not know the reasons why this could not be done.

> running legacy kestrel server
> And once everything is migrated, remove Kestrel dependency after that.

What are you going to replace Kestrel with?

**Comment by TechGeeky** [comment]
My understanding was to replace with GraphQL server? I am currently new to asp.net and GraphQL both as I coming from different background so my understanding might be off here but Kestrel is a web server right? And GraphQL also has server so I can completely remove Kestrel part and just use GraphQL server once everything is migrated from that to GraphQL layer correct?

Let me know if I am wrong here.

**Comment by Shane32** [comment]
Graphql runs on top of kestrel or another http server library. If you’re using asp.Net then you can use asp.Net middleware to bypass many layers of asp.Net (e.g. pages, controllers, authentication, etc) thereby speeding up your implementation. However kestrel would still be used to manage the http requests/responses.

**Comment by TechGeeky** [comment]
aah got it now. I think it makes sense.
