### ISSUE TITLE
Query vs Mutation use case for REST post call?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2269]
I am working on a project where I need to use `GraphQL` in my `asp.net core` 3.1 project and this is the first time I am working with `GraphQL`. I have a legacy application which already uses Kestrel server and all our GET and POST calls works fine. Now we are planning to add `GraphQL` layer in the same project and migrate each of our previous use case to this `GraphQL` layer.

Below is our postman call on our Kestrel web server which works fine. It's a post request where in the code we deserialize json body and then make calls to downstream services. After that we aggregate the response and return back to user in a json. So for each POST request we return back a json response to the user.

    curl --location --request POST 'http://abc.domain.com:1000/' \
    --header 'Content-Type: application/json' \
    --header 'abc-text1: 12345' \
    --header 'abc-text2: {"hello": "world", "kite": "data"}' \
    --data-raw '{
        "clientId": 12345,
        "customerId": 1,
        "processId": 1,
        "betaId": 1,
        "dataSetId": 1,
        "filters": [
            {
                "key": "o",
                "value": 1986
            }
        ],
        "request":
        {
            "aggrKey": "hello",
            "aggrCount": 0
        }
    }'

Now I am trying to convert this use case to `GraphQL` layer. Below is where I am stuck - 

- My confusion is do I need to use `Query` or `Mutation` here? What makes more sense here?
- Also how should I define schema for the above use case so that it can work with my mutations and resolver.

I started learning `GraphQL` and played with some examples from this [project](https://github.com/graphql-dotnet/examples/tree/master/src/AspNetCore) but I am kinda confuse on above things. Any example basis on my above use case will help me clear my doubts.

I am using below dependencies - 

    <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="4.2.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="4.2.0" />
    <PackageReference Include="GraphQL" Version="3.1.3" />

**Comment by sungam3r** [comment]
`Mutation` assumes data change. Everything depends on you and how you define schema. Any way will work. As for the examples, I recommend starting with the readme, docs https://graphql-dotnet.github.io/ and tests https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.Tests. There are many schema examples.

**Comment by TechGeeky** [comment]
Thanks for the link. In this case we aren't changing any data right? So it can be Query correct? Since as part of POST call we just get the request and basis on that call some underlying services and after that we aggregate the response and give it back to the user. So what do you think?

**Comment by sungam3r** [comment]
I think you can find answers here https://graphql.org/learn/ , https://graphql.org/learn/serving-over-http/

**Comment by Shane32** [comment]
Queries and mutations function identically (although by default queries run in parallel and mutations in series). Semantically a query should be used for retrieving information and a mutation for modifying information. GraphQL won’t care if you’re calling other services via get or post or store information on floppy disks.

**Comment by TechGeeky** [comment]
Thanks @Shane32. I figured out the difference after reading the link sungam shared above. And in my case, we are not modifying any data so I should be good in using Queries I guess. Let me know if that looks correct to you?

**Comment by sungam3r** [comment]
Closed as answered.
