### ISSUE TITLE
Recomendation 

### ISSUE THREAD

**Issue by leandrozapata** [graphql-dotnet/graphql-dotnet#227]
Hi, any recomendation for inject dynamic schema in MVC Controller.

Actually all schemas implements ISchema, I think it's possilble to make this with dependency injection, but i would like if actually exist aproved way.

Regards.

Leandro.

**Comment by joemcbride** [comment]
Yes you can use DI with a Schema.  Here are two examples:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Bootstrapper.cs#L30

https://github.com/joemcbride/marten/blob/graphql2/src/DinnerParty/Bootstrapper.cs#L62-L66
