### ISSUE TITLE
Disabling metrics

### ISSUE THREAD

**Issue by brunochaina** [graphql-dotnet/graphql-dotnet#2271]
Is there any way to disable the metrics in query responses? I haven't configured them so apparently they are enabled by default. I would like to have a cleaner response during development and if necessary, manually enabling the tracing info.

Thank you,

Bruno

**Comment by Shane32** [comment]
In v3, `ExecutionOptions.EnableMetrics` is enabled by default, but not written to the output unless `EnrichWithApolloTracing` is called.  If you are seeing them in your output, perhaps you are using the server project?  See https://github.com/graphql-dotnet/server which has an example in the readme -- you might need to disable metrics within the `AddGraphQL` service registration.

**Comment by brunochaina** [comment]
You are right, I'm using the server project and it wasn't enabled by default before I updated my NuGet package to the latest version. I found it in the example you shared:

services
        .AddGraphQL((options, provider) =>
        {
            options.EnableMetrics = Environment.IsDevelopment();
        })

Thanks a lot,

Bruno
