### ISSUE TITLE
Field scalar value and extension method

### ISSUE THREAD

**Issue by grean** [graphql-dotnet/graphql-dotnet#2278]
I have an extension method on a decimal type like this 
```c#
    public static class Conversion
    {
        public static decimal MegaJouleToKcal(this decimal value) => value * Constantes.MegaJouleToKcal;

    }
``` 
But when i want to use it in an objectType constructor, the second line throw a error
```c#
Field(i => i.DEJGoal);
Field(i => i.DEJGoal.MegaJouleToKcal(), nullable: true, type: typeof(DecimalGraphType)).Name("dejGoalKcal");
```
like this 
>Cannot infer a Field name from the expression: 'i.DEJGoal.MegaJouleToKcal()' on parent GraphQL type: 'PatientType'.

If i don´t use the extention method it works.
How can i achieve this ? I simply want to have the same value 'dejGoal' with a different unit.
Thanks.

**Comment by Shane32** [comment]
Try:
```cs
Field("dejGoalKcal", i => i.DEJGoal.MegaJouleToKcal(), nullable: true, type: typeof(DecimalGraphType));
```

**Comment by grean** [comment]
It works, thanks @Shane32 :)
