### ISSUE TITLE
Is there an example of graphql-dotnet used in production?

### ISSUE THREAD

**Issue by biapar** [graphql-dotnet/graphql-dotnet#228]
Is there an example of graphql-dotnet used in production?
Is't .NET Core compatible?

**Comment by joemcbride** [comment]
Yes, it is .NET Core compatible.  It currently targets NetStandard 1.1.

https://www.nuget.org/packages/GraphQL/

[Hudl](http://www.hudl.com/) has been using a fork of this project in production for close to a year.  The [conventions](https://github.com/graphql-dotnet/conventions) project that @tlil87 recently released is based off of what they are currently using in production.

**Comment by MrFlorent** [comment]
Hi everyone !
I was just wondering if there had been any updates on GraphQL dot net server used in production mode ? 
With a bad or happy ending :) 

Regards,
Flo
