### ISSUE TITLE
Need Advice - How to pass headers received on request to resolver method

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2285]
I have a very simple requirement where I need to capture the headers received on `/graphql` request and then make them available in resolve methods but I am confuse on how that is going to work out - 

Below is my `Configure` method in `Startup.cs` class - 

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
            app.UseDeveloperExceptionPage();

        app.UseMiddleware<GraphQLMiddleware>(new GraphQLSettings
        {
            Path = "/graphql",
            BuildUserContext = ctx => new GraphQLUserContext
            {
                User = ctx.User
            },
            EnableMetrics = true
        });

        // add http for Schema at default url /graphql
        // app.UseGraphQL<ISchema>();

        // use graphql-playground at default url /ui/playground
        app.UseGraphQLPlayground();
    }

And below is my `ExecuteAsync` method of `GraphQLMiddleware` class -

    private async Task ExecuteAsync(HttpContext context, ISchema schema)
    {
        var request = Deserialize<GraphQLRequest>(context.Request.Body);
        var result = await _executer.ExecuteAsync(_ =>
        {
            _.Schema = schema;
            _.Query = request?.Query;
            _.OperationName = request?.OperationName;
            _.Inputs = request?.Variables.ToInputs();

            // How should I pass the headers here in my "UserContext"?
            _.UserContext = _settings.BuildUserContext?.Invoke(context);

            _.ValidationRules = DocumentValidator.CoreRules.Concat(new[] { new InputValidationRule() });
            _.EnableMetrics = _settings.EnableMetrics;
            if (_settings.EnableMetrics)
            {
                _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
            }
        });
        await WriteResponseAsync(context, result);
    }

And below is my `GraphQLUserContext` class - 

    public class GraphQLUserContext : Dictionary<string, object>
    {
        public ClaimsPrincipal User { get; set; }
    }

Now my confusion is how can I access headers here in my `resolve` method?

    Field<HumanType>(
        "human",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id", Description = "id of the human" }
        ),
        resolve: context =>
        {
            var human = context.GetArgument<string>("id");
            // something like below I wanted to do or is it possible by any chance?
            var headers = context.Headers;
            // then do something with the header
            return data.GetHumanByIdAsync(human);
        }
    );

I am kinda confuse on what changes I need to make in my `ExecuteAsync` method to pass the header successfully to resolve method? @joemcbride Any thoughts on how can I get this working?

I am working based off this [example](https://github.com/graphql-dotnet/examples/tree/master/src/AspNetCore) just fyi.

**Comment by sungam3r** [comment]
1. Your user context is dictionary. Just add all headers from http context in `BuildUserContext` method.
2. Inject `IHttpContextAccessor` in your `GraphType`s ctors. Then use http context obtained from accessor directly in your resolver (via closure).

**Comment by TechGeeky** [comment]
Can I not store directly `headers` value to some variable in `GraphQLUserContext` class?

Like storing this `context.Request.Headers` in some variable directly in `GraphQLUserContext` class and then access it via user context in `resolve` method? I recently started with C# too so kinda confuse on how `BuildUserContext` works here. Can you provide an example if possible?

**Comment by sungam3r** [comment]
`GraphQLUserContext` is **your** class. You can do anything you want with it.

**Comment by TechGeeky** [comment]
Ok so I modified like this to add `headers` to `Headers` variable - 

            app.UseMiddleware<GraphQLMiddleware>(new GraphQLSettings
            {
                Path = "/graphql",
                BuildUserContext = ctx => new GraphQLUserContext
                {
                    User = ctx.User,
                    Headers = ctx.Request.Headers
                },
                EnableMetrics = true
            });

And also modified my `GraphQLUserContext` class like below - 

```
    public class GraphQLUserContext : Dictionary<string, object>
    {
        public ClaimsPrincipal User { get; set; }
        public IDictionary<string, StringValues> Headers { get; set; }
    }
```

Now confuse on how to get this `Headers` value from `GraphQLUserContext` class  in my resolve method - 

                resolve: context =>
                {
                    var human = context.GetArgument<HorusContainerRequest>("landingNavigation");
                    // how to get headers here?
                    var headers = context.UserContext.
                    Console.WriteLine("G");
                    // Console.WriteLine("Data-1: " + ObjectDumper.Dump(human));
                    return data.GetHumanByIdAsync(human);
                }

Sorry for asking silly question here. It looks like I might be doing something wrong here.

**Comment by sungam3r** [comment]
`IProvideUserContext.UserContext` property has `IDictionary<string, object>` type because this is interface. Just cast this property to your type - `GraphQLUserContext`.

**Comment by sungam3r** [comment]
Closed as answered.
