### ISSUE TITLE
How to use FieldAsync here bcoz my methods signatures are "async Task<...>"

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2286]
I have a resolve method like this in which I need to use `await` two times because `BuildRequest` and `ProcessData` method signatures are `async Task<....>` -

    Field<HumanType>(
        "human",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id", Description = "id of the human" }
        ),
        resolve: context =>
        {
            var human = context.GetArgument<string>("id");
            var requestContext = await clientService.BuildRequest(.....);
            var response = await metadataService.ProcessData(....);

            return response;
        }
    );

Is this the right way to use resolve like this? Or is there any async implementations which I can use here?

**Comment by sungam3r** [comment]
Use `FieldAsync`:
```graphql
 FieldAsync<__Type>(
                "mutationType",
                "If this server supports mutation, the type that mutation operations will be rooted at.",
                resolve: async context =>
                {
                    return await context.Schema.Filter.AllowType(context.Schema.Mutation).ConfigureAwait(false)
                        ? context.Schema.Mutation
                        : null;
                });
```

**Comment by TechGeeky** [comment]
You mean something like this?

```
FieldAsync<HumanType>(
    "human",
    arguments: new QueryArguments(
        new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id", Description = "id of the human" }
    ),
    resolve: async context =>
    {
        var human = context.GetArgument<string>("id");
        var requestContext = await clientService.BuildRequest(.....);
        var response = await metadataService.ProcessData(....);

        return response;
    }
);
```

**Comment by sungam3r** [comment]
> You mean something like this?

Yes. `FieldAsync` overloads.

**Comment by sungam3r** [comment]
Closed as answered.
