### ISSUE TITLE
IServiceProvider in Schema class re-initializing my other app class for GraphQL request?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2287]
I have a legacy `Asp.net Core 3.1` application which uses `Kestrel` server and all our `GET` and `POST` calls works fine. We have bunch of middlewares already on my legacy application and we use each of those middlewares for different purpose depending on what is the endpoint.

I am working on migrating all our legacy usecase to `GraphQL` endpoint. Currently starting with first use case to see if everything works fine or not with `GraphQL` layer.

Below is our legacy `BaseMiddleware` class which is extended by bunch of other middlewares we have but not `GraphQLMiddleware`:

**BaseMiddleware.cs**

    public abstract class BaseMiddleware {
      private const string LOGGING_TITLE = nameof(BaseMiddleware);
      protected static ICatalogService catalogService;
      protected static ICustomerService customerService;
      protected static ILandingService landingService;
      protected static ILoggingService loggingService;
      private static IDictionary <string, Object> requiredServices;

      private readonly RequestDelegate _next;

      public abstract bool IsCorrectEndpoint(HttpContext context);
      public abstract string GetEndpoint(HttpContext context);
      public abstract Task HandleRequest(HttpContext context);

      public BaseMiddleware(RequestDelegate next) {
        var builder = new StringBuilder("");
        var isMissingService = false;
        foreach(var service in requiredServices) {
          if (service.Value == null) {
            isMissingService = true;
            builder.Append(service.Key).Append(", ");
          }
        }

        if (isMissingService) {
          var errorMessage = builder.Append("cannot start server.").ToString();
          throw new Exception(errorMessage);
        }

        _next = next;
      }

      public async Task Invoke(HttpContext context) {
        if (IsCorrectEndpoint(context)) {
          try {
            await HandleRequest(context);
          } catch (Exception ex) {
            // handle exception here
            return;
          }
          return;
        }

        await _next.Invoke(context);
      }

      public static void InitializeDependencies(IServiceProvider provider) {
        requiredServices = new Dictionary<string, Object>();

        var catalogServiceTask = Task.Run(() => provider.GetService<ICatalogService>());
        var landingServiceTask = Task.Run(() => provider.GetService<ILandingService>());
        var customerServiceTask = Task.Run(() => provider.GetService<ICustomerService>());
        ....

        Task.WhenAll(catalogServiceTask, landingServiceTask, customerServiceTask).Wait();

        requiredServices[nameof(catalogService)] = catalogService = catalogServiceTask.Result;
        requiredServices[nameof(landingService)] = landingService = landingServiceTask.Result;
        requiredServices[nameof(customerService)] = customerService = customerServiceTask.Result;
        ....
      }
    }

Now all other middlewares just extend the above base ones and all our regular `GET`, `POST` calls works fine.

I created my `GraphQLMiddleware` class exactly from [here](https://github.com/graphql-dotnet/examples/blob/master/src/AspNetCoreCustom/Example/GraphQLMiddleware.cs) as it is and it doesn't extend my `BaseMiddleware` class yet (as I am confuse how should I go ahead and do that) - 

Below is how I am using my `Query` and `Schema` class - 

**TitanQuery.cs**

```csharp
    public class TitanQuery: ObjectGraphType<object> 
    {
      public TitanQuery(DummyData data, IConfigRepository props, ILandingService landingService, ICustomerService customerService, IHttpContextAccessor accessor) {
        Name = "Query";

        // this line throws NullRefException 
        // as "ConfigRepository" class gets reintialized for GraphQL request (not sure why)
        Console.WriteLine(props.TestMethod(5));

        Field <DummyType> (
          "landRequest",
          arguments: new QueryArguments(
            new QueryArgument <NonNullGraphType <CartInputType>> {
              Name = "cartInput",
              Description = "some stuff"
            }
          ),
          resolve: context => data.GetHumanByIdAsync(context.GetArgument <MessageRequest> ("cartInput"))
        );
      }
    }
```

**TitanSchema.cs**

```csharp
    using System;
    using GraphQL.Types;
    using GraphQL.Utilities;

    public TitanSchema(IServiceProvider provider) : base(provider)
    {
        Query = provider.GetRequiredService<TitanQuery>();
    }
```

Below is how my `Startup` class is configured -

```csharp
 public Startup(IHostingEnvironment env) {
   var builder = new ConfigurationBuilder()
     .SetBasePath(env.ContentRootPath)
     .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
     .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
     .AddEnvironmentVariables();
   Configuration = builder.Build();
 }

 public IConfigurationRoot Configuration { get; }

 public void ConfigureServices(IServiceCollection services) {
    // old legacy stuff here
    services.AddSingleton<IConfigRepository, ConfigRepository>();
    services.AddSingleton<ILandingService, LandingService>();
    services.AddSingleton<ICustomerService, CustomerService>();
    .....


   // graphql stuff
   services.AddSingleton <DummyData>();
   services.AddSingleton <TitanQuery>();
   services.AddSingleton <HumanType>();
   services.AddSingleton <InputType>();
   services.AddSingleton <FilterType>();
   services.AddSingleton <ISchema, TitanSchema>();

   services.AddGraphQL(options => {
       options.EnableMetrics = true;
     })
     .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true)
     .AddSystemTextJson()
     .AddUserContextBuilder(httpContext => new GraphQLUserContext {
       User = httpContext.User
     });
 }

 public void Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime) {
   // old legacy middlewares
   app.UseCategoryMiddleware();
   .......

   // graphql middleware - new one I added
   app.UseMiddleware<GraphQLMiddleware>(new GraphQLSettings
   {
       Path = "/graphql",
       BuildUserContext = ctx => new GraphQLUserContext
       {
         User = ctx.User
       },
       EnableMetrics = true
   });

   if (IsDevelopment())
     app.UseDeveloperExceptionPage();

   // add http for Schema at default url /graphql
   // app.UseGraphQL <ISchema> ();
   // use graphql-playground at default url /ui/playground
   app.UseGraphQLPlayground();
 }
```

Below is my `ConfigRepository` legacy class -

**ConfigRepository.cs**

    public class ConfigRepository: IConfigRepository 
    {
      private string _configName = "config.json";
      private static readonly object configLock = new object();
      private static bool initialized = false;
      private readonly StateManager <ConfigManifest> _stateManager = null;

      private readonly JsonSerializerSettings _textSerializerSettings = new JsonSerializerSettings {
        ContractResolver = new CamelCasePropertyNamesContractResolver(),
          NullValueHandling = NullValueHandling.Ignore
      };
      public ConfigRepository(IHolderManager holderManager, ILoggingService loggingService) {
        if (!initialized) {
          lock(configLock) {
            if (!initialized) {
              _stateManager = new StateManager <ConfigManifest>(holderManager, _configName, loggingService);
              initialized = true;
            }
          }
        }
      }

      // ... some other methods

      public int TestMethod(int x) {
        var propertyIndex = _stateManager.GetState().SystemPropertyDisplayValueOverrides;
        Console.WriteLine(propertyIndex);
        return x + 5;
      }
    }

**Problem Statement**

I am seeing a very weird problem and it might be related to `IServiceProvider` in my `TitanSchema` class here but could be wrong. 

- I started my server locally and I can see everything getting initialized. Also `ConfigRepository` class gets initialized too with all the objects in the constructor.
- If I hit my regular legacy GET call everything works fine (as no code changes here with old flow) and I do get the expected response back. It goes through one of my legacy middleware which calls bunch of services and eventually get the data back.
- Now if I hit same request through `GraphQL` layer (UI playground) then for some reason it hit my `ConfigRepository` class out of no where making it re-initialize twice. Since it was already initialize during server startup (`initialized` variable is true now) so it doesn't go inside `if` block making `_stateManager` to be null and then when the call goes to my `TestMethod` in same class from `TitanQuery` class then it throws NullRef exception.

So question (and confusion) is why `ConfigRepository` class gets called again whenever I hit my `GraphQL` request for the first time (making all objects null since it was initialized already during server startup) but it doesn't get called for any of my regular GET calls through postman. It looks like it tries to re-initialize `ConfigRepository` class again for `GraphQL` request. When I debug then I saw it was coming from my `TitanSchema` class which was calling this method in `ServiceProviderExtensions` which inturn called `ConfigRepository` class if I am not wrong.

    public static object GetRequiredService(this IServiceProvider provider, Type serviceType)
    {
        if (provider == null)
            throw new ArgumentNullException(nameof (provider));

        if (serviceType == null)
            throw new ArgumentNullException(nameof (serviceType));

        object service = provider.GetService(serviceType);
        if (service != null)
            return service;

        throw new InvalidOperationException($"Required service for type {serviceType} not found");
    }

It looks like it is happening with all other classes as well. For the first time whenever I hit my `GraphQL` request it tries to initialize all other dependency. I am not sure why. Maybe I need to change the way I have `TitanSchema` and `TitanQuery` defined? Do I need to add those in `InitializeDependencies` method in `BaseMiddleware` class?

**Comment by sungam3r** [comment]
```c#
 public static void InitializeDependencies(IServiceProvider provider) {
    requiredServices = new Dictionary<string, Object>();

    var catalogServiceTask = Task.Run(() => provider.GetService<ICatalogService>());
    var landingServiceTask = Task.Run(() => provider.GetService<ILandingService>());
    var customerServiceTask = Task.Run(() => provider.GetService<ICustomerService>());
    ....

    Task.WhenAll(catalogServiceTask, landingServiceTask, customerServiceTask).Wait();

    requiredServices[nameof(catalogService)] = catalogService = catalogServiceTask.Result;
    requiredServices[nameof(landingService)] = landingService = landingServiceTask.Result;
    requiredServices[nameof(customerService)] = customerService = customerServiceTask.Result;
    ....
  }

```

This is a strange code. I didn't understand what was going on. If your singleton is created twice, then you are likely using two different ServiceProviders.

**Comment by davidport21** [comment]
yeah in `InitializeDependencies` method `IServiceProvider` class is from Microsoft package but in `TitanSchema` class `IServiceProvider` is from GraphQL. Do you think that's the issue? If yes, then how can I resolve it. This is our legacy application so I am trying to move each of our use case to GraphQL so I can't change lot of things for old code flow. Any thoughts on how we can easily integrate with various IoC containers? @sungam3r

**Comment by TechGeeky** [comment]
yeah in `InitializeDependencies` method `IServiceProvider` class is from Microsoft package but in `TitanSchema` class `IServiceProvider` is from GraphQL. Do you think that's the issue? If yes, then how can I resolve it. This is our legacy application so I am trying to move each of our use case to GraphQL so I can't change lot of things for old code flow. Any thoughts on how we can easily integrate with various IoC containers? @sungam3r

**Comment by Shane32** [comment]
If your DI provider initializes the TitanSchema then it should be passing itself to the schema which will be available for singleton services within the schema...

**Comment by davidport21** [comment]
@Shane32 If you check my `ConfigureServices` method - I already have this line - 

```
 services.AddSingleton <ISchema, TitanSchema>();
```

Is that what you mean? But why  `TitanSchema` will try to initialize all my Singleton services again? That's where I am confuse.

**Comment by TechGeeky** [comment]
@Shane32 If you check my `ConfigureServices` method - I already have this line - 

```
 services.AddSingleton <ISchema, TitanSchema>();
```

Is that what you mean? But why `TitanSchema` will try to initialize all my Singleton services again? That's where I am confuse.

**Comment by Shane32** [comment]
Right; that’s correct. TitanSchema should not try to initialize your services again. Sorry I’m not at a pc right now to look deeper at the code you provided.

**Comment by TechGeeky** [comment]
yeah I have been scratching my head on this from quite some time. This is puzzling me a lot. I read lot of documentations but couldn't figure out why this is happening. Any help will be greatly appreciated whenever you get time. @Shane32

**Comment by Shane32** [comment]
If you can reproduce the issue in a temp repo then I’m sure we can get to the bottom of it. Of course that’s usually the trick with stuff like this. 

I will be on the road for a couple days so I can’t do much today or tomorrow. 

I did glance through what you sent and at a glance everything seems correct.

**Comment by TechGeeky** [comment]
sure let me work on putting up this on a temp repo. But in the meantime if you guys see anything wrong, please let me know.

**Comment by sungam3r** [comment]
I prefer the complete example. It will be much easier to correct a mistake in it.

**Comment by TechGeeky** [comment]
sure working on it to see if I can replicate this and put it out in temp repo. Appreciate your help guys!

**Comment by TechGeeky** [comment]
I have created a temp repo here which outline the issue - https://github.com/TechGeeky/graphql-example
Let me know if you guys are available to reproduce it. I think I am making a very basic mistake here given my background in C# and GraphQL is very new.
@Shane32 @sungam3r

**Comment by sungam3r** [comment]
1. Why do you call `BuildServiceProvider()` **three** times? Remove all calls to this method.
2. Remove `InitializeDependencies` method at all.
3. Change `public BaseMiddleware(RequestDelegate next)` to  `public BaseMiddleware(RequestDelegate next, ICatalogService srv1, ICustomerService srv2)`
4. Change `HealthServiceMiddleware` ctor too: `public HealthServiceMiddleware(RequestDelegate next, ICatalogService srv1, ICustomerService srv2) : base(next, srv1, srv2) { }
5. Your `DataImpl._isInitialized`  is never set to `true`.

**Comment by TechGeeky** [comment]
1. `BuildServiceProvider` code is like that only in our application since ages. I haven't modified those at all for GraphQL migration. I have lot of other code which in those classes which uses `BuildServiceProvider()` for some purpose.
2. `InitializeDependencies` method is also old legacy code since `BaseMiddleware` is old legacy code.
3. Do I really need to touch `BaseMiddleware` constructor? I am trying to avoid touching any legacy code base to make this work.
4. Same thing with `HealthServiceMiddleware` as it's a legacy code base.
5. That's a bug which I missed checking in. I have added that back in.

Idea is to migrate each use case one by one to GraphQL layer and since my legacy app has lot of codes which I haven't shown here but this repo mimics exact same setup basically. I have more than 10 middlewares in my original code. 

Is there any way to make this work without changing too much `HealthServiceMiddleware`, `BaseMiddleware` or `BuildServiceProvider` method? I am still confuse why this doesn't work? @sungam3r

**Comment by sungam3r** [comment]
> BuildServiceProvider code is like that only in our application since ages. I have lot of other code in those classes which uses BuildServiceProvider() for some purpose.

It is sad. It means you used the DI incorrectly all this time.

> Do I really need to touch BaseMiddleware constructor?

You can always add one more constructor wihout touching exesting one.

> Is there any way to make this work without changing too much HealthServiceMiddleware, BaseMiddleware or BuildServiceProvider method? I am still confuse why this doesn't work? I mean what's the actual problem?

The actual problem is that most likely you misunderstand the core principles of the Dependency Injection. I advise you to learn the basic concepts first. I have described to you what you should and shouldn't do based on how to properly work with Dependency Injection. If your system was originally designed in such a way that it goes against DI design, then I can hardly help you with anything else.

**Comment by TechGeeky** [comment]
I see. Thanks for looking into this. Can you explain why our current setup is against DI design? I mean little bit more in technical way so that I can talk to our team members about this? 

Also if I add another `BaseMiddleware` constructor like this `public BaseMiddleware(RequestDelegate next, ICatalogService srv1, ICustomerService srv2)`  then what should be the content of that constructor? I can try running it locally and see if it works for me.

**Comment by sungam3r** [comment]
https://stackoverflow.com/questions/58999401/calling-buildserviceprovider-from-application-code-results-in-copy-of-singleto
https://stackoverflow.com/questions/58804132/asp-net-core-3-0-disable-asp0000-do-not-call-iservicecollection-buildservicepr

For general advice on designing applications (not related to GraphQL.NET), I advise you to ask a question on StackOverflow.

**Comment by sungam3r** [comment]
Closed as answered.
