### ISSUE TITLE
How to enable Compression ...

### ISSUE THREAD

**Issue by KreeziOS** [graphql-dotnet/graphql-dotnet#2288]
Hello ,

I was trying to enable response compression in my application ...

 On the server side ...I  was able to successfully configure it on the GraphQL Server using ASP .Net Core Response Compression Middleware
```
            services.AddResponseCompression(options =>
            {
                options.Providers.Add<BrotliCompressionProvider>();
                options.Providers.Add<GzipCompressionProvider>();
                options.MimeTypes =
                    ResponseCompressionDefaults.MimeTypes.Concat(
                        new[] { "application/json" });
            });
```
And on the client side , using a GraphQLHttpClient I am passing the required headers using the underlying HttpClient Instance..

```
            using var graphQLClient = new GraphQLHttpClient(graphQLEndpoint, new NewtonsoftJsonSerializer());
            graphQLClient.HttpClient.DefaultRequestHeaders.Clear();
            graphQLClient.HttpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            graphQLClient.HttpClient.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));
            var httpClientHandler = new HttpClientHandler
            {
                AutomaticDecompression = System.Net.DecompressionMethods.GZip
            };
            graphQLClient.Options.HttpMessageHandler = httpClientHandler;
```

However , when I run it , the client is uanble to parse the response and throws an error 

> {"Unexpected character encountered while parsing value: \u001f. Path '', line 0, position 0."}

I inspected the request using Fiddler and found that the client was sending the desired headers and the server is able to compress the data seamlessly ... the problem seems to be at the receiving end . 

Is there anything that I am doing wrong . 

Thanks
SK

**Comment by Shane32** [comment]
Have you tried using the defaults for the client side? HttpClient should decompress automatically without extra code.

**Comment by Shane32** [comment]
Have you tried GraphiQL or similar? ( If GraphiQL works you can be sure that it’s a client side problem.)

**Comment by KreeziOS** [comment]
Hello Shane32 ,
Thanks for the quick response.
1.Defaults did not work as it was not setting the required gzip header.
2.I just tried GraphiQL and it works neatly (the compressed size is actually very good too)... 
and it sends these in the request headers ; so technically it means compression should work without any issues , right !?
`Accept-Encoding: gzip, deflate, br`

Thanks 
SK

**Comment by Shane32** [comment]
Yes, if GraphiQL works then you should be good. Offhand I’m not sure how to configure the client to request and process compressed responses.

**Comment by KreeziOS** [comment]
Okay Shane  ... no problem but Thanks for the GraphiQL idea ; i'll try to set a few more headers and see if it works .

**Comment by KreeziOS** [comment]
Finally !!  Should have done this first I believe   ... 
need to create an HttpClient instance manually and pass it to the GraphQLHttpClient ... 

```
            HttpClient httpClient = new HttpClient(new HttpClientHandler
            {
                AutomaticDecompression = System.Net.DecompressionMethods.GZip | System.Net.DecompressionMethods.Deflate
            });
            httpClient.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));

            GraphQLHttpClientOptions options = new GraphQLHttpClientOptions();
            options.EndPoint = new Uri(graphQLEndpoint);

            using var graphQLClient = new GraphQLHttpClient(options, new NewtonsoftJsonSerializer(), httpClient);
```

Hope someone finds it useful too ...

Another interesting fact => the response for a GraphiQL request was 200KB smaller .. weird ... may be a challenge for some other day ..
