### ISSUE TITLE
How to pass an object from query variables to InputType object?

### ISSUE THREAD

**Issue by davidport21** [graphql-dotnet/graphql-dotnet#2289]
I am working on designing my input request for my GraphQL layer.

Below is what I have in my UI Playground -

    query($data:Input!) {
      request(data: $data) {
        id
        name
      }
    }

**Query Variables**

    {
        "data": {
            "clientId": 2,
            "filters": [{
                "key": "xyz",
                "value": 100
            }],
            "aggregationType": {
                "aggregationKey": "hello"
            }
        }
    }

Now I am trying to map above request into my `InputType` as shown below but somehow I cannot map `aggregationType` to `AggregationType` object in `ContainerRequest` class. It is always null when I debug in my `Query` class-

    public class InputType : InputObjectGraphType<ContainerRequest>
    {
        public InputType()
        {
            Name = "Input";
            Field(x => x.clientId);
            Field<ListGraphType<FilterType>>("filters", "list of filters");
            // this line doesn't work
            Field(x => x.AggregationType.AggregationKey, nullable: true);
        }
    }

Here is my `ContainerRequest`, `AggregationType` and `Filter` class -

    public class ContainerRequest : IData, IProcess
    {
        public AggregationType AggregationType { get; set; }
        public IList<Filter> Filters { get; set; }
        public int ClientId { get; set; }
    }

    public class AggregationType
    {
        public string AggregationKey { get; set; }
    }

    public class Filter
    {
        public string Key { get; set; }
        public int Value { get; set; }
    }

Now below is how I am using my Query -

    Field<HumanType>(
        "request",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<InputType>> { Name = "data", Description = "some stuff" }
        ),
        resolve: context => data.GetHumanByIdAsync(context.GetArgument<ContainerRequest>("data"))
    );

When I run above request on UI playground then I am not seeing `AggregationType` getting populated in my `ContainerRequest` object from the input I am passing. It looks like something is off in my `InputType` class. Any idea what is wrong I am doing here?

**Comment by davidport21** [comment]
Got it working!

**Comment by sungam3r** [comment]
Relates to #2275 ?
