### ISSUE TITLE
Which database do you use as backend? Is there an example?

### ISSUE THREAD

**Issue by biapar** [graphql-dotnet/graphql-dotnet#229]
Which database do you use as backend? Is there an example?

**Comment by joemcbride** [comment]
This project supports any DB or backend.  Here is an example that uses NancyFX + [Marten](http://jasperfx.github.io/marten/).

https://github.com/joemcbride/marten/tree/graphql2/src/DinnerParty
https://github.com/joemcbride/marten/blob/graphql2/src/DinnerParty/Modules/GraphQLModule.cs

**Comment by biapar** [comment]
So, I wish to try to use (ReactNative)<->.NET Core WebAPI + GraphQL DotNet <-> SQL Server and as second try (ReactNative)<->FeahterJS <-> .NET Core WebAPI + GraphQL DotNet <-> SQL Server

What Do you think about?

**Comment by joemcbride** [comment]
Yep, GraphQL .NET is just a library that you can use with anything.  I'm not sure why you would want to use both FeathersJS (node + REST) + GraphQL .NET?  If you're using node, you can also use GraphQL for node?

Going to close this.
