### ISSUE TITLE
How to represent response object type for complex json objects?

### ISSUE THREAD

**Issue by davidport21** [graphql-dotnet/graphql-dotnet#2290]
`ContainerResponse` is the class which contains response for my request -

**ContainerResponse.cs**

    public class ContainerResponse
    {
        public int ResponseCode { get; set; }
        public ClientResponse ClientResponse { get; set; }
    }

**ClientResponse.cs**

    public class ClientResponse
    {
        public int ClientGroupCount { get; set; }
        public IList<ClientGroup> ClientGroups { get; set; }
    }

**ClientGroup.cs**

    public class ClientGroup
    {
        public string ClientLabel { get; set; }
        public string ClientType { get; set; }
        public string ClientGroupName { get; set; }
        public int ClientCount { get; set; }
        public IList<Client> Clients { get; set; }
        public int OrderNumber { get; set; }
    }

**Client.cs**

    public class Client
    {
        public string ClientId { get; set; }
        public int ClientValuesCount { get; set; }
        public IList<ClientValue> ClientValues { get; set; }
    }

**ClientValue.cs**

    public class ClientValue
    {
        public string DisplayValue { get; set; }
        public int ValueId { get; set; }
        public int totalCount { get; set; }
        public ClientUrl ClientUrl { get; set; }
        public double? OrderNumber { get; set; }
    }

**ClientUrl.cs**

    public class ClientUrl
    {
        public string Alias { get; set; }
        public string Resource { get; set; }
        public string BaseResource { get; set; }
        public string QueryString { get; set; }
        public string Url { get; set; }
    }

**ClientSnippet.cs**

    public class ClientSnippet
    {
        public string ImagePath { get; set; }
    }

Below is the sample JSON response for my above POCO -

    {
        "responseCode": 200,
        "clientResponse": {
            "clientGroupCount": 1,
            "clientGroups": [{
                "clientLabel": "Hello World",
                "clientType": "states",
                "clientGroupName": "states",
                "clientCount": 1,
                "clients": [{
                    "clientId": "t",
                    "clientValuesCount": 98,
                    "clientValues": [{
                        "displayValue": "Texas Sports",
                        "valueId": 1118,
                        "totalCount": 9876,
                        "clientUrl": {
                            "alias": "poy/texas",
                            "resource": "abc12345poqert",
                            "baseResource": "a-b-ce-kj-123",
                            "url": "poy/texas/abc12345poqert"
                        },
                        "orderNumber": 12311
                    }]
                }],
                "orderNumber": 0
            }]
        }
    }

Now I am trying to represent my graphql output in this below format using `GraphQL` -

    {
      "data": {
        "output": [
          {
            "title": "Hello World",
            "type": "states",
            "links": [
              {
                "clientId": "abc12345poqert",
                "totalCount": 9876,
                "resource": "a-b-ce-kj-123",
                "text": "Texas Sports",
                "href": "poy/texas/abc12345poqert"
              }
            ]
          }
        ]
      },
      "extensions": {
        "runTime": 29
      }
    }

Below is my Query - 

    Field<ResponseType>(
        "output",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id"}
        ),
        resolve: context =>
        {
            var input = context.GetArgument<string>("id");
            var containerResponse = data.GetResponse(input);
            return containerResponse;
        }
    );

Below is my `ResponseType` class which I started with but I got confuse on how to proceed further for other classes. Since my json is little bit complex so kinda confuse on how my other class will look like?

    public class ResponseType : ObjectGraphType<ContainerResponse>
    {
        public ResponseType()
        {
            Name = "Output";
            Field(h => h.ResponseCode).Description("Response Code of the request.");
            // is this right?
            Field<ObjectGraphType<ClientResponseType>>("clientResponse", "some stuff");
        }
    }

    public class ClientResponseType : ObjectGraphType<ClientResponseType>
    {
        public ClientResponseType()
        {
            Name = "ClientResponse";
            Field(h => h.ClientGroupCount).Description("some stuff");
            .....
        }
    }

Any example will be greatly appreciated.

**Comment by sungam3r** [comment]
`public class ClientResponseType : ObjectGraphType<ClientResponseType>`
->
`public class ClientResponseType : ObjectGraphType<ClientResponse>`

**Comment by davidport21** [comment]
yeah I already fixed that but I am seeing an error as -

```
System.InvalidOperationException: Required service for type GraphQL.Types.ObjectGraphType`1[Golden.Contracts.Types. ClientResponseType] not found
```

I have already added service as well - 

```
services.AddSingleton<ClientResponseType>();
```

**Comment by Shane32** [comment]
Fix:
```
//Field<ObjectGraphType<ClientResponseType>>("clientResponse", "some stuff");
Field<ClientResponseType>("clientResponse", "some stuff");
```
