### ISSUE TITLE
Why does my GraphQLMiddleware keeps getting called in background from UI Playground?

### ISSUE THREAD

**Issue by davidport21** [graphql-dotnet/graphql-dotnet#2291]
I have a simple GraphQL app based off from [here](https://github.com/graphql-dotnet/examples/tree/master/src/AspNetCore). The only difference is I have added `GraphQLMiddleware` class from `AspNetCoreCustom` folder to `AspNetCore` one in my local and everything works as expected.

I have noticed a very weird thing - Once I start that application and open UI playground then all the methods in `GraphQLMiddleware` class keeps getting  called in backgound it seems without even hitting any real requests.

Once I provide normal request in UI playground and hit execute button in middle then it gives me data back but if I don't do anything and keep UI playground open in the browser then still my `GraphQLMiddleware` class gets called on its own. I am not sure why is this the case? Any idea?

Is there any way to disable this so that it should only get called when I am hitting real requests either from curl or UI playground?

**Comment by Shane32** [comment]
You should be able to open the debug view of your browser and see what request it’s making periodically.

**Comment by sungam3r** [comment]
https://github.com/graphql/graphql-playground#settings
> 'schema.polling.enable': true, // enables automatic schema polling

**Comment by davidport21** [comment]
good catch. thanks for the link.
