### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#230]
Here is my initial list of documentation that is needed.

https://github.com/graphql-dotnet/graphql-dotnet/pull/217

### Getting Started

- [x] Basics
- [x] GraphiQL
- [x] Queries
- [x] Arguments
- [x] Mutations
- [x] Interfaces
- [x] IsTypeOf
- [x] Unions
- [x] ResolveType
- [x] Variables
- [x] Query Validation
- [x] Subscriptions (basic info is there, could use an example)
- [x] Schema Generation

### Learn
- [x] Error Handling
- [x] User Context
- [x] Dependency Injection
- [x] Object/Field Metadata
- [x] Field Middleware
- [x] Authentication / Authorization
- [x] Protection Against Malicious Queries / Query Complexity Analysis
- [x] Query Batching
- [x] Metrics
- [x] Relay (basic info is there, could use an example)

**Comment by dNetGuru** [comment]
Added #238.

**Comment by joemcbride** [comment]
Closing after the #238 merge.
