### ISSUE TITLE
Question about use of Newtonsoft.Json with graphql-dotnet version 3.3.2

### ISSUE THREAD

**Issue by edavedian** [graphql-dotnet/graphql-dotnet#2311]
Hello,

I am reading the documentation here https://graphql-dotnet.github.io/docs/migrations/migration3/ and I would like to continue to use Newtonsoft.Json as it is stated in the document.  I changed the GraphQLRequest as is indicated in the document as follows:

```
public class GraphQLRequest
{
    public string OperationName { get; set; }

    public string Query { get; set; }

    [JsonConverter(typeof(GraphQL.SystemTextJson.ObjectDictionaryConverter))]
    public Dictionary<string, object> Variables { get; set; }
}
```

But when I submit the request, I get the following exception:

```
System.InvalidCastException: Unable to cast object of type 'GraphQL.SystemTextJson.ObjectDictionaryConverter' to type 'Newtonsoft.Json.JsonConverter'.
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetJsonConverter(Object attributeProvider)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes(JsonProperty property, Object attributeProvider, String name, Type declaringType, MemberSerialization memberSerialization, Boolean& allowNonPublicAccess)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
```

I believe I am missing a configuration and I was wondering if I could ask you to assist in resolving this issue.

**Comment by Shane32** [comment]
The sample you copied was explaining how to convert to using the System.Text.Json converter.

Have you tried leaving that member as it was?
```cs
public Newtonsoft.Json.Linq.JObject Variables { get; set; }
```

I think we may have a type-o in the documentation, where the sample on top is showing the changes necessary for 3.0 with the Newtonsoft converter:
![image](https://user-images.githubusercontent.com/6377684/108925726-2a389080-760b-11eb-9bb5-90681c391080.png)

@sungam3r  can you confirm?

**Comment by sungam3r** [comment]
Yes. 2.x -> 3.0 and converter -> package.

**Comment by edavedian** [comment]
Thank you for clarifying the documentation typo.  I used the following but the got the same exception. 

```
    GraphQLRequest request;
    using (var reader = new StreamReader(context.Request.Body))
    using (var jsonReader = new JsonTextReader(reader))
    {
        var ser = new JsonSerializer();
        request = ser.Deserialize<GraphQLRequest>(jsonReader);
    }
```  

I am now trying to go back to and see if I could make that work

```
public Newtonsoft.Json.Linq.JObject Variables { get; set; }
```

**Comment by edavedian** [comment]
I got it to work with 

```
public Newtonsoft.Json.Linq.JObject Variables { get; set; }
```

but here is the issue I am facing now.  Previously with graphql-dotnet 2.0 I was able to only see the 'data' and 'errors' elements serialized in the response.  But now I see everything in the ExecutionResult object.  How would I be able to control the serialization of ExecutionResult to only show 'data' and 'errors' and for 'errors' only if not null.

**Comment by Shane32** [comment]
Please look at the same sample in the migration document you previously linked to.  You will see these two lines of code:

```cs
    var writer = new GraphQL.NewtonsoftJson.DocumentWriter();
    await writer.WriteAsync(context.Response.Body, result);
```

It is necessary to use a `GraphQL.NewtonsoftJson.DocumentWriter` instance to properly serialize the response to JSON.

**Comment by edavedian** [comment]
Thank you so very much.  It is almost working all the way.  How would I be able to eliminate the 'extensions' element from the 'errors' node.  This will make the response identical to what I had when using the 2.0 version.  Also the 'extensions' in our case is leaking some information as to why the request was rejected and it would be best to not return it.

**Comment by Shane32** [comment]
You can provide options to an instance of `ErrorInfoProvider` which is passed to the `DocumentWriter` constructor.  Please see https://graphql-dotnet.github.io/docs/getting-started/errors/#error-serialization for a detailed answer.  For instance, setting `ExposeExtensions` to `false` will completely hide the `extensions` property from being serialized.

**Comment by edavedian** [comment]
Thank you very much.  I really appreciate the support.
