### ISSUE TITLE
Inconsistent casting of input arguments for arrays

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#2313]
In the following code (In LinqPad), there is an input object with two properties and both are List of string.

In the query, for list1 one single value is passed (without []) and list 2 is passed with one value as array:
(Before this, I even did not know when parameter is defined as list, one single value could be passed without [] )

```
list1: "item1",
list2: ["item2"]
```

When the input parameter is getting cast to Dictionary<string, object>, the type of **list1** is **System.Object[]** and the type of **list2** is **System.Collections.Generic.List`1[System.Object]**

```csharp
void Main()
{
	var schema = new Schema { Query = new TestQuery() };

	var exec = new DocumentExecuter();

	var result = exec.ExecuteAsync(options =>
			{
				options.Schema = schema;
				options.Root = null;
				options.Query = "{ test(input: {list1: \"item1\", list2: [\"item2\"]}) { prop1  } }";
				options.OperationName = "";
			}
	).Result;
}

public class TestQuery : ObjectGraphType
{
	public TestQuery()
	{

		Field<TestResponseType>(
			name: "test",
			arguments: new QueryArguments(
				new QueryArgument<InputType> { Name = "input" }
			),
			resolve: context =>
			{
				var input = context.GetArgument<Dictionary<string, object>>("input");
				input["list1"].GetType().Dump();  	//<--- System.Object[]
				input["list2"].GetType().Dump();	//<--- System.Collections.Generic.List`1[System.Object]
				return new TestResponse();
			}
		);
	}
}

public class TestResponseType : ObjectGraphType<TestResponse>
{
	public TestResponseType()
	{
		Field(h => h.Prop1);
	}
}

public class TestResponse
{
	public string Prop1 { get; set; } = "Prop1";
}

public class InputType : InputObjectGraphType
{
	public InputType()
	{
		Field<ListGraphType<StringGraphType>>("list1");
		Field<ListGraphType<StringGraphType>>("list2");
	}
}

```

**Comment by Shane32** [comment]
This is designed this way for performance reasons.  Both can be cast to `IList<object>` for a consistent view of the data.

**Comment by Shane32** [comment]
Note that within v4, you should almost always be returned an `object[]` instance, rather than a `List<object>` instance.  However, it is still possible to be returned a `List<object>` if the argument is passed within a variable, and the variable value instance is an `IEnumerable` but does not implement `IList`.

**Comment by Shane32** [comment]
> when parameter is defined as list, one single value could be passed without [] 

This is pursuant to the GraphQL specification.

**Comment by rmeshksar** [comment]
We recently migrated from very old GraphQL .NET 0.14 to 3.2 and I noticed in old version it is always object[] .

So, I thought it might be a bug in 3.2.

**Comment by Shane32** [comment]
Please let me know if you have further questions.
