### ISSUE TITLE
DataLoader cache key collisions when alised fields are used

### ISSUE THREAD

**Issue by jack775544** [graphql-dotnet/graphql-dotnet#2326]
## Description

Version: 3.3.2

I am using the data loader feature and coming across an interesting issue with conflicting data loader keys when being used with query aliases.

### Steps to reproduce

I have a field created like so
```cs
Field<ListGraphType<OrderType>, IEnumerable<Order>>()
	.Name("Orders")
	.Argument<StringGraphType>("name").Description("Filter on the order name")
	.ResolveAsync(ctx =>
	{
		var ordersLoader = accessor.Context.GetOrAddCollectionBatchLoader<int, Order>(
			"GetOrdersByUserId",
			keys => orders.GetOrdersByUserIdAsync(keys, name));
		return ordersLoader.LoadAsync(ctx.Source.UserId);
	});
```

Which shall retrieve a list of related entities with a filter on the name property of the related entity. This works great until we try to fetch the relation twice with 2 different arguments

```gql
{
	users {
		id
		firstSubset : orders(name: "Paint") {
			id
			name
		}
		secondSubset : orders(name: "Brushes") {
			id
			name
		}
	}
}
```

### Expected result

Each aliased subquery will return different results.

### Actual result

Since both the aliases will be using the same cache key they will return the same results, which is an issue since they were called with different arguments

### Workaround

Currently I am working around this issue by concatenating my query path with the cache key name.

```cs
// Only get string parts of the query since the ints will force the a new call for each record returned.
var queryPath = context.ResponsePath.Where(x => x is string);
var ordersLoader = accessor.Context.GetOrAddCollectionBatchLoader<int, Order>(
	string.Join("-", queryPath) + "GetOrdersByUserId",
	....
```

**Comment by sungam3r** [comment]
> Since both the aliases will be using *the same** cache key 

After all, you yourself chose this key. The described behavior is quite expected. Shape the keys accordingly. I don't think there is anything to be done in GraphQL.NET. @Shane32  ?

**Comment by jack775544** [comment]
I was thinking that myself, I wasn't really sure that this was really a bug or if it was just intended behaviour instead. It just seems unintuitive that if you use a data loader on any field that takes arguments then you need to create dynamic cache keys instead of it just being handled for you.

**Comment by Shane32** [comment]
Agree.  The problem is that you are capturing a key and passing it directly into the dataloader.  I suggest including the arguments with the data key rather than with the data loader key.

```cs
Field<ListGraphType<OrderType>, IEnumerable<Order>>()
	.Name("Orders")
	.Argument<StringGraphType>("name").Description("Filter on the order name")
	.ResolveAsync(ctx =>
	{
		var name = ctx.GetArgument("name");
		var ordersLoader = accessor.Context.GetOrAddCollectionBatchLoader<(int, string), Order>(
			"GetOrdersByUserIdAndName",
			keys => orders.GetOrdersByUserIdAndNameAsync(keys));
		return ordersLoader.LoadAsync((ctx.Source.UserId, name));
	});

//rewrite GetOrdersByUserIdAsync like so:
public Task<ILookup<(int, string), Order>> GetOrdersByUserIdAndNameAsync(IEnumerable<(int, string)> keys)
{
	...
}
```

That's a general idea.  Depending on your data logic, you may need to group by name and issue multiple calls to your data provider to return the data (in which case you might as well use the workaround you already found, which is a perfectly acceptable solution).

**Comment by jack775544** [comment]
Thanks for the guidance, happy to know that I was on the right path :)
