### ISSUE TITLE
Further cleanup

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2327]
> Let's remove Fragments property from ExecutionContext and IResolveFieldContext. For some reason I missed it last time.

https://github.com/graphql-dotnet/graphql-dotnet/pull/2312#discussion_r583685445

> Let's remove GraphQL.Language.AST.Fields. I see only one usage of public void Add(Field field). Also anyone can call "native" Add/[] methods from dictionary ignoring "special" Add(Field field) method.

https://github.com/graphql-dotnet/graphql-dotnet/pull/2312#discussion_r583690941

**Comment by Shane32** [comment]
> Let's remove Fragments property from ExecutionContext and IResolveFieldContext. For some reason I missed it last time.

Remove GraphQL.Language.AST.Fields

> Let's remove this class. I see only one usage of public void Add(Field field). Also anyone can call "native" Add/[] methods from dictionary ignoring "special" Add(Field field) method.

**Comment by Shane32** [comment]
> I think we can safely remove schema argument and two lines from IAbstractGraphType.GetObjectType

```cs
 if (result is GraphQLTypeReference reference)
                result = schema.AllTypes[reference.TypeName] as IObjectGraphType;
```

**Comment by Shane32** [comment]
Remove TypeExtensions.IsPrimitive
