### ISSUE TITLE
Rename DirectiveGraphType

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2329]
See https://github.com/graphql-dotnet/graphql-dotnet/pull/2321/files#r583946032

**Comment by sungam3r** [comment]
What we have today:
1. `GraphQLParser.AST.ASTNodeKind.DirectiveDefinition`
2. `GraphQLParser.AST.GraphQLDirectiveDefinition`
3. `GraphQL.Language.AST.Directives` - collection wrapper for `Directive` 
4. `GraphQL.Language.AST.Directive`
5. `GraphQL.Types.DirectiveGraphType` <- **not a graph type**
6. `GraphQL.Types.AppliedDirectives` - collection wrapper for `AppliedDirective` 
7. `GraphQL.Types.AppliedDirective`
8. `GraphQL.Introspection.__Directive`
9. `GraphQL.Introspection.__AppliedDirective`

Options:
1. Change nothing 😄 
2. Revise the entire naming system for directives 😨 
3. Change only `DirectiveGraphType` and maybe something else.

**Comment by Shane32** [comment]
I’d pick between 2 and 3.

**Comment by sungam3r** [comment]
GraphQL.Types.DirectiveGraphType -> GraphQL.Types.DefinedDirective ? 😕

**Comment by Shane32** [comment]
I always get confused on the different types of directives and how they work.  Nor do I use them.  You decide.

**Comment by sungam3r** [comment]
I don't want to do any changes for this in v4.

**Comment by sungam3r** [comment]
Update. What we have today (after 1 year past):

    1. GraphQLParser.AST.ASTNodeKind.Directive / GraphQLParser.AST.GraphQLDirective
    2. GraphQLParser.AST.ASTNodeKind.DirectiveDefinition / GraphQLParser.AST.GraphQLDirectiveDefinition
    3. GraphQL.Types.SchemaDirectives <- collection wrapper for DirectiveGraphType 
    3. GraphQL.Types.DirectiveGraphType <- not a graph type
    4. GraphQL.Types.AppliedDirectives <- collection wrapper for AppliedDirective
    5. GraphQL.Types.AppliedDirective
    6. GraphQL.Introspection.__Directive <- introspection type around DirectiveGraphType
    7. GraphQL.Introspection.__AppliedDirective <- introspection type around AppliedDirective

Also note that
![изображение](https://user-images.githubusercontent.com/21261007/152607144-5ea76bc1-e664-4883-b720-a72fb003d9a8.png)
![изображение](https://user-images.githubusercontent.com/21261007/152607179-ec1d98db-9360-4f0d-af6a-0c1f8fdc07e1.png)

So... I simply suggest to rename `DirectiveGraphType` into `Directive` 😮 . In this case, the naming will be as apparent as possible. ping @Shane32

**Comment by Shane32** [comment]
Ok

**Comment by sungam3r** [comment]
I think I'll do it after all "big" PRs with our refactorings to eliminate conflicts.

**Comment by sungam3r** [comment]
Done in #2925
