### ISSUE TITLE
Add null support to ScalarGraphType

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2333]
I’m thinking that we should issue another PR immediately after this one to have scalars handle null values. People have asked for it before, and with all the cleanup we have done for v4, it will be very easy to implement (finally!).

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/pull/2321#discussion_r584180364_

**Comment by Shane32** [comment]
Unfortunately it wasn't easy to implement 😢 but it looks like it's nearly done now.

**Comment by sungam3r** [comment]
Closing ?
