### ISSUE TITLE
StringGraphType only accepts strings

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2335]
I'm okay to change this for v4.  Should not be changed during an interim version.  Will break code where people incorrectly return a number instead of a string, expecting GraphQL to cast it to a string automatically.  If you think we should do this also, let's do it in a separate PR.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/pull/2321#discussion_r584363939_

**Comment by sungam3r** [comment]
Also https://github.com/graphql-dotnet/graphql-dotnet/pull/2341/files/83d84d3070a78d54ae92ee1af2cc2618c390bee0#r585355828

**Comment by sungam3r** [comment]
Done?
