### ISSUE TITLE
Cache schema-first AST default values

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2336]
Of course we **can** cache AST in internal `FieldType` property and reset it in `DefaultValue.set`. The same for `QueryArgument`.

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/graphql-dotnet/pull/2321#discussion_r584195301_

**Comment by Shane32** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/109436964-6f0d5e80-7a33-11eb-90e8-0e9d4df4f733.png)

**Comment by Shane32** [comment]
Fixing this issue will not require the old code to be restored, as the AST from the schema-first syntax will be cached.  And code-first should not be setting a dictionary to a default value.

**Comment by Shane32** [comment]
And we decided not to provide a default implementation.

https://github.com/graphql-dotnet/graphql-dotnet/pull/2321#discussion_r584374625

**Comment by sungam3r** [comment]
See `TypeConfig`/`FieldConfig`. Now `FieldConfig` lacks `DefaultValue` property. And **if** we add this property that user **can** set this default (to dictionary or not).

**Comment by sungam3r** [comment]
You just need to keep this possibility in mind.

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/109437410-c9a7ba00-7a35-11eb-854f-b180c68bc0d6.png)

I'm talking about the same approach for `DefaultValue`.

**Comment by Shane32** [comment]
I'll take a look for sure.  Thanks for referencing the code that pertains here.

Initial thought: if there was a `FieldConfig.DefaultValue` field, it would be set to an internal representation of the custom object, just like a code-first syntax of `field.DefaultValue = xxx`, correct?  So we should be all set already ... if we ever add that property.

**Comment by sungam3r** [comment]
Probably.

**Comment by Shane32** [comment]
After the finished scalar rework, I do not think we should make any changes here, and close this issue.  Ok @sungam3r ?

**Comment by sungam3r** [comment]
Agree, but I want to add DefaultValue into `FieldConfig`. I'll publish PR.
