### ISSUE TITLE
Add test for schema validator

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2337]
Need a test to verify.

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/graphql-dotnet/pull/2321#discussion_r584126120_

**Comment by sungam3r** [comment]
I don't remember what the test it is, something with default value. Nevertheless, we have `SchemaInitializationTests` and I see `SchemaWithInvalidDefault_Should_Throw`. I propose to close. We have a lot of uncovered code. It is clear that we have to write tests for this code.

**Comment by Shane32** [comment]
Ok
