### ISSUE TITLE
Add ResolvedType == null check

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2338]
Regarding `field.ResolvedType != null` check here and in `VisitFieldArgumentDefinition`. I think that no one field/argument after schema initialization may have `null` in `ResolvedType`. Let's add one more explicit check for `ResolvedType != null` and remove it from here and `VisitFieldArgumentDefinition`: ` if (field.DefaultValue != null ` / `if (argument.DefaultValue != null`

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/graphql-dotnet/pull/2321#discussion_r584126909_

**Comment by sungam3r** [comment]
I will take it. Ok?
