### ISSUE TITLE
Provide Strong-Named Assemblies

### ISSUE THREAD

**Issue by Mischi** [graphql-dotnet/graphql-dotnet#234]
Hi,

thanks for your dotnet port! We noticed that the assemblies from the official nuget packages are not [Strong named Assemblies](https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx). We're trying to integrate graphgl-dotnet and graphql-parser into one of our projects which uses Strong named Assemblies and therefore requires that all dependencies are also Strong named Assemblies. Have you any plans to provide Strong named Assemblies? I would take a look at this and will try to come up with a PR if your're interested in this.

Cheers,
Fabian

**Comment by jeremydmiller** [comment]
@joemcbride I'd strongly recommend you point users at [Strongnamer](https://github.com/dsplaisted/strongnamer) and try to hold off on signing the assemblies

**Comment by joemcbride** [comment]
I do not currently have plans to provide strongly named assemblies.  Perhaps what @jeremydmiller suggested would work?

**Comment by Mischi** [comment]
Yes, Strongnamer works perfectly for us 👍 Didn't know about it before. Thanks for your quick help!
