### ISSUE TITLE
question: Does it possible to work not only with EF?

### ISSUE THREAD

**Issue by MakaBuka** [graphql-dotnet/graphql-dotnet#235]
Hi guys,

I've tried to use GraphQL in my project (instead of REST api) but I have one immutable request  - using SharePoint lists.
As far as I see, graphql-dotnet has only one adapter which uses to get data from DB and it's EF.
So, could you provide me more info is it possible to parse GraphQL query and apply it to another db (like sharepoint)? 

Looking forward to your reply
Thx, Dima.

**Comment by joemcbride** [comment]
GraphQL is database/data agnostic.  EF is not required at all and there is nothing in this project that is EF specific.  You can get your data from anywhere and however you want.  That means Sharepoint IS supported.  I'm guessing Sharepoint has some sort of REST api?  Make that API call in your field resolver.

**Comment by MakaBuka** [comment]
Hi joemcbride,
First of all, thank you for the prompt replay. 
According to EntityFrameworkExecutionTests.cs I found that you're using EFcontext (based on DbContext - which includes populating objects with data from a database, change tracking, and persisting data to the database):
var schema = GraphQL<EfContext>.CreateDefaultSchema(() => new EfContext());
It's mean, that we will have up-to-date data (let's assume that our EFContext is configured and working with MSSQLLocalDB).

It would be great if you clarify me (or just send  me an example) how it works without EF (in case when we have to retrieve/update data from database like mysql or mssql) 

Looking forward to your reply.
Thx, Dima.

**Comment by joemcbride** [comment]
That test does not exist in this project.  I think you meant to post in this other GraphQL project.

https://github.com/ckimes89/graphql-net/blob/981a6edb63726863a1a5d2acf727c5d683080d21/Tests.EF/EntityFrameworkExecutionTests.cs

They should be able to help you with that specific project.
