### ISSUE TITLE
Allow parsing enum variable by native .NET type

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2356]
> There's just no reason for any external values to be parsed as internal values.

My point is that for variables we cannot say for sure what is `internal` and `external` values.

> There's no way for json -- the transport of choice for graphql -- to carry an .NET enumeration type to be parsed at all. 

Forget about JSON. This is just one of the sources. Think about the fact that the variables can simply be created programmatically. In the end, this is the essence of the runtime - the runtime/platform on which the application is running.

> So if you allowed ParseValue to contain the internal value 1, you should also allow the literal to parse the value 1. 

Absolutely no. Literal is a part of GraphQL language. Variables are transport/platform specific. Also keep in mind that there may be no any transport at all.

> I don't mind allowing native types within ParseValue for Guid/Uri/DateTime/DateTimeOffset because you can consider the values as external values -- **in another format**. Just like receiving a double for a decimal graph type -- no problem, coerce the type. But parsing an enum against an internal list of values is not the same thing.

Why that argument about _just another format_ cannot be applied to enums ?

I suggest to add a new issue pointing to that thread and go on with this PR.

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/graphql-dotnet/pull/2341#discussion_r588407993_

**Comment by sungam3r** [comment]
Also https://github.com/graphql-dotnet/graphql-dotnet/pull/2341/files#r588350946

**Comment by Shane32** [comment]
These links you post (`files/#r123456` and similar) do not work for me.  It always just brings me to the top of the files page.

**Comment by Shane32** [comment]
The conversation links have been working fine, however. (e.g. `issues/2356#issuecomment-12345678`)

**Comment by Shane32** [comment]
Here is an option for allowing native .NET types to be parsed by ParseValue:

```cs
        public override object ParseValue(object value) => value switch
        {
            string s => Values.FindByName(s)?.Value ?? ThrowValueConversionError(value),
            Enum e => Values.FindByName(e.ToString())?.Value ?? ThrowValueConversionError(value),
            null => null,
            _ => ThrowValueConversionError(value)
        };


        public override bool CanParseValue(object value) => value switch
        {
            string s => Values.FindByName(s) != null,
            Enum e => Values.FindByName(e.ToString())?.Value != null,
            null => true,
            _ => false
        };
```

It retains the ability of ParseValue to only accept values based on their external names, and does not search by internal value.

**Comment by sungam3r** [comment]
Should handle enum casing.

**Comment by Shane32** [comment]
Already case insensitive matching

**Comment by sungam3r** [comment]
I'm talking about CONSTANT_CASE.

**Comment by Shane32** [comment]
Right; probably needs to be `ChangeEnumCase(e.ToString())`.

**Comment by sungam3r** [comment]
Yes
