### ISSUE TITLE
GraphQLTypeReference missing in 4.0

### ISSUE THREAD

**Issue by adamjones1** [graphql-dotnet/graphql-dotnet#2364]
I've just been updating my consumer code to use GraphQL 4.0.0-preview-240 in development in order to further test it and anticipate any gotchas that might come up with migrating to a new major version. So far it all looks fine (though I haven't gotten it to compile yet), except one thing: `GraphQLTypeReference` has been made internal.

This bit of functionality was integral to my use case of GraphQL.Net, I found it very useful when building schemas with circular references (which is most schemas). I can elaborate more if desired. Could this internalisation please be reversed or equivalent replacement functionality released?

**Comment by sungam3r** [comment]
What is your use case? This type has been marked as internal intentionally.

**Comment by adamjones1** [comment]
Basically, I'm writing an adapter layer from another data model (not GraphQL-related) to hook it up to GraphQL.Net. I'm not in control of the exact shapes of the data that are in the GraphQL schema, instead I work with something morally a bit like this:
```
interface ITypeVisitor<T>
{
    T VisitIntegerType();
    T VisitStringType();
    T VisitArrayType(T visitedElementType);
    T VisitObjectType(string typeName, Dictionary<string, T> visitedFieldTypes);
    T VisitObjectReference(string typeName);
    ...
}
```
So in other words, something beyond my control defines some data types like Human or Droid in some data model, and I can interact with it by implementing this interface and telling it to do something (producing a result of type `T`) at each kind of node in the hierarchy of the data type, and giving the visitor to the framework for evaluation. In my case I want to produce a GraphQL type from the data type to create a GraphQL schema overall, so `T` in this implementation is `IGraphType` and I return an `IntegerGraphType` from `VisitIntegerType`, an `ObjectGraphType` from `VisitObjectType` using its name and the graph types of the fields, etc. When the evaluation is done I get back the `IGraphType` of the root data type from the framework which I then include when building my Query type for the schema.

You can probably see where I'm going - one of the possibilities in the data model is of a 'soft reference' where you can essentially declare a pointer to an object of another type. In `VisitObjectReference`, I return a `GraphQLTypeReference` to the type returned elsewhere in the hierarchy in a `VisitObjectType` call by the name given by the pointer. There might be workarounds for this by attempting to store visited object types as the hierarchy is traversed and making the return type lazy and ensuring to evaluate objects before references or something, but `GraphQLTypeReference` was by far the most elegant and natural fit for my problem.

There were other usages of it elsewhere too but I think this broadly captures the spirit of all of them - basically I'm dynamically creating a schema and in some places in the API I work with I don't have access to the details of a type, only a reference to it and the assurance that the type is processed with its details elsewhere, and it's very finnicky (if possible) to bring the result of that processing into the current scope where the reference is processed.

**Comment by SebastianStehle** [comment]
Hi, I am doing exactly the same and I was not aware that this type even exists.

Therefore what I have done is to implement a 2-pass approach:

1. Loop over all my models and create the ObjectTypes (but not the fields) and store them in a dictionary.
2. Loop over all my models again and create the fields using the dictionary.

**Comment by Shane32** [comment]
Fixed @adamjones1 .   Please let us know if you have further issues with the v4 beta.

**Comment by adamjones1** [comment]
Thanks, will do! Compiles now, I'm getting some inevitable run-time failures though because the GraphQL.Server packages I'm using aren't updated to use 4.0 yet. I don't suppose there're any pre-release Server packages around that use the v4 beta are there?

**Comment by sungam3r** [comment]
Server packages will be published on top of v4 stable release.

**Comment by adamjones1** [comment]
Just FYI, I've finished testing my app now against v4 (by hacking a local copy of GraphQL.Server source to roughly use v4 previews well enough that it builds) and everything looks good 👍.
