### ISSUE TITLE
Dependency Injection failing when using ASP .Net Core

### ISSUE THREAD

**Issue by phillsteele** [graphql-dotnet/graphql-dotnet#2389]
## Description

When using the query organisation pattern with ASP .Net Core dependency injection is failing.

### Steps to reproduce

I'm attempting to order my queries using the pattern suggested here: https://graphql-dotnet.github.io/docs/getting-started/query-organization

This works fine if I use a similar approach to that given in the example:

    public class Query : ObjectGraphType
    {
        public Query()
        {
            Name = "Query";
            Field<OrganisationGraphType>("organisation", resolve: context => new { });
        }
    }

    public class OrganisationGraphType : ObjectGraphType
    {
        public OrganisationGraphType()
        {
            Name = "OrganisationQuery";
            Description = "Retrieve information on the organisations";
            MemoryRepo repo = new MemoryRepo();

            Field<ListGraphType<OrganisationType>>(
                name: "allOrganisations",
                resolve: context => repo.GetAll()
                );
        }
    }

However, my query needs access to a repository that I want to inject.  I.e.

    public class Query : ObjectGraphType
    {
        public Query()
        {
            Name = "Query";
            Field<OrganisationGraphType>("organisation", resolve: context => new { });
        }
    }

    public class OrganisationGraphType : ObjectGraphType
    {
        private readonly ILogger _logger;

        public OrganisationGraphType(IMemoryRepo repo, ILogger<OrganisationGraphType> logger)
        {
            _logger = logger;
            Name = "OrganisationQuery";
            Description = "Retrieve information on the organisations";

            Field<ListGraphType<OrganisationType>>(
                name: "allOrganisations",
                resolve: context => repo.GetAll()
                );
        }
    }

I'm using ASP.Net Core, according to this documentation the DI it implements is supported: https://graphql-dotnet.github.io/docs/getting-started/dependency-injection

### Expected result

I expect to see the results of my query when I run this.

### Actual result

However, when I attempt to run this query I receive the following error message:

"GraphQL.Execution.UnhandledError: Error executing document.\r\n ---> System.Exception: Failed to call Activator.CreateInstance. Type: GraphQLDemo.Model.OrganisationGraphType\r\n ---> System.MissingMethodException: No parameterless constructor defined for type 'GraphQLDemo.Model.OrganisationGraphType'......

### Environment

This is running locally within Visual Studio on a PC running Windows 64 Professional.

**Comment by sungam3r** [comment]
The problem is that you actually don't use ASP.NET `ServiceProvider`. By default resolution is handled via `DefaultServiceProvider`.
Please show your schema class and program composition root (Startup).

**Comment by phillsteele** [comment]
Ok, this is a copy of my startup class and schema class.  I created a sample project to isolate the issue.

I have to admit I'm confused as to why you would suggest I'm not using the ASP.NET ServiceProvider.  I've not altered any of the DI, so it is using out of the box ASP.NET DI.

    public class Startup
    {
        public Startup(IConfiguration configuration, IWebHostEnvironment environment)
        {
            Configuration = configuration;
            Environment = environment;
        }

        public IConfiguration Configuration { get; }
        public IWebHostEnvironment Environment { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddSingleton<IMemoryRepo, MemoryRepo>()
                .AddSingleton<Query>()
                .AddSingleton<OrganisationType>()
                .AddSingleton<OrganisationGraphType>()
                .AddSingleton<OrgSchema>()
                .AddGraphQL((options, provider) =>
                {
                    options.EnableMetrics = Environment.IsDevelopment();
                    var logger = provider.GetRequiredService<ILogger<Startup>>();
                    options.UnhandledExceptionDelegate = ctx => logger.LogError("{Error} occurred", ctx.OriginalException.Message);
                })
                .AddSystemTextJson(deserializerSettings => { }, serializerSettings => { })
                .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = Environment.IsDevelopment())
                .AddWebSockets()
                .AddDataLoader()
                .AddGraphTypes(typeof(OrgSchema));

            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });


            // Graph QL setup
            app.UseWebSockets();
            app.UseGraphQLWebSockets<OrgSchema>("/graphql");
            app.UseGraphQL<OrgSchema, GraphQLHttpMiddlewareWithLogs<OrgSchema>>("/graphql");
        }
    }


    public class OrgSchema : Schema
    {
        public OrgSchema(Query query)
        {
            Query = query;
        }
    }

**Comment by sungam3r** [comment]
```csharp
public class OrgSchema : Schema
{
    public OrgSchema(Query query, IServiceProvider provider) : base(provider) // <--- " why you would suggest I'm not using the ASP.NET ServiceProvider" - because of that
    {
        Query = query;
    }
}
```

Also you can remove
```csharp
.AddSingleton<Query>()
.AddSingleton<OrganisationType>()
.AddSingleton<OrganisationGraphType>()
```
since  `.AddGraphTypes(typeof(OrgSchema));` do taht for you.

**Comment by phillsteele** [comment]
Thanks for that, worked a treat :-)

Might be worth getting the docs updated though.

This link suggests you still need to register all the types with ASP.Net Core: https://graphql-dotnet.github.io/docs/getting-started/dependency-injection

**Comment by sungam3r** [comment]
`AddGraphTypes` is an extension method from the [server](https://github.com/graphql-dotnet/server/blob/master/src/Core/GraphQLBuilderExtensions.cs#L80) project.
