### ISSUE TITLE
Error trying to resolve a query field

### ISSUE THREAD

**Issue by lcola** [graphql-dotnet/graphql-dotnet#239]
Hi,
I started using graphiQL + graphql-dotnet with mysql database and EF.
I add a new query object "ruoli" in to the container, but when i try to execute a query i receive an "Error trying to resolve ruoli".

I don't understand what I'm doing wrong..
Any suggestions?

This is my Ruoli type class implementation:

    public class RuoliType : ObjectGraphType<ibb041_tbruoli>
    {
        public RuoliType(IBeachDBModel data)
        {
            Name = "ruoli";
            Description = "Definizione dei ruoli utente";
            Field(d => d.ibb041_id).Description("id ruolo");
            Field(d => d.ibb041_descrizione).Description("Descrizione ruolo");
            Field(d => d.ibb041_tipo).Description("Tipo ruolo");
        }
    }

My Query class:

    public class IBeachDBQuery : ObjectGraphType
    {
        public IBeachDBQuery()
        {
            Name = "Query";
            Field<RuoliType>("ruoli", "ricerca ruoli", arguments: new QueryArguments(new QueryArgument<NonNullGraphType<IntGraphType>> { Name = "id", Description = "id ruolo" }),
                resolve: context => db.ibb041_tbruoli.Find(context.GetArgument<int>("id")));

        }
    }

My schema class:

    public class IBeachDBSchema : GraphQL.Types.Schema
    {
        public IBeachDBSchema(Func<Type, GraphType> resolveType)
            : base(resolveType)
        {
            Query = (ObjectGraphType)resolveType(typeof(IBeachDBQuery));
        }
    }

The boostrapper class:

        private ISimpleContainer BuildContainer()
        {
            var container = new SimpleContainer();
            container.Singleton<IDocumentExecuter>(new DocumentExecuter());
            container.Singleton<IDocumentWriter>(new DocumentWriter(true));

            container.Singleton(new IBeachDB.DataModel.IBeachDBModel()); // EF : DBContext
            container.Register<IBeachDB.Schema.IBeachDBQuery>();
            container.Register<RuoliType>();
            container.Singleton(new IBeachDB.Schema.IBeachDBSchema(type => (GraphType)container.Get(type)));

            return container;
        }

QueryType preview: 
![query1](https://cloud.githubusercontent.com/assets/20487192/21075031/7ca0bc30-bf08-11e6-9ab7-597d1c3afb8a.png)

Error querying:
![query2](https://cloud.githubusercontent.com/assets/20487192/21075033/82a14e7e-bf08-11e6-9826-0c3c5fb1148d.png)

**Comment by JarnoNijboer** [comment]
You haven't specified an id in your query:

Quick example of your query with an id specified for `ruoli`
```graphql
query {
    ruoli (id: 10) {
        tipi
    }
}
```

**Comment by joemcbride** [comment]
@JarnoNijboer suggestion appears to be correct.  I think you need to pass an `id` in your query.  That should fail validation though since the code you posted shows a required argument.

You can see a stack trace and the inner error if you run the application in Debug mode and check the Errors on the `ExecutionResult`.  When the errors are serialized to JSON it currently excludes the inner exception and the stack trace.

**Comment by lcola** [comment]
I tried to pass an id in 2 different way (img1.png and img2.png), but the result are the same.
![img1](https://cloud.githubusercontent.com/assets/20487192/21081718/c0f9effe-bfcc-11e6-8377-9b4488dd38de.png)
![img2](https://cloud.githubusercontent.com/assets/20487192/21081721/d24d5502-bfcc-11e6-9564-dc1099e4b24e.png)

Following Local variables (_the stack trace is null_)

![local_var1](https://cloud.githubusercontent.com/assets/20487192/21081722/d7d6db7e-bfcc-11e6-99dd-f102d06ec35f.png)
![local_var2](https://cloud.githubusercontent.com/assets/20487192/21081723/d9ac42fe-bfcc-11e6-894d-059a0fd7af4e.png)


I also tried to make a query without parameters; response is the same 
**"message": "Error trying to resolve ruoli."**

        public IBeachDBQuery()
        {
            Name = "Query";
            Field<ListGraphType<RuoliType>>()
                .Name("ruoli")
                .Resolve(ctx =>
                {
                    using (var db = new IBeachDBModel())      // public partial class IBeachDBModel : DbContext
                        return db.ibb041_tbruoli.ToList();
                });
        }

Below my PostAsync method (_is the same using in the graphiQL original sample_):

      [HttpPost]
        public async Task<HttpResponseMessage> PostAsync(HttpRequestMessage request, GraphQLQuery query)
        {
            var inputs = query.Variables.ToInputs();
            var queryToExecute = query.Query;

            if (!string.IsNullOrWhiteSpace(query.NamedQuery))
            {
                queryToExecute = _namedQueries[query.NamedQuery];
            }

            var result = await _executer.ExecuteAsync(_ =>
            {
                _.Schema = _schema;
                _.Query = queryToExecute;
                _.OperationName = query.OperationName;
                _.Inputs = inputs;

                _.ComplexityConfiguration = new ComplexityConfiguration { MaxDepth = 15 };
                _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();

            }).ConfigureAwait(false);

            var httpResult = result.Errors?.Count > 0
                ? HttpStatusCode.BadRequest
                : HttpStatusCode.OK;

            var json = _writer.Write(result);

            var response = request.CreateResponse(httpResult);
            response.Content = new StringContent(json, Encoding.UTF8, "application/json");

            return response;
        } 

Any suggestions?
Regards.
Lorenzo

**Comment by tlil87** [comment]
@lcola you haven't provided any arguments to your field definition:

```diff
         Field<ListGraphType<RuoliType>>()
             .Name("ruoli")
+            .Argument<NonNullGraphType<IntGraphType>>("id", "<Description goes here>")
             .Resolve(ctx =>
```

**Comment by lcola** [comment]
@tlil87 nothing has changed; the same error message.

        public IBeachDBQuery()
        {
            Name = "Query";
            Field<ListGraphType<RuoliType>>()
                .Name("ruoli")
                .Argument<NonNullGraphType<IntGraphType>>("id", "codice ruolo")
                .Resolve(ctx =>
                {
                    using (var db = new IBeachDBModel())
                        return db.ibb041_tbruoli.Find(ctx.GetArgument<int>("id"))**.As<ListGraphType>()**; (with and without)
                });
        }

**Comment by tlil87** [comment]
What does the inner exception on that error say?

**Comment by lcola** [comment]
@tlil87: The first error was generated by my **big mistake**:: I create a database library but i didn't copy the app.config settings to WebAPi Web.config settings (a beginner's mistake, grrr).

Now i completly remove all the other error and this is the result:
query: {
ruoli (id:1) {
  ibb041_id
  ibb041_tipo
  ibb041_descrizione
}
}
result:
{
  "data": {
    "ruoli": {
      "ibb041_id": 1,
      "ibb041_tipo": "adm",
      "ibb041_descrizione": "Administrator"
    }
  }
}

Thank you at all for your attention!!
Regards.
Lorenzo

**Comment by joemcbride** [comment]
:+1: I've had the same frustration of needing to dig deep to figure out what the "real" error was.  @tlil87 I'm thinking perhaps a "debug" mode that would send full error/stack trace?

**Comment by tlil87** [comment]
@lcola Glad you found the problem. 👍 

@joemcbride Yep, in the Conventions library I'm actually untwining the exceptions to elevate the details of the inner exception (in most cases). We experienced similar difficulties in the past when trying to troubleshoot based on logs and stacktraces in prod without the full dump of inner exceptions. A similar approach might be worth considering in the engine?

**Comment by fbrier** [comment]
Did you ever add in that "debug" mode? I am having virtually the identical problem. When I am debugging my returned database object does contain data. Everything else looks the same. My error says:
```
{
  "data": {
    "resource": null
  },
  "errors": [
    {
      "message": "Error trying to resolve resource.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "resource"
      ]
    }
  ]
}
```

**Comment by tlil** [comment]
@fbrier are you using Conventions? Or vanilla graphql-dotnet?

The latest version of Conventions _should_ untwine the exception and show a more helpful message, but not necessarily the full stack trace. I haven't added the _debug_ mode yet... But that's something I could do for the next update.

**Comment by joemcbride** [comment]
@fbrier there is now an ExposeExceptions property on the ExecutionOptions, version 17.3+.

**Comment by fbrier** [comment]
I am using vanilla graphql-dotnet, ver. 2.0.0-alpha-820. I also added in [GraphiQL](https://github.com/JosephWoodward/graphiql-dotnet). I did see your Conventions project. Since my code seemed close to working, I did not want to add another moving part, but it does seem like it would reduce the amount of boiler plate code. If I can get this working, I will definitely look at adding it.

So the schema is displayed and navigable in GraphiQL. This is my first project with GraphQL in any language. Looking at the unit tests, it is not clear to me how to set the ExecutionOptions. The examples, based on the GraphQLMiddleware (GraphQLRequest, and GraphQLUserContext) classes being in a project under the GraphQL-DotNet solution, but not in NuGet, the intention seemed that developers would copy and customize those classes in their own project. If so, is this where the ExecutionOptions are set? How?

It seems like the DocumentWriter instance injected into GraphQLMiddleware class would need to be aware of the mapping to a GraphQL class, unless it is merely converting whatever POCO with public properties into JSON output, and graph types you create for GraphQL inputs do not matter. Does it matter? It seems like this is where my Resource return object is failing to be converted. The argument is being parsed from the context. The data is read from the database, and returned in the resolve lambda. I too have tried returning a single Resource instance, as well as an IEnumerable<Resource> (wrapping with a ListGraphType). The only gotchya I can see is that the ResourceType is a ResourceInterface which derives from InterfaceGraphType<> with the Resource as the type. Would that cause a problem? I plan on having many classes that extend the ResourceInterface, I was just trying to get a Query and a Mutation working first.

As an aside, your test support classes would be nice to have in NuGet, to create tests for people using GraphQL-DotNet.

**Comment by FrederickBrier** [comment]
The ExposeExceptions was embarrassingly easy <sigh>.

           var result = await _executer.ExecuteAsync(_ =>
            {
                _.Schema = schema;
                _.ExposeExceptions = true;
                _.Query = request.Query;
                _.OperationName = request.OperationName;
                _.Inputs = request.Variables.ToInputs();
                _.UserContext = _settings.BuildUserContext?.Invoke(context);
            });

**Comment by FrederickBrier** [comment]
The exception confirmed that you cannot return an InterfaceGraphType, which makes sense.

`"message": "GraphQL.ExecutionError: Error trying to resolve resource. ---> GraphQL.ExecutionError: Abstract type resource must resolve to an Object type at runtime for field Query.resource with value ARM.Server.Data.Entities.Resource, received 'null'.\r\n   at GraphQL.DocumentExecuter.
`
I created an ObjectGraphType to wrap the same Resource object and it worked. Now onto Mutations... Thank you!!

**Comment by fbrier** [comment]
And mutations work for me! This is very exciting. Thank you SO much for
writing this library.

**Comment by usman-khan-01** [comment]
If your working with local DB then see if there is a migration which you haven't updated. If so then try updating the db by using the command update-database in package manger console.
