### ISSUE TITLE
parseValue_from_system_text_json_ok sometimes fails on negative numbers 

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2395]
See https://github.com/graphql-dotnet/graphql-dotnet/runs/2105809570?check_suite_focus=true#step:10:464 
>   System.Text.Json.JsonException : '0xE2' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 9.
---- System.Text.Json.JsonReaderException : '0xE2' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 9.
  Stack Trace:
     at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)

or https://github.com/graphql-dotnet/graphql-dotnet/runs/2105809570?check_suite_focus=true#step:10:487
>  Newtonsoft.Json.JsonReaderException : Unexpected character encountered while parsing value: −. Path '', line 0, position 0.
  Stack Trace:
     at Newtonsoft.Json.JsonTextReader.ParseValue()

🤔

**Comment by Shane32** [comment]
it's due to the culture being changed by another test.  i need to format the input number as an invariant culture.

**Comment by Shane32** [comment]
not a bug in the library, just a bug in the test

**Comment by sungam3r** [comment]
> it's due to the culture being changed by another test.

But how ?

**Comment by Shane32** [comment]
There’s culture tests in the astprinter tests. It’s a global setting, and just like our other other issues with global settings, global options seem to affect other tests. Maybe there’s some way to force tests to run single threaded.

**Comment by sungam3r** [comment]
They are different. Our options are just static. Culture-related options are thread-binded. Parallel tests cannot be performed in the same thread so I don't understand how it happened.

**Comment by Shane32** [comment]
Well it’s pretty obvious that it’s what happened, regardless of how.

**Comment by sungam3r** [comment]
I have a suspicion that the error may be for another reason.

**Comment by sungam3r** [comment]
> Maybe there’s some way to force tests to run single threaded.

This is not a way out. Then we would not find different errors. Remember static directives.

**Comment by Shane32** [comment]
> They are different. Our options are just static. Culture-related options are thread-binded. Parallel tests cannot be performed in the same thread so I don't understand how it happened.

```cs
        public static void UseCulture(CultureInfo culture, Action scope)
        {
            var before = CultureInfo.CurrentCulture;
            var beforeUi = CultureInfo.CurrentUICulture;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;

            try
            {
                scope();
            }
            finally
            {
                CultureInfo.DefaultThreadCurrentCulture = before;
                CultureInfo.DefaultThreadCurrentUICulture = beforeUi;
            }
        }
```

The method changes: (from MSDN)

> Gets or sets the default culture for threads in the current application domain.

and

> Gets or sets the default UI culture for threads in the current application domain.

It does not merely change the current thread's culture.  Perhaps the method should be rewritten.

**Comment by sungam3r** [comment]
👍

**Comment by sungam3r** [comment]
After reading the documentation, I got the impression that the behavior of these properties could be different on Windows and Linux.
