### ISSUE TITLE
Breaks with GraphQL Dotnet Parser v7

### ISSUE THREAD

**Issue by Cito** [graphql-dotnet/graphql-dotnet#2399]
After updating GraphQL Dotnet Parser from v6 to v7 and running a query I'm getting the following error message:

```
      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'Void GraphQLParser.Lexer..ctor()'.
         at GraphQL.Execution.GraphQLDocumentBuilder..ctor()
         at GraphQL.DocumentExecuter..ctor() in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 33
```

The reason seems to be that Lexer has become a static class in GraphQL Dotnet Parser v7, but the GraphQLDocumentBuilder is trying to instantiate it [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/e41c76de4d4f4af18a517c0c21ce12d331ddc7b1/src/GraphQL/Execution/GraphQLDocumentBuilder.cs#L23).

**Comment by Shane32** [comment]
Parser v7 is not compatible with GraphQL.NET 3.x.  It is used with GraphQL.NET 4.x, which will be released shortly.

**Comment by Cito** [comment]
Great to hear that there will be a new version 4.x soon!

Maybe the GraphQL-Parser version should then be specified as `[5.3.3,6)` or `[5.3.3,7)` (in interval notation) or `5.3.*` (as floating version) in the PackageReference for the current version?
