### ISSUE TITLE
Publish GraphiQL VS2015 project to IIS

### ISSUE THREAD

**Issue by lcola** [graphql-dotnet/graphql-dotnet#240]
Hi @joemcbride.
Only a very quick question.
I published my WebAPI graphiQL in my IIS.
When calling the URL, I get the following error:
![img1](https://cloud.githubusercontent.com/assets/20487192/21113572/6af5612c-c0aa-11e6-9d74-8ab378410ba3.png)

If i execute the same WebAPI code in Visual Studio 2015, it works correctly.
![img2](https://cloud.githubusercontent.com/assets/20487192/21113711/e8c629c4-c0aa-11e6-8e17-5007810b6fe5.png)
Any suggestions?

Lorenzo

**Comment by joemcbride** [comment]
I would look at the http request response.  I would guess the server is returning a non-json result.

**Comment by lcola** [comment]
thank you @joemcbride. Could you pls answer on this thread for any news?
Lorenzo

**Comment by joemcbride** [comment]
This is not an issue with this project but an issue with your setup.  I can't be of much help, especially without you posting more information.

**Comment by lcola** [comment]
what kind of information do you need?
I created my own project copying the GraphiQL sample (same controller, bootstrapper, query and schema code).
If i try to publish the GraphiQL sample, i get the same result (as follows):

Code executed by visual studio:
![graphiql_ok](https://cloud.githubusercontent.com/assets/20487192/21240373/569d591a-c30b-11e6-8847-bc7b4173418d.png)

Code executed by IIS:
![graphiql_ko](https://cloud.githubusercontent.com/assets/20487192/21240393/6432f22e-c30b-11e6-94ee-5be42228d6f7.png)

**Comment by joemcbride** [comment]
Look at the http response in the browser developer tools.  You are most likely getting some error or html page as a response instead of JSON.

![screen shot 2016-12-15 at 12 22 02 pm](https://cloud.githubusercontent.com/assets/255007/21240661/1c99b28a-c2c1-11e6-96df-de5cc1c61e8b.png)

**Comment by lcola** [comment]
OK. resolution completed. tks @joemcbride

**Comment by harish-edgenuity** [comment]
Hi All
After Publishing my graphql project 
i am getting below  error
Kindly help me on this
![image](https://user-images.githubusercontent.com/84519142/120223747-b3411280-c25f-11eb-8550-5384a730e36f.png)

**Comment by hareeshkumarkr** [comment]
Hi All,
I have  created a small application using Graphql with .net core web API using browser interface Graphiql.It is working fine in localhost but  after publishing the project on IIS server I am getting the following error.

![image](https://user-images.githubusercontent.com/85127450/120227703-4a5d9880-c267-11eb-8728-87d77381906e.png)


kindly look into it
