### ISSUE TITLE
Create a UnionGraphType at runtime 

### ISSUE THREAD

**Issue by diaconesq** [graphql-dotnet/graphql-dotnet#241]
Related to #237

I am building various `ObjectGraphType` instances at runtime. I want to build an `UnionGraphType` that represents a set of a few of those `ObjectGraphType` instances.

I assumed I should do this: 

    IObjectGraphType objectType1 = ...; //build it
    IObjectGraphType objectType2 = ...; //build it

    unionType.AddPossibleType(objectType1);
    unionType.AddPossibleType(objectType2);

...but that fails when building a schema containing this type on this bit in the GraphQL.NET library (in `GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context)`: 

    if (!union.Types.Any())
    {
        throw new ExecutionError("Must provide types for Union {0}.".ToFormat(union));
    }

`UnionGraphType` has property `Type[] Types` and `IObjectGraphType[] PossibleTypes`. 
What is the difference? 

I can't add anything to the `Types` property, because my `IGraphType` instances are built on the fly - there is no corresponding .NET type for them. 

I could find an API for working with other composite types (e.g. ListGraphType.ctor(IGraphType)) but not for this one. 

Any suggestions?

**Comment by joemcbride** [comment]
This was missed with the initial "instance" behavior.  Just needs to be fixed!

**Comment by diaconesq** [comment]
Thank you for adding this! 

I gave it a try -- but hit issue #257.
