### ISSUE TITLE
Customizing the Auth Failure output

### ISSUE THREAD

**Issue by mostl33** [graphql-dotnet/graphql-dotnet#2413]
## Summary

Hey!

First: Thanks for this great library. 

I've a one little question. Is it possible to customize the Error message of an Authorization error? Imho the message leaks to much information (e.g. name of claim, the MS URL)

You are not authorized to run this query.\nRequired claim 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' with any value of '<NAMEOFCLAIM>' is not present.

I haven't found anything in the docs.

Thanks in advance.

Best regards,

ml

**Comment by sungam3r** [comment]
> I haven't found anything in the docs.

This repo has nothing to do with authorization. Which project do you use - https://github.com/graphql-dotnet/authorization or https://github.com/graphql-dotnet/server ?

And yes, it is possible after https://github.com/graphql-dotnet/server/pull/480 .

**Comment by mostl33** [comment]
Thanks (and sorry for posting it here ...)

I'm using GraphQL.Server.Transports.AspNetCore.
