### ISSUE TITLE
Can't resolve generic types that use GraphQL clr reference types

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2415]
My schema builder constructed the following graph type:
- `ConnectionType<GraphQLClrOutputTypeReference<Widget>>`

(Note: `ConnectionType<>` is provided with GraphQL.)

However, during schema initialization, the "wrapped" reference type was not resolved, since it was not recognized as a GraphQL reference type.

This breaks my use case.  I will provide a fix within the library as a PR in which it will examining each generic graph type to determine if it needs to be reconstructed.  I will also (eventually) provide a PR to `SchemaTypes` that has enough protected members to allow overriding portions of it as necessary to fix unforeseen problems like this in the future.

**Comment by sungam3r** [comment]
I need 1 hour to review.

**Comment by Shane32** [comment]
Looks like the linked issues are auto-closing again.

**Comment by sungam3r** [comment]
Yes, because PR is targeted against default branch.
