### ISSUE TITLE
Dynamic GraphQL Types/Schema generation and multiple typed fields

### ISSUE THREAD

**Issue by sooraj-karikkan** [graphql-dotnet/graphql-dotnet#2418]
I need to create GraphQL API based on some dynamic object types. 
As an example, let's say, I have a dictionary of an object type name and a list of its properties. And based on this dictionary I need to generate GraphQL API.
```csharp
Dictionary<string, List<FieldInformation>> ObjectTypes = new Dictionary<string, List<FieldInformation>>();
ObjectTypes.Add("Product", new List<FieldInformation>
{
	new FieldInformation { FieldName = "Name", FieldType = "string" },
	new FieldInformation { FieldName = "Price", FieldType = "float" }
});
```
where `FieldInformation` is defined as below
```csharp
public class FieldInformation
{
	public string FieldName { get; set; }
	public string FieldType { get; set; }
}
```
And say we have a number of Object types such as Customer, Seller, Order, ProductCategory, etc added to the dictionary with appropriate fields.
I was able to generate GraphQL Schema and the APIs using Reflection to generate C# classes, their corresponding GraphTypes and Queries as per the [GraphType first approach](https://graphql-dotnet.github.io/docs/getting-started/introduction/#graphtype-first-approach).
So there are no concrete models available and every models/types are created in memory and the data resolving is done similarly using `Activator.CreateInstance()` and setting individual properties/fields for a specific type.

My current requirement is that, a field need to support two data types, how can it be accomplished in GraphQL?
I know that GraphQL is strongly typed, but **is it possible to support multiple object types for a single filed**? 
For example, a field, ConcernedPerson, which can be of type Seller or Customer?

I tried `dynamic` and `object` types, both resulted in error.
I did also try to achieve this using [Interfaces in GraphQL](https://graphql-dotnet.github.io/docs/getting-started/interfaces) and was able to generate a Schema with the interface type that can hold both these types. But as seen in the docs, a GraphQL interface is actually a Class, so at the data resolving stage, when I assign a Customer(Type)/Seller(Type) to a field of DummyInterface type, c# compiler is throwing errors as there is no c# way of interface implementation (ie no relation between DummyInterface and CustomerType/SellerType)
Is there any more info regarding Interfaces, specifically at the data resolving stage?
Or whether switching to [Schema first approach](https://graphql-dotnet.github.io/docs/getting-started/introduction#schema-first-approach) be able to achieve the requirement of multiple typed fields or is it better as a whole as everything is dynamic in my case?

Please feel free to give suggestions/ideas/information regarding this dynamic GraphQL Type and Schema generation and also regarding multiple typed fields in GraphQL.
Thanks in advance.

**Comment by Shane32** [comment]
I have not used GraphQL interfaces much, but I think there's a method you can override for an interface graph class that will examine an object and determine which graph is appropriate to be returned for the object.  You could probably make a "generic" interface class with a settable delegate field so it could be generated dynamically.  Not sure if this helps, but just thinking out loud.

**Comment by sungam3r** [comment]
https://graphql-dotnet.github.io/docs/getting-started/interfaces#istypeof
https://graphql-dotnet.github.io/docs/getting-started/interfaces#resolvetype

**Comment by sungam3r** [comment]
> is it possible to support multiple object types for a single filed?

Yes. Either via interface or union.

**Comment by psinghms** [comment]
@sooraj-karikkan Can you share the sample code where you are generating the schema and the class at runtime and further creating the instance. I am also trying to do the similar thing where the schema and the classes will be generated dynamically.

**Comment by sungam3r** [comment]
Closed due inactivity.
