### ISSUE TITLE
GetGraphTypeFromType does not work for enums

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2420]
Assuming an enum has been mapped with the type mapper, such as in the below sample, the type mapping is ignored.

```cs
RegisterTypeMapping<MyEnum, MyEnumGraph>();
```

This is a breaking change from 3.x.

This is due to `GetGraphTypeFromType` specifically skipping enumeration types and instead constructing a generic type `EnumerationGraphType<T>`.

I will change the code so that, just like any other scalar, the enumeration is only changed to the above generic type within the schema initialization, if no type mapping can be found.

**Comment by sungam3r** [comment]
👍

**Comment by Shane32** [comment]
Also, there's a bug where for list types it examines if `clrElementType.IsNullable()` --- however, `IsNullable()` only returns true for `Nullable<T>` and not for classes.  So it would make lists of objects non-nullable, which seems incorrect to me.

**Comment by sungam3r** [comment]
Well, I think it's actually by design.

**Comment by Shane32** [comment]
So it "defaults" to non-nullable?  I can leave it that way if you think that's how it should be.

**Comment by Shane32** [comment]
Well then why would strings "default" to nullable?

**Comment by Shane32** [comment]
```cs
        public static bool IsNullable(this Type type)
            => type == typeof(string) || type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>);
```

Because it's a scalar type perhaps?

**Comment by Shane32** [comment]
Seems a little inconsistent.

**Comment by sungam3r** [comment]
Justs a desing flaw 😄 .

`isNullable` by default is `false` for parent type (container). Code tries to keep as more types non nullable as it can. By I would to remove this method from (make Obsolete and then remove).

Now there is no way to specify a nullability property for nested types. But see #1229. It will be a more natural solution.

**Comment by Shane32** [comment]
Mark IsNullable obsolete?  Good idea.

What to do now?

I would suggest that it default to nullable if the .NET type allows it, as generally it seems that nullable types are "preferred" by GraphQL schemas.  (I could be wrong; just my impression.)

Or maybe better to just leave classes (except string) to default as non-nullable as it had been coded before?  Perhaps that is for maximum compatibility with 3.x anyway.  What do you think?

NRT is of course ideal....

**Comment by sungam3r** [comment]
> Or maybe better to just leave classes (except string) to default as non-nullable as it had been coded before? Perhaps that is for maximum compatibility with 3.x anyway. What do you think?

Yes, let's keep it as is for v4.

**Comment by Shane32** [comment]
`BuiltInScalarMappings` is missing a mapping for `Uri`.  Should it have one?

**Comment by Shane32** [comment]
```cs
        internal static readonly Dictionary<Type, Type> BuiltInScalarMappings = new Dictionary<Type, Type>
        {
            [typeof(int)] = typeof(IntGraphType),
            [typeof(long)] = typeof(LongGraphType),
            [typeof(BigInteger)] = typeof(BigIntGraphType),
            [typeof(double)] = typeof(FloatGraphType),
            [typeof(float)] = typeof(FloatGraphType),
            [typeof(decimal)] = typeof(DecimalGraphType),
            [typeof(string)] = typeof(StringGraphType),
            [typeof(bool)] = typeof(BooleanGraphType),
            [typeof(DateTime)] = typeof(DateTimeGraphType),
            [typeof(DateTimeOffset)] = typeof(DateTimeOffsetGraphType),
            [typeof(TimeSpan)] = typeof(TimeSpanSecondsGraphType),
            [typeof(Guid)] = typeof(IdGraphType),
            [typeof(short)] = typeof(ShortGraphType),
            [typeof(ushort)] = typeof(UShortGraphType),
            [typeof(ulong)] = typeof(ULongGraphType),
            [typeof(uint)] = typeof(UIntGraphType),
            [typeof(byte)] = typeof(ByteGraphType),
            [typeof(sbyte)] = typeof(SByteGraphType),
        };
```

**Comment by sungam3r** [comment]
> Should it have one?

Yes.
