### ISSUE TITLE
NU1102 error on windows-latest

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2422]
https://github.com/graphql-dotnet/graphql-dotnet/pull/2421/checks?check_run_id=2150854275 

> D:\a\graphql-dotnet\graphql-dotnet\src\GraphQL.Dummy\GraphQL.Dummy.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.3) [D:\a\graphql-dotnet\graphql-dotnet\src\GraphQL.sln]
D:\a\graphql-dotnet\graphql-dotnet\src\GraphQL.Dummy\GraphQL.Dummy.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [D:\a\graphql-dotnet\graphql-dotnet\src\GraphQL.sln]
D:\a\graphql-dotnet\graphql-dotnet\src\GraphQL.Dummy\GraphQL.Dummy.csproj : error NU1102:   - Found 0 version(s) in Source [D:\a\graphql-dotnet\graphql-dotnet\src\GraphQL.sln]

**Comment by sungam3r** [comment]
`Re-run all jobs` button in GitHub CI UI solves this problem.

**Comment by Shane32** [comment]
I was experiencing the same issue and fix.  I don't think there's a problem with our scripts.

**Comment by sungam3r** [comment]
Windows:
![изображение](https://user-images.githubusercontent.com/21261007/111885606-d76bb200-89d9-11eb-9a4f-f8d37641705f.png)

Ubuntu:
![изображение](https://user-images.githubusercontent.com/21261007/111885620-ec484580-89d9-11eb-9931-0ac054942055.png)

I think we may try to disable `Microsoft Visual Studio Offline Packages` source.

**Comment by sungam3r** [comment]
Waiting 1-2 months after #2426 to see if it happens again.

**Comment by Shane32** [comment]
If anything, it’s a CI issue. Unlikely it’s anything with our CI scripts. Certainly not a bug.

**Comment by sungam3r** [comment]
Also found here https://github.com/graphql-dotnet/parser/pull/126/checks?check_run_id=2282874117

**Comment by sungam3r** [comment]
Closing.
