### ISSUE TITLE
ToConstantCase has different semantics

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2423]
In version 3.x, "Option1" was encoded as "OPTION_1".  With 4.x, it is now "OPTION1".  This should probably be fixed asap also.  This method is used by all `EnumerationGraphType<T>` instances.

**Comment by Shane32** [comment]
Sample test that can be used in 3.x or 4.x to demonstrate issue:  (passes in 3.x)

```cs
        [Fact]
        public void to_constant_case_tests()
        {
            var e = new EnumerationGraphType<MyEnum>();
            e.Values.Count().ShouldBe(2);
            e.Values.FindByValue(MyEnum.TestHello).Name.ShouldBe("TEST_HELLO");
            e.Values.FindByValue(MyEnum.Hello1).Name.ShouldBe("HELLO_1");
        }

        private enum MyEnum
        {
            TestHello,
            Hello1
        }
```

**Comment by sungam3r** [comment]
Do you fix it?

**Comment by Shane32** [comment]
I'm working on it.  Unless you don't think we should.

**Comment by sungam3r** [comment]
I wanted to publish server v5 but then I saw this bug.

**Comment by Shane32** [comment]
This is the last thing blocking my implementation..... I hope.  Most of my tests pass now, and I think I know what's needed to fix the rest.  I probably won't be able to test 4.0 in my production environment until Monday.  So I suggest we release 4.0.2 and 5.0 after merging this bug fix.

**Comment by sungam3r** [comment]
OK

**Comment by sungam3r** [comment]
I also need to update my own libraries stack first.

**Comment by Shane32** [comment]
We can also wait on server 5.0 until we have both had time to run it .... whatever you think.  But probably good to publish 4.0.2 tonight as people are already downloading 4.0.0 and 4.0.1.

**Comment by sungam3r** [comment]
I am not afraid to publish v5 now. The appearance of bugfixes after the main version is the usual thing. All the same, we need to do it, so as not to block other people.

**Comment by Shane32** [comment]
@sungam3r Do you want to release 4.0.2 and 5.0 now then?  Or I can release 4.0.2 if you like.

**Comment by sungam3r** [comment]
Release 4.0.2
