### ISSUE TITLE
LGTM doesn't work

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2428]
LGTM doesn't work even in the master branch.  Let's disable it.  All checks always show failed.

![image](https://user-images.githubusercontent.com/6377684/111893779-79d86500-89db-11eb-8bed-66f9b3b640fc.png)

**Comment by sungam3r** [comment]
I know about it and want to fix.

**Comment by Shane32** [comment]
Let’s disable it until then. How do we do that?

**Comment by sungam3r** [comment]
Something like `if: !always()` ?

**Comment by Shane32** [comment]
Oh it’s a workflow? I must have looked right at it and not seen it.

**Comment by Shane32** [comment]
I can't find it.  Where is it?  Are you sure it's not configured as an integration?

https://github.com/graphql-dotnet/graphql-dotnet/settings/installations

**Comment by sungam3r** [comment]
codeql-analysis.yml 
See this issue to get details https://github.com/github/codeql/issues/4893. I have not yet configured the integration properly.

**Comment by sungam3r** [comment]
CodeQL workflow works well. The problem is LGTM app integration (it's the same as CodeQL but just another API - dedicated app). I can' remove or disable it, I have no rights. @joemcbride Please remove LGTM app integration from graphql org/all repos.

**Comment by joemcbride** [comment]
I got LGTM removed.

**Comment by Shane32** [comment]
🥇

**Comment by joemcbride** [comment]
> 🥇

Only took a few months!  😅

**Comment by sungam3r** [comment]
:tada: :tada: :tada: :tada: :tada:
