### ISSUE TITLE
Allow labeling and commenting to PRs from forks 

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2439]
Applies to labeler and possible to codecov.
See https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ and especially https://securitylab.github.com/research/github-actions-preventing-pwn-requests

**Comment by sungam3r** [comment]
Hall of shame here: https://github.com/actions/labeler/issues/12

**Comment by sungam3r** [comment]
Fix here (not sure) https://github.com/actions/labeler/issues/12#issuecomment-670967607

**Comment by sungam3r** [comment]
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by sungam3r** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by Shane32** [comment]
I propose to remove labeler

**Comment by sungam3r** [comment]
Maybe, maybe, I'm almost ready to do so if it doesn't work after changing workflow.

**Comment by sungam3r** [comment]
By the way, GitHub allows to disable workflow to be able to enable it further if needed.

**Comment by sungam3r** [comment]
Waiting for the first PR from fork to see if fix from #2906 works.

**Comment by sungam3r** [comment]
@Shane32 #2906 works! See #3083. Thanks @Ekkeir for this test.
