### ISSUE TITLE
Signed Version of DLL

### ISSUE THREAD

**Issue by cnickeson** [graphql-dotnet/graphql-dotnet#244]
I am running into issues when grabbing the code down from Nuget. I am needing a signed version to run in my application. I can try to sign the GraphQL library myself but then I run into problems with the dependency on GraphQL-Parser not being signed. 

I have a workaround currently which includes bringing down the code and signing both the GraphQL-Parser DLL and then the GraphQL DLL and referencing that but would like to be able to have Nuget manage this.

**Comment by joemcbride** [comment]
I currently do not have plans to provide signed assemblies. Can you try the same solution as https://github.com/graphql-dotnet/graphql-dotnet/issues/234 ?

**Comment by cnickeson** [comment]
The strongnamer package was able to resolve my issue. Thanks for the help!
