### ISSUE TITLE
DataTime cannot customize the format output

### ISSUE THREAD

**Issue by tooclian** [graphql-dotnet/graphql-dotnet#2443]
Is it possible to customize the converter format output through the serializer?

**Comment by sungam3r** [comment]
See https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Scalars/DateTimeGraphType.cs . Serialize method returns string so the answer is no. However you can write your custom scalar to return DateTime in any format you want. See documentation in https://graphql-dotnet.github.io/docs/getting-started/custom-scalars

**Comment by Shane32** [comment]
Note that the documentation describes how to override the default date/time graph types with your own implementations so no adjustment is needed to the rest of your graphs.

**Comment by tooclian** [comment]
Thank you! Resolved by custom scalar.
