### ISSUE TITLE
Cannot resolve symbol 'SelfActivatingServiceProvider'

### ISSUE THREAD

**Issue by apai05** [graphql-dotnet/graphql-dotnet#2447]
I have included the package GraphQL.MicrosoftDI - 4.0.2 and tried to follow the example in 

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<ISchema, MySchema>(services => new MySchema(new SelfActivatingServiceProvider(services)));
}
```
But somehow the .net compiler issues following error:
` [CS0246] The type or namespace name 'SelfActivatingServiceProvider' could not be found (are you missing a using directive or an assembly reference?)`

Is there any additional lib I am missing here?

**Comment by Shane32** [comment]
`SelfActivatingServiceProvider` was just added and is not in 4.0.2.  It will be released with either 4.0.3 or 4.1.0.  Not sure exactly when that will be released.  We hadn't planned to release 4.1.0 for a month, but it may be worthwhile to release sooner.   #2427 should also be in the next release.  @sungam3r any comments?

@sungam3r -- a consequence of merging directly to `master` is that documentation for new features is updated before release.  We also cannot release 4.0.3 without including changes intended for 4.1.0.  We could consider another branch, but it's probably fine as-is.

**Comment by Shane32** [comment]
@apai05 The code for the class is extremely simple.  For now, you can just copy the class into your project, as it does not affect any other part of the framework.

See: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.MicrosoftDI/SelfActivatingServiceProvider.cs

**Comment by apai05** [comment]
Awesome, thank you so much.

**Comment by sungam3r** [comment]
> any comments?

#2427 is under review and will be a part of v4.1

> a consequence of merging directly to master is that documentation for new features is updated before release

I'm fine to keep it as is.

@apai05 I'll close this issue. You may subscribe to be notified when we publish a new release.
![изображение](https://user-images.githubusercontent.com/21261007/112382338-c8983e80-8cfc-11eb-80b8-e0a4958b81d5.png)
