### ISSUE TITLE
Double precision floats not properly parsed in some conditions in 3.2

### ISSUE THREAD

**Issue by jeancallisti** [graphql-dotnet/graphql-dotnet#2460]
Try this with GraphQL **3.0.0**.1268 : 

```
FieldAsync<BooleanGraphType>(
     "myMutation",
    arguments: new QueryArguments(
        new QueryArgument<NonNullGraphType<ListGraphType<NonNullGraphType<ComplexInputType>>>> { Name = "complexInput" }
    ),
    resolve: async context =>
    {
        var input = context.GetArgument<List<ComplexInput>>("complexInput");
        ...
        return true;
    }
}

```
The ComplexInputType is as follows : 

```
    public class ComplexInput
    {
        public double DoublePrecisionField1 { get; set; }
        public double DoublePrecisionField2 { get; set; }
    }

    public class ComplexInputType : InputObjectGraphType<ComplexInput>
    {
        public ComplexInputType()
        {
            Field(type: typeof(NonNullGraphType<FloatGraphType>), name: "doublePrecisionField1");
            Field(type: typeof(NonNullGraphType<FloatGraphType>), name: "doublePrecisionField2");
        }
    }
```

Call the mutation however way you like, for example with the GraphQL playground.
Make sure to use actual **double** floats (lots of digits after the comma) : 
```
complexInput: [
          { doublePrecisionField1: 59.2749013240351355, doublePrecisionField2: 15.223210957815533 },
          ...
]
```

**It works as expected**

Now do it again with **3.2**.0.0 : 

Even before entering the mutation field's custom code, GraphQL rejects the mutation with this error : 
`GraphQL.Validation.Errors.ArgumentsOfCorrectTypeError: Argument \"complexInput\" has invalid value [{doublePrecisionField1: 59.2749013240351355, 
...
`

Please note that this fails **only if the input is genuine double precision numbers**. If they're "just" float numbers, it works.
**This works :** 
```
complexInput: [{ doublePrecisionField1: 59.274901, doublePrecisionField2: 15.223210 }]
```

**This doesn't work :** 
```
complexInput: [{ doublePrecisionField1: 59.2749013240351355, doublePrecisionField2: 15.223210957815533 }]
```

**Comment by jeancallisti** [comment]
The issue seems to be resolved in version 5.

**Comment by sungam3r** [comment]
Version 5? We published only 4.x . Did you mean server v5?

**Comment by jeancallisti** [comment]
Yes. Fixed.
