### ISSUE TITLE
Docs need to be updated as the sample doesn't work right off the bat

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [graphql-dotnet/graphql-dotnet#2462]
## Summary

In the docs section, I noticed that the sample does not work. When I create a console application and follow those steps `schema.ExecuteAsync` shows an error as it needs `IDocumentWriter`

https://graphql-dotnet.github.io/docs/getting-started/introduction#graphtype-first-approach

### Motivation

We need to make sure sample in docs always work. I'd be happy to submit a change. When we use the `DocumentWriter` from 
`GraphQL.SystemTextJson`, it works just fine. 

Please let me know if this is an issue or needs to be updated.

**Comment by sungam3r** [comment]
@EmmanuelPonnudurai Thanks, fixed.
