### ISSUE TITLE
How to map multiple schema request to one object in one graphql query?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2464]
I am working with GraphQL.  I have two different queries in my below request and they all return data fine.

    # Write your query or mutation here
    {
      clientNavigationRequest(
        clientNavigation: {
          siteId: 2
          filters: [{ filterKey: "o", filterValueId: 99 }]
          protoRequest: {
            protoKey: "trim"
          }
        }
      ) {
        id
        name
      }
      helloWorldRequest(
        helloWorld: {
          siteId: 2
          filters: [{ filterKey: "o", filterValueId: 99 }]
          protoRequest: {
            protoKey: "trim"
          }
        }
      ) {
        id
        name
      }
    }

Below is the my Query code:

    public class StarWarsQuery : ObjectGraphType<object>
    {
        public StarWarsQuery(StarWarsData data)
        {
            Name = "Query";

            // #Schema1
            Field<HumanType>(
                "clientNavigationRequest",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<ClientNavigationInputType>> { Name = "clientNavigation", Description = "id of the human" }
                ),
                resolve: context =>
                {
                    var human = context.GetArgument<DataRequest>("clientNavigation");
                    var headers = (IDictionary<string, object>)context.UserContext;
                    return data.GetHumanByIdAsync(human);
                }
            );

            // #Schema2
            Field<HelloType>(
                "helloWorldRequest",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<HelloWorldInputType>> { Name = "helloWorld", Description = "id of the human" }
                ),
                resolve: context =>
                {
                    var human = context.GetArgument<DataRequest>("helloWorld");
                    var headers = (IDictionary<string, object>)context.UserContext;
                    return data.GetHumanByIdAsync(human);
                }
            );
        }
    }

**Problem Statement**

As you can see in my above code - For each schema request I extract the input passed from GraphQL and call `GetHumanByIdAsync` method to get the response.

- SchemaA input request is map to a objectA in `DataRequest` class.
- SchemaB input is map to a objectB in `DataRequest` class.

Input Request for both schema call is same mapped to `DataRequest` object and response `HelloType` and `HumanType` is also mapped to same response object.

So is there any way by which we can extract input for both of my input and get single `DataRequest` object but return the response back to user for each schema in the original way?

```
// Get Request from SchemaA and SchemaB and make one `DataRequest` object instead of making two in original example.
// And then call `GetHumanByIdAsync` method to get single response based on `DataRequest` object from point 1 above.
// Map that response to `HelloType` and `HumanType` and return back to the user in original way.

```

Is this possible to do by any chance?

**Comment by Shane32** [comment]
I think you want to eliminate the redundant call to GetHumanByIdAsync - correct? Check out the data loader documentation. It should be just what you need.

**Comment by TechGeeky** [comment]
yeah eliminate redundant call. Can you point me to data loader documentation? Also if you can provide an example here then that will be great for me to understand on how to accomplish this?

**Comment by Shane32** [comment]
See https://graphql-dotnet.github.io/docs/guides/dataloader

The documentation is pretty thorough which includes a sample for `GetUsersByIdAsync` which is probably most applicable to you.  Let me know if you have questions or open another issue.

**Comment by Shane32** [comment]
Please reopen if needed
