### ISSUE TITLE
How to chain GraphQL schema and call corresponding classes to get data out of it?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2465]
Is it possible to chain GraphQL request? Let's say I have 5 different schema as shown below -

```
  type Query {
    helloWorldRequest(
      helloWorld: HelloWorldInput!
    ): HelloWorldRequest
    clientNavigationRequest(
      clientNavigation: ClientNavigationInput!
    ): ClientNavigationRequest
    dataRequest(
      data: DataInput!
    ): DataRequest
    ...
    ...
  }
```

Is there any way to figure out what schemas are present in the request and call classes basis on that logic. For example:

- If SchemaA and SchemB are present then call ClassOne to get data.
- If SchemaA and SchemaC are present then call ClassThree to get data.
- If SchemaB and SchemaC are present then call ClassFour to get data.
- ...
- ...

Basis on certain combinations of schemas in the request call certain classes to get data out of it. We can create above mapping somewhere in the code and basis on that mapping call those classes if you see those schemas in the request. Is there anything in GraphQL dotnet where I can leverage this and do it in Query anyhow?

**Comment by Shane32** [comment]
A “schema” represents the entire definition of the types and fields. And a request doesn’t contain a schema at all but simply contains a query for fields - against a schema.

Do you mean execute different code based on which fields were requested? Or do you mean actually different entire schemas? I’m a bit confused.

**Comment by TechGeeky** [comment]
For example:

    # Write your query or mutation here
    {
      clientNavigationRequest(
        clientNavigation: {
          siteId: 2
          filters: [{ filterKey: "o", filterValueId: 99 }]
          protoRequest: {
            protoKey: "trim"
          }
        }
      ) {
        id
        name
      }
      helloWorldRequest(
        helloWorld: {
          siteId: 2
          filters: [{ filterKey: "o", filterValueId: 99 }]
          protoRequest: {
            protoKey: "trim"
          }
        }
      ) {
        id
        name
      }
    }

For above request, in my below query code - `clientNavigationRequest` call goes to `#Part1` and `helloWorldRequest` call goes to `#Part2`. Let me know if wording is wrong here and you can correct me.

    public class StarWarsQuery : ObjectGraphType<object>
    {
        public StarWarsQuery(StarWarsData data)
        {
            Name = "Query";

            // #Part1
            Field<HumanType>(
                "clientNavigationRequest",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<ClientNavigationInputType>> { Name = "clientNavigation", Description = "id of the human" }
                ),
                resolve: context =>
                {
                    var human = context.GetArgument<DataRequest>("clientNavigation");
                    var headers = (IDictionary<string, object>)context.UserContext;
                    return data.GetHumanByIdAsync(human);
                }
            );

            // #Part2
            Field<HelloType>(
                "helloWorldRequest",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<HelloWorldInputType>> { Name = "helloWorld", Description = "id of the human" }
                ),
                resolve: context =>
                {
                    var human = context.GetArgument<DataRequest>("helloWorld");
                    var headers = (IDictionary<string, object>)context.UserContext;
                    return data.GetHumanByIdAsync(human);
                }
            );
        }
    }

So similarly I can have for other schemas as well. Maybe my wording is wrong here but I hope you understand my point here. So is there any way we can batch multiple schema (some predefined combinations) request to some class and some other combination of schemas in GraphQL request to some other class to get data.

Does it make sense? If not I can try to clarify more.

**Comment by Shane32** [comment]
I'm still not sure I understand.
- Are you trying to automatically tie graphs to your data logic code?  Usually you'd be writing your own schema builder, but you might find some other frameworks like the https://github.com/graphql-dotnet/conventions project or my https://github.com/Shane32/GraphQL.DI project useful.  Within GraphQL.NET you can use `AutoRegisteringGraphType<T>` to assist creating the basic fields for a data object. 
- Are you just trying to batch the calls to `GetHumanByIdAsync`?  Just use one of the various data loader methods.  You can batch navigation fields, batch collection fields, or cache a single request.
- Are you trying to tailor a database call based on the child fields requested?  That's rather complicated.  There is a partial implementation you might consider at https://github.com/SimonCropp/GraphQL.EntityFramework/

**Comment by Shane32** [comment]
Please reopen if needed
