### ISSUE TITLE
How to create GraphQL schema which uses existing defined classes?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2474]
I have recently started working with `GraphQL`. I have played around with few examples [here](https://github.com/graphql-dotnet/examples/tree/master/src) and I have understood the basics of it. 

I have an existing `Asp.net Core 5.0` application which uses Kestrel server and all our GET and POST calls works fine. I am working on migrating all our legacy usecase to `GraphQL` endpoint. Currently starting with first use case to migrate it to `GraphQL`.

All our existing GET, POST requests is getting mapped to `ContainerRequest` class as shown below.

```csharp
    public interface IProcess
    {
        int ClientId { get; set; }
        int LanguageId { get; set; }
        int CustomerId { get; set; }
    }

    public interface IData
    {
        IList<Filter> Filters { get; set; }
        KeywordsTemplate KeywordsTemplate { get; set; }
    }

    public class Filter
    {
        public string Key { get; set; }
        public int Value { get; set; }
    }

    public class KeywordsTemplate
    {
        public string Query { get; set; }
        public string UserQuery { get; set; }
    }

    public class AggregationType
    {
        public string AggregationKey { get; set; }
    }

    public class ContainerRequest : IData, IProcess
    {
        public DetailsRequest DetailsRequest { get; set; }
        public ManagementRequest ManagementRequest { get; set; }
        public AggregationType AggregationType { get; set; }

        public IList<Filter> Filters { get; set; }
        public KeywordsTemplate KeywordsTemplate { get; set; }
        public int ClientId { get; set; }
        public int LanguageId { get; set; }
        public int CustomerId { get; set; }
        public int AppId { get; set; }

        // ToString() method here
    }
```

Now I am trying to map `GraphQL` request as it is to above classes as well without touching anything in above legacy classes. This way our existing usecase and `GraphQL` use case will use same `ContainerRequest` class to work for both scenarios.

Below is how I am using my `Query` -

```csharp
    FieldAsync<NavigationResponseType>(
        "navigationRequest",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<InputType>> { Name = "data", Description = "some stuff" }
        ),

        resolve: async context =>
        {
            var containerRequest = context.GetArgument<ContainerRequest>("data");
            // use containerRequest object here to call services async method to get the response back.
        }
    );
```

And this is what I have in my `InputType` class:

```csharp
    public class InputType : InputObjectGraphType<ContainerRequest>
    {
        public InputType()
        {
            Name = "Input";
            Field(x => x.ClientId);
            Field(x => x.AppId, nullable: true);
            Field(x => x.CustomerId, nullable: true);
            Field(x => x.LanguageId, nullable: true);
            Field<ListGraphType<FilterType>>("filters", "list of filters");
            Field<NonNullGraphType<AggregationTypeRequest>>("aggregationType", "some details here");
        }
    }
```

Below is my `AggregationTypeRequest` class:

```csharp
    public class AggregationTypeRequest : InputObjectGraphType<AggregationType>
    {
        public AggregationTypeRequest()
        {
            Name = "AggregationType";
            Field(x => x.AggregationKey);
        }
    }
```

Now if I go on GraphQL UI and run this query then it works fine. I am able to extract the arguments and map it to `ContainerRequest` class and also able to get the response back on the Graphical UI interface.

```graphql
{
  navigationRequest(data: {clientId: 123, filters: [{ key: "ke", value: 98 }], aggregationType: {aggregationKey: "process"}}) {
    title
    id
    name
  }
}
```

**Problem Statement**

Is there any way I can pass `GraphQL` request in the below format instead of passing it like I did above? And extract the arguments and map it to `ContainerRequest` class? I want to have `navigationRequest` schema which takes `clientId`, `filters` and `aggregationKey` as the input arguments.

```graphql
    {
      navigationRequest(clientId: 123, filters: [{key: "ke", value: "98"}], aggregationKey: "process") {
        title
        id
        name
      }
    }
```

What are the changes I need to make in my `Query` or `InputType` class to make sure it can accept the request in this format with `navigationRequest` as the schema? I can add some other new class to help me accept arguments in that format and then map it to `ContainerRequest` class if needed. Any help will be greatly appreciated.

I cannot modify `ContainerRequest` class as it's a legacy class.

**Comment by Shane32** [comment]
Add multiple arguments to your query field for filters, clientId, etc. Then within your field resolver construct your ContainerRequest object from the arguments.

**Comment by TechGeeky** [comment]
Thanks @Shane32. I got it resolved on my own by exactly doing what you recommended after posting the question here.
