### ISSUE TITLE
Map graphql schema response to poco fields

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2475]
I have a `ProcessResponse` class like below which contains our response that we return to the user. It has all the fields/objects that is needed by user to understand the response.

    [Serializable]
    public class ProcessResponse
    {
        public int ResponseCode { get; set; }
        public string Language { get; set; }

        public ClientResponse DocumentResponse { get; set; }
        public ClientResponse RegistryResponse { get; set; }
        public PetContext PetContext { get; set; }
        public TileComponentResponse TileComponentResponse { get; set; }
    }

    public class PetContext
    {
        public ParsedUrl CanonicalUrl { get; set; }
        public TransConfig TransConfig { get; set; }
    }

    public class TransConfig
    {
        public bool Index { get; set; }
        public bool Follow { get; set; }
    }

    [Serializable]
    public class ClientResponse
    {
        public int GroupCount { get; set; }
        public IList<ProtoGroup> ProtoGroups { get; set; }
    }

    [Serializable]
    public class ProtoGroup
    {
        public string ProtoLabel { get; set; }
        public string ProtoType { get; set; }
        public string ProtoGroupName { get; set; }
        public int ProtoCount { get; set; }
        public IList<ProtoGroup> SubGrouping { get; set; }
        public IList<Proto> Protos { get; set; }
        public Proto ProtoGroupUrl { get; set; }
        public int OrderId { get; set; }
    }

    [Serializable]
    public class Proto
    {
        public string ProtoId { get; set; }
        public int ProtoValuesCount { get; set; }
        public IList<ProtoValue> ProtoValues { get; set; }
    }

    [Serializable]
    public class ProtoValue
    {
        public string DisplayValue { get; set; }
        public int ValueId { get; set; }
        public int ProductCount { get; set; }
        public ParsedUrl ParsedUrl { get; set; }
        public IList<SnippetHolder> Snippets { get; set; }
        public double? OrderId { get; set; }
        public bool? IsPill { get; set; }
        public bool IsFeatured { get; set; }
    }

    [Serializable]
    public class ParsedUrl
    {
        public string Alias { get; set; }
        public string Resource { get; set; }
        public string BaseResource { get; set; }
        public string QueryString { get; set; }
        public string Url { get; set; }
    }

    [Serializable]
    public class SnippetHolder
    {
        public string ImagePath { get; set; }
    }

Now I have a below Query which is extracting arguments from the `GraphQL` request and getting the response from the underlying service which returns `ProcessResponse` as the response object back.

    FieldAsync<HumanType>(
        "human",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id", Description = "id of the human" }
        ),
        resolve: context =>
        {
            var human = context.GetArgument<string>("id");
            var requestContext = await clientService.BuildRequest(.....);

            // below line return `ProcessResponse` object
            var response = await metadataService.ProcessData(....);

            return response;
        }
    );

**Problem Statement**

Now I am confuse on how should I structure `HumanType` class so that it can give response in below format for below `GraphQL` request. I want to keep the keys in the same format as mentioned below:

    {
      human(id: 123) {
        title
        type
        links {
          text
          trkId
          href
          productCount
          resource
        }
      }
    }

This is the mapping between `GraphQL` response key to actual POCO key from the above classes. Data is already available in `ProcessResponse` class for above fields.

    title        --> protoLabel
    type         --> protoType
    text         --> displayValue
    trkId        --> resource
    href         --> url
    productCount --> productCount
    resource     --> baseResource

This is what I have as of now but I am confuse on how to get all other fields for `human` query?

    public class HumanType : ObjectGraphType<ProcessResponse>
    {
        public HumanType()
        {
            Name = "Human";
            // how should I map all above fields to `ProcessResponse` objects keys
        }
    }

Any example will be greatly appreciated that can help me understand on how to achieve this.

**Comment by Shane32** [comment]
Not at a pc but I think it’s:
`Field("title", x => x.ProtoLabel)`
And so on

**Comment by TechGeeky** [comment]
hmmm so we can give its own field name as the first parameter in `Field(......, ....)`? Also what about `links` structure? How can I make like that?

**Comment by Shane32** [comment]
If you’re mapping an object field — like SubGrouping — then you’ll want to register the clr type mapping in the schema constructor. 

`RegisterTypeMapping(typeof(ProtoGroup), typeof(ProtoGroupType))`

(HumanType in your example)

**Comment by Shane32** [comment]
Create another type like ProtoGroupLinksType and use the same `: ObjectGraphType<ProtoGroup>`

then in your humantype above, explicitly define the type and return the source

`Field<NonNullGraphType<ProtoGroupLinksType>>("links”, resolve: ctx => ctx.Source);`

**Comment by Shane32** [comment]
You don’t want to use type mapping because it would conflict with other automatic mappings of ProtoGroup

**Comment by Shane32** [comment]
Or a base type of `ObjectGraphType<ProcessResponse>` - you get what I mean

**Comment by Shane32** [comment]
Basically you’re just passing through the same object to a child type.

**Comment by TechGeeky** [comment]
@Shane32 I got confuse I guess. Do you think you can provide an example on what extra classes I need to add? And what new lines I should add in `HumanType` class.

**Comment by Shane32** [comment]
I think the problem is that your POCO objects are not lining up to the layout of your GraphQL response.  You just need to add some property accessors and/or LINQ to return the proper data.  For example, you appear to be trying to return a single result, but a ProcessResponse object contains `DocumentResponse` and `RegistryResponse`, both of which can contain multiple `ProtoGroup` instances.  So I'm a bit guessing how your data objects work, and I didn't test it, but you probably want something like this:

```cs
public class TitanSchema : Schema
{
    public TitanSchema(IServiceProvider provider) : base(provider)
    {
        Query = provider.GetRequiredService<TitanQuery>();
        this.RegisterTypeMapping<ProtoValue, ProtoValueType>();
    }
}

//within TitanQuery
FieldAsync<HumanType>(
    "human",
    arguments: new QueryArguments(
        new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id", Description = "id of the human" }
    ),
    resolve: context =>
    {
        var human = context.GetArgument<string>("id");
        var requestContext = await clientService.BuildRequest(.....);

        // below line return `ProcessResponse` object
        var response = await metadataService.ProcessData(....);

        // customize this to your needs:
        // pull the single "ProtoGroup" that you want to return from the response
        var protoGroup = response.DocumentResponse.ProtoGroups.Single();

        // don't return the whole response object here; return the single
        // ProtoGroup object that should be returned to the caller
        return protoGroup;
    }
);

//HumanType (which I would rename to ProtoGroupType or something appropriate)
public class HumanType : ObjectGraphType<ProtoGroup>
{
    public HumanType()
    {
        Name = "Human"; //note: you don't need to specify a name; it will automatically be inferred from the class name

         // add the basic fields
        Field("title", x => x.ProtoLabel)
        Field("type", x => x.ProtoType);

        // flatten the list of lists (!?!) into a single list and return it as a list of `ProtoValue` instances
        // the graph type will be inferred automatically since we registered the type mapping in the schema constructor
        Field("links", x => x.Protos.SelectMany(y => y.ProtoValues));
    }
}

// add the graph type for the "links" object field
public class ProtoValueType : ObjectGraphType<ProtoValue>
{
    public ProtoValueType()
    {
        Name = "ProtoValue";
        Field("text", x => x.DisplayValue);
        Field("trkId", x => x.ParsedUrl.Resource);
        Field("href", x => x.ParsedUrl.Url);
        Field("productCount", x => x.ProductCount);
        Field("resource" x=> x.ParsedUrl.BaseResource);
    }
}
```

**Comment by TechGeeky** [comment]
Thanks a lot @Shane32 for detailed explanation. Just going through your suggestion and incorporating in my code. 

After I added `RegisterTypeMapping` in `TitanSchema` class, it gives me this error?

```
'TitanSchema' does not contain a definition for 'RegisterTypeMapping' and no accessible extension method 'RegisterTypeMapping' accepting a first argument of type 'TitanSchema' could be found (are you missing a using directive or an assembly reference?)
```

Do I need to add any other dependency for this?

**Comment by Shane32** [comment]
No but maybe `using GraphQL;`. Or maybe the method name is a little different.

**Comment by TechGeeky** [comment]
I added `using GraphQL;` but still same error.

**Comment by Shane32** [comment]
It’s there somewhere if you’re on version 4. Just check what methods are available. Maybe it’s RegisterClrTypeMapping. Not at a pc now but it’s there for sure.

**Comment by Shane32** [comment]
Documentation for RegisterTypeMapping is on this page:

https://graphql-dotnet.github.io/docs/getting-started/schema-types

**Comment by TechGeeky** [comment]
Thanks @Shane32. Sure let me check out. I am not yet at version 4 but I am looking at upgrading to `4.2.0` from `3.1.3` version. But if you figure it out what should be the exact fix whenever you are back, I will really appreciate some help.

I don't see any `RegisterClrTypeMapping` method to use but still looking around to see if I can find out.

**Comment by Shane32** [comment]
In version 3 it’s a static method within GraphTypeTypeRegistry. Forgot the method name but it is probably “Register”. In version 4 the code sample I provided previously should work. I won’t be at a pc for most of the day today to check.

**Comment by Shane32** [comment]
Version 4 method: see line 87:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/SchemaExtensions.cs

Or line 129 here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/ISchema.cs

Version 3 method: see line 32 and 37:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master3/src/GraphQL/Utilities/GraphTypeTypeRegistry.cs

**Comment by TechGeeky** [comment]
@Shane32  Thank you for finding me the right class and method to use. I got that working by adding like this in the Schema class -

```
GraphTypeTypeRegistry.Register<ProtoValue, ProtoValueType>();
```

I have one last question which I think is pretty simple but missing something very basic. As of now my output comes in this format on GraphQL UI. As you can see `human` is a json object but I want it to be an array.

```
{
  "data": {
    "human": {
      "title": "abc",
      "type": "hello",
      "links": [
        {
          ...
          ...
        },
        {
          ...
          ...
        }
      ]
    }
  }
}
```

Basically I want output to be like this like where human can be a json array.

```
{
   "data":{
      "human":[
         {
            "title":"abc",
            "type":"hello",
            "links":[
               {
                  ...
                  ...
               },
               {
                  ...
                  ...
               }
            ]
         },
         {
            "title":"def",
            "type":"world",
            "links":[
               {
                  ...
                  ...
               },
               {
                  ...
                  ...
               }
            ]
         }
      ]
   }
}
```

My `ProtoGroups` is also a list in `ClientResponse` class. I tried returning as it is in my `TitanQuery ` class instead of using `.Single()` on them but still it doesn't work for me -

```
  var protoGroup = response.DocumentResponse.ProtoGroups;
  return protoGroup;
```

I believe there is something very minor which I am missing here.

**Comment by Shane32** [comment]
FieldAsync<ListGraphType<HumanType>>

**Comment by TechGeeky** [comment]
damn. Need coffee. I was using `ListGraphType` in my other example but couldn't figure it out here. Sorry about that.

**Comment by TechGeeky** [comment]
@Shane32 I added few other things on top of your suggestion and everything is working fine now but I think I hit a roadblock when I am trying to map below request using the same idea as you suggested.

    {
      human(id: 510005) {
        title
        type
        links {
          text
          trkId
          href
          productCount
          resource
        }
        petContext {
          canonicalUrl
          hasIndex
          hasFollow
        }
      }
    }

In the above request I have one extra new structure `petContext` which is mapping like this - 

    canonicalUrl --> Url
    hasIndex --> Index
    hasFollow --> Follow

I have a class `PetContext` at root level in `ProcessResponse` so I need to extract `canonicalUrl`, `hasIndex` and `hasFollow` from them. My original post already has `PetContext` class. 

It is kinda similar to what you helped me for `links` structure but when I tried same thing for `petContext` then I am getting bunch of compilation errors. Do you think you can help me with this one as well by providing an example?

**Comment by Shane32** [comment]
Hard to help without a sample.

**Comment by TechGeeky** [comment]
You mean data sample or code sample? @Shane32 

This is what I have so far where I am confuse. I tried few other ways but all resulted in compilation errors so keeping it simple for you to understand.

In `ProcessResponse` class, I have `PetContext` at root level so I am using `ProcessResponse` class instead of `ProtoGroup`  in `HumanType` so that I can use that to extract `PetContext` here but once I make that change I cannot get `ProtoLabel`, `ProtoType` or `Protos` which makes sense why I can't.

    public class HumanType : ObjectGraphType<ProcessResponse>
    {
        public HumanType()
        {
            Name = "Human";

             // they all gives errors
            Field("title", x => x.ProtoLabel)
            Field("type", x => x.ProtoType);
            Field("links", x => x.Protos.SelectMany(y => y.ProtoValues));
            # how to extract PetContext here along with above fields?
        }
    }

But then question becomes how can I extract `PetContext` at root level and then few other original objects at the inner most level? I don't want to extract everything from `ProcessResponse` class.

    public TitanSchema(IServiceProvider provider) : base(provider)
    {
        Query = provider.GetRequiredService<TitanQuery>();
        this.RegisterTypeMapping<ProtoValue, ProtoValueType>();
    }

    //within TitanQuery, modified it to return `ProcessResponse` object
    FieldAsync<HumanType>(
        "human",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id", Description = "id of the human" }
        ),
        resolve: context =>
        {
            var human = context.GetArgument<string>("id");
            var requestContext = await clientService.BuildRequest(.....);

            // below line return `ProcessResponse` object
            var processResponse = await metadataService.ProcessData(....);
            return processResponse;
        }
    );

    // add the graph type for the "links" object field
    public class ProtoValueType : ObjectGraphType<ProtoValue>
    {
        public ProtoValueType()
        {
            Name = "ProtoValue";
            Field("text", x => x.DisplayValue);
            Field("trkId", x => x.ParsedUrl.Resource);
            Field("href", x => x.ParsedUrl.Url);
            Field("productCount", x => x.ProductCount);
            Field("resource" x=> x.ParsedUrl.BaseResource);
        }
    }

**Comment by Shane32** [comment]
Well, I don't think these questions have anything to do with GraphQL.

Correct me if I'm wrong, but you want this query:

```gql
{
  human(id: 123) {
    title
    type
    links {
      text
      trkId
      href
      productCount
      resource
    }
    petContext {
      canonicalUrl
      hasIndex
      hasFollow
    }
  }
}
```

And this response:

```json
{
  "human": [
    {
      "title": "test1",
      "type": "abcd",
      "links": {
        ...
      },
      "petContext": {
        "canonicalUrl": "abcd",
        ...
      }
    },
    {
      "title": "test2",
      "type": "abcd",
      "links": {
        ...
      },
      "petContext": {
        "canonicalUrl": "abcd",
        ...
      }
    },
    ...
  ]
}
```

So the important point is that Human is returning a list of objects, but some of the data (petContext) is coming from the root, not within the list.  A graph can represent any model of data, but if you pass the ProcessResponse into the graph, then the graph will have no idea which index entry to return.  You're going to need to create a model that combines data from each ProtoGroup and data from the ProcessResponse together in order to more closely resemble the graph data format.

For instance, here's a basic LINQ query that does such a thing:

```cs
var processResponse = ...;
var humanList = processResponse.DocumentResponse.ProtoGroups.Select(protoGroup => new {
  PetContext = processResponse.PetContext,
  ProtoGroup = protoGroup
});

//for example, the data could be accessed like this now:
foreach (var human in humanList)
{
  var title = human.ProtoGroup.ProtoLabel;
  var petContextCanonicalUrlUrl = human.PetContext.CanonicalUrl.Url;
}
```

Now the above sample won't exactly work for you because it's an anonymous type, and you can't define a graphql source object type based on an anonymous type.  But create a concrete model instead of `new { ... }` and you should be fine.  (You can even use the `Tuple<T1, T2>` type if you wanted to.)

I suggest you read up on LINQ queries and create data models to resemble your output format closer before you attempt to map it to graphql objects.  Sometimes you may not need to, but here it seems that you do.

Once you have the data models constructed properly, then 90% of the time you can use the `Field("trkId", x => x.ParsedUrl.Resource);` syntax to map your fields, and Intellisense will help you complete the statement.  If you have something more complex, then you need to use a syntax that defines the exact graph type (e.g. `Field<ProtoGraphType>(...)`).

**Comment by TechGeeky** [comment]
@Shane32 Yes same exact query and same exact response. I also thought of creating a new model from `ProcessResponse` class which should exactly match with what I need in `GraphQL` response and then use that model in my `HumanType` class to get what I need. Is this what you meant and trying to explain right? 

I can do that for sure but I am trying to see if I can extract everything what I need directly from `ProcessResponse` class if there is any possibility. Is there any way by which I can do that here without creating extra response model? This is definitely helping me out to see how we can model complex structure if we have to do which in turn helping me to see what are the things we can do with GraphQL.

**Comment by Shane32** [comment]
Yes, correct.

Based on the sample you provided, it would seem that you need to create an intermediary model.  At least the one intermediary model anyway; perhaps the rest can remain.

**Comment by TechGeeky** [comment]
Yeah I can do that for sure but I was wondering is there any way we can do this without creating any intermediary model? Do you think there is an option by which we can do this directly using `ProcessResponse` class without any intermediary model?

**Comment by Shane32** [comment]
The thing is the graph only has one "source" -- a single object that you can pass to it.  You can't pass both the indexed and the parent.  If you've done MVC programming, it's a bit like a MVC model -- except no ViewData or ViewBag.  (There is a UserContext but that would be generic to the entire request, not just the 'human' request)

**Comment by Shane32** [comment]
So if human doesn't return a list, then it's easy.  But since you want a list, you need to return a list of something.  A list of the children object simply doesn't suit your needs.  You need the children AND the parent.  So you have to create a model to contain both the child and parent similar to the above example.  Again, you can use the `Tuple<T1, T2>` type if you don't want to add additional classes to your code.  But it just makes the code harder to read because the first item will be called `Item1` and the second `Item2`.

**Comment by Shane32** [comment]
Here's another idea -- you can try accessing the `Parent` property of the `IResolveFieldContext`.  I can't remember if the `Source` property is populated on it.  If so, it might suit your needs.

```cs
Field<PetContextType>("petContext", resolve: context => ((ProcessResponse)context.Parent.Source).PetContext);
```

**Comment by Shane32** [comment]
I'm looking at the source code now of `Parent` and that should actually work.

**Comment by Shane32** [comment]
Note that `Parent` is a new feature for v4.

**Comment by Shane32** [comment]
https://graphql-dotnet.github.io/docs/migrations/migration4#ability-to-get-parent-resolve-context-of-any-level

**Comment by Shane32** [comment]
Oh wait that won't work because the parent is the query root.  Oh well.

**Comment by TechGeeky** [comment]
Yeah I see your point. The reason I was asking this is to learn something new here and see if there is a way to do that directly without any extra model. By talking to you over few days just on this problem, I learned so much just to how we map complex structure. 

I was gonna try out the `Parent` property idea but it looks like you mentioned it may not work. Any other thoughts before I go back to creating a new model?

**Comment by Shane32** [comment]
Nope I'm out of ideas.

`Parent` can't help because there's no common ancestor where the instance of `ProcessResponse` was returned from the field resolver.  And if you return it directly from human then graphql will throw an exception because `ProcessResponse` is not an `IEnumerable` and your graph type is a `ListGraphType<>`.

**Comment by TechGeeky** [comment]
I am good guys. Thanks for the help! Closing this out.
