### ISSUE TITLE
Upgrading from 3.1.3 to 4.2.0 GraphQL version

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2476]
I am upgrading my GraphQL version from `3.1.3` to `4.2.0`. When I compile my code I am seeing below three issues - 

> The type or namespace name 'EnterLeaveListener' could not be found (are you missing a using directive or an assembly reference?)
> 
> 'IServiceProvider' does not contain a definition for 'GetRequiredService' and no accessible extension method 'GetRequiredService' accepting a first argument of type 'IServiceProvider' could be found (are you missing a using directive or an assembly reference?)
> 
> 'ExecutionOptions' does not contain a definition for 'FieldMiddleware' and no accessible extension method 'FieldMiddleware' accepting a first argument of type 'ExecutionOptions' could be found (are you missing a using directive or an assembly reference?)

Here is my `InputValidationRule` class where `EnterLeaveListener` class is being used:

    public class InputValidationRule : IValidationRule
    {
        public Task<INodeVisitor> ValidateAsync(ValidationContext context)
        {
            return Task.FromResult((INodeVisitor)new EnterLeaveListener(_ =>
            {
            }));

            return Task.FromResult((INodeVisitor)) new 
        }
    }

And here is my `GraphQLMiddleware` class:

       using GraphQL;
       using GraphQL.Instrumentation;
       using GraphQL.NewtonsoftJson;
       using GraphQL.Types;
       using GraphQL.Utilities;
       using GraphQL.Validation;
       
       public class GraphQLMiddleware
        {
            private readonly RequestDelegate _next;
            private readonly GraphQLSettings _settings;
            private readonly IDocumentExecuter _executer;
            private readonly IDocumentWriter _writer;

            public GraphQLMiddleware(
                RequestDelegate next,
                GraphQLSettings settings,
                IDocumentExecuter executer,
                IDocumentWriter writer)
            {
                _next = next;
                _settings = settings;
                _executer = executer;
                _writer = writer;
            }

            public async Task Invoke(HttpContext context, ISchema schema)
            {
                if (!IsGraphQLRequest(context))
                {
                    await _next(context);
                    return;
                }

                await ExecuteAsync(context, schema);
            }

            private bool IsGraphQLRequest(HttpContext context)
            {
                return context.Request.Path.StartsWithSegments(_settings.Path)
                    && string.Equals(context.Request.Method, "POST", StringComparison.OrdinalIgnoreCase);
            }

            private async Task ExecuteAsync(HttpContext context, ISchema schema)
            {
                var request = Deserialize<GraphQLRequest>(context.Request.Body);
                var result = await _executer.ExecuteAsync(_ =>
                {
                    _.Schema = schema;
                    _.Query = request?.Query;
                    _.OperationName = request?.OperationName;
                    _.Inputs = request?.Variables.ToInputs();
                    _.UserContext = _settings.BuildUserContext?.Invoke(context);
                    _.ValidationRules = DocumentValidator.CoreRules.Concat(new[] { new InputValidationRule() });
                    _.EnableMetrics = _settings.EnableMetrics;
                    if (_settings.EnableMetrics)
                    {
                        _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
                    }
                });
                await WriteResponseAsync(context, result);
            }

            private async Task WriteResponseAsync(HttpContext context, ExecutionResult result)
            {
                context.Response.ContentType = "application/json";
                context.Response.StatusCode = result.Errors?.Any() == true ? (int)HttpStatusCode.BadRequest : (int)HttpStatusCode.OK;

                await _writer.WriteAsync(context.Response.Body, result);
            }

            public static T Deserialize<T>(Stream s)
            {
                using (var reader = new StreamReader(s))
                using (var jsonReader = new JsonTextReader(reader))
                {
                    var ser = new JsonSerializer();
                    return ser.Deserialize<T>(jsonReader);
                }
            }
        }

And here is my `TitanSchema` class:

    using GraphQL;
    using GraphQL.Types;
    using GraphQL.Utilities;

    public class TitanSchema : Schema
    {
        public TitanSchema(IServiceProvider provider) : base(provider)
        {
            Query = provider.GetRequiredService<TitanQuery>();
            this.RegisterTypeMapping<ProtoValue, ProtoValueType>();
        }
    }

All these three classes are showing above three problems. I tried looking online but couldn't figure it out. Any help will be greatly appreciated.

**Comment by sungam3r** [comment]
https://graphql-dotnet.github.io/docs/migrations/migration4/ All breaking changes are described here.

**Comment by TechGeeky** [comment]
@sungam3r yeah I saw the migration doc but couldn't figure out what I need to do to resolve those issues. Is there any example which uses GraphQL version 4 which has usage of `GraphQLMiddleware`? If you can help me figure out on how to resolve these issues then it will be of great help.

**Comment by sungam3r** [comment]
> The type or namespace name 'EnterLeaveListener' could not be found (are you missing a using directive or an assembly reference?)

![изображение](https://user-images.githubusercontent.com/21261007/113569570-694efe00-961b-11eb-813d-364af3c2e8a4.png)

>'IServiceProvider' does not contain a definition for 'GetRequiredService' and no accessible extension method 'GetRequiredService' accepting a first argument of type 'IServiceProvider' could be found (are you missing a using directive or an assembly reference?)

https://graphql-dotnet.github.io/docs/migrations/migration4/#dependency-injection--getrequiredservice

> 'ExecutionOptions' does not contain a definition for 'FieldMiddleware' and no accessible extension method 'FieldMiddleware' accepting a first argument of type 'ExecutionOptions' could be found (are you missing a using directive or an assembly reference?)

https://graphql-dotnet.github.io/docs/migrations/migration4/#schema-configuration-options-moved

We spent a lot of time to describe all changes in the guide. If it seems to you that the explanation is insufficient, then the PR is welcomed.

**Comment by Shane32** [comment]
Also see https://github.com/graphql-dotnet/graphql-dotnet/issues/2406

**Comment by TechGeeky** [comment]
Figured it out. Thanks guys for helping!
