### ISSUE TITLE
GraphQL Syntax Error When An Object Type Is Implementing Multiple Interfaces Using Schema-First Approach

### ISSUE THREAD

**Issue by autumnkids** [graphql-dotnet/graphql-dotnet#2478]
## Description

When trying to use the schema-first approach to create the schema, `Schema.For` and `FederatedSchema.For` will throw a `GraphQLSyntaxErrorException` exception saying `&` is an unexpected character if a `type` is implementing two or more `interface`s.

I guess the issue comes from here https://github.com/graphql-dotnet/parser/blob/c17fe879af5534e083a09aeb631749fd46129272/src/GraphQLParser/LexerContext.cs#L19-L53, where the `&` operator is probably not properly parsed.

### Steps to reproduce

I got a couple unit tests to help reproduce this:

```
using NUnit.Framework;
using GraphQL.Types;
using GraphQL.Utilities.Federation;
using GraphQLParser.Exceptions;

namespace MyTest
{
    public class SchemaTest
    {
        private const string TestSchemaWithTwoInterfaceImplemented = @"
            type Query {
              me: Account
            }

            interface FooInterface {
              id: String
            }

            interface BooInterface {
              name: String
            }

            type Account implements FooInterface & BooInterface {
              id: String
              name: String
            }
        ";

        private const string TestSchemaWithOneInterfaceImplemented = @"
            type Query {
              me: Account
            }

            interface FooInterface {
              id: String
            }

            type Account implements FooInterface {
              id: String
              name: String
            }
        ";

        [Test]
        public void BuildSchema_WhenImplementMultipleInterfaces_ThrowException()
        {
            Assert.Throws<GraphQLSyntaxErrorException>(() => Schema.For(TestSchemaWithTwoInterfaceImplemented));
            Assert.Throws<GraphQLSyntaxErrorException>(() => FederatedSchema.For(TestSchemaWithTwoInterfaceImplemented));
        }

        [Test]
        public void BuildSchema_WhenImplementOneInterface_NoExceptionThrown()
        {
            Assert.DoesNotThrow(() => Schema.For(TestSchemaWithOneInterfaceImplemented));
            Assert.DoesNotThrow(() => FederatedSchema.For(TestSchemaWithOneInterfaceImplemented));
        }
    }
}
```

### Expected result

When building a schema for a type that implements two or more interfaces with `&` operator, `Schema.For` and `FederatedSchema.For` should not throw a syntax error saying `&` is unexpected.

### Actual result

The `GraphQLSyntaxErrorException` exception is thrown as demonstrated in the unit tests above.

### Environment

I'm using GraphQL 4.1.0

```
<PackageReference Include="GraphQL" Version="4.1.0" />
<PackageReference Include="GraphQL.DataLoader" Version="4.1.0" />
<PackageReference Include="GraphQL.Relay" Version="0.5.0" />
<PackageReference Include="GraphQL.SystemTextJson" Version="4.1.0" />
```

Thanks!

**Comment by joemcbride** [comment]
Thanks for the report!  Yes that does sound like a problem with the Parser, though that may have implications with this framework as well.

**Comment by sungam3r** [comment]
@Shane32 @joemcbride Please review linked PR. Should I publish a new v4.2.1 release with updated v7.1.0 parser dependency ?

**Comment by sungam3r** [comment]
@autumnkids Done in https://github.com/graphql-dotnet/parser/releases/tag/7.1.0. Try install https://www.nuget.org/packages/GraphQL-Parser/7.1.0 explicitly.

**Comment by sungam3r** [comment]
@joemcbride @Shane32  I think that there is no need to make a release with a new version, because this feature is little in demand. We will update the parser dependency later when the time of the next scheduled release comes.
