### ISSUE TITLE
Convert string to integer while extracting query arguments?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2479]
I have a GraphQL query like this - 

    {
      human(customers: [{key: "abc", value: 98}], clientName: "process") {
        title
        type
      }
    }

Below is my query where I am extracting the arguments passed from above and processing the response.

    FieldAsync<ListGraphType<HumanType>>(
        "human",
        arguments: new QueryArguments(
                new QueryArgument<ListGraphType<CustomerType>>
                {
                    Name = "customers",
                    Description = "customers input"
                },
                new QueryArgument<StringGraphType>
                {
                    Name = "clientName",
                    Description = "client name input"
                }
            ),

        resolve: async context =>
        {
            var customers = context.GetArgument<List<Customer>>("customers");
            var clientName = context.GetArgument<string>("clientName");
            // process request and call service to get the response back
            
            return response;
        }
    );

Here is my `CustomerType` class:

    public class CustomerType : InputObjectGraphType<Customer>
    {
        public CustomerType()
        {
            Name = "Customer";
            Field("key", x => x.CustomerKey);
            Field("value", x => x.CustomerValueId);
        }
    }

Here is my `Customer` class:

    public class Customer
    {
        public string CustomerKey { get; set; }
        public int CustomerValueId { get; set; }
    }

As you can see I am mapping `value` to `CustomerValueId` and everything works fine. Here `value` is Integer and `CustomerValueId` is also Integer.

Is there any way I can pass query arguments like this where value is also a string without changing data type in `Customer` class?

    {
      human(customers: [{key: "abc", value: "98"}], clientName: "process") {
        title
        type
      }
    }

I know this isn't desired but this is something to support our legacy use case. Is there anything that can be done where I can convert `string 98` to Integer and then map it to `CustomerValueId`?

**Comment by Shane32** [comment]
If you use an `IdGraphType` then it will allow strings or numbers.

`Field("value", x => x.CustomerValueId, type: typeof(NonNullGraphType<IdGraphType>));`

**Comment by TechGeeky** [comment]
This work. Thank you!
