### ISSUE TITLE
The input field '<field>' of an Input Object '<field>' must be an input type.

### ISSUE THREAD

**Issue by adityavaish** [graphql-dotnet/graphql-dotnet#2484]
## Description

When updating to 4.0 we are getting following errors:

The input field '<FieldA>' of an Input Object '<FieldB>' must be an input type.

Our schema is something like

```
type FieldA {
    foo: String
    bar: String
}

input FieldB {
    foo2: FieldA
}
```

### Steps to reproduce

Use the above schema. It works in 3.x but breaks in 4.x

### Expected result

Expecting backward compatibility or a workaround. 

### Actual result

Updating to 4.x breaks code

**Comment by Shane32** [comment]
In short, Version 4 enforces a requirement that input and output types need to be different classes, where input types inherit from `InputObjectGraphType` and output types don't.  It's hard to help more without seeing more of your code.

**Comment by sungam3r** [comment]
> It works in 3.x but breaks in 4.x

Yes. It was a bug in 3.x. Actually your schema above is not valid, it is not spec compliant. See http://spec.graphql.org/June2018/#sec-Input-Objects, section **Type validation**, then [IsInputType](http://spec.graphql.org/June2018/#IsInputType()) function.

**Comment by sungam3r** [comment]
You may change your schema. Split `FieldA` to `type FieldA` and `input FieldAInput`. Use `FieldAInput` for `foo2`.

**Comment by adityavaish** [comment]
Thanks, do understand that its not as per spec and it was supported by 3.x.
