### ISSUE TITLE
Result filed for RootExecutionNode is null

### ISSUE THREAD

**Issue by adityavaish** [graphql-dotnet/graphql-dotnet#2489]
## Description

The ```Result``` field for ```RootExecutionNode``` is null with update to 4.x. This field used to return final result in 3.x.

Here is the code parts

```
var result = await this.documentExecuter.ExecuteAsync(configure =>
            {
                configure.Schema = schemaProvider.Schema;
                configure.Query = inputQuery.Query;
                configure.OperationName = inputQuery.OperationName;
                configure.Inputs = inputQuery.Variables.ToInputs();
                configure.RequestServices = this.serviceProvider;
            });
```

```this.documentExecuter``` is of type ```DocumentExecutor```. The ```result``` in 4.x looks like

![image](https://user-images.githubusercontent.com/1886571/114036181-b4902900-9834-11eb-963e-7e21b9bda110.png)

while for 3.x the response to same schema was

![image](https://user-images.githubusercontent.com/1886571/114036712-29fbf980-9835-11eb-9558-8e89f8b9253c.png)

### Steps to reproduce

The response schema for DocumentExecutor changed and there is no filed to get final response.

### Expected result

In the response of DocumentExecutor there should be field corresponding to final response that should be returned.

### Actual result

The response schema for DocumentExecutor changed and there is no filed to get final response.

**Comment by Shane32** [comment]
The `RootExecutionNode` now is the final result, and has child dictionary entries exposed through its `SubFields` property, which may contain other `ExecutionNodes` instances such as `ArrayExecutionNodes`.  You can call `ToValue()` on the `RootExecutionNode` to return a `Dictionary<>` of values just like 3.x.  If you wish to process the `ExecutionNode` instances directly, take a look at the implementation in `GraphQL.SystemTextJson.ExecutionResultJsonConverter.WriteExecutionNode`:

https://github.com/graphql-dotnet/graphql-dotnet/blob/2e49888da2393b2991bb52a5306b110dc948b224/src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs#L55..L103

**Comment by adityavaish** [comment]
It worked! Worth mentioning in migration doc?
