### ISSUE TITLE
`variables` in gql POST payloads, forced to parse as Newtonsoft.Json.Linq.JObject

### ISSUE THREAD

**Issue by ZenSoftware** [graphql-dotnet/graphql-dotnet#249]
I have been stumbling across a hiccup parsing `variables` in POST payloads.

The issue I am facing, is that my CMS framework that I am integrating graphql-dotnet into, wraps and extends all of WebAPI 2.  The framework is DotNetNuke if you are curious, and I have been trying to put something together that is presentable to my community as an example of how to integrate our data access layer with graphql-dotnet.   Since I am integrating graphql-dotnet into a much larger technology stack, I am more restricted in changing the manner in which `variables` in the POST payload gets parsed.  Currently, it seems that I have no choice but to accept that `variables` wants to be parsed into a `Newtonsoft.Json.Linq.JObject` instead of being retained as a `String` by the time it gets to me.

Notice how I had to change `Variables` from type `String` to `Object` as seen below
```
public class GraphQLQuery
{
	public string OperationName { get; set; }
	public string NamedQuery { get; set; }
	public string Query { get; set; }
	public object Variables { get; set; }
}
```

For a payload of:
`{"query":"query PostsByAuthor($authId: Int) {\n  posts(authorId: $authId) {\n    content\n  }\n}","variables":{"authId":1},"operationName":"PostsByAuthor"}`

If `Variables` is defined as a `String`, then `ModelState` validation fails because it is being validated against something that is not a `String`.  It fails with the following exception.
`+		Exception	{"Unexpected character encountered while parsing value: {. Path 'variables', line 1, position 111."}	System.Exception {Newtonsoft.Json.JsonReaderException}`

This seems to be happening because `variables` is a direct JSON object, instead of JSON encapsulated in quotes. The only way to get `ModelState` validation to pass is to define `Variables` as an `Object`, not as a `String` unfortunately.  This is a problem because the only way I know how to construct the `Inputs` object, is via the [ToInputs()](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L52) string extension method.  Which obviously cannot be used on a `Newtonsoft.Json.Linq.JObject`

These are the options I have yet to explore as a solution:

1. Figure out how to get Apollo client to encapsulate the JSON object in quotes before it gets sent to the server.  I am not sure if that would even be compliant with the GraphQL standard.  But at least I would be able to use the [ToInputs()](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L52) string extension
2. Figure out how to construct `Inputs` from a `Newtonsoft.Json.Linq.JObject` by backwards engineering [ToInputs()](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L52) string extension.

I am actually not entirely sure if this behavior is specific to how our framework extends the WebAPI 2 pipeline, or if this pertains more generally to WebAPI 2.  I am just a community member trying to encourage support for graphql-dotnet.

The DNN community has some talented .NET web devs that I think would fall in love with this library if they only knew about it.  Would you be so kind as to share any insight with our community on how we should best approach this?  Is there another way of constructing `Inputs` that we are not aware of?  Thanks!  We are vested in your success ^_^

**Comment by ZenSoftware** [comment]
So the solution to construct `Inputs` via an already parsed `Variables` is actually quite simple.

Copy the static function [GetValue(object value)](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L80) and use the following code to construct the `Inputs` object required to execute the query:

```
public async Task<HttpResponseMessage> PostAsync(GraphQLQuery query)
{
	Inputs inputs = null;
	if (query.Variables != null)
	{ 
		var variables = query.Variables as Newtonsoft.Json.Linq.JObject;
		var values = GetValue(variables) as Dictionary<string, object>;
		inputs = new Inputs(values);
	}
	...
	...
	var result = await ExecuteQuery((Schema)_schema, queryToExecute, null, query.OperationName, inputs);
	...
	...
}

private static object GetValue(object value)
{
	// Copied from https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L80
	...
	...
}
```

Thanks a bunch @joemcbride
We're huge fans over here ^_^

**Comment by ZenSoftware** [comment]
It should be mentioned that those that require approaching constructing `Inputs` in this method should ensure that it was still parsed with the following `JsonSerializerSettings`:
```
JsonSerializerSettings
{
	DateFormatHandling = DateFormatHandling.IsoDateFormat
});
```

A simple pattern to ensure this is to do something akin to:

private static HttpConfiguration config;
static GraphQLController()
{
	config = new HttpConfiguration();
	config.Formatters.JsonFormatter.SerializerSettings.DateFormatHandling = DateFormatHandling.IsoDateFormat;
	config.Formatters.JsonFormatter.UseDataContractJsonSerializer = false;
}

public async Task<HttpResponseMessage> PostAsync(GraphQLQuery query)
{
	...
	...
	var response = Request.CreateResponse(httpResult, config);
	response.Content = new StringContent(json, Encoding.UTF8, "application/json");
	return response;
}

**Comment by joemcbride** [comment]
👍  Glad you were able to figure it out!  I believe once upon a time that function was public though looks like it got moved to private.  I would be fine with making it public once again.

**Comment by jbaxleyiii** [comment]
@ZenSoftware this saved my bacon! Thank you so much!

**Comment by ashleydw** [comment]
@ZenSoftware Did you make the PR to make the function public?

**Comment by joemcbride** [comment]
@ashleydw I don't believe so, no.

**Comment by joemcbride** [comment]
The helper methods are public once again in 0.14.7.  Let me know if that helps!

**Comment by codepunkt** [comment]
@joemcbride @jbaxleyiii @ZenSoftware 

I either had the same problem, or a very similar one.
Whenever i sent variables, Post Endpoint responded with 500 (System.NullReferenceException, Object reference not set to an instance of an object) because `query.Variables` is `null` and therefore `ToInputs()` can not be called.

The `variables` part of the request body sent to the endpoint is `"variables":{"id":"2"}`

When i change Variables to `public object Variables { get; set ; }` and use the code posted by @ZenSoftware, things work as they should. I'm using Web API on .NET Framework 4.6.2 - no other fancy stuff. I'm glad this solution works, but i'm confused why this even happens.

Can someone shed light on this?
