### ISSUE TITLE
Enum case is UPPERCASE in 4.x

### ISSUE THREAD

**Issue by adityavaish** [graphql-dotnet/graphql-dotnet#2493]
## Description

With update to 4.x the enum is now always returned as UPPERCASE. This is a break from 3.x as it was returning PascalCase.

C#
```
public enum Type {
    Standard,
    Generic
}
```

The returned value now is always UPPERCASE
```
{
    "type": "STANDARD"
}
```

### Steps to reproduce

Create PascalCase enum in C# and use schema first to define enum.

### Expected result

It should honor case that's in C# and not change to UPPERCASE

### Actual result

This was correct in 3.x

**Comment by Shane32** [comment]
Code-first? Schema-first? Can you supply a code sample?  As far as I know, schema-first maintains the case specified in the schema, and code-first has always changed to uppercase -- but perhaps I am wrong.  Either way, you can configure this rather easily.

**Comment by Shane32** [comment]
It should have been the same....

Version 3:

https://github.com/graphql-dotnet/graphql-dotnet/blob/2b927188a23d94402e88a512feb1a5465717a7a1/src/GraphQL/Types/Scalars/EnumerationGraphType.cs#L131

Version 4:

https://github.com/graphql-dotnet/graphql-dotnet/blob/488feff4c9ef0acd86c288747c0688c6142252d4/src/GraphQL/Types/Scalars/EnumerationGraphType.cs#L161

**Comment by Shane32** [comment]
A code-first workaround would probably be something like this:

```cs
public class PascalEnumerationGraphType<T> : EnumerationGraphType<T>
{
    protected override string ChangeEnumCase(string val) => val;
}

public class MyEnumGraphType : PascalEnumerationGraphType<MyEnum> { }
```

**Comment by adityavaish** [comment]
My case was schema first. The behavior was not to be *always uppercase* in 3.x

Here is the workaround I did

```
public class EnumGraphTypePreserveCase<TEnum> : EnumerationGraphType<TEnum>
        where TEnum : Enum
    {
        protected override string ChangeEnumCase(string val)
        {
            return val;
        }
    }
```

This preserves casing

**Comment by adityavaish** [comment]
> A code-first workaround would probably be something like this:
> 
> ```cs
> public class PascalEnumerationGraphType<T> : EnumerationGraphType<T>
> {
>     protected override string ChangeEnumCase(string val) => val;
> }
> 
> public class MyEnumGraphType : PascalEnumerationGraphType<MyEnum> { }
> ```

yes, this worked. Although shouldn't we just preserve enum case instead of making it uppercase (by default)?

**Comment by Shane32** [comment]
The GraphQL spec recommends (but does not mandate) that enumeration values are uppercase. 

https://spec.graphql.org/June2018/#sec-Enum-Value
