### ISSUE TITLE
Could not load type GraphQL.DataLoader.IDataLoaderContextAccessor

### ISSUE THREAD

**Issue by jeffrfinn** [graphql-dotnet/graphql-dotnet#2494]
## Description

Dataloader is breaking because the IDataLoaderContextAccessor can't be loaded in the Startup.cs in a .Net core 3.1 app
### Steps to reproduce

I am trying to add Dataloader to my application. I had it working in a project but I upgraded packages and now I get an exception on the application startup.

I reproduced the issue in a [simple application](https://github.com/jeffrfinn/GraphQLNetSample)

### Expected result
The Dataloader should be loaded and the application should startup.

### Actual result
I get this unhandled exception on the application startup.

`System.TypeLoadException: Could not load type 'GraphQL.DataLoader.IDataLoaderContextAccessor' from assembly 'GraphQL, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null'.
   at GraphQL.Server.GraphQLBuilderExtensions.AddDataLoader(IGraphQLBuilder builder)
   at GraphQLNetSample.Startup.ConfigureServices(IServiceCollection services) in C:\Code\Temp\GraphQLNetSample\GraphQLNetSample\GraphQLNetSample\Startup.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at GraphQLNetSample.Program.Main(String[] args) in C:\Code\Temp\GraphQLNetSample\GraphQLNetSample\GraphQLNetSample\Program.cs:line 16`
### Environment

<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="graphiql" Version="2.0.0" />
      <PackageReference Include="GraphQL.DataLoader" Version="4.2.0" />
      <PackageReference Include="GraphQL.Server.Core" Version="4.4.0" />
      <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="4.4.0" />
      <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="4.4.0" />
      <PackageReference Include="GraphQL.Server.Transports.Subscriptions.Abstractions" Version="4.4.0" />
      <PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="4.4.0" />
      <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="4.4.0" />
    </ItemGroup>

</Project>

**Comment by Shane32** [comment]
GraphQL.Server 4.x is not compatible with GraphQL 4.x.   You need to use GraphQL.Server 5.x for GraphQL 4.x

However, the data loader is included with GraphQL 3.x (GraphQL Server 4.x) and is included within the library so you don't need to import another package reference.

**Comment by Shane32** [comment]
Also, GraphQL.Server 5.x includes a reference to GraphQL.DataLoader, so you still don't need another reference.

GraphQL Server 4.x with GraphQL 3.x:

```
<ItemGroup>
  <PackageReference Include="graphiql" Version="2.0.0" />
  <PackageReference Include="GraphQL.Server.Core" Version="4.4.0" />
  <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="4.4.0" />
  <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="4.4.0" />
  <PackageReference Include="GraphQL.Server.Transports.Subscriptions.Abstractions" Version="4.4.0" />
  <PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="4.4.0" />
  <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="4.4.0" />
</ItemGroup>
```

GraphQL Server 5.x with GraphQL 4.x:

```
<ItemGroup>
  <PackageReference Include="graphiql" Version="2.0.0" />
  <PackageReference Include="GraphQL.Server.Core" Version="5.0.1" />
  <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="5.0.1" />
  <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="4.4.0" />
  <PackageReference Include="GraphQL.Server.Transports.Subscriptions.Abstractions" Version="5.0.1" />
  <PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="5.0.1" />
  <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="5.0.1" />
</ItemGroup>
```

**Comment by jeffrfinn** [comment]
Cheers, thanks for the reply I'll update to v5 on both. Are there any issues with the upgrade path? The reason I was holding off v5 was that there weren't any documented steps yet

**Comment by Shane32** [comment]
Here is the migration guide from GraphQL 3.x to 4.x, which would apply when upgrading server from 4.x to 5.x.  I'm not sure if the server library itself has a migration guide, but the differences should be minimal there.

https://graphql-dotnet.github.io/docs/migrations/migration4

**Comment by Shane32** [comment]
@sungam3r Perhaps for GraphQL 5.x we can unify the major version numbers between it and the server project -- for example, skipping version 5 and going to v6 with both projects.

**Comment by jeffrfinn** [comment]
thanks, for the help. I can confirm it works. I will agree that "GraphQL.Server 4.x is not compatible with GraphQL 4.x. " isn't the most intuitive. I might have missed it in the docs, but I didn't consider it. 

I'll close the issue now.

**Comment by sungam3r** [comment]
> for example, skipping version 5 and going to v6 with both projects.

What if I want to publish server v7 soon (v8, v9...)? Should GraphQL.NET version also be bumped to v7 without any breaking changes ?

**Comment by Shane32** [comment]
We can cross that bridge when we come to it.  We do not seem to have a lack of breaking changes we wish to make lol.

If I had to answer now, I would say no, v6 & v7 would both use v6 of GraphQL.  v7 of GraphQL would be skipped.  As it is necessary for the server project to increment a major version whenever GraphQL's major version changes, they would both flip to v8 in tandem.
