### ISSUE TITLE
Test Graphql types to ViewModels mapping

### ISSUE THREAD

**Issue by Vidzhel** [graphql-dotnet/graphql-dotnet#2499]
## Summary
Would you mind suggesting ways I can unit test view graph types to view models mapping? Maybe it's overkill, and I don't need to? I really like how easy it is to unit test auto mapper models.

## Relevant information

The way I validate AutoMapper:
```c#
public MappingTests() {
            _configuration = new MapperConfiguration(cfg => { cfg.AddProfile<MappingProfile>(); });

            _mapper = _configuration.CreateMapper();
        }

        [Test]
        public void ShouldHaveValidConfiguration() {
            _configuration.AssertConfigurationIsValid();
        }

        /// <summary>
        /// Tests all implementations of <seealso cref="IMapFrom{TSource}"/>
        /// </summary>
        [Test]
        public void ShouldSupportMappingFromSourceToDestination() {
            var mapFromTypes = typeof(DependencyInjection).Assembly.GetExportedTypes()
                .Where(t => t.HasParentOfType(typeof(IMapFrom<>), true));

            foreach (var destinationType in mapFromTypes) {
                var sourceType = destinationType.GetParentOfType(typeof(IMapFrom<>), true)
                    !.GetGenericArguments()[0];
                var instance = GetInstanceOf(sourceType);
                _mapper.Map(instance, sourceType, destinationType);
            }
        }
```

**Comment by sungam3r** [comment]
What do you want to test? GraphType does not have to accurately have the same fields/properties as ViewModel, if you mean Source object, passed in resolver.

**Comment by Vidzhel** [comment]
Heah, I understand, but if we exclude fields that use resolver, we end up with these that just convert values from GraphType DTO to other classes' fields and in the case when you have to manually specify a field type (not to mention a field name), it becomes error-prone. 

Probably one possible solution to my problem is just integration testing, which I'm rewriting right now to use GraphQl queries instead of constructing commands passing GraphQl layer (I use MediatR).

Anyway, I haven't seen any material regarding the subject, so maybe the thread will help others

**Comment by sungam3r** [comment]
I think that it's more important to test public GraphQL API than some internal mappings. GraphQL has introspection capability so your test client could verify actual results.
