### ISSUE TITLE
DecimalGraphType cannot be used on inputs

### ISSUE THREAD

**Issue by LasseNisted** [graphql-dotnet/graphql-dotnet#251]
An InputObjectGraphType with a DecimalGraphType field fails in the
GraphQLExtensions.AstFromValue method which does not have a case for decimal values.

**Comment by joemcbride** [comment]
The fix for this looks like is more complicated than I thought.  Not sure how to "properly" fix it yet.  Thanks for the report!

**Comment by ManuelDeLeon** [comment]
We solved this problem by adding a `DecimalValue` to IntValue.cs and a decimal check in GraphQLExtensions.cs

IntValue.cs:
```csharp
    public class DecimalValue : AbstractNode, IValue 
    { 
        public DecimalValue(decimal value) 
        { 
            Value = value; 
        } 
 
        public decimal Value { get; } 
 
        public override string ToString() 
        { 
            return "DecimalValue{{value={0}}}".ToFormat(Value); 
        } 
 
        protected bool Equals(DecimalValue other) 
        { 
            return Value == other.Value; 
        } 
 
        public override bool IsEqualTo(INode obj) 
        { 
            if (ReferenceEquals(null, obj)) return false; 
            if (ReferenceEquals(this, obj)) return true; 
            if (obj.GetType() != this.GetType()) return false; 
            return Equals((DecimalValue)obj); 
        } 
    } 
```

GraphQLExtensions.cs (in `AstFromValue`)
```csharp
            if (serialized is decimal) 
            { 
                return new DecimalValue((decimal)serialized); 
            } 
```

Is there a problem with this solution?

**Comment by joemcbride** [comment]
> Is there a problem with this solution?

Only in that there is no `DecimalValue` in the spec only `FloatValue`.  So that starts to muddy the waters, which we've kind of already done with `LongValue`.  We can probably add `DecimalValue` in the short term.  Long term I would like to provide hooks so that anyone who wants to add custom scalar types could override these behaviors.

**Comment by ManuelDeLeon** [comment]
> Long term I would like to provide hooks so that anyone who wants to add custom scalar types could override these behaviors.

That's an interesting idea. I dig it for custom types but I wonder about types native to .Net (like decimal). The target audience here are .Net developers so would it really make sense to declare "Types that translate to the GraphQL spec are handled out of the box. For the rest of the .Net types use this separate library (or turn on this flag)"?

> We can probably add DecimalValue in the short term. 

Want a PR?

**Comment by joemcbride** [comment]
> "Types that translate to the GraphQL spec are handled out of the box. For the rest of the .Net types use this separate library (or turn on this flag)"?

That has kind of been the thinking from the start.  We've just hit a few of these types of "bugs" so far so it would be nice if even these "core" types were just pluggable.  Turned "on" by default but still just pluggable.

> Want a PR?

Sure thing!

**Comment by ManuelDeLeon** [comment]
Cool. PR sent.

btw, if some poor soul reading this is having trouble opening this repo on Visual Studio (getting "dotnet-projectmodel-server unable to start"). Make sure you haven't installed one of the .Net Core Toolset **Preview 3 or 4** By default it grabs the highest (incompatible) version.

**Comment by joemcbride** [comment]
Fix published in https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.14.6.657
