### ISSUE TITLE
Azure functions v3, .Net Core 5 : Variable '$dish' is invalid. Unable to parse input as a 'DishInputType' type. Did you provide a List or Scalar value accidentally?

### ISSUE THREAD

**Issue by tsansome** [graphql-dotnet/graphql-dotnet#2510]
## Description
I'm trying to get my mutations working but always prompted with this error. Can't seem to find what's wrong.

> Variable '$dish' is invalid. Unable to parse input as a 'DishInputType' type. Did you provide a List or Scalar value accidentally?

Any suggestions? I've breakpointed and checked that it definitely parses to the ~~Dictionary<string, object> and object is a JObject.~~
```
System.Collections.Generic.Dictionary`2[System.String,System.Object]
```

### Steps to reproduce

Clear steps describing how to reproduce the issue.

Using Postman v7.36.5. Send the Http Post request with JSON as content type to trigger my mutation to create a new dish.

```
{
  "query": "mutation ($dish:DishInputType!){ createDish(dish: $dish) { name} }",
  "variables": {
    "dish": {
        "name": "Pad See Ew Chicken"
    }
  }
}
```

### Actual result
Doesn't enter into resolver but instead states error
"Variable '$dish' is invalid. Unable to parse input as a 'DishInputType' type. Did you provide a List or Scalar value accidentally?"

### Environment
Azure functions v3
.Net Core 5

other packages
```
<PackageReference Include="GraphQL" Version="4.2.0" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.12" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
    <PackageReference Include="SqlKata" Version="2.3.2" />
    <PackageReference Include="SqlKata.Execution" Version="2.3.2" />
```

### Graphql main
```
var logger = executionContext.GetLogger("graphql");
            logger.LogInformation("C# HTTP trigger function processed a request.");

            var schema = new Schema { 
                Query = new Query(), 
                Mutation= new Mutation() };

            var request = await JsonSerializer.DeserializeAsync<GraphQLRequest>(req.Body, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        
            var executer = new DocumentExecuter();
            var result = await executer.ExecuteAsync(options =>
            {
                options.Schema = schema;
                options.Query = request.Query;
                options.Inputs = request.Variables?.ToInputs();
            });

            var response = req.CreateResponse(HttpStatusCode.OK);
            response.Headers.Add("Content-Type", "appplication/json; charset=utf-8");
            var writer = new GraphQL.SystemTextJson.DocumentWriter();
            await writer.WriteAsync(response.Body, result);

            return response;
```

#### Mutation resolver
```
public class Mutation : ObjectGraphType {
        public Mutation() {
            Name="Mutation";

            Field<DishType>(
            "createDish",
            arguments: new QueryArguments(
                new QueryArgument<NonNullGraphType<DishInputType>> {Name = "dish"}
            ),
            resolve: context =>
            {
                DishInput dish = context.GetArgument<DishInput>("dish"); 
                Dish dishToSave = new Dish();               
                dishToSave.submitted_by = Guid.Parse("ECD7FE44-1FC4-4DBE-9D54-2D98E194675F");
                var dishRet = Repository.sql().Query("Dish").AsInsert(dishToSave).Get<Dish>();
                return dishRet;
            });
        }
    }
```

#### DishInputType
```
public class DishInputType : InputObjectGraphType<DishInput>
    {
        public DishInputType()
        {
            Name = "DishInputType";
            Field<StringGraphType>("name");
        }
    }
```

#### Graphql Request class
```
public class GraphQLRequest
    {
        public string OperationName { get; set; }

        public string Query { get; set; }

        public Dictionary<string, object> Variables { get; set; }
    }
```

**Comment by Shane32** [comment]
> I've breakpointed and checked that it definitely parses to the `Dictionary<string, object>` and `object` is a `JObject`.

I'm pretty sure `JObject` is a `Newtonsoft.Json` type, not a `System.Text.Json` type, but I could be wrong.  I'm not sure exactly how that's possible from the code sample you've provided.  I'd check this breakpoint again and find out the full type definition of `JObject`.  If it's a Newtonsoft object, you probably need to find out how/why `Newtonsoft.Json` is involved with the deserialization if you're attempting to use `System.Text.Json`.

See: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0

**Comment by tsansome** [comment]
Apologies @Shane32 i have double checked it and it is actually
```
System.Collections.Generic.Dictionary`2[System.String,System.Object]
```
So with that not being the issue, any other ideas?

**Comment by Shane32** [comment]
So the dictionary value within the dictionary is also a dictionary? (It should be, just checking)

**Comment by Shane32** [comment]
Can you post a copy of the DishInput class?

**Comment by tsansome** [comment]
The object inside of the dictionary is actually:
```
"System.Text.Json.JsonElement"
```

As for the DishInput class its:
```
public class DishInput {
        public string name {get; set;}
}
```

**Comment by Shane32** [comment]
Ok that makes sense.  You need to specify the `ObjectDictionaryConverter` converter so that `System.Text.Json` will convert all of the inner objects into dictionaries rather than `JsonElement` objects.  Please review this code:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.SystemTextJson/StringExtensions.cs

Also since `System.Text.Json` does not support `BigInteger` you may need the `JsonConverterBigInteger` converter specified as well to support large integers.

**Comment by Shane32** [comment]
@sungam3r A few questions:

1. The `DocumentWriter.WriteAsync<T>` method allows you to write any type of data, automatically converting `ExecutionNode` objects appropriately.  Does it make sense to provide a helper method to read arbitrary data types, converting `Dictionary<string, object>` values appropriately for graphql variables?  For example:

```cs
public static T FromJson<T>(this string json)
    => JsonSerializer.Deserialize<T>(json, _jsonOptions);

public static T FromJsonAsync<T>(this IO.Stream json, CancellationToken cancellationToken = default)
    => JsonSerializer.DeserializeAsync<T>(json, _jsonOptions, cancellationToken);
```

Signature?  Perhaps it shouldn't be an extension method.

2. Would it make sense to provide an extension method for converting from a `JsonElement` to `Inputs`? For example:

```cs
public static Inputs ToInputs(this JsonElement jsonElement)
    => //not sure what goes here yet
```

To be used after clients deserialize json with this class:
```cs
public class GraphQLRequest
{
    public string OperationName { get; set; }
    public string Query { get; set; }
    public JsonElement Variables { get; set; }
}
```

Of course the same can be done for `Newtonsoft.Json`

3. Is there an appropriate place in the documentation where notes on serialization and deserialization should go?  FAQ?  Seems like it may be important enough to have its own page.

**Comment by sungam3r** [comment]
>  1. Does it make sense to provide a helper method to read arbitrary data types, converting Dictionary<string, object> values appropriately for graphql variables?

I think this is the client's task, not the server. The server writes an answer to the output stream, and does not read it. Maybe this is the issue for https://github.com/graphql-dotnet/graphql-client that also has serialization projects
![изображение](https://user-images.githubusercontent.com/21261007/115559179-226c3400-a2bc-11eb-982e-64866e074669.png)

2. The answer the same as for 1.
3. I see notes about serialization only in `errors.md` . Yes, serialization own page seems reasonable.

**Comment by Shane32** [comment]
Perhaps you misunderstood the scenario. This relates to deserializing variables and accompanying data (e.g. query) on the server prior to the request. I’m not talking about anything on the client side.

**Comment by sungam3r** [comment]
Variables are deserialized in server project. GraphQL.NET works with already specified (parsed) `Inputs`. I'm OK with adding new API in the server project. Now server project only reads from input stream (deserializes) and GraphQL.NET only writes (serializes) to output stream. Now the zones of responsibility are clear and I think it is good.

**Comment by Shane32** [comment]
We cannot expect that people always use the server project.  I do not use the server project.  Further, the `ObjectDictionaryConverter` is in the `GraphQL.SystemTextJson` project and only exists to assist deserializing JSON data for variables.  It is not used for serialization at all.  Even the server project relies on the `ObjectDictionaryConverter` in the `GraphQL.SystemTextJson` project to perform proper deserialization.

**Comment by Shane32** [comment]
```cs
        public GraphQLRequestDeserializer(Action<JsonSerializerOptions> configure)
        {
            // Add converter that deserializes Variables property
            _serializerOptions.Converters.Add(new ObjectDictionaryConverter());

            configure?.Invoke(_serializerOptions);
        }
```

**Comment by sungam3r** [comment]
> It is not used for serialization at all. Even the server project relies on the ObjectDictionaryConverter in the GraphQL.SystemTextJson project to perform proper deserialization.

I was wrong. Indeed both serialization projects from GraphQL.NET have helper methods for deserializing from json strings. I'm OK to add other helper methods.

**Comment by Shane32** [comment]
I would like to provide an extension to `JsonElement` called `ToInputs`.  But there is no way to do this without serializing the element and deserializing it again.  In the future this will be available via `JsonNode.Parse<T>`.  See: https://github.com/steveharter/designs/blob/6437453395619af937bf84a60c13d1bc43d7ca05/accepted/2020/serializer/WriteableDomAndDynamic.md#api-walkthrough

So I will add other helper methods as noted above.  Please comment here or on my PR if you have any suggestions as to naming.  I'll be adding more documentation in the future.

**Comment by Shane32** [comment]
Closing.  The current version of GraphQL.NET includes the following extension methods:

```cs
// for Newtonsoft.Json
public static Inputs ToInputs(this JObject obj) { }

// for System.Text.Json
public static Inputs ToInputs(this JsonElement obj) { }
```
