### ISSUE TITLE
Subscription not working

### ISSUE THREAD

**Issue by tuphampro** [graphql-dotnet/graphql-dotnet#2511]
I am using .NET 5.0 for GraphQL (v4.3.0)
Error when Subscriptions:

![ảnh](https://user-images.githubusercontent.com/19162524/115192237-be5b3b80-a114-11eb-981d-bf3ff7faad93.png)
![ảnh](https://user-images.githubusercontent.com/19162524/115192316-d6cb5600-a114-11eb-9959-1f6e299dcbd4.png)

**Comment by sungam3r** [comment]
Could you provide more logs from server?

**Comment by tuphampro** [comment]
It don't have any logs. You can create a new project to see.

**Comment by sungam3r** [comment]
To see what exactly? There are some test projects in this repo. Tests passed. I can’t help you without any information about the error.

**Comment by Jonatthu** [comment]
```
{
  "error": {
    "message": "GraphQL.Execution.UnhandledError: Error executing document.\n ---> System.NotSupportedException: DocumentExecuter does not support executing subscriptions. You can use SubscriptionDocumentExecuter from GraphQL.SystemReactive package to handle subscriptions.\n   at GraphQL.DocumentExecuter.SelectExecutionStrategy(ExecutionContext context) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 304\n   at GraphQL.DocumentExecuter.BuildExecutionContext(ExecutionOptions options, Document document, Operation operation, Variables variables, Metrics metrics) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 270\n   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 142\n   --- End of inner exception stack trace ---",
    "extensions": {
      "code": "NOT_SUPPORTED",
      "codes": [
        "NOT_SUPPORTED"
      ]
    }
  }
}
```

@sungam3r Do you know why this could be happening?

**Comment by Shane32** [comment]
In version 4.x of GraphQL.NET, the default document executed does not support subscriptions. You need to import the GraphQL.SystemReactive nuget package and use or inherit the SubscriptionDocumentExecuter instead.
