### ISSUE TITLE
How to add proper error handling in the GraphQL middleware?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2524]
I have a simple `GraphQL` example working fine. I am trying to understand on how to add proper error handling and logging.

Below is my `TitanQuery` code:

    public class TitanQuery : ObjectGraphType<object>
    {
        public TitanQuery(....)
        {
            Name = "Query";

            FieldAsync<ListGraphType<ContentResponseType>>(
                "contentRequest",
                arguments: new QueryArguments(
                        new QueryArgument<NonNullGraphType<IntGraphType>>
                        {
                            Name = "clientId",
                            Description = "Client Id of the request"

                        },
                        new QueryArgument<ListGraphType<FilterType>>
                        {
                            Name = "filters",
                            Description = "Filters"
                        },
                        new QueryArgument<StringGraphType>
                        {
                            Name = "clientKey",
                            DefaultValue = "abc",
                            Description = "some stuff"
                        }
                    ),

                resolve: async context =>
                {
                    var clientId = context.GetArgument<int>("clientId");
                    var filters = context.GetArgument<List<Filter>>("filters");
                    var clientKey = context.GetArgument<string>("clientKey");

                    // mapping all the arguments to ProcessRequest class
                    ProcessRequest processRequest = new ProcessRequest()
                    {
                        ClientId = clientId,
                        Filters = filters,
                        ClientType = new ClientType()
                        {
                            ClientKey = clientKey
                        },
                        ProtoRequest = new ProtoRequest()
                    };

                    // below line returns 'ProcessResponse' object by using 'processRequest' object
                    var processResponse = await metadataService.ProcessData(processRequest);

                    var dataGroups = processResponse.LandingResponse.DataGroups.Select(dataGroup => new LandingGroup
                    {
                        DataGroup = dataGroup,
                        TileContext = processResponse.TileContext
                    });

                    return dataGroups;
                }
            );
        }
    }

In my above code if `metadataService.ProcessData` throws exception then how can I handle it so that I can log it properly and also give correct information back to user in the GraphQL UI. I know I can add a try catch there to log it but is there anything I can do in my middleware? This is what I have in my middleware as of now - 

    private async Task ExecuteAsync(HttpContext context, ISchema schema)
    {
        var request = Deserialize<GraphQLRequest>(context.Request.Body);
        var result = await _executer.ExecuteAsync(_ =>
        {
            _.Schema = schema;
            _.Query = request?.Query;
            _.OperationName = request?.OperationName;
            _.Inputs = request?.Variables.ToInputs();
            _.UserContext = _settings.BuildUserContext?.Invoke(context);
            _.ValidationRules = DocumentValidator.CoreRules.Concat(new[] { new InputValidationRule() });
            _.EnableMetrics = _settings.EnableMetrics;
            if (_settings.EnableMetrics)
            {
                _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
            }
        });
        await WriteResponseAsync(context, result);
    }

    // write response object and return to the user
    // how can I modify this method to take Exception as the input parameters as well.
    // Is there any way to pass exception object from "ExecuteAsync" method to here?
    private async Task WriteResponseAsync(HttpContext context, ExecutionResult result)
    {
        context.Response.ContentType = "application/json";
        context.Response.StatusCode = result.Errors?.Any() == true ? (int)HttpStatusCode.BadRequest : (int)HttpStatusCode.OK;

        await _writer.WriteAsync(context.Response.Body, result);
    }

I want to add a logic where I can interpret what kind of exception is being thrown and basis on that log it and return back to the caller with detailed message. Basically I want to add below exception handling logic somewhere in my above code. 

My below code look at what exception is being thrown and basis on that does all sort of manipulation and then log it and also make a generic object that can be return to the user. Here `HtttpContext` in my below code is of type `Microsoft.AspNetCore.Http.HttpContext`

    public async Task HandleException(HttpContext context, Exception ex)
    {
        var error = ex.Source;
        var message = ex.Message;
        var stackTrace = ex.StackTrace;
        switch (ex)
        {
            case ExceptionType1 e1:
                // do some stuff
                break;
            case ExceptionType2 e2:
                // do some stuff
                break;
        }

        // log exception here with above details

        context.Response.StatusCode = statusCode;
        context.Response.ContentType = "application/json";

        // make an object
        var exceptionInfo = new ExceptionInfo();
        exceptionInfo.ExceptionMessage = message;
        exceptionInfo.ExceptionSource = title;

        var exceptionContainer = new ExceptionContainer();
        exceptionContainer.ExceptionInfo = exceptionInfo;

        // this can be replaced with GraphQL "_writer.WriteAsync" line if I am not wrong
        Utf8Json.JsonSerializer.SerializeAsync(context.Response.Body, exceptionContainer, Utf8Json.Resolvers.StandardResolver.ExcludeNullCamelCase);
    }

How can I modify `WriteResponseAsync` method in my middleware to take exception as the input parameters as well? And then I can add the above method logic in it. Is this possible to do by any chance?

Do I need to wrap `var result = await _executer.ExecuteAsync(_ => ...` block inside try catch block and then use the exception object and handle it accordingly or is there any other option?

**Comment by sungam3r** [comment]
>  context.Response.StatusCode = result.Errors?.Any() == true ? (int)HttpStatusCode.BadRequest : (int)HttpStatusCode.OK;

See https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#status-codes

**Comment by TechGeeky** [comment]
@sungam3r  I saw that but it doesn't mention on how to handle `Exception`  coming after executing the request if there are any issues with the request. 

I want to log error message properly by analyzing `Exception` object and also set different status code in the `context` after analyzing what exception was thrown instead of just using two status code 400 and 200.

Basically I want to do what my `HandleException` method is doing? But I am confuse on how to get `Exception` object in my GraphQL middleware.

**Comment by TechGeeky** [comment]
I believe I found a way [here](https://graphql-dotnet.github.io/docs/getting-started/errors/) by using `UnhandledExceptionDelegate` as shown below in my `ExecuteAsync` method.

My idea is - 

- If the response is successful then send 200 status code back along with correct data.
- If the response isn't successful then log the actual error, send error message back to user and send correct status code back to the user (instead of sending 400 Bad Request one which was there in my original code).

I modified my `ExecuteAsync` to use `UnhandledExceptionDelegate` which calls `HandleException` method to analyze any errors and then log it and also assign correct error status code to `HttpContext`. 

Similarly I modified `WriteResponseAsync` method accordingly to set `200` status code if there are no errors. My question is - Is this the right way to do all these or is there any better option here?

    private async Task ExecuteAsync(HttpContext context, ISchema schema)
    {
        var request = Deserialize<GraphQLRequest>(context.Request.Body);
        var result = await _executer.ExecuteAsync(_ =>
        {
            _.Schema = schema;
            _.Query = request?.Query;
            _.OperationName = request?.OperationName;
            _.Inputs = request?.Variables.ToInputs();
            _.UserContext = _settings.BuildUserContext?.Invoke(context);
            _.ValidationRules = DocumentValidator.CoreRules.Concat(new[] { new InputValidationRule() });
            _.EnableMetrics = _settings.EnableMetrics;
            if (_settings.EnableMetrics)
            {
                _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
            }
            _.UnhandledExceptionDelegate = async ctx =>
            {
                await HandleException(context, ctx.Exception);
            };
        });
        await WriteResponseAsync(context, result);
    }

    private async Task WriteResponseAsync(HttpContext context, ExecutionResult result)
    {
        context.Response.ContentType = "application/json";
        if (result.Errors?.Any() == false)
            context.Response.StatusCode = (int) HttpStatusCode.OK;
        // context.Response.StatusCode = result.Errors?.Any() == true ? (int)HttpStatusCode.BadRequest : (int)HttpStatusCode.OK;
        await _writer.WriteAsync(context.Response.Body, result);
    }

    public async Task HandleException(HttpContext context, Exception ex)
    {
        int statusCode;
        var error = ex.Source;
        var message = ex.Message;
        var stackTrace = ex.StackTrace;
        switch (ex)
        {
            case ExceptionType1 e1:
                // do some stuff
                statusCode = e1.StatusCode
                break;
            case ExceptionType2 e2:
                // do some stuff
                statusCode = e2.StatusCode
                break;
        }

        // log exception here with above details like error, message, statuscode and stacktrace.
        // set error status code
        context.Response.StatusCode = statusCode;
    }
