### ISSUE TITLE
Is there equivalent of buildClientSchema in graphql-dotnet

### ISSUE THREAD

**Issue by azaslonov** [graphql-dotnet/graphql-dotnet#2528]
## Summary
Hi everyone, I'm looking a way to convert the result of the introspection query into a schema document, probably similar to what there is in graphql-js: https://graphql.org/graphql-js/utilities/#buildclientschema

The idea is to fetch the whole GraphQL type system and save it into document:
```
type Type 1 {
  ...
}

type Type2 {
  ...
}

type Query1 {
  ...
}
```

Any help greatly appreciated.

**Comment by Shane32** [comment]
There's a `SchemaPrinter` class which may suit your needs.

```cs
var printer = new SchemaPrinter(schema);
var ret = printer.Print();
```

**Comment by sungam3r** [comment]
If you are talking about converting from introspection to SDL on client side then see https://github.com/sungam3r/graphql-introspection-model and https://github.com/sungam3r/graphql-sdl-exporter .

**Comment by sungam3r** [comment]
Example https://github.com/sungam3r/graphql-introspection-model/blob/af1a38be468016b122b19e996f69d0e328c45978/src/GraphQL.IntrospectionModel.Tests/SDLBuilderTests.cs#L17

**Comment by azaslonov** [comment]
Looks like exactly what I need, thanks a lot, I really appreciate it!
