### ISSUE TITLE
Complex input types would benefit from a generic InputObjectGraphType class

### ISSUE THREAD

**Issue by LasseNisted** [graphql-dotnet/graphql-dotnet#253]
Complex input types currently cannot utilize the the TSourceType type argument of ComplexGraphType since InputObjectGraphType passes object as the TSourceType. Would it be possible to introduce a InputObjetGraphType<TSourceType>? 
Then complex fields in the input type can use the ResolveFieldContext.Source argument without casting in Resolve-definitions for fields.

**Comment by joemcbride** [comment]
I'm not sure that I'm following what you're asking for.

`InputObjectGraphType` is used with arguments, not with the Source type.  They are not related.  I don't see that an `InputObjectGraphType<T>` would be helpful other than generating the fields for you.  You can access the arguments via `context => context.GetArgument<MyClass>("argName")` which gives you a concrete `MyClass` class.

Is there something I'm missing?  Can you provide a code example of what issue you're having?

**Comment by LasseNisted** [comment]
I think you are right. Based on your response I looked into all .Resolve-calls on builders for inputs and none of them seem necessary. Thanks!

**Comment by EniOnGit** [comment]
Hello @joemcbride 

> I don't see that an `InputObjectGraphType<T>` would be helpful other than generating the fields for you.

IMHO: The possibility to declare typed properties, would be helpfull to prevent errors during conversion from the `InputObjectGraphType` to  `MyClass `.

Usage of the `InputObjectGraphType`:
```c#
public class MyQuery : ObjectGraphType 
{
  public MyQuery()
  {
  Field<ListGraphType<DataPointType>>("datapoints", "Get all datapoints.",
    arguments: new QueryArguments(
       new QueryArgument<ValueRangeType>() { Name = "ValueRange"}
    ),
     resolve: context =>
        {
        var myClass= context.GetArgument<MyClass>("ValueRange"); 
        // using myClass
        }
    );
  }
}
````

Input type Declaration: 
```c#
 public class ValueRangeType : InputObjectGraphType
    {
        public ValueRangeType()
        {
            Field<FloatGraphType>(name: "to", description: "maximal value");
            Field<FloatGraphType>(name: "from", description: "minimal value");
        }        
    }
```

Declaration of my MyClass:

```c#
public class MyClass 
{
        public double? From { set; get; }
        public double? To { set; get; }
   ...
}
```

To declare the properties, i have to name them by strings and they have to be equivalent to the MyClass declaration. In case of renaming a property of MyClass, i don't get a hint from the compiler, because of the untyped property declaration. 

Can this issue be solved by making the InputObjectGraphType generic?

**Comment by joemcbride** [comment]
> Can this issue be solved by making the InputObjectGraphType generic?

Yes that can.   My previous comment was to point out that the Source was not related to the Arguments.  Taking your code example that would be `InputObjectGraphType<IEnumerable<DataPoint>>`, or something like that, if it used the Source. Which is highly unlikely what someone would want.
