### ISSUE TITLE
Best Practices - Form mutation validation

### ISSUE THREAD

**Issue by sarahannnicholson** [graphql-dotnet/graphql-dotnet#2534]
## Summary
There seems to be many ways to validate graphql fields/mutations. You could use Field Validation, directives, or even custom validators. I am curious if you have a mutation that accepts an argument from form input fields, what is the best practice to validate these argument input type properties? 

## Relevant information
If I assume FieldMiddleware is the Best Practice here, I cannot seem to get a working version with my own custom Middleware. 

I currently don't have hot chocolate or any middleware installed in my API and the GraphQL .net docs code for Field Validation does not work. I'm using an IIS Express server to host. 

```
    public class MySchema: Schema
    {
        public MySchema(
            IServiceProvider provider,
            MyMiddlewareClass middleware
            ) : base(provider)
        {
            Query = provider.GetRequiredService<MyQuery>();
            Mutation = provider.GetRequiredService<MyMutations>();

            FieldMiddleware.Use(middleware);
        }
    }
```
![image](https://user-images.githubusercontent.com/10520771/117085884-e85d5200-acff-11eb-847e-27f92c831a15.png)

FieldMiddleware doesn't seem to be part of the schema. 

**Ultimately, I would like to know:**
1. If you have a mutation that accepts form input fields, what is the best practice to validate these fields?
2. Is FieldMiddleware supported in graphql.net 4.4.1? Or do I need to use Hot Chocolate for support?

### Environment (if relevant)
C3 .net core 2.1?
Only Nuget packages installed:
https://www.nuget.org/packages/GraphQL.Server.Core/4.4.1
https://www.nuget.org/packages/GraphQL.Server.Transports.AspNetCore.SystemTextJson/4.4.1
https://www.nuget.org/packages/GraphQL.Server.Ui.Playground/4.4.1

### Resources Read 
[Field Middleware Docs](https://graphql-dotnet.github.io/docs/getting-started/field-middleware)
[Directives Docs](https://graphql-dotnet.github.io/docs/getting-started/directives)
[graphql-dotnet Github](https://github.com/graphql-dotnet/graphql-dotnet)
[Instrumentation Example](https://github.com/graphql-dotnet/graphql-dotnet/tree/473378c6301332cff6abbfaad4e576280c4e312d/src/GraphQL/Instrumentation)
[Validation on query](https://github.com/graphql-dotnet/graphql-dotnet/issues/694)
[Malicious Queries Docs](https://graphql-dotnet.github.io/docs/getting-started/malicious-queries)

**Comment by Shane32** [comment]
Your references are for GraphQL Server 4.x, which uses GraphQL.NET 3.x. If you’re reading the current docs, they are for GraphQL.NET 4.x, and you’ll need to use GraphQL Server 5.x.

**Comment by Shane32** [comment]
I wouldn’t use middleware to validate form fields or any other type of input. Middleware always applies to every field of every query & mutation. Since each mutation’s arguments probably has different requirements, it wouldn’t make sense to use middleware alone. You can add directives with accompanying middleware or validation rules, but I find it easiest to simply add code within the field resolver to validate the inputs.

**Comment by sungam3r** [comment]
Look at this [custom validation rule](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/Rules.Custom/InputFieldsAndArgumentsOfCorrectLength.cs) which uses `@length` directive to take information about requirements for inputs. The main question that you should answer is at what stage you will produce data validation, to the immediate execution of the query or after. Depending on this, the response should either have `data` field or not.

**Comment by sungam3r** [comment]
Closed as answered.
