### ISSUE TITLE
Is it possible for an interface to implement an interface?

### ISSUE THREAD

**Issue by NaveAF** [graphql-dotnet/graphql-dotnet#2545]
## Summary
Thanks to all the contributors on this project!
As asked in the title, Is it possible for an interface to implement another interface as is allowed on gql spec?

The gql spec RFC: https://github.com/graphql/graphql-spec/pull/373
Spec: http://spec.graphql.org/draft/#sec-Interfaces.Interfaces-Implementing-Interfaces

examples:
```
interface Node {
  id: ID!
}

interface Resource implements Node {
  id: ID!
  url: String
}

interface Image implements Resource & Node {
  id: ID!
  url: String
  thumbnail: String
}
```

```
interface Node implements Named & Node {
  id: ID!
  name: String
}

interface Named implements Node & Named {
  id: ID!
  name: String
}
```

If not, is this in the roadmap?

Thanks!

### Environment (if relevant)
graphql-dotnet v4.5
.net 5

**Comment by sungam3r** [comment]
See https://github.com/graphql-dotnet/parser/issues/57 and #1497 . Closing this issue as duplicate.
