### ISSUE TITLE
Extensions Property is missing in ExecutionOptions

### ISSUE THREAD

**Issue by Popeye4242** [graphql-dotnet/graphql-dotnet#2549]
## Description

Extensions Property is missing in ExectionOptions.

Background: When working with WebSockets you cannot work with Headers as they are set initially when the WebSocket connection is made only. Therefore it is required that I can use Extensions for sending extra variables that don't belong in the query variables (for example OpenTracing trace id). 

### Steps to reproduce

1. Implement a Custom `IDocumentExecutor` and inject it into `IServiceCollection`
2. Set `context.extensions` variable in Apollo client
3. `ExecutionOptions` are missing in the `ExecuteAsync` Method of the `IDocumentExecutor`. 
![image](https://user-images.githubusercontent.com/35311793/118770537-bf9d9680-b881-11eb-80ad-79a1cecbeffe.png)

### Expected result

3. `Extensions` property should be available in `ExecutionOptions`. 

### Actual result

They are not. They are being completely removed and inaccessible. Even tho they definitely make it to the server in the payload. 
### Environment

```		
<PackageReference Include="GraphQL.Conventions" Version="4.1.0" />
<PackageReference Include="GraphQL.Server.All" Version="5.0.2" />
```

**Comment by Shane32** [comment]
@sungam3r The feature request has merit; see `includeExtensions` property here: https://www.apollographql.com/docs/react/networking/advanced-http-networking/

The reasoning is sound also; when using websockets, extensions may be necessary to provide any other parameters to the server.

However, @Popeye4242, as it is implemented in this pull request, I do not see any way that user code can utilize the extensions property.  The extensions property would need to be added to `ExecutionContext`, and probably added to `IResolveFieldContext` as well.  We would need to be sure it is not confused with the output extensions property.  Documentation may need to be added as well.  Note that a change to `IResolveFieldContext` would be a breaking change and would need to be implemented in v5.  Breaking changes need notes added to the v5 migration document (which does not yet exist).

Now if the extensions are only used as 'headers', it does not belong within `ExecutionOptions` or `ExecutionContext` as `IDocumentExecutor` simply executes a given query.  But in accordance with the GraphQL spec, we support writing extensions within field resolvers (and middleware/etc), and I see no reason why a field resolver could not access input "extensions" as well.  The GraphQL spec does not provide guidance upon the format of the GraphQL request beyond the document itself, so there is no conflict.

I'm not sure exactly how it relates to the conventions project, but I would say that with a custom JSON parser you should be able to grab the extensions property and throw it in the `UserContext` property as a temporary patch until this feature can be added.

**Comment by Shane32** [comment]
@sungam3r I'd like to discuss proper implementation.  I do think Extensions should be able be read from the input as well as being written to the output of the json response.

**Comment by Shane32** [comment]
Completed in #2766
