### ISSUE TITLE
Manually assembling schema

### ISSUE THREAD

**Issue by ronnyek** [graphql-dotnet/graphql-dotnet#255]
So along the lines of the the other tools that sit on top of graphql-dotnet... and generate schema... is there currently a way to generate schema in a more dynamic way?

I see all the builder samples etc, but I'm simply trying to do something like this:

```
var schema = new Schema();
var query = new ObjectGraphType();
for(properties on object){
query.AddFieldWithInformationDerivedFromReflectedType.

```
I'm playing with the starwars apps in both your app as well as graphql-dotnet-annotations to better understand things... but I dont feel like I'm getting closer. My schemas I'm building and printing with schema printer arent getting closer. And even if they were 1:1, I'm not convinced I could get that schema actually wired up to a context or something.

I've been able to achieve some of this, but I don't really understand how to build out a hierarchy. I've looked through how some of the external libraries work, but they work heavily on generics. 

So maybe any of these questions answers could help.

1. Does schema literally only build out a heirarchy, and have zero to do with the fetching etc, or do I have to effectively make all the QueryRoot collections be a function?
2. Is there a mechanism for building our a hierarchy as things sit? I get how you could take a ObjectGraphType, and .Field<someType>(), but does that actually add a field to the objectgraphtype?

Is it possible to get a really simple example of building say a sample schema for zoo or something
```
Zoo
- Animals
--Cats
--Dogs
-Employees

```

  I appreciate the response, and apologize for any frustration

**Comment by tlil87** [comment]
Have you had a look at the [Conventions](https://github.com/graphql-dotnet/conventions) library (which builds on top of [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet))? There's an example [here](https://github.com/graphql-dotnet/conventions/blob/master/test/GraphQL.Conventions.Tests.Server/Schema/Query.cs).

**Comment by ronnyek** [comment]
Ok, so I've already found valuable stuff here that will help elsewhere, but my point is I don't have classes that inherit from some ObjectGraphType.  So I need to be able to say generate the equivalent of marking an arbitrary class up with ObjectGraphType dynamically. Because I'm iterating through properties, generics will likely not work unless the methods were setup with type inference. Looks like some of the derivation tests might have an example how to achieve what I'm after. I'm gonna continue to dig through that after writing this up, so if it becomes glaringly obvious I'll update this.

Better example would be Starwars since everyone uses that for examples in graphql.

Pseudo Code for basically iterating my repository which can be marked up with my own custom attributes. Maybe graphql-dotnet was not at all designed to work this way, and thus my difficulty.+

```
[GraphQlEnabled("Droids")] //think this should just generate another object that has maybe AllDroids?
public class DroidRepository{
...
}

[GraphQlObject] //should theoretically just pull properties off into derived types
public class Droid{
...
}

var query = new ObjectGraphType(); // create root level element

//make sure schema understand what a droid is vs a human
assemblies.GetTypes()
.Where(x=>x.GetCustomAttribute<GraphQlObjectAttribute>()!=null)
.ForEach(t=>query.AddDerivedType);

assemblies.GetTypes()
.Where(x=>x.GetCustomAttribute<GraphQlEnabledAttribute>()!=null)
.ForEach(t=>query.AddTopLevelPropertyThatGetsMethodsAndPropertiesFor(t))

return query;

```

**Comment by tlil87** [comment]
@ronnyek i don't follow i'm afraid. so, with the Conventions library your object doesn't need to inherit from `ObjectGraphType`, you could implement something like this for example:

```cs
class Query
{
       public Droid GetDroid(string id) => _myRepository.GetDroidById(id);
}

class Droid // existing DTO
{
    public string Id { get; set; }

    public string Name { get; set; }

   // ...
}

var engine = new GraphQLEngine();
engine.BuildSchema(typeof(SchemaDefinition<Query>));
```

Is that what you're trying to do?

And if you wanted to modify any of your repo objects with attributes you can do that too:

```cs
[Name("Droid")]
[Description("Some description")]
class DroidDto // existing DTO
{
    public string Id { get; set; }

    [Description("The name of the droid.")]
    public string Name { get; set; }

    [Ignore]
    public double SomeInternalProperty { get; set; }
   // ...
}
```

Sorry if it's not very clear. I've been meaning to throw together some documentation for that library. Hope that helps though.

**Comment by ronnyek** [comment]
No no... I think its good and again I appreciate your patience... I think conceptually the dto exposure is actually pretty straight forward... I'm not asking anyone to build me anything. Just trying to understand how (or at this point, if I even can achieve this)

The first part tho... I dont want my structure to be hard defined in a query class... I want to build dynamically... so instead of creating Query class... I'd like to be able to have a builder or something... and I dont mind building that, but in the raw GraphQL-dotnet stuff... I cant seem to figure out how to just build a tree.

so instead of 
```
public class Query{

[GraphQlFunc]
public List<Droid> GetDroids(){
}

[GraphQlFunc]
public List<Human> GetHumans(){
}

}
```
I'm trying to do this...

```
var query = new Schema();
query.AddGraphQlFunc<List<Droid>>("Droids", Func<Droid>); //cant seem to figure out how to achieve this
query.AddGraphQlFunc<List<Human>>("Humans", Func<Droid>);

//and do I need to manually expose my dtos to schema?

//or maybe be able to have high level object that exposes more functions like DroidContext that will let me have a hierarchy like
query.Droids.AllDroids
query.Droids.DroidsWithFriends

```
I'm trying to effectively building a list of get funcs or whatever. For all intents and purposes the only thing I want generated based on class is the dto / known type stuff.

Also, I guess is part of my confusion is the schema itself... 
```
type QueryRoot {
  droids: [Droid] //is this a List type? Is it a function that returns a list? does the schema denote how items will be fetched?
  humans: [Human]
}
```

**Comment by joemcbride** [comment]
```
type QueryRoot {
  droids: [Droid] //is this a List type? Is it a function that returns a list? does the schema denote how items will be fetched?
  humans: [Human]
}
```

`droids: [Droid]` is a function that returns a List.  The easiest way to think about it is that ALL fields on a Graph type are a function.  GraphQL .NET just makes it easy on you that you don't need to provide a function for just basic properties.  It provides a "default" function for you in that case.

You can't add a function directly to the `Schema`.  You can only add functions to a Graph Type.  At the root of your `Schema` is either a `Query`, `Mutation`, or `Subscription`.  So you could create your own `AddGraphQlFunc<List<Droid>>("Droids", Func<Droid>);` extension method, though that would need to map to 1 of those 3 "root types".

[This unit test](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L94-L118) shows an example of dynamically building types and making a query.  It uses [an extension method](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L164) defined in the tests.  Does that help?

**Comment by joemcbride** [comment]
Oh, one other note.  GraphQL .NET doesn't do _any_ fetching.  You the developer are responsible for all of your data fetching in the `resolve` methods for the field.  For a list, you fetch the list of DTOs and return it in your resolve method.  Those DTOs should have the same "shape" as your defined Graph type.

```
class Droid // existing DTO
{
    public string Id { get; set; }

    public string Name { get; set; }

   // ...
}

class DroidType : ObjectGraphType
{
  public DroidType()
  {
    Field<StringGraphType>("id");
    Field<StringGraphType>("name");
  }
}

// or
var str = new StringGraphType();

var droidType = new ObjectGraphType();
person.Name = "Droid";
person.Field("id", str);
person.Field("name", str);
person.IsTypeOf = type => type is Droid;
```

**Comment by ronnyek** [comment]
ok, that's exactly what I was looking for. I'll play with that a bit more. I think that explanation along with some of the type resolver stuff you have in conventions, I've got a very good idea of what else I'll need to do. I appreciate you taking the time to answer these questions

**Comment by joemcbride** [comment]
Going to close this, re-open if needed.  Thanks!

**Comment by EmmanuelPonnudurai** [comment]
Hello @joemcbride Is this [piece of code](https://github.com/graphql-dotnet/graphql-dotnet/issues/255#issuecomment-271695410) still valid ? I am trying to generate my types dynamically based off of my model but I just cant seem to get the Query to build up correctly. What I have is something like this. But, the types are not getting registered correctly. The code which you have above gives compilation errors right now. May be because that was old, If i get it working correctly then I'll be more than happy to add a sample in the documentation? Thanks,

```cs
            var droidType = new ObjectGraphType
            {
                Name = "Droid"
            };
            droidType.Field(typeof(StringGraphType), "id");
            droidType.Field(typeof(StringGraphType), "name");
            droidType.IsTypeOf = type => type is Droid;
            var root = new ObjectGraphType
            {
                Name = "QueryRoot"
            };
            root.Field(
                typeof(ListGraphType<NonNullGraphType<?>>), // how do I specify the type of the droidType here?
              "droids",
              resolve: ctx => new[] { new Droid { Id = "R2-D2", Name = "R2-D2" }, new Droid { Id = "K-2SO", Name = "K-2SO" } });

            var schemaDynamic = new Schema
            {
                Query = root
            };
```

**Comment by joemcbride** [comment]
See this example:

https://github.com/graphql-dotnet/graphql-dotnet/blob/0dc0443ffd9d21673583901d534d47e3fefc3d7e/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L19

And this extension method:

https://github.com/graphql-dotnet/graphql-dotnet/blob/0dc0443ffd9d21673583901d534d47e3fefc3d7e/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L291

**Comment by EmmanuelPonnudurai** [comment]
Thank you @joemcbride It works now. I was trying to do it with existing overloads for adding fields. I'm wondering why this extension method lives in the test class and can it not be within the other available overloads for `Field(...)` in `ComplexGraphType.cs`
