### ISSUE TITLE
System.Text.Json ExecutionResultJsonConverter not serializing Extensions with provided JsonSerializerOptions

### ISSUE THREAD

**Issue by kyleadams-fm** [graphql-dotnet/graphql-dotnet#2552]
## Description

System.Text.Json ExecutionResultJsonConverter not serializing Extensions object based on the provided JsonSerializerOptions.

### Steps to reproduce

Using JsonSerializerOptions with a camelCase naming strategy 
```
var options = new JsonSerializerOptions
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DictionaryKeyPolicy = null,
    IgnoreNullValues = true,
    AllowTrailingCommas = true
};
```

Serialize an error object through WriteErrors with object in the extensions 
```
internal class ValidationViolation
{
    public string Message { get; }
    public string Property { get; }

    public ValidationViolation(string message, string property)
    {
        Message = message;
        Property = property;
    }
}
```

I believe this is due to the fact that options is not passed to the serializer at this point 
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs#L274

### Expected result

With this I would expect to see this object serialized as 
``` 
{
     "message": "....",
     "property": "....."
}
```

### Actual result

Serialization is 
```
{
  "Message": "User with given Email already exists",
  "Property": "Email"
}
```

**Comment by Shane32** [comment]
I agree. Do you want to make a PR with a fix?
