### ISSUE TITLE
"Document caching" docs references non-existent GraphQL.Caching package

### ISSUE THREAD

**Issue by jumpinjackie** [graphql-dotnet/graphql-dotnet#2561]
## Description

The [document caching](https://graphql-dotnet.github.io/docs/guides/document-caching) section of the docs ([source](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/guides/document-caching.md)) is out of date. The linked [GraphQL.Caching](https://www.nuget.org/packages/GraphQL.Caching) package is a 404. Presumably, this package is now called [GraphQL.MemoryCache](https://www.nuget.org/packages/GraphQL.MemoryCache/) instead.

~~1. The linked [GraphQL.Caching](https://www.nuget.org/packages/GraphQL.Caching) package is a 404
 2. Assuming the package in question is actually [GraphQL.MemoryCache](https://www.nuget.org/packages/GraphQL.MemoryCache/) then the code example for instantiating a `MemoryDocumentCache` doesn't work because there is no constructor that takes a `MemoryDocumentCacheOptions` parameter, only a `IOptions<MemoryDocumentCacheOptions>`, and in that case how would you provide an `IOptions<MemoryDocumentCacheOptions>` instance without having to buy into Microsoft's options/DI system or passing in an instance of your own concrete class implementing this interface?~~

### Steps to reproduce

Try to add document caching support using the referenced documentation and code examples

### Expected result

My .net GraphQL service has document caching enabled

### Actual result

~~The code examples do not compile~~
The `GraphQL.Caching` package referenced in the documentation does not exist. Using `GraphQL.MemoryCache` makes all the code examples work

### Environment

GraphQL.net 4.5.0
GraphQL.MemoryCache 4.5.0

**Comment by Shane32** [comment]
Good catch and thanks for the PR!
