### ISSUE TITLE
Federated Schema generates an empty query type in the SDL

### ISSUE THREAD

**Issue by myermian** [graphql-dotnet/graphql-dotnet#2563]
## Description

Creating a federated subgraph using graphql dotnet fails if you do not extend the Query type.

### Steps to reproduce

1. Download the [apollographql/federation-demo](https://github.com/apollographql/federation-demo) repository.
2. Run the `npm install` command to install the dependencies.
3. Run the `npm run start-services` command to run the services in terminal window A.
4. Run the `npm run start-gateway` command to run the gateway in terminal window B.
5. Download and run the [sample solution](https://github.com/graphql-dotnet/graphql-dotnet/files/6583970/Sample.zip) provided.
6. Modify the gateway.js file to include the new service endpoint. Save the file, the gateway will automatically try to update and fail.

### Expected result

The gateway should accept the new service endpoint and federate the schema properly.

### Actual result

The gateway fails with the error: `UnhandledPromiseRejectionWarning: Error: Couldn't load service definitions for "user-service" at http://localhost:5000/graphql: Syntax Error: Expected Name, found "}".` (full error below)

> (node:7676) UnhandledPromiseRejectionWarning: Error: Couldn't load service definitions for "user-service" at http://localhost:5000/graphql: Syntax Error: Expected Name, found "}".
>     at X:\GitHub\apollographql\federation-demo\node_modules\@apollo\gateway\dist\loadServicesFromRemoteEndpoint.js:45:19
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async Promise.all (index 4)
>     at async Object.getServiceDefinitionsFromRemoteEndpoint (X:\GitHub\apollographql\federation-demo\node_modules\@apollo\gateway\dist\loadServicesFromRemoteEndpoint.js:48:32)
>     at async ApolloGateway.updateSchema (X:\GitHub\apollographql\federation-demo\node_modules\@apollo\gateway\dist\index.js:266:24)
>     at async ApolloGateway.loadDynamic (X:\GitHub\apollographql\federation-demo\node_modules\@apollo\gateway\dist\index.js:250:13)
>     at async ApolloGateway.load (X:\GitHub\apollographql\federation-demo\node_modules\@apollo\gateway\dist\index.js:221:15)

<hr>

If you navigate to the new service (http://localhost:5000/ui/playground) and run the following query, you will see that the SDL is returning an empty type query.

```gql
query {
  _service {
    sdl
  }
}
```

```json
{
  "data": {
    "_service": {
      "sdl": "type Query {\r\n\r\n}\r\n\r\nextend type User @key(fields: \"id\") {\r\n  id: ID! @external\r\n  phone: String\r\n}\r\n"
    }
  },
  "extensions": {}
}
```

Compare that to the sdl generated from the "**inventory service**" (http://localhost:4004/), which also does not extend the query type:

```json
{
  "data": {
    "_service": {
      "sdl": "extend type Product @key(fields: \"upc\") {\n  upc: String! @external\n  weight: Int @external\n  price: Int @external\n  inStock: Boolean\n  shippingEstimate: Int @requires(fields: \"price weight\")\n}\n"
    }
  }
}
```

The "**inventory service**" is provided by the apollographql/federation-demo repository. It is a Node.js project, relying on the apollo npm packages. Also, I do not think that the carriage return line feeds that graphql-dotnet generates causes any problems compared to the fact that the Node.js only generates line feeds. It pretty much comes down to the empty type Query: `type Query {\r\n\r\n}`

### Environment

- OS: Windows_NT x64 10.0.19041
- Microsoft .NET Framework: .NET 5.0
- GraphQL (nuget): 4.5.0
- GraphQL Server (nuget): 5.0
- Node.js: 14.16.0
- VS Code Version: 1.56.2 (user setup)
- VS Code Commit: 054a9295330880ed74ceaedda236253b4f39a335
- VS Code Date: 2021-05-12T17:13:13.157Z
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- V8: 8.9.255.24-electron.0
- Microsoft Visual Studio Enterprise 2019: Version 16.9.4

**Comment by amrock-my** [comment]
FYI -- This can be solved by adding a simple if check in the [FederatedSchemaPrinter.cs](https://github.com/graphql-dotnet/graphql-dotnet/blob/d7680d6c120de7df92a47faa282955932f152203/src/GraphQL/Utilities/Federation/FederatedSchemaPrinter.cs#L53) file.

```cs
public override string PrintObject(IObjectGraphType type)
{
    // Do not return an empty query type: "Query { }" as it is not valid as part of the sdl.
    if (type != null && !type.Fields.Any(x => !IsFederatedType(x.ResolvedType.GetNamedType().Name))
       return "";

    var isExtension = type.IsExtensionType();

    var interfaces = type.ResolvedInterfaces.List.Select(x => x.Name).ToList();
    var delimiter = " & ";
    var implementedInterfaces = interfaces.Count > 0
        ? " implements {0}".ToFormat(string.Join(delimiter, interfaces))
        : "";

    var federatedDirectives = PrintFederatedDirectives(type);

    var extended = isExtension ? "extend " : "";

    return FormatDescription(type.Description) + "{1}type {2}{3}{4} {{{0}{5}{0}}}".ToFormat(Environment.NewLine, extended, type.Name, implementedInterfaces, federatedDirectives, PrintFields(type));
}
```

Are we allowed to create pull requests? If so, I can do that, but if not, please update your code to account for this if check (or something similar to avoid returning "Query {/r/n/r/n}" as part of the sdl.

**Comment by Shane32** [comment]
A pull request would be great! Can you include a test demonstrating that the issue is now fixed?

**Comment by myermian** [comment]
> A pull request would be great! Can you include a test demonstrating that the issue is now fixed?

Unfortunatey, it will not allow me to push my branch in order to create a pull request:

```
Switched to branch 'bugfix/fix-federation-sdl-removing-empty-query-type'
Checked out bugfix/fix-federation-sdl-removing-empty-query-type
Commit 29941ae3 created locally in repository X:\GitHub\graphql-dotnet\graphql-dotnet
Pushing bugfix/fix-federation-sdl-removing-empty-query-type
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/graphql-dotnet/graphql-dotnet.git/': The requested URL returned error: 403
Pushing to https://github.com/graphql-dotnet/graphql-dotnet.git
```

I updated the code and added a test case (`Fact` in xUnit) to cover this scenario. I also manually tested this on my local machine.

**FederatedSchemaPrinter.cs:**

```cs
public override string PrintObject(IObjectGraphType type)
{
    // Do not return an empty query type: "Query { }" as it is not valid as part of the sdl.
    if (type != null && String.Equals(type.Name, "Query", StringComparison.Ordinal) && !type.Fields.Any(x => !IsFederatedType(x.ResolvedType.GetNamedType().Name)))
       return String.Empty;

    var isExtension = type.IsExtensionType();

    var interfaces = type.ResolvedInterfaces.List.Select(x => x.Name).ToList();
    var delimiter = " & ";
    var implementedInterfaces = interfaces.Count > 0
        ? " implements {0}".ToFormat(string.Join(delimiter, interfaces))
        : "";

    var federatedDirectives = PrintFederatedDirectives(type);

    var extended = isExtension ? "extend " : "";

    return FormatDescription(type.Description) + "{1}type {2}{3}{4} {{{0}{5}{0}}}".ToFormat(Environment.NewLine, extended, type.Name, implementedInterfaces, federatedDirectives, PrintFields(type));
}
```

**FederatedSchemaPrinterTests.cs** (new file under GraphQL.Tests/Utilities/Federation/ folder)

```cs
using System;
using GraphQL.Types;
using GraphQL.Utilities;
using GraphQL.Utilities.Federation;
using Xunit;

namespace GraphQL.Tests.Utilities.Federation
{
    public class FederatedSchemaPrinterTests
    {
        [Fact]
        public void PrintObject_ReturnsEmptyString_GivenQueryTypeHasOnlyFederatedFields()
        {
            // Arrange
            ISchema schema = default;
            SchemaPrinterOptions options = default;
            var query = new ObjectGraphType { Name = "Query" };
            query.Field("_entities", new NonNullGraphType(new ListGraphType(new NonNullGraphType(new GraphQLTypeReference("_Any")))));
            query.Field("_service", new NonNullGraphType(new GraphQLTypeReference("_Service")));

            var federatedSchemaPrinter = new FederatedSchemaPrinter(schema, options);

            // Act
            string result = federatedSchemaPrinter.PrintObject(query);

            // Assert
            Assert.Equal(String.Empty, result);
        }
    }
}
```

**Comment by Shane32** [comment]
Fork the repository into your own GitHub account.  Create a new branch and make changes as desired.  After pushing the branch, you can come back to this repository and create a pull request here from the branch within your own fork.  Tests will automatically run and we can review code and communicate within the pull request.  Thanks!

**Comment by myermian** [comment]
> Fork the repository into your own GitHub account. Create a new branch and make changes as desired. After pushing the branch, you can come back to this repository and create a pull request here from the branch within your own fork. Tests will automatically run and we can review code and communicate within the pull request. Thanks!

Ok, sorry. I'm so used to Azure DevOps that I barely check in code on GitHub.

**Comment by Shane32** [comment]
No problem! Really appreciate the time helping on this project.

**Comment by myermian** [comment]
This was merged. I’m gonna request to close.

**Comment by sungam3r** [comment]
See #2751
