### ISSUE TITLE
Required fields in input types

### ISSUE THREAD

**Issue by mariusbancila** [graphql-dotnet/graphql-dotnet#2565]
I am trying to write mutations for inserting and updating records in database tables. These can have many fields, therefore I created input types with fields for all table columns that can be written.

```
input Widget {
   name : String
   width: Int
   height : Int
   # etc etc
}
```
However, some of these fields are required. If I don't provide them, the operation fails. I want to avoid that by marking these as mandatory. Since GraphQL does not have a "required" concept, I thought of using nullability.

```
input Widget {
   name : String!
   width: Int!
   height : Int!
   # etc etc
}
```
However, this does not seem to be possible. I get the following error:
```
Input type 'Widget' can have fields only of input types
```
GraphQL does not seem to prohibit this. [The docs show examples of this](https://graphql.org/learn/schema/#input-types):
```
input ReviewInput {
  stars: Int!
  commentary: String
}
```
I've seen that GraphQL.js [does not allow it](https://graphql.org/graphql-js/mutations-and-input-types/):
```
Input types can't have fields that are other objects, only basic scalar types, list types, and other input types
```

However, other implementations support it:

- [GraphQL Ruby: Input types](https://graphql-ruby.org/type_definitions/input_objects)
- [Apollo GraphQL: input types](https://www.apollographql.com/blog/graphql/basics/using-nullability-in-graphql/)

So what can I do in GraphQL.NET?

**Comment by Shane32** [comment]
The error is indicating that you are trying to use an output graph type (`ObjectGraphType`) for an field within an input graph type (a `InputObjectGraphType`).  You can only have input object graph types, lists, or scalars within other input graph types.  This is pursuant to the specification.  For example, this is valid:

```gql
input MyInput {
  testScalar: String
  testObject: MyInput2
}

input MyInput2 {
  name: String
}
```

However, this is not:
```gql
input MyInput {
  testScalar: String
  testObject: MyInput2
}

type MyInput2 {
  name: String
}
```

**Comment by Shane32** [comment]
> I want to avoid that by marking these as mandatory. Since GraphQL does not have a "required" concept, I thought of using nullability.

You are correct; this makes sense to me.  See the wording from the spec:

> Inputs (such as field arguments), are always optional by default. However a non‐null input type is required. In addition to not accepting the value null, it also does not accept omission. For the sake of simplicity nullable types are always optional and non‐null types are always required.

**Comment by mariusbancila** [comment]
> Note that GraphQL.NET fully supports nullable or non-nullable fields configured on input types, so long as the fields' type is supported by the specification (a scalar, list, or another input object type). Field and directive arguments also have the same restrictions.

I want to model this:
```jsonc
input Widget {
   name : String!
   width: Int!
   height : Int!
   # etc etc
}
```
Demo code:
```cs
   public class MyMutationType : ObjectGraphType
   {
      public MyMutationType()
      {
         Name = "Mutation";

         InputObjectGraphType widgetType = new()
         {
            Name = "Widget",
         };

         widgetType.Field(
            type: new NonNullGraphType(new StringGraphType()).GetType(),
            name: "name",
            resolve: ctx => "default");

         widgetType.Field(
            type: new NonNullGraphType(new IntGraphType()).GetType(),
            name: "width",
            resolve: ctx => 0);

         FieldType widgetField = new()
         {
            Name = "width",
            ResolvedType = widgetType,
            Resolver = new FuncFieldResolver<object>(ctx => null)
         };

         AddField(widgetField);
      }
   }
```

Or, if you prefer it like this:
```cs
InputObjectGraphType widgetType = new()
{
   Name = "Widget",
};

widgetType.Field<NonNullGraphType<StringGraphType>>()
   .Name("name")
   .Resolve(ctx => "default");

widgetType.Field<NonNullGraphType<IntGraphType>>()
   .Name("width")
   .Resolve(ctx => 0);
```

This does not work. When adding any of these fields I get the following runtine exception:
```
System.ArgumentOutOfRangeException: 'Input type 'Widget' can have fields only of input types: ScalarGraphType, EnumerationGraphType or IInputObjectGraphType. Field 'name' has an output type. (Parameter 'fieldType')'
```

**Comment by Shane32** [comment]
Change:
```cs
            type: new NonNullGraphType(new StringGraphType()).GetType(),
```
to this:
```
            type: typeof(NonNullGraphType<StringGraphType>),
```

**Comment by Shane32** [comment]
Similarly for your int graph type.  This is because the prior code equals `typeof(NonNullGraphType)` and not `typeof(NonNullGraphType<StringGraphType>)`

**Comment by Shane32** [comment]
Also you are specifying an input type (widgetField) to a mutation field (width) which is an output type.  You want to add an argument to the mutation field (width), and the argument is of type widgetField.

See: https://graphql-dotnet.github.io/docs/getting-started/mutations

**Comment by mariusbancila** [comment]
> Change:
> 
> ```cs
>             type: new NonNullGraphType(new StringGraphType()).GetType(),
> ```
> 
> to this:
> 
> ```cs
>             type: typeof(NonNullGraphType<StringGraphType>),
> ```

This solved the problem. I did not realize the difference but now that you mentioned it makes sense, of course.

> Also you are specifying an input type (widgetField) to a mutation field (width) which is an output type. 
> You want to add an argument to the mutation field (width), and the argument is of type widgetField. 
> The type of the width field should be an output type.

You are absolutely correct. I assembled some quick code in a hurry to post it here, I was looking for the exception repro, and made this error of adding it as an output field. The input types are used, ofc, for arguments. But thanks for pointing that out.

**Comment by Shane32** [comment]
Good to hear.  I'll close this issue, but please reopen if you have further questions regarding this topic, or start a new issue.
