### ISSUE TITLE
Extending existing type/interface?

### ISSUE THREAD

**Issue by magnusottosson** [graphql-dotnet/graphql-dotnet#2566]
Lets say we have a base ProductInterface like that is defined in one "Foundation" .NET project.

```
public class ProductInterface : InterfaceGraphType<IProductBase>
    {
        public ProductInterface()
        {
            Name = "Product";
            Description = "The base for any product.";
        }
    }
```

The interface does not have any fields. In a seperate .NET project we have logic for ecommerce and want to add a a price field to the product interface. Is it possible to add fields to existing types at runtime without modifying the ProductInterface class?

```
Solution
  - Project
    * Configuration of schema is done here
  - Features
    - Commerce
      * ProductInterfaceExtensions (know about ProductInterface)
  - Foundation
    - Products
      * ProductInterface (does not know about the Commerce project
```

Is it possible to add new fields to the existing ProductInterface type?

**Comment by SebastianStehle** [comment]
I would introduce a base interface and then build a simple plugin structure, where each feature registers its own IGraphQLExtension implementation which are invoked in your core.

something like this:

```
public class ProductBaseInterface : InterfaceGraphType<IProductBase>
{
    public ProductBaseInterface ()
    {
        Name = "Product";
        Description = "The base for any product.";
    }
}

/// Provides access to everything that can be extended.
class GraphQLScheme
{
   public ProductBaseInterface  Product { get; init; }
}

interface IGraphQLExtension 
{
  Task Extend(GraphQLSchema scheme);
}
```

**Comment by SebastianStehle** [comment]
> Is it possible to modify the already added ProductBaseInterface and add fields to it? I cant find any method for that?

No, I don't think so. By why can you not just invoke the extensions before you add the interface?

**Comment by magnusottosson** [comment]
Ah ok. I will see if I can come up with something similar. I definitely want to hook into when the schema is created and extend the existing types.

Thanks.

**Comment by SebastianStehle** [comment]
You only need this if you change your schema at runtime. e.g. if you have an "Install Extension" button or so. Otherwise you just need a few interfaces.

**Comment by sungam3r** [comment]
Thanks @SebastianStehle 
Closed as answered.
