### ISSUE TITLE
How to set default object in each request pair in certain conditions?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2570]
I am using batch data loader to group up a number of requests and return them to each of the field resolvers.

Below is what I have and it works fine -

    protected override async Task FetchAsync(IEnumerable<DataLoaderPair<IRequest, object>> list, CancellationToken cancellationToken)
    {
         //1. find the different types of requests
         var contentRequestPair = list.SingleOrDefault(x => x.Key is ContentRequest);
         var contentRequest = (ContentRequest)contentRequestPair?.Key;

         var findRequestPair = list.SingleOrDefault(x => x.Key is FindRequest);
         var findRequest = (FindRequest)findRequestPair?.Key;

         //2. initialize request
         var processRequest = new ProcessRequest {
             ....
         };

         // 3. execute request
         var processResponse = await ExecuteProcessRequestAsync(processRequest, cancellationToken);
         int statusCode = processResponse.ResponseCode;

         // 4. set the results
         if (contentRequest != null)
         {
             // create the data model for the graph
             var contentResponse = processResponse.GetContentResponse;
             if(contentResponse != null) {
                contentRequestPair.SetResult(contentResponse);
             }
             else {
             // this doesn't work
              contentRequestPair.SetResult(new ContentResponse());
             }
         }
         if (findRequest != null)
         {
             // create the data model for the graph
             var findResponse = processResponse.GetFindResponse;
             if(findResponse != null) {
                findRequestPair.SetResult(findResponse);
             }
             else {
              // but this works fine
              findRequestPair.SetResult(new new List<FindResponse>()());
             }
         }
    }

If the status code is 204, then I want to set default object in each of the requestpair back instead of using the corresponding objects from `processResponse` variable. For some weird reason when I set like this then my graph type throws exception as - `Error trying to resolve field 'clientId'.\n ---> System.NullReferenceException: Object reference not set to an instance of an object`

    contentRequestPair.SetResult(new ContentResponse());

**ContentResponseType class**

    public class ContentResponseType : ObjectGraphType<ContentResponse>
    {
          public ContentResponseType()
          {
              Name = "ContentResponse";
              Field("clientId", x.Holder.Data.ClientId.ToString());
              ....
          }
    }

But this works fine for `findRequestPair` object.

    public class FindResponseType : ObjectGraphType<FindResponse>
    {
        public FindResponseType()
        {
            Name = "FindingResponse";
            Field("title", x => x.Group.Label);
            Field("type", x => x.Group.Type);
        }
    }

**Comment by Shane32** [comment]
By executing `contentRequestPair.SetResult(new ContentResponse());`, now when `clientId` attempts to resolve, it looks at a new `ContentResponse` object and tries to evaluate `x.Holder.Data.ClientId.ToString()`.  Most likely, `Holder` is the default value of `null`, so evaluating `x.Holder.Data` results in a null reference exception.  I suggest one of two approaches:

1. Use `contentRequestPair.SetResult(null);`.  This will cause a `null` for the entire object graph to be returned and is probably the correct approach.  Then `clientId` will not attempt to be resolved at all.  If the graph type for the object is a non-null graph type then you may get an error due to a null being returned where it is not allowed.  Easiest to just try and see if the results are what you expect.

2. Use `Field("clientId", x => x.Holder?.Data?.ClientId?.ToString());`.  This will cause a null to be returned for `clientId` in your scenario.

**Comment by TechGeeky** [comment]
I wasn't aware of this `contentRequestPair.SetResult(null);`. Thanks for letting me know. And for second point I may need to make it nullable true then right?

**Comment by TechGeeky** [comment]
You sure on your point 2 I don't need to make this? If clientId can be null then I need to make this right?

    Field("clientId", x => x.Holder?.Data?.ClientId?.ToString(), true)

Or something I need to do here?

```
FieldAsync<ListGraphType<ContentResponseType>>(
            "contentRequest",
            arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<IntGraphType>>
                    {
                        Name = "clientId",
                        Description = "Client Id of the request"

                    },
                    new QueryArgument<ListGraphType<FilterType>>
                    {
                        Name = "filters",
                        Description = "Filters"
                    },
                    new QueryArgument<StringGraphType>
                    {
                        Name = "clientKey",
                        DefaultValue = "abc",
                        Description = "some stuff"
                    }
                ),

            resolve: async context =>
            {
                var dataLoader = context.RequestServices.GetRequiredService<MyDataRequestor>();
                var request = new ContentRequest {
                    ClientId = context.GetArgument<int>("clientId"),
                    Filters = context.GetArgument<List<Filter>>("filters"),
                    ClientKey = context.GetArgument<string>("clientKey"),
                };

                // after being processed by the dataloader, will return a List<ContentResponse>
                return dataLoader.LoadAsync(request);
            }
        );
```

**Comment by Shane32** [comment]
Unless of course you expect this to run and contain a null clientId string:

```
         var contentResponse = processResponse.GetContentResponse;
         if(contentResponse != null) {
            contentRequestPair.SetResult(contentResponse);
            // ----- if contentResponse.Holder.Data.ClientId still might be null here, then yes you need the change -----
         }
```
