### ISSUE TITLE
Closure issue?

### ISSUE THREAD

**Issue by magnusottosson** [graphql-dotnet/graphql-dotnet#2573]
I just updated from 2.1.0 -> 4.5.0 :) (we hade dependency issues before that prevented us from updating)

I have a lot of fields like this:

```
Field<NonNullGraphType<ListGraphType<NonNullGraphType<ImageSourceType>>>, IEnumerable<ImageSource>>("sources")
                .Argument<NonNullGraphType<ListGraphType<NonNullGraphType<ImageFormatEnum>>>>("configs", "The image configurations")
                .Resolve(context =>
                {
                    return context.GetArgument<IEnumerable<string>>("configs")
                        .Select(imageConfigRepo.GetImageFormat)
                        .Where(f => f != null)
                        .Select(format => new ImageSource
                        {
                            MediaItem = context.Source,
                            ImageFormat = format,
                        })
                });
```

Before the update this worked but after the update the MediaItem property was null when resolved in `ImageSourceType`. I realised that this is because the linq query is executed later and then the context is gone.

Adding a .ToList() to the end solved the issue. I guess that this is due to some internal optimisation.

Would you say that its correct to add a .ToList at the end or is there some more effective way of solving this?

**Comment by Shane32** [comment]
The context is re-used internally. You can cache the context.Source property in a local variable to fix the problem, or add ToList. It shouldn’t make too much difference either way.

**Comment by Shane32** [comment]
See migration notes here:
https://graphql-dotnet.github.io/docs/migrations/migration4#code-classlanguage-textiresolvefieldcontextcode-re-use

**Comment by magnusottosson** [comment]
great, thanks.
