### ISSUE TITLE
Is there a way to add description (not the comment) to field or type in schema? 

### ISSUE THREAD

**Issue by bohdan-kolomiiets** [graphql-dotnet/graphql-dotnet#2574]
## Summary
According to official graphql specification, field description is surrounded by double-quotes, type description is surrounded by triple double-quotes. 
In turn, comments start from the # character.

Value set via `GraphQL.Builders.Description`  method results in comment (not a description) in the schema.
```
Field<SomeGraphType>()
    .Name("fieldName")
    .Description("field description")
```

Value set via `Description` property of `GraphQL.Types.GraphType` also results in comment (not a description) in the schema.
```
public class MyGraphType : ObjectGraphType<MyModel>
{
    public MyGraphType()
    {
        Name = "TypeName";
        Description = "type description";
    }
}
```

Is there a way to specify description (not the comment) for the type (`GraphQL.Types.ObjectGraphType`) or for its fields in the "GraphType First Approach"?

## Relevant information
Assembly GraphQL, Version=4.1.0.0
GraphQL.Server.All, Version=5.0.2

https://spec.graphql.org/June2018/#sec-Descriptions
https://spec.graphql.org/June2018/#sec-Comments

**Comment by Shane32** [comment]
The description method/property does identify itself as a description to the graph, as can be seen from an introspection query, but there is a bug in the schema printer where it is printing descriptions as comments instead of as descriptions in the format described by the official specification. Confirmed in GraphQL.NET 4.5.0. Would you be interested in writing a pull request to fix the schemaprinter class?

**Comment by Shane32** [comment]
Enhancing this library to correctly parse descriptions requires https://github.com/graphql-dotnet/parser/pull/131 and https://github.com/graphql-dotnet/parser/pull/132 to be merged before it can be added to this library.  After they are merged, a PR can be written here to enable both the schema builder and schema printer to read and write descriptions according to spec.
