### ISSUE TITLE
Keycloak and GraphQL.NET

### ISSUE THREAD

**Issue by miko866** [graphql-dotnet/graphql-dotnet#2578]
For one of our projects we would like to use Keycloak (https://www.keycloak.org/) to create the JWT tokens. I realized that the GraphQL.Authorization only works for JWT tokens that are structured in the "Microsoft"-way for the roles. Has anyone found a way to use Keycloak together with GraphQL.NET? Is there a way for me to rewrite the policies in a way that it supports Keycloak format of the JWT token?

**Comment by Shane32** [comment]
It isn't _necessary_ to use the GraphQL.Authorization project at all.  And in fact there is another authorization project within the server project as well.  Personally, I have my own ASP.Net middleware which pulls the JWT token from the HTTP header, decodes it via `JwtSecurityTokenHandler.ValidateToken`, and adds the relevant information to a custom UserContext object stored in `ExecutionOptions.UserContext`.  I also wrote some extension methods to `IResolveFieldContext` to pull commonly used variables from the user context - for example:

```cs
public static int GetUserId(this IResolveFieldContext context) => ((MyUserContext)context.UserContext).UserId;
```

Then I protect the mutations via a hierarchal structure -- meaning, I put all the mutations requiring admin permissions under an ObjectGraphType called "admin".  The resolver for "admin" returns null if permission is not allowed, so no permission checks are needed within any child fields.  This probably works well for me where I have only 3 roles (not logged in, user, admin), but this is likely too simple for typical needs.  In the future I plan to use a validation rule which validates requested fields and graphs against metadata stored within the field/graph.  This will reduce the amount of permission checks within my mutations or fields.

So if you write your own authorization code, it really can be quite simple, and you can write it any way you want.  You don't need to use either of the Authorization projects if you don't want to.

Sorry, I don't know if you can use the Keycloak tokens within one of the existing authorization projects.  I just don't know enough about either Keycloak or the existing authorization projects.

**Comment by joemcbride** [comment]
Also just a note, GraphQL.Authorization works with ANY authentication mechanism, whether that's JWT or cookies. The JWT can be structured any way you want. You as the user of the library define the claims in the JWT that you check against. All the library depends on is a `ClaimsPrincipal`, which can be populated by any authentication mechanism.  Whether that's "Microsoft" format or not, that shouldn't matter.

**Comment by Shane32** [comment]
Closed due to lack of feedback.  Please re-open if you have further questions.
