### ISSUE TITLE
How to pass object from ExecuteAsync method of GraphQLMiddleware to DataLoader class?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2579]
I am using batch data loader to group up a number of requests and return them to each of the field resolvers. Everything works fine but I am confuse on a very simple thing.

This is what I have in my `GraphQLMiddleware` class. 

As you can see we have surrounded the GraphQL calls with our own `LogTimer` class so that we can log how much time it took and few other details along with it for debugging.

    private async Task ExecuteAsync(HttpContext context, ISchema schema)
    {
        var loggingService = ...;
        var loggingContext = ...;
        using (var logTimer = new LogTimer(loggingService, loggingContext, "GraphQL Demo Test", GetEndpoint(context), "start"))
        {
            try
            {
                var request = Deserialize<GraphQLRequest>(context.Request.Body);
                var result = await _executer.ExecuteAsync(opts =>
                {
                    opts.Schema = schema;
                    opts.Query = request?.Query;
                    opts.OperationName = request?.OperationName;
                    opts.Inputs = request?.Variables.ToInputs();
                    opts.RequestServices = context.RequestServices;
                    opts.UserContext = _settings.BuildUserContext?.Invoke(context);
                    opts.ValidationRules = DocumentValidator.CoreRules.Concat(new[] { new InputValidationRule() });
                    opts.EnableMetrics = _settings.EnableMetrics;
                    if (_settings.EnableMetrics)
                    {
                        opts.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
                    }
                    opts.UnhandledExceptionDelegate = async ctx =>
                    {
                        await HandleApiException(context, ctx.Exception, loggingService, loggingContext);
                    };
                });
                await WriteResponseAsync(context, result);
                logTimer.StatusCode = context.Response.StatusCode;
                // Is there any way to get `processRequest` object or `dumpRequest` string here after it is executed? 
                // Can I access it from the context object?
                // logTimer.logMessage = dumpRequest;
            }
            catch (Exception ex)
            {
                await HandleApiException(context, ex, loggingService, loggingContext);
                logTimer.StatusCode = context.Response.StatusCode;
            }
        }
    }

Below is my `DataLoader` class where I am extending `DataLoaderBase` and everything works fine.

    public class BatchLoader : DataLoaderBase<IGraphRequest, object>
    {
        private readonly IHttpContextAccessor _accessor;
         .....
        // constructor here

        protected override async Task FetchAsync(IEnumerable<DataLoaderPair<IRequest, object>> list, CancellationToken cancellationToken)
        {
             //1. find the different types of requests
             var contentRequestPair = list.SingleOrDefault(x => x.Key is ContentRequest);
             var contentRequest = (ContentRequest)contentRequestPair?.Key;

             //2. initialize request
             var processRequest = new ProcessRequest {
                 ....
             };

             var dumpRequest = StringifiedRequest(processRequest);
             // Now my confusion is how to log `dumpRequest` string on the same `LogTimer` which is being used in `ExecuteAsync` method of `GraphQLMiddleware` class as shown above.
             // How do I get logTimer object?
             // logTimer.logMessage = dumpRequest;

            // extract header
            _accessor.HttpContext.Request.Headers.TryGetValue("DEMO-HEADER", out var headerValue);
            var loggingContext = new LoggingContext(_accessor.HttpContext.Request.Headers);
             // 3. execute request
             var processResponse = await ExecuteProcessRequestAsync(processRequest, loggingContext, cancellationToken);
            _accessor.HttpContext.Response.StatusCode = processResponse.ResponseCode;

             // 4. set the results
             if (contentRequest != null)
             {
                 // create the data model for the graph
                 var contentResponse = processResponse.GetContentResponse;
                 if(contentResponse != null) {
                    contentRequestPair.SetResult(contentResponse);
                 }
                 else {
                  contentRequestPair.SetResult(null);
                 }
             }
        }
    }

I need to log `dumpRequest` string created in `FetchAsync` method using same `logTimer` object which was created in `ExecuteAsync` method of `GraphQLMiddleware` class.

- Is there any way to pass `logTimer` object from `ExecuteAsync` method of `GraphQLMiddleware` class to `FetchAsync` method so that I can log `dumpRequest` string.
- Or is there any way to see `processRequest` object or `dumpRequest` string created in `FetchAsync` directly in `ExecuteAsync` method of `GraphQLMiddleware` class after request is executed so that I can log it there? Maybe it can be passed down by setting it to some property in `HttpContext`?

My main goal is just to log `dumpRequest` string using the same `logTimer` object for that request.

**Comment by Shane32** [comment]
Can you paste the `Field()` code that queues the data loader?  At least one spot, anyway?

**Comment by TechGeeky** [comment]
@Shane32 You mean this code in our query class?

```
                    var dataLoader = context.RequestServices.GetRequiredService< BatchLoader >();
                    return dataLoader.LoadAsync(request);
```

**Comment by Shane32** [comment]
Try something like this:
```cs
return dataLoader.LoadAsync(request).Then(response => {
    lock (context.UserContext) {
        context.UserContext["response"] = response;
    }
    return response;
});
```
Then you can pull from the UserContext dictionary the response in your query execution code.

**Comment by Shane32** [comment]
```cs
            var userContext = _settings.BuildUserContext?.Invoke(context) ?? new Dictionary<string, object>();
            var result = await _executer.ExecuteAsync(opts =>
            {
                opts.Schema = schema;
                opts.Query = request?.Query;
                opts.OperationName = request?.OperationName;
                opts.Inputs = request?.Variables.ToInputs();
                opts.RequestServices = context.RequestServices;
                opts.UserContext = userContext;
                opts.ValidationRules = DocumentValidator.CoreRules.Concat(new[] { new InputValidationRule() });
                opts.EnableMetrics = _settings.EnableMetrics;
                if (_settings.EnableMetrics)
                {
                    opts.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
                }
                opts.UnhandledExceptionDelegate = async ctx =>
                {
                    await HandleApiException(context, ctx.Exception, loggingService, loggingContext);
                };
            });
            await WriteResponseAsync(context, result);
            logTimer.StatusCode = context.Response.StatusCode;
            logTimer.logMessage = userContext.TryGetValue("response", out var response) ? response : null;
```

**Comment by TechGeeky** [comment]
What is this `response` @Shane32? I think I am confuse now. I believe I don't need to log response of the query but the request.

In my case I need to find a way to log `dumpRequest` string created in `FetchAsync` method using same `logTimer` object which was created in `ExecuteAsync` method of GraphQLMiddleware class.

**Comment by Shane32** [comment]
oh ok....

**Comment by Shane32** [comment]
sorry I just was skimming your question and misunderstood.  I'm pretty busy today (as usual!)

**Comment by TechGeeky** [comment]
No worries and I understand you being busy. Thanks for your help though. Whenever you are free works for me. @Shane32

**Comment by Shane32** [comment]
Well the easiest thing would be to create a static AsyncLocal variable on the controller.

```cs
public readonly static AsyncLocal<LogTimer> LocalLogTimer = new AsyncLocal<LogTimer>();
```

Then before calling ExecuteAsync be sure you initialize LocalLogTimer.
```cs
LocalLogTimer.Value = logTimer;
```

Then within the Fetch delegate you can just set that value (as the AsyncLocal is static):
```cs
MyController.LocalLogTimer.Value.LogMessage = dumpRequest;
```

It's a bit of a hack, but it actually works the same as a DataLoaderContextAccessor or a HttpContextAccessor.  Look up the source code if you're interested, or read about AsyncLocal on MS's website.  It's fully multithreaded capable, by the way, unlike a simple static variable.  You can of course make a dummy class like `DumpRequestInfo` if you don't want to load the whole log in there, but what you can't do is use `AsyncLocal<string>` and just set the string.  Hard to explain, but if you read up on AsyncLocal you'll understand why.

You can also change the definition of the dataloader to load in a tuple of type `(IRequest, IResolveFieldContext)` or `(IRequest, Dictionary<string, object>)` (a user context) or something like that.  Then you just store the dumprequest in the usercontext or in the dumprequestinfo.  Maybe you put the LogTimer in the user context so you can access it directly.  Finally, you could add it as an output, so instead of outputting just the response, it outputs a tuple like `return (response, dumpRequest);` -- and then use `.Then()` as demonstrated above to store the dumprequest in the usercontext.

**Comment by Shane32** [comment]
In short, you're going to want to use either the UserContext or an AsyncLocal to hold the information.

**Comment by TechGeeky** [comment]
How about if I do like this - 

```
....
var dumpRequest = StringifiedRequest(processRequest);
_accessor.HttpContext.Items["dumpRequest"] = dumpRequest;
....
```

And then access like this in `ExecuteAsync` method - 

```
...
logTimer. logMessage = (string) context.Items["dumpRequest"];
....
``` 

Is this fine too? If not, then can you please provide the example for second case where I can change definition of dataloader to load in a tuple? I think that sounds good for my use case. I got slightly confuse on how to modify the signature of that and return accordingly.

**Comment by Shane32** [comment]
I don't see why that wouldn't work.

**Comment by TechGeeky** [comment]
Yeah it works fine but was just curious if that is the right way to do it or I did some hacky way to achieve that.

**Comment by Shane32** [comment]
seems fine to me.

**Comment by Shane32** [comment]
Just FYI if you look at how a HttpContextAccessor works, it's just a wrapper around AsyncLocal.  Pretty interesting.

https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http/HttpContextAccessor.cs

**Comment by TechGeeky** [comment]
Thanks @Shane32

**Comment by Shane32** [comment]
no problem.

**Comment by Shane32** [comment]
Oh one comment, be sure to put a lock around accessing the HttpContext.Items dictionary, as setting dictionary elements is not thread safe.  I guess that would be my biggest concern, is if another thread tried to load a dictionary element while your code was saving to the dictionary.

**Comment by Shane32** [comment]
(since you have no control over other code's use of HttpContext.Items)

**Comment by Shane32** [comment]
An easy to get around this is to create a thin wrapper to hold the data and store that in HttpContext.Items first, and only pull from HttpContext.Items within the data loader.

```cs
//controller
HttpContext.Items["log"] = new LogInfo();
//dataloader
HttpContext.Items["log"].Value = dump;

class LogInfo
{
    public string Value {get; set; }
|
```

**Comment by TechGeeky** [comment]
You mean only at the place where I put it in the dictionary? Something like this below or there is any better way?

```
private static readonly Object obj = new Object();

var dumpRequest = StringifiedRequest(processRequest);
lock(obj) {
    _accessor.HttpContext.Items["dumpRequest"] = dumpRequest;
}
```

Also is there any way to avoid locking here. It can slow down performance I guess. Do you think modify definition of dataloader to load in a tuple is best option here where locking isn't there?

**Comment by TechGeeky** [comment]
hmmm trying to understand your wrapper comment.

**Comment by Shane32** [comment]
I would lock on the dictionary, so the lock is unique per request, which won't hurt performance.
```cs
lock(_accessor.HttpContext.Items) {
    _accessor.HttpContext.Items["dumpRequest"] = dumpRequest;
}
```

The sample above with the LogInfo class doesn't use locking...but it does cause a dictionary write for every request even if you don't need to do it.  That probably is slower than the locking sample above, but more fool-proof.

**Comment by Shane32** [comment]
I'll try to demonstrate:
```cs
            context.Items["dumpRequest"] = new DumpRequestInfo();
            var result = await _executer.ExecuteAsync(opts =>
            (...)
```
Add this:
```cs
public class DumpRequestInfo
{
    public string Value { get; set; }
}
```
Then in the fetch delegate, no lock:
```cs
_accessor.HttpContext.Items["dumpRequest"].Value = dumpRequest;
```

**Comment by Shane32** [comment]
now within the parallel GraphQL execution there's only concurrent reads from HttpContext.Items, which is fully supported.  It reads an instance of DumpRequestInfo and sets a variable.  Even if two threads tried to write to Value at the same time, it wouldn't break anything.

**Comment by Shane32** [comment]
anyway, lots of different options there.

**Comment by TechGeeky** [comment]
So you will recommend doing this instead of locking? 

Also I will set it like this then right?

```
logTimer.StatusCode = context.Response.StatusCode;
logTimer.logMessage = (string) context.Items["dumpRequest"].Value;
```

**Comment by Shane32** [comment]
```cs
logTimer.logMessage = ((DumpRequestInfo)context.Items["dumpRequest"]).Value;
```
I would, but it's honestly a toss-up.  I'd probably use an AsyncLocal directly because it's strongly typed.

**Comment by Shane32** [comment]
I'll leave the issue open for now, but please close it when you're done - thanks!

**Comment by TechGeeky** [comment]
Thanks @Shane32. I will for sure.

**Comment by TechGeeky** [comment]
Quick question - I notice when I try this in fetch delegate, it gives error on `Value` which makes sense so I need to cast it right?

It says - `Cannot resolve symbol 'Value'`

```
_accessor.HttpContext.Items["dumpRequest"].Value = dumpRequest;
```

**Comment by Shane32** [comment]
Looks good
