### ISSUE TITLE
Is it possible to monitor Graphql.NET performance via .Net Runtime Metrics in Datadog?

### ISSUE THREAD

**Issue by jbarbacena** [graphql-dotnet/graphql-dotnet#2585]
We've successfully tracing Graphql.NET via dd-trace but we want to trace it thru .Net Runtime Metrics. is it possible?

**Comment by sungam3r** [comment]
What is ".Net Runtime Metrics" ? PerformanceCounters ? EventCounters ?

**Comment by sungam3r** [comment]
GraphQL.NET support Apollo Tracing, also see `InstrumentFieldsMiddleware`. I closed this issue due to lack of feedback.
