### ISSUE TITLE
GraphQL API response is strange

### ISSUE THREAD

**Issue by mantascaroxana** [graphql-dotnet/graphql-dotnet#2586]
Hello there, 

I've implemented a GraphQl API and I'm returning response.Data. The mainly problem here is that in Postman the response looks like this:
![image](https://user-images.githubusercontent.com/29401023/124500574-af596080-ddc8-11eb-8738-485c8dc05454.png)
And as I've seen while debugging, on Data the Field is null and the field I'm querying is under SubFields.
![image](https://user-images.githubusercontent.com/29401023/124500710-ea5b9400-ddc8-11eb-93c1-ea081cabf1f1.png)
Has anybody encountered this problem before? I verified everything and I can't really find the problem.
Thank you.

**Comment by Shane32** [comment]
I would guess that the response isn’t being serialized by a document writer (either GraphQL.SystemTextJson or GraphQL.NewtonsoftJson). This is mandatory in version 4 of GraphQL since the response object won’t serialize correctly if passed directly to a JSON serializer.

**Comment by Shane32** [comment]
See https://graphql-dotnet.github.io/docs/guides/serialization

**Comment by mantascaroxana** [comment]
Thank you very much, the doc helped.

**Comment by Shane32** [comment]
Please re-open the issue if you need further assistance.
