### ISSUE TITLE
Relay example

### ISSUE THREAD

**Issue by fiyazbinhasan** [graphql-dotnet/graphql-dotnet#2593]
Looks like the relay document lacks an example.

![image](https://user-images.githubusercontent.com/6568968/124886366-fbd5b380-dff5-11eb-81c6-db8bb62779c5.png)

Can this be added as a reference?

https://fiyazhasan.me/graphql-with-net-core-part-xii-relay/

@Shane32 @joemcbride

**Comment by Shane32** [comment]
Sure; can you post a PR ?
