### ISSUE TITLE
AutoRegisteringObjectGraphType<> doesnt create default expression resolvers for the auto generated fields?

### ISSUE THREAD

**Issue by truptivishe-gep** [graphql-dotnet/graphql-dotnet#2594]
Does AutoRegisteringObjectGraphType<> not create the default expression resolvers for the auto generated fields?
If not ,then how do we update these fields? 

My scenario is that I'm creating the corresponding graphtypes at runtime using classes that are dynamically created at run time. I'm having these runtime created graphtypes inherit from AutoRegisteringObjectGraphType<>. I guess that since the resolvers for these fields are missing,graphql is not able to filter these fields from the output. 

Is there a way by which I can programmatically update the expression resolvers for these autogenerated fields after the graphtype has been generated at runtime?

**Comment by truptivishe-gep** [comment]
Is there no way to have AutoRegisteringObjectGraphType generate the default resolver?

**Comment by Shane32** [comment]
I’m not sure what your question is. For the fields it auto creates, yes it creates resolvers for them.

**Comment by truptivishe-gep** [comment]
The resolvers are not getting created for me when I'm generating the class in the below manner :

My main method -
`
Type dataModelType = dataModelTypes.GetValueOrDefault(classSchema.Key);
TypeBuilder typeBuilder = CreateClassBuilder(classSchema.Key, dataModelType);
CreateConstructor(typeBuilder);
Type type = typeBuilder.CreateType();
`

Other methods to generate the graphQL type class - 

`
        private TypeBuilder CreateClassBuilder(string className, Type classType)
        {
            TypeBuilder typeBuilder = moduleBuilder.DefineType(className + "GraphType"
                                , TypeAttributes.Public |
                                TypeAttributes.Class |
                                TypeAttributes.AutoClass |
                                TypeAttributes.AnsiClass |
                                TypeAttributes.BeforeFieldInit |
                                TypeAttributes.AutoLayout
                                , null);
            typeBuilder.SetParent(typeof(AutoRegisteringObjectGraphType<>).MakeGenericType(classType));
            //typeBuilder.SetParent(typeof(ObjectGraphType<>).MakeGenericType(classType));
            return typeBuilder;
        }

        private void CreateConstructor(TypeBuilder typeBuilder)
        {
            typeBuilder.DefineDefaultConstructor(MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName);
        }
`

After registering the mapping for these classes in the Schema, when I check the Schma->AllTypes->the fieldtypes generated for these do not contain the resolvers

**Comment by Shane32** [comment]
Are you saying that the Resolver property for the field is null? That’s normal. During execution, fields with a null resolver property will resolve the field by matching the field name to a property of the context.Source - which is what the AutoRegisteringObjectGraphType used to create the field to begin with. So it will resolve properly even though the resolver property is null.

**Comment by truptivishe-gep** [comment]
Ohkay...thanks for explaining! I'm new to graphql so am in the initial stages of exploring things.
My graphql api isn't filtering the subfields stated in the query and is instead returning all properties of the mapped graph type. Therefore I thought that the issue might be due to the Resolver property for the fields being null.

Thanks again! I might be missing something else then.

**Comment by Shane32** [comment]
Closing this issue.  Please re-open if you have further questions along this line.
