### ISSUE TITLE
Database connection optimization

### ISSUE THREAD

**Issue by vikassharma5981** [graphql-dotnet/graphql-dotnet#2598]
Summary
We are using graphql-dotnet, we are using SQL Server as the backend. We create a complex query

query($params: request!){
  salesOrderList(request: $params) {
    carrier
    customerName
    orderLineItem {
         lineNumber
      orderedItem
       }
    customData
    {
        name
    }
  }
}

What happens is, when we invoke this query, if there is more than 1 item in the nested query, each time a new connection is created and the database is hit.

We want to reduce that connection creation and use a common connection for the scope of a query.

Can someone please guide me?
We are using GraphQL 3.2.

**Comment by Shane32** [comment]
A common solution is to use a data loader to resolve the 'orderedItem' and/or 'orderLineItem' fields, so that all of the data per-level is grouped into a single call to the database.

See: https://graphql-dotnet.github.io/docs/guides/dataloader

In your case, I would have the 'orderLineItem' field return a `CollectionBatchDataLoader` keyed on the id if the `salesOrder` (e.g. `salesOrder.Id`), and I'd have the 'orderedItem' field return a `BatchDataLoader` keyed on the id of the `orderedItem` (e.g. `orderLineItem.OrderedItemId`).

**Comment by Shane32** [comment]
The above suggestion should result in 3 calls to the database for the above query, no matter how many salesOrders, orderLineItems or orderedItems are returned.

As for reducing the actual number of connections to the database, usually this is handled by your ORM or underlying database technology.  For instance, Entity Framework should automatically handle this for you.  You might also read up on ADO.Net SQL connection pooling here: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling

For Entity Framework Core, you can also pool the dbcontext, but this doesn't have to do with pooling the SQL connection itself.  Performance gains are stated to be minimal.  See https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontextpool?view=efcore-5.0

**Comment by vikassharma5981** [comment]
Thanks for your response, sorry for the delayed response.
I have one more question though, how can I pass multiple parameters in the Dataloader query?
For instance: I need orderType, country, pageSize as parameters how can I pass them as a Dataloade query?
```
Field<ListGraphType<CustomFieldType>, IEnumerable<CustomFields>>()
                           .Name("customFields")
                           .ResolveAsync(ctx =>
                           {
                               var loader = accessor.Context.GetOrAddCollectionBatchLoader<string, CustomFields>("GetOrderCustomField", salesOrderRepository.GetCustomField);
                               return loader.LoadAsync(new string[] { "2", "2" });
                           });
```
Not sure if this is the right approach or not?

**Comment by Shane32** [comment]
Use a valuetuple as the key. It should work very well, although you may find that programming the data loader to be useful in this case is quite challenging.

**Comment by vikassharma5981** [comment]
I tried using ValueTupple but that did not go well with my requirements, I had to do a dirty of concatenating params and pass them as parameters and then performing the action.
Somehow it works but not in an efficient way though, any reference/inputs might help here.

**Comment by Shane32** [comment]
I can’t help more without a more complete sample

**Comment by Shane32** [comment]
Please re-open if you have further questions on this topic, or if you can provide a more complete sample.
