### ISSUE TITLE
How to fix error: FuncFieldResolver<Message>?

### ISSUE THREAD

**Issue by Oleg26Dev** [graphql-dotnet/graphql-dotnet#2609]
I have a small ASP.NET Core 3.1. server + GraphQL NuGet.
When I used GraphQL NuGet v3 - it worked, but after update to the latest v4.5 I cannot compile it
```
        public AuthorSubscription(IAuthor authordetails)
        {
            _author = authordetails;

            AddField(new EventStreamFieldType
            {
                Name = "authorAdded",
                Type = typeof(MessageType),
                Resolver = new FuncFieldResolver<Message>(ResolveAuthor),//<----
                Subscriber = new EventStreamResolver<Message>(Subscribe)//<----
            });
        }

```

There are errors:
 error CS1503: Argument 1: cannot convert from 'method group' to 'Func<IResolveFieldContext, Message>'

How to fix it?

**Comment by Shane32** [comment]
Can you post the signature of the `ResolveAuthor` and `Subscribe` methods in your class?  Offhand I do not know why a change would be needed.

**Comment by Shane32** [comment]
Closed due to lack of information.  Please re-open if you can provide additional details.
