### ISSUE TITLE
How to properly use "UnhandledExceptionDelegate" in GraphQLMiddleware "ExecuteAsync" class?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2615]
I am working on investigating a weird issue which is happening in below code. I am seeing NRE being thrown where `HttpContext` is null. 

I have below `ExecuteAsync` code in my GraphQL middleware class - 

    private async Task ExecuteAsync(HttpContext context, ISchema schema)
    {
        var loggingService = context.RequestServices.GetService<ILoggingService>();
        var loggingContext = new LoggingContext(context.Request.Headers);
        context.Items["logRequest"] = new RequestInfo();
        using (var logTimer = new LogTimer(loggingService, loggingContext, "Debug Logs", GetEndpoint(context), "start"))
        {
            try
            {
                var request = Deserialize<GraphQLRequest>(context.Request.Body);
                var result = await _executer.ExecuteAsync(opts =>
                {
                    opts.Schema = schema;
                    opts.Query = request?.Query;
                    opts.OperationName = request?.OperationName;
                    opts.Inputs = request?.Variables.ToInputs();
                    opts.RequestServices = context.RequestServices;
                    opts.UserContext = _settings.BuildUserContext?.Invoke(context);
                    opts.ValidationRules = DocumentValidator.CoreRules.Concat(new[] { new InputValidationRule() });
                    opts.EnableMetrics = _settings.EnableMetrics;
                    if (_settings.EnableMetrics)
                    {
                        opts.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
                    }
                    opts.UnhandledExceptionDelegate = async ctx =>
                    {
                        // called from here when that NRE exception happens.
                        await HandleErrors(context, ctx.Exception, loggingService, loggingContext);
                    };
                });
                await WriteResponseAsync(context, result);
                logTimer.StatusCode = context.Response.StatusCode;
                logTimer.Message = ((RequestInfo)context.Items["logRequest"]).Value;
            }
            catch (Exception ex)
            {
                await HandleErrors(context, ex, loggingService, loggingContext);
                logTimer.StatusCode = context.Response.StatusCode;
                logTimer.Message = ((RequestInfo)context.Items["logRequest"]).Value;
            }
        }
    }

And below is my `HandleErrors` method -

    private async Task HandleErrors(HttpContext context, Exception ex, ILoggingService loggingService, LoggingContext loggingContext)
    {
        if (ex == null)
        {
            // log here
            return;
        }
        int statusCode;
        var title = "GraphQLMiddleware";
        var error = ex.Source;
        var message = ex.Message;
        var stackTrace = ex.StackTrace;
        string eventName = null;
        switch (ex)
        {
            // bunch of cases here
            default:
                message = $"Exception handling: {ex.Message}";
                statusCode = StatusCodes.Status500InternalServerError;
                eventName = "Default Exception";
                break;
        }
        // log error here
        // now this below line throws exception as "System.NullReferenceException" and I am confuse why?
        context.Response.StatusCode = statusCode;
    }

Whenever below line is called in `ExecuteAsync` method and then it calls `HandleErrors` method which throws exception at `context.Response.StatusCode = statusCode` where I am confuse why it could do that?

    opts.UnhandledExceptionDelegate = async ctx =>
    {
        // called from here when that exception happens.
        await HandleErrors(context, ctx.Exception, loggingService, loggingContext);
    };

Is it because it is synchronous and had to be done that way? I see GQL doesn't support async for "UnhandledExceptionDelegate"

**Comment by Shane32** [comment]
`UnhandledExceptionDelegate` is a synchronous delegate, not asynchronous.  So when you assign it to an async lambda, you're basically doing this:
```cs
opts.UnhandledExceptionDelegate = MyHandler;

async void MyHandler(UnhandledExceptionContext context)
{
    await HandleErrors(context, context.Exception, loggingService, loggingContext);
}
```

and since that method is `async void` it doesn't get awaited.

Visual Studio really should show a warning in this scenario because it's not immediately obvious.

**Comment by TechGeeky** [comment]
@Shane32 Aah that make sense so how can we fix this in a proper way? Sorry for stupid question. I have been scratching my head since morning.

**Comment by Shane32** [comment]
This would be a great feature for v5, to have async support for UnhandledExceptionDelegate.

There's three ways now:
(1) make the method synchronous, and use synchronous calls to your database or other services
(2) call the async method and call `.GetAwaiter().GetResult()` or `.Wait()` on it, but this is not generally recommended
(3) create a scope for the async method; see below:

```cs
private void HandleErrors(HttpContext context, Exception ex, LoggingContext loggingContext)
{
    // no async code in this method!!
    if (ex == null)
    {
        // log here asynchronously (at same time that the rest of this method executes)
        LogErrorAsync();
        return;
    }
    int statusCode;
    var title = "GraphQLMiddleware";
    var error = ex.Source;
    var message = ex.Message;
    var stackTrace = ex.StackTrace;
    string eventName = null;
    switch (ex)
    {
        // bunch of cases here
        default:
            message = $"Exception handling: {ex.Message}";
            statusCode = StatusCodes.Status500InternalServerError;
            eventName = "Default Exception";
            break;
    }
    // log error here
    // now this below line throws exception as "System.NullReferenceException" and I am confuse why?
    context.Response.StatusCode = statusCode;

    async void LogErrorAsync()
    {
        // do not use ANY scoped services here
        // rather, create a scope which will live throughout this execution
        using (var scope = context.RequestServices.CreateScope())
        {
            // get all services from the local scope
            var localServices = scope.ServiceProvider;
            var loggingService = localServices.GetService<ILoggingService>();
            //log here
        }
        //note: you cannot return a value here because this method will have finished after the UnhandledExecutionDelegate has already finished
    }
}
```

**Comment by Shane32** [comment]
In this situation a static local function is better as it more clearly prevents accidental misuse of objects which will fall out of scope (such as the httpContext); so only pass in immutable objects to the LogErrorAsync method

**Comment by Shane32** [comment]
`ILoggingContext` should only contain immutable objects

**Comment by TechGeeky** [comment]
@Shane32 Are you recommending I should go with #3 instead of #1? If I go with 1 then do you see any issue? Let's say if I go with #1 then   code looks like below right?

So if I just go with point 1 then I just need to do this?

```
opts.UnhandledExceptionDelegate = ctx =>
{
    HandleErrors(context, ctx.Exception, loggingService, loggingContext);
};
```

**HandleError method -** 

```
private void HandleErrors(HttpContext context, Exception ex, LoggingContext loggingContext)
{
    // no async code in this method!!
    if (ex == null)
    {
        // log here normally? I am anyway logging everything synchronous
        return;
    }
    int statusCode;
    var title = "GraphQLMiddleware";
    var error = ex.Source;
    var message = ex.Message;
    var stackTrace = ex.StackTrace;
    string eventName = null;
    switch (ex)
    {
        // bunch of cases here
        default:
            message = $"Exception handling: {ex.Message}";
            statusCode = StatusCodes.Status500InternalServerError;
            eventName = "Default Exception";
            break;
    }
    // log error here
    // now this below line throws exception as "System.NullReferenceException" and I am confuse why?
    context.Response.StatusCode = statusCode;
}

```

**Comment by Shane32** [comment]
option 1 is the easiest for sure.  if you have no async/await then it will eliminate your problems.

**Comment by TechGeeky** [comment]
in my "HandleErrors" method I only have everything synchronous and I am not using any async call to anything.

**Comment by Shane32** [comment]
but if your ILoggingService only has async methods, then I would recommend option 3 (if it works for you).  you may be forced with option 2 if you must use async methods but need to return data from the logger through the response.

**Comment by Shane32** [comment]
then just try remove async/await and see if the bug is gone

**Comment by TechGeeky** [comment]
ILoggingService has all void methods and they don't have any async methods so I should be good I guess. But my confusion is why I saw this line throwing `context.Response.StatusCode = statusCode;` NRE? Any idea on that? I am trying to figure out a reason for that. It doesn't happen all the time but it did happen few times.

**Comment by Shane32** [comment]
it's because the async/await queued up the HandleErrors code to run at a later time.  ASP.Net will clear the http context when the execution stack is complete to prevent these types of coding errors from going unnoticed.

**Comment by Shane32** [comment]
So if the execution within HandleErrors runs quick enough, it will happen before ASP.Net clears the http context.  And you don't see any errors.  But if the OS runs the main execution thread faster than than the HandleErrors thread, then ASP.Net clears the http context before HandleErrors gets to that line of code.

**Comment by Shane32** [comment]
`async void` is very tricky to use correctly.

**Comment by Shane32** [comment]
It's really quite fortunate that ASP.Net does cause this exception.  Because if it didn't, most likely the service provider would be disposed of around the same time, which would include EF or any other scoped objects pulled from DI, potentially terminating the logging action of the method before it completed.

**Comment by Shane32** [comment]
keep in mind that it's not `context` that is null causing the NRE.  It's `context.Response` that's null (due to the contents of `context` being reset by ASP.Net).

**Comment by Shane32** [comment]
GraphQL.Net also re-uses `IResolveFieldContext` objects in a similar manner.  If you call a `async void` method from within a field resolver, the context will likely be re-used for another field before the `async void` method completes.  See https://graphql-dotnet.github.io/docs/migrations/migration4#code-classlanguage-textiresolvefieldcontextcode-re-use

**Comment by Shane32** [comment]
I opened a new issue for the feature request to allow async unhandled exception delegate.  I suggest closing this issue at your leisure.

**Comment by TechGeeky** [comment]
I see. Thanks for all the details. Is there a documentation around where it is mentioned "UnhandledExceptionDelegate" is synchronous?

**Comment by Shane32** [comment]
https://graphql-dotnet.github.io/docs/getting-started/errors#a-nameprocessingerrorsaprocessing-errors covers the use of the delegate and has an example.  It does not specifically say that it is synchronous, but the property is typed as `Action<UnhandledExceptionContext>`, which is not async.  If it was async, it would be `Func<UnhandledExceptionContext, Task>`.

**Comment by TechGeeky** [comment]
Thanks @Shane32. So I am gonna go with below code then by removing async/await altogether- 

```
opts.UnhandledExceptionDelegate = ctx =>
{
    HandleErrors(context, ctx.Exception, loggingService, loggingContext);
};
```

**HandleError method -**

```
private void HandleErrors(HttpContext context, Exception ex, LoggingContext loggingContext)
{
    // no async code in this method!!
    if (ex == null)
    {
        // log here normally? I am anyway logging everything synchronous
        return;
    }
    int statusCode;
    var title = "GraphQLMiddleware";
    var error = ex.Source;
    var message = ex.Message;
    var stackTrace = ex.StackTrace;
    string eventName = null;
    switch (ex)
    {
        // bunch of cases here
        default:
            message = $"Exception handling: {ex.Message}";
            statusCode = StatusCodes.Status500InternalServerError;
            eventName = "Default Exception";
            break;
    }
    // log error here
    // now this below line throws exception as "System.NullReferenceException" and I am confuse why?
    context.Response.StatusCode = statusCode;
}
```

**Comment by TechGeeky** [comment]
@Shane32 One last question - As you can see in my "ExecuteAsync" method I have a global catch block which catches all exception and I also have this block where I was earlier using "async" - 

```
opts.UnhandledExceptionDelegate = async ctx =>
  {
      // called from here when that NRE exception happens.
      await HandleErrors(context, ctx.Exception, loggingService, loggingContext);
  };
```

Do you think I really need this "opts.UnhandledExceptionDelegate" block of code to log and handle exception? All exceptions can go into catch block as well right if I remove that "UnhandledExceptionDelegate" delegate call? And anyway I have same logic to log and handle exception in catch block?

**Comment by Shane32** [comment]
Yes you do need it, unless you set `ThrowOnUnhandledException` to `true`.  When set to the default of `false`, exceptions that occur within field resolvers be added as errors to the returned `ExecutionResult` and are not re-thrown.

For your situation, as it seems you plan to return a 500 error when a server-side error occurs (which is fine), I would suggest changing `ThrowOnUnhandledException` to `true` and removing the delegate.

However, I can't see your various switch cases, so for example if you are changing various errors into friendly errors (and not returning a 500 error), then you must keep the delegate, since it executes on a per-field basis.

**Comment by TechGeeky** [comment]
That answers my question. Thanks @Shane32. Appreciate your help!

**Comment by TechGeeky** [comment]
@Shane32 We added the fix as we talked about few days back but we seeing the issue again in production coming from below stacktrace. We are still using the delegate as it is.

```
at GraphQLMiddleware.cs:line 214 (this is our "context.Response.StatusCode = statusCode;" line)
   at GraphQL.Execution.ExecutionStrategy.ProcessNodeUnhandledException(ExecutionContext context, ExecutionNode node, Exception ex) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 316
   at GraphQL.Execution.ExecutionStrategy.CompleteDataLoaderNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 239
   at GraphQL.Execution.ParallelExecutionStrategy.ExecuteNodeTreeAsync(ExecutionContext context, ExecutionNode rootNode) in /_/src/GraphQL/Execution/ParallelExecutionStrategy.cs:line 63
   at GraphQL.Execution.ExecutionStrategy.ExecuteAsync(ExecutionContext context) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 31
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 223
   ```

And this as well - 

```
at GraphQLMiddleware.cs:line 214 (this is our "context.Response.StatusCode = statusCode;" line)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 261
at GraphQLMiddleware.cs:line 112
```

So mainly it is coming from either `DocumentExecuter.cs:line 261` or `DocumentExecuter.cs:line 223`. Any idea what could be the reason?

This is our code in "UnhandledExceptionDelegate" where we added one extra thing and `HandleErrors` method is same as it is.

```
opts.UnhandledExceptionDelegate = ctx =>
{
// below if code is new code we added
if (ctx.Exception is OverflowException of)
{
    throw new AppDeserializationException(StatusCodes.Status204NoContent, of.Message, null);
}
    HandleErrors(context, ctx.Exception, loggingService, loggingContext);
};
```

**Comment by TechGeeky** [comment]
Opening a new one instead - https://github.com/graphql-dotnet/graphql-dotnet/issues/2635
