### ISSUE TITLE
Allow async UnhandledExceptionDelegate method

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2616]
See #2615 

Suggest to change:

https://github.com/graphql-dotnet/graphql-dotnet/blob/419a558cf76adb5636fb1cc6bc1aae99b31773f1/src/GraphQL/Execution/ExecutionOptions.cs#L66

to:

```cs
public Func<UnhandledExceptionContext, Task> UnhandledExceptionDelegate { get; set; } = context => Task.CompletedTask;
```

**Comment by TechGeeky** [comment]
@Shane32 Any thoughts on when can we get this feature out? We want to use this feature instead of adding some ways around to fix our code.

**Comment by Shane32** [comment]
This is a breaking change and needs to go in v5. I just released the last planned version of v4 but I would not expect v5 to be ready for a few months at least. I’m pretty busy and at present there’s no other active developers here unfortunately. If you’d like to make a PR it would be greatly appreciated.

**Comment by sungam3r** [comment]
Will be released in v5.
