### ISSUE TITLE
Upgrade from xproj/project.json to csproj

### ISSUE THREAD

**Issue by cable729** [graphql-dotnet/graphql-dotnet#262]
The .NET Core SDK preview 3 alpha was released on November 16th, and reached final stage on December 13th. This release introduced the new .csproj files (read about them here https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/). Basically, file blobs are a thing in .csproj, and dependencies on packages, libraries, and projects are now all rolled up in .csproj.

We should upgrade all projects to use the new format. This seems like an easy task, so I'd be happy to handle it if there are no concerns.

Edit: also, xproj/project.json files cannot be opened in VS2017 anymore. They require migration first.

**Comment by joemcbride** [comment]
I think the other major part will be possibly needing to upgrade the build process to not use `dotnet.exe` to pack the nuget.  I haven't looked at what will be needed for that yet or if `dotnet.exe` is still supported for nuget packing with the `.csproj` format.  We may need to switch back to `nuget.exe` or use something else.

I think my work is also keeping with `project.json` currently so could be a harder switch for me.

**Comment by cable729** [comment]
@joemcbride looks like it is still possible: https://github.com/dotnet/cli/issues/4765

And for your work, I'm not sure what to recommend. It would be nice to be able to work on this project in VS 2017. Upgrading to .csproj would allow work to be done on this project in VS Code, VS 2015, and VS 2017.

**Comment by joemcbride** [comment]
Great news, thanks!  I currently use Rider and VSCode.  I don't think the "older" GraphiQL project works in VSCode or Rider (I've been meaning to update it), but the core project does.  I think the trick is to still have the "older" dotnet core exe installed.  I'm currently running `1.0.0-preview2-003131`.

**Comment by joemcbride** [comment]
Closing this as it is now complete.
