### ISSUE TITLE
dynamically create object type and schema

### ISSUE THREAD

**Issue by psinghms** [graphql-dotnet/graphql-dotnet#2620]
Do you have any sample code where I can dynamically create schema/QueryType for each table. I have the code to get the table properties(like column and its type) . I would like to generate the object type dynamically and create schema. Please let me know if this is possible

**Comment by Shane32** [comment]
Many of the examples show how to create a schema from code. Just call the Schema constructor, then set Query or Mutation to an instance of ObjectGraphType. Add fields to the type as desired, and set arguments and etc on those fields. To make this process easier, I would suggest using type references and letting the schema resolve these references while the schema is being built. As long as you have registered a matching type in the schema, it should be taken care of. 

See:
- https://graphql-dotnet.github.io/docs/getting-started/schema-types#type-mapping
- https://graphql-dotnet.github.io/docs/getting-started/schema-types#type-references

**Comment by psinghms** [comment]
Are you referring to these examples 
https://github.com/graphql-dotnet/examples/tree/master/src

**Comment by sungam3r** [comment]
Probably yes. You can also find a lot of examples in tests. Closed as answered.
