### ISSUE TITLE
Documentation explorer not loaded in Chrome

### ISSUE THREAD

**Issue by joelpinheiro** [graphql-dotnet/graphql-dotnet#2622]
## Description

Can't open the GraphiQL API docs in Google Chrome (v92.0.4515.107). 
The API docs keep loading but they aren't rendered.

Works fine in Safari though.

Edit:
It worked fine after I delete all the cookies. So it seems it has something to do with the past queries? It should render the docs thought.

Google Chrome (v92.0.4515.107):
<img src="https://screenshot.click/10-14-qky3y-hl9gd.png" class="img-responsive" alt=""> </div>

Safari (v14.1.1):
<img src="https://screenshot.click/10-21-pskcw-fejzv.png" class="img-responsive" alt=""> </div>

### Steps to reproduce

Just open the /grahiql and you'll be able to reproduce it.

### Expected result

Should open the Documentation Explorer successfully in Chrome.

### Actual result

Documentation Explorer is not loading the actual documentation.

### Environment

MacOS BigSur 11.4
Google Chrome (v92.0.4515.107)

**Comment by sungam3r** [comment]
Closed due to inactivity.
