### ISSUE TITLE
Error while initializing and using variables only within code

### ISSUE THREAD

**Issue by giy** [graphql-dotnet/graphql-dotnet#2629]
## Summary
Hello, I was recently trying to upgrade from GraphQL 3.3 => 4.5.0 and GraphQL-Dotnet 4.2.0 => 5.0.2 and I'm seeing an error while trying to use variables.
I've added the information below and thank you very much in advance for the assistance!

## Relevant information
The error I see is,
```
System.InvalidOperationException: Cannot add variables to this instance.\n   at GraphQL.Language.AST.Variables.NoVariables.Add(Variable variable) in /_/src/GraphQL/Language/AST/Variables.cs:line 79\n
```

I believe context.Variable is set to NoVariables with the update due to which for some reason, it's not working like the way it did before and I'm a little lost.

The reason I'm trying to upgrade is to get some of the efficiency improvements and get access to context.Parent which was added in this version hoping it helps me with some of the nuances I'm facing on a particular project. based on a previous thread where I was helped with passing params down a tree.

In my GraphQLMiddleware, I've defined,
```
var result = await _executer.ExecuteAsync(opts =>
{
    opts.Schema = schema;
    opts.Query = request?.Query;
    opts.OperationName = request?.OperationName;
    opts.Inputs = request?.Variables.ToInputs();
    .....
}

```

So, I would expect it to accept variables.

The line my code fails on is,
```
context.Variables.Add(
  new Variable
  {
      Name = "varName",
      Value = value
  });
```

It does work if I try to do add a dummy variable while testing (All the requests that come in don't pass any),
```
query abcd($varName: String!)
```
However, I am dealing with a legacy application where I cannot change the graphql signatures/ requests and it doesn't pass me any variables.
What would you suggest so that I can initialize and add Variables within my code (i.e. TypeClasses) even if there are no variables passed from the request ? 

Thank you.

### Environment (if relevant)
I believe this is the change that introduces this behavior,
https://github.com/graphql-dotnet/graphql-dotnet/pull/2186/files#diff-8b390ba13f102c2bb874be636bbcc8918a97bd431b2b22bb67498c0ce6ef6553R79
So, I didn't face this earlier because I was on version before 4.0 but ideally, I'd like to update as well.

**Comment by Shane32** [comment]
Would using the `UserContext` dictionary work?  If I understand your use case, you're trying to pass information from the resolve method of one node to its children and/or siblings.  Assuming this is so, `Variables` is designed only for the input variables passed from the GraphQL request, whereas `UserContext` is designed to hold user defined information, exactly for purposes like this.  By writing to the `Variables` property you can potentially overwrite variables passed from the caller, causing unintended side effects.

Keep in mind also that writing to a dictionary is not a thread-safe operation, so you should use a serial execution strategy or initialize the user context with a `ConcurrentDictionary` instance.

**Comment by Shane32** [comment]
Please see my comments of the same nature here:
- #2614 

If there is another reason why you need to write to `Variables`, please let me know and I can offer another suggestion.

**Comment by giy** [comment]
Thanks a lot Shane for all the previous responses and for helping me again!

I am using UserContext too, based on your suggestion for one specific case which is instance specific, but in this case, they're all settings specific to the HttpContext or ExecutionContext.

The front-end client guarantees the ordering of the fields the way they're setup, so from a Variable perspective its working correctly and pretty well but I cannot change their graphql queries at this time.

In my use-case, I have hundreds of fields that we need to resolve, and I can't map them all on the Class itself because depending on settings that could be passed in by the client (marketing/ discounts/ restrictions for e.g.) and properties on the SKU I'll need to change certain things on the fly.

I was initially not sure about using QueryArguments or Variables, but based on this thread,
https://github.com/graphql-dotnet/graphql-dotnet/issues/1426
I inferred that since QueryArguments only allow Name and DefaultValues (provided by the user), in this case it made sense to use Variables since it's not something I need to take in from the user, but based on the property of the class (context.Source.someProperty), I need to pass this down to the children/ sibling classes.

You're completely right though that the real problem that I'm trying to get my head around is passing arguments down the tree in a clean way.

Given, that I've already started with Variables and that's working well, could you please offer a suggestion for how I can continue to use Variables (get around NoVariables) when they're not passed in by the client ?

Thanks again for taking the time to respond!

I can also add a better/detailed example below if that'd be helpful since I'd be grateful to get this right before I need to add a lot more new calcs/ logic.

**Comment by Shane32** [comment]
Well, I still don't understand why `UserContext` does not fulfill your use case.  Especially if the data is specific to the `HttpContext` or `ExecutionContext`.  But to answer your question, here's a couple methods:

1. Create a document execution listener, and within `AfterValidationAsync`, execute this:

```cs
if (context.Variables == Variables.None)
{
    ((ExecutionContext)context).Variables = new Variables();
}
```

2. Create your own `DocumentExecuter` which adds one line of code:

```cs
//existing
using (metrics.Subject("document", "Validating document"))
{
    (validationResult, variables) = await _documentValidator.ValidateAsync(
        options.Schema,
        document,
        operation.Variables,
        validationRules,
        options.UserContext,
        options.Inputs);
}
//add this line
if (variables == Variables.None) variables = new Variables();
```

**Comment by Shane32** [comment]
Keep in mind that `Variables` may not be writable at all in future versions of GraphQL.NET.

**Comment by giy** [comment]
Thanks a lot again Shane for the quick and detailed explanations.

I tried both approaches and given that you've alluded to Variables not being writeable I'm going with the UserContext approach. Sorry, from the name UserContext initially when I was new to the library it wasn't very intuitive to me that this IDictionaryImplementation is specifically for use-cases related to the Execution or HttpContext such as mine, and I'm now embarking on using this instead of my Variables implementation as suggested.

I had a couple of questions,
In https://github.com/graphql-dotnet/graphql-dotnet/issues/2614
you'd mentioned,
`
The cache could be limited to the request, rather than a long-lived cache, and could be implemented via serial execution and the context.UserContext property, or for parallel execution, by adding a ConcurrentDictionary instance to the user context before execution, then manipulating the concurrent dictionary at runtime. Of course there are fancier ways, such as encapsulating the logic within a service, and storing the concurrent dictionary within an AsyncLocal<> created by a document listener. Or more simply, a scoped service that has the concurrent dictionary created in its constructor.
`

1. I'm guessing that this means I can also cache the results of intermediate executions within UserContext or a ConcurrentDictionary. Is my understanding correct ?


Right now, I've changed my code to do something like this instead,
```
public class GraphQLUserContext : Dictionary<string, object>
    {
        public ClaimsPrincipal User { get; set; }
        public ConcurrentDictionary<string, object> RequestContext { get; set; }
    }
```

```
app.UseMiddleware<GraphQLMiddleware>(new GraphQLSettings
  {
      Path = "/graphql",
      BuildUserContext = ctx => new GraphQLUserContext
      {
          User = ctx.User,
          RequestContext = new ConcurrentDictionary<string, object>()
      },
      EnableMetrics = false
  });
```

```
((GraphQLUserContext)context.UserContext).RequestContext.TryAdd("propertyOfInterest",
                    context.Source.SKU.TheProperty);
....somewhere in the children
((GraphQLUserContext)context.UserContext).RequestContext.TryGetValue("propertyOfInterest", out var propertyOfInterest);
```


2. I was wondering if I can change GraphQLUserContext itself to a ConcurrentDictionary so I can just add directly to UserContext and if so how can I hook that up ?
That allows me to do something like this instead,
```
context.UserContext.TryGetValue("propertyOfInterest", out var propertyOfInterest);
```
Or should I just go with the RequestContext approach ?

As always, I'm grateful for any feedback if I'm doing something the way it wasn't supposed to, and make changes on my side. Thanks a lot again!

**Comment by Shane32** [comment]
Yes you're right on point on both accounts.  Note that with the second approach, some methods like `GetOrAdd` will still require a cast since they are not part of `IDictionary<string, object>` (but you don't have to use these methods):

```cs
((ConcurrentDictionary<string, object>)context.UserContext).GetOrAdd(...);
```

Here's a trick that I use in such scenarios to eliminate the cast -- write an extension method:

```cs
static class MyExtensions
{
    public static GraphQLUserContext GetMyContext(this IResolveFieldContext context)
        => (GraphQLUserContext)context.UserContext;
}
```

Then you can access it simply by calling `context.GetMyContext()`.

**Comment by Shane32** [comment]
> Keep in mind that `Variables` may not be writable at all in future versions of GraphQL.NET.

I didn't mean that there's any current plans to change `Variables`, but I'm just saying that this is more of the 'internal workings' of GraphQL.NET and more subject to change than not, as you've already experienced when moving to 4.x.

I would personally like to 'lock down' more of the execution pipeline so that properties like `Variables` and schema properties are only read-only during execution, where writing to them is unintended and can adversely affect the execution or future executions.  But I am rather busy right now for such extensive changes.  (Most of the schema is writable at runtime right now.)

**Comment by giy** [comment]
Thanks again Shane for all the assistance. UserContext is working well for me, so I am happy to mark this question as resolved.
