### ISSUE TITLE
StringGraphType

### ISSUE THREAD

**Issue by benjmanning** [graphql-dotnet/graphql-dotnet#263]
We have seen some strange behaviour when using the StringGraphType.  We have found that if the returned string is a ```"``` then an Index out of range exception is thrown and shown in the ```errors``` property of the returned json object.

The issue can be replicated by adding the following to an existing graphql type:
```Field<StringGraphType>("mark", "The mark associated with this event", resolve: context => "\"");```

We have fixed the problem temporarily by creating a new graphtype object with the following code:
```
using GraphQL.Types;

namespace Firefly.GraphQL.GraphTypes.TaskResponseEventDetailsTypes
{
    internal class FireflyStringGraphType : StringGraphType
    {
        public override object Coerce(object value)
        {
            // Currently, GraphQL breaks if returning a solitary double quote
            if (value != null && value is string && (string)value == "\"")
            {
                return "";
            }

            return base.Coerce(value);
        }
    }
}
```

I did not have much luck in finding where in the graphql-dotnet source the problem is but would be happy to submit a fix if someone could point me in the right direction :)

**Comment by joemcbride** [comment]
This should be working with the latest Nuget.  What version are you currently on?  That `Coerce` syntax is fairly old (5-6 months ago).

**Comment by joemcbride** [comment]
Here is our test for that scenario: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Types/StringGraphTypeTests.cs#L34-L38

**Comment by joemcbride** [comment]
Going to go ahead and close this.  Let me know if the latest version doesn't work for you.
