### ISSUE TITLE
Partial updates for mutations with non-scalar input arguments

### ISSUE THREAD

**Issue by kamnyborg** [graphql-dotnet/graphql-dotnet#2633]
## Summary
Hi, I recently upgraded to GraphQL v4 from v3 (a bit late to the party..).
Previously I had the following code that worked perfectly fine for partial updates to database objects:

```
public void Resolve(IResolveFieldContext<object> context, WorkOrderOperationProgress progress)
        {
            var dynamicObject = context.GetArgument<dynamic>(GraphQLQueryArguments.UpdateWorkOrderOperation.Name);
            var json = JsonConvert.SerializeObject(dynamicObject);
            JsonConvert.PopulateObject(json, progress);
        }
```
(WorkOrderOperationProgress is an EF core entity)
The intention here is to avoid overwriting values on updates. The dynamic object previously (in v3) had only picked up the values that were sent in, but now it gets **all** fields w/values of the object (UpdateWorkOrderOperationInputType) - though with default values on those that are not set:

![image](https://user-images.githubusercontent.com/2311623/130229618-b07821bb-aa4c-4fc0-97fb-09831640f2a6.png)
In the screenshot above, "progression" is sent in as null, the requests looks like this:
`mutation { updateWorkOrderOperation (id: "b360f45e-a140-408d-bcaa-be689ca9aaa2", workOrderOperation: { progression: null }) { id progression finalConfirmation noRemainingWork confirmationText }}`

The issue here is that it's no longer possible to distinguish between partial updates (arguments not being sent in VS null-values being sent in) for **non-scalar input arguments**. For scalar types, we can simply check the IResolveFieldContext.HasArgument.

## (Relevant) information
```
public sealed class UpdateWorkOrderOperationInputType : InputObjectGraphType<UpdateWorkOrderOperationInput>
    {
        public UpdateWorkOrderOperationInputType()
        {
            Name = "updateworkorderoperation";
            Description = "Input type for updating work order operations";

            Field(_ => _.Progression, type: typeof(IntGraphType));
            Field(_ => _.ConfirmationText, type: typeof(StringGraphType));
            Field(_ => _.NoRemainingWork, type: typeof(BooleanGraphType));
            Field(_ => _.FinalConfirmation, type: typeof(BooleanGraphType));
        }
    }
```

```
public class UpdateWorkOrderOperationInput
    {
        public int? Progression { get; set; }

        public string ConfirmationText { get; set; }

        public bool? NoRemainingWork { get; set; }

        public bool? FinalConfirmation { get; set; }
    }
```

### Environment
ASP.NET Core 5.0 Web API
![image](https://user-images.githubusercontent.com/2311623/130230100-28391134-0f26-439a-8fae-a030e9d5a798.png)

**Comment by Shane32** [comment]
Override the ParseDictionary method of the input type and have the method return the dictionary that is passed to it. This should revert behavior for you. Let me know if you need additional assistance.

**Comment by kamnyborg** [comment]
Wow, can't believe I missed that in this guide https://graphql-dotnet.github.io/docs/migrations/migration4. 
It's working now, thanks a lot for the quick response :)

In case anyone is curious about the solution:

```
public sealed class UpdateWorkOrderOperationInputType : InputObjectGraphType<UpdateWorkOrderOperationInput>
    {
        public UpdateWorkOrderOperationInputType()
        {
            Name = "updateworkorderoperation";
            Description = "Input type for updating work order operations";

            Field(_ => _.Progression, type: typeof(IntGraphType));
            Field(_ => _.ConfirmationText, type: typeof(StringGraphType));
            Field(_ => _.NoRemainingWork, type: typeof(BooleanGraphType));
            Field(_ => _.FinalConfirmation, type: typeof(BooleanGraphType));
        }

        public override object ParseDictionary(IDictionary<string, object> dictionary)
        {
            return dictionary;
        }
    }
```

**Comment by alexssander-leal-luz** [comment]
> Wow, can't believe I missed that in this guide https://graphql-dotnet.github.io/docs/migrations/migration4. It's working now, thanks a lot for the quick response :)
> 
> In case anyone is curious about the solution:
> 
> ```
> public sealed class UpdateWorkOrderOperationInputType : InputObjectGraphType<UpdateWorkOrderOperationInput>
>     {
>         public UpdateWorkOrderOperationInputType()
>         {
>             Name = "updateworkorderoperation";
>             Description = "Input type for updating work order operations";
> 
>             Field(_ => _.Progression, type: typeof(IntGraphType));
>             Field(_ => _.ConfirmationText, type: typeof(StringGraphType));
>             Field(_ => _.NoRemainingWork, type: typeof(BooleanGraphType));
>             Field(_ => _.FinalConfirmation, type: typeof(BooleanGraphType));
>         }
> 
>         public override object ParseDictionary(IDictionary<string, object> dictionary)
>         {
>             return dictionary;
>         }
>     }
> ```

The override function works like a charm :D 
Thanks man \o
