### ISSUE TITLE
Still getting System.NullReferenceException in some case randomly, when interface is applied

### ISSUE THREAD

**Issue by diouxis** [graphql-dotnet/graphql-dotnet#2639]
## Description

The system throw the Object reference not set to an instance of an object. and the whole API doesn't work anymore.
Same issue reported before in #978 

I am using 4.5 and I can see some improvement was applied from last time I reported this issue, so I start to use the node interface feature back again. 
It is much better than before, last time the whole application must be crashed after a couple of hours, the new version I only get this issue once in 2 weeks from 4 environments.

### Exception detail

`System.NullReferenceException: Object reference not set to an instance of an object.     
  at GraphQL.Types.SchemaTypes.ApplyTypeReference(IGraphType type) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 651     
  at GraphQL.Types.SchemaTypes.ApplyTypeReferences() in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 614     
  at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 167     
  at GraphQL.Types.Schema.CreateSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 328     
  at GraphQL.Types.Schema.Initialize() in /_/src/GraphQL/Types/Schema.cs:line 102     
  at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 80`

### Environment
GraphQL 4.5 on .NET 5

## Duplication of interface

Beyond this, I also get a problem that the same interface might be applied to a graph type multiple times, this is happening in the latest version of 4.6 as well. 
Seems this problem is because the schema is add types synchronously, but it only does the duplication check on the entry of Interface function, so there are still a chance the ResolvedInterface can be added multiple times on the same type. This one can happen pretty frequently, if the schema has a lot types with interface applied, and those types are referenced in multiple places.

Below is my current work around to solve it in temp

```csharp
    public abstract class NodeGraphType<TSource> : ObjectGraphType<TSource>, IObjectGraphType
    {
        public new void AddResolvedInterface(IInterfaceGraphType graphType)
        {
            if (!ResolvedInterfaces.Contains(graphType))
            {
                base.AddResolvedInterface(graphType);
            }
        }
    }

    public class NodeInterface : InterfaceGraphType, IInterfaceGraphType
    {
        public NodeInterface()
        {
            Name = "Node";
        }

        public new void AddPossibleType(IObjectGraphType type)
        {
            if (!PossibleTypes.Contains(type))
            {
                base.AddPossibleType(type);
            }
        }
    }
```

**Comment by sungam3r** [comment]
@Shane32  Your explanations are excellent as always 😉. Nevertheless, the fact remains a fact - the exception occurred during the schema initialization. You yourself said that
> (Schema initialization is done in a thread-safe manner.)

So... it is our responsibility to investigate this error and fix it in our code. @diouxis could you please reproduce the error and say which object exactly is `null` in `ApplyTypeReference` ? This project uses Source Link so enabling it into you IDE you may debug and navigate throught GraphQL.NET sources.

**Comment by Shane32** [comment]
The error is known; there is nothing to investigate. It occurs when two schemas access the same instance of a graph type. This only happens when people configure DI in a manner inconsistent with the instructions. 

The thing is that schema initialization is safe for the schema class. But regardless of thread safety, the graph classes can’t be used by multiple instances of the schema. This isn’t a thread safety issue at all, really, as there are memory leaks and other issues that can happen when a graph is shared among multiple schema instances. (For example, middleware reapplied over and over on a field.)

Now we could add a thread safe check on every graph to be sure it is assigned to only a single schema instance. But this will slow down initialization and increase memory requirements. I would not recommend we make this change.

**Comment by sungam3r** [comment]
> It occurs when two schemas access the same instance of a graph type.

How and where?

I consider the case with singleton graphtype and scoped schema/schemas like "rather normal". Imagine different arbitrary schemas in one multi-tenant financial app all of them using the same common graphtype, say, "Money" or "Account". It does not even matter the lifetime of schemas. Schemas can also be singletons. It is important that with simultaneous initialization, they correctly used the same instance of graphtype, if the DI container was configured to use such an instance.

> But this will slow down initialization and increase memory requirements. 

I do not think everything will be so bad. I think I can even write a test that reproduces the problem.

**Comment by sungam3r** [comment]
> I think I can even write a test that reproduces the problem.

But only after dealing with all mail.

**Comment by Shane32** [comment]
The problems start when setting the ResolvedType property of any field to argument. Which instance would be correct? If the resolved graph type was scoped, it would be improper to use any instance while initializing a singleton graph, or else scoped services used by that scoped graph are now run within the context of two different threads, violating thread safety, or executing after the scope has been disposed of. 

Middleware and unions and stuff suffer similarly. Middleware probably feels it the most right now. 

And if all graphs are singletons then there is no reason to use a scoped schema. 

The design of GraphQL.NET is such that presently all graphs hold direct references to each other after initialization. Thus it is impossible for some of the graphs to be singletons and some to be scoped.

**Comment by Shane32** [comment]
I believe this issue is handled by #3248 where an exception is thrown if a schema attempts to initialize a graph type which has already been initialized.

**Comment by sungam3r** [comment]
#3248 is in 7.0 milestone. @diouxis please try v7 release. I close issue for now but feel free to ask further questions if any.
