### ISSUE TITLE
Type extend with GraphType first and Apollo federation

### ISSUE THREAD

**Issue by martin-krivosudsky** [graphql-dotnet/graphql-dotnet#2644]
Went through documentation and examples and can not find solution for my use case. I would like to use GraphType first approach (managed to make it kind of work with schema first) with Apollo federation where type is defined in different GraphQL server (NodeJS) and I need to extend it inside dotnet GraphQL and define resolver. Is something like that possible or should I stick with Schema first approach? 

**Example:**
Lets say we have employee that manages multiple types of property in company. So schema would look something like this

User
__Organization
_____ManagedProperty
_______Vehicles
_______Computers

All of this is defined in different GraphQL schema with resolvers. Now I want to extend ManagedProperty with MobilePhones type with resolvers and filters. So basically I need GraphTypes approach to generate something like: 

extend type ManagedProperty {
__mobilePhone(id: ID!): MobilePhone
__mobilePhones: [MobilePhone]
}

type MobilePhone  @key(fields: ""id"") {
__id: ID!
__name....
}

**Comment by Shane32** [comment]
I’ve not done Apollo federation with GraphQL.NET but I’m pretty sure it’s not supported in code-first. See #2564
