### ISSUE TITLE
The JSON value could not be converted to Newtonsoft.Json.Linq.JToken

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2646]
I have a json that I am deserializing by using `NewtonSoftJson` Json library as shown below:

    public async Task InvokeAsync(HttpContext httpContext, ISchema schema)
    {
        ...
        var request = Deserialize<GraphQLRequest>(httpContext.Request.Body);
        ....
    }

    public static T Deserialize<T>(Stream s)
    {
        using (var reader = new StreamReader(s))
        using (var jsonReader = new JsonTextReader(reader))
        {
            var ser = new JsonSerializer();
            return ser.Deserialize<T>(jsonReader);
        }
    }

But for this I have to enable this `AllowSynchronousIO` flag which I don't want to -

    .UseKestrel(o =>
    {
        o.AllowSynchronousIO = true;
    })

I was reading this [wiki](https://graphql-dotnet.github.io/docs/guides/serialization/) as I am working with GraphQL and now I am trying to use `System.Text.Json` library to deserialize asynchronously as shown below -

    public async Task InvokeAsync(HttpContext httpContext, ISchema schema)
    {
        ...
        var request = await Deserialize<GraphQLRequest>(httpContext.Request.Body);
        ....
    }

    public static async Task<T> Deserialize<T>(Stream s)
    {
      return await JsonSerializer.DeserializeAsync<T>(s, new JsonSerializerOptions
          {
              PropertyNameCaseInsensitive = true
          }
      );
    }

Now if I hit below curl request then I am getting an error -

    curl --location --request POST 'http://localhost:1338/graphql' \
    --header 'Content-Type: application/json' \
    --data-raw '{"query":"query ($clientId : Int!, $appId : String!){\n    # Write your query or mutation here\n\tclientNavigation(\n\t\tclientId: $clientId\n\t\tfilters: [{ key: \"o\", value: $appId }]\n\t\tcustomerKey: \"league\"\n\t) {\n\t\ttitle\n\t\ttype\n\t\tlinks {\n\t\t\ttext\n\t\t\ttrkId\n\t\t\thref\n\t\t\tproductCount\n\t\t\tresource\n\t\t}\n\t}\n}","variables":{"clientId":"1234","appId":"12"}}'

Error is -

    The JSON value could not be converted to Newtonsoft.Json.Linq.JToken. Path: $.variables.siteId | LineNumber: 0 | BytePositionInLine: 380.

I am using `5.0.202` dotnet version. Any idea what is wrong here with `System.Text.Json` library and how can I fix this?

I know this might not be GraphQL related question but I was wondering why we don't support Utf8json library as it isn't mentioned in the above wiki? Also I tried with Utf8json library too and request still fails with different error so my question is why it only works with Newtonsoft?

**Comment by Shane32** [comment]
The message says 'The JSON value could not be converted to _**Newtonsoft.Json.Linq.JToken**_'.  Basically, you're trying to use System.Text.Json to convert an object to a Newtonsoft object.  System.Text.Json doesn't know anything about Newtonsoft so you need to change the 'GraphQLRequest' appropriately for System.Text.Json support.

**Comment by TechGeeky** [comment]
Is there any example where I can take a look at on how to change `'GraphQLRequest'` class for System.Text.Json support?

**Comment by Shane32** [comment]
I would look at the official GraphQL.NET documentation, the various examples (which I think now generally use System.Text.Json), or the implementation within the server project.  The `GraphQLRequest` class is not defined within the GraphQL.NET project itself; it is either something in your project or comes from another library.

**Comment by Shane32** [comment]
I recommend reading https://graphql-dotnet.github.io/docs/guides/serialization

**Comment by TechGeeky** [comment]
Yeah I was referring to above link only in my first post. I think I know what I need to do to make it work. Thanks for your help!
