### ISSUE TITLE
Please update GraphQL.StarWars NuGet

### ISSUE THREAD

**Issue by rose-a** [graphql-dotnet/graphql-dotnet#2648]
Hi, the current version of the [GraphQL.StarWars](https://www.nuget.org/packages/GraphQL.StarWars/) NuGet package is incompatible with the latest version of graphql-dotnet, since it still uses `IDependencyResolver` in the schema definition...

Could you please publish a up-to-date version of the package...

**Comment by Shane32** [comment]
Why does the `GraphQL.StarWars` package exist in the first place?  What does it contain?  Is it this:

https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.StarWars

?

**Comment by rose-a** [comment]
Yes... and it belongs to @joemcbride

I had used it for building test cases for [graphql-client](https://github.com/graphql-dotnet/graphql-client). When I tried to update the dependencies the testcases exploded 💥  

IMO it's quite helpful to have this schema which is used by lot's of GraphQL examples available as a NuGet package...

**Comment by sungam3r** [comment]
@rose-a I made this project explicitly as not packable 07.01.2020, see #1481 . I think GraphQL.Starwars was published on Nuget in the very start of the GraphQL.NET project "by mistake". It was a long time ago in 2017. I advise you to simply copy its source code for use in tests or examples. It is unlikely that we will publish it again and support. @Shane32 what do you think? @joemcbride what do you think about deprecating this package on Nuget? 
![изображение](https://user-images.githubusercontent.com/21261007/139600644-7e313f62-192e-4f63-a961-06c6f083dc14.png)

**Comment by Shane32** [comment]
Personally, I would not publish it, and would deprecate the nuget package.

**Comment by rose-a** [comment]
> I advise you to simply copy its source code for use in tests or examples.

Already done, works for me...

**Comment by sungam3r** [comment]
OK. So waiting for @joemcbride  decision regarding deprecation.

**Comment by sungam3r** [comment]
I think we can close this. I'm OK to abandon GraphQL.StarWars package as well.
