### ISSUE TITLE
Incorrect scalar type can be passed in variable

### ISSUE THREAD

**Issue by alekbarszczewski** [graphql-dotnet/graphql-dotnet#2652]
## Description

There is custom scalar EncodedIdGraphType which extends LongGraphType and it encodes/decodes value "on the fly".

```c#
class EncodedIdGraphType : LongGraphType
{
    public override object? ParseValue(object? value)
    {
        return ToLong(value)?.DecodeId(); // just long extension that decodes long to long
    }

    public override object? Serialize(object? value)
    {
        return ToLong(value)?.EncodeId(); // just long extension that encodes long to long
    }

    public override object? ParseLiteral(IValue value) => value switch
    {
        LongValue longValue => ParseValue(longValue.Value),
        IntValue intValue => ParseValue((long) intValue.Value),
        BigIntValue bigIntValue => ParseValue((long)bigIntValue.Value),
        NullValue _ => null,
        _ => ThrowLiteralConversionError(value)
    };

    protected long? ToLong(object? value) => value switch
    {
        long l => l,
        null => null,
        int i => i,
        sbyte sb => sb,
        byte b => b,
        short s => s,
        ushort us => us,
        uint ui => ui,
        ulong ul => checked((long) ul),
        BigInteger bi => (long) bi,
        _ => (long?) ThrowValueConversionError(value)
    };
}
```

The problem is that it is allowed to pass Long! type variable instead of declared EncodedIdGraphType to query.

### Steps to reproduce

```graphql

input MyInput {
  id: EncodedId!
}

# works, id is decoded
query myQuery {
  myQuery(input: { id: 123 }) { something }
}

# works, id is decoded
query myQuery($input: MyInput!) {
  myQuery(input: $input) { something }
}


# works, id is decoded
query myQuery($id: EncodedId!) {
  myQuery(input: { id: $id }) { something }
}

# does not work, id is not decoded and no exception is thrown
query myQuery($id: Long!) {
  myQuery(input: { id: $id }) { something }
}
```

### Expected result

Last query should throw exception. Even my GrqphQL IDE highlights this query as invalid. It seems gql.net allows casting Long  to EncodedId because EncodedId extends LongGraphType. I believe it should throw error that query is invalid because Long! is being used instead of EncodedId!. 

### Actual result

No exception is thrown, EncodedId scalar type is "bypassed" and value is not decoded.

### Environment

Max OS X or Docker alpine-linux, GraphQL 4.5.0

**Comment by Shane32** [comment]
I would agree that the scenario you described should return a GraphQL error.  Probably it should trigger the `ArgumentsOfCorrectType` validation error but I'm not sure yet.  Are you using the default validation rules when calling the document executer?

**Comment by alekbarszczewski** [comment]
It seems that we have not included core validation rules in GQL executer :( https://graphql-dotnet.github.io/docs/getting-started/query-validation/. After adding core validation rules correct error is returned:

```json
{
      "message": "Variable '$test' of type 'Long!' used in position expecting type 'EventId!'.",
      "locations": [
        {
          "line": 1,
          "column": 13
        },
        {
          "line": 3,
          "column": 33
        }
      ],
      "extensions": {
        "code": "VARIABLES_IN_ALLOWED_POSITION",
        "violations": null
      }
    }
```

Thanks for help!
I just wonder if it won't break app since it's in production since long time 😟

**Comment by Shane32** [comment]
No problem!  Keep in mind that the `GetArgument` method and similar parts of GraphQL.NET assume that the document has passed validation, and is not programmed to validate the arguments a second time.  So, you will likely find that without the validation rule, the variable is not properly deserialized (i.e. your encode/decode methods are not executed) when the value is passed as a Long variable instead of a EncodedId variable.
