### ISSUE TITLE
Access UserContext inside data fetch function when using Dataloader 

### ISSUE THREAD

**Issue by maximiliancsuk** [graphql-dotnet/graphql-dotnet#2653]
I am starting to integrate DataLoader into our project and I'm not sure how to best implement what I need. We're making use of 
the `UserContext` object provided by GraphQL to pass request-spanning information down to all resolvers. The resolvers can use this `UserContext` to do their actual work and fetch data from the database, for example. That worked great so far.

Our old code looks like this:
```
FieldAsync<StringGraphType>("CIName",
    resolve: async (context) =>
    {
        var ciid = context.Source!.CIID;
        var userContext = (context.UserContext as OmnikeeperUserContext)!;
        var names = await attributeModel.GetMergedCINames(SpecificCIIDsSelection.Build(ciid), userContext.LayerSet, userContext.TimeThreshold);
});
```

Note the use of the `userContext` and how its inner data is used for getting data from the Model layer (`attributeModel`).

With the introduction of the dataloader, it doesn't seem as straight forward anymore. Essentially, the function that now does the actual fetch does not have access to the `UserContext`... but we need this for data fetching. I've come up with a really cumbersome workaround of passing the UserContext as part of the key and inside a Tuple... but it makes all kinds of things much harder: we need a tuple, a custom equalityComparator, and the actual fetch function is much more complex too. Here's the workaround:

```
Field<StringGraphType>("CIName",
    resolve: (context) =>
    {
        var ciid = context.Source!.CIID;
        var userContext = (context.UserContext as OmnikeeperUserContext)!;

        var loader = dataLoaderContextAccessor.Context.GetOrAddBatchLoader("GetMergedCINames", Fetch, new EQ());
        return loader.LoadAsync((SpecificCIIDsSelection.Build(ciid), userContext));
    }
);

private class EQ : EqualityComparer<(SpecificCIIDsSelection ciidSelection, OmnikeeperUserContext context)>
{
    public override bool Equals([AllowNull] (SpecificCIIDsSelection ciidSelection, OmnikeeperUserContext context) x, [AllowNull] (SpecificCIIDsSelection ciidSelection, OmnikeeperUserContext context) y)
    {
        return x.ciidSelection.Equals(y.ciidSelection); // ignore context, its fixed per-request
    }

    public override int GetHashCode([DisallowNull] (SpecificCIIDsSelection ciidSelection, OmnikeeperUserContext context) t)
    {
        return t.ciidSelection.GetHashCode(); // ignore context, its fixed per-request
    }
}

private async Task<IDictionary<(SpecificCIIDsSelection ciidSelection, OmnikeeperUserContext context), string?>> Fetch(IEnumerable<(SpecificCIIDsSelection ciidSelection, OmnikeeperUserContext context)> ciidSelections)
{
    // HACK: treat as if we only have a single usercontext
    var userContext = ciidSelections.First().context;

    var ret = new Dictionary<(SpecificCIIDsSelection ciidSelection, OmnikeeperUserContext context), string?>() { };

    // ... snip: actual fetch code that uses userContext and batches all requests into a single one
    // then splits them again and returns the required, properly structured dictionary

    return ret;
}
```

Is there a better way to access the `UserContext` inside the fetch function?

**Comment by maximiliancsuk** [comment]
I'm dumb... I just realized that I can use a JS-style closure like the following to pass the `UserContext`:
```
Field<StringGraphType>("CIName",
  resolve: (context) =>
  {
      var ciid = context.Source!.CIID;
      var userContext = (context.UserContext as OmnikeeperUserContext)!;

      var loader = dataLoaderContextAccessor.Context.GetOrAddBatchLoader("GetMergedCINames", (IEnumerable<SpecificCIIDsSelection> ciidSelections) => Fetch(userContext, ciidSelections));
      return loader.LoadAsync((SpecificCIIDsSelection)SpecificCIIDsSelection.Build(ciid));
  });
```

That fixes my issue and makes everything simple again! :)

I'll close my question, but leave this up should anybody have the same brain-fart is I did ;)

**Comment by Shane32** [comment]
Keep in mind that only the first call to `GetOrAddBatchLoader` will capture the lambda (per request); the rest will use the lambda already specified.  Very similar to your "hack" comment in your previous sample.  This should be fine for the usercontext, since it will be the same for every data loader call for the same request.  So I think you're good.  You just wouldn't want to include the `context.Source` property in the lambda or anything like that, and you're relying on the data loader to keep concurrent requests separated by request (which it does within the `DataLoaderContextAccessor` via an `AsyncLocal`).

**Comment by maximiliancsuk** [comment]
Yes, you're right. I wouldn't want to use this approach for anything that would need to be "up-to-date" with every field resolving. So I also think it's ok to use for the UserContext.

I didn't actually think about concurrent requests at all, but just assumed that there would be safeguards that keep things separated here. Thanks for thinking it through! :)

I'll re-open should I run into problems down the road with this approach.
