### ISSUE TITLE
Dynamically create Fields at runtime using reflection - Unable to create a resolver

### ISSUE THREAD

**Issue by markmcgookin** [graphql-dotnet/graphql-dotnet#2667]
Apologies if this isn't the right place, I have also [posted on stackoverflow](https://stackoverflow.com/questions/69377888/graphql-dotnet-add-fields-at-runtime-using-reflection) for more general help on generics, but thought that the specialist knowledge here might help with the more specific issues.

We have a decent sized dataset that we are using graphql dotnet to query. We have custom logic in place to parse the GQL query string and generate a function that will select the appropriate fields from the database and not the full object.

As such, the 'Query' object in our schema has a load of almost identical calls to `Field` in it which just look an object up by it's Id, issue the parsed select command, and return the resulting object. 

For example: 

    // expression based department query
    Field<DepartmentType>(
        "department",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "organisationId" },
            new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "employerId" },
            new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "Id" }),
        resolve: context =>
        {
            var query = context.Document.OriginalQuery.Substring(context.Document.OriginalQuery.IndexOf("{"));
    
            var organisationId = new Guid(context.GetArgument<string>("organisationId"));
            var employerId = new Guid(context.GetArgument<string>("employerId"));
            var Id = new Guid(context.GetArgument<string>("Id"));
    
            appContext.OrganisationId = organisationId;
            appContext.EmployerId = employerId;
    
            var retVal = database.Departments()
                .Where(x => x.Id == Id && x.Deleted != true);
    
            var selectStatement = GraphDocumentParser.GenerateSelect(query, "department");
            var builder = new ExpressionBuilder();
            var statement = builder.BuildSelector<Department, Department>(selectStatement);
            var result = retVal.Select(statement);
    
            return result.FirstOrDefault();
        }).AuthorizeWith(Constants.GraphQL.Policies.API_ACCESS);

So I thought that I could just use reflection to loop our graphql types like this: 

    var queryableObjectTypes = Assembly.GetExecutingAssembly().GetTypes()
        .Where(x => x.IsClass && x.Namespace == "my.namespace.query.api" && !x.FullName.Contains("+<>c"))
        .ToList();
    
    //Loop through our GQL types
    foreach (var queryableObjectType in queryableObjectTypes)
    {
        Console.WriteLine(queryableObjectType.FullName);

        //Grab the fields property from the type
        var fieldsProperty = queryableObjectType.GetProperties().FirstOrDefault(x => x.Name == "Fields");
    
        //If this has our 'fields' property which we require
        if (fieldsProperty != null)
        {
            //Get the instance of this
            var instanceOfType = database.GetServiceProvider().GetService(queryableObjectType);
    
            //If this fields is the type we definitely want - i.e.actually get the value from the
            // instance and check it
                if (fieldsProperty.GetValue(instanceOfType) is GraphQL.Types.TypeFields typeFields)
            {
                //If this type contains an employerid, then we need to generate a query for this
                if (typeFields.Any(x => x.Name.ToLower() == "employerid"))
                { ... } //These are the objects that I want to generate fields for

Which does give me the correct collection of GQL Type objects that I can loop over and use to add a field (any one of our objects with an employerId... which I will blacklist a few of later on, but that would be a simple list to skip over)

I can then parse various bits like the 'base' entity that this type points to, and get most of the required data for the Field to add to our GQL query.

I am able to get almost everything I need to create a field type to add to our query... as shown here: 

    var f = new FieldType();
    f.Name = genericTypeNameFormatted;
    f.Description = string.Empty;
    f.Type = queryableObjectType;
    f.Resolver = ????????
    f.Arguments = new QueryArguments(
        new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "organisationId" },
        new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "employerId" },
        new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "Id" });
    f.AuthorizeWith(Constants.GraphQL.Policies.API_ACCESS);

However, I am totally stuck with the mix of generics etc.. required to create the resolver.

Is it possible to create a `Func<IResolveFieldContext<TSource>, Task<TReturn>>` using data from reflection etc? or is it actually not possible?

**Comment by markmcgookin** [comment]
Just realised this should be in the server project.

**Comment by Shane32** [comment]
I think this issue fits better here, actually.  The server project would discuss issues that pertain to tying ASP.NET to GraphQL, whereas this is a question about building a schema.

**Comment by Shane32** [comment]
To answer your question, the `FieldType.Resolver` property accepts an `IFieldResolver` interface, and only cares about the untyped `object? Resolve(IResolveFieldContext context);` method on that instance.  You can create your own class that implements `IFieldResolver` to return whatever data you want, without having to worry about generics.  This is essentially what the included `NameFieldResolver` does -- it takes the name of the field, and using that name finds a matching property on the source object and returns it.  You may find that it works well to copy the `NameFieldResolver` and modify it to your needs.

Here is a sample of a simple resolver that can be configured with a property, method, or field:

```cs
public class MemberFieldResolver : IFieldResolver
{
    private readonly System.Reflection.MethodInfo _methodInfo;
    private readonly System.Reflection.FieldInfo _fieldInfo;

    public MemberFieldResolver(System.Reflection.MethodInfo methodInfo) => _methodInfo = methodInfo;
    public MemberFieldResolver(System.Reflection.PropertyInfo propertyInfo) : this(propertyInfo.GetMethod) { }
    public MemberFieldResolver(System.Reflection.FieldInfo fieldInfo) => _fieldInfo = fieldInfo;

    public object? Resolve(IResolveFieldContext context)
        => _methodInfo != null ? _methodInfo.Invoke(context.Source, null) : _fieldInfo.GetValue(context.Source);
}
```

**Comment by Shane32** [comment]
FYI, here is how I get around the generics issue, when it's necessary (which hopefully it won't be for you):

```cs
        private string Method1(Type tObjectType, object param1, int param2, string param3)
        {
            if (tObjectType == null) throw new ArgumentNullException(nameof(tObjectType));

            //call the generic version of this function
            var method = _method1InternalDictionary.GetOrAdd(tObjectType, factory);
            return (string)method.Invoke(this, new object[] { param1, param2, param3 });

            MethodInfo factory(Type key)
            {
                return GetType().GetMethod(nameof(Method1Internal), BindingFlags.NonPublic | BindingFlags.Instance).MakeGenericMethod(key);
            }
        }

        private static readonly ConcurrentDictionary<Type, MethodInfo> _method1InternalDictionary = new ConcurrentDictionary<Type, MethodInfo>();

        protected virtual string Method1Internal<T>(T param1, int param2, string param3)
        {
            //code here
        }
```
