### ISSUE TITLE
Issue using scalar types

### ISSUE THREAD

**Issue by azaslonov** [graphql-dotnet/graphql-dotnet#2668]
Hello, I'm trying setup a query validation policy for our backend and it seems that scalar types (see `SomeType` below) are not being accepted. Simple reproduction (version 4.6.1):

```
    class Program
    {
        public static async Task Main(string[] args)
        {
            var schemaDoc = @"
            schema {
              query: Query
            }

            type Query {
              ship(id: String!): Ship
            }

            scalar SomeType

            type Ship
            {
                id: String!
                someField: SomeType
            }";

            var schema = Schema.For(schemaDoc);
            var json = await schema.ExecuteAsync(_ =>
            {
                _.Query = @"{ ship(id: ""GOMSTREE"") { id, someField } }";
            });

            Console.WriteLine(json);
        }
    }
```

Output:
```
{
  "errors": [
    {
      "message": "Error executing document.",
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ]
      }
    }
  ]
}
```
**One important clarification here:** I need to be able to accept any (unknown) scalar type, because the actual request will be handled by downstream components. I won't be able to inherit from `ScalarGraphType` to support this.

Any help is greatly appreciated!

**Comment by azaslonov** [comment]
The better question probably would be: How to implement universal `ScalarGraphType` that would accept every unknown type (no need to parse or map their values)?

**Comment by Shane32** [comment]
There is an Any scalar type which is used for federation which may be similar to what you need. Perhaps just create an instance, set the name, and register it manually in the schema builder - for each custom scalar. I don’t use schema first so I’m not sure on the exact syntax.

**Comment by azaslonov** [comment]
Thanks @Shane32, unfortunately I don't know the schema in advance. Can you please elaborate on Any? Where can I see it at least?

**Comment by Shane32** [comment]
You could probably parse the schema and look for all scalar types, then create an any type and name it (at runtime), add each one to the schema builder, and that might work. 

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/Federation/AnyScalarGraphType.cs

**Comment by azaslonov** [comment]
I guess you're right, I'll explore that options. Thanks!

**Comment by Shane32** [comment]
Please re-open if you have further questions.
