### ISSUE TITLE
Documentation on upgrade to v3.0 is missing

### ISSUE THREAD

**Issue by MarcinIN** [graphql-dotnet/graphql-dotnet#2673]
## Summary
I would like to see braking changes, upgrade guide and new features for version 3.0. I got this when I try to access any of the mentioned pages in releases:

![image](https://user-images.githubusercontent.com/26964984/137088996-791035d6-9e51-4916-b998-80a0a7304f84.png)

Related Links:
  - https://graphql-dotnet.github.io/docs/guides/migration3/#new-features
  - https://graphql-dotnet.github.io/docs/guides/migration3
  - https://graphql-dotnet.github.io/docs/guides/migration3/#breaking-changes

We're still on 2.4..

**Comment by Shane32** [comment]
Sorry about that. Just click Docs on the top of that page and then near the bottom of the navigation bar on the left side is the v2 to v3 and v3 to v4 migration guide.

**Comment by Shane32** [comment]
The specific pages you mentioned are all portions of the same page — the v2 to v3 migration guide. 

https://graphql-dotnet.github.io/docs/migrations/migration3

**Comment by Shane32** [comment]
Links in the 3.0 release have been updated
