### ISSUE TITLE
GraphQL.ExecutionError: Error trying to resolve remitsGeneralSearch.

### ISSUE THREAD

**Issue by dionysus1983** [graphql-dotnet/graphql-dotnet#2674]
**Summary:** 

My GraphQL ExecuteAsync returns a result that contains. According to the stackTrace provided below, the system cannot resolve my custom type remitsGeneralSearch. The remitsGeneralSearch resolver can return a type called ClaimPaymentOrCheckSearchGraphType which is a UnionGraphType.

**StackTrace:** 
["GraphQL.ExecutionError: Error trying to resolve remitsGeneralSearch.\n ---> System.InvalidOperationException: Unexpected type: \n   at GraphQL.Execution.ExecutionStrategy.BuildExecutionNode(ExecutionNode parent, IGraphType graphType, Field field, FieldType fieldDefinition, String[] path)\n   at GraphQL.Execution.ExecutionStrategy.SetSubFieldNodes(ExecutionContext context, ObjectExecutionNode parent, Dictionary`2 fields)\n   at GraphQL.Execution.ExecutionStrategy.SetSubFieldNodes(ExecutionContext context, ObjectExecutionNode parent)\n   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)\n   --- End of inner exception stack trace ---"]4008305)

**GraphQL Version:** 2.4.0
**FrameWork:** .Net
**OS:** MacOS Catalina
**Links Referenced:** https://github.com/graphql-dotnet/graphql-dotnet/issues/964

**CODE SNIPPETS:**

**RESOLVER:**
```
FieldAsync<ClaimPaymentOrCheckSearchGraphType>(
									"remitsGeneralSearch",
									resolve: async context =>
									{
										var securityFilter = await GetUserRemitFilters(context);
										var range = context.GetRange();
										var sortFields = context.GetArgument<List<SortField>>("sort") ?? Enumerable.Empty<SortField>();
										var whereClaimPayment = context.GetArgument<ClaimPaymentSearchFilter>("whereClaimPayment");

										Connection<ClaimPaymentSearchRow> claimPaymentSearchRowResult;

										try
										{
											using (LogContext.PushProperty("where", whereClaimPayment, true))
											{
								//claimPaymentSearchRowResult = await DMAQueryService.GetRemitReadersAsync(context);
								var whereArguments = context.Arguments["whereClaimPayment"] as Dictionary<string, object>;
												claimPaymentSearchRowResult = await DMAQueryService.GetRemitReadersAsync(
													range,
													 whereClaimPayment,
													whereArguments,
													 sortFields,
													securityFilter,
													context.CancellationToken
												);
											}
										}
										catch (Exception e)
										{
											_logger.LogInformation("Exception occurred {e}", e);
											throw e;
										}

										var userRemitFilters = context.UserContext as Services.DMA.UserRemitFilters;

										if (claimPaymentSearchRowResult.EdgeCount > 0)
										{
											return claimPaymentSearchRowResult;
										}

										var _whereCheckSearch = context.GetArgument<CheckSearchFilter>("whereCheck");

										try
										{
											Connection<CheckSearchRow> checkSearchRowResult;
											using (LogContext.PushProperty("whereCheck", _whereCheckSearch, true))
											{
												checkSearchRowResult = await DMAQueryService.GetCheckReadersAsync(context);
												return checkSearchRowResult;
											}
										}
										catch (Exception e)
										{
											throw e;
										}
									},
									arguments: queryArguments
							);
			}
			catch (Exception e)
			{
				throw e;
			}
```

Custom GraphType:

```
[Transient]
	public class ClaimPaymentOrCheckSearchGraphType : UnionGraphType
	{
		private readonly ILogger<ClaimPaymentOrCheckSearchGraphType> _logger;
		public ClaimPaymentOrCheckSearchGraphType(
			ILogger<ClaimPaymentOrCheckSearchGraphType> logger,
			ConnectionGraphType<ClaimPaymentSearchGraphType> claimPaymentSearchGraphType,
			ConnectionGraphType<CheckSearchGraphType> checkSearchGraphType
		)
		{
			_logger = logger;
			Type<ConnectionGraphType<ClaimPaymentSearchGraphType>>();
			Type<ConnectionGraphType<CheckSearchGraphType>>();

			ResolveType = obj =>
			{
				try
				{
					if (obj is Connection<ClaimPaymentSearchRow>)
					{
						return claimPaymentSearchGraphType;
					}

					if (obj is Connection<CheckSearchRow>)
					{
						return checkSearchGraphType;
					}

					throw new ArgumentOutOfRangeException($"Could not resolve graph type for {obj.GetType().Name}");
				}
				catch (Exception e)
				{
					_logger.LogInformation("ClaimPaymentOrCheckSearchGraphType Exception {e}: ", e);
					throw e;
				}

			};
		}
	}
```

**Comment by Shane32** [comment]
I didn't actually test it, but I'm imagining something like this:

```cs
public MySchema : Schema
{
    public MySchema(
        IServiceProvider services,
        ClaimPaymentSearchGraphType type1,
        CheckSearchGraphType type2,
        ILogger<ClaimPaymentOrCheckSearchGraphType> logger,
        MyQueryType queryType)
    {
        var type3 = new ClaimPaymentOrCheckSearchGraphType(logger, type1, type2);
        RegisterType(type1);
        RegisterType(type2);
        RegisterType(type3);

        //all other code here, for example:
        Query = queryType;
    }
}
```

**Comment by Shane32** [comment]
It might be easier to just register those types as singletons, or use `IsTypeOf` instead of `ResolveType`, but you may have other reasons why those solutions are not possible.

**Comment by Shane32** [comment]
> Are you saying that both `ClaimPaymentSearchGraphType` and `CheckSearchGraphType` that I have to implement the `IsTypeOf`

Yes, I believe so

> or should it be in `ClaimPaymentOrCheckSearchGraphType`?

No, I don't think so

See: https://graphql-dotnet.github.io/docs/getting-started/interfaces/#resolvetype

It's possible the default `IsTypeOf` implementation would work already (so you could just comment out the `ResolveType` code), but you're using connection types so maybe that's throwing a wrench into things.

**Comment by dionysus1983** [comment]
> > Are you saying that both `ClaimPaymentSearchGraphType` and `CheckSearchGraphType` that I have to implement the `IsTypeOf`
> 
> Yes, I believe so
> 
> > or should it be in `ClaimPaymentOrCheckSearchGraphType`?
> 
> No, I don't think so
> 
> See: https://graphql-dotnet.github.io/docs/getting-started/interfaces/#resolvetype
> 
> It's possible the default `IsTypeOf` implementation would work already (so you could just comment out the `ResolveType` code), but you're using connection types so maybe that's throwing a wrench into things.

@Shane32 
Tried this one and it did not work. Going to give the Schema suggestion a try. Also, is `MyQueryType` an actual GraphQL class or were you using that as code to represent custom code on my end?

**Comment by dionysus1983** [comment]
@Shane32 Considering that I am using version 2.4.0 of GraphQL, would it be worth it to upgrade to the most current version? Also are there any breaking changes that I should be aware of before upgrading? I tried the solutions that you've offered and those have not, however I assume it may be due to me using an outdated version of GraphQL. Thanks again.

**Comment by sungam3r** [comment]
> Considering that I am using version 2.4.0 of GraphQL, would it be worth it to upgrade to the most current version?

Of course.

> Also are there any breaking changes that I should be aware of before upgrading? 

A lot of breaking changes! https://github.com/graphql-dotnet/graphql-dotnet#upgrade-guides

**Comment by sungam3r** [comment]
Closing this one due to inactivity. It's worth to migrate to the-latest-and-greatest GraphQL v7. We have introduced a lot of changes in schema/types building/validation.
