### ISSUE TITLE
Dynamically Generating Complex Input Arguments not Generating a Valid Schema.

### ISSUE THREAD

**Issue by ianashleycooper** [graphql-dotnet/graphql-dotnet#2675]
I am dynamically generating my GraphQL schema from the equivalent of a database. It is important that I can dynamically generate so that it is easy to design the look and feel of our real GraphQL API by changing the database structure, putting some sample data in and then letting my content owners play with the output. I know, API first would be better, but, alas, this is data first design for good or bad.

I am finding different behaviour when trying to dynamically set complex input types. I think that I might have figured out how I can work around this issue, but there still seems to be a bug.

I am using GraphQL 4.6.1

If I do something like this:

```cs
new QueryArgument<ListGraphType<NonNullGraphType<StringGraphType>>> { Name = "objectIds", Description = "Unique id of the record" })
```

Which is not completely dynamic, there are certain queries that always have this 'objectIds' argument. The definition of this argument is static, it is dynamically added to my queries. This list of not null strings looks fine in my generated schema (using the pretty printer):

```gql
type Root {
  TestOT(objectIds: [String!], limit: Int, filter: InputString): [TestOT]
}
```

If I try and do something more dynamic that looks like:

```cs
InputObjectGraphType stringFilterInputType = new InputObjectGraphType { Name = "InputString" };

stringFilterInputType.AddField(new FieldType
{
    Name = "EQ",
    ResolvedType = new StringGraphType()
});
stringFilterInputType.AddField(new FieldType
{
   Name = "IN",
   ResolvedType = new ListGraphType<StringGraphType>()
});
stringFilterInputType.AddField(new FieldType
{
   Name = "NOT",
   ResolvedType = new NonNullGraphType<StringGraphType>()
});
```

This generates a broken schema that also breaks GraphiQL 'docs' when it does introspection. The generated type for this InputObjectType looks like:

```gql
input InputString {
  EQ: String
  IN: []
  NOT: !
}
```

What happened to my ListGraphType<StringGraphType> or my NonNullGraphType<StringGraphType>?

If I don't use the generic constructor for ListGraphType or NonNullGraphType, then I can get this to work. So, if I change my code to:

```cs
var stringType = new StringGraphType();
InputObjectGraphType stringFilterInputType = new InputObjectGraphType { Name = "InputString" };
stringFilterInputType.AddField(new FieldType
{
    Name = "EQ",
    ResolvedType = new StringGraphType()
});
stringFilterInputType.AddField(new FieldType
{
     Name = "IN",
     ResolvedType = new ListGraphType(stringType)
});
stringFilterInputType.AddField(new FieldType
{
     Name = "NOT",
     ResolvedType = new NonNullGraphType(stringType)
});
```

When I run the server now and look at the pretty printed SDL, I get something much better:

```gql
input InputString {
  EQ: String
  IN: [String]
  NOT: String!
}
```

Looking at the code I thought that:

```cs
var stringType = new StringGraphType();
var argument = new ListGraphType(stringType)
```

should be equivalent to:

```cs
var argument = new ListGraphType<StringGraphType>()
```

And, I also think that it should be impossible for the server to start if the schema is invalid, so, no matter how I managed to get a schema that looked like:

```gql
input InputString {
  EQ: String
  IN: []
  NOT: !
}
```

Then there should have been an exception thrown somewhere upon startup.

**Comment by Shane32** [comment]
Might this just be a problem with the SchemaPrinter?  Or is it not executing queries correctly either?

**Comment by ianashleycooper** [comment]
Hi Shane,

It isn't executing queries either, partially.

What happens is that when I do this in the way that breaks the schema out of the pretty printer, then 2 things happen:

1. The server starts but when I point my GraphiQL to the endpoint it is unable to generate the docs.
     This I believe is because the the schema is broken and so GraphiQL introspection queries fall over.
2. The server is actually running and I can execute queries, but only queries that do not use this argument.
     If I try and execute a query that includes this argument, then I get an error returned by the server.

Query (bit random):

> {
>   TestOT(objectIds: ["a", "b"], limit:1, filter: {IN: ["a"], NOT: "c"})
>   {
>     ObjectId
>     TestTable1 {
>       Column1
>       Column2
>       Column3
>       Column4
>     }
>   }
> }

Response if I use the workaround without generic constructor:

> {
>   "data": {
>     "TestOT": [
>       {
>         "ObjectId": "a",
>         "TestTable1": {
>           "Column1": 2,
>           "Column2": 100,
>           "Column3": "test1",
>           "Column4": "2021-01-01T00:00:00"
>         }
>       }
>     ]
>   }
> }

Response if I use the generic constructor:

> {
>   "errors": [
>     {
>       "message": "Error executing document.",
>       "extensions": {
>         "code": "ARGUMENT_OUT_OF_RANGE",
>         "codes": [
>           "ARGUMENT_OUT_OF_RANGE"
>         ]
>       }
>     }
>   ]
> }

If I run a query that doesn't invoke the 'filter' argument, then even with the 'bad' code, I do get the 'working' response from the server with the data populated and no errors.

NOTE: sorry about my formatting! Going to try and learn how to do better code comments in markdown.

**Comment by Shane32** [comment]
Sorta like this, without the `>` signs
```
> ```gql
> {
>    field1
>    field2
> }
> ```
```

**Comment by Shane32** [comment]
Does that make sense?

**Comment by sungam3r** [comment]
@Shane32  What milestone should I use if any?

**Comment by Shane32** [comment]
I suggest 4.6.2, and we can update it if we release a minor version instead of a revision.

**Comment by sungam3r** [comment]
@ianashleycooper thanks for reporting this.
