### ISSUE TITLE
Can we change the name of UserContext to just Context?

### ISSUE THREAD

**Issue by ghstahl** [graphql-dotnet/graphql-dotnet#268]
I created GraphQLUserContext to simply hold a reference to IHttpContextAccessor.
```c#
ASP.NET Core
public class GraphQLUserContext
{
    public IHttpContextAccessor HttpContextAccessor { get; private set; }
    public GraphQLUserContext(IHttpContextAccessor httpContextAccessor)
    {
        HttpContextAccessor = httpContextAccessor;
    }
}
```
Depending on the need, the downstream implementer can use whatever is in IHttpContextAccessor and do much more than just User validation.  In my case for a specific query I only needed culture.

```c#
 Resolve = async context =>
                {
                    var userContext = context.UserContext.As<GraphQLUserContext>();
                    var rqf = userContext.HttpContextAccessor.HttpContext.Features.Get<IRequestCultureFeature>();  
                     ...
               }
```
_**Change**_ 
```c# 

 var result = await _executer.ExecuteAsync(_ =>
            {
                _.UserContext = new GraphQLUserContext(_httpContextAccessor);
                _.Schema = _schema;
                _.Query = queryToExecute;
                _.OperationName = query.OperationName;
                _.Inputs = inputs;

                _.ComplexityConfiguration = new ComplexityConfiguration { MaxDepth = 15 };
                _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();

            }).ConfigureAwait(false);

the change would look like this.
var result = await _executer.ExecuteAsync(_ =>
            {
                _.Context = new MyCustomContext(_httpContextAccessor);
            }
```

**Comment by joemcbride** [comment]
It is named `UserContext` to match the JavaScript GraphQL project.  The intent is to keep close to those same names so we can use the same verbiage when talking about things.  The User in this sense means "the user of the GraphQL library", aka you as the developer.  You can name the class you use as the value of `UserContext` whatever you like.

**Comment by joemcbride** [comment]
Hah, so it appears they are just calling it `context` now.  So, perhaps it should indeed be updated.

**Comment by joemcbride** [comment]
This could lead to a bit of confusion since `context` has typically been used elsewhere for the "field resolver context".

From:
```
Resolve = async context =>
  {
    var userContext = context.UserContext.As<GraphQLUserContext>();
    var rqf = userContext.HttpContextAccessor.HttpContext.Features.Get<IRequestCultureFeature>();  
    ...
  }
```

To:
```
Resolve = async resolveContext =>
  {
    var context = resolveContext.Context.As<GraphQLUserContext>();
    var rqf = context.HttpContextAccessor.HttpContext.Features.Get<IRequestCultureFeature>();  
    ...
  }
```

**Comment by ghstahl** [comment]
Yea, Context is pretty generic and overused everywhere.  Going off topic, and just for fun, this is a autofac gem.

**Comment by jquense** [comment]
graphql.js gets away with calling it context because revolvers are passed a bunch of arguments (object, args, context, fieldInfo) but i like the graphql. dotnet approach better, naming things aside. also I was under the impression that what we call Root is what the js version calls context now

**Comment by joemcbride** [comment]
Coming back to this I think I'm just going to keep it as is for now.  Thank you for the suggestion though!
