### ISSUE TITLE
SchemaPrinter does not sort field names

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2685]
`SchemaPrinter` sorts directives and types by name, but does not sort field names, argument names, enumeration members, and so on.  It does not respect the `ISchemaComparer` set on the schema, and there is no setting to change this.

I suggest that a new property on `SchemaPrinterOptions` be added called `Comparer` which accepts a `ISchemaComparer` and uses it to print the schema.  This can be added to v4 without a breaking change.  Probably 4.7 since this changes the exposed API.

Perhaps in v5, the default behavior should be to respect the schema's comparer property, but allow for overriding the comparer if necessary.  I expect that in most of my applications, I will want the introspection verification test to use a sorted schema, but an introspection query would remain unsorted.

**Comment by sungam3r** [comment]
Agree. Also I want to note that `SchemaPrinter` requires many places to be completely rewritten.
