### ISSUE TITLE
How to disable introspection query?

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-dotnet#2692]
How can I disable the introspection query? Is there an easy way to do this in dotnet version of graphql. This is what we use as of now - 

```
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="4.2.0" />
    <PackageReference Include="GraphQL" Version="3.1.3" />
```

Is there any validation rule we can add to disable the introspection? This is what we have currently so I was thinking what we should do to disable introspection as well by adding validation rules? Or is there any other better way to do this instead of using Validation rules like using `ISchemaFilter` approach where I can implement all methods and using it in `ExecutionOptions`?

**Comment by TechGeeky** [comment]
@joemcbride Can you please help here? I saw you had some post regarding on how to disable it.

**Comment by Shane32** [comment]
What about using the schema filter (`ISchemaFilter` ?) to hide everything?  The introspection queries would still be present, but useless.

**Comment by TechGeeky** [comment]
Is there an example with `ISchemaFilter`? I can try it out if there is any. @Shane32

**Comment by Shane32** [comment]
I don't know of one offhand, but it should be pretty simple.  Search the source for ISchemaFilter and see if there is a base implementation.  If not, just write a class and implement the methods.  I think the methods are just predicates that return true/false if the type name passed to it is supposed to be shown/hidden.  So for starters you can just return true for everything. 
 I think you set the filter in the schema constructor, or else it's in the execution options.  If you run into problems, let me know, but I think it's pretty simple.

**Comment by TechGeeky** [comment]
Thanks @Shane32. This is what I got here. I hope this is what you meant and I got it right but how do I use this now?
Since I still use graphql version 3, looks like it has to be used in ExecutionOptions right? If yes, then how should I use it?

```
    public interface IAuthChecker
    {
        Task<bool> Authorized(IEnumerable<string> policies);
    }

    public class MySchemaFilter : ISchemaFilter
    {
        private readonly IAuthChecker _authChecker;

        public MySchemaFilter(IAuthChecker authChecker)
        {
            _authChecker = authChecker;
        }

        public Task<bool> AllowType(IGraphType type)
        {
            var policies = type.GetMetadata<List<string>>("authPolicies");
            return _authChecker.Authorized(policies);
        }

        public Task<bool> AllowField(IGraphType parent, IFieldType field)
        {
            return Task.FromResult(true);
        }

        public Task<bool> AllowArgument(IFieldType field, QueryArgument argument)
        {
            return Task.FromResult(true);
        }

        public Task<bool> AllowEnumValue(EnumerationGraphType parent, EnumValueDefinition enumValue)
        {
            return Task.FromResult(true);
        }

        public Task<bool> AllowDirective(DirectiveGraphType directive)
        {
            return Task.FromResult(true);
        }
    }
```

**Comment by Shane32** [comment]
Right; so just set it in the `ExecutionOptions.SchemaFilter = new MySchemaFilter();`  maybe.

Now if you want to hide everything, you might want to return `false` for everything.  Although I see you have the concept there where it checks the auth policy before showing the graph in the list.

**Comment by TechGeeky** [comment]
Is auth policy needed here? In my case I just simply wants to hide everything for any introspection related stuff.

**Comment by TechGeeky** [comment]
If I do this `ExecutionOptions.SchemaFilter = new MySchemaFilter();` then it complains because I don't have `MySchemaFilter` constructor with no arguments. @Shane32

**Comment by Shane32** [comment]
pull the schema filter from DI

**Comment by TechGeeky** [comment]
You mean like this @Shane32 

```
            services.AddGraphQL((options, serviceProvider) =>
            {
                options.EnableMetrics = false;
                options.SchemaFilter = serviceProvider.GetRequiredService<ISchemaFilter>();

            })
```

**Comment by Shane32** [comment]
`ExecutionOptions.SchemaFilter = ExecutionOptions.RequestServices.GetRequiredService<MySchemaFilter>();`

**Comment by Shane32** [comment]
yup

**Comment by Shane32** [comment]
you'll need to register it with DI of course.

**Comment by TechGeeky** [comment]
so I got like these - I hope that's what you meant. @Shane32 

            services.AddSingleton<ISchemaFilter, MySchemaFilter>();
            services.AddGraphQL((options, serviceProvider) =>
            {
                options.EnableMetrics = false;
                options.SchemaFilter = serviceProvider.GetRequiredService<ISchemaFilter>();

            })

Now confuse on authpolicy stuff which I don't have anything configured on my end at all. Do I need to configure anything or this will work as it is and all introspection related code will fail here?

**Comment by Shane32** [comment]
red alert!!  in version 3, even though the schema filter is set within the execution options, it's a setting on the schema.  **That means that if you have a singleton schema, you must have a singleton ISchemaFilter.**  This was fixed in version 4, where the schema filter is set in the schema constructor so you can't make this mistake.

**Comment by Shane32** [comment]
so just be sure to register the ischemafilter as a singleton -- and if it uses IAuthChecker, it must be a singleton also

**Comment by Shane32** [comment]
but if all you want to do is, basically hide all introspection queries, then just return `Task.FromResult(false)` for everything and remove the authchecker class.

**Comment by Shane32** [comment]
i've never used the schema filter actually, but as far as I can tell, what you have should work.

**Comment by TechGeeky** [comment]
> red alert!! in version 3, even though the schema filter is set within the execution options, it's a setting on the schema. **That means that if you have a singleton schema, you must have a singleton ISchemaFilter.** This was fixed in version 4, where the schema filter is set in the schema constructor so you can't make this mistake.

This is what we have in the code - Does this look right to you for version 3?

```
            services.AddSingleton<ISchema, SampleProjectSchema>();
            services.AddSingleton<ISchemaFilter, MySchemaFilter>();
            services.AddGraphQL((options, serviceProvider) =>
            {
                options.EnableMetrics = false;
                options.SchemaFilter = serviceProvider.GetRequiredService<ISchemaFilter>();
    
            })
```

And here is my updated `MySchemaFilter` class without `authchecker` class.

```
    public class MySchemaFilter : ISchemaFilter
    {
        public MySchemaFilter() { }

        public Task<bool> AllowType(IGraphType type)
        {
            // var policies = type.GetMetadata<List<string>>("authPolicies");
            // return _authChecker.Authorized(policies);
            return Task.FromResult(false);
        }

        public Task<bool> AllowField(IGraphType parent, IFieldType field)
        {
            return Task.FromResult(false);
        }

        public Task<bool> AllowArgument(IFieldType field, QueryArgument argument)
        {
            return Task.FromResult(false);
        }

        public Task<bool> AllowEnumValue(EnumerationGraphType parent, EnumValueDefinition enumValue)
        {
            return Task.FromResult(false);
        }

        public Task<bool> AllowDirective(DirectiveGraphType directive)
        {
            return Task.FromResult(false);
        }
    }
```

I am gonna try it out now to see if it works.

**Comment by Shane32** [comment]
looks good to me

**Comment by TechGeeky** [comment]
@Shane32 For some weird reason I am getting this error but I already have it registered as shown above basically. Do you know what's wrong here?

```
 No service for type 'Project.Api.Data.MySchemaFilter' has been registered.
```

**Comment by TechGeeky** [comment]
@Shane32  For some weird reason I am getting this error but I already have it registered as shown above basically. Do you know what's wrong here?

```
 No service for type 'Project.Api.Data.MySchemaFilter' has been registered.
```

**Comment by Shane32** [comment]
You're attempting to pull in `MySchemaFilter` in a constructor or via `GetRequiredService`, rather than `ISchemaFilter`.  Either change it to be `ISchemaFilter`, which is probably what I'd do ... or change your registration to register it as itself rather than as `ISchemaFilter`, as shown below:

```cs
services.AddSingleton<MySchemaFilter>();
```

**Comment by TechGeeky** [comment]
Okay that makes sense. When I run this below query on `ui/playground`  - 

```
{
  __type(name: "TestSchema") {
    name
    fields {
      name
      type {
        name
        kind
      }
    }
  }
}
```

then I get response as where fields is empty which I think is happening because of above introspection code I added. So I think it works.

```
{
  "data": {
    "__type": {
      "name": "TestSchema",
      "fields": []
    }
  }
}
```

But weird thing I am noticing is whenever I load `ui/playground` url on the browser I see this below message. Whenever I refresh `ui/playground` url I always see below error but as soon as I hit actual query this error is gone and I see actual response so I am not sure why this is getting shown. Any idea? @Shane32 

```
{
  "error": "Invalid or incomplete schema, unknown type: Query. Ensure that a full introspection query is used in order to build a client schema."
}
```

**Comment by Shane32** [comment]
Playground and GraphiQL rely on the Apollo GraphQL library to parse an introspection request for the auto completion capability. Since it’s not allowed for an object type to have no fields, it thinks the schema is invalid. In this case it would seem that it’s querying for the “query” type, which is required, and not getting a response.

**Comment by TechGeeky** [comment]
So you think this is fine and will not cause any issues whatsoever? or there is any way to fix this? I also see this in playground but server is up and running and request works fine. Not sure it is related to introspection stuff. @Shane32 

![image](https://user-images.githubusercontent.com/12375611/141421255-fc3a2484-34f7-445a-a7fd-55b24181e1da.png)

**Comment by Shane32** [comment]
As far as I know it shouldn’t have any ill effect. 

To eliminate the error you could have the schema filter return true for the query type or something probably. You’d have to play around with it.

**Comment by TechGeeky** [comment]
I did something like this in my above `MySchemaFilter` class as you mentioned -

```
        public Task<bool> AllowType(IGraphType type)
        {
            if(type != null && type.Name.Equals("Query"))
                return Task.FromResult(true);
            return Task.FromResult(false);
        }
```

But now I get different error whenever I load `ui/playground` -

```
{
  "error": "Invalid schema Error:\nType Query must define one or more fields."
}
```

I am confuse now what else should I check so that I don't get any error on ui/playground. Will you be able to help on this whenever you get a chance? @Shane32

**Comment by TechGeeky** [comment]
I did something like this in my above `MySchemaFilter` class as you mentioned -

```
        public Task<bool> AllowType(IGraphType type)
        {
            if(type != null && type.Name.Equals("Query"))
                return Task.FromResult(true);
            return Task.FromResult(false);
        }
```

But now I get different error whenever I load `ui/playground` -

```
{
  "error": "Invalid schema Error:\nType Query must define one or more fields."
}
```

I am confuse now what else should I check so that I don't get any error on ui/playground. Will you be able to help on this whenever you get a chance? @Shane32

**Comment by Shane32** [comment]
An object type is invalid if it contains no fields.  So you'd have to change the AllowField to return true for at least one field on the query type.  Of course, if it references another object type, you'd have to return true for that object type, and return true for at least one field on that type, and so on.  ui/playground is going to keep giving failures until the introspection query returns a valid schema.
