### ISSUE TITLE
Schema.For does not always decode default values correctly

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2695]
If a default value is dependent on another default value, Schema.For may decode (convert from AST to value representation) default values in the wrong order.

For example:

```gql
type Query {
    post(arg: SomeInputType = { name: ""John"" }): String
}

input SomeInputType {
    id: ID! = 1
    name: String!
}
```

In the above sample, the default value of `post` is coerced from an AST to a value prior to the default value of `id`.  So the default value for input argument `arg` is a `Dictionary<string, object>` with `name: "John"` but `id` equals an AST node instead of `1`.

At present, this is due to the validation walker coercing the default values in the order that it walks the node.

To fix this, the schema builder should do the following prior to the schema validation:

1. Scan all input types for fields with default values.
2. Sort the list as necessary based on dependencies.
3. Coerce default values in proper order, or throw an exception if there is a circular dependency based on default values.

So long as all the input types have been coerced, the remaining default values (for directives, arguments, variables, etc) will parse correctly.

**Comment by Shane32** [comment]
Another solution: modify the validation walker so that it always walks input types first, and in the correct order.

**Comment by Shane32** [comment]
Another solution: modify the schema builder to add types to the schema in the correct order, so that the validation walker will fix up default values correctly.

**Comment by sungam3r** [comment]
Have you look at https://github.com/graphql/graphql-spec/pull/793 ?
