### ISSUE TITLE
Get the input values in the order they were supplied

### ISSUE THREAD

**Issue by mariusbancila** [graphql-dotnet/graphql-dotnet#2701]
I have a schema where fields have several parameters, and one of them is a sort order. A query may look like this:

```
{
   users(sortOrder : {name : DESC, id : ASC}) {
      totalCount
      items {
         id
         name         
      }
   }
}
```

The problem is, the `Argument.Value` is a `Dictionary<string, object>`. So I get the data as:

```
{
   "id" : ASC,
   "name" : DESC
}
```

This does not allow me to know what order the values were supplied by the user. 

Is there any possibility to parse them in the given order? Or do I have to build something like an array of values:

```
{
   users(sortOrder : [{name : DESC}, {id : ASC}]) {
      totalCount
      items {
         id
         name         
      }
   }
}
```
This is the best I could come up with as an alternative.

**Comment by Shane32** [comment]
Enumerating `context.FieldAst.Arguments` should allow you to determine the order in which the arguments were supplied.  Note that `context.FieldAst.Arguments` may be `null` if no arguments were supplied.

I suggest using `context.GetArgument` to retrieve the actual values of those arguments, so the values can be parsed by the proper scalar type, converted if necessary, default argument values applied, and/or read from variables.

**Comment by Shane32** [comment]
Unfortunately I see you're trying to determine the order of the fields inside the argument's value.  This can be done also in a similar fashion -- but only if the `sortOrder` argument is passed as a literal.  Otherwise ... well, it is possible to write your own dictionary implementation which retains the order of elements added to it, then rewrite `GraphQL.SystemTextJson.InputsConverter` to use that custom dictionary type you created.  Perhaps implement similar changes in GraphQL for literals.  Then you might write a custom scalar for the sortorder object, with ParseDictionary overridden to interpret the object as passed in.  But I don't know that all this effort is worth it.

While your original concept is pretty cool, I would probably just do this:

```gql
{
  users (sortOrder: [{ by: NAME }, { by: ID, descending: true }] {
    totalCount
    items {
      id
      name
    }
  }
}
```

This way, the fields names are an enumeration type, and the `descending` field has a default value of false.  Then it is really easy to build a IEnumerable or IQuerablye as necessary like this:

```cs
public class Widget
{
    public string Name { get; set; }
    public string Value { get; set; }
}

class SortBy
{
    public WidgetFields By { get; set; }
    public bool Descending { get; set; }
}

enum WidgetFields
{
    Name,
    Value
}

//IEnumerable or IQueryable should work here
IEnumerable<Widget> Sort(this IEnumerable<Widget> data, IEnumerable<SortBy> sortBy)
{
    if (sortBy == null)
        return data;

    bool first = true;
    IOrderedEnumerable<Widget> ordered = null;
    foreach (var sortOrder in sortBy)
    {
        if (first)
        {
            switch (sortOrder.By)
            {
                case WidgetFields.Name when !sortOrder.Descending:
                    ordered = data.OrderBy(x => x.Name);
                    break;
                case WidgetFields.Name when sortOrder.Descending:
                    ordered = data.OrderByDescending(x => x.Name);
                    break;
                case WidgetFields.Value when !sortOrder.Descending:
                    ordered = data.OrderBy(x => x.Value);
                    break;
                case WidgetFields.Value when sortOrder.Descending:
                    ordered = data.OrderByDescending(x => x.Value);
                    break;
            }
        }
        else
        {
            switch (sortOrder.By)
            {
                case WidgetFields.Name when !sortOrder.Descending:
                    ordered = ordered.ThenBy(x => x.Name);
                    break;
                case WidgetFields.Name when sortOrder.Descending:
                    ordered = ordered.ThenByDescending(x => x.Name);
                    break;
                case WidgetFields.Value when !sortOrder.Descending:
                    ordered = ordered.ThenBy(x => x.Value);
                    break;
                case WidgetFields.Value when sortOrder.Descending:
                    ordered = ordered.ThenByDescending(x => x.Value);
                    break;
            }
        }
    }

    return first ? data : ordered;
}
```

This probably makes it easier to build the object in javascript anyway, as you can just push entries to an array to get the desired sort order.

**Comment by Shane32** [comment]
But your alternate idea would work well too -- `users(sortOrder : [{name : DESC}, {id : ASC}])`

**Comment by mariusbancila** [comment]
The idea of implementing my own dictionary and rewriting the `InputsConverter` seems interesting but might be too much work for something I can achieve differently.

The idea is that this schema is already in production and this is a bug we discovered which I am working to fix. I need to maintain backward compatibility as much as possible. So, currently, I think my best option would be to:

- keep `sortOrder` as it is now but limit it to a single value, which would work fine
- provide an additional `sortOrders` which is an array of values as I showed in my example

**Comment by Shane32** [comment]
Makes sense to me.

**Comment by mariusbancila** [comment]
I actually managed to find an easy fix. 

I replaced this code:
```
var sortOrderArgDef = ctx.FieldDefinition.Arguments?.FirstOrDefault(arg => arg.Name == "sortOrder");
var sortInputType = sortOrderArgDef.ResolvedType as InputObjectGraphType;

if (sortOrderArgDef is object && ctx.Arguments is object && ctx.Arguments.TryGetValue("sortOrder", out ArgumentValue sortOrder))
{
   if (sortOrder.Value is Dictionary<string, object> sortMemberDictionary)
   {
      foreach (var sortFieldName in sortMemberDictionary.Keys)
      {
         // handle it here
      }
   }            
}
```

with this code:
```
var sortOrderArgDef = ctx.FieldDefinition.Arguments?.FirstOrDefault(arg => arg.Name == "sortOrder");
var sortInputType = sortOrderArgDef.ResolvedType as InputObjectGraphType;

var arg = ctx.FieldAst.Arguments.FirstOrDefault(a => a.Name == "sortOrder");
if (arg is object)
{ 
   foreach(ObjectValue child in arg.Children)
   {
      foreach(ObjectField field in child.ObjectFields)
      {
         var sortClauseType = sortInputType.GetField(field.Name);
         if (Enum.TryParse<SortOrder>(field.Value.Value.ToString(), out var sortValue))
         {
            // handle it here
         }
      }
   }
}
```
This is exactly what I was looking for. Works like a charm.

**Comment by Shane32** [comment]
But that won’t work if the sort order is passed in a variable - correct?

**Comment by mariusbancila** [comment]
> But that won’t work if the sort order is passed in a variable - correct?

That's correct. I didn't think of that, but I checked it and you're right. Thanks for pointing it out.

**Comment by mariusbancila** [comment]
For the sake of reference, since others might read this looking for a similar solution, I decided to go with the following solution to be both backward compatible and support multiple sort order fields at the same time.

```
{
   users(sortOrder : {
         name : DESC
         _thenBy : {
            registrationDate : ASC
            _thenBy : {
               id : DESC
            }
         }})
   {
      totalCount
      items {
         id
         name         
      }
   }
}
```

The resolved type of the `_thenBy` field is the type of the `sortOrder` field, so this goes recursively as much as needed. And it's pretty easy to parse it, It also works with variables:

```
{
  "order" :{
      "name" : "DESC",
      "_thenBy" : {
        "registrationDate" :"ASC",
        "_thenBy" : {
          "id" :"DESC"
        }}}
}
```
