### ISSUE TITLE
Query with two fields with the same alias doesn't fail validation

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2703]
See validation rule 5.3.2:
- http://spec.graphql.org/October2021/#sec-Field-Selection-Merging

Needs verification & test

**Comment by Shane32** [comment]
This is due to `OverlappingFieldsCanBeMerged.Instance` not added to the default set of `CoreRules` in DocumentValidator:34

**Comment by Shane32** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/aa68c0540b6ad20fb7754b9a67b47a111f8cf4cb/src/GraphQL/Validation/DocumentValidator.cs#L32

**Comment by Shane32** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/aa68c0540b6ad20fb7754b9a67b47a111f8cf4cb/src/GraphQL/Validation/Rules/OverlappingFieldsCanBeMerged.cs#L19

**Comment by sungam3r** [comment]
I remember this code. Is it all bad in reality?

**Comment by Shane32** [comment]
I don’t know.
