### ISSUE TITLE
Issue with datetime input inside string field

### ISSUE THREAD

**Issue by mamasselin** [graphql-dotnet/graphql-dotnet#271]
Hi,

I recently started working on a project with your library and just found out that there might be an issue when passing "datetime-like" strings inside string fields.

Here's an explanation of my problem:

I have a class with a string field inside, like this:

```c#
public class Item
{
    public string Value { get; set;}
}
```

With corresponding GraphType and InputGraphType as below:
```c#
public class ItemType : ObjectGraphType<Item>
{
    public ItemType()
    {
        Field(x => x.Value);
    }
}

public class ItemInputType : InputObjectGraphType
{
    public ItemInputType()
    {
        Field<StringGraphType>("value");
    }
}
```

If I send a mutation with an ISO formatted datetime string, the corresponding argument is set to null in my resolver context.

Example of ISO formatted datetime string:
```json
{
    "ItemInputType": { "value": "2017-01-27T15:19:53.000Z" }
}
```

When I send a mutation with any other random text it works just fine.

I forked the master branch and created a unit test that replicates this issue.

Please see pull request #272 

cc: @cstlaurent

**Comment by joemcbride** [comment]
Because it is a date string, it is probably getting converted to a `DateValue`, which the `StringGraphType` does not know how to handle.  Are you able to use the `DateGraphType` instead of the `StringGraphType`?  Is there a reason why you want to just use the string?

**Comment by mamasselin** [comment]
Thanks for the quick response.

I can't use `DateGraphType` because my field will contain any kind of string values, including date strings.

I haven't had the chance to look deeper into this yet, so I'm just throwing some ideas here:

Would it be possible for the `StringGraphType` to fallback to the `.ToString()` of the object if it's from a different type?

Alternatively, the json could be interpreted as a string when deserializing (I assume by removing the `DateFormatHandling.IsoDateFormat` setting from the serializer), and if it's going into a `DateGraphType` only then it would be parsed as a `DateTime`?

**Comment by mamasselin** [comment]
I added the following setting to the JSON Serializer and it seems to solve my problem:
`DateParseHandling = DateParseHandling.None`

But now the following test fails because the date is converted to my local time for some reasons:
```c#
public void can_convert_utc_date_to_datetime_with_correct_kind()
{
    var json = @"{ 'h': '2016-10-21T13:32:15.753Z' }";
    var expected = DateTime.SpecifyKind(DateTime.Parse("2016-10-21T13:32:15.753"), DateTimeKind.Utc);

    var inputs = json.ToInputs();
    var myInput = inputs.ToObject<MyInput>();

    myInput.ShouldNotBeNull();
    myInput.H.ShouldBe(expected);  
    // Fail reason: myInput.H is now in my local time (2016-10-21T09:32:15.753)
}
```

**UPDATE:**

I made a small change in the ObjectExtensions.cs class to account for the above issue. I updated the ConvertValue method to look like this:
```c#
public static object ConvertValue(object value, Type fieldType)
{
    if (value == null) return null;

    if (fieldType == typeof(DateTime))
    {
        DateTime dateTimeValue;
        if (DateTime.TryParse($"{value}", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out dateTimeValue))
        {
            return dateTimeValue;
        }
    } 

    var text = value.ToString();
    return _conversions.Value.Convert(fieldType, text);
}
```

Could you please take a look at my pull request and see if that makes sense to you?
#272

**Comment by joemcbride** [comment]
Thanks for the PR!  There is another issue as well, https://github.com/graphql-dotnet/graphql-dotnet/issues/197, which this fix may tie into.  I want to pull this down and play with it a little bit but I think what you've done will probably work.  I should be able to do that on Friday.  Thanks again!

**Comment by joemcbride** [comment]
This fix is now published to Nuget, thanks!

**Comment by lngr** [comment]
This breaks UTC Dates that are resolved within resolvers.

**Comment by Palpie** [comment]
I'm having problem with this in 3.4.0. Do I need to do something to get the fix to work?

I've tried different formats and all of them becomes null:

- "2020-04-07T22:00:00.000Z"
- "2020-04-07T22:00:00.000+02:00"
- "2020-04-07T22:00:00"

I use this in a "custom fields" part, where the clients can send client specific data for a user in a array of key/value objects. Works fine, except for with datetime strings.

Why does it even try to parse it as a DateTime when I have configured the field to be a StringGraphType?

**Comment by mamasselin** [comment]
Maybe look at your serialization settings as mentioned in #1204 

On my end, I ended up creating a custom type based on`StringGraphType` and override the `ParseLiteral` method as below:

```c#
using System;
using GraphQL.Language.AST;
using GraphQL.Types;

public class StringThatCouldBeFormattedAsDateTimeGraphType : StringGraphType
{
    public StringThatCouldBeFormattedAsDateTimeGraphType ()
    {
        Name = nameof(StringThatCouldBeFormattedAsDateTimeGraphType);
    }

    public override object ParseLiteral(IValue value)
    {
        if (value is DateTimeValue)
        {
            return ((DateTime)value.Value).ToString("O"); // "O" = ISO 8601
        }
        return base.ParseLiteral(value);
    }
}
```

Then I use this in my input types instead of the regular `StringGraphType` so that even when passing an ISO 8601 formatted string, it keeps it as a string.

Not sure how good or bad this is but it resolved my issue.

**Comment by Palpie** [comment]
It solved it for me too so I'm happy! 

Thanks for your help!
