### ISSUE TITLE
Remove LGTM integration?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2718]
See https://github.com/graphql-dotnet/graphql-dotnet/settings/installations

I don't remember how/when I installed this integration. Perhaps this was done by @joemcbride. I don't know if LGTM.com is necessary anymore after #2717. Perhaps CodeQL workflow and LGTM integration are interconnected in some way. I see analysis report from CodeQL worflow in GitHub UI and I think that this is quite enough for at least yet. Personally, I would not like to have integration with LGTM, which I do not understand and/or not use.

**Comment by Shane32** [comment]
I would also suggest removing it.

**Comment by sungam3r** [comment]
@joemcbride Could you please remove LGTM integration. I think I have no access to do this operation.

**Comment by sungam3r** [comment]
@joemcbride bump

**Comment by sungam3r** [comment]
dup of #2428
