### ISSUE TITLE
Incorrect resolver return type when using batch loader and GraphQL.MicrosoftDI

### ISSUE THREAD

**Issue by alekbarszczewski** [graphql-dotnet/graphql-dotnet#2727]
## Summary
Without GraphQL.MicrosoftDI it works:

```csharp
Field<NonNullGraphType<OrgType>, OrgProto>()
    .Name("org")
    .Description("Organization details")
    .ResolveAsync(context => accessor.Context
        .GetOrAddBatchLoader<long, OrgProto>(
            loaderKey: context.Path + context.FieldAst.Name,
            fetchFunc: batchLoaders.Orgs(context))
        .LoadAsync(context.Source.OrgId)); // LoadAsync returns IDataLoaderResult<Org>
```

However when using GraphQL.MicrosoftDI and .WithService() I get compile error:

```csharp
Field<NonNullGraphType<OrgType>, OrgProto>()
    .Name("org")
    .Description("Organization details")
    .Resolve() // <=== Resolve
    .WithService<BatchLoaders>() // <=== WithService
    .ResolveAsync((context, batchLoaders) => accessor.Context
        .GetOrAddBatchLoader<long, OrgProto>(
            loaderKey: context.Path + context.FieldAst.Name,
            fetchFunc: batchLoaders.Orgs(context))
        .LoadAsync(context.Source.OrgId));
```

I get following compile error:
```
Cannot convert expression type 'GraphQL.DataLoader.IDataLoaderResult<Flymachine.Proto.Orgs.Org>' 
to return type 'System.Threading.Tasks.Task<Flymachine.Proto.Orgs.Org>'
```

Why I get this error? It seems I can fix this by using `.LoadAsync(...).GetResultAsync()` but I am not sure if it won't break batch loader functionality?:

```csharp
Field<NonNullGraphType<OrgType>, OrgProto>()
    .Name("org")
    .Description("Organization details")
    .Resolve() // <=== Resolve
    .WithService<BatchLoaders>() // <=== WithService
    .ResolveAsync((context, batchLoaders) => accessor.Context
        .GetOrAddBatchLoader<long, OrgProto>(
            loaderKey: context.Path + context.FieldAst.Name,
            fetchFunc: batchLoaders.Orgs(context))
        .LoadAsync(context.Source.OrgId).GetResultAsync()); // <=== .GetResultAsync(), no compile error
```

~~Is it okay to return `IDataLoaderResult.GetResultAsync()` here? I had no chance yet to test it properly as I am rewriting pretty big schema which fails to compile for now...~~ - finally managed to compile and run the schema and for sure `GetResultAsync()` can't be used because it causes batch-loaders to execute separately and not in batch. So the problem is with types when using `Resolve().WithService<Service>().ResolveAsync(...)`.

### Environment (if relevant)

GraphQL.net 4.5.0
.net 5.0
C# 9

**Comment by Shane32** [comment]
Technically the data loader's LoadAsync method is a synchronous method, not asynchronous.  So properly it should not have been called `LoadAsync` at all, which is what makes this confusing.

Just change your code like this and all will be fine:

```cs
Field<NonNullGraphType<OrgType>, IDataLoaderResult<OrgProto>>()
    .Name("org")
    .Description("Organization details")
    .Resolve() // <=== Resolve
    .WithService<BatchLoaders>() // <=== WithService
    .Resolve((context, batchLoaders) => accessor.Context
        .GetOrAddBatchLoader<long, OrgProto>(
            loaderKey: context.Path + context.FieldAst.Name,
            fetchFunc: batchLoaders.Orgs(context))
        .LoadAsync(context.Source.OrgId));
```

I don't see a real easy to write an extension method to 'fix' this.  FYI, the reason the other syntax works is because there are a number of extension methods in `DataLoaderExtensions.cs` defined to allow that and similar syntax.

**Comment by alekbarszczewski** [comment]
Perfect, thanks! It works now.
