### ISSUE TITLE
Expose ancestors from TypeInfo in more comfortable way

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2735]
See `if (context.TypeInfo.GetAncestor(i++) == actualOperation)` from graphql-dotnet/authorization#171

**Comment by Shane32** [comment]
At least for now, can we just add `context.TypeInfo.Ancestors` as a get property to return the count?

**Comment by sungam3r** [comment]
Most likely. I did not do it just to not redo several times. This issue will be solved in v5 (or even before) in one or another way.

**Comment by Shane32** [comment]
> This issue will be solved in v5 (or even before) in one or another way.

Done?

**Comment by sungam3r** [comment]
Not needed anymore.
