### ISSUE TITLE
First Character of Field Name becoming Lowercase

### ISSUE THREAD

**Issue by pravinhabbu4u** [graphql-dotnet/graphql-dotnet#275]
@joemcbride I have node and graphql-dotnet implementation for GraphQL. graphql-dotnet implementation is automatically converting first character of field name to lower case. Is there any way to avoid this issue? I am currently using GraphQL (0.14.6.657) from Nuget. Below is an example query and output on node and dot-net core.

Node Input & Output example:

```
query TestForFieldCase{
  Identity(id:"b4d13602-57f6-46da-b071-b4e35ddd272b"){
    Data{
      IdentityID
   	  FirstName
      LastName
    }
  }
}
```

Output: Note: I also have a field named Data in response 

```
{
  "data": {
    "Identity": {
      "Data": {
        "IdentityID": "b4d13602-57f6-46da-b071-b4e35ddd272b",
        "FirstName": "PRAVIN",
        "LastName": "HABBU"
      }
    }
  }
}
```

GraphQL dot net implementation example:
Input:

```
query TestForFieldCase{
  identity(id:"b4d13602-57f6-46da-b071-b4e35ddd272b"){
    Data{
      identityID
   	  firstName
      lastName
    }
  }
}
```

Output:

```
{
  "data": {
    "identity": {
      "data": {
        "identityID": "b4d13602-57f6-46da-b071-b4e35ddd272b",
        "firstName": "PRAVIN",
        "lastName": "HABBU"
      }
    }
  }
}
```

**Comment by joemcbride** [comment]
Short answer is no, that is not currently supported.  https://github.com/graphql-dotnet/graphql-dotnet/issues/169

**Comment by pravinhabbu4u** [comment]
@joemcbride My hack attempt on at [https://github.com/graphql-dotnet/graphql-dotnet/issues/169#issuecomment-277821315](url) has given me another idea. Instead of renaming field with a prefix why cant we have another implementation for FIELD method as FIELD_UDC - user defined case. This method can avoid converting first character of field to lower case/ camel case. I need your advice on how you feel about this suggestion. I was able to successfully achieve the results wanted using this change. I can submit a pull request if it makes any sense to you.

       public FieldBuilder<TSourceType, TProperty> Field_UDC<TProperty>(
            Expression<Func<TSourceType, TProperty>> expression,
            bool nullable = false,
            Type type = null)
        {
            string name;
            try
            {
                name = expression.NameOf().ToUserCase();   // Retains user defined case than camel case
            }
            catch
            {
                throw new ArgumentException(
                    $"Cannot infer a Field name from the expression: '{expression.Body.ToString()}' " +
                    $"on parent GraphQL type: '{Name ?? GetType().Name}'.");
            }
            return Field(name, expression, nullable, type);
        }


        public static string ToUserCase(this string s)
        {
            if (string.IsNullOrWhiteSpace(s))
            {
                return string.Empty;
            }
            return s;
        }


Usage:
      Field_UDC(x => x.IdentityID, nullable: true).Description("");
than Field(x => x.IdentityID, nullable:true).Description("");

Document Writer using custom case resolver:
        public DocumentWriter(bool indent)
            : this(
                indent ? Formatting.Indented : Formatting.None,
                new JsonSerializerSettings
                {
                    ContractResolver = new  CustomCaseResolver(),
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFF'Z'",
                })
        {
        }


    public class CustomCaseResolver : DefaultContractResolver
    {
        protected override string ResolvePropertyName(string propertyName)
        {
            string s = propertyName;
            return propertyName;
          //  return propertyName.ToLowerInvariant() == "errors" || propertyName.ToLowerInvariant() == "data"
          //      ? propertyName.ToLowerInvariant()
         //       : propertyName;
        }
    }

**Comment by joemcbride** [comment]
No, I don't think I would want to maintain "yet another way to register a field".  Have way too many of those already.

My thoughts on solving this issue are kind of similar to your `CustomCaseResolver` though I would want the GraphQL Engine to handle it and not the JSON Serializer.  This is because I do not think you have enough context in the serializer to know what case a field requires.  So here is what I think should be done - this is semi-pseudo code.

```
var result = await new DocumentExecuter().ExecuteAsync( _ =>
{
  _.Schema = schema;
  _.FieldNameConverter = new CamelCaseFieldNameConverter();

  ...

}).ConfigureAwait(false);

public class CamelCaseFieldNameConverter : IFieldNameConverter
{
  public string NameFor(string field, Type parentType)
  {
    return field.ToCamelCase();
  }
}

public class UnchangedNameConverter : IFieldNameConverter
{
  public string NameFor(string field, Type parentType)
  {
    if( isIntrospectionType(parentType) )
    {
      return field.ToCamelCase();
    }

    return field;
  }
}

public class PascalNameConverter : IFieldNameConverter
{
  public string NameFor(string field, Type parentType)
  {
    if( isIntrospectionType(parentType) )
    {
      return field.ToCamelCase();
    }

    return field.ToPascalCase();
  }
}
```

I'm not sure how much effort adding this feature will be though I think that will allow everyone to have their pick of how field names should be handled.

**Comment by pravinhabbu4u** [comment]
@joemcbride Thanks for the response. I am trying to understand above change to see if it will allow us to 
1. Query fields using user defined case???
+
2. See fields in response in user defined case

Do you want me to look into implementation of above change? Kindly advise. Thanks!

**Comment by joemcbride** [comment]
@pravinhabbu4u just pushed up a spike of the behavior I described in #277.  It should support what you are trying to accomplish.

**Comment by pravinhabbu4u** [comment]
@joemcbride Do you have any tentative date for making this change available on nuget package?

**Comment by joemcbride** [comment]
@pravinhabbu4u I don't ... I am traveling this week so not sure when I can get to it.  If things clear up in the next day or two I'll see if I can do the updates I need and get it pushed.

**Comment by ironpython2001** [comment]
looking for the same.

**Comment by sungam3r** [comment]
It's done long ago https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionOptions.cs#L62

**Comment by ironpython2001** [comment]
i got the nuget package . i see it is not working... is it published in nuget.

**Comment by sungam3r** [comment]
See readme: https://github.com/graphql-dotnet/graphql-dotnet#installation

**Comment by ironpython2001** [comment]
thanks for the information . using the packages GraphQL.SystemTextJson, GraphQL.NewtonsoftJson with the latest graphql 2.0.0 (stable ) library has lot of compartible issues with warnings.

**Comment by sungam3r** [comment]
These packages are dependent on a higher GraphQL-dotnet version 3.0.0-preview-XXXX. They **will not work** with any 2.X.X version.

**Comment by GeXiaoguo** [comment]
> It's done long ago https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionOptions.cs#L62

and also this: https://github.com/graphql-dotnet/graphql-dotnet/pull/277

**Comment by amroczeK** [comment]
If anyone is still looking to resolve this issue, you can do the following to prevent GraphQL.Client.Serializer.SystemTextJson from converting the capital to lowercase, by overriding the serializer options.

```
// using GraphQL.Client.Serializer.SystemTextJson;
// using System.Text.Json;
var client = new GraphQLHttpClient(_authOptions.GraphQlUrl, new SystemTextJsonSerializer(new JsonSerializerOptions()));
```

For reference my GraphQLRequest below, queryParams key names would convert from KeyName to keyName before implementing the solution I mentioned above.
```
public GraphQLRequest CreateRequest(string xdsName, string xdsViewName, string version, dynamic queryParams)
        {
            var request = new GraphQLRequest
            {
                Query = Constants.Query,
                Variables = new
                {
                    egressDataXdsName = xdsName,
                    egressDataViewName = xdsViewName,
                    egressDataVersion = version,
                    egressDataIncludeTimeZone = false,
                    egressDataParams = queryParams
                }
            };
            return request;
        }
```
