### ISSUE TITLE
Hello World Sample Broken?

### ISSUE THREAD

**Issue by MelbourneDeveloper** [graphql-dotnet/graphql-dotnet#2759]
Hi. I'm trying to get the most basic Hello World sample working but it doesn't compile. I created a .NET 6 console app, added the 4.6.1 NuGet package and I get compilation errors.

> CS1929	'Schema' does not contain a definition for 'ExecuteAsync' and the best extension method overload 'DocumentExecuterExtensions.ExecuteAsync(IDocumentExecuter, Action<ExecutionOptions>)' requires a receiver of type 'IDocumentExecuter'

```csharp
using System;
using System.Threading.Tasks;
using GraphQL;
using GraphQL.Types;
using GraphQL.SystemTextJson;

public class Program
{
  public static async Task Main(string[] args)
  {
    var schema = Schema.For(@"
      type Query {
        hello: String
      }
    ");

    var json = await schema.ExecuteAsync(_ =>
    {
      _.Query = "{ hello }";
      _.Root = new { Hello = "Hello World!" };
    });

    Console.WriteLine(json);
  }
}
```

The method seems to require two arguments - the first of type `IDocumentWriter` 

This was the best sample I could come up with and it works to some extent but it's not a robust example at all. Is anyone able to correct this and add it to the documentation? Or, let me know what I've done wrong here?

Note, this is a .NET 6 console app.

```csharp
using GraphQL;
using GraphQL.Types;
using System.Text;

var schema = Schema.For(@"
  type Query {
    hello: String
  }
");

var root = new { Hello = "Hello World!" };
var json = await schema.ExecuteAsync(new DocumentWriter(),_ =>
{
    _.Query = "{ hello }";
    _.Root = root;
});

Console.WriteLine(json);

public class DocumentWriter : IDocumentWriter
{
    public async Task WriteAsync<T>(Stream stream, T value, CancellationToken cancellationToken = default)
    {
        await stream.WriteAsync(Encoding.UTF8.GetBytes((value as dynamic).Data.Result.Hello));
    }
}
```

**Comment by sungam3r** [comment]
Where did you get this example?

**Comment by MelbourneDeveloper** [comment]
Straight from the GitHub page but the documentation has the same thing.
________________________________

**Comment by MelbourneDeveloper** [comment]
@sungam3r 

![image](https://user-images.githubusercontent.com/16697547/146693784-9f19de3d-54f7-4ee7-b138-a73badd91837.png)

**Comment by Shane32** [comment]
The necessary extension method is within the `GraphQL.SystemTextJson` nuget package.  Have you installed it?  You will also need `using GraphQL.SystemTextJson;` for the compiler to find the extension.  You can also choose to use `GraphQL.NewtonsoftJson`.  The first code sample at the top of your issue should compile correctly as long as the serialization package is installed.

**Comment by MelbourneDeveloper** [comment]
Actually @sungam3r here is a better sample using `GraphQL.NewtonsoftJson`

```csharp
using GraphQL;
using GraphQL.NewtonsoftJson;
using GraphQL.Types;

var schema = Schema.For(@"
  type Query {
    hello: String
  }
");

var root = new { Hello = "Hello World!" };
var json = await schema.ExecuteAsync(new DocumentWriter(),_ =>
{
    _.Query = "{ hello }";
    _.Root = root;
});

Console.WriteLine(json);
```

The point is that the documentation doesn't make it clear that you need to add a reference to the JSON NuGet package and inject the `IDocumentWriter` in to `ExecuteAsync`

**Comment by MelbourneDeveloper** [comment]
@Shane32 

> The first code sample at the top of your issue should compile correctly as long as the serialization package is installed.

Thanks! That's what I was missing. Perhaps the documentation example should include the using statements so it's clear that there is an extension method the consumer needs to add.

@sungam3r

**Comment by sungam3r** [comment]
OK, I'll copy example from here https://graphql.org/code/#c-net
