### ISSUE TITLE
Provide GetInputExtension method

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2767]
See #2766 and https://github.com/graphql-dotnet/graphql-dotnet/pull/2766/files/37454fb25ec60890bc2bd28d1322eb2b339649b2#r773411975

**Comment by sungam3r** [comment]
v4.8 ?

**Comment by Shane32** [comment]
Input extensions are not supported in 4.8.

**Comment by sungam3r** [comment]
🤦‍♂️

**Comment by Shane32** [comment]
@sungam3r Has this been done?

**Comment by sungam3r** [comment]
Nope, #3615
