### ISSUE TITLE
Split IGraphQLBuilder to IServiceRegister

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2771]
See https://github.com/graphql-dotnet/graphql-dotnet/pull/2571/files/59c1188c0bc8868784afdc29a2e7cc3104778b48#r773423125

**Comment by Shane32** [comment]
I suggest the property on `IGraphQLBuilder` be named `Services`.

For example:

```cs
builder.Services.Register<IDocumentExecuter, MyDocumentExecuter>(ServiceLifetime.Singleton);
```

**Comment by sungam3r** [comment]
OK

**Comment by Shane32** [comment]
From @sungam3r :

> All `Register` methods are for `IServiceRegister` and all other `AddXXX` are for `IGraphQLBuilder`

Also `Configure` is for `IServiceRegister`

**Comment by sungam3r** [comment]
I'm working on it.
