### ISSUE TITLE
Source is null when resolve is used with an IEnumerable 

### ISSUE THREAD

**Issue by lanwin** [graphql-dotnet/graphql-dotnet#2777]
I am currently trying to migrate our codebase to 4.6.1 and felt about the following problem.

`Field<ListGraphType<MyObjectType>>("test", resolve: x => List.Where(h => h.Id == x.Source.Id));`

This worked for the old versions but now it throws a NullReferenceException cause Source is null. This is cause `Where` returns a `IEnumerable` and so the `Func` in `Where` is executed when the `GetEnumerator` is called and not when the resolve is done.

My guess is that the IResolveFieldContext instance is reused and cleared right after the resolve is called but before the IEnumerable is done.

A simple fix would be to add an ToArray after the Where. But that is error prone and its also inefficient cause its wasted allocated memory.

It would be very helpful and less error prone if graphql-dotnet could help here and in example could keep the field context until the IEnumerable is enumerated. Or simply do a ToArray of the returned object if resolve is IEnumerable and the GraphType is a list (while that would increase memory usage).

I would guess that for a lot of users of graphql-dotnet its not obvious why source is null in that case.

**Comment by sungam3r** [comment]
https://graphql-dotnet.github.io/docs/migrations/migration4#code-classlanguage-textiresolvefieldcontextcode-re-use

**Comment by Shane32** [comment]
Although this is "documented", I agree that in this case, the context should not be re-used.  The intent was to have no change to field resolvers for "normal" code.  Not being able to return a LINQ enumerable breaks that concept.  Also, the memory/speed impact of preserving the context is very small.  Likely much smaller than `.ToList()` or `.ToArray()`.

See PR #2779.

**Comment by gao-artur** [comment]
@Shane32 when 4.7 is planned to be released? This issue is a show stopper for us, finding all such places and using resolver copy requires too much effort.

**Comment by Shane32** [comment]
@gao-artur What is your timeline?  Would 1 week be fine?  If you really need 4.7 asap, lmk.

@sungam3r Sound okay?

Personally, I'd be fine releasing 4.7 now, and releasing 4.7.1 if there are additional changes.  Or even 4.8 if needed.

I'll be on the road for the next few days -- if you want to release it now, @sungam3r go ahead.

**Comment by sungam3r** [comment]
50/50. Release if you want.

**Comment by Shane32** [comment]
#2813

**Comment by gao-artur** [comment]
@Shane32 this is actually the last issue I have to resolve, planed to merge this week. Really appreciate the effort to release 4.7 asap, thank you very much!
