### ISSUE TITLE
How to return a result dynamically?

### ISSUE THREAD

**Issue by Kurren123** [graphql-dotnet/graphql-dotnet#278]
I don't know the fields I need at compile time. This example [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L94-L118) builds a schema dynamically:

```
var person = new ObjectGraphType();
person.Name = "Person";
person.Field("name", new StringGraphType());
person.Field(
    "friends",
    new ListGraphType(new NonNullGraphType(person)),
    resolve: ctx => new[] {new SomeObject {Name = "Jaime"}, new SomeObject {Name = "Joe"}});
```

However the field "name" is already compiled as a property in the `SomeObject` class. Is there a way I can return a value when I only know the fields at runtime? Maybe return a `Dictionary<String, Object>` or something?

Thanks for the help

**Comment by jquense** [comment]
You can't create truly dynamic graphql types unfortunately. They are by design statically defined, otherwise the client would never know what it's gonna get back based on the type. Alternatively you can use a UnionType if you only have a set amount of variants of your type. In JavaScript land we generally handle this sort of thing with a custom JSON scalar like: https://github.com/taion/graphql-type-json

**Comment by Kurren123** [comment]
@jquense  thanks for your reply. The schema is being built at runtime and the response will match the schema exactly so it's static in that sense, but I don't know the fields at compile time. Say I have a CSV file where the top row is a header row but I'm unsure of columns at compile time.

I can generate the schema from the CSV file at runtime, but how would I return the response?

Thanks for the help

**Comment by joemcbride** [comment]
You could theoretically send those headers to the server, build the schema and cache it, then use introspection to determine what is available.  So you would have a schema per CSV.

**Comment by jquense** [comment]
bit of a tangential addendum. If you are using something like Relay, that wouldn't work, since the schema needs to be known at build time :/

**Comment by Kurren123** [comment]
What if an existing API gave me back response objects of type Dictionary<String, String>. How could I send that as a response? I'm pretty sure I could send it if the dictionary could be serialised into JSON rather than a plain object.

**Comment by Kurren123** [comment]
@joemcbride thanks. How would the response be sent in the resolve method in this situation?

**Comment by joemcbride** [comment]
My suggestion sort of works around the problem.

1. Make a post to a non-graphql endpoint with the csv information.  Create a schema and give it an ID.  Return the ID in the response.
2. Make an introspection post to the graphql endpoint with the ID of the schema you want to use.  Using the information from introspection, build your queries.
3. Make subsequent posts to the graphql endpoint, with the ID of the schema to use, with your "real" query that is statically typed for the specific CSV file.

You could technically use graphql in the initial post to the server using a mutation that generated a new schema.  So if you're just sending the whole file to the server that could work.

As Jason suggested you could also try a custom Scalar type, maybe coupled with a few arguments to the field on the GraphType that you could use for filtering/querying.

**Comment by Kurren123** [comment]
@joemcbride the problem is that the resolve method only accepts a plain object, on which it reflects over the objects properties. Once the scheme is built how do we return the response?

**Comment by Kurren123** [comment]
Hi @jquense and @joemcbride. I think this will all be solved if we allow the resolve method to return a dynamic object. This will allow users to use something like an [`ExpandoObject`](https://msdn.microsoft.com/en-us/library/system.dynamic.expandoobject(v=vs.110).aspx)  and do something like this:

```
dynamic person = new ExpandoObject();
person.FirstName= "Ellen"; //known at compile time

var personDict = person as IDictionary<String, object>;
personDict.Add(myFieldName, "Adams"); //not known at compile time

return person;
```

This way you don't have to know the fields at compile time, and the library will still return an error if you don't return fields specified by the schema. I don't mind making the required changes and submitting PR. I would propose the following:

1. In the [`Resolve`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Resolvers/NameFieldResolver.cs#L11) method of `NameFieldResolver`, before we call `source.GetType().GetProperty(context.FieldAst.Name, _flags);` add an if statement to check if `source` implements `IDynamicMetaObjectProvider`. 
2. If it doesn't, get the property as usual.
3. If it does, try casting it to `IDictionary<String, Object>` (the [easiest way](http://stackoverflow.com/a/2634969/1282944) to get the property) . If it fails, throw an error saying all dynamic objects returned from the resolve method must implement `IDictionary<String, Object>`. If it succeeds, get the property value by using the dictionary.

Something to note is that we can relax the conditions and just have the object implement `IDictionary<String, Object>` rather than having to be dynamic, and we can resort to trying to cast to a dictionary if trying to get the property the usual way fails. I don't mind implementing this approach either.

Afterwards I can add a unit test if need be. Please let me know if I am on the right track.

Thanks again for your help,
Kurren

**Comment by jquense** [comment]
I do think the default name resolver probably should handle the `dynamic` object case. I don't think this actually solves your problem, which is that the _schema_, not the source object, needs to be dynamic. Even if your source object is dynamic you will still need to statically define the type if is resolved to (and it's fields). There is a reason why GraphQL makes this sort of thing really hard and it's because without the static definition you lose a lot of the benefits on the client, such as type checking your queries.

I still think a custom scalar is the simplest way to handle this. We've used that JSON one or indeterminate db fields and it works great. In this case I'd be pretty straight forward to write a scalar that serializes a dynamic object as json directly. then you can put whatever you want in it.

**Comment by Kurren123** [comment]
> Even if your source object is dynamic you will still need to statically define the type if is resolved to (and it's fields)

@jquense thanks for your reply. The schema itself is in fact static, it never changes. It's just not known at compile time, the headers in the CSV file are never changing. I can construct the schema fairly easily using the dynamic schema creation and reading the headers of the CSV upon starting the webservice. I just get stuck on sending the response in the resolve method.

Instead of a CSV it could instead be a sql table whos columns never change or an API of an existing system that returns a `Dictionary<String, Object>` with the same keys every time rather than a plain object. In fact I think there are quite a lot of situations a dynamic object will be needed even with a static schema. 

In the graphQL javascript client we have the benefit of just doing `myObject['myProperty'] = 'value';` but the only real way in .Net is dynamic objects. I made the above change and added a unit test. I can use this for my own use but I'm also happy to do further work and submit a PR if you think the library can benefit from this.

Kind regards,
Kurren

**Comment by joemcbride** [comment]
As we've mentioned, the way to extend the GraphQL "language" and engine in the way you want is to write a custom scalar.  You shouldn't need to alter the source to accomplish this.

Something along these lines:

```csharp
public class DynamicGraphType : ScalarGraphType
{
   public DynamicGraphType()
   {
       Name = "Dynamic";
   }

   public override object Serialize(object value)
   {
     ...
   }

   public override object ParseValue(object value)
   {
     ...
   }

   public override object ParseLiteral(IValue value)
   {
     ...
   }
}


Field<DynamicGraphType>("someField");
```

**Comment by Kurren123** [comment]
Hi @joemcbride thanks for your help. I managed to find a solution without creating a custom scalar type or modifying the source. For anyone else reading that wants to return a dynamic object or `Dictionary<String, Object>` when resolving an `ObjectGraphType`:

First create a wrapper class:

```
public class FieldInfo
{
	public Dictionary<string, object> FieldValues { get; set; }
}
```

Then in your `resolve` method for the object type where you want to return a dictionary:

```
return new FieldInfo {FieldValues = myDictionaryResult};
```

Then in the `resolve` method for each field in the object type, I built each one dynamically so I already knew the field name:

```
var info = ctx.Source as FieldInfo;
return info.FieldValues(fieldName);
```

Thank you both very much for your time. I think we may close this issue now.

**Comment by lwansbrough** [comment]
@Kurren123 How did you build the fields dynamically? Presumably you'd need to know the keys of the dictionary in order to do that, correct? I'm at the point where I've got the field defined as so:

```csharp
            Field(
                typeof(ObjectGraphType),
                "metadata",
                "Metadata related to this object.",
                resolve: ctx =>
                {
                    return ctx.Source.Metadata[ctx.FieldName];
                }
            );
```

but of course because ObjectGraphType doesn't have any fields on it, I can't query like:

 `... metadata { someProperty } ...`

I get an error saying `someProperty` doesn't exist in ObjectGraphType.

**Comment by Kurren123** [comment]
@lwansbrough Yes the fields were contained in a static text file. I added each one to the `ObjectGraphType` and in the resolve method checked if dictionary contained in `ctx.Source` contained a key with the name of the current field being added.

As the others said the API itself needs to be static (not changing often) but in my case I didn't have .net classes defined for each `GraphObjectType`, they were built from other sources like text files and databases.

**Comment by acronoah** [comment]
I am running into the same problem.  I pull data dynamically from an underlying database and have my schema defined externally in a .graphqls file.  I am able to successfully build the fields, but if I try to resolve with a List<dynamic> I get an error at runtime:  

```
GraphQL.ExecutionError: Error trying to resolve id. ---> System.InvalidOperationException: Expected to find property id on JObject but it does not exist.\n   at GraphQL.Resolvers.NameFieldResolver.Resolve(Object source, String name)\n   at GraphQL.Resolvers.NameFieldResolver.Resolve(ResolveFieldContext context)\n   at GraphQL.Instrumentation.MiddlewareResolver.Resolve(ResolveFieldContext context)\n
```

Is there any plan to natively support dynamics as @Kurren123 mentioned earlier?  I'm at the point where I am contemplating forking the repo to deal with the problem as he described.   Any other best places to start from or alternate solutions to returning a dynamic?

**Comment by joemcbride** [comment]
@acronoah You just need to add a `IFieldResolver` that knows how to work with dynamics/JObjects.  No need to fork the repo.  The default resolver just uses reflection over properties.  You just have to teach the library to how to find the field.

```csharp
public class MyRootType : ObjectGraphType<JObject>
{
    public MyRootType()
    {
        Field(
            typeof(IdGraphType),
            "id",
            resolve: ctx =>
            {
                // ctx.Source is JObject as defined by ObjectGraphType<JObject>
                return ctx.Source[ctx.FieldName];
            }
        );
    }
}
```

The `Field` method is just a helper around `AddField`, which sets the `Resolver` property on the `FieldType`.  You can create your own `IFieldResolver` to resolve values however you want.

https://github.com/graphql-dotnet/graphql-dotnet/blob/6385f2b9a7ecf9a1f4c89bfc14e29fa06652c565/src/GraphQL/Types/ComplexGraphType.cs#L59-L78
