### ISSUE TITLE
Upgraded v2 to v4 - Auto Expanding GraphType no longer working

### ISSUE THREAD

**Issue by shadowfoxish** [graphql-dotnet/graphql-dotnet#2786]
I have an ASP.NET Core 3 API which is hosting a GraphQL endpoint used by various parts of my website. I've recently been doing upgrades to latest-and-greatest. I've worked through all the migration related issues with GraphQL (including Newtonsoft to the built-in json serializer) and it's working for just about everything, which is a relief. However, I discovered on two endpoints some issues regarding a Dictionary<string,object> result that doesn't work anymore. 

Here is a subsection of code, as it was working in v2:
```C#
    public class SearchResult
    {
        /* This gets created and returned by the search system's data layer */
        public string Search { get; set; }
        public int ResultSize { get; set; }
        public Dictionary<string, object> ElasticResult { get; set; }
    }

    public class DemoGraphType : ObjectGraphType<SearchResult>
    {
        public DemoGraphType()
        {
            Name = "Demo";

            Field(e => e.Search, type: typeof(StringGraphType));
            Field(e => e.ResultSize, type: typeof(IntGraphType));
            Field(e => e.ElasticResult, type: typeof(StringGraphType));
        }
    }
```

This is the gql query which would be issued by Apollo/React: (Note how "elasticResult" is only specifying a single field representing 'the dictionary')
```graphql
query: query Search($search: SearchRequestInput) {
  itemSearch(searchParams: $search) {
    search
    resultSize
    elasticResult
    __typename
  }
}
```

And the server would happily respond with this:
```json
{
	"data": {
		"itemSearch": {
			"search": "kq2",
			"resultSize": 24,
			"result": [
				{
					"invMastUid": 1851922,
					"itemCode": "SMC KQ2H07-34AS",
					"itemDescription": "SMC KQ2H07-34AS One-Touch Fitting",
					"mfgPartNumber": "KQ2H07-34AS",
					"availabilityMetric": 7677,
					"popularity": 133,
					"relevancy": 133000,
					[... lots of arbitrary fields and objects...]
					"categoryPaths": [
						"/4390/4282/",
						"/4390/",
						"/4390/4282/5775/"
					],
                                        "Port Size": "1/8\" NPT",
                                        "Sealant": "With Sealant",
					"invMastUidString": "1851922",
					"isRestricted": false,
					"restrictedCustomers": []
				},
				{
					[...23 other results with varying dictionaries removed for brevity...]
				}
			],
			"__typename": "Demo"
		}
	}
}
```

I'm writing this post because this doesn't work with V4 out of the box, as it did with V2, but I couldn't find anything about this in the migration guides. 

My first attempt was to build a GraphType class which sources from the dictionary [it's gross], using the well-known fields, and added those fields to the search query gql, and that sorta worked. However, I realized that I don't know all of the fields the search needs to function. Being explicit actually breaks the functionality, since it isn't known before it's requested. One product might have 10 attributes, another might have 20, another might have 3, and there doesn't necessarily need to be any overlap. Product attributes are powered by the data, not the schema, and the nature of Elastic Search just has these unstructured associative pairs of information and returns all that mess to the client. 

What should I do here? I have legitimately "unbounded" key-value-pair data and I have no idea how to send that out to the client in a way that resembles how it was working previously.

**Comment by sungam3r** [comment]
[Custom scalar](https://graphql-dotnet.github.io/docs/getting-started/custom-scalars) to the rescue!

**Comment by sungam3r** [comment]
@Shane32 Maybe we should provide "built-in" scalar like `Map` that returns structured dictionary data? It would be a good example. It is not necessary to include it in `SchemaTypes` by default, just provide this type so that it can be used if necessary.

**Comment by Shane32** [comment]
@shadowfoxish Do you have a need for dynamically-shaped input data, or only dynamic output data?

**Comment by shadowfoxish** [comment]
Hi guys, thanks for the quick replies. Had to go out and do some last minute holiday stuff.

I'll definitely look at the custom scalar thing!

@Shane32, the input is pretty straightforward and I dont think it changes. I could be wrong, but for this current issue, I'm just looking for the dynamic output data (output from server to client).

**Comment by Shane32** [comment]
Sample of a simple scalar that allows you to return any type of object.  This sample is not designed to be used as an input type.

```cs
public class DynamicObjectGraphType : ScalarGraphType
{
    public override object? ParseValue(object? value) => ThrowValueConversionError(value);
    public override object? Serialize(object? value) => value;
}

//use:
Field(e => e.ElasticResult, type: typeof(DynamicObjectGraphType));

//you may need to register the DynamicObjectGraphType in your DI framework
services.AddSingleton<DynamicObjectGraphType>();
```

**Comment by Shane32** [comment]
If it is a necessity for the graph introspection result to remain the same, you can change the behavior of `StringGraphType` to return the value directly, ignoring the actual data type of the returned data.

Note that to strictly meet the GraphQL specification, a `String` scalar value should only return a string, but a custom scalar may return dynamic data.  This is why in recent versions of GraphQL.NET, the `StringGraphType` scalar will throw an exception if the returned value is not a string.

**Comment by shadowfoxish** [comment]
@Shane32 @sungam3r Thanks so much to both of you for jumping on this. Shane's suggestion worked perfectly and saved me from having to do something hacky.
