### ISSUE TITLE
Move ComplexityAnalyzer bits into ValidationRule

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2791]
From @Shane32 :

> Correct, the default complexity analyzer is registered as a default service. So the standard AddComplexityAnalyzer does not overwrite the registration in case you have already registered another complexity analyzer.

> I considered using Configure<T> to configure options and setting them in the execution. However, this will always create an empty instance and then call the configuration delegates. If the MS Options abstractions were available this perhaps could be solved, but without them, we are faced with either (a) ignoring the current options.ComplexityConfiguration settings and creating a new instance, or (b) ignoring the options abstractions and invoking the delegate directly. So that's what I did:
```
public static IGraphQLBuilder AddComplexityAnalyzer(this IGraphQLBuilder builder, Action<ComplexityConfiguration>? action = null)
    => builder.ConfigureExecution(opts =>
    {
        opts.ComplexityConfiguration ??= new ComplexityConfiguration();
        action?.Invoke(opts.ComplexityConfiguration);
    });
```
> You see above that all the method does is register a delegate when ExecuteAsync runs, and passes the complexity configuration class to the action delegate to be mutated as desired. This preserves any complexity settings the user may have already had when calling ExecuteAsync.

> For v5, I suggest we remove ComplexityConfiguration from ExecutionOptions and instead have the options fed via DI to a new instance of the complexity analyzer, much like ErrorInfoProvider or SystemTextJson, etc.

> We might also, for v5, consider removing all complexity analyzer code entirely -- and instead putting the complexity analyzer into a validation rule. The builder method can remain as it is here, but it will then just be calling AddValidationRule along with Configure to configure the options. This has a benefit of simplifying the document executer, and allowing the complexity analyzer to skip execution if the document is pulled from the document cache.

> It is noteworthy that if a person uses the v4 builder methods to configure the complexity analyzer, then no changes should be required for v5 however we refactor the complexity analyzer. (Hopefully.)

**Comment by Shane32** [comment]
Partially done in #3172

**Comment by Shane32** [comment]
Finished by:
- #3872
