### ISSUE TITLE
Are DocumentExecuter and ComplexityAnalyzer supposed to be thread-safe?

### ISSUE THREAD

**Issue by niklaskallander** [graphql-dotnet/graphql-dotnet#280]
Hi,

I'm wondering whether `DocumentExecuter` and `ComplexityAnalyzer` are supposed to be thread-safe? Or whether they are intended to be used one-off per request?

The `ComplexityAnalyzer` isn't thread-safe right now as it uses the field `_result` (which is replaced per request) to store data during execution/analysis (without any sync locks anywhere). In a multi-threaded environment this will lead to race-conditions (which I've been experiencing in my application).

If they aren't intended to be thread-safe I'll simply alter my code, but if it's a bug I thought I'd report it!

Thanks, great work! (:

**Comment by joemcbride** [comment]
Thanks for the report!  `DocumentExecuter` should be thread safe, so looks like we need to update the `ComplexityAnalyzer` to be so as well.

**Comment by joemcbride** [comment]
This should be fixed in #707 (Thanks @bittercoder!)
