### ISSUE TITLE
Deal with relay types in SchemaTypes.AddTypeIfNotRegistered

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2807]
`GraphQLBuilderBase` registers now all relay types. @Shane32 Please take a look if these types can be removed from `SchemaTypes.AddTypeIfNotRegistered`.

**Comment by Shane32** [comment]
I would like to do this for v8.  This prevented me from getting AoT compilation working properly.

**Comment by Shane32** [comment]
Closed by:
- #3620
