### ISSUE TITLE
Release 4.7

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2813]
Let's merge these PRs first that are marked with the 4.7 milestone:

- [x] #2773 
- [x] #2751 
- [x] #2801

**Comment by sungam3r** [comment]
OK. I'll make a release.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/4.7.0

@Shane32 Edit release if you want. Auto-generate release notes GitHub feature works well.

**Comment by sungam3r** [comment]
Release hangs https://github.com/graphql-dotnet/graphql-dotnet/runs/4641637094?check_suite_focus=true

**Comment by sungam3r** [comment]
The release hanged at the stage of publishing packages, but they published.
