### ISSUE TITLE
InterfaceGraphType and ISchemaNodeVisitor related questions

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/graphql-dotnet#2822]
I played with `ISchemaNodeVisitor` in StarWars example from this [repo ](https://github.com/graphql-dotnet/examples) and found that interface related methods are never called. I expected to get calls for `CharacterInterface` but it never happens. Looking into [source code](https://github.com/graphql-dotnet/graphql-dotnet/blob/9bf36324750ceb8f62a9c09c13bcc0bfc44e85ee/src/GraphQL/SchemaExtensions.cs#L257) it appears that they will be called only on interfaces defined on root objects like `Query` for example. 
So my first question: does it make sense to declare interfaces on Query type (`StarWarsQuery` in this example)?
My second question: how can I visit interfaces declared on output types (like `CharacterInterface` on `HumanType`)?

A little background: I'm trying to implement custom directive that will provide CLR type behind `IdGraphType`. This is required for proper client generation from introspection. Today we are using `dynamic` because ID can be any of `int/long/string`. I want to use `ISchemaNodeVisitor` to retrieve `TReturnType` from fields defined as `Field<IntGraphType, TReturnType>()` and add it automatically to `appliedDirectives`. This works well for arguments, output and input graph types, but doesn't work interfaces.

**Comment by sungam3r** [comment]
>and found that interface related methods are never called.

🤔

**Comment by sungam3r** [comment]
I just put the breakpoint on this code and launched tests. I see that breakpoint was hitted.

**Comment by gao-artur** [comment]
I forget to say that I upgraded the repo to v4.7.0. Can't test it with original 3.1.3 because can't find how to register visitor 🤷‍♀️

**Comment by sungam3r** [comment]
`new MySuperVisitor().Run(mySchema);`

**Comment by gao-artur** [comment]
To make it simple, [here the repro](https://github.com/gao-artur/graphql-dotnet-2822). Try to set breakpoint in [MyVisitor](https://github.com/gao-artur/graphql-dotnet-2822/blob/master/src/StarWars/MyVisitor.cs) in any of `VisitInterface/VisitInterfaceFieldArgumentDefinition/VisitInterfaceFieldDefinition` - they are not hit. But `VisitInputObjectFieldDefinition` does work.

**Comment by sungam3r** [comment]
Oops, it's a bug, not a feature 😉 .

**Comment by gao-artur** [comment]
Nice! Thanks for a quick fix. So until the next release I'm going to call interface visitors from `VisitSchema` as a workaround
```
public override void VisitSchema(ISchema schema)
{
    foreach (var iface in schema.AllTypes.OfType<IInterfaceGraphType>())
    {
        VisitInterface(iface, schema);
        foreach (var field in iface.Fields)
        {
            VisitInterfaceFieldDefinition(field, iface, schema);
            if (field.Arguments?.Count > 0)
            {
                foreach (var argument in field.Arguments)
                {
                    VisitInterfaceFieldArgumentDefinition(argument, field, iface, schema);
                }
            }
        }
    }
}
```

**Comment by sungam3r** [comment]
👍

**Comment by sungam3r** [comment]
Release will come out from day to day.

**Comment by Shane32** [comment]
@sungam3r If we have no plans for other changes to 4.7 - which I don't think we do - I'll release 4.7.1 now.  ok?

**Comment by sungam3r** [comment]
Yes. Rename milestone too.
