### ISSUE TITLE
Enforce maximum depth of parsing query and variables

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2829]
- Requires https://github.com/graphql-dotnet/parser/pull/153
- Add `MaxDepth = 64` to default settings used by `GraphQL.NewtonsoftJson` for `ToInputs` extension method
- No changes needed for the `ToInputs` extension method of `GraphQL.SystemTextJson` deserializer

I suggest v4.8 fix ??  Technically this would be a breaking change, as deep queries ( > 64 depth) cannot be parsed anymore.

In v5, the maximum depth of query parsing should be configurable.

**Comment by sungam3r** [comment]
v4.8 / 4.7.2 / 5.0 - I'm fine either way.

**Comment by Shane32** [comment]
Since it would require the updated parser which already has breaking changes, we will probably target 5.0 for these changes.

**Comment by sungam3r** [comment]
@Shane32 Would you like to continue?

**Comment by Shane32** [comment]
I have a feeling this is already fixed since we bumped Newtonsoft. I’ll check.

**Comment by Shane32** [comment]
## Newtonsoft.Json

https://github.com/JamesNK/Newtonsoft.Json/releases/tag/13.0.1

> Change - JsonReader and JsonSerializer MaxDepth defaults to 64

## System.Text.Json

https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.maxdepth?view=net-6.0

> Gets or sets the maximum depth allowed when serializing or deserializing JSON, with the default value of 0 indicating a maximum depth of 64.

## Parser

https://github.com/graphql-dotnet/parser/pull/153

**Comment by Shane32** [comment]
I'm not sure if we have tests or not.  I'm closing the issue, but if you want to verify/write tests, feel free to reopen.

**Comment by sungam3r** [comment]
OK to close as is.
