### ISSUE TITLE
Resolving GraphTypes using API calls - Is Deserializer always required to access the value returned by API.

### ISSUE THREAD

**Issue by pravinhabbu4u** [graphql-dotnet/graphql-dotnet#283]
@joemcbride I am working on automating code generation for around 50+ APIs to allow data fetching from REST api's. I do have code ready for which we have to generally deserialize response from an API (received as string) to appropriate model before return. This works but I am trying to see if deserializer is always required or not (as I dont have to really do it during node implementation)

```csharp
public class ExampleCustomerModel
{
   public string ID {get; set;}
   public string Name {get; set;}
}

public class ExampleCustomerModelType : ObjectGraphType<ExampleCustomerModel>
{
           Field(x => x.ID , nullable: true).Description("unique id of cust");
	   Field(x => x.Name, nullable: true).Description("name");
}

// Below is a resolver method 
public static class ExampleCustomerResolver
{
public static async Task<ExampleCustomerModel> GetSingle_Resolver(string ID)
		{
			string Resp = await API_Handlers.Get_API_ByID(ID);
			ExampleCustomerModel API_Resp =  
                    Newtonsoft.Json.JsonConvert.DeserializeObject<ExampleCustomerModel >(Resp);
			return API_Resp;
		} 
}
```

My question is in the resolver method where I am basically trying to deserialize API response to specific type as returning as a string causes error in context resolver under Query Field

```csharp
Field<ExampleCustomerModelType>( "GetCustomer",
 arguments: new  QueryArguments(new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "custID"}),

resolve: context => {
		string __id =  context.GetArgument<string>("custID");
		if(String.IsNullOrWhiteSpace(__id)){return null;}
			return API_ContactInternet_Get_Resolvers.GetSingle_Resolver(__id);
		}
);
```

Note: I never had to have any sort of code to handle deserialization during node implementation.

**Comment by joemcbride** [comment]
I would say add error handling/logging around this method and verify that you're getting the JSON that you're expecting.

```csharp
public static async Task<ExampleCustomerModel> GetSingle_Resolver(string ID)
{
  string Resp = await API_Handlers.Get_API_ByID(ID);
  ExampleCustomerModel API_Resp =  
                Newtonsoft.Json.JsonConvert.DeserializeObject<ExampleCustomerModel >(Resp);
  return API_Resp;
}
```

There is an open issue (#279) that talks about exposing errors better.  Are you possibly getting a generic "can't resolve xyz field" error but not seeing the real error?

**Comment by joemcbride** [comment]
I'll also add that there are a few "schema generator" frameworks currently in the works, perhaps one of those would make it easier for you?

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md#schema-generation

**Comment by pravinhabbu4u** [comment]
Thanks. I will review those tomorrow just to verify deserializer is required or not. In my case I am using API metadata which includes such custom components such as linkage/ relationship of a microservice with other related microservices and any field conditions needed to cal related api. I feel this is a very unique case hence existing schema generators may not help. This additional relationship information allows me to create additional nested fields which can be queried by requestor to get data from more than 1 API.

**Comment by pravinhabbu4u** [comment]
yes I was getting generic error whenever API call was failing ( like api down) or whenever deserializer was failing after API call. I have handled API call errors using another mechanism (just generate default response by populating error block available on each APi response with an error and actual error description).

I am kind of aware root cause of deserializer errors. It it happening whenevev I have a field in APi response which is list/ array of string but has link to another microservice. In this case I was modifying auto generated schema to have list/ array as another model including original string field and then additional field withresolver logic to call microservice to resolve it. I will use somewhat different approach in case deserialize is always required and is guarantted to fail whenever i was overriding primitive type list to model. This was actually working well with node version:

Example:
Customer has an array of strung which holds ids of referred customer. In this case I want to  allow callers to access information of each referred customer as
query example{
Customer(id:"1234"){
Data{
Name
ReferredCustomer{
CustomerID
ReferredCustomerDetails{
 Data {Name} Errors{ErrorID Desc}
}
}
Errors{
ErrorID Desc}
}

**Comment by pravinhabbu4u** [comment]
Please ignore my previous message about node implementation as I think I am doing something different to make it work. I will review and edit my message tomorrow.

list<string> referredcustomers

list<customermodel> referredcustomers_Details - resolved using foreacgh string id in referred customers

**Comment by joemcbride** [comment]
Sounds like you got this resolved, going to go ahead and close this issue.
