### ISSUE TITLE
[Proposal] Extend AutoRegisteringInputObjectGraphType<T>

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2837]
### Proposed design and goals:

- Auto register public writable properties of generic type `T`

- Inherits `InputObjectGraphType<T>`

- Class features
  - Supports `[Name(...)]` on the class to set the graph type name
    - Defaults to the name of `T` after removing "Model" from the end of `T` if it exists.
  - Supports `[Description(...)]` and `[Obsolete(...)]` to set the description and deprecation reason
  - Can inherit from this class and add code to the derived class's constructor to add additional fields or modify existing ones.

- Field features
  - Skips properties marked with `[Ignore]`
  - Supports `[Name(...)]` on the property to set the field name
  - Supports `[Description(...)]` and `[Obsolete(...)]` to set the description and deprecation reason
  - Supports `[GraphType(...)]` to manually select an exact graph type (ignoring all type inference)
  - Supports `[DefaultValue(...)]` to set a default value for intrinsic values, and for complex types, `[DefaultValueAst(...)]` to set a complex default value from a string that is parsed as an AST and converted to the graph type's type just like the schema builder would do.
  - Without manually selecting a graph type, will auto generate a graph type using `GetGraphTypeFromType` method
    - Supports nullability attributes to determine nullability of type (and if applicable its list) -- for example:
      - `List<string?>` is `NonNullGraphType<ListGraphType<StringGraphType>>`
      - `List<string>?` is `ListGraphType<NonNullGraphType<StringGraphType>>`
    - For libraries without NRT annotations, or to override type nullability inference, supports `[Required]`, `[Optional]`, `[RequiredList]` and `[OptionalList]` attributes (applied to the property for ease of use)
    - Supports `[Id]` to indicate that a member should be an `IdGraphType`
      - Works with NRT annotations and lists, etc

- Class is completely extendable with overridable members used to build the graph.  Typically this would be meant for derived generic classes, as there should be enough extensibility with attributes to not require code to modify behavior.
  - `GetDefaultName()` to set the default name of the graph.  Derived generic classes may override this member to customize default naming.
  - `GetPropertiesToProcess()` returns the set of properties of `T` that should be added to the graph.  Derived classes may use this method to customize how property scanning is done.
  - `ProcessProperty(PropertyInfo property)` returns a `FieldType` for the property
  - `GetNullabilityInformation(...)` and `GetTypeInformation(...)` to examine the property type and return data that can be used to build a graph type.  Typically these would not be overridden unless a bug was found in the code.
  - `ApplyAttributes` scans for property attributes that control type information, such as `Optional` and `Id`, and can mutate the type information provided by `GetTypeInformation`.  Typically would be overridden to support custom attributes.
  - `InferGraphType` takes the type information from the above and returns a graph type.  Typically this would not need to be overridden.

### Sample with NRT annotations

Class:

```cs
// type AutoRegisteringInputObjectGraphType<ProductAddInputModel>
public class ProductAddInputModel
{
    [Id]
    public int Id { get; set; }
    public string Name { get; set; }
    public string? Description { get; set; }
    public int QuantityAvailable { get; set; }
}
```

Generated runtime schema: (note that the NameConverter changed the names from PascalCase to camelCase)

```gql
input ProductAddInput {
  id: ID!
  name: String!
  description: String
  quantityAvailable: Int!
}
```

### Sample without NRT annotations

```cs
// type AutoRegisteringInputObjectGraphType<ScoreData>
[Name("DataInput")]
public class ScoreData
{
    [Id]
    public Guid? UserId { get; set; }

    [Required, OptionalList]
    public List<ScoreInfo> Scores { get; set; }

    [Name("BestScore")]
    public double HighScore { get; set; }

    [Ignore]
    public int SomeIgnoredData { get; set; }

    // private member
    private int SomePrivateData { get; set; }

    [GraphType(typeof(NonNullGraphType<OtherGraphType>))]
    public OtherData SomeOtherData { get; set; }
}

// type AutoRegisteringInputObjectGraphType<ScoreInfo>
public class ScoreInfo
{
    [Description("Score of the game")]
    public double Score { get; set; }

    [Name("Date")]
    [Description("Date the game was scored")]
    public DateTimeOffset ScoredAt { get; set; }

    // non-writable property
    public double ScoreDoubled => Score * 2;

    // method
    public double GetScore() => Score;

    // field
    public string Notes;
}
```

Generated runtime schema (assuming type mappings were registered properly):

```gql
input DataInput {
  userId: ID
  scores: [ScoreInfo!]
  bestScore: Float!
  someOtherData: Other!
}

input ScoreInfo {
  "Score of the game"
  score: Float!
  "Date the game was scored"
  date: DateTimeOffset!
}
```

**Comment by sungam3r** [comment]
👍 `AutoRegisteringInputObjectGraphType<T>` already exists.

**Comment by Shane32** [comment]
Whoops!

What do you think of the suggested design?

**Comment by sungam3r** [comment]
I'm fine. Just not in one single PR.

**Comment by Shane32** [comment]
Will be added in multiple PRs:
1. [ ] #2840 
2. [ ] Add attributes
3. [ ] Add `TypeInformation` struct and `GetTypeInformation` internal method
4. [ ] Add `ApplyAttributes` and `InferGraphType` internal methods
5. [ ] Add `CreateField` internal method
6. [ ] Add `ConfigureGraph` internal method
7. [ ] Update `AutoRegisteringInputObjectGraphType` to use above methods

**Comment by Shane32** [comment]
@sungam3r You requested multiple PRs to encompass the functionality.  Unfortunately it seems impractical to write the code for this in a segmented fashion.  I will create multiple PRs as requested, but they all use the prior PR as a target branch.  We cannot merge the 4th PR before the first 3 PRs are merged.  (Or else the 3rd PR will contain the changes from the 3rd and 4th PRs).

**Comment by sungam3r** [comment]
I can review quickly if it helps.
