### ISSUE TITLE
Need Help - GraphQL Middleware- Deserialization of GraphQL Request fails while using Parameters

### ISSUE THREAD

**Issue by pravinhabbu4u** [graphql-dotnet/graphql-dotnet#284]
In GraphQL Middleware I have:

       private async Task<ExecutionResult> ExecuteAsync(HttpRequest request)
        {
            string requestBodyText;
            using (var streamReader = new StreamReader(request.Body))
            {
                requestBodyText = await streamReader.ReadToEndAsync().ConfigureAwait(true);
            }
            var graphqlRequest = JsonConvert.DeserializeObject<GraphQLRequest>(requestBodyText );

JsonConvert.DeserializeObject fails whenever I try to pass query variables from graphiql. I understand this has something to do with variables but not able to figure out the issue. Can someone help?

Example Request:

```json
{"query":"query techInfo($paramAlias: String!) {Identities(fAlias: $paramAlias) {Data {firstName}}}\\n\\n\\n\\n","variables":{"paramAlias":"pravin"},"operationName":"techInfo"}
```

Message = "Unexpected character encountered while parsing value: {. Path 'variables', line 1, position 122." This position is somewhere after variables":  - either { or ".

I might have used old implementation of GraphQL Middleware method and that might be the culprit. Any help is greatly appreciated.

**Comment by pravinhabbu4u** [comment]
I tried changing Variables type from string to public Dictionary<string, string> Variables { get; set; }. It has fixed deserializer issue. Now I am trying to figure out how I am going to pass it to DocumentExecuter().ExecuteAsync

return await new DocumentExecuter().ExecuteAsync(schema, null, graphqlRequest.Query, graphqlRequest.OperationName, null??????? ).ConfigureAwait(true);

**Comment by joemcbride** [comment]
Using `ExecuteAsync` with a bunch of overloads is the "legacy" way of calling that method.  I would suggest to use the newer configuration options as that overload will be removed sometime in the future.  Something like this:

```csharp
var result = await new DocumentExecuter().ExecuteAsync( _ =>
          {
            _.Schema = schema;
            _.Query = graphqlRequest.Query;
            _.Inputs = new Inputs(graphqlRequest.Variables);
          }).ConfigureAwait(false);
```

**Comment by pravinhabbu4u** [comment]
@joemcbride Thanks for the quick response. I just tried your suggestion. It is working as well after modifying variables type as:

        public Dictionary<string, object> Variables { get; set; }
from 
        public Dictionary<string, string> Variables { get; set; }

**Comment by pravinhabbu4u** [comment]
@joemcbride  Moved back Variables type to string from Dictionary as it was causing problem with schema not loading with exception (Dicitionary cant be null ).

Now using:
          return await new DocumentExecuter().ExecuteAsync(_ =>
            {
                _.Schema = schema;
                _.Query = graphqlRequest.Query;
                _.Inputs = new Inputs(graphqlRequest.Variables.ToInputs());
            }).ConfigureAwait(false);

**Comment by joemcbride** [comment]
`Inputs` inherits from `Dictionary<string, object>` and takes a `Dictionary<string, object>` in its constructor, which is why that code is working.  You can simplify to just using the extension method alone.

```csharp
_.Inputs = graphqlRequest.Variables.ToInputs();
```

**Comment by pravinhabbu4u** [comment]
@jaymitchell  I am back to square 1 - Do you need to make any change on request deserialization as changing Variables types back to string brings back the deserializer issue.

   var graphqlRequest = JsonConvert.DeserializeObject<GraphQLRequest>(requestBodyText);

**Comment by joemcbride** [comment]
I don't know, since this isn't an issue with this project.  The sample graphiql project works fine with just using a `string` as the `Variables` property.  Others have also said they had issue with that approach, so I can only guess it depends on how you have your project setup.

What this project _does_ require is that the JSON.NET types get converted to "real" .NET types instead of the `JArray` / `JObject` etc. to populate the `Inputs` class.

**Comment by pravinhabbu4u** [comment]
@joemcbride Makes sense. For now I have fixed the issue by making some changes in my graphiql interface/ middleware implementation in .net core. 

I will review the Middleware implementation once I complete some automation work on mutations.
```
`    internal sealed class GraphQLRequest
    {
        public string OperationName { get; set; }

        public string Query { get; set; }

        public Dictionary<string, object> Variables { get; set; }
    }`
```
```
                Inputs inputs = null;
                if (graphqlRequest.Variables != null)
                {
                    inputs = new Inputs();
                    foreach (var arg in graphqlRequest.Variables)
                    {
                        inputs.Add(arg.Key, arg.Value);
                    }
                }
                //var inputs = graphqlRequest.Variables.ToInputs();
                return await new DocumentExecuter().ExecuteAsync(_ =>
                {
                    _.Schema = schema;
                    _.Query = graphqlRequest.Query;
                    _.Inputs = inputs;
                }).ConfigureAwait(false);
```

My team is quite desperate in having PascalCases back on field names. I will wait for completion of remaining work on your end to support pascal cases.

**Comment by joemcbride** [comment]
Since `Inputs` takes a Dictionary in its constructor you don't need to loop over all of the key/values yourself.

```
inputs = new Inputs(graphqlRequest.Variables);
```
