### ISSUE TITLE
Using DataLoader with MicrosoftDI

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [graphql-dotnet/graphql-dotnet#2850]
## Summary

DataLoader code fails to compile when using scoped resolvers

## Relevant information

Before, compiles fine, but needs to be scoped:

```csharp
Field<UserType, User>()
     .Name("User")
     .ResolveAsync(context =>
     {
         var db = context.RequestServices.GetRequiredService<MyDbContext>()
         var loader = accessor.Context.GetOrAddBatchLoader<int, User>("GetUsersById", db.GetUsersByIdAsync);
         return loader.LoadAsync(context.Source.UserId);
     });
```

After:

```csharp
Field<UserType, User>()
     .Name("User")
     .ResolveScopedAsync(context =>
     {
         var db = context.RequestServices.GetRequiredService<MyDbContext>()
         var loader = accessor.Context.GetOrAddBatchLoader<int, User>("GetUsersById", db.GetUsersByIdAsync);
         return loader.LoadAsync(context.Source.UserId);
     });
```

Gives an error on the return like:

```
Cannot implicitly convert type 'GraphQL.DataLoader.IDataLoaderResult<User>' to 'System.Threading.Tasks.Task<User>'. An explicit conversion exists (are you missing a cast?)
```

I'm not sure how to resolve this!

### Environment (if relevant)

Version 4.7.1

**Comment by Shane32** [comment]
`.Returns<IDataLoaderResult<User>>.ResolveScoped(…`

but it probably won’t work because the scope will be discarded at the end of this method, before the data loader executes

**Comment by sungam3r** [comment]
Context.RequestServices intended to be scoped already.

**Comment by Shane32** [comment]
Not if you want to use a parallel execution strategy. Of course with a serial execution strategy you shouldn’t need to create a scope at all.

**Comment by jeffw-wherethebitsroam** [comment]
Yes, we run in parallel with an EF core context. So without scopes, we run into the error:

> A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe.

So I was wondering how best to handle this situation when using DataLoader

**Comment by Shane32** [comment]
There is no easier way provided than you’ve already been doing. 

I would create new extension methods for IDataLoaderContext that simplifies creating a scope and pulling the database from it or whatever you need. 

In my code I simplify that kind of stuff down to one line of code, where I can. So to have a data loader pull a list of orders for a customer I might just write:

```cs
this.AddDataLoadedCollectionField(“orders”, source => source.Id, db => db.Orders.Where(x => !x.Deleted), orders => orders.CustomerId);
```

So it works throughout my codebase - but that is specific to my needs.

**Comment by sungam3r** [comment]
@Shane32 close?

**Comment by Shane32** [comment]
Please ask if there are any further questions.
