### ISSUE TITLE
ExecuteAsync always expects Query even if Document is provided

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#2851]
Hi,
My question is why ExecuteAsync method options must include Query even if the Document is provided.
What happens if they don't match?

Thanks.

**Comment by sungam3r** [comment]
Document will be used if present.

> What happens if they don't match?

Nothing. `Options.Query` is ignored.

> My question is why

I think this is just an oversight.

@Shane32 
```c#
 if (options.Query == null)
                throw new InvalidOperationException("Cannot execute request if no query is specified");
```
->
```c#
 if (options.Query == null  && options.Document == null)
                throw new InvalidOperationException("Cannot execute request if no query is specified");
```

?

**Comment by sungam3r** [comment]
Or should we always require query and compare it with `options.Document.Query` if document was specified?

**Comment by rmeshksar** [comment]
Query is used as the key for DocumentCache and therefore always should exist. No sure what would be the best way to make sure these two values are compatible.

**Comment by Shane32** [comment]
I would only make this change @sungam3r suggested:

```cs
 if (options.Query == null && options.Document == null)
    throw new InvalidOperationException("Cannot execute request if no query is specified");
```

If the document is passed to the `DocumentExecuter`, or if it is successfully retrieved from the cache, it is not saved to the cache once the query successfully executes, so the key is not needed in addition to the `Document`.  Also, the `Document` already holds an instance of `OriginalQuery` which is used for error messages.

> Or should we always require query and compare it with `options.Document.OriginalQuery` if document was specified?

I wouldn't.

Side note: `OriginalQuery` is specified as `string?` but is considered required by much of the error message code.  We should consider if (a) it should be `string`, or (b) the error message code does not need the query, and so change all of the `string` types to `string?` there.

**Comment by sungam3r** [comment]
🤔 If you look at the question from the performance point of view, then it is not very good to have a `string` object. Remember all changes in parser, it works with `ROM` "chunks" and does everything that it can to not allocate strings. It would be possible to change some properties from `string` to `ROM` in this project and server to allow buffers utilization.

**Comment by Shane32** [comment]
I doubt it will help.  The ROM will originate from a string, and only helps if using other ROMs to point to the same portion of memory.  If we still deserialize all the data to strings, then whether the original query is a ROM or a string won't make any difference.

Remember we already tried a whole ton of code to extensively use ROMs?  https://github.com/graphql-dotnet/graphql-dotnet/pull/2199  We couldn't make it perform any better at all.

**Comment by sungam3r** [comment]
>  The ROM will originate from a string

or from memory pool of chars

**Comment by Shane32** [comment]
With the JSON transports in use today, there is no practical way to benefit from that feature. Also, the “memory pool of chars” still isn’t a UTF-8 byte sequence, which could potentially save memory and processing time.

**Comment by sungam3r** [comment]
At least I still have hope that we will come up with something for perf.
