### ISSUE TITLE
Utilize VARIABLE_DEFINITION

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2854]

**Comment by sungam3r** [comment]
I fix one or two places. While I did not really deal with this issue.

**Comment by Shane32** [comment]
@sungam3r Please add a description to the issue above or close the issue.

**Comment by sungam3r** [comment]
I forgot. It was something about using `GraphQLVariableDefinition.Directives`. I do not think that this issue is important for now. If it affects someone, then we will make a fix.
