### ISSUE TITLE
Obsolete in services.AddGraphQL

### ISSUE THREAD

**Issue by apis3445** [graphql-dotnet/graphql-dotnet#2856]
## Summary

Hello! I am using version 4.7.1 in .net & and now Visual studio shows a warning that services.AddGraphQL is obsolete, but I couldn't find any documentation about the new method. I added the GraphQL.MicrosoftDI but I don't know how to use

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Harness/Startup.cs:

```c#
using GraphQL.MicrosoftDI;

 public void ConfigureServices(IServiceCollection services)
        {
            // add execution components
            services.AddGraphQL(builder => builder
                .AddSystemTextJson()
                .AddErrorInfoProvider((opts, serviceProvider) =>
                {
                    var settings = serviceProvider.GetRequiredService<IOptions<GraphQLSettings>>();
                    opts.ExposeExceptionStackTrace = settings.Value.ExposeExceptions;
                })
                .AddSchema<StarWarsSchema>()
                .AddGraphTypes(typeof(StarWarsQuery).Assembly)
                .AddMiddleware<CountFieldMiddleware>(false) // do not auto-install middleware
                .AddMiddleware<InstrumentFieldsMiddleware>(false) // do not auto-install middleware
                .ConfigureSchema((schema, serviceProvider) =>
                {
                    // install middleware only when the custom EnableMetrics option is set
                    var settings = serviceProvider.GetRequiredService<IOptions<GraphQLSettings>>();
                    if (settings.Value.EnableMetrics)
                    {
                        var middlewares = serviceProvider.GetRequiredService<IEnumerable<IFieldMiddleware>>();
                        foreach (var middleware in middlewares)
                            schema.FieldMiddleware.Use(middleware);
                    }
                }));
```

**Comment by fubar-coder** [comment]
The source you've shown is from the `develop` branch, but the 4.7.1 release doesn't contain an `AddGraphQL` extension method that takes an `Action<IGraphQLBuilder>`.

**Comment by sungam3r** [comment]
@fubar-coder 
                                                                                                 
> https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Harness/Startup.cs

                                                          ^^^^^^^

**Comment by Shane32** [comment]
@apis3445 There are now two different ‘IGraphQLBuilder` interfaces. The obsolete one from the server project and the new one in the main project. The old one will be supported for the remainder of the 4.x lifetime but it is being replaced by the new one. There is also two extension methods called `AddGraphQL` - the new one in GraphQL.MicrosoftDI and the old one in the server project. The new one uses the new interface of course. 

Please note that there are subtle differences in functionality; it is advised to read the documentation for the new builder methods and be sure they fit your needs. 

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#dependency-injection-registration-helpers

**Comment by Shane32** [comment]
> We don't have a way to use comfortably use the new API in `GraphQL.MicrosoftDI`, because (at least in ASP.NET Core 6.0), the global namespaces will always include `Microsoft.Extensions.DependencyInjection`.

Known issue - you will need to reference the extension method explicitly as a simple static method rather than using it as an extension method. After the old extension methods are removed in the next major version, this will not be an issue. 

We thought it best to mark the old methods as obsolete so everyone had time to transition to the new methods.

**Comment by fubar-coder** [comment]
The one in the `master` branch looks like this:

```csharp
            services.AddGraphQL()
                .AddSystemTextJson()
```
while the one you quoted, which comes from the `develop` branch and isn't released yet, looks like this:

```csharp
            services.AddGraphQL(builder => builder
                .AddSystemTextJson()
```

But this doesn't solve the problem that there isn't an easy way to use the new extension method, except by explicitly calling it, e.g.:

```csharp
            GraphQL.MicrosoftDI.GraphQLBuilderExtensions.AddGraphQL(services)
                .AddSystemTextJson()
```

**Comment by apis3445** [comment]
Sorry I can't get the project working. 
If I added the codemGraphQL.MicrosoftDI.GraphQLBuilderExtensions.AddGraphQL(services)  I got the error

: Error CS0234: The type or namespace name 'MicrosoftDI' does not exist in the namespace 'CaducaRest.GraphQL' (are you missing an assembly reference?) (CS0234) (CaducaRest)

If I added the code in the link 
`services.AddSingleton<ISchema, CaducidadSchema>(services => new CaducidadSchema(new SelfActivatingServiceProvider(services))); `

I got error 
Unable to resolve service for type 'GraphQL.Server.Transports.AspNetCore.IGraphQLRequestDeserializer' while attempting to activate 'GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1[GraphQL.Types.ISchema]'.

My repo is https://github.com/apis3445/CaducaRest

**Comment by sungam3r** [comment]
@apis3445 I cloned your repo and it compiles. I see that you commented GraphQL.NET code and use HotChocolate. If this issue is no actual anymore for you then please close.

**Comment by apis3445** [comment]
Because I didn't have any response I change and comment the code

**Comment by sungam3r** [comment]
I don't know what to comment/uncomment exactly. Please provide ready-to-go example.

**Comment by apis3445** [comment]
You can use this version https://github.com/apis3445/CaducaRest/tree/c61f04f26f9ff95f13f55cafca01499fd0631ff9/CaducaRest and update code to don't mark obsolete

**Comment by sungam3r** [comment]
```csharp

            services.AddSingleton<ISchema,CaducidadSchema>();
            services.AddSingleton<CaducidadInputType>();
            services.AddSingleton<CaducidadMutation>();

            // problem code here
            var builder = GraphQLBuilderExtensions
                .AddGraphQL(services)
                .AddServer(true, (options, provider) =>
                {
                    options.EnableMetrics = CurrentEnvironment.IsDevelopment();
                    var logger = provider.GetRequiredService<ILogger<Startup>>();
                    options.UnhandledExceptionDelegate = ctx => logger.LogError("{Error} occured", ctx.OriginalException.Message);
                });
            global::GraphQL.GraphQLBuilderExtensions.AddErrorInfoProvider(builder, opt => opt.ExposeExceptionStackTrace = CurrentEnvironment.IsDevelopment());
            global::GraphQL.SystemTextJson.GraphQLBuilderExtensions.AddSystemTextJson(builder); // For .NET Core 3+
            global::GraphQL.DataLoader.GraphQLBuilderExtensions.AddDataLoader(builder); // Add required services for DataLoader support
            global::GraphQL.GraphQLBuilderExtensions.AddGraphTypes(builder, typeof(CaducidadSchema).Assembly); // Add all IGraphType implementors in assembly which ChatSchema exists
            // end

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddTransient<IAuthorizationHandler, PermisoEditHandler>();
```

@Shane32  It was not worth marking methods as obsolete. Very few people will understand what to change to get rid of warning.
@apis3445 We already removed all that "old stuff" and consolidated extension methods to work well but these changes is from `develop` branch. We plan to release in April.

**Comment by sungam3r** [comment]
@apis3445 Now only two developers support GraphQL.NET  - @Shane32  and I. I prefer to get rid of the old code immediately, even if the price of backward incompatibility. @Shane32 is more careful and prefers to mark old code as `Obsolete` to give clients time to upgrade. It so happened that in this case the final result is far from the ideal. Sorry.

**Comment by Shane32** [comment]
@sungam3r It is easy to release another version of the server project without the obsolete methods, that is compatible with GraphQL.NET 4.x.  It is not the main project that caused the methods to be obsolete.  And supporting two different builders within the server project certainly is confusing.  I actually didn't even merge in those changes until your review in late December, precisely because of the confusion it would cause having two sets of builder methods in one repo.

**Comment by sungam3r** [comment]
I would not release v6. Only two months left to the planned release in April. Only extra work.

**Comment by sungam3r** [comment]
@apis3445 Do you have any questions left?

**Comment by apis3445** [comment]
No I only prefer if you add something to obsolete add a sample about how to remove in the same version

**Comment by Navusas** [comment]
I thought it's just me who is struggling for 2 days now trying to get it setup on a completely new project...

Was hoping setting up GraphQL on a new project is going to be < 20 minute job, but it turned out to be mission impossible.

**Comment by Navusas** [comment]
Thanks for all the resources @Shane32 👍 
Your example worked in a matter of minutes, but I needed a bit more complex solution (i.e. EF core database, services injection, etc).

I went through quite a few of them and wasn't able to get the project going to be honest. Most of them uses the v4 graphql-dotnet, which seems to somewhat work differently from v5. 

I went through the public docs many times, but must admit that I would just skim through them in a few seconds, don't find anything, and then come back to the tutorials you have listed above. (It's just in my nature, I guess, that I don't read every single line/sentence in the docs, I am more of "oh, this looks cool, let's try it". 

But anyways, after about 3-4 days of going through tutorials and trying to set it the basic app, I have finally decided to sit down, spend a few hours on docs and read most of the stuff in it, leaving some notes while I do that. Must admit that after I did it was much easier to create the project from scratch (I guess I took an hour to make the project below). I found that some of the most useful information for me personally was hidden usually either in the middle or right at the end.

So, note to myself. Read more docs! 📝 


For anyone else as lost as I was, here is the most basic solution (not perfect) of getting GraphQL-dotnet v5 working with .NET 6 (using EF Core code-first approach).
https://github.com/Navusas/graphql5-dotnet6

**Comment by SpicyCatGames** [comment]
In graphql version 7.8.0, @Shane32 's answer gives error "The type 'IGraphQLBuilder' is defined in an assembly that is not referenced. You must add a reference to assembly 'GraphQL, Version=4.6.1.0" with the AddGraphQL() also marked as obsolete. So We are forced not to use new version? I cannot find what the correct way to do it is in new version.

**Comment by Shane32** [comment]
@SpicyCatGames  Please provide a list of your GraphQL nuget packages you are referencing along with their version numbers.

**Comment by Shane32** [comment]
Without knowing what NuGet packages you have installed, it's hard to say, but generally I expect that you still have a reference to an old GraphQL.NET Server package.  So long as you have v7 GraphQL.NET Server packages installed, you should be able to use v7 GraphQL.NET packages.  Please note that some old packages are not necessary and should be removed for proper operation.  Please see the readme file at https://github.com/graphql-dotnet/server for a list of packages which should be removed when upgrading to v7.
