### ISSUE TITLE
within_schema_language_well_placed_directives test is wrong

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2864]
It passes on `develop/master` and fails in #2863 . Obviously it should fail. See `onObject`, `onInterface`, `onEnum`, etc, directive usages. 

`ValidationSchema` defines only `onQuery`, `onMutation`, `directiveA`, `directiveB`, `directive`, `rep` directives. So why does it work on master? Because of incorrect AST traversal.  `GraphQL.Language.AST` namespace has no AST node for type definitions, only for execution definition. So this test checks what has never been implemented 😮 . In #2863 all directive usages are properly detected so test fails. And in fact, the error should occur even earlier, because spec allows to execute only executable definitions. GraphQL server should return error if it detect type definition in incoming request - #2844.

**Comment by Nexuscompute** [comment]
https://fedlex.data.admin.ch/eli/cc/1993/1945_1945_1945[]()

**Comment by Shane32** [comment]
@sungam3r  We removed `GraphQL.Language.AST` in #2863.  According to the issue description above, the test should fail, and does after #2863.  So is this PR still valid?  I'm a bit confused.  It seems that this issue has been solved and should be closed.

**Comment by sungam3r** [comment]
Yep. It looks like I found this one while working on #2863, then I changed `ShouldPassRule` to `ShouldFailRule`
![изображение](https://user-images.githubusercontent.com/21261007/234322807-d38243e6-163a-4a2b-ba32-747b38d01d76.png)
and forgot about that issue. One thing I did - renamed `within_schema_language_well_placed_directives` to `within_schema_language_unknown_directives` in 400f292ce0b6c0f66d85c7b85093258b77b2357e .
