### ISSUE TITLE
Rewrite SchemaPrinter

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2868]
Convert `Schema` into `GraphQLDocument` and then use `SDLWriter`.

**Comment by sungam3r** [comment]
Note: why `SchemaPrinter` sorts types and directives first?
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L90
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L95

And after `SchemaPrinter` applies comparers:
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L102
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L103

😕 

Looks like a bug because output is sorted by names even if `Options.Comparer` is `null`.

**Comment by sungam3r** [comment]
Note 2: `SchemaPrinter` adds whitespace after `#` in each comment. See `prints_enum` test for example. Looks like a bug too.

**Comment by Shane32** [comment]
I think there should be some logic to the default behavior.  Perhaps just types and directives.  Perhaps all "sortable" members.  I feel that 'no sorting' would be a bad choice.  Perhaps setting the comparer to null allows for "no sorting", but I feel that it should sort by default.

**Comment by Shane32** [comment]
SchemaPrinter won't print comments anymore, correct?  Since a `Schema` can't contain comments, and descriptions will be printed as descriptions, not comments.

**Comment by sungam3r** [comment]
> SchemaPrinter won't print comments anymore, correct? Since a Schema can't contain comments, and descriptions will be printed as descriptions, not comments.

Yes.

**Comment by Shane32** [comment]
See also:
- #2887

**Comment by sungam3r** [comment]
It looks like now I should finish this one for v8 🤔

**Comment by Shane32** [comment]
> Convert `Schema` into `GraphQLDocument` and then use `SDLWriter`.

Completed in #3649
