### ISSUE TITLE
Dynamic subscription handler

### ISSUE THREAD

**Issue by azaslonov** [graphql-dotnet/graphql-dotnet#2869]
Hi everyone,

Is it possible to define a universal subscription handler that would process every subscription and every field? I'm looking for something like this:
```
    public class DynamicSubscription : ObjectGraphType
    {
        public DynamicSubscription()
        {
            AddField("*", ...);
        }
        ...
    }

   var executor = new SubscriptionDocumentExecuter();
   schema.Subscription = new DynamicSubscription();
```

The structure of the schema and incoming queries are not known in advance.

Any help greatly appreciated.

**Comment by Shane32** [comment]
With a truly dynamic schema, there’s no way to fully parse the query into execution nodes or even to validate it. I would suggest using the parser project to parse the query into an AST and write your own execution code, as there isn’t much useful that GraphQL.NET can do without a schema. You can of course use the classes and execution result class and serializers and so on which will greatly facilitate such an endeavor.

**Comment by azaslonov** [comment]
@Shane32, thanks for quick response. Sorry for confusion: we don't know the schema in advance (when we build the code), but we do know schema at the moment of request (from our DB), and we do run some validations of the request against the schema. What I meant is that we can't code anything like that AddField method, because in build-time we don't know what fields will be there.

**Comment by Shane32** [comment]
Is it known prior to the time of request, for example after the database boots up with daily refresh, or only at the moment of the request?

**Comment by azaslonov** [comment]
Yeah, our users can update the schema in DB (prior to making the request). This is when we re-parse it and keep in memory for quicker request processing.

**Comment by Shane32** [comment]
Why can't you build the schema from the database then (and cache it)?  I have plenty of code that builds dynamic schemas... shouldn't be too hard.  You can certainly use the same field resolver for each field if you like.

**Comment by azaslonov** [comment]
Yep, that's the problem, I don't know how to make that AddField operation dynamic, it requires specific field name to attach to, like in this example:
```
    AddField(new EventStreamFieldType
    {
      Name = "messageAdded",
      Type = typeof(MessageType),
      Resolver = new FuncFieldResolver<Message>(ResolveMessage),
      Subscriber = new EventStreamResolver<Message>(Subscribe)
    });
```
How can I attach the same (universal) resolver to all of the types/fields?

**Comment by Shane32** [comment]
Just run AddField for each field.

**Comment by azaslonov** [comment]
I was afraid you say that :). Are there any other options by chance?

**Comment by Shane32** [comment]
Pseudocode:

1. If user's db schema has changed
  a. Rebuild GraphQL `Schema` from db schema
  b. Cache schema
2. Pull GraphQL schema from cache
3. Execute query

**Comment by Shane32** [comment]
Again, if you do not initialize the GraphQL `Schema` class with each field and type, `GraphQL` cannot validate the query or know how to execute any nodes.  There's just nothing for GraphQL.NET to do.  You can parse the query via the parser project, and then write your own code to examine the nodes and so on.

**Comment by azaslonov** [comment]
Yeah, got it. Thanks a lot for your answers, really appreciate your help.
