### ISSUE TITLE
We don't dispose GraphQLDocument

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2878]
`GraphQLDocument.Dispose` releases internal memory buffers 😕 , I can not confidently say where it should be done.

**Comment by Shane32** [comment]
I think a better solution would be to remove `GraphQLDocument.Dispose`.  We should not be using rented memory for comments.  Moreover, comments are not ever parsed by GraphQL.NET for execution.

**Comment by sungam3r** [comment]
It seems I just realized that we are parsing comments completely wrong.

**Comment by Shane32** [comment]
According to spec, comments should be completely ignored and treated as whitespace.

**Comment by sungam3r** [comment]
> It seems I just realized that we are parsing comments completely wrong.

No, from a lexical point of view, the parcing is correct, just the parser glues all the tokens of comments in one logical commentary AST. This is the only place that creates a node that difffers from how it is described in spec's grammar. Another way is change property in `ASTNode` from
```
public virtual GraphQLComment? Comment { get => default; set { } }
```
to
```
public virtual List<GraphQLComment>? Comments { get => default; set { } }
```

Then the comments parcing will be simplified and there will be no need to glue them. As a consequence, we can delete all the code with memory pools and remove `IDisposable` from `GraphQLDocument`! I'll do it, it will give the winning both in design and in performance.

> According to spec, comments should be completely ignored and treated as whitespace.

Well.... yes but there is a big problem with practical view point. While the specification is not allowed to place descriptions on absolutely all syntactic elements, we cannot stop processing comments. I remember that I saw the discussion of this. I am 100% sure that my projects will stop working if we remove comments support.

**Comment by Shane32** [comment]
> Well.... yes but there is a big problem with practical view point. While the specification is not allowed to place descriptions on absolutely all syntactic elements, we cannot stop processing comments. I remember that I saw the discussion of this. I am 100% sure that my projects will stop working if we remove comments support.

I understand -- just saying, we need not put excessive support on this feature.  In this case, I think that using memory pools is excessive.

> public virtual List<GraphQLComment>? Comments { get => default; set { } }

Sounds good to me.  It won't affect anyone not parsing comments.  And it will make parsing simpler.

**Comment by sungam3r** [comment]
Done in https://github.com/graphql-dotnet/parser/pull/210

**Comment by sungam3r** [comment]
Closing)
