### ISSUE TITLE
Using a schema from another server

### ISSUE THREAD

**Issue by ManuelDeLeon** [graphql-dotnet/graphql-dotnet#288]
Sorry for the question...

We're thinking of using DocumentValidator to check/validate queries against a schema in another server. The idea is to query the 3rd party server for their schema, populate an ISchema object, and then use it to validate queries using DocumentValidator.

Do you already have something to load/convert a __schema response into an ISchema which can be used to validate queries?
Do you know of another way to validate a query against the schema of another graphql server? (like what Graphi does, but in C#)

Thanks

**Comment by joemcbride** [comment]
>Do you already have something to load/convert a __schema response into an ISchema which can be used to validate queries?

Not currently, no.

>Do you know of another way to validate a query against the schema of another graphql server? (like what Graphi does, but in C#)

What you propose is the only way I can think of at this moment.

**Comment by ManuelDeLeon** [comment]
Oh well. Thanks anyway =)

**Comment by joemcbride** [comment]
One thing of note.  A separate GraphQL server may have its own custom validation rules.  So you could run the _default_ rules, but the only way to know if its truly valid would be to send it to the other server.
