### ISSUE TITLE
Drop support of old options in SchemaPrinterOptions

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2887]
@Shane32  I propose to drop this. Actual spec does not allow use ',' instead of '&amp;' when inheriting a type from multiple interfaces. Also support of this feature requires changes in parser project (little but...) .

Rel: #2868

**Comment by Shane32** [comment]
I agree

**Comment by sungam3r** [comment]
And even this one
![изображение](https://user-images.githubusercontent.com/21261007/151465251-057c5a8e-9f8a-4897-8351-c55570b8fd08.png)

8 years left...

**Comment by Shane32** [comment]
Agree.  

In general, current version should support current-1 spec at most. People can use v4 if they need old spec support.

**Comment by sungam3r** [comment]
Or inherit from `SDLWriter` and override desired parts.
