### ISSUE TITLE
Modularizing schema and multiple end points

### ISSUE THREAD

**Issue by vikassharma-trantor** [graphql-dotnet/graphql-dotnet#2889]
We are using GrapQL 4.7.
We started off with a basic query project and now our application is growing day by day, we want to have multiple schemas and endpoints in the same project.

For instance, we have one schema tied up with all the queries, we need to separate them out like one schema for Users, one for Orders, etc.

Right now my Query file is growing a lot, can I separate that in different components as well?

**Comment by sungam3r** [comment]
#1154

**Comment by Shane32** [comment]
> Right now my Query file is growing a lot, can I separate that in different components as well?

I call a separate method inside the constructor for each field. These methods could easily be defined in different files of a partial query class.

**Comment by vikassharma-trantor** [comment]
@Shane32 , can you share an example?

One more thing, when i upgraded now my queries are giving me the exception like the one below:
**System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues. Path: $.Data.SubFields.FieldDefinition.Type.**

```
     var queryResult = await _documentExecuter.ExecuteAsync(o =>
                {
                    o.Schema = _schema;
                    o.Query = query.Query;
                    o.Inputs = inputs;
                    o.Listeners.Add(_dataLoaderDocumentListener);
                });
                   // var writer = new GraphQL.SystemTextJson.DocumentWriter();
                    //await writer.WriteAsync(HttpContext.Response.Body, queryResult);
                   
                    return CreateWebResponse(queryResult);
```
queryResult will mostly have the data of type 

```
 protected IActionResult CreateWebResponse(ExecutionResult result)
        {
            Response response = new();
            if (result.Errors?.Count > 0)
            {
                response.Status = (int)HttpStatusCode.BadRequest;
                response.Message = "Error while fetching data";
                List<string> errors = new();
                foreach (var item in result.Errors)
                {
                    errors.Add(item.Message);
                }
                response.Errors = errors;
                return BadRequest(response);
            }
            else
            {
                response.Data = result.Data;
                response.Status = (int)HttpStatusCode.OK;
                return Ok(response);
            }

        }
```
```
public class Response
    {
        [JsonPropertyName("data")]
        public object Data { get; set; }

        [JsonPropertyName("status")]
        public int Status { get; set; }

        [JsonPropertyName("message")]
        public string Message { get; set; }

        [JsonPropertyName("errors")]
        public List<string> Errors { get; set; }

        public Dictionary<int, string[]> ErrorMessages { get; set; }

        [JsonPropertyName("referenceNumber")]
        public string ReferenceNumber { get; set; }

    }
```

Any input may be helpful.

**Comment by Shane32** [comment]
> can you share an example?

```cs
partial class Query : ObjectGraphType
{
    public Query()
    {
        ConfigureProductsField();
        ConfigureUsersField();
        //...
    }
}

//another file
partial class Query
{
    private void ConfigureProductsField()
    {
        Field("Products"......);
    }
    private  void ConfigureOrdersField()
    {
         Field("Orders".......);
    }
}

//repeat as desired in multiple files
```

> exception

It is required to use the document writer such as in your example.

> If I uncomment the line

So maybe what's wrong is that the document content type was not set.

If you're using the code inside a controller action, you may wish to check this link:

https://github.com/graphql-dotnet/graphql-dotnet/issues/2157#issuecomment-757044578

**Comment by Shane32** [comment]
FYI, the reference sample has code like this:
```cs
            context.Response.ContentType = "application/json";
            context.Response.StatusCode = 200; // OK

            await _writer.WriteAsync(context.Response.Body, result, cancellationToken);
```

**Comment by vikassharma-trantor** [comment]
Thanks @Shane32 , this certainly helped me a lot.
just one thing, since the query result is a JSON, it adds an additional **data** section in the response.
```
{
	"data": {
		"data": {
			"clientZones": [
				{
					"zip": "84111"
				}
			],
			"status": 200,
			"message": null,
			"errors": null,
			"errorMessages": null,
			"referenceNumber": null
		}
	}
}
```
However, I am expecting this:
```
{
	"data": {
		"zones": [
			{
				"zip": "84111"
			}
		]
	},
	"status": 200,
	"message": null,
	"errors": null,
	"errorMessages": null,
	"referenceNumber": null
}
```
I tried to use **result.Data**, but that wont work since its not a valid JSON
```
response.Status = (int)HttpStatusCode.OK;
                var writer = new GraphQL.SystemTextJson.DocumentWriter();
                using (MemoryStream stream = new MemoryStream())
                {
                  writer.WriteAsync(stream, result);
                   response.Data = JsonSerializer.Deserialize<dynamic>(Encoding.UTF8.GetString(stream.ToArray()));
                }
                return Ok(response);
```
this is how I am constructing it.

**Comment by Shane32** [comment]
Yeah, that's not going to work.  The serialized data stream from the document writer already contains data and errors and stuff; you can't wrap it inside the `Response` object.

For example, this might work:

```cs
response.Status = (int)HttpStatusCode.OK;
                var writer = new GraphQL.SystemTextJson.DocumentWriter();
                using (MemoryStream stream = new MemoryStream())
                {
                  writer.WriteAsync(stream, result);
                   var data = JsonSerializer.Deserialize<dynamic>(Encoding.UTF8.GetString(stream.ToArray()));
                }
                return Ok(data);
```

(Although now the result is getting serialized and deserialized and serialized again.)

**Comment by Shane32** [comment]
I would recommend reviewing the recommended approach - writing some ASP.Net Core middleware rather than adding code within a controller action.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Harness/GraphQLMiddleware.cs

(A fully working sample is included in the repo.)

**Comment by vikassharma-trantor** [comment]
Thanks for the above reference, I will look into it.
```
 public partial class Queries : ObjectGraphType
    {
public Queries(ContextServiceLocator contextServiceLocator)
        {
            DemoQueries(contextServiceLocator);
         }
partial void DemoQueries(ContextServiceLocator contextServiceLocator);
}
```
```
 public partial class Queries
    {
        partial void ReceivingQueries(ContextServiceLocator contextServiceLocator)
        {
            Field<UserProfileType>(
                 "xxxxx",
                 arguments: new QueryArguments(new QueryArgument<IntGraphType> { Name = "id" }),
                 resolve: graphContext => contextServiceLocator.Repository.Get(graphContext.GetArgument<int>("id")));


        }


    }
```
Why I am getting Fields is not valid
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'Field' does not exist in the current context	
```
Why not sure what wrong am I doing here?

**Comment by sungam3r** [comment]
Ensure that you declared both partial classes in the same namespace.

**Comment by vikassharma-trantor** [comment]
It was in the same namespace, restarting VS solved this, weird.

Thank you for the input, it helped me a lot.
The only thing that I need to research is making sure, I get the desired output.
