### ISSUE TITLE
[Question] Inspect given properties while working with complex variables for a mutation

### ISSUE THREAD

**Issue by Sascha-Lindtner** [graphql-dotnet/graphql-dotnet#2896]
I'm currently struggling while working with variabels for mutations, when arguments are a complex type. My problem is, that I get a deserialized type of Note in the example below but not a list of properties which are defined in the argument value (**example call 1**). I really think this is possible in any way and I have just a "simple" missunderstanding. 

When not using a variable and passing the struct directly into the argument, it is very easy for me to read which properties are given (**example call 2**), just by inspecting `context.Arguments`.

I created this simple example to demonstrate my problem.

Classes
```
    public class Note
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
    }

    public class NoteGraphType: ObjectGraphType<Note>
    {
        public NoteGraphType()
        {
            Name = $"Note";
            Field(typeof(StringGraphType), "Id");
            Field(typeof(StringGraphType), "Title");
            Field(typeof(StringGraphType), "Body");
        }
    }

    public class InputNoteGraphType : InputObjectGraphType<Note>
    {
        public InputNoteGraphType()
        {
            Name = $"InputNote";
            Field(typeof(StringGraphType), "Id");
            Field(typeof(StringGraphType), "Title");
            Field(typeof(StringGraphType), "Body");
        }
    }
```

Mutation
```
    Field<NoteGraphType>("upsertNote",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<InputNoteGraphType>> { Name = "input" }

        ),
        resolve: context => {
            var argumentVar = context.Variables.FirstOrDefault(x => x.Name == "input").Value;
            // How to resolve which properties of the variable are given? Here: ["title", "body"]
            // store.UpsertNote(argumentVar, propertyList);
            return argumentVar;
        });

    // example call 1
   mutation upsertNote($input: InputNote!) {
      upsertNote(input: $input) {
        id
      }
    }
```

Example call 1
```
mutation upsertNote($input: InputNote!) {
  upsertNote(input: $input) {
    id
  }
}

# Variables
#  {
#    "input": { 
#      "title": "Test note",
#      "body": "Hello World"
#    }
#  }
```

Example call 2
```
mutation upsertNote {
  upsertNote(input: { title: "Test note", body: "Hello World" })  {
    id
  }
}
```

**Comment by sungam3r** [comment]
Try look into `context.Arguments` dictionary first.

**Comment by Sascha-Lindtner** [comment]
In `context.Arguments` is also "just" the deserialized Note instance

**Comment by sungam3r** [comment]
Then `context.Inputs`.

**Comment by Sascha-Lindtner** [comment]
> Then `context.Inputs`.

context is `IResolveFieldContext` and has no property `Inputs`

**Comment by sungam3r** [comment]
What version do you use?

**Comment by Sascha-Lindtner** [comment]
> What version do you use?

5.2.0

**Comment by sungam3r** [comment]
@Shane32 We have `ExecutionOptions.Inputs` and use it in `ValidationContext` to fill variables (parse/map discrete inputs into variables) but then no initial inputs available from resolver.

**Comment by Shane32** [comment]
Trying to read the "initial inputs" would be a pain anyway.  The input might be a literal and not contained within the variables, or it might be nested within another object.  Then answer is easy with `ParseDictionary`, as this is exactly what the method was designed for:

### Option 1

Add this code to your input graph type:

```cs
public override object ParseDictionary(IDictionary<string, object?> value)
    => value;
```

Then within your resolver, pull the raw dictionary like this:

```cs
var args = context.GetArgument<IDictionary<string, object>>("argument");
```

### Option 2

```cs
    public class Note
    {
        public string Id { get; set; }
        public bool HasId { get; set; }
        public string Title { get; set; }
        public bool HasTitle { get; set; }
        public string Body { get; set; }
        public bool HasBody { get; set; }
    }

//within input graph type
public override object ParseDictionary(IDictionary<string, object?> value)
{
    var note = new Note();
    note.HasId = value.TryGetValue("id", out var obj);
    if (note.HasId) note.Id = (string)obj;
    //repeat for title and body
    return note;
}

//within resolver
var arg = context.GetArgument<Note>("arg");
if (arg.HasId) ...
```

### Note

If you nest complex types, you might need to use the second option.

**Comment by Shane32** [comment]
@Sascha-Lindtner Were you able to solve your issue?

**Comment by Slashi** [comment]
Sorry for my late answer. I created a fix. But all the other solutions did not work. As long as I created my InputTypes via InputObjectGraphType<T>, I'm not able to see which fields are given. Now all my InputTypes a inherited by InputObjectGraphType instead and its fine.
