### ISSUE TITLE
[Feature] Provide ability to configure execution strategies via DI

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2926]
Suggestion:
- Add `IQueryExecutionStrategy`, `IMutationExecutionStrategy` and `ISubscriptionExecutionStrategy` interfaces, which have no methods but each inherit from `IExecutionStrategy`
- Configure `DocumentExecuter` to pull these from DI
- Retain ability to override `SelectExecutionStrategy` method, but default behavior is to use the DI-provided interfaces
- Add `IGraphQLBuilder` methods:
  - Option 1:
    - `AddQueryExecutionStrategy<TExecutionStrategy>() where TExecutionStrategy : IQueryExecutionStrategy` and similar overloads
    - Similar for mutation and subscription
  - Option 2:
    - `AddExecutionStrategy<TExecutionStrategy>(OperationType operationType)` and similar
- `AddGraphQL` uses `TryRegister` to register a "none" `ISubscriptionExecutionStrategy` that throws a `NotSupportException` if calling `ExecuteAsync`.

@sungam3r comments?

**Comment by sungam3r** [comment]
I think that the way with 3 marker interfaces is wrong. You may provide `AddExecutionStrategy<TExecutionStrategy>(OperationType operationType)` without marker inteerfaces. Consider this:
```csharp
public interface IExecutionStrategySelector
{
  IExecutionStrategy Select(ExecutionContext context);
}
public class DefaultExecutionStrategySelector : IExecutionStrategySelector
{
   private readonly ExecutionStrategyRegistration[] _registrations;
   public DefaultExecutionStrategySelector(IEnumerable<ExecutionStrategyRegistration> registrations) { _registrations = registrations}
   public IExecutionStrategy Select(ExecutionContext context)
 {
     foreach (var r in _registrations)
        if (r.Operation == context.Operation.Operation)
           return r.Strategy;
    throw ...;
 }
}
public record ExecutionStrategyRegistration(IExecutionStrategy Strategy, OperationType Operation);
public static AddExecutionStrategy<TExecutionStrategy>(OperationType operationType) where TExecutionStrategy : IExecutionStrategy
{
   services.TryAdd<IExecutionStrategy, TExecutionStrategy>(p => p.GetService<TExecutionStrategy>());
   services.TryAdd<TExecutionStrategy, TExecutionStrategy>();
   services.AddSingleton(provider => new ExecutionStrategyRegistration(provider.GetService<TExecutionStrategy>(), operationType);
}
public class DocumentExecuter
{
   public DocumentExecuter(..., IExecutionStrategySelector executionStrategySelector)
}
```

So `DocumentExecuter.SelectExecutionStrategy will be entirely moved into `IExecutionStrategySelector` component.

**Comment by Shane32** [comment]
Works for me.  Seems a bit more complicated, but that's okay.  It seems also we could put the selection code in the document executor and eliminate the interface, but your suggestion is fine.

One add'l benefit is we can eliminate the SubscriptionDocumentExecuter (if desired).  Just simply add the strategy registration and done.

**Comment by Shane32** [comment]
I'll write a PR sometime.

**Comment by sungam3r** [comment]
> One add'l benefit is we can eliminate the SubscriptionDocumentExecuter (if desired). Just simply add the strategy registration and done.

Yes, because of explicit separation of responsibilities.
