### ISSUE TITLE
Exceptions for many classes in System.Web.Http for GraphQL.GraphiQL

### ISSUE THREAD

**Issue by psavanur** [graphql-dotnet/graphql-dotnet#294]
When running GraphQL.GraphiQL project large number of exceptions are seen for classes in System.Web.Http like No registration for Name = "ITraceManager" FullName = "System.Web.Http.Tracing.ITraceManager", No registration for Name = "ITraceWriter" FullName = "System.Web.Http.Tracing.ITraceWriter etc.

Not able to see UI at chrome browser not sure if its related to these exceptions.
Anyone know how to fix this?

**Comment by joemcbride** [comment]
I have double checked that GraphiQL is working on latest master.  Perhaps you need to do a clean and re-build?  Going to close this.
