### ISSUE TITLE
FieldDelegate support in v5?

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2942]
@sungam3r I'm working on the field resolvers as part of my ValueTask conversion and am looking at support for the `FieldDelegate` method.

The method is designed to allow dynamic binding of a method for a field resolver, so that a method's arguments will be bound to either the IResolveFieldContext, the source, the user context, or arguments.  So the code works like this:
1. If the method argument is of type `IResolveFieldContext`, bind to the context.
2. If the method argument is named "source", AND the type of the source can be cast without error, then bind to source
3. If the type of the user context instance can be cast to the method argument, then use the user context instance
4. Otherwise bind to GetArgument

If it is desired to compile a field resolver ahead-of-time with the same logic, the closest I can do is:
1. If the method argument is of type `IResolveFieldContext`, bind to the context.
2. If the method argument is named "source", then bind to source
3. If the method argument type is `IDictionary<string, object>`, then bind to user context
4. Otherwise bind to GetArgument

Some other options would be:
1. Keep the code as it is, dynamically invoking the method at runtime based on the runtime type of the values within the context
2. Drop support of user context, or perhaps look for the name "userContext", and keep the remainder as I outlined above
3. Copy (or reuse) all logic from AutoRegisteringObjectGraphType, which means:
  a. `IResolveFieldContext` is automatically supported
  b. `[FromSource]` needs to be applied to source parameters
  c. `[FromUserContext]` needs to be applied to user context parameters (need to add this attribute, but we probably should anyway)
  d. `CancellationToken` is automatically supported
  e. Using `[Name]` allows for mapping of method arguments to query arguments with a different name
  f. `[Id]` and similar attributes have no effect, since the attributes are only used to build the field resolver, and not the query arguments
4. Same as option 3, but also extend `FieldDelegate` to build query arguments as well based on the GraphQLAttributes marked on the method signature
5. Drop support of `FieldDelegate` altogether

In any case, I believe I can support ahead-of-time interpretation of the return type of the method -- whether it is a `ValueTask<T>`, `Task<T>`, or `T`.

See ReflectionHelper.BuildArguments:
- https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Reflection/ReflectionHelper.cs

**Comment by Shane32** [comment]
The same code is also used in these places as follows:
- `AccessorFieldResolver`, used by the schema builder
- `EventStreamResolver`, used by the schema builder
- `AsyncEventStreamResolver`, used by the schema builder

So we really need to answer the same question about how the schema builder resolvers work as well.

**Comment by Shane32** [comment]
If we use the code from `AutoRegisteringObjectGraphType` with no changes, this means the following breaking changes for users:
- `source` arguments need to be tagged with `[FromSource]`
- User context arguments need to be tagged with `[FromUserContext]`

I think that's the only real effect.  Benefit is that there will be no late-binding for any methods when using the schema builder.  I think that is worth it, but it is possible that a user would need to change a great many methods during a migration to v5.

We could try to add additional logic to eliminate the `[FromSource]` need, but it would probably only work with the schema builder; not `FieldDelegate` -- and it would differ from `AutoRegisteringObjectGraphType`.

What do you think?

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/153851860-86c83ce9-ac46-4a2c-af26-7dd688612b97.png)
I never used this method and have a strong feeling about its useless. Regarding `AccessorFieldResolver` and other stuff used by `SchemaBuilder` I think that you can change internals using the new autoregistering capabilities.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/2942#issuecomment-1037789896 - agree
