### ISSUE TITLE
Analyze performance for data loaders and queries

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#2945]
Hi,

this would be a topic for the discussions. But they are not enabled, so I ask them here.

A customer of mine is complaining about bad performance. His query is huge and it results in 200+ (up to 3000!) database queries being made.  I use data loaders everywhere and I have only 2 type of queries to resolve references. So in my understanding it should only mean 20 queries or so, given the queries I have seen.

Do you use any tools to analyze the execution of the queries and how data loaders are used?

**Comment by sungam3r** [comment]
Did you try enabling apollo-tracing?

**Comment by Shane32** [comment]
@SebastianStehle No it should not be pascal-case.  If this is an issue we can work on a fix.  I'm pretty sure I reworked this code for v5 and took care to be sure that it was serialized with camelCase regardless of the underlying serializer's configuration.  But there may still be an issue for v4.  Lmk which serializer you use and which exact version of GraphQL.NET please.

**Comment by SebastianStehle** [comment]
I use these packages 

```

    <PackageReference Include="GraphQL.DataLoader" Version="4.7.1" />
    <PackageReference Include="GraphQL.MicrosoftDI" Version="4.7.1" />
    <PackageReference Include="GraphQL.Server.Core" Version="5.2.0" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.2.0" />
    ```
    
    I am looking through my code, perhaps I find any strange customization that is left and not removed yet.

**Comment by Shane32** [comment]
When I was diagnosing speed issues in my own application, I added the MS Application Insights nuget package and added code to my middleware (note: I don't use the server project, but have my own middleware) to record some additional infomation into the telemetry, such as the specific GraphQL query and operation name.  I think EF Core would already record telemetry for database events, and I think there's telemetry recorded for http calls or something also.  Then I would look up a trace within Azure for a sample that took a long time to execute, and try to determine where the bottleneck occurred.  That didn't fully help me, however.  It did reveal that optimizing middleware and DI injection of services during a request really helped.

Then, being that all my queries are predetermined (from the accompanying SPA website), I store each unique query in a database with a unique ID, and store logs for exactly how long each query took to execute and related data (so they are very small db records).  Then I wrote some queries to pull the slowest queries, most recent, etc.  So now I can just request a list of the slowest queries on my site and the average time.

Finally, I wrote code to store the queries in progress (in memory), so if the site is running slow, I can view all queries currently pending, and when they started, etc.  Useful if the site seems to hang and you can catch it in the act.  This lead to my discovering that some of my data loader code was causing a memory leak resulting in an periodic app crash or corrupted results.  (Using the data loaders in the manner documented on the website would not have had those issues.)

**Comment by SebastianStehle** [comment]
> When I was diagnosing speed issues in my own application, I added the MS Application Insights nuget package and added code to my middleware (note: I don't use the server project, but have my own middleware) to record some additional infomation into the telemetry, such as the specific GraphQL query and operation name. I think EF Core would already record telemetry for database events, and I think there's telemetry recorded for http calls or something also. Then I would look up a trace within Azure for a sample that took a long time to execute, and try to determine where the bottleneck occurred. That didn't fully help me, however. It did reveal that optimizing middleware and DI injection of services during a request really helped.

I am doing something similar. I already have traces collected with Open Telemetry. The resulting diagram is just a big mess, and I also do not have number of IDs per query and so on, which could support me to check if the data loaders work properly. Perhaps I should just add these information.

Btw: I just resolved a reference to IDocumentWriter to check with implementation is used and I was confused, that there is no reference to ApolloTraceJsonConverter.

![image](https://user-images.githubusercontent.com/1236435/153925226-c1b4f1d0-902b-44cd-a8ac-39c72ecf5472.png)

**Comment by Shane32** [comment]
Hmm.  Weird.  Assuming you are using the AddSystemTextJson builder method -- either the new or old builder method -- it should be adding that converter.

**Comment by Shane32** [comment]
Perhaps you can find your code that registers the systemtextjson writer and post the code so I can check it out.  And let me know if you use the old or new builder methods (if any).

**Comment by Shane32** [comment]
Not sure that I have any other advice here @SebastianStehle but I would be interested in your findings.

**Comment by Shane32** [comment]
See PR:
- #3691
