### ISSUE TITLE
Incorrect rounding of decimal numbers

### ISSUE THREAD

**Issue by dulcisclade** [graphql-dotnet/graphql-dotnet#2958]
## Description

The issue is reproduced for decimal numbers with max available precision, scale (16, 2)
For mutation model with decimal type field as a result of parsing the value is rounding incorrectly 
 e. g. 12345678901234.56 -> 12345678901234.6

 
### Steps to reproduce

- Request:
![2](https://user-images.githubusercontent.com/31682990/154928215-0077712d-e8e3-4291-b674-158ac678cd79.png)

- Mutation Model:

```
public class MutationTestModel
    {
        public decimal Discount { get; set; }
    }
```

- Mutation Type:
```
 public sealed class MutationTestType : InputObjectGraphType<MutationTestModel>
    {
        public MutationTestType()
        {
            Field(x => x.Discount);
        }
    }
```

 For getting requests variables GraphQL.SystemTextJson.StringExtensions is used
 ```
     var request = await stream.FromJsonAsync<T>();
 ```
  
 The issue is related to *GraphQL.SystemTextJson.InputsConverter: private static object ReadNumber(ref Utf8JsonReader reader)*.
 **Any decimal number from the request is parsed as Double and *reader.TryGetDecimal(out decimal dm)* method is never used**.
 
 ``` 
        private static object ReadNumber(ref Utf8JsonReader reader)
        {
            if (reader.TryGetInt32(out int i))
                return i;
            else if (reader.TryGetInt64(out long l))
                return l;
            else if (JsonConverterBigInteger.TryGetBigInteger(ref reader, out var bi))
                return bi;
            else if (reader.TryGetDouble(out double d))
                return d;
            else if (reader.TryGetDecimal(out decimal dm))
                return dm;
            ...
 ```
 
![3](https://user-images.githubusercontent.com/31682990/154928275-81f482c6-85ac-40b2-b237-631ad7eb30f6.png)

Therefore, when the input is mapped to the query model, double is parsed to decimal, and for numbers with the maximum available precision, the scale (16, 2) is rounded incorrectly.
 
![4](https://user-images.githubusercontent.com/31682990/154928364-80de8810-4fb3-45d6-b572-883bc55aba16.png)

### Expected result

The decimal field value should be the same as in the request
12345678901234.56 -> 12345678901234.56

### Actual result

The decimal field value is incorrect
12345678901234.56 -> 12345678901234.6

### Environment

GraphQL Version: 4.7.0
FrameWork: .Net 6.0

**Comment by Shane32** [comment]
This is already fixed in the next major version, to be released in April.

**Comment by sungam3r** [comment]
@Shane32 I see the same code for `ReadNumber` in `develop`.

**Comment by Shane32** [comment]
Oh, right, I was thinking of literals.

**Comment by sungam3r** [comment]
@dulcisclade Do you need this fix ASAP for v 4.x or can you wait a bit for April v5 release?

**Comment by dulcisclade** [comment]
I'm good with April's release, thanks!

**Comment by sungam3r** [comment]
Merged and will be published in v5.
