### ISSUE TITLE
How to apply a directive

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#2961]
Hi, I wanna build a client side directive, where the client can decide to cache some fields using an IMemoryCache.

I have created the directive:

```
public sealed class MemoryCacheDirective : DirectiveGraphType
{
	public MemoryCacheDirective()
		: base("cache", DirectiveLocation.Field, DirectiveLocation.FragmentSpread, DirectiveLocation.InlineFragment)
	{
		Description = "Enable Memory Caching";

		Arguments = new QueryArguments(new QueryArgument<NonNullGraphType<IntGraphType>>
		{
			Name = "duration",
			Description = "Cache duration in seconds."
		});
	}
}
```

And also registered it.

And I am using the following extension method:

```
public static TimeSpan CacheDuration(this IResolveFieldContext context)
{
	var cacheDirective = context.FieldDefinition.FindAppliedDirective("cache");

	if (cacheDirective != null)
	{
		var duration = cacheDirective.FindArgument("duration");

		if (duration?.Value is int value && value > 0)
		{
			return TimeSpan.FromSeconds(value);
		}
	}

	return TimeSpan.Zero;
}
```

But the directive is always null:

My query (from tests)

```
var query = CreateQuery(@"
	query {
	  findMySchemaContent(id: '<ID>') {
		id
		flatData {
		  myReferences @cache(duration: 1000) {
			id
		  }
		}
	  }
	}", contentId);
```

The extension method is invoked on the correct field (myReferences), but does not provide a result.

### Environment (if relevant)

GraphQL.NET: 4.7

**Comment by SebastianStehle** [comment]
Sorry, I have found a solution:

```
public static TimeSpan CacheDuration(this IResolveFieldContext context)
{
	var cacheDirective = context.FieldAst.Directives?.Find("cache");

	if (cacheDirective != null)
	{
		var duration = cacheDirective.Arguments?.ValueFor("duration");

		if (duration is IntValue value && value.Value > 0)
		{
			return TimeSpan.FromSeconds(value.Value);
		}
	}

	return TimeSpan.Zero;
}
```

**Comment by sungam3r** [comment]
You are right. `FieldDefinition` is a `FieldType` i.e. server "entity". You need a client "entity" - `FieldAst`. Also you may be interested in https://github.com/graphql-dotnet/graphql-dotnet/pull/2920 which will be published in v5.

**Comment by SebastianStehle** [comment]
From the wording I have not understand it. I was also not sure what an "applied directive" is. A client side directive is somehow also applied. But I got it working with the debugger ;)

**Comment by sungam3r** [comment]
`DirectiveGraphType` is a directive definition like `FieldType` is a definition for field. `MemoryCacheDirective` is a definition. You may _apply_ your directive to some schema element. In your case you apply `@cache` directive to some field or fragment spread. Client sends a request like
```graphql
{ name @cache(duration: 100) }
```

From field resolver you now may to get information about this _applied_ directive via APIs added in #2920.
```csharp
Field<StringGraphType>("myField", resolve: context =>
{
    var dir = ctx.GetDirective("myDirective");
    var arg = dir.GetArgument<string>("arg");
    ...
});
```

Yes, no _applied_ wording here to just keep simple naming - GetArgument/GetDirective.

**Comment by sungam3r** [comment]
Closed as answered.
