### ISSUE TITLE
Callback on all children completion : handle 'IDisposable' and 'IAsyncDisposable' by calling their 'dispose' methods

### ISSUE THREAD

**Issue by noe555** [graphql-dotnet/graphql-dotnet#2969]
## Summary

The goal is that, when a parent node which has children (ObjectExecutionNode and ArrayExecutionNode) have all their children completed, be able to run some code. 
By 'completed', I mean more precisely that all the 'leaf' values node have been computed (including the differed case of IDataLoaderResult), or nested parent nodes have themselves completed (and if present, their own callback has also been run, and so on recursively).

As this has some symmetry with the node creation given than some code can be run in any of the FieldBuilder.Resolve() and FieldBuilder.ResolveAsync() methods in the order parent -> child and now we want the reverse, I think it would seem natural to use the IDisposable and IAsyncDisposable interfaces so that, if an object which implements either IDisposable and IAsyncDisposable is returned inside the .Resolve() and .ResolveAsync()  methods, the related Dispose() and DisposeAsync() methods should be called when all the children have completed.
Furthermore, when all the children have completed, my understanding is that the object becomes useless in the GraphQL engine (they are not needed for the serialization, as the serialization only generate curly or square brackets for these nodes) after having their creation triggered by it. Thus using these interfaces, given their names and their usage pattern, would make sense.

### Motivation

This would allow to clean up ressources that could be re-used accross different nodes.

Consider the following example : 

query {
&nbsp;&nbsp;efQ1: [
&nbsp;&nbsp;&nbsp;&nbsp;{ v1 v2 },
&nbsp;&nbsp;&nbsp;&nbsp;{ w1 w2 }
&nbsp;&nbsp;],
&nbsp;&nbsp;efQ2: [
&nbsp;&nbsp;&nbsp;&nbsp;{ x1 x2 },
&nbsp;&nbsp;&nbsp;&nbsp;{ y1 y2 }
&nbsp;&nbsp;]
}

We use the SerialExecutionStrategy.

A top-level node ('query', which is the Graph QL full query) have 2 children.
Each of them is of type graphType ListGraphType<> and are backed by (the dotnet object returned by .Resolve() containing) an underlying EF query : an IAsyncEnumerator (obtained with IQueryable<>.GetAsyncEnumerator()), as the underlying EF query is streamed.
The leaves vN, wN, ... extract data from the current row, are of type IDataLoaderResult, and when the first leaf is requested, the underlying (full) EF query is initiated before the read.
We need to close the IAsyncEnumerator after the full fetching of the (first) node efQ1 so that the second query efQ2 can run. But, we have no (easier than the GraphQL engine) way to identify the last leaf of efQ1 which reads data from the query to close it when it has finished.

Right now, since we cannot close the connection between the two efQN nodes, the second one fails to open the connection (exception example with mysql : 'System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse').

Thus we have to perform 2 graphql queries : one per EF query, instead of a single one, and this problems extends to as many queries as needed, and rely on adding additional logic external of the GraphQL engine to close the (single) connection.

**Comment by Shane32** [comment]
Regarding IAsyncEnumerable see:
- #2532

**Comment by Shane32** [comment]
If you are returning an IAsyncEnumerable from Entity Framework right now, what happens is that EF is casting the IQueryable it’s already generated to an IAsyncEnumerable upon the call to AsAsyncEnumerable. GraphQL.NET does not recognize this and is detecting that the object returned implements IEnumerable, and so is iterating the list synchronously. 

Please read through the linked PR above why currently IAsyncEnumerable is not supported. 

I would strongly suggest you call ToListAsync so that the database call is asynchronously iterated. This should also solve your immediate issue with disposal of connections.

**Comment by noe555** [comment]
Hi Shane32, thank you for time and your response.

In my case I cannot resolve the efQ definitions directly to the IEnumerator based of the full query.
This query requires all the descendants (named v, w, ... in my example) to be known to compute the full projection inside the .Select().
Thus, we use 'IDataLoaderResult' for the children, and on the first .GetResultAsync() on them, the full (streaming) query will be triggered in the custom EF object of a custom class ("EFWrapper") which was the resolver for the efQ nodes.
This enhancement request is to have symmetrically an easy entry point to close it when the last child has completed.

The full query is something I use internally in EFWrapper class, and is not directly accessed by the GraphQL engine.

To return the IEnumerator<> for the efQ nodes resolver, "EFWrapper" runs a minimal query, which rougly returns the # of rows, and closes right away.
That one does not need to be IAsyncEnumerator, as my understanding of the ticket you mentionned.

You're right that calling .ToListAsync() instead of streaming solves the issue, but requires arbitrary extra memory (each row has more data than that of the db row, as it needs at this point to keep track of which child requested which data, and thus the full list will cost much more than what will be used to fill the final ExecutionResult.data, for comparison), and prevents the parallelism of reading the data from the db and the processing by the GraphQL engine.

**Comment by Shane32** [comment]
I'm not sure if this is something we will want to merge or not.  However, have you tried making your own execution strategy, such as this:

```cs
public class MySerialExecutionStrategy : SerialExecutionStrategy
{
    protected override async Task CompleteNodeAsync(ExecutionContext context, ExecutionNode node)
    {
        await base.CompleteNodeAsync(context, node);
        if (node.Result is IDisposable disposable)
            disposable.Dispose();
    }
}
```

**Comment by Shane32** [comment]
For my own code, I have the parent field resolver examine the children nodes that are requested (see #2164 ) and build a select query for the columns that are needed.  Select queries create/return dictionaries and child nodes pull the relevant column from the dictionary.  In this manner the SQL query returns no more columns than necessary and can take advantage of indexing with included columns.  Data loaders are not necessary unless I need to queue up IDs from child objects for another query, so that there are no performance issues with relationships with multiple child entities.  But that's just how I do it.

**Comment by noe555** [comment]
> I'm not sure if this is something we will want to merge or not. However, have you tried making your own execution strategy, such as this:
> 
> ```cs
> public class MySerialExecutionStrategy : SerialExecutionStrategy
> {
>     protected override async Task CompleteNodeAsync(ExecutionContext context, ExecutionNode node)
>     {
>         await base.CompleteNodeAsync(context, node);
>         if (node.Result is IDisposable disposable)
>             disposable.Dispose();
>     }
> }
> ```

Hi @Shane32 , this does not solve the issue, as the CompleteNode() is called on the efQ node just after the IEnumerable<> has been computed, before the execution of the children, not after.

**Comment by noe555** [comment]
> For my own code, I have the parent field resolver examine the children nodes that are requested (see #2164 ) and build a select query for the columns that are needed. Select queries create/return dictionaries and child nodes pull the relevant column from the dictionary. In this manner the SQL query returns no more columns than necessary and can take advantage of indexing with included columns. Data loaders are not necessary unless I need to queue up IDs from child objects for another query, so that there are no performance issues with relationships with multiple child entities. But that's just how I do it.

Thanks. I did not try this. I will, but, given the size of the changes, I don't know when I will be able to give the feedback.

**Comment by Shane32** [comment]
> Hi @Shane32 , this does not solve the issue, as the CompleteNode() is called on the efQ node just after the IEnumerable<> has been resolved, before the execution of the children, not after.

Right. Well, I’d just write my own execution strategy for this particular feature. It should not be difficult to make the proper modifications to dispose of the node at the correct location for your needs. I would find it unlikely that we would want to merge such a feature into this codebase because it seems like you are not quite using results and data loaders for their intended purpose. (Nothing wrong with that, but it not quite how the code was designed to be used.)

**Comment by Shane32** [comment]
@noe555 You may wish to review this issue which discusses pulling only requested fields from the database:
- https://github.com/SimonCropp/GraphQL.EntityFramework/issues/145

**Comment by sungam3r** [comment]
> it seems like you are not quite using results and data loaders for their intended purpose

Agree. In addition, I do not think that returning `IDisposable` object from the resolver as is should be treated as a command/indication to dispose it. In general, we do not know _anything_ about the lifetime of this object. But I also agree that we _may_ figure out something useful from this discussion so let's keep issue opened.

**Comment by Shane32** [comment]
If we were to implement such a feature, which seems unlikely, I would expect us to do so as another method on a document listener, such as `CompletedNodeChildren` or some such thing.  But so far it seems to me that for this special use case a custom execution strategy would be the best answer.

**Comment by noe555** [comment]
> In addition, I do not think that returning `IDisposable` object from the resolver as is should be treated as a command/indication to dispose it. In general, we do not know _anything_ about the lifetime of this object. 

I don't understand much this point. 
The method paramter in .Resolve(), is called by the GraphQL Engine, and one returns an object to be used for it, with its lifecycle, and only the GraphQL engine can notify efficiently when it is not needed by it anymore. 
If the resolved object needs to listen to any other lifecycle that have colliding method names ("Dispose"), then it needs to be split into 2 objects by the client developer to handle the two lifecycles (which can be a good practise even when the names do not collide). 

For example, in the Dependecy Injection API, in [this method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions.addscoped?view=dotnet-plat-ext-6.0#microsoft-extensions-dependencyinjection-servicecollectionserviceextensions-addscoped(microsoft-extensions-dependencyinjection-iservicecollection-system-type-system-func((system-iserviceprovider-system-object)))), one is also free to return in the implementationFactory method any object which may have any other api lifecycle that may call its Dispose() method, and still, the  [Dispose() method is called when it has become useless for the container (on Scope closure)](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines).

**Comment by sungam3r** [comment]
> and one returns an object to be used for it

Why so? Resolver may return anything, for example, it _may_ return some singleton object pulled from DI. Why should GraphQL engine dispose this object? How to know when it should and when it should not?

Regarding DI example. Your example relates to a different case. GraphQL engine knows nothing about what to do with disposable instances returned from resolver. But we _may_ teach engine to do something if returned result implements some "special" interface like `IDataLoaderResult`. Anyway I don't think it is useful and I don't think it is the way you want to use.

**Comment by Shane32** [comment]
As I see it, the bigger issue is the fact that you’ve requested a specific lifecycle. Even if it would be reasonable to dispose of the returned object, there is no logical reason to wait to dispose of it until all child objects have been resolved. It would make more sense to dispose of it immediately after enumerating the list. Someone could also say that since the returned objects within the array are not completely serialized yet, it shouldn’t be disposed until after the execution result is serialized to JSON. However, your use case necessitates a “disposal” after child objects are converted to nodes, and specifically at that time. Not sooner and not later.

So in this case your need is unique and does not match typical disposal patterns, which are less dependent on when exactly the object is disposed.

**Comment by noe555** [comment]
> For my own code, I have the parent field resolver examine the children nodes that are requested (see #2164 ) and build a select query for the columns that are needed. Select queries create/return dictionaries and child nodes pull the relevant column from the dictionary. In this manner the SQL query returns no more columns than necessary and can take advantage of indexing with included columns. Data loaders are not necessary unless I need to queue up IDs from child objects for another query, so that there are no performance issues with relationships with multiple child entities. But that's just how I do it.

Hi Shane, we eventually implemented this, and it looks to fulfill our use case.
So we don't need this feature anymore for our needs.
Thanks again for your feedbacks and your time, and feel free to close the ticket.
