### ISSUE TITLE
Exceptions for many fragments

### ISSUE THREAD

**Issue by IGOOA** [graphql-dotnet/graphql-dotnet#297]
Does graphql support to show the errors per fragement? Can we provide some extension or injection on error handling?

**Comment by joemcbride** [comment]
* the line/column should be provided in the error for the fragment so you can trace it back to a resolver
* you can add your own try/catch in your field resolve functions
* you can log or debug and check the inner exceptions for specific exceptions

Possibly related?  #279

**Comment by IGOOA** [comment]
Thanks for your feedback. It's very helpful for us.
