### ISSUE TITLE
.NET Metrics / Prometheus

### ISSUE THREAD

**Issue by wolfcomp** [graphql-dotnet/graphql-dotnet#2973]
## Summary
.NET Metrics / Prometheus support

### Basic example
Would it be possible to add a function be it a middleware to extends the current support of metrics from just apollo metrics but to the entire [.NET Metrics](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/metrics) ecosystem this way it could also be exposed in the Prometheus package that is available on NuGet

### Motivation
Would allow for continuous monitoring of requests with how long execution time it takes without actually making the requests your self

**Comment by sungam3r** [comment]
You may achive that by writing a custom field middleware. I did so at my work. Exposed metrics: resolved fields count, count of fields with errors, etc. In general, my answer regarding your question is that the mission of this repository is in providing sufficient set of extension points.

**Comment by wolfcomp** [comment]
Mainly just timing of request, hit count, and such based on what is requested and maybe even complexity of the request as a histogram. And yes was thinking of until it's not in the main codebase just writing my own middleware for it when I have the time to implement it.

**Comment by wolfcomp** [comment]
Also, to see what the Prometheus package does currently, here is the [repo](https://github.com/prometheus-net/prometheus-net)

**Comment by SebastianStehle** [comment]
The world is moving to Open Telemetry anyway. Would make sense to have an integration for that.

**Comment by wolfcomp** [comment]
Seems the Open Telemetry uses a different method than .NET Metrics, so possibility for both would be nice. As .NET Metrics is `System.Diagnostics.Metrics` and Open Telemetry uses `System.Diagnostics`.

**Comment by sungam3r** [comment]
Closed as answered.
