### ISSUE TITLE
Build checks intermittently fail

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2982]
Continuing build check failures:

- `GraphQL.Tests.Introspection.AppliedDirectivesTests.introspection_should_return_applied_directives`
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5384459140?check_suite_focus=true
  - Sometimes it returns `"name": "RootMutation"` (correct) and sometimes `"name": "AppliedDirectivesTests_RootMutation"` (incorrect)
- `GraphQL.Tests.Initialization.SchemaInitializationTests.SchemaWithArgumentsOnInputField_Should_Throw`
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5737387227?check_suite_focus=true
  - Also seems to have to do with a static option incorrectly set

Fixed:
- `GraphQL.Tests.Types.AllScalarGraphTypeTests.parseValue_from_system_text_json_ok`
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5378902286?check_suite_focus=true
  - Culture problem with negative value
- Fails when all tests pass
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5383976682?check_suite_focus=true
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5378827075?check_suite_focus=true
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5603665805?check_suite_focus=true
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5651194580?check_suite_focus=true
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5721750186?check_suite_focus=true
  - https://github.com/graphql-dotnet/graphql-dotnet/runs/5801756371?check_suite_focus=true
  - Seems to be issues with coverlet

**Comment by Shane32** [comment]
I will continue to update this PR as more checks fail.

**Comment by sungam3r2022** [comment]
> "RootMutation" (correct) and sometimes "name": "AppliedDirectivesTests_RootMutation"

Known issue with static setting.

**Comment by sungam3r2022** [comment]
Note:

>Additional Info:
    Converted value: −1E+25, Type: **System.Double**

I added this trace some time ago to deal with failed results.

**Comment by sungam3r2022** [comment]
Something wrong with `JsonConverterBigInteger.TryGetBigInteger` called from `InputsJsonConverter.ReadNumber`

**Comment by sungam3r2022** [comment]
![изображение](https://user-images.githubusercontent.com/100795854/156454976-a09dda02-6dc1-4ec4-aa61-b0f585290769.png)
Maybe here. I always get `HasValueSequence = false` but on CI it may be `true` and something happens.

**Comment by sungam3r2022** [comment]
Long story short - `converted` variable from `parseValue_from_system_text_json_ok` should be of type `BigInteger`.

**Comment by Shane32** [comment]
You notice that the "converted value" logged has the incorrect unicode character for minus.  So the current culture at the time the test ran was abnormal.  However, this shouldn't have been a problem if parsing was to JSON spec (using invariant culture).  I think `JsonConverterBigInteger.TryGetBigInteger` is not specifying an invariant culture and so is unable to parse the minus sign while the culture is abnormal.

**Comment by sungam3r2022** [comment]
>  incorrect unicode character for minus

🤦‍♂️ completely forgot about that

**Comment by sungam3r** [comment]
https://github.com/coverlet-coverage/coverlet/issues/865

The fix seems to be simple - change coverlet.msbuild to coverlet.collector and change one worflow to use other dotnet test arguments. I use coverlet.collector at my work for a long time. We even inject coverlet.collector at out CI , i.e. our test csprojs do not contain references to all that coverage stuff to not bother developers.

**Comment by sungam3r** [comment]
@Shane32 I'm sure you may fix it yourself if you would or I can fix it myself some time later on next week. Now I would like to spend some time reading about subscriptions. I have already studied everything I want about Rx to start work with.

**Comment by sungam3r** [comment]
Done

**Comment by Shane32** [comment]
Updated notes at top of this PR to reflect that the coverlet issue was fixed.

**Comment by Shane32** [comment]
To fix the other issues, think we should try creating a "Test Collection" for any tests that modify static variables, and then modify the properties of the test collection to disable parallelism.  

https://xunit.net/docs/running-tests-in-parallel

So long as the tests revert the static variables before completion, I'm hoping this will prevent incorrect static variables during other tests, fixing the other two issues above.

To do this we need to identify all tests that modify static variables or change the culture settings.
