### ISSUE TITLE
[Discussion] Remove IAccessor ?

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2986]
IAccessor is only used by the schema builder and it seems only as a temporary way of holding a reference to a member, used to generate a field resolver.  It would seem that it could be removed, unless it is needed to be able to be assigned by attributes or some such thing.

**Comment by sungam3r2022** [comment]
Looks like a wrapper but I don't know this part well.

**Comment by Shane32** [comment]
I suggest we do not make this change for v5.  Maybe if we remove TypeConfig and FieldConfig in v6 then we can remove IAccessor at the same time.
