### ISSUE TITLE
Working in new reality

### ISSUE THREAD

**Issue by sungam3r2022** [graphql-dotnet/graphql-dotnet#2989]
Hi @joemcbride and @Shane32 !

We live at an interesting time, yeah. My GitHub account was blocked/suspended due to situation in Ukraine. Politics sucks. VPN does not help, they locked account. My new account is @sungam3r2022 . Now I think what to do next. For a while I can not support this project. Honestly, I can not support any projects that I had access before. @Shane32 To make sure that I am I, you may send me a letter to the email specified in my suspended profile. Blocking covered me at the moment when I did review.

**Comment by Shane32** [comment]
No problem.  I just sent a Slack message to you for confirmation on the graphql Slack account.  I'm sure for immediate needs you can fork the repo and create PRs and stuff, and I can merge your PRs for you.  I don't have permissions to add you as a collaborator.

**Comment by sungam3r2022** [comment]
Answered. I still have to tinker with SSH keys. By the way, there is no guarantee that the new account is also not blocked over time. I wrote in their (GitHub) support with a request to unlock my account. Little hope.

I will continue review tomorrow. Today my mood is spoiled.

**Comment by sungam3r** [comment]
Account was unblocked after conversation with Github support.
