### ISSUE TITLE
How protect query with JWT

### ISSUE THREAD

**Issue by janskoruba** [graphql-dotnet/graphql-dotnet#299]
I am wondering how can I protect the specific query with valid JWT?

Is it some best practice how use the access token?

Thank you
Jan

**Comment by jquense** [comment]
Authentication should happen before the GQL bits get involved by whatever is actually handling your http requests. If you are using WebApi then an auth filter/action/whatever they are called can grab the token from the header, validate it, and reject or continue the request.

For metadata you might be storing in your token, I'd decode that in your http handler, and add it to the `UserContext` object when creating the schema, that way any field resolvers can access it through the whole graph

**Comment by janskoruba** [comment]
Thank you so much, you are right because I've used the web api. :)

**Comment by joemcbride** [comment]
Here's also a little bit I put together on [Authentication/Authorization](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md#authentication--authorization).

**Comment by ujwaliyer** [comment]
above Authentication/Authorization link is broken! @joemcbride

**Comment by joemcbride** [comment]
@ujwaliyer Updated:  https://graphql-dotnet.github.io/learn/#authentication-authorization

Also see: https://github.com/graphql-dotnet/authorization

**Comment by ujwaliyer** [comment]
Thank you so much joe!

**Comment by ericcanadas** [comment]
The link is broken again @joemcbride 
I search a sample who securise all graphql access with JWT
