### ISSUE TITLE
Query / How To : Need assistance in implementation of Union

### ISSUE THREAD

**Issue by pravinhabbu4u** [graphql-dotnet/graphql-dotnet#300]
@joemcbride Requesting your expertise on implementing union in below example. 

Example: A company has employee and customers. They want a search screen to show matching employees and customers using SearchWord (name search).

```
   public class Employee
    {
        public string Name { get; set; }
        public string EmployeeID { get; set; }
    }

    public class EmployeeType : ObjectGraphType<Employee>
    {
        public EmployeeType()
        {
            Field(x => x.Name, nullable: true).Description("Name");
           Field(x => x.EmployeeID).Description("ID");
        }
    }

    public class Customer
    {
        public string Name { get; set; }
        public string CustomerNumber { get; set; }
    }

    public class CustomerType : ObjectGraphType<Customer>
    {
        public CustomerType()
        {
            Field(x => x.Name, nullable: true).Description(" Name");
            Field(x => x.CustomerNumber).Description("ID");
        }
    }
    public class EmployeeORCustomer : UnionGraphType
    {
        public EmployeeORCustomer()
        {
            Type<EmployeeType>();
            Type<CustomerType>();

            ResolveType = (obj) =>
           {
               if(obj is EmployeeType)
               {
                   EmployeeType e = new EmployeeType();
                   return e;
               }

               if (obj is Customer)
               {
                   CustomerType e = new CustomerType();
                   return e;
               }

               throw new ArgumentOutOfRangeException($"Could not resolve graph type for {obj.GetType().Name}");
           };
        }
    }
```

I have a query that exposes only 1 root search field for union as 

```
    public class Query__: ObjectGraphType
	{
		public Query__()
		{
            Field<EmployeeORCustomer>("SearchEmployeeOrCustomer",
        arguments: new QueryArguments(new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "SearchWord" }),
        resolve: context =>
        {
            // shoud I write logic here to find matching employees
            // and then matching customers 
            // if yes then how can I return them from here as return EmployeeType + CustomerTYpe 
            // how this portion works with resolvetype on union
            return null;   
        }
    );

```

I am struggling to understand steps for resolve: an explanation by returning __Employee , __Customer would help.

Employee __Employee = new Employee();
__Employee.Name = "TEST EMP";  __Employee.EmployeeID = "1234";

Customer __Customer= new Customer();
__Customer.Name = "TEST CUST";  __Customer.CustomerNumber= "8888";

How to say return __Employee |union|  __Customer;???

**Comment by jquense** [comment]
You probably don't have to do anything fancy with `ResolveType` at all. try just removing it. The reason you'd need it is that the Union type needs to know how to turn its source `object` into the output type. To do that it needs to know which of the union type (Employee, Customer) maps to that Source, and ResolveType can provide some custom logic to do that. **However** individual types can also implement a `IsTypeOf` method that takes a source object and returns `true` if it's a valid source type. All the `ObjectGraphType<T>` types already implement this method by default as `type => type is T`. So if the source object is a `Customer` it will resolve to CustomerGraphType, and the same for Employee.

**Comment by pravinhabbu4u** [comment]
@jquense Thanks for the quick response. This truly clears my biggest confusion on why I needed both resolve on query field and ResolveType on union object. I have removed the resolve type section now. I am only trying to see how I can take care of resolve method on union field.

 public class Query__: ObjectGraphType
	{
		public Query__()
		{
            Field<EmployeeORCustomer>("SearchEmployeeOrCustomer",
        arguments: new QueryArguments(new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "SearchWord" }),
        resolve: context =>
        {
    
        List<Employee> EmpList = new List<Employee>();
       ..... Add few records to employee list
        List<Customer> CustomerList= new List<Customer>();
       ..... Add few records to cust list

      var matchingEmployees = EmpList.find(....); // filter matching
      var matchingCustomers = CustList.find(....); // filter matching

how can I now return matchingEmployees + matchingCustomers from here????
        }
    );

**Comment by jquense** [comment]
that's up to you, This sort of polymorphic list is more of a c# pattern question. GQL.net doesn't add any special utilities for adding discriminated unions. The most straightforward way to do it tho, is to have a `List<IPeople>` where Customer and Employee both implement `IPeople`

**Comment by pravinhabbu4u** [comment]
@jquense Thanks for the explanation. I think I am close to resolution now but kind of not sure why still the response is null. Any input from your end is greatly appreciated. Thanks!

```
    public class Human
    {
        public string _Name { get; set; }
    }

    // Class : API_IdentityV5_GetMulti_IdentityModel
    public class Employee :Human
    {
        public string _Name { get; set; }
        public string EmployeeID { get; set; }
    }

    public class EmployeeType : ObjectGraphType<Employee>
    {
        public EmployeeType()
        {
            Field(x => x._Name, nullable: true).Description("Name");
            Field(x => x.EmployeeID, nullable: true).Description("ID");
        }
    }

    public class Customer :Human
    {
        public string _Name { get; set; }
        public string CustomerNumber { get; set; }
    }

    public class CustomerType : ObjectGraphType<Customer>
    {
        public CustomerType()
        {
            Field(x => x._Name, nullable: true).Description("l Name");
            Field(x => x.CustomerNumber, nullable: true).Description("ID");
        }
    }

    public class EmployeeORCustomer : UnionGraphType
    {
        public EmployeeORCustomer()
        {
            Type<EmployeeType>();
            Type<CustomerType>();
        }
        
    }
```

        ```
    Field<EmployeeORCustomer>("SearchEmployeeOrCustomer",
        arguments: new QueryArguments(new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "SearchWord" }),
        resolve: context =>
        {
            Employee ee = new Employee();        ee.EmployeeID = "1234";             ee._Name = "AABBCC";
            Customer cc = new Customer();       cc.CustomerNumber = "xyz";        cc._Name = "david";

            List<Human> L = new List<Human>();
            L.Add(ee);
            L.Add(cc);
            return L;
        }

```

for some reason my response is empty/ null. I understand it is not a graphql issue but something that you can clarify would be great.

query Union{
  
  SearchEmployeeOrCustomer(SearchWord:"ABC"){
    ... on EmployeeType{
      _Name
      EmployeeID
      
    }
    ... on CustomerType{
      _Name
      CustomerNumber
    }
  }
}


Response:

{
  "data": {
    "SearchEmployeeOrCustomer": null
  }
}


I am trying to find missing link of EmployeeType vs Employee and CustomerType vs Customer which seems like an issue

**Comment by pravinhabbu4u** [comment]
Got it, It was stupid issue of me not specifying ListGraphType on query field but was returning list. Changed it and is working as expected. Thanks @jquense
