### ISSUE TITLE
Subscription implementation problems

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3002]
## 1. Execution errors are not returned

This seems to be a flaw in the design.  I see no reason why the subscription support should not return errors generated while executing a subscription data event (which is much like a document executer).  The specification clearly says that errors should be returned.

http://spec.graphql.org/October2021/#sec-Response-Stream

Suggestion: return execution errors just like a document executer would

## 2. Execution errors, extensions, and metrics are not cleaned up after a data event

Each data event that generated errors would get added to the `ExecutionContext.Errors` instance, and never cleared.  A similar issue would happen if metrics were enabled.  Essentially this is a memory leak, and potentially a bad one if metrics were enabled along with the middleware.

Suggestion: reinitialize errors, output extensions and metrics from the shared context after they are returned within the execution result (if necessary).

## 3. Exceptions generated by a document listener are not handled by the unhandled exception handler

Suggestion: process exceptions by the unhandled exception handler

## 4. Errors generated by the observable source are not handled by the unhandled exception handler

Suggestion: process exceptions by the unhandled exception handler

## 5. Default error descriptions are inaccurate, and contain the entire original query

Suggestion: fix, and remove entire original query from error message

## 6. If the initial request contains multiple subscription requests, the context is shared

This could lead to problems like errors from one subscription data event being returned within another subscription data event.  I'm not actually sure that the GraphQL spec allows for multiple subscriptions at once, but regardless, it seems like a design flaw in the code.

Suggestion: clone the ExecutionContext for each individual subscription field requested; executions within that subscription occur sequentially so the ExecutionContext can be shared over multiple data events

## 7. The cancellation token provided to field resolvers for data events reflects the http cancellation token and not the subscription cancellation token (set when the subscription is disposed of)

The graphql-ws protocol allows for starting and stopping subscriptions without breaking the websockets connection.  So the cancellation token for the http context may be longer than that of the subscription.  In practice this won't matter much as the websocket handler should request disconnection from the event stream source and if an extra event gets through, the websocket handler should ignore it.

Suggestion: Assuming the ExecutionContext has been cloned as stated above, the cancellation token within the execution context can be set within each data event to a CreateLinkedCancellationToken of the http cancellation token and subscription cancellation token.

Note: Unlike the document executer, upon an OperationCancelledException, the code should not `throw;` back to the observer source, but rather should produce a simple execution result with a 'operation cancelled' message.  This may happen under normal circumstances if a disconnection or stop request happens exactly at the same time that the event source sends data.  Such an event should not throw back to the event stream source.

## 8. The RequestServices property is set to null after the initial request by the subscription execution strategy

While this is good in practice, and works as intended, it seems to be flawed in design.  It is not the job of the subscription execution engine to know what the lifetime of the RequestServices property is or to manage it.

Consider that it is only because we changed the implementation within the server project to create a scope for the request that we wanted to clear it at all.  The change in the server project was correct, but fixing a side-effect within the GraphQL.NET project seems incorrect.

It is certainly possible to execute the subscription (for its whole lifetime) with the RequestServices property of the http context.  It is not disposed of until the http connection is broken.  It may not be practical for some DI-based frameworks like EF, but it's still a valid configuration.

Note that the RequestServices property is currently not cleared for field resolvers executed when data from the event stream is resolved.

Suggestion 1: Do not clear the RequestServices property.  If it is used after the initial request, an ObjectDisposedException will occur from the DI provider (since the server project will have disposed of the scope by then).  Consequence is that there is an unneeded reference to the service provider hanging around for the lifetime of the subscription, even if it is disposed properly.  (I would assume that the DI provider would clear its managed resources properly upon disposal and we need not worry about this.)

Suggestion 2: We could have ExecutionContext hold a reference to the ExecutionOptions instance that configured it, and so the server project can set ExecutionOptions.RequestServices to null at the appropriate time, which would effectively set all lingering ExecutionContext and ReadonlyResolveFieldContext instances to have a null RequestServices property also.  However, this probably has other consequences, like preventing a document listener from setting RequestServices, and preventing fixing issue 9 below.

## 10. There is no way to use a serial execution strategy for data events within a subscription

My GraphQL frameworks heavily rely on scoped services and serial execution, as the scoped services (e.g. Entity Framework) do not support multi-threaded use.  When I start using subscriptions shortly, I would very much prefer to have the data events' node trees executed serially with RequestServices set to a new service scope for the duration of the data event only.  In fact I would have to say that much of my code would probably not work unless that change could be made.

Suggestion 1: Provide a single class SubscriptionExecutionStrategy with an argument in the constructor to specify serial or parallel execution.

Suggestion 2: Provide two classes, ParallelSubscriptionExecutionStrategy and SerialSubscriptionExecutionStrategy.

In either case, a user can override one of the methods within the strategy to create a service scope and change the context's RequestServices property during a data event.  Perhaps within MicrosoftDI we provide a ScopedSubscriptionExecutionStrategy implementations.

## 11. Output extensions are not returned for data events

Suggestion: Return extensions, if any, along with the response

## 12. Metrics may be captured but not returned on data events

Suggestion 1: Disable metrics for all data events (set context to Metrics.None or similar).

Suggestion 2: Perform metrics on data events same as a document executer would.  It is up to the server project to "EnrichWithApolloTracing" on each event if desired.  (Tricky because the context does not know if ExecutionOptions.UseMetrics was set to true or false)

Suggestion 3: Provide a way to configure between the two suggestions above, perhaps a constructor argument

## 13. SubscriptionExecutionResult is somewhat unnecessary and requires a cast to use

Implementations must cast the execution result from the DocumentExecuter to SubscriptionExecutionResult to be able to retrieve the Streams property.

Suggestion: Move the Streams property from SubscriptionExecutionResult to ExecutionResult - #3024 

Suggestion 2: Leave as-is.

**Comment by Shane32** [comment]
@sungam3r Please review and provide thoughts.  I am in the middle of rewriting SubscriptionExecutionStrategy and ran into so many issues with the existing codebase that I wanted you to look over the issues before I made too many changes.

**Comment by Shane32** [comment]
Please note that I will be writing extensive tests for the new SubscriptionExecutionStrategy implementation(s).  Whatever we decide, it will be rock solid.

**Comment by sungam3r** [comment]
I don't use subscriptions and know basic things about implementation. It is difficult for me to answer all suggestions. I am guided by what I know. Do not even understand the whole picture I can make the review of individual parts. Each of your suggestion has justifications so let's go on.

**Comment by sungam3r** [comment]
> Suggestion 1: Do not clear the RequestServices property. If it is used after the initial request, an ObjectDisposedException will occur from the DI provider (since the server project will have disposed of the scope by then). **Consequence is that there is an unneeded reference to the service provider hanging around for the lifetime of the subscription, even if it is disposed properly. (I would assume that the DI provider would clear its managed resources properly upon disposal and we need not worry about this.)**

After provider was disposed:
![изображение](https://user-images.githubusercontent.com/21261007/159589674-1d778415-4fb1-4413-8ada-6a8ab5185c9f.png)

It seems that it holds the whole resolved graph in memory after beeng disposed.

**Comment by Shane32** [comment]
We can solve that easy in the server project with a wrapper around the service provider instance, which would also provide a meaningful error message if someone tried to access the service provider. 

However, I think this is the wrong answer because either all executions should have a scope, or none should. So it should really be handled by a scoped execution strategy. And if you don’t need a scoped service provider then all executions can use the root service provider. Better either way.

**Comment by sungam3r** [comment]
So? What is the plan?

**Comment by Shane32** [comment]
I'm planning to write a scoped subscription execution strategy in the MicrosoftDI project after #3004 is merged, and remove the code that creates the scope from the server project.

**Comment by Shane32** [comment]
That will be a breaking change of course.  I don't have a good answer for how to do everything without a breaking change here.

However, already it will be that people have to change the execution strategy in use for the next version of GraphQL.NET since the old nuget package will have been deleted including the SubscriptionDocumentExecuter and so on.  I plan on updating the notes we have already written in the migration document to cover the added ScopedSubscriptionExecutionStrategy class.

**Comment by sungam3r** [comment]
ok

**Comment by sungam3r** [comment]
> Suggestion: Assuming the ExecutionContext has been cloned as stated above, the cancellation token within the execution context can be set within each data event to a **CreateLinkedCancellationToken** of the http cancellation token and subscription cancellation token.

No linked token in #3004?

**Comment by Shane32** [comment]
No.  The subscription lives on its own until disposed, and the original execution context's cancellation token is discarded.  It is the responsibility of the server project to disconnect the subscription when the http context is closed, properly propagating the cancellation request through to the execution and also disconnecting from the source.  If we use a linked cancellation token but the server project does not dispose of the subscription, the observable will continue to send events to a dead observer.  So it is necessary for the server to dispose of the subscription.

From another viewpoint, the original request has been completed, and it is not appropriate to monitor the cancellation token any more, since it may not be relevant.  When the observable is subscribed, it should live until it is disposed.  That's how it is programmed now.

This may be part of the root of the problems that on user had, where they had memory leaks they could not trace until we propagated disposal properly throughout the server project.

**Comment by Shane32** [comment]
All issues fixed in #3004
