### ISSUE TITLE
Where is the CamelCaseAttribute?

### ISSUE THREAD

**Issue by justinmchase** [graphql-dotnet/graphql-dotnet#3005]
## Summary

What package / namespace do I need to import to get the `[CamelCase]` attribute to resolve?

I'm looking at the [documentation](https://graphql-dotnet.github.io/docs/getting-started/schema-types) about enums and it shows an eum like this:

```cs
[CamelCase]
public enum CamelCaseEnum
{
    FirstValue,
    SecondValue
}
```

But when I try to do this in my project it gives an error saying the Type cannot be found.

![Screen Shot 2022-03-09 at 2 05 15 PM](https://user-images.githubusercontent.com/10974/157524815-82667623-d161-4e3b-ac5e-1836751518c8.png)

It would be very helpful if documentation like this had at the top of the page the complete list of `using` statements needed and the complete list of packages needed to make the examples work.

## Relevant information

```xml
    <PackageReference Include="GraphQL.Server.All" Version="5.2.0" />
```

### Environment (if relevant)

Mac, net6.0, vscode

**Comment by Shane32** [comment]
GraphQL.Types

See bottom of this file:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Scalars/EnumerationGraphType.cs

If it's not there, also include a nuget reference to GraphQL 4.7.1, as GraphQL Server 5.2.0 only references GraphQL 4.6.1

**Comment by justinmchase** [comment]
That must be the issue, because the Type does not exist in the namespace when I just add a using. Will it actually work if I mix the versions like that?

**Comment by justinmchase** [comment]
Lol, its camelCasing the Keys and the Values. 🤦 

Is there a way to alias the keys?

**Comment by Shane32** [comment]
GraphQL 4.x is fully backwards compatible with prior 4.x versions.  In this case GraphQL Server requires a minimum of 4.6.1 but you may use any newer version of GraphQL 4.x.  Most likely GraphQL.DataLoader and GraphQL.SystemTextJson (or GraphQL.NewtonsoftJson) are also referenced by GraphQL.Server.All.  You can load the latest versions of those if you like as well for the newest updates.

When GraphQL 5.0 is released next month, you will need a new version of GraphQL Server to use with it.

**Comment by Shane32** [comment]
> Lol, its camelCasing the Keys and the Values. 🤦
> 
> Is there a way to alias the keys?

Not sure exactly what you mean here.  I would have thought it would essentially make a schema like this:

```gql
enum Episode {
  newhope
  empire
  jedi
}
```
rather than uppercase... of course it should still map to `Episode.Jedi`, etc.

**Comment by Shane32** [comment]
I think the documentation is pretty clear as to your options for changing case.  You can pretty much define an enumeration however you want if you use the second example in the documentation -- different names, different case, whatever.

```cs
public enum Episode
{
    NewHope,
    EmpireStrikesBack,
    ReturnOfTheJedi
}
public class EpisodeEnum : EnumerationGraphType
{
    public EpisodeEnum()
    {
        Name = "Episode";
        Description = "One of the films in the Star Wars Trilogy.";
        AddValue("new_hope", "Released in 1977.", Episode.NewHope);
        AddValue("empireStrikesBack", "Released in 1980.", Episode.EmpireStrikesBack);
        AddValue("JEDI", "Released in 1983.", Episode.ReturnOfTheJedi);
    }
}
```

**Comment by Shane32** [comment]
You can map one key to another value too.  If you don't use the `EnumerationGraphType<T>` version, you can do whatever you want.

```cs
AddValue("new_hope", "description", Episode.ReturnOfTheJedi);
```

**Comment by Shane32** [comment]
In the new version you can just do this:

```cs
public enum Episode {
    [Name("newHope")]
    ANewHope,
    [Name("empire_strikes_back")]
    TheEmpireStrikesBack,
    [Name("JEDI")]
    ReturnOfTheJedi,
}
```

But not yet.

**Comment by justinmchase** [comment]
Sorry, I am definitely having some issues here but working through them... I think one problem I was having was, coming from TypeScript and having string enums there and then seeing this in the Altair UI confused me:

![Screen Shot 2022-03-09 at 3 00 27 PM](https://user-images.githubusercontent.com/10974/157535271-6206f1d4-c5dd-4881-a152-0569e167d1eb.png)

It looks like a `key: value` enum where I forgot that in gql the key and the value are the same. So your snippet there helped me I was trying to make a "snake case" enum and was setting the key to one thing and the value to another and there was no mapping back for the enum. So changing the value to jsut be the enum value helped.

The other thing throwing me off is it seems like one of my other types has a field of type Punctuation and it seems like its causing a default type to get built _before_ my enum type is registered and so I had to make a change there:

```cs
public record Hello(string Name, Punctuation Punctuation, string Greeting);

public class HelloType : ObjectGraphType<Hello>
{
  public HelloType()
  {
    Name = "Hello";
    Description = "A hello response object.";

    Field(d => d.Name, nullable: false).Description("The name of the greeting");

    // This causes an error:
    // "Unable to register GraphType 'PunctuationEnum' with the name 'Punctuation'...
    Field(d => d.Punctuation, nullable: false).Description("The type of puncutation for the greeting");

    Field(d => d.Greeting, nullable: false).Description("The greeting");
  }
}
```

Swapping that field to be declared like this fixes it:
```cs
Field<PunctuationEnum>("punctuation", "The type of puncutation for the greeting");
```

So that was very confusing to me...

It seems like I should put a (TypeMap)[https://graphql-dotnet.github.io/docs/getting-started/schema-types#type-mapping] on the Punctuation enum... but again, it seems like that type is not in any known assembly or namespaces, struggling to find that and try it.

**Comment by justinmchase** [comment]
But that solved it for me, thanks and sorry for the stupid questions, I'm full of them!

Also, here's my snake case enum in case anyone wants to know:
```cs
public class SnakeCaseEnumerationGraphType<TEnum> : EnumerationGraphType where TEnum : Enum
{
  //
  // Summary:
  //     Initializes a new instance of the GraphQL.Types.EnumerationGraphType class.
  public EnumGraphType()
  {
    var type = typeof(TEnum);
    var enumerable =
      from name in Enum.GetNames(type)
      select (name, member: type.GetMember(name, BindingFlags.DeclaredOnly | BindingFlags.Static | BindingFlags.Public).First()) into e
      select (e.name, e.member.Description(), e.member.ObsoleteMessage());

    this.Name = type.Name.ToPascalCase();
    this.Description ??= typeof(TEnum).Description();
    this.DeprecationReason ??= typeof(TEnum).ObsoleteMessage();

    foreach (var (name, description, deprecationReason) in enumerable)
    {
      var n = name.ToSnakeCase();
      var v = Enum.Parse(type, name);
      this.AddValue(new EnumValueDefinition
      {
        Name = n,
        Value = v,
        Description = description,
        DeprecationReason = deprecationReason,
        // Metadata
      });
    }
  }
}
```
```cs
public static class StringExtensions
{
  public static string ToSnakeCase(this string value)
  {
    var sb = new StringBuilder();
    for (var i = 0; i < value.Length; i++)
    {
      var c = value[i];
      if (char.IsUpper(c) && i > 0)
      {
        _ = sb.Append('_');
      }

      _ = sb.Append(char.ToLower(c));
    }

    return sb.ToString();
  }
}
```

**Comment by Shane32** [comment]
In your schema's constructor, if you register a type mapping for your enum type, then `Field(x => x.Punctuation)` will work properly.

```cs
this.RegisterTypeMapping<Punctuation, PunctuationGraphType>();
```

Or you can use an `IGraphQLBuilder` extension in your `Startup.cs` to auto-register all graph type mappings found in the specified assembly.  Assuming you are using the currently recommended DI approach, this should work just as well.

```cs
services.AddGraphQL()
    .AddClrTypeMappings();
```

https://graphql-dotnet.github.io/docs/getting-started/schema-types#type-mapping

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#dependency-injection-registration-helpers

**Comment by Shane32** [comment]
You can even change DI so that all enumeration types automatically use snake case:

```cs
services.AddSingleton(typeof(EnumerationGraphType<>), typeof(SnakeCaseEnumerationType<>));
```

**Comment by Shane32** [comment]
Then you don't need to create a `PunctuationGraphType` at all, and `Field(x => x.Punctuation)` will create a punctuation type for you.

**Comment by justinmchase** [comment]
Close, it works but since the `EmuerationGraphType<>` logic is in the constructor and I have to derive from it it still runs and adds all of the all caps values to the enum...

**Comment by justinmchase** [comment]
I'm using this in my Startup:

```
gql.AddGraphTypes(assembly);
```

Is `.AddClrTypeMappings()` better?

**Comment by Shane32** [comment]
AddGraphTypes registers the types in DI -- but AddClrTypeMappings adds the mappings from the CLR type to the Graph Type.

Basically, you need both.

**Comment by Shane32** [comment]
Oh, right.  Can't you just inherit from `EnumerationGraphType<>` and override the one method `ChangeEnumCase` like it shows in the documentation?

```cs
public class SnakeCaseEnumerationGraphType<T> : EnumerationGraphType<T> where T : Enum
{
    protected override string ChangeEnumCase(string val) => val.ToSnakeCase();
}
```

**Comment by justinmchase** [comment]
I can indeed do that! Combined with the global registration it works great.

That was the first thing I tried but the duplicate registration and the Altair UI threw me off and I'm an idiot apparently 😝
