### ISSUE TITLE
Release v5

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3009]
@sungam3r There is only 2 weeks left until April, and I’d like to release v5 promptly at that time. What goals, issues or PRs do you wish to accomplish before then?

In general, I would like to finish the updated subscription support here and update the server project, where it would be nice to support graphql-transport-ws. I may also consider additional work towards #2893 

My todo:
- [x] #3004 
- [x] #3024
- [x] #3025
- [x] #3022
- [x] Update subscription support in a new server project

**Comment by sungam3r** [comment]
I want to rewrite SchemaPrinter and federation. I stopped in the middle of work.

**Comment by Shane32** [comment]
@sungam3r I would like to release v5 now; I do not mind if v6 is close behind.  I looked through the open issues and PRs and do not see anything else that I would like to add to v5.  Our migration document is comprehensive with many examples, although perhaps not orderly.  Note that I will need to release parser v8 first.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/parser/issues/206 ?

**Comment by Shane32** [comment]
This is an open-ended definition.  I'm not sure what you want me to do.  The specification is hundreds of pages long.  Typically you keep up with revisions to the spec, not me.  Even the list of PRs for the changelog to the spec is a couple pages.

https://github.com/graphql/graphql-spec/blob/main/changelogs/October2021.md

The only feature I really wanted to add for v5 is oneOf support, which is a draft spec and hasn't been finalized, and I don't have time to do even if it was merged.

You can review the spec and update it for v6 if there are any issues, which as you say will be released soon anyway.

**Comment by Shane32** [comment]
Any other comments here @sungam3r before I issue a release?

**Comment by sungam3r** [comment]
Let's go on with v8/v5 releases. Recently I have no enough time to do everything I want. I do not want to delay progress.

**Comment by Shane32** [comment]
GraphQL 4.8 and Server 5.2.1 have been published to nuget which include restrictions on their dependencies so that Server is only using 4.6.1 or newer 4.x of GraphQL, and GraphQL is only using Parser 7.2.0 or newer 7.x.

GraphQL Parser 8.0.0 has been published.  GraphQL.NET dependency on parser has been updated to 8.0.0.

GraphQL `develop` has been merged into `master`, so from now on all changes will go into `master` for 5.x

GraphQL 5.0.0 released

@sungam3r Please update release notes as you see fit.

**Comment by sungam3r** [comment]
Thanks.
