### ISSUE TITLE
How load object with collection

### ISSUE THREAD

**Issue by janskoruba** [graphql-dotnet/graphql-dotnet#301]
I want to get object user which has following structure:

```
{
id: int
userName: string
friends: [
id: int
userName: string
]
}
```

I want to get this object from database using Entity Framework where I create the command which prepare the user object with colletion of friends.

How can I pass these data with friends collection to GraphQLType?

I have tried this:
```
public class UserType : ObjectGraphType<User>
    {
        public UserType()
        {
            Field(x => x.Id).Description("The Id of the user.");
            Field(x => x.UserName).Description("The userName of the user.");

            Field(x => x.Friends, true).Description("The friends of the user");
        }        
    }
```

Following query:
```
Field<ListGraphType<UserType>>(
                "users",
                resolve: context => _userRepository.GetUsers()
            );
```

This method return prepared object with friends collection - `_userRepository.GetUsers()`

But this doesn't work - I get error message: 

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=The GraphQL type for Field: 'Friends' on parent type: 'UserType' could not be derived implicitly. 

  Source=<Cannot evaluate the exception source>

Inner Exception 1:
ArgumentOutOfRangeException: The type: ICollection`1 cannot be coerced effectively to a GraphQL type

```

Please, can you help me - how can I map my object with collection (with friends) to my UserType?

Thank you

**Comment by jquense** [comment]
In your example the field `Friends` isn't a known scalar value (string, int, date, etc) so We can't _infer_ the graphType for `Friends`. In those cases you need to tell it what type it is, using one of the (many) overloads

```
Field(
  name: "Friends",
  description: "The friends of the user",
  resolve: context => context.Source.Friends);
```

**Comment by jquense** [comment]
you'll need to write a `FriendGraphType` btw, which is probably a `ObjectGraphType<Friend>`

**Comment by joemcbride** [comment]
Here's how it is done in the Star Wars sample. https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.StarWars/Types/DroidType.cs#L15-L18

**Comment by janskoruba** [comment]
I am excited :) it works like a charm

I am wondering about creating the queries to the database:

If I've use the query above "users" where this query returns the  list of users with friends but if I've created following query:

```
{
   users{
    id
  }
}
```

This query get users with friends from database and in the memory get only users with id's.
Is it good approach? 
I am wondering how optimize the finally query to database according the query from the client like this:
`SELECT id FROM dbo.[User]`

What do you think about that?

Thank you.

**Comment by jquense** [comment]
@janskoruba there isn't one specific way to do that. I'd do a quick search of the issue tracker here for the current conversations happening around that. Personally tho i've found that the ORM (we've used the telerik Data Access which is mostly an Entity clone) does a pretty good job of optimizing and batching as it is.

**Comment by janskoruba** [comment]
Thank you very much guys for your quick reply. I appreciate it. I will continue discover this awesome implementation of GraphQL. :)

**Comment by prabaprakash** [comment]
https://gist.github.com/prabaprakash/eaaf86ad27b343c10615182290d21bdd
