### ISSUE TITLE
Question - Nested async resolvers

### ISSUE THREAD

**Issue by jptissot** [graphql-dotnet/graphql-dotnet#3017]
## Summary

Hi, I am building a SAAS with many different features that can be enabled / disabled based on our clients needs. I am using GraphQL to power our api's and it has been working pretty well but the schema is growing in size. To cleanup the schema, I am trying to setup a hierarchy per feature / table.

Here is an example query: 

```graphql
query MyQuery {
  myFeature1 {
    table1 {
        nodes { //async resolver here
            id
            name
        }
        aggregates { //async resolver here
            nameGroupBy
            _count
        }
    }
  }
  myFeature2 {
    table2 {
        nodes { //async resolver here
            id
            name
        }
        aggregates { //async resolver here
            nameGroupBy
            _count
        }
    }
  }
}

```

Right now, everything gets added at the top level using a naming convention and it works well. But as soon as I try to add an ObjectGraphType to group things by features or tables, the bottom resolvers are no longer being called. 

I am trying to add the fields like this: 
```c#
var definitionObject = ...; // object that contains table definitions

query.AddField(new FeatureField("Feature1", definitionObject));
query.AddField(new FeatureField("Feature2", definitionObject2));
```
And then inside the `FeatureField`, we have custom code that uses the `definitionObject` and creates fields for each tables, which in turns adds `nodes` and `aggregates` fields.

The nodes (and aggregates) field have the async resolver that builds SQL based and queries the database. These work when added at the top level but are never triggered when nested.

My question is this: is it possible to write resolvers for the first two levels that simply loop through the selected fields and execute their resolvers top down ?

### Environment (if relevant)

Version 4.7.1, .NET 5.0

**Comment by Shane32** [comment]
Can you explain further about the field resolvers are not being called? What type of result are you seeing in response to a request? Have you ensured that the parent resolvers return an object?

In my code I’ll write `context => new object()` as the top level resolver to be sure the nested resolvers execute. It can also be used as security — for example on an admin subgraph, you could write `context => context.UserContext[“IsAdmin”] == true`

**Comment by jptissot** [comment]
This feels silly, all I needed was to return `new object()` from the top level context and everything else started working. Thank you !
