### ISSUE TITLE
Generic sanitize html string input

### ISSUE THREAD

**Issue by danmac03** [graphql-dotnet/graphql-dotnet#3020]
Hi,

I'm looking for the best way to generalize the html sanitize input concept without having to do it inside each mutation once I cast my input into my input object. What would be the best way? Tried adding a validation rule that sanitized the input and then trying to compare it with the input but my sanitizer is to hard and make it fail all the time since it's very sensible. What would be the best approch to do something like that? Is it possible to modify my field value inside the validation rules?

Thank you very much,
Dan

**Comment by Shane32** [comment]
If you are trying to sanitize HTML fields, I would write a custom scalar - e.g. `HtmlGraphType` - which would perform sanitization to remove javascript or whatever before it hits the resolvers.  Errors would be thrown in the validation stage, although generally sanitization will occur twice - once when it is validated and once when it is deserialized - depending on how you write the scalar.

If you are trying to sanitize string fields to be sure there is no HTML in them, I would write a custom scalar to replace StringGraphType, which will take effect for all uses of StringGraphType in your codebase.

**Comment by sungam3r** [comment]
Closed as answered.
