### ISSUE TITLE
Dictionary is appropiate to store fields

### ISSUE THREAD

**Issue by rohitlodha** [graphql-dotnet/graphql-dotnet#303]
Usually a dictionary is considered to store fields with key as its name. In class ComplexGraphType<TSourceType> I think we should use a dictionary with Name of FieldType immutable. Are there any advantages using a list?

**Comment by joemcbride** [comment]
What use case do you have where a dictionary would be preferable?  So far the list as been working fairly well.  There may be one or two places in the code where doing a dictionary lookup could be faster.  Do you have something specific that you're seeing an issue with or are you just commenting in general?

**Comment by joemcbride** [comment]
I'm going to close this. Feel free to re-open with more context.
