### ISSUE TITLE
Nested Fragments

### ISSUE THREAD

**Issue by ansulgoenka1** [graphql-dotnet/graphql-dotnet#3030]
## Summary

When I am trying to pass a query that contains nested fragments, the DocumentExecutor throws this Error: "Error executing the document. The given key was not present in the dictionary."

## Relevant information

Query: 

                fragment nameFragment on Dog {
                    name
                    ... nestedNameFragment
                }

                fragment nestedNameFragment on Dog {
                    name
                }

                {
                    dog {
                        name
                        ... nameFragment
                    }
                }

Is this query correct? If not how do we use nested fragments here or is this a bug? I could not find any documentation on this

Any help would be greatly appreciated

**Comment by sungam3r** [comment]
I'll try to reproduce it.

**Comment by ansulgoenka1** [comment]
I am using the 5.00 (preview) version.

I was debugging the code and found that document.Definition (after using DocumentBuilder) contains errors for this query. When we use DocumentExecutor and set Complexity Configuration, ComplexityAnalyzer Line 60 throws this error when it iterates over the document.Definition (probably because it cannot find error in that switch condition)

**Comment by ansulgoenka1** [comment]
Your test suite passes this test as it uses DocumentValidator

**Comment by sungam3r** [comment]
>  document.Definition (after using DocumentBuilder) **contains errors** for this query

I don't understand. How can GraphQL AST contain _errors_? Could you please post PR with test repro?

**Comment by ansulgoenka1** [comment]
It can also be reproduced by debugging all_fragment_names_are_used in NoUsedFragmentTests

![image](https://user-images.githubusercontent.com/102316754/160473916-d58d1dae-47fb-4f16-ae65-c8b43bb96fe3.png)

**Comment by sungam3r** [comment]
See linked PR, it's just a displayed text for debugger.

**Comment by sungam3r** [comment]
@ansulgoenka1 

I'm interested in that:
> DocumentExecutor throws this Error: "Error executing the document. The given key was not present in the dictionary."

Could you write a repro after #3032 merged?

**Comment by ansulgoenka1** [comment]
If you replace DocumentValidator with DocumentExecutor in ValidationTestBase line 89:

private ExecutionResult Validate(string query, ISchema schema, IEnumerable<IValidationRule> rules, Inputs variables)
        {
            var validator = new DocumentExecuter();
            return validator.ExecuteAsync(new ExecutionOptions
            {
                Schema = schema,
                ValidationRules = rules,
                ComplexityConfiguration = new GraphQL.Validation.Complexity.ComplexityConfiguration() { MaxDepth = 10 },
                Query = query,
                Variables = variables
            }).Result;
        }
        
You can reproduce this error for the above-mentioned test.

I will try to reproduce it again after #3032 is merged

**Comment by sungam3r** [comment]
Reproduced

**Comment by sungam3r** [comment]
@ansulgoenka1 Thanks for the repro. I need to think about fix. I understand what is happening and why.

**Comment by sungam3r** [comment]
@ansulgoenka1 Fix will be published in v5.
