### ISSUE TITLE
GraphQL.NET: How to find the full field path using IValidationRule

### ISSUE THREAD

**Issue by ghstahl** [graphql-dotnet/graphql-dotnet#304]
I don't know if you guys follow your tag graphql-dotnet on stackoverflow, being that there are exactly 2 questions including mine, I am going to double post it here.
http://stackoverflow.com/questions/42931516/graphql-net-how-to-find-the-full-field-path-using-ivalidationrule

Using the documented RequiresAuthValidationRule implementation;

[learn](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md)

There is an example that checks if a field has certain permission and if a user can access that field.

_.Match<Field>(fieldAst =>{...})

It looks like the GraphQL engine is walking a tree and calling the IValidationRule.Validate(...) at each node.

What is the best way to know what the full path of the field is.

The star wars example;  
[StarWars in Getting Started](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md)

i.e. i want to know that the field is human->friends->name  when I am at the 'name' node.

From what I can see I only have visibility to the current field node and it children, but not its parents.

I am reusing my GraphTypes everywhere so hardcoding AddPermission is out, as allowing access to a field depends on the query context.  In my case the context is the entire path to the field.

**Comment by joemcbride** [comment]
I believe `ValidationContext.TypeInfo.GetLastType()` should be the parent.  `ValidationContext.TypeInfo` has a lot of context for where you are in the graph.

**Comment by joemcbride** [comment]
And I'm following the SO tag now.  ;]

**Comment by ghstahl** [comment]
```
_.Match<Field>(fieldAst =>
                {
                    var fieldDef = context.TypeInfo.GetFieldDef();
                    var parentType = context.TypeInfo.GetParentType();
                    var name = fieldAst.Name;
                });
```
Ok, so you did have a parent.
Next question, is there a more efficient way  for me to get the path, as I would have to traverse up on each of the iterations.   I was hoping to build up the path as I go.

Is the lifecycle of my ValidationRule class  something that I can count on.  It seems that you keep it around.  I was hoping I could trigger off of the _.Match<Operation>() as a start, and if I see another one, I start over.

**Comment by joemcbride** [comment]
Yes you should be able to count on the order.  The [`DocumentValidator`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/DocumentValidator.cs#L54) uses a [`BasicVisitor`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/BasicVisitor.cs) to traverse all of the `INode` in the `Document`.

**Comment by joemcbride** [comment]
Looking at the code for [`TypeInfo`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/TypeInfo.cs#L64) it pushes the parent type when it hits a `SelectionSet`.  So you should be able to add a `.Match<SelectionSet>` and keep a list of parent types yourself.  You can provide both a `enter` and a `leave` actions, so you can remove the type from you list on the `leave` action.

**Comment by joemcbride** [comment]
Going to go ahead and close this. Feel free to reopen if you have additional questions.
