### ISSUE TITLE
GetRecursiveVariables returns null

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3049]
GetRecursiveVariables returns null instead of an empty list; this should be noted in the migration document.

**Comment by sungam3r** [comment]
It was one of my changes.

**Comment by Shane32** [comment]
No big deal. It broke my code for a few seconds - simple to fix. I was surprised how many issues I ran into, and pleasantly surprised how they were all (with this minor exception) well documented. It certainly helped the transition significantly.
