### ISSUE TITLE
Cannot pass query enum arguments in variables

### ISSUE THREAD

**Issue by schlaup** [graphql-dotnet/graphql-dotnet#305]
A query like the following is not working: (where AnimalType is an EnumerationGraphType)

```
query getAnimals($type: AnimalType)
{
  animals(type: $type) {
    name
  }
}
```

with variables:

```
{
  "type": "Dog"
}
```

However, without using variables it is working:

```
query getAnimals
{
  animals(type: Dog) {
    name
  }
}
```

I found an issue regarding converting strings to enums for mutations. (Test: "mutation_input_from_variables") I seems that the issue and fix only was for mutations and not for queries.

**Comment by schlaup** [comment]
I forgot to include the error message:

```
{
  "errors": [
    {
      "message": "Variable \"$type\" of type \"AnimalType\" used in position expecting type \"AnimalType!\".",
      "locations": [
        {
          "Line": 1,
          "Column": 24
        },
        {
          "Line": 3,
          "Column": 23
        }
      ]
    }
  ]
}
```

**Comment by joemcbride** [comment]
Going to close this one as the same issue as #309
