### ISSUE TITLE
Enum types where the name ends with "Type" cannot be resolved

### ISSUE THREAD

**Issue by arnaudleclerc** [graphql-dotnet/graphql-dotnet#3055]
## Description

When executing a query via `Schema.ExecuteQueryAsync` querying a type with one field being an enum whose name ends with "Type", the field cannot be resolved.

I currently use an Azure Function where I added a GraphQL API. The type definitions define two types and a query. One of those types is an enum named "ProjectType". The execution of a GraphQL query goes like this : 

```
public class GraphQLServer
{
    private readonly string _typeDefinition = @"
        type Project {
            id: ID,
            status: ProjectType
        }

        enum ProjectType {
            Completed,
            Failed
        }

        type Query {
            projects: [Project]
        }
    ";

    public IServiceProvider ServiceProvider { get; set; }

    public async Task<string> ExecuteQueryAsync(string query)
    {
        var schema = Schema.For(_typeDefinition, builder =>
        {
            builder.ServiceProvider = ServiceProvider;

            builder.Types.Include<GraphQLQuery>("Query");
            builder.Types.Include<ProjectType>();
        });

        return await schema.ExecuteAsync(new GraphQLSerializer(), options => options.Query = query);
    }
}
```

When this is called, an error comes back : 

```
{
    "errors": [
        {
            "message": "Error trying to resolve field 'status'.",
            "locations": [
                {
                    "line": 1,
                    "column": 12
                }
            ],
            "path": [
                "projects",
                0,
                "status"
            ],
            "extensions": {
                "code": "INVALID_OPERATION",
                "codes": [
                    "INVALID_OPERATION"
                ]
            }
        }
    ],
    "data": {
        "projects": [
            {
                "status": null
            }
        ]
    }
}
```

Weirdly enough, if I rename the enum to anything **not finishing with 'Type'**, this works.

If I include the enum using a name, this works : 

```
builder.Types.Include<ProjectType>("ProjectType");
```

You can find a repo reproducing this issue here : https://github.com/arnaudleclerc/graphql-azurefunction

### Steps to reproduce

- Use a type definition where an enum has a name finishing with 'Type'.
- Execute a query to retrieve the field with the enum type.

### Expected result

Field should be resolved correctly.

### Actual result

Field cannot be resolved with error : Error trying to resolve field '<field>'

### Environment

- .NET 6
- Azure Function V4
- GraphQL.Newtonsoft 5.0.0. I also had the same issue using 4.7.1.

**Comment by sungam3r** [comment]
It's by design
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/TypeExtensions.cs#L69

Convention used is to trim _Type_ and _GraphType_ if no explicit name was provided into `Include`.

**Comment by sungam3r** [comment]
Either use `Include` overload with name or mark enum with `GraphQLMetadataAttribute`.

**Comment by arnaudleclerc** [comment]
Thank you for the explanation! I'll use the overload to define the name 👍
