### ISSUE TITLE
GraphQL.Server.Core dependencies

### ISSUE THREAD

**Issue by mariusbancila** [graphql-dotnet/graphql-dotnet#3068]
`GraphQL.Server.Core` 5.2.0 has the following dependencies:
```
GraphQL.DataLoader (>= 4.6.1)
GraphQL.SystemReactive (>=4.6.1)
Microsoft.Extensions.Options (>= 3.1.0)
```

I have migrated from version 4.x to 5.0, which means I also updated the `GraphQL.DataLoader` to version 5.0.0.

How, there is a new version of `GraphQL.Server.Core`  5.2.1 that has the following dependencies:
```
GraphQL.DataLoader (>= 4.6.1 && < 5.0.0)
GraphQL.SystemReactive (>=4.6.1 && < 5.0.0)
Microsoft.Extensions.Options (>= 3.1.0)
```

That leads to errors updating the package:
```
MyProj.GraphQL.Host -> MyProj.GraphQL.Api -> GraphQL.DataLoader (>= 5.0.0) 
MyProj.GraphQL.Host -> GraphQL.Server.Core 5.2.1 -> GraphQL.DataLoader (>= 4.6.1 && < 5.0.0).
```

Why is `GraphQL.Server.Core` 5.2.1 depending on `GraphQL.DataLoader` < 5.0.0? What am I missing here?

**Comment by Shane32** [comment]
It’s saying that 5.2.1 of the server project (and also prior versions) are incompatible with GraphQL v5 and listing the two conflicts

**Comment by mariusbancila** [comment]
I understand the messages. That's not the issue. Why is GraphQL.Server.Core 5.x incompatible with GraphQL 5.x? This is confusing, you know. (Especially since 5.2.0 didn't have this problem.)

**Comment by Shane32** [comment]
GraphQL Server 5.2.0 will not work with GraphQL 5.x either.  It simply was not annotated as such.  All GraphQL Server 5.x versions will only work with GraphQL 4.x versions.

Yes it is confusing.  I've long recommended that we unify the version numbers so it is more obvious which versions work together and which do not.

GraphQL 6 may be released within a relatively short time frame.  If and when GraphQL Server 6 is released, it will likely work for both GraphQL 5 and GraphQL 6, thereby unifying the version numbers at that time.

As of now you may switch to GraphQL.AspNetCore3 to fill in for the server project.  It has more features, supports the new websocket protocol, more test coverage, easier to use, more bug fixes, better documentation, more samples, and so on.

https://github.com/Shane32/GraphQL.AspNetCore3

**Comment by mariusbancila** [comment]
All right, thanks for clarifying it! 🙋‍♂️
