### ISSUE TITLE
How to: Partial cache API response using an approach similar to  DataLoader-style batching

### ISSUE THREAD

**Issue by pravinhabbu4u** [graphql-dotnet/graphql-dotnet#307]
At present we have a .net core Orchestration up and running on around 50 backend Rest APIs successfully. I am working on implementing a feature that would reduce some backend calls to an API in case similar API call (identified by URL) was already made under current Orchestration request. It is more like doing a partial cache/ intra request cache and is mainly similar to graphql data loader. 

Do we have a similar package that would act like facebooks data loader package for graphql? My initial plan was to keep a list of API call and response in context under current request, however, this is not highly useful as all async calls are made by passing a copy of context in resolver methods.

**Comment by pravinhabbu4u** [comment]
Note: I do have a current implementation that is solving my problem of caching within a request (which is what I want). However, I would like to know if there is a unique way for it

**Comment by joemcbride** [comment]
We do not have a dataloader in this project yet, no.  See https://github.com/graphql-dotnet/graphql-dotnet/issues/264
