### ISSUE TITLE
There is no way to tell that authorization is required without a role or policy specified

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3076]
@sungam3r I messed up a bit in the last PR.  The ASP.NET Core `[Authorize]` attribute when specified without a role or policy indicates that the user should be authenticated (not a guest).  We should have matching functionality in GraphQL.

This means that the `RequiresAuthorization` extension method should return `true` when a field is marked with `[GraphQLAuthorize]`, which it does not now.

I suggest:
- Add a new extension method to indicate that the user must be authenticated.  For example, called `RequireAuthentication` or `WithAuthorization()`.
- Modify the attribute to call the above method when no policies or roles are specified
- Modify the `RequiresAuthorization` extension method to return `true` when the above method is called.  (breaking change from yesterday; not breaking from 5.0.0)

I would like to do this promptly, while GraphQL 5 is still new.  Hopefully release 5.1.1 (or 5.2.0) tomorrow with this change.

**Comment by sungam3r** [comment]
OK, go on, I'll review.

**Comment by Shane32** [comment]
Do you have a suggestion as to the exact implementation:

Option 1:
- add new metadata key like "Authorization__Required" which is set to `true` in this situation, like this:

```cs
public static bool RequiresAuthorization(this IProvideMetadata provider)
    => GetPolicies(provider)?.Count > 0 || GetRoles(provider)?.Count > 0 ||
        provider.GetMetadata<bool>(AUTHORIZE_KEY) ?? false;
```

Option 2:
- add an empty list to ROLE_KEY ("Authorization__Roles") and modify as follows:

```cs
public static bool RequiresAuthorization(this IProvideMetadata provider)
    => GetPolicies(provider)?.Count > 0 || GetRoles(provider) != null;
```

**Comment by Shane32** [comment]
Do you have a suggestion as to the name of the extension method to indicate that authorization is required?

Options:
- `Authorize()`
- `RequireAuthentication()`
- `RequireAuthorization()`

Based on some of my reading, it seems that technically I would think this is "requiring authentication", as it is just checking that authentication has occurred, versus "requiring authorization", indicating that a check of roles/policies are required.  But I'm not sure and everything else here is called authorization.  It is noteworthy that the ASP.NET Core attribute name is `[Authorize]` (even without roles or policies).

I vote for option 1: `.Authorize()` which seems to match `.AuthorizeWithPolicy(...)` and `.AuthorizeWithRole(...)` best.

**Comment by sungam3r** [comment]
I would not add new Authorization__Required key. So Option 2.

> I vote for option 1: .Authorize()

Agree.

**Comment by sungam3r** [comment]
Wait a bit. Option 1 with new metadata key seems reasonable now.

**Comment by Shane32** [comment]
I'll wait for your review of #3077 .  I'm willing to change it but it did seem reasonable.

**Comment by sungam3r** [comment]
> Based on some of my reading, it seems that technically I would think this is "requiring authentication", as it is just checking that authentication has occurred, versus "requiring authorization", indicating that a check of roles/policies are required. But I'm not sure and everything else here is called authorization. It is noteworthy that the ASP.NET Core attribute name is [Authorize] (even without roles or policies).

Agree about naming mismatch. Let's keep _Authorize_ term .
