### ISSUE TITLE
[Feature] Add AllowAnonymous metadata

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3078]
To finish adding authorization metadata to align with ASP.NET Core, I suggest adding the equivalent of the `[AllowAnonymous]` attribute to allow this behavior:

- When a field is marked to allow anonymous access, and the field is the only one in the selection set of a parent protected graph type, then access to the graph will be allowed.

Example schema:

```gql
type Query {
  hero: Person!
}

type Person {     # [Authorize("MyPolicy")]
  id: ID!         # [AllowAnonymous]
  name: String!
}
```

Now requests like this fail validation for an anonymous use:

```gql
{
  hero {
    id
    name
  }
}
```

But this passes:

```gql
{
  hero {
    id
  }
}
```

I suggest making this functionality only apply "one level deep".

For example, for this schema:

```gql
type Query {
  hero: Person!   # [Authorize]
}

type Person {
  id: ID!         # [AllowAnonymous]
  name: String!
}
```

Then this request would still fail, because AllowAnonymous only relaxes authentication definitions on Person, not on Query.

```gql
{
  hero {
    id
  }
}
```

This feature will allow these scenarios to work:

1. Mark the query type as requiring authentication, but allow anonymous access to `__type` and `__schema`.
2. Mark the query type as requiring authentication, but allow anonymous access to a 'login' graph for authentication services.

This should help to solve:
- https://github.com/graphql-dotnet/server/issues/549

My specific suggestions are:
- Add `.AllowAnonymous()` extension method which sets a `Authorization__AllowAnonymous` metadata key to `true`
- Add `.AllowingAnonymous()` extension method which returns a boolean from the key
- Add `AllowAnonymousAttribute` for fields only which calls `AllowAnonymous` on the field

**Comment by Shane32** [comment]
Note that the interpretation of the metadata is up to the implementation of the authorization library.  As such, perhaps the `AllowAnonymousAttribute` should be able to be set on anything (graphs, fields, query arguments, etc).  The authorization library could also have configuration options that change the behavior of what is described above.

**Comment by sungam3r** [comment]
> I suggest making this functionality only apply "one level deep".

😞 it is not a graphql design, it is asp net core controllers/actions design with only one level of nesting.

**Comment by sungam3r** [comment]
I agree that interpretation of attributes/metadata stored by them is outside of this repo but now it is necessary to think how to use that hierarchical structure of meta-information. And yes, all attributes should be able to be set on anything. I'm fine to add `.AllowAnonymous()` method and `AllowAnonymousAttribute`, sounds reasonable. `AllowingAnonymous` sound a bit odd. I would prefer `AllowsAnonymous` to align such naming with `RequiresAuthorization` though we will have two similar names - `AllowAnonymous` and `AllowsAnonymous`.

**Comment by Shane32** [comment]
What about IsAnonymousAllowed and IsAuthorizationRequired (deprecating RequiresAuthorization)? ( I dislike the similar names also. )

**Comment by sungam3r** [comment]
OK
