### ISSUE TITLE
Field resolves for a child fields should run in parallel?

### ISSUE THREAD

**Issue by pravinhabbu4u** [graphql-dotnet/graphql-dotnet#308]
Example: My application has a root field Customer. This is resolved using an API call which returns customer number & name.
{CustomerNo: "1"  Name:"abc xyz"}

I am adding a field in my graphql customer model as "CustomerPaymentHistory" which basically will be resolved at run time by calling another API in case it is requested in graphql query. 

Now - If a graphql request to get customers matching a name is sent and it identifies 10 matching customers then are calls to resolve CustomerPaymentHistory for all 10 customers supposed to run in parallel/ async? This is what I am trying to achieve but looks like it is not truly running in parallel.

This should cut down my response time as 10 calls will be made in parallel to CustomerPaymentHistory API than 10 calls in sequence.

Is there any configuration entry that needs to be turned out to enable it? I do have async methods but for some reasons these calls mostly appears to be sequential. Kindly advice

**Comment by pravinhabbu4u** [comment]
Is it all about using FieldAsync than Field??? OMG I am so excited to see this in another thread

**Comment by joemcbride** [comment]
The framework itself does not do anything to batch field resolves.  Field resolvers _should_ run in parallel though for a given type.  You can return a `Task` from a field resolver and the framework will wait until all fields for that type are resolved and continue.

**Comment by pravinhabbu4u** [comment]
@joemcbride. Thanks for the quick response. Will the field resolver run in parallel only when FieldAsync is used? In above example, I am expecting if 10 customer records are returned then call to next API (PaymentHistory) should invoke at same time after 1st list type is resolved hence ideally having total time down to time taken to call first API (get customer list) + (max time taken by paymenthistory API)

**Comment by joemcbride** [comment]
No, you don't have to use `FieldAsync`, `FieldAsync` just makes it a little easier to return a `Task`.  If none of you're resolvers are returning a `Task`, then they probably are all running in sequence.

**Comment by pravinhabbu4u** [comment]
@joemcbride Thanks. I will make some changes to return a Task and see what happens. If FieldAsync is not always needed then I was expecting at least a resolve request for all 10 records should have initiated at same time.

**Comment by joemcbride** [comment]
Related discussion: https://github.com/graphql-dotnet/graphql-dotnet/issues/205

**Comment by pravinhabbu4u** [comment]
@jomcbride Thanks a ton. return Task.Run(() => { resolver code} ); has made a huge difference. I will try to improve performance further.
