### ISSUE TITLE
[Suggestion] Rename "GraphQLAuthorizeAttribute" to "AuthorizeAttribute"

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3080]
I suggest we change `[GraphQLAuthorize("MyPolicy")]` to `[Authorize("MyPolicy")]` similar to the ASP.NET Core authorization attribute.  It seems unlikely that someone would have imported the GraphQL namespaces to ASP.NET Core controllers, nor the appropriate ASP.NET Core authorization namespace to GraphQL schema definitions.

We can implement this for 5.1.1 by duplicating the attribute and marking the old one as obsolete for a non-breaking change.  Alternatively, the new one can inherit from the existing attribute (or vice versa).

**Comment by Shane32** [comment]
I would add the missing AttributeUsage property to the new attribute also.

**Comment by sungam3r** [comment]
OK. 
`
[Obsolete]
GraphQLAuthorize : Authorize
`
