### ISSUE TITLE
IndexOutOfRangeException with more than 16 named fragment spread

### ISSUE THREAD

**Issue by cotillion** [graphql-dotnet/graphql-dotnet#3093]
## Description
If a query is executed with more than 16 named fragments and atleast 1 is not spread at the top level System.IndexOutOfRangeException is thrown.

GetFragmentSpreads() does not take into account the possibility of recursion in CollectFields

### Steps to reproduce

```

query {
  hero {
    ...first
    ...second
    ...third
    ...fourth
    ...fifth
    ...sixth
    ...seventh
    ...eight
    ...ninth
    ...tenth
    ...eleventh
    ...twelfth
    ...thirteenth
    ...fourteenth
    ...fifteenth
    ...sixteenth           
  }
}


fragment first on Character {
  id
}

fragment second on Character {
  id
}

fragment third on Character {
  id
}

fragment fourth on Character {
  id
}

fragment fifth on Character {
  id
}

fragment sixth on Character {
  id
}

fragment seventh on Character {
  id
}

fragment eight on Character {
  id
}

fragment ninth on Character {
  id
}

fragment tenth on Character {
  id    
}

fragment eleventh on Character {
  id  
}
fragment twelfth on Character {
  id  
}
fragment thirteenth on Character {
  id  
}

fragment fourteenth on Character {
  id  
}

fragment fifteenth on Character {
  id  
}

fragment sixteenth on Character {
  id  
  ...boom
}

fragment boom on Character {
  id
}

```

### Expected result

Result

### Actual result

Boom.

### Environment

v5

**Comment by Shane32** [comment]
Note: the reason it is 16 is because even though the number is miscounted for any nested fragment, the array used is rented.  The MS array pool probably always allocates arrays with at least 16 elements minimum in it.

**Comment by sungam3r** [comment]
https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs#L31
