### ISSUE TITLE
Float value parsing tests are failed on some locale systems (decimal point is ',')

### ISSUE THREAD

**Issue by kantora** [graphql-dotnet/graphql-dotnet#310]
coerces_numeric_string_to_decimal [0:00.046] Failed: type.ParseValue("12345.6579")
```
type.ParseValue("12345.6579")
    should be
12345,6579m
    but was
null
```

     float_into_boolean [0:00.002] Failed: Input string was not in a correct format.
     float_into_enum [0:00.006] Failed: Input string was not in a correct format.
     float_into_id [0:00.002] Failed: Input string was not in a correct format.
     float_into_int [0:00.002] Failed: Input string was not in a correct format.
     float_into_string [0:00.002] Failed: Input string was not in a correct format.
     good_float_value [0:00.011] Failed: Input string was not in a correct format.
     simple_float_into_int [0:00.009] Failed: Input string was not in a correct format.

**Comment by joemcbride** [comment]
Hi!  Thanks for reporting. We have an issue to track a fix for this. https://github.com/graphql-dotnet/graphql-dotnet/issues/302

**Comment by kantora** [comment]
sorry, tried to search for duplicates using the wrong keyword 'locale'
