### ISSUE TITLE
Can't override graph types within DI

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3100]
When using dependency injection to replace a requested graph type with a derived type, `SchemaTypes` does not add the proper type to its internal dictionary and constructs the type multiple times (which should never happen), with the result that the `ResolvedType` property of a parent graph is a different instance than what is stored in `schema.AllTypes`.  The duplicate type is not initialized, causing various problems -- in my case, field names of the uninitialized instance were not converted to camel case, causing a query validation failure.

A sample of the code that would cause a problem is shown here:

```cs
// override AutoRegisteringObjectGraphType with MyAutoGraphType
services.AddTransient(typeof(AutoRegisteringObjectGraphType<>), typeof(MyAutoGraphType<>));

private class MyAutoGraphType<T> : AutoRegisteringObjectGraphType<T>
{
    // this class contains no code and should perform identical to the type it derives from
}
```

@sungam3r This is a critical bug for my code.  I'm not exactly sure how it worked in v4, or what I may have changed in my project during the transition to v5, but it doesn't work now.  I started modifying `SchemaTypes` to store the requested type (rather than the resolved type's `GetType()` value), but it seems to be a rather invasive change.  Do you have any ideas before I dive into this?  Again, this is critical for me, and if you have any ideas, please let me know.  Thanks!!

See #3101 for a demo of the bug

Note that I can implement workarounds in other classes to get around this failure, but it would probably take as much work as fixing the problem within GraphQL.NET.

**Comment by Shane32** [comment]
> Note that I can implement workarounds in other classes to get around this failure, but it would probably take as much work as fixing the problem within GraphQL.NET.

I was able to work around the bug partially by using the new `IGraphTypeMappingProvider` to remap auto-generated graph types on the fly, but this doesn't cover explicitly specified graph types.  Fortunately there were few of these in my code base.  So I have a working solution for the time being.

**Comment by sungam3r** [comment]
> Do you have any ideas

**Comment by Shane32** [comment]
I would like to fix this bug, one way or another, and then release 5.1.  If you have time to look at it briefly tonight, that would be appreciated.

I'll likely try to work on a patch tonight (which is after your 'tonight').  It will be in the form of a patch to `SchemaTypes`, or possible a rework of the whole class.  (I've long intended to rewrite `SchemaTypes`, as it seems overly complex, but I have not had the motivation, which this bug amply supplies.)

**Comment by sungam3r** [comment]
Today I will need to work the rest of the evening.

**Comment by Shane32** [comment]
No problem
