### ISSUE TITLE
UnhandledExceptionDelegate.Context can be null

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3107]
If an exception is thrown before the `IExecutionContext` instance is created, for example while building the document, the caught exception is handled by the `UnhandledExceptionDelegate` with a `null` value for the `IExecutionContext`.  This means that error handling code cannot log the source document that may have triggered the exception.  Is there a better solution?  Perhaps the execution context should contain a reference to the execution options?

Of course this scenario should never happen, but the point of error handling is to catch and record errors when they unexpectedly do happen.

**Comment by sungam3r** [comment]
>  Perhaps the execution context should contain a reference to the execution options?

Did you mean `UnhandledExceptionContext` should contain... ? If yes then I agree. `UnhandledExceptionContext` may contain any value useful for error handler. I would add `UnhandledExceptionContext.ExecutionOptions { get; internala set; }` property.

**Comment by Shane32** [comment]
The `UnhandledExceptionContext` is also called from the execution strategy, and there the `ExecutionOptions` are not available to be passed to the unhandled exception context (since `ExecutionContext` does not hold a reference to it).

We could add it to both, but I don't think we can add it to only the unhandled exception context.

**Comment by sungam3r** [comment]
`ExecutionStrategy` always has non-nullable `ExecutionContext`.

**Comment by sungam3r** [comment]
You are talking about a possible problem that may happen when there is no execution context yet. What to do then? We _can_ provide additional info via new property inside `UnhandledExceptionContext`. Or you may inherit from `UnhandledExceptionContext` and add new non-nullable property only here.

**Comment by Shane32** [comment]
I don’t understand why we would purposely add a property that can only be populated for errors at the start of the request, but at no other time, when the information it contains is pertinent to the entire execution. I must be missing something. Just doesn’t seem to make sense.

**Comment by sungam3r** [comment]
Because of such a design. Information from `ExecutionOptions` is used to create the `ExecutionContext` object, then the framework works with it. Do not understand me wrong - I'm not talking about some fundamental problem. This is just a matter of design. Not all parts of the system have a reference to `ExecutionOptions` (and this is normal). Properties from options are copied to other objects like `ExecutionContext`. In your particular case error **may** happen **before** that copying. `UnhandledExceptionContext` is used in both places - where we already have constructed `ExecutionContext` (strategy) and don't (document executer). Somehow you need to enrich `UnhandledExceptionContext` with additional information. OK.

**Comment by Shane32** [comment]
It just seems like a bad design to have to write error logging code like this:

```cs
var query = errorContext.Context?.Document.Source.ToString() ?? errorContext.ExecutionOptions!.Query;
```

Because this won't work:

```cs
var query = errorContext.Context.Document.Source.ToString();
```

and this won't work either:

```cs
var query = errorContext.ExecutionOptions.Query;
```

**Comment by Shane32** [comment]
Especially when all the options are valid and unchanged for an entire execution.

**Comment by Shane32** [comment]
What if you wanted to log some other property from ExecutionOptions?  It would not be possible.

**Comment by sungam3r** [comment]
What do you suggest? To drag a reference to `ExecutionOptions` everywhere only because to be able to log the necessary data in case of unhandled exception?

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/165604925-d00fcb49-a23f-4d92-bcea-cfb27a8674c4.png)
Or change all these properties to a single reference to `ExecutionOptions` and create `ExecutionContext` before try/catch?

**Comment by Shane32** [comment]
I have not thought it through fully, but I would consider something like that.  It seems like a lot of unnecessary copying of variables.

**Comment by Shane32** [comment]
Maybe I can create an example PR we can both review together (when you have time; no urgency).

**Comment by Shane32** [comment]
Note that I do not have any pressing need for this change.  It's simply that nullable reference annotations revealed to me that my error logging code could NRE if an exception occurs early in the document executer.

**Comment by sungam3r** [comment]
I know such situations. I have to put up with this somehow. Copying carries not only disadvantages, but also advantages. `ExecutionContext` (and which is more important - `IExecutionContext`) does not depend on `ExecutionOptions`. If you remove copying, then the close relationship of the code parts will increase.

**Comment by Shane32** [comment]
Yeah.  On a side note, `IExecutionContext` is currently rather pointless, as `IExecutionStrategy` requires `ExecutionContext`.  Not only that, we have `internal` variables within `ExecutionContext`, making it so that we cannot easily replace the existing references to `ExecutionContext` with `IExecutionContext`.  I've wanted to make `IExecutionContext` usable for various reasons over the last couple years, but at the moment it does not seem feasible.

**Comment by Shane32** [comment]
While the situation I describe in the original issue can occur, it should be extremely unlikely.  Initializing the schema should produce an exception that is not dependent on the original query.  Parsing the query string into a document should only produce SyntaxError exceptions, which do not get passed through the unhandled exception handler.  Similar with validation errors.  So only a bug in GraphQL.NET code could trigger an unhandled exception handler when the execution context was null.

We can always modify this behavior as a non-breaking change to add an additional constructor and additional properties.  Closing for now.
