### ISSUE TITLE
Issues parsing variables after GQL upgrade to v5

### ISSUE THREAD

**Issue by giy** [graphql-dotnet/graphql-dotnet#3108]
## Summary
I recently upgraded from v 4.6.0 to v 5.1.1 and ran into an issue where it's not able to parse variables. Could you please tell me what I've forgotten or gotten wrong,

Old code
```
opts.Inputs = request?.Variables.ToInputs();
```

New code
```
opts.Variables = request?.Variables.ToInputs();
```

## Relevant information

GQL request e.g.
```
query ($productID: String!) {
	productData(productId: $productID) {
		productId
                 title
```

Variables
```
{
    "productID": "12345", 
}
```

Errors,
```
errors": [
        {
            "message": "GraphQL.Validation.InvalidVariableError: Variable '$productID' is invalid. Unable to convert '4851605' to 'String'\n ---> System.InvalidOperationException: Unable to convert '12345' to the scalar type 'String'\n   at GraphQL.Types.ScalarGraphType.ThrowValueConversionError(Object value) in /_/src/GraphQL/Types/Scalars/ScalarGraphType.cs:line 235\n   at GraphQL.Types.StringGraphType.ParseValue(Object value) in /_/src/GraphQL/Types/Scalars/StringGraphType.cs:line 27\n   at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValueScalar|49_1(ScalarGraphType scalarGraphType, GraphQLVariableDefinition variableDef, VariableName variableName, Object value) in /_/src/GraphQL/Validation/ValidationContext.cs:line 249\n   --- End of inner exception stack trace ---\n   at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValueScalar|49_1(ScalarGraphType scalarGraphType, GraphQLVariableDefinition variableDef, VariableName variableName, Object value) in /_/src/GraphQL/Validation/ValidationContext.cs:line 253\n   at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValue|49_0(IGraphType type, GraphQLVariableDefinition variableDef, VariableName variableName, Object value, IVariableVisitor visitor) in /_/src/GraphQL/Validation/ValidationContext.cs:line 234\n   at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValue|49_0(IGraphType type, GraphQLVariableDefinition variableDef, VariableName variableName, Object value, IVariableVisitor visitor) in /_/src/GraphQL/Validation/ValidationContext.cs:line 224\n   at GraphQL.Validation.
```

Validation Rule
```
opts.ValidationRules = DocumentValidator.CoreRules.Concat(new[] { new InputValidationRule() });
```

Where InputValidationRules.cs is,
```
public class InputValidationRule : IValidationRule
    {
        public ValueTask<INodeVisitor> ValidateAsync(ValidationContext context)
        {
            return ValueTask.FromResult<INodeVisitor>(new NoopNodeVisitor());
        }

        private class NoopNodeVisitor : INodeVisitor
        {
            public void Enter(ASTNode node, ValidationContext context) { /* Noop */ }
            public void Leave(ASTNode node, ValidationContext context) { /* Noop */ }
        }
    }
```

I think the issue is either related to the way I've set the Variables or the InputValidationRule and I would be grateful to understand what to fix. Thank you!

**Comment by Shane32** [comment]
Are you using Newtonsoft to deserialize the request?

**Comment by giy** [comment]
Hi Shane, no I am using SystemText.Json 
`GraphQL.SystemTextJson.GraphQLSerializer`

**Comment by Shane32** [comment]
Well, the error is saying that, for some reason, the number "12345" is not detected as a string.  For example, if you were to try to parse these variables, then the error would be as expected:

```json
{
    "productID": 12345
}
```

Can you verify that the json does include the number as a json string field as shown in your previous example?  Assuming that's not the problem, can you provide more of the code that performs the deserialization for review?

**Comment by giy** [comment]
Oh, it's expected as a string.
For e.g., I've also checked with,
```
query ($productID: Int!, $siteID: Int!) {
	pdp(productId: $productID, siteId: $siteID) {
		productId
		title
```

where
```
{
    "productID": 12345, 
    "siteID": 23
}
```
 
And I also get,
```
{
            "message": "GraphQL.Validation.InvalidVariableError: Variable '$siteID' is invalid. Unable to convert '23' to 'Int'\n ---> System.InvalidOperationException: Unable to convert '2' to the scalar type 'Int'\n   at GraphQL.Types.ScalarGraphType.ThrowValueConversionError(Object value) in /_/src/GraphQL/Types/Scalars/ScalarGraphType.cs:line 235\n   at GraphQL.Types.IntGraphType.ParseValue(Object value) in /_/src/GraphQL/Types/Scalars/IntGraphType.cs:line 41\n   at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValueScalar|49_1(ScalarGraphType scalarGraphType, GraphQLVariableDefinition variableDef, VariableName variableName, Object value) in /_/src/GraphQL/Validation/ValidationContext.cs:line 249\n   --- End of inner exception stack trace ---\n   at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValueScalar|49_1(ScalarGraphType scalarGraphType, GraphQLVariableDefinition variableDef, VariableName variableName,
``` 

The thing though is that all these requests work with 4.6.1. So it's either the library, or most likely I've missed something or made a mistake during the version upgrade.

**Comment by sungam3r** [comment]
@Shane32 Let's change error message:
`$"Unable to convert '{value}' to '{scalarGraphType.Name}'"`
->
`$"Unable to convert '{value}' of type {value.GetType().Name} to scalar '{scalarGraphType.Name}'"`

Of course value may be null.

**Comment by Shane32** [comment]
We made a lot of changes to the scalars for version 5, so there certainly could have been a change made that would affect your scenario.  However, I had thought that during the transition from v3 to v4 is when the scalar values were rejected if they were not the correct type.

See the source code for v4.6.0 which also throws an exception if the value is not a string (see ParseValue):

https://github.com/graphql-dotnet/graphql-dotnet/blob/4.6.0/src/GraphQL/Types/Scalars/StringGraphType.cs

So we would need to investigate further, with a reproducible sample that works in 4.6.x and fails in 5.x in order to debug further.

In the meantime, you can write a custom scalar which will happily accept numeric values for string graph types, and override the built-in StringGraphType with your custom implementation.  There should be no need to change any of your graphs.  There is extensive documentation on this here:

https://graphql-dotnet.github.io/docs/getting-started/custom-scalars

Let me know if you run into trouble implementing the custom scalar.

**Comment by Shane32** [comment]
Just for reference, see version 3.3.2 source code for StringGraphType, which converts any value to a string during parsing:

https://github.com/graphql-dotnet/graphql-dotnet/blob/3.3.2/src/GraphQL/Types/Scalars/StringGraphType.cs

Whereas in 4.0.0 it rejects anything besides a string:

https://github.com/graphql-dotnet/graphql-dotnet/blob/4.0.0/src/GraphQL/Types/Scalars/StringGraphType.cs

**Comment by giy** [comment]
Oh, thank you. I'm just doing the upgrade from a maintainability perspective, so there's nothing pressing.

But, would be grateful if you'll could take a look. I am happy to provide any further snippets from my side.

Just wanted to confirm that the below snippet is the right way of setting variables.
```
opts.Variables = request?.Variables.ToInputs();
```

**Comment by giy** [comment]
Also because siteId is an int and set as an int on the variable, I don't think it's related to the types here though

**Comment by Shane32** [comment]
Is `request.Variables` a string?  `ToInputs()` was removed in v5.  Are you using the code snippet listed in the migration document?

**Comment by giy** [comment]
Oh, so when I did the migration I just thought that Inputs had been renamed to variables. So, I just changed what was in my original post.

request.Variables itself looks fine.
<img width="451" alt="Screen Shot 2022-04-27 at 12 59 01 PM" src="https://user-images.githubusercontent.com/4637666/165621240-7aa101be-6286-4a0a-a6e6-41f92a2bc7b1.png">

Maybe I have not set opts.Variables correctly ?

**Comment by Shane32** [comment]
You are correct that `opts.Inputs` was changed to `opts.Variables`.  However, the `.ToInputs()` extension method you are using should not exist anymore; it was removed in v5 in favor of using dependency injection,

Also the picture you posted does not look like the variables have been deserialized properly.  This is why your code is not working the same as in v4.6.1.  Notice the "Value" of each `KeyValuePair` is a `JsonElement` instead of a `string` or `int`.  So it would seem that your input variables have not been deserialized correctly.  This could occur, for example, if the `InputsJsonConverter` was not supplied within the JSON deserialization options to the System.Text.Json deserializer.

I suggest right-clicking on the `.ToInputs()` extension method and 'go to definition' to see in which library it is defined.  It should not exist in the GraphQL libraries anymore.  Perhaps you have not bumped the `GraphQL.SystemTextJson` package to 5.1.1 ?

Once you have ensured that `.ToInputs()` does not exist and fails to compile, you can replace the extension method with the snippet from the migration document, or use dependency injection to pull `IGraphQLTextSerializer` into the class and call `_serializer.Deserailize<Inputs>(request?.Variables)` to deserialize the request.

**Comment by Shane32** [comment]
Edit: I just realized that the variables picture you posted is of `request.Variables`, which makes sense.  Perhaps you can post a similar picture of what `options.Variables` looks like

**Comment by giy** [comment]
Thank you so much again for looking into this.
Sure, I've attached opts.Variable,
<img width="571" alt="Screen Shot 2022-04-27 at 1 13 47 PM" src="https://user-images.githubusercontent.com/4637666/165623379-d9e238f9-fa9a-4780-b916-bc5d506aff90.png">

**Comment by Shane32** [comment]
Yeah, it certainly shouldn't be holding references to `JsonElement`s.

**Comment by giy** [comment]
Oh, that's interesting.
I see that my previous code had,
```
public class GraphQLRequest
    {
        public string OperationName { get; set; }

        public string Query { get; set; }

        [JsonConverter(typeof(ObjectDictionaryConverter))]
        public Dictionary<string, object> Variables
        {
            get; set;

```

while now I just have,
```
public class GraphQLRequest
    {
        public string OperationName { get; set; }

        public string Query { get; set; }

        public Dictionary<string, object> Variables
        {
            get; set;
```

I can't find this `ObjectDictionaryConverter` class anymore

**Comment by Shane32** [comment]
You can probably change to `public Inputs Variables` with `[JsonConverter(typeof(InputsJsonConverter))]`.

Or you can change it to `public JsonElement Variables`.  Then call this to deserialize:

```cs
var serializer = new GraphQL.SystemTextJson.GraphQLSerializer();
opts.Variables = serializer.ReadNode<Inputs>(request.Variables);
```

**Comment by Shane32** [comment]
@sungam3r I'm not sure when we deprecated `ObjectDictionaryConverter` but we could probably write migration notes for that as well.

**Comment by Shane32** [comment]
@giy Note that there is a GraphQLRequest class in GraphQL 5, however, it needs to be deserialized with a serializer configured with the `InputsJsonConverter` set in the serializer options.

**Comment by sungam3r** [comment]
> I'm not sure when we deprecated ObjectDictionaryConverter but we could probably write migration notes for that as well, assuming we removed it in v5.

I don't know what to write exactly since I don't remember. Write something if you feel that it's necessary.
