### ISSUE TITLE
Operation is not valid due to the current state of the object error

### ISSUE THREAD

**Issue by giy** [graphql-dotnet/graphql-dotnet#3109]
Hello, yesterday I had a question related to variables and ended up making this change,

I changed Variables to,
```
public JsonElement Variables
{
    get; set;
}
```
and changed,
```
opts.Variables = serializer.ReadNode<Inputs>(request?.Variables);
```

However, today just the build with this change seems to be giving me an 
`Operation is not valid due to the current state of the object error` in the GraphQLMiddleware. I was wondering if I've missed something else during the variable upgrade ? Thank you

**Comment by giy** [comment]
So, I am going back to the other way,
```
[JsonConverter(typeof(ObjectDictionaryConverter))]
        public Dictionary<string, object> Variables
        {
            get; set;
```

I tried replacing `ObjectDictionaryConverter` with 
```
[JsonConverter(typeof(InputsJsonConverter))]
        public Dictionary<string, object> Variables
```

But that gives me an error too,
```
 The converter specified on ...Api.Kestrel.GraphQLRequest.Variables' is not compatible with the type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'
```

What is the right way for me to replace `ObjectDictionaryConverter` ?

**Comment by giy** [comment]
Added,
```
if (request?.Variables != null && request.Variables.ValueKind != JsonValueKind.Undefined)
{
    variables = serializer.ReadNode<Inputs>(request.Variables);
}
``` but just want to make sure this looks right for all cases

**Comment by Shane32** [comment]
```cs
[JsonConverter(typeof(InputsJsonConverter))]
public Inputs Variables { get; set; }
```

**Comment by Shane32** [comment]
Then `opts.Variables = request.Variables;`

**Comment by giy** [comment]
Oh, I see.. thank you!!
