### ISSUE TITLE
Block schema introspection based on a HTTP request header

### ISSUE THREAD

**Issue by Heuts** [graphql-dotnet/graphql-dotnet#3111]
## Summary

Block schema introspection based on a HTTP request header value without running the IFieldMiddleware for every single field.

## Relevant information

Hello there! It's me again. I'd like to block schema introspection based on a HTTP request header value (we only want to allow introspection to IP's from certain IP ranges). At the moment we have built a middleware class which implements the `IFieldMiddleware` interface and which checks the header value for matching values. The 'problem' we have with this approach though is that it does the check for every single field in the request. We're worried that this might hurt the performance of our API and before deploying this I would like to check with you guys if there possibly is a better approach to implement logic like this?

### Environment (if relevant)

version 4.8.0

**Comment by Shane32** [comment]
call `app.UseWhen` probably like this:

```cs
app.UseWhen(context => ValidateIpAddress(context), app2 => app2
    .UseGraphQL(...));

bool ValidateIpAddress(HttpContext context)
{
    // examine ip and return true if allowed
}
```

**Comment by Shane32** [comment]
If you want it to ** only ** block introspection requests, and not all requests, then you have to leave it as a validation rule.  You can enhance performance by checking the IP address once during the validation rule setup, and then either returning null if allowed or a rule if not:

```cs
    public class InputValidationRule : IValidationRule
    {
        public ValueTask<INodeVisitor> ValidateAsync(ValidationContext context)
        {
            if (ValidateIpAddress(context)) return null; // no need for validation rule at all

            // otherwise need a validation rule to check that 
            return new ValueTask<INodeVisitor>(new MatchingNodeVisitor<GraphQLField>(
                (field, context2) =>
                {
                     // fail if introspection field
                }));
        }
    }
```

**Comment by Heuts** [comment]
Cool, thanks! I'll give this a try

**Comment by Heuts** [comment]
Do you maybe have an example for GraphQL 4? I'm having a tough time finding one.

And can I access the headers by using the `ValidationContext` object?

**Comment by Shane32** [comment]
Inject IHttpContextAccessor via DI and use that to pull the http context and from that the headers (or client IP address). 

Look at the source code of the repo, and go to the tag (under branches) for a 4.x version. Then look under src GraphQL Validation Rules to see a whole bunch of validation rule examples for 4.x

**Comment by Heuts** [comment]
It took some figuring out but I managed to make it work for our use-case. Once again thanks for your assistance 🚀
