### ISSUE TITLE
Error Could not load type 'GraphQL.Http.IDocumentWriter' 

### ISSUE THREAD

**Issue by wuzixiao** [graphql-dotnet/graphql-dotnet#3117]
## Description

The code works fine under version 4.8.
```c#
 private void AddGraphQL(IFunctionsHostBuilder builder)
  {
      builder.Services.AddSingleton<HoldingData>();
      builder.Services.AddSingleton<IDocumentExecuter>(sp => new DocumentExecuter());
      //builder.Services.AddSingleton<IGraphQLSerializer>(sp => new GraphQLSerializer());
      builder.Services.AddSingleton<IDocumentWriter>(sp => new DocumentWriter());
      builder.Services.AddGraphQL();
  }
```

However, after updating to 5.1.1, it failed to start and showed the error as below 

>System.TypeLoadException: 'Could not load type 'GraphQL.IDocumentWriter' from assembly 'GraphQL, Version=5.1.1.0, Culture=neutral, PublicKeyToken=null'.'

The [official documentation](https://graphql-dotnet.github.io/docs/migrations/migration5/) mentioned 

>As such, the DocumentWriter classes have been renamed to GraphQLSerializer, and the AddDocumentWriter extension method for IGraphQLBuilder has been renamed to AddSerializer

But it still complained about missing IDocumentWriter when it tries to call AddGraphQL(). 

Is there anything else I missing here? 

Thanks
### Environment
Azure Function

**Comment by Shane32** [comment]
Can you post all the GraphQL nuget packages in use?

**Comment by wuzixiao** [comment]
I am using these 3 packages in my project:

    <PackageReference Include="GraphQL" Version="5.2.0" />
    <PackageReference Include="GraphQL.NewtonsoftJson" Version="5.2.0" />
    <PackageReference Include="GraphQL.Server.Core" Version="5.2.1" />

**Comment by sungam3r** [comment]
The problem part is `GraphQL.Server.Core`. GraphQL.NET v5.x.x is compatible with server v6.x.x (v4.x.x with v5.x.x and so on). Please use v6 server packages https://github.com/graphql-dotnet/server/releases/tag/6.0.0. `GraphQL.Server.Core` package was removed in v6. See sample project from server package for comple example.

**Comment by sungam3r** [comment]
Closed as answered.
