### ISSUE TITLE
Error Cannot return null for a non-null type. Field: queryType, Type: __Type! 

### ISSUE THREAD

**Issue by PouryaMontakhab** [graphql-dotnet/graphql-dotnet#3122]
Hi. I have migrated to new version of GraphQl (5.2.0) and I would like to use AutoRegisteringObjectGraphType for automatically scanning  my graphs. 
in order to do that, I have used these two classes 
![image](https://user-images.githubusercontent.com/45295227/167296010-357d2c1a-596a-4d41-954a-c2c522207cad.png)
and 
![image](https://user-images.githubusercontent.com/45295227/167296032-76b739f5-9486-4b7b-ba8c-903a23d65f72.png)

my ConfigureService :
`services.AddTransient(typeof(AutoRegisteringObjectGraphType<>), typeof(AutoRegisteringObjectGraphTypeWithoutMethods<>));
            services.AddTransient(typeof(AutoRegisteringInputObjectGraphType<>), typeof(AutoRegisteringInputObjectGraphTypeWithoutMethods<>));`

so in Query class I Added query like below:
![image](https://user-images.githubusercontent.com/45295227/167297069-5a02a766-732b-430b-8d2f-58d25e48d2fd.png)

finally I receive this error as an exception.
`{
  "message": "Cannot return null for a non-null type. Field: queryType, Type: __Type!."
}`

is there any solution?

**Comment by sungam3r** [comment]
It seems that your schema has no Query type at all. Spec requires it for introspection purposes. How do you initialize your schema?

**Comment by PouryaMontakhab** [comment]
My Schema initialize in this way: 

in ConfigureServivce method : 
`services.AddScoped<ISchema, GraphQLMainSchema>();`

GraphQLMainSchema class : 
` public class GraphQLMainSchema : Schema
    {

        public GraphQLMainSchema(IServiceProvider provider) : base(provider)
        {
            Query = provider.GetService<RootQuery>();
            Mutation = provider.GetService<RootMutation>();
        }

    }
also I have two root classes RootQuery and RootMutation like below:
![image](https://user-images.githubusercontent.com/45295227/167348525-b9f2b27d-3a1d-416d-b48c-6d52f64a6b71.png)

![image](https://user-images.githubusercontent.com/45295227/167348568-16085172-074a-4cae-badc-dcaffe3adaae.png)

So, in GraphqlController where my schema is executed I have post action method like below: 
![image](https://user-images.githubusercontent.com/45295227/167349427-581bc447-ee84-4550-ad5b-4415409b6871.png)

**Comment by PouryaMontakhab** [comment]
Oh sorry. I made a mistake in ConfigureService method. I forgot to AddGraphTypes.
I solved it with this some line codes : 
![image](https://user-images.githubusercontent.com/45295227/167365871-897d9dc5-f32b-4ae0-8a80-13b6c1e50785.png)
