### ISSUE TITLE
Error "The GraphQL type for field 'AutoRegisteringInputObject.type' could not be derived implicitly"

### ISSUE THREAD

**Issue by PouryaMontakhab** [graphql-dotnet/graphql-dotnet#3128]
Hey guys.
I'm trying to use AutoRegisteringInputObject and AutoRegisteringObject for auto scanningmy graphs. I've also used [OutputType] and [InputType] attributes for all nested types, But I receive this error:
`The GraphQL type for field 'AutoRegisteringInputObject.type' could not be derived implicitly. Could not find type mapping from CLR type 'System.Type' to GraphType. Did you forget to register the type mapping with the 'ISchema.RegisterTypeMapping'?`

is there any solution ?

**Comment by Shane32** [comment]
If you can provide a code sample of one of your graphs, it should be quite easy to fix.

**Comment by PouryaMontakhab** [comment]
I've solved it :-)
It was my mistake. Thank a million @Shane32
