### ISSUE TITLE
One-way upgrade when opening solution in VS 2017

### ISSUE THREAD

**Issue by codepunkt** [graphql-dotnet/graphql-dotnet#313]
_One-way upgrade
Visual Studio will automatically make functional changes to the following projects in order to open them. You will not be able to open these projects in the version of Visual Studio in which they were originally created.
	 - GraphQL, "D:\web\graphql-dotnet\graphql-dotnet\src\GraphQL\GraphQL.xproj"
	 - GraphQL.StarWars, "D:\web\graphql-dotnet\graphql-dotnet\src\GraphQL.StarWars\GraphQL.StarWars.xproj"
	 - GraphQL.Tests, "D:\web\graphql-dotnet\graphql-dotnet\src\GraphQL.Tests\GraphQL.Tests.xproj"_

What does this mean? 
Can this project be upgraded to support VS 2017?

**Comment by joemcbride** [comment]
Microsoft got rid of project.json with VS2017.  See #311.

**Comment by codepunkt** [comment]
I've read a lot on the subject in the last few hours. My intial questions might have been short-sighted. Two questions remain:

1. i assume xproj was the project file that was used in combination with project.json?
2. the projects in this repository still use project.json/xproj - i assume #311 will be merged some time soon?

**Comment by joemcbride** [comment]
1. Yes
2. I do not have an estimate really, other than most likely sometime within the next few weeks.  In addition to just updating the project files the build script also needs to be updated.  So there's some work to be done.

**Comment by codepunkt** [comment]
Great, thank you! Looking forward to it! 👍
