### ISSUE TITLE
DocumentExecuter should return ExecutionResult when Query & Document are null

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3138]
@sungam3r Uhhh....???  I would change this behavior here to return an `ExecutionResult` as @SlavaUtesinov already posted.  While your idea is somewhat logical, it seems like a make-work project.  Now the server project (and any other custom middleware) would have to catch errors thrown from `DocumentExecuter` and check if it's an `ExecutionError` (or `RequestError`) and encapsulate it in an `ExecutionResult`.  Better just to write the code here in the `DocumentExecuter`.

We have never considered breaking changes to error conditions as preventing a minor version bump, and this change should have no negative effect on any existing code in the server project or provided samples.  For instance, GraphQL v6 (and GraphQL.AspNetCore3) will still return a 400 error and not even call the DocumentExecuter to begin with.

Rather, we are now "supporting a feature" we did not before -- namely, providing a response when there is no query provided.  Again, while this is breaking in the strictest sense, it should be allowed with a minor version bump.

Finally, as stated previously, situations where `result.Executed == false` should already return 400 according to spec, and does so and will continue to do so.  There is no reason why a missing (`null`) query should be a 400 and an empty (`""`) query should return 200.  If a user were returning 200 for empty (`""`) queries, then it should be acceptable to return a 200 for a null query as well.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/pull/3134#discussion_r872161019_

**Comment by sungam3r** [comment]
I'm fine returning result with some error and translate this into 400 http error code at transport layer (instead of throwing). I just thought about the strictest case.

**Comment by Shane32** [comment]
Closing as previously completed
