### ISSUE TITLE
Arguments can have logical operations?

### ISSUE THREAD

**Issue by psavanur** [graphql-dotnet/graphql-dotnet#314]
Is it possible to include logical operations like AND, OR etc in Arguments similar SQL?

**Comment by joemcbride** [comment]
Not in the GraphQL language itself.  You can add arguments, though they are in key/value pairs.

```graphql
query {
  droid(ids: [1, 2, 3]) {
    id
    name
  }
}
```

```csharp
Field<DroidType>(
      "droid",
      arguments: new QueryArguments(
        new QueryArgument<ListGraphType<IntGraphType>> { Name = "ids" }),
      resolve: context =>
      {
        var ids = context.GetArgument<List<int>>("ids");
        return repo.GetDroidsByIdsAsync(ids);
      }
    );
```

**Comment by joemcbride** [comment]
There is a feature called Directives which you can use.  There are only a couple of built-in directives - `@incldue` and `@skip`.  It is possible to add a custom directive, though you would have to handle the logic for that yourself.

http://graphql.org/learn/queries/#directives

**Comment by psavanur** [comment]
Thanks joemcbride
