### ISSUE TITLE
How to implement file upload graph?

### ISSUE THREAD

**Issue by PouryaMontakhab** [graphql-dotnet/graphql-dotnet#3151]
Hey guys.
I've upgraded my GraphQl version to 5.2.0 and I want to know how I can receive a file from QueryArgument?
I've searched a lot, but I haven't found any solution yet. Is there any idea?

**Comment by sungam3r** [comment]
File upload issues: #682, #419, #213.

**Comment by Shane32** [comment]
I’ve implemented file download in some of my schemas as base64 encoded strings. File upload could be done the same way. Another common download technique would be to return a url pointing to the file data. Similarly you could have the caller PUT the file to a temporary storage url and post the url as a string within a variable to the GraphQL endpoint.
