### ISSUE TITLE
Query/Mutation name in the Execution Errors collection

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#3158]
Hi,
We are logging all GraphQL execution errors in our database. 
The issue is that this execution error object, does not contain any information about the query/mutation that is getting executed. 

When we fetch error log from database, we have no idea which schema method is causing this error.

Is there any way to add more context in the execution error object.

Thanks.

**Comment by Shane32** [comment]
How are you logging errors?  Are you using the `UnhandledExceptionDelegate`?  If so, you can access the execution context and pull the document from there.  This is how I've written code in my applications, when configuring services with `IGraphQLBuilder`:

```cs
.ConfigureExecutionOptions(opts =>
{
    opts.UnhandledExceptionDelegate = async context =>
    {
        if (context.Context != null)
        {
            var exceptionLogger = context.Context.RequestServices.GetRequiredService<ExceptionLogger>();
            await exceptionLogger.LogExceptionAsync(context.Exception, context.Context.Document.Source);
        }
    };
})

class ExceptionLogger
{
    public Task LogExceptionAsync(Exception ex, string query)
    {
    }
}
```

**Comment by rmeshksar** [comment]
Hi, 
No, we are not using UnhandledExceptionDelegate.

We are just logging ExecutionResult.Errors 

```chsarp
if (result.Errors != null)
{
    foreach (var e in result.Errors)
    {
          // Log error here by calling a method that accepts argument of type Exception
    }
}
```

I thought maybe we can add some extra information to Data collection of Exception object before logging it, but even full result object does not include any information of the context.

Here is an example of the result object (the output of calling ExecuteAsync) which as you can see the value of Query, Document and Operation is all null.

```json
{
    "Data": null,
    "Errors": [{
            "ClassName": "GraphQL.Validation.Errors.ArgumentsOfCorrectTypeError",
            "Message": "Argument \"test\" has invalid value {prop2: null}.\nIn field \"prop2\": Expected \"Int!\", found null.",
            "Data": null,
            "InnerException": null,
            "HelpURL": null,
            "StackTraceString": null,
            "RemoteStackTraceString": null,
            "RemoteStackIndex": 0,
            "ExceptionMethod": null,
            "HResult": -2146233088,
            "Source": null,
            "WatsonBuckets": null
        }
    ],
    "Query": null,
    "Document": null,
    "Operation": null,
    "Perf": [{
            "Category": "operation",
            "Subject": null,
            "Metadata": null,
            "Start": 0.0,
            "End": 9.4763,
            "Duration": 9.4763
        }, {
            "Category": "schema",
            "Subject": "Initializing schema",
            "Metadata": null,
            "Start": 0.0007,
            "End": 9.2474,
            "Duration": 9.2467
        }, {
            "Category": "document",
            "Subject": "Building document",
            "Metadata": null,
            "Start": 9.2479,
            "End": 9.2632000000000012,
            "Duration": 0.015300000000001646
        }, {
            "Category": "document",
            "Subject": "Validating document",
            "Metadata": null,
            "Start": 9.2643,
            "End": 9.471,
            "Duration": 0.20669999999999966
        }
    ],
    "Extensions": null
}

```

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/172210114-078b7f4c-b5aa-410b-9f93-b9328167570e.png)


@Shane32 Maybe we should try to preserve more context for those cases?

**Comment by Shane32** [comment]
@sungam3r Probably, though I'm a bit surprised that `ExecutionResult` even contains those properties.  Typically you'd expect that the caller would already have access to the inputs provided through `ExecutionOptions`.  The only exception is `Document`, as that is typically generated within the `DocumentExecuter`.

@rmeshksar If you're inspecting the response from `IDocumentExecuter.ExecuteAsync`, why do you not have access to the options provided through the same method?  You should be able to pull whatever 'context' information you wish there.

For example:

```cs
var options = new ExecutionOptions {
    // set options here
};
var result = await _executer.ExecuteAsync(options);
if (result.Errors != null)
{
    foreach (var e in result.Errors)
    {
          e.Data["query"] = options.Query;
          e.Data["operationName"] = options.OperationName;
          // Log error here by calling a method that accepts argument of type Exception
    }
}
```

You can do the same via DI with `ConfigureExecution` if you're using the server project or similar to serve results.

**Comment by rmeshksar** [comment]
You are right,
For us, these are in two separate methods, but I guess we can move error logging portion inside the execute method.


```csharp

public async run() 
{
  var result = await Execute();

  if (result.Errors != null)
  {
      foreach (var e in result.Errors)
      {
            // Log error here by calling a method that accepts argument of type Exception
      }
  }
}

public async Task<ExecutionResult> Execute() 
{
    var options = new ExecutionOptions {
        // set options here
    };
    return await _executer.ExecuteAsync(options);
}
```

**Comment by sungam3r** [comment]
@Shane32 I would not say that the properties of `ExecutionResult` look superfluous. I agree that `Query` and `Operation` _may_ seem excessive but these properties may be computed (i.e. "output" properties). Remember about caching/APQ. I would keep them as is.

**Comment by Shane32** [comment]
Sure; it doesn’t hurt.

**Comment by rmeshksar** [comment]
BTW, I forgot to mention we are using GraphQL version 3.2. Not sure if it is still the case in the later versions.

**Comment by Shane32** [comment]
Closing as answered
