### ISSUE TITLE
Data flattening is supported?

### ISSUE THREAD

**Issue by psavanur** [graphql-dotnet/graphql-dotnet#316]
Is data flattening supported in GraphQL? For ex: If I want to retrieve hero{ name : "R2-D2" } as hName: "R2-D2", is it possible?

**Comment by joemcbride** [comment]
No, that is not possible.  You can do an alias http://graphql.org/learn/queries/#aliases , but not transform/project.

**Comment by psavanur** [comment]
Thanks joemcbride
