### ISSUE TITLE
No service for type 'GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1[Application.GraphQL.GraphQLSchema.DefaultSchema]' has been registered.

### ISSUE THREAD

**Issue by NicolaiJee** [graphql-dotnet/graphql-dotnet#3162]
Hi
I am trying to migrate my solution from 4.x to 5.30.
But I keep running into this error:
No service for type 'GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1[Application.GraphQL.GraphQLSchema.DefaultSchema]' has been registered.

I have a simple authenticationmiddleware but nothing else in the execution pipeline.
Project and all packages has been upgraded to newest version today.
These are my usings:

```
using GraphQL;
using GraphQL.MicrosoftDI;
using GraphQL.SystemTextJson;
using GraphQL.Types;
```
This is how I register GraphQL:

```
services.AddGraphQL(builder => builder
                .AddSystemTextJson()
                .AddSchema<DefaultSchema>()
                .AddErrorInfoProvider((opts, serviceProvider) =>
                {
                    //var settings = serviceProvider.GetRequiredService<IOptions<GraphQLSettings>>();
                    opts.ExposeExceptionStackTrace = true;
                })
                .AddGraphTypes(typeof(DefaultQuery).Assembly));

```
Am I doing something wrong or is that a bug ?
I have tried setting it up like various example projects.

**Comment by Shane32** [comment]
That's a server issue - I think you need to add `.AddHttpMiddleware<DefaultSchema>()` in there... (which will not be required in the upcoming server v7)

**Comment by Shane32** [comment]
See https://github.com/graphql-dotnet/server/blob/master/samples/Samples.Server/Startup.cs#L37
