### ISSUE TITLE
Fix complexity analyzer fragments' calculations

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3164]
I don't understand what's going on here, but it doesn't seem correct.  It should just be `3*6` - where 3 is the value of the parent and 6 is the total of the fragment.  This should then compute to 18, not 27.  Can we fix this while we are making changes here?

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/pull/3159#discussion_r891181135_

**Comment by sungam3r** [comment]
@Shane32 I'm sure that existing algorithm of complexity calculation is awkward (at least for me). Nevertheless, it was invented so for a reason. I would like to redesign calculation method some day to make it more obvious. In any case, we get some abstract metric - just a number - more or less. This number can be very far from reality, and all our attempts to guess it is only approximation

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/298#issuecomment-289555421

**Comment by Shane32** [comment]
In my mind, there is no reason why these queries should calculate differently:

```gql
{
  field1 {
    child1
    child2
  }
}
```

and

```gql
{
  field1 {
    ...fragment1
  }
}

fragment fragment1 on Widget {
  child1
  child2
}
```

So I consider this a bug.

**Comment by Shane32** [comment]
If there is a reason, it should be stated in a comment or documentation.

**Comment by Shane32** [comment]
Complexity analyzer has been rewritten for v8 in #3989 .  It will now calculate a document that uses fragments the same as one with the fields specified inline.  Calculations are now logical and straightforward.
