### ISSUE TITLE
Ignore complexity limit for introspection queries

### ISSUE THREAD

**Issue by gat-cs** [graphql-dotnet/graphql-dotnet#3171]
## Summary

The `IDocumentExecuter` offers the possibility to limit the complexity of incoming queries by setting a maximum depth. Unfortunately, the maximum depth applies to introspection queries as well. Introspection queries are used by most GraphQL tools (code generation, autocomplete, etc) and tend to be deeper than regular queries. As a result, setting a fairly low maximum depth (e.g. 5) prevents the use of most introspection-based tools.

As a default or as a option, would it be possible to skip the complexity checks for introspection queries?

### Basic example

``` csharp
      var result = await executer.ExecuteAsync(o =>
      {
        // ...
        o.ComplexityConfiguration = new ComplexityConfiguration { MaxDepth = 5 };
      });
```
The configuration above prevents the use of most introspection-based tools.

### Motivation

Limiting the depth of queries is a very valuable feature. However, it should not be incompatible with the use of introspection for things such as code generation.

**Comment by Shane32** [comment]
This should be easy with https://github.com/graphql-dotnet/graphql-dotnet/pull/3159 which was just merged -- setting the root introspection types to have an impact of zero should effectively have a net zero complexity factor for the entire introspection portion of the graph, since any child/nested fields/fragments will be multiplied by zero.

**Comment by Shane32** [comment]
Personally, I see the MaxDepth property having limited usefulness, because often extremely complex queries can be written with a very shallow depth.  Example:

```cs
{
  featuredProducts {
    similarProducts {
      similarProducts {
        similarProducts {
          name
        }
      }
    }
  }
}
```

Meanwhile, a simple query might have a very deep depth:

```gql
# pull 10 products, with the name of the product, plus the manufacturer name, city, and state
{
  products(first:10) {
    edges {
      cursor
      node {
        id
        name
        manufacturer {
          name
          address {
            city {
              name
              state
            }
          }
        }
      }
    }
  }
}
```

Introspection queries are typically simple queries that can be quite "deep"

**Comment by sungam3r** [comment]
> because often **extremely complex** queries can be written with a very shallow depth.

Author of the particular schema can and should decide what is extremely complex and what is not - #3159 helps with this.

**Comment by gat-cs** [comment]
Thank you both for the fast answer.

My reasoning for skipping complexity analysis specifically for introspection queries was that I would expect these queries to have a predictable low cost to resolve, and that it is generally expected that introspection just works.

Having a look at #3159, do you think it would make sense to have a maximum depth equivalent? e.g. `.WithMaxDepth(3)`

**Comment by sungam3r** [comment]
I don't understand how it will work.

**Comment by sungam3r** [comment]
@Shane32 By the way what to do with **default** complexity of introspection types?

**Comment by Shane32** [comment]
Complexity analyzer has been rewritten for v8 in #3989 .  There is now a `ISchema` extension method to set or remove complexity limit for introspection fields.
