### ISSUE TITLE
Change IComplexityAnalyzer.Validate to return ComplexityError(s)

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3175]
I suggest to change `Validate` signature to return `ComplexityError(s)`.

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/graphql-dotnet/pull/3172#discussion_r895101599_

**Comment by Shane32** [comment]
I would remove IComplexityAnalyzer instead - see #3177

**Comment by sungam3r** [comment]
ok
