### ISSUE TITLE
Remove IComplexityAnalyzer and move the analysis code within ComplexityValidationRule

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3177]
Reasoning: `IComplexityAnalyzer` is now just a wrapper for `IValidationRule`.  There essentially is no difference between the two interfaces.  We can still retain the protected member `Analyzed` within the validation rule.  And anyone who writes a fully custom implementation can do so just as easily by writing a new validation rule.  So `IComplexityAnalyzer` serves no purpose.

Also, by rolling the code within `ComplexityAnalzyer` into `ComplexityValidationRule`, we can roll the complexity analysis code into the node visitor used by the `DocumentValidater`, which will save a notable amount of processing time, because all of the code within `TypeInfo` does not need to be allocated or run again.

I suggest marking `IComplexityAnalyzer` and related classes as `[Obsolete]` for the upcoming version, and removing them in the next major version.

**Comment by sungam3r** [comment]
I would remove now.
