### ISSUE TITLE
Is there a DictionaryGraphType<TKey, TValue>?

### ISSUE THREAD

**Issue by xplatsolutions** [graphql-dotnet/graphql-dotnet#318]
Awesome library! Works so good for my use cases. Thanks.

I already have `QueryArgument<ListGraphType<StringGraphType>>` and works great, I wonder if I can pass an argument like the below.

```
query FetchData {
  data(dictionaryFieldValues: { address: [ "address1", "address2" ], state: [ "states1", "states2" ] }) {
    id,
    name,
    region
  }
}
```

I believe you can tell that I have a `QueryArgument` of type `Dictionary<string, IEnumerable<string>>`. I understand that I could break them down but I want to use it as generic keys that will change at runtime so I would like to keep it in a `Dictionary` form.

**Comment by joemcbride** [comment]
There is not a built-in DictionaryGraphType.  You can create your own input types though.  In general, GraphQL is a very Type specific system.  You can create an input type that matches that signature.  While it may be possible to create a "Dictionary Graph Type" I wouldn't really recommend it as that kind of defeats the purpose of GraphQL.

```csharp

public class SearchOptions
{
    public List<string> Address { get; set; }
    public List<string> State { get; set; }
}

public class SearchOptionsType : InputObjectGraphType
{
    public SearchOptionsType()
    {
        Description = "Search criteria";
        Field<ListGraphType<StringGraphType>>("address");
        Field<ListGraphType<StringGraphType>>("state");
    }
}

public class SearchDataType : ObjectGraphType
{
    public SearchDataType()
    {
      Field<ListGraphType<SearchResultType>(
        "data",
        arguments: new QueryArguments(new QueryArgument<SearchOptionsType>("options")),
        resolve: context =>
        {
            // this is now your strongly-typed DTO (not a GraphQL type)
            var options = context.GetArgument<SearchOptions>("options");
        }
      );
    }
}
```

**Comment by jquense** [comment]
I do wish there was gql support for typed maps. someone should submit an RFC :P

**Comment by xplatsolutions** [comment]
Hmmm, I get what you mean and thank you for the example. 

I need this to be agnostic so at the moment I will just work it out using a different endpoint and just pass the results through GraphQL to filter response.
