### ISSUE TITLE
AutoRegisteringObjectGraphType does not apply non-null for read-only (only getter) properties

### ISSUE THREAD

**Issue by psmolinsky** [graphql-dotnet/graphql-dotnet#3185]
## Description

`AutoRegisteringObjectGraphType<>` does not wrap output type to `NonNullGraphType<>` for read-only (only getter, no setter) properties despite the type can be non-nullable.

### Steps to reproduce

1. Create following model

```csharp
public class Foo
{
    public string Bar => "Hello world";
}
```

2. Register its graph type `AutoRegisteringObjectGraphType<Foo>` accordingly.

3. It outputs following schema. It is incorrect in my opinion as far as the type `string` is non-nullable.

```graphql
type Foo {
  bar: String
}
```

4. Add a dummy setter to the model. Notice that the property type is still same.

```csharp
public class Foo
{
    public string Bar
    {
        get => "Hello world";
        set => throw new NotSupportedException();
    }
}
```

5. Now the schema has non-nullable property:

```graphql
type Foo {
  bar: String!
}

**Comment by Shane32** [comment]
Good catch. I’ll fix it.
