### ISSUE TITLE
Can I auto add certain fields in response even when those ar not requested in query

### ISSUE THREAD

**Issue by pravinhabbu4u** [graphql-dotnet/graphql-dotnet#319]
Our API's has Data and Error blocks hence I am looking for a way to auto add Error field in response even when it is not requested by caller. Or even better would be to add it only in case it has data (just like standard errors block in Orchestration response)

**Comment by joemcbride** [comment]
No, that is not currently a feature of GraphQL.

**Comment by joemcbride** [comment]
I think perhaps your best bet is to have a "result" class that you can add that data to.

**Comment by joemcbride** [comment]
Going to close this, re-open if needed.  Thanks!

**Comment by minawalphonce** [comment]
I this this is needed
in facebook, they always add Id for example, 
i need to add something like totalCount even if it is not requested but paging is requested
