### ISSUE TITLE
Feature request: global GraphQL attributes

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3198]
I propose adding within global options a list of GraphQL attributes which are applied to all types anywhere they could otherwise be applied.  This typically applies to schema-first and type-first, of course.

For an example use case, users could add a global attribute which converts query arguments of type DbContext to pull from services, like this:

```cs
public class DbContextFromServicesAttribute : GraphQLAttribute
{
    public override void Modify<TParameterType>(ArgumentInformation argumentInformation)
    {
        if (typeof(TParameterType) == typeof(DbContext))
            argumentInformation.SetDelegate(context => (context.RequestServices ?? throw new MissingRequestServicesException())
                .GetRequiredService<TParameterType>());
    }
}

// in Startup.cs or Program.cs
static void Startup()
{
    GlobalSwitches.GlobalAttributes.Add(new DbContextFromServicesAttribute());
}
```

Although the above attribute is applied to other types as well, it would not affect them since it would be executing other overloads of `Modify()` which execute no code.

Ideally this would be configured per schema, but that is not possible with the current GraphQL.NET design, where graph types do not have access to schema properties in their constructors.

**Comment by sungam3r** [comment]
OK. What about possibility of double execution of methods in such attributes?

**Comment by Shane32** [comment]
My first thought is that I wouldn’t worry about it. I only see it useful for users that are designing a custom global attribute. It’s not like they are going to globally apply IdAttribute or something. 

I did also think of the fact that rather than add a list to GlobalSwitches, we could set it up so users add global GraphQL attributes to the assembly (and then we scan for them there when initializing a type or field). Or we could do both.

**Comment by Shane32** [comment]
It seems that we should consider updating some of the `Modify` methods to have a CLR type parameter also, to allow the attribute code to perform further examinations of the type as it sets properties and stuff.

For example logic like this could be written:

```cs
override Modify(IGraphType graphType, Type clrType)
{
    // if it's a database type
    if (clrType.IsAssignableFrom(typeof(IDatabaseModel)))
    {
        // set the name appropriately
        graphType.Name = clrType.Name + "DbModel";
    }
}

override float Priority => -1f; //run first
```

**Comment by sungam3r** [comment]
>Modify methods to have a CLR type parameter also

ok
