### ISSUE TITLE
Advice on Claims Based Security through GraphQL-DotNet

### ISSUE THREAD

**Issue by drobertson123** [graphql-dotnet/graphql-dotnet#320]
I am looking for advice, examples or even a nudge in the right direction for how I would go about implementing a Claims Based Authorization scheme through GraphQL.

This is the basic scenario. We are using GraphQL to provide data to a SPA style React web application. We use Auth0 for identity and have claims tokens assigned to users designating the rights they have to certain data.  

Each data source we have loaded into GraphQL can have different rights and restrictions based on the Claims Tokens associated with the identity. 

The system works fine at the React level and I can determine the Identity and Claims Tokens of the user accessing the GraphQL server.

What I need to figure out is how to pass that information down to the query or mutation, through GraphQL and to the actual data objects. Then at the data object level, I need to implement some form of authorization controls that allow a user with the correct claims tokens to get to the data or be denied.

I would love to be able to use an annotation-based system similar to this;

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims#adding-claims-checks

My issue is that this would need to run at the Data Object layer and not up on IIS. Does anyone have a suggestion for doing this?

**Comment by joemcbride** [comment]
This is what I ended up doing.

You can use "object/field metadata" to add arbitrary information to either an Object or Field.  You can then use that information and write Validation rules that check for authentication and authorization.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md#objectfield-metadata
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md#authentication--authorization

This ended up looking like:

```
Field(x => x.Name).AddPermission("Some permission");
```

You could tweak that code a bit to look more like:

```
Field(x => x.Name).RequiresClaim("SomeClaim", "SomeValue");
```

**Comment by joemcbride** [comment]
Going to go ahead and close this.
