### ISSUE TITLE
Add an attribute for setting the complexity factor on fields of type-first/schema-first schemas.

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3200]
Note: we should add an attribute for setting the complexity factor on fields of type-first/schema-first schemas.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/issues/3195#issuecomment-1164760968_

**Comment by sungam3r** [comment]
@Shane32 Do you still want to include this in v7?

**Comment by Shane32** [comment]
I’m not inclined to. We can always add it later.
