### ISSUE TITLE
Can I Inject Ilogger using IFieldMiddleware?

### ISSUE THREAD

**Issue by Hemant2384** [graphql-dotnet/graphql-dotnet#3201]
Hi! Can we inject the ```ILogger``` interface while implementing a Custom Middleware inherited from the ```IFieldMiddleware``` class. I could not found any way to inject it in my Custom Middleware. Can you please help me in doing that? if that's not possible, then how can I log my details in the console while implementing a custom middleware inherited from the the ```IFieldMiddleware``` class.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/GraphQLBuilderExtensions.cs#L701
4 methods to register middleware.

**Comment by Hemant2384** [comment]
If I register my Middleware using the ```AddMiddleware```, then do I need to add it in my pipeline using the ```FeldMiddleware.Use``` ?

**Comment by Shane32** [comment]
No
