### ISSUE TITLE
`AutoRegisteringObjectGraphType` does not discover `base` methods 

### ISSUE THREAD

**Issue by psmolinsky** [graphql-dotnet/graphql-dotnet#3204]
## Description

`AutoRegisteringObjectGraphType<>` correctly discovers `base` (from inherited class) properties, which I find very useful, but methods are not discovered.

### Steps to reproduce

1. Use following model:

    ```csharp
    public class FooBase
    {
        public string BaseProperty => "abc";

        public string BaseMethod() => "abc";
    }

    public class Foo : FooBase
    {
        public string ThisProperty => "abc";

        public string ThisMethod() => "abc";
    }
    ```
2. Register `AutoRegisteringObjectGraphType<Foo>` accordingly.
3. Output GraphQL schema correctly contains `BaseProperty` but misses `BaseMethod`:

    ```graphql
    type Foo {
      thisProperty: String!
      baseProperty: String!
      thisMethod: String!
    }
    ```

## Remarks

I think it is because of `BindingFlags.DeclaredOnly` filter [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/5810855929755fd6ad15fbcba9a31ec71bca1e75/src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs#L237). Most likely it can be replaced with `x.DeclaringType != typeof(object)` filter.

**Comment by Shane32** [comment]
This was by design.  We can change it for the next major version, but then we need to add exclusions for `GetHashCode` and `MemberwiseClone` and similar.  Do you want to create a PR?

**Comment by psmolinsky** [comment]
Thanks for the workaround explanation - that's exactly how I did it. So I move it to PR #3205. Please review.
