### ISSUE TITLE
Use of Metrics while implementing IFieldMiddleware

### ISSUE THREAD

**Issue by Hemant2384** [graphql-dotnet/graphql-dotnet#3206]
Hi!
I was implementing a middleware using the ```IFieldMiddleware```. Can you please help me by giving an example of how we can log the details of execution on a per field basis using the ```Metrics``` and ```PerfRecord``` methods. 

This is my Middleware,

```C#
using GraphQL;
using GraphQL.Instrumentation;
using GraphQLParser.AST;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace GraphQLMIddleware
{
    public class InstrumentFieldsMiddleware : IFieldMiddleware
    {
        public async ValueTask<object> ResolveAsync(IResolveFieldContext context, FieldMiddlewareDelegate next)
        {
            var metadata = new Dictionary<string, object>
            {
                {"typeName", context.ParentType.Name},
                {"fieldName", context.FieldDefinition.Name.ToString()},
                {"path",context.Path },
                {"arguments",context.Arguments },
                {"metrics" , context.Metrics }
            };
            var path = $"{context.ParentType.Name}.{context.FieldDefinition.Name}";
            //var metrics = $"{context.Metrics.Start(context.Operation.ToString())}";
            using (context.Metrics.Subject("field", path, metadata))
            {
                return await next(context).ConfigureAwait(false);
            }
        }
    }
}
```
Here I want to implement the ```PerfRecord``` method of ```Metrics```,  which is of  the ```IResolveFieldContext```. So, Can you give me an example of implementing that or guide me how to use the different methods of context.
I tried to implement it but on the console I got the extension name. So, Please Can you help me.

The method
```C#
Metrics.Subject
```
records an performance metric.

So, if I try to print it in my console by storing ```context.Metrics.Subject("field", path, metadata)``` in a variable.
I am getting ```GraphQL.Instrumentation.Metrics+Marker```. I am not able to understand this.

**Comment by Shane32** [comment]
If you just want to log to the console, why are you using Metrics at all?  Why not just `Debug.WriteLine` whatever you want to log?  `Metrics` is designed to log metrics for interpretation after the execution has completed, typically including the data alongside the results.

```cs
    public class InstrumentFieldsMiddleware : IFieldMiddleware
    {
        public async ValueTask<object> ResolveAsync(IResolveFieldContext context, FieldMiddlewareDelegate next)
        {
            var start = DateTime.UtcNow;
            var ret = await next(context).ConfigureAwait(false);
            var end = DateTime.UtcNow;
            var path = string.Join("/", context.Path.Select(x => x.ToString()));
            Debug.WriteLine($"Executed field at {start} finished at {end} path is {path}");
            return ret;
        }
    }
```

**Comment by Hemant2384** [comment]
Ohh Okay. But if we add ```services.AddApolloTracing```, we get all the execution details. Is that the same we will get through the Metrics?

**Comment by Shane32** [comment]
Basically.  `AddApolloTracing` adds metrics into the `context.Metrics`, then configures execution to run `EnrichWithApolloTracing` after the execution is complete to add the metrics data to the execution result.

You can manually add the middleware without running `EnrichWithApolloTracing` and instead configure your own code to do something with the metrics data once execution is complete.

**Comment by Hemant2384** [comment]
Okay completely understood. Just one doubt I had. So, basically, if I remove the ```services.AddApolloTracing``` and write my own middleware with the methods, it will include the data alongside the results, I got it right?.

**Comment by Shane32** [comment]
I guess I'm not exactly sure what you're asking.  I suggest you look at the source code below, then make your own middleware or extension methods as necessary.  There really isn't much code.

## `AddApolloTracing`

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/GraphQLBuilderExtensions.cs#L1060..L1079

## `InstrumentFieldsMiddleware`

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs

## `EnrichWithApolloTracing`

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Instrumentation/ApolloTracingExtensions.cs

**Comment by Hemant2384** [comment]
Okay, Thankyou so much!
