### ISSUE TITLE
GraphQL readability to express complex SQL WHERE-like queries?

### ISSUE THREAD

**Issue by ilya-chumakov** [graphql-dotnet/graphql-dotnet#321]
Hello, 
I'm investigating a possibility to use GraphQL on top of relational SQL database-driven .NET Core app. Our plan is to build complex queries on JS client and  translate it to SQL at server side. SQL example:

> WHERE Customer.Age BETWEEN 22 AND 25
> AND   Order.Status = 'Active'
> OR    Product.Name LIKE '%foo%'

I read a lot of GraphQL docs and tutorials. There is `filter` feature in GraphQL but it looks like that keyword is not widely-supported. I asked at [StackOverflow](http://stackoverflow.com/q/43451978/5112433) about it. Probably I'm misunderstanding something so feel free to correct me.

Finally, let me ask here: does `GraphQL for .NET` support parsing of such complex filtration queries? I looked at docs... well, `select object by id` - is not a complex scenario. 

I suppose we also need a transator from parsed GraphQL query to Expression or IQueryable (we use Entity Framework Core). Does anyone have a fresh idea how to start with that on top of `GraphQL for .NET`? Not able to use https://github.com/ckimes89/graphql-net because it hasn't been ported to .NET Core yet.

**Comment by jquense** [comment]
Graphql as a query language has no specific filtering or sorting syntax. What it does have are query arguments that you can use to implement filtering or sorting in your field revolvers. In this way it's more like REST apis than sql, where you are responsible for building the various semantics you want into your server.

**Comment by jquense** [comment]
An additional note, the idea of GQL is _not_ to give the client access to your sql database or do direct queries against it. That's generally a bad idea. Graphql, like REST is a way to define specific, albeit flexible, apis, not be a frontend for your database

**Comment by chumakov-ilya** [comment]
@jquense, thanks for nice explanation. It seems that GraphQL's best application is to describe projections in short and well-readable way, isn't?

**Comment by joemcbride** [comment]
I'm going to close this.  Re-open if needed.  Btw, I really like your avatar pic @ilya-chumakov 😄

**Comment by SimonCropp** [comment]
just an fyi. i stated a small side project with some basic support for EF `where`, `skip` and `take, semantics https://github.com/SimonCropp/GraphQL.EntityFramework
