### ISSUE TITLE
FieldMiddleware issue

### ISSUE THREAD

**Issue by Hemant2384** [graphql-dotnet/graphql-dotnet#3210]
Hi! I implemented the ```InstrumentFieldsMiddleware``` examples from the docs.

```C#
    public class InstrumentFieldsMiddleware : IFieldMiddleware
    {
        public async ValueTask<object> ResolveAsync(IResolveFieldContext context, FieldMiddlewareDelegate next)
        {
            var metadata = new Dictionary<string, object>
            {
                {"typeName", context.ParentType.Name},
                {"fieldName", context.FieldDefinition.Name.ToString()},
                {"path",context.Path },
                {"arguments",context.Arguments },
                //{"metrics" , context.Metrics }
            };
            var path = $"{context.ParentType.Name}.{context.FieldDefinition.Name}";
            using (context.Metrics.Subject("field", path , metadata))
            {
                return await next(context).ConfigureAwait(false);
            }
       }
}
```
And registered it in the Schema.

```C#
    public class MySchema : Schema
    {
        public MySchema(IServiceProvider services, MyQuery query, InstrumentFieldsMiddleware middleware) : base(services)
        {
            Query = query;
            FieldMiddleware.Use(middleware);
        }
    }
```
Also, enabled Apollo Tracing in my StartUp.cs

```C#
           services
            ..AddMiddleware<InstrumentFieldsMiddleware>()
             .ConfigureExecutionOptions(options =>
            {
                var logger = options.RequestServices.GetRequiredService<ILogger<Startup>>();
                options.UnhandledExceptionDelegate = ctx =>
                {
                    logger.LogError("{Error} occurred", ctx.OriginalException.Message);
                    return Task.CompletedTask;
                };
                options.EnableMetrics = true;
            })
```
But, when I am querying I am only getting the data, not any execution metrics.
Am I understanding it wrong, or do I have to add something else, Can you please me help in clearing this concept. ?

**Comment by Shane32** [comment]
Please re-read the source code links I sent you here:

https://github.com/graphql-dotnet/graphql-dotnet/issues/3206#issuecomment-1170704986

Specifically, read the source code for `AddApolloTracing` where it calls `ConfigureExecution`:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/GraphQLBuilderExtensions.cs#L1066-L1077

You will see you are missing the call to `EnrichWithApolloTracing` which is what adds the metrics to the result.  Setting `EnableMetrics` to `true` allows the metrics to be recorded, and calling `EnrichWithApolloTracing` is what adds the data to the result.

You should also be aware that you are adding the middleware twice, which you don't want to do -- once in the `MySchema` constructor and once via `AddMiddleware`.  Pick one or the other, but not both.  If you register it in the `MySchema` constructor, then you will probably need to register it in DI manually via `services.AddSingleton`.  Whereas using `AddMiddleware` both registers it in DI and registers it with the schema.

**Comment by Hemant2384** [comment]
Sorry, for asking again and again. Actually, I started few months back only with .NET Core.
Just one last confusion. If we just register the ```services.AddApolloTracing``` and remove the ```InstrumentFieldsMiddleware``` from the DI container as well as Schema, we get all the metrics alongside with data.
Then, we create a ```InstrumentFieldsMiddleware``` and register the Middleware, then also we get the same result.
We do not get anything specific by making this custom material. Then what is the use of making this custom middleware?

**Comment by Shane32** [comment]
I’m not sure what you’re trying to accomplish. If you just want the Apollo Tracing data generated and added to the result, just call AddApolloTracing. Custom middleware would be used if you want to do something non-standard.

**Comment by Hemant2384** [comment]
Okay, So, I will ask this, Can you please help me by demonstrating an output that how does the ```Custom Middleware``` from the ```IFieldMiddleware``` does something in different on-standard way. From, writing the middleware to getting the execution details along side with the data. And how the non-standard execution details we get in the output is from our ```Custom Middleware```. I am not that good in .NET, so, please if you could manage some time and help me.

**Comment by Shane32** [comment]
It will be easier to provide an example if you can state what it is that you want to accomplish. 

Otherwise just copy the three code snippets I previously linked, rename the methods/classes, and start changing it as you desire.

**Comment by Shane32** [comment]
I really don’t know what good uses for field middleware exist. Tracing data generates too much data for logging. It seems to me that a Apollo Tracing exists generally just for diagnostic purposes, and middleware supports Apollo Tracing. 

Perhaps there could be some weird situation where you wanted to catch a particular exception and then retry the field or return null instead of using the unhandled exception delegate. 

Perhaps you might want to monitor for a certain condition and write some data to the debug window (which I already provided a sample for). 

Perhaps you’d want to generate Apollo Tracing data for certain IPs or situations and log it, if you were trying to track down a slow query.

**Comment by Hemant2384** [comment]
Okay, Thankyou so much  .
