### ISSUE TITLE
Avoid "same GraphType name" exception 

### ISSUE THREAD

**Issue by dgmoex** [graphql-dotnet/graphql-dotnet#3215]
Hello.

I update GraphQL from 2.4.0  to 4.7.1
I have two scheme Admin and Public
and use two types

```
public class MyEntityPublicType : ObjectGraphType<MyEntity>
witn this.Name = "myEntity"
```

and

```
public class MyEntityAdminType : ObjectGraphType<MyEntity>
with this.Name = "myEntity"
```

after update I have broken introspection and exception 

> Unable to register GraphType 'MyEntityAdminType ' with the name 'myEntity'. The name 'myEntity' is already registered to 'MyEntityPublicType '. Check your schema configuration.

There ara a lot of using name type "myEntity" in client code, i can not set unique name for each type and actualize all client code.
1) How I can restore old behavior?
2) Maybe I can disable this validation?
3) Maybe I can register each type at only corresponding scheme?
MyEntityPublicType  at Public scheme
MyEntityAdminType  at Admin scheme

Best regards, 
DG

**Comment by sungam3r** [comment]
Single schema can not have two graph types with the same name. Such schema is not compatible with GraphQL spec. It is a bug in 2.x that lead to weird runtime errors. This bug was fixed a long time ago.

> Maybe I can register each type at only **corresponding** scheme.

What do you mean corresponding?

**Comment by dgmoex** [comment]
corresponding i.e. register 
MyEntityPublicType only for Public scheme 
and 
MyEntityAdminType only for Admin scheme

**Comment by dgmoex** [comment]
now i do
services
                .AddGraphQL()
                .AddSelfActivatingSchema<AdminSchema>()
                .AddSelfActivatingSchema<PublicSchema>()
                .AddDataLoader()
                .AddDocumentListener<DataLoaderDocumentListener>()
                .AddGraphTypes()
                .AddNewtonsoftJson();

**Comment by Shane32** [comment]
@dgmoex It sounds like you have two different schemas, with one using MyEntityPublicType and one using MyEntityAdminType, correct?  The problem is not that both of the graph types are being registered within DI; the problem is that within one of your two schemas, there is a reference to both of the two different graph types.

**Comment by dgmoex** [comment]
it seems you are right, [Shane32](https://github.com/Shane32). Are there simple algo to find MyEntityPublicType node into Admin Schema? May be exist solution for visualize very complex scheme?

**Comment by sungam3r** [comment]
Iterate through all types and for all fields of type and compare field's type with `MyEntityPublicType`. Or open GraphQL Playground and download SDL .
