### ISSUE TITLE
Subscriptions Example

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#322]
How I can implement subscriptions with this library on the back-end?
Is this going to tell the client when some event happens?
Or this is not ready yet?

**Comment by joemcbride** [comment]
Please see #186

**Comment by Jonatthu** [comment]
@joemcbride Well it seems no example is available yet, but is this in theory working?

**Comment by joemcbride** [comment]
Yes this should in theory be working.

**Comment by joemcbride** [comment]
Going to go ahead and close this one.
