### ISSUE TITLE
Could not load type 'GraphQL.Server.Transports.AspNetCore.IGraphQLRequestDeserializer

### ISSUE THREAD

**Issue by eddyjl077** [graphql-dotnet/graphql-dotnet#3229]
System.TypeLoadException: 'Could not load type '### **GraphQL.Server.Transports.AspNetCore.IGraphQLRequestDeserializer**' from assembly 'GraphQL.Server.Transports.AspNetCore, Version=**6.1.0.0**, Culture=neutral, PublicKeyToken=null'.'

![image](https://user-images.githubusercontent.com/20169438/179227254-e94a9a73-dd2c-4ea8-8a3f-2d7843080baa.png)

**Comment by Shane32** [comment]
Please provide a list of nuget packages you have referenced.

**Comment by Shane32** [comment]
Please remove these references:
```
    <PackageReference Include="GraphQL.Server.Core" Version="5.2.1" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.2.1" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore.NewtonsoftJson" Version="5.2.1" />
```
