### ISSUE TITLE
Default Value on arguments not working

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#323]
Maybe this is not the right way of usage

```
                    var list = new List<User>();
                    int? id = context.GetArgument<int?>("id", defaultValue: 9999);

                    list.Add(new User { Id = id.Value });

                    return list;
```

But this is not getting the value 9999 and is giving me a null.

**Comment by jquense** [comment]
yeah this is a bit confusing. the default value is used when the argument doesn't exist at all in the query, not when it's empty. e.g `null` is considered a value here.

**Comment by Jonatthu** [comment]
Yes I know I'm not sending any argument in the query that's why, I'm going to do testing to validate this

**Comment by jquense** [comment]
Ya if you put together an example of that not working we can troubleshoot a bit more
