### ISSUE TITLE
Feature Request: skip empty / null fields

### ISSUE THREAD

**Issue by negue** [graphql-dotnet/graphql-dotnet#325]
I have some fields which mostly have `null` as a value, but it would be nice to skip them for each entry. 

Already tried to use the JsonSerializerSettings like:

```csharp
new JsonSerializerSettings
{
   NullValueHandling = NullValueHandling.Ignore,
   DefaultValueHandling = DefaultValueHandling.Ignore,
}
```

But that doesn't work since the data object (and every layer down) is a Dictionary, and on those the `NullvalueHandling` doesn't work.

**Comment by joemcbride** [comment]
I'm pretty sure that skippping null fields would be contrary to the GraphQL spec, so I don't think this is a feature that will be added.  If the user requests a field, as long as that field exists and null is a return value then it will be returned.

**Comment by negue** [comment]
Hmm, I see.

I just had the idea so that I don't have to transfer all null fields to the client, to speed up the network request

**Comment by joemcbride** [comment]
Going to go ahead and close this.

**Comment by jmsunseri** [comment]
Does this mean you are actively ignoring the JsonSerializationSettings?  

app.UseGraphQL<GraphSchema>("/graphql", x => {
                 x.NullValueHandling = NullValueHandling.Ignore; 
            });

I seem to still be getting null values for some fields even after doing this

**Comment by sungam3r** [comment]
These settings used to **deserialize** GraphQL request, not for **serialize**. You point to method from server project. [DocumentWriter](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Http/DocumentWriter.cs) serializes json response.
