### ISSUE TITLE
Where has Subscriber gone when defining a Subscription?

### ISSUE THREAD

**Issue by AndyEdmonds** [graphql-dotnet/graphql-dotnet#3251]
The documentation for the upgrade from 4 to 5 says in section 34

"Please use FieldType instead. The Subscriber property has been moved to the FieldType class so no other changes should be required. The AsyncSubscriber property has been removed as described above."

FieldType does not have a "Subscriber" property.

**Comment by Shane32** [comment]
It’s called StreamResolver now. We need to fix the migration document on that.
