### ISSUE TITLE
When using variables throws error

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#326]
https://github.com/graphql-dotnet/graphql-dotnet/issues/260
I was looking this issue but the answer and the docs are not very clear

I have this Field
```
            b.Field<UserType>(
                name: "user",
                description: "A user inside TyFitt",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<IntGraphType>> { Name = "id", Description = "The unique user id" }
                ),
                resolve: ctx => new User { Id = ctx.GetArgument<int>("id") }
            );
```

And this query

```
query user ($id: Int!) {
  user(id: $id) {
    id
    gymsOwned {
      name
      ownerId
      id
      clients {
        gymId
      }
    }
    address {
      city
    }
     
  }
}
```

QUERY VARIABLES

```
{
  "id": 3
}
```

And this throws in graphiQL

> SyntaxError: Unexpected end of JSON input

But with a query like this everything is OK

```
query user {
  user(id:3) {
    id
    gymsOwned {
      name
      ownerId
      id
      clients {
        gymId
      }
    }
    address {
      city
    }
     
  }
}

```

Which is not using variables, How can I configure the project or the field to accept this variables?

**Comment by joemcbride** [comment]
How are you passing your variables to the GraphQL .NET Engine?

[This is how the sample is doing it.](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Controllers/GraphQLController.cs#L60)

**Comment by Jonatthu** [comment]
Great! @joemcbride Can we put this on the docs? Or Is it already there?

**Comment by joemcbride** [comment]
This is what we currently have: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md#variables

Any suggested additions?

**Comment by Jonatthu** [comment]
I will do a pull request of getting started @joemcbride for now I will close this issue thanks!
