### ISSUE TITLE
Unable to debug my controller code

### ISSUE THREAD

**Issue by kikshore** [graphql-dotnet/graphql-dotnet#3266]
Hello ,

I have created a graphql api sometime back using the ASP .NET MVC Web Api (.net core 3.1 )  . The code always worked really well . Now after a long time I plan to update it with some new code for which I started testing it again .

To my surprise I am unable to debug the code . The break point in the controller does not get hit at all.  I remember the Post method working and then moving to the Query class . Looks like the code in the controller is not even getting executed.

Startup.cs
Configure Services Method
```
            //names changed
	      services.AddSingleton<ISchema, Schema1>();
	       services.AddSingleton<Query>();
               services.AddSingleton<Type1>();
               services.AddSingleton<Type2>();

 

                    services.AddGraphQL(options => { options.EnableMetrics = false; })
                    .AddSystemTextJson()
                    .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true)
                    .AddDataLoader();           


            services.AddMvc(options => options.EnableEndpointRouting = false);

```

Controller
 ```
public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
        {
            
            Inputs inputs = query.Variables;

            var result = await new DocumentExecuter().ExecuteAsync( _options=>
            {
                _options.Schema = schema; 
                _options.Query = query.Query;
                _options.OperationName = query.OperationName;
                _optionsInputs = inputs;
                
            });


            if (result.Errors?.Count > 0)
            {
                return BadRequest(result.Errors);
            }

            
            return Ok(result);
```

Query Class Constructor

```
	
 public Query()
        {
            Field<ListGraphType<Type1>>(
            "type1s",
             
             resolve: context =>
                                {

                                     
                                    using var serviceScope = context.RequestServices.CreateScope();
                                    var provider = serviceScope.ServiceProvider;
                                    var DbContext = provider.GetRequiredService<DbContext>();

                                    var type1data = DbContext.....//db logic
                                    return type1data;



                                });


        

        }

```

        

please help.

Thanks
Kishore

**Comment by sungam3r** [comment]
> Looks like the code in the controller is not even getting executed.

If so most likely this is the problem before any code from this project. Turn on switch in your IDE to show all exceptions. Maybe this helps to understand what is going wrong.

**Comment by Shane32** [comment]
Typically I find this problem to be due to DI issues; very possibly the schema is throwing an exception while being initialized.

One thing I often try is to add something like this to the Startup.cs file:

```cs
app.ApplicationServices.GetRequiredService<ISchema>().Initialize();
```

If there's an issue it will throw an exception on that line of code and the application will fail to start.

**Comment by kikshore** [comment]
Thank you for the quick response .But the query is returning the desired results . If there were an exception it shouldn't tight !?

**Comment by kikshore** [comment]
> Typically I find this problem to be due to DI issues; very possibly the schema is throwing an exception while being initialized.
> 
> One thing I often try is to add something like this to the Startup.cs file:
> 
> ```cs
> app.ApplicationServices.GetRequiredService<ISchema>().Initialize();
> ```
> 
> If there's an issue it will throw an exception on that line of code and the application will fail to start.

I added the line to the Configure Method in StartUp and it worked without any issues.

**Comment by Shane32** [comment]
I guess I don’t understand your issue if everything is working correctly ….

**Comment by kikshore** [comment]
Hi Shane ,
The issue is that if I put a breakpoint in my [POST] action method , it is never hit . Any changes I make to my controller , I am not able to debug.

Thanks.

**Comment by Shane32** [comment]
Do you have anything in your startup like app.UseGraphQL or MapGraphQL ?   (Besides AddGraphQL)

**Comment by sungam3r** [comment]
The idea is that you configure GraphQL execution engine **twice** - within controller mentioned above and somehow else so control flow does not fall into your controller but in general everything just works.

**Comment by sungam3r** [comment]
Closed due to inactivity.
