### ISSUE TITLE
More context for IDocumentCache

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3267]
I want to cache only those documents that come via APQ. In the general case, the cache can grow quickly if you cache all incoming requests. All that I need is to look into `ExecutionOptions.Extensions` and check `persistedQuery` key but `IDocumentCache` has not access to extensions. My first thought was to change `string query` to `ExecutionOptions option` (and maybe in `SetAsync` as well) but it looks not good. Other thoughts? ping @Shane32

**Comment by sungam3r** [comment]
Second option - add new interface like 
```c#
public interface IDocumentCache2 : IDocumentCache
{
    bool IsCachable(ExecutionOptions options);
}
```

and modify this line:
`if (document == null && (document = await _documentCache.GetAsync(options.Query!).ConfigureAwait(false)) != null)`
casting `_documentCache` to `IDocumentCache2` and calling `IsCachable`. Dirty solution but non-breaking.

**Comment by Shane32** [comment]
My first thought is that the cache should be implemented entirely as IConfigureExecution and we can remove IDocumentCache. But there’s more to consider. I’ll look later tonight

**Comment by sungam3r** [comment]
Interesting. It may be a bit complicated thought.
