### ISSUE TITLE
how to query a relation 

### ISSUE THREAD

**Issue by zimmybln** [graphql-dotnet/graphql-dotnet#328]
Hi,

assuming I have a query like this

```javascript
query {
    typeA {id: 1)
    {
      field1
      field2
      typeB
       {
          idoftypeA
         field3
         field4
        }
    }
```

TypeB is suptype of TypeA with a field reference _idoftypeA_.

I define a query like this:

``` csharp
public class TypeAQuery : ObjectGraphType
{
   public TypeAQuery()
   {
      Field<ListGraphType<TypeA>>("typeA", arguments:..., resolve: ResolveTypeA);
      Field<ListGraphType<TypeB>>("typeB", resolve: ResolveTypeB); // no arguments here for typeB ?
   }

   public IEnumerable<TypeA> ResolveTypeA(....)
   {
   }

   public IEnumerable<TypeB> ResolveTypeB(...)
   {
   }
}
```
As long as I query only TypeA or TypeA with parameters it works fine. I can access the query arguments and return valid data. But I can't resolve TypeB. How do I know from which TypeA instance it comes for selecting valid data of TypeB with relation to a datarow of TypeA?

Best regards,
Torsten

**Comment by joemcbride** [comment]
I'm pretty sure you should be able to check the `Source` property in your resolve method.  `TypeA` should get resolved and passed down to the `TypeB` resolver.

**Comment by zimmybln** [comment]
Hi Joe,

thanks for your reply. Meanwhile I found it, I should have use the resolver for TypeB in TypeA instead of the resolver within the query type. Everything is fine.

Best regards,
Torsten
