### ISSUE TITLE
Fix tests for .NET 6.0.400 SDK

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3280]
Api approvals broke with the .NET 6.0.400 SDK released today.  Not sure why; they run fine on my PC.  For some reason it would seem that the api approvals generate differently on Linux than Windows under 6.0.400

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/pull/3278#discussion_r941908993_

**Comment by sungam3r** [comment]
Waiting for https://github.com/PublicApiGenerator/PublicApiGenerator/pull/247

**Comment by sungam3r** [comment]
Not actual anymore.
