### ISSUE TITLE
How to use Custom Directives

### ISSUE THREAD

**Issue by arianmotamedi** [graphql-dotnet/graphql-dotnet#329]
I noticed that the library supports custom directives, but I'm not entirely sure how to get the document executor to include my custom directive and apply it automatically. Let's say I have a class like this:

`public class ToUpperDirective : DirectiveGraphType
{
	public ToUpperDirective()
		: base("toUpperCase", new[] { DirectiveLocation.Field })
	{
	}
}`

and add it to my Schema like this:

`var directives = new List<DirectiveGraphType> {new ToUpperDirective()};
directives.AddRange(schema.Directives);
schema.Directives = directives;`

Where should I write the code to look for this directive per field and apply a method (.ToUpper()) on it?

**Comment by joemcbride** [comment]
For custom directives you do the check in the field resolver using the `FieldAst` field on the `ResolveFieldContext`.  You could do a "generic" implementation by using [field middleware](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md#field-middleware).

**Comment by joemcbride** [comment]
Here's an example of checking directive values: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L849-L863

**Comment by arianmotamedi** [comment]
Thanks Joe. I'm having a hard time figuring out the actual value of a field during resolution. Does a Field Middleware have access to the values? Or at what point does it get called? In my example I'm trying to run a .ToUpper() on a field if it has that directive, but obviously that can't happen until after the value is obtained...

**Comment by joemcbride** [comment]
Here's a basic example:

```csharp
public class ToUpperDirectiveFieldMiddleware
{
    public async Task<object> Resolve(
        ResolveFieldContext context,
        FieldMiddlewareDelegate next)
    {
        // the next delegate calls into the "next" child middleware
        var result = await next(context);
        // check context.Field.Directives + context.Variables to determine if
        // a directive is being applied
        // see the GetArgumentValues method in DocumentExecutor
        var uppercase = false;
        return uppercase ? result.ToString().ToUpper() : result;
    }
}
```

**Comment by arianmotamedi** [comment]
That makes sense. One final question, how can I register this middleware class now? In your example (https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md#field-middleware), you're just using `FieldMiddleware.Use<InstrumentFieldsMiddleware>()`, but the `Use()` method in my DocumentExecutor has a different method signature: `IFieldMiddlewareBuilder Use(Func<FieldMiddlewareDelegate, FieldMiddlewareDelegate> middleware);`

**Comment by joemcbride** [comment]
Its probably in the wrong namespace right now, but that extension method is here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Instrumentation/FieldResolverBuilderExtensions.cs#L13

**Comment by arianmotamedi** [comment]
Awesome, thank you sir! Much appreciated.

**Comment by joemcbride** [comment]
Going to go ahead and close this.  Re-open if needed.  Thanks!

**Comment by petrovic-ivan** [comment]
I am little confused now. Can we register custom directives in schema or we need to use middleware? I don't understand exactly.

My directive is same:
```
    public class ToUpperDirective : DirectiveGraphType
    {
        public ToUpperDirective() : base("toUpperCase", new[] { DirectiveLocation.Field })
        { }
    }
```

I added directive to schema like this:

```
   var directives = new List<DirectiveGraphType> { new ToUpperDirective() };

   Directives = directives;
```
In query field I tried to resolve like this:

```
public class Feature1Query : OperationQuery
    {        
        public Feature1Query()
        {
            Name = "Feature1Query";

            this.Field<SubFeatureQuery>(
              "SubFeatureQuery",
              "This is sample for concrete query.",
              resolve: context =>
              {
                  var directive = context.FieldAst.Directives.Find("toUpperCase");
                  return context;
              }
            );

        }
    }
```
My query is like this:
```
query ConcreateQuery {
  Feature1Query {
    SubFeatureQuery {
      testQuery @toUpperCase
    }
  }
}
```
In query intellisense can recognizes my directive and I am able to execute query.

But in my field resolver this line of code return `null`:
` var directive = context.FieldAst.Directives.Find("toUpperCase");`

Am I using this correctly?

**Comment by denisedelbando** [comment]
> Here's a basic example:
> 
> ```cs
> public class ToUpperDirectiveFieldMiddleware
> {
>     public async Task<object> Resolve(
>         ResolveFieldContext context,
>         FieldMiddlewareDelegate next)
>     {
>         // the next delegate calls into the "next" child middleware
>         var result = await next(context);
>         // check context.Field.Directives + context.Variables to determine if
>         // a directive is being applied
>         // see the GetArgumentValues method in DocumentExecutor
>         var uppercase = false;
>         return uppercase ? result.ToString().ToUpper() : result;
>     }
> }
> ```

this helped me solve the error handler. thank you
