### ISSUE TITLE
do u need any help updating downstreams?

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-dotnet#3292]
```
  SampleWeb.csproj: [NU1608] Detected package version outside of dependency constraint: 
GraphQL.Server.Transports.AspNetCore 6.1.1 requires GraphQL (>= 5.3.0 && < 6.0.0) but version GraphQL 7.0.0 was resolved.
```

**Comment by Shane32** [comment]
I’ll have the updated server project released within a few hours. Help with the other projects (conventions, authorization or relay) projects would be appreciated if you use any of those projects. Note that Server included its own authorization validation rule which has been updated already.

**Comment by Shane32** [comment]
FYI since IValidationRule has changed, the authorization project is sure to break. Not sure about the other projects.

**Comment by SimonCropp** [comment]
conventions: https://github.com/graphql-dotnet/conventions/pull/233

**Comment by sungam3r** [comment]
I think all downstreams were updated and released. Closing.
