### ISSUE TITLE
FieldBuilder no longer works  with Field<Type>().Name("foo")

### ISSUE THREAD

**Issue by cotillion** [graphql-dotnet/graphql-dotnet#3293]
## Description

There is no longer an overload for Field which takes 0 arguments. We used this version of the FieldBuilder extensively unfortunately. Was this removal intentional?

```
Field<Type>().Name("foo").Resolve(...
``` 

It seems it was removed in f1f8348c0f8ae45b71f06688dfd4dde2338d5f05

### Expected result

Either a gradual deprecation or continued functionalty

### Actual result

error CS1501: No overload for method 'Field' takes 0 arguments 

### Environment

7.0.0

**Comment by Shane32** [comment]
It was likely unintentional, as we intended all existing code to function in this regard.  I'll look into this.

**Comment by sungam3r** [comment]
It was intentional indeed. I reasoned that **any** field declaration should always specify field name. Could you just use 'find and replace' feature of your IDE to change all calls from `Field<Type>().Name("foo")` to `Field<Type>("foo")` ?

**Comment by sungam3r** [comment]
Moreover I wanted to remove default value from ` public virtual FieldBuilder<TSourceType, TReturnType> Field<TGraphType, TReturnType>(string name = "default")` but something went wrong. I don't remember.

**Comment by Shane32** [comment]
7.0.1 released with the method restored
