### ISSUE TITLE
Generating description automatically from xml comments

### ISSUE THREAD

**Issue by wakuflair** [graphql-dotnet/graphql-dotnet#3297]
For GraphType First approach, is there a way to generate description from xml comments?

I know I can use `Description` attribute to generate the description, but it's much better to use the xml comments.

From 
``` csharp
public Class Person
{
  /// <summary>
  /// The name of the person
  /// </summary>
  public string Name {get; set;}
}
```

To  
``` json
...
"fields": [
        {
          "name": "name",
          "description": "The name of the person"
        }
      ]
```

It's exactly the same as https://github.com/ChilliCream/hotchocolate/issues/715

**Comment by Shane32** [comment]
Yes it's a global switch.

https://graphql-dotnet.github.io/docs/getting-started/global-switches

**Comment by wakuflair** [comment]
I can't believe I missed it.
