### ISSUE TITLE
Dependency injection?

### ISSUE THREAD

**Issue by tlycken** [graphql-dotnet/graphql-dotnet#33]
I'm really excited that this project exists, and I'm hoping to get an opportunity to make use of it - and thereby also make time to help - at some point. For now, though, I'm just toying around to see where I can get with it :)

I've noticed a lack of DI in the examples - `var data = new StarwarsData()` is used in a bunch of places. 
What I'd like to accomplish, is basically to send dependencies (like data stores) as constructor arguments to the various types that need them for resolving things, e.g. 

```
    public class StarWarsQuery : ObjectGraphType
    {
        public StarWarsQuery(IDataReader data)
        {
            Name = "Query";
            Field<CharacterInterface>("hero", resolve: context => data.GetDroid(id: 3));
        }
    }
```

And, of course, the `data` parameter here could be just passed-through to wherever it's needed for resolving more stuff.

Are there any plans for DI support in the future? Perhaps it's already possible, but not shown off in the examples?

**Comment by joemcbride** [comment]
The example you show is possible.  The types will get resolved through the [`Schema.ResolveType`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Schema.cs#L11) func.  Replace that property with a call to your container.

**Comment by tlycken** [comment]
Hm. You mean something like

    public class StarWarsSchema : Schema
    {
        public StarWarsSchema(IContainer container) {
            ResolveType = type => container.Resolve(type);
        }
    }

and then injecting also the schema into wherever I need it? This would mean I have to register the container with itself, which seems a little smelly, but way better than not being able to do anything like this at all :)

**Comment by joemcbride** [comment]
Something like that, yes.  Instead of using your container directly you can use a "service locator" instead, though it essentially the same idea.

Instead of having a func on the Schema that could be changed to a service locator that is injected, though it is basically the same outcome (and that service locator would still need to be registered with your container).

Open to suggestions on how to make it better.

**Comment by tlycken** [comment]
Well, there's a number of reasons I don't want to use a service locator - [this](http://blog.ploeh.dk/2015/10/26/service-locator-violates-encapsulation/) is a good read on the topic, but you might want to start [here](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/).

It would probably be possible to use a factory pattern, or - better yet - to utilize `System.Func` as a parameter, but I'd have to think on it for a while to come up with something that might actually work.

**Comment by joemcbride** [comment]
I am aware of the dislike of service location patterns.  I didn't want dependency injection to be required to use the library, though I did want to support it.  This is why the property is a `System.Func`.  Having an overloaded `ctor` that accepted the func would be easy to add.

**Comment by tlycken** [comment]
Yeah, that would probably be a good solution - that would let any DI container do the job, even if they don't support property injection. (Some DI containers can even auto-register `Func`s that act as factories for registered types, making that even more attractive...)

**Comment by joemcbride** [comment]
I'll add the `ctor` overload.  I had thought about putting a `Get<T>` on the resolve context you are given, though that is closer to that service locator pattern which is considered bad.  With the func as is, you can just add your dependencies to the `ctor` of your `GraphType` as you demonstrated.

**Comment by tlycken** [comment]
That sounds like a good plan!

It might also be worthwhile to extract some interfaces on the schema types, to make container registration easier.

**Comment by joemcbride** [comment]
I agree on the interfaces thing.  In #14 there may be a fairly big re-name of types, which is when we'll add in some additional interfaces.

**Comment by ManishTrivedi** [comment]
@joemcbride I am fairly new to GraphQL. As per my understanding, there should be only one query class. So, if I get data from multiple classes, like StarWarsData, how will I initialize it in the StarWarsQuery class. Number of parameters in the StarWarsQuery class will keep on increasing right? I might be completely wrong.

**Comment by joemcbride** [comment]
@ManishTrivedi There is only one root query object per schema.  You can setup multiple schemas in your GraphQL server and send additional metadata as per which schema should be used.

Instead of injecting the data class directly into the top level object, you can still have child graph types use dependency injection.  Both the [`DroidType`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/StarWars/DroidType.cs) and `HumanType` do this.

**Comment by ManishTrivedi** [comment]
@joemcbride It would be great if you can share your thoughts on these issues:

1. We register all the types and queries in the GraphQL controller constructor. What if I have 100 types in my system. Will I be registering all in this controller or can I have multiple controllers?

2. Should I be using Factory method pattern to decide which schema should be used based on the metadata.

3. Can you please elaborate on what do you mean by top level object in the above comment. If I have StarWarsData.cs and many other data classes, my StarWarsQuery constructor would look like this StarWarsQuery(StarWarsData data, .............. ). I am confused about the dependency injection in the Query class.

Please help!

**Comment by joemcbride** [comment]
@ManishTrivedi Please do not post on closed issues with questions not related to those specific issues and commits.  Please create a new issue with your question.  You may also get a faster reply if you post on stackoverflow with questions about general programming topics.
