### ISSUE TITLE
GraphQL ' SQL JOIN statement' policy question

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#330]
Is GraphQL not 'JOIN xTable' friendly by design?
Or is this implementation not friendly and this should in the future find a way to do joins?

Also I do not want to skip my service layer (business logic), so in conclusion...

Should I forget using JOIN's in SQL using GraphQL? And
How that will affect to my network in a SQL Server getting to many request because is getting more trips?

**Comment by joemcbride** [comment]
GraphQL is originally designed around calling into your service layer and/or other REST services and aggregating those into a single service.  There are a few GraphQL projects out there that convert your GraphQL query into direct SQL commands, though this project is not one of them.  There are many discussions around solving N+1 queries with a service layer.

See a few of these links:

#264 
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md#query-batching
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md#projects-attempting-to-solve-n1
https://github.com/facebook/dataloader

**Comment by Kurren123** [comment]
Hi @joemcbride, thanks for your reply. I want to use graphql-dotnet's query batching but the example isn't very easy to follow because it assumes knowledge of marten. Is there a simpler example, using e.g. Entity framework's [include](https://msdn.microsoft.com/en-us/library/jj574232(v=vs.113).aspx) method? I think more people would familiar with that rather than marten.

**Comment by joemcbride** [comment]
@Kurren123 I haven't used EF for years so I'm not sure I can be of much help there.  As far as I understand it, I'm not sure that just using `Include` will get you query batching though.  The above links point to a [DataLoader for GraphQL .NET](https://github.com/dlukez/graphql-dotnet-dataloader) project which does use EF as an example if that is helpful.

**Comment by joemcbride** [comment]
I'm going to close this, re-open if needed.  Thanks!

**Comment by ceferrari** [comment]
I have made an extension method that converts the GraphQL Query into Entity Framework Includes.

```
public static class ResolveFieldContextExtensions
{
    public static string GetFullIncludeString(this ResolveFieldContext<object> source)
    {
        return string.Join(',', GetIncludePaths(source.FieldAst));
    }

    private static IEnumerable<Field> GetChildren(IHaveSelectionSet root)
    {
        return root.SelectionSet.Selections.Cast<Field>().Where(x => x.SelectionSet.Selections.Any());
    }

    private static IEnumerable<string> GetIncludePaths(IHaveSelectionSet root)
    {
        var q = new Queue<Tuple<string, Field>>();
        foreach (var child in GetChildren(root))
        {
            q.Enqueue(new Tuple<string, Field>(child.Name.ToPascalCase(), child));
        }

        while (q.Any())
        {
            var node = q.Dequeue();
            if (GetChildren(node.Item2).Any())
            {
                foreach (var child in GetChildren(node.Item2))
                {
                    q.Enqueue(new Tuple<string, Field>(node.Item1 + "." + child.Name.ToPascalCase(), child));
                }
            }
            else
            {
                yield return node.Item1;
            }
        }
    }
}
```

Lets say we have the following query: 

```
query {
  getHistory {
    id
    product {
      id
      category {
        id
        subCategory {
          id
        }
        subAnything {
          id
        }
      }
    }
  }
}
```

We can create a variable in "resolve" method of the field:

`var include = context.GetIncludeString();`

which generates the following string:

`"Product.Category.SubCategory,Product.Category.SubAnything"`

and pass it to Entity Framwork:

```
public Task<TEntity> Get(TKey id, string include)
{
    return _db.Set<TEntity>().Include(include).SingleOrDefaultAsync(c => c.Id.Equals(id));
}
```
