### ISSUE TITLE
ULong returned from the API is rounded up

### ISSUE THREAD

**Issue by georgiosd** [graphql-dotnet/graphql-dotnet#3303]
## Description

An object property of type `ulong` automatically mapped with GraphQL.NET, is rounded up!

Specifically, `4512823269514208799` is served as `4512823269514209000`.

### Steps to reproduce

```
public class Foo
{
  public ulong Prop { get; set; } = 4512823269514208799;
}

public class FooGraphType : ObjectGraphType<Foo>
{
  public FooGraphType()
  {
    Field(x => x.Prop);
  }
}
```
Define a query that will return a `Foo`.

### Expected result

`Prop = 4512823269514208799`

### Actual result

`Prop = 4512823269514209000`

### Environment

.NET 6 on Windows.

**Comment by Shane32** [comment]
What environment are you using to call the graphql api from?

**Comment by Shane32** [comment]
If it is a web browser, use F12 to view the network trace of the data returned by the GraphQL endpoint.  Please check the number in the raw data log.  I believe you will find that the number is accurate.  However, within the Javascript language (which includes Node), numbers always are of a double-precision data type.  Javascript numbers simply cannot contain the precision of a 64-bit integer.

To demonstrate, try running this javascript code:

```javascript
alert((4512823269514208799).toString());
```

It will always inaccurately print `4512823269514209000`.

However, if you call the GraphQL endpoint from a .NET environment, you should be able to recover the information as it was serialized without precision loss.

You may wish to switch to a string-based graph type (Id, String, or a custom graph type) if you need to call your API from a javascript client.

**Comment by georgiosd** [comment]
Ah yes, why didn't I think of that? 😠 

Indeed I was using GraphiQL and couldn't believe my eyes. 

Thank you!
