### ISSUE TITLE
not support  FindType, that type is created on the fly ??

### ISSUE THREAD

**Issue by IGOOA** [graphql-dotnet/graphql-dotnet#331]
I can not found the api (schema.FindType(Type type))  in latest release and it was in the release not v 0.9 
When a ListGraphType or NonNullGraphType type is requested via FindType, that type is created on the fly.

**Comment by joemcbride** [comment]
I believe this changed in this release: https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.14.0.633

With the release of instance-based schema creation.  This simplified the schema so that it would only store the "root" type and not deal with nonull/list types.
