### ISSUE TITLE
Auto register graphtype of deeply nested object

### ISSUE THREAD

**Issue by oscgu** [graphql-dotnet/graphql-dotnet#3310]
For example some DTO of a Lib I installed and can't directly edit

```csharp
public class A 
{
    public B b { get; set; }
    ...
}

public class B 
{
    public C c { get; set; }
    ...
}

public class C 
{
   ...
}
```

**Comment by Shane32** [comment]
I'm not sure what the question is.  You can map auto-registering graph types of the nested classes if you wish, which should work just fine, but the auto-registering graph types don't give you much flexibility when you do not have control over the definition of the types themselves.

If you need to customize a graph type of a class you do not have control of, it is typically better to create a graph type via code-first and specify each member as needed.

Please let me know if you have a specific question that pertains to this topic.

**Comment by oscgu** [comment]
Basically AutoRegisteringObjectGraphType<T> is not working for a deeply nested DTO, it always fails to map the property of the custom class. I'm not sure what the correct way to handle this is, since manually specifying the type is not an option due to the amount of fields and maintainability (because the DTO comes from a lib)

**Comment by Shane32** [comment]
Can you give a more precise example of something that is failing? Then we can provide a suggestion.

**Comment by wakuflair** [comment]
Hi @Shane32 
I have the same need. 

We use `AutoRegisteringObjectGraphType` a lot to avoid creating GraphType for our DTOs.
`AutoRegisteringObjectGraphType` works well for these DTOs contain only primitive types, but once contains another DTO type, the `AutoRegisteringObjectGraphType` failed to work and raise following error on document generating (taking @oscgu 's example):

```
The GraphQL type for field `A.b` could not be derived implicitly. Could not find type mapping from CLR type `XXX.B` to GraphType. Did you forget to register the type mapping the `ISchema.RegisterTypeMapping'?
```

Then we have to manually create a GraphQLType class for `A`, which is trivial.
So can `AutoRegisteringObjectGraphType` also auto register the nested type?

**Comment by Shane32** [comment]
No, it cannot.  However, you have two options:

1. Register the nested CLR type(s) to auto-registering graph types

```cs
services.AddGraphQL(b => b
    .ConfigureSchema(schema => schema.RegisterTypeMapping<Class1, AutoRegisteringObjectGraphType<Class1>>()));
```

This can also be done within the schema constructor.

```cs
this.RegisterTypeMapping<Class1, AutoRegisteringObjectGraphType<Class1>>());
```

2.  Register all unmapped CLR types to auto-registering types.

```cs
services.AddGraphQL(b => b
    .AddAutoClrMappings());
```

**Comment by wakuflair** [comment]
Thanks, `AddAutoClrMappings` works like a charm!

**Comment by Shane32** [comment]
Glad I could help

@oscgu Perhaps this solution is what you were looking for also.  Please re-open this issue if you have any further questions.
