### ISSUE TITLE
System.ArgumentOutOfRangeException: 'A field with the name 'Field' is already registered for GraphType

### ISSUE THREAD

**Issue by Xelit3** [graphql-dotnet/graphql-dotnet#3315]
Hi all,

I'm updating a project from version 4.6.1 to 7.0.2 and after having done some changes checked in the [migration guide](https://graphql-dotnet.github.io/docs/migrations/migration7/) I'm having some troubles that I'm not able to determine where is coming from and how to fix it.

I have the following data type:
```csharp
public class UserModel : ObjectGraphType<UserDbModel> 
    {

        public UserModel()
        {
            Field(t => t.Id);
            Field(t => t.UserName);
            Field(t => t.Email, nullable: true);
            Field(t => t.PhoneNumber, nullable: true);
            Field(t => t.Culture);
            Field(t => t.RegistrationDate);
            Field(t => t.IsActive);
        }
    }
```

These Queries (GraphQueryBase is an internal super class extending ObjectGraphType and encapsulating a generic repository taken from the IUnitOfWork):
```csharp
 public class UserQuery : GraphQueryBase<UserDbModel>
    {
        public UserQuery(IUnitOfWork unitOfWork)
            : base(unitOfWork)
        {
            Field<ListGraphType<UserModel>>("all")
                .Description("All users")
                .Resolve(context => _modelRepository.FromAll().ToList());

            Func<IResolveFieldContext, Guid, UserDbModel> func =
                (context, id) => _modelRepository.Find(id);


            Field<UserModel, UserDbModel>("single")
              .Argument<NonNullGraphType<IdGraphType>>("id", "Id of the user")
              .ResolveDelegate(func);
        }
    }
```

This schema:
```csharp
public class UserSchema : Schema
    {
        public UserSchema(IServiceProvider serviceProvider) 
            : base(serviceProvider)
        {
            Query = new AutoRegisteringObjectGraphType<UserQuery>();
        }
    }
```

And the configuration in startup:
```csharp
 services
  .AddGraphQL(b => b                
  .AddSchema<UserSchema>()
  .AddAutoClrMappings()
  .AddSystemTextJson());
```

The problem that I am facing is the following one:

> _**System.ArgumentOutOfRangeException: 'A field with the name 'Field' is already registered for GraphType 'UserQuery'**_ 
![image](https://user-images.githubusercontent.com/55638917/188374209-9dd14c0a-1af5-4035-af79-1976b3a8b19a.png)

For sure something is missing or I'm not properly understanding...

Any idea?

Many thanks in advance :)

**Comment by sungam3r** [comment]
It's simple - you use graph type for `AutoRegisteringObjectGraphType<UserQuery>` instead of "CLR type". Change `UserQuery` in generic argument to something else, that's all.

**Comment by sungam3r** [comment]
@Shane32 Maybe to throw exception inside `AutoRegisteringObjectGraphType<T>/AutoRegisteringInputObjectGraphType<T>` if `T` is `GraphType`?

**Comment by Shane32** [comment]
Good idea

**Comment by Shane32** [comment]
@Xelit3 you might have wanted `Query = serviceProvider.GetRequiredService<UserQuery>();`

I also suggest that you end your graph types with the name `GraphType` versus models with the name `Model`, as these representations are distinctly different -- think of graph types as configuration files for models.  For instance, your `UserModel` really is a graph type for the `UserDbModel` model, and should be called `UserGraphType`.  Graph types that end with "GraphType" will have the "GraphType" portion stripped from the GraphQL representation of the name.  So in the prior example, `UserGraphType` will have a default GraphQL name of `User`.

`AutoRegisteringObjectGraphType` creates a graph type for a model automatically.  So you could define your `UserGraphType` like this:

```cs
public class UserGraphType : AutoRegisteringObjectGraphType<UserDbModel>
{
    public UserGraphType()
    {
        // optional: additional customizations here
    }
}
```

Or as you are using `AddAutoClrMappings` already, the above class is not necessary if you do not plan to make any changes to the generated graph.

Finally, I also suggest calling `AddClrTypeMappings` so that if you do create any custom graph types like `UserGraphType`, they will automatically be used when creating fields elsewhere.  For example:

```cs
// without AddClrTypeMappings
Field<UserModel, UserDbModel>("single")
    .Argument<NonNullGraphType<IdGraphType>>("id", "Id of the user")
    .ResolveDelegate(func);

// with AddClrTypeMappings
Field<UserDbModel>("single")  // <-- do not need to specify graph type here
    .Argument<NonNullGraphType<IdGraphType>>("id", "Id of the user")
    .ResolveDelegate(func);
```

Without `AddClrTypeMappings`, when attempting to use the latter syntax, GraphQL.NET will map this to a default implementation of `AutoRegisteringObjectGraphType` due to the call to `AddAutoClrMappings` that you have, rather than your custom `UserGraphType` class (currently named `UserModel`).

**Comment by Shane32** [comment]
> @Shane32 Maybe to throw exception inside `AutoRegisteringObjectGraphType<T>/AutoRegisteringInputObjectGraphType<T>` if `T` is `GraphType`?

See:
- #3316

**Comment by Xelit3** [comment]
Dear @Shane32 and @sungam3r .

Many thanks both for your support and specially for the long and detailed explanation given by @Shane32 , it helped me to understand a bit better how it works and how to implement it.

Now I'm getting some problems aside of the initial question, since the base Base class is using a scoped interface (IUnitOfWork) inside (and also registering UserQuery as scoped), I'm having problems with the DI container, properly saying that I cannot resolve a scoped  service from root provider...

```csharp
public class GraphQueryBase<T> : ObjectGraphType
    where T : class
{

    protected readonly IRepository<T> _modelRepository;


    public GraphQueryBase(IUnitOfWork unitOfWork)
    {
        _modelRepository = unitOfWork.GetRepository<T>();
    }

}
```

Since the problem is not related to the initial question, I will try to fix it aside of this, but if you have more suggestions in order to improve my project's structure/code I'll be glad to read it!

Many many thanks!

**Comment by Xelit3** [comment]
UPDATE:

Some minutes later, I fixed changing the scope registering the Schema:

> .AddSchema<UserSchema>(GraphQL.DI.ServiceLifetime.Scoped)

Many many thanks guys again

**Comment by Shane32** [comment]
I strongly recommend you read this documentation on usage of scoped services:

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection/#thread-safety-with-scoped-services

Of particular note, even though the schema is scoped (supported but not recommended), you will need to use a serial execution strategy, or you will very likely end up with concurrency issues within your scoped services.

**Comment by Shane32** [comment]
There is much other valuable information within the same link that discusses proper lifetime of graph types, etc.

**Comment by sungam3r** [comment]
Closed as answered.

Regarding #3316 and #3317. @Shane32 I'm now slowly climbing through the hundreds emails. In recent weeks, there was no time to do this.

**Comment by Shane32** [comment]
> Regarding #3316 and #3317. @Shane32 I'm now slowly climbing through the hundreds emails. In recent weeks, there was no time to do this.

No problem @sungam3r.  As always, I try to leave adequate time for a review before merging any PRs, but if there are no comments, I will make the best choice I can and move on.

**Comment by sungam3r** [comment]
So far I reviewed all merged PRs since the last time I checked my emails, ~140 left.
