### ISSUE TITLE
Graphql schema from Entityframework Core 

### ISSUE THREAD

**Issue by badre429** [graphql-dotnet/graphql-dotnet#332]
extract graphql schema from  Entityframework Core 
and if it is possible create a sample with (aspnet core + Entityframework core )

**Comment by joemcbride** [comment]
> extract graphql schema from Entityframework Core

I'm not sure what you're asking for.

>if it is possible create a sample with (aspnet core + Entityframework core )

Here is a link for an example that uses Entity Framework: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md#how-do-i-use-xyz-ormdatabase-with-graphqlnet

**Comment by badre429** [comment]
i meed Schema generator based [Entityframework core](https://github.com/aspnet/Entityframework) DbContext

**Comment by joemcbride** [comment]
A feature like that is beyond the scope of this core project.  The [conventions project](https://github.com/graphql-dotnet/conventions) should work with EF code-first.
