### ISSUE TITLE
Cannot use ValidateAsync in .NET 4.7.1

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#3322]
Hi,
I am trying to use GraphQL 7.0.2 in a .NET 4.7.1 application (netstandard2.0).

However, when I try to use ValidateAsync method I am getting this error:

![image](https://user-images.githubusercontent.com/5131689/189734111-2e0c754c-5cc2-4e7f-879a-99bed6b4399e.png)

C# language version for .NET 4.7.1 (netstandard2.0)  is 7.3 and GraphQL which is mutli-target solution, is using some features of newer C#.

I am wondering if you have any solution to this problem. 

Also, out of my curiosity,  how come GraphQL got compiled in first place with C# 9.0 features to target netstandard2.0 without compile tags?

Thanks.

**Comment by Shane32** [comment]
It is possible to use C# 9.0 code with .NET Framework -- just add a Directory.Build.props file containing:

```xml
<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

However, I realize this is an unsupported scenario for .NET Framework projects, and as such, we should not have used `init;` for the .NET Standard 2.0 compilation.  We simply did not realize this would be a problem -- Microsoft says the following:

> Property init accessors will be emitted as a standard set accessor with the return type marked with a modreq of IsExternalInit. 

(See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init#metadata-encoding )

As such the project should be binary-compatible with .NET Standard 2.0, so personally I would consider it a bug that VS 2022 prevents _use_ of init-only setters in C# 7.3 projects.  But perhaps there is a reason I do not fully understand here.

**Comment by sungam3r** [comment]
The problem looks weird. https://stackoverflow.com/questions/66491591/after-update-to-vs-16-9-0-feature-init-only-setters-is-not-available-in-c-sha

@rmeshksar What IDE and version do you use?

**Comment by sungam3r** [comment]
In my opinion the problem is in some version of compiler bundled with IDE and DLLs with init-only setters **may be** consumed by projects written for older NET platforms.

**Comment by Shane32** [comment]
@sungam3r By the way the MS docs say this also:

> If we want to make the change of `init` to `set` a source and binary compatible change then it will force our hand on the modreq vs. attributes decision below because it will rule out modreqs as a solution. 

Since they chose to use modreq, then it would seem that they knew that `set` would not be binary compatible.

**Comment by sungam3r** [comment]
> to prevent use by old compilers.

If I understand correctly VS 2022 (or of any other version) has single version of C# compiler (roslyn or csc.exe for old editions) that compiles all types of projecs - either netcore or NET Framework.

**Comment by sungam3r** [comment]
It will be a shame if the problem is in the bug in particular VS version and it was just possible to update it.
