### ISSUE TITLE
Execution Result Data is of type RootExecutionNode and not Dictionary

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#3325]
Hi,
We are in the process of migrating from GraphQL version 3.2 to 7.0.
Consider this code: 

```csharp
void Main()
{
	var schema = new Schema { Query = new TestQuery() };
	var exec = new DocumentExecuter();
	exec.ExecuteAsync(options =>
			{
				options.Schema = schema;
				options.Query = "{ test { prop1  } }";
			}
	).Result.Data.Dump();  
}

public class TestQuery : ObjectGraphType
{
	public TestQuery()
	{
		Name = "TestQuery";
		Field<TestResponseType>(name: "test",
			resolve: context => new TestResponse()
		);
	}
}

public class TestResponseType : ObjectGraphType<TestResponse>
{
	public TestResponseType()
	{
		Name = "TestReponse";
		Field<BooleanGraphType>("prop1");
	}
}

public class TestResponse
{
	public bool Prop1 { get; set; }
}
```

In GraphQL version 3.2, Data is dictionaty which is correct:
![image](https://user-images.githubusercontent.com/5131689/189925833-24d07192-cb53-4222-9223-c2ee99a3abaf.png)

However, exact same code in GraphQL version 7.0.2 returns RootExecutionNode:
![image](https://user-images.githubusercontent.com/5131689/189926026-b1217d01-30a4-4cec-b7b4-ce2deac31058.png)

Am I missing anything here?

**Comment by Shane32** [comment]
It is as designed.  You are required to use an `IGraphQLSerializer` implementation to serialize the data from the execution nodes into JSON (or any other format).  There are serializers provided for System.Text.Json and Newtonsoft.Json.  If you really need a dictionary, you can call `ToValue()` on the `RootExecutionNode` instance, or use a helper method like this one:

https://github.com/graphql-dotnet/graphql-dotnet/blob/80b966e4fa737b285aa1e68dd52b535cfa9c64a1/src/GraphQL.Tests/TestExtensions.cs#L14-L28

Note that this implementation is used solely for tests within GraphQL.NET, probably does not meet GraphQL spec as it relates to null handling.  (It should probably return `null` if `data == null`.)  Again, it is recommended to use one of the included serializer implementations, which provides better performance and is fully tested for things like property casing and data formats.  The serializer also supports `IErrorInfoProvider` for formatting errors properly within the JSON response.

**Comment by Shane32** [comment]
Please note the change is listed in the migration guide for 3.x to 4.x:

https://graphql-dotnet.github.io/docs/migrations/migration4#other-breaking-changes-including-but-not-limited-to

> `ExecutionResult.Data` format breaking changes. Both `GraphQL.NewtonsoftJson` and `GraphQL.SystemTextJson` serializers received the necessary changes to produce the same JSON as before. However, consumers using `ExecutionResult` instances directly most likely will not work correctly. Call `((ExecutionNode)result.Data).ToValue()` to return the data in the same format as 3.x (as a dictionary).

I suggest reading each of the applicable migration guides to help ease the transition.  I found when migrating my own projects that searching the migration guide for issues I ran into helped a lot.  We have worked hard to ensure that the migration documents are comprehensive and cover all breaking changes.

**Comment by rmeshksar** [comment]
Thanks for the reply. I read the migration notes but seems I missed this.
Appreciate your prompt response and help.
