### ISSUE TITLE
Add `IMetadataBuilder` interface

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3328]
In the next version of GraphQL.NET, perhaps the field and connection builders should implement `IMetadataProvider` so these methods can be removed.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/issues/3324#issuecomment-1244737081_

**Comment by sungam3r** [comment]
`IMetadataBuilder` ?

**Comment by Shane32** [comment]
I agree and was thinking along the same lines.

**Comment by sungam3r** [comment]
I think we talk about different things. Do you want to add **new** interface `IMetadataBuilder` (I thought it was just a typo) or implement **existing** one named `IMetadataProvider`?

**Comment by Shane32** [comment]
I would add `IMetadataBuilder` so that we don't have extension methods intended for _getting_ metadata mixed up in the builder class.  Also methods that use `IMetadataBuilder` would be (more likely) to return the builder type.

I have not tried a PR yet.  Perhaps it is not necessary.  Just a thought.

Note: the existing interface is actually named `IProvideMetadata`, I think.
