### ISSUE TITLE
Using Directives

### ISSUE THREAD

**Issue by zimmybln** [graphql-dotnet/graphql-dotnet#333]
I'm not sure if I use directives correctly, but it doesn't work (at least it looks like). 
```
query directivequery ($withTypeB : Boolean!) {
                            TypeA {
                                ...fields
                                TypeB @include(if: $withTypeB)
                                {
                                    ...
                                }
                            }
                        }
```
The value of `withTypeB` I give with the inputs field. Everything works but the directive has no effect. The data for TypeB are never included. When I use @skip as directive the data is ever includes, independend of which value I give. Looks like a bug, isn't?

Best regards,
Torsten

**Comment by akaSybe** [comment]
I would like to know how to use custom directives too

**Comment by jacksonveroneze** [comment]
I would like to know how to use custom directives too²

**Comment by PascalSenn** [comment]
See https://github.com/graphql-dotnet/graphql-dotnet/issues/860 for an example

**Comment by sungam3r** [comment]
@zimmybln Since the moment you created this issue, a lot of time has passed and many things have been changed and fixed. Also repo has a lot of tests for @skip and @include. If this issue is no longer actual, then let me know.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
