### ISSUE TITLE
Casing causes FieldsOnCorrectTypeError on mapped fields

### ISSUE THREAD

**Issue by GeertvanHorrik** [graphql-dotnet/graphql-dotnet#3331]
## Description

A type is registered like this.

```
public class MyObjectGraphType : ObjectGraphType<MyObject>
{
    public MyObjectGraphType()
    {
        Field(p => p.Id);
        Field(p => p.Name);
    }
}
```

There is also a generic wrapper that allows for skip, take and total to be added to any query (left out here for simplicity, added at the end to the unit tests).

The (dynamically generated) schema is using the camel case naming convention. 

When checking the schema (e.g. inspecting it via code, or via GraphiQL), it shows the correct lowercase members (applying camel case):

``` 
query {
  myObjects {
    data {
      id
      name
    }
    skip
    take
    total
  }
}

``` 

When executing this query, it shows this error:

``` 
{
  "errors": [
    {
      "message": "Cannot query field 'id' on type 'MyObject'. Did you mean 'Id'?",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "extensions": {
        "code": "FIELDS_ON_CORRECT_TYPE",
        "codes": [
          "FIELDS_ON_CORRECT_TYPE"
        ],
        "number": "5.3.1"
      }
    },
    {
      "message": "Cannot query field 'name' on type 'MyObject'. Did you mean 'Name'?",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "extensions": {
        "code": "FIELDS_ON_CORRECT_TYPE",
        "codes": [
          "FIELDS_ON_CORRECT_TYPE"
        ],
        "number": "5.3.1"
      }
    }
  ]
}
``` 

When checking the *introspection*, it returns this (seems the names are correct):

``` 
{
	"kind": "OBJECT",
	"name": "MyObject",
	"description": null,
	"fields": [
		{
			"name": "id",
			"description": null,
			"args": [],
			"type": {
				"kind": "NON_NULL",
				"name": null,
				"ofType": {
					"kind": "SCALAR",
					"name": "ID",
					"ofType": null
				}
			},
			"isDeprecated": false,
			"deprecationReason": null
		},
		{
			"name": "name",
			"description": null,
			"args": [],
			"type": {
				"kind": "NON_NULL",
				"name": null,
				"ofType": {
					"kind": "SCALAR",
					"name": "String",
					"ofType": null
				}
			},
			"isDeprecated": false,
			"deprecationReason": null
		}
	],
	"inputFields": null,
	"interfaces": [],
	"enumValues": null,
	"possibleTypes": null
}
```

**What could cause the schema to return it in camelCase, but the server validation requiring it in PascalCase?**

### Steps to reproduce

Hard to reproduce yet. I did write unit tests (see end of this post). This test case is a simplified version of a complex graphql schema, but somehow I cannot find why it's not applying the naming convention correctly here.

### Expected result

I would expect the query to return the correct results.

### Environment

GraphQL 7.0.2
GraphQL.Server 7.1.1

### Unit tests

```

public class MyBugTest : QueryTestBase<Schema>
{
    private readonly Schema _schema;

    public MyBugTest()
    {
        var schema = new Schema
        {
            NameConverter = new CamelCaseNameConverter()
        };

        var queryGraphType = new ObjectGraphType
        {
            Name = "Query"
        };

        RegisterGenericQueryGraphTypes(schema, queryGraphType, "MyObject", "MyObjects");

        schema.Query = queryGraphType;

        _schema = schema;
    }

    [Fact]
    public void Camel_Case_Convention_Should_Work()
    {
        var query = @"
query {
  myObjects {
    data {
      id
      name
    }
    skip
    take
    total
  }
}";

        var expected = @"{
    ""myObjects"": {
      ""data"": [
        {
          ""id"": ""96b8c7b5-d542-4d70-a0cf-b0bbc0db119f"",
          ""name"": ""test1""
        },
        {
          ""id"": ""b405cb58-b966-4926-a989-90a76217af66"",
          ""name"": ""test2""
        }
      ],
      ""skip"": 0,
      ""take"": 10,
      ""total"": 2
    }
  }";
        AssertQuerySuccess(query, expected, null);
    }

    public override Schema Schema => _schema;

    private static void RegisterGenericQueryGraphTypes(Schema schema, ObjectGraphType queryGraphType,
        string singular, string plural)
    {
        var objectGraphType = new MyObjectGraphType();
        schema.RegisterType(objectGraphType);

        queryGraphType.Field<MyObjectGraphType>(singular)
            .Arguments(new QueryArguments(
                new QueryArgument(typeof(Guid?).GetGraphTypeFromType(true)) { Name = "Id" }))
            .Resolve(context => new MyObject
            {
                Id = Guid.NewGuid(),
                Name = "test"
            });

        var objectDataResultGraphType = CreateDataResultObjectGraphType<MyObject>(singular, objectGraphType, null);
        schema.RegisterType(objectDataResultGraphType);

        queryGraphType.Field(plural, objectDataResultGraphType)
            .Arguments(new QueryArguments(
                new QueryArgument(typeof(int?).GetGraphTypeFromType(true)) { Name = "Skip" },
                new QueryArgument(typeof(int?).GetGraphTypeFromType(true)) { Name = "Take" }))
            .Resolve(context =>
            {
                var dataResult = new DataResult<MyObject>
                {
                    Skip = 0,
                    Take = 10,
                    Total = 2
                };

                dataResult.Data.AddRange(new[]
                {
                    new MyObject
                    {
                        Id = Guid.Parse("96b8c7b5-d542-4d70-a0cf-b0bbc0db119f"),
                        Name = "test1"
                    },
                    new MyObject
                    {
                        Id = Guid.Parse("b405cb58-b966-4926-a989-90a76217af66"),
                        Name = "test2"
                    },
                });

                return dataResult;
            });
    }

    private static IObjectGraphType CreateDataResultObjectGraphType<TEntity>(string name, IObjectGraphType objectGraphType, FuncFieldResolver<DataResult<MyObject>, List<TEntity>> fieldResolver)
    {
        var graphType = new ObjectGraphType
        {
            Name = $"{name}DataResult"
        };

        // Total
        graphType.AddField(new FieldType
        {
            Name = nameof(DataResult<MyObject>.Total),
            ResolvedType = new LongGraphType(),
        });

        // Offset
        graphType.AddField(new FieldType
        {
            Name = nameof(DataResult<MyObject>.Skip),
            ResolvedType = new IntGraphType(),
        });

        // Take
        graphType.AddField(new FieldType
        {
            Name = nameof(DataResult<MyObject>.Take),
            ResolvedType = new IntGraphType(),
        });

        // Data
        graphType.AddField(new FieldType
        {
            Name = nameof(DataResult<MyObject>.Data),
            ResolvedType = new ListGraphType(objectGraphType),
            Resolver = fieldResolver
        });

        return graphType;
    }
}

public class MyObject
{
    public Guid Id { get; set; }
    public string Name { get; set; }
}

public class MyObjectGraphType : ObjectGraphType<MyObject>
{
    public MyObjectGraphType()
    {
        Field(p => p.Id);
        Field(p => p.Name);
    }
}

public class DataResult<TResult>
{
    public DataResult()
    {
        Data = new List<TResult>();
    }

    public long Total { get; set; }

    public int Skip { get; set; }

    public int Take { get; set; }

    public List<TResult> Data { get; private set; }
}

public class DataResultGraphType<TType, TGraphType> : ObjectGraphType<DataResult<TType>>
    where TGraphType : IGraphType
{
    public DataResultGraphType()
    {
        Field(x => x.Skip);
        Field(x => x.Take);
        Field(x => x.Total);
        Field(x => x.Data);
    }
}
```

**Comment by Shane32** [comment]
Very good chance it is because the same instance of `ObjectGraphType` is not used consistently for `MyObject`.  I'll look at your unit test to see if I can make a suggestion.

**Comment by GeertvanHorrik** [comment]
Thanks. Please note that the unit test succeeds (so I am unable to repro in a unit test scenario). Debugging against a local build of GraphQL now, hopefully I can update the ticket soon.

**Comment by Shane32** [comment]
By the way, `public override Schema Schema => _schema;` did not compile so I replaced it with:

```cs
        public override void RegisterServices(IServiceRegister register)
        {
            register.Register(typeof(Schema), _schema);
        }
```

**Comment by GeertvanHorrik** [comment]
I made the property virtual on my side in graphql to make it compile. Your solution is probably better :-)

**Comment by GeertvanHorrik** [comment]
Yes! Figured it out. Not sure if it's by design or not.

``` 
    public MyBugTest()
    {
        var schema = new Schema
        {
            NameConverter = new CamelCaseNameConverter()
        };

        var queryGraphType = new ObjectGraphType
        {
            Name = "Query"
        };

        schema.RegisterType(queryGraphType); // <========= THIS LINE IS ADDED TO UNIT TESTS

        RegisterGenericQueryGraphTypes(schema, queryGraphType, "MyObject", "MyObjects");

        schema.Query = queryGraphType;

        _schema = schema;
    }
```

Not sure if I am too pro-actively registering the query graph type there, but it causes these issues.

**Comment by Shane32** [comment]
Either way lol.

In general, I would guess that your dynamic code probably uses some type of lookup to tie a object type to another object type.  So like if `ParentType` has a child property `Child` of type `ChildType`, perhaps you are using a method `GetTypeFor` to dynamically create the child type.  This won't work because another parent referencing the same child type is going to get a different (new) instance of `ChildType`.

The reason introspection queries work is because the first `ChildType` to get detected by the schema gets the name converted properly and registered, and the system assumes the other references are the same type, which they are not.  Since the introspection query pulls from the registered type list, they will always return the correctly camelcase version.  But when `ParentType.Child` is resolved at runtime, it gets the individual reference it was assigned, which may not be the first registered instance.

The simplest fix for your code is to create a dictionary to hold created types, so you can pull from the dictionary instead of creating new instance (e.g. within `GetTypeFor`).

Another option is to use `GraphQLTyepReference` to reference another type by its GraphQL type name, or to use `GraphQLClrInputTypeReference` and `GraphQLClrOutputTypeReference` to reference another type by a CLR reference.  With the latter, you can use `AddGraphTypeMappingProvider` to dynamically create GraphQL types from unmapped CLR types.

**Comment by Shane32** [comment]
Of course it could be something else entirely.  I'll see if I can identify what's going on within your revised sample.

**Comment by Shane32** [comment]
It's got to be something like what I mentioned above, because all types that the schema considers 'registered' (i.e. within `Schema.AllTypes`) are going to get converted to camel case.  And so at runtime the `MyObject` type must not be referencing the copy within `AllTypes`, one way or another.  It doesn't convert to camel-case at runtime -- only during schema initialization -- and the original name of the property is overwritten at that time.

**Comment by Shane32** [comment]
One easy thing you can do is to add `schema.Initialize();` and then debug what's being held in memory after initialization.  Follow the types' `ResolvedType` properties and see what's converted or not.  Check if the references are the same.  Maybe the `Query` type is added by the infrastructure automatically and hence is being added twice.  Maybe I can take a look later.

![image](https://user-images.githubusercontent.com/6377684/190868413-73ff1c4e-cdfc-498e-ac64-7feb82d18e53.png)

**Comment by GeertvanHorrik** [comment]
You are right. When initializing the collection, it sees it already has initialized the object name `MyObject` in `SchemaTypes.AddTypeIfNotRegistered` (and `ReferenceEquals(object, existingObject) == false`).

In the unit tests, I tried re-using the object graph type by passing it into the collection, but I suspect that this "auto-initializes" as well (but as a different instance):

```
queryGraphType.Field<MyObjectGraphType>(singular)
```

I can fix it in my code by rewriting:

```
queryGraphType.Field<MyObjectGraphType>(singular)
```

into 

```
queryGraphType.Field(singular, objectGraphType)
```

But since this is a very, very tricky thing to happen, maybe there could be one of the following changes:

1. If type already exists, start using the already existing (correct) type instead of the current instance?
2. If type already exists, compare and throw exception if they are different 

I think the current situation can lead to unexpected, hard to debug, situations like mine.

The easiest to implement seems 2, and I am happy to provide a PR if you are interested.

**Comment by Shane32** [comment]
That would be great thanks!

**Comment by Shane32** [comment]
I’d probably go with option 2. When people write dynamic code, they often just create an ObjectGraphType ‘by hand’ and if for example they forget to rename the type, we wouldn’t want the infrastructure to use an entirely different graph type in its place. Nor would we want to encourage constructing graph types multiple times assuming that the infrastructure will “deduplicate” the references.

**Comment by GeertvanHorrik** [comment]
Thanks for the info.

Questions: 

1. should it be done against develop or master branch?
2. shall I introduce an option (e.g. `ThrowExceptionOnTypeDuplicatesWithDifferences` that defaults to `true`) on Schema to disable the exceptions in case people really want to use the "old" way?

**Comment by Shane32** [comment]
Master

No - there are more issues that can occur than just capitalization. For instance child fields of the uninitialized type may not have their ResolvedType properties set resulting in an unusable schema. 

I’ll release this with v7.1 as a minor version bump.

**Comment by GeertvanHorrik** [comment]
You mentioned that there could be more than 1 issue (e.g. uninitialized types, etc). I am probably not able to understand all the complications so this integrity check probably needs to be expanded in the future (now it checks whether all field names are equal).

**Comment by sungam3r** [comment]
Oh... Again that `SchemaTypes` tricky stuff jumping around types, instances and different registration order 😖 . It’s not even bad that problems constantly arise with that code. The bad thing is that the already non-obvious code is increasingly becoming more complicated.

**Comment by Shane32** [comment]
Sometime I would like to rewrite `SchemaTypes`....
