### ISSUE TITLE
Arguments cannot be retrieved with registration case

### ISSUE THREAD

**Issue by GeertvanHorrik** [graphql-dotnet/graphql-dotnet#3333]
## Description

When an argument is registered with "PascalCase", the (default) naming converter changes it to "camelCase". However, when retrieving the argument with this code, it will not return anything.

```
if (context.Arguments.TryGetValue("Take", out var take) &&
    take.Value is int intCount &&
    intCount > 0)
{
    pageableQuery.Take = intCount;
}
``` 

### Steps to reproduce

Register argument:

``` 
// Take
graphType.AddField(new FieldType
{
    Name = "Take",
    ResolvedType = new IntGraphType(),
});
```

Try retrieving the argument value:

``` 
if (context.Arguments.TryGetValue("Take", out var take) &&
    take.Value is int intCount &&
    intCount > 0)
{
    pageableQuery.Take = intCount;
}
```

Will not work. The dictionary has "take", not "Take".

### Expected result

I would expect to be able to retrieve the argument via the name I registered it with (e.g. if we change naming convention, we have to manually go through all the argument retrieval functions).

### Actual result

Dictionary keys use the post-naming-convention style.

### Environment

GraphQL 7.0.2

### Possible solutions

**Simple**

Make the dictionary holding the arguments case insensitive.

**Complex but more reliable**

Keep an internal dictionary of mappings (e.g. registration name and naming convention name). As long as there are no duplicates (this could easily be checked), the actual "camelCase" argument could be resolved via the "PascalCase" registration name.

**Comment by GeertvanHorrik** [comment]
I did some extra research and noticed that one can use the GetArgument extension method:

```
var take = context.GetArgument<int>("Take");
if (take > 0)
{
    pageableQuery.Take = take;
}
```

**Comment by Shane32** [comment]
Correct; this is as designed — the dictionary contains the exact names within the request while GetArgument runs the supplied name through the name converter.
