### ISSUE TITLE
Debugger initializes schema

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#3338]
## Description

You have this line of code: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Schema.cs#L196

When you use the debugger and inspect the schema, it gets initialized and basically changes the code.

So if you have a very simple sample like this and you add a breakpoint to the first Console.WriteLine and then expand the "schema" variable the middleware is not applied anymore.

```
using System;
using System.Threading.Tasks;
using GraphQL;
using GraphQL.Types;
using GraphQL.SystemTextJson;

public class Program2
{
    public static async Task Main(string[] args)
    {
        var schema = Schema.For(@"
      type Query {
        hello: String
      }
    ");

        Console.WriteLine(schema.Initialized);

        schema.FieldMiddleware.Use(next =>
        {
            return context =>
            {
                return new ValueTask<object?>("42");
            };
        });

        var json = await schema.ExecuteAsync(_ =>
        {
            _.Query = "{ hello }";
            _.Root = new { Hello = "Hello World!" };
        });

        Console.WriteLine(json);
    }
}
```

Not a big problem, but it can take a while to find the problem to the solution.

**Comment by Shane32** [comment]
Makes sense... do you have a suggestion?  Perhaps we can use `DebuggerDisplayAttribute` to map the displayed value to the underlying `_allTypes` instance value.

**Comment by SebastianStehle** [comment]
It sounds dangerous to initialize the schema on the fly. What happens when you use AllTypes in a `ISchemaNodeVisitor`? 

I would just throw an exception in the method.

**Comment by Shane32** [comment]
It is an option, but would likely require many changes to the tests which rely on that behavior.

**Comment by sungam3r** [comment]
> What happens when you use AllTypes in a `ISchemaNodeVisitor`?

`_allTypes` is already initialized at that moment so you just get reference to it.
![изображение](https://user-images.githubusercontent.com/21261007/200824932-786a9deb-639b-4c29-8fa5-b595d19764bb.png)

**Comment by SebastianStehle** [comment]
True. Sorry,  I thought the order is different, like 

1. Run visitors
2. Initialize schema.
