### ISSUE TITLE
metadata missing

### ISSUE THREAD

**Issue by zimmybln** [graphql-dotnet/graphql-dotnet#334]
Hi,

when I use typename within my query I get a valid result. But when I use Shema, TypeKind, Field or Directive (taken from GraphQL spezification) I got an error because of invalid query (cannot find the fields). Which metadata do you support?

Best regards,
Torsten

**Comment by joemcbride** [comment]
All metadata should be supported.  Can you provide an example query of the issue you're having?

**Comment by joemcbride** [comment]
Going to go ahead and close this.  Feel free to re-open with an example of the issue you're having.
