### ISSUE TITLE
Add Extensions dictionary to ExecutionError object

### ISSUE THREAD

**Issue by thurstonford** [graphql-dotnet/graphql-dotnet#3354]
## Summary

Consider adding an Extensions dictionary (String, object) to the ExecutionError object to honour the GraphQL spec:
https://spec.graphql.org/October2021/#sec-Errors
https://spec.graphql.org/October2021/#example-8b658

### Basic example

Developers can then add custom properties to the errors collection via the dictionary in the usual manner, eg:
```
try {
    ...
} catch(Exception ex) { 
    ExecutionError executionError = new ExecutionError("Oh dear, that went horribly wrong");
    executionError.Extensions.Add("customError", "Your custom error here")
    context.Errors.Add(executionError);
}
```
The output of which would be something like:
```
{
"data": {
    "someMutation": null
},
"errors": [{            
        "message": "Oh dear, that went horribly wrong",            
        "extensions": {
            "customError": "Your custom error here"                
        }            
    }]
}
```
### Motivation
This should allow for simplified exception handling with custom errors, and also honour the GraphQL spec.

PS: Have asked this question here too:
https://stackoverflow.com/questions/74012743/why-doesnt-graphql-net-honour-the-errors-extensions-schema

**Comment by Shane32** [comment]
As it is now, GraphQL.NET has a convention set up for error responses where the `extensions` property has specific children properties, as follows:

- `code` is the name of the exception type converted to camel case - e.g. `InvalidIdError` becomes `INVALID_ID`
- `codes` is an array of the inheritance hierarchy of the exception types converted to camel case -- e.g. if `InvalidIdError` inherits from `InvalidPropertyError` then it might be `["INVALID_ID", "INVALID_PROPERTY"]`
- `number` is used for validation errors that conform to the GraphQL spec, and returns the reference to the spec where the error is referenced; note that this value may change as the spec changes
- `details` if enabled returns the stack trace of the exception
- `data` if enabled returns the `Exception.Data` collection

You can tailor this behavior by writing your own `IErrorInfoProvider` implementation.  See the default implementation here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ErrorInfoProvider.cs

For instance, you can create a class called `UserError` which inherits `ExecutionError` and includes an `Extensions` collection which is serialized to the extensions property in the manner you described.

You could also alter your `IErrorInfoProvider` implementation to return information from `Exception.Data` directly into the `extensions` property of the GraphQL response.  However, note that other C# libraries use the `Data` collection to store data which you may not want to be revealed to callers of your GraphQL endpoint -- for example, the SQL client does so.  We have also run into issues in the past where keys within the `Exception.Data` collection contained null keys which were throwing exceptions during serialization.  This is why that data is not serialized by default.

All that being said, this is certainly worth further discussion.  Having the design you suggested would unify direct access to error extensions to be similar to input extensions and output extensions.  Whereas now the codebase could be thought of as a hybrid design using `IErrorInfoProvider` to map errors into responses along with `ExecutionError` which contains some GraphQL-specific information.  I doubt we would scrap `IErrorInfoProvider`, as this would prevent global configuration of error responses, but perhaps we might add an `Extensions` collection which appends those entries to the response, separate from the `Data` collection used by `Exception`.

**Comment by thurstonford** [comment]
Thanks for the response and ideas @Shane32 

I'll have a swing at creating my own ErrorInfoProvider.
