### ISSUE TITLE
ExecutionResult copy-ctor does not copy all properties

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3358]
Are `Streams` and `Executed` just ... forgotten ?

**Comment by Shane32** [comment]
Seems so.  The ctor is not called by any code or tests.

Personally I would fix it and mark as obsolete at the same time.  I can't imagine why a shallow copy of a execution result would be useful.

**Comment by sungam3r** [comment]
I use it for logging purposes when I need to log errors and data in different properties. I copy ExecutionResult, nullify one prop or anther and then serialize entire ExecutionResult.
