### ISSUE TITLE
Custom JsonConverter for DateTime types not being called when serializing the response

### ISSUE THREAD

**Issue by mglace** [graphql-dotnet/graphql-dotnet#3359]
## Description

`JsonConverter<DateTime>` not working because DateTime values are returned as strings by the `ValueExecutionNode.ToValue()` method on line 46 of the ExecutionResultJsonConverter.

### Steps to reproduce

I created a new DateTimeJsonConverter as follows: 

```
public class DateTimeJsonConverter : JsonConverter<DateTime>
{
    public override bool CanConvert(Type typeToConvert) => typeToConvert == typeof(DateTime);

    public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return DateTime.Parse(reader.GetString());
    }

    public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString("MM-dd-yyyy'T'HH:mm:ss"));
    }
}
```

And I registered it with the GraphQLSerializer like so:

```
var options = new JsonSerializerOptions();

options.Converters.Add(new DateTimeJsonConverter());

var serializer = new GraphQLSerializer(options);
```

Using the Star Wars example, I added a DateTime property to the Droid class:

```
public class Droid
{
    public string Id { get; set; }
    public string Name { get; set; }
    public DateTime Timestamp { get; set; }
}

public class DroidType : ObjectGraphType<Droid>
{
    public DroidType()
    {
        Field(x => x.Id).Description("The Id of the Droid.");
        Field(x => x.Name).Description("The name of the Droid.");
        Field(x => x.Timestamp).Description("The timestamp the Droid was brought online.");
    }
}

public class StarWarsQuery : ObjectGraphType
{
    public StarWarsQuery()
    {
        Field<DroidType>("hero")
            .Resolve(context => new Droid { Id = "1", Name = "R2-D2", Timestamp = DateTime.UtcNow });
    }
}
```

### Expected result

When calling `await serializer.WriteAsync(stream, result);`, timestamp property on the DroidType should be formatted using the custom JsonConverter provided.

### Actual result

When I call `await serializer.WriteAsync(stream, result);`, it serializes my DroidType with no regard to my custom DateTimeJsonConverter.  Placing a breakpoint in the Write method of my converter confirms that it is not being called.  When I break on the CanConvert method, I see that the value of `typeToConvert` is System.String, not System.DateTime as expected.

### Further Investigation

The Result property on the ExecutionNode is getting properly set to a DateTime value on line 460 of the ExecutionStrategy, however the value is later overwritten by a string on line 534 of the ExecutionStrategy.

### Environment

.NET Core 6 Console App
GraphQL 7.1.1

**Comment by Shane32** [comment]
The selected scalar graph type converts the `DateTime` to a string so the result meets ISO specifications regardless of the JSON serializer's configuration.  You are using the expression syntax which will automatically select the `DateTimeGraphType` by default.  The `DateTimeGraphType` scalar serializes dates in ISO-8601 format.  See here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Scalars/DateTimeGraphType.cs#L63

To change this behavior, create a custom scalar graph type with the serialization behavior you desire.  You can redefine the default graph type used for `DateTime` properties by calling RegisterTypeMapping in the schema constructor:

```cs
this.RegisterTypeMapping<DateTime, MyDateTimeGraphType>();
```

Or in your startup file like this:

```cs
services.AddGraphQL(b => b
    .ConfigureSchema(schema => {
        schema.RegisterTypeMapping<DateTime, MyDateTimeGraphType>();
    }));
```

You can also manually define the graph type when calling `Field`.

See more documentation on creating custom scalars here:

https://graphql-dotnet.github.io/docs/getting-started/custom-scalars

Note that since `DateTime` is not a graph type defined in the GraphQL spec, you may use a graph type name of `DateTime` so long as you are not using the included `DateTimeGraphType` (or there would be a conflict).

I suggest to start by copying the `DateTimeGraphType` and modifying it for your needs.

**Comment by Shane32** [comment]
As a side note, prior to version 4, the scalars performed as you expected, passing through values to allow the JSON serializer to convert the values to strings.  We found that this behavior led to inconsistent behavior across different JSON serializers and hindered ISO-8601 conformity, both in serialization and in parsing.  So from version 4 on, date and time values are converted to/from strings within the scalar.  As such, a `JsonConverter` has no effect on `DateTime` values.

**Comment by mglace** [comment]
Thank you for your quick response.  Your suggestion worked perfectly.

**Comment by vuonghung12** [comment]
hi @Shane32 after adding this line

> _schema.RegisterTypeMapping<DateTime, CustomDateTimeGraphType>();

```
            GraphQLData? data = new GraphQLSerializer(serializerOptions).Deserialize<GraphQLData>(requestBody);
            _schema.RegisterTypeMapping<DateTime, CustomDateTimeGraphType>();
            var json = await _schema.ExecuteAsync(_ =>
            {
                _.Query = data?.Query;
                _.OperationName = data?.OperationName;
                _.Variables = data?.Variables;
            });

            return new ContentResult
            {
                Content = json,
                ContentType = "application/json",
                StatusCode = 200,
            };
```

I have this error: This graph type 'RootQuery' has already been initialized. Make sure that you do not use the same instance of a graph type in multiple schemas. It may be so if you registered this graph type as singleton;

Why this happend and do you have any solution?

**Comment by Shane32** [comment]
Try moving the call to `RegisterTypeMapping` into the schema constructor and see if that solves the issue.

**Comment by vuonghung12** [comment]
no, this not work :(

> _.Schema.RegisterTypeMapping<DateTime, CustomDateTimeGraphType>();

**Comment by Shane32** [comment]
Does it give the same "already been initialized" error when the type mapping is registered in the schema constructor?

**Comment by vuonghung12** [comment]
> Does it give the same "already been initialized" error when the type mapping is registered in the schema constructor?

yes it's same

I will try DateGraphType

**Comment by vuonghung12** [comment]
update: DateGraphType not work too, still error "Unable to convert '1952-03-22' to 'DateTime'"

**Comment by vuonghung12** [comment]
sorry this is my mistake
I have conflict with Date and DateTime some where
thanks for suggest
I clean my code now
