### ISSUE TITLE
QueryArgument Description is not printed by the SchemaPrinter

### ISSUE THREAD

**Issue by SvenSchlesinger** [graphql-dotnet/graphql-dotnet#3364]
Hey,

I have a question regarding the SchemaPrinter and the descriptions of QueryArguments. According to the GQL spec from 2018, it should be possible to save also descriptions for query arguments in the SDL based schema ([see Specification](https://spec.graphql.org/June2018/#example-64e5a)). I use the SchemaPrinter to save my schema in the SDL string representation. Generally, it works fine. The SchemaPrinter prints the descriptions for types and associated fields as expected, but it does not work for QueryArguments - although this should work according to the documentation.

I tried different approaches. However, I can not find the issue, why it is not working. The code snippet down below shows an example, that is quite similiar to one test case in the [SchemaPrinter unit test - line 384](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs):

            Schema testSchema = new()
            {
                Query = new ObjectGraphType() { Name = "Query" }
            };

            testSchema.Query.AddField(new FieldType()
            {
                Name = "testQuery",
                Description = "this is the query"
                Type = typeof(IntGraphType),
                Arguments = new QueryArguments(new QueryArgument<IntGraphType>() { Name = "testArg", Description = "this is the argument" })
            });

            testSchema.Initialize();
            SchemaPrinter printer = new SchemaPrinter(testSchema, new SchemaPrinterOptions() { IncludeDescriptions = true, PrintDescriptionsAsComments = false });
            Console.WriteLine(printer.Print());

I would expect the following output:

`
type Query {
  """
  this is the query
  """
  testQuery("this is the argument" testArg: Int): Int
}
`

But actually it is:

`
type Query {
  """
  this is the query
  """
  testQuery(testArg: Int): Int
}
`

What do I miss? Thank you in advance!

**Comment by Shane32** [comment]
It seems that the `SchemaPrinter` does not print descriptions for query arguments.  A fix is needed in the `PrintInputValue` method here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L306

**Comment by sungam3r** [comment]
Probably fixed by #3382

**Comment by Shane32** [comment]
`SchemaPrinter` is deprecated in v8 and the new `SchemaExporter` solves this issue.
