### ISSUE TITLE
Intercepting Resolver in a FieldBuilder extension

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#3365]
Hi, 
I want to create a FieldBuilder extension that will be applied after Resolve and conditionally can override Resolve behavior. 
In the example below, the extension is called WithComment. 
it:
- Adds an argument called comment if not already provided.
- In the resolver, it checks if comment is needed (here the logic is only for demo)
- If comment is needed and not provided, it returns response with error.
- if comment is need and also provided, it should fall back to the original resolver execution.

I came up with the following approach and wondering if you can advise if it is correct ot there is any better way.
(Only look at the implementation of WithComment extension)

```csharp
async Task Main()
{
	var schema = new Schema { Query = new TestQuery() };
	var result1 = await schema.ExecuteAsync(_ =>
			{
				_.Query = "{ test1 { status, id, errorMessage } }";
			}
	);

	var result2 = await schema.ExecuteAsync(_ =>
			{
				_.Query = "{ test2 { status, id, errorMessage } }";
			}
	);


	result1.Dump();
	result2.Dump();
}

public class TestQuery : ObjectGraphType
{
	public TestQuery()
	{
		Field<TestResponseType, TestResponse>("test1")
			.Resolve(context =>
			{
				return new TestResponse();
			})
			.WithComment(1);

		Field<TestResponseType, TestResponse>("test2")
			.Resolve(context =>
			{
				return new TestResponse();
			})
			.WithComment(2);

	}
}

public static class FieldBuilderExtensions
{
	public static readonly string COMMENT_ARGUMENT = "comment";

	public static FieldBuilder<TSourceType, TReturnType> WithComment<TSourceType, TReturnType>(
			this FieldBuilder<TSourceType, TReturnType> builder, int value) where TReturnType : BaseResponse, new()
	{
		if (builder.FieldType.Resolver == null) {
			throw new Exception("Resolve must be used before WithComment");
		}
		
		if (builder.FieldType.Arguments == null)
		{
			builder.FieldType.Arguments = new QueryArguments();
		}

		if (!builder.FieldType.Arguments.Any(f => f.Name == COMMENT_ARGUMENT))
		{
			builder.FieldType.Arguments.Add(new QueryArgument<StringGraphType>
			{
				Name = COMMENT_ARGUMENT
			});
		}

		var currentResolver = builder.FieldType.Resolver;

		builder.FieldType.Resolver = new FuncFieldResolver<TSourceType, TReturnType>((IResolveFieldContext<TSourceType> context) =>
		{
			var needsComment = value % 2 == 0;	//Dummy logic here for demo
			var comment = context.GetArgument<string>(COMMENT_ARGUMENT);

			if (needsComment && comment == null)
			{
				return new TReturnType() {
					Status = "Fail",
					ErrorMessage = "Comment must be provided"
				};
			}
			else
			{
				return (TReturnType)currentResolver.ResolveAsync(context).Result;
			}
		});

		return builder;
	}
}

public class TestResponseType : BaseResponseType<TestResponse>
{
	public TestResponseType()
	{
		Field<StringGraphType>("Id");
	}
}

public class BaseResponseType<T> : ObjectGraphType<T>
{
	public BaseResponseType()
	{
		Field<StringGraphType>("status");
		Field<StringGraphType>("errorMessage");
	}
}

public class TestResponse : BaseResponse
{
	public string Id { get; set; }
	public TestResponse()
	{
		Id = "0";
	}
}

public class BaseResponse
{
	public string Status { get; set; } = "success";
	public string ErrorMessage { get; set; } = "";
}
```

**Comment by Shane32** [comment]
I think it looks good.  Here's a couple other ideas also, just FYI:

1. If the comment argument was a non-null argument, validation would fail if the comment was not provided, so you might not need to overwrite the field resolver.  Validation has a benefit that the query does not execute if validation fails.  In your example above, you indicated that the comment was only conditionally required based on runtime logic, so this might not work for you.

Also, it seems that you are returning error messages within the GraphQL response.  I would personally recommend using GraphQL errors instead, and unify error responses with validation errors.

2. If the comment is not used in the resolver but is simply there for logging, you could likely provide it "out of bounds" as a directive or comment, and write a validation rule that ensures that the directive or comment exists.  So for example it is possible to validate this within a validation rule:

```gql
{
  something {
    # a comment here <-- validation code ensures there is a comment here prior to execution of 'child' below
    child { id }
  }
}
```

However, the example above probably violates spec as comments should be treated as whitespace during execution.

**Comment by rmeshksar** [comment]
Thanks for the fast reply as usual.

**Comment by sungam3r** [comment]
> you could likely provide it "out of bounds" as a directive or comment

Of course directive  can help here

```graphql
{
  something {
    child @comment("Hello world!") { id }
  }
}
```
Directive looks more promising, structured (unlike comments). You **may** go this way but prepare to fight with some difficulties - exposing directives via introspection, using GraphQL clients that aware of directives, write validation rule checking directive. The official specification has not yet been able to fully reveal all the possibilities of directives.
