### ISSUE TITLE
Custom logic for parsing enumerations

### ISSUE THREAD

**Issue by rmeshksar** [graphql-dotnet/graphql-dotnet#3367]
Hi,
I would like to have a custom logic of parsing and serialization of enumerations.

I looked at this:
[EnumerationGraphType](https://github.com/graphql-dotnet/graphql-dotnet/issues/3105)

The issue is that our application is old based on .NET 4.7.1 and we are using our custom implementation of SimpleContainer and I don't know how we can register the type mapping between EnumerationGraphType and the custom implementation.

Is there any way to use the same mechanism of overwriting Scalars using RegisterType  for Enums?

**Comment by Shane32** [comment]
There are multiple solutions here.  If you have a custom implementation of `SimpleContainer`, then you should be able to do something along these lines within the service resolver method:

```cs
if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(EnumerationGraphType<>)) {
    var nestedType = type.GetGenericArguments()[0];
    var type2 = typeof(CaseInsensitiveEnumerationGraphType<>).MakeGenericType(nestedType);
    return Activator.CreateInstance(type2);
}
```

The above is the equivalent of this:

```cs
services.AddTransient(typeof(EnumerationGraphType<>), typeof(CaseInsensitiveEnumerationGraphType<>));
```

Another solution would be to register a custom `IGraphTypeMappingProvider` implementation.  The contents would be something like this:

```cs
if (preferredGraphType == null && clrType.IsEnum)
    return typeof(CaseInsensitiveEnumerationGraphType<>).MakeGenericType(clrType);
return preferredGraphType;
```

Or you could use `RegisterType` for every enum in your project...

**Comment by rmeshksar** [comment]
For the IGraphTypeMappingProvider approach, Do I have to also resigster IEnumerable<IGrapgTypeMappingProvider> in SimpleContainer. Because if I don't I get this error:

No registration for System.Collections.Generic.IEnumerable`1[GraphQL.Types.IGraphTypeMappingProvider]

**Comment by rmeshksar** [comment]
I did as you suggested.
In SimpleContainer, I run:

```csharp
container.Singleton<IEnumerable<IGraphTypeMappingProvider>>(() => new List<CustomGraphTypeMappingProvider>());
```

Then I implemented:
```csharp
    public class CustomGraphTypeMappingProvider : IGraphTypeMappingProvider
    {
        public Type GetGraphTypeFromClrType(Type clrType, bool isInputType, Type preferredGraphType)
        {
            if (preferredGraphType == null && clrType.IsEnum)
                return typeof(CaseInsensitiveEnumerationGraphType<>).MakeGenericType(clrType);

            return preferredGraphType;
        }
    }

    public class CaseInsensitiveEnumerationGraphType<T> : EnumerationGraphType<T> where T : Enum
    {
    }
```

But when I debug it, GetGraphTypeFromClrType method is not getting used.

Am I missing anything?

**Comment by Shane32** [comment]
Add an instance to the list

**Comment by Shane32** [comment]
Note that the `IGraphTypeMappingProvider` solution is effective with _inferred_ graph types only.  So it would work for this:

```cs
Field(x => x.MyEnumField);
```

But not for this, because this explicitly states the graph type:

```cs
Field<EnumerationGraphType<MyEnum>>("MyEnumField", resolve: ctx => ctx.Source.MyEnumField);
```

**Comment by rmeshksar** [comment]
Thanks for the clarification. 
So, IGraphTypeMappingProvider approach won't work for me. 
I will try to go with other approach.

**Comment by Shane32** [comment]
You can also wrap the SimpleContainer with another provider class:

```cs
public class MyWrapper : IServiceProvider
{
    private readonly IServiceProvider _provider;

    public MyWrapper(IServiceProvider provider)
        => _provider = provider;

    public object GetService(Type type)
    {
        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(EnumerationGraphType<>)) {
            var nestedType = type.GetGenericArguments()[0];
            var type2 = typeof(CaseInsensitiveEnumerationGraphType<>).MakeGenericType(nestedType);
            return Activator.CreateInstance(type2);
        }

        return _provider.GetService(type);
    }
}
```

Then you'd need to alter the schema constructor to use the wrapper

```cs
public class MySchema : Schema
{
    public MySchema(IServiceProvider provider)
        : base(new MyWrapper(provider))
    {
    }
}
```

**Comment by rmeshksar** [comment]
@Shane32 , You are genius. Thanks a million.
It is the best approach as I did not like to modify the SimpleContainer just because of this.

One last question. Do I always have to register IEnumerable<IGraphTypeMappingProvider> in the container even if I don't want to make any change in behavior?

Something like this:
```cshart
container.Singleton<IEnumerable<IGraphTypeMappingProvider>>(() => null);
```

**Comment by Shane32** [comment]
Yes and no.  GraphQL.NET relies on the typical behavior of `IServiceProvider.GetService` to return `null` if no matching service is registered.  If your `SimpleContainer` throws an exception instead, then yes you would need to add that registration.  Alternatively, you can have it return `null` as other DI providers do (possibly by adding a try/catch handler in the wrapper).

I would like to point out that you can transition to the MS DI provider by adding a reference to the Microsoft.Extensions.DependencyInjection nuget package.  The current version is fully compatible with .NET Framework 4.6.1+.  See link below.

https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/6.0.1#dependencies-body-tab

Of course, as the saying goes, "if it ain't broke, don't fix it"...

**Comment by rmeshksar** [comment]
Thanks.

**Comment by rmeshksar** [comment]
Sorry for opening this. 
I have one more question. 
What do you suggest doing for the case of having an enum class. I mean:

```csharp
public class StatusGraphType : EnumerationGraphType
{
	public StatusGraphType()
	{
		Add("CURRENT", 0);
		Add("PROPOSED", 1);
		Add("REVERSE", 2);
	}
}
```

I know we can inherit this class from CaseInsensitiveEnumerationGraphType, but in our case it means changing several hundreds of files.

**Comment by Shane32** [comment]
Search and replace. Perhaps a global using that is an equivalent of `using EnumerationGraphType = MyStuff.MyEnumGraphType;` would work. 

Sorry I don’t have any better answer

**Comment by rmeshksar** [comment]
Thanks. Sorry if it was a stupid question :)

I tried to implement both generic and non-generic version of CaseInsensitiveEnumerationGraphType.

```csharp
public class CaseInsensitiveEnumerationGraphType : EnumerationGraphType
{
}

public class CaseInsensitiveEnumerationGraphType<TEnum> : CaseInsensitiveEnumerationGraphType where TEnum : Enum
{
}
```

But when I map EnumerationGraphType to CaseInsensitiveEnumerationGraphType:
```csharp
public object GetService(Type type)
{
// first solution above, just implemented outside the SimpleContainer
if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(EnumerationGraphType<>))
{
	var nestedType = type.GetGenericArguments()[0];
	var type2 = typeof(CaseInsensitiveEnumerationGraphType<>).MakeGenericType(nestedType);
	return Activator.CreateInstance(type2);
}

return _provider.GetService(type);
}
```

And use it in an input, I get this error:
```json
{
    "errors": [{
            "message": "Error executing document.",
            "extensions": {
                "code": "INVALID_OPERATION",
                "codes": ["INVALID_OPERATION"],
                "details": "GraphQL.Execution.UnhandledError: Error executing document. ---> System.InvalidOperationException: An Enum type 'CaseInsensitiveEnumerationGraphType_1' must define one or more unique enum values.\r\n   at GraphQL.Utilities.SchemaValidationVisitor.VisitEnum(EnumerationGraphType type, ISchema schema)\r\n   at GraphQL.SchemaExtensions.Run(ISchemaNodeVisitor visitor, ISchema schema)\r\n   at GraphQL.Types.Schema.Validate()\r\n   at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes()\r\n   at GraphQL.Types.Schema.Initialize()\r\n   at GraphQL.DocumentExecuter.<CoreExecuteAsync>d__9.MoveNext()\r\n   --- End of inner exception stack trace ---"
            }
        }
    ]
}
```


I can inherit the generic version also from EnumerationGrapgType, but in this case I need to duplicate the code.
What do you advise?

**Comment by Shane32** [comment]
> I can inherit the generic version also from EnumerationGrapgType, but in this case I need to duplicate the code.

In your case I'd duplicate the code.  The alternative would duplicate the code in another manner, so it's just a manner of what code to duplicate, since you can't inherit two different classes.

```cs
// not possible
public class CaseInsensitiveEnumerationGraphType<TEnum>
    : CaseInsensitiveEnumerationGraphType, EnumerationGraphType<TEnum>
    where TEnum : Enum
```

**Comment by rmeshksar** [comment]
Great, Thanks.
