### ISSUE TITLE
DI This graph type 'Query' has already been initialized

### ISSUE THREAD

**Issue by AdamPzpn** [graphql-dotnet/graphql-dotnet#3369]
## Description

After preparing Schema -> Query ->Types program is compiling but after using playground I am getting information:
"System.InvalidOperationException: This graph type 'AppQueries' has already been initialized. Make sure that you do not use the same instance of a graph type in multiple schemas. It may be so if you registered this graph type as singleton;"

Query ==>  Name = "AppQueries";

### Steps to reproduce

My configuration:
Dll: GraphQL 7.1.1
GraphQL.MiscrosoftDI 7.1.1
GraphQL.Server.Transports.AspNetCore 7.1.1
GraphQl.Server.Ui.Playgroun d 7.1.1
GraphQL.SystemTextJson 7.1.1

Startup:
```cs
     builder.Services.AddGraphQL(b => b
                .AddSystemTextJson()
                .AddErrorInfoProvider(opt => opt.ExposeExceptionDetails = true)
                .AddSchema<AppSchema>()
                 .AddGraphTypes(typeof(AppSchema).Assembly));

    services.AddSingleton<AppQueries>();
    services.AddSingleton<AppMutation>();
    services.AddSingleton<AppSchema>();
```

Configuration
```cs
           app.UseGraphQL("/graphql");
            app.UseGraphQLPlayground(
                "/",                               
                new PlaygroundOptions
                {
                    GraphQLEndPoint = "/graphql",         
                    SubscriptionsEndPoint = "/graphql",   
                });


    public class AppSchema : Schema
    {
        public AppSchema(IServiceProvider provider)
            : base(provider)
        {
            Query = provider.GetRequiredService<AppQueries>();
            Mutation = provider.GetRequiredService<AppMutation>();
        }
    }
```

### Expected result

Normal execution of query

### Actual result

System.InvalidOperationException
```
GraphQL.Types.GraphType.Initialize(ISchema schema) in /_/src/GraphQL/Types/GraphType.cs:line 33\r\n   
		  at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 428\r\n   
		  at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 669\r\n   
		  at GraphQL.Types.SchemaTypes.Initialize(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 201\r\n   
		  at GraphQL.Types.Schema.CreateSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 398\r\n   
		  at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 369\r\n   
		  at GraphQL.Types.Schema.Initialize() in /_/src/GraphQL/Types/Schema.cs:line 143\r\n  
		  at GraphQL.DocumentExecuter.CoreExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 100\r\n
```

### Environment

.Net 6,  GraphQL 7.1.1, Windows, Visual Studio 2022, IIS Express

**Comment by Shane32** [comment]
Are there any other references to `AppQueries` in your application?

**Comment by Shane32** [comment]
What if you try removing these lines of code:
```cs
    services.AddSingleton<AppQueries>();
    services.AddSingleton<AppMutation>();
    services.AddSingleton<AppSchema>();
```
They should not be necessary considering the rest of the code you have there.

**Comment by AdamPzpn** [comment]
Yes i was just trying everything. It seems that error description is missleading. I have 3 FieldType in AppQuery:
ClubType,
MatchType and
PlayerType (I have also mutation for this one.

It seems that there is no problem with DI. When i comment all but ClubType then playground is working fine for clubs. It seems that there is some problem with other types. I am not sure what is the problem. I even bring them unique name. It still wasnt helpfull.

**Comment by Shane32** [comment]
Hmm.  I might spend some time trying to see if it is possible to clarify the error message, but I'm still not understanding how you solved the issue.

I assume `Match.HostClub` is of type `Club`, and `Match.GuestClub` is of type `Club` also?  Doesn't seem to be any problem there.  But how is the correct graph type inferred from `Field(x => x.HostClub)`?  I do not see `.AddClrTypeMappings()` called during DI registrations, nor any calls to `this.AddTypeMapping()` within the schema constructor.

**Comment by sungam3r** [comment]
Rel: #3378
