### ISSUE TITLE
How to implement a Relay compatible node field?

### ISSUE THREAD

**Issue by MichaelHilus** [graphql-dotnet/graphql-dotnet#337]
Hey,

great framework! The more I work with it, the more I love it. :-)

I am currently working on an implementation of a Relay compatible node field.
What I have implemented so far in my query type is (`GlobalId` is a helper, that I use to offer unique base64 encoded ids to the client):

    this.Field<NodeType>(
        "node",
        arguments: new QueryArguments(new QueryArgument<IdGraphType> { Name = "id", Description = "The node id." }),
        resolve: context =>
    {
        // get the entity name
        var globalId = context.GetArgument<string>("id");
        var entityName = GlobalId.ToEntityName(globalId);

        // switch through entity names and call matching repository or manager
        if (entityName == "EntityA")
        {
            var id = GlobalId.ToLocalId<Guid>(globalId);
            return new EntityA { Id = id, Name = "EntityA from node" };
        }

        throw new NotImplementedException();
    });

    this.Field<ViewerType>("viewer", resolve: context => new Viewer());

My `ViewerType` extends from a class `NodeType` and `NodeType` looks like that:

    public class NodeType: ObjectGraphtype {
        public NodeType()
        {
            this.Interface<NodeInterfaceType>();
            this.AddIdField();
            this.IsTypeOf = value => true;
        }
    }

My class `NodeInterfaceType` is defined as follows:

    public class NodeInterfaceType : InterfaceGraphType
    {
        public NodeInterfaceType()
        {
            this.Name = "Node";
            this.Field<NonNullGraphType<IdGraphType>>("id", "The id of the node");
        }
    }

But when I try to query the node field like this:

    query EntityList_ViewerRelayQL($id_0:ID!) {
      node(id:$id_0) {
        id,
       __typename,
        ...F0
      }
    }
    fragment F0 on ViewerType {
      _entityListdSPVg:entityList {
        id,
        name
      },
      id
    }

I get the following error message:

`Fragment "F0" cannot be spread here as objects of type "NodeType" can never be of type "ViewerType".`

Am I still missing an important part?

EDIT:
Btw, should I ask here or better on Stackoverflow?

**Comment by jquense** [comment]
You might be interested in https://github.com/graphql-dotnet/relay generally. 

For your specific problem tho your query is confusing types. You are essentially trying to cast Viewer as a Node but then also expecting the cast Node to have Viewer fields. The error is really indicating that Node types don't have An entityList fielx

**Comment by MichaelHilus** [comment]
Thanks for your link, I will defineltly go deeper into that project.

The query that I posted was generated by my Relay based app after it was told to reload the `entityList`. I can't say how I could manipulate this in any way. But obiously `NodeType` is not the right type set when I define my node field, or am I wrong?
Should I define it to return a `ViewerType`?

**Comment by jquense** [comment]
ahh sorry...your Node Query should return a `NodeInterface` not a concert `Node` type e.g. `Field<NodeInterfaceType>()` GraphQL isn't aware of your c# inheritance (that's not codified in the schema)

**Comment by MichaelHilus** [comment]
Ah, thank you, that did the trick!
