### ISSUE TITLE
.net-core example?

### ISSUE THREAD

**Issue by ghost** [graphql-dotnet/graphql-dotnet#338]
Great repo. Enhancement: Wondering if a .net-core usage example available. Thanks.

**Comment by seralexeev** [comment]
Here is great example of using graphql-dotnet with dotnet core and EF core: https://github.com/JacekKosciesza/StarWars

**Comment by joemcbride** [comment]
Here's some middleware for .NET Core: https://github.com/wesamco/ASP.Net-Core-GraphQL-Middleware

**Comment by mahald** [comment]
Yea the above mentioned middleware is great. BUT don't forget to take the bugfixes from the open pull request. Else u will run into big trouble.

**Comment by sh1989** [comment]
^ That middleware pr has been merged now :)

**Comment by joemcbride** [comment]
Going to close this as I just added a .NET Core middleware example to the repo.
