### ISSUE TITLE
Filtering a ListGraphType, from a dynamic schema

### ISSUE THREAD

**Issue by GeekyEggo** [graphql-dotnet/graphql-dotnet#339]
I'm attempting to construct a schema dynamically, and then filter results. With the following snippet, I'm receiving `Unknown argument "id" on field "people" of type "root".`
```csharp
var person = new ObjectGraphType();
person.Name = "person";
person.Field<IntGraphType>("id");
person.Field<StringGraphType>("name");

var people = new ListGraphType(person);
people.Name = "people";
people.ResolvedType = person;

var root = new ObjectGraphType();
root.Name = "root";
root.AddField(new FieldType()
{
    Name = "people",
    ResolvedType = people
});

var schema = new Schema();
schema.Query = root;
return schema;
```
```javascript
query {
    people(id: 1) { 
        id,
        name
    }
}
```
I'm assuming I'm missing something, or I've misunderstood how to construct the schema. Any help is much appreciated.

**Comment by joemcbride** [comment]
This is how you add/use arguments: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md#arguments

**Comment by joemcbride** [comment]
[Here's an extension method](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs#L184-L199) that can help with registering fields in an instance-based API.

**Comment by GeekyEggo** [comment]
Thanks @joemcbride, that also answers another question I had regarding a _missing_ method within unit tests (the `Field(...)` one).

I've added the arguments successfully, however I'm having issues consuming them. It might be worth mentioning, I'm working against a single in-memory instance of a dynamic object. Ideally I'd like to auto-magically query the object, but appreciate that might not be supported as standard?

I'm currently setting the `Root` to the dynamic object when constructing a new `DocumentExecutor`.

**Comment by joemcbride** [comment]
> that might not be supported as standard

Correct, that is not standard behavior currently.  The "default" behavior is the [`NameFieldResolver`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Resolvers/NameFieldResolver.cs).  You can override that by just setting the resolver.

**Comment by GeekyEggo** [comment]
Thanks again @joemcbride, your feedback has given me enough insight to start work on a little "dynamic object schema builder". 😄
