### ISSUE TITLE
Implement Mutations

### ISSUE THREAD

**Issue by qorsmond** [graphql-dotnet/graphql-dotnet#340]
I had great success in implementing Queries so now I want to implement Mutations but are struggling as I don’t seem to find sample code in the GraphQL.StarWars section how to do mutations. 

I checked the section on mutations in the getting started guid, but cant figure out where to get IDocumentSession or how it should look. Is there a sample for the NerdDinner project somewhere that is shown there?

Tanks for the great lib!

**Comment by joemcbride** [comment]
Here are links to the NerdDinner sample.  `IDocumentSession` is a class from the [Marten](http://jasperfx.github.io/marten/) project.

https://github.com/joemcbride/marten/tree/graphql2/src/DinnerParty/Models/Schema
https://github.com/joemcbride/marten/blob/graphql2/src/DinnerParty/Modules/GraphQLModule.cs
