### ISSUE TITLE
UseMemoryCache don't work

### ISSUE THREAD

**Issue by Molochnikov** [graphql-dotnet/graphql-dotnet#3408]
Hello! Im using  GraphQL 7.1.1 Memory Cache package and register it in DI like that:
`.UseMemoryCache(options =>
                {
                    options.SizeLimit = 1_000_000;
                    options.SlidingExpiration = null;
                })`

My sample resolve is:

```
 public class Query : ObjectGraphType<object>
    {
        public Query(IBusinessData data)
        {
            Name = "Query";
          Field<ListGraphType<EmailType>, IEnumerable<Emails>>("emails")
                .ResolveAsync(context => data.GetAutomappedValuesAsync<Emails>("Emails", "Emails", "", context.UserContext));
            
```

where  `GetAutomappedValuesAsync` method is reading < 1MB data from web.

But every time i run `query {emails {id}}`  GraphQL making web request instead of reading from cache.

What i have missed in configuring cache?

**Comment by sungam3r** [comment]
`UseMemoryCache` feature is not about caching GraphQL responses. It is about caching GraphQL AST that is built from incoming GraphQL request (query string).

**Comment by sungam3r** [comment]
https://graphql-dotnet.github.io/docs/guides/document-caching/

**Comment by Molochnikov** [comment]
Thank you! Is there any implementation of response caching or some ideas?

**Comment by Shane32** [comment]
I would look here:

https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.memorycache?view=dotnet-plat-ext-7.0

Inside the resolver you can hit the cache first for the id before pulling the data from your source
