### ISSUE TITLE
ValidationContext.GetVariableValuesAsync has side effects

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3418]
Today I faced one funny bug (side effect) in one of our services. The same validation error was listed 5 times:
![изображение](https://user-images.githubusercontent.com/21261007/203378448-3ce6888a-40e6-4767-8457-144c756829a7.png)

This is "be design" of `ValidationContext.GetVariableValuesAsync`. This method parses inputs and coerces them into appropriate types. **Also** it reports validation errors via `ReportError` call (4 calls in ValidationContext.cs). OK? Yes... but this method is public and one of our custom validation rules calls it as well to get variables list. This rule does so inside `MathingNodeVisitor<GraphQLField>` so each time traversing algorithm visits some field `ValidationContext.GetVariableValuesAsync` method is called. In case of invalid variable **each** field in query yields new element in `ValidationContext.Errors` about the same problem. 5 fields -> 5 errors, 100 fields -> 100 errors. I think this is a design flaw. We should not add errors **inside** this method. Instead we should return them as a result along with variables. The only place where we use `GetVariableValuesAsync` is `DocumentValidator` just before returning `ValidationResult` to the called. The code easily may be rewritten to append returned collection of errors to existing errors in `context` variable:
![изображение](https://user-images.githubusercontent.com/21261007/203381085-e0465275-b9d4-41af-9905-3b5cc3802aa7.png)

But... it's a breaking change for `GetVariableValuesAsync`. Thoughts?

The current workaround for me now - make a clone of `ValidationContext` instance in our validation rule each time I want to call `GetVariableValuesAsync`.

**Comment by sungam3r** [comment]
ping @ekkeir

**Comment by Shane32** [comment]
I’m not looking at the code just now, but couldn’t we make it a lazy loaded property or something, so the code doesn’t run repeatedly? Seems like a design flaw to run the same code 100 times.

**Comment by Ekkeir** [comment]
Yep, that one is quite present for us.
I'm not sure we have choice in the matter as we have to construct our very own ResolveFieldContext with local fieldDef and fieldAst, so the variables are needed as well.
Caching sounds reasonable.

Variables aren't expected to change during a request's lifecycle, are they?

**Comment by sungam3r** [comment]
`Variables` class is mutable one.

**Comment by Shane32** [comment]
It may be mutable, but so is FieldType. Variables are not _expected_ to change.

**Comment by sungam3r** [comment]
> Seems like a design flaw to run the same code 100 times.

We don't do this on GraphQL.NET side. Only single call. Validation rules, as you know, do not touch variables. 

In our custom validation rule we can move `GetVariableValuesAsync` call outside mathing visitor i.e cache it on our side.

**Comment by sungam3r** [comment]
Also note that
![изображение](https://user-images.githubusercontent.com/21261007/203389654-72657432-0d6a-47cd-bcad-1e9ab3597865.png)
In case of caching, this stops working.

**Comment by Shane32** [comment]
Then it would still run at least twice.

If I remember right, in GraphQL.NET we run validation rules first to try and catch errors before parsing variables - correct? I’d have to see. 

Sometimes I feel like we should move custom validation rules so they run after both standard rules and variable parsing. And maybe remove the ability to skip standard rule checks. It’s an ongoing problem for custom validation rules to access variables

**Comment by Shane32** [comment]
> In case of caching, this stops working.

Interesting. Do you know why?

**Comment by sungam3r** [comment]
> in GraphQL.NET we run validation rules first to try and catch errors before parsing variables - correct?

Yes.
![изображение](https://user-images.githubusercontent.com/21261007/203390766-4387ba7f-9377-4adb-8b87-2410cad19a26.png)

> Interesting. Do you know why?

Because that visitor just will not be called in we introduce cache.

**Comment by sungam3r** [comment]
In short, I do not think that these variables need to be caсhed **inside** this method. It looks normal to cache the result on the caller side.

**Comment by Ekkeir** [comment]
> Sometimes I feel like we should move custom validation rules so they run after both standard rules and variable parsing. And maybe remove the ability to skip standard rule checks. It’s an ongoing problem for custom validation rules to access variables

For our use case this seems like quite a beneficial change.

**Comment by Shane32** [comment]
> Because that visitor just will not be called in we introduce cache.

Pretty sure that is incorrect.  The `DocumentValidator` is unaware of the cache and simply operates on whatever rules it has been provided, with the parsed (or cached) `Document`.  The `DocumentExecuter` executes any rules in the `ValidationRules` property.  The cache "execution middleware" will reset the `ValidationRules` property to the `CachedDocumentValidationRules` property if there is a cache hit.

There should be no reason why `IVariableVisitor`s returned from validation rules should not work with caching.  Unless of course the validation rule has been configured to skip execution for cached documents - which is why we provide that configuration option.  Any validation rule that depends on variables or external state (such as `HttpContext.User`) should be configured to run for cached documents.

**Comment by sungam3r** [comment]
Maybe we are talking about different things. `IVariableVisitor.VisitXXX` methods are called from inside `GetVariableValuesAsync` body - all that coercing stuff that you suggest to cache as a result of `GetVariableValuesAsync`. So caching will affect these calls as well - `IVariableVisitor.VisitXXX` methods just will not be called.

````
var vars1 = context.GetVariableValuesAsync(myVarVisitor); // first call to GetVariableValuesAsync: 1) returns some vars 2) caches them 3) myVarVisitor's methods are called here
var vars2 = context.GetVariableValuesAsync(myVarVisitor); // second call to GetVariableValuesAsync: 1) returns vars from cache 2) myVarVisitor's methods are **not** called here since builded `Variables` value already exists 
Console.WriteLine(object.ReferenceEquals(vars1, vars2)); // true
```

**Comment by Shane32** [comment]
Ok I see what you're saying.
