### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3431]
I used this setting when published release:
![изображение](https://user-images.githubusercontent.com/21261007/204730097-bf9d06fb-f3de-4578-8948-4b3adc982a93.png)

But UI shows it as latest:
![изображение](https://user-images.githubusercontent.com/21261007/204729968-7da0e420-5dc6-4294-bc44-473a27e13b97.png)

**Comment by Shane32** [comment]
Well that’s why I said we should release 7.2.0 at the same time, so it shows up as latest. The releases page always sorts by date.

**Comment by Shane32** [comment]
Review #3417 and we will release 7.2.0. It should be a simple review.

**Comment by sungam3r** [comment]
Closing this one as not important.
