### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by Kielek** [graphql-dotnet/graphql-dotnet#3448]
## Summary

Possibility to instrument GraphQL library by the OpenTelemetry.
Instrumentation should be [OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace) compliant.

### Basic example

Expected way to register GraphQL in OpenTelemetry is

```csharp
using OpenTelemetry.Trace;

public class Program
{
    public static void Main(string[] args)
    {
        using var tracerProvider = Sdk.CreateTracerProviderBuilder()
            .AddSource("GraphQL")
            .AddConsoleExporter()
            .Build();
    }
}
```

[MassTransit](https://masstransit-project.com/) introduced this feature in 8+ release. There is a possibility to check how it was implemented.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

[OpenTelemetry .NET AutoInstrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation) supports GraphQL instrumentation for [2.3.0,3.0.0) by bytecode instrumentation. Broader support has to be implemented separately.
It requires enabling .NET CLR profiling which is heavy operation and have big performance impact.
It can be avoided if instrumented library implements implement activity model based on [System.Diagnostics.DiagnosticSource v 6.0.0+](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/6.0.0).

It will allows to instrument GraphQL also without OTel AutoInstrumentation.

### Notes
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/graphql.md
https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/instrumentation/graphql.yml

**Comment by sungam3r** [comment]
In some sense this was answered in #2973 - here https://github.com/graphql-dotnet/graphql-dotnet/issues/2973#issuecomment-1053735273

**Comment by Shane32** [comment]
Each user may have their own needs for how and what is instrumented, so while it may not make sense to include an implementation inside GraphQL.NET, it may make sense to provide a sample implementation.  This is similar to how we provide a sample implementation of JWT bearer authentication for the server project, but due to necessary dependencies and the wide variety of usage and configuration options, it is not included.

@Kielek Would you be interested in working on this further?  The important thing is to determine what it is that should be logged; the implementation will be the easy part, and we can point you towards the classes necessary to write such an implementation.

**Comment by Kielek** [comment]
@Shane32, I have checked internally and I will probably not have a time in next month to look into it.

In OTel
we are instrumenting `GraphQL.Execution.ExecutionStrategy.ExecuteAsync` and `GraphQL.Execution.SubscriptionExecutionStrategy.ExecuteAsync`.

I would say that it is common practice as the same methods are used in DD and Splunk profilers.

**Comment by gao-artur** [comment]
Here is my implementation of the spec semantic conventions (depends on `OpenTelemetry.Extensions.DependencyInjection v1.4.0-rc.1`):
```csharp
public class GraphQLInstrumentationOptions
{
    public const string DiagnosticsName = "GraphQL";
    public bool RecordDocument { get; set; }
}

// https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/instrumentation/graphql/
public class GraphQLInstrumentationMiddleware : IFieldMiddleware
{
    private static readonly ActivitySource _activitySource = new(GraphQLInstrumentationOptions.DiagnosticsName);
    private static readonly ConcurrentDictionary<(OperationType type, string name), string> _activityNameCache = new();
    private static readonly IReadOnlyDictionary<OperationType, string> _operationTypes = new Dictionary<OperationType, string>
    {
        [OperationType.Query] = "query",
        [OperationType.Mutation] = "mutation",
        [OperationType.Subscription] = "subscription",
    };

    private readonly GraphQLInstrumentationOptions _options;

    public GraphQLInstrumentationMiddleware(IOptions<GraphQLInstrumentationOptions> options)
    {
        _options = options.Value;
    }

    public ValueTask<object> ResolveAsync(IResolveFieldContext context, FieldMiddlewareDelegate next)
    {
        if (!_activitySource.HasListeners() || context.Parent != null)
        {
            return next(context);
        }

        using var activity = CreateActivity(context);

        return next(context);
    }

    private Activity CreateActivity(IResolveFieldContext context)
    {
        if (!_activitySource.HasListeners())
        {
            return null;
        }

        var activityName = _activityNameCache.GetOrAdd(
            (context.Operation.Operation, context.Operation.Name?.StringValue),
            tuple => tuple.name == null
                ? _operationTypes[tuple.type]
                : $"{_operationTypes[tuple.type]} {tuple.name}");

        var activity = _activitySource.StartActivity(activityName);

        if (activity == null)
        {
            return null;
        }

        if (activity.IsAllDataRequested)
        {
            activity.SetTag("graphql.operation.name", context.Operation.Name?.StringValue);
            activity.SetTag("graphql.operation.type", _operationTypes[context.Operation.Operation]);

            if (_options.RecordDocument)
            {
                activity.SetTag("graphql.document", context.Document.Source.ToString());
            }
        }

        return activity;
    }
}

public static class GraphQLBuilderExtensions
{
    public static IGraphQLBuilder UseOpenTelemetryInstrumentation(
        this IGraphQLBuilder builder,
        Action<GraphQLInstrumentationOptions> configureGraphQLInstrumentationOptions = null)
    {
        if (builder is null)
        {
            throw new ArgumentNullException(nameof(builder), "Must not be null");
        }

        var services = ((GraphQLBuilder)builder).ServiceCollection;

        if (configureGraphQLInstrumentationOptions != null)
        {
            services.Configure(configureGraphQLInstrumentationOptions);
        }

        services.ConfigureOpenTelemetryTracerProvider((sp, tracerProviderBuilder) =>
        {
            tracerProviderBuilder.AddSource(GraphQLInstrumentationOptions.DiagnosticsName);
        });

        return builder.UseMiddleware<GraphQLInstrumentationMiddleware>();
    }
}
```

While everyone can implement this himself, this is the basic telemetry expected from every GraphQL server, so it makes sense to include it in this project. If someone needs more telemetry, they can implement additional middleware and add required tags to the already created activity/scope:
```csharp
Activity.Current?.SetTag("my.company.foo", "bar");
```

**Comment by Shane32** [comment]
The way this is set up, every single field generates telemetry.  It would seem that this could have a measurable performance impact on the application when returning a GraphQL request with thousands of individual fields.  If `RecordDocument` is enabled, it will also convert the entire source document into a string and record it for each telemetry event.  
Not only that, I don't see it is actually recording which field is executing, or the length of time it took to resolve the field, so I'm not sure what the point is.

Might it not make more sense to add the telemetry for the execution as a whole, via `.ConfigureExecution()`?  Then it can record data from `ExecutionOptions` such as the source document and operation name, plus timing data and success/failure or errors.  There would be additional complexity to properly gather telemetry for subscriptions, of course.  Perhaps a Document Listener would be more appropriate than `.ConfigureExecution()`.

**Comment by gao-artur** [comment]
Thanks for your feedback.
While the middleware will be triggered on every field, it will start the activity only when `context.Parent == null` means it's a root query field (do I understand this correctly?). But I agree, it would be better to do that on Executor level (I'm not familiar enough with lib internals). The `RecordDocument` should be enabled for debugging and never in production because of the performance hit you mentioned similar to [SetDbStatement](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.MySqlData#setdbstatement) in MySqlData instrumentation.
Regarding times: the activity records the time it's started and the duration until it's disposed. You don't need to add this info manually.
In general, as I said, this is the minimal required implementation just to set activity (scope), then users can add more on top of it.
This is how it looks like in Jaeger

![image](https://user-images.githubusercontent.com/4518483/209986365-0bfacc33-ed2b-43e1-b275-8139d41fb4c6.png)

The parent activity `/graphql` create by Asp.Net Core instrumentation has additional info about the web request, including the status code.

**Comment by Shane32** [comment]
Makes sense. Under CreateContext you’ll need to await the next(context) or else the way it is now it will only time synchronous code and no async continuations. Also even though it times root nodes, the time will not include executions of nested nodes.  I’d probably implement via ConfigureExecution which will then include all execution time of the entire request.

**Comment by gao-artur** [comment]
I've looked into ConfigureExecution, and I don't the OperationType in ExecutionOptions. It seems it's not available yet at this stage.

**Comment by gao-artur** [comment]
Trying another approach. Do you see any issues with it?
```csharp
public class OTelExecutionStrategySelector : IExecutionStrategySelector
{
    private readonly IOptions<GraphQLInstrumentationOptions> _options;
    private readonly IExecutionStrategySelector _selector;

    public OTelExecutionStrategySelector(
        IOptions<GraphQLInstrumentationOptions> options,
        IEnumerable<ExecutionStrategyRegistration> executionStrategyRegistrations)
    {
        _options = options;
        _selector = new DefaultExecutionStrategySelector(executionStrategyRegistrations);
    }

    public IExecutionStrategy Select(ExecutionContext context)
    {
        var strategy = _selector.Select(context);
        return new OpenTelemetryExecutionStrategy(_options, strategy);
    }
}

public class OpenTelemetryExecutionStrategy : IExecutionStrategy
{
    ...
    private readonly GraphQLInstrumentationOptions _options;
    private readonly IExecutionStrategy _executionStrategy;

    public OpenTelemetryExecutionStrategy(
        IOptions<GraphQLInstrumentationOptions> options,
        IExecutionStrategy executionStrategy)
    {
        _options = options.Value;
        _executionStrategy = executionStrategy;
    }

    public async Task<ExecutionResult> ExecuteAsync(ExecutionContext context)
    {
        if (!_activitySource.HasListeners())
        {
            return await _executionStrategy.ExecuteAsync(context);
        }

        using var activity = CreateActivity(context);

        return await _executionStrategy.ExecuteAsync(context);
    }

    public Task ExecuteNodeTreeAsync(ExecutionContext context, ExecutionNode rootNode)
    {
        return _executionStrategy.ExecuteNodeTreeAsync(context, rootNode);
    }

    public Dictionary<string, (GraphQLField field, FieldType fieldType)> GetSubFields(ExecutionContext context, ExecutionNode node)
    {
        return _executionStrategy.GetSubFields(context, node);
    }

    private Activity CreateActivity(IExecutionContext context)
    {
         ...
    }
```

**Comment by Shane32** [comment]
That works, for sure, and should work well.  It won't time the actual parsing of the document, or report if there's a failure during parsing.  Just FYI, you could use the result from `ConfigureExecution` to capture the operation name/type.  Personally I'd probably use `ConfigureExecution` to call `StartActivity` and append a document listener which calls `SetTag` to set the operation name/type.  Then assuming that there's failure during the call to `next(options)`, I'd call `SetTag` or similar to indicate if the result was successful.

```cs
.ConfigureExecution(async (options, next) =>
{
    using var activity = activitySource.StartActivity("GraphQL");
    if (options.OperationName != null) activity.SetTag("OperationName", options.OperationName);
    // log query/variables/etc here if desired
    options.Listeners.Add(new ActivityListener(activity));
    var ret = await next(options).ConfigureAwait(false);
    var successful = ret != null && !(ret.Errors?.Count > 0);
    activity.Status = successful ? ActivityStatusCode.Ok : ActivityStatusCode.Error;
    return ret;
})

public class ActivityListener : DocumentExecutionListenerBase
{
    private readonly Activity _activity;
    public ActivityListener(Activity activity) => _activity = activity;
    public override Task BeforeExecutionAsync(IExecutionContext context)
    {
        _activity.SetTag("Operation", context.Operation.Operation.ToString());
        return Task.CompletedTask;
    }
}
```

Of course your solution might be better -- I've not had actual experience with this logging framework.

**Comment by gao-artur** [comment]
Ok, I'll try that, thanks.

**Comment by gao-artur** [comment]
Actually, it won't work. [GrapgQL semantic conventions](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/instrumentation/graphql/) define the Activity (aka Span) name:

> The span name MUST be of the format <graphql.operation.type> <graphql.operation.name> provided that graphql.operation.type and graphql.operation.name are available. If graphql.operation.name is not available, the span SHOULD be named <graphql.operation.type>. When <graphql.operation.type> is not available, GraphQL Operation MAY be used as span name.

With `ConfigureExecution` the span name will be always `GraphQL Operation` which is not very useful.

**Comment by gao-artur** [comment]
The earliest place to create the activity seems to be immediately after this [block of code](https://github.com/graphql-dotnet/graphql-dotnet/blob/0de4b623923a724517a75e718c56d048749d1878/src/GraphQL/Execution/DocumentExecuter.cs#L116-L120) in `DocumentExecuter`
```csharp
var operation = GetOperation(options.OperationName, document);
if (operation == null)
{
    throw new InvalidOperationError($"Query does not contain operation '{options.OperationName}'.");
}
```
But there is no extension point.

**Comment by Shane32** [comment]
I see.  Then perhaps I would suggest this:

```cs
    .ConfigureExecution(async (options, next) =>
    {
        using var activity = activitySource.StartActivity("graphql");
        if (activity == null)
            return await next(options).ConfigureAwait(false);
        activity.SetTag("graphql.operation.name", options.OperationName);
        activity.SetTag("graphql.document", options.Query);
        options.Listeners.Add(new ActivityListener(activity));
        var ret = await next(options).ConfigureAwait(false);
        var successful = !(ret.Errors?.Count > 0);
        activity.SetStatus(successful ? ActivityStatusCode.Ok : ActivityStatusCode.Error);
        return ret;
    })

public class ActivityListener : DocumentExecutionListenerBase
{
    private readonly Activity _activity;
    public ActivityListener(Activity activity) => _activity = activity;
    public override Task BeforeExecutionAsync(IExecutionContext context)
    {
        var operationType = context.Operation.Operation.ToString().ToLowerInvariant();
        _activity.SetTag("graphql.operation.type", operationType);
        var operationName = context.Operation.Name?.StringValue;
        _activity.SetTag("graphql.operation.name", operationName);
        _activity.DisplayName = operationName == null ? operationType : $"{operationType} {operationName}";
        return Task.CompletedTask;
    }
}
```

This produces traces like this:

```
Activity.TraceId:            e35b8ab96d2bd97139562af3a7efd590
Activity.SpanId:             2b2bc4ab51a93262
Activity.TraceFlags:         Recorded
Activity.ParentSpanId:       8e0acf6a1ab838be
Activity.ActivitySourceName: MyCompany.MyProduct.MyService
Activity.DisplayName:        query test
Activity.Kind:               Internal
Activity.StartTime:          2022-12-30T16:23:07.5022708Z
Activity.Duration:           00:00:00.0005370
Activity.Tags:
    graphql.operation.name: test
    graphql.document: query test { hero }
    graphql.operation.type: query
StatusCode: Ok
Resource associated with Activity:
    service.name: MyCompany.MyProduct.MyService
    service.version: 1.0.0
    service.instance.id: bc9a8548-145d-494f-b585-b7b2ba7ae630

Activity.TraceId:            e35b8ab96d2bd97139562af3a7efd590
Activity.SpanId:             8e0acf6a1ab838be
Activity.TraceFlags:         Recorded
Activity.ActivitySourceName: Microsoft.AspNetCore
Activity.DisplayName:        /graphql
Activity.Kind:               Server
Activity.StartTime:          2022-12-30T16:23:07.5015445Z
Activity.Duration:           00:00:00.0240140
Activity.Tags:
    net.host.name: localhost
    net.host.port: 7250
    http.method: POST
    http.scheme: https
    http.target: /graphql
    http.url: https://localhost:7250/graphql
    http.flavor: 2.0
    http.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
    http.status_code: 200
Resource associated with Activity:
    service.name: MyCompany.MyProduct.MyService
    service.version: 1.0.0
    service.instance.id: bc9a8548-145d-494f-b585-b7b2ba7ae630
```

Complete sample as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GraphQL" Version="7.2.1" />
		<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="7.2.0" />
		<PackageReference Include="GraphQL.Server.Ui.Playground" Version="7.2.0" />
		<PackageReference Include="OpenTelemetry.Api" Version="1.4.0-rc.1" />
		<PackageReference Include="OpenTelemetry.Extensions.DependencyInjection" Version="1.4.0-rc.1" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0-rc.1" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.4.0-rc.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.10" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.10" />
		<PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc9.10" />
		<PackageReference Include="OpenTelemetry" Version="1.4.0-rc.1" />
	</ItemGroup>

</Project>
```

```cs
using System.Diagnostics;
using OpenTelemetry;
using OpenTelemetry.Exporter;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;
using GraphQL;
using GraphQL.Execution;
using Microsoft.Extensions.Options;

// Define some important constants to initialize tracing with
var serviceName = "MyCompany.MyProduct.MyService";
var serviceVersion = "1.0.0";

var builder = WebApplication.CreateBuilder(args);

// Configure important OpenTelemetry settings, the console exporter, and instrumentation library
builder.Services.AddOpenTelemetry().WithTracing(b => b
    .AddSource(serviceName)
    .SetResourceBuilder(
        ResourceBuilder.CreateDefault()
            .AddService(serviceName: serviceName, serviceVersion: serviceVersion))
    .AddHttpClientInstrumentation()
    .AddAspNetCoreInstrumentation()
    .AddSqlClientInstrumentation()
    .AddConsoleExporter(o => o.Targets = ConsoleExporterOutputTargets.Debug))
    .StartWithHost();

var activitySource = new ActivitySource(serviceName);

builder.Services.AddGraphQL(b => b
    .AddAutoSchema<Query>()
    .AddSystemTextJson()
    .ConfigureExecution(async (options, next) =>
    {
        using var activity = activitySource.StartActivity("graphql");
        if (activity == null)
            return await next(options).ConfigureAwait(false);
        activity.SetTag("graphql.operation.name", options.OperationName);
        activity.SetTag("graphql.document", options.Query);
        options.Listeners.Add(new ActivityListener(activity));
        var ret = await next(options).ConfigureAwait(false);
        var successful = !(ret.Errors?.Count > 0);
        activity.SetStatus(successful ? ActivityStatusCode.Ok : ActivityStatusCode.Error);
        return ret;
    })
);

var app = builder.Build();

app.UseGraphQL("/graphql");
app.UseGraphQLPlayground("/");

app.Run();

public class ActivityListener : DocumentExecutionListenerBase
{
    private readonly Activity _activity;
    public ActivityListener(Activity activity) => _activity = activity;
    public override Task BeforeExecutionAsync(IExecutionContext context)
    {
        var operationType = context.Operation.Operation.ToString().ToLowerInvariant();
        _activity.SetTag("graphql.operation.type", operationType);
        var operationName = context.Operation.Name?.StringValue;
        _activity.SetTag("graphql.operation.name", operationName);
        _activity.DisplayName = operationName == null ? operationType : $"{operationType} {operationName}";
        return Task.CompletedTask;
    }
}

public class Query
{
    public static string Hero => "Hello World";
}
```

This sets the operation name both initially, and after the document has been parsed, since the operation could a name even if it was not specified in the options.

Since all of this code simply relies on .NET 5+ classes, we could consider adding this code to GraphQL.NET.

**Comment by gao-artur** [comment]
Interesting. So it appears you can change the activity name which goes into `Activity.Operation` while OTel is interested in the `Activity.DisplayName` property. Good to know.
It could be great to add this piece of code to the library itself. I'd just add some configuration options to include/exclude the document, variables, and introspection query (as it's usually not interesting). Take a look at [Asp.Net instrumentation options](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/README.md#advanced-configuration).

**Comment by gao-artur** [comment]
Btw what happens if the query fails the validation? The listener won't be executed, right? So the activity will have the wrong name and probably the wrong operation type.

**Comment by Shane32** [comment]
See:
- #3467 

That's correct; however, if we move the listener code from `BeforeExecutionAsync` into `AfterValidationAsync`, then it will run even in the case of a failed validation.  Note that if the query fails to be parsed, the display name will simply be "graphql".

**Comment by Shane32** [comment]
It is possible that an unhandled exception could be caught while executing a validation rule, preventing the document listener from running.  However validation rules should not be throwing any exceptions.

It's also possible for the `ConfigureExecution` code to prepend a validation rule which would run prior to any other validation rules rather than using a document listener.

**Comment by gao-artur** [comment]
> It's also possible for the ConfigureExecution code to prepend a validation rule which would run prior to any other validation rules rather than using a document listener.

I like this more. Sounds simpler.

**Comment by sungam3r** [comment]
> Also even though it times root nodes, the time will not include executions of nested nodes. 

It's not bad at all. Tracing graph is not the same as a "flame graph". The relative position of the field spans inside the whole trace is more important - it will help to see places that could be performed in parallel, and not sequentially.

**Comment by sungam3r** [comment]
>  It won't time the actual parsing of the document, or report if there's a failure during parsing.

I'm 100% sure that document parsing and validation should be instrumented as well with their own activities. These are the main building blocks of entire GraphQL pipeline: parsing->validation->execution. That arises the question about what is the best way to inject activities into codebase. Custom document builder and document validator? Then `UseTelemetry` may register them in DI. But that may conflict with user code adding its own document builders / validators. Honestly, the idea to integrate activities directly into the main codebase does not leave me. I don’t even look at the new `System.Diagnostics.DiagnosticSource` dependency with such caution as I usually look at other dependencies. For NET5+ we get this dep just "for free". Maybe just take and use it as nuget dep for other TFMs?
![изображение](https://user-images.githubusercontent.com/21261007/218390837-fb48c6fa-73fe-42f5-a11b-7befbea88f92.png)
