### ISSUE TITLE
Testing with ReSharper in VS2017

### ISSUE THREAD

**Issue by kfrajtak** [graphql-dotnet/graphql-dotnet#345]
Hi,

I have tried running the tests in VS2017 with ReSharper, but got this error (and none of the tests were executed)

```
JetBrains.ReSharper.UnitTestFramework.DotNetCore.Exceptions.ProcessExitedUnexpectedlyException: dotnet exited unexpectedly with the code (-1)
Output stream: 
Error stream: dotnet-test Error: 0 : System.InvalidOperationException: C:\Work\git\graphql-dotnet\src\GraphQL.Tests\project.json does not exist.
```

When I have created the project.json file, 
```
{
  "version": "1.0.0-*",
  "dependencies": {
    "System.Runtime.Serialization.Primitives": "4.3.0",
    "xunit": "2.2.0-*",
    "dotnet-test-xunit": "2.2.0-*"
  },
  "testRunner": "xunit",
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      }
    },
    "net452": {
    }
  }
}
```

I got this 
```
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
```

I might be missing something, can you please help?
Thanks,
Karel

**Comment by jquense** [comment]
Not sure how that would be related to this project. Sounds like you have something in VS or ReSharper configured or installed wrong

**Comment by kfrajtak** [comment]
Thanks Jason for your reply. I was not implying there's something wrong
with the project, I just ran into this problem and wondered if anybody had
the issue.

**Comment by wallymathieu** [comment]
Could be that resharper is running the tests from a different folder than another test runner. Sometimes you got to make sure to copy some files, make sure to locate the files next to the dlls, et.c.?

**Comment by wallymathieu** [comment]
Shouldn't you use csproj format in order to test it with VS2017?

**Comment by kimbell** [comment]
Project.json is only supported on VS2015. For VS2017, you need to upgrade the project type to the new csproj format.

**Comment by joemcbride** [comment]
Closing this as I am able to run the project in latest VS + Resharper.
