### ISSUE TITLE
Bounty program note in package readme

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3450]
Include note about bounty program right into packages descriptions so devs can see it on nuget.org. This can cover a much larger audience, because not everyone reads readme/release notes.

**Comment by Shane32** [comment]
PR #3396  includes changes to the readme, which will appear prominately on nuget.org.  The package description field does not appear on nuget.org if the readme is configured.

**Comment by Shane32** [comment]
We would need to publish a new release to make the update readme appear, of course.

**Comment by sungam3r** [comment]
Ok. Just need to check. I remember that nuget.org has some restrictions on readme contents and does not support  all markdown features.

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/233929136-831efd57-84f5-448a-9bd2-ca0ddd120daa.png)

**Comment by sungam3r** [comment]
@Shane32 I noticed that `Get paid for contributing` link points to https://www.nuget.org/packages/GraphQL/ . I fixed it in https://github.com/graphql-dotnet/graphql-dotnet/commit/3c6ceeece473925e1cf668314fa71fa2006d1142
