### ISSUE TITLE
Improve Enum resolver errors

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/graphql-dotnet#3451]
Let's say I have two similar enums in different namespaces
```
namespace A
{
    public enum MyEnum { Val }
}

namespace B
{
    public enum MyEnum { Val }
}
```
And I have a field defined like this
```
query.Field<EnumerationGraphType<A.MyEnum>>("myEnum").Resolve(context => B.MyEnum.Val);
```

Before the upgrade from v4 to v7 this code worked (even though it was wrong), but after the upgrade, I started receiving the runtime error

> Unable to serialize 'Val' to the scalar type 'MyEnum'.
System.InvalidOperationException: Unable to serialize 'Val' to the scalar type 'MyEnum'.
   at GraphQL.Types.ScalarGraphType.ThrowSerializationError(Object value) in /_/src/GraphQL/Types/Scalars/ScalarGraphType.cs:line 251
   at GraphQL.Execution.ExecutionStrategy.CompleteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 553

Without manually checking the namespace of the enum in the field definition and the resolver, it's hard to understand what's wrong because the `Val` exist in the `MyEnum`. Adding this information to the error message will make the mistake more obvious.

I also tried to write a field visitor to find such mistakes in my graph, but unfortunately, `IFieldResolver` hides the information about resolving delegate and its return type. Is there any other way to find it without manually checking field after field?

**Comment by sungam3r** [comment]
> Adding this information to the error message will make the mistake more obvious.

I'm 50/50 here. Of course we can add additional information about namespace of "wrong" value into message.

Something like
```"Unable to serialize 'Val' of type B.MyEnum to the scalar type 'MyEnum'.```

**Comment by sungam3r** [comment]
And of source this change (if desired) should be done in all `ThrowXXX` methods in `ScalarGraphType`.

**Comment by gao-artur** [comment]
@Shane32 I'm aware of these options. My question was if there is any way to find the wrong resolvers. We have nearly 100 fields of Enum type, and checking all of them or changing their definition to get compile time errors is not a trivial task.

**Comment by Shane32** [comment]
Unfortunately for the sample you provided, the delegate is of type `Func<IResolveFieldContext<TSource>, object>`, and so although you could check the type of the `FuncFieldResolver<,>` generated, it would indicate the return type of `object`, which doesn't help you.

**Comment by gao-artur** [comment]
I see. Thank you for the reply!

**Comment by sungam3r** [comment]
I think the same.

>  this would seem like too much of an edge case to warrant it.

yeah.

Though I still think that it will be better to modify error messages in ScalarGraphType to include clr type name. Other messages do.

**Comment by sungam3r** [comment]
Also see https://github.com/graphql-dotnet/graphql-dotnet/pull/3630

**Comment by Shane32** [comment]
@gao-artur Close issue?

**Comment by gao-artur** [comment]
Yes, you can close it.
