### ISSUE TITLE
Feature: IAsyncEnumerable support for subscriptions

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3454]
## Summary

Currently the `AutoRegisteringObjectGraphType` class supports subscriptions that return `IObservable<T>`.  While this works great when the application is built with some type of broadcast mechanism, such as a singleton that returns `IObservable<T>` results, it's not so great when you want to write an async iterator method.  This is useful most specifically in a couple scenarios:

1. You want to write some code as an observable that performs a certain task, periodically returning results.
2. You want to write async code that pulls results from another `IAsyncEnumerator` via `await foreach`, processes them and yields them.

### Example

The below sample shows one possible use case: a subscription field that performs a task over a period of time, using a GraphQL subscription to report on progress.  The code demonstrates (1) the code may throw an exception, which is properly reported through GraphQL (2) the code may finish, which is properly reported by a completed subscription (3) the code may return an arbitrary number of data packets (4) the code may be notified of an unsubscription request (or TCP disconnection) via a cancellation token.

```cs
public class Subscription
{
    [Scoped]
    [Description("Generates random numbers between the specified numbers until the magic number is generated")]
    public static async IAsyncEnumerable<DiceStatusModel> RollDiceAsync(
        int min, int max, int magic, int crash,
        [FromServices] Random rng, // demo scoped service
        CancellationToken cancellationToken)
    {
        do {
            var num = rng.Next(min, max);
            if (num == magic) {
                // demonstrate returning a model and ending the enumerable
                yield return new DiceStatusModel { Description = $"Matched number {magic}" };
                yield break; // gracefully end the enumerable
                // alternate in this example: break; will quit the do loop, and exiting the method
                // will gracefully end the enumerable
            }
            if (num == crash) {
                // demonstrate ending the enumerable by throwing an exception
                throw new ExecutionError($"Cannot handle number {crash}");
            }
            // demonstrate returning status
            yield return new DiceStatusModel { Description = $"Rolled number {num}" };
            await Task.Delay(2000, cancellationToken);
        } while (true);
    }

    public class DiceStatusModel
    {
        public string Description { get; set; } = null!;
    }
}
```

### Existing workaround

By referencing the `System.Linq.Async` nuget package, the `ToObservable` extension method can be used to map an `IAsyncEnumerable` into an `IObservable`.  However it requires excess boilerplate code that reduces code readability.  On top of that, `[Scoped]` is useless, so if scoped services are needed, `[FromServices]` cannot be used.  Plus, `[EnumeratorCancellation]` is required for proper operation.  Below is a sample:

```cs
    [Description("Generates random numbers between the specified numbers until the magic number is generated")]
    public static IObservable<DiceStatusModel> RollDice(
        int min, int max, int magic, int crash,
        [FromServices] IServiceScopeFactory scopeFactory,
        CancellationToken cancellationToken)
    {
        // requires System.Linq.Async dependency
        return RollDiceAsync(min, max, magic, crash, scopeFactory, cancellationToken).ToObservable();
    }

    private static async IAsyncEnumerable<DiceStatusModel> RollDiceAsync(
        int min, int max, int magic, int crash,
        IServiceScopeFactory scopeFactory,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        await using var scope = scopeFactory.CreateAsyncScope();
        var rng = scope.ServiceProvider.GetRequiredService<Random>(); // demo scoped service
        // ** remainder of method here **
    }
```

### Challenges

One challenge will be handling service scope.  It will be easy enough to build in automatic mapping from a return type of `IAsyncEnumerable` to `IObservable`, however, the service scope created by `[Scoped]` would end before the async iterator completes, causing the services created within the service scope to crash.  One way to solve this (within GraphQL.MicrosoftDI where `[Scoped]` lives) is by detecting a `SourceStreamMethodResolver` and hooking into its internals or something.  Unfortunately this means that when coupled with another attribute that modifies the resolver (we have no such attribute), the functionality may break depending on the order of the attributes.  However, field middleware applies later on, so it should not be affected.  Another option may be to keep the service scope alive until the subscription is disposed.  This would work well in any scenario (but the code will be based on fact that an `IObservable` used by GraphQL is only used a single time).

The second challenge is the cancellation token.  Without `[EnumeratorCancellation]` the cancellation token will not be tied to the unsubscribe request, potentially leaving the code running perpetually until the websocket connection disconnects.  This is unacceptable; and so I will not be able to copy-and-paste the `ToObservable` method that System.Linq.Async uses.  However, it should be elegantly solvable (although undoubtedly complicated).  An easy solution would be to throw an exception at build time if the cancellation token is not marked with `[EnumeratorCancellation]`, but there are three reasons against this: (1) `IResolveFieldContext.CancellationToken` would still report the wrong cancellation token (2) if the method returns `IAsyncEnumerable<T>` but isn't an async iterator method, then the marking is pointless, and potentially could have the same issue if the method it maps to is not marked with the attribute (3) it's simply more cumbersome to use that way.  So rather I will just tie the cancellation token created for the `IObservable` mapping into the `IResolveFieldContext` prior to executing the method, and all the code will flow naturally with the correct cancellation token.

### Summary

This will be a tough task, but one which I would like to proceed with.  The implementation will be complicated due to the challenges listed above, and especially because it will be intertwined with the already-complex `SourceStreamMethodResolver` class and related functionality.  I would appreciate any comments before beginning this.

**Comment by sungam3r** [comment]
>  On top of that, [Scoped] is useless, so if scoped services are needed, [FromServices] cannot be used.

Why?

**Comment by sungam3r** [comment]
> The second challenge is the cancellation token. Without [EnumeratorCancellation] the cancellation token will not be tied to the unsubscribe request, potentially leaving the code running perpetually until the websocket connection disconnects

Some time ago, I began to read about [EnumeratorCancellation], but I did not understand what it was and postponed reading.

**Comment by sungam3r** [comment]
> This will be a tough task

And reviewing as well. I think I got the core idea but I do not understand the details, because I do not use subscriptions code. I will try not to delve into the details.

**Comment by Shane32** [comment]
> > On top of that, [Scoped] is useless, so if scoped services are needed, [FromServices] cannot be used.
> 
> Why?

Well that's not entirely accurate.  Previously `[Scoped]` could be useful when performing tasks PRIOR to returning the `IObservable`.  But if the `IObservable` instance was pulled from a scoped service, then it would be disposed before the `IObservable` was actually used.

So like you could access a scoped DbContext to check some variables from the database, but then you have to create/pull `IObservable` only from singleton services.

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/210186564-86fce0f8-0649-4a42-b286-95c04b5aa6f2.png)
