### ISSUE TITLE
FieldResolvers not triggered in SourceStreamResolvers

### ISSUE THREAD

**Issue by bbjoern** [graphql-dotnet/graphql-dotnet#3459]
Hi everyone,

first of all thanks for your awesome work!

Currently I'm stuck in one question: shouldn't FieldResolvers of my ObjectGraphType be triggered on my SourceStreamResolver as well ? If yes, its not working for me

This is my SourceStreamResolver 

            AddField(new FieldType 
            {
                Name = "eventAdded",
                Type = typeof(EventVMType),
                Resolver = new FuncFieldResolver<EventVM>(context => context.Source as EventVM),
                StreamResolver = new SourceStreamResolver<EventVM>(context => {
                    var appAndUserId = SecurityHelper.GetAppAndUserId((context.UserContext as GraphQLUserContext).User);
                    return this._eventSubscriptionSubject.OnEvent(appAndUserId);
                })
            });

I'm adding the changed EventVM-object and it is corretly delivered to my front-end. Yet the FieldResolver which should load additional information to the object isn't triggered

        public EventVMType(IServiceProvider serviceProvider)
        {
            Field(x => x.Id, nullable:true);
            Field(x => x.Name, nullable: true);
            Field(x => x.Host, nullable:true, type: typeof(ContactVMType)).ResolveAsync(context => {
                if(context.Source.HostId.HasValue){
                    var loader = serviceProvider.GetRequiredService<ContactByIdDataLoader>();
                    var result = loader.LoadAsync(context.Source.HostId.Value);
                    return (Task<ContactVM?>) result;
                }
                return Task.FromResult<ContactVM?>(null);
            });

Am I missing some point ? Or is this simply not possible ?!

Appreciate any help !

Thanks
Björn

**Comment by Shane32** [comment]
Which version of GraphQL.NET are you using?

I don't initially see anything wrong.  Yes the field resolver should also execute, but your code as listed above is simply `context => context.Source as EventVM` which seems correct.  Which line of code is the code that doesn't appear to be executing?

Now if you're referring to the data loader use in the second snippet (the "Host" field), it would appear that you have data loader code that is based on version 2.x, as I see it returns a `Task<T>`.  Data loaders in v3.x and newer return an `IDataLoaderResult<T>` value and work quite a bit differently, solving some inherit problems in the old data loader design.  The new data loaders are fully supported with subscriptions.  I don't think the old data loaders are supported at all anymore, even if you copied the old code, due to the removal of `IDocumentExecutionListener.BeforeExecutionStepAwaitedAsync` in v5.

**Comment by bbjoern** [comment]
Sorry about the mission version. I'm using

```
<TargetFramework>net6.0</TargetFramework>
<PackageReference Include="GraphQL.Server.All" Version="7.1.1" />
```

The line of code that is not executing is the FieldResolver of EventVMType for example when debugging in line

`if(context.Source.HostId.HasValue){ `

The data loader looks like this. (I took from the examples https://graphql-dotnet.github.io/docs/guides/dataloader/#di-based-data-loaders )

```
public class ContactByIdDataLoader : DataLoaderBase<int, ContactVM>
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly IMediator _mediator;
    private readonly IMapper _mapper;

    public ContactByIdDataLoader(IHttpContextAccessor httpContextAccessor, IMediator mediator, IMapper mapper): base(false)
    {
        _httpContextAccessor = httpContextAccessor;
        _mediator = mediator;
        _mapper = mapper;
    }

    protected override async Task FetchAsync(IEnumerable<DataLoaderPair<int, ContactVM>> list, CancellationToken cancellationToken)
    {
        IEnumerable<int> ids = list.Select(pair => pair.Key);
        
        var applicationId = SecurityHelper.GetApplicationId(_httpContextAccessor.HttpContext.User);
        var userId = SecurityHelper.GetUserId(_httpContextAccessor.HttpContext.User);
        var request = new ContactReadByIdsRequest{ ContactIds = ids };
        var contacts = await _mediator.Send(request);
        var contactVMs = _mapper.Map<IEnumerable<ContactVM>>(contacts);

        var data = contactVMs.ToDictionary(x => x.Id);

        foreach (DataLoaderPair<int, ContactVM> entry in list)
        {
            entry.SetResult(data.TryGetValue(entry.Key, out var order) ? order : null);
        }
    }
}

```
For queries this all works fine and the docs (link from above) says that this is the right way to implement a data loader. I'm a little bit confused about data loaders v2.x vs v3.x. Do you have any examples or additional docs to this ?

**Comment by Shane32** [comment]
Try this and see if you get anywhere:

```cs
using GraphQL.DataLoader;

    public EventVMType()
    {
        Field(x => x.Id, nullable:true);
        Field(x => x.Name, nullable: true);
        Field(x => x.Host, nullable:true, type: typeof(ContactVMType))
            .Returns<ContactVM>() // should not be needed if x.Host is of type ContactVM
            .ResolveAsync(context => {
                if(context.Source.HostId.HasValue){
                    var loader = context.RequestServices.GetRequiredService<ContactByIdDataLoader>();
                    var result = loader.LoadAsync(context.Source.HostId.Value);
                    return result; // should be of type IDataLoaderResult<ContactVM>
                }
                return null!;
            });
```

Is your schema registered as a singleton or scoped?  What about the data loader (`ContactByIdDataLoader`)?

**Comment by Shane32** [comment]
Alternatively without the `using` then you can use `.Returns<IDataLoaderResult<ContactVM>?>()` along with `.Resolve(...)` rather than `ResolveAsync`.  But with `using GraphQL.DataLoader` there's an extension method to take care of that for you.

**Comment by bbjoern** [comment]
@Shane32 Thanks for your support ! The suggested changes didn't work yet my solution already worked. The missing point was that the Subject of the StreamResolver wasn't triggered in my code. 

```
StreamResolver = new SourceStreamResolver<EventVM>(context => {
    var appAndUserId = SecurityHelper.GetAppAndUserId((context.UserContext as GraphQLUserContext).User);
    return this._eventSubscriptionSubject.OnEvent(appAndUserId);
})
```

When i pushed to "_eventSubscriptionSubject" the FieldResolvers got fired !

Again thank you for the support !
