### ISSUE TITLE
Unable to build Xamarin iOS App (Could not AOT the assembly) since version 5.4.0

### ISSUE THREAD

**Issue by andreaslausen** [graphql-dotnet/graphql-dotnet#3460]
Hi,

we have a Xamarin App running on iOS which has full offline capability and shares a huge amount of code with the server. Therefore we are using GraphQL.Net (the server part) inside the Xamarin App on iOS.
We recently upgraded from version 4.5.0 to the latest version. Unfortunately it is no longer possible to build the app because of the following error:

`Could not AOT the assembly '/Users/alausen/git/stationaer/MontBlanc/mobile/App/MediFoxDAN.MontBlanc.Doku.App.UI.iOS/obj/iPhone/Release/mtouch-cache/3-Build/GraphQL.dll'`

Further investigation revealed that there must have been some changes between versions 4.5.0 and 5.4.0 that cause this issue.

This can be worked around by enabling the Xamarin Interpreter (see https://devblogs.microsoft.com/xamarin/introducing-xamarin-ios-interpreter/). But enabling the Xamarin Interpreter causes major performance issues and is not a viable solution for us.

As a workaround we downgraded to version 4.5.0, but we need a long term solution.

Is there any way to fix this issue in future releases?

Thanks

Andreas

**Comment by sungam3r** [comment]
It is rather generic error. In fact it says nothing about the core problem. If you provide some more information about why GraphQL.dll assembly could not be AOT-ed then we can investigate.

**Comment by Shane32** [comment]
GraphQL.NET is currently not designed to be AOT-ed -- at least, not by .NET 7.  There are many bits of dynamically-constructed types which usually pose quite a problem for AOT compilation.  However, I've not had any problems during compilation, but rather at runtime, and mostly just trimming errors.  Within PR #3461 I've demonstrated changes to GraphQL.NET necessary to support AOT compilation and a demo application that executes the StarWars demo schema with no changes to the schema.

I find it very interesting that you were able to AOT-compile and run GraphQL.NET v4.5.0.  It is very likely that Xamarin compiles differently than .NET 7 does; hence the difference.  If you can provide a sample project, which can be built on Windows, demonstrating how it compiles with 4.5.0 and not with 5.4.0, I could investigate further.  I do not have access to a Linux or Mac operating system.

Until then, the most I can do is get AOT compilation working for .NET 7.

**Comment by lausen1** [comment]
Hi,

thanks for the details.

Unfortunately it is not possible to reproduce this issue on a Windows machine.

I will try to further investigate the problem myself and get back to you.


Thanks

Andreas

**Comment by Shane32** [comment]
Please let us know if you have further information on this topic.
