### ISSUE TITLE
Question: How to create static Connection field

### ISSUE THREAD

**Issue by need** [graphql-dotnet/graphql-dotnet#3462]
I  create connection like below code 

`  public static Connection<News> Data1()
    {
        return new Connection<News>();
    }
`
`
    public static Connection<ArticlePicture> Data2()
    {
        return new Connection<ArticlePicture>();
    }`

but get error

`[Error] "Unable to register GraphType 'AutoRegisteringObjectGraphType<Connection<ArticlePicture>>' with the name 'Connection'. The name 'Connection' is already registered to 'AutoRegisteringObjectGraphType<Connection<News>>'. Check your schema configuration."`

if only Data1 field remove Data2 field, no error.

 I use GraphQL Server version is GraphQL.Server.All 7.2.0 

How to create static connection correctly?

Can anybody help? many thanks!

**Comment by need** [comment]
Thanks for your reply.

I try way 1 get below error
`[Error] Unable to register GraphType 'AutoRegisteringObjectGraphType<Edge<ArticlePicture>>' with the name 'Edge'. The name 'Edge' is already registered to 'AutoRegisteringObjectGraphType<Edge<News>>`

way 2 get below error
`[Error] "Unable to register GraphType 'ConnectionType<AutoRegisteringObjectGraphType<ArticlePicture>>' with the name 'AutoRegisteringObjectConnection'. The name 'AutoRegisteringObjectConnection' is already registered to 'ConnectionType<AutoRegisteringObjectGraphType<News>>'`

**Comment by Shane32** [comment]
Hmm... you're right

Well, unfortunately i'd probably just create the edge type and connection type and name each of the types.  Perhaps in the next version of GraphQL.NET we can change the automatic naming algorithm for connection types.

```cs
public class NewsConnectionType : ConnectionType<AutoRegisteringObjectGraphType<News>, NewsEdgeType<AutoRegisteringObjectGraphType<News>>>
{
    public NewsConnectionType()
    {
        Name = "NewsConnection";
    }
}

public class NewsEdgeType : EdgeType<AutoRegisteringObjectGraphType<News>>
{
    public NewsEdgeType()
    {
        Name = "NewsEdge";
    }
}

// [OutputType(typeof(NewsConnectionType))]
// or
// [OutputType(typeof(NonNullGraphType<NewsConnectionType>))]
```

An alternate method is to create a concrete type for `News`:

```cs
// note: be sure to end this name in "GraphType"
public class NewsGraphType : AutoRegisteringObjectGraphType<News>
{
}

// [OutputType(typeof(ConnectionType<NewsGraphType>))]
// or
// [OutputType(typeof(NonNullGraphType<ConnectionType<NewsGraphType>>))]

// but will need to be sure the CLR type mapping is registered properly so other references to `News`
// e.g. .AddClrTypeMappings() during DI configuration
// or this.RegisterTypeMapping<News, NewsGraphType>() during schema configuration
```

You can also register the type mapping for `Connection<News>` so you don't need to use `[OutputType]`

```cs
// in schema constructor, or within ConfigureSchema:
schema.RegisterTypeMapping<Connection<News>, NewsConnectionType>();
// or ConnectionType<News> depending on the solution picked above
```

In this way nullability is automatically determined.

**Comment by Shane32** [comment]
There's just so many different ways to perform the same task....
