### ISSUE TITLE
Graph types' automatic names are not distinct for generic classes

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3465]
This is a problem when there's a type such as `Connection<News>` which is generated as `Connection` rather than `ConnectionNews` or `NewsConnection`.  This then conflicts with `Connection<Article>` and similar.  Obviously we could hard-code detection for `Connection<T>` and `Edge<T>`, but I feel we should solve this for any generic type.  This is more distinctly a problem for auto-registering graph types, (and auto-registering schemas) where there typically is no class definition and so cannot be easily solved by adding a single line of code.  Since the object type is a generic type, one cannot add an attribute to the class to set the auto-generated name either.

Suggestions:

1. Include the generic type name(s) of the class when generating a GraphQL name for a class, in the order they appear.  So this means:

| Class Name | Graph Name |
|-|-|
| `News` | `News` |
| `Connection<News>` | `ConnectionNews` |
| `Data<Connection<News>>` | `DataConnectionNews` |
| `Data<News, Obj>` | `DataNewsObj` |

2. Same, but reverse order

| Class Name | Graph Name |
|-|-|
| `News` | `News` |
| `Connection<News>` | `NewsConnection` |
| `Data<Connection<News>>` | `NewsConnectionData` |
| `Data<News, Obj>` | `ObjNewsData` |

3. Introduce a global switch to configure the naming algorithm, with three options: current, option 1 above, and option 2 above.

Option 1 makes the most sense at first glance, although the current use case (relay types) would indicate that option 2 would be preferred -- in fact, required to meet GraphQL relay spec (connection types must end in "Connection").  Option 3 also has quite a bit of merit, as it could be introduced now in version 7 with the option of changing the default for version 8, while also allowing for easy backwards-compatible behavior in v8 if we change the default.  It also allows users to choose between option 1 and option 2.  However, I generally prefer to choose an specific answer over adding a global switch.  Global switches add more code to be maintained, and are unlikely for users to realize they even exist.

So at the moment, I'd just go with option 2 and put the feature in v8.  My second choice is option 3, with option 2 being the default setting in v8.  I'd also be happy to introduce a global switch for v7 to use the v8 naming strategy, removing the global switch for v8.

**Comment by sungam3r** [comment]
60/40 for 2 vs 3.

**Comment by Shane32** [comment]
See:
- #3462

**Comment by Shane32** [comment]
@gao-artur Thoughts on this issue?

**Comment by gao-artur** [comment]
I like 2 except the `Data<News, Obj>` => `ObjNewsData`. I think It should be `NewsObjData`. Nested generics are in reverse order; siblings are in the same order.

I suggest going for a global switch to allow backward compatibility because this change on the server side will require adopting the client. In scenarios like ours, when client and server have different release cycles, it can be a problem. So this is the best option in my opinion:

> I'd also be happy to introduce a global switch for v7 to use the v8 naming strategy, removing the global switch for v8.

It will solve the problem for v7 users, giving them time to adopt before the removal of the global switch in v8.

**Comment by Shane32** [comment]
Patch for v7:

```cs
GlobalSwitches.GlobalAttributes.Add(new FixNamingAttribute());

public class FixNamingAttribute : GraphQLAttribute
{
    public override void Modify(IGraphType graphType)
    {
        var type = graphType.GetType();
        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(AutoRegisteringObjectGraphType<>)) {
            graphType.Name = NameOf(type.GetGenericArguments()[0]);
        }

        static string NameOf(Type type)
        {
            if (!type.IsGenericType)
                return type.Name;
            var sb = new StringBuilder();
            foreach (var arg in type.GetGenericArguments()) {
                sb.Append(NameOf(arg));
            }
            sb.Append(type.Name[..type.Name.IndexOf("`")]);
            return sb.ToString();
        }
    }
}
```

**Comment by Shane32** [comment]
There's no real clear way to fix this; it's a hot mess right now.

Currently, graph types' default names are derived from the class name of the graph type and works like this:

| Sample class | Name | Notes |
|-|-|-|
| `MyInput` | `MyInput` | it's a graph type and shouldn't be named this |
| `MyInputGraphType` | `MyInput` | |
| `MyInputType` | `MyInputType` | |
| `MyClass.MyInputGraphType` | `MyInput` | when `UseDeclaringTypeNames` is `false` |
| `MyClass.MyInputGraphType` | `MyClass_MyInput` | when `UseDeclaringTypeNames`  is `true` |
| `MyInputGraphType<TSourceType>` | `MyInputGraphType_1` | poor naming strategy |
| `Auto@1` | `Auto_1` | auto-generated F# classes contain `@` - see #3472 |

Now for the auto-registering types, it calls `GraphQLName` on `TSourceType` and works like this:

| Sample TSourceType | Name | Notes |
|-|-|-|
| `MyInput` | `MyInput` | |
| `MyInputGraphType` | `MyInput` | it's not a graph type; this logic doesn't make sense |
| `MyInputType` | `MyInput` | this might be used for schema-first classes?? doesn't make sense to me |
| `MyClass.MyInput` | `MyInput` | ignores `UseDeclaringTypeNames` |
| `MyInput<Cat>` | `MyInput` | ignores generic type arguments |

Finally, for `ConnectionType<TEdgeType>`, it takes `TEdgeType` and passes it to `GraphQLName`, then adds "Connection" on the end.  So while above `GraphQLName` is used for data model types, now it's used for graph types!?!

| Sample | Name | Notes |
|-|-|-|
| `ConnectionType<MyInputType>` | `MyInputConnection` | |
| `ConnectionType<MyInputGraphType>` | `MyInputConnection` | now we see the weird logic above being useful |
| `ConnectionType<MyInputType<Cat>>` | `MyInputConnection` | poor naming |

**Comment by Shane32** [comment]
I'd like to unify the naming in to a single method.  Then use `if (typeof(IGraphType).IsAssignableFrom(type))` if there is different logic between selecting a name based on a graph type class or a data model class.

Should `GlobalSwitches.UseDeclaringTypeNames` have effect only for default graph type names?

Also, should I add a global switch with an enum to select between different naming strategies?  Should I just add a flag `UseLegacyTypeNaming` or something?

**Comment by Shane32** [comment]
> I like 2 except the `Data<News, Obj>` => `ObjNewsData`. I think It should be `NewsObjData`. Nested generics are in reverse order; siblings are in the same order.

Agree

> I suggest going for a global switch to allow backward compatibility because this change on the server side will require adopting the client. In scenarios like ours, when client and server have different release cycles, it can be a problem. So this is the best option in my opinion:
> 
> > I'd also be happy to introduce a global switch for v7 to use the v8 naming strategy, removing the global switch for v8.
> 
> It will solve the problem for v7 users, giving them time to adopt before the removal of the global switch in v8.

I'm thinking that we should add a switch now and just deprecate it in v8.  If we add the switch now and make the change immediate, then we break compatibility within v7.  This really isn't a bug fix so much as a feature change.  If we just add the switch and immediately deprecate it, it is unlikely anyone will notice the deprecation because the switch is not in use.  So it seems we need to add the switch and make the change, giving people time to read the release notes and notice the change, and time to fix it later rather than having to edit all their graphs immediately.

So all that being said, I think we should add the switch now, and change the default value of the switch in v8, deprecating it at that time.

**Comment by Shane32** [comment]
The version goal being that within a major version, only non-breaking changes (unless they can reasonably called bug or security fixes), and across major versions, breaking changes are allowed, favoring a method to give users time to make changes instead of forcing all changes during the upgrade.  (Sometimes this is possible, sometimes not.)
