### ISSUE TITLE
EnsureTypeEquality enhancements

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/graphql-dotnet#3480]
Asks:
------------------
1. Would it be possible to get more verbose logging out of the terminal exception case?
2. Can AnyScalarGraphType be added to the EnsureTypeEquality check.

Details:
-------------------
Working on upgrading from 3.3 to 7.2 and I'm running into "A different instance of the GraphType" errors.
If I followed the code changes correctly, the old version would just overwrite anything that name matched with the last item in.
The part that is confusing me is that I'm already storing the types that have been created - so I'm not sure what difference it's finding.

Additionally, I think there was a second layer of protection related to:
https://github.com/graphql-dotnet/graphql-dotnet/issues/474

 My older code used:
 class JsonGraphType : ScalarGraphType
 
But the suggested change was:
AnyScalarGraphType

So the "// Ignore scalars" is also skipped.

```
    private void EnsureTypeEquality(IGraphType existingType, IGraphType newType)
        {
            if (ReferenceEquals(existingType, newType))
            {
                return;
            }

            // Ignore scalars
            if (existingType is ScalarGraphType && newType is ScalarGraphType)
            {
                return;
            }

            if (existingType.GetType() != newType.GetType())
            {
                throw new InvalidOperationException($"Unable to register GraphType '{newType.GetType().GetFriendlyName()}' with the name '{newType.Name}'. The name '{newType.Name}' is already registered to '{existingType.GetType().GetFriendlyName()}'. Check your schema configuration.");
            }

            // All other types are considered "potentially wrong" when being re-registered, throw detailed exception
            throw new InvalidOperationException($"A different instance of the GraphType '{newType.GetType().GetFriendlyName()}' with the name '{newType.Name}' has already been registered within the schema. Please use the same instance for all references within the schema, or use {nameof(GraphQLTypeReference)} to reference a type instantiated elsewhere.");
        }
```

**Comment by Shane32** [comment]
Try GraphQL.NET 7.2.1 and see if there's any change.

**Comment by Shane32** [comment]
or 7.2.2

**Comment by sungam3r** [comment]
1. Of course it is possible but I don't understant the situation you want to log.
2. I think that it is a wrong way. Scalars were ignored intentionally.

**Comment by Shane32** [comment]
If you’re still on 7.2.0 or prior 7.x version, very likely you are seeing the wrong error and the true error is being masked. Using 7.2.1 or newer will show the correct error.

**Comment by OpenSpacesAndPlaces** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/3480#issuecomment-1372646801

![image](https://user-images.githubusercontent.com/30755002/210873961-8ac9a91c-4ef6-42db-b87c-2ab9aedcb8c0.png)

**Comment by OpenSpacesAndPlaces** [comment]
I'm on 7.2.2.

Rereading the code for "EnsureTypeEquality" it can't get to:
`throw new InvalidOperationException($"A different instance of the GraphType...`

If this didn't pass:
if (existingType.GetType() != newType.GetType())

--

All of the core introspection code was written years ago at this point.
Trying to wrap my head around where the hidden duplication issue is.

**Comment by sungam3r** [comment]
@OpenSpacesAndPlaces @Shane32 I think I may add some additional "trace info" into message.

**Comment by OpenSpacesAndPlaces** [comment]
Thanks! 
In the meantime I've made all the graph naming more verbose - it'll at least finishing generation the Schema:
albeit I expect to see a lot of duplicate class declaration.

**Comment by sungam3r** [comment]
@OpenSpacesAndPlaces #3488 should help to locate the problem. You can download package from here https://github.com/graphql-dotnet/graphql-dotnet/pkgs/nuget/GraphQL/62126246 before official release.

**Comment by OpenSpacesAndPlaces** [comment]
The additional detail helps!!! Thanks!!!

Can you no longer share the same object across navigation properties?
In 3.3 it overwrote the definition, and since they were all the same definition, it just worked.
Would be possible to have some sort setting for - if same name, assume same object?

Of is there different way I need to assign these now so I avoid the duplication checks?

```
System.InvalidOperationException
  HResult=0x80131509
  Message=A different instance of the GraphType 'QueryTableType<DBContext>' with the name 'MyTable_q_c_' has already been registered within the schema. Please use the same instance for all references within the schema, or use GraphQLTypeReference to reference a type instantiated elsewhere.
Existing type trace:

Loop over manually-added non-scalar types from AdditionalTypeInstances
AddTypeIfNotRegistered(IGraphType, TypeCollectionContext) for type 'Query'
Loop for fields of complex type 'Query'
Field 'Query.MyTable'
AddTypeIfNotRegistered(IGraphType, TypeCollectionContext) for type 'MyTable_q_c_'

New type trace:

Loop over manually-added non-scalar types from AdditionalTypeInstances
AddTypeIfNotRegistered(IGraphType, TypeCollectionContext) for type 'Query'
Loop for fields of complex type 'Query'
Field 'Query.MyTable'
AddTypeIfNotRegistered(IGraphType, TypeCollectionContext) for type 'MyTable_q_c_'
Loop for fields of complex type 'MyTable_q_c_'
Field 'MyTable_q_c_.MyTableOneToManySpiderIdChildNavigation'
AddTypeIfNotRegistered(IGraphType, TypeCollectionContext) for type 'MyTableOneToManySpider_q_c_'
Loop for fields of complex type 'MyTableOneToManySpider_q_c_'
Field 'MyTableOneToManySpider_q_c_.IdChildNavigation'
AddTypeIfNotRegistered(IGraphType, TypeCollectionContext) for type 'MyTable_q_c_'
  Source=GraphQL
  StackTrace:
   at GraphQL.Types.SchemaTypes.EnsureTypeEquality(IGraphType existingType, IGraphType newType, TypeCollectionContext context)
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.SchemaTypes.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter)
   at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.SchemaTypes.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter)
   at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.SchemaTypes.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter)
   at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.SchemaTypes.Initialize(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings)
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings)
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider)
   at GraphQL.Types.Schema.CreateSchemaTypes()
   at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes()
   at GraphQL.Types.Schema.Initialize()
```

**Comment by sungam3r** [comment]
> Can you no longer share the same object across navigation properties?

I don't understand 😕 .

**Comment by OpenSpacesAndPlaces** [comment]
In the previous version if I had like:

Table 0
Table 1 with Child Reference to Table 0
Table 2 with Child Reference to Table 0
Table 3 with Child Reference to Table 0

That would just work because the source was just using the last reference for everything, in this case:
Table 3 with Child Reference to Table 0

In the current version It sees the above example, and at least for my definition, says, wait hold here, that's bad.

To make it work I have change the declaration slightly to differentiate the naming, so like:
Table 1 with Child Reference to Table 0_0 
Table 2 with Child Reference to Table 0_1
Table 3 with Child Reference to Table 0_2

Even though Table 0_0, Table 0_1 and Table 0_2 are all the same model.

It's not exactly a problem - it just blows out the schema size unnecessarily and makes queries slightly less reusable.

**Comment by sungam3r** [comment]
The core part is how you build your schema. You can do it in many ways and it is hard to tell what is wrong without clear picture.

**Comment by sungam3r** [comment]
I suspect that `GraphQLTypeReference` can help you if you manually build your schema traversing database models.

**Comment by Shane32** [comment]
You can certainly use the same graph type by multiple other types.  I am in the process of updating the FAQ to answer questions such as these.  Please let me know if reading this documentation helps:

https://github.com/graphql-dotnet/graphql-dotnet/blob/update_faq/docs2/site/docs/guides/known-issues.md#multiple-instances-of-same-graph-type-error

**Comment by OpenSpacesAndPlaces** [comment]
I think I narrowed down the problem:
The tables causing the issues have self-referential navigations - e.g.

MyTable 
{
        Int ID
        String Name
        String Desc
        MyTable MyTableNavigationColumn
}

In that scenario I wouldn't have been able to cache "MyTable", because "MyTable" is still be defined. 
So when it gets to the child self-referencing column, it will of course need to define itself.

I'm not seeing good way around this without some sort of setting on the Field or ObjectGraphType that can tell the schema initializer, like, "hey, if you see this one again - it's really the same thing."

**Comment by Shane32** [comment]
It's hard to give a sample when I don't know what the goal is, but for a dynamic schema, couldn't you do something like this?

```cs
    private readonly Dictionary<string, IGraphType> _graphTypesByTableName = new();

    public IGraphType GetOrCreateGraphType(string tableName)
    {
        if (_graphTypesByTableName.TryGetValue(tableName, out var graphTypeMatched))
            return graphTypeMatched;

        // construct the graphtype and add it to the dictionary prior to adding any fields
        var graphType = new ObjectGraphType();
        _graphTypesByTableName.Add(tableName, graphType);

        // name the graph type with a unique name

        // for each column on table
        //   add field to graphType, recursively calling GetOrCreateGraphType if needed

        return graphType;
    }
```

The dictionary could be based on anything unique that you use to generate types.  Here's another way, along the same principal:

```cs
    private readonly HashSet<string> _createdGraphTypesByName = new();

    public IGraphType GenerateGraphType(string tableName)
    {
        // generate a unique graph type name for the table
        var graphTypeName = tableName + "TableType"; // or whatever

        // if it has already been constructed, return a reference
        if (!_createdGraphTypesByName.Add(graphTypeName))
            return new GraphQLTypeReference(graphTypeName);

        // construct the graphtype and return it
        var graphType = new ObjectGraphType() { Name = graphTypeName };

        // for each column on table
        //   add field to graphType, recursively calling GenerateGraphType

        return graphType;
    }
```

**Comment by OpenSpacesAndPlaces** [comment]
That's more/less what I'm already doing.

The issue is that this happening in the middle of the tree traversal for the parent - so since the parent is fully defined yet, it's not in the cache.

If I'm understanding the problem right, It's kind of chicken/egg.
The only hack I can think of is if there is a way to-do a full traversal before the initializer is called to correct it.

Or outside of that - try to pre-identify these problem cases and only create dupes for those that will be an issue.

**Comment by Shane32** [comment]
I guess what I'm saying is that if you cache the entry of the parent ** before ** traversing children, then children will realize that a parent node will exist "in the future" when traversal is complete, and can reference them ahead of time via `GraphQLTypeReference` (see second sample).  Or as shown in the first sample, via an uninitialized `IGraphType` reference (which is perfectly valid to do this way), which will be initialized by the time traversal is complete.

**Comment by sungam3r** [comment]
Consider two-phase construction. First phase creates types without fields. Second phase fills created types with fields.

**Comment by Shane32** [comment]
Right.  You don't need to have all -- or any -- of the child fields set on an `IGraphType` reference before using the same reference in other places in the schema.

**Comment by sungam3r** [comment]
@OpenSpacesAndPlaces Without any piece of **your** schema construction code it's hard to fix it.

**Comment by Shane32** [comment]
> so since the parent is fully defined yet, it's not in the cache.

Basically, the solution is to put it in the cache before defining it; then define it.

**Comment by Shane32** [comment]
Closing due to lack of information required to solve the underlying problem.
