### ISSUE TITLE
Would it be possible to sign the NuGet assembly with a strong name?

### ISSUE THREAD

**Issue by ChristianRuiz** [graphql-dotnet/graphql-dotnet#349]
I'm working on a SharePoint project were we'd like to use GraphQL. Right now I've had to download the repo and sign the dll myself. Would it be possible to sign the dll on the NuGet package?

Thanks!

**Comment by joemcbride** [comment]
I currently do not have plans to provide signed assemblies.  Hopefully you can use the same solution as #234.

**Comment by ChristianRuiz** [comment]
Hi Joe, I didn't know about StrongNamer. We try it out! Thanks!
