### ISSUE TITLE
How to build an argument type to model expressions

### ISSUE THREAD

**Issue by mariusbancila** [graphql-dotnet/graphql-dotnet#3495]
I need to find a way to build complex filters in my schema. As of now, I can do this as follows:

Ex: get the order with the specified ID:
```
{
  order(filter : {orderNo : {_eq: 1}})
  {
  }
}
```
Ex: get all orders created after Jan 1.
```
{
  order(filter : {orderDate : {_gt: 20230101}})
  {
  }
}
```

The `filter` argument allows me to pass expression used to build a filter. It also supports AND and OR operations, such as follows:

Ex: get all orders created after Jan 1 with an amount greater than 1000:
```
{
  order(filter : {_and : [
      {orderDate : {_gt: 20230101}},
      {totalAmount : {_gt: 1000}}
  ]})
  {
  }
}
```

However, in all these cases I compare fields (which are table columns) with literals (numbers, strings, etc.). However, I want to be able to build expressions where I have other fields on the right side of the expression. So not just `orderDate > 20230101` or `totalAmount > 1000` but things like `dueDate > orderDate + 30` or `paidAmount < totalAmount`.

My problem is defining the input type. Let's ignore the complex expressions on the right side for a moment. Let's just say I want to say `fieldA > fieldB`. I can't define a type to allow me to this:

```
{
  order(filter : {paidAmount : {_lt: totalAmount}})
  {
  }
}
```

I could do something like this but it's ugly:
```
{
  order(filter : {paidAmount : {_lt: {totalAmount : ???}}})
  {
  }
}
```
??? can be a number, or a boolean value or whatever.

I could also have an enumeration with the column tables and use that on the right side:
```
{
  order(filter : {paidAmount : {_lt: TOTAL_AMOUNT}})
  {
  }
}
```
But that lacks any consistency with the rest and is at least as ugly as the previous approach.

Do you have any suggestions for this problem?

**Comment by Shane32** [comment]
Maybe Antlr4 to parse language text into an expression tree which can then be compiled into SQL or whatever needed?

**Comment by mariusbancila** [comment]
I was hoping to avoid defining an ADL for this. I know I could do things like this:

```
{
  order(filter : "paidAmount < totalAmount")
  {
  }
}
```
But then this is inconsistent with the rest of the schema.

**Comment by Shane32** [comment]
I think you’ve thought about all the typical solutions to this problem. GraphQL isn’t really designed for passing expressions. Generally speaking, I’d say any solution is a hack - even your current implementation. 

I think someone considered using a directive to have the server store results from one portion of a query into a variable where it could be used in your existing implementation as a variable argument. (This isn’t really what you’re looking for I know.)

Another idea is that custom scalars can have any representation so perhaps it could be either a number or an enumeration. Again, a hack.

**Comment by sungam3r** [comment]
This is one of the features in my personal "todo wishlist". There is not enough time at all to do this. I thought this can be done with a separate functional block like `Field<MyOutType>("clients").AddFiltering().AddSorting()`, which would be connected on demand to any field in the schema. All the necessary input types representing the filter will be generated when schema is initialized so that the developer does not need to write them himself.
