### ISSUE TITLE
Guid Type "could not be derived implicitly". How to ?

### ISSUE THREAD

**Issue by mahald** [graphql-dotnet/graphql-dotnet#350]
Hi,

I'm trying to use a GUID type but i'm strugling.

I've got the Class 

```
    public class UserProfile
    {
        [Key]
        public Guid Id { get; set; }

```

However i get the error if i try to set it up with:

```
    public class UserProfileType : ObjectGraphType<db.UserProfile>
    {
        public UserProfileType()
        {
            Name = "UserProfiles";
            Field(x => x.Id).Description("Id of the UserProfile");
            Field(x => x.ParentUserProfileId).Description("Id of the ParentUserProfile");
        }
    }
```
In the Field(id) line i get a "could not be derived implicitly" error.

How can i use GUID with GraphQL ?
Maby by converting it to string in GraphQL, How ?

Wouldn't it be nice tp support it out of the box ?

**Comment by RustamIbragimov** [comment]
@mahald, did you solve the problem ?

**Comment by mahald** [comment]
Yes

It must be defined explicitly:

`Field(x => x.Id, type: typeof(IdGraphType)).Description("Id of the UserProfile");`

**Comment by joemcbride** [comment]
Similar issue as with https://github.com/graphql-dotnet/graphql-dotnet/issues/336

**Comment by brgrz** [comment]
@joemcbride 

This way also isn't supported

`Field<IdGraphType>(x => x.Id.ToString());`

Even though the Docs say int, long and string are supported for IdGraphType.

How come?

**Comment by sungam3r** [comment]
> Field<IdGraphType>(x => x.Id.ToString());
Expression should return property of x, not arbitrary code expression. 
@joemcbride  Should we add check to guard such invalid usage?

**Comment by nivle** [comment]
You need to use the GraphQL types which can be found [here](https://graphql-dotnet.github.io/docs/getting-started/schema-types/).
For Guid it would be `Field(x => x.Id, type: typeof(IdGraphType));`

**Comment by sungam3r** [comment]
> Should we add check to guard such invalid usage?

Never mind, I saw that such a check is already there.
```c#
throw new ArgumentException(
                    $"Cannot infer a Field name from the expression: '{expression.Body.ToString()}' " +
                    $"on parent GraphQL type: '{Name ?? GetType().Name}'.");
```
