### ISSUE TITLE
Note in readme about AOT

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3505]
Rel: #3461

I suggest to place dedicated section in readme about GraphQL AOT compatibility. Maybe here 
![изображение](https://user-images.githubusercontent.com/21261007/212772462-88357701-c637-4293-b273-965e19ee1083.png)

I would place a comment (among other text about AOT) here like that:
> We will try to support the AOT maximum possible. If you have a problem using any of GraphQL packages from application published with AOT-enabled features, then feel free to post an issue.

**Comment by Shane32** [comment]
Looks like I already did this.

**Comment by Shane32** [comment]
https://github.com/graphql-dotnet/graphql-dotnet#ahead-of-time-compilation
