### ISSUE TITLE
Returning Customer errors possible ?

### ISSUE THREAD

**Issue by mahald** [graphql-dotnet/graphql-dotnet#351]
Is it possible to add customer errors ?
i would expect this to be possible somehow like this:

`context.Errors.Add(new GraphQLError { Message: "darn u failed !!"})`

or

`throw new ValidationException("Darn u Failed");`

is there currently a way ? If ! then this.makeTo("Feature Request");

This is possible in other languages such as python or node.js

**Comment by Karnich** [comment]
im sitting with the exact same thing. I would expect this to be possible, but cant figure out how.

anyone? @joemcbride @moserware

**Comment by joemcbride** [comment]
@Karnich see https://github.com/graphql-dotnet/graphql-dotnet/pull/342

**Comment by joemcbride** [comment]
This is now released https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.16.1.705
