### ISSUE TITLE
Needing Projection on queries

### ISSUE THREAD

**Issue by devFarshadFahimi** [graphql-dotnet/graphql-dotnet#3515]
## Summary
I read the GraphQL.NET documentation and I didn't see any projection that I could use while executing queries, I need projection to execute exactly the query send to backend, for example if my Type Class includes 4 fields, and my query contains two of them, I need to executed query be look like this : “select field1, field2 from Entity”, but right now, it queries on all Type Class fields.
How can I achieve that ?!
## Relevant information
I'm using GraphQL.NET Version 7.2.2

**Comment by Shane32** [comment]
From experience, I can say that it is possible with much work.  Most specifically you'd be looking at the `IResolveFieldContext.SubFields` property to determine which child fields were selected.  Here are some other references:

- https://github.com/graphql-dotnet/graphql-dotnet/issues/3435
- https://github.com/graphql-dotnet/graphql-dotnet/issues/2164
- https://github.com/SimonCropp/GraphQL.EntityFramework/issues/145

**Comment by Shane32** [comment]
Please ask if you have further questions
