### ISSUE TITLE
Merge Queue feature - enable or not?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3524]
- https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

![изображение](https://user-images.githubusercontent.com/21261007/217605969-0aad58ba-9309-434d-b5b8-073eedab555e.png)

I have just got a tooltip about it on our repos and have read a bit about. It seems useless for our pace of work. I think to ignore it for now in all repos. What do you think @Shane32 ?

**Comment by Shane32** [comment]
Agree.  If it handled the situation where multiple PRs were intended to be 'stacked', one PR being built on another, that would be useful in the develop branch.  But it does not seem to do so.  Let's close for now.

**Comment by sungam3r** [comment]
> that would be useful in the develop branch

As I understand it is not about master or develop as such (breaking changes or not - does not matter), but about PR rate to automate manual work with integration someone's changes into my own PR over and over again. This should be a repository with a huge number of users/bots and a high pace of work, something like dotnet/runtime maybe.

Closing.
