### ISSUE TITLE
APQ spec compatibility

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3533]
Rel : #3134

Today I was asked the question why GraphQL.NET returns a response that does not correspond to the specifications from https://www.apollographql.com/docs/react/api/link/persisted-queries/#protocol, particularly:
```json
{
"errors":[
  {
    "message":"Persisted query with \u0027BCED85A94818E4F33733D12411A29116A2812155BAC5874CF6A3CB96B99B3C8F\u0027 hash was not found.",
    "extensions":{"code":"PERSISTED_QUERY_NOT_FOUND","codes":["PERSISTED_QUERY_NOT_FOUND"]}}
]
}
```

I was surprised and went to read the specification. I was even more surprised when I saw that:

> When the initial query signature is received by a backend, if it is unable to find the hash previously stored, it will send back the following response signature:

```json
{
  "errors": [
    { "message": "PersistedQueryNotFound" }
  ]
}
```
@Shane32 I remember very well how we added support for APQ. I absolutely do not understand how we could allow such a miss.

**Comment by Shane32** [comment]
True, although the spec is written poorly. As written, we could not include any other `extensions` to the error.  Also, the spec says that a 200 response must be returned.  While this is recommended by the GraphQL over HTTP spec for errors written with the `application/json` content type, it is not recommended for errors written with the `application/graphql-response+json` content type.  The GraphQL over HTTP spec should dictate the response code, not the APQ specification.

I would not suggest blindly following the specification to the letter in this case.  However, we should test the implementation against the Apollo client so we can be sure it works properly.  Most likely we must adjust the message property to match the specification and that will be sufficient.  I would continue to produce our `code` as we do with all other errors produced by GraphQL.NET.

I would consider changing the message description is a non-breaking change as it would be expected that GraphQL.NET users are matching on the `code` property (as the `message` property is not constant).  We should add a note in the source code that the `message` property must match the spec.

**Comment by Shane32** [comment]
I'm not even sure that Apollo is following their own spec:

https://github.com/apollographql/apollo-server/blob/main/packages/server/src/internalErrorClasses.ts

**Comment by sungam3r** [comment]
In this story, for me, the question remains why we did not immediately see that we were violating the specification.
