### ISSUE TITLE
InputObjectGraphType json cast to dictionary fails in DocumentExecuter.AssertValidValue and GraphQLExtensions.AstFromValue

### ISSUE THREAD

**Issue by mule** [graphql-dotnet/graphql-dotnet#355]
Not sure if this is related to nested InputObjectGraphTypes but the cast to dictionary in the functions mentioned fails making the input object dictionary null, So in order to fix it, instead of safe casting to dictionary with the as-operator  I have to do it like this:
`                var jsonObject = input as JObject;
                var dict = jsonObject.ToObject<Dictionary<string, object>>();`

**Comment by joemcbride** [comment]
Can you provide example input values of it failing?  Even better, a unit test for it?

**Comment by phischepi** [comment]
Hi there,

I'm facing a similar issue: when I try to pass a complexObject into the variables, it seems that the DocumentExecuter could deserialize the JSON:

**request:**
mutation TryLogin($info: LoginInput!) {
  tryLogin(login: $info)
}
**variables**
{
  "info": {
    "email": "xxxx",
    "password": "yyyy",
    "rememberme": false
  }
}

I got the following exception:
**Exception**
```
Variable '$info' is invalid. Unable to parse input as a 'LoginInput' type. Did you provide a List or Scalar value accidentally?
   at GraphQL.DocumentExecuter.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
    at GraphQL.DocumentExecuter.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
    at GraphQL.DocumentExecuter.GetVariableValue(Document document, ISchema schema, VariableDefinition variable, Object input)
    at GraphQL.DocumentExecuter.<>c__DisplayClass18_0.<GetVariableValues>b__0(VariableDefinition v)
    at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
    at GraphQL.DocumentExecuter.GetVariableValues(Document document, ISchema schema, VariableDefinitions variableDefinitions, Inputs inputs)
    at GraphQL.DocumentExecuter.BuildExecutionContext(ISchema schema, Object root, Document document, Operation operation, Inputs inputs, Object userContext, CancellationToken cancellationToken, Metrics metrics)
    at GraphQL.DocumentExecuter.<ExecuteAsync>d__7.MoveNext()
```

Here is my inputtype:
```
    public class LoginInputType : InputObjectGraphType
    {
        public LoginInputType()
        {
            Name = "LoginInput";

            Field<NonNullGraphType<StringGraphType>>("email");
            Field<NonNullGraphType<StringGraphType>>("password");
            Field<BooleanGraphType>("rememberme");
        }
    }
```
My Mutation:
```
        public MAPMutation(IApplicationUserManager manager)
        {
            Name = MutationName;
            FieldAsync<LoginResultType>(
                "tryLogin",
                arguments: new QueryArguments(new QueryArgument<LoginInputType> {Name = "login"}),
                resolve: async context =>
                {
                    var login = context.GetArgument<LoginDto>("login");
                    return await manager.SignInAsync(
                        login.Email,
                        login.Password,
                        login.RememberMe);

                }
            );
        }
```
The schema:
`            services.AddSingleton<ISchema>(sp => new Schema {Query = sp.GetService<MAPQuery>(), Mutation = sp.GetService<MAPMutation>()});`

And the action:
```
        [HttpPost]
        public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
        {
            var vars = query.Variables;

            var result = await _executer.ExecuteAsync(_ =>
            {
                _.Schema = _schema;
                _.Query = query.Query;
                _.Inputs = query.Variables != null ? new Inputs(query.Variables) : null;
            }).ConfigureAwait(false);

            if (result.Errors?.Count > 0)
                return BadRequest();

            return Ok(result);
        }
```

Sorry if I did not pack the code into a ZIP but I have quiet a lot of dependencies on 3rd parts

**Comment by phischepi** [comment]
One small, I found a workaround:
```
            var dico = new Dictionary<string, object>();
            if (query.Variables != null)
                foreach (var var in query.Variables)
                    dico.Add(var.Key, (var.Value as JObject)?.ToObject<Dictionary<string, object>>());
```
But as far as I can see, it should not work with nested objects (level 2 and more)

**Comment by joemcbride** [comment]
@phischepi at first glance I'm noticing the request is sending non-null LoginType argument and your query is not defined as such.  Can you try adding non-null to your query argument definition on the input?

**Comment by phischepi** [comment]
@joemcbride : I try both without success

**Comment by joemcbride** [comment]
Other possible issue.  I see you're not using the built-in conversion to the `Inputs` class.  That conversion converts `JObject` values to actual .NET types.  So the framework may be hanging up on that.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md#variables

So `query.Variables` should be raw JSON vs. a `Dictionary<string, object>` that contains `JObject` values.

```csharp
var inputs = variablesJson.ToInputs();

var result = await executer.ExecuteAsync(_ =>
{
    _.Inputs = inputs;
});
```

[You may also call `GetValue` manually if needed.](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L52)

**Comment by phischepi** [comment]
I try to change my model to store the variables into a simple string but the JSON formatter dont let do it so easily (I try to use the GraphQLQuery as written in the tests but then the query failed).

Just for the info, my project is running asp.net core 1.1 and this could be my issue.

**Comment by phischepi** [comment]
Another workaround, instead of having the property as "string", I set the type to JObject and when executing the query I use the following trick:
```
...            
_.Inputs = query.Variables?.ToString()?.ToInputs();
...
```

**Comment by joemcbride** [comment]
You can also pass the JObject to GetValues.  Though may need to configure the Serializer settings to match that of the ToInputs method.

**Comment by phischepi** [comment]
Thank you for the hint, for those interested, here is my final try:
```
...
var inputs = StringExtensions.GetValue(query.Variables) as Dictionary<string, object>;
...
```
where "Variables" is a JObject

**Comment by joemcbride** [comment]
Going to go ahead and close this, re-open if needed.  Thanks!
