### ISSUE TITLE
Return -out option into CI

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3555]
I would like to revert changes from  #3536 and #3554 once MS fixes SDK. I like the version with -out option more. It's simpler. In addition, I copy these scripts to other repositories from time to time when I need to add СI, so I would like to avoid the differences that appear.

**Comment by Shane32** [comment]
I agree completely

**Comment by sungam3r** [comment]
👍 

I gradually return to normal after the hospital, but so far I can not work at PC in full force. While I have to work without my glasses and with frequent breaks. I see that I have quite a few new letters, gradually I will look at them. Most likely, tomorrow.

**Comment by sungam3r** [comment]
fixed by #3558 and #3588
