### ISSUE TITLE
Doubled package

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3556]
https://github.com/orgs/graphql-dotnet/packages?repo_name=graphql-dotnet

![изображение](https://user-images.githubusercontent.com/21261007/221644420-70499c83-e34d-4d7c-a53c-1f26d05a2085.png)

WTF?

Also I see GraphQL.SystemReactive in the list. Keep or remove?

**Comment by Shane32** [comment]
I dunno. They are dev packages. It doesn’t matter much except for the latest versions. It’s not like anyone can use them without a bunch of pain anyway.

**Comment by sungam3r** [comment]
I deleted GraphQL.SystemReactive package.

Also I posted a request into GitHub Packages support.

**Comment by sungam3r** [comment]
Amswer from support team:
> Looks like there was some issue with our indexing. We have fixed and verified it. Could you check again and confirm whether or not it's working?

It's fixed now.
