### ISSUE TITLE
Line number along with error message for errors present in gql schema

### ISSUE THREAD

**Issue by ansulgoenka1** [graphql-dotnet/graphql-dotnet#3559]
## Summary

Brief explanation of the feature.

Returning line number along with the error message returned by Document Executor for errors present in GQL schema

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

If there is an error in the schema, the error currently looks like this: "Error executing document. The field 'user' of an Object type 'Query' must be an output type"

Expecting an output with line number included in this error message

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

Currently, it is very difficult for users to pinpoint the error in the schema, considering that the schema is really huge. It will be very helpful for someone to debug the error if the DocumentExecutor returns the line number along with the error message.

**Comment by Shane32** [comment]
The error you provided has no bearing on the query.  The query could be entirely valid.  The error is a schema initialization error, and it says exactly what is wrong.  The `user` field of type `Query` has been improperly configured with an input object graph type.  Until that is fixed, no queries can be executed, regardless of whether they use the `user` field or not.

**Comment by Shane32** [comment]
In my code, I often add `schema.Initialize()` or equivalent somewhere in the startup of my application.  Then it is easier to debug schema initialization errors before any requests are made.  For example:

```cs
// initialize the schema (assumes you have a singleton schema)
app.Services.GetRequiredService<ISchema>().Initialize();
```

**Comment by sungam3r** [comment]
Closed as answered and due to inactivity.
