### ISSUE TITLE
Is there a BuildSchema function in Graphql-dotnet? 

### ISSUE THREAD

**Issue by clementpeihengtan** [graphql-dotnet/graphql-dotnet#356]
Hi, I am new to graphql-dotnet. I have some questions about the feature in graphql-donet but not sure is this the right place to ask them. Let me know if this is the wrong place. 

Is there a function like buildschema in graphql-js where you just pass a string of graphql schema into it? Right now, I have a graphql schema but not sure how to import this schema into my project. Do i need to create whole new class for each of the type or is there an easier way to do it?

**Comment by joemcbride** [comment]
There is not, though it is a feature I'm very interested in having.  See #317
