### ISSUE TITLE
GraphQL.Execution.ObjectExecutionNode Error

### ISSUE THREAD

**Issue by ishakdemir** [graphql-dotnet/graphql-dotnet#3564]
Data is not coming with result.data.
"Self referencing loop detected for property 'Parent' with type 'GraphQL.Execution.ObjectExecutionNode'. Path 'SubFields[0].SubFields[0]" gives this error, how can I solve it.

Code
```
 private readonly IDocumentExecuter _documentExecuter;
private ISchema _schema { get; set; }

 public GridSettingsController(ISchema schema,
            IDocumentExecuter documentExecuter)
        {
            _schema = schema;
            _documentExecuter = documentExecuter;
}

public async Task<IActionResult> Query([FromBody] GraphQLQuery query){
 var executionOptions = new ExecutionOptions { Schema = _schema, Query = query.Query };

            var result = await _documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);
            return Ok(result.Data);
}
```

```
FieldAsync<PaginationListType<ErFieldsType, ErFieldDataRequest>>(
                "test",
                arguments: new QueryArguments(
                    new QueryArgument<IntGraphType> { Name = "pageSize", Description = "Number of elements to display in one page" },
                    new QueryArgument<IntGraphType> { Name = "pageNumber", Description = "Page number" },
                    new QueryArgument<StringGraphType> { Name = "tableName", Description = "Table name" },
                    new QueryArgument<ProductFilterType> { Name = "filter", Description = "filter values" }
                ),
                resolve: async context =>
                {
                    var pageSize = context.GetArgument<int>("pageSize", DefaultPageSize);
                    var pageNumber = context.GetArgument<int>("pageNumber", 1);
                    var tableName = context.GetArgument<string>("tableName");
                    var filter = context.GetArgument<ProductFilter>("filter");
                    if (filter == null)
                    {
                        filter = new ProductFilter();
                    }
                    var data = await _erFields.GetAll(tableName, pageSize, pageNumber, filter);

                    return data;
                }
            )
```
Output
```
"errors": [
        {
            "statusCode": 500,
            "code": null,
            "message": "Self referencing loop detected for property 'Parent' with type 'GraphQL.Execution.ObjectExecutionNode'. Path 'SubFields[0].SubFields[0]'."
        }
    ],
```

**Comment by sungam3r** [comment]
I've already seen such issues before. The reason is `Ok(result.Data);`. You should use special serialization code to properly serialize results. See https://graphql-dotnet.github.io/docs/guides/serialization#serialization-of-a-graphql-response

**Comment by ishakdemir** [comment]
> I've already seen such issues before. The reason is `Ok(result.Data);`. You should use special serialization code to properly serialize results. See https://graphql-dotnet.github.io/docs/guides/serialization#serialization-of-a-graphql-response

There is no IDocumentWriter in GraphQl version 7.2.0.

**Comment by sungam3r** [comment]
https://graphql-dotnet.github.io/docs/migrations/migration5#17-code-classlanguage-textidocumentwritercode-has-been-renamed-to-code-classlanguage-textigraphqlserializercode-and-related-changes

**Comment by Shane32** [comment]
You’ll need a reference to either the GraphQL.SystemTextJson (preferred) or the GraphQL.NewtonsoftJson NuGet package.

**Comment by Shane32** [comment]
If you wish, you can use the GraphQLExecutionActionResult or ExecutionResultActionResult classes provided with the server nuget package. See various sample implementations here:

https://github.com/graphql-dotnet/server/blob/master/samples/Samples.Controller/Controllers/HomeController.cs

**Comment by Shane32** [comment]
https://github.com/graphql-dotnet/server#configuration-with-a-mvc-controller

**Comment by sungam3r** [comment]
Closed as answered.
