### ISSUE TITLE
Interfaces Implementing Interfaces

### ISSUE THREAD

**Issue by KvaKoZyaBBrr** [graphql-dotnet/graphql-dotnet#3565]
Im trying to implement interface by interface but cant do that because IInterfaceGraphType haven`t AddResolvedInterface method. But spec by October 2021had https://spec.graphql.org/draft/#sec-Interfaces.Interfaces-Implementing-Interfaces. How can I implementing interfaces by interface?

**Comment by Shane32** [comment]
This feature was added in the 2021 spec and has not yet been added to GraphQL.NET.  Are you interested in writing a PR to add this functionality?

**Comment by KvaKoZyaBBrr** [comment]
Oh. Im tried to write  myself fix by override, but have not lot of time for it. And I thought what it help me use less of fields in types, but this is not possible. If this functional wil be in new patch I think schema will be so logical because now I use temporary interface which dublicate existing type. Whatever in https://github.com/graphql-dotnet/graphql-dotnet#schema-introspection is used spec 2021 and I thought Im wrong use library when this functionality was is not work. 
Generally I think this PR may be so usefull and also maybe PR for Interface Extensions (https://spec.graphql.org/June2018/#sec-Interface-Extensions)
