### ISSUE TITLE
Date format is changed when I use GraphQLSerializer

### ISSUE THREAD

**Issue by shinjiDev** [graphql-dotnet/graphql-dotnet#3566]
## Summary
Hi GraphQL Dotnet team,
I'm using GraphQL.NET in my project, trying to work with some specific date time formats and I'm getting the expected result in ExecutionResults class:
![image](https://user-images.githubusercontent.com/236560/226094454-e9b4949b-430d-4786-adee-69bddc9f86fc.png)
The problem is that when I use GraphQLSerializer class (and Serialize method)
`new GraphQLSerializer(indent: true).Serialize(executionResults);`
it changes my string values (that represents date time formats) to this:

```json
{
  "data": {
    "allStrings": {
      "items": [
        {
          "id": 1,
          "dateColumn": "12/05/2022 00:00:00",
          "dateTimeOffsetColumn": "07/14/2022 00:00:00",
          "dateTime2Column": "10/05/2010 00:00:00",
          "timeColumn": "13:30:00",
          "dateTimeColumn": "01/21/2023 00:00:00"
        }
      ]
    }
  }
}
```

Is there any way to avoid that format change? 
Any help or support is appreciated.

**Comment by Shane32** [comment]
Are you using code-first?  Can you provide the constructor of the 'item' type?

**Comment by shinjiDev** [comment]
Hi @Shane32, 
No, It's not code first. I'm loading schema from GQL schema file.
The execution is done using Resolvers. The items array is a json array build only with strings.
I would like to know how to avoid the change of those strings that represent a date field.

**Comment by Shane32** [comment]
then can you provide the schema-first definition of the item type?

**Comment by Shane32** [comment]
Generally, the scalars control the serialization of native .NET types to serialized strings.  For example, the `DateTimeGraphType` has this code:

```cs
    public override object? Serialize(object? value) => value switch
    {
        // ISO-8601 format
        // Note that the "O" format is similar but always prints the fractional parts
        // of the second, which is not required by ISO-8601.
        DateTime d => d.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK", DateTimeFormatInfo.InvariantInfo), // ISO-8601 format (without unnecessary decimal places, allowed by ISO-8601)
        null => null,
        _ => ThrowSerializationError(value)
    };
```

Notice that if you were to attempt to return a string from the resolver, it would throw an exception and not return anything.

You need to replace the date/time scalars with custom scalars which has your own serialization code within it.

**Comment by Shane32** [comment]
I do not understand why a GraphQLSerializer instance would return dates in the format you said it is doing at all, unless the scalar is not a GraphQL.NET date/time scalar.  So, there is no easy answer here, but if you can provide additional information, I may be able to help.

**Comment by shinjiDev** [comment]
Schema:
```
type StringTable {
  id: Int!
  dateColumn: String!
  dateTimeOffsetColumn: String!
  dateTime2Column: String!
  smallDateTimeColumn: String!
  dateTimeColumn: String!
  timeColumn: String!
  charColumn: String!
  varCharColumn: String!
  textColumn: String!
  nCharColumn: String!
  nTextColumn: String!
  uniqueIdentifierColumn: String!
}

type StringQueryResult {
  items: [StringTable]  
}

type Query {
  allStrings: StringQueryResult
}
```

Piece of code:
           ```
var userContext = this.ConstructResolverContext(context, resolvers, logEntry, memoryLimiter, outgoingRequestCache);
            userContext.Add(SyntheticGraphQLConstants.DictionaryKeys.RequestQuery, query);

            var executor = new DocumentExecuter();
            ExecutionResult executionResults = default;
            try
            {
                executionResults = await executor.ExecuteAsync(_ =>
                {
                    _.Schema = apiSchema.Schema;
                    _.Query = query;
                    _.UserContext = userContext;
                    _.Variables = inputs;
                    _.CancellationToken = cancellation;
                });
            }
            catch (Exception ex)
            {
                this.HandleProcessingError(context, SyntheticGraphQLConstants.Errors.Reasons.EmptyRequestBody, ex.Message);
                return;
            }
            finally
            {
                this.DisposeUserContext(userContext);
            }
            var result = new GraphQLSerializer(indent: true).Serialize(executionResults);
```

Screen capture of executionResults:

![image](https://user-images.githubusercontent.com/236560/226129637-9ec323f3-c68a-4fba-9208-60bd1d3dd505.png)


About your message:
> I do not understand why a GraphQLSerializer instance would return dates in the format you said it is doing at all, unless the scalar is not a GraphQL.NET date/time scalar. So, there is no easy answer here, but if you can provide additional information, I may be able to help.

My main idea is that the executionResults has a Json result with full strings (with id exception) and keep that format.

**Comment by Shane32** [comment]
Are you using the system.text.json serializer or the Newtonsoft serializer ?

**Comment by Shane32** [comment]
Perhaps you could list the installed GraphQL packages you are using and their versions.

**Comment by Shane32** [comment]
While looking at your screen capture, I was puzzled by the data you show there.  What value were you inspecting?  `(ExecutionResult.Data as RootExecutionNode).Result` should be `null` unless you provide a value to `ExecutionOptions.Root`, which you are not.

**Comment by Shane32** [comment]
`ExecutionResult.Data` in version 7 does not contain a 'JSON' result -- meaning, it does not contain a value that can be serialized directly by a ignorant serializer.  Rather, it is an `RootExecutionNode` instance which may contain nested `ExecutionNode` instances stored in a proprietary manner based on the specific type (e.g. `ObjectExecutionNode`, `ArrayExecutionNode` or `ValueExecutionNode`).  These instances are created and used during the execution phase.  To convert `ExecutionResult.Data` to a dictionary, you may call `((RootExecutionNode)result.Data).ToValue()`.  This should be essentially the same as the data node within the JSON result when using the `GraphQLSerializer`.  However, the `GraphQLSerializer` serializes the `ExecutionNode` instances directly to the JSON writer to save allocations.

**Comment by Shane32** [comment]
Note that the value of `ExecutionNode.Result` is not typically used once the execution finishes, as it only represents the value of the objects passed to field resolvers during execution.  Only for `ValueExecutionNode` instances does it hold a value that will be serialized.  But for `ObjectExecutionNode` and other types, the value is meaningless once execution has finished.

I suspect that the problem lies in the resolvers' execution, not in the serialization of the result.

**Comment by shinjiDev** [comment]
> Are you using the system.text.json serializer or the Newtonsoft serializer ?
System.Text.Json in our case.

> While looking at your screen capture, I was puzzled by the data you show there. What value were you inspecting? `((RootExecutionNode)ExecutionResult.Data).Result` should be `null` unless you provide a value to `ExecutionOptions.Root`, which you are not.
The value inspected is this one: ((GraphQL.Execution.ObjectExecutionNode)executionResults.Data).SubFields[0].Result
![image](https://user-images.githubusercontent.com/236560/226195512-689fac67-d109-45b2-999b-6d2703054e78.png)


> Note that the value of `ExecutionNode.Result` is not typically used once the execution finishes, as it only represents the value of the objects passed to field resolvers during execution. Only for `ValueExecutionNode` instances does it hold a value that will be serialized. But for `ObjectExecutionNode` and other types, the value is meaningless once execution has finished.
> 
> I suspect that the problem lies in the resolvers' execution, not in the serialization of the result.

My resolver execution only does something like this in each field:
rowJson[name] = dateTimeOffsetColumn.ToString("yyyy-MM-ddTHH:mm:ss.fffK");


> `ExecutionResult.Data` in version 7 does not contain a 'JSON' result -- meaning, it does not contain a value that can be serialized directly by an ignorant serializer. Rather, it is an `RootExecutionNode` instance which may contain nested `ExecutionNode` instances stored in a proprietary manner based on the specific type (e.g. `ObjectExecutionNode`, `ArrayExecutionNode` or `ValueExecutionNode`). These instances are created and used during the execution phase. To convert `ExecutionResult.Data` to a dictionary, you may call `((RootExecutionNode)result.Data).ToValue()`. This should be essentially the same as the data node within the JSON result when using the `GraphQLSerializer`. However, the `GraphQLSerializer` serializes the `ExecutionNode` instances directly to the JSON writer to save allocations.

Yes, that's why I would like to know the way to modify JSON writer behavior, because my ((GraphQL.Execution.ObjectExecutionNode)executionResults.Data).SubFields[0].Result is:
```
{{
  "items": [
    {
      "id": 1,
      "dateColumn": "2022-12-05T00:00:00",
      "dateTimeOffsetColumn": "2022-07-14T00:00:00-05:00",
      "dateTime2Column": "2010-10-05T00:00:00",
      "smallDateTimeColumn": "2022-01-18T00:00:00",
      "dateTimeColumn": "2023-01-21T00:00:00",
      "timeColumn": "13:30:00",
      "charColumn": "C         ",
      "varCharColumn": "VarCharValue",
      "textColumn": "TextValue",
      "nCharColumn": "N         ",
      "nVarCharColumn": "NVarcharValue",
      "nTextColumn": "NTextValue",
      "uniqueIdentifierColumn": "3caefe78-f3f5-4753-8c81-0d23bea3a5d3"
    }
  ]
}}
```

But after running GraphQLSerializer, my ExecutionResult look like this (I'm taking only 6 fields) :
```
{{
  "data": {
    "allStrings": {
      "items": [
        {
          "id": 1,
          "dateColumn": "12/05/2022 00:00:00",
          "dateTimeOffsetColumn": "07/14/2022 00:00:00",
          "dateTime2Column": "10/05/2010 00:00:00",
          "timeColumn": "13:30:00",
          "dateTimeColumn": "01/21/2023 00:00:00"
        }
      ]
    }
  }
}}
```

I mean, I want to avoid this conversion:
`"dateTimeOffsetColumn": "2022-07-14T00:00:00-05:00" -> "dateTimeOffsetColumn": "07/14/2022 00:00:00"`


> Perhaps you could list the installed GraphQL packages you are using and their versions.
```
         <PackageReference Include="GraphQL" Version="5.4.0" />
	<PackageReference Include="GraphQL.NewtonsoftJson" Version="5.4.0" />
	<PackageReference Include="GraphQL.SystemReactive" Version="4.8.0" />
	<PackageReference Include="GraphQL.SystemTextJson" Version="5.4.0" />
	<PackageReference Include="Microsoft.Azure.ApiManagement.Infra.Redis" Version="13.0.2" />
	<PackageReference Include="Microsoft.Azure.ApiManagement.Management.Contracts.Policies" Version="7.42.0" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.0" />
	<PackageReference Include="Newtonsoft.Json.Schema" Version="3.0.14" />
```

**Comment by Shane32** [comment]
FYI, GraphQL.SystemReactive is not compatible with or necessary for GraphQL.NET v5 as its functionality has been moved into the main library. Please remove the dependency. You may add a reference to System.Reactive if your library requires it, as it is no longer needed for GraphQL. You may also remove the GraphQL.NewtonsoftJson reference if you are using the System.Text.Json serializer. 

Please read:
- https://graphql-dotnet.github.io/docs/migrations/migration5#19-subscription-support-improved

However, these changes will not solve your issue.

**Comment by Shane32** [comment]
Please use the inspection tool to dig a bit deeper and find the ValueExecutionNode for “dateColumn” and provide a screen shot of the ValueExecutionNode object including the Result property.

**Comment by shinjiDev** [comment]
Let me try to see if I understood:
![image](https://user-images.githubusercontent.com/236560/226205726-bafb1741-6153-442b-bdc0-96ad9a1e4f71.png)
![image](https://user-images.githubusercontent.com/236560/226205991-c0199f98-751e-4ee2-a418-acb46db4e8c0.png)

I appreciate you support @Shane32

**Comment by Shane32** [comment]
no, like `SubFields[0].Items[0].SubFields[0].SubFields[0]`

**Comment by Shane32** [comment]
not sure exactly, but probably follow either `SubFields` or `Items` as deep as you can

**Comment by shinjiDev** [comment]
Got it:
![image](https://user-images.githubusercontent.com/236560/226206639-9bd72177-ac0d-4071-a637-33f34a77998c.png)

![image](https://user-images.githubusercontent.com/236560/226206581-1fa2ab14-5a1d-4295-8447-561587320e5a.png)

**Comment by Shane32** [comment]
Now see in the first photo, the Result field of the ValueExecutionNode is the incorrectly formatted date. So we can be sure that the problem is in the field resolver, not the serializer.

**Comment by Shane32** [comment]
(Since this is captured before the serializer is invoked)

**Comment by Shane32** [comment]
We need to review your field resolvers’ code.

**Comment by Shane32** [comment]
Please ask if you have further questions
