### ISSUE TITLE
Backward resolving

### ISSUE THREAD

**Issue by Molochnikov** [graphql-dotnet/graphql-dotnet#3567]
Hello!

In JS DOM Object event flow we have events that have forward and backward propagation. Can i do the same in resolving sequence?

The problem is that i cannot say to parent node "don't return your value if you child nodes are empty and some parameter is set". Because of that i need to repeat filter logic of inner resolvers in outer resolvers and to find reuse algorithm for this resolvers. It is a big problem when i have many filters that overburdens outer resolvers.

For example i want to replace this code:

```
query (
  $orgs: [String!]!,
  $orgCertifications: [String!]!
  $specs: [String!]!
) {
  employees(
    organizationsfilterByName: $orgs,
    specializationsfilterByName: $specs,
    organizationCertificationsfilterByName: $orgCertifications,
  ) {
    name
    organizations(filterByName: $orgs) {
      name
      certification(filterByName: $orgCertifications) {
        claimed
      }
    }
    specialization(filterByName: $specs) {
      name
    }
  }
}
```

...by that code:

```
query {
  employees {
    name
    organizations(stopBackPropagationIfEmpty, filterByName: $orgs) {
      name
      certification(stopBackPropagationIfEmpty, filterByName: $certs) {
        claimed
      }
    }
    specialization(stopBackPropagationIfEmpty, filterByName: $specs)   {
      name
    }
  }
}
```

...and not return any employees with empty organizations, with empty certifications or with empty specializations. I'm using DataLoader in all child types resolvers.

How i can do that?

**Comment by Shane32** [comment]
There may be simpler or cleaner ways to perform what you're looking for also.  For instance, GraphQL.NET does back-propagate nulls for non-nullable fields; this is triggered in the `ExecutionStrategy` after execution is complete.  Perhaps you could copy/rewrite the `PropagateNull` code to do something similar, perhaps based on a directive attached to the field in the request.  Directives are global and so easier to match on rather than field arguments.  This might be a much cleaner solution, but may require you to change your schema.

Example:

```gql
query {
  employees @removeNulls {
    name
    organizations(filterByName: $orgs) @asNonNull @requireChildren {
      name
      certification(filterByName: $certs) @asNonNull @requireChildren {
        claimed
      }
    }
    specialization(filterByName: $specs) @asNonNull @requireChildren   {
      name
    }
  }
}
```

In this example `@removeNulls` instructs your custom code to remove any child elements that are null, and `@asNonNull` instructs it to back-propagate a null if the value is null (without an error), and `@requireChildren` returns null if the child list is empty

If this works for you, it has a benefit of being able to be applied anywhere with no special code added to your field resolvers.  It will still be complicated to add, I expect.  Also the field definitions will all need to be nullable, or else you'll have to deal with removing the errors from the error list that is returned.

**Comment by Molochnikov** [comment]
Do i need to check `@requireChildren` directive in a new `RemoveNullsDirectiveVisitor : BaseSchemaNodeVisitor` class and use `FuncFieldResolver` instead of `AsyncFieldResolver` in [directives documentation example](https://graphql-dotnet.github.io/docs/getting-started/directives/#how-do-directives-work)? How i can check for an empty `ArrayExecutionNode` after wrapped original filed resolver returns a value?

**Comment by Shane32** [comment]
`AsyncFieldResolver` was rolled into `FuncFieldResolver` in v5.

See https://graphql-dotnet.github.io/docs/migrations/migration5#36-asynchronous-field-resolver-classes-have-been-removed

Sorry if our directives documentation is out of date.  ☹

**Comment by Shane32** [comment]
So to recap, I'd write a method based somewhat on the PropagateNull code, which recursively traverses the `ExecutionResult.Data` property (which is either `null` or a `RootExecutionNode` instance), looking at the `Field` property to find the AST node and checking for directives applied to the `GraphQLField` instance.  If it finds `@removeNulls` or `@asNonNull` or `@requireChildren` it will act accordingly.

**Comment by Molochnikov** [comment]
How i can add [ExecutionResultJsonConverter.cs](https://github.com/graphql-dotnet/graphql-dotnet/blob/ab42978894faccb4dd38bed9fdb3c5447e337fc4/src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs#L68) for my new `NullArrayExcecutionNode `with custom PropagateNull code?

**Comment by Molochnikov** [comment]
I thought i need to create my own `NullExecutionStrategy `and override `BuildExecutionNode `method to the new `ArrayExecutionNode `with custom `PropagateNull`

**Comment by Shane32** [comment]
Don’t replace it. Just add a document listener to run your code after propagatenull is done. I’m not at a PC now but I’ll check in an hour that this is feasible

**Comment by Shane32** [comment]
```cs
using GraphQL.DI;
using GraphQL.Types;

namespace GraphQL.Execution;

// to use:
//   .ConfigureExecution<BackwardResolvingHandler>();
internal class BackwardResolvingHandler : IConfigureExecution
{
    public float SortOrder => GraphQLBuilderExtensions.SORT_ORDER_CONFIGURATION;

    public async Task<ExecutionResult> ExecuteAsync(ExecutionOptions options, ExecutionDelegate next)
    {
        var ret = await next(options).ConfigureAwait(false);
        if (ret.Data is RootExecutionNode rootNode)
            PropagateNull(rootNode);
        return ret;
    }

    private bool PropagateNull(ExecutionNode node)
    {
        if (node is ArrayExecutionNode arrayNode)
        {
            // when @removeNulls is set, loop through arrayNode.Items and remove null entries
            if (HasDirective(arrayNode, "removeNulls"))
            {
                arrayNode.Items?.RemoveAll(PropagateNull);
            }
            // when @removeNulls is not set, do standard null propagation
            else if (arrayNode.Items != null)
            {
                var isNullableType = false;

                foreach (var item in arrayNode.Items)
                {
                    bool valueIsNull = item.PropagateNull();

                    if (valueIsNull && !isNullableType)
                    {
                        if (((ListGraphType)arrayNode.GraphType!).ResolvedType is NonNullGraphType)
                        {
                            arrayNode.Items = null;
                            break;
                        }
                        else
                        {
                            isNullableType = true;
                        }
                    }
                }
            }
            // when @requireChildren is set, set node to null if arrayNode.Items is empty
            if (HasDirective(arrayNode, "requireChildren"))
            {
                if (arrayNode.Items?.Count == 0)
                {
                    arrayNode.Items = null;
                }
            }
            // return true if node is null
            return arrayNode.Items == null;
        }
        else if (node is ObjectExecutionNode objectNode)
        {
            if (objectNode.SubFields == null)
                return true;

            foreach (var child in objectNode.SubFields)
            {
                bool valueIsNull = child.PropagateNull();

                if (valueIsNull && IsNonNull(child))
                {
                    objectNode.SubFields = null;
                    return true;
                }
            }

            return false;
        }
        else
        {
            return node.ToValue() == null;
        }
    }

    private bool IsNonNull(ExecutionNode node)
    {
        if (HasDirective(node, "asNonNull"))
            return true;
        if (node.FieldDefinition?.ResolvedType is NonNullGraphType)
            return true;
        return false;
    }
    
    private bool HasDirective(ExecutionNode node, string directiveName)
        => node.Field?.Directives?.Any(d => d.Name == directiveName) ?? false;
}
```

untested, but this is the general concept I think

**Comment by Molochnikov** [comment]
Thank you! There must be `PropagateNull(child)` not `child.PropagateNull()`.

**Comment by Shane32** [comment]
Yes, and also `bool valueIsNull = item.PropagateNull();` should be `bool valueIsNull = PropagateNull(item);`

**Comment by Shane32** [comment]
I updated my snippet above
