### ISSUE TITLE
Mutation without response

### ISSUE THREAD

**Issue by RustamIbragimov** [graphql-dotnet/graphql-dotnet#357]
How can I create a mutation which does not return anything?
I have a mutation `deleteRole`. I tried to create it this way

> FieldAsync<ObjectGraphType>(
>                 "deleteRole",
>                 arguments: new QueryArguments(new QueryArgument<IntGraphType> {Name = "id"}),
>                 resolve: async ctx =>
>                 {
>                     var id = ctx.GetArgument<int>("id");
>                     await _requestMaker.DeleteRoleAsync(id);
>                     return new { };
>                 }
>             );

But in GraphiQL I get lots of js errors.  And also, how can I execute this mutation?

**Comment by joemcbride** [comment]
All mutations have to return a value. That is part of the GraphQL spec.  Take a look at the mutations section at http://graphql.org/learn/queries/ for how to execute a mutation.  Essentially, just change the "query" keyword to "mutation" and set your root mutation object on your Schema.
