### ISSUE TITLE
Directive for Input fields

### ISSUE THREAD

**Issue by KvaKoZyaBBrr** [graphql-dotnet/graphql-dotnet#3570]
How can I mark input field as deprecated? If we have old not optimised filters by field and I add new filter field but I wanna mark old field as obsolete/deprecated. 

input FilterOperationSet {
  oldFilter: Boolean <-- this must be delete in future
  newFilter: Boolean
}
I trying use deprecated but @deprecated(reason: String = "No longer supported") on FIELD_DEFINITION | ENUM_VALUE and INPUT_FIELD_DEFINITION not supported.
Then I trying use custom directive with INPUT_FIELD_DEFINITION, but in schema I haven`t mark:
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L306
public string PrintInputValue(FieldType field)
{
    Schema?.Initialize();
    var argumentType = field.ResolvedType!;
    var description = $"{FormatDescription(field.Description, "  ")}  {field.Name}: {argumentType}";
    if (field.DefaultValue != null)
    {
        description += " = {0}".ToFormat(FormatDefaultValue(field.DefaultValue, argumentType));
    }
    return description;
}

**Comment by Shane32** [comment]
What versions of GraphQL nuget packages do you have?

code first or schema first?

**Comment by KvaKoZyaBBrr** [comment]
nuget packages 7.2.2
code first

**Comment by sungam3r** [comment]
See #1112. I myself want have such feature. Our team members required it.

**Comment by sungam3r** [comment]
WOW! It was merged on Dec 3, 2020

links to read https://github.com/graphql/graphql-spec/pull/525#issuecomment-653163051 and https://github.com/graphql/graphql-spec/pull/525#issuecomment-685934302 and especially https://github.com/graphql/graphql-spec/pull/525#issuecomment-830397550

And https://github.com/graphql/graphql-spec/pull/805 was merged on Jun 3, 2022 !

@KvaKoZyaBBrr @Shane32 I think we can go on implementing this one. I want to try in myself. Give me a couple of days.

**Comment by sungam3r** [comment]
In master
![изображение](https://user-images.githubusercontent.com/21261007/229514295-2bf049d0-a690-410b-9487-dd831836056b.png)

**Comment by sungam3r** [comment]
I mean it's in the working draft
![изображение](https://user-images.githubusercontent.com/21261007/229515279-007516f7-ec6e-47d3-977e-bbef976295e1.png)
and it literally means an invitation for implementations to work on this feature.

**Comment by sungam3r** [comment]
@Shane32 I would like to go on with the same approach we did with `RepeatableDirectives` placing this as property in `ExperimentalFeatures`.

**Comment by Shane32** [comment]
How does implementing this conflict with the current spec?

**Comment by sungam3r** [comment]
The same way as for `RepeatableDirectives` - by allowing user to enable it manually.

**Comment by Shane32** [comment]
Assuming it's already in the draft spec, I would not add it as an experimental feature.  It is a mainstream feature that has already made it through the entire approval process and has been merged into the spec.  There is a slim-to-none chance that it will be modified again before the entire draft spec is released as a new version.  Chances are that it's already in the reference implementation too.

The existing 'experimental features' are ones that the GraphQL community has not agreed upon an implementation for, but we as GraphQL.NET feel are need for reasonable support of the ecosystem.  This does not fall into that category.

**Comment by Shane32** [comment]
If you like, you could add an xml comment to the property that notes that the feature is currently in the draft spec and may change.

**Comment by KvaKoZyaBBrr** [comment]
Anyway we use stable version of library and this update our platform for this feature take several days. I think this improvement does not will be append in last release of our soft. I just read issue in spec and this project and does not understood which status of this problem. So I think if this feature will be able in future we will update to next version but now is not high priority

**Comment by KvaKoZyaBBrr** [comment]
We will append draft text to description, I think

**Comment by sungam3r** [comment]
> Assuming it's already in the draft spec, I would not add it as an experimental feature. It is a mainstream feature that has already made it through the entire approval process and has been merged into the spec.

Nope. As usual - there are problems with tooling and other. I have read all discussions in the provided links.

> The existing 'experimental features' are ones that the GraphQL community has not agreed upon

Nope. `RepeatableDirectives` feature is not our invention.

> Also in this case, I'm guessing that this feature is 100% backwards compatible. Meaning, if you don't mark an input type as deprecated, it won't show up on introspection requests. Hence there is no need to 'turn it on' or 'turn it off'. Correct?

Unfortunately, no. It may be breaking so GraphQL WG even decided to require validation rule on schema initialization.

> If you like, you could add an xml comment to the property that notes that the feature is currently in the draft spec and may change.

Yep, we wrote so for `RepeatableDirectives`.

**Comment by Shane32** [comment]
Please explain how adding this feature WITHOUT putting a flag within `ExperimentalFeatures`, and WITHOUT marking any input types as obsolete would cause a problem with existing tooling.

**Comment by Shane32** [comment]
> > The existing 'experimental features' are ones that the GraphQL community has not agreed upon
>
> Nope. RepeatableDirectives feature is not our invention.

Ok but I was referring to `AppliedDirectives`

**Comment by Shane32** [comment]
If `RepeatableDirectives` and/or other new features are going to break introspection queries, it is likely that some users will want to maintain compatibility with older versions regardless of what is the newest release.  Perhaps we should add a property to the schema called something like `CompatibilityLevel`, which could be set to `June2018`, `October2021`, `WorkingDraft` and `Experimental`.

**Comment by Shane32** [comment]
> Please explain how adding this feature WITHOUT putting a flag within `ExperimentalFeatures`, and WITHOUT marking any input types as obsolete would cause a problem with existing tooling.

I'm looking at the required changes and they do seem to be potentially breaking to tools

**Comment by sungam3r** [comment]
> Please explain how adding this feature WITHOUT putting a flag within ExperimentalFeatures, and WITHOUT marking any input types as obsolete would cause a problem with existing tooling.

Just so that the changes in the introspection do not break tooling (Playground, etc), I arrange all the changes under the ExperimentalFeatures's new flag. Or I do not understand question.

**Comment by Shane32** [comment]
Ok

**Comment by sungam3r** [comment]
Will be published in v7.4

**Comment by KvaKoZyaBBrr** [comment]
Thank you for answer and operative feature

**Comment by sungam3r** [comment]
Just to clarify - v7.4 may be published today or the next month. I do not know.
