### ISSUE TITLE
SchemaPrinter should print isDeprecated/deprecationReason for args and input fields

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3573]
See https://github.com/graphql-dotnet/graphql-dotnet/pull/3571

**Comment by Shane32** [comment]
Possibly fixed by #3649

**Comment by Shane32** [comment]
`SchemaPrinter` is now deprecated in v8 and `SchemaExporter` exports deprecated fields and arguments with the `@deprecated` directive.
