### ISSUE TITLE
Using Simple Injector Fails in second level after root

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#358]
In Root Query Simple Injector is working fine.

But inside a type when I try to inject a Service on the constructor GraphiQL fails throwing a Unexpected JSON output.

What could be the solution for this?

```
public class RootQuery {
    public RootQuery(Service1 service) {
          Field<InnerType>()
            .Name(/*...*/
            .Resolve(x => service.GET()) <--- Working Fine
    }
}

public class InnerType : /* ... etc ... */ {
   public InnerType(Service2 service) { <---- When I inject whatever service this fails at running time
     Field(x => x.Id);
   }
}
```
If I remove Service2 and I don't use it, the output schema works fine.
Am I missing something? 
Should register a Schema like this as a must?

`            container.Singleton(new StarWarsSchema(type => (GraphType) container.Get(type)));
`

**Comment by joemcbride** [comment]
Yes, if you are using any sort of dependency injection then something like `container.Singleton(new StarWarsSchema(type => (GraphType) container.Get(type)));` is required.  That gives the `Schema` class a func that it can use to resolve types in your DI container.

The `SimpleContainer` class is just that - very simple, and I would not be surprised if you ran into bugs or issues with it.  I would not suggest to use it for any sort of production application.  I would suggest to use a different container such as [StructureMap](http://structuremap.github.io/).

That being said, the `SimpleContainer` expects every type to be registered with the container, [such as in the example](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Bootstrapper.cs).  Have you registered both your `InnerType` and the `Service2` with the container?

**Comment by Jonatthu** [comment]
When I try 
`type => (GraphType) container.Get(type))`
From
`container.Singleton(new StarWarsSchema(type => (GraphType) container.Get(type)));`
I got a precompile issue saying can not convert from System.Type to MyNamespace.GraphType

**Comment by joemcbride** [comment]
That should be calling [this method on the `Schema` class](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Schema.cs#L48) and [this method on the `SimpleContainer` class](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.StarWars/IoC/SimpleContainer.cs#L61).  Does your `Schema` class have a different constructor that takes different arguments?

**Comment by Jonatthu** [comment]
@joemcbride 
It looks like this 

```
        public StarWarsSchema(Func<Type, GraphType> resolveType)
            : base(resolveType)
        {
            Query = (StarWarsQuery)resolveType(typeof (StarWarsQuery));
        }
```

and my registration

'container.Register(new FooSchema(type => (GraphType)container.GetInstance(type)));'

and `container.GetInstance(type)` is returning a `object`  type.

**Comment by joemcbride** [comment]
That looks fine to me then.  I can't say why you're getting a compile error.

**Comment by Jonatthu** [comment]
It was `container.Register(() =>new StarWarsSchema(type => (GraphType)container.GetInstance(type)));`
@joemcbride  thanks!

**Comment by joemcbride** [comment]
Ah, yes the example shows registering the `Schema` as a Singleton vs. an instance.  You only ever need a single instance of your schema.  `container.Singleton(...)`

**Comment by Jonatthu** [comment]
```
            container.Register<TyNETRootQuery, TyNETRootQuery>(Lifestyle.Scoped);

            var typeAssambly = typeof(GraphQL.Types.UserType).GetTypeInfo().Assembly;
            var typeRegistrations = typeAssambly.GetExportedTypes()
                .Where(x => x.Namespace == "TyNET.Api.GraphQL.Types" && x.GetTypeInfo().IsClass);

            foreach (var reg in typeRegistrations)
            {
                container.Register(reg, reg, Lifestyle.Scoped);
            }

            container.Register(() => new TyNETSchema(type => (GraphType)container.GetInstance(type)), Lifestyle.Scoped);
```

As you see the implementation is Scoped should I change all these to Singleton?

**Comment by joemcbride** [comment]
Yes, should be Singletons.

**Comment by Jonatthu** [comment]
What about scoped ? Because when I side singleton it says that my schema is implementing dispose :/

**Comment by joemcbride** [comment]
That's because it DOES implement `IDisposable`.  It cleans up types it used when it is disposed.  As stated above it is suggested you register all of your graph types and schema as singletons.

**Comment by Jonatthu** [comment]
@joemcbride Should my services being call inside this schema and types be Singletons as well?
