### ISSUE TITLE
[BOUNTY] Setup up-to-date Node.JS

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3584]
**This issue participates in bounty program, see https://github.com/graphql-dotnet/graphql-dotnet/blob/master/BOUNTY.md**

**bounty amount: $100**

The goal is to have up-to-date Node.JS environment to build documentation.

Tasks to be done:
1) Setup LTS Node.JS (https://github.com/nodejs/release#release-schedule) in CI workflows.
2) Update all needed packages in package.json. The exact amount of work is unknown.
3) Make other needed changed in /docs2 folder.

Expected result - `test-documentation.yml` worflow ended successfully.

See releated issues: https://github.com/graphql-dotnet/graphql-dotnet/pull/2687 and https://github.com/graphql-dotnet/graphql-dotnet/pull/2827

**Comment by Shane32** [comment]
I'm assigning this bounty to you @ThakurKarthik  under the terms of the bounty program.  Thanks for your assistance!

**Comment by Shane32** [comment]
@ThakurKarthik Thanks for helping to fix this issue.  Please submit an expense to the OpenCollective for the bounty amount of $100 here: https://opencollective.com/graphql-net/expenses/new

**Comment by sungam3r** [comment]
@ThakurKarthik Also I would ask you about feedback regarding bounty program. What would you like to note? How did you know about it? How do you estimate the size of the bounty and the scope of work? How do you evaluate the program conditions? Was everything clear in them? Your feedback can help us to improve bounty program.

**Comment by Shane32** [comment]
@sungam3r I'm removing the 'in progress' label and leaving both 'bounty' and 'bounty-paid'.  It will not show up as an active bounty since the issue has been closed.

**Comment by Shane32** [comment]
Actually our guidelines say to remove 'bounty' so i'll do that

**Comment by sungam3r** [comment]
OK. I'm happy to see that bounty program works. Some time later I'll suggest more issues to include in the program.
