### ISSUE TITLE
Nullable reference types best practice for nullable field

### ISSUE THREAD

**Issue by julienFlexsoft** [graphql-dotnet/graphql-dotnet#3586]
I use the GraphQL package 7.2.2.
I have recently enable nullable refernce types in my GraphQL project and I was wondering how I could handle this snippet:

```csharp
Field<Project, ProjectViewModel?>("Project")
    .ResolveAsync(ctx =>
    {
        if (ctx.Source.ProjectId > 0)
        {
            var loader = accessor.Context!.GetOrAddBatchLoader<int, ProjectViewModel>
            ("projectDataStore", x => projectDataStore.GetItem(x, ctx));
            return loader.LoadAsync((int)ctx.Source.ProjectId);
        }
        return null;
    });
```
So, here my type has a field "Project" that can be null. The type "Project" doesn't have the "nonnull" tags around it and the viewModel has the "?" at the end. The issue is that I get the warning on the first line:
```
Warning CS8620: Argument of type 'FieldBuilder<ActivityViewModel, ProjectViewModel?>' cannot be used for parameter 'builder' of
type 'FieldBuilder<ActivityViewModel, ProjectViewModel>' in 'FieldBuilder<ActivityViewModel, ProjectViewModel>
DataLoaderExtensions.ResolveAsync<ActivityViewModel, ProjectViewModel>(FieldBuilder<ActivityViewModel, ProjectViewModel>
builder, Func<IResolveFieldContext<ActivityViewModel>, IDataLoaderResult<ProjectViewModel>> resolve)' due to
differences in the nullability of reference types.
```
and this warning on the `return null;` line:
`Possible null reference return`
I don't understand why, the ViewModel has a "?" at the end. It looks like ot only looks at what the dataloader returns.

Honestly, this all works fine, the dataloader is skipped if the projectId is null, and when it's not, the ProjectViewModel is returned. 

The datastore GetItem in case this helps (it creates a new scope for parallel execution):
```
public async Task<IDictionary<int, TViewModel>> GetItem(IEnumerable<int> ids, IResolveFieldContext ctx)
{
    using var scope = ctx.RequestServices!.CreateRequestScope();
    var resource = scope.ServiceProvider.GetRequiredService<TResource>();

    var result = await _mapper.Value.ProjectTo<TViewModel>(resource.GetQueryable()
        .Where(x => ids.Contains(x.Id)))
        .ToListAsync();

    return result.ToDictionary(x => x.Id);
}
```

I already tried changing the whole datastore to simply return `TViewModel?`, but then it creates warnings for when the viewModel is not nullable. If I go that route I should make two methods: one "GetIOtem" and one "GetNullableItem". Before i go there I'd like to know what you guys think.

**Comment by Shane32** [comment]
I'm guessing it's because you're returning `IDataLoaderResult<ProjectViewModel>` or `null`, so the definition is `IDataLoaderResult<ProjectViewModel>?` not `IDataLoaderResult<ProjectViewModel?>`.

This is fine for GraphQL.NET, as you can see.  However, the extension method we have for data loaders probably is not typed the way you are using it.

You can probably patch it with this:

```cs
Field<Project, ProjectViewModel>("Project")
    .ResolveAsync(ctx =>
    {
        if (ctx.Source.ProjectId > 0)
        {
            var loader = accessor.Context!.GetOrAddBatchLoader<int, ProjectViewModel>
            ("projectDataStore", x => projectDataStore.GetItem(x, ctx));
            return loader.LoadAsync((int)ctx.Source.ProjectId);
        }
        return null!;
    });
```

Or maybe this:

```cs
Field<Project, ProjectViewModel?>("Project")
    .ResolveAsync(ctx =>
    {
        if (ctx.Source.ProjectId > 0)
        {
            var loader = accessor.Context!.GetOrAddBatchLoader<int, ProjectViewModel?>
            ("projectDataStore", x => (ProjectViewModel?)projectDataStore.GetItem(x, ctx));
            return loader.LoadAsync((int)ctx.Source.ProjectId);
        }
        return null!;
    });
```

Or maybe this:

```cs
// define a static null response
var nullResponse = new DataLoaderResult<ProjectViewModel?>(Task.FromResult((ProjectViewModel?)null));

Field<Project, ProjectViewModel?>("Project")
    .ResolveAsync(ctx =>
    {
        if (ctx.Source.ProjectId > 0)
        {
            var loader = accessor.Context!.GetOrAddBatchLoader<int, ProjectViewModel?>
            ("projectDataStore", x => (ProjectViewModel?)projectDataStore.GetItem(x, ctx)); // is cast necessary here?
            return loader.LoadAsync((int)ctx.Source.ProjectId);
        }
        return nullResponse;
    });
```

Or maybe write a new `ResolveAsync` extension method for your needs.

**Comment by Shane32** [comment]
Unfortunately `Task<T>` is not `Task<out T>` (it is not covariant) which means that `IDataLoaderResult` isn't covariant either.  Not much we can do about that.  So I think that means that widening conversions will not automatically take place when returning values.

**Comment by Shane32** [comment]
Closing as answered
