### ISSUE TITLE
Directive on input object fields

### ISSUE THREAD

**Issue by mariusbancila** [graphql-dotnet/graphql-dotnet#3595]
I am trying to define a directive that I can put on input value fields. I need this because for some fields users may not need to provide a value, but tell the system to automatically assigned it to a "next" or "expected" value.

So I am thing to something like this:
```
voucher_create(value:{
  batchNo : 42
  voucherNo : 0 @suggest
  date : "2023-04-20"
  amount : 100
})
{
  # ...
}
```

The catch is that assigning values for these fields must be done in the order given by the user. That's why, in my example, `voucherNo` must come second with no value specified by the user. I know I could do something like this:

```
voucher_create(value:{
  batchNo : 42
  date : "2023-04-20"
  amount : 100
}, suggest: {
  voucherNo : 0
})
{
  # ...
}
```
But then I wouldn't know what is the right order of the `voucherNo` assignment.

So I defined a directive as follows:
```
internal class SuggestDirective : Directive
{
   public SuggestDirective() :
        base("suggest", DirectiveLocation.Field)
   {
      Description = "Suggest value for a field.";
   }
}
```
And I can see it available in GraphiQL for input fields, but when I execute the query in the first snippet, I get the following error message:
```
{
  "errors": [
    {
      "message": "Error parsing query: Expected Name, found @; for more information see http://spec.graphql.org/October2021/#ObjectField",
```

Is there any way I can achieve this?

**Comment by sungam3r** [comment]
What version of GraphQL packages for you use?

**Comment by sungam3r** [comment]
Also field! = object field. You may use wrong location.

**Comment by sungam3r** [comment]
The error you provided is from parser. I think you use old version of parser that does not support directives on object fields.

**Comment by sungam3r** [comment]
Nope, it's even simpler - GraphQL does not support specifying directives on ObjectField. Just follow the link from error message.

**Comment by mariusbancila** [comment]
Yes, I've checked the link and have seen this:

```
ExecutableDirectiveLocation : one of
   QUERY
   MUTATION
   SUBSCRIPTION
   FIELD
   FRAGMENT_DEFINITION
   FRAGMENT_SPREAD
   INLINE_FRAGMENT
   VARIABLE_DEFINITION
```

```
TypeSystemDirectiveLocation : one of
   SCHEMA
   SCALAR
   OBJECT
   FIELD_DEFINITION
   ARGUMENT_DEFINITION
   INTERFACE
   UNION
   ENUM
   ENUM_VALUE
   INPUT_OBJECT
   INPUT_FIELD_DEFINITION
```

But I was hoping that maybe `FIELD` included input objects.

**Comment by mariusbancila** [comment]
I was thinking of using an argument like:
```
voucher_create(value:{
  batchNo : 42
  voucherNo(suggest: true) : 0
  date : "2023-04-20"
  amount : 100
})
{
  # ...
}
```
But that's not possible either. Input types cannot have arguments on fields.

Is there any alternative for this? The requirements are that:

- The schema must be backwards compatible (so existing queries should not be affected)
- Some category of fields (numeric) in most input types must be able to have their value automatically set

**Comment by mariusbancila** [comment]
But I don't see how this can help me. I don't have a default value. I need to tell the backend to figure out the value.

**Comment by Shane32** [comment]
Can you just use a placeholder value to indicate the server should figure out the value, like -1 ?

**Comment by sungam3r** [comment]
> I need to tell the backend to figure out the value

I think that such use cases are not supposed to be handled by GraphQL design. Surely you can come up with some workarounds, but they all most likely will look bad.

**Comment by Shane32** [comment]
_suggest could be an array and so you need not have _suggest1, _suggest2, etc

**Comment by Shane32** [comment]
If you want to go against spec you can fork the parser project and modify it to allow directives for input object fields. But this doesn’t help when the values are passed in via variables, which is probably why they are not allowed by the spec.

**Comment by mariusbancila** [comment]
> 

I don't what that. That's the point. I need suggest fields mixed with fields for which a value is provided. Like this:
```
voucher_create(value:{
  batchNo : 42
  _suggest1: { voucherNo : null }
  amount : 100
  _suggest2: { date : null }
})
{
  # ...
}
```

**Comment by Shane32** [comment]
Right; just saying, you can make `_suggest` an array like this:
```gql
voucher_create(value: {
  batchNo: 42
  amount: 100,
  _suggestions: [
    { voucherNo : null },
    { date : null }
  ]
})
{
  # ...
}
```

**Comment by Shane32** [comment]
you could design it like this also; just depends on your needs:

```gql
voucher_create(value: {
  batchNo: 42
  amount: 100,
  _suggestions: [
    { field: VOUCHERNO },
    { field: DATE, min: "2023-04-01", max: "2023-04-30" }
  ]
})
{
  # ...
}
```

**Comment by mariusbancila** [comment]
I decided to use `null` to indicate "suggest" and for those fields that support an interval (they are few) have an extra field like `suggest_customerNo` to provide the range.

Thank you for the help.
