### ISSUE TITLE
Error after upgrading to parser v9

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3597]
![изображение](https://user-images.githubusercontent.com/21261007/233671903-41c7584d-c41c-4647-bf74-4f45666f492f.png)

Oops

**Comment by sungam3r** [comment]
I need the latest parser in my project that uses GraphQL v7. And apparently program failes.

**Comment by sungam3r** [comment]
Funny fact - error message I see is
```
System.InvalidOperationException: 'The default value of Input Object type field 'BundleHeadDtoInput.periodicity' is invalid.'
```
because of that
![изображение](https://user-images.githubusercontent.com/21261007/233673087-63098a28-4729-40c8-a0a1-0d635197c660.png)

**Comment by sungam3r** [comment]
At least there are tro options:
1. Bump to v9 and release v8
2. Bring back default ctors for AST nodes from internal to public.

**Comment by sungam3r** [comment]
See #3598 to see all problem places.

**Comment by Shane32** [comment]
We are not ready to release GraphQL v8

**Comment by Shane32** [comment]
Oh sorry I remember.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/parser/pull/316

**Comment by sungam3r** [comment]
I'll add new ctors in v8.3

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/pull/3599
