### ISSUE TITLE
Roslyn analyzer + automatic code fixes

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/graphql-dotnet#3623]
A few areas in this library usage could be improved using static code analysis to catch incorrect usages and provide automatic code fixes. Some examples:
-  When a type implements an interface, the static code analyzer can verify all fields from the interface are implemented and have the correct type. The automatic code fix can add missing fields with empty resolvers and suggest changing the field type on base or derived graph type in case of a mismatch
```c#
public class PersonGraphType : InterfaceGraphType
{
    public PersonGraphType()
    {
        Field<StringGraphType>("FirstName");
        Field<StringGraphType>("LastName");
        Field<IntGraphType>("Age");
    }
}

public class WorkerGraphType : ObjectGraphType<Worker>
{
    public WorkerGraphType()
    {
        Interface<PersonGraphType>();

        Field<StringGraphType>("FirstName").Resolve(x => x.Source.FirstName);
        // missing "LastName" field
        Field<IdGraphType>("Age");  // wrong type. Should be IntGraphType
    }
}
```

- The resolver of the field returns an incompatible type. For example, returning `int` for `ListGraphType<T>` field
```c#
//incompatible type, suggest changing return type to IntGraphType
Field<ListGraphType<IntGraphType>>("Numbers").Resolve(x => 5);
```

A few deprecations were made in the latest versions that are great candidates for automatic code fixes. For example:
- [A bunch of FieldXXX APIs were deprecated](https://graphql-dotnet.github.io/docs/migrations/migration7/#11-a-bunch-of-fieldxxx-apis-were-deprecated) can be fixed automatically (and this is the main reason I started thinking about Roslyn code fixes)
```c#
// GraphQL 5.x
Field<NonNullGraphType<StringGraphType>>(
  "name",
  "Argument name",
  resolve: context => context.Source!.Name);

// GraphQL 7.x
Field<NonNullGraphType<StringGraphType>>("name")
  .Description("Argument name")
  .Resolve(context => context.Source!.Name);
```
- The `Field<T>()` method without arguments was deprecated and can be fixed automatically
```c#
Field<StringGraphType>().Name("FirstName");

Field<StringGraphType>("FirstName");
```
- #3574. With Roslyn analyzer, the runtime error can be detected and automatically fixed in compile time.

I can think of more examples like missing `Resolve` method or returning `Task<T>` from the sync `Resolve` method.

**Comment by sungam3r** [comment]
Yes, it can be helpful. Would you like to post PR?

**Comment by gao-artur** [comment]
I'm not experienced with Roslyn API. Wanted to post the issue here in case someone can implement it. I hope to start playing with Roslyn in the near future. If no one will do that until than, I'll try to provide the PR.

**Comment by gao-artur** [comment]
@sungam3r I started working on this rule
```c#
Field<T>().Name("xxx") ==> Field<T>("xxx")
```
I'm wondering, if the parameterless `Field<>()` method was deprecated and always requires `name` argument, why the `Name(name)` method wasn't deprecated? It allows overriding the name provided in `Field<>(name)` that may be unexpected.

**Comment by gao-artur** [comment]
Hi @Shane32! I finally got my hands on this issue again. I'm now working on rewriting `Field` methods that return `FieldType` with those that return `FieldBuilder`. For example:
```c#
Field<StringGraphType>(
    "name",
    "description",
    resolve: context => "text");
```
Will become
```c#
Field<StringGraphType>("name")
    .Description("description")
    .Resolve(context => "text");
```

 A couple of questions:
How do I rewrite the non-generic `Field` and `FieldSubscribe` methods?
```c#
Field(
    typeof(string),
    "name",
    resolve: context => "text");
```
Should I use `AddFiled`?
```c#
AddField(new FieldType
{
    Type = typeof(string),
    Name = "name",
    Resolver = new FuncFieldResolver<TSourceType, object>(context => "text")
});
```
How do I rewrite the `FieldDelegate`? I never used it and not sure I understand its use case.

**Comment by Shane32** [comment]
Non-generic Field/FieldSubscribe:
```cs
Field("name", typeof(string))
    .Resolve(context => "test");  // or ResolveStream for FieldSubscribe
```

FieldDelegate:
```cs
Field<StringGraphType>("test")
    .ResolveDelegate(TestMethod);

//later:
public string TestMethod(IResolveFieldContext context)
    => "test";
```

Basically, FieldDelegate provides similar functionality to how the `AutoRegisteringObjectGraphType` functions, except it does not define the return type or arguments (but can use them if they are defined).  It does support `[Scoped]` and `[FromServices]` and stuff that affects the resolver's execution.

**Comment by gao-artur** [comment]
Ok. Should be easier than I thought then. Will try it tomorrow. Thanks!
