### ISSUE TITLE
Proposal: Better compatibility with OpenTelemetry AutoInstrumentation

### ISSUE THREAD

**Issue by RassK** [graphql-dotnet/graphql-dotnet#3626]
## Summary

[OpenTelemetry AutoInstrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/) has issues supporting libs with custom bootstrapping, external libs, etc.
I'm researching currently if it's possible for library authors to address some feedback for better compatibility.

### Basic example

There are 2 ways to make automatic instrumentation easier for us to implement:

#### Activity creation ON by default (Preferred)
A library should always try to create activities by default. If there is no listener, no activities are created (this is `System.Diagnostics.DiagnosticSource` behaviour).
Major examples: ASP.NET Core, HttpClient

#### Activity creation ON by calling initializer

In any case if library authors do not want to create activities by default (overhead caused by architecture, etc), it is the backup behaviour how AutoInstrumentation can still easily wire up activity creation. 

A library should contain specialized type for bootstrapping Auto Instrumentation:

```csharp
namespace OpenTelemetry.AutoInstrumentation;

internal class Initializer
{
    public static void EnableAutoInstrumentation(InstrumentationOptions options)
    {
         // Library owner implements bootstrapping
    }
}
```

### Motivation

This proposal is opened for feedback to research generic / easy patterns how to enable automatic instrumentation for libraries.

**Comment by Shane32** [comment]
We discussed at some great length within these links whether the instrumentation should be opt-in or on-by-default:
- https://github.com/graphql-dotnet/graphql-dotnet/issues/3448
- https://github.com/graphql-dotnet/graphql-dotnet/pull/3467

We did not discuss using the specialized type for bootstrapping auto instrumentation.  That idea has merit, but in order to allow customization of the logged events, breaking changes are likely required to GraphQL.NET.  This is because the configuration classes need to be DI-injected to the DocumentExecuter rather than using the existing builder approach. 
 So it is likely that we would need to consider such changes for v8.

**Comment by RassK** [comment]
@Shane32 thanks for the info!

`.UseTelemetry()` actually does work very well with [OpenTelemetry SDK](https://github.com/open-telemetry/opentelemetry-dotnet) (manual instrumentation). Unfortunately in OpenTelemetry AutoInstrumentation, we do not have access to user code, so we either modify IL or use reflection to bootstrap instrumentation. That being said, the biggest worry for us is to call `.UseTelemetry()` twice - eg when user code does it and then decides later to opt into less effortless instrumentation (the automatic way).  Since this information lives in a DI container, that makes the check very complicated.

**Comment by Shane32** [comment]
> That being said, the biggest worry for us is to call `.UseTelemetry()` twice

See:
- #3628 

If merged, it would not matter.

FYI, note that `.UseTelemetry()` is only available when GraphQL.NET is compiled for .NET 5 or later.  This is because a NuGet dependency on `System.Diagnostics.DiagnosticSource` would be necessary for prior .NET versions.

**Comment by RassK** [comment]
That should simplify it also quite a bit. 

We will still need to IL tap to `AddGraphQL()` and grab and extend `Action<IGraphQLBuilder>? configure`. I'll check if we can do it. 

If possible, something like this could also simplify it further for us. I think it should not introduce breaking changes - at least we would not be interested in it. 

```csharp
public static IServiceCollection AddGraphQL(this IServiceCollection services, Action<IGraphQLBuilder>? configure)
{
    if(OpenTelemetry.AutoInstrumentation.IsEnabled)
    {
        Action<IGraphQLBuilder> telemetry = b => b.UseTelemetry(OpenTelemetry.AutoInstrumentation.Options /* Pass or map options here */);
        configure += telemetry;
    }

    _ = new GraphQLBuilder(services, configure);
    return services;
}
```


> FYI, note that .UseTelemetry() is only available when GraphQL.NET is compiled for .NET 5 or later. This is because a NuGet dependency on System.Diagnostics.DiagnosticSource would be necessary for prior .NET versions.

Yes, we are aware. Currently only supported version is `2.*.*` via IL hooking. IL hooking takes a lot of manual effort, so I guess if we get in pair with OpenTelemetry SDK, it will be great.

**Comment by RassK** [comment]
> Can you confirm that the initializer will run prior to user code (i.e. before the call to AddGraphQL)? 

Yes, all our hooks are before `AddGraphQL()`: runtime native profiler injecting a managed loader -> `StartupHook` -> `IHostingStartup`. 

> Can you provide the definition of InstrumentationOptions or a link to the relevant spec that we should be meeting? Keeping in mind of course that we cannot add third-party dependencies.

`GraphQL.Telemetry.GraphQLTelemetryOptions` should be already implemented by the spec. As I see it already contains the reference link to the spec, auto instrumentation does not have separate spec but it might contain a few extra environment variables to configure options. Generally there is no other way to pass values, only environment variables. In the future there will be a OTel configuration file. NET Fx can also read `web.config`.

Usually auto instrumentation initializes options, passes it to (vendor) plugins for optional post-processing and then passes the instance to the instrumentation.

> Also, if you already have IL-tapped to the `BuildServiceProvider` call, this may be easier:
> 
> ```cs
> services.TryAddEnumerable(new ServiceDescriptor(typeof(IConfigureExecution), typeof(GraphQLTelemetryProvider), ServiceLifetime.Singleton));
> services.TryAddSingleton<GraphQLTelemetryOptions>();
> ```
> 
> Normally `GraphQLTelemetryOptions` gets mapped to `IOptions<GraphQLTelemetryOptions>` but so long as this runs after any other DI registrations, it should be fine.

I think this should also work well with `IHostingStartup` as far as it stays pretty much constant.

**Comment by Shane32** [comment]
@RassK would these changes be correct?
- #3631

**Comment by RassK** [comment]
> @RassK would these changes be correct?
> 
> * [Support OpenTelemetry auto instrumentation #3631](https://github.com/graphql-dotnet/graphql-dotnet/pull/3631)

Yes, I managed to build the another side of it and it works great!

**Comment by Shane32** [comment]
@RassK Are there any outstanding issues here or shall I close this issue?

**Comment by RassK** [comment]
@Shane32 yes, can be closed. I think it's done and seems good for now!
