### ISSUE TITLE
what is the actual request body?

### ISSUE THREAD

**Issue by jerry-sileon** [graphql-dotnet/graphql-dotnet#3635]
When building a request using the GraphQLRequest, is there a way to see what is actually sent to the GraphQL server?

**Comment by Shane32** [comment]
Is this for the [GraphQL.Client](https://www.nuget.org/packages/GraphQL.Client) nuget package?  If so, I can transfer it to the correct repo here: https://github.com/graphql-dotnet/graphql-client

**Comment by Shane32** [comment]
Closing due to lack of input.
