### ISSUE TITLE
How to flatten response?

### ISSUE THREAD

**Issue by jerry-sileon** [graphql-dotnet/graphql-dotnet#3636]
Hi all, I hope someone is out there willing to help a GraphQL.net noob...

We get this response (done in Insomnia, I could not find a way to ask GrapQL.net to log the real request and the real response):
```json
{
  "data": {
    "someOptions": {
      "someThings": [
        {
          "thing": {
            "productId": "N0FBOUYwNDctNjBGOS00MUU5LUI2MDAtNkE2RDZCMUM5N0Y0OkNSRURJVFBST0RVQ1Q6MUMxMkZCNUQtOTVBMC00QTU5LTg2NzctNUQ2OUZCNTFENjEx",
            "product": {
              "name": "Product 1"
            },
            "numberOfElements": 3
          },
          "location": "MWMxMmZiNWQtOTVhMC00YTU5LTg2NzctNWQ2OWZiNTFkNjEx"
        },
        {
          "thing": {
            "productId": "N0FBOUYwNDctNjBGOS00MUU5LUI2MDAtNkE2RDZCMUM5N0Y0OkNSRURJVFBST0RVQ1Q6NDAwMEQxQzMtRUI3NC00NDE0LTg2MjktQzc3N0JENzM0QUNC",
            "product": {
              "name": "Product 2"
            },
            "numberOfElements": 6
          },
          "location": "NDAwMGQxYzMtZWI3NC00NDE0LTg2MjktYzc3N2JkNzM0YWNi"
        },
```

To read this using the built-in deserializers I need a lot of nested classes making it quite unreadable. I prefer to have a little more control and make it more readable. So I was trying to turn that GraphQL response into a class structure that would serialize to this:

```json
someOptions: {
  someThings: [
    thing: {
      productId: "...",
      productName: "...",
      numberOfElements: ...,
      location: "..."
    }
```

How can I do that with GraphQL.net? All examples I could find that have something to do with this are making things longer and harder to read. I cannot believe there is a simpler way, like letting me parse the response myself.

Thanks!

**Comment by Shane32** [comment]
Are you referring to the [GraphQL.Client](https://www.nuget.org/packages/GraphQL.Client) library ?

**Comment by Shane32** [comment]
FYI, I do not use the GraphQL.Client library, but wrote my own implementation.  It is quite simple; the implementation is probably is only about 250 lines of code.  One of its features is to take a 'path' property and then look through successful results and deserialize only the path requested.  (similar to T-SQL [JSON path expressions](https://learn.microsoft.com/en-us/sql/relational-databases/json/json-path-expressions-sql-server?view=sql-server-ver16)) In the example you provided, the path would be `"someOptions.someThings"` and then you'd deserialize to `Thing[]` (e.g. `GraphQLClient.RequestAsync<Thing[]>(...)`) and there is no need to make all the unnecessary wrapper classes, although you still need a definition for `Thing`.  So it just gives you the data you really want and throws an exception if any errors occur.

This is the method definition:

```cs
public Task<TResponse> RequestAsync<TResponse>(string query, string? operationName, object? variables, string? path, CancellationToken cancellationToken)
```

At this time I cannot share the code; you'd have to write your own implementation.

I am not sure if there are similar features within [GraphQL.Client](https://www.nuget.org/packages/GraphQL.Client); @rose-a could answer better than I.  If not, chances are that you could write some type of extension method for GraphQL.Client to add such a feature.

**Comment by Shane32** [comment]
Please indicate if you need further assistance.
