### ISSUE TITLE
Adding Execution Errors from inside Field Resolve

### ISSUE THREAD

**Issue by drobertson123** [graphql-dotnet/graphql-dotnet#366]
I am using graphql-dotnet to interface with a data system that uses a Query Object style data request. You create the data request object, set the parameters for the specific request and send it through a ProcessRequest method. This then returns the request that is filled with the data you asked for.

So far this is fairly straightforward. The Request object also contains a property that is an Errors collection. This contains any errors encountered while servicing the data request. Errors don't mean the entire request is bad, just that there were specific issues dealing with parts of the Request. Note - these are not raised as exceptions, it is just a collection of error objects.

I would like to be able to add these errors to the ExecutionErrors of the ExecutionResult from inside Resolve on the Query since that is the closest point to receiving the Errors. I had originally (mistakenly) thought that adding the Errors to the context.Errors collection would allow them to bubble up with the returned info.

Question: Is there a way to add these Errors to the ExecutionResult from inside Resolve similar to this;

```
public class ItemListQuery : ObjectGraphType
    {
        publicItemListQuery()
        {
            Name = "getItemList";
            Description = "Retrieves a list of all Items in specified location and returns errors for bad items.";
            FieldAsync<ListGraphType<OutputItemType>>
                (
                    "items",
                    arguments: new QueryArguments(new QueryArgument<NonNullGraphType<LocationEnum>> { Name = "location", Description = "The location of the items." }),
                    resolve: async context =>
                   {

                       ItemLocations location = (ItemLocations)context.GetArgument<ItemLocations?>("location");
                       ItemsConnector connector = new ItemConnector();
                       ItemOperation req = connector.GetItemsListRequest(location);
                       req = await connector.ProcessRequest(req) as ItemOperation;

                       if (req.Errors.Any())
                       {
                           context.Errors = context.Errors ?? new ExecutionErrors();
                           List<ExecutionError> errors = req.Errors.Select(x => new ExecutionError(x.ToResponseMsg())).ToList();
                           context.Errors.AddRange(errors);
                       }

                       List<OutputItem> items = req.Select(x => new OutputItem(x, location)).ToList();

                       return items;
                   }
                );
        }
    }
```

Also, should a good data response that has a few errors in it be sent back as an OK(response) or a Bad(response). What is the effective difference between the two? I want the receiver to treat the data as good even if it does have a few errors in it.

Thanks for the great system.

**Comment by joemcbride** [comment]
Definitely the intent of https://github.com/graphql-dotnet/graphql-dotnet/pull/342 was so that the errors would bubble. If they're not then we're missing some proper integration tests.  Looking back at that PR that could be the case.

As per status code, I'm not sure if there is specific guidelines in the spec for that or not, as the spec is transport agnostic.  Can take a look at the JS project to see what they do.

**Comment by drobertson123** [comment]
Thanks Joe,

Is there anything I can do to test this further and help dig into the problem. It makes sense to me that the errors should bubble up, but as far as I can tell they are getting lost someplace.

From my perspective, it looks like the context object is somehow getting lost or disconnected. Anything I add to it inside the Resolve is gone once the Resolve finishes.

I will do some more testing and see if that is the case.

**Comment by drobertson123** [comment]
Before you waste much time, it looks like the context object is working and errors are bubbling up. I am not sure what the difference is, but this is a different outcome from what I was seeing earlier. I think I was testing against the Nuget package earlier and now I am working with the latest code directly.

I am looking at a slightly different problem related to this.  It seems like if there are any errors at all in the results from the DocumentExecutor then no data is sent with the request.

```
{
  "data": null,
  "errors": [
    {
      "message": "Operation Error: test"
    }
  ]
}
```
 vs no errors

```
{
  "data": {
    "files": [
      {
        "fileName": "2017_June.zip",
        "size": 551923895,
        "location": "FTP",
        "fileType": "Monthly",
        "fileDate": "2017-06-01T00:00:00Z"
      },
      {
        "fileName": "items_20170505.zip",
        "size": 25948808,
        "location": "FTP",
        "fileType": "Compressed",
        "fileDate": "2017-05-05T00:00:00Z"
      },
      {
        "fileName": "items_20170508.zip",
        "size": 25250319,
        "location": "FTP",
        "fileType": "Compressed",
        "fileDate": "2017-05-08T00:00:00Z"
      }
    ]
  }
}
```
In both cases the only difference is if there is an Error in the ExecutionResult.Errors collection. In both cases the result object contained the same data and both cases the response was being sent as an Ok(result).

`return Ok(result);`

Based on my reading of the GraphQL spec this doesn't seem to be the correct outcome for a request that contains errors.

[7.2.2Errors](http://facebook.github.io/graphql/#sec-Errors)

This is a bit different from my original Issue. I would be happy to have this issue closed and I can create a new issue focused on the response problem if that would help keep things organized.

**Comment by joemcbride** [comment]
Thanks for the investigation - this is probably the culprit: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionResultJsonConverter.cs#L32

Can just keep this issue and perhaps rename the title.

**Comment by drobertson123** [comment]
It looks like that is the problem. Based on my reading of the GraphQL spec errors section I think that the document should return data even if there are errors. A small change to writeData in the ExecutionResultJsonConverter could fix that.

```
        private void writeData(ExecutionResult result, JsonWriter writer, JsonSerializer serializer)
        {
            var data = result.Data;

            if (result.Errors?.Count > 0 && data == null)
            {
                return;
            }

            // Remove this section or make it configurable
            //if (result.Errors?.Count > 0)
            //{
            //    data = null;
            //}

            writer.WritePropertyName("data");
            serializer.Serialize(writer, data);
        }
```

**Comment by joemcbride** [comment]
This should be fixed in https://github.com/graphql-dotnet/graphql-dotnet/commit/0539da91c24932d9a8ba36887f37382427710427.  I'm pushing out a `0.17.0` with that fix.

**Comment by drobertson123** [comment]
Thanks for the quick response on that.

**Comment by joemcbride** [comment]
Got that published to Nuget.  Let me know if that works for you.

**Comment by drobertson123** [comment]
I finally had a chance to pull the nuget and do some tests. Everything looks like it is working fine.

I can add errors from inside resolve, they make it back up to the ExecutionResult and the JSON conversion now includes both errors and data as expected.  Thank you for the help.
