### ISSUE TITLE
Data Loader extensions

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#3675]
Hi,

I have a few simple data loader extensions that might be useful. I am not sure if you want to have that.

## Empty Result

Sometimes I can pass by the data loader result, so I use the empty result for that. Only a small benefit, because I think you could just return `Array.Empty<T>()` directly, but it is generated in a other class and I want to avoid object result.

```
public sealed class EmptyDataLoaderResult<T> : IDataLoaderResult<T[]>
{
    public Task<T[]> GetResultAsync(
        CancellationToken cancellationToken = default)
    {
        return Task.FromResult(Array.Empty<T>());
    }

    Task<object?> IDataLoaderResult.GetResultAsync(
        CancellationToken cancellationToken)
    {
        return Task.FromResult<object?>(Array.Empty<T>());
    }
}
```

I would also introduce `DataLoaderResult.Empty<T>()` in case you are interested.

## Select Result

I use the batch data loader, which could return null entries. The problem is, that my field does not allow null.

I have a simple data loader result that makes the conversion:

```

internal sealed class SelectDataLoaderResult<T, TResult> : IDataLoaderResult<TResult>
{
    private readonly IDataLoaderResult<T> source;
    private readonly Func<T, TResult> selector;

    public SelectDataLoaderResult(IDataLoaderResult<T> source, Func<T, TResult> selector)
    {
        this.source = source;
        this.selector = selector;
    }

    public async Task<TResult> GetResultAsync(
        CancellationToken cancellationToken = default)
    {
        var single = selector(await source.GetResultAsync(cancellationToken));

        return single;
    }

    async Task<object?> IDataLoaderResult.GetResultAsync(
        CancellationToken cancellationToken)
    {
        return await GetResultAsync(cancellationToken);
    }
}

internal static class SelectDataLoaderExtensions
{
    public static IDataLoaderResult<TResult> Select<T, TResult>(this IDataLoaderResult<T> source, Func<T, TResult> selector)
    {
        return new SelectDataLoaderResult<T, TResult>(source, selector);
    }
}
```

To use it:

```
return GetDataLoader().LoadAsync(ids).Select(x => x.Where(y != y != null));
```

**Comment by Shane32** [comment]
Have you tried the Then extension?

**Comment by SebastianStehle** [comment]
No, seems to do exactly the same :D ... Perfect! Less code is better.

**Comment by Shane32** [comment]
The Empty suggestion is worth considering but it applies to arrays and IDataLoaderResult isn’t specifically an array type response class. So if we were to add it, it would need to be called something appropriate. Maybe ArrayDataLoaderResult.Empty or DataLoaderResult.EmptyArray

**Comment by Shane32** [comment]
I'm inclined not to add `EmptyArray` unless any else has a comment here.
