### ISSUE TITLE
Cant stitch multiple schemas after receiving them as string

### ISSUE THREAD

**Issue by MWTRX** [graphql-dotnet/graphql-dotnet#3689]
Hey, I have a problem while trying to stitch multiple schemas after receiving them as a string.
After receiving the schemas as a string I'm building them with `Schema.For().` Then I add the fields of Query, Mutation and Subscription to the new schema.
Some of the queries/mutations of the schemas use the same GraphType. Because I'm building the schemas from their string they all create their own instance of those types and references to that.
Finally if I try to initialize the new schema I receive an InvalidOperationException with the error message:

```
A different instance of the GraphType 'ObjectGraphType' with the name 'DataPointType' has already been registered 
within the schema. 
Please use the same instance for all references within the schema, or use GraphQLTypeReference to reference a 
type instantiated elsewhere.
To view additional trace enable GlobalSwitches.TrackGraphTypeInitialization switch.
```
 

This is the source code I use:

```
private Schema? StitchSchemas()
{
     Schema? stitchedSchema = new Schema()
     {
                Mutation = new ObjectGraphType<object>() { Name = "dummyMutations", Description = "dummyDescription" },
                Query = new ObjectGraphType<object>() { Name = "dummyQuerys", Description = "dummyDescription" },
                Subscription = new ObjectGraphType<object>() { Name = "dummySubscription", Description = "dummyDescription" },
     };
    foreach (KeyValuePair<ServiceName, string> schemaKeyValuePair in _serviceSchemas)
            {
                Schema schema = Schema.For(schemaKeyValuePair.Value);

                schema.Mutation?.Fields.ToList().ForEach(field => stitchedSchema.Mutation.AddField(field));
                schema.Query?.Fields.ToList().ForEach(field => stitchedSchema.Query.AddField(field));
                schema.Subscription?.Fields.ToList().ForEach(field => stitchedSchema.Subscription.AddField(field));

                foreach (IGraphType graphType in schema.AdditionalTypeInstances)
                    {
                        if (!stitchedSchema.AdditionalTypeInstances.Any(type => type.Name == graphType.Name))
                        {
                            stitchedSchema.RegisterType(graphType);
                        }
                    }
            }
    try
            {
                stitchedSchema.Initialize();
            }
            catch (InvalidOperationException ioe)
            {
                return null;
            }
    return stitchedSchema;
}
```

The problem occurred with the update from v5 to v7. Since v7 GraphTypes can't have multiple instances, and in the [migration guide](https://graphql-dotnet.github.io/docs/migrations/migration7/) from v5 to v7, it's suggested in item 15 under 'Breaking Changes' to solve that by using a dictionary of instantiated types, or GraphQLTypeReference.

So now my questions are:
How can I provide the dictionary of instantiated types when parsing a schema string?
Is there another way to fix my problem?

**Comment by Shane32** [comment]
Is the purpose just to stitch together the schema strings and produce a stitched schema string?

**Comment by Shane32** [comment]
For that purpose I’d write code like this:
1. Parse each schema string with GraphQLParser
2. Find and remove the schema definition from each
3. Use the schema definition to identify the query, mutation and subscription type names. If not present, assume default names of Query, Mutation and Subscription
4. Combine or store one copy of the schema definition to be added to the result
5. Find and remove the query, mutation and subscription types, combining each of them and storing the combined definition
6. Get all the remaining definitions using DistinctBy (or GroupBy+First) on the name to be copied to the result. 
7. Add the schema definition and query/mutation/subscription definitions previously stored
8. Optional: sort with SDLSorter
9. Print schema with SDLPrinter

You can then use the resulting string with Schema.For if desired

**Comment by MWTRX** [comment]
Your code suggestion fixes the problem and Im able to stitch the schemas and initialize them.
Thank you
