### ISSUE TITLE
How to disable introspection query in a clean way ?

### ISSUE THREAD

**Issue by Brilbroeder** [graphql-dotnet/graphql-dotnet#3694]
for security reasons we want to disable the introspection.
How to do this ? An old post suggested by mingling with the a ISchema filter, but that does not seems to work anymore in the current version.

Any suggestions ?

**Comment by Shane32** [comment]
If you’re using an authorization library then just apply a policy to the introspection fields. If not you could write a very simple validation rule. I can assist if you’re unsure how.

**Comment by Shane32** [comment]
For a validation rule, you can copy the code from this PR, which may or may not get merged:
- https://github.com/graphql-dotnet/graphql-dotnet/pull/3695

**Comment by Brilbroeder** [comment]
@Shane32 I'm new to GraphQl. Checked the PR, but I have no idea where or what I should add to our application. In short I created schema's, types, queries, .... and hook them up in our app using services.AddGraphQL() and grphQlBuilder.AddSchema<T>.

**Comment by Shane32** [comment]
So in the call to AddGraphQL just add `.AddValidationRule<NoIntrospectionValidationRule>()`

**Comment by Shane32** [comment]
You need to add the validation rule and the error class. You don’t need to add the tests.

**Comment by Brilbroeder** [comment]
that dit it. Thx.
