### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/graphql-dotnet#3702]
There are some broken links in documentation pages: https://graphql-dotnet.github.io/. Mainly cross-page links.
For example, [Unions](https://graphql-dotnet.github.io/docs/getting-started/unions/) has a broken link to the `Interfaces` page
Instead of going to
```
https://graphql-dotnet.github.io/docs/getting-started/interfaces/
```
It goes to
```
https://graphql-dotnet.github.io/docs/getting-started/unions/Interfaces
```
Note the `/unions` before `/Interfaces` and also capital `I` instead of `i`.

- [ ] Also [Schema Types](https://graphql-dotnet.github.io/docs/getting-started/schema-types/) has a broken link to [Processing Error](https://graphql-dotnet.github.io/docs/getting-started/schema-types/errors#ProcessingErrors)
- [x] [Directives](https://graphql-dotnet.github.io/docs/getting-started/directives/#how-do-directives-work) to [Schema Service Lifetime](https://graphql-dotnet.github.io/docs/getting-started/directives/dependency-injection#schema-service-lifetime)
- [x] [Error Handling](https://graphql-dotnet.github.io/docs/getting-started/errors/#error-serialization) to [serialization](https://graphql-dotnet.github.io/docs/getting-started/guides/serialization)
- [x] [Field Middleware](https://graphql-dotnet.github.io/docs/getting-started/field-middleware/#field-middleware-and-dependency-injection) to [Dependency Injection](https://graphql-dotnet.github.io/docs/getting-started/field-middleware/Dependency-Injection)
- [ ] [Known Issues & FAQ](https://graphql-dotnet.github.io/docs/guides/known-issues/#entity-framework-concurrency-issues) to [dependency injection documentation](https://graphql-dotnet.github.io/docs/guides/getting-started/dependency-injection.md#scoped-services-with-a-singleton-schema-lifetime)

**Comment by Shane32** [comment]
Fixed items are noted by checkmarks above
