### ISSUE TITLE
upgradation of api from 3.1 to 6.0 

### ISSUE THREAD

**Issue by himanij949** [graphql-dotnet/graphql-dotnet#3731]
Hi,while upgrading the api we are facing issue with DocumentExecutor on below line

await documentexecuter.ExecuteAsync(options).ConfigureAwait(false);

we are getting this values but after upgrading the documentexecutor variable is returning null,
and i am getting some more errors

System.InvalidOperationException: IGraphQLTextSerializer not set in DI container. Add a IGraphQLTextSerializer implementation, for example GraphQL System TextJson.GraphQLSerializer or
GraphQL.NewtonsoftJson.GraphQLSerializer. For more information, see: https://github.com/graphql- dotnet/graphql-dotnet/blob/master/README.md.
at GraphQLDI.GraphQLBuilderBase.<>c.<RegisterDefaultServices>b_0_101ServiceProvider) in //src/GraphQL/DI/GraphQLBuilderBase.cs:line 36 at
Microsoft.Extensions.Dependencylnjection.ServiceLookup.CallSiteRuntimeResolver. VisitDisposeCache(ServiceCallSi te transientCallSite, RuntimeResolverContext context)at Microsoft.Extensions. Dependencyinjection.ServiceLookup.CallSiteVisitor 2 VisitCallSite(ServiceCallSite callSite,TArgument argument)
at Microsoft.Extensions.Dependencyinjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSiteSite. Service ProviderEngineScope scope)
at Microsoft.Extensions.Dependencyinjection.ServiceLookup.DynamicServiceProviderEngine.
<>c_DisplayClass2_0.<RealizeService>b_0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType. ServiceProviderEngineScope serviceProviderEngineScope)at
Microsoft.Extensions. DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(ServiceProvider provider. Type service Type)at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T]
(IServiceProvider provider) at GraphQL Server. Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in  PDQS\Graph_QL\src\DUSGraphQLServer Transports.AspNetCore\GraphQLHttpMiddleware.cs:line 77

Argument jobinput' has invalid value. In field 'dateRange': [In field 'startDate: [Expected type 'DateTime', found \" 2023-09-27\.] In field 'endDate': [Expected type 'DateTime', found \"2023-09- 27\"]] In field 'scheduleType': [Expected type 'ScheduleType', found Adhoc.] In field 'dataSource: [Expected type DataSourceType', found all.] In field 'outputFormatType': [Expected type 'OutputFormatType", found csv.]"

please help me to resolve those errors.

**Comment by himanij949** [comment]
Before upgration we are using this packages
<PackageReference Include="GraphQL.Server.Transports.Subscriptions.Abstractions" Version="4.4.1" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="4.4.1" />
<PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="4.4.1" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="4.4.1" />
<PackageReference Include="GraphQL.Server.Ui.Voyager" Version="4.4.1" />
<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="6.9.0" />
<PackageReference Include="Serilog.Extensions.Logging.File" Version="2.0.0" />
<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.9.0" />
<PackageReference Include="System.Reactive" Version="5.0.0" />

during upgradation we are using this
<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
<PackageReference Include="Azure.Identity" Version="1.10.2" />
<PackageReference Include="GraphQL.Authorization" Version="7.0.0" />
<PackageReference Include="GraphQL.DataLoader" Version="7.6.1" />
<PackageReference Include="GraphQL.MicrosoftDI" Version="7.6.1" />
<PackageReference Include="GraphQL.Server.All" Version="7.6.0" />
<PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="7.6.0" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="7.6.0" />
<PackageReference Include="GraphQL.Server.Ui.Voyager" Version="7.6.0" />
<PackageReference Include="Microsoft.Identity.Client" Version="4.56.0" />
<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.0.2" />
<PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.2" />
<PackageReference Include="System.Reactive" Version="6.0.0" />

**Comment by himanij949** [comment]
Before upgradation we are using this packages
<img width="518" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/ab710617-8e5d-4e8f-93b1-68e6d226a2c7">


during upgradation we are using this
<img width="623" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/22178eaa-b6d9-4d13-97db-e9b85ca5c054">

**Comment by Shane32** [comment]
Ok, makes sense.  One questione: In your 'before' list I do not see GraphQL.Authorization.  Are you adding authorization?  If so, I suggest using the authorization library included within GraphQL.Server.All.

**Comment by Shane32** [comment]
I can help you with the migration.  But first, have you read through the migration documents for each version located here:
- [Version 3.x to 4.x](https://graphql-dotnet.github.io/docs/migrations/migration4/)
- [Version 4.x to 5.x](https://graphql-dotnet.github.io/docs/migrations/migration5/)
- [Version 5.x to 7.x](https://graphql-dotnet.github.io/docs/migrations/migration7/)

**Comment by himanij949** [comment]
my main project having dependency of two assemblies,
Before upgrading 1st assembly having dll,s
<PackageReference Include="Azure.Identity" Version="1.4.0" />
<PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
<PackageReference Include="GraphQL" Version="3.3.2" />
<PackageReference Include="GraphQL.NewtonsoftJson" Version="3.3.2" />
<PackageReference Include="GraphQL.Server.Core" Version="4.4.1" />
<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
<PackageReference Include="Microsoft.Extensions.Options" Version="2.2.0" />
<PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
<PackageReference Include="System.Runtime.Caching" Version="5.0.0" />
after upgrading that assembly version,
<PackageReference Include="Azure.Identity" Version="1.10.2" />
<PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
<PackageReference Include="GraphQL.Authorization" Version="7.0.0" />
<PackageReference Include="GraphQL.DataLoader" Version="7.6.1" />
<PackageReference Include="GraphQL.MemoryCache" Version="7.6.1" />
<PackageReference Include="GraphQL.MicrosoftDI" Version="7.6.1" />
<PackageReference Include="GraphQL.NewtonsoftJson" Version="7.6.1" />
<PackageReference Include="GraphQL.Server.All" Version="7.6.0" />
<PackageReference Include="GraphQL.Server.Ui.Altair" Version="7.6.0" />
<PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="7.6.0" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="7.6.0" />
<PackageReference Include="GraphQL.Server.Ui.Voyager" Version="7.6.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="7.0.0" />

<PackageReference Include="Microsoft.Extensions.Options" Version="7.0.1" />
<PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
<PackageReference Include="System.Runtime.Caching" Version="7.0.0" />

Before upgradation of second assembly
DUSLIb --> <PackageReference Include="Azure.Identity" Version="1.4.0" />
<PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
<PackageReference Include="GraphQL" Version="3.3.2" />
<PackageReference Include="Jaeger" Version="0.4.3" />
<PackageReference Include="Microsoft.ApplicationInsights" Version="2.17.0" />
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.17.0" />
<PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.8" />
<PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.8" />
<PackageReference Include="Microsoft.Extensions.Options" Version="3.1.8" />
<PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.9" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
<PackageReference Include="prometheus-net" Version="4.1.1" />
<PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
<PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
<PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
<PackageReference Include="System.Runtime.Caching" Version="5.0.0" />

after upgrading the dependent assembly
<PackageReference Include="Azure.Identity" Version="1.10.2" />
<PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
<PackageReference Include="GraphQL.Authorization" Version="7.0.0" />
<PackageReference Include="GraphQL.Server.All" Version="7.6.0" />
<PackageReference Include="Jaeger" Version="1.0.3" />
<PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
<PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
<PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
<PackageReference Include="Microsoft.Extensions.Options" Version="7.0.1" />
<PackageReference Include="Microsoft.Identity.Client" Version="4.56.0" />
<PackageReference Include="Microsoft.Identity.Web" Version="2.15.1" />
<PackageReference Include="Microsoft.Identity.Web.TokenCache" Version="2.15.1" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
<PackageReference Include="prometheus-net" Version="8.0.1" />
<PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
<PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
<PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
<PackageReference Include="System.Runtime.Caching" Version="7.0.0" />

**Comment by himanij949** [comment]
yes we have gone through with this upgrade documentation and following it.

**Comment by Shane32** [comment]
It looks like you’re upgrading from .NET Core 2.2 to .NET Core 7.0 at the same time - is that correct? Or is this a .NET Framework project?

**Comment by Shane32** [comment]
If you’re still getting the error regarding “IGraphQLTextSerializer not set in DI container” then we should review how it’s wired up in your startup.cs / program.cs files. Can you provide the relevant code?

**Comment by Shane32** [comment]
Once you have basic “hello world” requests going again then we can fix the date. Probably the date error is due to a field resolver returning a date string for a date graph type instead of returning the date itself. The current version of GraphQL is much more strict about being sure that .NET code returns .NET types, having the scalar convert it to a string when needed. Also on the input side, Newtonsoft by default parses dates, so we need to be sure the date parsing is disabled so the scalar can do this job. So that could be an issue also.

**Comment by himanij949** [comment]
my main project is in .net core 3.1 and one dependent assembly is in 3.1 also,second one using .net standard 2.0 and we are migrating to 6.0.

**Comment by himanij949** [comment]
can you suggest some point to resolve below error,
<img width="659" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/53831a9d-53ce-4fdb-a4f3-8dc97e62c2b1">

**Comment by Shane32** [comment]
> my main project is in .net core 3.1 and one dependent assembly is in 3.1 also,second one using .net standard 2.0 and we are migrating to 6.0.

Ok that’s no problem

**Comment by himanij949** [comment]
> can you suggest some point to resolve below error, <img alt="image" width="659" src="https://user-images.githubusercontent.com/71135940/275225572-53831a9d-53ce-4fdb-a4f3-8dc97e62c2b1.png">

Issue resolved.

**Comment by himanij949** [comment]
I need some help related to token generation getting below errors 
Microsoft.Identity.Client.MsalServiceException: 'AADSTS1002012: The provided value for scope User.Read is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).
and Unable to cast object of type 'GraphQL.Execution.RootExecutionNode' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object].,kindly help to resolving this.

**Comment by Shane32** [comment]
The second problem will be due to the GraphQL response not being serialized by the GraphQL serializer implementation. Can you provide the code that the error stops on?

**Comment by Shane32** [comment]
As for the identity client error, I’m not very familiar with that library, but if you post the code that’s causing the issue I could let you know if I have any ideas.

**Comment by himanij949** [comment]
startup.cs file.
public class Startup
{
    public IConfiguration Configuration { get; }

 

    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
        // ApplicationInsights            
        var telemetryConfiguration = TelemetryConfiguration.CreateDefault();
        var telemetryClient = new TelemetryClient(telemetryConfiguration);
        telemetryClient.TrackPageView("Startup");
    }

 

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvcCore();
        services.AddApplicationInsightsTelemetry(Configuration);

 

        services.AddSingleton<IServiceProvider>(s => new FuncServiceProvider(s.GetRequiredService));
        services.AddSingleton<IDocumentExecuter, DocumentExecuter>();
        //services.AddSingleton<IDocumentWriter, DocumentWriter>();
        services.AddSingleton<IGraphQLSerializer, GraphQLSerializer>();
        services.AddSingleton<GraphQL.IGraphQLTextSerializer, GraphQLSerializer>();
        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        services.AddSingleton<IDUSOperations, DUSData>();

 

        services.AddSingleton<DUSSchema>();
        services.AddSingleton<DUSQuery>();
        services.AddSingleton<DUSMutation>();

 

        services.AddSingleton<PractitionerInformationGraphType>();
        services.AddSingleton<PractitionerTypeGraphType>();
        services.AddSingleton<PractitionerProfessionalIdGraphType>();
        services.AddSingleton<PractitionerEducationGraphType>();
        services.AddSingleton<PractitionerNpiGraphType>();
        services.AddSingleton<PractitionerDeaGraphType>();
        services.AddSingleton<PractitionerCdsGraphType>();
        services.AddSingleton<PractitionerLicenseGraphType>();
        services.AddSingleton<PractitionerMedicaidGraphType>();
        services.AddSingleton<PractitionerMedicareGraphType>();
        services.AddSingleton<PractitionerPracticeLocationGraphType>();
        services.AddSingleton<PractitionerArchivedLocationGraphType>();
        services.AddSingleton<PracticeLocationGraphType>();
        services.AddSingleton<PractitionerRejectedLocationGraphType>();
        services.AddSingleton<PractitionerBatchGraphType>();
        services.AddSingleton<ISchema, DUSSchema>();
        services.AddSingleton<GraphQLAuthMiddleware>();
        services.AddSingleton<ConstraintType>();
        services.AddGraphQL(options =>
        {
            //options.AddAutoSchema<Query>();
            //options.AddExecutionStrategy<SerialExecutionStrategy>(OperationType.Query);
            options.AddDataLoader();
            options.UseApolloTracing();
            options.AddScopedSubscriptionExecutionStrategy();
            //options.EnableMetrics = true;
            //options.ExposeExceptions = true;
            options.ConfigureExecution(async (options, next) =>
            {
                var timer = Stopwatch.StartNew();
                var result = await next(options);
                result.Extensions ??= new Dictionary<string, object?>();
                result.Extensions["elapsedMs"] = timer.ElapsedMilliseconds;
                return result;
            });
        })
        .AddWebSockets(webSocketOptions => new WebSocketOptions()
        {
            KeepAliveInterval = TimeSpan.FromSeconds(120)
        });
        //.AddDataLoader();

 

 

        services.Configure<IISOptions>(options => options.ForwardClientCertificate = false);

 

        services.AddLogging(X =>
        {
            X.AddConsole();
            X.AddDebug();
            X.AddEventSourceLogger();
        });

 

        services.Configure<IISServerOptions>(options =>
        {
            options.AllowSynchronousIO = true;
        });

 

    }

 

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
    {
        if (env.EnvironmentName == Microsoft.Extensions.Hosting.Environments.Development)
            app.UseDeveloperExceptionPage();

 

        app.UseDefaultFiles();
        app.UseStaticFiles();

 

        string filePath = Configuration.GetSection(string.Format(DUSGraphQLConstants.CONFIG_SECTION_FORMAT_TEXT, "LogFilePath")).Value;
        loggerFactory.AddFile(filePath);

 

        string graphQLEndPoint = Configuration.GetSection(string.Format(DUSGraphQLConstants.CONFIG_SECTION_FORMAT_TEXT, DUSGraphQLConstants.GRAPHQL_END_POINT)).Value;
        string defaultGraphQLEndPoint = Configuration.GetSection(string.Format(DUSGraphQLConstants.CONFIG_SECTION_FORMAT_TEXT, DUSGraphQLConstants.DEFAULT_GRAPHQL_END_POINT)).Value;

 

        app.UseGraphQLAuth();
        app.UseWebSockets();
        //app.UseGraphQLWebSockets<DUSSchema>(defaultGraphQLEndPoint);
        app.UseGraphQL<DUSSchema>(defaultGraphQLEndPoint);
        // add http for Schema at default url /graphql
        app.UseGraphQL<ISchema>(defaultGraphQLEndPoint);

 

        app.UseGraphQLPlayground(DUSGraphQLConstants.PATH_UI_PLAYGROUND_TEXT, options: new PlaygroundOptions()
        {
            GraphQLEndPoint = graphQLEndPoint
        });
        app.UseGraphQLGraphiQL(DUSGraphQLConstants.PATH_UI_GRAPHIQL_TEXT, options: new GraphiQLOptions()
        {
            GraphQLEndPoint = graphQLEndPoint
        });
        app.UseGraphQLVoyager(DUSGraphQLConstants.PATH_UI_VOYAGER_TEXT, options: new VoyagerOptions()
        {
            GraphQLEndPoint = graphQLEndPoint
        });
        app.UseRouting();
    }
}

**Comment by himanij949** [comment]
we are getting error in this line
<img width="715" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/97aa7690-fb4b-4d1f-b989-4ff16ddb41e1">

**Comment by Shane32** [comment]
your startup looks pretty good.  you should be able to remove these lines:

```cs
    services.AddSingleton<IServiceProvider>(s => new FuncServiceProvider(s.GetRequiredService));
    services.AddSingleton<IDocumentExecuter, DocumentExecuter>();
    //services.AddSingleton<IDocumentWriter, DocumentWriter>();
    services.AddSingleton<IGraphQLSerializer, GraphQLSerializer>();
    services.AddSingleton<ISchema, DUSSchema>();
```

and then change this line and add another:

```cs
//remove:
    //options.AddAutoSchema<Query>();
//add:
    options.AddSchema<DUSSchema>();
    options.AddNewtonsoftJson(); // or options.AddSystemTextJson();
```

Is `GraphQLAuthMiddleware` one of your classes?  I don't recognize it from any current versions of GraphQL.NET code.

**Comment by Shane32** [comment]
Can you provide the stack trace for the error you're receiving?  Also the definition of the `jobInput` argument and the code that defines the `startDate` and `endDate` fields.

**Comment by Shane32** [comment]
I'm also having difficulty finding what `app.UseGraphQLAuth();` does.  Is this also part of your code?

**Comment by himanij949** [comment]
When i am trying to resolve this error i have added this lines for  removig this error can you confirm is it correct 
Argument 'jobInput' has invalid value. In field 'dateRange': [In field 'startDate': [Expected type 'DateTime']
<img width="449" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/2f6ebc32-2ccb-48a9-b755-d07b5432b828">

**Comment by Shane32** [comment]
It is unlikely that will help.  `options.AddNewtonsoftJson` already sets those options by default.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.NewtonsoftJson/JsonSerializerSettings.cs

**Comment by Shane32** [comment]
> Can you provide the stack trace for the error you're receiving? Also the definition of the `jobInput` argument and the code that defines the `startDate` and `endDate` fields.

I'll need this to continue analysis.

**Comment by Shane32** [comment]
My comment about date parsing is really only applicable when you're using NewtonsoftJson directly, such as through custom middleware or a MVC endpoint.  But in your case you are using the ASP.Net Core middleware within GraphQL.NET Server which should have all the default options set up correctly.

**Comment by Shane32** [comment]
I'd also suggest switching to the SystemTextJson serializer, which is natively async, but it should work identical either way.

**Comment by himanij949** [comment]
<img width="401" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/69c60f11-735d-4083-964c-3464943a3f75">
<img width="368" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/9ac74637-61c9-4471-83b8-11e1e9a4e411">

**Comment by Shane32** [comment]
Are there graph types defined for these fields? Or using AutoRegisteringInputObjectGraphType?

**Comment by himanij949** [comment]
yes we have graphtype defined.

**Comment by Shane32** [comment]
are they using DateTimeGraphType or DateGraphType ?

**Comment by himanij949** [comment]
DateTimeGraphType

**Comment by Shane32** [comment]
Ok then that's your problem.  In GraphQL.NET v4 (?) and newer, `DateTimeGraphType` requires date/time values in ISO-8601 format such as:
- `2023-10-14T12:34:56Z` or
- `2023-10-14T12:34:56.789-05:00`

It will parse those values and convert them into UTC `DateTime` instances, and it will reject any other format.  To use ISO-8601 date-only format, use the `DateGraphType` which will serialize and deserialize values in this format:
- `2023-10-14`

See:
- https://github.com/graphql-dotnet/graphql-dotnet/blob/f44194cb3fb9099ffdc189afab8f9d8fd146a70f/src/GraphQL/Types/Scalars/DateGraphType.cs#L48-L55
- https://github.com/graphql-dotnet/graphql-dotnet/blob/f44194cb3fb9099ffdc189afab8f9d8fd146a70f/src/GraphQL/Types/Scalars/DateTimeGraphType.cs#L45-L52


You can of course create a custom scalar which will deserialize and serialize `DateTime` values the way that works best for you.

New to .NET 6 is the `DateOnly` format, also supported by GraphQL.NET via the `DateOnlyGraphType`.  It also only accepts ISO-8601 date-only formats when serializing or deserializing.  Now that SqlClient supports `DateOnly`, I've converted my own applications to use only `DateOnly` or `DateTimeOffset` values throughout, corresponding to the SQL `date` and `datetimeoffset` data types, never using `DateTime` unless necessary.

**Comment by himanij949** [comment]
> Ok then that's your problem. In GraphQL.NET v4 (?) and newer, `DateTimeGraphType` requires date/time values in ISO-8601 format such as:
> 
> * `2023-10-14T12:34:56Z` or
> * `2023-10-14T12:34:56.789-05:00`
> 
> It will parse those values and convert them into UTC `DateTime` instances, and it will reject any other format. To use ISO-8601 date-only format, use the `DateGraphType` which will serialize and deserialize values in this format:
> 
> * `2023-10-14`
> 
> See:
> 
> * https://github.com/graphql-dotnet/graphql-dotnet/blob/f44194cb3fb9099ffdc189afab8f9d8fd146a70f/src/GraphQL/Types/Scalars/DateGraphType.cs#L48-L55
> * https://github.com/graphql-dotnet/graphql-dotnet/blob/f44194cb3fb9099ffdc189afab8f9d8fd146a70f/src/GraphQL/Types/Scalars/DateTimeGraphType.cs#L45-L52
> 
> You can of course create a custom scalar which will deserialize and serialize `DateTime` values the way that works best for you.
> 
> New to .NET 6 is the `DateOnly` format, also supported by GraphQL.NET via the `DateOnlyGraphType`. It also only accepts ISO-8601 date-only formats when serializing or deserializing. Now that SqlClient supports `DateOnly`, I've converted my own applications to use only `DateOnly` or `DateTimeOffset` values throughout, corresponding to the SQL `date` and `datetimeoffset` data types, never using `DateTime` unless necessary.

Thankyou so much for your response and support,issue has been resolved.

**Comment by himanij949** [comment]
we are getting error in this now,when we are sending in this casetype '"json" it is throwing error,please guide me with the same.
outputFormatType: json
"Argument 'jobInput' has invalid value. In field 'outputFormatType': [Expected type 'OutputFormatType', found json.]",
public enum OutputFormatType
{
    JSON = 1,
    CSV = 2,
}

**Comment by himanij949** [comment]
and we are getting this error if you have any idea to how to resolve 
<img width="841" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/2ff708a4-c4ad-4882-a313-636a925f8eed">

**Comment by himanij949** [comment]
> and we are getting this error if you have any idea to how to resolve <img alt="image" width="841" src="https://user-images.githubusercontent.com/71135940/275318754-2ff708a4-c4ad-4882-a313-636a925f8eed.png"> <img alt="image" width="574" src="https://user-images.githubusercontent.com/71135940/275329460-7a4df1f7-c05c-4f82-99d8-f9c57ebb304a.png">

issue resolved.

**Comment by Shane32** [comment]
> we are getting error in this now,when we are sending in this casetype '"json" it is throwing error,please guide me. outputFormatType: json "Argument 'jobInput' has invalid value. In field 'outputFormatType': [Expected type 'OutputFormatType', found json.]", public enum OutputFormatType { JSON = 1, CSV = 2, }

Enums are case sensitive now, pursuant to the GraphQL specification.  Probably a v4 change.

**Comment by Shane32** [comment]
> > and we are getting this error if you have any idea to how to resolve <img alt="image" width="841" src="https://user-images.githubusercontent.com/71135940/275318754-2ff708a4-c4ad-4882-a313-636a925f8eed.png"> <img alt="image" width="574" src="https://user-images.githubusercontent.com/71135940/275329460-7a4df1f7-c05c-4f82-99d8-f9c57ebb304a.png">
> 
> issue resolved.

Both issues?

The first issue is because ExecutionResult.Data contains a RootExecutionNode now instead of a dictionary.  The second issue is because you have a Field / Resolve instead of FieldAsync / ResolveAsync.

**Comment by himanij949** [comment]
all issue has been resolved,thankyou so much for your help and support.

**Comment by himanij949** [comment]
one issue is pending,once that will resolve i will close this ticket.

**Comment by himanij949** [comment]
Hi,Do you have any idea how to convert this input parameter enum case sensitive to case insensitive,so it will accept all cases.

> > we are getting error in this now,when we are sending in this casetype '"json" it is throwing error,please guide me. outputFormatType: json "Argument 'jobInput' has invalid value. In field 'outputFormatType': [Expected type 'OutputFormatType', found json.]", public enum OutputFormatType { JSON = 1, CSV = 2, }
> 
> Enums are case sensitive now, pursuant to the GraphQL specification. Probably a v4 change.

**Comment by Shane32** [comment]
Add this class:

```cs

    public class CaseInsensitiveEnumGraphType<T> : EnumerationGraphType<T>
        where T : Enum
    {
        /// <inheritdoc/>
        public override object? ParseLiteral(GraphQLValue value) => value switch {
            GraphQLEnumValue enumValue => Values.FindByName(enumValue.Name.ToString().ToUpperInvariant())?.Value ?? ThrowLiteralConversionError(value),
            GraphQLNullValue _ => null,
            _ => ThrowLiteralConversionError(value)
        };

        /// <inheritdoc/>
        public override bool CanParseLiteral(GraphQLValue value) => value switch {
            GraphQLEnumValue enumValue => Values.FindByName(enumValue.Name.ToString().ToUpperInvariant()) != null,
            GraphQLNullValue _ => true,
            _ => false
        };

        /// <inheritdoc/>
        public override object? ParseValue(object? value) => value switch {
            string s => Values.FindByName(s.ToUpperInvariant())?.Value ?? ThrowValueConversionError(value),
            null => null,
            _ => ThrowValueConversionError(value)
        };

        /// <inheritdoc/>
        public override bool CanParseValue(object? value) => value switch {
            string s => Values.FindByName(s.ToUpperInvariant()) != null,
            null => true,
            _ => false
        };
    }
```

Then add this in your startup:

```cs
        // make all enums case insensitive
        services.AddTransient(typeof(EnumerationGraphType<>), typeof(CaseInsensitiveEnumGraphType<>));
```

It should work across your entire codebase with no other code changes, so long as you typically just use `EnumerationGraphType<T>` and do not manually define your enum graph types.

**Comment by Shane32** [comment]
If you provide a sample of an enumeration graph type I can demonstrate the changes required

**Comment by himanij949** [comment]
<img width="534" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/228c7f9c-2d9e-400e-ae77-947fc90418ed">
<img width="442" alt="image" src="https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/a05565c7-c4f9-44d4-8855-a93b909a902c">

**Comment by Shane32** [comment]
Just change the base type of your enumeration graph types to the one I posted. Should work fine.

**Comment by himanij949** [comment]
> > Ok then that's your problem. In GraphQL.NET v4 (?) and newer, `DateTimeGraphType` requires date/time values in ISO-8601 format such as:
> > 
> > * `2023-10-14T12:34:56Z` or
> > * `2023-10-14T12:34:56.789-05:00`
> > 
> > It will parse those values and convert them into UTC `DateTime` instances, and it will reject any other format. To use ISO-8601 date-only format, use the `DateGraphType` which will serialize and deserialize values in this format:
> > 
> > * `2023-10-14`
> > 
> > See:
> > 
> > * https://github.com/graphql-dotnet/graphql-dotnet/blob/f44194cb3fb9099ffdc189afab8f9d8fd146a70f/src/GraphQL/Types/Scalars/DateGraphType.cs#L48-L55
> > * https://github.com/graphql-dotnet/graphql-dotnet/blob/f44194cb3fb9099ffdc189afab8f9d8fd146a70f/src/GraphQL/Types/Scalars/DateTimeGraphType.cs#L45-L52
> > 
> > You can of course create a custom scalar which will deserialize and serialize `DateTime` values the way that works best for you.
> > New to .NET 6 is the `DateOnly` format, also supported by GraphQL.NET via the `DateOnlyGraphType`. It also only accepts ISO-8601 date-only formats when serializing or deserializing. Now that SqlClient supports `DateOnly`, I've converted my own applications to use only `DateOnly` or `DateTimeOffset` values throughout, corresponding to the SQL `date` and `datetimeoffset` data types, never using `DateTime` unless necessary.
> 
=
hey,i am getting one error from this i changed from datetime' to 'dateonly' but in some where in our some Api call we are getting this error  In field 'dateRange': [In field 'startDate: [Expected type 'DateTime', found " 2023-09-27.] In field 'endDate': [Expected type 'DateTime', found "2023-09- 27"]]
can i have any solution where it will accept for format type of dates,if you help it would be grateful. Thanks

**Comment by Shane32** [comment]
I would suggest making a custom scalar.  You can then customize the date parsing in any way you wish.

I would start by duplicating the source code of `DateGraphType` or `DateOnlyGraphType` and modifying it as needed.  You can read detailed instructions for custom scalars here:
- https://graphql-dotnet.github.io/docs/getting-started/custom-scalars/

You will likely need to register the custom scalar with your schema - see this link:
- https://graphql-dotnet.github.io/docs/getting-started/custom-scalars/#8-code-first-register-the-net-type-mapping-with-the-schema-optional

Anything that directly references `DateGraphType` or `DateOnlyGraphType` may need to change to reference your new class.

Once complete, your schema will parse date formats based on the code you've written in the custom scalar, and you should have no more trouble.

**Comment by Shane32** [comment]
Note that this should be pretty easy to do.  Let me know if you run into any difficulty.

**Comment by Shane32** [comment]
Please re-open if you have further issues

**Comment by himanij949** [comment]
Hi Shane,we are getting one exception,while we are creating JWT token for a 1st time it is generating in properly format,but after hitting second time,miliseconds are it get trimmed after we are converting else it will not generating the mili second.
![datetime](https://github.com/graphql-dotnet/graphql-dotnet/assets/71135940/c5ea17db-5e2f-42f8-b3d8-03b91397b6e9)

**Comment by Shane32** [comment]
GraphQL.NET doesn't deal with JWTs directly.  If you're using GraphQL.NET Server, well it doesn't either except for within the JWT sample application.  What code are you using to generate your JWTs?  Not that it should do that, but is the lack of decimals a problem?
