### ISSUE TITLE
Cannot convert value to AST

### ISSUE THREAD

**Issue by mattferrin** [graphql-dotnet/graphql-dotnet#376]
I send similar queries with similar inputs all the time, and can't fathom what is wrong this time.

Errors:
```
[0] = {"Cannot convert value to AST: b6cca29a-1457-46a1-a5c7-26f599bb20b4"}
```

Partial Code:
```
            ISchema graphSchema = container.Get<GraphSchema>();
            var result = await executer.ExecuteAsync(_ =>
            {
                _.Schema = graphSchema;
                _.Query = query;
                //_.OperationName = operationName;
                _.Inputs = inputs;
                _.UserContext = deeplyRelevant;
            });
            return writer.Write(result);
```

Input:
```
[0] = {[inspectionReportInspectionIds, [
  "b6cca29a-1457-46a1-a5c7-26f599bb20b4"
]]}
```

Query:
```
query InspectionReportInspectionTagQuery(
  $inspectionReportInspectionIds: [String]
) {
  viewer {
    ...InspectionReportInspectionTag_viewer_34tdXo
  }
}

fragment InspectionReportInspectionTag_viewer_34tdXo on Viewer {
  ...AppTagWeb_viewer
  subViewer {
    inspectionReportInspections(inspectionIds: $inspectionReportInspectionIds) {
      inspectionId
    }
  }
}

fragment AppTagWeb_viewer on Viewer {
  ...HomeBodyTagWeb_viewer
  isAdmin
}

fragment HomeBodyTagWeb_viewer on Viewer {
  isAuthenticated
}
```

**Comment by joemcbride** [comment]
Do you have a custom scalar that is returning a `Guid` in its serialize method?  What is the `GraphType` for `inspectionIds` on `inspectionReportInspections`?

There error is [thrown here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/GraphQLExtensions.cs#L411), so the type returned from the `scalar.Serialize` method is returning a type that the method doesn't recognize.

See also https://github.com/graphql-dotnet/graphql-dotnet/issues/370#issuecomment-314803698

**Comment by mattferrin** [comment]
I've looked through the Github source and saw that... but all I am dealing with is a list of strings, even removed the dashes to see if it would help.

No custom scalars.


The field in question:
```
Field<ListGraphType<InspectionType>>(
    "inspectionReportInspections",
    arguments: new QueryArguments(new QueryArgument[] {
        new QueryArgument<ListGraphType<StringGraphType>> {
            Name = "inspectionIds"
        }
    }),
    resolve: context =>
    {
        // I have more code here, but it's not relevant.
    }
);
```

**Comment by joemcbride** [comment]
What version are you using?

**Comment by mattferrin** [comment]
I just updated to the latest on Nuget. Will edit this comment with the version number, which I am looking up now.

**Comment by joemcbride** [comment]
Honestly not sure what the issue is.  It works on basic queries, proved here: https://github.com/graphql-dotnet/graphql-dotnet/pull/377

Possibly an issue with fragments?  Can you reproduce the issue in a test?

**Comment by mattferrin** [comment]
I think it is an issue a bit related to Relay Modern fragment generation. Queried the field with Relay Classic before. 

Cloned the dependencies. Am going to try to debug, if stepping into dependencies is possible in C# like this. Slightly more of a JavaScript guru. Thanks for taking a look at this.

**Comment by joemcbride** [comment]
Also just pushed a test with using variables in a fragment and it works there too.  So has to be some other setup you have.

> if stepping into dependencies is possible in C# like this

Should be.

**Comment by mattferrin** [comment]
I don't understand why this is the case this one particular time, but...

Adding a `serialized.GetValue()` clause to graphql-dotnet\src\GraphQL\GraphQLExtensions.cs works:
```
            if (serialized is string)
            {
                if (type is EnumerationGraphType)
                {
                    return new EnumValue(serialized.ToString());
                }

                return new StringValue(serialized.ToString());
            }

            if (serialized.GetValue() is string)
            {
                if (type is EnumerationGraphType)
                {
                    return new EnumValue(serialized.GetValue().ToString());
                }

                return new StringValue(serialized.GetValue().ToString());
            }

            throw new ExecutionError($"Cannot convert value to AST: {serialized}");
```

**Comment by joemcbride** [comment]
That shouldn't be needed.  In that context, what is the .NET Type of `serialized`?  How are you creating your `Inputs` class?  The `.ToInputs` extension method calls `GetValue` for you ...

**Comment by mattferrin** [comment]
First thing my MVC Controller Action does regarding inputs:

```cs
            Func<string> getRequest = () =>
            {
                Request.InputStream.Position = 0;
                using (Stream receiveStream = Request.InputStream)
                {
                    using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                    {
                        return readStream.ReadToEnd();
                    }
                }
            };
            request = getRequest();

            IDictionary<string, object> nestedKeysValues = JsonConvert.DeserializeObject<IDictionary<string, object>>(request, new JsonConverter[] { new NestedKeysValues() });
            Inputs inputs = new Func<Inputs>(() =>
            {
                if (nestedKeysValues.ContainsKey("variables") && nestedKeysValues["variables"] != null)
                {
                    return new Inputs((Dictionary<string, object>)nestedKeysValues["variables"]);
                }
                else
                {
                    return new Inputs(new Dictionary<string,object>());
                }
            })();
```

**Comment by mattferrin** [comment]
My object appears to be another object that is a string, but I will update this comment if I am wrong.

**Comment by joemcbride** [comment]
That looks to be the issue. I would suggest to do it like this example:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQLCore/GraphQLMiddleware.cs#L57

**Comment by mattferrin** [comment]
I'm honestly confused because the dictionary I pass to inputs looks great when I inspect it and I parse a lot of other input variables that are also arrays of strings just fine, but I'll try anything. Don't mind changing my code to match the example as much as possible. Thanks for the help and we'll see if it works.

**Comment by mattferrin** [comment]
Your deserialization technique works perfectly and resolves my issue. Thank you.
```cs
public class GraphQLRequest
{
    public string OperationName { get; set; }
    public string Query { get; set; }
    public JObject Variables { get; set; }
}

[HttpPost]
[AllowAnonymous]
public async Task<string> PostGraph(string request)
{
    Func<string> getRequest = () =>
    {
        Request.InputStream.Position = 0;
        using (Stream receiveStream = Request.InputStream)
        {
            using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
            {
                return readStream.ReadToEnd();
            }
        }
    };
    request = getRequest();
    GraphQLRequest deserialized = JsonConvert.DeserializeObject<GraphQLRequest>(request);

    // ...
```
