### ISSUE TITLE
Analyzer should verify input object constructors

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/graphql-dotnet#3774]
> @gao-artur Assuming you approve of this PR, a good candidate for an analyzer for v8 would be as follows: look for classes that inherit from `InputObjectGraphType<T>` where the following is true:
> 1. The class is not a generic class
> 2. `ParseDictionary` is not overridden
> 3. `T` has multiple public constructors
> 4. `T` has no parameterless public constructor
> 5. `T` has no public constructor marked with `[GraphQLConstructor]`
> 
> I would simply flag as an error with no automatic code fix; let the developer mark the proper constructor or otherwise resolve the issue.  This would certainly be valuable when upgrading from v7 to v8.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/issues/3773#issuecomment-1811762073_

**Comment by gao-artur** [comment]
@Shane32 can you please create an `analyzers` label?

**Comment by Shane32** [comment]
> @Shane32 can you please create an `analyzers` label?

Done
