### ISSUE TITLE
`InputGraphTypeAnalyzer`  should skip types that override `ParseDictionary`

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/graphql-dotnet#3775]
`InputGraphTypeAnalyzer`  should skip by default types that override `ParseDictionary` or when the source code of one of the base types is not available.

It should allow providing a configuration in `.editorconfig` with a list of base types that should be analyzed anyway.

A real-world example: we have created a base type that inherits from `InputObjectGraphType<T>` and overrides `ParseDictionary`. Most of our input types inherit from this base class, which is both: overrides `ParseDictionary` and distributed with nuget (its source code is not available during the code analysis). But we still rely on the proper fields-properties mapping.

@Shane32 is this additional configuration sound reasonable to include?

**Comment by Shane32** [comment]
Sure
