### ISSUE TITLE
SchemaPrinter does not emit `scalar Date` when schema contains a DateGraphType node

### ISSUE THREAD

**Issue by antmdvs** [graphql-dotnet/graphql-dotnet#378]
This applies to `Decimal` as well as `Date`.

Do you think these custom scalars should be auto-emitted by `SchemaPrinter` if there are any nodes using them?

**Comment by joemcbride** [comment]
They are currently they are considered "built-in" scalars, as [configured here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L25-L26).  They are not technically part of the spec, so I could see an argument for printing them.

We could perhaps provide a way to override what the built-in scalars are defined as instead of it just being an additive configuration as it currently is.

**Comment by antmdvs** [comment]
I see now that the code is already in place to print the SDL/IDL in question, but the issue seems to stem from the indistinct treatment of *custom* "built-in" scalars and **actual** ["built-in scalars"](https://facebook.github.io/graphql/#sec-Scalars) as defined in the spec: `Int, Float, String, Boolean, ID` (those being referred to as "core types" [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L18-L23)).

To illustrate this, I temporarily modified the `IsBuiltInScalar()` method to exclude "Date" and "Decimal" as follows:

```csharp
public bool IsBuiltInScalar(string typeName)
{
    return _scalars
        .Except(new[] { "Date", "Decimal" }) // these are "custom" according to the spec
        .Contains(typeName);
}
```
and then the expected SDL is included in the schema printout:
```graphql
# The `Date` scalar type represents a timestamp provided in UTC. `Date` expects
# timestamps to be formatted in accordance with the
# [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
scalar Date

scalar Decimal
```

Would you be open to aligning the terminology with that of with the spec?

1. ["core types"](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L18) should be "built-in scalars"
2. All other scalars, including `Date`/`Decimal`, should be "custom" scalars.

**Comment by jquense** [comment]
I think that distinction makes sense to me. It can be a point of confusion to not treat Date and Decimal as "custom" explicitly, especially if you do looking for more general GQL documentation about them and are confused why you can't find stuff.  I think carrying over that explicitness in the printer is a good thing, especially for interop with none C# consumers who may need to know what additions are required to consume a schema (a pie in the sky sort of cases)

**Comment by joemcbride** [comment]
Sounds good to me.  This should be a fairly easy change, most of the work being updating tests.

@antmdvs Care to make a PR for this?  Just need to [delete these lines](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaPrinter.cs#L25-L26) and update tests.

**Comment by antmdvs** [comment]
Happy to do it! Just need to find some time.
