### ISSUE TITLE
EnumerationGraphType serialization issue

### ISSUE THREAD

**Issue by arianmotamedi** [graphql-dotnet/graphql-dotnet#379]
Hi Everyone, 
I'm seeing a really weird issue with my enum values being turned into all uppercase when returned as part of the query. For example let's say I have an enum called "MyEnum" with members "Foo", "Bar", and "FooBar". I register the field like the following:

`Field(x => x.MyProperty, true, typeof(EnumerationGraphType<MyEnum>));`

Querying `myProperty` returns FOO, BAR, FOO_BAR respectively. Any ideas why this is the case?

**Comment by joemcbride** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/EnumerationGraphType.cs#L82

EnumerationGraphType<T> does a ToUppercase().

**Comment by arianmotamedi** [comment]
Hmm so how should I get around that? It doesn't seem like StringGraphType works for enums. Why does it do a .ToUpperCase() anyways? I'm curious now :D

**Comment by joemcbride** [comment]
All uppercase is idiomatic GraphQL/JavaScript.  http://graphql.org/learn/schema/#enumeration-types

* Use EnumerationGraphType instead (the base class) and add the values manually
* Copy the code and change that one line (a little easier)
* Decide to be a hipster and stick with uppercase (easiest!) 😄

**Comment by arianmotamedi** [comment]
Thanks Joe. I'll copy the code and change that line. I'd personally be ok with being a hipster, but unfortunately I can't force that on our consumers who have already coded against these enum values 😉

**Comment by arianmotamedi** [comment]
Feel free to close the issue 😄

**Comment by joemcbride** [comment]
:+1:
