### ISSUE TITLE
Parsing queries from Relay

### ISSUE THREAD

**Issue by sammosampson** [graphql-dotnet/graphql-dotnet#38]
Hi 
POSTS from Relay come in the form of json i.e wrapped like this:

*{"query":"query xxxx","variables":{}}* 
e.g *{"query":"query RouteQuery { viewer { routes{ createdOn, machine } } }","variables":{}}*

In order for this to work with graphql.net you need to remove the starting *{"query":"* and ending *","variables":{}}* and pass that as the query.

I have tried parsing the whole thing with a NewtonSoft.JObject but it fails, which has left me with the only option of using string.Replace to remove them. Is there a better way anyone knows of that will do this?

**Comment by nmaait** [comment]
I'm using relay without any issues. What is the object you are passing to your controller? Have you tried annotating the properties? 

Mine looks like

```c#
[DataContract]
public class GraphQLQuery 
{
    [DataContract(Name="query")]
    public string Query { get; set; }
    [DataContract(Name="variables")]
    public Dictionary<string,string> Variables { get; set; }
}
```

**Comment by sammosampson** [comment]
I am not using a controller, I am reading the request (directly) to string
and passing that to the graphql executor

**Comment by joemcbride** [comment]
The following should work for you:

```
public class GraphQLQuery
{
    public string Query { get; set; }
    public Dictionary<string, string> Variables { get; set; }
}

var request =
    "{\"query\":\"query RouteQuery { viewer { routes{ createdOn, machine } } }\",\"variables\":{\"one\":\"two\"}}";
var query = JsonConvert.DeserializeObject<GraphQLQuery>(request);
```

**Comment by sammosampson** [comment]
Thanks again jo

**Comment by joemcbride** [comment]
Closing this, feel free to re-open if you are still having an issue.

**Comment by mattferrin** [comment]
We should copy paste someone's Relay compatible MVC and/or Web API code into the readme at some point. My MVC isn't working because I assumed arguments would be embedded in my mutation query. I'm still not sure how to pass a relay mutation to the async executer.

**Comment by mattferrin** [comment]
(I do see that the Inputs parameter inherits from Dictionary<string,object> now.) I'm going to assume "Inputs" and "Arguments" are synonymous and move ahead.

**Comment by joemcbride** [comment]
@mattferrin Inputs, or Input values, and Arguments are different.

> Field and directive arguments accept input values of various literal primitives; input values can be scalars, enumeration values, lists, or input objects.

> If not defined as constant (for example, in DefaultValue), input values can be specified as a variable. List and inputs objects may also contain variables (unless defined to be constant).

In this case, `id` is an Argument, which has an Input value of type `StringValue`.

```
 query {
    human(id: ""1"") {
      name
      homePlanet
    }
 }
```

In this case, `id` is still an Argument and `idValue` is a variable which also has an Input value type of `StringValue`.
```
query getHuman($idValue: String) {
    human(id: $idValue) {
      name
      homePlanet
    }
 }
```

You can use the [`ToInputs`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L15) to convert json to an Inputs class.

Using the sample `GraphQLController` using `ToInputs` should look something like:

```
public class GraphQLController : ApiController
{
    private readonly ISimpleContainer _container;
    private readonly ISchema _schema;
    private readonly IDocumentExecuter _executer;

    public GraphQLController()
    {
        _executer = new DocumentExecuter();

        _container = new SimpleContainer();
        _container.Singleton(new StarWarsData());
        _container.Register<StarWarsQuery>();
        _container.Register<HumanType>();
        _container.Register<DroidType>();
        _container.Register<CharacterInterface>();
        _container.Singleton(() => new StarWarsSchema(type => (GraphType) _container.Get(type)));

        _schema = _container.Get<StarWarsSchema>();
    }

    public async Task<ExecutionResult> Post(GraphQLQuery query)
    {
        var inputs = query.Variables.ToInputs();
        return await Execute(_schema, null, query.Query, null, inputs);
    }

    public async Task<ExecutionResult> Execute(
      ISchema schema,
      object rootObject,
      string query,
      string operationName = null,
      Inputs inputs = null)
    {
        return await _executer.ExecuteAsync(schema, rootObject, query, operationName);
    }
}

public class GraphQLQuery
{
    public string Query { get; set; }
    public string Variables { get; set; }
}
```

Hope that helps, here's the official spec links:

http://facebook.github.io/graphql/#sec-Language.Arguments
http://facebook.github.io/graphql/#sec-Input-Values
http://facebook.github.io/graphql/#sec-Language.Variables

**Comment by mattferrin** [comment]
I really do appreciate the awesome help. Your simple container gave me pause yesterday evening, but your code looks really great. Thanks. (Beginning again now.)

**Comment by mattferrin** [comment]
I am having a little trouble with this because Relay does not send "variables" as a string, but as JSON without double quotes around it. My "Variables" property is always null no matter what I do.

**Comment by mattferrin** [comment]
My finally DefaultNetworkLayer compatible solution:
```csharp
string request;
Request.InputStream.Position = 0;
using (Stream receiveStream = Request.InputStream)
{
     using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
     {
         request = readStream.ReadToEnd();
     }
}
GraphQLQuery parsed = JsonConvert.DeserializeObject<GraphQLQuery>(request);
Inputs inputs = JsonConvert.SerializeObject(parsed.variables).ToInputs();
```
```csharp
public class GraphQLQuery
{
    public string query { get; set; }
    public object variables { get; set; }
}
```
