### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wakuflair** [graphql-dotnet/graphql-dotnet#3800]
## Description

The objects created during a GraphQL request never get released.

See the example query:

``` csharp
public class MyQuery : ObjectGraphType
{
    public MyQuery()
    {
        Field<ListGraphType<AutoRegisteringObjectGraphType<Person>>, List<Person>>("getPeople")
            .Resolve(Resolve!)
            ;
    }

    private List<Person> Resolve(IResolveFieldContext<object> arg)
    {
        var people = new List<Person>();
        for (int i = 0; i < 10000; i++)
        {
           people.Add(new Person{Name = $"Person{i}", Age = i}); 
        }

        return people;
    }
}

public class Person
{
    public string Name { get; set; }
    public int Age { get; set; }
}
```

I just created 10000 person instances (Of course, in my real scenario, the instances are returned from business services), and they are serialize to JSON by using `System.Text.Json`.

All the lifetimes are singleton:

``` csharp
builder.Services.AddSingleton<MyQuery>();
builder.Services.AddSingleton<ISchema, MySchema>();
```

After the request finished, these instances are supposed to be disposed, but what I observed is the memory usage is keeping increase. 

### Steps to reproduce

1. Clone the minimum reproduce project [here](https://github.com/wakuflair/GraphQLMemory)
2. Build and Run
3. Execute `getPeople` API:

``` graphql
query{
  getPeople{
    name,
    age
  }
}
```
4. Observe memory usage

### Expected result

The memory usage should be stable.

### Actual result

Memory keeps increasing and never get down

### Environment

* Windows 10 x64
* .NET 7.0

**Comment by wakuflair** [comment]
**UPDATE**

I used DotNetMemory to do a rough analysis, it may related to the `InstrumentFieldMiddleware`.

**Comment by gao-artur** [comment]
From my tests, there are no referenced `Person` objects in the memory after the GC runs:
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/4518483/611dcbd9-8c49-4c1b-a06e-6a94e34126bc)
The memory is mainly occupied by the array pools. The GraphQL holds only a small fracture of memory
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/4518483/d099904f-7dff-49d1-b46b-4110bb95908a)
And if you Force GC in the dotMemory multiple times, the memory consumption is back to normal
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/4518483/1292c4f2-cfb6-4af6-bac7-c6bd79c7ae54)

**Comment by wakuflair** [comment]
Thanks, after force GC, I can also see the memory down.
