### ISSUE TITLE
Method is missing from StringExtensions.cs in NuGet package.

### ISSUE THREAD

**Issue by shenbomo** [graphql-dotnet/graphql-dotnet#382]
It seems like the below extension method is missing from NuGet package dll (version 0.17.1.727 for both 45 and 47), but it exists in the source code. Any reason it never made it to the release? Will it be included in the next release?
``
public static Inputs ToInputs(this JObject obj){...}
``

Thank you very much!

**Comment by joemcbride** [comment]
The commit with that code was added after the last release.  It was added with the mutation example.  https://github.com/graphql-dotnet/graphql-dotnet/releases Shows commits to master after the release.  It will be included in the next release.

**Comment by shenbomo** [comment]
Thank you so much for the fast response and clarifications, I am closing the issue.
