### ISSUE TITLE
Deprecated input fields break the schema in 7.4.0

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/graphql-dotnet#3825]
Related issue #3658.

I'm upgrading from 7.3.0 to 7.7.1.
We have a few input types with all fields marked as deprecated. With a new version, I'm getting the following error even when `schema.Features.DeprecationOfInputValues = false;`

> {
>   "error": "Invalid schema Error:\nInput Object type ContentRecordsQueryParams must define one or more fields."
> }

With this config key set to `false` (default), I expect the field depreciation will be ignored, just like it was in the older version, but instead, the field is deprecated and not returned from the introspection query and breaks previously valid graph type.

**Comment by gao-artur** [comment]
As a workaround, I'm currently removing the depreciation reason from the input fields with the schema visitor:
```c#
internal class InputFieldsUnDeprecationVisitor : BaseSchemaNodeVisitor
{
    public override void VisitInputObjectFieldDefinition(FieldType field, IInputObjectGraphType type, ISchema schema)
    {
        field.DeprecationReason = null;
    }
}
```

**Comment by Shane32** [comment]
So should we change the code so that it acts as though it was not deprecated when the feature is off?

**Comment by gao-artur** [comment]
Yes, I believe so. Moreover [migration notes](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/migrations/migration7.md#12-allow-deprecation-of-input-values) say

> Since this feature may be potentially breaking for your app, clients or tooling it was done as opt-in. Either set schema.Features.DeprecationOfInputValues = true; or call schema.EnableExperimentalIntrospectionFeatures() method before initializing a schema.

This flag should fully disable this feature.
