### ISSUE TITLE
[Question]How to do parameters in sub objects?

### ISSUE THREAD

**Issue by David-BOG** [graphql-dotnet/graphql-dotnet#383]
Hello, i have a question:
I'm trying to achieve something like this:
```
query  {
  accounts {
    accountName
    accountNumber
    status
    accountDescription
    accountPayments(first: 10 offset: 0){
     amount
     paymentDate
    }
  }
}
```

here in accounts query i have property of type List and I need to apply some sort of paging to that propery
**accountPayments(first: 10 offset: 0){**
....
}
How can it be done?

thanks in advance

**Comment by joemcbride** [comment]
http://graphql-dotnet.github.io/graphql-dotnet/getting-started#arguments
http://graphql-dotnet.github.io/graphql-dotnet/getting-started#variables
http://graphql.org/learn/queries/#variables

**Comment by David-BOG** [comment]
Arguments an variables work for main query AFAIK, i need to apply them to one of the fields

**Comment by joemcbride** [comment]
You can use variables anywhere within the Query.  You can add arguments to any field.

**Comment by David-BOG** [comment]
How can i add them to field? 
I resolve this property on main Type like this:
 Field(x => x.AccountPayments, nullable: true, type: typeof(ListGraphType<AccountPaymentsType>)).Resolve(context => context.Source.AccountPayments)

if i just add  accountPayments(first: 10 offset: 0) arguments in  graphiql expplorer, query fails

**Comment by joemcbride** [comment]
```graphql
query AccountList($first: Int!, $offset: Int!) {
  accounts {
    accountName
    accountNumber
    status
    accountDescription
    accountPayments(first: $first, offset: $offset){
     amount
     paymentDate
    }
  }
}
```

You have to add arguments to the field as is shown in the documentation.

```csharp
Field<ListGraphType<AccountPaymentsType>>(
      "accountPayments",
      arguments: new QueryArguments(
        new QueryArgument<IntGraphType> { Name = "first" },
        new QueryArgument<IntGraphType> { Name = "offset" }
      ),
      resolve: context =>
      {
        var first = context.GetArgument<int>("first");
        var offset = context.GetArgument<int>("offset");
        var source = (MyClass)context.Source;
        return source.AccountPayments.Skip(offset).Take(first);
      }
    );
```

**Comment by David-BOG** [comment]
```
accountPayments(first: $first, offset: $offset){
     amount
     paymentDate
    }
```
I did it this way and it works:

```
 Field(x => x.AccountPayments, nullable: true, type: typeof(ListGraphType<AccountPaymentsType>))
  .Resolve(context => context.Source.AccountPayments).Argument<IntGraphType> ("first", "").Argument<IntGraphType>("offset", "");
```
and retrieve values like this
```
 var first = c.Variables.ValueFor("first");
var offset = c.Variables.ValueFor("offset");
```

**Comment by David-BOG** [comment]
Ok doing like above, ii set arguments to my field, but when I try to retrieve values like this"
```
 resolve: context =>
                    {
                        var first = c.GetArgument<int>("first");
                        var offset= c.GetArgument<int>("offset");
}
```
values are 0
is that a bug or i'm doing it wrong?

**Comment by joemcbride** [comment]
Are you sending the variables in the http request as shown here?

http://graphql-dotnet.github.io/graphql-dotnet/getting-started#variables

**Comment by David-BOG** [comment]
yes, like that
anyway i figured all out, I add Field with resolver in constructor of AccountType Class and all works
thanks for your support
