### ISSUE TITLE
Intermittent failure with NewtonsoftJson test

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3837]
Intermittent failure with GraphQL.Tests.Execution.InputConversionNewtonsoftJsonTests.can_convert_json_to_input_object_with_custom_converter

https://github.com/graphql-dotnet/graphql-dotnet/actions/runs/7227876411/job/19696340154?pr=3833

**Comment by gao-artur** [comment]
How exactly is the serializer selected in these tests? The `InputConversionSystemTextJsonTests` and `InputConversionNewtonsoftJsonTests` look identically and use the same `JsonStringExtensions.ToInputs` implementation. Is it possible they both use STJ?

**Comment by Shane32** [comment]
No idea.

I know that @sungam3r wrote `GraphQLSerializersTestData.cs` but I don't see how that impacts those tests.

It certainly is possible.  I'd probably step through with the debugger to see.

**Comment by gao-artur** [comment]
I think it was broken in #2831
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/4518483/80e71f52-0998-4ae5-a00b-74cabbb8fe6e)

**Comment by Shane32** [comment]
Makes sense.

**Comment by Shane32** [comment]
(whoops!)

**Comment by gao-artur** [comment]
This may happen if these classes run concurrently because `ValueConverter` is static.

**Comment by Shane32** [comment]
We can fix that with `[Collection("StaticTests")]` then
