### ISSUE TITLE
Automatically defining type fields

### ISSUE THREAD

**Issue by Giorgi** [graphql-dotnet/graphql-dotnet#384]
When defining a new type we need to call `Field` method for every property to define fields. In most of the cases we can avoid repeating these calls by adding a base class which uses reflection to automatically register fields using reflection.  If you think this should be included in the library I am happy to provide a PR.

**Comment by joemcbride** [comment]
This is on purpose since your GraphQL api may not match your internal api.  I wouldn't mind adding a class that inherited from `ObjectGraphType<T>` that did this though.  Tough part will be what the name should be. 😆

**Comment by MFFoX** [comment]
+1 from me so long as it's optional. A couple of quick thoughts:

How would it work for complex members? Would/should you be able to control the reflection depth? What about circular navigational properties?

**Comment by Giorgi** [comment]
It won't work for complex members at least in the beginning. If you need to
register those too you will have to do it manually because you will
probably want to provide customer resolver.

**Comment by Giorgi** [comment]
@MFFoX I created a pull request for this issue. See #386

**Comment by joemcbride** [comment]
Closing as we merged the PR.
