### ISSUE TITLE
Subscription for load balancer round robin.

### ISSUE THREAD

**Issue by vansangnguyen1998** [graphql-dotnet/graphql-dotnet#3846]
I have implement subscription with dotnet 6 and graphql verion 7.

I have problem about the load balancer with round robin on production.
I have 2 instance to load balancer, when user 1 subscription into server 1. 
After that time have request call to server 2, it is not make senses with subscription i am expecting.

I have research with web socket have the adapter for socket. https://socket.io/docs/v4/redis-adapter/#common-questions

I am not sure that graphql dotnet how to implement with my case.
Best regards,

**Comment by Shane32** [comment]
GraphQL.NET does not handle the mechanism for distributing notifications across both your servers. You will need to implement this layer yourself, probably using Redis or something similar. Since each GraphQL subscription may request different fields, this may prove challenging depending on your schema and the amount of database hits you want to deduplicate. 

You may wish to have a single server dedicated to subscription requests to simplify this setup. It would probably be configured at a different endpoint than your query or mutation requests in that case. Then each of your load balanced servers need only the subscription server of any events that should be broadcast.

**Comment by vansangnguyen1998** [comment]
> GraphQL.NET does not handle the mechanism for distributing notifications across both your servers. You will need to implement this layer yourself, probably using Redis or something similar. Since each GraphQL subscription may request different fields, this may prove challenging depending on your schema and the amount of database hits you want to deduplicate.
> 
> You may wish to have a single server dedicated to subscription requests to simplify this setup. It would probably be configured at a different endpoint than your query or mutation requests in that case. Then each of your load balanced servers need only notify the subscription server of any events that should be broadcast.

Do you have any example or docs config Redis for subscription GraphQL-Dotnet?

**Comment by Shane32** [comment]
No this is outside the scope of GraphQL.NET.  GraphQL.NET requires an `IObservable` that is fed a sequence of events, and provides documentation for resolving those data events into GraphQL responses.  But we do not have documentation for how to distribute an event sequence across servers.

ChatGPT suggests using StackExchange.Redis to perform this task.  ChatGPT has provided the outline listed below.  I suggest asking ChatGPT for further information and/or sample code, or reading the official StackExchange.Redis documentation.


# Using StackExchange.Redis with IObservable in .NET

## Overview
This document provides an overview of how to use StackExchange.Redis to collect events from multiple servers and make them available in an `IObservable` sequence to multiple servers.

## Steps

### 1. Setting Up StackExchange.Redis
- Install the StackExchange.Redis library via NuGet package manager.

### 2. Establishing a Redis Connection
- Create a `ConnectionMultiplexer`. It's used for communication with the Redis server.
- Configure it to connect to your Redis server.

    ```csharp
    var multiplexer = ConnectionMultiplexer.Connect("redis-server-hostname");
    ```

### 3. Publishing Events to Redis
- Use `IDatabase` from `ConnectionMultiplexer` to publish messages.
- Serialize event data to JSON and publish it to a Redis channel.

    ```csharp
    IDatabase db = multiplexer.GetDatabase();
    string message = JsonConvert.SerializeObject(yourEventObject);
    db.Publish("channelName", message);
    ```

### 4. Subscribing to Redis Channels
- Use `ISubscriber` from `ConnectionMultiplexer` to subscribe to channels.
- Handle incoming messages in the subscription callback.

    ```csharp
    ISubscriber sub = multiplexer.GetSubscriber();
    sub.Subscribe("channelName", (channel, message) => {
        // Handle the message
    });
    ```

### 5. Integrating with IObservable
- Create an `IObservable` sequence to listen for messages on the subscribed channel.

### 6. Deserializing and Processing Events
- Deserialize received messages back to event objects.
- Process these events as required.

### 7. Distributing Events
- Distribute events to `IObservable` subscribers on the server.

### 8. Error Handling and Resilience
- Implement error handling for connection failures or message issues.
- Consider retry mechanisms or fallback strategies.

### 9. Monitoring and Optimization
- Monitor and optimize Redis interactions for performance.

## Conclusion
This guide outlines a basic structure for using StackExchange.Redis with `IObservable` in .NET. Adapt as necessary for your application's requirements.

**Comment by Shane32** [comment]
Please let us know if there's any other questions you may have
