### ISSUE TITLE
Http request for mutation variables

### ISSUE THREAD

**Issue by Stoom** [graphql-dotnet/graphql-dotnet#385]
Hi, I'm trying to figure out the json body for a mutation request with variables.  Everything I've tried results in an error:  

`Variable '$app' is invalid. Unable to parse input as a 'ApplicationInput' type. Did you provide a List or Scalar value accidentally?`

Here is my json:
```graphql
{
	"query": "mutation($app: ApplicationInput!) { createApplication (application: $app) }",
	"variables": {
		"app": "{ApplicationInput { name: \"Test App\" }}"
	}
}
```

If I inline everything it works fine.

**Comment by joemcbride** [comment]
I'm guessing your schema looks something like this:

```graphql
input ApplicationInput {
  name: String
}

type Mutation {
  createApplication(application: ApplicationInput!) : Something
}
```

Check the value of the `app` variable.  It is the `string` value `{ApplicationInput { name: "Test App" }}`.  You want to actually send a JSON object vs. just a `string`.

```json
"app": {
  "name": "Test App"
}
```

**Comment by Stoom** [comment]
This is still causing the error:

```graphql
{
	"errors": [
		{
			"message": "Variable '$app' is invalid. Unable to parse input as a 'ApplicationInput' type. Did you provide a List or Scalar value accidentally?"
		}
	]
}
```

```graphql
{
	"query": "mutation($app: ApplicationInput!) { createApplication (application: $app) }",
	"variables": {
		"app": {
			"name": "Test App"
		}
	}
}
```

Here is the schema introspective

```graphql
{
    "name": "Mutation",
    "kind": "OBJECT",
    "fields": [
        {
            "name": "createApplication",
            "type": {
                "name": "String",
                "fields": null,
                "inputFields": null
            }
        },
        {
            "name": "removeApplication",
            "type": null
        }
    ],
    "inputFields": null
},
{
    "name": "ApplicationInput",
    "kind": "INPUT_OBJECT",
    "fields": null,
    "inputFields": [
        {
            "name": "name",
            "defaultValue": null
        },
        {
            "name": "isDefault",
            "defaultValue": null
        }
    ]
},
```

**Comment by joemcbride** [comment]
How are you passing the variables to the execution engine?  Are you using the `ToInputs` extension method?

[Official Docs](http://graphql-dotnet.github.io/graphql-dotnet/getting-started#variables)
[ASP .NET Core Example](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQLCore/GraphQLMiddleware.cs#L64)
[ASP .NET Example](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Controllers/GraphQLController.cs#L47)

**Comment by joemcbride** [comment]
My only other suggestion is to ensure that the `app` variable does actually exist as an `IDictionary<string, object>` in the `Inputs` class when passing it to the engine.

It may not be super intuitive, but this actually removes all validation rules and just adds your single rule.  You most likely want to add `DocumentValidator.CoreRules()` to that list.  Perhaps you get a different error when you do?

```csharp
                x.ValidationRules = new[]
                {
                    new AuthorizationValidationRule()
                };
```

**Comment by Stoom** [comment]
I've fixed the validation rules, but same error.  Here is a screenshot of the inputs after the `ToInput()`
![image](https://user-images.githubusercontent.com/5356206/28991462-ab7da748-794d-11e7-83c0-b3128080d160.png)

**Comment by joemcbride** [comment]
Perhaps the problem is non-null vs. null.  In your query you are defining a non-null, though in your definition it is nullable.

**Comment by Stoom** [comment]
If I make the argument nullable I get this error
```graphql
{
	"errors": [
		{
			"message": "Variable \"$app\" of type \"ApplicationInput\" used in position expecting type \"ApplicationInput!\".",
			"locations": [
				{
					"line": 1,
					"column": 10
				},
				{
					"line": 1,
					"column": 68
				}
			]
		}
	]
}
```

Could it be something about the default value of `isDefault` is null.  It is marked as a nullable field in the input type.

**Comment by Stoom** [comment]
Everything I try keeps coming back to that error.  Is there a unit test that exercises custom input types that I can reference?

**Comment by joemcbride** [comment]
This is where that error is: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L674

Only way to get that error is if the variable is null.

**Comment by Stoom** [comment]
Not quite sure whats going on.  I uninstalled the nuget package and included the source directly and everything worked.  I then removed that and installed the nuget package and everything is working...

I'm good with closing this, but really don't know what happened.

**Comment by joemcbride** [comment]
If you're using VS2017, I wouldn't be surprised.  I've had some funny things happen myself...
