### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#388]
It would be nice to have better documentation with executable code samples that compare to [graphql.org](http://graphql.org)

Perhaps a [gatsbyjs](http://gatsbyjs.org) site?

**Comment by SimonCropp** [comment]
There is also 
https://readthedocs.org/

**Comment by SimonCropp** [comment]
As for compilable/runnable snippets i created this 
https://github.com/SimonCropp/MarkdownSnippets. Happy to help apply it, if u think it would make things easier

**Comment by pekkah** [comment]
For my purposes I created this https://pekkah.github.io/tanka-docs-gen/beta/basics/1-usage.html. For c# it uses Roslyn to find the snippet to include and for others it uses the docfx extensions for markdig. Here's a something generated using it https://pekkah.github.io/tanka-graphql/beta/.

**Comment by joemcbride** [comment]
This is done with the gatsby site, so I’ll close this.
