### ISSUE TITLE
How add the UnhandledExceptionDelegate in the startup?

### ISSUE THREAD

**Issue by julienFlexsoft** [graphql-dotnet/graphql-dotnet#3881]
I am using version 7.2.2.

Right now I am using a custom GraphQLMiddleware. It looks like this:
```csharp
var result = await _executer.ExecuteAsync(options =>
{
    options.Schema = schema;
    options.Query = graphQLRequest.Query;
    options.OperationName = graphQLRequest.OperationName;
    options.Variables = graphQLRequest.Variables;
    options.UserContext = GenerateGraphQLUserContext(context);
    options.User = context.User;
    options.EnableMetrics = enableMetrics;
    options.RequestServices = context.RequestServices;
    options.CancellationToken = context.RequestAborted;
    options.Listeners.Add(dataLoaderDocumentListener);
    options.ThrowOnUnhandledException = false;
    options.ValidationRules = context.RequestServices.GetServices<IValidationRule>().Concat(DocumentValidator.CoreRules);
    options.UnhandledExceptionDelegate = ctx =>
    {
        return HandleErrors(context, ctx, graphQLRequest, requestContext, envHelper, logger);
    };
});
private GraphQLUserContext GenerateGraphQLUserContext(HttpContext context)
{
    GraphQLUserContext result = new()
    {
        { "User", context.User },
        { "CustomKey", "" },
        { "CustomKey1", "" }
    };
    result.User = context.User;
    return result;
}
private Task HandleErrors(HttpContext context, UnhandledExceptionContext exceptionCtx, GraphQLRequest graphQLRequest,
    IRequestContext requestContext, IEnvHelper env, ILogger<GraphQLMiddleware> logger)
{
     // Custom logic here (ex: special logging, metrics)
}
```

and I am changing it to this:
```csharp
services.AddGraphQL(x => x
    .AddUserContextBuilder(context => {
        GraphQLUserContext result = new()
        {
            { "User", context.User },
            { "CustomKey", "" },
            { "CustomKey1", "" }
        };
        result.User = context.User;
        return result;
    })
);
```
But I am wondering how I can get my UnhandledExceptionDelegate logic in there?
I am switching away from the middleware because someone here told me that this was the preferred way to initialize GraphQL, mainly because it will require less work when updating later. Is this still accurate?
For example, the options.ValidationRules line caused some issues when updating GraphQL last time, which wouldn't have been an issue if I used the startup method.

**Comment by Shane32** [comment]
```cs
        builder.ConfigureExecutionOptions(o =>
        {
            o.UnhandledExceptionDelegate = e =>
            {
                var serviceProvider = o.RequestServices!;
                var httpContext = serviceProvider.GetRequiredService<IHttpContextAccessor>().HttpContext;
                var request = new GraphQLRequest { Query = o.Query, Extensions = o.Extensions, OperationName = o.OperationName, Variables = o.Variables };
                IRequestContext requestContext; // don't know what this is
                var env = serviceProvider.GetRequiredService<IEnvHelper>();
                var logger = serviceProvider.GetRequiredService<ILogger<GraphQLMiddleware>>();
                return HandleErrors(httpContext, e, request, env, logger);
            };
        });
```

**Comment by Shane32** [comment]
Sorry no dedicated extension method for that yet.

**Comment by Shane32** [comment]
> I am switching away from the middleware because someone here told me that this was the preferred way to initialize GraphQL, mainly because it will require less work when updating later. Is this still accurate?

Yes; by using the `IGraphQLBuilder` interface to configure GraphQL, we can abstract the configuration away from the implementation.  So if the implementation changes, the builder methods can remain the same, reducing or eliminating the amount of refactoring required across versions.

Also, the GraphQL.Server project has a highly-configurable ASP.Net Core middleware implementation based on the GraphQL over HTTP standard being developed, so you should not need to write your own middleware.

**Comment by Shane32** [comment]
See #3882 @julienFlexsoft .

For example, if in the future we decide to make the handler be an `IUnhandledExceptionHandler` interface instead of a delegate, the option would change within `ExecutionOptions`, but the builder methods would not change.
