### ISSUE TITLE
 new QueryArgument<ListGraphType<StringGraphType>> not working

### ISSUE THREAD

**Issue by mahald** [graphql-dotnet/graphql-dotnet#389]
Hi,

I've got the Problem that String Arrays aren't working as query argument.

Here the definition: 
` new QueryArgument<ListGraphType<StringGraphType>>`

While IdGraphType arrays are working:
` new QueryArgument<ListGraphType<IdGraphType>>`

on String i get the error: `Cannot convert value to AST: {serialized}` 

i investigated the issue and found that `Cannot convert value to AST` only is at one location in the source.

while debugging i noticed that the ListType was found, a callto: `var values = list.Map(item => AstFromValue(item, schema, itemType));` on string however this call then ends with `throw new ExecutionError($"Cannot convert value to AST:  ....` because the type of serialized seems to be `Newtonsoft.Json.Linq.JValue` 

thus i added new check just before the error message like this:

```
            if (serialized is Newtonsoft.Json.Linq.JValue)
            {
                if (type is EnumerationGraphType)
                {
                    return new EnumValue(serialized.ToString());
                }

                if (type is StringGraphType)
                {
                    return new StringValue(serialized.ToString());
                }
            }

            throw new ExecutionError($"Cannot convert value to AST: {serialized} serializedType:" + serialized.GetType().ToString() + ", type: " + type.ToString());
```

Then it works. But i think this is not the proper way to fix it. Or is it ? Any ideas/hints ?

**Comment by joemcbride** [comment]
I'm guessing you are using variables?  The engine expects the values to be converted from JSON.NET types before execution.

See the [Variables](http://graphql-dotnet.github.io/graphql-dotnet/getting-started#variables) section in the docs about converting from json/JObject to the Inputs type.

**Comment by mahald** [comment]
The GraphQL request is lookin like this: 

```
mutation permissionGroupUpdate($id: ID!, $permissions: [String]) {
  permissionGroupUpdate(id: $id, permissions: $permissions) {
    id
    name
    permissions {
      id
    }
  }
}
```

The Variables: 

```
{
  "id": "7a2883e1-b113-4c45-9ffd-7c3fde4d6254", 
  "permissions": ["USER_PROFILE_R","USER_PROFILE_R"]
}
```
Here is the way i execute it: 

```
        private async Task<ExecutionResult> ExecuteAsync(HttpContext context)
        {
            string requestBodyText;
            using (var streamReader = new StreamReader(context.Request.Body))
            {
                requestBodyText = await streamReader.ReadToEndAsync().ConfigureAwait(true);
            }
            var graphqlRequest = JsonConvert.DeserializeObject<GraphQLRequest>(requestBodyText);

            return await new DocumentExecuter().ExecuteAsync(schema: schema, root: null , query: graphqlRequest.Query, operationName: graphqlRequest.OperationName,
                inputs: graphqlRequest.Variables, userContext: context).ConfigureAwait(true);
        }
```

<-- Is this not ok ?

**Comment by mahald** [comment]
i can not finde the ToInputs() function on Variables

**Comment by joemcbride** [comment]
What type is `GraphQLRequest.Variables`?  `ToInputs` takes a `String` (raw json) or `JObject`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/d7264a9ad3b0be88638a72ff4e4cc318eae41ef0/src/GraphQL/StringExtensions.cs#L52
https://github.com/graphql-dotnet/graphql-dotnet/blob/d7264a9ad3b0be88638a72ff4e4cc318eae41ef0/src/GraphQL/StringExtensions.cs#L60

**Comment by joemcbride** [comment]
I would also suggest to use the `ExecuteAsync(_=>...)` function as the one that takes individual parameters is going to be deprecated here pretty soon...

**Comment by mahald** [comment]
Ok, thanks for the help, i had to change:
`JsonConvert.DeserializeObject<GraphQLRequest>(requestBodyText);`
to:
`JsonConvert.DeserializeObject<JObject>(requestBodyText);`

The entire function now looks as follows:
```
        private async Task<ExecutionResult> ExecuteAsync(HttpContext context)
        {
            string requestBodyText;
            using (var streamReader = new StreamReader(context.Request.Body))
            {
                requestBodyText = await streamReader.ReadToEndAsync().ConfigureAwait(true);
            }

            var graphqlRequest = JsonConvert.DeserializeObject<JObject>(requestBodyText);

            var Variables = graphqlRequest["variables"]?.ToInputs();

            var result = await new DocumentExecuter().ExecuteAsync(_ =>
            {
                _.Schema = schema;
                _.Root = null;
                _.Query = graphqlRequest["query"].ToString();
                _.Inputs = Variables;
                _.OperationName = graphqlRequest["operationName"].ToString();
                _.UserContext = context;
            }).ConfigureAwait(false);

            return result;
        }
```

i had to add following code to ur lib:

```
        public static Inputs ToInputs(this JToken obj)
        {
            var variables = obj?.GetValue() as Dictionary<string, object>
                            ?? new Dictionary<string, object>();
            return new Inputs(variables);
        }
```

as `graphqlRequest["variables"]` is of type `Jtoken`

**Comment by joemcbride** [comment]
You can perhaps change your `GraphQLRequest` to look like this to avoid some extra work:

https://github.com/graphql-dotnet/graphql-dotnet/blob/6c45e34805ec8aad99b83ee13f44d5006b4164b1/src/GraphQL.GraphiQLCore/GraphQLRequest.cs#L5-L10

My understanding is that a `JToken` is just a generic representation of a value.  So it could and should be a `JObject`.  So perhaps it would be better to update that extension method to be a `JToken` since it is just trying to cast the value.

**Comment by mahald** [comment]
Thanks a lot this solved it.

**Comment by GoaKoala** [comment]
Just a side note as it might help someone in the future. For the fix to work you need to have the latest nuget pkg of the GraphQl(currently 0.17.3). It might not work with older versions. (It doesn't work with 0.15.1.678)

**Comment by Lechus** [comment]
it is not in "GraphQL" Version="3.3.2"  ?
