### ISSUE TITLE
Relay Node Interface

### ISSUE THREAD

**Issue by rvlietstra** [graphql-dotnet/graphql-dotnet#39]
Hi.
Firstly thanks for a dotnet implementation of graphQL!

I'm trying to implement the relay node interface.

I have a UserType
```c#
public class UserType : ObjectGraphType
{
    public UserType(Entities db)
    {
        Name = "User";

        Field<NonNullGraphType<StringGraphType>>("id",
                resolve: context =>
                {
                    User o = (User)context.Source;
                    return Util.ToGlobalID(this.GetType(), o.Id);
                }
            );

        Interface<NodeInterface>();

        Field<StringGraphType>("Firstname");
        Field<StringGraphType>("Lastname");
    }
}
```

The UserType implements the NodeInterface
```c#
public NodeInterface(UserType userType)
{
    Name = "Node";
    Field<NonNullGraphType<StringGraphType>>("id");

    ResolveType = obj =>
    {                                
        if (obj is DataLayer.User)
            return userType;
        throw new Exception("Not handeling type: " + obj.GetType().Name);
    };

}
```

Relay then generates a query that look something like this
```
query User
{
  node(id:\"T3JnQ2F0ZWdvcnk=:MQ==\") {...__RelayQueryFragment1}
} 
fragment __RelayQueryFragment1 on User{id,Firstname} 
```

The result returned by grapql is 
```
{"data":{"node":{}}}
```

While investigating the issue I found what may or may not be the issue
[DocumentExecuter Line 587](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L587) does an equality test, the GetType().FullName of both variables on that line returns MyNamespace.UserType, yet fails to be equal.

So two questions:
1. Any idea of why the relay query fails ?
2. Do we still need to implement an "id" field if the interface defines it ?

Any other tips on how to get relay working would be awesome!

Thanks!

**Comment by joemcbride** [comment]
I haven't implemented Relay yet myself, though I have heard from others that they have.

>1 Any idea of why the relay query fails ?

Can't say without a bit more info.  There are tests that work with fragments, though it is certainly possible you found a bug.  Can you post your full schema?  Do you have a root query object with a `node` field?  Can you write a failing test in the core project?

>2 Do we still need to implement an "id" field if the interface defines it ?

Yes, just like in C# the interface defines what is available though not the implementation.  In the `ResolveType` func on the interface you are defining the "real" `GraphType` for GraphQL to use to get the data.

```
ResolveType = obj =>
    {                                
        if (obj is DataLayer.User)
            return userType;
        throw new Exception("Not handeling type: " + obj.GetType().Name);
    };
```

**Comment by rvlietstra** [comment]
Hi.
I changed the previously referenced equality check in DocumentExecuter to compare the type name instead of the two objects, for what ever reason they are not equal. I will write a test at some point, I could be using things wrong but at least this allows me to move on.

My node interface is now working.

**Comment by joemcbride** [comment]
Closing this.  Feel free to re-open or post a new issue if you can verify a bug.

**Comment by rvlietstra** [comment]
Just tested it and it seems to work!
Many thanks!
