### ISSUE TITLE
Multithreading and metrics 

### ISSUE THREAD

**Issue by landbolts** [graphql-dotnet/graphql-dotnet#390]
in src\GraphQL\Instrumentation\Metrics.cs

noticed that when there are multiple threads trying to add PerfRecord(s) to the _records generic List, we occasionally get an "Index out of bounds" error (since the generic list is not thread safe).
 
After changing: 
private readonly IList<PerfRecord> _records = new List<PerfRecord>();

to: 
private readonly ConcurrentBag<PerfRecord> _records = new ConcurrentBag<PerfRecord>();

the problem seems to go away. Additionally there doesn't seem to be a performance hit with this change, however not sure if this is the best approach.

**Comment by joemcbride** [comment]
I'm fairly sure that `ConcurrentBag<T>` doesn't keep a specific order, which the Metrics want.  Perhaps can change this to a `ICollection<T>` backed by a `ConcurrentStack<T>`.

**Comment by landbolts** [comment]
hi joe, thanks for the reply. ConcurrentBag is unordered, however I noticed that "AllRecords" property in  Metrics.cs is being sorted by its start time in milliseconds: 
public IEnumerable<PerfRecord> AllRecords => _records.OrderBy(x => x.Start).ToArray();
Is there a reason why the list would need to be ordered beforehand?

**Comment by pvsleeper** [comment]
We're also having some inconsistent failure around the metrics, but we're getting a NullReferenceExcepsion.

The exception's stacktrace look like this:
```at GraphQL.Instrumentation.Metrics.<>c.<get_AllRecords>b__7_0(PerfRecord x)\r\n   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)\r\n   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)\r\n   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at GraphQL.DocumentExecuter.<ExecuteAsync>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
.
.
.
.```

Looks like its on the `AllRecords` property and from what I can tell this will happen if an item in the _records list is null. Suspecting this some threadsafe issue....
