### ISSUE TITLE
How can I preserve the order of fields as given in variables?

### ISSUE THREAD

**Issue by mariusbancila** [graphql-dotnet/graphql-dotnet#3902]
I work on a system where the order of fields assignment (at least to some degree), when creating or updating, is important.

Let's say we need to create an order. We can have something like this:
```
order_create(values: [{
     customerNo: 10000,
     orderType: 2,
     orderPreferences: 0,
     transactionType :1
  }])
{
}
```
This is just an example but let's assume the order of these four fields matter. When someone writes a query like this I parse the field AST and get the values in the input in the order they were provided so I can make use of them in the user-given order.

However, someone can provide the entire object as a variable (showing here only the relevant parts):
```
order_create(values: $values)
{
}
```
```
{
   "values":[
   {
      "customerNo":10290,
      "orderType":2,	
      "orderPreferences":0,
      "transactionType":1,
   }]
} 
```
In this case, due to serialization somewhere within the framework, the order of these fields is changed. When I look at `ReadonlyResolveFieldContext.Arguments`, I have an array of key-value pairs, that looks like this:
```
{
   {"orderPreferences":0},
   {"orderType":2},	
   {"transactionType":1},
   {"customerNo":10290},
}
```
That is, the order of the fields as they were defined in the GraphQL input type. Let's say this is called `OrderInput` and its fields are in this order (although my types are generated dynamically, this static type shows the concept):
```
type OrderInput {
  orderPreferences: Int
  orderType: Int
  transactionType : Int
  customerNo : Int
}
```

My question is: is there a way I can change this serialization of `ExecutionOptions.Variables` to this array of `KeyValuePair` objects based on the order of the fields as they are found in the type definition? I'm also thinking of looking at the original `ExecutionOptions.Variables` (which I can store in the `UserContext`) while I'm evaluating `ReadonlyResolveFieldContext.Arguments`, but I'm not sure how I can rematch them.

**Comment by Shane32** [comment]
This is where the order is switched to the order of the fields as defined within the graph type:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionHelper.cs#L175

**Comment by Shane32** [comment]
As far as I'm aware, the order of the items in a `Dictionary<TKey, TValue>` is unspecified, and although we could rewrite `ExecutionHelper` to preserve the order of the items added to the dictionary, there is no guarantee that .NET will retain this order when storing it within the dictionary.  As such, I'm not inclined to rewrite the existing code.

See:
- https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.system-collections-idictionary-keys?view=net-8.0#remarks

**Comment by Shane32** [comment]
> I'm also thinking of looking at the original `ExecutionOptions.Variables` (which I can store in the `UserContext`) while I'm evaluating `ReadonlyResolveFieldContext.Arguments`, but I'm not sure how I can rematch them.

You'd probably have to rewrite ExecutionHelper.GetArguments and CoerceValue.  Keep in mind that these methods are changing a lot in v8 so you may need to rewrite them after v8 is released.

**Comment by mariusbancila** [comment]
Thanks for pointing to the significant bits of code. I will look into what I can do.
