### ISSUE TITLE
C# error exposed in error message

### ISSUE THREAD

**Issue by BottlecapDave** [graphql-dotnet/graphql-dotnet#3908]
## Description

We use this library in a production environment which recently had a pen test against it. One of the observations was that when an array was passed to a field resolver with a query parameter of type `int`, it exposed the following code-level error message with code 'INVALID_VALUE'.

```
Variable '$id' is invalid. Unable to convert 'System.Collections.Generic.List`1[System.Object]'
```

This information could then be used to determine the underlying codebase which could then be used for targeted attacks.

### Steps to reproduce

1. Have a field resolver where an input value is of type 'Int'
2. Execute a query against the field resolver using a tool like Insomnia, Postman or Curl where instead of an int an array is passed

```
{
  "operationName":"GetPlan",
  "variables":{"id": [1,2]},
  "query":"query GetPlan($id: Int!) { planById(id: $id) {id}}"
}
```

### Expected result

Any errors that could potentially expose C# level errors should be omitted, either always or via a config variable that can be set for production environments.

### Actual result

The following environment variable was exposed

```
Variable '$id' is invalid. Unable to convert 'System.Collections.Generic.List`1[System.Object]'
```

### Environment

.NET - 8
GraphQL.NET - 7.7.2
MacOS or Docker container

**Comment by BottlecapDave** [comment]
The `UnhandledExceptionDelegate` doesn't seem to be called in this situation with `ThrowOnUnhandledException` turned off. 

The error in question looks like it's raised at https://github.com/graphql-dotnet/graphql-dotnet/blob/49f24b574380f92f6c74f7963b8320167004438a/src/GraphQL/Validation/ValidationContext.cs#L311. My worry is there are other areas that aren't sanitised that could easily be missed.

**Comment by BottlecapDave** [comment]
It looks like this error in particular is occurring at https://github.com/graphql-dotnet/graphql-dotnet/blob/49f24b574380f92f6c74f7963b8320167004438a/src/GraphQL/Validation/ValidationContext.cs#L311

**Comment by Shane32** [comment]
This is actually an [input error](https://graphql-dotnet.github.io/docs/getting-started/errors/#input-errors), due to the fact that `IdGraphType` cannot parse a list.  See here:
- https://github.com/graphql-dotnet/graphql-dotnet/blob/49f24b574380f92f6c74f7963b8320167004438a/src/GraphQL/Types/Scalars/IdGraphType.cs#L47-L62

So `ParseValue` runs `ThrowValueConversionError`, which throws the exception you showed above.

The exception message should be updated so that `ToString` isn't called for unknown types such as arrays and objects.

**Comment by Shane32** [comment]
@BottlecapDave I looked into this further; you are correct, although `ParseValue` throws an error, `ValidationContext.cs:311` rethrows a generic error which should not contain C#-specific information.
