### ISSUE TITLE
Connection and Edges with instance types instead of generics

### ISSUE THREAD

**Issue by schlaup** [graphql-dotnet/graphql-dotnet#393]
I do not know the internals of GraphQL DotNet and changed the current implementation like this:

EdgeType.cs

```
using System;

namespace GraphQL.Types.Relay
{
    public class EdgeType<TTo> : EdgeType
        where TTo : IGraphType
    {
        public EdgeType()
            : base(typeof(TTo))
        {
        }
    }

    public class EdgeType : ObjectGraphType<object>
    {
        internal EdgeType(Type type)
            : this(type.GraphQLName())
        {
            Field(type, "node", "The item at the end of the edge");
        }

        public EdgeType(IGraphType resolvedType)
            : this(resolvedType.Name)
        {
            Field<GraphType>("node", "The item at the end of the edge")
                .ResolvedType = resolvedType;
        }

        private EdgeType(string name)
        {
            Name = string.Format("{0}Edge", name);
            Description = string.Format(
                "An edge in a connection from an object to another object of type `{0}`.",
                name);

            Field<NonNullGraphType<StringGraphType>>()
                .Name("cursor")
                .Description("A cursor for use in pagination");
        }
    }
}
```
ConnectionType:
```
using System;

namespace GraphQL.Types.Relay
{
    public class ConnectionType<TTo> : ConnectionType
        where TTo : IGraphType
    {
        public ConnectionType()
            : base(typeof(TTo))
        {
        }
    }

    public class ConnectionType : ObjectGraphType<object>
    {
        protected ConnectionType(Type type)
            : this(type.GraphQLName())
        {
                Type = type;

            Field<GraphType>("edges", "Information to aid in pagination.")
                .ResolvedType = new ListGraphType(new EdgeType(type));

            ItemsField = Field<GraphType>("items",
                    "A list of all of the objects returned in the connection. This is a convenience field provided " +
                    "for quickly exploring the API; rather than querying for \"{ edges { node } }\" when no edge data " +
                    "is needed, this field can be used instead. Note that when clients like Relay need to fetch " +
                    "the \"cursor\" field on the edge to enable efficient pagination, this shortcut cannot be used, " +
                    "and the full \"{ edges { node } } \" version should be used instead.");
        }

        public ConnectionType(IGraphType resolvedType)
            : this(resolvedType.Name)
        {
            ResolvedType = resolvedType;

            Field<GraphType>("edges", "Information to aid in pagination.")
                .ResolvedType = new ListGraphType(new EdgeType(resolvedType));

            Field<GraphType>("items",
                    "A list of all of the objects returned in the connection. This is a convenience field provided " +
                    "for quickly exploring the API; rather than querying for \"{ edges { node } }\" when no edge data " +
                    "is needed, this field can be used instead. Note that when clients like Relay need to fetch " +
                    "the \"cursor\" field on the edge to enable efficient pagination, this shortcut cannot be used, " +
                    "and the full \"{ edges { node } } \" version should be used instead.")
                .ResolvedType = new ListGraphType(resolvedType);
        }

        private ConnectionType(string name)
        {
            Name = string.Format("{0}Connection", name);
            Description = string.Format("A connection from an object to a list of objects of type `{0}`.",
                name);

            Field<IntGraphType>()
                .Name("totalCount")
                .Description(
                    "A count of the total number of objects in this connection, ignoring pagination. " +
                    "This allows a client to fetch the first five objects by passing \"5\" as the argument " +
                    "to `first`, then fetch the total count so it could display \"5 of 83\", for example. " +
                    "In cases where we employ infinite scrolling or don't have an exact count of entries, " +
                    "this field will return `null`.");

            Field<NonNullGraphType<PageInfoType>>()
                .Name("pageInfo")
                .Description("Information to aid in pagination.");
        }

        public Type Type { get; private set; }
        public IGraphType ResolvedType { get; set; }
        private FieldType ItemsField { get; set; }

        public override string CollectTypes(TypeCollectionContext context)
        {
            if (Type != null)
            {
                var innerType = context.ResolveType(Type);
                ResolvedType = innerType;
                var name = innerType.CollectTypes(context);
                context.AddType(name, innerType, context);
                ItemsField.ResolvedType = new ListGraphType(ResolvedType);
                return "Connection[{0}]".ToFormat(name);
            }
            return "Connection[{0}]".ToFormat(ResolvedType.Name);
        }
    }
}
```
Usage would be like this:

```
Field<GraphType>(
    "products",
    arguments: new QueryArguments(
        new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "code", Description = "Product code (EAN, UPC or ISBN)" }
    ),
    resolve: context => GetProductsAsync(context.GetArgument<string>("code"), context.CancellationToken)
).ResolvedType = new ConnectionType(myGeneratedProductGraphType);
```

I loosly based it on ListGraphType.cs.

It seems to be working fine.

Is this the way to go? (For example, I am not sure about CollectTypes() - is this correct?)

Any recommendations to improve this? (Besides of the duplicate strings.)

Thanks!

**Comment by joemcbride** [comment]
Unfortunately I don't know Relay at all.  `.ResolvedType = new ConnectionType(myGeneratedProductGraphType);` is not how you should be registering types though.  That is mixing the instance-based and type-based systems, with isn't a good idea.

I would suggest to use [GraphQL.Relay](https://github.com/graphql-dotnet/relay) project.

**Comment by schlaup** [comment]
Thanks for the feedback!

I looked at GraphQL.Relay project and it seems that it does not support the instance-based type system.

> That is mixing the instance-based and type-based systems, which isn't a good idea.

Really? Maybe, I do not understand it correctly.

I my example "myGeneratedProductGraphType" is a GraphType and "ConnectionType" is a GraphType as well. (It is "ConnectionType" from your project that I modified. Maybe "ConnectionType" in your project should really be named "ConnectionGraphType"?)

Am I correct that I can use:

```
ResolvedType` = new ListGraphType(new StringGraphType));
```

Is this the correct usage of the instance-based system? (Is there more documentation on how to use the type system? It seems to me that it evolved over time and I am never really sure what the "official" or current way to do it is.)

Thanks!

**Comment by joemcbride** [comment]
Hey, sorry for the terse response previously.

The `Field<T>` creates a `FieldType` class and adds it to the `ObjectGraphType`.  So when you call `Field<GraphType>`, is it creating the `FieldType` with a `Type` of `GraphType`.  That is the "type-based" system.  When the Schema is first built, the engine goes through and resolves all of the `Type`'s and assigns the value to the `ResolvedType` property on the `FieldType`.  So what you have done here is define both the `Type` and the `ResolvedType` properties with different values.  It perhaps technically could run, though that is setting yourself up for potentially odd errors.

So a better approach would be to add a method that worked with only instances.  Creating the `FieldType` and assigning the `ResolvedType` property within the method instead of assigning it after the fact and creating the type mis-matches.

Also note that there only ever needs to be a single instance of a given `GraphType`.  So there only ever needs to be a single instance of the `StringGraphType`.  This is a little difficult to work with with the current release because how do you get an instance of the `StringGraphType` to use?  I have a PR (#362) that introduces `GraphQLTypeReference` for this purpose.  So you can reference a type without having the actual instance of it.

**Comment by schlaup** [comment]
Ok, thanks for the explanation! I really appreciate it!

I will revise my code and post it here so that anyone else looking for a solution can find it.

I also have to change my implementation of my GraphType generator because I am creating new instances of `StringGraphType` for each property. Thanks for the hint! I have a much better idea now how your implementation is working internally.

**Comment by hyzx86** [comment]
Hello, I have the same question. Can you give me an example?

**Comment by EricArita** [comment]
@schlaup Thank u so much for your code. It helped me to solve the problem.
@hyzx86 Don't know have you already solved the problem or not? But I got the same issue with you and the code of Schlaup above is great solution right now. We have to clone the entire class ConnectType and EdgeType with the support of their instance-based constructors :D

**Comment by Shane32** [comment]
The original functionality requested in this issue does not seem applicable.  The graph type instance (e.g. `ConnectionType<T>`) defines the GraphQL type returned.  Closing as this issue is 6 years old.

**Comment by hyzx86** [comment]
@EricArita  I'm going to skip this now and just create a type that contains two fields： items and total
