### ISSUE TITLE
Cannot convert value to AST

### ISSUE THREAD

**Issue by mafalarz** [graphql-dotnet/graphql-dotnet#394]
If I indicate QueryArgument of ListGraphType that is of StringGraphType, then get message Cannot convert value to AST. 
1. If I change to QueryArgument to just StringGraphType then it works
2. If I put the string array in query directly (bypassing the use of variable), then it works

**Comment by joemcbride** [comment]
Please read this thread:  https://github.com/graphql-dotnet/graphql-dotnet/issues/389 - I'm guessing you're having the same type of issue with variables.

**Comment by mafalarz** [comment]
Thanks for the help, It's working now. I didn't know the engine expects the values to be converted from JSON.NET types before execution and like in thread #389 I was passing in a Json type. I fixed it like this: 
```
var queryDictionary = query.Variables.GetValue() as Dictionary<string, object>;
var executionOptions = new ExecutionOptions
            {
                Schema = schema,
                Query = query.Query,
                Inputs = new Inputs(queryDictionary);
            };
```
