### ISSUE TITLE
Read Complex Type Properties 

### ISSUE THREAD

**Issue by arunprasathv** [graphql-dotnet/graphql-dotnet#397]
@joemcbride 
I have a class with scalar properties and object. Not able to get values from object.
Getting error
User error: expected an IEnumerable list though did not find one.

Here's the code,

 Field(x => x.billingArrangementId).Description("Account Number");
            Field(x => x.firstName).Description("First Name");
            Field(x => x.lastName).Description("Last Name");
            Field(x => x.workPhoneNumber).Description("Phone Number");
            Field(x => x.serviceStatus);
            Field(x => x.serviceType);
            Field(x => x.homePhoneNumber);
            Field(x => x.customerId);
            **_## Field<ListGraphType<ServiceAddressType>>("serviceaddress",
                 resolve: context => context.Source.ServiceAddress);_**  _** Error Line. Not able to get the Address Properties.**_

**_ServiceAddressType_** 
   public class ServiceAddressType : ObjectGraphType<ServiceAddress>
    {
        public ServiceAddressType()
        {      
            Field(x => x.locationId).Description("Location ID");
            Field(x => x.streetAddress).Description("Street Address");
            Field(x => x.streetAddress2).Description("Street Address");
            Field(x => x.unitNumber).Description("Unit Number");
            Field(x => x.zipCode).Description("Zip");
            Field(x => x.state);
            Field(x => x.city);
            Field(x => x.careOf);
        }
    }

**Comment by jquense** [comment]
Is `ServiceAddress` a list? Also the GQL type is `ListGraphType<TGraphType>`

**Comment by arunprasathv** [comment]
[types.txt](https://github.com/graphql-dotnet/graphql-dotnet/files/1226170/types.txt)
@jquense  Attached file has all the classes that are required.

**Comment by arunprasathv** [comment]
@jquense @joemcbride I made it working by passing array

**Comment by jusefb** [comment]
@arunprasathv I am getting the same issue could you explain what you mean by "I made it working by passing array"?

**Comment by santoshpatro** [comment]
I am also getting the same error. Joe can you please help me to get the fix that you applied in this case. Any help on this is much appreciated.
