### ISSUE TITLE
Using an Int variable for a Long argument (or field)

### ISSUE THREAD

**Issue by mariusbancila** [graphql-dotnet/graphql-dotnet#3978]
Is there something in the specs of GraphQL that prevents using a `Int` argument for a `Long` field? 

I have node in the schema that's using an argument of type `Int`.

```
myNode(id : 123)
{
}
```

I'd like to change it (for some reasons) to have the type `Long`. 

However, this breaks existing queries, such as the following:

```
query read($id : Int!)
{
  myNode(id : $id)
  {
  }
}
```

What I get is:

```
"Variable '$id' of type 'Int' used in position expecting type 'Long'."
```
(with a `VARIABLES_IN_ALLOWED_POSITION` code).

**Comment by Shane32** [comment]
The GraphQL specification prohibits coercing one type of scalar to another.  However, you can redefine the `Int` graph type to accept and return `long` values.  So essentially the `Int` type would act like the `Long` type.  See https://graphql-dotnet.github.io/docs/getting-started/custom-scalars/#replacing-built-in-scalar-types

Please note that if your front end is written in JavaScript, that JavaScript cannot accurately represent all `long` values.

> Me: what is the largest integer that can be accurately represented in javascript?  (or, what is the first integer above zero that cannot be represented in javascript)
>
> ChatGPT:  In JavaScript, numbers are represented using the IEEE 754 double-precision floating-point format. The largest integer that can be accurately represented in JavaScript is 2^53 - 1, which is 9,007,199,254,740,991. 
>
> Therefore, the first integer above zero that cannot be accurately represented in JavaScript is 2^53, which is 9,007,199,254,740,992.

While `long.MaxValue` is 9,223,372,036,854,775,807.  (about 1000x larger)  Similar constraints exist for negative values.  See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by mariusbancila** [comment]
OK, I understand. Thank you for clarifying.
