### ISSUE TITLE
How to use ID type for accepting string or integer

### ISSUE THREAD

**Issue by arulkumaran456** [graphql-dotnet/graphql-dotnet#3979]

**Comment by arulkumaran456** [comment]
I want to use ID type for one of the mutation input parameter. How to do that in graphql dotnet. It should accept string or integer. in below example the departureId must accept string as well as the integer

 Orientation(
        departureId: 123 or "123"
    ) {
        ... on Success {
            responseStatus
        }
    }
}

**Comment by Shane32** [comment]
Any ID type will accept an string or integer.

```cs
// code-first input/output model
Field(x => x.Id, type: typeof(NonNullGraphType<IdGraphType>));

// code-first argument
Field<Product>("GetProduct", true)
    .Argument<NonNullGraphType<IdGraphType>>("id")
    .Resolve(ctx => new Product { Id = ctx.GetArgument<int>("id") });

// type-first input/output model
class Product
{
    [Id]
    public int Id { get; set; }
    public string? Name { get; set; }
}

// type-first argument
class Query
{
    public static Product? GetProduct([Id] int id) => new Product { Id = id };
}
```
Query:
```gql
# valid
{
  getProduct(id: 2) { id name }
}

# also valid:
{
  getProduct(id: "2") { id name }
}
```
Note that any ID fields returned from a field resolver will be coerced to a string automatically.  So regardless of the type of Product.Id, the string "2" will be returned in the `id` field.

**Comment by Shane32** [comment]
Let me know if you have further questions
