### ISSUE TITLE
Query batching

### ISSUE THREAD

**Issue by cime** [graphql-dotnet/graphql-dotnet#398]
Is there any plan to support query batching? Basically batching means just an array of normal queries.

http://dev.apollodata.com/core/network.html#BatchingExplained

**Comment by jquense** [comment]
You can already do that, it just depends on how you implement the https bits on your end. For instance the Relay adapters here (https://github.com/graphql-dotnet/relay/blob/master/src/GraphQL.Relay/Http/RequestHandler.cs) demonstrate one way to do it

**Comment by joemcbride** [comment]
Going to close this as you can accomplish this as @jquense mentions. 🎉
