### ISSUE TITLE
GetRecursivelyReferencedFragments returns skipped fragments

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3980]
## Summary

`TypeInfo.GetRecursivelyReferencedFragments` returns fragments that are not used by the execution strategy due to being skipped by `@skip` or `@include`.  While this is correct for many validation rules to execute properly, other rules such as GraphQL.NET Server's authorization rule requires a list of only fragments that will be executed.

## Background

The authorization validation rule within the GraphQL.NET Server repo requires a list of referenced fragments in order to determine which fields require authorization checks or not.  It is also aware of `@skip` and `@include` directives, and does not perform authorization checks for fragments which are skipped.  For example:

```gql
query getUser ($isAdmin: Boolean) {
  user (id: "abcd") {
    id
    name
    permissions @include(if: $isAdmin) {  # this field only accessible to admins
      ...permissionsFragment
    }
  }
}

fragment permissionsFragment on Permission {
  id
  name
}

# perhaps other operations or fragments here, some of which may not be accessible to admins
```

In this example, when `$isAdmin` is `true`, then `permissionsFragment` is referenced, but if it was `false` then it would not be.  This is proper, as it is akin to only assessing the selected operation for authorization, and not the entire document.

In order to accomplish this, it has a dedicated AST visitor which scans the document, being aware of `@skip` and `@include` to properly assess the referenced fragments.  It does not use the `ValidationContext.GetRecursivelyReferencedFragments` method, as it would return all referenced fragments.

## Proposal

I propose modifying the `GetRecursivelyReferencedFragments` method to accept a boolean indicating whether skipped fragments should be included in the result.  (It will be necessary to include them for many of the built-in validation rules, as occurs now.)

## Why

This will provide other validation rules, such as the complexity analyzer or third-party validation rules, access to the same computed list of referenced fragments without the overhead of computing the list a second time.  It also should deduplicate some code as described below.

## Other benefits

Currently the execution strategy has a protected method called `ExecutionStrategy.ShouldIncludeNode` that performs this check, allowing users to override the behavior if they wish to include any other code to indicate when a field should be skipped.  Potentially this method could be called by the referenced-fragments visitor to determine whether AST nodes should be included.  Currently in v7, a user must override `AuthorizationVisitorBase.SkipNode` in addition to `ShouldIncludeNode` (if they use the authorization rule).

## Problems / required changes

1. The `ExecutionStrategySelector` requires an instance of `ExecutionContext` which does not yet exist during validation
2. `ExecutionContext` typically contains the variable values, which `ExecutionStrategy.ShouldIncludeNode` uses to check the directive's `if` parameter
3. Ignoring the other execution context properties, the directive values are not parsed for use by `ShouldIncludeNode` until after the first pass of the validation rules.  However, we could configure it so the new functionality is only operational during the second pass.  Validation rules of this kind (auth / complexity) should generally be in the second pass anyway, after the document is determined to be generally valid and variables have been parsed.

These don't seem like very many issues, but fixing them would change a lot of code / method signatures / how it fundamentally works.

## Other solutions to the problems

1. We could move `ShouldIncludeNode` to the `Schema`, and perhaps remove the dependency on the `ExecutionContext` (meaning, it will not be able to read parsed directives), but this feels like a step backwards in some respects.
2. We could ignore the problem and duplicate the `@skip` and `@include` checks within the updated `GetRecurisvelyReferencedFragments` method, possibly fixing the problem in a later release.  However, we are changing a lot of validation-related code in v8 and now would be a better time for breaking changes than v9, most likely.

I'm not really sure what other solutions there are.

**Comment by Shane32** [comment]
Relevant code:

```cs
// ===== DocumentExecuter =====
var validationResult = await _documentValidator.ValidateAsync(
    new ValidationOptions { /* lots of stuff */ })
    .ConfigureAwait(false);
context = BuildExecutionContext(options, document, operation, validationResult, metrics);

// protected so that users can return a class derived from ExecutionContext if desired
protected virtual ExecutionContext BuildExecutionContext(ExecutionOptions options, GraphQLDocument document, GraphQLOperationDefinition operation, IValidationResult validationResult, Metrics metrics)
{
    var context = new ExecutionContext { /* lots of stuff */ };
    context.ExecutionStrategy = SelectExecutionStrategy(context);
    return context;
}

// override for legacy / non-DI way of selecting the execution strategy
protected virtual IExecutionStrategy SelectExecutionStrategy(ExecutionContext context)
    => _executionStrategySelector.Select(context);

// ===== DefaultExecutionStrategySelector =====
// this is used by default for DI-based execution strategy registrations by IGraphQLBuilder extensions,
// and although commonly used, typically only the operation type of the selected operation is pulled from
// the context as seen below
public virtual IExecutionStrategy Select(ExecutionContext context)
{
    var operationType = context.Operation.Operation;

    foreach (var registration in _registrations)
    {
        if (registration.Operation == operationType)
            return registration.Strategy;
    }
    // no matching registration, so return default implementation
    return operationType switch
    {
        OperationType.Query => ParallelExecutionStrategy.Instance,
        OperationType.Mutation => SerialExecutionStrategy.Instance,
        OperationType.Subscription => SubscriptionExecutionStrategy.Instance,
        _ => throw new InvalidOperationException($"Unexpected OperationType '{operationType}'.")
    };
}

// ===== ExecutionStrategy =====
// here we see that the context.DirectiveValues property is used to look up the '@skip' and '@include' directives
// and read the parsed value for the 'if' argument (note: context.DirectiveValues is new for v8)
protected virtual bool ShouldIncludeNode<TASTNode>(ExecutionContext context, TASTNode node)
    where TASTNode : ASTNode, IHasDirectivesNode
{
    if (node.Directives == null)
        return true;
    if (context.DirectiveValues?.TryGetValue(node, out var directives) ?? false)
    {
        // where @skip and @include are used, validation will ensure that the 'if' argument exists and is a non-null boolean
        if (directives.TryGetValue(context.Schema.Directives.Skip.Name, out var skipDirective) &&
            (bool)skipDirective.Arguments["if"].Value!)
        {
            return false;
        }

        if (directives.TryGetValue(context.Schema.Directives.Include.Name, out var includeDirective) &&
            !(bool)includeDirective.Arguments["if"].Value!)
        {
            return false;
        }
    }

    return true;
}
```

**Comment by Shane32** [comment]
PR added with "ignore problem" as temporary solution; no worse than before, anyway.  I was thinking that then we can make a separate PR to fix the duplicated code issue...

**Comment by gao-artur** [comment]
No thoughts on this. Sorry.

**Comment by Shane32** [comment]
Ok then I’d like to merge the PR and continue with subsequent PRs
