### ISSUE TITLE
Very Large response causes "InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead."

### ISSUE THREAD

**Issue by edavedian** [graphql-dotnet/graphql-dotnet#3986]
We have a scenario which produces a very large response to the graphql request and in that case the `FlushInternal(flushEncoder: false);` in the below function in GraphQL.NewtonsoftJson.HttpResponseStreamWriter is called which eventually calls Kestrel's HttpResponseStream here https://github.com/dotnet/aspnetcore/blob/9098a47dbfede8c549633090fe931687a4e9ee8d/src/Servers/Kestrel/Core/src/Internal/Http/HttpResponseStream.cs#L81 and that generates an exception due to SyncrhonousIO not being set.  It seems that this should call FlushInternalAsync instead of FlushInternal.

```
public override void Write(char value)
{
    if (_disposed)
    {
        throw new ObjectDisposedException(nameof(HttpResponseStreamWriter));
    }

    if (_charBufferCount == _charBufferSize)
    {
        FlushInternal(flushEncoder: false);
    }

    _charBuffer[_charBufferCount] = value;
    _charBufferCount++;
}
```

### Steps to reproduce

Generate a large response that exceeds DEFAULT_BUFFER_SIZE = 16 * 1024 defined in GraphQL.NewtonsoftJson.HttpResponseStreamWriter

### Expected result

No exception should occur with large response

### Actual result

InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.

### Environment

ASP.NET Core 8, GraphQL 7.8.0

**Comment by Shane32** [comment]
HttpResponseStreamWriter implements both synchronous and asynchronous methods including WriteAsync. However, the Newtonsoft.Json writer does not support asynchronous serialization.  See the MS docs on .NET 3.0 migration here:

https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-8.0&tabs=visual-studio#allowsynchronousio-disabled

GraphQL.NET does not include an automatic buffering mechanism for synchronous serializers the way that ASP.NET does for the Newtonsoft.Json formatter. 

I suggest switching to the System.Text.Json serializer which has native asynchronous support.

**Comment by Shane32** [comment]
Our readme indicates the same here:
https://github.com/graphql-dotnet/graphql-dotnet?tab=readme-ov-file#2-serialization

**Comment by edavedian** [comment]
Thank you very much for the quick response. Could I ask you to please refer me to the documentation on how to switch to System.Text.Json serializer.

**Comment by edavedian** [comment]
Thank you very much. I figured it out.
