### ISSUE TITLE
Missing information about using GraphQL over network

### ISSUE THREAD

**Issue by nick-lehmann** [graphql-dotnet/graphql-dotnet#399]
Maybe I am just not aware of it, but I did not find any information about how to use this, by the way quite awesome, library with a GraphQL backend over the network e.g. [graph.cool](graph.cool).

Is there any information about that which I simply haven't seen yet? Or is it just not possible at the moment?

**Comment by joemcbride** [comment]
From my understanding, graph.cool IS your GraphQL server, and you use JavaScript to make calls to your API to fetch data.  So no, you wouldn't use this project at all with graph.cool.

**Comment by nick-lehmann** [comment]
Yes, graph.cool is my GraphQL server/backend. And I was trying to find a GraphQL client to make calls to it from a client programmed in C#. Since you find this project first when you search for "C# graphql", I just looked into and did not find any information about using graphql-dotnet as client. Are you aware of any graphql client libraries for C#?

**Comment by jquense** [comment]
@nick-lehmann you may not need a specific client library, the core http client libs should be fine. From the client side there isn't really anything special about querying a GQL backend, you send a http POST with the query and variables. Most actual backends differ on want format they want the request specified anyway.

For complex cases where you want caching and the like client libraries like Relay and Apollo are cool, but as far as i know there aren't any big libraries like that outside the javascript/browser ecosystem. It'd be really neat tho!

**Comment by nick-lehmann** [comment]
@jquense Thanks for the answer. I had a bad feeling that this might be the case. This [tutorial](https://gregshackles.com/building-flexible-xamarin-apps-with-graphql/) on how to use GraphQL with Xamarin might be helpful. Still, it would be nice to have some kind of information in the documentation about how to consume GraphQL API, since the name of the project does not include "server" and at least I found it while searching for a client library.

**Comment by jquense** [comment]
> since the name of the project does not include "server" and at least I found it while searching for a client library.

Yeah i understand where you are coming from if you aren't familiar with GQL. Honestly the reason it doesn't specify "server" is because there isn't a client portion. Like you don't usually see things labeled as REST api servers, and REST api clients. A REST api means server, and so too here. And like i mentioned generally you really don't need a specialized client, like you don't need a REST client, the normal http libraries do everything you need.

**Comment by joemcbride** [comment]
Going to go ahead and close this.
