### ISSUE TITLE
Suggested Analyzer: ensure Fields with expression trees can detect a name

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#3992]
Valid:

```cs
Field(x => x.Active);                       // name inferred as Active
Field("ActiveNum", x => x.Active ? 1 : 0);  // name is explicit
```

Invalid:

```cs
Field(x => x.Active ? 1 : 0);  // can't infer field name
```

**Comment by Shane32** [comment]
@gao-artur We don't have an analyzer for this yet, do we?

**Comment by Shane32** [comment]
Not pretty.  Just throws an invalid cast exception.

https://github.com/graphql-dotnet/graphql-dotnet/blob/37145b7a2fb9f40e9d3cbe634bcc73bc2f243680/src/GraphQL/Extensions/GraphQLExtensions.cs#L207

It is thrown on the exact line of code that attempts to define the field, so at least it's easy to debug (vs during initialization or runtime).

**Comment by gao-artur** [comment]
Should we also improve the runtime error? Not many devs are familiar with `Expression` API, so failure casting to `MemberExpression` will not be very helpful for them. But with the help of `[CallerArgumentExpression]`, we can provide a more user friendly error message.

**Comment by gao-artur** [comment]
There is actually an error handling code here
https://github.com/graphql-dotnet/graphql-dotnet/blob/37145b7a2fb9f40e9d3cbe634bcc73bc2f243680/src/GraphQL/Types/Composite/ComplexGraphType.cs#L740-L745
