### ISSUE TITLE
Question about Generating Entire Schema

### ISSUE THREAD

**Issue by michshat** [graphql-dotnet/graphql-dotnet#4]
It's pretty awesome what you've done.Thanks!!! It could be used as an ORM extension of some sort that'd create a graph over underline database model while correctly maintaining foreign key relationships.  

I was looking into GraphQL.Tests project trying to find a way how to build an entire schema that could be used to pass to babel-relay-plugin for validation when compiling the source - but haven't figured out that part yet.

Any idea?

**Comment by joemcbride** [comment]
I'm not terribly familiar with Relay yet, though looking at the relay-starter-kit I think you want the introspection queries.

Is [this what you're looking for](https://github.com/relayjs/relay-starter-kit/blob/master/build/babelRelayPlugin.js)?  Getting the schema in json format?

I just added additional support for introspection on Friday (it should be pretty close to complete).  Check out the [StarWars introspection tests](https://github.com/joemcbride/graphql-dotnet/blob/master/src/GraphQL.Tests/StarWars/StarWarsIntrospectionTests.cs).

**Comment by joemcbride** [comment]
Note that those changes aren't on NuGet yet, there are a couple issues left to fix before I want to push an update.

**Comment by michshat** [comment]
Joe thanks!!! 

That's right the babelRelayPlugin.js initializing schema and validating against it.

I did get the the library from nuget at first, but later realized it wasn't up todate. I used introspections queries to produce schema - it does work very nicely - but i think i may need to combine several of them into one for babelRelayPlugin to consider it complete.
 
I'll play more with it and let you how it goes.

Thanks again.

Michael

**Comment by michshat** [comment]
A couple things I noticed aren't supported yet :)
1. field arguments via arg property - where compiler complains resolving arg property
the case is described here https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsIntrospectionTests.js#L299

2. when generating schema of this schema introspection query babel relay plug-in says it's incomplete
 var query = @"
            query SchemaIntrospectionQuery {
              __schema {
                queryType { name, kind }
                types { 
                    kind
                    name
                    description
                    fields {
                        name
                        description
                        type {
                            name
                            kind
                        }
                        isDeprecated
                        deprecationReason
                    }
                }
                mutationType { name }
                directives {
                  name
                  description
                  onOperation
                  onFragment
                  onField
                }
              }
            }
            ";

I'll play with it more ...

Thanks!!!

**Comment by joemcbride** [comment]
@michshat Pushed up some changes that may fix your issues.  Give it a go again?

**Comment by michshat** [comment]
Joe, that's awesome. Thanks!

I'm past resolving arg property, now hitting the "can't resolve *ofType*"
````
\"errors\":[{\"ClassName\":\"GraphQL.ExecutionError\",\"Message\":\"Error trying to resolve ofType.\",\"Data\":null,\"InnerException\":{\"ClassName\":\"System.IndexOutOfRangeException\",\"Message\":\"Index was outside the bounds of the array.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at GraphQL.Introspection.__Type.\u003c.ctor\u003eb__b(ResolveFieldContext context) in 
````

Thanks again. And looking forward getting further with that :)

Michael

**Comment by joemcbride** [comment]
@michshat Added a bunch of fixes, plus a project that runs the GraphiQL interface.  Give it a try!

**Comment by michshat** [comment]
Wow, adding graphiql is huge!!! I have got no errors whatsoever, and relay babelify plugin takes the schema and able perform validation against it.  I'll play more today.

Thanks!!!

**Comment by joemcbride** [comment]
Awesome, I'm going to push a new Nuget version.  Let me know if you find any issues.

**Comment by michshat** [comment]
That's great!

Couple things:
1. isDeprecated": "False" - 
2. Also the following code generates circular reference error where babel-relay-plugin raises "maximum call stack size exceeded while parsing" exception (there is seem to be object and interface type collusion)
````
{
                    "kind": "OBJECT",
                    "name": "User",
                    "description": "A mechanical creature in the Star Wars universe.",
                    "fields": [ { "name": "UserId", "description": null, "args": [ ], "type": { "kind": "NON_NULL", "name": null, "ofType": { "kind": "SCALAR", "name": "Int", "ofType": null } }, "isDeprecated": false, "deprecationReason": null }, { "name": "FirstName", "description": null, "args": [ ], "type": { "kind": "SCALAR", "name": "String", "ofType": null }, "isDeprecated": false, "deprecationReason": null }, { "name": "LastName", "description": null, "args": [ ], "type": { "kind": "SCALAR", "name": "String", "ofType": null }, "isDeprecated": false, "deprecationReason": null } ],
                    "inputFields": [ ],
                    "interfaces": [ 
                        { "kind": "INTERFACE", "name": "User", "ofType": null } ],
                    "enumValues": [ ],
                    "possibleTypes": [ ]
                },
````

Thank you!

**Comment by joemcbride** [comment]
1. isDeprecated should be a boolean.  Which are you getting?  In the sample you posted it looks like a boolean.
2. Hm, yes perhaps you have an issue in your schema?  Is your User object defined as an Object or an Interface?

**Comment by michshat** [comment]
1. In the example above i had it adjusted, here is non modified example:
````
{"name":"ENUM","description":"Indicates this type is an num.  `enumValues` is a valid field.","isDeprecated":"False","deprecationReason":null},
````
Parser doesn't seem to mind it though

2. I have this that causes the issue

```` C#
public class UserType: ObjectGraphType
    {
        public UserType()
        {
            Name = "User";
            Description = "A mechanical creature in the Star Wars universe.";
            Field<NonNullGraphType<IntGraphType>>("UserId", "The id of the droid.");
            Field<StringGraphType>("FirstName", "The name of the droid.");
            Field<StringGraphType>("LastName", "The name of the droid.");
            Interface<UserInterface>();
        }
    }
````
Note *User*Type and *User*Interface

**Comment by joemcbride** [comment]
1. Yeah that's fine I think.

2. What name did you give the UserInterface?  I'm guessing it is also marked as User.  Those two names need to be unique.

**Comment by michshat** [comment]
Regarding item 2:

I have tried to change the name from User to IUser (for the sake of it) and also changing UserInterface to IUserInterface - in both cases running to exception where it says that the schema is incomplete

What seem to be missing (could be wrong though), is INTERFACE type definition:
````
 {
          "kind": "INTERFACE",
          "name": "Node",
          "description": "An object with an ID",
          "fields": [
            {
              "name": "id",
              "description": "The id of the object.",
              "args": [],
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "ID",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            }
          ],
          "inputFields": null,
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": [
            {
              "kind": "OBJECT",
              "name": "Todo",
              "ofType": null
            },
            {
              "kind": "OBJECT",
              "name": "User",
              "ofType": null
            }
          ]
        }
````

Object Types interfaces are properly defined, it's the type that is not.

**Comment by joemcbride** [comment]
I'm not sure I'm fully following, though are you able to just add more to your introspection query to get the data you need?  My first thought is you may need the tripple `ofType` definition listed below in the `TypeRef` fragment.

I added a "full introspection query" [here](https://github.com/joemcbride/graphql-dotnet/blob/master/src/GraphQL/Introspection/SchemaIntrospection.cs#L9) that the graphql-js project is using, which seems to include a bit more information than the introspection query you posted above.  Does using that help?

Posting the query here for posterity:
```
query IntrospectionQuery {
  __schema {
    queryType { name }
    mutationType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      args {
        ...InputValue
      }
      onOperation
      onFragment
      onField
    }
  }
}
fragment FullType on __Type {
  kind
  name
  description
  fields {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}
fragment InputValue on __InputValue {
  name
  description
  type { ...TypeRef }
  defaultValue
}
fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
      }
    }
  }
```

**Comment by michshat** [comment]
Joe, thank you.

This query is exactly what i'm after :)
But have a look here it skips the "INTERFACE" kind
````
{
    "data": {
        "__schema": {
            "queryType": { "name": "Query" },
            "mutationType": null,
            "types": [
                { "kind": "SCALAR", "name": "String", [ ... ] },
                { "kind": "SCALAR", "name": "Boolean", [ ... ] },
                { "kind": "SCALAR", "name": "Float", [ ... ] },
                { "kind": "SCALAR", "name": "Int", [ ... ] },
                { "kind": "SCALAR", "name": "ID", [ ... ] },
                { "kind": "OBJECT", "name": "__Type", [ ... ] },
                { "kind": "ENUM", "name": "__TypeKind", [ ... ] },
                { "kind": "OBJECT", "name": "__Field", [ ... ] },
                { "kind": "OBJECT", "name": "__EnumValue", [ ... ] },
                { "kind": "OBJECT", "name": "__InputValue", [ ... ] },
                { "kind": "OBJECT", "name": "Query", [ ... ] },
                { "kind": "OBJECT", "name": "User", [ ... ] },
                { "kind": "OBJECT", "name": "__Schema", [ ... ] },
                { "kind": "OBJECT", "name": "__Directive", [ ... ] },
                { "kind": "INTERFACE", "name": "IUser", [ ... ] ], } <= this part is getting output
            ],
            [ ... ]
            [ ... ]
        }
    }
}
````

**Comment by joemcbride** [comment]
You are saying it should *not* export the `INTERFACE` type `IUser`?

**Comment by michshat** [comment]
Sorry. It should export, but it doesn't - it is missing from the generated schema top level __schema->types


Does it make sense? If not, i'll troubleshoot the code and see what's happening.

**Comment by joemcbride** [comment]
Okay I understand.  In the sample repo it is using an Interface type `Character`, which is getting returned.  I'm not sure why you're interface isn't, sounds like a bug.  It is [getting all the types from here](https://github.com/joemcbride/graphql-dotnet/blob/master/src/GraphQL/Types/Schema.cs#L38) if you can run under debug and want to see all of the available types being returned.

**Comment by michshat** [comment]
I had tried your suggestion, the `Character` interface is handled correctly - something is wrong with my setup :)

It's all good. Thank you!!!

**Comment by joemcbride** [comment]
I think I figured out the issue.  An interface object would not be registered in the type lookup if it is not used somewhere as a field.  I pushed a change to master that registers the interface object.  It seems like you would want to use that interface type as a field type somewhere though.

**Comment by michshat** [comment]
Joe thank you!!!

Few more nuances I came across while playing with Relay
1. Relay doesn't like `errors:[]` - to make it work i had to strip it liek this: `result = result.Replace(",\"errors\":[]", "");` But more elegant would be omitting it when returning success data

2. Property names should be camel cased in both ends (example. firstName, lastName) - result data returns it in such format
````
public UserType()
        {
            Name = "User";
            Description = "A mechanical creature in the Star Wars universe.";
            Field<NonNullGraphType<IntGraphType>>("userId", "The id of the droid.");
            Field<StringGraphType>("firstName", "The name of the droid.");
            Field<StringGraphType>("lastName", "The name of the droid.");
            Interface<IUserInterface>();
        }
````
3. For whatever reason root level arguments type expected to be string (note id parameter bellow, i had initially setup as integer)
````
 Field<UserType>(
                "user",
                arguments: new QueryArguments(
                    new[]
                    {
                        new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id" }
                    }),
                resolve: context => data.SingleOrDefault<User>("WHERE UserId=@0", (string)context.Arguments["id"])
````

**Comment by joemcbride** [comment]
1. `errors:[]` - your GraphQL endpoint can return whatever, it doesn't need to return the `ExecutionResult` directly.  You can easily return an object with a `data` property and resulting object from the `ExecutionResult` class.

2. The field names provided are just static, however when checking objects for those values it ignores the casing.  When data is returned from the API it returns the field named exactly as it was defined in the field.  You can use a [CamelCasePropertyNamesContractResolver](https://github.com/joemcbride/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/App_Start/WebApiConfig.cs#L15) with JSON.NET to force all returned field names to camel case, though then you could have a mis-match between the Introspection query and the output.  I could certainly add something to force camel case, though just naming the fields that way when registering is pretty easy.

3.  I have been able to see an integer come through as that type.  Did you perhaps send the value as a string in the GraphQL query?  This is what works for me:

```javascript
Field<HumanType>(
  "human",
  arguments: new QueryArguments(
    new [] {
        new QueryArgument<NonNullGraphType<IntGraphType>> {
          Name = "id", Description = "id of the human"
        }
    }),
  resolve: context =>
  {
    var id = (int)context.Arguments["id"];
    return data.GetHumanById(id.ToString());
  }
);

/////////////////////////////////
// correct
query AQuery {
  human(id: 1 /*sending as number*/) {
    name
  }
}

/////////////////////////////////
// incorrect
query AQuery {
  human(id: "1" /*sending as string*/) {
    name
  }
}
```

**Comment by michshat** [comment]
Joe thanks!

1. I'll check that out, but i think graphql-relay library (https://github.com/graphql/graphql-relay-js) that does runtime validation

when i defined the Relay like following:
````
export default Relay.createContainer(Index, {
   fragments: {
    user : () => Relay.QL`
      fragment on User {
        firstName,
        lastName,
      }
    `,
  },
});
````
the request is being handled by GraphQL server:
````c#
        public ContentResult ExecuteGraphQL(string query)
        {
            var result = (new Executer()).Execute(new UserSchema(), query);
            result = result.Replace(",\"errors\":[]", "");

            return Content(result, "application/xhr");
        }
````

and if empty array of errors is present `"errors":[]` the relay-graphql complains

2. ok
3. Testing that on its' own - works with integers, but when connecting Relay layer - it won't (but may be its' just my setup, i'll play more with it)

Thanks again!

**Comment by joemcbride** [comment]
> and if empty array of errors is present "errors":[] the relay-graphql complains

Right, so you need to change your `Executer` class to not just serialize the `ExecutionResult` class.  Manually removing the errors in the string is working around the problem.  Change it so it creates a different object vs. just serializing what is returned from the `DocumentExecutor`.  I would also suggest to not just return a string and instead return an object that gets serialized to JSON.  Something like:

```csharp
[HttpPost]
public JsonResult ExecuteGraphQL(string query)
{
    MyResult result = Execute(_schema, null, query);
    return Json(result); 
}

public class MyResult {
  public object data {get;set;}
}

public MyResult Execute(
  Schema schema,
  object rootObject,
  string query,
  string operationName = null,
  Inputs inputs = null)
{
    var executer = new DocumentExecuter();
    var executeResult = executer.Execute(schema, rootObject, query, operationName);
    if (executeResult.Errors.Count() == 0) {
      return new MyResult { data = executeResult.Data };
    }
    return new MyResult { data = new { error = "An error has occured" } };
}
```

**Comment by michshat** [comment]
Joe, that's pretty slick - I wasn't aware of that -Thanks!

Another question, not sure if it's a part of the scope of the the GraphQL.NET - the Relay `nodeDefinitions` (`nodeInterface` and `nodeField`), as well `connection`  and `connectionType`
1. `nodeDefinitions` - defining node and its' edges (item and item collections)
2. `connection` - connecting related data and providing paging information

**Comment by joemcbride** [comment]
A connection class is now included in the core library.  I do think it could be helpful to add some of the other Relay classes.  I'm going to close this issue and create a new one to track that.
