### ISSUE TITLE
Connection Sample

### ISSUE THREAD

**Issue by rvlietstra** [graphql-dotnet/graphql-dotnet#40]
Hi.

Sorry I'm unsure of how to use Connection<,>
As I understand it it should be used like Interface<>, in the constructor of the parent type ?

Is there a Test/Example of how to use it with edges etc. ?
Thanks!

**Comment by rvlietstra** [comment]
Ok, this is what I have so far

```c#
Connection<OrganizationType, UserType>().Name("Users").Resolve(                
    context => 
    {
        Organization org = context.Source as Organization;
        List<UserType> ret = ...
        return ret;
});
```

The Resolve func is returning a list of ObjectGraphTypes, shouldn't that be a list of my actual data layer types ? The reason I think that is that later on UserType is given the items in the list to resolve, which then has a context.Source of UserType when resolving it's fields instead of a User (type) ...

Please help! :)

**Comment by joemcbride** [comment]
Yes, this is a problem with me bringing in features without tests or examples.  I wouldn't think you would be returning a `GraphType`.  In every case I can think of you should be returning your actual object.  I don't know that Relay would be different.  @tlil87 do you have a basic example of creating a Relay Schema?

**Comment by tlil87** [comment]
Hi @joemcbride and @rvlietstra - apologies, this is an artefact from us having combined the `GraphType` and the data object early on. We've migrated away from that now, but I haven't gotten around to create a PR here to get that into the public repo yet. It was a blunder on my part forgetting to open up for the use of data objects instead. I have started on a branch migrating the version that we're currently using across to the public repo. This will allow you to do what you're trying to do above @rvlietstra. That branch will also include a bunch of unit tests for the `FieldBuilder` and the `ConnectionBuilder`. I will have that ready by tomorrow for you. Sorry for the inconvenience. (Will include a basic example in the unit tests, @joemcbride).

**Comment by rvlietstra** [comment]
Hi,
Excellent.

Thanks!!

**Comment by tlil87** [comment]
@joemcbride: I've submitted PR https://github.com/graphql-dotnet/graphql-dotnet/pull/42 for this - @rvlietstra, have a look at the unit tests for examples.

**Comment by joemcbride** [comment]
Gong to close this, let us know if you have any other questions.
