### ISSUE TITLE
How to Map List property

### ISSUE THREAD

**Issue by arunprasathv** [graphql-dotnet/graphql-dotnet#400]
@joemcbride 
Here are the class that I need to map. Need help with mapping list property in AccountSearchType.

    public class **AccountSearchResult**
    {
        public List<BillingArrangement> BillingArrangement { get; set; }
    }

    public class AccountSearchType : ObjectGraphType<**AccountSearchResult**>
    {
        public AccountSearchType()
        {
            **Field<ListGraphType<BillingArrangementType>>("billingArrangement",
                resolve: context => new List<BillingArrangement>().Add());**
        }
    }

**Comment by joemcbride** [comment]
Did you try out that code?  That is how it is done.

https://github.com/graphql-dotnet/graphql-dotnet/blob/4da2d8af548b4f0d9cd620da2504781861cf6e37/src/GraphQL.StarWars/Types/DroidType.cs#L15-L18

**Comment by arunprasathv** [comment]
Getting this error

Field billingArrangement of type [BillingArrangementType] must have a sub selection.
Code
Field<ListGraphType<BillingArrangementType>>("billingArrangement",
                 resolve: context => context.Source.BillingArrangement);

**Comment by joemcbride** [comment]
That error means you need to provide the fields you want to select on the BillingArrangementType.

**Comment by arunprasathv** [comment]
I need the whole object AccountSearchResult.

**Comment by joemcbride** [comment]
The way GraphQL works is you need to explicitly request the specific fields you want.

If your classes look something like this:

```csharp

public class BillingArrangement
{
   public string Name { get; set; }
   public string Type { get; set; }
}

public class AccountSearchResult
{
    public List<BillingArrangement> BillingArrangement { get; set; }
}

public class BillingArrangementType : ObjectGraphType<BillingArrangment>
{
  public BillingArrangementType()
  {
    Field(x => x.Name);
    Field(x => x.Type);
  }
}

public class AccountSearchResultType : ObjectGraphType<AccountSearchResult>
{
  public AccountSearchResultType()
  {
    Field<ListGraphType<BillingArrangementType>>("billingArrangement");
  }
}

public class Query : ObjectGraphType
{
  public Query
  {
    Field<AccountSearchResultType>(
      "searchAccounts",
      context => new AccountSearchResult());
  }
}

var schema = new Schema { Query = new AccountSearchResultType() };
```

Your GraphQL query would look something like this:

```graphql
query SearchResults {
  searchAccounts {
    billingArrangement {
      name
      type
    }
  }
}
```

**Comment by arunprasathv** [comment]
Yes, I get that. I need to make an API call instead of  **context => new AccountSearchResult()**  which gets the model to map.

    Field<AccountSearchResultType>(
      "searchAccounts",
      context => new AccountSearchResult());

**Comment by joemcbride** [comment]
You can put whatever code you want within that function.

```csharp
Field<AccountSearchResultType>(
  "searchAccounts",
  context => 
{
  // call API here
  AccountSearchResult result = myApi.GetResult();
  return result;
});
```

**Comment by joemcbride** [comment]
Take a look at the StarWars example.  It shows how to get data from an external source.

https://github.com/graphql-dotnet/graphql-dotnet/blob/4da2d8af548b4f0d9cd620da2504781861cf6e37/src/GraphQL.StarWars/StarWarsQuery.cs#L7-L32

**Comment by joemcbride** [comment]
Going to close this.  Re-open if needed.
