### ISSUE TITLE
Resolve query dinamically

### ISSUE THREAD

**Issue by petrovic-ivan** [graphql-dotnet/graphql-dotnet#401]
I am trying to understand how what is the correct way to dynamically add a query and resolve. I imagine having one schema and implementations of multiple queries. By multiple queries, I consider implementing multiple C# classes which will their fields. Is it event right way to do that? Do I need to split queries into multiple classes?

**Comment by jquense** [comment]
Usually you don't need to do that, Since the user can query for some or all of the possible fields you define in your types, you can just define types that cover all the different possibilities and then a user can just query for the fields relevant to them

**Comment by petrovic-ivan** [comment]
An example in StarWars app we have `StarWarsQuery` class. Basically, correct way will be to always implement new fields and types if I need them, not to implement now `SomeQuery `class and register somehow?

**Comment by jquense** [comment]
you wouldn't implement a new query type no, its not like a REST api where you might version it and have 3 different full API's, GQP you can add new types or fields as you go. If you want to remove older fields you can deprecate them
