### ISSUE TITLE
Strong Name Signing

### ISSUE THREAD

**Issue by kdelorey** [graphql-dotnet/graphql-dotnet#405]
At least when using the NuGet package, I cannot load the assembly in my environment because it is not signed. It'd be nice if the assembly was signed.

> ` System.IO.FileLoadException: Could not load file or assembly 'GraphQL, Version=0.17.2.752, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`

**Comment by joemcbride** [comment]
Please see #234

**Comment by kdelorey** [comment]
@joemcbride Yeah I just found that and I came to close this myself. Apologies.
