### ISSUE TITLE
context getArgument<string>("id") fails on numeric values

### ISSUE THREAD

**Issue by mac2000** [graphql-dotnet/graphql-dotnet#4075]
## Description

according to [spec](https://spec.graphql.org/June2018/#sec-ID) and [docs](https://graphql-dotnet.github.io/docs/getting-started/schema-types/#scalars) `ID` field can be both numeric and string

but context getArgument method does not respect that and has missleading behavior

### Steps to reproduce

```bash
mkdir demo
cd demo
dotnet new console
dotnet add package GraphQL
dotnet add package GraphQL.SystemTextJson
```

**Program.cs**

```cs
using GraphQL;
using GraphQL.Types;
using GraphQL.SystemTextJson;

var schema = new Schema { Query = new StarWarsQuery() };

var json = await schema.ExecuteAsync(_ =>
{
  _.Query = "{ demo1:hero(id:\"1\") { id } demo2:hero(id:2) { id } }";
});

Console.WriteLine(json);

public class Droid
{
  public string Id { get; set; }
  public string Name { get; set; }
}

public class DroidType : ObjectGraphType<Droid>
{
  public DroidType()
  {
    Field(x => x.Id).Description("The Id of the Droid.");
    Field(x => x.Name).Description("The name of the Droid.");
  }
}

public class StarWarsQuery : ObjectGraphType
{
  public StarWarsQuery()
  {
    Field<DroidType>("hero")
        .Argument<NonNullGraphType<IdGraphType>>("id")
        .Resolve(context =>
        {
          // return new Droid { Id = "1", Name = "R2-D2" };// techinically resolver works in both cases
          // until we try to get the argument value

          // this one will fail with INVALID_OPERATION exteption - which is strange
          // especially taking into account that spec say ID should be serialized as string
          // return new Droid { Id = context.GetArgument<string>("id"), Name = "R2-D2" };

          // but somethow this one works
          return new Droid { Id = context.GetArgument<int>("id").ToString(), Name = "R2-D2" };

          // for ID field - it is expected to read it as string
        });
  }
}
```

### Expected result

expecting to read `ID` as string out of the box the same way it is done in other libraries

### Actual result

in case of numeric argument INVALID_OPERATION exception occurs

### Other libs

In HotChocolate id read as string

also here is an example for 

<details>
<summary>apollo server</summary>

```bash
mkdir demo
cd demo
npm init -y -f
npm i -S @apollo/server
node server.js
```

**server.js**

```js
import { ApolloServer } from '@apollo/server'
import { startStandaloneServer } from '@apollo/server/standalone'

const typeDefs = `#graphql
type User {
  id: ID!
}
type Query {
  user(id: ID!): User!
}
`

const resolvers = {
  Query: {
    user: (_, { id }) => {
      console.log('id', id, typeof id)
      return { id }
    },
  },
}
const server = new ApolloServer({ typeDefs, resolvers })
startStandaloneServer(server).then(({ url }) => console.log(`open ${url}`))
```

in simpilar requests id is passed as string

</details>

So it seems like there is something wrong inside `getArgument` method or may be docs missing some pices of how should we get arguments

---

### Possible solution/workaround

after quick debugging it seems like `ObjectExtensions.GetPropertyValue` may be an extension point

e.g. somewhere at the very end something like this may solve everything:

**src/GraphQL/Extensions/ObjectExtensions.cs**

```cs
public static object? GetPropertyValue(this object? propertyValue, Type fieldType, IGraphType mappedType) {
  // ....

  // if schema expects ID (which may be int and string), client passed int and our code wants string then return string
  if (propertyValue != null && propertyValue is int && fieldType == typeof(string) && mappedType is IdGraphType) {
    return propertyValue.ToString();
  }
}
```

### Motivation

Imagine following - you with your teammates agree to use string identifiers averywhere, so your code is full of pieces like this inside resolvers:

```cs
var id = context.getArgument<string>("id");
```

and everything seems to be fine, until you upgrade federation gateway which has [this](https://github.com/apollographql/federation/blob/main/internals-js/src/values.ts#L390-L393) 🤔

<img width="677" alt="image" src="https://github.com/user-attachments/assets/da86ed36-4e8a-4307-8959-bbc99dc68e52">

somehow guys there decided to reduce payloads for two bytes but completely broke everything

because it does not matter if you send: `{ droid(id:"1") {id}}` or `{ droid(id:2) {id}}` in both cases, under the hood numeric argument will be passed

but from other hand, indeed according to both spec and graphql.net docs ID may be both int and string, even more - resolver part works

and for now we can do either:

- replace everywhere `var id = context.getArgument<int>("id");` which is even worse because who knows if tomorrow indeed we want string identifiers, and why the heck it works in both cases
- replace everywhere to something like `var id = context.getArgument<object>("id").toString();` - which is kind of strange
- ask apollo - why the hell they decided to change the types - but I bed their response will be the spec
- provide some kind of workaround to graphql.net

**Comment by Shane32** [comment]
try putting this in your startup:

```cs
ValueConverter.Register<int, string>(value => value.ToString(CultureInfo.InvariantCulture));
```

If a change were made in the GraphQL.NET library, we would solve it in the above method.  (The value converter is used to convert strings to numbers as you have seen already works.)  This is due to the graphql specification which says:

> When expected as an input type, any string (such as "4") or integer (such as 4 or -4) input value should be coerced to ID as appropriate for the ID formats a given GraphQL service expects. Any other input value, including float input values (such as 4.0), must raise a request error indicating an incorrect type.

In essence, the scalar cannot know, yet, whether the user wants to coerce the value to a number or a string.

However, there are other ways to solve this by the user.  For example, you could provide a custom implementation of `IdGraphType` which converts integer inputs to strings.

**Comment by mac2000** [comment]
That's really really helpful, thank you 🙏

Technically I bed that this issue can be closed, because you are 100% right, especially with note about custom Id type resolver, why I did not think about this 🤦‍♂️


May be there should be some note about this like one made for GUID [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/2af9f60aac88ba68d0588eac27df39127061cd12/docs2/site/docs/getting-started/schema-types.md?plain=1#L18)

<img width="869" alt="image" src="https://github.com/user-attachments/assets/981294d7-ce4e-4ccb-87d5-cea983a6c89c">

But according to how much you are better on explaining I won't even try :)

But hopefully this one will help someone in future as well

**Comment by Shane32** [comment]
Considering that it is expected that an ID (which can contain a number or string) would be read with `GetArgument<string>`, it would be logical to provide the conversion in the default set of conversions by GraphQL.NET, and even moreso when Apollo Router actively changes IDs from strings to integers at will.  See PR #4076.

**Comment by Shane32** [comment]
Also see:
- #3933
