### ISSUE TITLE
Question: How to do mutation on types which use interface

### ISSUE THREAD

**Issue by petrovic-ivan** [graphql-dotnet/graphql-dotnet#408]
This question is related to the already opened issue [#58](https://github.com/graphql-dotnet/graphql-dotnet/issues/58) and I understand that this is not supported right now.

Problem is I don't think that I am doing properly because it leads to a lot of code repetition.

Let say that I have class `Car` with property `Maker` type of `IMaker`. Maker is concrete maker which can vary depending on the case (in this example `Ford` and `Dodge`).

```
    public class Car
    {
        public IMaker Maker { get; set; }

        public int Year { get; set; }
    }

    public interface IMaker
    {
        string Model { get; set; }
    }

    public class Ford : IMaker
    {
        public string Model { get; set; }

        public string Address { get; set; }
    }

    public class Dodge : IMaker
    {
        public string Model { get; set; }

        public string Headquarter { get; set; }
    }
```
Now if I want to implement `ObjectGraphType` types for the query it is clear. But what is correct if I want 
to use mutation?

Do I need to implement two times `InputObjectGraphType` for `Car`? Plase see example:

```
    public class CarDodge : InputObjectGraphType
    {
       
        public CarDodge()
        {
            Name = "CarDodge";

            Field<DodgeInputType>("Maker", "The car Dodge maker.");
            Field<IntGraphType>("Year", "The car year.");
        }

    }

    public class CarFord : InputObjectGraphType
    {

        public CarFord ()
        {
            Name = "CarFord";

            Field<FordInputType>("Maker", "The car Ford maker.");
            Field<IntGraphType>("Year", "The car year.");
        }

    }
```

Here only difference is field maker. In one case I have `DodgeInputType` and in another I have `FordInputType`. 

Is this right way to do this?

**Comment by joemcbride** [comment]
Yes, you would need two different inputs if you want to be able to determine a specific type.  That would make it so you have to have a different method for each `IMaker` type though, which wouldn't be very fun.

Are the input values going to be different per `IMaker`?  If not, perhaps you could add a `Type` property to the input and make it more generic.

**Comment by petrovic-ivan** [comment]
Values per `IMaker` will be very different. By adding `Type` property did you mean to add some identifier and based on that deserialize into the desired type? It can work but it will become more complicated once I find nested properties.

**Comment by joemcbride** [comment]
Yes.  Not super elegant but it could work.

```csharp
resolve: context =>
{
  var input = context.GetArgument("input") as Dictionary<string, object>();
  string inputType = input["type"];
  Type type = determineType(inputType);
  var actualInput = context.GetArgument(type, "input") as IMaker;
}
```

You could also smuggle the information as a serialized string, then deserialize in the handler.  Also not super elegant and you wouldn't get any built-in validation.

**Comment by joemcbride** [comment]
Going to close this, though would be interested in hearing if you came up with a good solution.
