### ISSUE TITLE
Backend implementation

### ISSUE THREAD

**Issue by Radiv3** [graphql-dotnet/graphql-dotnet#41]
I'm trying to find out how I can create a custom graphql-dotnet backend, but there is no mention of it as far as I can see? Any pointers on where I can look?

**Comment by joemcbride** [comment]
Are you just trying to create a basic GraphQL server endpoint?  There is a [sample in the codebase](https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.GraphiQL) which runs `GraphiQL`.  Have you seen the [GraphQLController](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Controllers/GraphQLController.cs)?

**Comment by Radiv3** [comment]
Yes, I want to add a endpoint that can receive GraphQL queries from our SPA, and translate the GraphQL to our internal query format, fetch the data, and return it. We're currently do that with OData, but we would love to support GraphQL as well.

The GraphQLController helps a bit, but it still takes a lot of effort to get an overview of how the different parts fit together. I think a description that can help people understand the project would make the barrier for entry a lot lower. I see how much effort that has been put into this, and I would love for this to be widely used, so please take this as constructive feedback!  

To me it looks like the following is needed: 
- create a class that implements IDocumentExecuter.
- create a schema class
- create a query class (only one for all queries?)
- define the graph types that represents our internal schema. 
- Do i need to create a a class that implements ISimpleContainer, or can I use SimpleContainer from the test project?

**Comment by joemcbride** [comment]
Thanks for the feedback.  From your questions it seems you would like more of a "start from scratch" guide on how GraphQL works and how to get it configured with this project.  The README shows everything you should need to get started (creating a schema and executing a query), with the code in the tests/sample project showing a fully working solution with dependency injection.  Some answers inline.

* create a class that implements IDocumentExecuter.
You can technically do this, though there is a `DocumentExecuter` implementation class.  This is all of the core GraphQL logic so doubtful you would ever want to implement this yourself.

* create a schema class
Yes

* create a query class (only one for all queries?)
Yes, your Schema has only one Query object and only one Mutation object.  This is the design of the GraphQL spec.

* define the graph types that represents our internal schema.
Yes

* Do i need to create a a class that implements ISimpleContainer, or can I use SimpleContainer from the test project?
No, you don't need to use `ISimpleContainer` at all.  `ISimpleContainer` represents a dependency injection container.  Using dependency injection is optional.

There are some [other resources out there for learning GraphQL](https://learngraphql.com/) itself, though I found [this video](https://www.youtube.com/watch?v=DNPVqK_woRQ) a nice example of using the JavaScript implementation.  Of course that is JavaScript, though a lot of the concepts apply to the .NET implementation.

Some more detailed docs would certainly be nice, though are not on my radar at the moment.  PRs welcome!

Feel free to post issues with any specific items you run into though.

**Comment by sachinnshah** [comment]
I am new to GraphQL. Do you have any idea about working example.. GraphQL Server in .net and web page in java script ?

**Comment by joemcbride** [comment]
@sachinnshah As mentioned above, have a look at the GraphQLController and GraphiQL project in the codebase.  GraphiQL is a javascript project by the creators of GraphQL that allows you to query a GraphQL api.  https://github.com/graphql/graphiql

**Comment by joemcbride** [comment]
This blog series has a good introduction walkthrough for getting started.  http://fiyazhasan.me/tag/graphql-dotnet/
