### ISSUE TITLE
Batching strategy

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#410]
First call

1. A Collection of users come from the database
2. Per each `UserType` we have the normal properties and complex properties
3. All the normal properties will be called to build the `ListGraphType<UserType>` but not the complex properties marked with `Field<ListGraphType<SettingsType>>().BatchStrategy().Name("..").Resolve("...")` or `Field<SettingsType>().BatchStrategy().Name("..").Resolve("...")`.
4. After finished the normal properties of the list, all the complex properties will be reduced into One per property type, and `ctx.Source.Batching.Ids` property will be added and will be called this way

```
.Resolve(ctx => {
   return _Service.GetUsersByIds(ctx.Source.Batching.Ids)
                We will create a dictionary of <int, object> after call this function.
})
```
5. Then internally each item of the dictionary will be added to the initial  `Field<ListGraphType<SettingsType>>().BatchStrategy().Name("..").Resolve("...")`  and just added to our previous Collection of` ListGraphType<UserType>` so we don't need to do complex async batching or use dataloaders.

I don't really know how this library works but this is the ideas that I can think to resolve the N+1 problem, which I think this should be out of the box. If I did not that explain my thoughts very well please tell me or let's chat about how can I help or something like that..

**Comment by joemcbride** [comment]
Hey, thanks for participating in this project!  We have an issue that is basically this - #264 - which is creating/providing a `DataLoader` like Facebook's.

**Comment by joemcbride** [comment]
Closing this since its duplicate.
