### ISSUE TITLE
Use interface implementing interface lost opportunity to query by fragment

### ISSUE THREAD

**Issue by KvaKoZyaBBrr** [graphql-dotnet/graphql-dotnet#4105]
Hello! I dont know is this a bug or not so it is a question
## Summary
In version 7.2.2 when interfaces cannot implementing another interfaces, we have next schema:
```GraphQl
# Type
type Car implements ICar & _ICar & ICarExt
{
    id: Int
    name: String
    extField: String
}

# Base Interface. Not included ext fields
interface ICar
{
    id: Int
    name: String
}

# Ext interface
interface ICarExt
{
    extField: String
}

# Final interface for implementing
interface _ICar
{
    id: Int
    name: String
    extField: String
}
```
In version 8.2.1 we can do something more pretty:
```GraphQl
# Type
type Car implements _ICar
{
    id: Int
    name: String
    extField: String
}

# Base Interface. Not included ext fields
interface ICar
{
    id: Int
    name: String
}

# Ext interface
interface ICarExt
{
    extField: String
}

# Final interface for implementing
interface _ICar implements ICar & ICarExt
{
    id: Int
    name: String
    extField: String
}
```
But we get error on query
```GraphQl
query{
    cars{
        ... on ICar{
            name
        }
    }
}
```
Error text: "Fragment cannot be spread here as objects of type "_ICar" can never be of type "ICar"".
But I think we can get results as any implementations any deep. Is this bug by new feature or expect behaviour?

**Comment by Shane32** [comment]
The schema configuration is illegal when configured in this manner.  It is required for the implementing types to implement all transitively implemented interfaces.  See spec: https://spec.graphql.org/October2021/#sel-EAHbhBDHAACLA-uB

> Transitively implemented interfaces (interfaces implemented by the interface that is being implemented) must also be defined on an implementing type or interface. For example, `Image` cannot implement `Resource` without also implementing `Node`:
>
> ```gql
> interface Node {
>   id: ID!
> }
> 
> interface Resource implements Node {
>   id: ID!
>   url: String
> }
> 
> interface Image implements Resource & Node {
>   id: ID!
>   url: String
>   thumbnail: String
> }
> ```

We should write a schema validation rule to validate that the schema has been configured properly.  Perhaps also write an optional schema node visitor to apply the transitively implemented interfaces to all implementing types.

**Comment by Shane32** [comment]
For now you will need to explicitly implement `ICar`, `_ICar` and `ICarExt` on `Car`, similar to v7.

**Comment by KvaKoZyaBBrr** [comment]
Oh I get it! I should more attentively work with spec. Thank you for quick answer!

**Comment by KvaKoZyaBBrr** [comment]
@Shane32 In future we need to run TransitiveInterfaceVisitor for object to automatically implement all implemented interfaces included transitive. Right?

**Comment by Shane32** [comment]
No, it's configured to run automatically during schema initialization.

**Comment by KvaKoZyaBBrr** [comment]
Oh, we manually generating schema. Is this safety for us?

**Comment by KvaKoZyaBBrr** [comment]
It look like good but we need try this carefully. Thank you

**Comment by Shane32** [comment]
If you copy the visitor into your codebase, and run it after calling schema.Initialize, it should work and you can test it now before 8.3.0 is released, in case there are any issues.

**Comment by Shane32** [comment]
It is very important not to run the visitor before calling schema.Initialize.
