### ISSUE TITLE
Mapping an Entity Type to a Specific Table in the Database

### ISSUE THREAD

**Issue by enkodellc** [graphql-dotnet/graphql-dotnet#411]
I am attempting to map an Entity Type to a Specific Table in the Database. I want to use a schema called User but map it to the aspnet_Users table in my existing database.

Example: All properties of User will be mapped to columns in a table called "aspnet_Users"

```
modelBuilder.Entity<User>()  
    .ToTable("aspnet_Users");
```
If I use a table called "Users" the entity works fine, but if I try to map it using ToTable I receive the following error:

`"message": "Error trying to resolve user.",`

I am using this repo for testing https://github.com/JacekKosciesza/StarWars and so most of my code is taken from it.

To recreate just duplicate a table, rename it and try to map it with the ToTable extension. Thanks

**Comment by joemcbride** [comment]
`Error trying to resolve user.` means you got an error running your resolver.  Please check the inner exception on the Errors result to find out what you need to fix.  Or you can add a try/catch around your code and find out what the problem is.

**Comment by enkodellc** [comment]
Thanks!
