### ISSUE TITLE
ObjectGraphType as QueryArgument supported ?

### ISSUE THREAD

**Issue by mahald** [graphql-dotnet/graphql-dotnet#412]
I Try to set a ObjectGraphType as input parameter/QueryArgument like this: 
```
    public class SnippetPackage2
    {
        public String Id { get; set; }
    }

    public class SnippetPackageType2 : ObjectGraphType<SnippetPackage2>
    {
        public SnippetPackageType2()
        {
            Name = "SnippetPackage2";

            Field(_ => _.Id, type: typeof(StringGraphType))
                .Description("Unique Key of the element");
        }
    }

...

            FieldAsync<SnippetPackageType>(
            "snippetPackageUpdate",
                arguments: new QueryArguments(
                    new QueryArgument<SnippetPackageType2> { Name = "snippet", Description = "item" },
...
```

however in GqphiQL i can't see the documentation becaus i get following error:

```
Error: Introspection must provide input type for arguments.
    at invariant (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.10.2/graphiql.js:24179:11)
    at getInputType (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.10.2/graphiql.js:29987:29)
    at buildInputValue (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.10.2/graphiql.js:30126:16)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.10.2/graphiql.js:24309:31
    at Array.reduce (<anonymous>)
    at keyValMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.10.2/graphiql.js:24308:15)
    at buildInputValueDefMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.10.2/graphiql.js:30120:36)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.10.2/graphiql.js:30114:15
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.10.2/graphiql.js:24309:31
    at Array.reduce (<anonymous>)
```

Is this supposed to work, im doing something wrong ?

**Comment by joemcbride** [comment]
Input types have to be `InputObjectGraphType` vs. `ObjectGraphType`.

```csharp
public class HumanInputType : InputObjectGraphType
{
    public HumanInputType()
    {
        Name = "HumanInput";
        Field<NonNullGraphType<StringGraphType>>("name");
        Field<StringGraphType>("homePlanet");
    }
}
```

**Comment by cheesemacfly** [comment]
@joemcbride I know this is an old ticket but I was actually wondering why we couldn't use an `ObjectGraphType` as an InputObjectGraphType? It's definitely possible for a type to be used for both a input on a mutation and as result of a query. Is there a way to not have to create 2 separate classes in this case?

**Comment by joemcbride** [comment]
@cheesemacfly The GraphQL spec prescribes these as two different types.  At present they are design as two different classes in this implementation.  There are at least a couple places in the logic that behaves differently based on whether it is an input or an object.

**Comment by cheesemacfly** [comment]
@joemcbride thanks for the answer. Do you have a link to where they behave differently? In my current project, I'm using a generic class and reflection to add the property of my dto to the graphql types. I need to do it twice because of that and I'm trying to find a better way to handle it.
