### ISSUE TITLE
Include path property in error

### ISSUE THREAD

**Issue by mrdezzods** [graphql-dotnet/graphql-dotnet#415]
According to the [specs](http://facebook.github.io/graphql/#sec-Errors) the error object also contains a property `path`. This could be extremely helpful when dealing with form validation error messages specific to a field. Is this already implemented (I don't find anything about it in the source code nor in the docs) or are there plans to do it? 

Thanks in advance

**Comment by joemcbride** [comment]
This is not added yet.  The conventions project added this feature though did not push it upstream.  So could take some guidance from there to complete the feature.
