### ISSUE TITLE
Question: GraphTypeBuild<T> for easier GraphType Building

### ISSUE THREAD

**Issue by JJLost** [graphql-dotnet/graphql-dotnet#416]
I like the library thus far but like many others i am trying to reconcile having to rewrite alot of my objects in the GraphType syntax.  That being said i was trying to find the line between manually writing the class definitions and a more [Conventions](https://github.com/graphql-dotnet/conventions) based approach.  The conventions would require additional dependencies in legacy code if used. 

[Gist of GraphTypeBuilder](https://gist.github.com/JJLost/49c5dc8e7d08d9cffd9b51384083bf6e)

I have built a couple helpers classes to handle the generation of the GraphTypes.  This would give you the ability to dynamically generate a majority of the fields.  If the field is two complex or you dont want to resolve it you can add or alter fields in the inherited class.  Ideally i would like the ability to remove fields if necessary but that is a discussion for another day.

What do you think of this approach?  Do you see any downsides etc....

  My initial thought are im not really a fan of the reflection, but things like [Fast Member](https://github.com/mgravell/fast-member) may speed that up.  Worst case the classes could always be generated if the reflection is a performance it.

**Comment by joemcbride** [comment]
I think what you have in the gist is a fine approach and cuts down on the boilerplate.

I have a PR open to also support the GraphQL Schema syntax and move towards a more MVC endpoint approach.  Would that work for your codebase?  See #362

**Comment by trbngr** [comment]
I've been playing with some experimental syntax as well.

Check it out [here](https://gist.github.com/trbngr/dd6721bc03c8d08750076b309392baf4#file-syntaxtests-cs-L21)

I still need to complete it. But it's not bad for 1.5 hours of hackin ;)

**Comment by holm0563** [comment]
I build a schema generator as well: https://github.com/holm0563/graphql-schemaGenerator

**Comment by sungam3r** [comment]
@JJLost what you are talking about is very similar to [AutoRegisteringObjectGraphType](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs). I will close this issue, feel free to ask questions if you have any.
