### ISSUE TITLE
Possibility to return custom error message

### ISSUE THREAD

**Issue by mahald** [graphql-dotnet/graphql-dotnet#418]
Hi,

It hase become a must have that i can return meaningful errror messages from the graphql api.

AFAIK this is not yet possible.

I thus recommend following new feature:

1. Add a new ExceptionClass Called maybe "GraphQL.CustomException"
2. If this Exception is thrown within a resolver the "Message" of the Exception is displayed
3. This is going to bypass ExposeExceptions as i expect this to be "expected behaivor" and ur custom message may tells u more than anything else.

So i could simply throw a message inside a resolver like:
`
thrown new GraphQL.CustomException($"insufficent permissions, und need the permission {RequiredPermission}");`

and it will be displayed in errors (without Lines)

@joemcbride  What do you think of this feature ? Are u gonna accept a pull request for this ?

**Comment by mahald** [comment]
Note: The example maybe not good as permission are handled out side the resolver. But i may case it would be like:

thrown new GraphQL.CustomException($"insufficent licenses, please buy more licenses in the license menu");

**Comment by joemcbride** [comment]
You can add custom errors in the `ResolveFieldContext`.  I think this should solve your issue?

```csharp
context =>
{
  context.Errors.Add(new ExecutionError("Some Error"));
  return null;
}
```

**Comment by joemcbride** [comment]
See your previous issue: https://github.com/graphql-dotnet/graphql-dotnet/issues/351

**Comment by mahald** [comment]
oops, sorry missed that this was implemented. thanks a lot.
