### ISSUE TITLE
Question: File type for uploaded files

### ISSUE THREAD

**Issue by petrovic-ivan** [graphql-dotnet/graphql-dotnet#419]
I implemented file upload which works but I want to enhance introspection for this mutation. My mutation in server is like in following:

```
            Field<StringGraphType>(
                "uploadFile",
                arguments: new QueryArguments(
                    new QueryArgument<StringGraphType> { Name = "args" }
                ),
                resolve: context => {
                    var files = context.UserContext.As<IFormFileCollection>();

                    SaveFIles(files);

                    return "Success";
                }
            );
```

And my mutation on client is like this:

```
const FileUpload = gql`
mutation ConcreteMutation($args: String) {
  uploadFile(args: $args)
}
`;
```

Here I am calling Apollo mutate:
```
this.apollo.mutate({
      mutation: FileUpload,
      variables: {
        args: 'Test file upload',
        file: event.target.files[0]
      }
    })
```

My questions is how I can provide some information in order to help user to properly consume my mutation? In GraphiQL user cannot play with mutation and there are no any documentation on schema related to how to consume mutation. Basically he will not be able to construct `variables` segment properly.

I would like to be able to add some query argument so, user will be able to get more information. Something like this:

```
            Field<StringGraphType>(
                "uploadFile",
                arguments: new QueryArguments(
                    new QueryArgument<StringGraphType> { Name = "args" },
                    new QueryArgument<FileGraphTpe> { Name = "file" }
                ),
                resolve: context => {
                    var files = context.UserContext.As<IFormFileCollection>();

                    SaveFIles(files);

                    return "Success";
                }
            );
```
Now, in GraphiQL user can see more info. Is it possible to do something like this?

**Comment by joemcbride** [comment]
You can't directly send files as arguments.  This is a limitation of http.  It needs to be sent as a multi-part form.  You can do something like the following though:

https://medium.com/@danielbuechele/file-uploads-with-graphql-and-apollo-5502bbf3941e

Create a custom `NetworkInterface` in Apollo which replaces the files with a unique id.  You could then perhaps use your custom `FieldGraphType` to match up the file with the id.

**Comment by petrovic-ivan** [comment]
Thanks for response. I created dummy `FileGraphType` which can serve as description only.
