### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/graphql-dotnet#420]
I've been playing with implementing Apollo Client compatible subscription support using websockets and now have the basic messages flowing. I was planning on using `Task IDocumentExecutionListener.AfterExecutionAsync(object userContext, CancellationToken token);` to listen for executions of mutations, but it seems that I don't have access to the results of the execution there.

Do I have anyway of listening for mutations? I would also need to know the affected types of the mutation so I can trigger the correct subscriptions.

**Comment by pekkah** [comment]
Got it working but not very cleanly. Is there an easy way to filter object properties based on the selection set of an query? Basically executing but with given result object?

**Comment by joemcbride** [comment]
Can you explain a bit more about what you're trying to do?  Are you trying to follow the official GraphQL spec on subscriptions?

http://facebook.github.io/graphql/#sec-Subscription

**Comment by joemcbride** [comment]
This example is using the JavaScript projects, but shows an app that uses subscriptions:

Blog: https://dev-blog.apollodata.com/tutorial-graphql-subscriptions-server-side-e51c32dc2951
Code: https://github.com/apollographql/graphql-tutorial/tree/t8-end

Note that this project currently does not implement the subscription spec.  So once it does, working with subscriptions should be easier to do.  See  #322

**Comment by pekkah** [comment]
Sorry for being bit unclear what I was doing. That's what you get from hammering the code for too long. Not getting the thoughts out clear anymore. 

I mean I have subscriptions working now with graphql-dotnet and websockets transport compatible with this https://github.com/apollographql/subscriptions-transport-ws. Whole setup is currently working with GraphiQL built on top of .NET Core 2.0.

Currently I'm publishing an event from my mutation resolver and if there are any subscriptions for that event I'm publishing the data associated with the mutation. How I currently handle the subscribing part is very very hacky. Didn't want to mess with the dotnet-graphql code base first.  I'm going to delete the hacky prototype next and implement it properly. To get things right I probably need to implement my own SubscriptionExecuter (similar to DocumentExecuter) which will return an event stream as result. This allows me to have the proper pipeline for filtering the events based on the subscription query and the field selection set.

I'll let you know when I have something to show. As this is an hobby project for me there's no timeline for it.

**Comment by joemcbride** [comment]
> need to implement my own SubscriptionExecuter (similar to DocumentExecuter) which will return an event stream as result

I think this will be the best route to take.  Without changes in the core project, you could also probably inherit from `FieldType` and add a Subscribe field that would be used instead of the existing Resolver.  There is logic in the DocumentExecutor that could be refactored so it could be re-usable.

**Comment by pekkah** [comment]
Here's my current progress
![graphql-subscriptions](https://user-images.githubusercontent.com/822416/30278580-6a4314c8-9713-11e7-8799-2dad12d7ce0a.gif)

I took the `DocumentExecuter` as a base and modified it so that the result of the execution is a Dictionary of streams. Each stream is just an `IObservable<ExecutionResult>`.  When websocket connection is made I check if the requested protocol is "graphql-ws" and then create a connection wrapper. This wrapper will read any messages coming from the client. Currently supporter are init, and start messages. If message is start message I executer the query using the new executer and subscribe to the resulting observable.

Here's the subscription node

```
public class ChatSubscriptions : ObjectGraphType<object>
    {
        private readonly IChat _chat;

        public ChatSubscriptions(IChat chat)
        {
            _chat = chat;
            AddField(new EventStreamFieldType
            {
                Name = "messageAdded",
                Type = typeof(MessageType),
                Resolver = new EventStreamResolver(Subscribe)
            });
        }

        private Task<IObservable<object>> Subscribe(ResolveEventStreamContext context)
        {
            return _chat.JoinAsync();
        }
    }
```
Here's the Chat domain object:

```
public class Chat : IChat
    {
        private readonly IEventAggregator _events;

        public ConcurrentStack<Message> Messages { get; }

        public Chat(IEventAggregator events)
        {
            _events = events;
            Messages = new ConcurrentStack<Message>();
        }

        public void AddMessage(Message message)
        {
           Messages.Push(message);
            _events.Publish("messageAdded", message);
        }

        public Task<IObservable<object>> JoinAsync()
        {
            var subject = _events.Subject("messageAdded");
            return Task.FromResult(subject);
        }
    }
```
I call `Chat.AddMessage` from the mutation node.

Todo

- [ ] transport: unsubscribe
- [ ] executer: clean up and tests
- [ ] transport: query (standard query trough websocket)
- [ ] transport: proper websocket close state handling

**Comment by joemcbride** [comment]
Looking good!

**Comment by joemcbride** [comment]
A couple other thoughts:

* I believe I saw in the Apollo implementation that the `Resolve` method on the Subscription functioned as a data transform.  So it could transform the `Message` payload before it got sent to the client.  So that's an argument for both `Resolve` and `Subscribe` on the `FieldType`.
* Need a way to filter events based on arguments passed in the subscription query.

```csharp
private Task<IObservable<object>> Subscribe(ResolveEventStreamContext context)
{
  return _chat.JoinAsync(context.GetArgument<string>("from"));
}

public Task<IObservable<object>> JoinAsync(string from)
{
    var subject = _events
        .Subject("messageAdded")
        .Where(x => x.From == from);
    return Task.FromResult(subject);
}
```

**Comment by pekkah** [comment]
Each value in the observable returned by `EventStreamResolver.Resolve` goes trough `DocumentExecuter.CompleteValueAsync` and gets wrapped into the `ExecuteResult`. So it uses the FieldType to transform the result. 

You can pass in any arguments your domain requires as longs the result is an `IObservable<object>` from the resolver. `IObservable` makes it quite easy to implement any filtering etc logic. You could even handle the actual creation of the stream in another service and just proxy it trough. The `IEventAggregator` I'm using in the sample is just a simple PubSub service I created to make the testing easier.

**Comment by joemcbride** [comment]
I was thinking more of something like this:

```csharp
Field("messageAdded"
  resolve: context =>
  {
    // convert Message to another data type
    var message = context.Source as Message;
    return new MyOtherClass {  };
  },
  subscribe: context => _chat.JoinAsync(context.GetArgument<string>("channel")));
```

**Comment by pekkah** [comment]
What benefit would that resolve give?

If you wanted transform the results you could do this:

```
private async Task<IObservable<object>> Subscribe(ResolveEventStreamContext context)
        {
            var messages = await _chat.JoinAsync();

            return messages.Select(message => new MyOtherClass());
        }
```
Of course that MyOtherClass would then the passed trought the `CompleteValueAsync`. So it would need  to match the FieldType.

Another option for transforming the result would be when subscribing to the stream. You could specify transformation there before sending to the client.

**Comment by joemcbride** [comment]
Looking again at the reference implementation, that is how it is implemented there.  I would say this is mostly so that the `resolve` doesn't have different behavior when it is a subscription, which could be confusing.  If someone wants to do the transform outside of the resolver that would work perfectly fine as well, since the default behavior would be to just return the object that it is given.

[graphql-js implementation](https://github.com/graphql/graphql-js/blob/eb01a23c578d949ccea2fa2b350e65a3893e6895/src/subscription/subscribe.js#L61-L62)

**Comment by pekkah** [comment]
Yep, I'll change it to execute instead of just complete value.  I'll push the code this week so it's easier to comment on and maybe move it into the main project.

**Comment by pekkah** [comment]
These work now.

```
using System.Threading.Tasks;
using GraphQL.Server.Execution;
using GraphQL.Server.Resolvers;
using GraphQL.Server.Types;
using GraphQL.Types;
using System;
using System.Reactive.Linq;
using GraphQL.Resolvers;

namespace GraphQL.Server.Tests.TestSchema
{
    public class ChatSubscriptions : ObjectGraphType<object>
    {
        private readonly IChat _chat;

        public ChatSubscriptions(IChat chat)
        {
            _chat = chat;
            AddField(new EventStreamFieldType
            {
                Name = "messageAdded",
                Type = typeof(MessageType),
                Resolver = new FuncFieldResolver<Message>(ResolveMessage),
                Subscriber = new EventStreamResolver(Subscribe)
            });

            AddField(new EventStreamFieldType
            {
                Name = "messageAddedByUser",
                Arguments = new QueryArguments(
                    new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id" }
                ),
                Type = typeof(MessageType),
                Resolver = new FuncFieldResolver<Message>(ResolveMessage),
                Subscriber = new EventStreamResolver(SubscribeById)
            });
        }

        private async Task<IObservable<object>> SubscribeById(ResolveEventStreamContext context)
        {
            var id = context.GetArgument<string>("id");

            var messages = await _chat.MessagesAsync();

            return messages.Where(message => message.From.Id == id);
        }

        private Message ResolveMessage(ResolveFieldContext context)
        {
            var message = context.Source as Message;

            return message;
        }

        private async Task<IObservable<object>> Subscribe(ResolveEventStreamContext context)
        {
            return await _chat.MessagesAsync();
        }
    }
}
```

@joemcbride should I make a PR for the subscription executer or would you prefer it as a separate repo/nuget? I was planning to move the websockets transport/protocol code to separate NuGet and release it, but I'm sure the actual subscription executer should be part of this repo.

**Comment by joemcbride** [comment]
Nice work!

> the actual subscription executer should be part of this repo

Agreed, a PR to here will work.

**Comment by junelau** [comment]
Thanks for the subscription executer 😄 

Fwiw, I made a [small chat sample with groups](https://github.com/junelau/graphql-dotnet-subscriptions-websockets/tree/master).

**Comment by pekkah** [comment]
@junelau FYI https://github.com/graphql-dotnet/server

**Comment by oasis1992** [comment]
@joemcbride I used this example to understand subscriptions with an owner, thank you for sharing
https://github.com/apollographql/graphql-tutorial/tree/t8-end

**Comment by joelmandell** [comment]
Hello. I am in need to stick to .NET 4.5.2 as highest currently, therefore I use System.Net.WebSockets.
Trying to wrap my head around how to implement the subscription functionality.
I just dont know really where to start.

**Comment by joemcbride** [comment]
@joelmandell I'm not familiar with using WebSockets in 4.5.2.  What you need to implement depends on the JavaScript client you're using.  If using Apollo, this is the server protocol that client expects:

https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md
