### ISSUE TITLE
GraphQL 0.17.3 still cannot install into .net core 2.0 app.

### ISSUE THREAD

**Issue by mokeyish** [graphql-dotnet/graphql-dotnet#423]
PS E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest> dotnet add package GraphQL --version 0.17.3
  Writing C:\Users\YISH\AppData\Local\Temp\tmp1689.tmp
info : Adding PackageReference for package 'GraphQL' into project 'E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj'.
log  : Restoring packages for E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj...
warn : Package 'System.Reflection.TypeExtensions 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
error: Detected package downgrade: System.Reflection.TypeExtensions from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.
error:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> NETStandard.Library (>= 1.6.1) -> System.Linq.Expressions (>= 4.3.0) -> System.Reflection.TypeExtensions (>= 4.3.0)
error:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> System.Reflection.TypeExtensions (>= 4.0.0)
error: Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different version.
error:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> Newtonsoft.Json (>= 9.0.1) -> Microsoft.CSharp (>= 4.0.1) -> System.Reflection.TypeExtensions (>= 4.1.0)
error:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> System.Reflection.TypeExtensions (>= 4.0.0)
error: Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different version.
error:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> Newtonsoft.Json (>= 9.0.1) -> System.Dynamic.Runtime (>= 4.0.11) -> System.Reflection.TypeExtensions (>= 4.1.0)
error:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> System.Reflection.TypeExtensions (>= 4.0.0)
error: Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different version.
error:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> Newtonsoft.Json (>= 9.0.1) -> System.Linq.Expressions (>= 4.1.0) -> System.Reflection.TypeExtensions (>= 4.1.0)
error:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> System.Reflection.TypeExtensions (>= 4.0.0)
info : Package 'GraphQL' is compatible with all the specified frameworks in project 'E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj'.
info : PackageReference for package 'GraphQL' version '0.17.3' added to file 'E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj'.
PS E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest> dotnet restore
  Restoring packages for E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj...
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : warning NU1701: Package 'System.Reflection.TypeExtensions 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605: Detected package downgrade: System.Reflection.TypeExtensions from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version. \r
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> NETStandard.Library (>= 1.6.1) -> System.Linq.Expressions (>= 4.3.0) -> System.Reflection.TypeExtensions (>= 4.3.0) \r
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> System.Reflection.TypeExtensions (>= 4.0.0)
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605: Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different version. \r
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> Newtonsoft.Json (>= 9.0.1) -> Microsoft.CSharp (>= 4.0.1) -> System.Reflection.TypeExtensions (>= 4.1.0) \r
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> System.Reflection.TypeExtensions (>= 4.0.0)
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605: Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different version. \r
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> Newtonsoft.Json (>= 9.0.1) -> System.Dynamic.Runtime (>= 4.0.11) -> System.Reflection.TypeExtensions (>= 4.1.0) \r
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> System.Reflection.TypeExtensions (>= 4.0.0)
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605: Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different version. \r
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> Newtonsoft.Json (>= 9.0.1) -> System.Linq.Expressions (>= 4.1.0) -> System.Reflection.TypeExtensions (>= 4.1.0) \r
E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj : error NU1605:  QLTest (>= 1.0.0) -> GraphQL (>= 0.17.3) -> System.Reflection.TypeExtensions (>= 4.0.0)
  Generating MSBuild file E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\obj\QLTest.csproj.nuget.g.props.
  Restore failed in 282.63 ms for E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj.
PS E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest>

**Comment by joemcbride** [comment]
Please see #402 for a fix.
