### ISSUE TITLE
The type: [object] cannot be coerced effectively to a GraphQL type

### ISSUE THREAD

**Issue by PiotrFerenc** [graphql-dotnet/graphql-dotnet#426]
plz help :) 

```
    public class AnimalType
    {
        public int AnimalTypeId { get; protected set; }
        public string Name { get; protected set; }
        public string Code { get; protected set; }

        private AnimalType() { }
}
```

```
    public class Animal  
    {
        public int Id { get; set; }
        public int AnimalTypeId { get; set; }
        public AnimalType animalType { get; set; }
}
```

![obraz](https://user-images.githubusercontent.com/30370747/30376807-eb4ad8aa-988d-11e7-8699-e8cf3ed1c33c.png)

**Comment by jquense** [comment]
You need to explicitly tell the field what graph type it is for complex types. As well as define an Animal graph type that  extend ObjectGraphType see the various examples and docs for examples on objects

**Comment by RobinHoody** [comment]
> You need to explicitly tell the field what graph type it is for complex types. As well as define an Animal graph type that extend ObjectGraphType see the various examples and docs for examples on objects

Wouldn't a link to the examples you're referencing above help the original poster here?

**Comment by timvandesteeg** [comment]
If you need to generate a type for an enum, do the following:

1. create an EnumerationGraphType class for the enum
```
public class MyStatusGraphQLEnum : EnumerationGraphType<MyStatusEnum>
    {
    }
```
2. Add the field as complex type to your graphType
```
Field<MyStatusGraphQLEnum>("Status");
```
More info: https://graphql-dotnet.github.io/docs/getting-started/schema-types
