### ISSUE TITLE
Query Batching support

### ISSUE THREAD

**Issue by OneCyrus** [graphql-dotnet/graphql-dotnet#429]
Any plans for query batching support? just batching from http requests and not batching in the backend.

https://blog.graph.cool/improving-performance-with-apollo-query-batching-66455ea9d8bc

**Comment by joemcbride** [comment]
This IS supported today.  You just need to write your http endpoint to support it. See #398

**Comment by jquense** [comment]
If anyone is looking for an example of code that does this check out https://github.com/graphql-dotnet/relay/blob/master/src/GraphQL.Relay/Http/RequestExecutor.cs and surrounding code.
