### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by chmontgomery** [graphql-dotnet/graphql-dotnet#43]
Do you have plans to release a version that supports DNXCore,Version=v5.0? Are there any external dependencies blocking this?

**Comment by joemcbride** [comment]
I would certainly like to support DNX.  I haven't tried it yet.  The main dependency that could hold things up is the Antlr runtime.

**Comment by chmontgomery** [comment]
it *seems* like Antlr4 already supports this as of `v4.5-alpha003`: https://github.com/tunnelvisionlabs/antlr4cs/issues/126

**Comment by joemcbride** [comment]
:+1: Right now my highest priorities are:

* Failing CI when tests fail due to test runner crashing
* Adding validation

Going to update this issue title to reflect this request.  You're welcome to take a stab at it!

**Comment by alexsandro-xpt** [comment]
+1

**Comment by we4sz** [comment]
+1

**Comment by natemcmaster** [comment]
Unless the dependency on Antlr4 is removed, this will be hard to complete before Antlr also supports .NET Core. See https://github.com/antlr/antlr4/issues/1142

Also, DNX [is being retired](https://github.com/aspnet/dnx#dnx-retired). It's better to support its replacement, dotnet cli. See https://github.com/dotnet/cli.

**Comment by baluubas** [comment]
If someone is really itching (like me) to make the move to .NET core then I've made a quick and ditry port based on this fork of antlr4: https://github.com/lecode-official/antlr4

You can find it here:
https://www.myget.org/feed/Packages/baluubas

Needless to say, is comes with a huge disclaimer.

**Comment by tlil87** [comment]
@baluubas also, have a look at: https://github.com/graphql-dotnet/graphql-dotnet/pull/127 :)

**Comment by baluubas** [comment]
@tlil87 Awesome, looking forward to a .NET core build

**Comment by joemcbride** [comment]
Have an alpha nuget up on the AppVeyor feed for .NET Core support if anyone wants to give it a whirl.

`0.12.0-alpha-510`

https://ci.appveyor.com/nuget/graphql-dotnet
https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/build/0.12.0.510/artifacts

I've tried it with a .NET 4.6.1 console app and a .NET Core console app.

/cc @tlil87 @baluubas @jquense

**Comment by joemcbride** [comment]
I went ahead and published `0.12.0-alpha-511` to nuget as well.

**Comment by baluubas** [comment]
0.12.0-alpha-511 works perfectly in my core solution, no hiccups so far.

**Comment by tlil87** [comment]
Works great here as well - will keep testing it and report if I see any issues :+1:
