### ISSUE TITLE
Subscription Transport

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/graphql-dotnet#430]
I have something that works with apollo subscription-transport-ws client including a GraphiQL sample.

I could put it under my own account on GitHub but as there seems to be nice organization here "graphql-dotnet" it might be nice to put it under here. Might get some push to actually implementing the rest of the protocol messages. 

Apollo just announced their new apollo link based extension model but it seems to still use the same subscription-transport-ws client. Of course in future we could implement our own "apollo link" client and server based on SignalR (Have been playing with the Core release a bit but things seems to be still moving a lot. They promise release version with .NET Core 2.1).

**Comment by joemcbride** [comment]
How about a `subscriptions-transport-ws` repo under this org?

**Comment by pekkah** [comment]
Yep, will post any problems importing the codebase here https://github.com/graphql-dotnet/subscriptions-transport-ws/issues/1
