### ISSUE TITLE
GraphQL spec and patent issues

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/graphql-dotnet#433]
You can follow the whole conversation at https://github.com/facebook/graphql/issues/351

Here's the issue in short

> Facebook’s GraphQL spec doesn’t grant a patent license. Therefore, for reasons as set forth below, most GraphQL users infringe Facebook’s patents.

**Comment by joemcbride** [comment]
Thanks, I was aware of it. Good to have an issue here though.  Hopefully they have some good news soon.

**Comment by joemcbride** [comment]
Looks like they have issued new licenses that should alleviate any patent issues. 🎉 

https://medium.com/@leeb/relicensing-the-graphql-specification-e7d07a52301b
https://dev-blog.apollodata.com/facebook-grants-full-patent-rights-to-all-graphql-users-2c41abc6df66

**Comment by pekkah** [comment]
Yep. That should "fix" the issue
