### ISSUE TITLE
Argument with decimal crashing on a computer with non dot delimiter for decimals

### ISSUE THREAD

**Issue by eXon** [graphql-dotnet/graphql-dotnet#438]
As a follow up to #302, when the argument of a query is a decimal or float, if the server is configured with a language using a non dot delimiter for decimals, as soon as your argument has a decimal, it will crash.

Example:

```csharp
Field<ListGraphType<FranchiseType>>(
    "franchises",
    resolve: context => new Restaurant().Franchises,
    arguments: new QueryArguments(
        new QueryArgument<DecimalGraphType> { Name = "latitude" },
        new QueryArgument<DecimalGraphType> { Name = "longitude" }
    )
);
```

This is crashing on my computer configured with a `fr-CA` locale. If I add this code, it will work:

```csharp
// Fix decimals for GraphQL
Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");
```

There is probably a few `.ToString()` missing the Invariant property.

**Comment by eXon** [comment]
I'm using `v0.17.3`

**Comment by joemcbride** [comment]
This should be fixed when #434 is merged.

**Comment by joemcbride** [comment]
This should be fixed in this release - feel free to re-open if you find an issue.  https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v2.0.0-alpha-793

**Comment by eXon** [comment]
Great thanks for the follow up! 👍
