### ISSUE TITLE
Expose GraphQL & GraphiQL Middlewares

### ISSUE THREAD

**Issue by claylaut** [graphql-dotnet/graphql-dotnet#444]
Hi,

Can you expose middleware extensions for .NET Core. So we don't have to copy/paste from the examples and if you have any fixes everyone will benefit from them.

Ideally, we will have the below usage out of the box (or something similar):
```cs
app.UseGraphQL(new GraphQLOptions
{
    GraphQLPath = "/graphql" ,
    Schema = StarWarsSchema
});

app.UseGraphiQL(new GraphiQLOptions()
{
    GraphiQLPath = "/graphiql"
});
```
https://github.com/wesamco/ASP.Net-Core-GraphQL-Middleware

Thanks in advance,
Clayton

**Comment by Odonno** [comment]
That is pretty much exactly what every developer want when starting a new project.

**Comment by pekkah** [comment]
https://github.com/graphql-dotnet/server/blob/develop/README.md

**Comment by joemcbride** [comment]
Yes, this is no covered by the server project.
