### ISSUE TITLE
Nullable types

### ISSUE THREAD

**Issue by damithashyamantha** [graphql-dotnet/graphql-dotnet#445]
How to retrieve nullable types?

**Comment by joemcbride** [comment]
Can you be more specific?  Perhaps post your question on stackoverflow?

**Comment by damithashyamantha** [comment]
Lets say I have a model class as follows.

public class Model
{
public int id{get; set;}
public Datetime? CreatedOn{get; set;}
}

how do we fetch this date field?

Thanks,

**Comment by joemcbride** [comment]
Here are the docs on how to use this library.

http://graphql-dotnet.github.io/graphql-dotnet/

**Comment by damithashyamantha** [comment]
nullable: true great thanks, mate. Cheers!
