### ISSUE TITLE
GraphQL -Version 2.0.0-alpha-797 still cannot install into .net core 2.0 app

### ISSUE THREAD

**Issue by mokeyish** [graphql-dotnet/graphql-dotnet#446]
vs2017 15.3.5;
TargetFramework:netcoreapp2.0;
here is the error output.
PM> Install-Package GraphQL -Version 2.0.0-alpha-797
  GET https://api.nuget.org/v3/registration3-gz-semver2/graphql/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/graphql/index.json 233ms
Restoring packages for E:\WorkSpace\Visual Studio 2017\Projects\QLTest\QLTest\QLTest.csproj...
Package 'System.Reflection.TypeExtensions 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
Install-Package : Detected package downgrade: System.Reflection.TypeExtensions from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different ve
rsion. 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> NETStandard.Library (>= 1.6.1) -> System.Linq.Expressions (>= 4.3.0) -> System.Reflection.TypeExtensions (>= 4.3.0) 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> System.Reflection.TypeExtensions (>= 4.0.0)
At line:1 char:1
+ Install-Package GraphQL -Version 2.0.0-alpha-797
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different ve
rsion. 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> Newtonsoft.Json (>= 9.0.1) -> Microsoft.CSharp (>= 4.0.1) -> System.Reflection.TypeExtensions (>= 4.1.0) 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> System.Reflection.TypeExtensions (>= 4.0.0)
At line:1 char:1
+ Install-Package GraphQL -Version 2.0.0-alpha-797
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different ve
rsion. 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> Newtonsoft.Json (>= 9.0.1) -> System.Dynamic.Runtime (>= 4.0.11) -> System.Reflection.TypeExtensions (>= 4.1.0) 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> System.Reflection.TypeExtensions (>= 4.0.0)
At line:1 char:1
+ Install-Package GraphQL -Version 2.0.0-alpha-797
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different ve
rsion. 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> Newtonsoft.Json (>= 9.0.1) -> System.Linq.Expressions (>= 4.1.0) -> System.Reflection.TypeExtensions (>= 4.1.0) 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> System.Reflection.TypeExtensions (>= 4.0.0)
At line:1 char:1
+ Install-Package GraphQL -Version 2.0.0-alpha-797
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Detected package downgrade: System.Reflection.TypeExtensions from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different ve
rsion. 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> System.Reactive.Core (>= 3.1.1) -> System.Dynamic.Runtime (>= 4.0.11) -> System.Reflection.TypeExtensions (>= 4.1.0) 
 QLTest (>= 1.0.0) -> GraphQL (>= 2.0.0-alpha-797) -> System.Reflection.TypeExtensions (>= 4.0.0)
At line:1 char:1
+ Install-Package GraphQL -Version 2.0.0-alpha-797
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'QLTest'.
At line:1 char:1
+ Install-Package GraphQL -Version 2.0.0-alpha-797
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.0139843

**Comment by joemcbride** [comment]
That version does not target 2.0 (look at the dependencies on nuget.org).  Please stop opening new issues in regards to this.

**Comment by pekkah** [comment]
Version GraphQL -Version 2.0.0-alpha-800 has the new target
