### ISSUE TITLE
The Nuget package doesn"t match the source and example

### ISSUE THREAD

**Issue by sergejacquemindfb** [graphql-dotnet/graphql-dotnet#448]
In the 0.17.3 nuget version, there's no` static ISchema For(string[] typeDefinitions, Action<SchemaBuilder> configure = null)` method (or its overload).

I also tried 0.17.2 with the same result.

**Comment by joemcbride** [comment]
Use the latest pre-release.  You can also read the docs for alternatives.

http://graphql-dotnet.github.io/graphql-dotnet/

**Comment by n-ate** [comment]
It looks like this may be version: **0.16.0.1140**, not **0.17.2.752**

**Comment by sungam3r** [comment]
Is this issue still actual?

**Comment by sungam3r** [comment]
Closed as obsolete/resolved issue. Feel free to reopen.
