### ISSUE TITLE
Connection causes Introspection Failure

### ISSUE THREAD

**Issue by wakemaster39** [graphql-dotnet/graphql-dotnet#451]
I am trying to implement a paged list return. From the Facebook graphql [documentation](http://graphql.org/learn/pagination/) the recommended method seems to be to use a Connection. When I attempt to use a Connection, I am getting an error on introspection of the schema.

`{GraphQL.ExecutionError: Error trying to resolve type. ---> GraphQL.ExecutionError: Cannot return null for non-null type. Field: type, Type: __Type!.
   at GraphQL.DocumentExecuter.<CompleteValueAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.DocumentExecuter.<ResolveFieldAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---}`

My types are as follows:

```   
 public class WeatherForecastType : ObjectGraphType<SampleDataController.WeatherForecast>
     {
        public WeatherForecastType()
        {
            Name = nameof(SampleDataController.WeatherForecast);

            Field(w => w.DateFormatted).Description("The Date of the Forcecast");
            Field(w => w.Summary).Description("Forecast summary");
            Field(w => w.TemperatureC).Description("Temperature in Celcius");
            Field(w => w.TemperatureF).Description("Temperature in Farenheit").Name("test");
        }
    }
```

SampleDataController.WeatherForecast is just a POCO with the field names shown.

```
public class JobTrackingQueueQuery : ObjectGraphType<object>
{
    private static string[] Summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    public JobTrackingQueueQuery()
    {
        Name = "Query";
            
        Connection<WeatherForecastType>()
            .Name("weatherForecasts")
            .Description("Test")
            .Resolve(context =>
            {
                // resolve code
            });
    }
}
```

If I simply change the Connection to a Field the code is working and a GraphiQL interface can execute introspection without an issue. I am trying to figure out if there is something missing or drastically changed in the master branch vs 0.17.3. I am trying to go over the unit tests and see what is different between my entry and it, but at this point it eludes me.

**Comment by holm0563** [comment]
I'm having the same issue. So far I'm hoping its an issue in the master branch but I haven't yet tried removing all custom endpoints from our project.

**Comment by wakemaster39** [comment]
The issue was related to the dependency injection. I needed to ensure I added the Relay types so that they could be resolved.

` 
services.AddTransient(typeof(ConnectionType<>));
services.AddTransient(typeof(EdgeType<>));
services.AddTransient<PageInfoType>();
`

**Comment by SimonCropp** [comment]
@joemcbride shouldnt handling of the above types be an internal library concern?

**Comment by benmccallum** [comment]
I was using `GraphQL.Server.GraphQLBuilderExtensions::AddRelayGraphTypes` for this purpose. If this lands, can we go remove that extension from over in the server src?
