### ISSUE TITLE
Missing DOC chapter :)

### ISSUE THREAD

**Issue by patsadow2** [graphql-dotnet/graphql-dotnet#453]
Hello,

Where is a section how to usage it ?

We are not Gods :)

Sample query: POST/GET

**Comment by joemcbride** [comment]
There are several docs showing how to use this project.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/README.md
http://graphql-dotnet.github.io/graphql-dotnet/
https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.GraphiQLCore


If you’re looking for more detailed learning of GraphQL in general, see the Facebook docs.

http://graphql.org/learn/
