### ISSUE TITLE
Object Extensions ConvertValue attempting to convert values it doesn't need too

### ISSUE THREAD

**Issue by wakemaster39** [graphql-dotnet/graphql-dotnet#457]
I am running into an issue of enumeration types on inputs for arguments and deserialization when using get arguments. I am attempting to add ordering information into a query to get ordered results. The code in my query is:
```
Field<HumanType>()
    .Name("humansTest")
    .Description("Test")
    .Argument<ListGraphType<OrderingInfoType<HumanOrderInfoType>>>("orderBy", "Ordering")
```

The related classes are:

```
public class OrderingInfoType<TOrderEnum> : InputObjectGraphType
    where TOrderEnum : GraphType
{
    public OrderingInfoType()
    {
        Name= string.Format("{0}Connection", typeof(TOrderEnum).GraphQLName());
        Field<NonNullGraphType<TOrderEnum>>()
            .Name("sort");
        Field<Direction>()
            .Name("direction");
    }
}
public class OrderingInfo
{
    public PropertyMappingValue Sort { get; set; }
    public DirectionEnum Direction { get; set; }
}

public class HumanOrderInfoType : EnumerationGraphType
{
    public WeatherForecasteOrderType()
    {
        AddValue(new EnumValueDefinition
        {
            Name = nameof(OrderProperties.TemperatureC).ToCamelCase(),
            Description = "",
            Value = new PropertyMappingValue(new List<string> { nameof(SampleDataController.WeatherForecast.TemperatureC)})
               });
    }
}

public class PropertyMappingValue
{
    public bool Revert { get; set; }
    public PropertyMappingValue()
    {}
     public PropertyMappingValue(bool revert = false)
     {
        Revert = revert;
      }
}

```

I am getting a object null reference except and I have tracked it down to
https://github.com/graphql-dotnet/graphql-dotnet/blob/216739246c98be15f5a43f9535a40fea6d08e9fd/src/GraphQL/ObjectExtensions.cs#L130-L150

In this case given the above, the value input has a type of `PropertyMappingValue` and the call of `value.ToString()` is just returning the object name. Then calling convert fails because it doesn't know about the type `PropertyMappingValue`. 

In lines 134 to to 137, if the type being passed in is a datetime you just return the value. Is there some reason that this cannot be changed as follows? All the tests still pass and I am happy to submit the pull request, I just wanted to make sure there wasn't a reason to not make the change. This would stop unnecessary conversion of types and failures to convert to types that the system doesn't need to know about.

```
if (value.GetType() == fieldType)
{
    return value;
}
```

**Comment by joemcbride** [comment]
Hey, it was never intended for the `Value` property of the `EnumerationGraphType` to have any value other than a primitive value (string, int, long, etc.) so I'm not surprised you're hitting some issues.

> Is there some reason that this cannot be changed as follows?

Not as far as I'm aware.

**Comment by sungam3r** [comment]
@wakemaster39 Now `ObjectExtensions.ConvertValue` calls `ValueConverter.ConvertTo` which in turn calls `if (targetType.IsInstanceOfType(value)) return value;` so I think this issue has been solved.
