### ISSUE TITLE
Add support for apollo tracing

### ISSUE THREAD

**Issue by jonaskello** [graphql-dotnet/graphql-dotnet#459]
This would be useful in order to get tracing data from the server. Several other servers have integrated it (Node, Ruby, Scala, Java, and Elixir). For more info see this post:

https://dev-blog.apollodata.com/exposing-trace-data-for-your-graphql-server-with-apollo-tracing-97c5dd391385

**Comment by joemcbride** [comment]
Agreed. We are tracking that with #381
