### ISSUE TITLE
Passing variables to executor.

### ISSUE THREAD

**Issue by LogikBlitz** [graphql-dotnet/graphql-dotnet#46]
So this is a question as to how you pass variables.

Following the demo in the repo i have the following query object:

```
 public class GraphQlQuery
    {
        public string Query { get; set; }
        public string Variables { get; set; }
    }
```

Processing of the query:
```
        public async Task<IHttpActionResult> Query(GraphQlQuery query)
        {
            var input = new Inputs();
            var responseModel = await Execute(new MediaSchema(), null, query.Query, inputs: input);
            return Ok(responseModel);
        }

        private async Task<ExecutionResult> Execute(
            Schema schema,
            object rootObject,
            string query,
            string operationName = null,
            Inputs inputs = null)
        {
            var executer = new DocumentExecuter();

            return await executer.ExecuteAsync(schema, rootObject, query, operationName, inputs);
        }

```

And this is the actual Query from the GrahiQl IDE
```
query getSomeMedia($page:Int!){
  allMedia(pageSize:$page, starts:"P"){
    ...mediaInfo,
    articles(amount:2){
      articleId
    }
  }
}

fragment mediaInfo on Media{
  id
  name
  mediaType
  customerSpecific
}

VARIABLES
{
   "page":10
}

```
So how do i pass the variables on to the executor?

I have tried a number of variations to get the system to handle the variables, and also looked into the source and tests as to how to add the variables to the executor, but in vain.
Help is very much appreciated.

And it is an awesome work you are doing here. Kudos :+1:

**Comment by LogikBlitz** [comment]
Just be explicit. 
The variables are present in the QueryObject, the question is how to pass it in to the Executor in a proper manner.

**Comment by nmaait** [comment]
For ease of use I changed the Variable property to a Dictionary<string, object>.

    [DataContract]
    public class GraphQLQuery
    {
        [DataMember(Name = "query")]
        public string Query { get; set; }
        [DataMember(Name = "variables")]
        public Dictionary<string, object> Variables { get; set; }
    }

Then Inputs can take Variables in its constructor.

        public async Task<IHttpActionResult> Query(GraphQlQuery query)
        {
            var input = query.Variables != null ? new Inputs(query.Variables) : null;
            var responseModel = await Execute(new MediaSchema(), null, query.Query, inputs: input);
            return Ok(responseModel);
        }

**Comment by joemcbride** [comment]
The suggestion above should work. You may also try the 'ToInputs' extension method on string, which tries to handle nested complex objects.

**Comment by LogikBlitz** [comment]
> You may also try the ToInputs extension method on string, which tries to handle nested complex objects.

That indeed did the trick, and it now works like a charm.
I chose to now change the input to being a dict, to preserve compatibility and just passing a string.

@joemcbride I am keen on writing a guide as to how to build a graphQl server using this lib.
I could do it on code project but would rather do it here on a wiki and link to a repo containing the full source in steps.
Since this a learning progress for me it will also allow for easy updating of possible misconceptions and alike if we do it on the wiki.
Is that something you are interested in?

Thanks again. Your responses saved my day.

**Comment by LogikBlitz** [comment]
I am closing the issue and moving my question as to creating a wiki into a more direct PM to @joemcbride

**Comment by joemcbride** [comment]
@LogikBlitz That sounds pretty good.  The wiki is enabled if you want to add some pages - https://github.com/graphql-dotnet/graphql-dotnet/wiki

**Comment by TLogik** [comment]
I'm pretty busy at work and such but I'll slowly start adding to the wiki. Expect a couple of weeks before completion. Hopefully sooner but time has a tendency to fly fast😏
