### ISSUE TITLE
Limit possible values of an InputObjectGraphType's Field

### ISSUE THREAD

**Issue by ceferrari** [graphql-dotnet/graphql-dotnet#461]
Is it possible to limit possible values of an InputObjectGraphType's Field? Something like:

`Field<StringGraphType>("Status").Accepts(new[] { "Active", "Paused", "Closed" });`

**Comment by joemcbride** [comment]
I would suggest to use an enumeration for that.

```csharp
private enum Status
{
  Active,
  Paused,
  Closed
}

public class StatusEnum : EnumerationGraphType<Status>
{
    public StatusEnum()
    {
        Name = "StatusEnum";
    }
}
```

**Comment by ceferrari** [comment]
Thank you for your response but it produced the following error:

`TypeError: Cannot read property 'kind' of null`

**Comment by joemcbride** [comment]
Are you using DI?  Did you register the type with your container?

**Comment by ceferrari** [comment]
Registering the enum within my container made the error disappear.

Thank you @joemcbride !

**Comment by ceferrari** [comment]
@joemcbride Could you help me again please? 

Now I am trying to read the values of the field.

I am implementing a filter logic using aPredicate Builder and I need those values to build the predicate.

Like this:

```
public override Expression<Func<Product, bool>> GetExpression()
        {
            var predicate = PredicateBuilder.New<Product>(true);

            if (STATUS_FIELD_VALUE == Status.Active)
                predicate.And(x => x.Status.Equals("active"));
            else if (STATUS_FIELD_VALUE == Status.Paused)
                predicate.And(x => x.Status.Equals("paused"));
            else if (STATUS_FIELD_VALUE == Status.Closed)
                predicate.And(x => x.Status.Equals("closed"));

            return predicate;
        }
```

How can I access the STATUS_FIELD_VALUE?

**Comment by joemcbride** [comment]
I can't help much with that code since that is not related to this project and I have no context.  Are you asking how you get the value from the input?  What does your `InputObjectGraphType` look like?

This is how I would get an input object in a GraphQL resolver (see [Mutations](http://graphql-dotnet.github.io/graphql-dotnet/getting-started#mutations)).

```csharp
public class MyInputType : InputObjectGraphType
{
    public MyInputType()
    {
      Name = "MyInput";
      Field<StatusEnum>("Status");
    }
}

public class MyInputClass
{
    public Status Status { get; set; }
}

public class SomeObjectType : ObjectGraphType
{
    public SomeObjectType()
    {
        Name = "SomeObject";
        Field<StringGraphType>(
            "something",
            arguments: new QueryArguments(new QueryArgument<MyInputType>{ Name = "input" })
            resolve: context =>
            {
              var input = context.GetArgument<MyInputClass>("input");
              return "something";
            });
    }
}
```

**Comment by ceferrari** [comment]
I would like to access input.Status or input["Status"] in "resolve: context" somehow.
