### ISSUE TITLE
Should the Relay-related types be migrated to graphql-dotnet/relay?

### ISSUE THREAD

**Issue by MFFoX** [graphql-dotnet/graphql-dotnet#462]
This conversation was started in https://github.com/graphql-dotnet/graphql-dotnet/issues/352. The options as I see it are:

- Keep the types in this repository and add documentation and basic support
- Move them to graphql-dotnet/relay 

My opinion is favoring the first option. But, the burden of support shouldn't be on @joemcbride  and it doesn't seem like issues related to the relay types are getting much attention. With that being said, it might make sense to go with option two so we can refocus support and possibly growth.

As a side note, I am starting this conversation because I'd like to open up more conversations (and possibly PRs) about Connections but I'd like to do it in the most fitting place.

**Comment by joemcbride** [comment]
Thoughts on this @jquense, as you are the owner of the relay project.

**Comment by jquense** [comment]
Its ok with me, but there is a niceness to having the Object type have a connection builder, as a first class API. That may be addressable tho, it's already a bit annoying that `Connection` and `Field` so easily diverge, maybe it'll end up being neater to handle it outside the API here...

**Comment by Shane32** [comment]
Personal opinion: I like it as-is, with some basic graph type implementations available in the base project, and all other functionality in a separate repo, similar to data loader support.

As there has been no comments in > 5 years, I'm closing.

**Comment by sungam3r** [comment]
Agree. Maybe some day we will reorganize code across repos but not now.
