### ISSUE TITLE
Using with Angular Apollo Client

### ISSUE THREAD

**Issue by pwfraley** [graphql-dotnet/graphql-dotnet#463]
Hi,

I am running into a weird issue here:

We switched our GraphQL Server from NodeJS Apollo Server to C# graphql-dotnet.  The GraphIQL works fine and we can query the Server, but when we send the same query from our Angular app, the query object in the controller is null.  Looking at what the browser says it sends, both generated queries look the same.  Did someone here have the same issue?

TIA
Patrick

**Comment by hfroliveira** [comment]
Hello,

maybe this can help, this query was sent using Postman with content-type: application/json.
 
```
 {
 "Query": "query getCharacterById($characterId: String!) { character(Id: $characterId) { name friends { name } } }",
 "Variables": "{ characterId: \"15\"	}"
 }
```

Using Fiddler to inspect the request sent by GraphiQL you will be able to see the same kind of data.
So the query typed using GraphiQL is a bit different than the one sent throught the wire.

**Comment by joemcbride** [comment]
This can happen if there is some exception or if you are using Dependency Injection and haven’t registered all of your types with the container.  Try setting the ExposeExceptions property on the ExecutionOptions and printing your Schema with SchemaPrinter and look for missing types.

**Comment by kaffeeserver** [comment]
Hey, well what is really weird (I am answaering for pwfraley btw) is that the query works when we put it in the graphiql web interface (copied from our angular app).  So I do not think it has to do with the types.  Also when we debug the server, the first line in the controller which checks if the query object is null, fails because the query object is null.

The query object comes from:

        public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
        {            
            if (query == null) { 
                throw new ArgumentNullException(nameof(query)); 
            }
and it throws the exception, but only if the query comes from angular, if we use the graphiql interface it works fine.

**Comment by joemcbride** [comment]
Gotcha, that is higher up the chain than I was thinking, so that isn’t hitting any code from this project.  I would look at the HttpContext directly and verify what is being sent to the server.

**Comment by pwfraley** [comment]
That is what we checked and it seems identical.  Just was hoping someone had used this server with the angular apollo client and had a quick anser.  Thanks for the help!

**Comment by Keeo** [comment]
Hi, It is long shot but I think you hit the same issue as I while implementing this with apollo. GraphQLQuery should look like this - note that **Variables** are type **Inputs**:
```csharp
public class GraphlqlQuery
{
    public string OperationName { get; set; }
    public string NamedQuery { get; set; }
    public string Query { get; set; }
    public Inputs Variables { get; set; }
}
```

**Comment by joemcbride** [comment]
@Keeo That's not what you want.  You want the `Variables` to come in as its raw form and use the `.ToInputs` extension method.  That extension method will convert the JSON.NET Types to their .NET equivalent.  Otherwise you can get some unwanted behavior since the core GraphQL engine doesn't understand JSON.NET types.

**Comment by pwfraley** [comment]
The Problem is that APollo Client sends the Variables not as strings, but as JSON, so the definition

    public class GraphlqlQuery
    {
        public string OperationName { get; set; }
        public string NamedQuery { get; set; }
        public string Query { get; set; }
        public string Variables { get; set; }
    }

fails.  Will try Keeo suggestion and see if this works.

**Comment by joemcbride** [comment]
Take a look at this example.

https://github.com/graphql-dotnet/graphql-dotnet/blob/85bc995e2bc8246592feca86a045fbed0913ad68/src/GraphQL.GraphiQLCore/GraphQLRequest.cs#L5-L10

https://github.com/graphql-dotnet/graphql-dotnet/blob/85bc995e2bc8246592feca86a045fbed0913ad68/src/GraphQL.GraphiQLCore/GraphQLMiddleware.cs#L64

**Comment by pwfraley** [comment]
Thank you all, we got it working.  joemcbride example worked. :)

**Comment by Keeo** [comment]
Aslo thanks :+1:
