### ISSUE TITLE
Multiple fields in mutation are executed in parallel

### ISSUE THREAD

**Issue by serhii-ohorodnyk** [graphql-dotnet/graphql-dotnet#467]
Both, with latest release pack [0.17.3](https://www.nuget.org/packages/GraphQL/0.17.3) and pre-release [2.0.0-alpha-802](https://www.nuget.org/packages/GraphQL/2.0.0-alpha-802) multiple fields in mutation are executed in parallel.
I'm targeting 4.5 framework.

According to [documentation](http://graphql.org/learn/queries/#multiple-fields-in-mutations) multiple fields in mutations should be executed in series.

```
using System;
using GraphQL.Types;
using System.Threading.Tasks;
using GraphQL;

public class Program
{
    public static void Main()
    {
        var executer = new DocumentExecuter();
        var task = Task.Run(() => executer.ExecuteAsync(_ =>
        {
            _.Schema = new Schema()
            {
                Query = new Query(),
                Mutation = new Mutation()
            };
            _.Query = @"
                mutation {
                    one: testAsync
                    two: testAsync
                    three: testAsync
                }
            ";
            _.OperationName = null;
            _.Inputs = null;
        }));
        task.Wait();
    }

    public class Mutation : ObjectGraphType
    {
        public Mutation()
        {
            Name = "Mutation";

            FieldAsync<StringGraphType>(
                "testAsync",
                resolve: async context =>
                {
                    Console.WriteLine($"{DateTime.Now}: begin async");
                    await Task.Delay(TimeSpan.FromSeconds(2));
                    Console.WriteLine($"{DateTime.Now}: end async");
                    return "mutation hello world";
                });
        }
    }

    public class Query : ObjectGraphType
    {
        public Query()
        {
            Name = "Query";

            Field<StringGraphType>(
                "hello_world",
                resolve: context => "hello world"
            );
        }
    }
}
```

**Comment by joemcbride** [comment]
From my understanding, this will happen if you use `Task.Run` as you have shown.  Don't use `Task.Run`.  The latest alpha uses `Task.Run` for you when not a mutation.

**Comment by serhii-ohorodnyk** [comment]
@joemcbride thanks for your feedback but isn't that just spins off another thread?
Anyway I do have the same result without `Task.Run`:
```
var task = executer.ExecuteAsync(_ =>
        {
            _.Schema = new Schema()
            {
                Query = new Query(),
                Mutation = new Mutation()
            };
            _.Query = @"
                mutation {
                    one: testAsync
                    two: testAsync
                    three: testAsync
                }
            ";
            _.OperationName = null;
            _.Inputs = null;
        });
        task.Wait();
```

Do you have a working example?

**Comment by holm0563** [comment]
It seems like I originally had the opposite problem. Everything was running in series. See
https://github.com/graphql-dotnet/graphql-dotnet/pull/452

Specifically:
https://github.com/graphql-dotnet/graphql-dotnet/pull/452/files#diff-cd0bbfa3fdf59b53c127e4af8a76db8d

Does the version you are using have these changes in?

**Comment by SimonCropp** [comment]
@serhii-ohorodnyk could you submit a PR with a failing unit test?

**Comment by sungam3r** [comment]
Now all mutations are executed in series. Queries are executed in parallel. Try the latest package version. Closed as resolved.
