### ISSUE TITLE
Squash merge to master

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/graphql-dotnet#469]
It would make it easier to see what's changed in master if the PRs would be merged using the squash merge. Now there's lot of noise in the history of master branch.

**Comment by joemcbride** [comment]
I have come to accept that a lot of people just don't understand how to use git.  And for whatever reason some people will always do a merge vs. a rebase (perhaps using tooling vs. the command line?).  After it has been available, I have used squash on a case-by-case basis.

**Comment by pekkah** [comment]
When closing a PR there's an option to do an squash merge. This doesn't require the creator of the PR to squash or rebase the commits.

**Comment by joemcbride** [comment]
Yes, I know.

> After it has been available, I have used squash on a case-by-case basis.

^^
