### ISSUE TITLE
ResolutionArguments vs ResolveFieldContext

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#47]
Hi,

As I understand, in a GraphType, (atleast) two ways of adding fields is provided: a single method and a builder-pattern method:

```C#
Field<StringGraphType>("foo", resolve: (ResolveFieldContext context) => "foo");

Field<StringGraphType>()
  .Name("bar")
  .WithObject<int>()
  .Returns<string>()
  .Resolve((FieldBuilder<StringGraphType, int, string>.ResolutionArguments resolutionArguments) => "bar");
```

While the ResolutionArguments contains nicly typed properties etc. it does not expose the original ResolveFieldContext, nor all of it's fields. Espcially the CancellerationToken seem to be missing.

Is there a good reason for this? Or would it make sense to either:
 - Expose the ResolveFieldContext
 - Expose the missing parts from the ResolveFieldContext (CancellerationToken being one of them)
 - Make ResolutionArguments extend ResolveFieldContext (with some unfortunate "new" stuff required)

**Comment by tlil87** [comment]
Reading my mind :) This will also come through with the refactoring that I'm currently working on. It's on my list to migrate across from what we use internally. Will ping here when available, but quite packed schedule this week and beginning of next, so probably won't get to it until end of next week or so.

**Comment by joemcbride** [comment]
Closing this as `ResolutionArguments` now exposes `ResolveFieldContext`.
