### ISSUE TITLE
Generic ScalarGraphType 

### ISSUE THREAD

**Issue by deinok** [graphql-dotnet/graphql-dotnet#471]
Should `GraphQL.Types.ScalarGraphType` be generic like `GraphQL.Types.ScalarGraphType<Type> where Type: string, int, {...}`?
If I send a PR would it be accepted?

**Comment by KoditkarVedant** [comment]
@joemcbride what are your views on this? I really don't see any use case for this.

**Comment by SimonCropp** [comment]
How would that work? Generic constraints are ANDed. So in your example no type could both be a string and an int

**Comment by deinok** [comment]
Source has changed a lot from 2017/11 Closing this
