### ISSUE TITLE
Add UriGraphType

### ISSUE THREAD

**Issue by deinok** [graphql-dotnet/graphql-dotnet#472]
Add an `GraphQL.Types.UriGraphType` to represent `Uri`.

**Comment by joemcbride** [comment]
Can you talk to what a Uri specific GraphType would provide that the `StringGraphType` does not?

**Comment by deinok** [comment]
The same as `DateTimeGraph`

A string with a special format

**Comment by joemcbride** [comment]
Can you provide a concrete example?

**Comment by deinok** [comment]
An URI, "must" have the format of this spec -> https://tools.ietf.org/html/rfc3986
Anything that cant be parsed with this rules is not a valid URI.

Imagine I have a Schema with field called "uri" of type URI.
If I try to insert a valid URI everything goes okey, if its invalid, an error is returned to the caller, cause I dont want invalid URIs in my DB.

If "uri" is of type String, by default, the two scenarios above goes okey and the DB have an unexpected value.

(Yes, we could check if a "String" is an URI in our own code, but better share this "check" with other interested people)

Also, the fact that somthing is of type URI, gives to the client more information about the schema.
