### ISSUE TITLE
Support for JSON scalar type

### ISSUE THREAD

**Issue by lbrolinz** [graphql-dotnet/graphql-dotnet#474]
Hi,
Is JSON scalar type should be added soon to the library?
If not, what is the best way to add it (inherit from ScalarGraphType)?

Thank you

**Comment by joemcbride** [comment]
There aren't currently plans to add one, no.  This could be difficult to add with what is currently supported.  #458 should make that easier to do though.

**Comment by kamsar** [comment]
It is possible to do this easily, because JSON can accept a `StringValue`. The implementation (which unfortunately I can't share at this time) is a simple class that derives from `ScalarGraphType`; no value class or converter (like is in #458) is required. Also works for input objects.

**Comment by Odonno** [comment]
Why can't we convert a `string` or `ExpandoObject` to `JSONGraphType`?

**Comment by valorad** [comment]
Hi @acronoah , can you provide more details of your code snippet? 

- What do you mean `tv?.GetValue();` in `ParseLiteral()` method? Because there is no `GetValue()` method defined in `JsonGraphTypeConverter` class.

- How can we implement this custom scalar? I tried specifying `schema.RegisterValueConverter(new JsonGraphTypeConverter());` in Schema  and `scalar Json` in Graph definition but does not seem enough. I get an error: `Error: Unable to resolve reference to type 'Json' on 'Query' occured`

Thank you.

**Comment by Shane32** [comment]
See also #1780 - "Is is possible to have an input type of Object?"

**Comment by poojavarya** [comment]
> Essentially works, although graphQL explorer complains about the input side:
> 
> ```cs
>   class JsonGraphTypeConverter : IAstFromValueConverter
>     {
>         public bool Matches(object value, IGraphType type)
>         {
>             return type.Name == "Json";
>         }
> 
>         public IValue Convert(object value, IGraphType type)
>         {
>             return new JsonGraphValue(value as Dictionary<string, object>);            
>         }
>     }
> 
> 
>     class JsonGraphValue : ValueNode<Dictionary<string, object>>
>     {
>         public JsonGraphValue(Dictionary<string, object> value)
>         {
>             Value = value;
>         }
> 
>         protected override bool Equals(ValueNode<Dictionary<string, object>> node)
>         {
>             return Value == node.Value;
>         }
>     }
> 
>     internal class JsonGraphType : ScalarGraphType
>     {
>         public JsonGraphType()
>         {
>             Name = "Json";
>         }
> 
>         public override object Serialize(object value)
>         {
>             return ParseValue(value);
>         }
> 
>         public override object ParseValue(object value)
>         {
>             if (value == null)
>             {
>                 return null;
>             }
> 
>             return value;
>         }
> 
>         public override object ParseLiteral(IValue value)
>         {
>             if (value is JsonGraphValue)
>             {
>                 return value.Value;
>             }
>             else
>             {
>                 var tv = value as JsonGraphTypeConverter;
>                 return tv?.GetValue();
>             }
>         }
>     }
> ```
> 
> ![image](https://user-images.githubusercontent.com/30051812/40446527-210f8c6a-5e95-11e8-89ec-802361b809b5.png)

How did you resolve the issue on the input side? I am getting the same error "Expected Value of type JSON"

**Comment by poojavarya** [comment]
In case anyone else stumbles upon this issue. i resolved it in the following way:
` class JsonGraphTypeConverter : IAstFromValueConverter
    {
        public bool Matches(object value, IGraphType type)
        {
            return type.Name == "Json";
        }

        public IValue Convert(object value, IGraphType type)
        {
            return new JsonGraphValue(value as JObject);            
        }
    }


    class JsonGraphValue : ValueNode<JObject>
    {
        public JsonGraphValue(JObject value)
        {
            Value = value;
        }

        protected override bool Equals(ValueNode<JObject> node)
        {
            return Value == node.Value;
        }
    }

    internal class JsonGraphType : ScalarGraphType
    {
        public JsonGraphType() => this.Name = "JSON";

        public override object ParseLiteral(IValue value) => value.Value;

        public override object ParseValue(object value)
        {
			var jsonString = JsonConvert.SerializeObject(value);
			return JObject.Parse(jsonString);
        }

        public override object Serialize(object value)=> this.ParseValue(value);
    }`

**Comment by joemcbride** [comment]
Here is also a link to the `_Any` GraphType, which supports JSON data.

https://github.com/graphql-dotnet/graphql-dotnet/issues/669#issuecomment-674273598

**Comment by poojavarya** [comment]
i resolved it by making some changes to the solution from @acronoah 
`class JsonGraphTypeConverter : IAstFromValueConverter
    {
        public bool Matches(object value, IGraphType type)
        {
            return type.Name == "Json";
        }

        public IValue Convert(object value, IGraphType type)
        {
            return new JsonGraphValue(value as JObject);            
        }
    }

    class JsonGraphValue : ValueNode<JObject>
    {
        public JsonGraphValue(JObject value)
        {
            Value = value;
        }

        protected override bool Equals(ValueNode<JObject> node)
        {
            return Value == node.Value;
        }
    }

    internal class JsonGraphType : ScalarGraphType
    {
        public JsonGraphType() => this.Name = "JSON";

        public override object ParseLiteral(IValue value) => value.Value;

        public override object ParseValue(object value)
        {
			var jsonString = JsonConvert.SerializeObject(value);
			return JObject.Parse(jsonString);
        }

        public override object Serialize(object value)=> this.ParseValue(value);
    }`

**Comment by poojavarya** [comment]
> Here is also a link to the `_Any` GraphType, which supports JSON data.
> 
> [#669 (comment)](https://github.com/graphql-dotnet/graphql-dotnet/issues/669#issuecomment-674273598)

@joemcbride which version of Graphql is this available in? i am using v2.4.0 and i cant seem to register AnyValueConverter in my schema

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/GraphQL/3.0.0

**Comment by sungam3r** [comment]
@Shane32 It can be done for v4.1 - either `JsonScalarGraphType` or `MapScalarGraphType` (#669).

**Comment by sungam3r** [comment]
In case of `JsonScalarGraphType` we obviously can't put it in the main project to the rest of the scalars, because JSON scalar will require to add a reference to some serizlizer package - Newtonsoft/SystemTextJson so I think that it will be right to add scalar to each serializer project.

**Comment by sungam3r** [comment]
@Shane32 It seems that we are ready to implement some sort of JSON scalar (after all serialization refactorings)?

**Comment by Shane32** [comment]
Yes I would think so.

**Comment by OpenSpacesAndPlaces** [comment]
Has support been re-added for this? 
If so, is there a new syntax for redefining `JsonGraphTypeConverter : IAstFromValueConverter`?

Working on upgrading from 3.3 to 7.2 - this is one of the few items left I'm hitting.

Thanks!

**Comment by Shane32** [comment]
@OpenSpacesAndPlaces You should be able to use `AnyScalarGraphType` in most cases.  I wrote PR #3257 but it's almost identical to what currently exists in `AnyScalarGraphType`.  There's also PR #3246 but that is for passing JSON objects as text through a scalar, not arbitrary complex objects through a scalar.

**Comment by sungam3r** [comment]
Yeah, we should of course return to this feature and add it in one of the upcoming releases.

**Comment by Shane32** [comment]
Or just update AnyScalarGraphType slightly and call it a day.  It's just missing the code to convert a default value to a literal when printing the schema.  This code is present in #3257 and could be copied over.

**Comment by Shane32** [comment]
Fixed by #3257
