### ISSUE TITLE
Problem with defining Interface types

### ISSUE THREAD

**Issue by mrpink76** [graphql-dotnet/graphql-dotnet#477]
I've had som problems trying to use GraphQL Interfaces and boiled down the problem to the following modification of the starwars example: 

Commented out most of the constructor in the file StarWarsQuery.cs
```
        public StarWarsQuery(StarWarsData data)
        {
            Name = "Query";

            Field<CharacterInterface>("hero", resolve: context => data.GetDroidByIdAsync("3"));
            // Everything else is commented out
            // ...
        }
```

After making the modification above I thought the application would still work but it's not since the "HumanType" and the "DroidType" seems not to be registered. I get the following error "Abstract type Character must resolve to an Object type at runtime for field Query.hero..." when sending the following GraphQL-query:

```
{
  hero {
    id
    name
  }
}
```

Am I supposed to register the types in some other way?

Thanks in advance,
Petter

**Comment by joemcbride** [comment]
Yes, see RegisterType in the docs about Interfaces.

http://graphql-dotnet.github.io/graphql-dotnet/getting-started#registertype

**Comment by mrpink76** [comment]
Ahh, thanks!
