### ISSUE TITLE
[Request] ObjectExtension ToObject support private constructor

### ISSUE THREAD

**Issue by miguelcaravantes** [graphql-dotnet/graphql-dotnet#479]
Please add support for private constructor in ToObject method for can get non-anemic model as argument

example: EF support private constructor

Changing
var obj = Activator.CreateInstance(type); 
to
var obj = Activator.CreateInstance(type, true);
in ToObject method

**Comment by joemcbride** [comment]
Just a note on this after looking at it - I'm not sure I want to support this, since it would also mean potentially trying to support setting values on read-only properties.

**Comment by miguelcaravantes** [comment]
yes, the proposal would include can initialize via reflection private set properties

**Comment by sungam3r** [comment]
@joemcbride setting `private set` properties costs nothing, it already works with existing `SetValue`

**Comment by sungam3r** [comment]
@miguelcaravantes #1286 fixes this and is waiting for a review.

**Comment by sungam3r** [comment]
@miguelcaravantes You can try the latest preview version.

**Comment by miguelcaravantes** [comment]
thanks, when i have a change, I'll try it.

**Comment by Shane32** [comment]
This feature is planned to be removed for v8 in #3771 to better match deserialization behavior of System.Text.Json and to prepare for source-compilation of `ToObject`, where it would not be possible to use private constructors.  `ParseDictionary` can be overridden if needed to use custom deserialization logic.  @miguelcaravantes if this feature is critical for you, we could discuss further.

See:
- #3771 

cc: @gao-artur
