### ISSUE TITLE
Registering types in controller

### ISSUE THREAD

**Issue by ManishTrivedi** [graphql-dotnet/graphql-dotnet#48]
@joemcbride It would be great if you can share your thoughts on these issues:

- We register all the types and queries in the GraphQL controller constructor. What if I have 100 types and multiple schemas and queries in my system. Will I be registering all in this controller?
 
Please help!

**Comment by joemcbride** [comment]
Are you talking about the [`Controller` in the example](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Controllers/GraphQLController.cs#L18-L26)?  Use a "real" dependency container such as [structuremap](http://structuremap.github.io/) which can handle all of the container registration in an easier manner.

**Comment by joemcbride** [comment]
Closing this.  Let me know if that didn't answer you question.
