### ISSUE TITLE
No Subscription @Unsubscribe in EventStreamFieldType

### ISSUE THREAD

**Issue by KreativJos** [graphql-dotnet/graphql-dotnet#480]
There currently is no option to have a function that is called at the 'unsubscribe' event in Subscriptions.
I'm guessing I'm going to hack this together based on [this Subscriptions project](https://github.com/graphql-dotnet/server), but it would be nice if there was an API for this function.

**Comment by pekkah** [comment]
You can handle it with the unsubscribe of your observable

**Comment by lwansbrough** [comment]
This doesn't cover asynchronous work. I'm having to run an async method with forced synchronization in the Dispose method of my observable.

**Comment by KreativJos** [comment]
It is a temporary solution. We have solved it by extending the framework (=> hacking a lot), but it makes the code pretty unreadable for now.

**Comment by sungam3r** [comment]
@Shane32 Do you have any comments about this?

**Comment by Shane32** [comment]
`IObservable<object>.Subscribe` returns an `IDisposable`.  Its `Dispose` method is called when the client explicitly unsubscribes from the subscription, or when the client unexpectedly disconnects.  This is the only purpose of the `IDisposable`, so basically, `IObservable` explicitly supports notifications of unsubscribe events (as it must).

> You can handle it with the unsubscribe of your observable

Correct; it is rather simple to write a wrapper around an `IObservable` to capture the `IDisposable.Dispose` and run custom code.  Chances are that `System.Reactive` even has a helper method for this purpose.  If it doesn't, it would be extremely simple to write such a helper method.

> This doesn't cover asynchronous work

It does not matter to GraphQL.NET whether the `Dispose` request occurs immediately or not.  As GraphQL.NET must support concurrent calls to `OnNext` / `OnError` / `Complete` during the call to `Dispose`, any subsequent `OnNext` or `Complete` notifications will be discarded.  So it is completely safe and acceptable (in this case) to write code like this:

```cs
async void Dispose()
{
    // some async calls
}
```

Or if desired:

```cs
void Dispose()
{
    _ = DisposeAsync();
}

async ValueTask DisposeAsync()
{
    // some async calls
}
```

There is one exception: if the client disconnects from a given id and reconnects to another subscription with the same id, and if a data event arrives from the first subscription after `Dispose` is called and returns and after the client reconnects using the same id, it will be accepted.  I could 'fix' this issue with some breaking changes.  Although really clients should not be reusing ids.  (And no other WebSocket connection would be affected, as ids are unique per connection.)

Note that GraphQL.NET does assume that `Dispose` will return without throwing an exception, as is standard practice in .NET.  If an exception were thrown, the WebSocket connection would be terminated, dropping any remaining subscriptions within that HTTP connection, bubbling the exception up through the entire ASP.NET Core stack to the nearest exception handler for logging purposes.  Other and future HTTP connections would be unaffected.

As such, I would say that GraphQL.NET supports notifications of unsubscribe requests, specific asynchronous support is not applicable, and no changes are needed.

I could add support for `IAsyncDisposable`, where if the `IDisposable` returned by `Subscribe` implements `IAsyncDisposable`, then `DisposeAsync` is called instead.  This is similar to `IAsyncDisposable` support within the latest MS-DI framework.  It would require some API changes to the `SubscriptionList` class within the server project.

**Comment by Shane32** [comment]
I suggest closing this.
