### ISSUE TITLE
Subscription response object graph does not match subscription query

### ISSUE THREAD

**Issue by kamsar** [graphql-dotnet/graphql-dotnet#485]
Suppose you have a subscription query like:

```
subscription {
   foo {
      bar
   }
}
```

When the subscription executes, the result object will look like:

```
{
   "data": {
      "bar": "some value"
   }
}
```

It's missing the subscription name, and Apollo for example complains about the result object not matching the query when it attempts to cache the result. The result object expected would look like:

```
{
   "data": {
      "foo": {
         "bar": "some value"
      }
   }
}
```

This is because the `SubscriptionExecutor` returns the field resolve result directly, without wrapping it in the field name:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Subscription/SubscriptionExecuter.cs#L188

I fixed this by wrapping `fieldResolveResult.Value` in a dictionary.

**Comment by joemcbride** [comment]
Thanks for the report!  That indeed seems like a bug.

**Comment by pekkah** [comment]
#496 should fix this issue

**Comment by kamsar** [comment]
Looks great @pekkah. Sorry I didn't PR it myself (working on getting permission for that...)

**Comment by joemcbride** [comment]
Going to close this as it appears it is fixed.  Thanks @pekkah @kamsar !
