### ISSUE TITLE
How to use schema builder with complex object tree?

### ISSUE THREAD

**Issue by roman-kozachenko** [graphql-dotnet/graphql-dotnet#487]
Hello.
In our product we are exploring ability to use GraphQL at server side.
We have quite easy GraphQL schema, and I event make implementation  for it using `ObjectGraphType<>` implementations like in [Starwars sample](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.StarWars/StarWarsSchema.cs)
But then I found that your library allow to load GraphQL [schema](http://graphql.org/learn/) from file, register some types, like in [README](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/README.md#parameters) and have working schema.
It also works ok, event if we have some complex object tree: Blogs, containing Posts for example.
But I stuck with fields with parameters in nesting types.
I created a simple test in that PR:
https://github.com/graphql-dotnet/graphql-dotnet/pull/486

We can leave our ObjectGraphType-based implementation, but I want schema validation.

**Comment by roman-kozachenko** [comment]
Another question related to compex object tree - is it possible to access `ResolveFieldContext` (or some other context) in `Blog(string id)` method?

**Comment by joemcbride** [comment]
Yes, `ResolveFieldContext` just needs to be ahead of any GraphQL arguments:

```csharp
public Blog Blog(ResolveFieldContext context, string id)
{
  ...
}
```

You can also directly inject the `ResolveFieldContext.Source`.

There is a bug currently (https://github.com/graphql-dotnet/graphql-dotnet/issues/455) where you can't use `ResolveFieldContext` as the only parameter.

**Comment by joemcbride** [comment]
#455 is now fixed and released: https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v2.0.0-alpha-817
