### ISSUE TITLE
Field middleware being set on ExecutionOptions is weird

### ISSUE THREAD

**Issue by kamsar** [graphql-dotnet/graphql-dotnet#492]
It's a bit odd that you apply field middleware on the `ExecutionOptions`, e.g.

`options.FieldMiddleware.Use<InstrumentFieldsMiddleware>();`

This is because the `ExecuteAsync()` method is only applying the middleware if the schema is not yet initialized; if the schema is already initialized applying different middleware does nothing.

This can cause surprising results if you pass different sets of middleware in different queries to the same `Schema` object, because the first request determines which middleware are permanently applied for the life of the schema.

It would be a bit less surprising if field middleware was attached directly to the schema, and not as a parameter to an execution, which gives the impression it is mutable per execution when in fact it is not.

**Comment by joemcbride** [comment]
Thanks for the feedback.  I have some ideas for an overhaul for the field middleware.  Would you ever have a scenario where you would want to apply middleware to only a specific resolver and not all of them?

**Comment by kamsar** [comment]
In usages so far, no. But seems like it might be a use case for other scenarios to target resolvers by type.

**Comment by kamsar** [comment]
Would it make sense [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs#L41) to have `ApplyTo` also `return` before applying anything if `_components.Count == 0`?

Then I think the `SetFieldMiddleware` execution option would be more or less irrelevant as middleware wouldn't be applied unless some was used.

**Comment by Shane32** [comment]
I don't understand why this issue was closed without any discussion and I believe it should be reopened @sungam3r .  It is a very valid point.  I would agree that middleware should not be set during execution, but rather beforehand during configuration of the schema.

**Comment by sungam3r** [comment]
Ok

**Comment by Shane32** [comment]
Fixed in #2210
