### ISSUE TITLE
A GraphQL Client for .NET

### ISSUE THREAD

**Issue by deinok** [graphql-dotnet/graphql-dotnet#497]
@joemcbride 
It seems that there is not a GraphQL client for .NET.
So, in our company, we have been working on creating it

We would be happy if the GraphQL client we wrote was accepted by the "graphql-dotnet" organization.
Transfer ownership of everything and helping in its maintenance and improvement.

Link to GraphQL.Client: https://github.com/deinok/GraphQL.Client

**Comment by joemcbride** [comment]
I would be fine with that.  I can have it setup so you have full control over that repo as well.  I can add AppVeyor/myget for the project if you like (under the org), but you can use whatever setup you prefer.

**Comment by joemcbride** [comment]
I would probably want to change the repo name to `client` or something like that to keep with the simple repo names.

**Comment by deinok** [comment]
Before Transfer:
- [ ] Change name of repository from `GraphQL.Client` to `graphql-client`

After Transfer:
- [ ] Give you rights at nuget
- [ ] Change `.props` in order to show the change of property.
- [ ] Change links of graphql.org and

**Comment by deinok** [comment]
@joemcbride I think i dont left anything.
If you give me the OK I will start with the tranfer

**Comment by joemcbride** [comment]
👍

**Comment by joelmandell** [comment]
This is awesome. Gonna use it :)

**Comment by deinok** [comment]
@joemcbride Seems like we dont have rights to create repositories :(
Following error while tranfering:
`You don’t have the permission to create repositories on graphql-dotnet`

**Comment by deinok** [comment]
@joelmandell Thanks, its our intention ;)

**Comment by joemcbride** [comment]
@deinok Do you want to transfer the existing repo or create a new repo and push to that repo?  You can transfer via `Settings->Danger Zone->Transfer Ownership`.  Otherwise I can create a new repo.

**Comment by deinok** [comment]
Yeah, transfer it. I will tranfer it to you then you can doit for me.

**Comment by deinok** [comment]
Ok, i have tranfer it to you

**Comment by joemcbride** [comment]
@deinok I made the transfer to the org, you should have read/write access and be able to add more collaborators.

**Comment by joemcbride** [comment]
👍  Got them.  Do you want me to add AppVeyor or do you want to stick with CircleCi?

**Comment by deinok** [comment]
@joemcbride I'm okey with CircleCI but i dont have any problem changing the CI.

**Comment by joemcbride** [comment]
Moving the CI conversation to https://github.com/graphql-dotnet/graphql-client/issues/4

**Comment by deinok** [comment]
Okey, I Close this.
Also thanks for accepting it. We will probably continue creating more libraries related to GraphQL and helping to this org ;)
