### ISSUE TITLE
 GraphQL Schema syntax - field\type description and deprecation

### ISSUE THREAD

**Issue by hfroliveira** [graphql-dotnet/graphql-dotnet#498]
Hello, 

Since version 2.0.0-alpha-783 it is possible to build schemas using GraphQL Schema syntax.
I would like to know if there is a way to set a field\type description and deprecation using this notation.

Thanks.

**Comment by joemcbride** [comment]
You can currently use `GraphQLMetadataAttribute` to set description/deprecation, though you can't currently use the Schema syntax (the Parser ignores all comments at present).

```csharp
[GraphQLMetadata("hero", Description = "A description", DeprecationReason = "A reason")]
public Droid GetHero()
{
  return new Droid { Id = "123", Name = "R2-D2" };
}
```

I have started work on enabling comments in the Parser though it still needs some work.  https://github.com/graphql-dotnet/parser/pull/16

**Comment by hfroliveira** [comment]
Hello, 

Thanks for the help. I'm trying to generate the types from Schema Syntax using the graphql parser. So, having the parser reading comments is enough to generate the proper GraphQLMetadata as you mentioned. I've seen the commit graphql-dotnet/parser#16 and the additional comment member. 
In terms of Schema Syntax I understand that the description would be set using markdown:

```graphql
type CustomType
{
	# field `count` description
	count: Int!
}
```
What I can't understand, even reading graphql spec, is how to deprecate fields and set a proper deprecation reason just by using Schema Syntax.
Do you believe that this could be a future enhancement of this project?
Thanks.

**Comment by hfroliveira** [comment]
> What I can't understand, even reading graphql spec, is how to deprecate fields and set a proper deprecation reason just by using Schema Syntax.

I think you are trying to accomplish this using the directive  @deprecated(reason: "deprecation reason"), is that true?

```graphql
 extend type Query {
                fieldB : Int
                fieldD: Int @deprecated(badName : "must be called reason")
                fieldE: Int @deprecated(reason : "it must have", one : "argument value")
            }
```

**Comment by hfroliveira** [comment]
Hi,

a situation that I just came across now is the fact that it is not possible to deprecate or set the description of a field within a type using GraphQLMetadata. The attribute usage is set to AttributeTargets.Class and AttributeTargets.Method.

```csharp
public class Droid
{
	public string Id { get; set; }
	
	[GraphQLMetadata("name", Description = "Name of the droid.")]
	public string Name { get; set; }
	
	[GraphQLMetadata("foo", DeprecationReason = "Replaced by something else.")]
	public string Foo { get; set; }	
}
 ```

This way I don't know if there is an alternative way to deprecate or set a description of fields belonging to a type when loading build schemas using GraphQL Schema syntax.

Thanks.

**Comment by joemcbride** [comment]
Sorry, I lost track of this.

Yes, I would like to eventually support the `@deprecated` directive in the schema syntax.  I _believe_ that the parser will handle that, though the schema builder doesn't currently handle it.  That should be a fairly easy addition if the parser already supports it.

At present the Schema Builder also does not support handling fields like your `Droid` example.  This is a bit harder to add but not impossible.

**Comment by hfroliveira** [comment]
Hi, no problem. Thanks.

**Comment by joemcbride** [comment]
The `@deprecated` support is published in [`GraphQL.2.0.0-alpha-839`](https://www.nuget.org/packages/GraphQL/2.0.0-alpha-839)

**Comment by acronoah** [comment]
@joemcbride - Any progress on adding description support via comments in the parser?  This is definitely the "standard" way/place for this information to go.

**Comment by philosowaffle** [comment]
+1 for adding support for comments to parser

**Comment by sungam3r** [comment]
Is this question still relevant?

**Comment by sungam3r** [comment]
graphql-dotnet/parser#26

> 
> 
> @acronoah Not yet. I believe the code is mostly done, though it needs updated tests and potentially more tests to confirm. Happy to review a PR based on my existing one of you're up for the challenge.

Here it  is graphql-dotnet/parser#26

**Comment by sungam3r** [comment]
Closed as resolved. Now graphql-dotnet has support for both comments (from sdl, code, xml attributes) and deprecation directive. You can use latest prerelease nugets from [myget](https://myget.org/F/graphql-dotnet/api/v3/index.json).
