### ISSUE TITLE
Expand documentation to include tutorial on setting up GraphiQL UI. 

### ISSUE THREAD

**Issue by aconfee** [graphql-dotnet/graphql-dotnet#499]
Hello!

Thanks for this awesome library. I'm working to build a case for using this at my workplace, and having GraphiQL set up is a huge part of that. Unfortunately, I'm having trouble getting the UI set up without existing documentation, and an example project that I can't seem to run (also no docs for how to run). 

This seems like an easy win since the code is already written. I would love to see a tutorial for setting up the UI. This would be, as far as I can tell, the only tool that has a working UI for a non-Core version of ASP.NET. 

If I'm missing something, or there are existing resources I could use in the meantime, I'd really appreciate it. 

Thanks!

**Comment by jquense** [comment]
Have you tried: https://github.com/graphql/graphiql#getting-started ?

**Comment by joemcbride** [comment]
For the .NET Core GraphiQL sample:

```
> download source
> navigate to root of project in cmd
> npm install -g yarn
> yarn install
> yarn start
> Open Solution in VS
> Run the GraphiQLCore project
```

**Comment by joemcbride** [comment]
And here's a new stand-alone example: https://github.com/graphql-dotnet/example-aspnetcore

**Comment by drobertson123** [comment]
also, here is a super easy thing to just add;

https://www.nuget.org/packages/GraphiQL/

**Comment by KreativJos** [comment]
If you use [GraphQL server](https://github.com/graphql-dotnet/server), you can add graphiql & graphql playground with some easy steps:
In commandline (version could be upgraded later on):
```
dotnet add package GraphQL.Server.Transports.Subscriptions.Abstractions -v 3.1.0-alpha0003
dotnet add package GraphQL.Server.Transports.AspNetCore
dotnet add package GraphQL.Server.Ui.GraphiQL
```
And optionally for the playground and subsequently websockets:
```
dotnet add package GraphQL.Server.Transports.WebSockets
dotnet add package GraphQL.Server.Ui.Playground
```

And then in Startup.cs - Configure
```
app.UseGraphiQLServer(new GraphiQLOptions
{
    GraphiQLPath = "/graphiql",
    GraphQLEndPoint = "/graphql/v1"
});
```
And for the playground:
```
app.UseGraphQLPlayground(new GraphQLPlaygroundOptions()
{
    Path = "/playground",
    GraphQLEndPoint = "/graphql/v1"
});
```
