### ISSUE TITLE
Thought - Transpiling the JS implementation?

### ISSUE THREAD

**Issue by bryanerayner** [graphql-dotnet/graphql-dotnet#5]
Discovered GraphQL today. I would LOVE to use this at work - But we're a dot net stack.

I would be interested in contributing (a very small amount of time, measured in hours / month is all I can spare) to this project.

At first glance, it appears that the quickest way to implement the project, would be to transpile the ES6 implementation https://github.com/graphql/graphql-js to C#. I also feel like that's the easiest way I could contribute.

Does this align with the way you're approaching the project?

**Comment by joemcbride** [comment]
At first thought, I don't think transpiling would be a good way to go.  I have been using the JavaScript source as a reference, though not auto-generating the code.  I think C# offers us some options that I don't think would come through just by trying to auto-generate.  That said, I haven't seen code samples of what that would look like.  Feel free to post some.

As of right now, there is a "roadmap" of current features/missing features.  The biggest missing feature is Validation.

There is still a bit of a flaw in the design of some type registration (for introspection #3), though I'm working through it.  I've been a bit busy on another side project so haven't come back to this yet.

**Comment by bryanerayner** [comment]
@joemcbride Just submitted a PR for validation. Let me know what you think.

**Comment by joemcbride** [comment]
Closing this as this is not the route I would like to go (transpiling).
