### ISSUE TITLE
Return non-scalar field

### ISSUE THREAD

**Issue by ManishTrivedi** [graphql-dotnet/graphql-dotnet#50]
- I want to return a non-scalar field for a type.
How do I return fields that do not extend graph type by default, like returning a dictionary or System.Drawing.Size

**Comment by joemcbride** [comment]
You create `ObjectGraphType`'s for non-scalar fields.

```
public class SizeType : ObjectGraphType
{
  public SizeType()
  {
    Name = "Size";

    Field<NonNullGraphType<IntGraphType>>("height", "The height of the size.");
    Field<NonNullGraphType<IntGraphType>>("width", "The width of the size.");
  }
}
```

You could also create your own custom scalar.
```
public class SizeScalarType : ScalarGraphType
{
  public SizeScalarType()
  {
    Name = "Size";
  }

  public override object Coerce(object value)
  {
    var size = (Size)value;
    return string.Format("{0},{1}", size.Height, size.Width);
  }
}
```

For a dictionary it depends on how you want the values output.  All in one field?  Key/Value pairs?  Just the values?  You can create custom `ObjectGraphType`'s or `ScalarGraphType`'s to output whatever you want it to look like.

**Comment by ManishTrivedi** [comment]
Thank you for your response. Makes me understand GraphQL better. One thing I have noticed that the HumanType and DroidType need to have all the fields that are present in the CharacterInterface. Is there a better way to do this? Not duplicate fields present in the interface.

**Comment by joemcbride** [comment]
> But I should not be knowing the key of the dictionary in advance. Is there a way to return the dictionary in a generic manner?

You are the only one that can answer this question.  With the information you provided I don't know what you're trying to do.  Why are you using a dictionary?  What is in the dictionary?  What are you trying to get out of the dictionary?  What is the key?  Where does the key come from that you're trying to use?  What is the value?  I can't help you without an example of what you're trying to do.

> One thing I have noticed that the HumanType and DroidType need to have all the fields that are present in the CharacterInterface. Is there a better way to do this? Not duplicate fields present in the interface.

You can create an abstract base class that implements the common properties.

**Comment by ManishTrivedi** [comment]
I have a 'ImageType' which has a field 'Version'. This 'Version' field is a dictionary of <string, string> which contains a key value pair of different versions of an image. My GraphQL query returns this ImageType. Hence, I need to return this dictionary as part of the request. I have a DictionaryGraphType which inherits the ObjectGraphType. As of now, I am trying to figure out how to resolve the key and value for any dictionary of type <string, string>, so that I can return it in the GraphQL query.

**Comment by joemcbride** [comment]
Dictionaries aren't specifically supported in the GraphQL spec (only arrays), though [there are plans for something](https://github.com/facebook/graphql/issues/101#issuecomment-170170967) in the future.

Do you want to return everything in the dictionary?  If you want to return all versions I would suggest creating an object that represents the values and convert the dictionary to that object.  Something like this:

```
    public class Image
    {
        public Dictionary<string, string> Versions { get; set; }
    }

    public class ImageVersion
    {
        public string Version { get; set; }
        public string Url { get; set; }
    }

    public class ImageType : ObjectGraphType
    {
        public ImageType()
        {
            Name = "Image";
            Field<ListGraphType<ImageVersionType>>("versions",
                resolve: context =>
            {
                var dict = context.Source as Dictionary<string, string>;
                return dict.Keys.Select(key =>
                    new ImageVersion
                    {
                        Version = key,
                        Url = dict[key]
                    });
            });
        }
    }

    public class ImageVersionType : ObjectGraphType
    {
        public ImageVersionType()
        {
            Name = "ImageVersion";
            Field<StringGraphType>("version");
            Field<StringGraphType>("url");
        }
    }
```

This will allow you to do a query like this:

```
query ImageQuery {
  versions {
    version
    url
  }
}
```

You can create a more generic `KeyValuePairType` (with `key` and `value` fields) if you want to have a generic type to use with all dictionaries, though I would probably suggest a specific type.

If you don't want every version though only the "latest" version or something like that, you can just select the "first" item in the dictionary sorted as you like.

If you want a specific version you can add an `Argument` to the field and use that to filter the dictionary.
