### ISSUE TITLE
"resolve" parameters should accept async method

### ISSUE THREAD

**Issue by samueledirito** [graphql-dotnet/graphql-dotnet#503]
Maybe I'm wrong, but it seems that resolve param in ComplexGraphType<T>.Field method does not accept async lambda operator.

Just to be clear, I want to do something like this:
```
Field<ListGraphType<CompetenceAreaType>>("competenceAreas",
  resolve: async context =>
    await competenceAreas.GetProjection(x => new CompetenceAreaDTO
      {
         Id = x.Id,
         Name = x.Name,
         Code = x.Code
       }, new string[] {}));
```

Thank you very much for your work and your help 👍

**Comment by joemcbride** [comment]
Use FieldAsync

**Comment by samueledirito** [comment]
Oooook, amazing! Thank you ;)
