### ISSUE TITLE
BeforeExecutionAwaitedAsync Executed After Awaiting

### ISSUE THREAD

**Issue by speeddm** [graphql-dotnet/graphql-dotnet#508]
I am attempting to solve the N+1 problem in our project. I had tried to use Dataloader dot net, but found [it was not working out of the box](https://github.com/dlukez/graphql-dotnet-dataloader/issues/4).

My issue is that if I adapt the ExecuteBatchListener example that it doesn't hit until the tasks I have set have _already awaited_.

An example of the schema with a simple type (snippet only):

    public class TestSchema : Schema
    {
        public TestSchema()
        {
            Query = new TestQuery();
        }
    }

    public class TestQuery : ObjectGraphType
    {
        public TestQuery()
        {
            Field<HumanType>("getHuman", resolve: context =>
            {
                return Task.Run(() =>
                {
                    Thread.Sleep(TimeSpan.FromSeconds(10));
                    return new Human {GivenName = "John", FamilyName = "Citizen"};
                });
            });
        }
    }

And there is a listener:

    public class ExecuteBatchListener : DocumentExecutionListenerBase<GraphQlUserContext>
    {
        public override async Task BeforeExecutionAwaitedAsync(
            GraphQlUserContext userContext,
            CancellationToken token)
        {
            // this code does not fire until the 10 second thread sleep is up
        }
    }

Which is added here:

    var userContext = new GraphQlUserContext()
    var result = await executer.ExecuteAsync(_ =>
                {
                    _.Schema = new TestSchema();
                    _.Query = "query { getHuman { givenName familyName } } }";
                    _.UserContext = userContext;
                    _.Listeners.Add(new ExecuteBatchListener());
                }).ConfigureAwait(false);

As I have said in the comment - you do not hit the `BeforeExecutionAwaitedAsync` call until after the task in "getHuman" has run to completion - or if you are trying to batch (and trigger off the execution of the tasks in the `BeforeExecutionAwaitedAsync` method) then it never gets hit at all.

Is there a piece of the puzzle that I'm missing?

**Comment by joemcbride** [comment]
This could be another victim of the most recent threading refactor.  I don’t think we have good tests around this feature so there could be a regression.

Could perhaps be this same issue?  #506

**Comment by kamsar** [comment]
Funny I came here to report the same thing but with a different reproduction. In my case, I'm using `TaskCompletionSource` to block the field from completing until the `BeforeExecutionAwaitedAsync()` method is fired. This is the method that Marten, which the batching example uses, is using.

In all cases, the execution of `BeforeExecutionAwaitedAsync` is being blocked until after the resolvers have been awaited (i.e. without the timer to push things along, the sample below would hang forever)

I've also noticed different behavior depending on the number of async fields in the query. In my example below, if I query on `{ foo }`, the `BeforeExecutionAwaitedAsync` gets called in a sane order, but if I change the query to `{ foo bar: foo }` (repeating the same field) then the execution order is incorrect: `BeforeExecutionAwaitedAsync` is called _before bar is added to the batch by its resolver_.

I'm also using `SetFieldMiddleware = false`, which should avoid the wrapping deadlock in #506 

Here's my test code (against 2.0-alpha820):

```

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using GraphQL;
using GraphQL.Execution;
using GraphQL.Types;

namespace UnitTestProject1
{
    public class UnitTest1
    {
        public static Timer breaker;

        public async Task TestMethod1()
        {
            var schema = new Schema();
            schema.Query = new AsyncGraphType();

            var userContext = new GraphQLUserContext();

            breaker = new Timer(obj =>
            {
                Console.WriteLine("Timed out, pushing query batch (as it isn't pushing itself)");
                userContext.Batch();
            }, null, 5000, 5000);

            var result = schema.ExecuteAsync(_ =>
            {
                _.UserContext = userContext;
                _.Query = $@"{{ foo bar: foo }}";
                _.ExposeExceptions = true;
                _.Listeners.Add(new ExecuteBatchListener());
                _.SetFieldMiddleware = false;
            });

            var output = await result;
            breaker.Dispose();

            Console.WriteLine(output);
        }

        public class AsyncGraphType : ObjectGraphType
        {
            public AsyncGraphType()
            {
                Name = "Query";
                Field<StringGraphType>("foo", resolve: context =>
                {
                    Console.WriteLine("Deferring until batched");
                    var uc = context.UserContext.As<GraphQLUserContext>();
                    return uc.DeferUntilBatched();
                });

                Field<StringGraphType>("bar", resolve: context => "bar");
            }
        }

        public class ExecuteBatchListener : DocumentExecutionListenerBase<GraphQLUserContext>
        {
            public override Task BeforeExecutionAwaitedAsync(GraphQLUserContext userContext, CancellationToken token)
            {
                userContext.Batch();

                return Task.CompletedTask;
            }
        }

        public class GraphQLUserContext
        {
            private List<TaskCompletionSource<string>> tcses = new List<TaskCompletionSource<string>>();

            public Task<string> DeferUntilBatched()
            {
                var tcs = new TaskCompletionSource<string>();
                tcses.Add(tcs);

                return tcs.Task;
            }

            public void Batch()
            {
                Console.WriteLine("Batching\r\n" + new StackTrace());
                int i = 0;
                foreach (var tcs in tcses)
                {
                    tcs.SetResult($"BATCHED{i}");
                    i++;
                }

                tcses.Clear();
            }
        }

        
    }
}
```

**Comment by johnrutherford** [comment]
I'm also running into the same issue. Even if I go back to an earlier version where `BeforeExecutionAwaitedAsync()` is called at the expected time, it only works for the first level. If there are batched operations beyond the first level, I get a deadlock. 

Has anyone been able to get some sort of DataLoader solution working beyond one level? It appears that the [dataloader-dotnet](https://github.com/dlukez/dataloader-dotnet) repository has been abandoned. It seems like maybe it would help if there was a hook like `BeforeExecutionAwaitedAsync()` called for each level.

I'm just trying to determine if this is even possible with this library at this time or if it will be at any point in the near future.

**Comment by kamsar** [comment]
It makes sense for a multilevel query to deadlock, because the result of
child resolvers would deadlock with needing the parent resolver to
complete. I'm not sure if this pattern will work as intended without
refactoring the way queries execute unless Joe is an async ninja who knows
things I don't. Which he might be ;)

**Comment by johnrutherford** [comment]
I haven't really looked at the internals to know whether it possible or not currently. 

But the whole point of GraphQL is to allow the client to query the relationships that they need across any number of levels. So if query batching only works on a single level, then it's not very useful.
