### ISSUE TITLE
When registering a type, throw exception if key already exists

### ISSUE THREAD

**Issue by UptownBob** [graphql-dotnet/graphql-dotnet#510]
I have an subtle enhancement request.  There's a lot of this going on in GraphTypesLookup:
lock (_lock)
            {
                _types[name] = type;
            }

If I have two GraphType's accidentally and unknowingly with the same Name it assigns a new value to the key in the _types Dictionary without any check or exception.  This typically results in Field members losing their ResolvedType properties, then query results complete successfully with null data and without any indication why bad data.  Great library, thanks for your work.

**Comment by drobertson123** [comment]
I absolutely want to add many upvotes to this. We are configuring a GraphQL server from multiple data projects. It is extremely easy to overwrite a type and cause a bug that is almost impossible to track down.

I would much rather have to deal with an exception than the mystery result that happens later in the process.

As a non-breaking alternative, I would be open to a different method for registering the Types. A SafeRegister method or something like it.

This goes for any area that has the same type of collection overwrite code. By allowing an overwrite it creates an opportunity for lots of unintended consequences. This should be an anti-pattern;

collection[name] = thing

**Comment by drobertson123** [comment]
After doing some research I can see where this could be a fairly major undertaking. On the surface, it looks simple but there are valid arguments for overwriting registrations. There is also the complication of precedence in registering types.

Autofac has an excellent discussion of a similar (but not exactly the same) topic;

[Discussion: ContainerBuilder.Update Marked Obsolete](https://github.com/autofac/Autofac/issues/811)

I actually like their eventual solution. They added two extension methods that helped get around the problems;

**[RegistrationExtensions.IfNotRegistered<TLimit, TActivatorData, TStyle> Method](https://autofac.org/apidoc/html/BEE129AA.htm)**
Attaches a predicate such that a registration will only be made if a specific is not already registered. The predicate will run at registration time, not runtime, to determine whether the registration should execute.

**[RegistrationExtensions.OnlyIf<TLimit, TActivatorData, TStyle> Method](https://autofac.org/apidoc/html/D513BEF6.htm)**
Attaches a predicate to evaluate prior to executing the registration. The predicate will run at registration time, not runtime, to determine whether the registration should execute.

The core idea would be to add these extension methods for cases where more control is needed over the registration process, but the main function would remain the same.

**Comment by drobertson123** [comment]
@joemcbride 

I am wondering what your thoughts are on the two extension methods or a similar idea.

If it seems to be worthwhile I can take a shot at doing a pull request for them. One thing that would be helpful is pointing to where you would see something like this living in the code.

**Comment by sungam3r** [comment]
Relates to #1284

**Comment by sungam3r** [comment]
@UptownBob I think that #1284 should help. Feel free to reopen if the problem persists.
