### ISSUE TITLE
Improve query validation

### ISSUE THREAD

**Issue by kamsar** [graphql-dotnet/graphql-dotnet#512]
[Right here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L129), the execution options are being validated that they contain a string query.

```
if (string.IsNullOrWhiteSpace(options.Query))
            {
                throw new ExecutionError("A query is required.");
            }
```

I would like to propose dropping that validation _if_ `options.Document != null`, because that's the equivalent of a query, just pre-parsed/validated.

**Comment by joemcbride** [comment]
I’m fairly certain that the original query is used for other things, such as providing line/column numbers in error messages.  So it would still be required.

**Comment by kamsar** [comment]
The document object has an originalquery property though. Wouldn't that be
used?

**Comment by sungam3r** [comment]
> I’m fairly certain that the original query is used for other things, such as providing line/column numbers in error messages. So it would still be required.

Agree. `Document` can be null or caller side may set in to some cached instance. `options.Query` is required while `options.Document` is optional.
