### ISSUE TITLE
Converting a resolver arg to an unknown type results in NullReferenceException

### ISSUE THREAD

**Issue by kamsar** [graphql-dotnet/graphql-dotnet#517]
Reproduction:
In any resolve method, take an argument and convert it to some unknown type, for example:

```
public object Resolve(ResolveFieldContext context) {
   var foo = context.GetArgument<HttpContextBase>("foo");
}
```
The result won't be a decent error like "Unable to convert argument to {type} because no converter exists", but instead a NullReferenceException because this method does not perform a null check on the indexer result before invoking the converter:

https://github.com/graphql-dotnet/graphql-dotnet/blob/bb0ef2845c5deccb7fc63bd18583a3afc325f8fd/src/GraphQL/Conversion/Conversions.cs#L92

It would be easier to understand if it was something like:

```
public object Convert(Type type, string raw)
{
    var converter = _convertors[type];
    if(converter == null) throw new InvalidOperationException($"Unable to convert argument to {type.Name} because no converter exists for {type.FullName}");
    return converter(raw);
}
```

It doesn't look like it's possible to register new conversions either due to their being private/static:

https://github.com/graphql-dotnet/graphql-dotnet/blob/bb0ef2845c5deccb7fc63bd18583a3afc325f8fd/src/GraphQL/ObjectExtensions.cs#L13

**Comment by joemcbride** [comment]
Indeed this needs some help.  Care to do a PR?  😄

**Comment by KoditkarVedant** [comment]
I think this issue is irrelevant now.

**Comment by joemcbride** [comment]
Yes, this should be fixed now with the new `ValueConverter `.
