### ISSUE TITLE
Problem passing parameters using the example application

### ISSUE THREAD

**Issue by mrpink76** [graphql-dotnet/graphql-dotnet#519]
I'm having problems passing parameters using graphiql and the example application.
The query parameter of the PostAsync method is resolved to null after passing input as specified below.

I think the problem is that the "query" parameter in PostAsync expects that the "Variables" are passed as a string when infact they ar passed as a json-object:

Query:
```
query lala($id: String!) {
  human(id: $id) {
    name
  }
}
```

Variables:
```
{
  "id": "1"
}
```

Passed to the server:
```
{"query":"query lala($id: String!) {\n  human(id: $id) {\n    name\n  }\n}","variables":{"id":"1"},"operationName":"lala"}
```

My quick fix was the following:

```
    public class GraphQLController : ApiController
    {
        [HttpPost]
        public async Task<HttpResponseMessage> PostAsync(HttpRequestMessage request, GraphQLQuery query)
        {
            var inputs = new Inputs(query.Variables ?? new Dictionary<string, dynamic>());
            // ...
        }
    }

    public class GraphQLQuery
    {
        public string OperationName { get; set; }
        public string NamedQuery { get; set; }
        public string Query { get; set; }
        public Dictionary<string, dynamic> Variables { get; set; }
    }
```

Is this infact an error or I'm a doing something incorrect?

**Comment by joemcbride** [comment]
I haven’t tested the ASP.NET MVC example project in a while, though yes it did work with just a String previously.

```
var inputs = new Inputs(query.Variables ?? new Dictionary<string, dynamic>());
```

You can run into problems with this.  GraphQL expects all JSON.NET types to be converted to scalar .NET Types.  You want to use the `.ToInputs` extension method which does the conversion.

I would instead suggest to use `JObject` along with `.ToInputs` [as seen here](https://github.com/graphql-dotnet/example-aspnetcore/blob/4ebbdd99392db9ab7bcfa447ec73caa95abaa082/src/Example/GraphQLRequest.cs#L5-L10)

```csharp
    public class GraphQLRequest
    {
        public string OperationName { get; set; }
        public string Query { get; set; }
        public JObject Variables { get; set; }
    }
```

**Comment by joemcbride** [comment]
Going to close this.  Let me know if you're still having issues.
