### ISSUE TITLE
Bug with variables in request body

### ISSUE THREAD

**Issue by Wavum** [graphql-dotnet/graphql-dotnet#521]
When I send this `{"operationName":null,"variables":null,"query":"{ hero { id }}"}` to my endpoint i get a normal response, but if I send this `{"operationName":null,"variables":{},"query":"{ hero { id }}"}` to my endpoint i get back a 500 http status code.

As seen in the [GraphQL specs](https://facebook.github.io/graphql/October2016/#sec-Input-Objects) both should work.

Original Value | Variables | Coerced Value
-- | -- | --
{ a: "abc", b: 123 } | null | { a: "abc", b: 123 }
{ a: 123, b: "123" } | null | { a: "123", b: 123 }
{ a: "abc" } | null | Error: Missing required field b
{ a: "abc", b: null } | null | Error: b must be non‐null.
{ a: null, b: 1 } | null | { a: null, b: 1 }
{ b: $var } | { var: 123 } | { b: 123 }
{ b: $var } | {} | Error: Missing required field b.
{ b: $var } | { var: null } | Error: b must be non‐null.
{ a: $var, b: 1 } | { var: null } | { a: null, b: 1 }
**{ a: $var, b: 1 }** | **{}** | **{ b: 1 }**

**Comment by joemcbride** [comment]
I'm double checking this, though can you expand on how you're handling your variables?  Are you using `JObject` and `.ToInputs` as shown here?  .NET Core or Full Framework?

https://github.com/graphql-dotnet/example-aspnetcore/blob/master/src/Example/GraphQLRequest.cs#L9
https://github.com/graphql-dotnet/example-aspnetcore/blob/master/src/Example/GraphQLMiddleware.cs#L59

**Comment by Wavum** [comment]
No, I'm requesting from react-apollo on my local machine. I use .NET Core on the server side.

**Comment by joemcbride** [comment]
It would be helpful to know how your server is setup, including the stacktrace of the error.

**Comment by joemcbride** [comment]
I've validated this works with the following test.  Are you able to write a failing test?

```csharp
[Fact]
public void optional_variable_not_provided()
{
    var testSchema = @"
      input ExampleInputObject {
        a: String
        b: Int!
      }
      type Query {
        something(input: ExampleInputObject): String
      }
    ";
    var schema = GraphQL.Types.Schema.For(testSchema, _ => _.Types.Include<MyHandler>());
    var result = schema.Execute(_ =>
    {
        _.Query = "query ($var: String) { something(input: { a: $var, b: 1 }) }";
        _.Inputs = "{}".ToInputs();
    });

    System.Console.WriteLine(result);
}

public class MyInput
{
    public string A { get; set;}
    public int B { get; set; }
}

[GraphQLMetadata("Query")]
public class MyHandler
{
    public string Something(ResolveFieldContext context, MyInput input)
    {
        return $"A: {input.A}, B: {input.B}";
    }
}
```

**Comment by Wavum** [comment]
Sorry, my fault. My endpoint couldn't accept `variables` as an object. Fixed it.
