### ISSUE TITLE
Can create types where name is invalid

### ISSUE THREAD

**Issue by bittercoder** [graphql-dotnet/graphql-dotnet#524]
It's possible currently to create a type where the name is invalid (does not follow the spec http://facebook.github.io/graphql/draft/#sec-Names) - but it will be returned via graphqldotnet when issuing an introspection query.

This was quite hard to track down as it was just causing GraphQL playground/graphiql to silently fail to load the schema.

It would be nice if GraphQL server would fail-fast reporting that the type in the schema had an invalid name.

**Comment by joemcbride** [comment]
Thanks for the report.  We are tracking this issue here: https://github.com/graphql-dotnet/graphql-dotnet/issues/475

Up do doing a PR for it?
