### ISSUE TITLE
Are types resolved by graphql cached?

### ISSUE THREAD

**Issue by Jefffrey** [graphql-dotnet/graphql-dotnet#526]
I'm running into a problem where it seems that GraphQL is caching something across different requests. Is it possible that either graphql types or that results of the DI resolver passed to the schema instance are cached?

In both cases there may be a bug in this library.

**Comment by joemcbride** [comment]
Yes the types are cached using GraphTypesLookup.

**Comment by Jefffrey** [comment]
But what if a graphql type is injected a resource X via the standard DI which is supposed to be "transient" or "scoped" (live as long as the request lives)?

**Comment by joemcbride** [comment]
You can use constructor injection coupled with a DI setup, though at this time the result will be cached and live the lifetime of the Schema.

**Comment by Jefffrey** [comment]
For something like `DbContext` that seems suboptimal. Considering that `DbContext` is not guaranteed to be thread safe and considering that resolvers, as far as I know, are run concurrently, that may yield concurrent errors. With Npsql (Postgres binding for Entity Framework) I get exceptions due to concurrent access to the same DbContext instance which is injected into multiple GraphQL types.
