### ISSUE TITLE
[Discussion] Get arguments as plain objects.

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#527]
Hi,

I want to extend my REST with a second endpoint using GraphQL. Some of my inputs are highly dynamic. Therefore I just use JObject class. Can I get the raw arguments in my mutations?

**Comment by SebastianStehle** [comment]
I tried to understand the code, but I don't get it yet. For me it seems, that the input is converted in this way JObject => Dictionary => AST Nodes => Objects

seems to be very complicated, especially because JObject is more powerful and faster than the custom conversion and deserialization stuff.

**Comment by joemcbride** [comment]
AST Nodes is for the Query itself, not arguments/variables.  You can access the Arguments (as a Dictionary) via the ResolveFieldContext.Arguments.  Granted this could potentially be faster, though there are rules in the GraphQL spec in regards to the Arguments which preclude just providing the raw JSON arguments.

**Comment by SebastianStehle** [comment]
The point is:  I don't want to write another serializer from Dictionary<string, object> to my code. I would just like to get the JObject that represents my object that is passed as variable to the mutation, but this does not work.

**Comment by joemcbride** [comment]
Are you able to provide an example of what doesn't work for you?  This is how this library is currently setup to function:

https://graphql-dotnet.github.io/getting-started/#mutations

```csharp
public class StarWarsMutation : ObjectGraphType
{
    public StarWarsMutation(StarWarsData data)
    {
        Field<HumanType>(
            "createHuman",
            arguments: new QueryArguments(
                new QueryArgument<NonNullGraphType<HumanInputType>> {Name = "human"}
            ),
            resolve: context =>
            {
                var human = context.GetArgument<Human>("human");
                return data.AddHuman(human);
            });
    }
}

public class HumanInputType : InputObjectGraphType
{
    public HumanInputType()
    {
        Name = "HumanInput";
        Field<NonNullGraphType<StringGraphType>>("name");
        Field<StringGraphType>("homePlanet");
    }
}

public class Human
{
    public string Name { get; set; }
    public string HomePlanet { get; set; }
}
```

**Comment by SebastianStehle** [comment]
Basically I need

      resolve: context =>
            {
                var human = context.GetArgument<JObject>("human");
                return data.AddHuman(human.ToObject<Human>());
            });

**Comment by joemcbride** [comment]
Have you tried:

```csharp
var obj = JObject.FromObject(context.Arguments);
var obj = JObject.FromObject(context.Arguments["human"]);
```

Also, are you expecting there to be values in the Arguments that aren't defined in your GraphQL Schema?

This is the GraphQL spec for how arguments are determined: http://facebook.github.io/graphql/October2016/#sec-Coercing-Field-Arguments

So the values found in `ResolveFieldContext.Arguments` is determined by the algorithm defined in the spec.

If for whatever reason you're looking to bypass that portion of the spec, the easiest route would be to create a "user context" object and add the raw values to that context.

https://graphql-dotnet.github.io/learn/#user-context

**Comment by SebastianStehle** [comment]
This actually works, stupid me. But of course it is not optimal with a lot of conversion steps:

Stream => JObject => Dictionary => JObject

Thanks

**Comment by SebastianStehle** [comment]
Works fine, thx

**Comment by hasibul2363** [comment]
@SebastianStehle 
Could you please share your solution, please. I am very new on GraphQL
What will be possible `queryArgument` type.
I am also interested to collect an anonymous object from the argument.
```
new QueryArguments(
                        new QueryArgument<What will be type here> { Name = "model", Description = "anonymous" })
```

Stream => JObject => Dictionary => JObject
Is it string or stream?

Expecting your help.
