### ISSUE TITLE
mutation input type casting issue

### ISSUE THREAD

**Issue by landbolts** [graphql-dotnet/graphql-dotnet#529]
hi, 

I noticed an issue when an input graph type which contains a collection is being resolved on a mutation. the collection seems to always be cast to a generic List. Wanted to get anyone's input if it would be safer to cast to the actual "fieldType" that has been resolved (assuming the object implements IList). 

example below: 

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/ObjectExtensions.cs

line 61
var genericListType = typeof(List<>).MakeGenericType(elementType);
var newArray = (IList) Activator.CreateInstance(genericListType);

potential change to: 
 var newArray = (IList) Activator.CreateInstance(fieldType);

This code seems to solve the issue, any input would be helpful. 

thanks
Aleks

**Comment by joemcbride** [comment]
Can you provide an example of how this caused a problem?  What is the fieldType in your case?

**Comment by landbolts** [comment]
thanks for the quick response, the fieldType in my case extends from a generic list, eg. 

MyObjectCollection : List<MyObject>, ICloneable

The type on my input graph type is just a ListGraphType. 
I think the issue seems to be down-casting the list to the collection.

**Comment by joemcbride** [comment]
Gotcha. Probably would need to check to see that the type implements IList, then could use the fieldType. Otherwise use the generic list. That way can also support IEnumerable<T> properties.

Up to doing the PR?

**Comment by joemcbride** [comment]
This is published as [`GraphQL.2.0.0-alpha-839`](https://www.nuget.org/packages/GraphQL/2.0.0-alpha-839)
