### ISSUE TITLE
Trying to run GraphiQL in Visual Studio 2017.  bundle.js is 404

### ISSUE THREAD

**Issue by mindmodel** [graphql-dotnet/graphql-dotnet#532]
Sorry if this is a noob question.

I'm trying to run GraphiQL in Visual Studio 2017, latest version.

I downloaded the solution.
Set startup project to GraphQL.GraphiQL.
Compiled and ran.

I get a blank web page.
In Chrome dev tools I see that the page is trying to load bundle.js, but can't find it (404).

I read this issue

https://github.com/graphql-dotnet/graphql-dotnet/issues/203

but don't really understand what's going on there.

I get the idea that this might have something to do with restoring NuGet packages in GitHub vs. running VS locally, and/or Node.  I don't know Node.

How do I get GraphiQL running locally in VS?  Please let me know or point me in the direction of how to troubleshoot this problem.

Thanks in advance,

Adam

**Comment by joemcbride** [comment]
The `bundle.js` file is created by running [webpack](https://webpack.js.org/).  Webpack is a javascript bundler.  You can find the [configuration file](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/webpack.config.js) at the root of this repo.  To bundle all of the javascript files to run the GraphiQL sample, you will need to have node installed and follow the steps in the readme of the project:

At the root of the repo run:

```
npm install
npm start
```

`npm install`: installs of the node package dependencies
`npm start`: runs the `start` "script" found in the node [`package.json`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/package.json) file.

That should create the bundle.js files.  You can then run the application from Visual Studio.

**Comment by mindmodel** [comment]
Works perfectly! :)

Never doubt the age-old wisdom of RTFM.

Thanks,

Adam
