### ISSUE TITLE
Null value bubbling in case of error

### ISSUE THREAD

**Issue by roman-kozachenko** [graphql-dotnet/graphql-dotnet#535]
Hello.
We found the following issue.
According to lastest GraphQL [spec draft](http://facebook.github.io/graphql/draft/#sec-Errors):
> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field. 

Current version of **graphql-dotnet** library doesn't work in such way: I created a PR with test for that feature #534.
The problem is that [Apollo library](https://github.com/apollographql/apollo-ios/) which is used by frontend in our application  expect that behavior from server. 
Currently frontend team make a workaround for that. And we wanted to know, do you have any plans to implement that?
Thanks.

**Comment by joemcbride** [comment]
Hey, thanks for the report.  We are tracking this issue here:  #424
