### ISSUE TITLE
Implement DataLoader that works across multiple levels

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/graphql-dotnet#537]
Hi @joemcbride, 

I'd like to contribute a DataLoader implementation that works across multiple levels since the [dataloader-dotnet](https://github.com/dlukez/dataloader-dotnet/) repository appears to be abandoned. 

I have it mostly working (see 2 below) with some modifications to the `DocumentExecuter`. I added a method to `IDocumentExecutionListener` called `BeforeResolveLevelAwaitedAsync` (maybe it should be "Before*Resolution*LevelAwaitedAsync"). This is called on each level to dispatch any pending batched requests. 

I wanted to get feedback on some issues before submitting a pull request.

1. I currently have 3 new projects (DataLoader, DataLoader.GraphQL and DataLoader.Tests) as part of the GraphQL solution. Should these go in a separate repository? The DataLoader project has no dependency on GraphQL, and the DataLoader.GraphQL project includes an `IDocumentExecutionListener` implementation. 

2. Currently operations are not able to be batched efficiently because of how the execution branches. If you have results that branch, each branch is executed one by one rather than executing each branch in parallel. 

If you have results like this:
```
A
 +-- B1
 |   +-- C1
 |   +-- C2
 +-- B2
 |   +-- C3
 |   +-- C4
+-- B3
 |   +-- C5
 |   +-- C6
```

They will be executed in this order: A -> B1+B2+B3 -> C1+C2 -> C3+C4 -> C5+C6.

So the C-level operations cannot be all batched together. 

Ideally we would want each level to be executed together to maximize the batches. Like this: A -> B1+B2+B3 -> C1+C2+C3+C4+C5+C6.

This would require more changes to the `DocumentExecuter`, and obviously there may be concerns with mutations. 

3. I'm not sure if I understand the need for `IFieldResolver.RunThreaded()` and `SlowFuncFieldResolver`. It's used to run resolvers on ThreadPool threads, but this behavior is not obvious or intuitive when calling `FieldAsync()`.

**Comment by joemcbride** [comment]
Thanks for looking into this! We have been tracking this as #264.

I'll be honest and say that tackling this is a bit beyond my currently level of knowledge and is a major reason why this feature does not exist yet.  I also think it would be a great feature to have.

1. I have a repo I setup under the org for a dataloader implementation that I created a while back.  We can use that for the parts that do not have a GraphQL dependency.  Perhaps the GraphQL specific parts could also go in that repo but a different project.  Depending on what it looks like, I could see adding those dependencies to the [server](https://github.com/graphql-dotnet/server) project or at least an example.

https://github.com/graphql-dotnet/dataloader

2. Mutations do have to run serially and can't be batched.  In general, the guts of `DocumentExecutor` needs a fairly big overhaul.  `<insert lame excuse here>`  In the past I had in my head a "batching" executor vs. a "serial" executor.  I'm fairly sure the ruby project does something like that.  That could be transparent to the user but sort of like a pluggable behavior model within the executor.

3. I agree on the threading.  I can understand why it was changed (a community contribution) though it does feel like there should be a better design.  This also is not my expertise so I'm grasping at straws a bit there myself.

**Comment by johnrutherford** [comment]
Ok, great. 

1. I'll start with a pull request to the dataloader repository. Then once we have that on a MyGet feed or on NuGet, I can add the dependency to the GraphQL.DataLoader project. I think it would make more sense to have the GraphQL.DataLoader project in this repository since it's going to depend on re-working the DocumentExecuter.

2. Yeah, I was looking at the Java port and they have the concept of "execution strategies" (http://graphql-java.readthedocs.io/en/v6/execution.html?highlight=strategy#execution-strategies). So something like that could work. 

3. Yeah, I definitely think it should be more obvious to the implementer that the resolver is going to be executed on a ThreadPool thread. And it should be handled in the resolver itself. The executor shouldn't have to know about it. I'll address that too since it's related to the areas I want to work on.

**Comment by joemcbride** [comment]
Lets continue this in #264 , though @drobertson123 makes a good point that we should probably just keep all of this in the core repo to reduce fracturing.  Can pull it out to a different repo/NuGet later if needed.

**Comment by johnrutherford** [comment]
Ok, it looks like I can't submit a pull request to the dataloader repository because it's empty. 

I just pushed to this repository: https://github.com/johnrutherford/dataloader. Do you want to look that over and then give me push access? Or you could just add a README or something and then it should allow a pull request.

**Comment by johnrutherford** [comment]
Ah, ok. I'll keep the dataloader in the main solution then for now. And I'll continue the discussion in #264.
