### ISSUE TITLE
Partial update mutation

### ISSUE THREAD

**Issue by emulicus** [graphql-dotnet/graphql-dotnet#541]
Hello everyone,
We're encountering one case that hopefully someone already dealt with before. 
We're using entity framework for our data layer and oracle as our database. 
A lot of our mutations have massive input objects and we would like to support a scenario where user can just send a partial model and we would just update the specified fields in the database through the Entity Framework( pretty much patch request from rest world).
The problem we have now is that in the mutation resolver we use GetArgument method to directly map to the entity and since the entity is partial we're updating a bunch of fields to nulls.
So, ultimately I think we need a way to identify which fields are sent in mutation and only update those.

Thanks in advance.

**Comment by KreativJos** [comment]
Yes, we have done this before, but in a kind of hacky way (kan be done in a much better way, probably with observables or something in that direction).

Currently, it is solved by having a 'isChanged' property for every property in the model, like this:

`protected string _name;
        public bool IsNameSet { get; set; } = false;
        public string Name
        {
            get { return _name; }
            set
            {
                _name= value;
                IsNameSet = true;
            }
        }`

Then, when saving the data, we check if the property has been set.

`if (input.IsNameSet ) efItem.Name = input.Name;`

This can also be used for checking if an object should be created or updated for example, and working with sub-objects becomes easier that way.

**Comment by dylinmaust** [comment]
+1 - also interested in leveraging this technique

**Comment by michaelkrog** [comment]
IMO the Best solution is to load the entity from the backend, patch the loaded object and then persist it. Then it will work no matter what backend the entity comes from.

I created something similar for Json and Rest. I did not want to use json-patch as I find it cumbersome. I just wanted to be able to send a partial model.

Check out https://github.com/michaelkrog/rest-patch

**Comment by LarsCelie** [comment]
Would be nice to have support for this "out of the box"
Currently we have a generic solution where we check which input types are supplied, and only apply those values to the domain entity.

```
FieldAsync<ActivityType>(
    "createActivity",
    arguments: new QueryArguments(
        new QueryArgument<NonNullGraphType<ActivityInputType>> { Name = "activity" }
     ),
     resolve: async context =>
     {
         var activityFieldInputArguments = context.Arguments["activity"] as Dictionary<string, object>;
         // patch your entity based on field inputs here
     }
```

**Comment by aaronjedwards** [comment]
@joemcbride any thoughts on the issue? I am looking to solve the same problem. In the rest world I would take an incoming `JObject` from a `PATCH` request, patch an existing model and then persist the patched model. With an InputType model, I can't find a way to distinguish what has been explicitly set as null and what doesn't exist and is mapped as null with `GetArgument`.

**Comment by aaronjedwards** [comment]
@BenjaBobs @alexandercarls seems like you both have a similar approach. Would I need to have a dummy input type to capture the argument then?

**Comment by alexandercarls** [comment]
@aaronjedwards that is just a normal input graph type which can have `object` as the generic type argument. The field names have to be present for the schema + built-in validation, other than this I see no reason for an `UpdateFoo` DTO. As we work with the changes directly.

**Comment by BenjaBobs** [comment]
We do have the `UpdateFoo` in the schema, but we generate it based on attributes on our `Foo` class so we don't have to maintain both separately.

**Comment by aaronjedwards** [comment]
@alexandercarls thanks for the help! For now I was able to deserialize as `Dictionary<string, Object>` as was suggested and patch in a similar way as I had before by converting the deserialized dictionary to a `JObject` with `JObject.FromObject(deserialized)`, and then using the created `JObject`. My method of patching the model uses the `JsonSerializer.Populate` method. Not sure if I am doing myself injustice with that approach or not, but it works for now. I will look into using reflection as that may be a more reliable and effective way.

**Comment by aaronjedwards** [comment]
@BenjaBobs what do you mean/how do you generate your `UpdateFoo` DTO based on your `Foo` class if you don't mind me asking?

**Comment by BenjaBobs** [comment]
I use reflection to add a type to the schema that has the same properties as my data class, except all nullable.

**Comment by aaronjedwards** [comment]
(sorry for all the questions) and do you use a non specific Schema Type for the fields? or do you somehow map the data class property type to one of the library provided Schema Types?

**Comment by andrebts** [comment]
@aaronjedwards aproach worked for me. I'm using `GetArgument<dynamic>` and serializing it using `JsonConvert.SerializeObject` then by calling `JsonConvert.PopulateObject` I'm able to update only the fields that were informed.

**Comment by larsbloch** [comment]
I fixed this issue in my project by using reflection and passing down the dictionary that is in the context

Example

GraphQL part:
```
			this.AuthorizeWith("Authorized");
			Field<CharacterType>("updateCharacter", arguments: new QueryArguments(new QueryArgument<NonNullGraphType<CharacterInputType>> { Name = "character" }),
			resolve: context =>
			{
				var characterInput = context.GetArgument<IDictionary<string, object>>("character");

				var id = (long)characterInput.GetAndRemove("id");

				return characterRepository.UpdateCharacter(id, characterInput);
			});
```
My method in my repository (using entity framework)
```
		public Character UpdateCharacter(long id, IDictionary<string, object> values)
		{
			using (var db = new DbCon())
			{
				var result = db.Characters.FirstOrDefault(x => x.Id == id);
				result.UpdateObjectFromDict(values);
				db.SaveChanges();

				return result;
			}
		}
```
The extension method to update an object from a dictionary

```
        public static object UpdateObjectFromDict(this object someObject, IDictionary<string, object> source)
        {
            var someObjectType = someObject.GetType();
            foreach (var item in source)
                someObjectType.GetProperty(item.Key, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance).SetValue(someObject, item.Value, null);

            return someObject;
        }
```
        
I am no proffesional and i cant see if there should be any negatives using this solution. I think its simpler than what most people have suggested. And simplicity is pretty important in my opinion.
Feel free to suggest improvements : )

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/541#issuecomment-449123595 : 
> With an InputType model, I can't find a way to distinguish what has been explicitly set as null and what doesn't exist and is mapped as null with GetArgument.

Although further down the text I see that everyone came to the conclusion to work with the dictionary of arguments directly.

@Shane32 Anything else to note here? Closing ?

**Comment by Shane32** [comment]
Version 4 will allow overriding `ParseDictionary`, for a given `IInputObjectGraphType`, to be able to

> distinguish what has been explicitly set as null and what doesn't exist and is mapped as null

So this specific request is supported by v4, in a somewhat similar fashion to what was previously done.

It is noteworthy that if someone attempts to use the previous fix -- working with the dictionary of arguments directly -- they will find that by default the object type will be of type `TSourceType` in v4 (see below), not a dictionary.  This is a breaking change.  To revert to previous behavior, they will need to override `ParseDictionary` as follows:

```cs
public override object ParseDictionary(IDictionary<string, object> value) => value;
```

Then the dictionary will not be coerced to the `TSourceType` generic type of `InputObjectGraphType<TSourceType>`.  Further, the signature of `IResolveFieldContext.Arguments` has changed, another breaking change.

In the end, it may be that @larsbloch may still have the best answer, coupled with the code snippet above for v4.
