### ISSUE TITLE
AppVeyor NuGet feed URL

### ISSUE THREAD

**Issue by TwitchBronBron** [graphql-dotnet/graphql-dotnet#542]
Could the readme.md be updated to include the AppVeyor nuget feed for those of us who want to use the very latest builds without jumping through hoops in dotnet core (setting up local nuget repository) and without waiting for the official NuGet packages to be published? 

Once you've signed into AppVeyor, it's under the project settings -> NuGet. The URL defaults to the project name and random stuff after that, but you could configure it to have a meaningful name.

**Comment by joemcbride** [comment]
We push the packages to MyGet automatically for this.

https://www.myget.org/F/graphql-dotnet/api/v3/index.json

I would not suggest using the AppVeyor feed as it has some funky packages on there and I have no control over it.

**Comment by TwitchBronBron** [comment]
Oh ok. Good to know. Is this in the documentation somewhere and I just missed it? If it's not, do you think it would be valuable to put this link in the installation section as an alternative? Something like this:

# Installation
You can install the latest version via [NuGet](https://www.nuget.org/packages/GraphQL/).

`PM> Install-Package GraphQL`

Or you can get the latest pre-release packages from the [MyGet feed](https://www.myget.org/F/graphql-dotnet/api/v3/index.json).
