### ISSUE TITLE
GraphiQL.Core System.IO.FileLoadException in macOS

### ISSUE THREAD

**Issue by ericnograles** [graphql-dotnet/graphql-dotnet#545]
Hi there,

Great work on this library and sample project, I'm looking forward to kicking the tires on it as I get reacquainted with ASP .Net and C#!

I did encounter an issue (I'm running macOS High Sierra 10.13.2) when attempting to run the `GraphiQL.Core` project:

![image](https://user-images.githubusercontent.com/6023705/35777244-863529b4-0978-11e8-91f0-7353a0003947.png)

Note that I have not installed Mono (as I didn't think I needed it, but I could be wrong) and just tried taking this for a spin as a pure .Net Core app. Is there anything I'm missing?

Thanks for your help!

**Comment by OneCyrus** [comment]
it looks like grapgql 2.0 prereleases are not compatible with asp.net core 1.x. try to upgrade to asp.net 2.0.

**Comment by ericnograles** [comment]
Good call @OneCyrus. No luck with upgrading to 2.0, but I'm just going to use the `v0.17.3` branch for now till the latest gets stable. Thanks for the assist!

**Comment by joemcbride** [comment]
They are compatible with 1.x (I’m using it myself in a 1.x production project), though there is currently some churn in master.

Have you tried this example that uses nuget packages?  https://github.com/graphql-dotnet/example-aspnetcore

**Comment by SimonCropp** [comment]
@ericnograles any response to https://github.com/graphql-dotnet/graphql-dotnet/issues/545#issuecomment-362916829

is this still happening for you?

**Comment by sungam3r** [comment]
@ericnograles I closed it since there is no any activity on this issue. You can try latest stable 2.4.0 or preview 3.0.0 version. Feel free to post a new issue if such problem remains.
