### ISSUE TITLE
Question about Dependency Injection

### ISSUE THREAD

**Issue by nportelli** [graphql-dotnet/graphql-dotnet#546]
I may not be understanding how the dependency injection works in this library.  I've implemented a derived schema that takes in the FuncDependencyResolver.  Does that mean DI will work all the way down the graph?  For example if I have dependencies in the ObjectGraphType constructor, will it inject the needed dependency?

**Comment by joemcbride** [comment]
Yes that is the case.  One note though - at present once a `GraphType` is created it is cached in the Schema.  So those types will "live" for the lifetime of the Schema.

**Comment by SimonCropp** [comment]
@nportelli is this answered to your satisfaction? ok if we close?
