### ISSUE TITLE
Setting values on a union type?

### ISSUE THREAD

**Issue by FrederickBrier** [graphql-dotnet/graphql-dotnet#549]
I want to return a union of possible values to the client based on whether I was able to satisfy a request. If I could not, I was going to return a Guid, RequestId. If I could, return the Item. I looked through the tests, but while there are a lot of union tests, I did not see an example of marshaling the data from a POCO into an ObjectGraphType. Is that because C# does not have unions? BTW, I did not compile the code below, it is an attempt at simplifying the question.

```csharp
public class RequestId
{
   public Guid Id {get; set;}
}

public class Item
{
   public string Name {get; set;}
}

public class RequestIdType : ObjectGraphType<RequestId>
{
   public RequestIdType()
   {
      Name = "RequestId";
      Field(x => x.Id, type: typeof(IdGraphType), nullable: false).Description("Guid that is the Id of the pending request.");
   }
}

public class ItemType : ObjectGraphType<Item>
{
   public ItemType ()
   {
      Name = "Item";
      Field(x => x.Name).Description("Name of the item.");
   }
}

public class ResponseUnionType: UnionGraphType<???>
{
    public ResponseUnionType()
    {
       Name = "ResponseUnion";

       Type<RequestIdType>();
       Type<ItemType>();
       ResolveType = value => null;
    }
}
```

So is there a C# class that goes in the <???> and what does it look like? Or do I need another class as in the test class "ValidationQueryRoot", such as:

```csharp
public class ResponseResultType : ObjectGraphType<???>
{
   public ResponseResultType()
   {
      Field<ResponseUnionType>("Result");
   }
}
```

If so, what does the C# class that contains the data look like. Would it be the type passed in <???> Does it have a base "object" data member in the class to which either RequestId or Item could be assigned? And uses the Field name "Result" to map it?

```csharp
public class ResponseResult
{
   public object Result {get; set;}
}
```

I also looked at the ObjectGraphType derived classes, and do not see how I would set values in them, so I assume they are merely the grammar metadata used to marshal to JSON.

**Comment by FrederickBrier** [comment]
I attempted the above approach and am still getting an exception trace from GraphiQL.

```json
Error: Introspection must provide object type for possibleTypes.
    at invariant (http://localhost:8888/GraphQL/graphiql.js:24179:11)
    at getObjectType (http://localhost:8888/GraphQL/graphiql.js:29999:29)
    at Array.map (<anonymous>)
    at **buildUnionDef** (http://localhost:8888/GraphQL/graphiql.js:30076:47)
    at buildType (http://localhost:8888/GraphQL/graphiql.js:30020:16)
    at getNamedType (http://localhost:8888/GraphQL/graphiql.js:29980:19)
    at http://localhost:8888/GraphQL/graphiql.js:30151:12
    at Array.map (<anonymous>)
    at buildClientSchema (http://localhost:8888/GraphQL/graphiql.js:30150:41)
    at http://localhost:8888/GraphQL/graphiql.js:2140:55
```
 GraphiQL was displaying the schema in the documentation panel, but now it is not. This type of error trace can occur if you do not use an InputObjectGraphType, however I am, and the stack trace has a buildUnionDef call. I am only using the UnionGraphType to output a response.

I was also thinking the marshaling could occur from a C# object that looked like:
```csharp
public class ResponseResult
{
   public RequestId RequestId {get; set;}
   public Item Item {get; set;}
}
```
And only one item would be non-null.

**Comment by joemcbride** [comment]
I would suggest reading about Unions here: http://graphql.org/learn/schema/#union-types

A Union means the result may be any of the types defined in the Union.

For this library's specific implementation I would suggest reading about `ResolveType` and `IsTypeOf`.

https://graphql-dotnet.github.io/getting-started/#resolvetype
https://graphql-dotnet.github.io/getting-started/#istypeof

In your resolver you return the value you want mapped, and `ResolveType` or `IsTypeOf` is used to make a determination of which `GraphType` to use to map the values over the transport.

There is no `UnionGraphType<T>` because a Union can have an unlimited number of members and that makes it hard to try to use generics.

Unfortunately I don't think what you're wanting to use a Union for will work.  If you want to have a result type with optional members then I would just use an `ObjectGraphType<T>` and add fields for each of the items.

**Comment by sungam3r** [comment]
May be related to graphql/graphql-spec#215

**Comment by sungam3r** [comment]
@FrederickBrier Is this issue still actual for you?

**Comment by FrederickBrier** [comment]
No. I defined an API which is in production now. Thank you. I am closing the ticket. Sorry about that.
