### ISSUE TITLE
Argument datatype mismatch

### ISSUE THREAD

**Issue by ManishTrivedi** [graphql-dotnet/graphql-dotnet#55]
I have noticed that an error is not thrown when the argument datatypes do not match. 

```
public APIQuery()
        {
            Name = "APIQuery";
            Field<UserType>(
                "GetUserById",
                arguments: new QueryArguments(
                    new[]
                    {
                        new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "id",      Description = "id of the user" }
                    }),
                resolve: context => UserData.GetUser((string)context.Arguments["id"])
                );
        }
```

If I pass an int as the id, there is no error. I thought GraphQL is strongly typed. Or am I missing something?

PS. I am using id as a string for testing purposes
Thank you.

**Comment by joemcbride** [comment]
Validation has not yet been implemented.  There is some basic validation in the core engine, though overall validation isn't in yet.  Thats the last major feature left.  https://github.com/graphql-dotnet/graphql-dotnet/issues/10

**Comment by joemcbride** [comment]
Going to close this.  Thanks!
