### ISSUE TITLE
Q:  Pagination

### ISSUE THREAD

**Issue by MakaBuka** [graphql-dotnet/graphql-dotnet#555]
Hi guys,

I've just read GraphQL topic regarding pagination - http://graphql.org/learn/pagination/ 
and didn't find any implementation of it (first or after) in GraphQL .net lib (except couple directives like @skip(if: T/F) or Include) 
So, it hasn't been implemented yet, right? or I'm no good at searching and missed something?

Thx, D.

**Comment by joemcbride** [comment]
We do have some basic cursor pagination support with `Connection`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs

There is a bit more support and helpers around nodes/edges/connections in the Relay project.  https://github.com/graphql-dotnet/relay

**Comment by jphenow** [comment]
Have you implemented a project that uses this form of paginatiton @joemcbride? Just hobbled through some errors to get it half-working, but was wondering if we could get an example? If that's tough for you in the next few days, I'll try to wrap up my attempts and push a PR - if there's issues we can fix there

**Comment by MakaBuka** [comment]
@jphenow haven't implemented yet (not be able to do it, at least during this week).
For sure, keep us posted with attempts here

**Comment by jphenow** [comment]
Nope, sorry! I've been focused elsewhere in the last several weeks. If I can spend a few minutes I'll try to come back and see if it can at least have an example so it can easily plug in to Apollo - maybe Relay's that seems like more of an undertaking.

**Comment by Tochemey** [comment]
Hello,

Can someone please guide us in how to implement the pagination feature in graphl?.

**Comment by athurner** [comment]
A example of how to implement pagination would be very much appreciated. 

Thank you

**Comment by denisedelbando** [comment]
i've implemented something but not utilizing the directives.
https://github.com/denisedelbando/AspNetGraphQL/blob/master/Data/Schema/Type/CompanyType.cs

**Comment by RehanSaeed** [comment]
There is a fully working example of bi-directional pagination using Connection in the [ASP.NET Core GraphQL Boxed](https://github.com/Dotnet-Boxed/Templates/blob/master/Docs/GraphQL.md) project template.

**Comment by dasoncheng** [comment]
## source

```cs
public class PaginationListType<T, U> : ObjectGraphType<PaginationList<U>> where T : IGraphType
{
    public PaginationListType()
    {
        Name = String.Format("PaginationList{0}", typeof(U).Name);

        Field(x => x.Total).Description("Total");
        Field(x => x.Size).Description("Size");
        Field(x => x.Index).Description("Index");
        Field(x => x.Pages).Description("Pages");
        Field<ListGraphType<T>>(
            name: "Data",
            description: "Data",
            resolve: context => context.Source.Data
        );
    }
}

public class PaginationList<T>
{
    public int Total { get; set; }
    public int Size { get; set; }
    public int Index { get; set; }
    public int Pages { get; set; }
    public IEnumerable<T> Data { get; set; } = new List<T>();
}


FieldAsync<PaginationListType<RoleType, Role>>(
    name: "roles",
    arguments: new QueryArguments(
        new QueryArgument<IntGraphType> { Name = "size", Description = "size" },
        new QueryArgument<IntGraphType> { Name = "index", Description = "index" },
        new QueryArgument<StringGraphType> { Name = "search", Description = "search" },
        new QueryArgument<ListGraphType<StringGraphType>> { Name = "asc", Description = "asc" },
        new QueryArgument<ListGraphType<StringGraphType>> { Name = "desc", Description = "desc" }
    ),
    resolve: async context =>
    {
        var query = new PaginationListQuery
        {
            Size = context.GetArgument<int>("size", 20),
            Index = context.GetArgument<int>("index", 20),
            Search = context.GetArgument<string>("search"),
            Asc = context.GetArgument<IEnumerable<string>>("asc"),
            Desc = context.GetArgument<IEnumerable<string>>("desc"),
        };
        // Task<PaginationList<Role>> GetRolesAsync(PaginationListQuery query);
        var list = await roleRepository.GetRolesAsync(query);
        return list;
    }
);
```

## query

```
query GetData {
  roles(size: 30, index: 2) {
    total
    pages
    size
    index
    data {
      ...CommonRole
    }
  }
}
```

## result

```
{
  "data": {
    "roles": {
      "total": 4,
      "pages": 1,
      "size": 30,
      "index": 1,
      "data": [
           ...
      ]
    }
  },
  "extensions": {}
}
```

**Comment by JasminSinanovic** [comment]
> ```cs
> PaginationListQuery
> ```

Could you pleas give me information what is "PaginationListQuery" is that custom object ?

**Comment by dasoncheng** [comment]
@JasminSinanovic `PaginationListQuery` is a custom object used to construct query parameters

**Comment by Shane32** [comment]
Please open a new issue if there are further questions on this topic.
