### ISSUE TITLE
Q: efficient filtering for data volumes

### ISSUE THREAD

**Issue by ujwaliyer** [graphql-dotnet/graphql-dotnet#556]
It looks like the filtering is completely custom, where u can to get the argument and then access ur ORM, and filter it. 

But this would mean that I need to get the resultset in memory, perform linq on it and get a filtered result set. 

Also does the JS version have some new developments on this side? 

Is there an efficient, recommended way to perform filtering on such data sets(not big data, but large nevertheless). 

Any best practices, and pointers wud be great! Tks!

**Comment by joemcbride** [comment]
Are you talking about across fields or in a single field?

You would only be doing filtering in-memory if your ORM didn't support the query you are trying to do.

There is a `DataLoader` pattern that can be used for efficient querying across fields.  This is a new feature just added to this project.

https://github.com/facebook/dataloader (javascript implementation by Facebook)

https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.DataLoader.Tests (Tests for the `DataLoader`)
https://github.com/graphql-dotnet/graphql-dotnet/pull/540 (PR for updates to the `DataLoader` pattern in this repo)

**Comment by ujwaliyer** [comment]
so i can using Dapper or Iqueryable EF to directly execute my filter clauses on the server right. that shud be the way going forward.

**Comment by joemcbride** [comment]
Yep.  Here's a basic example using Dapper.

```csharp
public class InvoiceData
{
    public Invoice GetInvoiceByID(int id)
    {
        using (var db = new SqlConnection("Connection String"))
        {
            const string sql = "SELECT * FROM Invoice WHERE InvoiceID = @InvoiceID;";
            return db.QueryFirstOrDefault<Invoice>(sql, new {InvoiceID = id});
        }
    }
}


public class QueryObjectType : ObjectGraphType
{
    public QueryObjectType(InvoiceData data)
    {
        Name = "Query";
        Field<InvoiceObjectType>(
            "invoice",
            arguments:  new QueryArguments(
              new QueryArgument<NonNullGraphType<IntGraphType>> { Name ="invoiceID"}
            ),
            resolve: ctx =>
            {
              return data.GetInvoiceByID(ctx.GetArgument<int>("invoiceID"))
            });
    }
}
```

**Comment by DrSensor** [comment]
I also curious is it possible to implement multiple Query Arguments?
<details>
<summary><b>Example</b></summary>

```graphql
query getActors(
    filter: {
        movies_some: {
            releaseDate_gte: "2009"
        }
    }
    first: 3
    orderBy: name_ASC
) 
{
    name
    movies {
        title
    }
}
```
</details>

**Comment by SimonCropp** [comment]
@ujwaliyer would this help you? https://github.com/SimonCropp/GraphQL.EntityFramework

**Comment by SimonCropp** [comment]
@joemcbride @sungam3r this this one should be closed?
