### ISSUE TITLE
Unable to use object in mutation.

### ISSUE THREAD

**Issue by ericklind** [graphql-dotnet/graphql-dotnet#557]
I've been trying to get a mutation to work in graphiql for several days.
Here's the mutation:

 ```
public class DataViewMutation : ObjectGraphType
    {
        public DataViewMutation(IDataViewRepository data)
        {
            Name = "DataViewMutation";

            Field<DataViewType>(
                "createDataView",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<DataViewInputType>> { Name = "dataView" }
                ),
                resolve: context =>
                {
                    var dataView = context.GetArgument<DataViewInputType>("dataView");
                    
                    var name = context.GetArgument<string>("viewName");
                    var fields = context.GetArgument<ListGraphType<StringGraphType>>("viewColumns");

                    return data.Query(new string[] { "" }, "");//This is empty for now, but I don't even get this far.
                });
        }
    }
}
```
Here's the input type:
```
public class DataViewInputType : InputObjectGraphType<DataViewType>
{
        public DataViewInputType()
	{
	   Name = "DataViewInput";
            Field<NonNullGraphType<StringGraphType>>("viewName");
            Field<NonNullGraphType<StringGraphType>>("clientName",
            resolve: context =>
            {
                return context.GetArgument<List<string>>("clientName");
            });
            Field<ListGraphType<StringGraphType>>("viewColumns",
                resolve: context => {
                    var columns = context.GetArgument<List<string>>("viewColumns");
                    return columns;
                    }
                );
	 }
}
```

Here's the call to the mutation:

```
mutation DataView($dataView: DataViewInput!) {
  createDataView(dataView: $dataView) {
    viewName
    viewColumns {
      columnName
      
    }
  }
}
```
variables:

```
{
  "dataView": {
    "viewName": "v_ReadyReports",
    "clientName": "Suntime",
    "viewColumns": [
      "id",
      "product"
    ]
  }
}
```

And here's the error:
```
{
  "errors": [
    {
      "message": "GraphQL.ExecutionError: Variable '$dataView' is invalid. Unable to parse input as a 'DataViewInput' type. Did you provide a List or Scalar value accidentally? ---> GraphQL.Execution.InvalidValueException: Variable '$dataView' is invalid. Unable to parse input as a 'DataViewInput' type. Did you provide a List or Scalar value accidentally?\r\n   at GraphQL.DocumentExecuter.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)\r\n   at GraphQL.DocumentExecuter.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)\r\n   at GraphQL.DocumentExecuter.GetVariableValue(Document document, ISchema schema, VariableDefinition variable, Object input)\r\n   at GraphQL.DocumentExecuter.<>c__DisplayClass28_0.<GetVariableValues>b__0(VariableDefinition v)\r\n   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)\r\n   at GraphQL.DocumentExecuter.GetVariableValues(Document document, ISchema schema, VariableDefinitions variableDefinitions, Inputs inputs)\r\n   at GraphQL.DocumentExecuter.BuildExecutionContext(ISchema schema, Object root, Document document, Operation operation, Inputs inputs, Object userContext, CancellationToken cancellationToken, Metrics metrics)\r\n   at GraphQL.DocumentExecuter.<ExecuteAsync>d__12.MoveNext()\r\n   --- End of inner exception stack trace ---"
    }
  ]
}
```

I've tried everything I can think of but I've been stuck for several days. How do I get this to work?

-Erick

**Comment by joemcbride** [comment]
Input objects are essentially POCOs, so with your `DataViewInputType` you shouldn't need any resolvers.  In fact, you're trying to use Arguments in `DataViewInputType` but you have no arguments defined.  I will have to double-check, though I don't think you're allowed to use Arguments with input objects, so that may be an API Design issue.

It seems that error is typically from a mis-match between null and non-null definitions in the query/mutation.  You are using `DataViewInput!` in your mutation so that seems correct based on your definition in `DataViewMutation `.

> Unable to parse input as a 'DataViewInput' type

Notice that the error does not have a `!` on the type, so perhaps somewhere isn't sending the mutation incorrectly?  Have you tried this out with just a basic http request using something like Postman?

```csharp
var dataView = context.GetArgument<DataViewInputType>("dataView");
var name = context.GetArgument<string>("viewName");
var fields = context.GetArgument<ListGraphType<StringGraphType>>("viewColumns");
```

The above fetching of the arguments is invalid.  You need to use a POCO object and not the `GraphType`.  Then you just use the values on the POCO.

```
public class DataViewInput
{
  public string ViewName { get; set; }
  public string ClientName { get; set; }
  public List<string> ViewColumns { get; set; }
}

var dataView = context.GetArgument<DataViewInput>("dataView");
dataView.ViewName
...
```

**Comment by ericklind** [comment]
Thanks for getting back to me Joe. I changed the DataViewInput to what you posted above.  I changed the mutation to this:
 ```
public class DataViewMutation : ObjectGraphType
    {
        public DataViewMutation(IDataViewRepository data)
        {
            Name = "DataViewMutation";

            Field<DataViewType>(
                "createDataView",

                resolve: context =>
                {
                    var dataView = context.GetArgument<DataViewInput>("dataView");
                    Debug.WriteLine(dataView.ViewColumns);
                
                    return data.Query(new string[] { "" }, "");
                });
        }
    }
```
But I'm still getting errors:
```
{
  "errors": [
    {
      "message": "GraphQL.Validation.ValidationError: Variable \"dataView\" cannot be non-input type \"DataViewInput\".",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ]
    },
    {
      "message": "GraphQL.Validation.ValidationError: Unknown type DataViewInput. Did you mean \"DataViewQuery\" or \"DataView\"?",
      "locations": [
        {
          "line": 2,
          "column": 30
        }
      ]
    },
    {
      "message": "GraphQL.Validation.ValidationError: Unknown argument \"dataView\" on field \"createDataView\" of type \"DataViewMutation\".",
      "locations": [
        {
          "line": 3,
          "column": 18
        }
      ]
    }
  ]
}
```

Thoughts?

Thanks,

Erick

**Comment by joemcbride** [comment]
You will still need the argument on your mutation.

```
public class DataViewMutation : ObjectGraphType
    {
        public DataViewMutation(IDataViewRepository data)
        {
            Name = "DataViewMutation";

            Field<DataViewType>(
                "createDataView",
                arguments: new QueryArguments(
                   new QueryArgument<NonNullGraphType<DataViewInputType>> { Name = "dataView" }
               ),
                resolve: context =>
                {
                    var dataView = context.GetArgument<DataViewInput>("dataView");
                    Debug.WriteLine(dataView.ViewColumns);
                
                    return data.Query(new string[] { "" }, "");
                });
        }
    }
```

How are you trying to run the mutation?  Through graphiql?  Postman? Apollo?  If any of those, what version are you using?

**Comment by ericklind** [comment]
So I need to create a DataViewInput and a DataViewInputType?  What should the definition of the DataViewInputType look like? Something like this?

```
	public class DataViewInputType : ObjectGraphType<DataViewInput>
	{
		public DataViewInputType(IDataViewRepository data)
		{
			Name = "DataView";

			Field(r => r.ViewName).Description("ViewName");
			Field(r => r.ClientName).Description("Fields to pull from the database");
                        Field(r => r.ViewColumns).Description("List of view columns for the report.");
               }
       }
```
I'm using graphiql, using this cdn: https://cdn.jsdelivr.net/graphiql/0.7.5/graphiql.min.js

**Comment by joemcbride** [comment]
Yes, you need an InputType for GraphQL, and the POCO class for easier mapping from the raw dictionary.  The POCO class isn't necessary but makes it way easier to work with.

For input objects you need to use `InputObjectGraphType<T>` vs. `ObjectGraphType<T>`.  Also since they're basically just POCOs you probably don't need any dependencies in the constructor.

```
public class DataViewInputType : InputObjectGraphType<DataViewInput>
{
    public DataViewInputType(IDataViewRepository data)
    {
        Name = "DataView";

        Field(r => r.ViewName).Description("ViewName");
        Field(r => r.ClientName).Description("Fields to pull from the database");
        Field(r => r.ViewColumns).Description("List of view columns for the report.");
    }
}
```

**Comment by joemcbride** [comment]
Oh - and the version of graphiql may be the issue.  I've been using 0.11.2+ on projects with latest pre-release versions of GraphQL.NET.

**Comment by ericklind** [comment]
I'm still getting errors, but I have to switch to another project. I'll swap out the graphiql next week and get back to you.  Thanks!

**Comment by JSanchezIO** [comment]
I think this also might be related to your variables not being sent over as a string. Variables should be posted over as a JSON string and then converted to Inputs using the `.ToInputs()` extension method.

e.g. 
```json
{
"query": "mutation ($someVarName: DataViewInput!) { createDataView(dataView: $someVarName) { PROPERTIES_I_WANT_BACK_AFTER_MUTATION }}",
"variables": "{'someVarName': { 'viewName': 'my-view', 'clientName': 'my-client', 'viewColumns': ['column1', 'column2' ] }"
}
```

**Comment by ericklind** [comment]
I'm not having any issues with the JSON. Variables are being deserialized properly and I can see them at the breakpoints. I have the code implemented per Joe's instructions but I am still getting the following errors:

```
{
  "errors": [
    {
      "message": "GraphQL.Validation.ValidationError: Variable \"dataView\" cannot be non-input type \"DataViewInput\".",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ]
    },
    {
      "message": "GraphQL.Validation.ValidationError: Unknown type DataViewInput. Did you mean \"DataViewQuery\" or \"DataView\"?",
      "locations": [
        {
          "line": 2,
          "column": 30
        }
      ]
    }
  ]
}
```

Thoughts?

**Comment by JSanchezIO** [comment]
You mind posting your mutation and input?

**Comment by joemcbride** [comment]
Lets break down the error:

> Unknown type DataViewInput

This means there is no `DataViewInput` type registered with your `Schema`, which is a type you must be using in your mutation request.

> Did you mean \"DataViewQuery\" or \"DataView\"?

The `InputObjectGraphType` example I posted used the `Name` `DataView`.  So you probably have a name mis-match.

> Variable \"dataView\" cannot be non-input type \"DataViewInput\".

While this error is "valid" per say, it is caused by the other issue.  Since `DataViewInput` does not exist in the `Schema`.

**Comment by ericklind** [comment]
Here's the Schema:

```
	public class DataViewSchema : Schema
	{
		public DataViewSchema(IDependencyResolver resolver) : base(resolver)
		{
			Query = resolver.Resolve<DataViewQuery>();
            Mutation = resolver.Resolve<DataViewMutation>();
		}
	}
```
Here's the mutation:

```
 public class DataViewMutation : ObjectGraphType
    {
        public DataViewMutation(IDataViewRepository data)
        {
            Name = "DataViewMutation";

            Field<DataViewType>(
                "createDataView",
                arguments: new QueryArguments(
                   new QueryArgument<NonNullGraphType<DataViewInputType>> { Name = "dataView" }
               ),
                resolve: context =>
                {
                    var dataView = context.GetArgument<DataViewInput>("dataView");
                    Debug.WriteLine(dataView.ViewColumns);
                
                    return data.Query(new string[] { "" }, "");
                });
        }
    }
```
Here's the DataViewInput:

```
 public class DataViewInput
    {
        public string ViewName { get; set; }
        public string ClientName { get; set; }
        public List<string> ViewColumns { get; set; }
    }
```
And lastly, the DataViewInputType:

```
public class DataViewInputType : InputObjectGraphType<DataViewInput
{
	public DataViewInputType(IDataViewRepository data)
	{
			Name = "DataView";

			Field(r => r.ViewName).Description("ViewName");
			Field(r => r.ClientName).Description("Fields to pull from the database");
            Field(r => r.ViewColumns).Description("List of view columns for the report.");
        }
}
```
Also, here are my entries in the Startup ConfigureServices:

```
services.AddScoped<IDataViewRepository, DataViewRepository>();
services.AddScoped<DataViewInput>();
services.AddScoped<DataViewInputType>();
services.AddTransient<DataViewType>();
services.AddScoped<DataViewMutation>();
services.AddScoped<DataViewQuery>();
```

**Comment by ericklind** [comment]
@joemcbride  I missed your post about the Name="DataView". Changing that seemed to help, but now I'm getting an issue deserializing the variables using NewtonSoft.  It doesn't seem to like converting that to a dictionary<string, object> which is weird because that part was working before, but now it's not. O_o

Any idea why it would have an issue with the Variables property:
```
[JsonProperty("variables")]
public Dictionary<string, object> Variables { get; set; }
```
And the variables from the query:
`{\n  \"dataView\": {\n    \"viewName\": \"v_ReadyReports\",\n    \"clientName\": \"Suntime\",\n    \"viewColumns\": [\n      \"id\",\n      \"product\"\n    ]\n  }\n}
`
throwing this error:
Error converting value \"{\n  \"viewName\": \"v_ReadyReports\"\n}\" to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'. Path 'variables', line 1, position 236."


Thoughts?

Thanks,

Erick

**Comment by joemcbride** [comment]
I suggest to use a JObject instead.  Example here:

https://github.com/graphql-dotnet/example-aspnetcore/blob/master/src/Example/GraphQLRequest.cs

**Comment by JSanchezIO** [comment]
@joemcbride I thought `string` wasthe preferred type, for `variables`, followed by using the `.ToInputs()` extension method. Has that changed?

**Comment by joemcbride** [comment]
@JSanchezIO It all depends on your server setup.  `string` _seems_ to work fine with old ASP.NET MVC.  `JObject` seems to work better with .NET Core.  `JObject` should work in both places though, so I have started to just suggest that.  You still use `.ToInputs` with `JObject`.  If you use `.ToInputs` with a `string` it essentially just converts it to a `JObject` first.

**Comment by ericklind** [comment]
Joe, I adjusted the Variables property to JObject and used the Deserializer code in the example and it's telling me that it cannot convert a JValue object to JObject for the Variables property.  Is there some other setting I need for the deserializer?

**Comment by joemcbride** [comment]
@ericklind Its extremely difficult to debug your code without actually having it in hand.  That error tells me that either you have an invalid request or some setup wrong.  Are you able to push your code so I see your setup?  If not, I would suggest to fork the working examples or use the existing .NET Core middleware that is setup for you.

ASP.NET MVC: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Controllers/GraphQLController.cs
ASP.NET MVC Core: https://github.com/graphql-dotnet/example-aspnetcore
ASP.NET Core Middleware: https://github.com/graphql-dotnet/server

**Comment by ericklind** [comment]
I can't fork it as it's company code. But here are the relevant bits:

```
public class GraphQLQuery
{
	[JsonProperty("query")]
	public string Query { get; set; }

	[JsonProperty("variables")]
        //public Dictionary<string, object> Variables { get; set; }
        public JObject Variables { get; set; }

        [JsonProperty("operationName")]
	public string OperationName { get; set; }
}
```
The deserialization code:

   ```
public static T Deserialize<T>(Stream s)
        {
            using (var reader = new StreamReader(s))
            using (var jsonReader = new JsonTextReader(reader))
            {
                var ser = new JsonSerializer();
                return ser.Deserialize<T>(jsonReader);
            }
     }
```
The call where it's crashing:

```
private async Task ExecuteAsync(HttpContext context)
		{
			try
			{
                var request = Deserialize<GraphQLQuery>(context.Request.Body);
//,....Other code
}
}
```
And finally, the error message:

InnerException: {System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.
   at lambda_method(Closure , Object , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)}
    Message: "Error setting value to 'Variables' on 'Sift.GraphQL.Server.Common.GraphQLQuery'."
    Source: "Newtonsoft.Json"

I'll check out the other samples that you've suggested.

**Comment by joemcbride** [comment]
That error is telling you that you are trying to cast a Value (such as a string, int, etc.) to an Object.  So that tells me that the variables you are passing to the server is probably a `string`, which to match to your server configuration, it should be a JSON object.

Not this:

```json
{
  ...
  "variables": "{'someVarName': { 'viewName': 'my-view', 'clientName': 'my-client', 'viewColumns': ['column1', 'column2' ] }}"
}
```

But this:

```json
{
  ...
  "variables": {
    "someVarName": {
      "viewName": "my-view",
      "clientName": "my-client",
      "viewColumns": ["column1", "column2" ]
    }
  }
}
```

**Comment by ericklind** [comment]
Hmmm....It is coming back as the second. It's from Graphiql:
```
{
  "dataView": {
    "viewName": "v_ReadyReports",
    "clientName": "Suntime",
    "viewColumns": [
      "id",
      "product"
    ]
  }
}
```

**Comment by joemcbride** [comment]
That is the variables pasted into GraphiQL, but did you confirm that that is what the actual http request looks like?  The actual http request should have a different structure than that, `variables` should be the top level and `dataView` and everything else should be an object under it.  What version of GraphiQL are you using?

**Comment by ericklind** [comment]
Here's the request:
`"{\"query\":\"\\nmutation DataView($dataView: DataViewInputType) {\\n  createDataView(dataView: $dataView) {\\n    viewName\\n    viewColumns {\\n      columnName\\n      \\n    }\\n  }\\n}\\n\",\"variables\":\"{\\n  \\\"dataView\\\": {\\n    \\\"viewName\\\": \\\"v_ReadyReports\\\",\\n    \\\"clientName\\\": \\\"Suntime\\\",\\n    \\\"viewColumns\\\": [\\n      \\\"id\\\",\\n      \\\"product\\\"\\n    ]\\n  }\\n}\",\"operationName\":\"DataView\"}"
`
I'm using Graphiql 0.7.5. I tried using the latest, and it was causing some issues.  I give it another go.

Thanks for responding and being so helpful!

**Comment by joemcbride** [comment]
So that request appears to be sending the variables as a string.  Newer versions of GraphiQL send it as the JSON structure.  You just need to have your server match whichever way you want to use it.

**Comment by ericklind** [comment]
Okay, I dropped in the 0.11.11 version. I'm not getting the previous error, but now it deserializes to null.

**Comment by ericklind** [comment]
Switch back to my previous deserialization with the JObject and it seems to be working.  Thanks!

**Comment by ericklind** [comment]
Actually the mutation is not. :( Let me work through some of it.

**Comment by ericklind** [comment]
Finally! Have it working as expected. Phew! Thanks Joe.

**Comment by joemcbride** [comment]
🎉

**Comment by kirill-chilingarashvili** [comment]
With latest GraphQL and request onject as below, I was getting the same exception:
```c#
       public class RequestVm
        {
            public string OperationName { get; set; }
            public string NamedQuery { get; set; }
            public string Query { get; set; }
            public Dictionary<string, object> Variables { get; set; }
        }
```

The fix was to change dictionary to JObject
```c#
       public class RequestVm
        {
            public string OperationName { get; set; }
            public string NamedQuery { get; set; }
            public string Query { get; set; }
            public Newtonsoft.Json.Linq.JObject Variables { get; set; }
        }
```

I also had to change 
```c#
                var inputs = query.Variables != null ?
                    new Inputs(query.Variables) :
                    new Inputs();
```
to
```c#
                var inputs = query.Variables.ToInputs();
```

**Comment by sajadghobadi** [comment]
> Switch back to my previous deserialization with the JObject and it seems to be working. Thanks!

can you share your fixed codes.
