### ISSUE TITLE
Q: How do i throw an error for a field?

### ISSUE THREAD

**Issue by Wavum** [graphql-dotnet/graphql-dotnet#563]
How do i throw an error for a field as described [here](https://facebook.github.io/graphql/October2016/#sec-Errors-and-Non-Nullability).
I tried to throw an error in a field middleware like this
```c#
public FieldMiddlewareDelegate Resolve(FieldMiddlewareDelegate next) {
    return context => {
        if (context.FieldName == "id") {
            context.Errors.Add(new ExecutionError("Test-Error"));
        }

        return next(context);
    };
}
```
But I don't get response body, all I get is a HTTP status of 400.

**Comment by jquense** [comment]
How are you handling errors in your endpoint?

**Comment by Wavum** [comment]
@jquense
Now I see where I made the mistake. I have used this [project](https://github.com/JacekKosciesza/StarWars) as a template. My error handling now looks like this
```c#
if (result.Errors?.Count > 0) {
    returnValue = BadRequest(result);
}
```
instead of `returnValue = BadRequest();`. My response body looks now like this
```json
{
    "data": {
        "hero": {
            "id": 1,
            "name": "San Holo"
        }
    },
    "errors": [
        {
            "message": "Test-Error"
        }
    ]
}
```
Is there a way to set `id` automatically to null when i add an error for this field?

**Comment by johnrutherford** [comment]
If you `throw` the `ExecutionError`, the field should get set to null.

**Comment by pouladpld** [comment]
@johnrutherford I tired throwing `ExecutionError` but I get the whole exception serialized in json:

```json
{
    "data": {
        "firstName": {
            "ClassName": "GraphQL.ExecutionError",
            "Message": "some error",
            "Data": null,
            "InnerException": null,
            "HelpURL": null,
            "StackTraceString": null,
            "RemoteStackTraceString": null,
            "RemoteStackIndex": 0,
            "ExceptionMethod": null,
            "HResult": -2146233088,
            "Source": null,
            "WatsonBuckets": null
        }
    }
}
```

**Comment by pouladpld** [comment]
I believe there should be another catch block to allow users define their own custom exceptions. Maybe using an `ExecutionError`.

Users should be able to define `message`, `localtion` and `path` for an error. [Specs here](http://facebook.github.io/graphql/October2016/#sec-Errors).

https://github.com/graphql-dotnet/graphql-dotnet/blob/514fa76063c05cf3e4d60514c1b6eedb5ac69722/src/GraphQL/Execution/ExecutionStrategy.cs#L224-L233

**Comment by Wavum** [comment]
@johnrutherford This works for me, thanks.
@pouladpld I created an own issue for this #564.
