### ISSUE TITLE
Define custom ExecutionError

### ISSUE THREAD

**Issue by Wavum** [graphql-dotnet/graphql-dotnet#564]
Users should be able to define `message`, `location` and `path` for an `ExecutionError` as described [here](https://facebook.github.io/graphql/October2016/#sec-Errors).

Currently this is not possible.
https://github.com/graphql-dotnet/graphql-dotnet/blob/514fa76063c05cf3e4d60514c1b6eedb5ac69722/src/GraphQL/Execution/ExecutionStrategy.cs#L224-L233

_Originally mentioned by @pouladpld [here](https://github.com/graphql-dotnet/graphql-dotnet/issues/563#issuecomment-366491151)._

**Comment by pouladpld** [comment]
Also, I'd prefer to derive from that exception class and make my own custom error to include more machine readable data like error `type`.

**Comment by joemcbride** [comment]
Can you elaborate on why you believe that this is not possible?  You can use essentially that same code in your resolver and return null to provide the same result, or provide a more generic try/catch in field middleware to do the same.

**Comment by pouladpld** [comment]
@joemcbride That's a good idea. I tried and there is a small problem.

here is my resolve func to get user by its username.

```c#
public async Task<User> GetUserAsync(ResolveFieldContext<object> context)
{
    string username = context.GetArgument<string>("id");
    UserEntity entity;
    try
    {
        entity = await _userRepo.GetByNameAsync(username, cancellationToken: context.CancellationToken);
    }
    catch (EntityNotFoundException)
    {
        context.Errors.Add(new Error("not found") // "Error" inherits from "ExecutionError"
        {
            Type = "ID_ERROR",
            Path = new[] {"user"}
        });
        return default;
    }

    return (User) entity;
}
```

#### Expected

- `data` should have value of `null` or could be omitted.
- `type` of error

```json
{
    "data": null,
    "errors": [
        {
            "message": "not found",
            "type": "ID_ERROR",
            "path": [
                "user"
            ]
        }
    ]
}
```

#### Actual

```json
{
    "data": {
        "user": null
    },
    "errors": [
        {
            "message": "not found",
            "path": [
                "user"
            ]
        }
    ]
}
```

**Comment by pouladpld** [comment]
In addition, how can I properly assign these 2 values to my exception from outside of `ExecutionStrategy`?

```c#
error.AddLocation(node.Field, context.Document); 
error.Path = node.Path; 
```

**Comment by pouladpld** [comment]
I'd suggest to add two more catch blocks to `ExecutionStrategy`:

```c#
catch (ExecutionError error)
{
    error.AddLocation(node.Field, context.Document); 
    error.Path = node.Path; 
    context.Errors.Add(error);
    node.Result = null; 
}
catch (AggregateException ex)
    when (ex.InnerExceptions.All(e => e is ExecutionError))
{
    context.Errors.AddRange(ex.InnerExceptions
        .Select(error =>
        {
            error.AddLocation(node.Field, context.Document); 
            error.Path = node.Path; 
        }
    );
    node.Result = null; 
}
catch (Exception ex) 
{ 
    var error = new ExecutionError($"Error trying to resolve {node.Name}.", ex); 
    error.AddLocation(node.Field, context.Document); 
    error.Path = node.Path; 
    context.Errors.Add(error); 
    node.Result = null; 
}
```

**Comment by joemcbride** [comment]
Agreed that having those extra error handlers would be nice.  Path, Field (FieldAst) and Document are all found on the FieldResolutionContext so you can use those to call AddLocation and set Path.

**Comment by joemcbride** [comment]
Also note that at present other fields are not serialized.  So that is an example of something not currently possible.  Have ideas for making that easier to customize?

https://github.com/graphql-dotnet/graphql-dotnet/blob/514fa76063c05cf3e4d60514c1b6eedb5ac69722/src/GraphQL/Execution/ExecutionResultJsonConverter.cs#L48

**Comment by pouladpld** [comment]
maybe something like this would help:

```c#
errors.Apply(error =>
{
if (error.GetType() != typeof(ExecutionError))
{
    string json = JsonConvert.SerializeObject(error);
    writer.WriteRaw(json);
    return;
}
// ...
```

assuming that we use json attribs on error classes now.

```c#
// [json.OptIn, camelcased]
class MyCustomError : ExecutionError {

  // [json prop. default value - ignore]
  string Type;
}
```

**Comment by jinhong-** [comment]
Also, I want to point out that right now the resolver logic catches all exceptions and converts it to an item in the error list. I don't think this is the right move forward considering that all errors are now swallowed, which prevents the caller from further handling exceptions and processing them. One possible use case is this. In HTTP protocol, 4XX status codes represents client error. During resolution, in the event that something blows up. the entire exception gets swallowed and added into the Errors list. And if we're using the middleware, it would automatically return 4XX code. Which in most cases is incorrect since there are many reasons why. IE, database down, programming bug etc. and all these should never be 4XX but 5XX errors
Just to summarize, i think not only should custom execution errors be provided, I think we should not be swallowing all Exceptions, but letting the higher layer handle it

**Comment by joemcbride** [comment]
I failed to link this issue, though in #578 it does now catch `ExecutionError`.  The generic error handler is still there though.

**Comment by joemcbride** [comment]
A note on this - the GraphQL spec now defines an `extensions` section for errors.  We have added `data` and `code` to that.  So at present you can add extra info to `data` which will get serialized to the `extensions` on the error.  See #748 

http://facebook.github.io/graphql/June2018/#sec-Errors

```json
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
}
```

**Comment by joemcbride** [comment]
Also added a `ThrowOnUnhandledException` option to `ExecutionOptions`.  See #776

**Comment by dinoantonello** [comment]
We just upgraded to the latest version of graphql dot net have have noticed code is now moved to be wrapped in an extensions object. This breaks a lot of code that we dont have access too as they are in our clients system.

How do we manage this in terms of backward compatibility? 

There must be lots of other implementations who have clients who have existing code that is looking for the error code in the error object and not in extensions object

**Comment by joemcbride** [comment]
@dinoantonello this change was made to conform to the latest GraphQL spec.  Previously this aspect was not well defined.  You could perhaps do your own serialization of the ExecutionResult and include it in both places until all your clients have updated.
