### ISSUE TITLE
Define multiple queries on schema

### ISSUE THREAD

**Issue by pouladpld** [graphql-dotnet/graphql-dotnet#565]
Is it possible to have multiple queries on a schema?
I can't find any examples of that in using .NET package.

**Comment by joemcbride** [comment]
No, in GraphQL there is only a single root Query.

You can however "namespace" your queries on the root Query by providing a "stub" field + resolver, as shown here: https://github.com/graphql-dotnet/graphql-dotnet/issues/515#issuecomment-354916397

**Comment by pouladpld** [comment]
Oh. My bad. Thank you. Still learning the language...

**Comment by tinganho** [comment]
@joemcbride I've tried with the namespace solution. Though, doesn't look so elegant, since it requires consumer of the API to namespace the queries as well?

Can't you just add a feature to compose multiples Query classes?
```cs
namespace Books.Types
{
    public class StarwarsQuery : ObjectGraphType
    {
        public Query()
        {
            Extends(CharacterQuery);
            Extends(DroidQuery);
        }
    }
}
```
It stills conforms to GraphQL having only one root query.

**Comment by vytautas-pranskunas-** [comment]
Does ayone knows downsides of @joeaudette solution? Because it loks clear and does notcreate query wrapper like with: Field<HeartQuery>("heart", resolve: ctx => new {});

**Comment by mrfoster** [comment]
I think @joeaudette's solution is a great workaround but ideally there would be something similar built in that allows code to be organized in a modular / feature driven way. A replacement to the current [Query Organization](https://graphql-dotnet.github.io/docs/getting-started/query-organization/) guidance that allows a complete separation.

**Comment by julienFlexsoft** [comment]
```
public class CultureQueryField : ObjectGraphType
  {
        public CultureQueryField()
        {
        }

        public FieldType GenerateMultiple()
        {
            var field = FieldAsync<ListGraphType<Culture>>(
                "cultures",
                resolve: async context =>
                {
                     // Code to retrieve the data
                });
            return field;
        }
}
```
and then I do this
```
public class CustomQuery: ObjectGraphType
  {
        public CustomQuery(CultureQueryField cultureQueryField)
        {
              AddField(cultureField.GenerateMultiple()).AuthorizeWith(AuthPolicies.AuthorizationPolicy);
        }
}
```
And then this for the schema
```
public class CustomSchema : Schema
    {
        public CustomSchema(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            Query = serviceProvider.GetRequiredService<CustomQuery>();
            Mutation = serviceProvider.GetRequiredService<CustomMutation>();
        }
}
```

It works great and that way I can organize my files. I don't know if this is the best technique for performance.

**Comment by sourcecode71** [comment]
I have used Hotchocolate's ExtendObjectType for both query and mutation.
```
 [ExtendObjectType(typeof(CatalogueQueryResolver))]
    public class SchoolQueryResolver
    {
        readonly ISchool _schoolService;

        public SchoolQueryResolver(ISchool schoolService)
        {
            _schoolService = schoolService;
        }

        [GraphQLDescription("Gets the list of School.")]
        [UseSorting]
        [UseFiltering]
        public IQueryable<School> GetAllActiveSchools()
        {
            IQueryable<School> schools = _schoolService.GetSchools();
            return schools;
        }
    }
```
Here main Query Type is CatalogueQueryResolver. 
```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services
            .AddGraphQLServer()
            .AddQueryType<CatalogueQueryResolver>()
           .AddTypeExtension<SchoolQueryResolver>()
    }
}
```
