### ISSUE TITLE
Need more realistic tests/documentation for subscriptions

### ISSUE THREAD

**Issue by lwansbrough** [graphql-dotnet/graphql-dotnet#566]
The tests for GraphQL subscriptions include only a trivial example where the entire API is a synchronous reactive model. This seems like a highly unlikely scenario in the real world. Most code will talk asynchronously to some backend to fetch messages/subscribe to a queue. In fact, it's actually rather complicated to introduce any asynchronous code into this workflow. It's practically impossible to use the async/await pattern in an `EventStreamResolver`.

**Comment by pekkah** [comment]
You probably have already looked here https://github.com/graphql-dotnet/server/tree/master/samples/Samples.Server

**Comment by pekkah** [comment]
This is currently blocking easy async/await with Rx https://github.com/Reactive-Extensions/Rx.NET/pull/435

**Comment by pekkah** [comment]
@lwansbrough I made a PR with async subscriber support. Can you check it out if it helps with your problem.

**Comment by lwansbrough** [comment]
@pekkah Yes that API is perfect for my needs. This looks great, thank you!
