### ISSUE TITLE
Serialized ExecutionResult from subscription differs from query

### ISSUE THREAD

**Issue by lwansbrough** [graphql-dotnet/graphql-dotnet#567]
I return the same interface for both queries and subscription updates, but the serialized data is different between the two. I'm not sure if this is intentional or not, but I don't think it's consistent with other GraphQL subscriptions implementations.

query:
```json
{
  "data": {
    "user": {
      "id": 123
    }
}
```

subscription:
```json
{
  "data": {
    "id": 123
  }
}
```

It seems the root field is missing (ie. `"user"`) and only its sub-fields are returned.

**Comment by joemcbride** [comment]
What version are you using?  This was fixed once already...

**Comment by lwansbrough** [comment]
Whoops, I should have upgraded before filing this, I'm on `2.0.0-alpha-817`. I'll upgrade then retry. Thanks!

**Comment by lwansbrough** [comment]
Fixed, thank you.
