### ISSUE TITLE
ExpandoObject as Root

### ISSUE THREAD

**Issue by kvarv** [graphql-dotnet/graphql-dotnet#569]
Hi!

I'm looking for a solution where the root object can be a type of `ExpandoObject` instead of an anonymous type in the example below:
```
var schema = Schema.For(@"
  type Query {
    hello: String
  }
");

var root = new { Hello = "Hello World!" };
//var root = expandObject;

var result = schema.Execute(_ =>
{
  _.Query = "{ hello }";
  _.Root = root;
});

Console.WriteLine(result);
```

As far as I can tell this is handled by the `NameFieldResolver` which uses the reflection api.

**Comment by joemcbride** [comment]
Yes, so to support `ExpandoObject` you would have to write your own `IFieldResolver` that knows how to work with `ExpandoObject`.  Using a custom `IFieldResolver` is not currently supported with the handler+Schema syntax.

**Comment by SimonCropp** [comment]
closing since it seems to be answered
