### ISSUE TITLE
How to generate query fields, mutation fields and input/output types for graphql schema using JSON schema? 

### ISSUE THREAD

**Issue by vinayakbhadage** [graphql-dotnet/graphql-dotnet#57]
Hi ,

While evaluation graphql, also gone through the [reindex.io](https://www.reindex.io/) ,which has custom [schema generation capability](https://www.reindex.io/docs/tutorial/defining-the-schema/) .
In that case it takes the json schema and based on it generate CRUD operation in grapghql using query and mutation..

To Give an example: 

Following schema is uploaded to there endpoint:

````
[
  {
    "name": "User",
    "kind": "OBJECT",
    "interfaces": [
      "Node"
    ],
    "fields": [
      {
        "name": "id",
        "type": "ID",
        "nonNull": true,
        "unique": true
      },
     {
        "name": "username",
        "type": "String",
        "nonNull": true,
       }
    ]
  }
]
```

Based on this following query, mutation fields and input/output types are generated,
e.g.
Schema
|
|____ query:
| .......        |_getById(id:ID):User
| .......        |_ allUsers(filterInfo:UserFilterInfo):UserCollection
|
|___ mutation
.......  |__ createUser(userInput:UserInputType):UserType
 ........|__updateUser(userInput:UserInputType):UserType

Please let me know, How can we achieve it using this library?

Thanks & Regards,
-Vinayak

**Comment by joemcbride** [comment]
This library does not have a feature like this.  https://github.com/graphql-dotnet/graphql-dotnet/issues/14 is similar, though is convention based on .NET types.  There is currently no plans to add support for generating a schema based on a JSON schema.

If I were to add something like this I would probably base it off of the short-hand schema definition that Facebook has provided, as shown [here](https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/schemaPrinter.js#L511).

**Comment by vinayakbhadage** [comment]
@joemcbride Thank you for clarification also for removing Resolve Type dependency from InterfaceGraphType in 0.5.1.
