### ISSUE TITLE
Querying only non-leaf child nodes

### ISSUE THREAD

**Issue by ravgupms** [graphql-dotnet/graphql-dotnet#572]
I have a schema define as below:

```
type Query {
  users: [User]
}

type User {
  id: ID
  name: String
  address: String
  phone: String
  setting: UserSettings
}

type UserSettings
{
    setting1: String
    setting2: String
}
```

On server side, I have two resolvers, one which returns a user schema containing its basic properties like name, address and phone while other resolve its settings.

Now, if I want to query only settings of a particular user i.e.

```
{
  users(id: "xyz")
  {
    settings
    {
      setting1,
      setting2
    }
}
```

Both the resolvers gets executed in this case, even I'm not requesting any field which is powered by first resolver. Is there any way to avoid this extra network call?

**Comment by joemcbride** [comment]
Not with that setup, no.  GraphQL is designed to work that way.  If you want to retrieve settings without first going through a `User`, you would have to add that as a top-level field on `Query`.

```
type Query {
  users: [User]
  userSettings(id: String!): UserSettings
}
```

**Comment by ravgupms** [comment]
public class UserType : ObjectGraphType<User>
{
    public UserType()
    {
        Field("id", x => x.Id).Description("Id of the user.");
        Field(x => x.Name);
        Field(x => x.Address);
        Field(x => x.Phone);
        Field<UserSettingsType>("settings", resolve: context => { ... });
    }
}

Is there any way to write a single resolver for Name, Address and Phone fields? That way from top I can pass a dummy User object with only Id field populated and then make a network call to get other properties in case if anyone of them is requested?

**Comment by joemcbride** [comment]
That would be possible, yes, though I would not suggest doing that as it would be way less performant than just loading those simple values (according to your example) up front.

You can see what sub fields are requested by checking `SubFields` on `ResolveFieldContext`.

**Comment by ravgupms** [comment]
Manually checking whether any leaf field of a type is requested or not at every level is a big overhead. 

What I'm looking for is some sort of lazy resolving. I think right now the library executes a parent resolver before iterating its children, right? If somehow we can delay its execution that would take care of my scenario. Correct me if I'm wrong.

**Comment by joemcbride** [comment]
You can use the `DataLoader` pattern for lazy resolving.  No docs yet, though you can look at the tests.

https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.DataLoader.Tests

Tracking docs for `DataLoader` here: #560

**Comment by sungam3r** [comment]
@ravgupms Is this issue still actual for you?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
