### ISSUE TITLE
interpretation of null values in mutations

### ISSUE THREAD

**Issue by landbolts** [graphql-dotnet/graphql-dotnet#575]
The graphql spec mentions that a lack of a value could be represented either as an explicit null value or as an omitted value. 

http://facebook.github.io/graphql/October2016/#sec-Null-Value

Furthermore it mentions that these two could be interpreted differently, e.g.  "deleting a field vs not altering a field"

I wanted to see if anyone has any recommendations on how one could differentiate between explicitly supplied null values vs completely omitted arguments when converting a json string into a c# object during a mutation. 

The end result of converting a json string into a c# object in graphql-dotnet currently seems to yield the same result for both of these operations, e.g. property is null. I believe the code for this conversion is in src\GraphQL\ObjectExtensions.cs.

One option could be to update this logic  to differentiate between explicitly and implicitly specified values. For example when explicitly specifying a null value the logic could use the default type of a field, and for objects activate a new instance (assuming a default constructor exists).
If on the other hand the value is not supplied, the value could be left out during conversion, which would be the current behavior. 

Any opinions would be helpful. 

thanks
Aleks

**Comment by jquense** [comment]
I have not personally found a good option for handling "patch" operations in GQL with C# but generally (in JS world) i've reserved `null` to mean an explict change in value for a field, and `omitted` as an indication that the field is not altered. To give meaning to that distinction tho you need someway of handling the mapping in either case. I'd imagine that for patch/updates mapping the json object to an existing instance of an object in C# land would work, e.g. `Automapper.Map` where you provide the initial destination object and only override the values that are included in the source.

**Comment by rose-a** [comment]
I noticed a strange interpretation of explicit `null` values when the concerning property is defined as a `ListGraphType<someothertype>`: It results in a `System.Object[]` containing one element which is `null`!

Is this a behaviour desired?

**Comment by mrtoby** [comment]
Why not create a generic class, e.g. Optional<T> (like in java) that can represent a present value (which could be null) and a absent value? Then you could add handling for this special type when parsing input types.

I imagine something like

public class User {
    public string Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class UserPatch {
    public Optional<string> FirstName { get; set; }
    public Optional<string> LastName { get; set; }
}

Then you use the User class for queries and mutations that create users, but the UserPatch class for mutations that can be used to update the first name, the last name or both.

A workaround is to avoid using input types and rather just use plain arguments. You can see if an argument is provided or not and it can have the value null (I guess...).

**Comment by mrtoby** [comment]
Another idea: Implement the property setters so that they track if a value has been set or not.
This would relay on that GraphQL.NET not set null explicitly even if the field is absent in the mutation.

Something like:
`
public class UserPatch {
    private string _firstName;
    private string _lastName;
    public bool HasFirstName { get; private set; }
    public bool HasLastName { get; private set; }
    public Optional FirstName { get _firstName; set => { HasFirstName = true, _firstName = value; } }
    public Optional LastName { get _lastName; set => { HasLastName = true; _lastName = value; } }
}
`

**Comment by Shane32** [comment]
> I wanted to see if anyone has any recommendations on how one could differentiate between explicitly supplied null values vs completely omitted arguments when converting a json string into a c# object during a mutation.

This is supported in v4 for query arguments via the `IResolveFieldContext.Arguments` dictionary.  You can determine if a value was the supplied via a literal or variable, or if it is the field default, or even if it is the default value of a variable (which is supplied by the query).  Keep in mind that you will need to transform argument names to the proper case yourself, as `INameConverter` is not applied when accessing the dictionary directly.

It may be easier to use the updated `HasArgument` method, which returns `true` if the argument value was specified within the query (either via literal, variable, or a query-defined variable default value), versus `false` if it was left as the field's default value (defined in the schema).

You can also, in v4, define custom `IInputObjectGraphType` implementations which by overriding `ParseDictionary` can be used to determine if any fields of an input object were left undefined.  However, you cannot tell which values are field defaults versus specified values.  This coercion was built to the graphql specification.  Please re-open this issue if you have a need for that in this scenario.

**Comment by sungam3r** [comment]
> However, you cannot tell which values are field defaults versus specified values. This coercion was built to the graphql specification

@Shane32 Could you please point to the appropriate spec place?

**Comment by Shane32** [comment]
http://spec.graphql.org/October2021/#sec-Input-Objects.Input-Coercion

See rule #1 :

> If no value is provided for a defined input object field and that field definition provides a default value, the default value should be used. If no default value is provided and the input object field’s type is non-null, an error should be raised. Otherwise, if the field is not required, then no entry is added to the coerced unordered map.

**Comment by Shane32** [comment]
Keep in mind that our software cannot differentiate between a default value of `null` and a no default value -- so, it is consistently assumed that no default value was specified if `field.DefaultValue == null`.

**Comment by sungam3r** [comment]
Regarding
> However, you cannot tell which values are field defaults versus specified values. This coercion was built to the graphql specification

Why not? `ArgumentSource.FieldDefault` vs `ArgumentSource.Literal/Variable`. Do I misunderstand you?

**Comment by Shane32** [comment]
I was specifically talking about fields of an _input object_.  The input object itself you can use `ArgumentSource` to determine if it came from a field default/etc, but the fields within the input object are processed as specified in the above link, which specifically relates to _input object coercion_.  After coercion, the "map" (dictionary) is passed to `ParseDictionary`, and the dictionary values do not contain `ArgumentSource` information.
