### ISSUE TITLE
Does InputObjectGraphType support the polymorphism ?

### ISSUE THREAD

**Issue by vinayakbhadage** [graphql-dotnet/graphql-dotnet#58]
Hi,

Like ObjectGraphType supports the polymorphism as shown below, 

```
public class NamedType : InterfaceGraphType
{
    public NamedType()
    {
        Name = "Named";

        Field<StringGraphType>("name");
    }
}

public class DogType : ObjectGraphType
{
    public DogType()
    {
        Name = "Dog";

        Field<StringGraphType>("name");
        Field<BooleanGraphType>("barks");

        Interface<NamedType>();

        IsTypeOf = value => value is Dog;
    }
}
```

can we use the same thing for InputObjectGraphType ?

Thanks & Regards,
-Vinayak

**Comment by joemcbride** [comment]
Input Objects do not have a defined polymorphism as provided by the GraphQL spec.

http://facebook.github.io/graphql/#sec-Input-Objects
http://facebook.github.io/graphql/#sec-Input-Object-Values

For shared fields you should be able to do traditional inheritance though.  Does that help?

```
public class NamedInput : InputObjectGraphType
{
  public NamedInput()
  {
    Field<StringGraphType>("name");
  }
}

public class DogInput : NamedInput
{
  public DogInput()
  {
    Field<BooleanGraphType>("barks");
  }
}
```

**Comment by vinayakbhadage** [comment]
Thanks, But it is useful feature as GraphQL response is supporting the polymorphism and not in a request. Other API like  WCF, REST(Swagger) also support it.

Might be in future they will support it.

-vinayak

**Comment by joemcbride** [comment]
Are you able to provide an example of how you would like to use polymorphic inputs?

**Comment by vinayakbhadage** [comment]
Sure, Let us assume, want to provide user authentication using graphql mutation. User can be authenticated in multiple ways 
1. User name and password authentication.
2. Username, security question and answer.
3. Username and Token based authentication.

```
mutation authenticateUser(AuthenticationInput) {
    userId,
    userDetails
   {
      firstName
      ... etc
    }
  }
````

Here AuthenticationInput can have following subtypes:

```
public class AuthenticationInput : InputObjectGraphType
{
    public AuthenticationInput ()
    {
      Field<StringGraphType>("userName");
    }
}

public class UserNamePasswordAuthenticationInput : AuthenticationInput 
{
    public UserNamePasswordAuthenticationInput ()
    {
      Field<StringGraphType>("password");
    }
}

public class SecurityQuestionBasedAuthenticationInput : AuthenticationInput 
{
    public SecurityQuestionBasedAuthenticationInput ()
    {
      Field<StringGraphType>("secretQuestion");
      Field<StringGraphType>("secretAnswer");
    }
}

public class TokenBasedAuthenticationInput : AuthenticationInput 
{
    public TokenBasedAuthenticationInput ()
    {
      Field<StringGraphType>("token");
    }
}

```

This is available in WCF using [KnownType ](https://msdn.microsoft.com/en-us/library/ms730167(v=vs.110).aspx)attribute on DataContract .

Thanks & Regards,
-Vinayak

**Comment by draganjovanovic1** [comment]
Hi, here is an interesting idea on how this could be solved by implementing union input type https://github.com/Cardinal90/graphql-union-input-type

**Comment by sungam3r** [comment]
Polymorphism for inputs leads to more complex specification and increased implementation requirements. It is unlikely that in the foreseeable future there will be such a feature.

**Comment by sungam3r** [comment]
Relates to graphql/graphql-spec#114, graphql/graphql-spec#415, graphql/graphql-spec#488, graphql/graphql-spec#617

**Comment by sungam3r** [comment]
See https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md . We could add support for input unions after this rfc will be merged into the spec. For now it will be better to close this issue.
