### ISSUE TITLE
Using Apollo Client Developer Tools Chrome extension with GraphQL server

### ISSUE THREAD

**Issue by ravgupms** [graphql-dotnet/graphql-dotnet#581]
How can I make my GraphQL server written in C# to work with Apollo Client Developer Tools Chrome extension? 

Right now, Chrome developer tools don't even show Apollo tab for my server.

**Comment by pekkah** [comment]
These tools https://github.com/apollographql/apollo-client-devtools are for client development. So you need a client side app which uses Apollo. Then you should be able to use them.
