### ISSUE TITLE
Avoiding strong typing and deserialization into C# schemas as part of resolvers?

### ISSUE THREAD

**Issue by ravgupms** [graphql-dotnet/graphql-dotnet#582]
I'm building a GraphQL Aggregate service which won't be owning any data by itself, instead will call a number of underlying services to fetch the data.

I'm using Handler/Endpoints approach but wanted to check is there any way to skip the strong typing and deserialization into C# schemas as part of resolvers? Something like a resolver returns data in JSON format(JObject) and GraphQL package will automatically picks necessary data out of it (assuming both uses same schema) without deserializing it to object first and then again serializing it to JSON, hence improving overall perf of our service.

**Comment by joemcbride** [comment]
No this is not currently supported.  It would most likely require significant changes to the current design of the library.

**Comment by ravgupms** [comment]
But are there any plans to support something like this in the near future?

**Comment by joemcbride** [comment]
There is no current plan to try to support this scenario in the near future.  You could perhaps get close to something working with implementing your own `IFieldResolver` (work with `JObjects` vs. class properties + methods).  Though the internal system would still need the GraphQL Schema Model to know how to execute the GraphQL requests.

**Comment by elauffenburger** [comment]
I actually came here to ask this exact question!  I couldn't find a good solution, so I'm wrapping up something I've been working on.  It's...a bit of a hack as it requires dynamic type generation, but it fetches the remote schema and generates subtypes that just proxy through a JObject.

@joemcbride: do you have any interest in me forking to show that work to see if want to take it over?

Oh, and great job on this library -- it's been really invaluable to me and the rest of my team!

**Comment by joemcbride** [comment]
@elauffenburger For sure, I would be interested in seeing what you came up with.

**Comment by ravgupms** [comment]
@elauffenburger : Even I want to have a look too.

**Comment by elauffenburger** [comment]
Awesome! I'll get something together in the next day or two since I need to wrap this up, get it pulled out of my NuGet package, scrub it a bit (😄), and get you a PR!

If I seem to fall off the face of the planet, it's probably because I'm dealing with some fire or something, so feel free to just message me 😄

**Comment by elauffenburger** [comment]
@joemcbride: So I started porting my work over, and the only real issue I'm seeing is that I use some very Full .NET FX-y APIs like `AppDomain.CurrentDomain` or `AppDomain.DefineDynamicAssembly`, which is going to be a problem for netstandard2.0 and netstandard1.3 support.

Any recommendations here? I'm thinking we could have framework-dependent implementations and inherit from the base type (letting each implementation figure out how it wants to support those APIs), but I think it's going to just straight up be an issue for anyone targeting netstandard2.0 or netstandard1.3.

**Comment by joemcbride** [comment]
Codegen in the “new world” is with Roslyn.  My colleague Jeremy Miller is doing some interesting stuff with that in his new project BlueMilk.  I would lean towards something like that for .NET Core.

https://github.com/JasperFx/bluemilk

Unless you want to dive into that, it’s fine just seeing what you’re doing with the dynamic assembly stuff.

**Comment by elauffenburger** [comment]
Ah yeah, that makes total sense.  I didn't really even look into what was supported via Roslyn, but I imagine it's a lot :)

I'll just get this up and then we'll figure out how to correct it.

**Comment by ravgupms** [comment]
@elauffenburger : Did you get a change get a PR out for you code changes?

**Comment by elauffenburger** [comment]
@ravgupms Sorry! I've been a bit underwater at work, so I haven't had a chance to get it all up there yet. I'd like to throw at least a couple test cases out there to demonstrate usage. 

I'll try to get at it in the next couple days (assuming nothing else is on fire)

**Comment by elauffenburger** [comment]
@joemcbride @ravgupms: PR is up! Take a look to see what I'm thinking.  I mentioned it in the PR, but this **is not prod ready** but I'd reckon it's ~70% complete (I need to support union types and, like we talked about earlier, doesn't use Roslyn for codegen).

**Comment by SimonCropp** [comment]
give this comment https://github.com/graphql-dotnet/graphql-dotnet/pull/592#issuecomment-537174161

> Schema stiching has been superseded by Apollo Federation. See #1169

it would seem this should be closed?
