### ISSUE TITLE
InputObjectGraphType referencing an ObjectGraphType should error

### ISSUE THREAD

**Issue by tinganho** [graphql-dotnet/graphql-dotnet#587]
I lost a day or so tracking down a bug in introspection. I've got this generic error:

```shell
Introspection must provide input type for arguments.
```
Turns out, `InputObjectGraphType` cannot have fields containing a `ObjectGraphType`. Couldn't the `Field<TGraphType>` be constrained to only accept `InputObjectGraphType` instead of `ObjectGraphType`?

**Comment by joemcbride** [comment]
Sorry to hear about that!  I think that `Field<TGraphType` will need to stay at `IGraphType`, though could probably change `AddField` on `ComplexGraphType` to be virtual and ensure the given type does not inherit from `ObjectGraphType`.  Both `InputObjectGraphType` and `ObjectGraphType` use `ComplexGraphType`.
