### ISSUE TITLE
How To Create A DateGraphType Field

### ISSUE THREAD

**Issue by BenjaminHolland** [graphql-dotnet/graphql-dotnet#588]
There doesn't seem to be an implicit or explicit conversion between DateGraphType and either DateTime or DateTimeOffset, and there doesn't seem to be any example of creating a field with this type. How is this done?

**Comment by BenjaminHolland** [comment]
Nevermind. It doesn't work if I specify the type explicitly, but the type-parameterless Field function seems to work correctly.

**Comment by RehanSaeed** [comment]
I'm trying to use a `DateTimeOffset` using the following syntax but I'm getting errors, a `DateTime` works. What is the syntax you settled on?

```
Field(o => o.Created);
```
