### ISSUE TITLE
Assembly Versioning Disagreements

### ISSUE THREAD

**Issue by jweite** [graphql-dotnet/graphql-dotnet#589]
Attempts to run GraphQL.GraphiQLCore result in an 

`FileLoadException: Could not load file or assembly 'GraphQL, Version=2.0.0.820, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
GraphQL.GraphiQLCore.Startup.ConfigureServices(IServiceCollection services)`

error message on my browser.  The version built by the GraphQL project in this solution is 0.16.0.1140.  (A 2.0.0.820 does get pulled in by NuGet for GraphQL.GraphiQLCore but nowhere else). 

Changing the version info in the GraphQL projects's CommonAssemblyInfo.cs and project files does resolve this and the GraphQL.GraphiQLCore runs.  Not sure, though, if the code in in the GraphQL project is 2.0.0.820 code.

**Comment by joemcbride** [comment]
That sample has been deprecated (and I will be removing it from the source very soon here ...) in favor of https://github.com/graphql-dotnet/example-aspnetcore - can you give that one a try?

**Comment by jweite** [comment]
Thanks Joe.  example-aspnetcore works fine.  I find it less useful to me as a study project, though, since the biz logic (StarWars) comes in via Nuget, and is therefore rather opaque.  But I'll learn what I need to from the predecessor project.

**Comment by SimonCropp** [comment]
@jweite so looks like this one can be closed?
