### ISSUE TITLE
ObjectExtensions.ToObject<T>() and Guid / Nullable<T>

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#59]
Hi,

`ObjectExtensions.ToObject<T>()` seems to have some limitations when it comes to Guids and Nullable<>. I believe there is similar cases with more complex structures (e.g. an array of Nullable<T> or array of non-structs), where the method should likely be recursive. I made a local modified version of the method that seems to make the tests parse, where the isNullable bool is ignored and the use of Convert.ChangeType has been changed to something like this:

```
...
var isNullable = fieldType.IsGenericType && fieldType.GetGenericTypeDefinition() == typeof(Nullable<>);
if (isNullable)
{
  fieldType = fieldType.GenericTypeArguments.First();
}

propertyType.SetValue(obj, GetValue(value, fieldType), null);
...

static object GetValue(object value, Type fieldType)
{
  if (value == null) return null;

  var text = value as string;
  return text != null 
    ? TypeDescriptor.GetConverter(fieldType).ConvertFromInvariantString(text) 
    : Convert.ChangeType(value, fieldType);
}
```

Extending InputConversionTests with test cases: 

        public class MyInput
        {
          ..
            public int? D { get; set; }
            public Guid E { get; set; }
          }

        [Test]
        public void can_convert_json_to_input_object_with_nullable_int()
        {
          var json = @"{'a': 1, 'b': '2', 'd': '5'}";
          var inputs = json.ToInputs();
          inputs.ShouldNotBeNull();
          var myInput = inputs.ToObject<MyInput>();
          myInput.ShouldNotBeNull();
          myInput.D.ShouldEqual(5);
        }

        [Test]
        public void can_convert_json_to_input_object_with_guid()
        {
          var json = @"{'a': 1, 'b': '2', 'e': '920a1b6d-f75a-4594-8567-e2c457b29cc0'}";
          var inputs = json.ToInputs();
          inputs.ShouldNotBeNull();
          var myInput = inputs.ToObject<MyInput>();
          myInput.ShouldNotBeNull();
          myInput.E.ShouldEqual(new Guid("920a1b6d-f75a-4594-8567-e2c457b29cc0"));
        }

```

**Comment by tlil87** [comment]
Yes, I've seen the same, and have a more general, recursive variant in place locally that I use with the `conventions` repo that I'll release soon.

**Comment by MartinLorensen** [comment]
Sounds great.

I am not sure I understand the separation between the convention and the "main" repo. But as long as the different elements found in conventions can be used independently that is fine with me. It seems like "data and contract in one instance" vs. "data instances (non-GraphType) and contract instances (GraphType-derived)" is central to the convention - but that does not seem to be related to this `ToObject<T>()` nor to e.g. `EnumType<T>`.  But if "conventions" is just anything to do with conventions (less code by following some "standard" conventions, e.g. fewer Field/Connection builders), no matter how the underlying model is, that sounds very reasonable - and in that case the `ToObject<T>()` is most definitly a convetion-thing.

**Comment by joemcbride** [comment]
I've got all of these issues fixed, will be pushing that up soon.  🎉

**Comment by tlil87** [comment]
Good thing - I've completely forgotten about this, sorry. :tada:

**Comment by JarnoNijboer** [comment]
@tlil87 Can you share details on the release of the conventions repo?
We are thinking about refactoring our current v1 GraphQL implementation, and some of the things in the conventions repo, e.g. IdType, are making our codebase a lot easier to manage.

Keep up to good work guys!

**Comment by tlil87** [comment]
@JarnoNijboer I aim to get the first release out early next week :) will keep you posted
