### ISSUE TITLE
Ordering of fields and arguments in introspection

### ISSUE THREAD

**Issue by mvestergaard** [graphql-dotnet/graphql-dotnet#594]
There is currently no ordering of fields and arguments in introspection, they just appear in the order they are defined. This makes it very difficult to find what you are looking for in a large schema.

Is this intended, or are you open to changing this? I don't mind sending in a PR for this.

**Comment by kamsar** [comment]
+1 to being able to control ordering. I'm doing schema composition so it's difficult to control the order in which all fields are added.

**Comment by mvestergaard** [comment]
@joemcbride Any thoughts on this? Like I said, I'll happily submit a PR for this, but I'm unsure whether ordering was left out intentionally.

**Comment by PascalSenn** [comment]
Makes sense. I wouldn't order the inputs though. It's handy to do for example multi column orderings in the order they are defined in the request.

**Comment by jquense** [comment]
I don't feel like i understand that value vs complexity this adds here. Fields should be ordered in by creation order, which makes sense as the correct default i think. Adding additional sorting is likely to cases performance concerns for a benefit that is purely useful during introspection in development?

**Comment by jquense** [comment]
the spec does have a bit of a section on this: http://facebook.github.io/graphql/October2016/#sec-Objects

**Comment by mvestergaard** [comment]
I don't know if you've tried looking at a root Query with several hundred fields. Unless they are ordered in a meaningful way, it's pretty difficult to find what you are looking for.  
And expecting developers to sort them manually at the time of definition is not really feasible.

If this is not something you wish to do by default. Could we at least add an ability to do it optionally?

**Comment by mvestergaard** [comment]
I read the points made in the spec as, when you query something, the fields should appear in the order in which they were queried, which makes sense. But this issue relates to something else. It relates to order in which fields are output in the introspection information.

**Comment by mvestergaard** [comment]
Just to clear that up even further. I'm only suggesting ordering the introspection data, not fields in results in general.

**Comment by mvestergaard** [comment]
I went ahead and added a PR for this. The change should really be very harmless.
