### ISSUE TITLE
VisualStudio is crashing | “System.InvalidCastException” in Microsoft.CodeAnalysis.Workspaces.dll

### ISSUE THREAD

**Issue by dojo90** [graphql-dotnet/graphql-dotnet#596]
I have a simple WPF app where I have included the QtSharp library.

The problem is that my VisualStudio 2017 v15.5.7 is crashing whenever it tries to load the QtSharp DLLs for it's intelliSense. Somebody know how to prevent crashing or ignoring f.e. a System.InvalidCastException? I have already stoppped ReSharper to exlude this. The following Screenshot and StackTrace is shown when I inject a debugger (**See link**).

It's a very strange behavior because on some methods or overloads it's working like a charm without any problems and after some minutes or (for example) if using the AddWidget() method it crashes.

https://stackoverflow.com/questions/49260487/system-invalidcastexception-in-microsoft-codeanalysis-workspaces-dll

Best Regards
Dominic

**Comment by joemcbride** [comment]
Hey, I think you added this to the wrong project.  Perhaps this is the QtSharp project you're looking for?

https://github.com/ddobrev/QtSharp

**Comment by dojo90** [comment]
Oh that's embarrassing! Yes that's right, of course!
