### ISSUE TITLE
GraphType.Connection<TGraphType> with new() constraint

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#60]
Hi,

GraphType.Connection<TGraphType>() has a new() constraint on TGraphType which doesn't seem to be needed, and is causing me some headache! I would be happy to make an attempt of creating a pull request - but with the amount of refactoring and extension going on, I though it might better be done in some other context.

```
        public ConnectionBuilder<TGraphType, object> Connection<TGraphType>()
            where TGraphType : ObjectGraphType, new()

```
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/GraphType.cs#L34

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Builders/ConnectionBuilder.cs#L10

**Comment by tlil87** [comment]
:+1: Will take a look at that @MartinLorensen

**Comment by tlil87** [comment]
This should do: https://github.com/graphql-dotnet/graphql-dotnet/pull/61 :)

**Comment by joemcbride** [comment]
[0.6.0](https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.6.0) published with those changes.

**Comment by MartinLorensen** [comment]
I am VERY impressed and pleased! Thanks a lot!
