### ISSUE TITLE
Spliting GraphQL schema into multiple files for better manageability

### ISSUE THREAD

**Issue by ravgupms** [graphql-dotnet/graphql-dotnet#600]
I'm trying to build my graphql server using Handler/Endpoints approach and one problem I'm facing is that my graphql schema is pretty big and maintaining such a big file is becoming an overhead.

Is there any way I can split it into multiple file and use it in my graphql server?

**Comment by KreativJos** [comment]
It is quite easy to split up your root query into multiple sub-queries, like this:
```
query {
  subRootQuery {
    hero: Droid!
  }
}
```

**Comment by miguelcaravantes** [comment]
Schema.For supports a string array for definitions string[] typeDefinitions, split your definition in multiple files and read all files on your path and create this string array.

Something like this:


`string[] typeDefinitions =Directory.EnumerateFiles(Path.Combine(_env.ContentRootPath, _options.SchemaDirectory))
                .Select(path => File.ReadAllText(path))
                .ToArray()

var schema = Schema.For(schemaDefinition);

`
