### ISSUE TITLE
Repeated sub-fields quit working

### ISSUE THREAD

**Issue by joshkel** [graphql-dotnet/graphql-dotnet#602]
To simplify query generation, we had some queries of the form

```
query {
  person(id: 1) {
    business { id name }
    business { id address { id street city state } }
  }
}
```

with repeated sub-fields (`business`) in this case.

This worked in GraphQL .NET 0.17.3, but, when I upgraded to 2.0.0-alpha-868, only the most recent sub-field was honored.

We were able to work around it by restructuring our queries, but it seems like a bug in GraphQL .NET for it to not support this use case.

Thanks!

**Comment by joemcbride** [comment]
Thanks for the report!  Indeed I do believe that is a bug.

**Comment by mrtes** [comment]
I have tracked down the issue to [this line of code](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionHelper.cs#L317).
According to spec, at this point, duplicate equivalent fields  (with sub selections) should be merged into one.

I'm assuming that advanced field equivalence (i.e. are the arguments the same) is already checked during validation. This allows to merge the fields if the alias (if defined) and field names are equal.
I'm going to add a PR for this soon.

**Comment by joemcbride** [comment]
> I'm assuming that advanced field equivalence (i.e. are the arguments the same) is already checked during validation.

Not yet. That is the last validation rule not yet implemented.  #160

**Comment by joshkel** [comment]
Thanks!
