### ISSUE TITLE
BooleanGraphType not converting "1"

### ISSUE THREAD

**Issue by dBug404** [graphql-dotnet/graphql-dotnet#606]
In a mutation i use a type for the arguments which has a bool property. If the client sends the argument as string "1" it gets converted to false.

```
    class MyMutation
    {
        public bool Value { get; set; }
    }
          
          //in mutation
          resolve: context =>
                {
                    var mutation = context.GetArgument<MyMutation>("request");
                }
```

I am not sure, if this is really intended or a bug. If i look at the code, the BooleanGraphType supports "1" in the ParseValue method. But it seems the result from the Serialize method gets used, which is always false when no bool is provided.

```
//BooleanGraphType
public override object Serialize(object value)
    {
      if (value is bool)
        return (object) (bool) value;
      return (object) false;
    }
```

When I look at other ScalarTypes then usually ParseValue is called in the Serialize method, which would work in my case, when the BooleanGraphType would do the same.

```
public override object Serialize(object value)
    {
      return this.ParseValue(value);
    }
```

I always wondered what is the purpose of these two methods and which method should do what excactly.

I am currently in version 0.17.

**Comment by joemcbride** [comment]
I would agree that having both the parse (data coming in) and serialize (data going out) should know how to handle both.

I would think that the output should still always be a bool, but update it so if it is a number then it provides the correct boolean value?

**Comment by dBug404** [comment]
I don't have a problem that the output will always be bool. 

My problem is, that the input of "1" results in false and  both methods (serialize/parse) gets called, but the result of the serialize method is used.

**Comment by kenrim626** [comment]
I have a similar problem, but with actually "true" being converted to false.

The input type has a field "desc":
`Field<NonNullGraphType<BooleanGraphType>>("desc");`

In the GraphQL query the property is set to true:
`desc: true`

The `context.GetArgument<T>(string)` method returns the object with all properties set, but the "desc" property is false.

**Comment by KoditkarVedant** [comment]
Hello @joemcbride, If this issue is still up for grab, I would like to work on it. If I have got issue reported by @dBug404 correctly, He wants if the given input is a numerical string then it should convert be to boolean.

**Comment by joemcbride** [comment]
@KoditkarVedant Still up for grabs.  Yes, need to make a change in the `Serialize` for `BooleanGraphType` to call `ParseValue`.  Can add tests for `Serialize` to here.  https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Types/BooleanGraphTypeTests.cs

**Comment by KoditkarVedant** [comment]
Thanks, @joemcbride, I'll work on this and create the pull request.

**Comment by KoditkarVedant** [comment]
@joemcbride I'm thinking of only considering "1" and "0" as a valid boolean string. What do you think? I earlier thought of considering all strings which are non-zero as true but not sure whether we support like it.

**Comment by joemcbride** [comment]
Closing as this has now been fixed.
