### ISSUE TITLE
Problem passing parameters

### ISSUE THREAD

**Issue by mrpink76** [graphql-dotnet/graphql-dotnet#608]
I'm having problem using variables pass an array of parameters to the graphql backend...

### Query

```graphql
query q($query:String!, $parameters:[QueryEngineParameter!]) {
  sqlQuery(query:$query, parameters:$parameters) {
    columns
  }
}
```

### Variables

```json
{
  "query": "select * from table1 where :p1 = 2",
  "parameters": [{"name": "p1", "value": "1"}]
}
```

### Error message

```json
{
  "errors": [
    {
      "message": "Variable '$parameters[0]' is invalid. Unable to parse input as a 'QueryEngineParameter' type. Did you provide a List or Scalar value accidentally?"
    }
  ]
}
```

### Query

```graphql
query q($query:String!) {
  sqlQuery(query:$query, parameters:[{name:"p1", value:"2"}]) 
  {
    columns
  }
}
```

### Variables

```json
{
  "query": "select * from table1 where :p1 = 2"
}
```

Is there something I'm missing?

The backend code for the query looks like this:

```csharp
  Field<ListGraphType<SqlRowType>>(
      "sqlQuery",
      arguments: new QueryArguments(
          new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "query", Description = "" },
          new QueryArgument<ListGraphType<NonNullGraphType<QueryEngineParameterType>>> { Name = "parameters" }
      ),
      resolve: context => data.ExecuteSqlQueryAsync((AuthenticatedUserDto)context.UserContext, context.GetArgument<string>("query"), context.GetArgument<List<QueryEngineParameterDto>>("parameters"))
  );
```

**Comment by joemcbride** [comment]
How is QueryEngineParameterType defined?  Is it a InputGraphType?

**Comment by mrpink76** [comment]
It's defined as:

```csharp
    public class QueryEngineParameterType : InputObjectGraphType
    {
        public QueryEngineParameterType(IndsysDao indsysDao, IMapper mapper)
        {
            Name = "QueryEngineParameter";
            Field<NonNullGraphType<StringGraphType>>("Name");
            Field<NonNullGraphType<StringGraphType>>("Value");
        }
    }
```

**Comment by joemcbride** [comment]
That error is from here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/41c516a9f4be08d9b338b94c9da39c4c3f35ee7a/src/GraphQL/Execution/ExecutionHelper.cs#L166-L175

So it appears that those variable values are not ever getting to there.  I'm guessing it is failing on line 168.  How are you passing your variables to the execution engine?  Are you using the `.ToInputs` extension method?  That method does a conversion from JSON.NET types to basic .NET types which the core engine relies upon.

A couple snippets from this example:

https://graphql-dotnet.github.io/getting-started/#variables
https://github.com/graphql-dotnet/example-aspnetcore/blob/master/src/Example/GraphQLMiddleware.cs#L59

```csharp
public class GraphQLRequest
{
    public string OperationName { get; set; }
    public string Query { get; set; }
    public JObject Variables { get; set; }
}

private async Task ExecuteAsync(HttpContext context, ISchema schema)
{
    var request = Deserialize<GraphQLRequest>(context.Request.Body);

    var result = await _executer.ExecuteAsync(_ =>
    {
        _.Schema = schema;
        _.Query = request.Query;
        _.OperationName = request.OperationName;
        _.Inputs = request.Variables.ToInputs();
        _.UserContext = _settings.BuildUserContext?.Invoke(context);
    });

    await WriteResponseAsync(context, result);
}
```

**Comment by mrpink76** [comment]
You were absolutely correct! 

My fault since I was storing inputs in an unstandard way.

Sorry for the inconvenience!

**Comment by buster95** [comment]
> That error is from here:
> 
> https://github.com/graphql-dotnet/graphql-dotnet/blob/41c516a9f4be08d9b338b94c9da39c4c3f35ee7a/src/GraphQL/Execution/ExecutionHelper.cs#L166-L175
> 
> So it appears that those variable values are not ever getting to there. I'm guessing it is failing on line 168. How are you passing your variables to the execution engine? Are you using the `.ToInputs` extension method? That method does a conversion from JSON.NET types to basic .NET types which the core engine relies upon.
> 
> https://graphql-dotnet.github.io/getting-started/#variables
> 
> A couple snippets from this example:
> 
> https://github.com/graphql-dotnet/example-aspnetcore/blob/master/src/Example/GraphQLMiddleware.cs#L59
> 
> ```cs
> public class GraphQLRequest
> {
>     public string OperationName { get; set; }
>     public string Query { get; set; }
>     public JObject Variables { get; set; }
> }
> 
> private async Task ExecuteAsync(HttpContext context, ISchema schema)
> {
>     var request = Deserialize<GraphQLRequest>(context.Request.Body);
> 
>     var result = await _executer.ExecuteAsync(_ =>
>     {
>         _.Schema = schema;
>         _.Query = request.Query;
>         _.OperationName = request.OperationName;
>         _.Inputs = request.Variables.ToInputs();
>         _.UserContext = _settings.BuildUserContext?.Invoke(context);
>     });
> 
>     await WriteResponseAsync(context, result);
> }
> ```

this was related with my issue but you forget tell that to use JObject in dotnet 3 or higher, we need to add the package
Microsoft.AspNetCore.Mvc.NewtonsoftJson

Usage:
https://dotnetcoretutorials.com/2019/12/19/using-newtonsoft-json-in-net-core-3-projects/
