### ISSUE TITLE
QueryArgument.Name -> Force CamelCase

### ISSUE THREAD

**Issue by deinok** [graphql-dotnet/graphql-dotnet#609]
Should be QueryArgument.Name be forced to CamelCase?

Seems like its more a variable than a Type

**Comment by joemcbride** [comment]
When this library was fairly new, it only supported camelCase just about everywhere.  There were a number of issues logged asking for this to be configurable.  So I would vote for avoiding forcing casing to something specific.

There is a `IFieldNameConverter` that could perhaps be utilized to "force the preference".

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Conversion/IFieldNameConverter.cs

**Comment by deinok** [comment]
Im usign a lot of `nameof(Type)` and the QueryArguments seems the only point where a "variable" is using not the DefaultNameConverter.
Also, this change will be a breaking change, so im not sure if its okey to do it or no.
