### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by wiktor-golonka** [graphql-dotnet/graphql-dotnet#610]
Hi, 
Stable version of the nuget package is already 7 months old. 
Can we please have an update of that version?

**Comment by joemcbride** [comment]
There are pre-release versions of 2.0 on nuget.  There won't be any more 0.x versions published.  Here are the milestones that need to be complete for an official 2.0 release:

https://github.com/graphql-dotnet/graphql-dotnet/milestone/2
