### ISSUE TITLE
Is it possible to call a field resolver from different resolver?

### ISSUE THREAD

**Issue by wiktor-golonka** [graphql-dotnet/graphql-dotnet#611]
Hi,
I know it's not a typical case and normally FieldB should be requested through FieldA. 
I have two fields:
```
this.FieldAsync("fieldA", resolve: async context => await DbQueryForFieldA(context.Source.GetPropertyValue("SomeId")));
this.Field("fieldB", resolve: context => FieldA.FieldB );
```

Field B depends on `fieldA` and `fieldA` is resolved only when requested itself. Is it possible from `fieldB` resolver to ensure that `fieldA` has been resolved and if not then resolve `fieldA` from `fieldB` resolver?

I want to use this inside a generic method so I do not have any properties on context.Source. 

The only thing I can do is access the `FieldType` object of fieldA.

Cheers!

**Comment by joemcbride** [comment]
Perhaps you could use a dataloader?  I'm not sure if that would exactly fit (needing a sub property of what is loaded), but seems like that could potentially be supported.

https://graphql-dotnet.github.io/dataloader/

**Comment by wiktor-golonka** [comment]
If I correctly understood it, the dataloader has to be filled with data already so unfortunately I can't use it.

**Comment by sungam3r** [comment]
@wiktor-golonka Is this issue still actual for you?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
