### ISSUE TITLE
Is it possible to filter fields based on their values?

### ISSUE THREAD

**Issue by r2o3k** [graphql-dotnet/graphql-dotnet#615]
We have a use case where we'd like to hide certain fields from users based on a combination of the permissions that they have and the values that get returned for the objects.  I don't believe there is a way to do this now, so I guess this is more of a question of what steps would be needed in order to do this.  Any help would be greatly appreciated on this.

**Comment by r2o3k** [comment]
Disregard, we've managed to find a way to do this.

**Comment by joemcbride** [comment]
Mind sharing what you ended up going with?  This has been a TODO.  Since you may also want to filter what is returned with Introspection.
