### ISSUE TITLE
IDependencyResolver obsolete, how do I properly setup schema using .net core 2.0 DI and GraphQL ?

### ISSUE THREAD

**Issue by peyoquintero** [graphql-dotnet/graphql-dotnet#616]
I am setting up my  .net core environment to use .net core DI with GraphQL . The sample code (starwars) does this: 

services.AddSingleton<ISchema>(  s => new StarWarsSchema(new FuncDependencyResolver(type => (IGraphType)s.GetRequiredService(type))));

However, the IDependencyResolver interface is not available in the GraphQL version I am using (latest at this time: 0.17.3) so I can't use that code. Is there any example of how to do this with this latest version of graphQL or should I revert to some previous version instead?.

**Comment by joemcbride** [comment]
That example is using the 2.0 pre-release which is newer than 0.17.3.  So you can upgrade to the pre-release or use the setup that is required in 0.17.3, which is just removing the `FuncDependencyResolver` type.

2.x
```
services.AddSingleton(
  s => new StarWarsSchema(new FuncDependencyResolver(type => (IGraphType)s.GetRequiredService(type))));
```

0.x
```
services.AddSingleton( 
  s => new StarWarsSchema((type) => (IGraphType)s.GetRequiredService(type)));

**Comment by peyoquintero** [comment]
Thanks Joe. Is 2.0 pre-release the TypeResolve branch?

**Comment by joemcbride** [comment]
2.0 is currently the master branch

**Comment by fiyazbinhasan** [comment]
Hi @joemcbride , what if I configure the default container the following way,

    services.AddSingleton<StartWarsQuery>();
    services.AddSingleton<ISchema, StarWarsSchema();

And apply constructor injection to pass in the query or mutation,

    public class StarWarsSchema : Schema 
    {
        public StarWarsSchema(StartWarsQuery query)
        {
            Query = query;
        }
    }

Will it be any different from,

    services.AddSingleton(s => new StarWarsSchema(new FuncDependencyResolver(type => (IGraphType)s.GetRequiredService(type))));

**Comment by joemcbride** [comment]
@fiyazbinhasan Yes, if you do not provide a dependency resolver to your Schema then if you attempt to do constructor injection in any other GraphTypes in the graph then it will fail.  By default, if no dependency resolver is provided, it attempts to use `Acivator.CreateInstance` to create the graph types.

**Comment by joemcbride** [comment]
Updates related to this in #780.
