### ISSUE TITLE
Walking the nodes is different when fragments are involved

### ISSUE THREAD

**Issue by ghstahl** [graphql-dotnet/graphql-dotnet#618]
I build up the path to the node as it gets visited, as I have an outside configuration that requires claims to exist to see the node.
Enter appends the new field, and Leave pops it.
```
query qMyAuth{
  identity{
    claims{
      name
    }
  }
}
```
gets walked differently than
```
query qMyAuth{
  identity{
    claims{
      ... ClaimFragment
    }
  }
}

fragment ClaimFragment on claim {
 	name
}
```

With the no-fragment variant, I can build up a path to 
```
/identity/claims/name
```
which is validated against my outside config;
```
{
        "operationType": "query",
        "fieldPath": "/identity/claims/value",
        "claims": [{
            "type": "x-graphql-auth",
            "value": ""
          }]
      }
```

When fragments are in play I only can track the path as deep as;
```
/identity/claims
```
After the claims node has been visited it starts leaving, so my path starts to unwind.

Things then start over with;
```
/name
```

I would have hoped that fragments were transformed into the non-fragment variant to preserve a consistent walk.

i.e. 
```
query qMyAuth{
  identity{
    claims{
      ... ClaimFragment
    }
  }
}

fragment ClaimFragment on claim {
 	name
}
```
gets transformed to 
```
query qMyAuth{
  identity{
    claims{
      name
    }
  }
}
```
and then start the walk.

**Comment by ghstahl** [comment]
I was able to correctly track path through walk when there were FragmentSpreads.  I store away the path up to the FragmentSpread and then fix things up when I get a following FragmentDefinition.  

Anyway, I want to make sure you know that I am tracking visited filed paths for the purpose of authenticating by path.
```
{

  "graphQLFieldAuthority": {
    "records": [
      {
        "operationType": "query",
        "fieldPath": "/accessCode",
        "claims": [
          {
            "type": "x-graphql-auth",
            "value": ""
          }
        ]
      },
      {
        "operationType": "query",
        "fieldPath": "/identity/claims/value",
        "claims": []
      },
      {
        "operationType": "mutation",
        "fieldPath": "/blog2",
        "claims": [
          {
            "type": "x-graphql-auth",
            "value": ""
          }
        ]
      }
    ]
  }

}
```
The above, by convention, requires that the user.isAuthenticated and the claims must exist to be authorized.

**Comment by sungam3r** [comment]
@ ghstahl  I'm glad that you was able to correctly track path. There is nothing to fix here. FragmentSpread (as well as InlineFragment) is a special node in AST. 

> I would have hoped that fragments were transformed into the non-fragment variant to preserve a consistent walk.

The `Document` presents AST as is. No transformations are performed. All transformations and the interpretation of their results are entirely your responsibility. You may look at `Fields.CollectFields` method. What you are talking about happens inside. Also see http://spec.graphql.org/June2018/#sec-Field-Collection .It describes the algorithm for traversing the AST and working with fields, fragment spreads and inline fragments.
