### ISSUE TITLE
Error converting Input type with field for Enum List

### ISSUE THREAD

**Issue by ltouro** [graphql-dotnet/graphql-dotnet#621]
I have a InputType that has some fields. One of then is defined as follow:

```csharp
Field<ListGraphType<SomeEnumType>>("fieldName",
    resolve: context => context.Source.SomeEnumList                
);         
```
This list may be null. So, I execute the mutation sending an empty value 

```json
variables: {"fieldName": null}
```

Trying get the argument from the Graph Context generates an error: Value cannot be null. Parameter name: Item

```csharp
ResolveFieldContext<object>graphContext;
graphContext.GetArgument<MyInputTypeWithEnumList>("input");
```
This happens because the argument is present in the context as an object list containing one item: a null value. When converting the input to the List, it try to add a null object to the list, which generates the mentioned exception.
```
{object[1]} 
object[1] == null
```
Should the argument in context be null or should I handle adding null values to my enum list?

**Comment by PascalSenn** [comment]
I'm not sure how this behaves, but have you ever tried to use a nullable type as the underlying list type?

**Comment by PascalSenn** [comment]
Or just add a null check and return a empty list

**Comment by ltouro** [comment]
@PascalSenn Thanks for the swift feedback. Tried  your suggestion and it "worked". That is, the conversion to the object completed without errors.

However, the final array contains a null value, which does not map entirely to the input.

Which means:

```json
somePossibleNullList: null
```
is treated as 
```json
somePossibleNullList: [null]
```

That is fine because I can handle that scenario with no problem. However, that seems kind odd. Should I look around for a possible fix?

**Comment by joemcbride** [comment]
I believe that is a bug, fixed in #626

**Comment by SimonCropp** [comment]
@joemcbride looks like should be closed now?

**Comment by ltouro** [comment]
Thanks for all the support guys. This library is awesome :) Cheers
