### ISSUE TITLE
DocumentWriter and ILMerge /internalize nuget package

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#63]
I am trying to construct a DocumentWriter instance with a specific formatting (Indented). However, with the NuGet version of GraphQL, that is not possible as the public constructor takes an internal Enum as argument (not allowed by the compiler, but ILMerge and the verifyer does not seem to care).

I am not sure why Antlr4.Runtime.dll and Newtonsoft.Json.dll are embedded. I assume that will cause some problems like license-issues (your license must be either the same or atleast reference their licenses) and effectivly disabling bindings redirects, also causing bigger products when the same (or different versioned) nuget packages is installed elsewhere.

The workaround is rather simple - either build GraphQL.dll and use that instead of nuget (unpleasent) or simply replicate the functionality of DocumentWriter elsewhere (slightly annoying but reasonable for now).

**Comment by joemcbride** [comment]
Thanks for catching this!

Antlr4.Runtime.dll and Newtonsoft.Json.dll are embedded for a few reasons:

* Avoid the need for binding redirects (this is on purpose) - this shouldn't cause any versioning issues - I've been using a framework with a similar setup for years
* The version of Antlr referenced is a "pre-release" version, which some companies have policies against using - embedding it avoids that issue
* Convenience of having only a single DLL to reference

`IDocumentWriter` is not depended on by anything in the framework so it is provided as a convenience only.  I will fix it so it doesn't expose those internal types though and still provide a way to configure indents.  We can add more settings in the future if needed.

I could perhaps see an argument for not ILMerging Newtonsoft, though I definitely want to ILMerge Antlr.

I will look into the potential license issue with IL merging.

**Comment by joemcbride** [comment]
Published [0.6.1](https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.6.1) with that updated.

**Comment by MartinLorensen** [comment]
Thanks - This works fine with regards to the DocumentWriter.
