### ISSUE TITLE
QueryArgument<T> Interface support

### ISSUE THREAD

**Issue by PascalSenn** [graphql-dotnet/graphql-dotnet#630]
Is there any particular reason that QueryArguments must implement `GraphType`?

https://github.com/graphql-dotnet/graphql-dotnet/blob/b5dfa69fc08ed7f1d35e00e89693458662345c97/src/GraphQL/Types/QueryArgument.cs#L7
and
https://github.com/graphql-dotnet/graphql-dotnet/blob/b5dfa69fc08ed7f1d35e00e89693458662345c97/src/GraphQL/Types/QueryArgument.cs#L24

It's currently not possible to add query arguments which derive from IGraphType

**Comment by joemcbride** [comment]
None at all, that is a bug.
