### ISSUE TITLE
[Question] about value objects

### ISSUE THREAD

**Issue by miguelcaravantes** [graphql-dotnet/graphql-dotnet#636]
i have an object with a value object email and i need query the email as string. ¿How can i do this whitout use a DTO class?

**Comment by joemcbride** [comment]
`ResolveFieldContext.Arguments` is a dictionary with arguments.   Should be able to pull values from there.  If it is multiple levels deep then you would have to do some additional casting to/from `Dictionary<string,object>()`.

**Comment by miguelcaravantes** [comment]
the problem is not pull arguments, the problem is sending values to the client, my email value object is not sended as string

**Comment by joemcbride** [comment]
Ah - you could create your own scalar type to do that.  To convert it from your value object to a string.

**Comment by joemcbride** [comment]
Something like this:

```
Field<EmailGraphType>("email", resolve: context =>
{
    return new Email{ Value = "me@me.com"};
});

    public class Email
    {
        public string Value { get; set; }
    }

    public class EmailGraphType : ScalarGraphType
    {
        public override object ParseLiteral(IValue value)
        {
            if(value is StringValue)
            {
                return ((StringValue)value).Value;
            }

            return null;
        }

        public override object ParseValue(object value)
        {
            if(value is string)
            {
                return new Email { Value = value.ToString() };
            }

            return null;
        }

        public override object Serialize(object value)
        {
            return ((Email)value).Value;
        }
    }
```

**Comment by miguelcaravantes** [comment]
thank you so much!!!
