### ISSUE TITLE
Extracting better error messages on schema failures

### ISSUE THREAD

**Issue by pingvinen** [graphql-dotnet/graphql-dotnet#638]
Whenever I mess up my schema, I currently have to dig down into your dll and set a breakpoint the DocumentExecutor in the `catch (Exception)` block.

I always seem to be given a `TargetInvocationException` which is extremely unhelpful, but the innerException on that actually contains useful information.

Would it make sense to add something like:
```csharp
catch (TargetInvocationException e)
{
	if (e.InnerException != null)
	{
		// use the InnerException
	} 
	else
	{
		// do the current thing
	}
}
```

**Comment by joemcbride** [comment]
Have you been using the ExposeExceptions option in the ExecutionOptions?  That should show the inner exception if I’m not mistaken.

**Comment by pingvinen** [comment]
I had not noticed that option. I will try that out.

**Comment by pingvinen** [comment]
That works :)
