### ISSUE TITLE
Get type requested fields names as an array of strings

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#659]
I would like to know how to get all the names of fields from a query so I can build dynamic selects at the query level.

Example: "{ hero { name, firstname } }"

My List array would content ["name", "firstname"]

```
    public class StarWarsQuery : ObjectGraphType
    {
      public StarWarsQuery()
      {
        Field<DroidType>(
          "hero",
          resolve: context => {
                    context.RequestedFields // [name, firstname ]
return new Droid { Id = "1", Name = "R2-D2" }}
        );
      }
    }
```

thanks!

**Comment by joemcbride** [comment]
Try `context.SubFields`

**Comment by Jonatthu** [comment]
Graphql 0.17.3 does not have SubFields on context when I am debugging  @joemcbride

**Comment by joemcbride** [comment]
@Jonatthu Was added in 2.0.
