### ISSUE TITLE
null returned for resolved records

### ISSUE THREAD

**Issue by bdparrish** [graphql-dotnet/graphql-dotnet#666]
Why am I seeing `null` for each record resolved?

```json
{
    "data": {
        "customers": [
            null,
            null
        ]
    }
}
```

**Comment by joemcbride** [comment]
Not enough information to be of much help.  Primary reason you would be getting nulls is if your resolver returned a null.

Did an exception happen?  Did you debug your resolver and ensure that it is actually returning data?

**Comment by bdparrish** [comment]
I originally thought this was just a common problem with me doing a dumb mistake.  I debugged it as much as I could.  It would not step into the library resolver for the returned entities.  There are two entities in the database.  I am using the shared model and repository code that I have with my standard API and I am returning the two entities from my database there.

Here is the resolver code, it is utilizing an async process, but I am assuming that that is not the problem since the result has the right number of records.  My guess is from the library not being able to create the object correctly.  Is there anyway to utilize Newtonsoft.JSON library to return the right JSON?  It seems like it is the standard for a JsonResult and that is what I am currently implementing on my models.

```csharp
public Func<ResolveFieldContext<object>, object> GetResolver()
{
    return context => {
        Guid id = context.GetArgument<Guid>("id");

        if (id != Guid.Empty)
        {
            return _customerRepository.GetAsync(id);
        }
        else
        {
            return _customerRepository.ListAllAsync();
        }
    };
}
```

**Comment by joemcbride** [comment]
What does the rest of your field definition look like?  Looking at that resolver it is returning both a single object and a list.  You would typically have two different fields for that and two different resolvers.

**Comment by bdparrish** [comment]
```csharp
Field<CustomerInterface>(
    "customer",
    resolve: new CustomerData(customerRepository).GetResolver()
);

Field<ListGraphType<CustomerInterface>>(
    "customers",
    resolve: new CustomerData(customerRepository).GetResolver()
);
```

**Comment by joemcbride** [comment]
Check out these sections of the docs:

https://graphql-dotnet.github.io/getting-started/#interfaces
https://graphql-dotnet.github.io/getting-started/#istypeof
https://graphql-dotnet.github.io/getting-started/#resolvetype

**Comment by bdparrish** [comment]
Yeah it returns a `Customer` object, other things look like this...

CustomerSchema
```csharp
public class CustomerSchema : Schema
{
    public CustomerSchema(ICustomerRepository customerRepository)
    {
        Query = new CustomerQuery(customerRepository);
        RegisterType<CustomerType>();
    }
}
```

CustomerInterface
```csharp
public class CustomerInterface : InterfaceGraphType<Customer>
{
    public CustomerInterface()
    {
        Name = "customer";

        Field(x => x.Id, type: typeof(IdGraphType)).Name("id");
        Field(x => x.Name).Name("name");
    }
}
```

CustomerData
```csharp
public class CustomerType : ObjectGraphType<Customer>
{
    public CustomerType()
    {
        Name = "Customer";

        Field(x => x.Id, type: typeof(IdGraphType)).Name("id");
        Field(x => x.Name).Name("name");
    }
}
```

**Comment by joemcbride** [comment]
Don't see `Interface<CustomerInterface>();` on `CustomerType`.  You probably also need to use a different name for the interface and the implementing type.  Internals of the library may not distinguish between `customer` and `Customer`.

**Comment by bdparrish** [comment]
Bingo! Thanks @joemcbride 

I had to add these... to my Type definition.

```csharp
Interface<CustomerInterface>();

IsTypeOf = obj => obj is Customer;
```

**Comment by joemcbride** [comment]
🎉 `IsTypeOf` is added for you if you use `ObjectGraphType<T>`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/ObjectGraphType.cs#L25

**Comment by bdparrish** [comment]
So, why didn't it work in my original definition of `CustomerType` if it is automagically added?

**Comment by joemcbride** [comment]
You were missing `Interface<CustomerInterface>();`.  I would venture if you removed the `IsTypeOf` but kept the `Interface<>` it would work.

**Comment by bdparrish** [comment]
Quick change and that is correct.  Thanks again for the quick responses @joemcbride - excellent customer service and a 5 star rating.
