### ISSUE TITLE
[Question] - nested mutations or multiple files

### ISSUE THREAD

**Issue by sgwozdz** [graphql-dotnet/graphql-dotnet#667]
Hi guys,

I'm trying to figure out how to do nested mutations if it's even possible? 

I want to have better, logical spearation.
**Schema.Mutation** is type **IObjectGraphType**. 
So I created corresponding file. Everything is fine when I have all mutations in one file, but it's stupid for anything bigger than example project. I want to split mutations logical into separate file, but how to wrap it and make it work ?

**Comment by sgwozdz** [comment]
In fact few minutes after I wrote this question I found out this solution. I'm not happy with this but it works.

**Comment by joemcbride** [comment]
Here is one "trick" you can do - you can "group" them under a subfield.  Something like this:

```
Field<PersonMutation>("people", resolve: ctx => new {});

mutation CreatePersonMutation {
  people {
    createPerson(name: "Joe") {
      id
      name
    }
  }
}
```

Not the best perhaps, but an option.
