### ISSUE TITLE
DataLoader without DI

### ISSUE THREAD

**Issue by joelmandell** [graphql-dotnet/graphql-dotnet#668]
Hello,
I am having trouble implementing DataLoader without DI.
In the documentation it is just an example of how to do it with an DI.
But I have setup so I have a WebApi Route for Graphql, where I set up the DocumentExecutor.
How can I setup DataLoader in this scenario?

**Comment by joelmandell** [comment]
Okay so I did find a way. But I does not feel quite right to do it like this.
Sorry for vb syntax:
```Dim ctxAc = New DataLoader.DataLoaderContextAccessor
ctxAc.Context = New DataLoaderContext()
Dim doc = New DataLoader.DataLoaderDocumentListener(ctxAc)
```

And when defining the DocumentExecutor I set the Root object to contain the DataLOaderContextAccessor.
Then in my field resolvers I can do ctx.Root.Context.GetOrAddBatchLoader...

If there is a better way than using DI, I would like to know it :=)

**Comment by johnrutherford** [comment]
Yeah, it was really designed to work with DI. But I don't see any problems with the way you've done it.
