### ISSUE TITLE
Handling Map Types (looking for a better solution than Serialisation) 

### ISSUE THREAD

**Issue by KiraNamida** [graphql-dotnet/graphql-dotnet#669]
Greetings.

I am looking for a way to handle an input map types myself as I know that they are not supported out of the box in the GraphQL as I need to send a collection of Key Value pairs over for an arbitrary set. However, I running into some trouble with defining my `InputObjectGraphType` to handle the conversion.

Here's what I have (names simplified and bits cut out for brevity):

The query I am using to send over:
```
{
  "create": {
    "name": "name",
    "set": "DOMAIN",
    "stats": [
      {"key": "hello", "value": "1"}
    ]
  }
}
```
And the Class I want it to be in when all is said and done:
```
public class CreateCharacter
{
    public string Name { get; set; }
    public string Set { get; set; }
    public IEnumerable<KeyValuePair<string, int>> Stats { get; set; }
    public IEnumerable<KeyValuePair<string, string>> MetaData { get; set; }
}
```
I know that these two ultimately work because I can do either of the following in my mutation (where I desire this input) and get the `context.Arguments` onto my object (ignoring the fact it doesn't loop for the sake of this example)
```
var step1 = context.Arguments["create"];
var step2 = (step1 as Dictionary<string, object>)["stats"];
var step3 = (step2 as object[])[0];
var step4 = (step3 as Dictionary<string, object>);
var keyValues = new List<KeyValuePair<string, int>>();
keyValues.Add(new KeyValuePair<string, int>(step4["key"].ToString(), int.Parse(step4["value"].ToString())));
var create = new Create { Stats =  keyValues };
```
or
```
var createCharacter = JsonConvert.DeserializeObject<Create>(JsonConvert.SerializeObject(context.Arguments["create"]));
```
The GraphiQL style ui also lets me enter this without issue so the schema definition works and  I am reasonable confident I am sending over data that matches what I want.
Where if's falling down is in trying to set up my argument type so I can leverage `context.GetArgument<CreateType>("create")` so I don't have to keep writing long conversion chains or serialise and unserialise in each query or mutation.

Currently, my input object graph look like this:
```
CreateType : InputObjectGraphType<Create>...
public CreaterType()
{
    Name = "Character";
    Field(x => x.Name);
    Field(x => x.Set, type: typeof(EnumerationGraphType<Set>));
    Field<ListGraphType<InputMapType>>(nameof(Create.Stats), resolve: context => {
        var step1 = context.Arguments["createCharacter"];
        var step2 = (step1 as Dictionary<string, object>)["stats"];
        var step3 = (step2 as object[])[0];
        var step4 = (step3 as Dictionary<string, object>);
        var keyValues = new List<KeyValuePair<string, int>>();
        keyValues.Add(new KeyValuePair<string, int>(step4["key"].ToString(), int.Parse(step4["value"].ToString())));
        new CreateCharacter { Stats = keyValues };
    });
}

public class InputMapType : InputObjectGraphType
{
    public InputMapType()
    {
        Name = "InputMap";
        Field<StringGraphType>("key");
        Field<StringGraphType>("value");
    }
}
```
At the moment: I never hit this code so debugging it isn't a ready option. If I just try and call  `context.GetArgument<Create>("create")` I get a nice fat Argumentation that is typically vague (though included below anyway for reference). Any idea what is going on here and how I can define the input type to do this conversion for me as I don't really know what it's trying to do when it fails so begin trying to fix it.

Thank you.

**Comment by joemcbride** [comment]
I think the issue you're running into is that `KeyValuePair` only has a constructor and the code in `GetArgument` expects a class with a parameterless default constructor and tries to set properties (Key/Value on `KeyValuePair` are read-only).

**Comment by joemcbride** [comment]
```
Field<ListGraphType<InputMapType>>(nameof(Create.Stats), resolve: context => {
    context.Arguments["createCharacter"];
});
```

This code should not work because you have not defined an argument for that field - which you shouldn't be using Arguments with input types anyways. Input types should basically be a 1-1 mapping to your DTOs.

**Comment by joemcbride** [comment]
Here's an example of something that works:

```
mutation {
  createCharacter(create: { name: "name", set: "DOMAIN", stats: [ { key: "hello", value: 1  } ] }) {
    name
    set
    stats {
      key
      value
    }
  }
}
```

```csharp
    public class Character
    {
        public string Name { get; set; }
        public string Set { get; set; }
        public IEnumerable<StatsKVP> Stats { get; set; }
    }

    public class CreateCharacter
    {
        public string Name { get; set; }
        public string Set { get; set; }
        public IEnumerable<StatsKVP> Stats { get; set; }
    }

    public class StatsKVP
    {
        public string Key { get; set;}
        public int Value { get; set;}
    }

    public class CharacterType : ObjectGraphType<Character>
    {
        public CharacterType()
        {
            Name = "Character";
            Field(x => x.Name);
            Field(x => x.Set);
            Field(x => x.Stats, type:typeof(ListGraphType<StatType>));
        }
    }

    public class CreateCharacterInputType : InputObjectGraphType<CreateCharacter>
    {
        public CreateCharacterInputType()
        {
            Name = "Character";
            Field(x => x.Name);
            Field(x => x.Set, nullable: true);
            Field<ListGraphType<StatsInputType>>("stats");
        }
    }

    public class StatType : ObjectGraphType
    {
        public StatType()
        {
            Name = "Stat";
            Field<StringGraphType>("key");
            Field<IntGraphType>("value");
        }
    }

    public class StatsInputType : InputObjectGraphType
    {
        public StatsInputType()
        {
            Name = "StatsInput";
            Field<StringGraphType>("key");
            Field<IntGraphType>("value");
        }
    }

    public class MySchema : Schema
    {
        public MySchema()
        {
            Mutation = new CreateMutation();
        }
    }

    public class CreateMutation : ObjectGraphType
    {
        public CreateMutation()
        {
            Name = "Mutation";
            Field<CharacterType>(
                "createCharacter",
                arguments: new QueryArguments(
                    new QueryArgument<CreateCharacterInputType>() { Name = "create" }
                ),
                resolve: context =>
                {
                    var create = context.GetArgument<CreateCharacter>("create");
                    // create character from arguments
                    return new Character();
                });
        }
    }
```

**Comment by KiraNamida** [comment]
That still leaves we with:
```
[ {key, value}, {key, value}, {key, value}, ... ]
```
rather than
```
{
    key: value,
    key: value,
    key: value,
    ...
}
```
which is what I am going to to match up with my .NET entites.

**Comment by sungam3r** [comment]
> At the moment: I never hit this code so debugging it isn't a ready option. 

It is a known issue. `InputObjectGraphType` does not use resolvers. See #1176 and linked issues.

**Comment by sungam3r** [comment]
@KiraNamida Done in #1582 . You can try the latest preview.

**Comment by joemcbride** [comment]
For anyone coming here looking for generic `Dictionary` support.

There is an _Any scalar type in the Federation objects which you can use with dictionaries.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/Federation/AnyScalarGraphType.cs
https://github.com/graphql-dotnet/graphql-dotnet/blob/06cc50bea0bb942237934cec3ed001dc8fd48ed6/src/GraphQL.Tests/Utilities/FederatedSchemaBuilderTests.cs#L86-L121

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/Federation/AnyValue.cs
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/Federation/AnyValueConverter.cs

You will need to register the AnyScalarGraphType, AnyValue, and AnyValueConverter with your Schema.

```csharp
 public ExampleSchema(IDependencyResolver resolver)
    : base(resolver)
{        
    this.RegisterValueConverter(new AnyValueConverter());
}
```

**Comment by Socolin** [comment]
@joemcbride Hello, could you update the example for the new version ? `RegisterValueConverter` does not exists anymore and there is no documentation about the replacement

**Comment by Shane32** [comment]
@Socolin Are you trying to write a JSON scalar?  For input over variables, input as a literal, output, or all of the above?  Have you read https://graphql-dotnet.github.io/docs/getting-started/custom-scalars#valueconverter ?

**Comment by Socolin** [comment]
@Shane32 No, I have a mutation to configure an endpoint and I need to pass a list or dictionary of header, so I'm looking either for 

- a list of `KeyValuePair<string, string>` in the input model that I can convert to a `Dictionary<string, string>`
- a dictionary in the input model that will be assigned to the dictionary

Since I'm getting an error for the first option 


```
Object of type 'System.Collections.Generic.List`1[System.Collections.Generic.KeyValuePair`2[System.String,System.String]]' cannot be converted to type 'System.Collections.Generic.Dictionary`2[System.String,System.String]'
```

I'm looking for a dictionary in the input model,  (but any of the 2 options will work in my case)

I tried
```cs
ValueConverter.Register<List<KeyValuePair<string, string>>, Dictionary<string, string>>(v => v.ToDictionary(x => x.Key, x => x.Value));
```

but I'm still getting the error

**Comment by Shane32** [comment]
If you post your `Field` call, and any graph types you've created to try to get it to work, I can probably suggest some changes to help.

**Comment by Socolin** [comment]
```cs
public class SomeData
{
	public string? Url { get; set; }
	public Dictionary<string, string>? Headers { get; set; }
}

public sealed class SomeDataInputType : InputObjectGraphType<SomeData>
{
	public SomeDataInputType()
	{
		Name = nameof(SomeDataInputType);
		Field<StringGraphType>("url");
		Field(p => p.Headers, nullable: false, typeof(ListGraphType<HttpHeaderInputType>))
			.Name("headers");
	}
}

public sealed class HttpHeaderInputType : InputObjectGraphType<KeyValuePair<string, string>>
{
	public HttpHeaderInputType()
	{
		Name = nameof(HttpHeaderInputType);
		Field(p => p.Key)
			.Name("name");
		Field(p => p.Value, nullable: false)
			.Name("value");
	}
}
```


```gql
  createSomething(
    input: {
      data: {
        url: "abc"
        headers: [{
          name: "abc"
          value: "a"
        }]
      }
    }
```

**Comment by Shane32** [comment]
```cs
public class SomeData
{
	public string? Url { get; set; }
	public Dictionary<string, string>? Headers { get; set; }
}

public sealed class SomeDataInputType : InputObjectGraphType<SomeData>
{
	public SomeDataInputType()
	{
		Name = nameof(SomeDataInputType);
		Field<StringGraphType>("url");
		Field(p => p.Headers, nullable: false, typeof(ListGraphType<HttpHeaderInputType>))
			.Name("headers");
	}

	public override object ParseDictionary(IDictionary<string, object> value)
	{
		return new SomeData
		{
			Url = value.TryGetValue("url", out var url) ? url?.ToString() : null,
			Headers = value.TryGetValue("headers", out var headers) ? new Dictionary<string, string>((IEnumerable<KeyValuePair<string, string>>)headers) : null,
		};
	}
}

public sealed class HttpHeaderInputType : InputObjectGraphType<KeyValuePair<string, string>>
{
	public HttpHeaderInputType()
	{
		Name = nameof(HttpHeaderInputType);
		Field(p => p.Key)
			.Name("name");
		Field(p => p.Value, nullable: false)
			.Name("value");
	}
}
  createSomething(
    input: {
      data: {
        url: "abc"
        headers: [{
          name: "abc"
          value: "a"
        }]
      }
    }
```

Try adding an `override object ParseDictionary` method to SomeDataInputType.

**Comment by Shane32** [comment]
You might also need to implement ParseDictionary on HttpHeaderInputType, since you're not using AutoRegistringInputObjectGraphType.  If you need to, it should return a `KeyValuePair<string, string>`

**Comment by Socolin** [comment]
I'm getting another error ` System.InvalidCastException: Unable to cast object of type 'System.Object[]' to type 'System.Collections.Generic.IEnumerable`1[System.Collections.Generic.KeyValuePair`2[System.String,System.String]]'.\` since this is still an `Object[]` at this point 

![image](https://user-images.githubusercontent.com/539620/173673090-a2ab81a0-5b58-4544-ad48-2a8277beeb4a.png)

When I do not override it it being converted in `ObjectExtensions.ToObject()`.

![image](https://user-images.githubusercontent.com/539620/173673442-fe3164e0-5725-46f5-9106-0157c5dfaa00.png)

I can try to customize a bit ParseDictionary but I'm not expecting writting this each time I have to deal with something like this.
Could ObjectExtension handle this case too ? `Enumerable<KeyValuePair>` => `Dictionary` or call `ValueConverter.TryConvertTo` after the collection is converted to the `List<KeyValuePair>`

**Comment by Shane32** [comment]
Probably.  There are so many different ways to do the same thing with GraphQL.NET.  I'm just not as familiar with the `ValueConverter` since I don't use it (whereas I added the `ParseDictionary` method).

**Comment by Shane32** [comment]
I assume you already tried this, or it doesn't work for you?

```cs
public class SomeData
{
	public string? Url { get; set; }
	public IEnumerable<KeyValuePair<string, string>>? Headers { get; set; }
}
```

**Comment by Shane32** [comment]
So the cast is wrong because `object[]` cannot be converted directly to `IEnumerable<KeyValuePair<string, string>>`.  That makes sense.

```cs
	public override object ParseDictionary(IDictionary<string, object> value)
	{
		return new SomeData
		{
			Url = value.TryGetValue("url", out var url) ? url?.ToString() : null,
			Headers = value.TryGetValue("headers", out var headers) && headers != null
				? new Dictionary<string, string>(((IEnumerable<object>)headers).Cast<KeyValuePair<string, string>>()) : null,
		};
	}
```

**Comment by Shane32** [comment]
If I had a use case, I would probably have written:

```cs
// graph type: AutoRegisteringInputObjectGraphType<SomeData>
public class SomeData
{
	public string? Url { get; set; }
	[InputType(typeof(AutoRegisteringInputObjectGraphType<KeyValuePair<string, string>>))]
	public IEnumerable<KeyValuePair<string, string>>? Headers { get; set; }
}
```

But if you want to name the graph type and stuff, or if you want `Headers` to be a dictionary, you need a bit more code.

**Comment by Socolin** [comment]
> ```cs
> [InputType(typeof(AutoRegisteringInputObjectGraphType<KeyValuePair<string, string>>))]
> ```

`SomeData` is a shared object accross multiple project, so I don't want to add graph specific annotation on this.

**Comment by Shane32** [comment]
There's a decent chance that the value converter could work.  Just not sure what it is at the moment, sorry.

**Comment by Shane32** [comment]
ParseDictionary, on the other hand, lets you convert any form of input values to any form of object.  Like a custom deserializer.  It was added in response to requests for a 'resolve' function for input fields -- sorta what you need right now.

**Comment by Shane32** [comment]
Maybe we could add a `ParseField` method also.

```cs
// default implementation
protected virtual object? ParseField(string fieldName, IDictionary<string, object?> dictionary)
    => dictionary.TryGetValue(fieldName, out var val) ? val : null;

// your code
protected override object? ParseField(string fieldName, IDictionary<string, object?> dictionary)
{
    //e.g. when requesting 'whatever' field, convert to uppercase
    if (fieldName == "whatever")
        return dictionary.TryGetValue("whatever", out var val) ? val?.ToString().ToUpper() : null;
    return base.ParseField(fieldName, dictionary);
}
```

I'd look at the ValueConverter source code and poke around a bit there to see if I could get that to work then.

You can of course call base.ParseDictionary, but if it throws an exception, then that's not going to help

**Comment by Shane32** [comment]
You can very easily derive from `InputObjectGraphType<>`, add `ParseField` base definition, and then override `ParseDictionary` with code that uses `ParseField`.  Then for any of your models that need such functionality, you just derive from `MyInputObjectGraphType<>`.

**Comment by Socolin** [comment]
Something like this works too, but the less custom code I have to write the easier it is to maintain
```cs
	public override object ParseDictionary(IDictionary<string, object?> value)
	{
		if (value.Remove("headers", out var headers))
		{
			var data = (SomeData) base.ParseDictionary(value);
			data.Headers = headers != null
				? new Dictionary<string, string>(((object[]) headers).Cast<KeyValuePair<string, string>>())
				: null;
			return data;
		}

		return base.ParseDictionary(value);
	}
```
