### ISSUE TITLE
Multiple queries in one request

### ISSUE THREAD

**Issue by Dale4** [graphql-dotnet/graphql-dotnet#670]
Is there a way to send a single request with multiple queries.  I am trying to get information on 2 separate accounts, with out having to make two post requests.

This request will only return the latter Account_2 information.
{"query":"{
	account(name:\"Account_0\"){name created createdby}
	account(name:\"Account_2\"){name created createdby}
   }"
}

**Comment by BenjaBobs** [comment]
Yes
```graphql
query GetAccounts {
  A : account(name: "Account_0") { 
    name 
  }
  B : account(name: "Account_2") {
    name
  }
}
```

**Comment by Dale4** [comment]
Awesome! Thanks.

**Comment by priaChandrasekhar** [comment]
What is wrong with this request?

`{
  a: search(limit: 1, term: "RN109331951") {
    account {
      first_name
      last_name
      middle_name
      uid
    }
  }
  b: search(limit: 1, term: "RN107455617") {
    account {
      first_name
      last_name
      middle_name
      uid
    }
  }
}`

This is the output i see:

`{
  "data": {
    "a": [
      {
        "account": {
          "last_name": "cb7202",
          "uid": 646094,
          "middle_name": "",
          "first_name": "e3c524a"
        }
      }
    ]
  }
}`
