### ISSUE TITLE
Unable to run GraphQL Server

### ISSUE THREAD

**Issue by Tochemey** [graphql-dotnet/graphql-dotnet#671]
Hello Geeks,

I am facing an issue starting a graphql server on netcore. I am using this library and the netcore graphqli library to build a graphql server. However anytime I run the app I got the following error:

```
TypeError: Cannot read property 'kind' of null
    at getType (http://localhost:5000/graphql/graphiql.js:29953:17)
    at getOutputType (http://localhost:5000/graphql/graphiql.js:29992:16)
    at http://localhost:5000/graphql/graphiql.js:30113:15
    at http://localhost:5000/graphql/graphiql.js:24309:31
    at Array.reduce (<anonymous>)
    at keyValMap (http://localhost:5000/graphql/graphiql.js:24308:15)
    at buildFieldDefMap (http://localhost:5000/graphql/graphiql.js:30107:36)
    at fields (http://localhost:5000/graphql/graphiql.js:30056:16)
    at resolveThunk (http://localhost:5000/graphql/graphiql.js:27041:40)
    at defineFieldMap (http://localhost:5000/graphql/graphiql.js:27203:18)
```

**Comment by joemcbride** [comment]
What versions of this library and GraphiQL.js are you using?  Have you been able to make requests without using GraphiQL?

**Comment by Tochemey** [comment]
Hello,

I have tried a direct request and I got the following error:

```
{
    "errors": [
        {
            "message": "Object reference not set to an instance of an object."
        }
    ]
}
```

I am a newbie in graphql.

**Comment by Tochemey** [comment]
Hello Joe,

Please how do we solve this issue:
```
{
    "errors": [
        {
            "message": "Expected non-null value, resolve delegate return null for \"$......TransactionType\"",
            "code": "INVALID_OPERATION"
        }
    ]
}
```

**Comment by joemcbride** [comment]
I need more information to be able to help.  Can you post what your Schema and GraphType's look like?

Also, on the `ExecutionOptions` you can set `ExposeExceptions` which will give you the full stacktrace of the error.  You can also see the full exceptions when debugging by looking at the `ExecutionResult`.

```csharp
schema.Execute(_ =>
{
  _.ExposeExceptions = true;
});
```

**Comment by Tochemey** [comment]
I am able to figure out the issue. It was due to IoC registration. Some of my types were not registered. 
Thank you very much.

**Comment by ddecours** [comment]
thank you for taking the time to post the resolution - you save me time!
