### ISSUE TITLE
IDependencyResolver Issue in StarWars Sample project

### ISSUE THREAD

**Issue by libinks10** [graphql-dotnet/graphql-dotnet#679]
I have tried the StarWars sample provided and got some issue with "IDependencyResolver" even after referring the "Systems.Web.mvc".  The Error has been mentioned below.

"Error	3	'System.Web.Mvc.IDependencyResolver' does not contain a definition for 'Resolve' and no extension method 'Resolve' accepting a first argument of type 'System.Web.Mvc.IDependencyResolver' could be found (are you missing a using directive or an assembly reference?)	C:\Users\Lijo\Documents\Visual Studio 2012\Projects\Study\WindowsFormsApplication4\MvcApplication2\StarWarsSchema.cs	18"

Expect an immediate help on this from Anyone.

Thanks in Advance for your Help.

**Comment by joemcbride** [comment]
@libinks10 This library provides a `IDependencyResolver` interface.  It is not the same as the one in `System.Web.Mvc.IDependencyResolver`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/IDependencyResolver.cs

You will want to provide an implementation of that interface for the IoC container you are using.
