### ISSUE TITLE
NonNullGraphType<EnumType<MyEnum>> fails introspection querys

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#68]
I am not sure if this is a conventions issue or a GraphQL issue, but I think it is a GraphQL issue.

Adding the attached test [NonNullEnumGraphTypeTests.cs](https://github.com/graphql-dotnet/graphql-dotnet/files/208486/NonNullEnumGraphTypeTests.cs.txt) to the conventions test project illustrates the problem.

I have my own version of the EnumType<>-class which works outside the context of conventions 
[EnumType.cs](https://github.com/graphql-dotnet/graphql-dotnet/files/208495/EnumType.cs.txt). That version also causes the test to fail.

The ExecutionResult.Errors contains 2 errors:
"Error trying to resolve kind."
"Error trying to resolve name."

During execution of the retrospection query, somehow ends up calling GraphQL.Introspection.__Type.KindForType(Type type) with the type-object of the enum (in the example, 'Tests.Reflection.Wrappers.NonNullEnumGraphTypeTests+Foo') which ends up in 

      throw new ExecutionError(StringExtensions.ToFormat("Unkown kind of type: {0}", (object) type));

I have attempted to understand why, but so fare have not been able to get the big picture...

The test is a highly modified version of NonNullGraphTypeTests and from that I know that it seems to be only the introspection query that fails - querying data works fine.

**Comment by tlil87** [comment]
Let me take a look at this early next week @MartinLorensen - I'll be out travelling over the weekend and won't have time before that. Sorry. I'm pretty sure that I've run into the same in the past and that I've resolved it with my local, unpushed changes, but I will have to take a closer look before confirming that.

**Comment by MartinLorensen** [comment]
Sounds great!

And no hurry! The JS tooling (at least the one we are using) does not seem to care too much about anything being marked NonNull - so the easy workaround is just to declare the types as `EnumType<T>` instead of `NonNullGraphType<EnumType<T>>`.

**Comment by joemcbride** [comment]
It looks like this [tracks back to `ofType` on `__Type`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Introspection/__Type.cs#L111-L116).  It is resolving the generic argument.  It looks like this is currently used to expose `QueryArgument<T>` types.  Not sure how we want to solve that yet, though that looks like the issue.

Perhaps we can check if the generic type is of `GraphType` and return null if not, as an initial thought.

**Comment by joemcbride** [comment]
I was able to fix this with https://github.com/graphql-dotnet/graphql-dotnet/pull/69

All the tests pass at least.

@tlil87 Let me know if you fixed it differently.

**Comment by MartinLorensen** [comment]
I am not sure if this is the same issue, but adding the code bellow in a GraphType caused a simular problem:

```
      Connection<FooType>()
        .Name("foo")
        .Argument<EnumType<MyEnum>>("p", "p")
        .WithObject<Bar>()
        .Unidirectional()
        .Resolve(
          c => GetFoos(c.Object, c.GetArgument<MyEnum>("p"));
```

Introspection failes with (Exception message: "Unkown kind of type: MyEnum", from GraphQL.Introspection.__Type.KindForType(Type type) in C:\Home\projects\graphql-dotnet\src\GraphQL\Introspection\__Type.cs:line 205).

Second, I had hoped c.GetArgument<MyEnum>("p")  would work, but it returns defailt(MyEnum), ignoring the actual value of p. If i use c.GetArgument<string>("p") I get the string. This is a different problem, and I can see it is not obvious to solve as the context c does not seem know about the underlying GraphType (EnumType<> from conventions) which is the one that knows the actual mapping from string to enum value. Any thoughts? Should I make a separate issue? Here or in the conventions project?

**Comment by joemcbride** [comment]
The introspection error is probably the same issue.  I will go ahead and merge my change and push out a release.

> I had hoped c.GetArgument("p") would work

This is a separate issue.

> Here or in the conventions project

You would have to be explicitly depending on the conventions project for issues to be from there.  As far as I'm aware, there are no current releases of the conventions project.

**Comment by tlil87** [comment]
Correct. Aiming for a first release of the conventions project some time this week.

**Comment by joemcbride** [comment]
Published [v0.6.4](https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.6.4) with that introspection change.

**Comment by MartinLorensen** [comment]
I think 0.6.4 is broken. Our schema.json just shrunk 10% in size (from about 145 KB to about 131 KB) when upgrading from 0.6.3 to 0.6.4 (no other changes). And using the schema with GraphiQL, graphql-js causes exceptions like: 

```
ERROR in [...]/js/graphiqlapp.js
Module build failed: Error: Decorated type deeper than introspection query.
    at getType ([...]/node_modules\graphql\utilities\buildClientSchema.js:89:15)
 ....

```

It looks like most ofType becomes null. E.g. the __Schema  type, the types field  is of type "NOT_NULL" with `ofType = null` (where in 0.6.3 it was `ofType = List<NotNull<__Type>>`.

**Comment by joemcbride** [comment]
Is the type or types that it is failing on the same Enum type?  All of the existing tests we have pass with that change so perhaps we're missing a scenario.

**Comment by MartinLorensen** [comment]
It is a lot simpler. Running the attached [Program.cs](https://github.com/graphql-dotnet/graphql-dotnet/files/229319/Program.cs.txt):

```
      var documentExecuter = new DocumentExecuter();
      var executionResult = documentExecuter.ExecuteAsync(new Schema(), null, SchemaIntrospection.IntrospectionQuery, null).Result;
      var json = new DocumentWriter(true).Write(executionResult.Data);
      var version = new AssemblyName(documentExecuter.GetType().Assembly.FullName).Version;
      var scema = new SchemaPrinter(new Schema()).PrintFilteredSchema(_ => true);

      using (var textWriter = File.CreateText($"EmptyScema-{version}.txt"))
        textWriter.WriteLine(scema);

      using (var textWriter = File.CreateText($"EmptyScema-{version}.json.txt"))
        textWriter.WriteLine(json);

```
... it creates attached output file [EmptyScema-0.6.3.0.json](https://github.com/graphql-dotnet/graphql-dotnet/files/229297/EmptyScema-0.6.3.0.json.txt) with version 0.6.3, while with version 0.6.4 it creates [EmptyScema-0.6.4.0.json](https://github.com/graphql-dotnet/graphql-dotnet/files/229298/EmptyScema-0.6.4.0.json.txt). If you compare the two there is a lot of differences that I would not expect.

The other generated file (from the ScemaPrinter) is actually identical.

**Comment by tlil87** [comment]
@joemcbride @MartinLorensen: Re what I said about first release of conventions: I'm out traveling the next couple of weeks and won't have internet access unfortunately. So won't be able to make the release until I'm back. Sorry about that.

**Comment by joemcbride** [comment]
@MartinLorensen Thanks for catching this.  I have https://github.com/graphql-dotnet/graphql-dotnet/pull/71 which fixes this and adds a test to ensure there are no further regressions.

**Comment by MartinLorensen** [comment]
This seems to work now. Thanks!
