### ISSUE TITLE
How to create a file upload endpoint with dotnet-graphql 

### ISSUE THREAD

**Issue by tcetin** [graphql-dotnet/graphql-dotnet#682]
I am trying to create an endpoint about file upload but it doesn't handle with Apollo client. I asked at [stackoverflow](https://stackoverflow.com/questions/50671937/asp-net-core-file-upload-with-graphql-dotnet)

Please help with this.

**Comment by RehanSaeed** [comment]
My understanding is that GraphQL just does not cover how to do file upload/downloads. This is not something that is handled and you should still use a REST API for this scenario.

That said, there are some who have tried to shoehorn this feature in unofficially. [Here](https://medium.freecodecamp.org/how-to-manage-file-uploads-in-graphql-mutations-using-apollo-graphene-b48ed6a6498c) and [here](https://medium.com/@danielbuechele/file-uploads-with-graphql-and-apollo-5502bbf3941e) are good examples.

I don't think this project should bake these unofficial features in. When or if an official spec is announced, then it should be added.

**Comment by RehanSaeed** [comment]
Looks like it's possible but [not currently documented](https://github.com/graphql-dotnet/graphql-dotnet/issues/758).

@petrovic-ivan seems to have implemented it [here](https://github.com/graphql-dotnet/graphql-dotnet/issues/419).
@jlebensold has also managed it [here](https://github.com/graphql-dotnet/graphql-dotnet/issues/213).

Would be nice to get this documented.

**Comment by SirwanAfifi** [comment]
Is there any working example of how to upload a file? @joemcbride

**Comment by SimonCropp** [comment]
closing this since it is outside the scope of graphql-dotnet. the graphql spec doesnt define how attachments should be done, and graphql-dotnet does not stop you from using any of the suggested workarounds. for example https://github.com/SimonCropp/GraphQL.Attachments
