### ISSUE TITLE
After subscribing, graphql automatically sends the last notification

### ISSUE THREAD

**Issue by wiktor-golonka** [graphql-dotnet/graphql-dotnet#683]
Hi, 
If there were any notifications before subscribing then that new subscriber receives automatically the last one.

Steps to reproduce:
1. Subscribe to graphql subscription field.
2. Wait for the new notification.
3. New notification is spread to subscribers.
4. Another client subscribes.
5. Client receives the last notification that has been sent.

I verified if that's a graphql-server issue or maybe my code issue but it's not.

**Comment by joemcbride** [comment]
This is typical if using a ReplaySubject.  It does as you describe by design.  What type of observable are you returning in your subscription?

**Comment by wiktor-golonka** [comment]
@joemcbride : ... You're right! I was initializing ISubject with ReplySubject. Completely missed that. Thanks!
