### ISSUE TITLE
Defining union types in .graphqls?

### ISSUE THREAD

**Issue by acronoah** [graphql-dotnet/graphql-dotnet#685]
I am using a graphqls file to define my schema in a standardized way and then hooking that schema up dynamically at runtime to collections in Mongo, resolving links, etc.  Everything is working great...until I start trying to define unions in the schema.

```
interface IAutomationJobOutput {
    s3Path: String
}

type SimulationJobOutput implements IAutomationJobOutput {
    s3Path: String
}

union AutomationJobOutput = SimulationJobOutput 
```

Error:
```
Application startup exception: GraphQL.ExecutionError: Union type AutomationJobOutput does not provide a "resolveType" functionand possible Type "SimulationJobOutput" does not provide a "isTypeOf" function.  There is no way to resolve this possible type during execution.
   at GraphQL.Types.GraphTypesLookup.<>c__DisplayClass18_2.<AddType>b__2(IObjectGraphType unionedType)
```

Advice?  I don't want to define these in C# - these unions should be definable by people unfamiliar with C#.

**Comment by joemcbride** [comment]
You can still use Schema syntax, though you do have to provide that implementation - just like you have to provide a resolver.  No way around that.

Example of providing `IsTypeOf`: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs#L120

See these docs: https://graphql-dotnet.github.io/getting-started/#istypeof

**Comment by joemcbride** [comment]
Going to close this, let me know if I can help further.
