### ISSUE TITLE
AstPrinter _configs protected

### ISSUE THREAD

**Issue by PascalSenn** [graphql-dotnet/graphql-dotnet#690]
could we make _configs protected?

https://github.com/graphql-dotnet/graphql-dotnet/blob/c66b6c0b4cde1cdd7b93d025c60b169f9a0c81d4/src/GraphQL/Utilities/AstPrinter.cs#L155

That would really help in build a own query visitor

**Comment by joemcbride** [comment]
Probably fine - I'd be curious in hearing what your scenario is?

**Comment by PascalSenn** [comment]
I need to get all variable references from a query. 
Probably gonna make a pull request with a refactored AST printer. Gonna make it more generic.   
AstPrintVisitor : AstVistor

**Comment by joemcbride** [comment]
Hm, you could probably do what you need with the `BasicVisitor` used in Validation.

https://github.com/graphql-dotnet/graphql-dotnet/blob/c66b6c0b4cde1cdd7b93d025c60b169f9a0c81d4/src/GraphQL/Validation/BasicVisitor.cs

**Comment by joemcbride** [comment]
Something like this?

```csharp
var document = ...

var varDefMap = new Dictionary<string, VariableDefinition>();

var listener = new EnterLeaveListener(_ =>
{
    _.Match<VariableDefinition>(
        varDefAst => varDefMap[varDefAst.Name] = varDefAst
    );
});

var visitor = new BasicVisitor(listener);
visitor.Visit(document);

// print each variable in varDefMap using AstPrinter.Print()
```

**Comment by PascalSenn** [comment]
That's.. 
yes, exactly what I was searching for 👍  Thanks a lot !

**Comment by joemcbride** [comment]
I should probably move that visitor/listener to `Utilities` namespace to make it more discoverable ...

**Comment by PascalSenn** [comment]
That'd be good. 👍
