### ISSUE TITLE
validate user using query parameter

### ISSUE THREAD

**Issue by alonstar** [graphql-dotnet/graphql-dotnet#692]
If I want to validate user authority using query parameter, ex : Company has field named "authorzie", it needs roles to access. Now I validate roles on resolve, does any other way to do this?

```csharp
public class GraphQLQuery : ObjectGraphType
{
    public GraphQLQuery(
        IUser user,
        ICompanyAppService companyService)
    {
        this.Field<CompanyType>(
            "Company",
            arguments: new QueryArguments(new QueryArgument<NonNullGraphType<IntGraphType>>() { Name = "id" }),
            resolve: context =>
            {
                var id = context.HasArgument("id") ? context.GetArgument<int>("id") : default;
                return companyService.FindCompany(id);                    
            })
            .AuthorizeWith(PolicyConstant.Member);
    }
}

public class CompanyType : ObjectGraphType<Company>
{
    public CompanyType(
        IUser user)
    {
        this.Name = "Company";
        this.Field(_ => _.Id);
        this.Field(_ => _.Name);

        this.Field<AuthorizedType>("Authorize", resolve: context =>
        {
            if (!user.ValidateRoles(context.Source.Id, RoleClaim.Authroize))
            {
                context.Errors.Add(new ValidationError(context.Document.OriginalQuery, "authorization", "You are not authorized to run this query"));
                return default;
            }

            return context.Source.CompanyId;
        });
    }
}
```

**Comment by joemcbride** [comment]
You can use this authorization library.  https://github.com/graphql-dotnet/authorization

Looks like perhaps you looked at it already with `.AuthorizeWith(PolicyConstant.Member);`?

**Comment by alonstar** [comment]
@joemcbride  I can't figure out how to pass the company id to the validator.

**Comment by joemcbride** [comment]
Ah, my misunderstanding.  At present there isn't an easy way to do it.  What you have currently is the easiest way.  You could probably write a custom validation rule to do it, though it would not be very straightforward.

**Comment by joemcbride** [comment]
I'll also note that Facebook suggests to do exactly what you are doing with that type of scenario:

https://graphql.org/learn/authorization/

**Comment by alonstar** [comment]
@joemcbride  oh, I got it. Thanks !👍
