### ISSUE TITLE
DateTimeOffset converted to DateTime in StringExtensions.GetValue

### ISSUE THREAD

**Issue by SapphireBrand** [graphql-dotnet/graphql-dotnet#693]
If a query variable is of type DateTimeOffset, then the offset is ignored when the variable is converted. This happens in https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/StringExtensions.cs#L160:

```
        public static object GetValue(this object value)   // {{"from": "2018-05-23T17:26:57.66-04:00"}}
        {
            var objectValue = value as JObject; // objectValue is good: {{"from": "2018-05-23T17:26:57.66-04:00"}}
            if (objectValue != null)
            {
                var output = new Dictionary<string, object>();
                foreach (var kvp in objectValue)  // kvp is incorrect: {[from, 5/23/2018 5:26:57 PM]}
                {
                    output.Add(kvp.Key, GetValue(kvp.Value));  // kvp.Value is already a DateTime, so the offset is lost.
                }
                return output;
            }
```

**Comment by SapphireBrand** [comment]
OK, so this issue is outside the GraphQL code, I am leaving the solution here so that others can stumble upon the answer.

The GraphQL code does not deal with serializing the incoming message. Instead, your web app code has an object that represents the request payload, and a web framework constructs the payload by deserializing the request. For example, my code had the following:

```
        public class GraphQLDto
        {
            public string Query { get; set; }
            public string OperationName { get; set; }
            public JObject Variables { get; set; }
        }

        [Route("")]
        public async Task<HttpResponseMessage> PostAsync(GraphQLDto query)
        {
        }
```

So the Web framework (System.Web.Http) is constructing a JObject from the request object, and it is the serialization settings from *that* conversion that need to be controlled in order to get dates to convert into DateTimeOffset.

The solution is to add the line below to the config for your web app:

```
    config.Formatters.JsonFormatter.SerializerSettings.DateParseHandling = DateParseHandling.None;
```

(And you also need to declare your query arguments as DateTimeOffset, and define a DateTimeOffsetGraphType based on ScalarGraphType, and define a ParseValue member function that converts string to DateTimeOffset.)

An alternative is to set DateParseHandling.DateTimeOffset, but I think that is a subtle error. The key point is that the query knows the type of every variable, and the GraphQL engine will perform the right conversions internally. So it is best to use DateParseHandling.None (which leaves all dates as strings) so that the declaration of each variable will determine the type of parsing required.

**Comment by joemcbride** [comment]
Another thing that may be of note is the JSON Settings on serialization.  That may want to be customized with the `DocumentWriter`.

**Comment by SapphireBrand** [comment]
I didn't find any problem that required changes to GraphQL.Net's serialization settings. IIRC, the default serialization settings convert dates into strings, which works fine whether the source is DateTime or DateTimeOffset.

If I find anything then I will post a question.
