### ISSUE TITLE
Validation on the query parameter

### ISSUE THREAD

**Issue by phoenixjun** [graphql-dotnet/graphql-dotnet#694]
I would like to know what is the best place to put validation to the input parameter for the query for example 

```
{
  user(email: "useremail"){
  }
}
```

I want to make sure the passed in email is in the correct format, what is the best place to validate that?

while we are resolving the data? or there is some other options there?

**Comment by joemcbride** [comment]
You can use a `ValidationRule` for this to validate the inputs before it attempts to execute the query.  Here's one of the core validation rules used by the GraphQL spec that deals with Arguments:

https://github.com/graphql-dotnet/graphql-dotnet/blob/3f2355aacd6cfd8e080dba1d802b2fa00f958f85/src/GraphQL/Validation/Rules/ArgumentsOfCorrectType.cs#L14-L38

You can pass the validation rules you want to run to the `DocumentExecutor`.

```csharp
var executor = new DocumentExecutor();
var result = await executer.ExecuteAsync(_ =>
{
    _.Schema = schema;
    _.Query = request.Query;
    ...
    _.ValidationRules =
        DocumentValidator.CoreRules().Concat(new[]{ new EmailValidationRule() });
});
```

You could add metadata to the `QueryArgument` to provide a more generic way to configure what validations should be done for that argument, and use some validation library to do so.

https://graphql-dotnet.github.io/learn/#objectfield-metadata

**Comment by phoenixjun** [comment]
Thanks very much to your reply @joemcbride .

You mentioned about adding metadata to the QueryArgument, how is that done in the library? Currently, my argument is StringGraphType, do I need to create the argument as a separated type and then put the meta data there or I can just configure that when I defined the QueryArgument?

Thanks

**Comment by joemcbride** [comment]
I would say to add the metadata to the `QueryArgument`.  `QueryArgument` does not currently have built-in metadata like fields and objects do but should be able to add it.

This is what I was thinking:

```csharp
public class MyQueryArgument<T> : QueryArgument<T>, IProvideMetadata
{
    // members of IProvideMetadata
    IDictionary<string, object> Metadata { get; }
    TType GetMetadata<TType>(string key, TType defaultValue = default(TType));
    bool HasMetadata(string key);
}

public static class ArgumentValidationExtensions
{
    public static QueryArgument IsEmail(this QueryArgument argument)
    {
        emailArgument.Metadata["validator"] = "EMAIL_VALIDATOR";
    }
}

arguments: new QueryArguments(new MyQueryArgument<StringGraphType>().IsEmail())
```

Then in your `ValidationRule` you can check to see if the `QueryArgument` has any associated validations.

* Get the validator from metadata, match it with the actual validator.
* Get the argument value - it will either be a direct value or a variable, so you may have to pull the value out of a variable
* run the validator passing it the provided value

Some pseudo code:

```csharp
// in the ValidationRule
var argumentAst = ...  // this is an Argument from the executed query
var argument = ...  // this is a QueryArgument from the Schema
var validator = GetValidator(argument);
var value = GetValue(argumentAst, argument, context.Inputs);  // context is ValidationContext

var validationResults = validator.Validate(value);
// add any errors to ValidationContext as needed
```

**Comment by phoenixjun** [comment]
Thanks for your information on this.

**Comment by sarahannnicholson** [comment]
I'm not sure if this is correct or not. I leared a lot from @joemcbride's posts above. I kinda feel that Email makes sense as a GQL scalar? I wrote this:

```
using System;
using GraphQL.Language.AST;
using GraphQL.Types;

namespace MYAPI.GraphQL.Types.Scalars
{
    /// <summary>
    /// The Email scalar graph type represents an email string
    /// </summary>
    public class EmailGraphType : StringGraphType
    {
        public EmailGraphType()
        {
            Description = "The `Email` scalar type represents an email string ";
        }

        public override object ParseLiteral(IValue value) => value switch
        {
            NullValue _ => null,
            StringValue s => s.Value,
            _ => throw new InvalidOperationException($"Unable to convert '{value}' to the scalar type '{Name}'")
        };

        public override object ParseValue(object value) => value switch
        {
            string email => ValidateEmail(email, value), // no boxing
            StringValue s => s.Value,
            null => null,
            _ => throw new FormatException($"Could not parse email. Value: {value}")
        };

        private static object ValidateEmail(string value, object email)
        {
            if(!isValidEmail(value)) throw new FormatException($"Expected email formatting. Value: {value}");
            return email; // no boxing
        }

        private static bool isValidEmail(string email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(email);
                return addr.Address == email;
            }
            catch
            {
                return false;
            }            
        }
    }
}
```

For your `ObjectGraphType` (Query)
```
            Field<EmailGraphType>()
                .Name("Email")
                .Resolve(c => c.Source.Email);
```

For your `InputObjectGraphType` (mutation argument input type)
```
            Field<NonNullGraphType<EmailGraphType>>()
                .Name("Email")
                .Resolve(c => c.Source.Email);
```
In the Front End / Client side code:
```
mutation myNamedMutation(
        $email: Email!  #Previously was: `$email: String!`
    ) {
        myMutation(user: {
            email: $email
            # other fields
        }) {
            email
            # other fields
        }
    }
```

Related to: https://github.com/graphql-dotnet/graphql-dotnet/issues/636#issuecomment-383230982

**Comment by Shane32** [comment]
Looks pretty good.

I'd recommend inheriting from `ScalarGraphType` instead of `StringGraphType`.  The default implementation of `ScalarGraphType.CanParseValue` and `ScalarGraphType.CanParseLiteral` will then call your `ParseValue` and `ParseLiteral` methods attempting a conversion and return true/false appropriately.  However, the `StringGraphType.CanParseValue` and `StringGraphType.CanParseLiteral` will return true if it's a string without attempting a conversion to an email address. This is important for proper validation of the query before execution begins.

```cs
public class EmailGraphType : ScalarGraphType
```

It would seem that `ParseLiteral` is not validating the email address.  I'd make this change:
```cs
    public override object ParseLiteral(IValue value) => value switch
        {
            NullValue _ => null,
            StringValue s => ValidateEmail(s.Value),
            _ => throw new InvalidOperationException($"Unable to convert '{value}' to the scalar type '{Name}'")
        };
```

You also have the choice to eliminate `ParseLiteral` altogether, as the default implementation will call `ParseValue`.  Note that the default implementation of `Serialize` also calls `ParseValue`, which in this case is fine.

`StringValue` is for used only for literals, and will never be passed to `ParseValue`.  So I would remove that condition from `ParseValue`:

```cs
        public override object ParseValue(object value) => value switch
        {
            string email => ValidateEmail(email, value),
            null => null,
            _ => throw new FormatException($"Could not parse email. Value: {value}")
        };
```

Boxing doesn't apply to reference types like strings, so I'd suggest this change:
```cs
        private static string ValidateEmail(string value)
        {
            if(!isValidEmail(value)) throw new FormatException($"Expected email formatting. Value: {value}");
            return value;
        }
```

You also have the choice to use the supplied exception-generating methods rather than your own exceptions by "returning" `ThrowValueConversionError(value)`.  Either way is just fine.

So in summary, you can simplify your code to the following:
```cs
    public class EmailGraphType : ScalarGraphType
    {
        public EmailGraphType()
        {
            Description = "The `Email` scalar type represents an email string ";
        }

        public override object ParseValue(object value) => value switch
        {
            null => null,
            string email => ValidateEmail(email, value),
            _ => ThrowValueConversionError(value)
        };

        private static string ValidateEmail(string value)
        {
            if(!isValidEmail(value)) throw new FormatException($"Expected email formatting. Value: {value}");
            return value;
        }

        private static bool isValidEmail(string email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(email);
                return addr.Address == email;
            }
            catch
            {
                return false;
            }            
        }
    }
```

Please note that my comments are based on GraphQL.NET 4.x.  Be aware that custom scalar implementation has changed from version 3.x and prior.

There is much more information on custom scalars available here:
- https://graphql-dotnet.github.io/docs/getting-started/custom-scalars

**Comment by sarahannnicholson** [comment]
Thanks so much for the feedback @Shane32! These are really great changes!

I should have noted that I am using GraphQL.NET 3.x and don't have access to the `ThrowValueConversionError(value)`

I feel this thread would help anyone struggling with this in the future. 

Thanks again for the detailed response! :)

**Comment by sungam3r** [comment]
> I am using GraphQL.NET 3.x 

I strongly recommend moving on 4.* version.

**Comment by sachindwivediit** [comment]
I tried this concept for validating date argument for graphql query but how we can handle this exception .

Below is the code for validating date format
```
 public class CustomScalerType : ScalarGraphType
    {
        /// <summary>
        /// Implement a DateGraphType which handles variable parsing, literal parsing, and serialization
        /// </summary>
        public CustomScalerType()
        {
            Name = "Date";
            Description = "The `Date` scalar type represents an date string ";
        }
        public override object ParseValue(object value)
        {
            if (value is null)
                return null;

            if (ValidateDateFormat(value))
            {
                return value;
            }

            throw new FormatException($"Could not parse date. Value: {value}");
        }

        //Prepare to accept CustomScalerType inputs from query arguments. 
        public override object ParseLiteral(IValue value)
        {
            if (value is NullValue)
                return null;

            if (value is StringValue stringValue)
                return ParseValue(stringValue.Value);

            return ThrowLiteralConversionError(value);
        }

        private bool ValidateDateFormat(object date)
        {
            Regex regex = new Regex(@"^\d{4}-((0\d)|(1[012]))-(([012]\d)|3[01])$");

            //Verify whether date entered in dd/MM/yyyy format.
            bool isValid = regex.IsMatch(Convert.ToString(date));

            if (!isValid)
                return false;
            else
                return true;
        }
```


calling this customscalertype
  ```
Field<ListGraphType<PurchasePaymentType>>(
                name: "PurchasePayment",
                arguments: new QueryArguments(new List<QueryArgument>
                {
                    new QueryArgument<NonNullGraphType<ListGraphType<StringGraphType>>>{ Name = "companyIds" },
                    new QueryArgument<NonNullGraphType<**CustomScalerType**>>{ Name = "startDate" },
                    new QueryArgument<NonNullGraphType<DateGraphType>>{Name = "endDate"}
                }),
                resolve: context =>
                {
                    //Get the value of specified argument 
                    var companyIds = context.GetArgument<List<string>>("companyIds");
                    var startDate = context.GetArgument<DateTime?>("startDate");
                    var endDate = context.GetArgument<DateTime?>("endDate");
 });
```

**Comment by Shane32** [comment]
`DateGraphType` already does all that, only parsing strings in the yyyy-mm-dd format.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Scalars/DateGraphType.cs

**Comment by Shane32** [comment]
Keep in mind that the Newtonsoft JSON converter will convert strings to dates during its deserialization process unless disabled within its configuration options.  This is relevant if you are passing the date value as a variable (and using Newtonsoft).  This is handled by the built-in `DateGraphType` as it will accept a `DateTime` value within `ParseValue` in case this happens.  The very newest release of GraphQL.Net (4.5.0) includes deserialization helper methods which will disable this automatic date handling, allowing the scalar code to parse the date value from a string to a date.  Those new methods are described here:

https://graphql-dotnet.github.io/docs/guides/serialization#deserialization-of-a-graphql-request-and-variables
