### ISSUE TITLE
2.0 release timeline

### ISSUE THREAD

**Issue by mrtes** [graphql-dotnet/graphql-dotnet#708]
The due date of the respective milestone is still unspecified and the issues listed there are quite stale.
Having a stable (and recent) release would certainly help anyone trying to convince stakeholders to use GraphQL (with a .NET stack) in production.

Therefore I'm curious about the plans for this library and the final 2.0 release.
If there are issues that require help, just point me to them and I will try to help :)

**Comment by joemcbride** [comment]
The milestone is "up to date".  Those are the issues that need to be worked on.  There is one regression bug, one breaking change PR waiting changes, and most of the others are documentation.  The larger portion of the work needed is on documentation.  Once all those things are done I would be comfortable pushing an official release.

https://github.com/graphql-dotnet/graphql-dotnet/milestone/2

**Comment by mrtes** [comment]
Alright.

I'll take a look at that bug first, and try to understand the Handler/Endpoints approach. Maybe I can do something about the documentation stuff too.

Are there any contributor rules/guidelines for this repo?

**Comment by RehanSaeed** [comment]
This can be closed. 2.0 is out. There is a call for additional documentation here https://github.com/graphql-dotnet/graphql-dotnet/issues/758.
