### ISSUE TITLE
Diffrent date parses depending on query parameter passing method

### ISSUE THREAD

**Issue by stysiok** [graphql-dotnet/graphql-dotnet#713]
### Main Issue
While I was writing my GraphQL server I found different behaviors regarding data parsing. Behaviour is dependant on the how the date is passed as a query parameter.

### Reproduction steps
On the picture below you can see that I have some competitions in my DB server.  
![image](https://user-images.githubusercontent.com/15197685/41908359-f78ec8aa-7943-11e8-8986-3f5bd156acc2.png)

I added a optional query parameter to get competitions based on the date that they take place. In the field its type is DateGraphType. If I am passing value for this parameter in the query by hardcoding it in the query itself, the value after parsing will be exactly the same as the value hardcoded in the query. 
![image](https://user-images.githubusercontent.com/15197685/41908641-f8a294a0-7944-11e8-9962-cb6504c5e770.png)
![image](https://user-images.githubusercontent.com/15197685/41908705-34242e26-7945-11e8-9899-5cfa7737c1f2.png)

If I am passing the same value as a variable, the parsing date will be changed to the UTC timezone, which will cause diffrent date if you are not in the UTC timezone.
![image](https://user-images.githubusercontent.com/15197685/41908865-b86567cc-7945-11e8-9e66-07cb1a3ae4fa.png)
![image](https://user-images.githubusercontent.com/15197685/41908938-e6f29678-7945-11e8-854d-d90b23520da5.png)
As you can see, the parsed date value is diffrent then the one that has been passed as a variable. 

Is this an expected behaviour of parsing the date?

**Comment by joemcbride** [comment]
#662 Was recently merged which has done an overhaul on date types.  I believe those changes change this behavior to be more in line with what you expect.

**Comment by sungam3r** [comment]
@stysiok  Is this issue still actual? Did you manage to solve it?

**Comment by stysiok** [comment]
@sungam3r tbh I don't know. 

What I've done was introducing a new graph type for a Date. [Code](https://github.com/stysiok/NextLevelBJJ.Backend/blob/master/NextLevelBJJ.Api/GraphQLExtensions/OriginalDateGraphType.cs)

**Comment by sungam3r** [comment]
I close this issue since it is most likely solved.
