### ISSUE TITLE
Q: Filtering Pattern

### ISSUE THREAD

**Issue by espray** [graphql-dotnet/graphql-dotnet#715]
Question. Below is the example schema that has `HumanFilterType` for defining a filter. I want to convert the `HumanFilterType` into linq so I can execute it against Entity Framework.  
Someone must have solved this already. Anyone have sample code for this?

```
type Query {
  human(filter: HumanFilterType): [HumanType]
}

type HumanType {
  id: Int!
  name: String
}

type HumanFilterType {
  id: IntFilterType
  name: StringFilterType
  and: [HumanFilterType]
  or: [HumanFilterType]
}

type IntFilterType {
  eq: Int
  gt: Int
  gte: Int
  in: [Int]
  lt: Int
  lte: Int
  neq: Int
  nin: [Int]
}

type StringFilterType {
  eq: String
  gt: String
  gte: String
  in: [String]
  lt: String
  lte: String
  neq: String
  nin: [String]
}
```

**Comment by eugenpaval** [comment]
My soultion would be something similar to this:
`type Query
{
    humans(exp: String!): [HumanType]!!
}
type HumanType
{
    id: Int!
    name: String!
}`

And use System.Linq.Dynamic nuget package which allows for string expressions instead of lambda expressions as parameters.

Then a query may look like
`{
    humans(exp: "name == \"given-name\""
}`
