### ISSUE TITLE
Error in mutation code?

### ISSUE THREAD

**Issue by Perlkonig** [graphql-dotnet/graphql-dotnet#723]
In the middle of the mutation sample code, is the following line not incorrect?

`var human = context.GetArgument<Human>("human");`

Shouldn't it be:

`var human = context.GetArgument<HumanInputType>("human");`

**Comment by joemcbride** [comment]
The sample is correct. You’re mapping to a DTO, not a GraphType.  The InputGraphType represents the structure of the data only.  That code is mapping a Dictionary of values to a class structure.  The GraphType doesn’t contain those properties.

**Comment by Perlkonig** [comment]
DTO = data transfer objects? There is no `Human` object in the sample code (or anywhere else in the documentation).

My database layer is EFCore over MySQL. I pass the context into the mutator. I have a `InputObjectGraphType` that lists the fields the mutator expects. I then have the following mutator code:

```csharp
public APMutator(MyContext db)
{
    Field<UserType>(
        "createProfile",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<ProfileInputType>> {Name = "user"}
        ),
        resolve: _ => {
            var profile = _.GetArgument<????>("user");
            //do stuff with `db` to create and save objects based on `profile`
        }
    );
}
```

I can't figure out how to access the values passed in from the argument. And do I simply return the newly created database object and the library takes care of mapping that to `UserType`?

**Comment by joemcbride** [comment]
> DTO = data transfer objects

Yes.

Here is the StarWars Schema code, where the `Human` type very much exists.

https://github.com/graphql-dotnet/graphql-dotnet/blob/fbfc8c3ebe86fbeed7ca5ccb378252cb9e994ae9/src/GraphQL.StarWars/Types/StarWarsCharacter.cs#L11-L14

And in the samples:

https://github.com/graphql-dotnet/examples/blob/a62468ebd08e6241502a33a9ff3bc5d33a9ea0ae/src/StarWars/Types/StarWarsCharacter.cs#L11-L14

> I can't figure out how to access the values passed in from the argument.

`context.Arguments` is a `Dictionary<string, object>` which contains the values passed to that resolver.  Those values are calculated based on variables, inline values and default values.  Its your job to figure out how to map that `Dictionary<string, object>` to whatever format your data store requires.  Typically the easiest way to do so is a DTO, which the library provides that `GetArgument` method to use.

> And do I simply return the newly created database object and the library takes care of mapping that to UserType?

Yep, that's how it works.  Your `GraphType` represents the structure of your data.  As long as you provide the engine a class instance with the structure that it expects it will do the work for you.  That's where `IsTypeOf` kicks in, to map the DTO to a `GraphType` if the `GraphType` is an `InterfaceGraphType` or `UnionGraphType`.
