### ISSUE TITLE
ConnectionBuilder<,>.Argument<TArgumentGraphType> without constraint.

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#73]
The ConnectionBuilder<,>.Argument<TArgumentGraphType> does not have a GraphType constraint. Specifying something not a GraphType causes a cast exception which I found to be fairly hard to track back to the source - adding a constraint would be very nice - And I can't come up with a situation where it makes sense to use it with a non-GraphType type argument.

**Comment by tlil87** [comment]
:+1: Will do that with my next PR

**Comment by joemcbride** [comment]
Fixed this in the above while I was in there.  Added a type check in the `ctor` of `QueryArgument` so that should be easier to track down if someone hits it again.

**Comment by tlil87** [comment]
:+1:

**Comment by joemcbride** [comment]
Fixed with 0.7.0.
