### ISSUE TITLE
UserContext can not be injected as interface

### ISSUE THREAD

**Issue by mrtes** [graphql-dotnet/graphql-dotnet#731]
Using the Handler/Endpoints approach, lets assume I have defined the following method on my Schema class :

```csharp
public Test Test(IMyUserContext context){
   //Do some stuff
}
```
Additionally, I have registered an UserContext that implements the interface.

This will not work, because the [code](https://github.com/graphql-dotnet/graphql-dotnet/blob/cc5d15fe68563b206e713d2144e6af9217860630/src/GraphQL/Resolvers/FieldResolverBase.cs#L36) that checks the parameter type and compares it with the registered UserContext type only takes the concrete type into account.

**Comment by KreativJos** [comment]
Shouldn't the UserContext be an interface instead of an object type? The only issue I see with that is that there is no property or function which can be within that interface. But it would be better for clarity.

**Comment by SimonCropp** [comment]
@KreativJos @mrtes have a look at  https://github.com/graphql-dotnet/graphql-dotnet/pull/1474
