### ISSUE TITLE
GraphQL pass argument to parent

### ISSUE THREAD

**Issue by jannavarro** [graphql-dotnet/graphql-dotnet#739]
In GraphQL you can put an argument on any field. For example below in the height field I could put in an argument.

![image](https://user-images.githubusercontent.com/4499051/42920931-df92a5b8-8b4b-11e8-8e19-aa02dcfdc55b.png)

If I have an argument called `unit` in `HumanGraphType` how would I pass that to the parent `HumanSummaryQuery`? I don't want to put the unit as query in `human (id: 1000, unit: FOOT)` like this.

```
public class HumanSummaryQuery : ObjectGraphType
    {
        public HumanSummaryQuery()
        {
            Field<HumanGraphType>(
                name: "human",
                arguments: new QueryArguments(
                    new QueryArgument<IntGraphType>() { Name = "id" }
                    ),
                resolve: context => 
                {
                    var id = context.GetArgument<int>("id");
                    // How do I get unit from subclass??? <==================
                    var unit = context.GetArgument<string>("unit");
                    return doSomething(id, unit);
                }
            );
            
        }
    }
```
```
public class HumanGraphType : ObjectGraphType<Human>
    {
        public HumanGraphType()
        {
            Field("name", "description", resolve: t => t.Name);
            Field("height", 
            "description", 
            new QueryArguments(
                new QueryArgument<StringGraphType>() { Name = "unit" }),
            resolve: t => t.Height);
        }
    }
```

**Comment by joemcbride** [comment]
You have access to variables and the parsed `Document` + `Operation` in the `ResolveFieldContext`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/ad9c5c8523dde84dd040755a80d829b1f74ede9e/src/GraphQL/Types/ResolveFieldContext.cs#L33-L39

**Comment by jannavarro** [comment]
@joemcbride I looked at `Document` and `Operation` and I can get it there though it is more complex. I'm going to add it as variables. How do you add variables for the code I posted? This [article](https://graphql-dotnet.github.io/getting-started/#variables) doesn't declare variables. Do I need to create an `InputGraphType` and add it as field like: `Field<SomeInputGraphType>`?

**Comment by jannavarro** [comment]
Oh, saw it. I need to add it as inputs.

 ExecutionResult result = await new DocumentExecuter().ExecuteAsync(options =>
            {
                options.Schema = schema;
                options.Query = queryText;
                options.Inputs = 
            });
