### ISSUE TITLE
DateGraphType does not map when using variables

### ISSUE THREAD

**Issue by keenjus** [graphql-dotnet/graphql-dotnet#744]
# Issue
`someDate` argument is of type `DateGraphType`

```
mutation ($date: Date!) {
    test(someDate: $date)
}
```
Variables: `{ "date": "2018-08-13" }`

The `someDate` field will be null.

---

Using the string directly instead of a variable works fine:

Ex. ```test(someDate: "2018-08-13")```

## Environment
* 2.0.0-alpha-947
* .NET Core 2.1

**Comment by joemcbride** [comment]
Looks like this is indeed a bug with the new `DateGraphType`.  I've tracked it down to the GraphType not properly converting the string to a `DateTime` on serialization.

**Comment by joemcbride** [comment]
The fix is released and pushed to Nuget.  May take a bit for it to be indexed.  https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v2.0.0-alpha-951
