### ISSUE TITLE
Relay & NonNull-arguments in variables

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#75]
I have a schema with a root query of `Foo[MyEnum]`. This works fine when I make queries using GraphiQL. However, when Relay makes queries, it makes the arguments into variables and relay specifies these variables of type `MyEnum!` (non-null enum). Since I nowhere i my schema have used `NonNullGraphType<EnumType<MyEnum>>`, the schema lookup method is not able to map the string `MyEnum!` to a `GraphType`. If I manually registers this type or makes a dummy field somewhere with this type, everything is fine - but otherwise the query fails with:

```
Variable '$arg_0' expected value of type 'MyEnum!'
 at GraphQL.DocumentExecuter.GetVariableValue(ISchema schema, Variable variable, Object input) in C:\Home\projects\graphql-dotnet\src\GraphQL\Execution\DocumentExecuter.cs:line 388
```

While one could argue that Relay should not have specified a `NonNullType`, it seems that other GraphQL implementations allows this, so having relay fix the problem may not be the right solution.

I am not sure what right fix for GraphQL-dotnet is. A simple one could be to register all types with and without NonNull-type in the string-to-`GraphType`-dictionary (like what is done for simple scalar types already). An alternativ could be to make the lookup logic understand trailing `!`.

**Comment by tlil87** [comment]
I seem to remember this being the reason for one of the changes I had in earlier that i later removed as I didn't remember the reason... Duh.. Will try to address this in my next branch as well - I've got some other changes lined up as well, so can deal with this at the same time.

**Comment by joemcbride** [comment]
@MartinLorensen Can you see if [v0.9.0](https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.9.0) fixes this issue for you?

**Comment by joemcbride** [comment]
Going to go ahead and close this one.
