### ISSUE TITLE
validate enum names?

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-dotnet#750]
enum names should be `/[_A-Za-z][_0-9A-Za-z]*/`

http://facebook.github.io/graphql/June2018/#sec-Names 

should that be verified somewhere? perhaps https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/EnumerationGraphType.cs#L109

**Comment by joemcbride** [comment]
Probably a good idea.  Either there or the `AddValue` method.
