### ISSUE TITLE
Schema types not directly exposed in Query / Mutation

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#76]
I have a type which is only exposed in the schema via it's interface (in fact, the relay node interface). This means that I need to expose (register) the type in the schema in some other way. I can not seem to figure out how/when/where.

My first attempt was to call `FindType(typeof(MyGraphType))` in the constructor of my schema. This however caused part of my schema to go missing (everything added to Query/Mutation AFTER this line of the constructor) since `FindType` triggers the only-once-`GraphTypeLookup.Create`-call added as the solution to issue 67. (a way to issue an error if `Query`/`Mutation` objects are modified AFTER `GraphTypeLookup` has been created would be nice - but definitely not straight forward).

My workaround now is to just expose a dummy field of the type I would like exposed somewhere in my schema.

I guess I could ensure that extra types are added AFTER all fields have been added to the `Query/Mutation` fields - to me this sound more like a hack - but it might work (while being a bit inconvenient in my case due to some IoC-plugin-architecture).

How should I do this the right way?

**Comment by joemcbride** [comment]
I've added https://github.com/graphql-dotnet/graphql-dotnet/pull/77 with the following api:

```
public class MySchema : Schema
{
  public MySchema()
  {
    RegisterType<MyOtherType>();
    RegisterType(typeof(MyOtherType));
    RegisterTypes(new [] { typeof(MyOtherType) });
    AdditionalTypes = new [] { typeof(MyOtherType) };
  }
}
```

Think that will work for you?

**Comment by joemcbride** [comment]
This was published in [0.6.6](https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.6.6).

**Comment by MartinLorensen** [comment]
While using the new methods in our code, I noted that they are not part of the interface ISchema. I am not sure if that is intentionally or not. It was not a problem for me, but I would just mention it.

**Comment by joemcbride** [comment]
That was an oversight, thanks!
