### ISSUE TITLE
Implement Timeouts and Throttling Like GitHub GraphQL API

### ISSUE THREAD

**Issue by RehanSaeed** [graphql-dotnet/graphql-dotnet#764]
## Summary

GitHub implements timeouts and time based throttling as described [here](https://www.howtographql.com/advanced/4-security#Throttling) and [here](https://developer.github.com/v4/guides/resource-limitations/).

### Motivation

We already have maximum depth and complexity settings we can use but timeouts and throttling are other common methods of securing GraphQL from abuse, used by GitHub and others.

**Comment by SimonCropp** [comment]
shouldnt timeouts and time based throttling be the responsibility of the controller (or any web api) that is executing the graphql query? it can then propagate that cancellation through to graphql via the cancellation token

**Comment by RehanSaeed** [comment]
Yes, perhaps this issue should live in the server repo.

**Comment by RehanSaeed** [comment]
Moved to https://github.com/graphql-dotnet/server/issues/140
