### ISSUE TITLE
nuget has no icon

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-dotnet#771]
Want a PR?

**Comment by joemcbride** [comment]
Yep I’ll take one.

**Comment by KoditkarVedant** [comment]
@joemcbride which icon we have planned to set for NuGet package? Is it a plain GraphQL icon or should we have a hybrid of .Net and GraphQL.

**Comment by KoditkarVedant** [comment]
![image](https://user-images.githubusercontent.com/18693839/44959565-54afa400-af0e-11e8-80ba-8891e4761300.png)
@joemcbride I see we already have icon URL in GraphQL.csproj file. So I think we should close this. what are your thoughts?
