### ISSUE TITLE
I get a 401 when using apollo to call my GraphQL API

### ISSUE THREAD

**Issue by RaySheikh** [graphql-dotnet/graphql-dotnet#772]
Hi, I get a 401 error when running a query to my graphql end point. Has anyone ran into this issue? My front end works with one of the mock web GraphQL server. Anyone know what i may be doing wrong?

Thanks in advance.

```
 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
            app.UseCors(builder =>
                builder.AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials());

            app.UseHttpsRedirection();
            app.UseGraphiql("/graphiql", options =>
            {
                options.GraphQlEndpoint = "/GraphQL"; //Point to the controller
            });
            app.UseMvc();
        }
```

**Comment by joemcbride** [comment]
What does your controller look like?  Did you add an Authorize attribute to it?  Did you add a a setting to require Auth on all controllers?

**Comment by RaySheikh** [comment]
Hi joe, I did not add an authorize attribute. below is my controller.

      `[Route("[controller]")]
    public class GraphQLController : Controller
    {
        private IDocumentExecuter _documentExecuter { get; set; }
        private ISchema _schema { get; set; }
        private readonly ILogger _logger;

        public GraphQLController(ISchema schema, IDocumentExecuter documentExecuter, ILogger<GraphQLController> logger)
        {
            _schema = schema;
            _documentExecuter = documentExecuter;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            _logger.LogInformation("Got request for GraphiQL. Sending GUI back");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
        {
            if (query == null) { throw new ArgumentNullException(nameof(query)); }

            var inputs = query.Variables.ToInputs();
            var executionOptions = new ExecutionOptions
            {
                Schema = _schema,
                Query = query.Query,
                Inputs = inputs
            };

            var result = await _documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);

            if (result.Errors?.Count > 0)
            {
                _logger.LogError("GraphQL errors: {0}", result.Errors);
                return BadRequest(result);
            }
            _logger.LogDebug("GraphQL execution result: {result}", JsonConvert.SerializeObject(result.Data));
            return Ok(result);
        }
    }`

**Comment by joemcbride** [comment]
Have you tried hitting your endpoint manually in the browser or that GraphiQL middleware?  Do you get the same 401?

What does your `ConfigureServices(IServiceCollection services)` look like?  Are you adding any authorization middleware?  Authorization filters for MVC?

Something like this would require auth on all controllers.

```

services.AddMvc(options =>
{
  var policy = new AuthorizationPolicyBuilder()
    .RequireAuthenticatedUser()
    .Build();

  options.Filters.Add(new AuthorizeFilter(policy));
});
```

You could also try adding the `[AllowAnonymous]` attribute.

Other than that, I'm out of ideas.

**Comment by RaySheikh** [comment]
Hi Joe, Everything works perfectly with GraphiQL interface. I'm using EFcore and all of the queries/mutations work on GraphiQL. Only issue is the 401 when using Apollo. I know the client works with other mockup GraphQL endpoints.
below is my startup.cs. Thank you again for your help on this.

    `public class Startup
    {
        private readonly string _EnvUrl;
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
            _EnvUrl = Configuration["EnvUrls:CurrentUrl"];
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            string appapprovalconn = Configuration.GetConnectionString("AppApprovalConn");
            services.AddDbContext<AppApprovalContext>(options => options.UseSqlServer(appapprovalconn, opt => opt.EnableRetryOnFailure()));

            //DI
            services.AddScoped<AppApprovalSchema>();
            services.AddScoped<AppApprovalQuery>();
            services.AddScoped<AppApprovalMutation>();

            services.AddScoped<UserType>();
            services.AddScoped<RoleType>();
            services.AddScoped<ApprovalChainType>();
            services.AddScoped<V_AppApprovalChainApproverCountType>();
            services.AddScoped<V_AppApprovalRecordFullType>();
            services.AddScoped<V_ApplicationApprovalChainType>();
            services.AddScoped<V_AppApprovalRecordHistoricalType>();
            services.AddScoped<V_WestDivEmployeesType>();
            services.AddScoped<ApplicationCostType>();

            services.AddScoped<ApprovalChainInputType>();
            services.AddScoped<V_AppApprovalRecordFullInputType>();
            services.AddScoped<UserInputType>();
            services.AddScoped<RoleInputType>();
            services.AddScoped<ApprovalRecordInputType>();
            services.AddScoped<ApplicationCostInputType>();


            services.AddScoped<IAppApprovalRepository, AppApprovalRepository>();

            services.AddScoped<IDocumentExecuter, DocumentExecuter>();
            var sp = services.BuildServiceProvider();
            services.AddSingleton<ISchema>(new AppApprovalSchema(new FuncDependencyResolver(type => sp.GetService(type))));


            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
            app.UseCors(builder =>
                builder.AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials());

            app.UseHttpsRedirection();
            app.UseGraphiql("/graphiql", options =>
            {
                options.GraphQlEndpoint = "/GraphQL"; //Point to the controller
            });
            app.UseMvc();
        }
    }`

**Comment by joemcbride** [comment]
Not much I can do to help since it appears this isn’t an issue with this project.  My last suggestion is to look at the http request in the browser to make sure it is going to your server and to the correct endpoint.

**Comment by RaySheikh** [comment]
Joe, 
I figured it out, It was something very minor and I feel stupid not catching it. Taking a break from programming for a couple of days helped a lot. 
Reading some of your responses let me to check the Debug settings in the project properties and checking "Enable Anonymous Authentication" fixed the issue.
Thank you again for your help. If anyone needs help building an API with EFcore using your repository layer please feel free to hit me up. I have queries and mutations working and i'm working on the subscriptions next.
Thanks again Joe!!
![image](https://user-images.githubusercontent.com/35114618/44041759-66a4fc00-9ed3-11e8-92fc-95c262156e53.png)
