### ISSUE TITLE
Add documentation for ThrowOnUnhandledException

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#777]
Add info about `ExecutionOptions.ThrowOnUnhandledException` to https://graphql-dotnet.github.io/docs/getting-started/errors

**Comment by sungam3r** [comment]
@Shane32 you said you were working on documentation and migration guide. Could you help with this?

**Comment by Shane32** [comment]
Yup thanks

**Comment by cameverett** [comment]
Hey everyone - I realize I have jumped the gun on opening up a pull request for this one seeing as it was previously assigned.

I am more than happy to close the pull request and first express interest If this issue is active and up for grabs.

**Comment by Shane32** [comment]
It’s no problem. I’m actually more working on the migration documentation and anything you have to offer I can also integrate into the migration documentation where applicable.

**Comment by sungam3r** [comment]
@joemcbride Could you please regenerate docs site? I could not install/configure the necessary tools.

**Comment by sungam3r** [comment]
We still need to regenerate docs site.
