### ISSUE TITLE
Is it time to drop 4.5 and netstandard1.3  support?

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-dotnet#782]
we current use System.Reactive.Core Version 3.1.1.

But version 4 only support net4.6 and netstandard2.0

This is the first blocker, but i suspect other dependencies will soon follow with dropping older framework support

net net4.6  was released in 2015-07-20, and  netstandard2.0 was released 2017-08-14, so i think that is reasonable.

thoughts?

**Comment by joemcbride** [comment]
I think that would be fine for a 3.0 release.

**Comment by RehanSaeed** [comment]
4.5 is not supported by Microsoft. The minimum bar for them is 4.5.2 or 4.6.1 and above.

**Comment by pingvinen** [comment]
As a user, I can say that the company I work in use this in the context of dotnet Core 2.x only. So for me it makes sense :)
