### ISSUE TITLE
Support for NodaTime

### ISSUE THREAD

**Issue by shoooe** [graphql-dotnet/graphql-dotnet#787]
## Summary

Support NodaTime types conversions to the corresponding scalar values (at least major ones like `LocalDate`, `LocalTime`, `Instant`).

Alternatively supporting type converters (for example from a custom type to `DateTimeGraphType`), which I feel already exists but I can't find in the documentation or issues.

### Basic example

And example of this would be:

```c#
Field("createdAt", 
    x => x.CreatedAt, 
    type: typeof(NonNullGraphType<DateTimeGraphType>));
```

where `x.CreatedAt` would be of type `NodaTime.Instant`.

### Motivation

NodaTime [has been an integral part of C#](https://codeblog.jonskeet.uk/2009/11/06/noda-time-is-born/) for quite sometimes. In the C# community it is considered the de-facto replacement for the shortcomings of `DateTime` and `DateTimeOffset`.

Integrations with Entity Framework (for example in Npgsql) have been added in recent years. Supporting these types like default system types would be a good addendum to an already good library 😄.

**Comment by Jefffrey** [comment]
@SimonCropp This month I won't have time to take a look at this, but if there's anybody else that care about it I might work on a PR.

**Comment by kenrim626** [comment]
The idea of NodaTime integration is great, but wouldn't it make sense to make a separate, optional package for it? I mean, not everyone needs NodaTime.

**Comment by Jefffrey** [comment]
@kenrim626 Maybe a more appropriate way would be to allow for user defined conversions to be defined in this library and then, yes, create a specific NodaTime package for the integration.

**Comment by joemcbride** [comment]
> allow for user defined conversions to be defined

It is currently possible to create your own scalars, it is just not well documented.  You should be able to create a NodaTime package as an add-on without further changes to this library.

Take a look at [`GraphTypeTypeRegistry`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/GraphTypeTypeRegistry.cs), which is where you can override or add the default scalar GraphType for a specific .NET type.

[`ValueConverter`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/ValueConverter.cs) for any value conversions.

This is where the conversion to an `IValue` happens for scalars.  If one of those does not work for your scalar GraphType, then you can register your own with the Schema.

https://github.com/graphql-dotnet/graphql-dotnet/blob/d90a1a4daa80dff4844c3e361b12366d25199fac/src/GraphQL/Types/Schema.cs#L46

https://github.com/graphql-dotnet/graphql-dotnet/blob/d90a1a4daa80dff4844c3e361b12366d25199fac/src/GraphQL/GraphQLExtensions.cs#L372-L441

**Comment by Jefffrey** [comment]
In the first case is it possible to add a converstion from, for example, `LocalDate` to `DateGraphType` without changing the library code (via a pull request or local edit)?

**Comment by joemcbride** [comment]
You won't be using `DateGraphType` since it doesn't know how to work with a `LocalDate` (I'm assuming that is a NodaTime Type).  You will need to write your own custom scalars to work with the NodaTime Types.

Here's an example of a custom scalar for `LocalDate`:

```csharp
public class LocalDateValue : ValueNode<LocalDate>
{
    public LocalDateValue(LocalDate value)
    {
        Value = value;
    }

    protected override bool Equals(ValueNode<LocalDate> other)
    {
        return Value == other.Value;
    }
}

public class LocalDateValueConverter : IAstFromValueConverter
{
    public bool Matches(object value, IGraphType type)
    {
        return value is LocalDate;
    }

    public IValue Convert(object value, IGraphType type)
    {
        return new LocalDateValue((LocalDate)value);
    }
}

public class NodaLocalDateGraphType : ScalarGraphType
{
    public StringGraphType()
    {
        Name = "LocalDate";
    }

    public override object Serialize(object value)
    {
        return ParseValue(value);
    }

    public override object ParseValue(object value)
    {
        return ValueConverter.ConvertTo<LocalDate>(value);
    }

    public override object ParseLiteral(IValue value)
    {
        var localDate = value as LocalDateValue;
        return localDate?.Value;
    }
}

// set default GraphType for LocalDate, so you can use Field(x => x.MyLocalDate) syntax
GraphTypeTypeRegistry.Register(typeof(LocalDate), typeof(NodaLocalDateGraphType));

ValueConverter.Register(typeof(DateTime), typeof(LocalDate), value =>
{
    // however you convert a DateTime to a LocalDate
    return ConvertToLocalDate(value);
});
ValueConverter.Register(typeof(string), typeof(LocalDate), value =>
{
    // however you convert a string to a LocalDate
    return ConvertToLocalDate(value);
});
ValueConverter.Register(typeof(DateTimeOffset), typeof(LocalDate), value =>
{
    // however you convert a DateTimeOffset to a LocalDate
    return ConvertToLocalDate(value);
});


// register your GraphType and ValueConverter with your schema
schema.RegisterType<NodaLocalDateGraphType>();
schema.RegisterValueConverter(new LocalDateValueConverter());
```

**Comment by joemcbride** [comment]
Usage of `NodaLocalDateGraphType` would look like:

```csharp
public class MyObject
{
    public LocalDate MyLocalDate { get; set; }
}

public class MyGraphType : ObjectGraphType<MyObject>
{
  public MyGraphType()
  {
    Field(x => x.MyLocalDate);
    Field<NodaLocalDateGraphType>("myLocalDate", resolve: context =>
    {
        var source = context.Source as MyObject;
        return source.MyLocalDate;
    });
  }
}
```

**Comment by Jefffrey** [comment]
What's `GraphTypeTypeRegistry` and `ValueConverter`? Where can I read the docs about making a custom scalar type? Why wouldn't a class inheriting from `ScalarGraphType` be enough to map `LocalDateGraphType` to `LocalDate`?

**Comment by joemcbride** [comment]
@Jefffrey the reasons are related to the GraphQL Specification.  There is a limited set of scalar values defined in the specification and those scalar values are defined and used in a certain fashion.  

https://facebook.github.io/graphql/June2018/#sec-Appendix-Grammar-Summary.Lexical-Tokens

If you want to augment the specification, then you need to provide the pieces that this engine requires.  This engine requires the following pieces:

1. A custom value ast (abstract syntax tree) type (`ValueNode<T>`)
2. A custom scalar graph type that knows how to work with the new custom value ast type (`ScalarGraphType`)
3. A `IAstFromValueConverter` to convert between your custom type (`LocalDate` in this instance) to the custom value ast type
4. (optional) Using `ValueConverter` is optional, though you may want to provide a way to automatically convert one value type to another (such as converting a `DateTime` to a `LocalDate`).

1 and 3 (`ValueNode<T>` and a `IAstFromValueConverter`) can be optional.  For instance, you can create your own scalar type without those items, though you would have to work with the built-in `ValueNode`'s, which are those defined in the spec:

IntValue
FloatValue
StringValue
BooleanValue
NullValue

There is no other documentation for writing a custom scalar type.  The posts in this issue are presently the only docs available.

**Comment by Jefffrey** [comment]
So what would be the simplest example (with only the 2nd step) for a custom `LocalTime` scalar value assuming a local time value is passed in as a JSON string to GraphQL (ex. "2018-05-24")?

**Comment by joemcbride** [comment]
Assuming you're serializing the JSON with JSON.NET where it would convert `2018-05-24` to a `DateTime` first, if you want to use Noda's `LocalDate` instead, you don't have a simplified option.  You need 1-4.  If you are somehow serializing the JSON to a `LocalDate` directly, you still need 1-3.

**Comment by Jefffrey** [comment]
I'm not doing any serialization manually. I think `StringValue` would be fine.

**Comment by joemcbride** [comment]
Using `StringValue` will work fine if you want to work with `string` types, with your POCO model looking something like this:

```csharp
public class MyInput
{
    public string Date { get; set; }
}
```

If it doesn't look like that, and you want to use `LocalDate` (which I assume you do since that is what this issue is), you need 1-4.

```csharp
public class MyInput
{
    public LocalDate Date { get; set; }
}
```

Scalars are designed to be used for both Input and Output values.  I encourage you to put that code in your project and try it out to see how it works.

**Comment by Jefffrey** [comment]
I tried to define this:

```

using System;
using GraphQL.Language.AST;
using GraphQL.Types;
using NodaTime.Text;

namespace Server.GraphQL.Scalars
{
    public class LocalDateType : ScalarGraphType
    {
        public LocalDateType()
        {
            this.Name = "LocalDate";
            this.Description = "";
        }

        public override object Serialize(object value)
        {
            return this.ParseValue(value);
        }

        public override object ParseValue(object value)
        {
            try
            {
                return LocalDatePattern.Iso.Parse(value as string).GetValueOrThrow();
            } 
            catch (Exception) { return null; }
        }

        public override object ParseLiteral(IValue value)
        {
            var stringVal = value as StringValue;
            return stringVal?.Value;
        }
    }
}
```

and then I registered it with:

            // Custom scalars
            services.AddScoped<LocalDateType>();

in my Startup class.

If I try to use it as input I get:

> GraphQL.ExecutionError: Variable '$at' is invalid. Invalid Scalar value for input field. ---> GraphQL.Execution.InvalidValueException: Variable '$at' is invalid. Invalid Scalar value for input field.↵   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)

**Comment by shoooe** [comment]
I'm sorry, but I'm yet again unable to create my own custom scalar types and the whole interface is extremely confusing. The lack of documentation also doesn't help. I've looked at the comments above, tests and other related material online and I still don't understand how this whole thing works.

It also seems that in a recent update to the library ISO strings (for instants) are parsed as `DateTime`s. 

Apparently returning an ISO string from `Serialize` also somehow triggers a conversion to `DateTime` which results in something like:
```
{
    "field": {}
}
```

where `field` is of type `Instant` (my custom `Instant` type).

I'm sorry if I sound whiny but I've been working on this for days and I'm extremely frustrated. I'm sure the interface was designed this way for a reason, I just can't grasp it.

Given that I know how to convert:
 - `DateTime` to `Instant`
 - `string` to `Instant`
 - `Instant` to `DateTime`
 - `Instant` to `string`

Can you explain like I'm 5 how I can implement a custom scalar that works both for reading and writing (considering also that certain strings are ISO formatted and others aren't)?

**Comment by shoooe** [comment]
I've tried this:

```
    public class SchemaType : GraphQL.Types.Schema
    {
        public SchemaType(IDependencyResolver resolver)
            : base(resolver)
        {
            Query = resolver.Resolve<QueryType>();
            Mutation = resolver.Resolve<MutationType>();

            ConfigureInstant();
        }

        private void ConfigureInstant()
        {
            GraphTypeTypeRegistry.Register(typeof(Instant), typeof(InstantType));
            ValueConverter.Register(typeof(DateTime), typeof(Instant), value =>
            {
                var dateTime = (value as DateTime?).Value;
                return Instant.FromDateTimeUtc(dateTime);
            });
            ValueConverter.Register(typeof(string), typeof(Instant), value =>
            {
                var str = value as String;
                return InstantPattern.ExtendedIso.Parse(str).Value;
            });
            ValueConverter.Register(typeof(DateTimeOffset), typeof(Instant), value =>
            {
                var dateTimeOffset = (value as DateTimeOffset?).Value;
                return Instant.FromDateTimeOffset(dateTimeOffset);
            });
            this.RegisterType<InstantType>();
            this.RegisterValueConverter(new InstantValueConverter());
        }
  }
```

with this:

```
    public class InstantValue : ValueNode<Instant>
    {
        public InstantValue(Instant value)
        {
            Value = value;
        }

        protected override bool Equals(ValueNode<Instant> other)
        {
            return Value == other.Value;
        }
    }

    public class InstantValueConverter : IAstFromValueConverter
    {
        public bool Matches(object value, IGraphType type)
        {
            return value is Instant;
        }

        public IValue Convert(object value, IGraphType type)
        {
            return new InstantValue((Instant)value);
        }
    }

    public class InstantType : ScalarGraphType
    {
        public InstantType()
        {
            Name = "Instant";
        }

        public override object Serialize(object value)
        {
            return ParseValue(value);
        }

        public override object ParseValue(object value)
        {
            return ValueConverter.ConvertTo<Instant>(value);
        }

        public override object ParseLiteral(IValue value)
        {
            var Instant = value as InstantValue;
            return Instant?.Value;
        }
    }
```

and this in `Startup`:

```
            services.AddSingleton<InstantType>();
```

just like any other type.
And I repeated something similar for `LocalDate`.

And in my JSON I get:

```
date: {calendar: {…}, year: 2019, month: 2, day: 18, dayOfWeek: 1, …}
```

where `date` is supposed to be of GraphQL type `LocalDate`.

**Comment by shoooe** [comment]
For those wondering [here](https://gist.github.com/shoooe/437c34773e05cf8a8f4ffbf692b3d9c8) you can find 4 examples (`Instant`, `IsoDayOfWeek`, `LocalDate`, `LocalTime`) of the `ScalarGraphType` definitions that I've tested as of today.

**Comment by SimonCropp** [comment]
Have u considered wrapping it up in a nuget?

**Comment by shoooe** [comment]
@SimonCropp I'm writing it now, but I'm dubious as to how to hook these scalar types up without having the user add them manually:

```
services.Singleton<InstantGraphType>();
services.Singleton<LocalDateGraphType>();
...
```

**Comment by joemcbride** [comment]
@shoooe They don't technically need to be in your container at all since they have no dependencies, so you could leave that up to the user.  You can manually register them with the schema like so:

```csharp
schema.RegisterTypes(new []{ typeof(InstantGraphType), typeof(LocalDateGraphType) });
```

Though that should also not be needed if the types are in your public schema.  I see you didn't create any new Value nodes and converters.  You if you had those, you could register those with the schema too with an extension method like this:

```csharp
public static class NodaTimeSchemaExtensions
{
  public static ISchema UseNodaTime(this ISchema schema)
  {
    schema.RegisterTypes(new []{ typeof(InstantGraphType), typeof(LocalDateGraphType) });
    // other value stuff
    return schema;
  }
}

schema.UseNodaTime();
```

**Comment by shoooe** [comment]
I'll work on it at: https://github.com/shoooe/graphql-nodatime.
The current 0.0.1 version just contains the above 4 types. I'll likely expand on those in the following weeks.

Contributions are welcomed.
Thanks everybody.
