### ISSUE TITLE
Difference between approaches 

### ISSUE THREAD

**Issue by IT786** [graphql-dotnet/graphql-dotnet#788]
Hi,
I have found three different approaches when using GraphQL with Asp.Net Core.
1)  services.AddGraphQL(
No controller or middleware
2) using middleware
3) Controller, mostly in Asp.Net web API 2

Is this possible to use controller base approach in Core API? If there is any help please let me know.
When to use controller base approach and when to use middleware based approach.
Any help will be highly appreciated

**Comment by joemcbride** [comment]
Option 1. is not a different approach.  That is just registering services for middleware or a controller to use.

Yes you can use the Controller approach in ASP.NET Core.  The code would be nearly identical from what you would use in ASP.NET Web Api.

https://stackoverflow.com/questions/45568380/what-is-the-asp-net-core-equivalent-to-httprequestmessage

```csharp
public class GraphQLController : Controller
{
    private readonly ISchema _schema;
    private readonly IDocumentExecuter _executer;
    private readonly IDocumentWriter _writer;
    private readonly IHttpContextAccessor _accessor;

    public GraphQLController(
        IDocumentExecuter executer,
        IDocumentWriter writer,
        ISchema schema,
        IHttpContextAccessor accessor)
    {
        _executer = executer;
        _writer = writer;
        _schema = schema;
        _accessor = accessor;
    }

    [HttpPost]
    public async Task<IActionResult> PostAsync([FromBody]GraphQLQuery query)
    {
        var inputs = query.Variables.ToInputs();
        var queryToExecute = query.Query;

        var result = await _executer.ExecuteAsync(_ =>
        {
            _.Schema = _schema;
            _.Query = queryToExecute;
            _.OperationName = query.OperationName;
            _.Inputs = inputs;

            _.ComplexityConfiguration = new ComplexityConfiguration { MaxDepth = 15 };
            _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();

        }).ConfigureAwait(false);

        var httpResult = result.Errors?.Count > 0
            ? HttpStatusCode.BadRequest
            : HttpStatusCode.OK;

        var json = _writer.Write(result);
        return new Content(json, "application/json");
    }
}

public class GraphQLQuery
{
    public string OperationName { get; set; }
    public string Query { get; set; }
    public Newtonsoft.Json.Linq.JObject Variables { get; set; }
}
```

**Comment by ddecours** [comment]
Hi Joe -  thanks for the fantastic work!!   Any thoughts on when it could be better to use graphql middleware technique vs. using an mvc controller?    The code is very similar, but it's not obvious to me which technique is best.   Maybe have both in place and allow a hook to "pre-process" the request prior to handoff to the controller?

I realize the implementation depends on the business need, so really just looking for general input.

Much appreciated!

**Comment by f2002642** [comment]
Hi Joe
i am a novice to GraphQL.
In case of using 3rd approach (controller), i always see that constructor injection is failing for Types.
Everything works as expected if i chose first approach.
Any pointers will help me in understanding nuances better.
