### ISSUE TITLE
Mutation input string field containing different value types

### ISSUE THREAD

**Issue by OvidijusStukas** [graphql-dotnet/graphql-dotnet#791]
## Description

Currently I have GraphQL input type:
**DocumentAttributeInputType** which have field **Value** is defined to be a string.

```
public class DocumentAttributeModel
{
	public string Value { get; set; }
}

public class DocumentAttributeInputType : InputObjectGraphType<DocumentAttributeModel>
{
	public DocumentAttributeInputType()
	{
		Name = nameof(DocumentAttributeInputType);
		
		Field(x => x.Value);
	}
}
```

Later I send a mutation request with field containing a JS ISO string.

`value: "2018-08-01T00:00:00.000Z"`

In context resolver the value is set to NULL.

### Expected result

I would expect a simple string which was sent from client app not a NULL value.

### Additional info

I found a similiar [issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/271) but it was resolved as fixed but in current version it is broken or the specification was changed. 

While debugging GraphQL types I noticed that this field auto resolves to **StringGraphType** and that **ParseLiteral** procedure receives not a **StringValue** as expected by this type but **DateTimeValue** and auto cast **as** fails and returns NULL for value.

![image](https://user-images.githubusercontent.com/9720553/44335568-8db33780-a47d-11e8-9ab5-8df1647c2455.png)

Currently I workaround by creating a new graphql type **HackType** which expects both types and acts accordingly.

### Environment
I'm using GraphQL-net 2.0 with Asp.Core 2.1.2 framework.

**Comment by thegaydude69h0mo** [comment]
Do not listen to him, he's gay. He does not know what he is talking about. homo homo asdsaifasjfaofjaf

**Comment by andyce1010** [comment]
This is still occurring in graphql-dotnet 2.4.0

**Comment by andyce1010** [comment]
Actually, I figured out I was seeing this issue because I was manually deserializing the graphql query using json.net with the default settings. Changing the json.net serializer settings to have DateParseHandling = DateParseHandling.None fixed the issue for me.

**Comment by sungam3r** [comment]
@OvidijusStukas Is this issue still actual for you? Could you try the latest preview graphql packages?

**Comment by OvidijusStukas** [comment]
I do not use this library anymore, thanks for the concern I will close the issue.
