### ISSUE TITLE
UnionGraphType doesn't support ScalarGraphType

### ISSUE THREAD

**Issue by MNie** [graphql-dotnet/graphql-dotnet#797]
## Description

I want to create a UnionGraphType which would simulate a situation when I would get a BooleanGraphType or some CustomGraphType (inherited from ObjectGraphType).

### Steps to reproduce

create a UnionGraphType like:

```csharp
public class BoolOrCustomType : UnionGraphType
{
    public BoolOrCustomType()
    {
        Type<CustomType>();
        Type<BooleanGraphType>();
    }
}

public class CustomType : ObjectGraphType<Custom>
{
    public CustomType()
    {
        Name = "Custom";
        Field<NonNullGraphType<StringGraphType>>("a", resolve: ctx => ctx.Source.A);
        Field<NonNullGraphType<IntGraphType>>("b", resolve: ctx => ctx.Source.B);
    }
}

public class Custom
{
    public readonly string A;
    public readonly int B;
    
    public Custom(string a, int b)
    {
        A = a;
        B = b;
    }
}

```

### Expected result

Compile && ability to ask for data like that:

```graphql
{
    boolOrCustom {
        ... on Bool
        ... on Custom {
            a
            b
        }
    }
}
``` 

### Actual result

Right now there is no possibility to write code like that, mainly because UnionGraphType inherits from an `IAbstractGraphType` so changing the constraints from `IObjectGraphType` to something else would be a breaking change. Also the question is is it possible/correct (in GraphQL) to ask for a value like that (if not I think we could close this issue):

```graphql
{
    boolOrCustom {
        ... on Bool
    }
}
``` 

CC: @joemcbride

**Comment by MNie** [comment]
@joemcbride up

**Comment by joemcbride** [comment]
Taking a look at the spec:

http://facebook.github.io/graphql/June2018/#sec-Unions

> GraphQL Unions represent an object that could be one of a list of GraphQL Object types, but provides for no guaranteed fields between those types.

I read this as only Object GraphTypes are allowed.

**Comment by MNie** [comment]
@joemcbride what a shame, cause syntax when ScalarTypes would be allowed looks neat. Closing this one, thanks!
