### ISSUE TITLE
How to unit test this API?

### ISSUE THREAD

**Issue by VladimirAkopyan** [graphql-dotnet/graphql-dotnet#800]
I have written an API using this great library, and it's working well. 
I am wondering how do you test it. Ordinary in REST APIs i usually setup tests against the controller, and
directly invoke the methods used in POST/GET/Etc. I am trying to figure out how would I do the equivalent here. 

I am using GraphType First and defining my queries and Mutations as such: 
```
public StarWarsQuery()
  {
    Field<DroidType>(
      "droid",
      arguments: new QueryArguments(
        new QueryArgument<IdGraphType> { Name = "id" }
      ),
      resolve: context =>
      {
        var id = context.GetArgument<string>("id");
        return _droids.FirstOrDefault(x => x.Id == id);
      }
    );
  }
```
I can setup a unit test against the resolver, but how do I unit test against the Field taht's being created here?

**Comment by RehanSaeed** [comment]
I've been running integration tests using the `Microsoft.AspNetCore.Mvc.Testing` package. See [docs](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1). You can run normal HTTP requests by passing in the GraphQL query in your request body.

As for lower level unit tests of individual graph types, I'd be interested in learning a way to do that too.

**Comment by jquense** [comment]
Assuming you've got most of the logic behind the resolvers in a layer that's unit testable, my favorite approach to testing gql apis in general is to stand up the server, mock out the layer right below it and do something like a snapshot test against queries that exercise the API surface area

**Comment by joemcbride** [comment]
This sample Harness test project also uses Alba for doing HTTP request testing similar to `Microsoft.AspNetCore.Mvc.Testing`.  So you have a number of choices.

https://github.com/graphql-dotnet/graphql-dotnet/blob/83e1ee320e20581cb98e076ca91d89524b549370/src/GraphQL.Harness.Tests/BasicTests.cs#L8-L24

**Comment by VladimirAkopyan** [comment]
Thanks a lot for the feedback. Converting GraphQL request to JSON works fine, and I am using  `Microsoft.AspNetCore.Mvc.Testing`. 

I found that I wanted to replace HTTPClient used in `GraphQLHttpHandler` to the one produced by the testing framework, and use the full GraphQLClient class. 
Currently `GraphQLHttpHandler` class is marked as internal.  I think I should be able to replace it through reflection. 

Do you recon we could have a helper class or provide HTTPclient in constructor it to make testing nice and easy? Or am I doing something silly?

**Comment by deinok** [comment]
@VladimirAkopyan use the GraphQLClient v2 and `server.CreateHttpHandler()` or the `AsGraphQLClient()` extension method

**Comment by VladimirAkopyan** [comment]
Thank you deinok, i am not sure how I missed that.

**Comment by deinok** [comment]
@VladimirAkopyan Not your fault, I should document how make the tests

**Comment by WellspringCS** [comment]
> var input = new GraphQLRequest 
>              { 
>                  Query = @"{ hero { name} }" 
>              };

Joe, thank you again for this awesome tool and the example code for testing. Don't know if this will prove helpful for the next guy, but I can add a thought and then ask a question.

The thought is this: I lost about 6 hours yesterday with this error message

```
GraphQL.ExecutionError: A query is required
```
I finally solved it after changing class GraphQLRequest to have the Query property be lower case 'query'

Such is life, sometimes.

My question is this -- any pointers on how I could have figured this out by means other than losing teeth banging my head against a brick wall?

Right now it seems there is this black-box zone between when the pipeline receives the request and the point at which my query class of type ObjectGraphType receives the request and starts processing it. The only way for me to figure out (with my noob background) was to put this line in a some middleware early in the pipeline...

```
string bodyContent = new StreamReader(context.Request.Body).ReadToEnd();
```
and literally examine the body, looking for differences. I noted this difference...

successful Rest Client (VSCode) call:

```
"{\"query\":\"query a {\\n\\tmyUser {\\n\\t\\t\\tlastName\\n\\t\\t\\tfirstName\\n\\t\\t\\temail\\n\\t\\t}\\n}\",\"variables\":{}}"
```

vs this failure (using Alba):

```
"{\"OperationName\":null,\"Query\":\"{\\r\\n\\t\\t\\t\\t\\t\\t\\tmyUser {\\r\\n\\t\\t\\t\\t\\t\\t\\t\\tlastName\\r\\n\\t\\t\\t\\t\\t\\t\\t\\tfirstName\\r\\n\\t\\t\\t\\t\\t\\t\\t\\temail\\r\\n\\t\\t\\t\\t\\t\\t\\t}\\r\\n\\t\\t\\t\\t\\t}\",\"Variables\":null}"
```

And thought hmmmm I wonder what would happen if I changed that Query to be lower case.

Sorry for long-winded, but any guidance appreciated. I'd love to be more able to troubleshoot my GraphQL queries...

**Comment by sungam3r** [comment]
What exactly do you propose to do?

I see you use `GraphQL.Server.Transports.AspNetCore.SystemTextJson` so I guess you can call
```c#
.AddSystemTextJson(deserializerSettings => { deserializerSettings.PropertyNameCaseInsensitive = true; }, serializerSettings => { })
```

**Comment by WellspringCS** [comment]
You give me way too much credit, and please understand I wasn't proposing anything. I was, as a noob, asking for any short words of guidance as to how I can better analyze queries and figure out why GraphQL doesn't like them.

Full disclosure -- not sure where I would use that line of code you posted. :flushed: So, for instance, where would I have put that line.

Not asking for lots of advice, more of a request for where I should go do my homework so that I can get better at this.

**Comment by sungam3r** [comment]
>  how I can better analyze queries and figure out why GraphQL doesn't like them.

You can always use general purpose http request tracing.

>  how I can better analyze queries and figure out why GraphQL doesn't like them.

In your startup after call to `.AddGraphQL`: https://github.com/graphql-dotnet/server#configure

**Comment by WellspringCS** [comment]
Thx much @sungam3r  I've given your suggestions a whirl, and I think the takeaway is for me to learn "a query is required" means... wait for it... it couldn't find a query.

After adding an UnhandledExceptionDelegate i was able to trap the error in flight, but it still just reported that "a query is required". So maybe general purpose http request tracing is the way to go, since a custom UnhandledExceptionDelegate doesn't seem to give me the body of the request that failed.

I also now see where your suggestion on modifying AddSystemTextJson would go. But now that I know what to look for, I think I'll leave things as they are and avoid "Query vs query" errors going forward.

thx
