### ISSUE TITLE
Using GraphQLAbstractType as schema objects

### ISSUE THREAD

**Issue by aaerox** [graphql-dotnet/graphql-dotnet#81]
Hello,

I've implemented a graphql object in the following way -

`class DynamicTemplateType : GraphQLAbstractType`

This seems to work well for most purposes, and returns a dynamically resolved type through the use of the `GetObjectType` method on `GraphQLAbstractType`. I encounter a problem when using introspection however, as the `__Type` object is unable to resolve it's `TypeKind`. The code which determines this is as follows:

```
public TypeKind KindForInstance(GraphType type)
{
	if (type is EnumerationGraphType)
	{
		return TypeKind.ENUM;
	}
	if (type is ScalarGraphType)
	{
		return TypeKind.SCALAR;
	}
	if (type is ObjectGraphType)
	{
		return TypeKind.OBJECT;
	}
	if (type is InterfaceGraphType)
	{
		return TypeKind.INTERFACE;
	}
	if (type is UnionGraphType)
	{
		return TypeKind.UNION;
	}
	if (type is InputObjectGraphType)
	{
		return TypeKind.INPUT_OBJECT;
	}
	if (type is ListGraphType)
	{
		return TypeKind.LIST;
	}
	if (type is NonNullGraphType)
	{
		return TypeKind.NON_NULL;
	}

	throw new ExecutionError("Unkown kind of type: {0}".ToFormat(type));
}
```

Note the lack of a comparison for `GraphQLAbstractType`. Was this an oversight, or is it intentional and I'm not meant to be using this type like this?

Cheers

**Comment by joemcbride** [comment]
That is intentional.  You should be able to use `UnionGraphType` or `InterfaceGraphType` for dynamic types.

**Comment by joemcbride** [comment]
Going to close this, let me know if you have any other issues or questions.
