### ISSUE TITLE
Microservice pattern, with Apollo Server as a gateway?

### ISSUE THREAD

**Issue by anthonyhumphreys** [graphql-dotnet/graphql-dotnet#813]
Hello,
I am hoping to use this package in my .net core microservices, with an Apollo Server as a gateway, using introspection to discover the services. Is this achievable? Will subscriptions be achievable in this architecture?

Thanks!
AH

**Comment by joemcbride** [comment]
You could perhaps do something like that, though that is not a "built in" scenario for this project (at least my understanding of what you're trying to do).  You can easily call other microservices from within a field resolver (GraphQL IS designed to do that) though that would not be related to introspection.

You may be interested in this work that others have done.  https://github.com/graphql-dotnet/graphql-dotnet/pull/592
