### ISSUE TITLE
Can I somehow switch execution strategy for queries? Parallel execution strategy for queries not always a best option. 

### ISSUE THREAD

**Issue by ennui** [graphql-dotnet/graphql-dotnet#814]
Hello,
I ran into a problem when I tried to use `FieldAsync<TGraphType>` and `async `requests to Entity Framework with  PostgreSQL provider.
I have one DbContext per request lifetime and all my services use this connection to PostgreSQL server and when try to get 2 async  field in query sometime a got exception that query try to be executed while another query is running.

`FieldAsync<ListGraphType<OrderType>>(
    "getAll",
    resolve: async (context) => await ordersService.GetAllAsync().ConfigureAwait(false));
`

`
FieldAsync<NonNullGraphType<IntGraphType>>(
    "count", 
    resolve: async (context) => await ordersService.CountOrdersAsync());
`

That happens because i try execute 2 requests parallel on same connection. In SQL Server it can be easily fixed in connection string using 'MultipleActiveResultSets=True', but PostgreSQL does not support this feature. Also it can be handled by changing requests and field to synchronous, but it's not a good design.

Is it possible to configure Execution strategy for query from Parallel to Serial, or maybe implement custom execution strategy?

**Comment by BenjaBobs** [comment]
I suggest creating a class that inherits from [DocumentExecuter](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs) and overrides the `SelectExecutionStrategy()` method.

**Comment by ennui** [comment]
Thank you so much. It's works great! I did not even think in this direction
