### ISSUE TITLE
Errors not following spec by default

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#82]
According to https://facebook.github.io/graphql/#sec-Errors, the errors section should contain maps with a mandatory "message" key.

The current default implementation seems to dump exceptions which causes the property to be "Message" (wrong casing).

Furthermore if possible, the errors should include a locations which is a list of { line, column }. I assume is is possible to include this in most cases too.

While I haven't verified yet, the casing issue seems to cause relay to ignore any errors making debugging some what more troublesome.

**Comment by MartinLorensen** [comment]
I would assume that one solution would be to change ExecutionError to it does no extend Exception and add a property "message" mapped to "innerException.Message" and an optional locations list also provided by a constructor argument.

**Comment by tlil87** [comment]
Yep, run into the same and was gonna address that. :+1: I think your suggestion would make sense.

**Comment by joemcbride** [comment]
Sounds reasonable to me. Providing line/column of the query is not yet possible, though will be once I complete the "language" updates branch.

**Comment by MartinLorensen** [comment]
Most uses of ExecutionError is currently in the form of "throw new ExecutionError(....)" so it needs to extend exception or it has to be split into the exception and the "DTO".

The result of the current incorrect casing of message causes Relay to output something along the way of: `Server request for query "Xxxx" failed for the following reasons: 1. undefined, 2. undefined, 3. undefined....`. where the undefined is the value of the (missing) message key in the errors list.

Things looks better with a simple FiddlerScript a la:
`static function OnBeforeResponse(oSession: Session) {
        if (oSession.PathAndQuery=="/path/to/graphql") {            
            oSession.utilReplaceInResponse('Message','message');
        }
    }`.

**Comment by joemcbride** [comment]
Got the project updated to the latest GraphiQL and added a `JsonConverter` for the `ExecutionResult`.  Think that will work for you?  That will allow us to keep the Exception strategy though then project the error however we want.  I'm thinking this would also allow us to provide a "debug" mode which could include a stacktrace and such.

![image](https://cloud.githubusercontent.com/assets/255007/15698636/69d7dd60-277b-11e6-9723-ed6808e36b67.png)

**Comment by tlil87** [comment]
Sounds good @joemcbride

**Comment by joemcbride** [comment]
Published 0.7.0 with this update.

**Comment by MartinLorensen** [comment]
This does not seem to work for me. I am not 100% sure, but I think the reason is that I am not able to enable the "correct" JsonFormatter.

If I replicate the code in "graphql-dotnet\src\GraphQL.GraphiQL\App_Start\WebApiConfig.cs" in my project build with the NuGet version of GraphQL, I get a different instance of Newtonsoft.Json then the one internalized and embedded in GraphQL. So when the "public" version scans for attributes it does not find the `[JsonConverter(typeof(ExecutionResultJsonConverter))]` attribute - and then it does just do default formatting (at least that is the result - it acts as before - both with 0.7.1 and 0-8.0-alpha.

Does that sound reasonable?

**Comment by MartinLorensen** [comment]
Reproduction:
 1) Add the following method to `graphql-dotnet\src\GraphQL.GraphiQL\Controllers\GraphQLController.cs`:

```
    public async Task<HttpResponseMessage> Get(HttpRequestMessage request)
    {
      return await Post(request, new GraphQLQuery { Query = "query foo { hero }" , Variables = "" });
    }
```

 2) Verify that you can see the expected error (request `http://localhost:47080/api/graphql` in a browser):

```
{
  "data": null,
  "errors": [
    {
      "message": "Error trying to resolve hero."
    }
  ]
}
```

 3) Remove the GraphQL project from the solutionn. Add GraphQL 0.7.1 from NuGet.

 4) Verify that you can see the unformated error 

```
{
  "data": {
    "hero": null
  },
  "errors": [
    {
      "ClassName": "GraphQL.ExecutionError",
      "Message": "Error trying to resolve hero.",
      "Data": null,
      "InnerException": {
        "ClassName": "System.NullReferenceException",
        "Message": "Object reference not set to an instance of an object.",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action) in C:\\Home\\projects\\graphql-dotnet\\src\\GraphQL\\EnumerableExtensions.cs:line 29\r\n   at GraphQL.DocumentExecuter.CollectFields(ExecutionContext context, GraphType specificType, Selections selections, Dictionary`2 fields, List`1 visitedFragmentNames) in C:\\Home\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\DocumentExecuter.cs:line 534\r\n   at GraphQL.DocumentExecuter.<>c__DisplayClass10_0.<CompleteValue>b__1(Field field) in C:\\Home\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\DocumentExecuter.cs:line 291\r\n   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action) in C:\\Home\\projects\\graphql-dotnet\\src\\GraphQL\\EnumerableExtensions.cs:line 31\r\n   at GraphQL.DocumentExecuter.<CompleteValue>d__10.MoveNext() in C:\\Home\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\DocumentExecuter.cs:line 289\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at GraphQL.DocumentExecuter.<ResolveField>d__8.MoveNext() in C:\\Home\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\DocumentExecuter.cs:line 189",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": "8\nApply\nGraphQL, Version=0.7.1.0, Culture=neutral, PublicKeyToken=null\nGraphQL.EnumerableExtensions\nVoid Apply[T](System.Collections.Generic.IEnumerable`1[T], System.Action`1[T])",
        "HResult": -2147467261,
        "Source": "GraphQL",
        "WatsonBuckets": null
      },
      "HelpURL": null,
      "StackTraceString": null,
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": null,
      "HResult": -2146233088,
      "Source": null,
      "WatsonBuckets": null
    }
  ]
}
```

**Comment by joemcbride** [comment]
That does indeed seem to be a problem, so perhaps switching to a different class structure is still preferable if people want to use their own json serializer.  I was able to get this working using the included `DocumentWriter` since that references the same types.

```
public async Task<HttpResponseMessage> Post(HttpRequestMessage request, GraphQLQuery query)
{
    var inputs = query.Variables.ToInputs();
    var result = await Execute(_schema, null, query.Query, query.OperationName, inputs);

    var httpResult = result.Errors?.Count > 0
        ? HttpStatusCode.BadRequest
        : HttpStatusCode.OK;

    var json = _writer.Write(result);

    var response = request.CreateResponse(httpResult);
    response.Content = new StringContent(json, Encoding.UTF8, "application/json");

    return response;
}
```

**Comment by joemcbride** [comment]
This should not be an issue now that JSON.NET is not being ILMerged.  Going to close.
