### ISSUE TITLE
Best approach - too many db queries on resolve

### ISSUE THREAD

**Issue by denisedelbando** [graphql-dotnet/graphql-dotnet#820]
## Summary
I was looking at most samples out there with this library and usually the samples to navigate to another database table from current object is using the resolve => call data service which is usually a database call.
For example in the [droid type](https://github.com/graphql-dotnet/examples/blob/master/src/StarWars/Types/DroidType.cs): 
```
Field<ListGraphType<CharacterInterface>>(
                "friends",
                resolve: context => data.GetFriends(context.Source)
);
```

This is fine for the sample project because the parent objects -- Hero, Droid and Human return one item. What if I had allHero and i had 100 of them. Inside hero, I had friends
Wouldn't that be 101 calls to the database? for each 100 of the hero, you had to resolve the friends of that hero.
I verified this using breakpoints and it does call the database many times.

Is there a better implementation around this issue?
We have lots of parent objects that return many and inside them have navigational properties that require resolving via database calls and so I was wondering if there is a better way?

My workaround is to get rid of these kinds of properties. So now I am facing with lots of Types just to avoid this.

**Comment by BenjaBobs** [comment]
Also there is the [Dataloader](https://graphql-dotnet.github.io/docs/guides/dataloader).

**Comment by denisedelbando** [comment]
@BenjaBobs thank you.
