### ISSUE TITLE
GraphQL-Dotnet Subscriptions Returning null

### ISSUE THREAD

**Issue by Patrick-Spiegel** [graphql-dotnet/graphql-dotnet#822]
## Summary
So I have tried to make an example for another issue in this repo, but GraphQL subscriptions don't work the same way as they used to work.  Subscriptions are always returning null as data and terminating the connection. Without errors.
So where could I have made an error?
## Relevant information
I have created a repo with my code [here](https://github.com/Patrick-Spiegel/GraphQL-Dotnet-Server)

The critical path I guess is in this class. The Subscribe method is never called when you do a subscription. 
```  
public class DummyObservable : IObservable<Value>
    {
        public IDisposable Subscribe(IObserver<Value> observer)
        {
            return new DummyObserver(observer);
        }
    }
```
But the object is being created. 

### Environment (if relevant)

- graphql-dotnet version 2.0 (stable)
- windows 10
- Clients: GraphiQL, GraphQL Playground, Insomnia

**Comment by BenjaBobs** [comment]
This may be related to #815. You could try checking out the repo using that as reference instead of the nuget package to test if it was fixed by #815.

**Comment by Patrick-Spiegel** [comment]
Alright. I will just wait for a new Release as it is currently not too urgent. 

👍

**Comment by Patrick-Spiegel** [comment]
@joemcbride any plans on making a new Bugfix release?

**Comment by joemcbride** [comment]
@Patrick-Spiegel 2.1 is released with this fix.  Sorry it took so long!
