### ISSUE TITLE
`$type` field in response

### ISSUE THREAD

**Issue by alexb5dh** [graphql-dotnet/graphql-dotnet#824]
What does `$type` property in response means and how can it be removed?
I'm getting it for each entity in every response and it doesn't seem to correspond to entity type. Nothing in documentation also.

Example:
![image](https://user-images.githubusercontent.com/4650832/45639713-5f933880-bab9-11e8-9929-4170aafd8310.png)

**Comment by jquense** [comment]
I believe that's added by https://www.newtonsoft.com/json it should be configurable

**Comment by alexb5dh** [comment]
Yes, found an issue in JSON.NET configuration.
Thanks.
