### ISSUE TITLE
Custom `GraphType` for dictionary

### ISSUE THREAD

**Issue by alexb5dh** [graphql-dotnet/graphql-dotnet#826]
Our project is trying to migrate to GraphQL from regular REST approach and currently we faced a problem with serialization of `Dictionary<string, T>`-like properties.

By default JSON.NET serializes them as regular JSON objects and that's what UI is expecting. So the idea is to use GraphQL query language to filter fields of `T` generic parameter (same as for `ListGraphType`) while providing JSON objects in response.

## Example:
__Classes:__
```csharp
public class Employee
{
  public string Name { get; set; }
  // ...
}

public class Job
{
  public string Id { get; set; }
  public Dictionary<string, Employee> Employees { get; set; }
  // ...
}
```

__Query:__
```
{
  job(id: "..."){
    employees{
      name
    }
  }
}
```

__Response:__
```
{
  employees: {
    "John": {
      name: "John"
    },
    "Bob": {
      name: "Bob"
    }
  }
}
```
_Employees_ property here has dynamic set of fields (schema), determined by the data.

As such I'm trying to define shema or custom `GraphType` to describe such properties but can't find anything similar in examples or documentation.  
Is it possible with GraphQL.NET?

**Comment by joemcbride** [comment]
That unfortunately does not follow the GraphQL Spec so it would not be supported.  You could create a Dictionary GraphQL scalar type, though since it is a scalar the engine would not be able to support querying sub fields.

**Comment by joemcbride** [comment]
That _could_ be done, though that would not conform to the GraphQL spec and it would need special handling in the engine.  Since that is far outside of the spec, unfortunately that is not a feature that I would want to add.
