### ISSUE TITLE
How can you efficiently share Field Resolvers between objects in the same inheritance tree?

### ISSUE THREAD

**Issue by JamiePed** [graphql-dotnet/graphql-dotnet#829]
I've been attempting to define some GraphQL Types that use Inheritance in order to differentiate between types of objects being returned. I noticed that any fields held on an `InterfaceGraphType` will not be displayed in the schema unless the field definition is duplicated in the implementing class. despite adding `this.RegisterType<ManagerType>();` to the Schema I.e.

```csharp
public class Person
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public Address CorrespondenceAddress { get; set; }
}

public class Employee : Person
{
    public Guid EmployeeReference { get; set; }
    public string Department { get; set; }
}

public class Customer : Person
{
    public string EmailAddress { get; set; }
}

public class PersonType: InterfaceGraphType<Person>
{
    public PersonType()
    {
        this.Name= "Person";
        this.Field(x => x.Id, type: typeof(IdGraphType)).Description("The unique identifier");
        this.Field(x => x.Name);

    }
}

public class EmployeeType : ObjectGraphType<Employee>
{
     public EmployeeType()
    {
        this.Name = "Employee";
        this.Field(x => x.Department);

        this.Interface<PersonType>();
    }
}
```

When querying the schema like this the only field visible on the employee type is the Department - I was expecting to automatically get the fields from the interface, am I missing something or is that not possible?

More importantly, is it possible to share resolvers in the base interface type? I.e. If you added

```csharp
this.Field(x => x.Address, type: typeof(AddressType))
.Resolve(context =>
{
    …
    return address;
});
```

to the `PersonType` how can this be used by all of the inheriting classes?

**Comment by jumpinjackie** [comment]
If it helps, I use an extension method (off of ObjectGraphType<T>) to farm off field registrations for common sets of properties (from interfaces or base classes, which you would constrain T to), so that instead of duplicating the field registrations over and over, just call the common extension method instead to do it all for you.

**Comment by JamiePed** [comment]
Interesting, so you have a separate Extension method for each interface type you want to inherit fields from? That isn't too bad a way to share that logic without flat out copying it!

I may investigate creating either some kind of `BaseObjectGraphType<T1, T2>` or create a `this.Base<T>()` method that might be able to automagically import some stuff. If I get anything working I'll try to create a PR for it

**Comment by jumpinjackie** [comment]
Currently, yes: We use registration extension methods for certain interfaces in our GraphQL-visible types.

Though if you want to take this to the extreme, you could do this generically by using reflection and reflect on `typeof(T)` to look for properties of a certain custom attribute (eg. `[GraphQLField]`) to perform field registrations (as `Field()` has non-generic overloads that can work with `string` property names and `System.Type` type, which you can slot in whatever your reflected `PropertyInfo` instances give back)

Which your hypothetical `BaseObjectGraphType<T1, T2>` could probably automagically do for you.

And if you *really* want to be adventurous, you could try looking for methods of a certain signature (a method that takes the GraphQL resolver context (`ResolveFieldContext<T>`) and returns a known GraphQL base type) with another custom attribute (eg. `[GraphQLResolvedField]`) to perform resolved field registrations. I haven't fully thought through if C# generics is expressive enough to allow us to do this, so I may be talking about something which is not possible.

**Comment by SimonCropp** [comment]
seems this is resolved and should be closed?
