### ISSUE TITLE
Input Enum is getting other value when using generics 

### ISSUE THREAD

**Issue by denisedelbando** [graphql-dotnet/graphql-dotnet#830]
Hello,

I have query builder that uses the same functionality with the exception of props being sent.
What I did was create generics for it like so:
![screenshot - 2018-09-23 10_13_37 pm](https://user-images.githubusercontent.com/3780000/45935874-f494a680-bf7d-11e8-9007-f2a2bb8650db.png)

The issue is, in the `graphiql` tool, the options of the endpoint that uses the EmployeePropsEnum is getting the wrong options for the property `prop` and instead shows options of StudentPropsEnum

EmployeePropsEnum has:
```
Id
Name
IsActive
CreateDate
```

other StudentPropsEnum is:
```
Id
FirstName
LastName
IsActive
CreateDate
ModifiedDate
Company
```
This is what shows up in EmployeeProps even if its supposedly just 4 values
![screenshot - 2018-09-23 10_17_15 pm](https://user-images.githubusercontent.com/3780000/45935922-7be21a00-bf7e-11e8-84be-9d9d70a693f0.png)

When I commented out the endpoint that uses the StudentPropsEnum, the options that uses EmployeePropsEnum is now showing correct.

I am using autofac as IoC and this is how I am resolving:
```
builder.RegisterGeneric(typeof(FilterInputType<,>)).AsSelf();
```

```
builder.RegisterType<EmployeePropsEnum>().AsSelf();
builder.RegisterType<StudentPropsEnum>().AsSelf();
```

Any help appreciated. Thank you.

**Comment by joemcbride** [comment]
What does your schema look like when printed with SchemaPrinter?

**Comment by denisedelbando** [comment]
i got it working. its a case of copying and pasting.
the name part i never bothered changing. i did not know it had to be unique everytime i create an enumgraphtype.
forexample
```
public class UserPropsEnumType : EnumerationGraphType<UserPropsEnum>
    {
        public UserPropsEnumType()
        {
            Name = "userprops";
        }
    }

public class EmployeePropsEnumType : EnumerationGraphType<EmployeePropsEnum>
    {
        public EmployeePropsEnumType()
        {
            //needs to change here
            Name = "employeeprops";
        }
    }
```

i was using just name="props" before so it was easy to miss this.
