### ISSUE TITLE
Is it possible to use grahpql.net direct with sql server using sql queries?

### ISSUE THREAD

**Issue by MustaMohamed** [graphql-dotnet/graphql-dotnet#831]
I can use graphql.net with entity framework and create schema and types that's working for me.

but I want to talk direct to the sql server database and make my graphql queries on the database. 

Is that possible?

Thank you.

**Comment by BenjaBobs** [comment]
Here is some reading material on the subject:

- http://fiyazhasan.me/tag/graphql-dotnet/
- https://fullstackmark.com/post/17/building-a-graphql-api-with-aspnet-core-2-and-entity-framework-core

**Comment by MustaMohamed** [comment]
Thank you BenjaBobs, but unfortunately this is not what I want.

I want to use the grahpql direct with sql server queries.

So I am able to write sql select query and it's executed on the database, or something like that. So I am able to talk direct to the database not using entity framework.

Thank you again.

**Comment by BenjaBobs** [comment]
Then you can use the same approach as me (although it's not documented anywhere).

What I've set up is a service can traverse the entire AST and then translates it into another query language (in my case, Gremlin, but you'd use SQL).

Then I use that service in my root resolver to fetch the data.
I'm not sure how well that would work with a regular SQL database though, as joins can become quite expensive.

**Comment by RehanSaeed** [comment]
I've seen a few people talk about converting the AST to Gremlin or other graph database queries. Are there any examples? I think it would make an interesting blog post.

**Comment by BenjaBobs** [comment]
Not that I've seen, but I initially started doing it that way to take advantage of the Gremlin language for traversals with better performance than SQL joins.

The execution flow is something like this, though this is an old version:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgY2xpZW50IGFzIFJlYWN0IENsaWVudFxuICAgIHBhcnRpY2lwYW50IHdlYiBhcyBXZWJDb250cm9sbGVyXG4gICAgcGFydGljaXBhbnQgZ3FsIGFzIEdyYXBoUUwgZG90bmV0XG4gICAgcGFydGljaXBhbnQgdHJhdmVyc2VyIGFzIEdyYXBoUUwgVHJhdmVyc2VyXG4gICAgcGFydGljaXBhbnQgbm9kZSBhcyBHcmFwaFFMIE5vZGUgVmlzaXRvclxuICAgIHBhcnRpY2lwYW50IGV4dHJhY3QgYXMgR3JhcGhzb24gVHJhdmVyc2VyXG4gICAgcGFydGljaXBhbnQgZ3JhcGhzb25Ob2RlIGFzIEdyYXBoc29uIE5vZGUgVmlzaXRvclxuICAgIHBhcnRpY2lwYW50IGNvc21vcyBhcyBDb3Ntb3NcblxuICAgIGNsaWVudC0-PndlYjogR3JhcGhRTCByZXF1ZXN0XG4gICAgd2ViLT4-Z3FsOkdyYXBoUUwgc3RyaW5nICYgdmFyaWFibGVzXG4gICAgZ3FsLT4-Z3FsOiBWYWxpZGF0ZSBzeW50YXhcbiAgICBncWwtPj50cmF2ZXJzZXI6IEdyYXBoUUwgYXN0XG4gICAgbG9vcCBFdmVyeSBub2RlXG4gICAgICAgIHRyYXZlcnNlci0-Pm5vZGU6IEdyYXBoUUwgbm9kZVxuICAgICAgICBub2RlLT4-bm9kZTogVmFsaWRhdGUgc2VtYW50aWNhbGx5XG4gICAgICAgIG5vZGUtPj50cmF2ZXJzZXI6IEVycm9yc1xuICAgICAgICBub2RlLT4-bm9kZTogVHJhbnNsYXRlIHRvIGdyZW1saW5cbiAgICAgICAgbm9kZS0-PnRyYXZlcnNlcjogR3JlbWxpbiBzdWJzdHJpbmdcbiAgICBlbmRcbiAgICB0cmF2ZXJzZXItPj5ncWw6IEVycm9yc1xuICAgIHRyYXZlcnNlci0-PmNvc21vczogR3JlbWxpbiBxdWVyeVxuICAgIGNvc21vcy0-PmV4dHJhY3Q6IFJlc3VsdCBpbiBncmFwaHNvblxuICAgIGxvb3AgRXZlcnkgbm9kZVxuICAgICAgICBleHRyYWN0LT4-Z3JhcGhzb25Ob2RlOiBHcmFwaHNvbiBub2RlXG4gICAgICAgIGdyYXBoc29uTm9kZS0-PmdyYXBoc29uTm9kZTogUGFyc2UgYXMgZW50aXR5XG4gICAgICAgIGdyYXBoc29uTm9kZS0-PmV4dHJhY3Q6IEVudGl0eVxuICAgIGVuZFxuICAgIGV4dHJhY3QtPj5ncWw6IEVudGl0aWVzXG4gICAgZ3FsLT4-d2ViOiBKc29uIHJlc3BvbnNlICsgRXJyb3JzXG4gICAgd2ViLT4-Y2xpZW50OiBKc29uIHJlc3BvbnNlICsgRXJyb3JzIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

**Comment by EmmanuelPonnudurai** [comment]
I have a small suggestion. Why don't you use the well tested and solid [ADO.NET](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/)? 

It gives you so many features, one of which is to [execute queries against SQL Server](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ado-net-code-examples#sqlclient).

All you'd have to do is hookup your resolver to the these and you should be good to go. 

Please disregard if this is not what you are looking for. Thank you.

**Comment by mariomuja** [comment]
Hi Mustafa, 

one way to achieve this is to first provide an API for your database (tables, views, functions, procedures etc) that is compatible with the OAS (Open API Specification). 

Then you can automatically generate a GraphQL endpoint without writing a single line of code using 
Loopback OAS-to-GraphQL: 

https://loopback.io/openapi-to-graphql.html

This is only one example. There are several solutions to generate a GraphQL endpoint from OAS REST interfaces.

Regards, Mario

**Comment by SimonCropp** [comment]
@MustaMohamed  yes this is possible https://github.com/SimonCropp/GraphQL.EntityFramework
