### ISSUE TITLE
Enum issue - Could not find conversion from System.Int32 to IncidentTypeEnum

### ISSUE THREAD

**Issue by darbio** [graphql-dotnet/graphql-dotnet#834]
## Summary

When I try and use an [EnumerationGraphType](https://graphql-dotnet.github.io/docs/getting-started/schema-types#enumerations) as variable of an input in a mutation I get an `INVALID_OPERATION` error with the message "Error trying to resolve createIncident.", which contains an inner exception with the message "Could not find conversion from System.Int32 to IncidentTypeEnum".

The exception is thrown when I call `var incident = context.GetArgument<IncidentType>("incident");`

How do I use the [enum type](https://graphql-dotnet.github.io/docs/getting-started/schema-types#enumerations)?

## Relevant information

Enum type:
```
    public class IncidentTypeEnum : EnumerationGraphType
    {
        public IncidentTypeEnum()
        {
            Name = "IncidentType";

            AddValue("Bushfire", "Bush fire incident", 0);
            AddValue("MVA", "Motor vehicle incident", 1);
        }
    }
```

Input Type:
```
    public class IncidentInputType : InputObjectGraphType
    {
        public IncidentInputType()
        {
            Name = "IncidentInput";

            Field<NonNullGraphType<IncidentTypeEnum>>("type");
            Field<NonNullGraphType<FloatGraphType>>("latitude");
            Field<NonNullGraphType<FloatGraphType>>("longitude");
        }
    }
```

Mutation:
```
public class IncidentMutation : ObjectGraphType
    {
        public IncidentMutation(DomainEventOrchestrator orchestrator)
        {
            Name = "IncidentMutation";

            FieldAsync<IncidentType>(
                "createIncident",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<IncidentInputType>>
                    {
                        Name = "incident"
                    }
                ),
                resolve: async context =>
                {
                    var incident = context.GetArgument<IncidentType>("incident");
                    ...
                    return incident;
                }
            );
        }
    }
```

Query:
```
mutation IncidentMutation($incident:IncidentInput!) {
  createIncident(incident: $incident) {
    id
  }
}

```

Variables:
```
{
  "incident": {
    "type": "Bushfire",
    "latitude": -32.123,
    "longitude": 152.098
  }
}
```

Error:
```
{
  "data": {
    "createIncident": null
  },
  "errors": [
    {
      "message": "Error trying to resolve createIncident.",
      "locations": [
        {
          "line": 29,
          "column": 3
        }
      ],
      "path": [
        "createIncident"
      ],
      "extensions": {
        "code": "INVALID_OPERATION"
      }
    }
  ]
}
```

### Environment (if relevant)

DotNet core 2.1.402
GraphQL 2.0.0

**Comment by joemcbride** [comment]
Okay - yes, you cannot use a GraphType with GetArgument.  You need to use a DTO, with only .NET types. So you need to use an actual C# enumeration.  I see you’re trying to use the same class for both, which could cause some issues - it was not designed to use the same class for both.  It _may_ work if you use a C# enum.

See the Human class in the Mutation example.

https://graphql-dotnet.github.io/docs/getting-started/mutations

**Comment by darbio** [comment]
Cheers. I'll give it a go and get back to you. How does it know what enum to convert it to? Is it based on the number of the name?

**Comment by sungam3r** [comment]
I have 2 questions:
1. If the problem is solved, can this issue be closed?
2. @joemcbride Is it worth making a runtime check to avoid such use and explicitly inform the user of the error?
```c#
public class IncidentType : ObjectGraphType<IncidentType> { }
```

**Comment by sungam3r** [comment]
Closed as stale.
