### ISSUE TITLE
Should the DataLoader work inside a Mutation ?

### ISSUE THREAD

**Issue by mrezmerita** [graphql-dotnet/graphql-dotnet#837]
Hello,

We noticed that in the case of a complex type return from a Mutation the DataLoader doesn't seem to behave as it does inside a Query. 

For the same type : 
 - if returned from a Query the data loading is done correctly, at once 
 - when returned from a Mutation, the N+1 problem appears. 

Is this the correct behaviour or is that something that we miss ? 

Thank you.

**Comment by Cooke** [comment]
My guess is that the result selects of the mutations execute in serial which prevents the data loader from batching. I guess this since mutations are required to execute in serial and it feels likely that this execution strategy continues when executing the sub selects.

**Comment by mrezmerita** [comment]
Thank you,
It makes sense.

We'll modfy the mutation in order to return less data but it is not ideal as it could force the client application to refetch with a query in order to obtain all the details. 

I assume that there is not much else that we can do about it, for now.

**Comment by randyridge** [comment]
Cd
Llogj
