### ISSUE TITLE
Could not find conversion from System.Int64 to System.Double

### ISSUE THREAD

**Issue by jnewman30** [graphql-dotnet/graphql-dotnet#840]
## Description

When upgrading to 2.0 from 2.0.0-alpha-870 we ran into this error. Could not find conversion from System.Int64 to System.Double.

### Steps to reproduce
Our Data Models are using long and DateTimeOffset in quite a few places which are the only thing I could come up with to check regarding this error.  That being said our GraphQL model types for long properties are using FloatGraphType (Because originally I think that was the only place that conversion was supported) fields and our DateTimeOffet properties using DateTimeGraphType fields.
We switched all the fields using DateTimeGraphType to DateTimeOffsetGraphType where the matching properties were DateTimeOffset and that had no effect.

### Expected result

I am puzzled as to why this error is occurring.  Have not been able to pinpoint but it shouldn't be throwing an exception with a conversion issue.

### Actual result

GraphQL call fails when converting data model to GraphQL type result here:
https://github.com/graphql-dotnet/graphql-dotnet/blob/4b02f6e2628d3f8e02829c60938616cea6a54fee/src/GraphQL/ValueConverter.cs#L179

### Environment

We are not yet using [GraphQL Server](https://github.com/graphql-dotnet/server)

ASPNET Core 2.1/NetStandard 2
GraphQL 2.0.0
AnyCpu/x64
Windows 10/Windows Server 2016

**Comment by joemcbride** [comment]
This is most likely because there is not a long->double converter registered.  Can you try the following and see if it fixes your issue?

Add this somewhere in your app bootstrapping.

```csharp
ValueConverter.Register(
  typeof(long),
  typeof(double),
  value => Convert.ToDouble((long)value, NumberFormatInfo.InvariantInfo));
```

**Comment by minuseight** [comment]
GraphQL.ExecutionError: Could not find conversion from System.Single to System.Double

Adding the code suggested fixed the issue:

 ValueConverter.Register(
                typeof(float),
                typeof(double),
                value => Convert.ToDouble(Math.Round((float)value, 3, MidpointRounding.AwayFromZero), NumberFormatInfo.InvariantInfo));

**Comment by huysentruitw** [comment]
Any progress on this issue?
