### ISSUE TITLE
Bugs introduced during alpha phase?

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/graphql-dotnet#846]
I trying to pin down 2 broken unit-tests in graphql-conventions that seem to be introduced during the graphql-dotnet 2.0.0 alpha phase. Bear with me...

With NuGet package [2.0.0-alpha-937](https://www.nuget.org/packages/GraphQL/2.0.0-alpha-937) all unit-tests of graphql-convetions pass just fine.

One package later [2.0.0-alpha-938](https://www.nuget.org/packages/GraphQL/2.0.0-alpha-938) breaks this unit-test: https://github.com/graphql-dotnet/conventions/blob/master/test/Tests/Web/RequestHandlerTests.cs#L61 with

> System.ArgumentNullException : Value cannot be null. Parameter name: values

Again, one package later [2.0.0-alpha-947](https://www.nuget.org/packages/GraphQL/2.0.0-alpha-947) breaks another unit-test: https://github.com/graphql-dotnet/conventions/blob/master/test/Tests/Adapters/Engine/AbstractTypeConstructionTests.cs#L24 with

> Message: Assert.Equal() Failure
> Expected: 1970-01-01T00:00:00.0000000
> Actual:   1970-01-01

Here it seems the actual value is always "1970-01-01" even though I change the hour/minute/seconds value in the query...

Any idea what is going wrong, or an idea how we can pinpoint the commits that have caused this depending on the alpha package versions?

**Comment by huysentruitw** [comment]
I have decompiled those 3 packages and ran the code through KDiff3.

Only change between 937 and 938 is this commit: https://github.com/graphql-dotnet/graphql-dotnet/commit/fbfc8c3ebe86fbeed7ca5ccb378252cb9e994ae9#diff-b4c19b6d66951c1c5d547222ae0d874b

Changes between 938 and 947 is this probably related to the change in DateGraphType: https://github.com/graphql-dotnet/graphql-dotnet/commit/ad9c5c8523dde84dd040755a80d829b1f74ede9e#diff-6ecb3c17fef816d6cd02a67ad408ea9eR17 which can probably be fixed in graphql-conventions by using the new `DateTimeGraphType` instead. Let me check...

**Comment by joemcbride** [comment]
Yes - here's the release notes for 947:

https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v2.0.0-alpha-947

**Comment by huysentruitw** [comment]
Ok fixed both issues https://github.com/graphql-dotnet/conventions/pull/106/files
