### ISSUE TITLE
Generic Creation of ObjectGraphType

### ISSUE THREAD

**Issue by dimortizp** [graphql-dotnet/graphql-dotnet#847]
Hi,

I'm trying to use a generic response using ObjectGraphType like this:

public class ResponseRegister<TEntityType,TEntity> : ObjectGraphType<ResponseMutationModel<TEntity>>
    {
        public ResponseRegister(){
             Field(x => x.Error, nullable:true).Description("Hay error");
             Field<ListGraphType<ValidationErrorType>,IEnumerable <ValidationErrorModel>>()
                .Description("Lista de errores")
                .Name("ErrorList");
             Field<TEntityType,TEntity>()
                .Name("Entity")
                .Description("Entity");
        }
    }

When I register each mutations like this:

Field<ResponseRegister<SchoolSiteType,SchoolSites>>
            (
                "CreateSchoolSite",
                arguments:new QueryArguments(new QueryArgument<NonNullGraphType<InputSchoolSiteType>>{Name = "schoolSite"}),
                resolve: context => 
                {
                    var entity = context.GetArgument<SchoolSites>("schoolSite");
                    return _repository.AddSchoolSiteAsync(entity);
                }
            );

Field<ResponseRegister<TeacherType,Teachers>>
            (
                "CreateTeacher",
                arguments:new QueryArguments(new QueryArgument<NonNullGraphType<InputStudentType>>{Name = "teacher"}),
                resolve: context => 
                {
                    var entity = context.GetArgument<Teachers>("teacher");
                    return _repository.AddTeacherAsync(entity);
                }
            );

It alwasy takes the last field register to autocomplete on graphiQL, I'd like to know if that's a problem with something that I'm doing, with the component or maybe with GraphiQL. For example in this case, if I try to call the mutation CreateSchoolSite, it takes the values of CreateTeacher to autocomplete the response.

Thanks for your help

**Comment by joemcbride** [comment]
Are you providing a unique type name on your ResponseRegister types?

**Comment by dimortizp** [comment]
Hi @joemcbride 

What do you mean on "unique type name"?

My ResponseRegister is like this: 

public class ResponseRegister<TEntityType,TEntity> : ObjectGraphType<ResponseMutationModel<TEntity>>
    {
        public ResponseRegister(){
             Field(x => x.Error, nullable:true).Description("Hay error");
             Field<ListGraphType<ValidationErrorType>,IEnumerable <ValidationErrorModel>>()
                .Description("Lista de errores")
                .Name("ErrorList");
             Field<TEntityType,TEntity>()
                .Name("Entity")
                .Description("Entity");
        }
    }

And in the implementations, I'm trying to do it in this way

Field<ResponseRegister<StudentType,Students>> with the name CreateStudent
Field<ResponseRegister<TeacherType,Teachers>> with the name CreateTeacher

If I try to call the mutation the autocomplete always shows me 
the option of the TeacherType for the response of the migration, in this way

mutation{
  createSchool
  (
    school:
    {
      name:"test school same ID"
      internalIdentification:"800236529"
    }
  ) {
    entity{
      **userId**
    }
  }
}

But the parameter **userId** doesn't belongs to StudentType, it belongs to TeacherType.

**Comment by dimortizp** [comment]
Hi @joemcbride 

Now I got what you meant. The issue was caused because I didn't add a unique name for the generic ObjectGraphType. It was solved just by doing this:

public class ResponseRegister<TEntityType,TEntity> : ObjectGraphType<ResponseMutationModel<TEntity>>
    {
        public ResponseRegister(){
            Name=typeof(TEntity).Name;
            Field(x => x.Error, nullable:true).Description("Hay error");
            Field<ListGraphType<ValidationErrorType>,IEnumerable <ValidationErrorModel>>()
            .Description("Lista de errores")
            .Name("ErrorList");
            Field<TEntityType,TEntity>()
            .Name("Entity")
            .Description("Entity");
        }
    }

Thanks
