### ISSUE TITLE
How do you run the GraphiQL example?

### ISSUE THREAD

**Issue by ManuelDeLeon** [graphql-dotnet/graphql-dotnet#85]
I cloned the repo but when I open `\graphql-dotnet\src\GraphQL.GraphiQL\GraphQL.GraphiQL.csproj` I get:

![image](https://cloud.githubusercontent.com/assets/4257750/15752713/9385b5a6-28ac-11e6-8cf5-01e17e656c22.png)

**Comment by joemcbride** [comment]
Did you restore the Nuget packages?  What version of Visual Studio are you using?  The other projects load/compile fine?

**Comment by joemcbride** [comment]
Here are the options in Visual Studio if you don't have them set:

![image](https://cloud.githubusercontent.com/assets/255007/15756243/3dace150-28b5-11e6-8bc4-5aeb2004486f.png)

**Comment by ManuelDeLeon** [comment]
Thanks. Had to download nuget.exe from https://docs.nuget.org/consume/Command-Line-Reference put it on the root folder and then execute `nuget restore GraphQL.sln`

**Comment by joemcbride** [comment]
👍  There is also a visual studio extension that can help with that, but that works.
