### ISSUE TITLE
Mutation type with alias field will not map.

### ISSUE THREAD

**Issue by nojaf** [graphql-dotnet/graphql-dotnet#850]
## Description

When having a mutation that uses an alias, `ObjectExtensions.ToObject` will be unable to populate the values.

### Steps to reproduce

See [unit test](https://github.com/graphql-dotnet/graphql-dotnet/pull/851).

### Expected result

Properties should be mapped, `Field("properties", x => x.PropertyValues,
                type: typeof(ListGraphType<ProgramStepPropertyValueInputType>)).Name("properties");` will not be mapped by [ObjectExtension](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/ObjectExtensions.cs#L34).

`Assert.True(Program.Steps.Any(step => step.PropertyValues.Count > 0));`

### Actual result

Empty List of properties.

### Environment

2.0.0, Windows full framework

**Comment by nojaf** [comment]
If you can give me some pointer how to tackle this, I'm willing to try this myself.

**Comment by sungam3r** [comment]
@nojaf I copied your test from #851 without changes. Now it successfully passes.

**Comment by nojaf** [comment]
Great news! Thanks a lot.

**Comment by sungam3r** [comment]
@nojaf merged!
