### ISSUE TITLE
Is there any option to add some custom data to extensions property of graphql response ?

### ISSUE THREAD

**Issue by rajmondburgaj** [graphql-dotnet/graphql-dotnet#854]
Hi,

Thanks for this great library :),

I wanted add some custom data in the `extensions` property but it does not seem to be easy in `graphql-dotnet`, I can not find such a property in the `ExecutionError` class or anywhere else , is there any implementation for this feature or any plan for near future to add this feature ?

[Original issue](https://github.com/graphql-dotnet/server/issues/170)

**Comment by joemcbride** [comment]
There is an `Extensions` property on the `ExecutionResult` which you can add extra information.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionResult.cs#L26

On a per-error basis, you can add extra information to the `Data` property which will get rendered as `extensions`.

**Comment by rajmondburgaj** [comment]
Cool, that worked for me. Thanks for the info :)
