### ISSUE TITLE
DataLoader dead-locks

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/graphql-dotnet#855]
@johnrutherford 

You can check-out this branch: https://github.com/huysentruitw/conventions/tree/sample/dataloader-efcore

Running `Update-Database` in the package manager console should create the database with seed data.

I am using the DataLoader implementation in combination with the GraphQL Conventions library, but the latter shouldn't make any difference here.

Currently, the repositories use sync calls to EF Core and what I see is that I can query first and second level data with these GraphQL queries:

First level:

```
query AllMovies {
  movies {
    id
    title
    genre
    releaseDateUtc
  }
}
```

Second level:

```
query AllMovies {
  movies {
    id
    title
    genre
    releaseDateUtc
    
    actors {
      id
      name
    }
  }
}
```

But as soon as I add a third level to the query, the thing deadlocks:

```
query AllMovies {
  movies {
    id
    title
    genre
    releaseDateUtc
    
    actors {
      id
      name
      
      country {
        code
        name
      }
    }
  }
}
```

The reason is because the `DataLoaderContext.DispatchAll()` method exists before all field resolvers were able to run. I've used similar code in the past with EF6 and .NET 4.7.1 and mostly deadlocks like this were caused by a missing `ConfigureAwait(false)` somewhere (which should no longer be needed because there is no AspNetSyncrhonizationContext for .NET Core). Anyway, in that test project, I've already tried to switch to this dataloader implementation: https://github.com/dlukez/dataloader-dotnet but the results are the same (I had some hope, because that implementation contains it's own synchronization context and task scheduler, but no luck...).

When changing the repositories to async EF Core calls, you even can't query the second level without deadlocks.

**Comment by huysentruitw** [comment]
I've tested with my own implementation [YADI](https://github.com/huysentruitw/yadi) and I must say: Damn I'm good 😁 

See the Yadi branch: https://github.com/huysentruitw/conventions/tree/sample/yadi

And even with async EF Core calls: https://github.com/huysentruitw/conventions/tree/sample/yadi-async-repos

I think the reason is the while loop, which keeps running and checking for new loaders: https://github.com/huysentruitw/yadi/blob/master/src/Yadi/DataLoaderContext.cs#L49

**Comment by johnrutherford** [comment]
Hi, it looks like you're just not using the DataLoader correctly. Please refer to the documentation here: https://graphql-dotnet.github.io/docs/guides/dataloader#setup. Specifically, you need to set up the `DataLoaderDocumentListener`. This will automatically call `DispatchAll()` at the right time on each execution level. And you should be injecting `IDataLoaderContextAccessor` rather than `DataLoaderContext`.

**Comment by huysentruitw** [comment]
The current behavior is exactly the same, I do have a `DataLoaderContext` per request and the `DispatchAllAsync` is called at exactly the right time (see GraphQL.Conventions if you want). These two things have nothing to do with the issue here. I can try to transform my sample to GraphQL dotnet only, but the issue will remain the same.

**Comment by huysentruitw** [comment]
Ok, I do have a `DataLoaderContext` per request, so I don`t need that accessor in my example. However I see that the GraphQL convention listener is only triggering the `DispatchAll` once per query (`BeforeExecutionAwaitedAsync`) instead of per *step*.

**Comment by huysentruitw** [comment]
I've found out it does and that totally makes sense. Thanks for the heads up! I will try to call DispatchAll on BeforeExecutionStepAwaitedAsync tomorrow, but that will likely solve my issue here.

Will test tomorrow and report back. Thanks for your time already.

**Comment by huysentruitw** [comment]
triggering the `DataLoaderContext` in `BeforeExecutionStepAwaitedAsync` instead of `BeforeExecutionAwaitedAsync` fixes this issue. Closing now.

Thanks again 👍
