### ISSUE TITLE
Documentation for directly using the AST to call graph databases

### ISSUE THREAD

**Issue by RehanSaeed** [graphql-dotnet/graphql-dotnet#858]
## Summary

I have seen a few people using GraphQL.NET and Apollo Server mention using the AST directly to build a call to a graph database like CosmosDB. It would be nice to have some documentation or perhaps a blog post talking about the AST and showing an example of how this could be done.

### Motivation

It's an advanced scenario but I think it's quite important for real world scenarios where you should probably either use the DataLoader or the AST to reduce the calls to the database.

**Comment by espray** [comment]
@BenjaBobs  can you share your GraphQL=>Gremlin source?
I am looking to do exactly what your doing GraphQl to Gremlin to Azure CosmosDB(Graph)

**Comment by BenjaBobs** [comment]
I'm not quite sure I'm allowed to, we have talked a bit about open sourcing at my job, but it's not something that has amounted to anything yet.

I can say though, that I'm working on making Gremlin.Net.CosmosDb suitable for GraphQl -> Gremlin conversion.

A few small pointers:
For queries, what I do is simply create a traversal that reaches the same entities as the GraphQl does and then use the `tree()` step.

Example:

```graphql
query GetPersonTransactions {
  people {
    name
    purchased {
      id
      price
    }
    sold {
      id
      price
    }
  }
}
```
Would translate roughly to

```groovy
g.V().has('label', 'person')
  .union(
    OutE('purchased').InV(),
    OutE('sold').InV()
  ).tree()
```

**Comment by espray** [comment]
@BenjaBobs thanks fo the reply! I guessed that might be the case, but had to ask. If your team could give back even just a little to the .net GraphQL community, it would me much appreciated. Who know with more eyes on it, the community could improve it or find bugs. :)

**Comment by BenjaBobs** [comment]
Just got back from sprint start and talked to my boss about open sourcing. He said that he liked the idea, but he'd have to take it further up the chain to see if it's okay legally.

**Comment by espray** [comment]
@BenjaBobs Any update?

**Comment by BenjaBobs** [comment]
Well, the higher ups have asked my team to compile a pros and cons list pf open sourcing, which I think will be discussed in january at some point (hopefully). If we are able to convince them that open sourcing is the way forward I'd have to take some time to actually prep the repo (lot of undocumented code and structures I've since come to regret.) for being published. I have no idea how long that would take, but I'll post again when I know what the future holds. Until then I'd be happy to discuss architecture. :)

**Comment by lyrana** [comment]
Following

**Comment by lyrana** [comment]
There's this one too, haven't looked at it yet so can't comment, but did want to leave the link here https://github.com/The-Don-Himself/graphql2gremlin

**Comment by preshi** [comment]
@BenjaBobs : Any update on open-sourcing the codebase? Thanks In Advance.

**Comment by BenjaBobs** [comment]
Unfortunately not. I'd be happy to talk about implementation possibilities though.

**Comment by sungam3r** [comment]
@RehanSaeed @Shane32 I suggest to close this one due inactivity. 4 years passed since last comment.

**Comment by Shane32** [comment]
Agree
