### ISSUE TITLE
Instrumentation reporting low numbers when using DataLoader

### ISSUE THREAD

**Issue by sommarlov** [graphql-dotnet/graphql-dotnet#859]
I suspect instrumentation only reports time to fetch from cache, not the actual data fetch.

**Comment by joemcbride** [comment]
It would report how long the particular resolver took.  If you're using a cache, it would only reflect the actual data fetch when not pulling the data from the cache.

**Comment by sommarlov** [comment]
Sorry, I meant the data loader's cache.
To me it looks like only LoadAsync is instrumented (fetch from data loader cache).

**Comment by joemcbride** [comment]
I'm not aware of any metrics captured specific to using a DataLoader.  The main metrics being captured are on a per-field (resolver) basis.  If that field uses a DataLoader then the time it takes to fetch could be different if pulling from the DataLoader's cache vs. the first time it fetches.

Here's the docs for metrics:  https://graphql-dotnet.github.io/docs/getting-started/metrics

And the implementation of `InstrumentFieldsMiddleware`:

https://github.com/graphql-dotnet/graphql-dotnet/blob/3c7bd27dbd00c3971a7b7bfef4f277946e716e25/src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs#L8-L25

**Comment by johnrutherford** [comment]
It looks to me like the `next` delegate needs to be awaited in `InstrumentFieldsMiddleware` for accurate timing with an async resolver.

**Comment by joemcbride** [comment]
@johnrutherford  Ha, duh - yes that would do it.

**Comment by RehanSaeed** [comment]
@joemcbride There seems to be an implementation of `InstrumentFieldsMiddleware` built in [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/fbfc8c3ebe86fbeed7ca5ccb378252cb9e994ae9/src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs) which has not been updated yet with an await. Also, is this something that is enabled by default in the server project, I can't quite figure it out?

**Comment by joemcbride** [comment]
@RehanSaeed Yes, I'm updating that with async/await.  Metrics are not enabled by default in the server project.  You would need to create your own class that inherits from `DefaultGraphQLExecuter<T>` so you can add the `InstrumentFieldsMiddleware` to the `ExecutionOptions`.

**Comment by sommarlov** [comment]
Thanks for this!

**Comment by joemcbride** [comment]
This is published in 2.3.0 (along with a few other things)
