### ISSUE TITLE
No Custom Directive Documentation

### ISSUE THREAD

**Issue by troydalldorf** [graphql-dotnet/graphql-dotnet#860]
## Description
The [GitHub documentation](https://github.com/graphql-dotnet/graphql-dotnet) indicates that custom directives are supported, but there is no documentation, examples or tests on how to accomplish this.
Adding the custom directive seemed to be obvious, 
```
            Schema.RegisterDirective(
                new DirectiveGraphType("lowercase", new[] { DirectiveLocation.Field })
                {
                    Description = "Converts value to lowercase."
                });
```
### Steps to reproduce
Not able to find an example for custom directives.

### Expected result
Expected documentation, unit tests and examples.

### Environment
Version: 952b4ef

**Comment by jacksonveroneze** [comment]
I'm having trouble implementing custom policies. Following your example I registered to the register, but how to make the codification so that it does what is proposed?

**Comment by joemcbride** [comment]
@jacksonveroneze You can either check for that Directive in your resolve method of your field, or use Field Middleware.  Currently Field Middleware isn't super performant so if you go that route I suggest to do some performance testing.

Examples:

```csharp
public class MyGraphType : ObjectGraphType
{
    public MyGraphType()
    {
        Name = "MyType";
        Field<StringGraphType>("a", resolve: c =>
        {
            var result = "Hello World";

            // can check for directive here or with Field Middleware
            // don't need to do both.

            // check if directive exists, check argument values, etc.
            var directive = c.FieldAst.Directives.Find("lowercase");
            return directive != null ? result.ToLower() : result;
        });
    }
}
```

```csharp
// field middleware
public class LowercaseFieldsMiddleware
{
    public async Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next)
    {
        var result = await next(context);
        var directive = context.FieldAst.Directives.Find("lowercase");
        // check if directive exists, check argument values, etc.
        return directive != null ? result?.ToString().ToLower() : result;
    }
}
```

```csharp
public class DirectiveSchema : Schema
{
    public DirectiveSchema()
    {
        Query = new MyGraphType();

        RegisterDirective(
            new DirectiveGraphType("lowercase", new[] { DirectiveLocation.Field })
            {
                Description = "Converts value to lowercase."
            });
    }
}

var executer = new DocumentExecutor();
var runResult = executer.ExecuteAsync(_ =>
{
    _.Schema = schema;
    _.Query = @"{ a @lowercase }";
    _.FieldMiddleware.Use<LowercaseFieldsMiddleware>();
});
```

**Comment by joemcbride** [comment]
I'll also say that the implementation for the directive you create is entirely up to you.  Your directive may actually be related to some sort of validation, so you wouldn't be checking that directive in the field resolver at all but in a validation rule.  So pretty much up to you for what that directive means in your domain.

**Comment by jacksonveroneze** [comment]
I am very grateful. I'll make an implementation tonight.

**Comment by jacksonveroneze** [comment]
@joemcbride 

Hello.

I performed the implementation to verify that the policy was informed and processed.

I want to reuse this encoding for other fields, but I'm trying hard to pass on the value of the field so I do not need to reference the property inside the code.
    
```
private Func<ResolveFieldContext<User>, Task<string>> resolveLowercase = async c =>
{
    return await Task.Run(() =>
    {
        Directive directive = c.FieldAst.Directives.Find("lowercase");

        return directive != null ? c.Source.Name.ToLower() : c.Source.Name;
    });
};
```

```
Field(x => x.Name).Name("name").ResolveAsync(resolveLowercase);
```

**Comment by Chiragkhanna** [comment]
I am being new to graphql and need to know how can I restrict field value on the basis of user role. Suppose if authenticated user has Admin role then only he can see the value of all fields plus email field whereas other user can see every field but email field value will be null.can anyone help me in implementing it in .net whereas similar example in JavaScript https://codeburst.io/use-custom-directives-to-protect-your-graphql-apis-a78cbbe17355

**Comment by joemcbride** [comment]
@Chiragkhanna here's an answer related to your question, specific to directives. https://github.com/graphql-dotnet/graphql-dotnet/issues/1002#issuecomment-499160140

There is a different way you can accomplish what you need though.  [See these docs](https://graphql-dotnet.github.io/docs/getting-started/authorization) and the [Authorization project](https://github.com/graphql-dotnet/authorization).

**Comment by SimonCropp** [comment]
seems this is answered and should be closed?

**Comment by sungam3r** [comment]
I would like to stay it open for some time. I have not finished yet my work on directives which is related to this issue.

**Comment by Hrle97** [comment]
Any news on this? How can I get the arguments of a directive?

**Comment by sungam3r** [comment]
No news 😞 

> How can I get the arguments of a directive?

What do you mean? Use `GraphQLDirective.Arguments` or `DirectiveGraphType.Arguments`.

**Comment by sungam3r** [comment]
@troydalldorf @jacksonveroneze @joemcbride @Chiragkhanna @SimonCropp @Hrle97 See #2276 . I'm sure you will find all the answers there. This is part of my "big directive rework". I would be grateful for your comments on the code and documentation. I close this issue and propose to transfer all activity to #2276 .
