### ISSUE TITLE
Distributed request resolve

### ISSUE THREAD

**Issue by mcdis** [graphql-dotnet/graphql-dotnet#862]
Hi!

I've plugin like distributed system. Every plugin holds some data.
I want to make API that will allow me to work with all system like a solid.
Can you show checkpoints to make that scenario:

2 Backend services:
- <Service A> holds "Humans" dataset.
- <Service B> holds "Orks" dataset.

All services use GQL. 
Any service **after autoupdate can starts use different scheme**.

Want to create single <Facade> service which provide merged API.

Dataflow Sample 1:
`{humans {id name} }` -> **Facade** service -> **Service A**

Dataflow Sample 2:
`{orks {id name} }` -> **Facade** service -> **Service B**

Dataflow Sample 3:
`{humans {id name} orks {id name} }` -> **Facade** service -> **Service A**,**Service B**

**Comment by sungam3r** [comment]
@mcdis I hope you found a solution. Feel free to reopen with additional details. Closed.
