### ISSUE TITLE
How to map input object to complex object

### ISSUE THREAD

**Issue by zjean** [graphql-dotnet/graphql-dotnet#864]
## Summary
I would like to know how to map the following mutation (PersonInput) to the models Person having an Account, using GraphQL.NET 2.0

```
mutation createPerson ($person: PersonInput!){
  createPerson(person: $person)
  {
	id
  }
}
```

```
{
 "person": {
	"firstName": "Sjaak",
	"lastName": "Trekhaak",
	"email": "jan@test.com",
	"password": "sjanie"
  }
}
```

```
public class PersonInputObject : InputObjectGraphType
{
	public RentePersonInputObject InputObject()
	{
		this.Name = "PersonInput";
		
		this.Field(typeof(StringGraphType), "firstName");
		
		this.Field(typeof(StringGraphType), "lastName");
		
		this.Field(typeof(StringGraphType), "password");
		
		this.Field(typeof(StringGraphType), "email");
	}
}

public class Person
{
	public int Id { get; set; }
	public string FirstName { get; set; }
	public string LastName { get; set; }

	public Account Account { get; set; }
}

public class Account
{
	public string Email { get; set; }
	public string Password { get; set; }
}
```

This is my mutation object.

```
public MutationObject()
{
	this.Name = "Mutation";
	this.Description = "The mutation type, represents all updates we can make to our data.";

        

	this.FieldAsync<PersonObject, Person>(
		"createPerson",
		"Create a person.",
		arguments: new QueryArguments(
			new QueryArgument<NonNullGraphType<PersonInputObject>>()
			{
				Name = "person",
				Description = "The person you want to create.",
			}),
		resolve: context =>
		{
			var person= context.GetArgument<Person>("person");
// dostuff
			
			return person;
		}
	);
}
```

Or should I resolve everything by hand in the mutation's resolver?

Any examples available?

**Comment by joemcbride** [comment]
There is currently nothing built-in to transform the input in this way.  This would need to be a manual transform that you do yourself from the `Arguments` dictionary.

**Comment by rose-a** [comment]
You can let `Newtonsoft.Json` do the conversion like so:

```c#
var personArg = ctx.GetArgument<object>("person");
var person = personArg != null
    ? JToken.FromObject(personArg).ToObject<Person>()
    : null;
```

Works pretty well by default in most situations, you can even leverage a potentially already written custom JsonConverter for complexer objects.

**Comment by joemcbride** [comment]
Perhaps a slightly better version (with a little less processing):

```csharp
var personArg = ctx.Arguments["person"];
var person = personArg != null
    ? JToken.FromObject(personArg).ToObject<Person>()
    : null;
```

**Comment by zjean** [comment]
Thanks for your suggestions!

**Comment by rose-a** [comment]
Just to be thorough, here are some ready to use extension methods:

```c#
public static class ResolveFieldContextExtensions
{
    public static TObject ConvertArgumentToObject<TObject>(this ResolveFieldContext ctx, string argumentName)
        => _convertArgument<TObject>(ctx.Arguments, argumentName);

    public static TObject ConvertArgumentToObject<TObject>(this ResolveFieldContext<object> ctx, string argumentName)
        => _convertArgument<TObject>(ctx.Arguments, argumentName);

    public static TObject ConvertArgumentToObject<TObject, TSource>(this ResolveFieldContext<TSource> ctx, string argumentName)
        => _convertArgument<TObject>(ctx.Arguments, argumentName);

    private static TObject _convertArgument<TObject>(IReadOnlyDictionary<string, object> arguments, string argumentName)
    {
        return arguments[argumentName] != null
            ? JToken.FromObject(arguments[argumentName]).ToObject<TObject>()
            : default;
    }
}
```

to be used like this:

```c#
var person = ctx.ConvertArgumentToObject<Person>("person");
```

@joemcbride 
Maybe this could be delivered with the library? 

Is there a reason the generic `ResolveFieldContext<TSource>` does not inherit from `ResolveFieldContext`? This would eliminate the need of creating separate extension methods for them (not just in this case)...

**Comment by joemcbride** [comment]
@rose-a I don't want to have multiple ways to transform the data.  This is an often requested feature though so I think we should provide some way to do it.  I'm not sure what that looks like yet, but I'm stewing on it.

**Comment by BenjaBobs** [comment]
I second @rose-a question about the inheritance chain.

```c#
public class ResolveFieldContext
{
	//...
	public object Source { get; set; }
}

public class ResolveFieldContext<TSource> : ResolveFieldContext
{
	public new TSource Source 
	{ 
		get => (TSource)base.Source; 
		set => base.Source = value;
	}
}
```

If we design it like this, we can do create generic solutions by creating solutions for the `ResolveFieldContext`.
I think it would simplify the code.

**Comment by benmccallum** [comment]
Hey @SimonCropp, I've got a situation like above where I wanna use an input type with an inner complex input type. Solution above seems nice enough for me utilising `Newtonsoft.Json` to deserialize input into an object. I was thinking of extending @rose-a's example by adding a line to fire the fluent validation like so:
`ArgumentValidation.Validate(context.GetCache(), typeof(TArgument), argument, context.UserContext);`, but `ArgumentValidation` is a private type. Can you make it public?

**Comment by SimonCropp** [comment]
@benmccallum is that question meant to be in a diff repo?

**Comment by benmccallum** [comment]
@SimonCropp Thought I'd tag on here, but will create an issue in your repo where the change is required.

**Comment by Indeavr** [comment]
And what about using AutoMapper for this purpose ?

**Comment by sungam3r** [comment]
I would not want to drag it into the project. This is an extra dependency, dragging along a bunch of unnecessary functionality. I have been working with the AutoMapper for a long time and cannot say that I am delighted with it.

**Comment by sungam3r** [comment]
Relates to #684

**Comment by sungam3r** [comment]
> Is there a reason the generic ResolveFieldContext<TSource> does not inherit from ResolveFieldContext? This would eliminate the need of creating separate extension methods for them (not just in this case)...

Done in other PRs.

**Comment by sungam3r** [comment]
>  I don't want to have multiple ways to transform the data. This is an often requested feature though so I think we should provide some way to do it. I'm not sure what that looks like yet, but I'm stewing on it.

@joemcbride it's done in #1582 

> This would eliminate the need of creating separate extension methods for them 

@rose-a you're right, with changes from #1582 you can continue to use `GetArgument` API through your codebase.

**Comment by sungam3r** [comment]
@zjean Done in #1582 . You can try the latest preview.
