### ISSUE TITLE
Accept queries as standard GraphQL AST instead of string (graphql-tag)

### ISSUE THREAD

**Issue by lanwin** [graphql-dotnet/graphql-dotnet#867]
We want to use https://github.com/apollographql/graphql-tag#readme in our Javascript client. Mostly to since it offers some nice tooling in vscode. But the main idea of graphql-tag is to parse the queries while building the production build and provide them diretly as graphql AST.

Now Ive looked into the codebase of grahql-dotnet and did not found a way of injecting and parsing and graphql AST from json and give it to the executor. 

So I would like to suggest to add such a feature to graphql-dotnet. I there is interest, I would offer some help.

Example how this all looks like are offerend in the link above.

This is partially related to #858 but, the goal is not the same.

**Comment by joemcbride** [comment]
Other JavaScript clients, such as Apollo, also use graphql-tag, though they convert it back to a query before sending it to the server.  Sending a json payload of the AST is going to be a much larger payload than just the Schema syntax.  I don’t think this is a feature that fits with the goals of this project.  It would be possible for you to convert the AST json to this project’s Document AST and pass that to the Executor.  The ExecutionOptions allows you to pass a pre-populated Document.  There are other aspects that expect there to be the raw query (such as line/column numbers in errors).

**Comment by lanwin** [comment]
Thanks for your answer. Your are right, I think I misunderstood what the persistent AST is used for.
