### ISSUE TITLE
Performance improvements (#805) causes ExecutionError: Cannot return null for non-null type.

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-dotnet#871]
So we updated to 2.3 and started getting an exception when a client is asking for an introspection query.

```
GraphQL.ExecutionError
  HResult=0x80131500
  Message=Cannot return null for non-null type. Field: type, Type: __Type!.
  Source=GraphQL
  StackTrace:
   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node)
  in GraphQL\Execution\ExecutionStrategy.cs:line 270
```

![image](https://user-images.githubusercontent.com/122666/47330433-f6a86d00-d6c3-11e8-9d26-f5e2bb260e65.png)

We made no other changes to our code base.

Through a process of elimination i isolated it to this commit

https://github.com/graphql-dotnet/graphql-dotnet/commit/952b4ef6950e51bbfe009354f0520180c343e8d4

I can reproduce in our solution , so if anyone has ideas let me know and i can verify them. I have not managed to repro in a stand alone (smaller) solution yet.

**Comment by SimonCropp** [comment]
ok this fixed it. but i have no idea why https://github.com/SimonCropp/GraphQL.EntityFramework/commit/a7737df9d6d79e03268fa72f6910b68dbe24665a

**Comment by joemcbride** [comment]
@SimonCropp Do you think you were perhaps hitting #873 ?

**Comment by SimonCropp** [comment]
i dont see how given this was the argument that caused it to happen https://github.com/SimonCropp/GraphQL.EntityFramework/commit/a7737df9d6d79e03268fa72f6910b68dbe24665a#diff-42e8db515530f05df18eb7b2fa6b852dR35

happy to be corrected :)
