### ISSUE TITLE
Who is using this is production ?

### ISSUE THREAD

**Issue by abhikmitra** [graphql-dotnet/graphql-dotnet#874]
Is there a list of companies who is using this in production ? It would also be good to see if any company is officially backing this ?

**Comment by joemcbride** [comment]
There are a lot of companies using this in production, though there are no companies directly backing  this project.  There are several indirectly supporting it by allowing their developers time to work on features and fix bugs.

**Comment by ivaxi** [comment]
Hey. We plan to use it in the existing government project of document flow for the whole country - Ukraine. Some parts already on it.

**Comment by AmbroiseCouissin** [comment]
We use it in prod. No regret. Amazing library.

**Comment by abhikmitra** [comment]
Awesome ,probably it would be good to have a section in the readme called "Built with GraphQLDotNet"

**Comment by joemcbride** [comment]
OrchardCMS is currently using it.

https://twitter.com/bleroy/status/1057406453827297280

**Comment by alexolex** [comment]
[We are using](https://medium.com/@henrypuh/graphql-what-you-always-wanted-but-never-dared-to-query-67ce6440b742) it heavily on production. graphql-dotnet framework is pretty friendly to use.

**Comment by SimonCropp** [comment]
Also using in production. Closing this one. Seems have served its purpose
