### ISSUE TITLE
Schema first mutation

### ISSUE THREAD

**Issue by baig316-adfenix** [graphql-dotnet/graphql-dotnet#876]
Hi,
Can you please tell me how to implement schema-first mutation? I have the schema as follows:

```
              type Mutation {
                sendInvite(campaignId: ID! propertyId: ID! email: String!): Boolean!
              }

              schema {
                query: Query
                mutation: Mutation
              }
```

**Comment by joemcbride** [comment]
Syntax for a mutation is the exact same syntax for a query.  The only difference is having the `Mutation` name vs. `Query`.

**Comment by baig316-adfenix** [comment]
And how would we cater for custom input types as arguments to the mutation when those custom input types also include nested custom types.

**Comment by baig316-adfenix** [comment]
Got it working.

**Comment by bgoerdt** [comment]
@baig316-adfenix can you post an example of how to do custom input types with schema-first?
