### ISSUE TITLE
Q: Organize query with dependency injection?

### ISSUE THREAD

**Issue by Marsellus47** [graphql-dotnet/graphql-dotnet#878]
Is there a way how to organize queries including dependency injection?
Example at https://graphql-dotnet.github.io/docs/getting-started/query-organization/ shows how to organize queries to multiple ObjectGraphType, but what if I need for example inject the DbContext into AccountGroupGraphType? I can inject DbContext into Query, but when I try to inject DbContext into AccountGroupGraphType I get runtime error saying that there is no parameterless constructor in AccountGroupGraphType.

**Comment by joemcbride** [comment]
You need to add those types to your DI Container so it can construct the objects.  By default it uses `Activator.CreateInstance`.

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection

**Comment by Marsellus47** [comment]
Thank you very much.
The problem wasn't in missing DI settings, but in not passing IDependencyResolver to my Schema.
