### ISSUE TITLE
SDK compatibility

### ISSUE THREAD

**Issue by narbit** [graphql-dotnet/graphql-dotnet#880]
The global.json file is locking dev environment to SDK version 2.1.302. If this exact SDK version is not installed on user's machine, solution doesn't compile and throws various messages for each included project along the lines:

_The current .NET SDK does not support targeting .NET Standard 2.0. Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0._

In my environment I don't have 2.1.302 but have lower and higher SDK versions. Deleting global.json allowed me to compile.

[According to MS](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json), "In general, you want to use the latest version of the tools, so no global.json file is needed."

Proposing to drop this file in one of the future releases.

**Comment by narbit** [comment]
Unfortunately I don't have any AppVeyor experience. Searching for any yml-based non-PS solutions didn't produce any good leads. It appears as though AppVeyour explicitly supports .NET Core SDK 2.1.402, same version I was able to compile against locally after pulling global.json out. Wouldn't it just work the same way in AppVeyor?

**Comment by RehanSaeed** [comment]
Relying on AppVeyor to have the right version of the SDK is flaky at best (They take a while to update). I use the following line in my yaml to ensure the correct version is installed:

```
- ps: choco install dotnetcore-sdk --no-progress --confirm --version 2.1.301
```

AppVeyor has chocolatey installed by default.

**Comment by joemcbride** [comment]
@RehanSaeed Agreed, that's a simple enough change for me.
