### ISSUE TITLE
Expose IAstFromValueConverters Registered with Schema

### ISSUE THREAD

**Issue by abarger-bss** [graphql-dotnet/graphql-dotnet#885]
## Summary

It would be nice if all IAstFromValueConverters registered with a Schema were made available in a public, 
 read-only collection on Schema. These seem to be the only types the user can register that aren't made available this way.

### Basic example

```
public class Schema
{
    //All Existing functionality...

    public IEnumerable<IAstFromValueConverter> ValueConverters { get; }
}
```
### Motivation

I'm writing a utility to allow for the definition of 'partial schemas' that can be rolled up into a single composite. The structure of Schema makes this trivial for the most part, but the lack of access to Value Converters means I can't register these in my composite without resorting to reflection.

**Comment by sungam3r** [comment]
@abarger-bss Fix will be published in v4 soon.
