### ISSUE TITLE
filter, first, orderby support

### ISSUE THREAD

**Issue by alexdpars** [graphql-dotnet/graphql-dotnet#886]
Hi, 
I am currently experimenting with graphQL and find it great! However, I was expecting it to support features as filter, orderby, first out of the box. Are theses features that are meant to be on the client side or server side? To me it looks like odata for .net rest API which is a server side feature. 

[There ](https://lucasconstantino.github.io/graphiql-online/) is an example that implement it. as you can see in this example the features even are in intelisense.

Is this because theses features aren't supported in the .net implementation yet?

My environment: windows 10, VS 2017 enterprise
I used graphql nuget version 2.3.0.

**Comment by joemcbride** [comment]
> Is this because theses features aren't supported in the .net implementation yet?
> filter, orderby, first

Those features are not part of the GraphQL spec.  To support those features you have to build them yourself.  Since this project is Data-Source Agnostic, there are no plans to try to provide this type of functionality.
