### ISSUE TITLE
Conflict between System.Reactive.Core 3.1.1 and System.Reactive 4.0.0

### ISSUE THREAD

**Issue by RPHEngineering** [graphql-dotnet/graphql-dotnet#887]
I'm getting conflicts between System.Reactive.Core 3.1.1 in your NuGetpackage and System.Reactive 4.0.0 in another. I get the following build errors:

Error CS0121: The call is ambiguous between the following methods or properties: 'System.Reactive.Linq.Observable.GetAwaiter<TSource>(System.IObservable<TSource>)' and 'System.Reactive.Linq.Observable.GetAwaiter<TSource>(System.IObservable<TSource>)' (CS0121)

Error CS0121: The call is ambiguous between the following methods or properties: 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>, System.Action<T>)' and 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>, System.Action<T>)' (CS0121)

This package references System.Reactive.Core 3.1.1 and the other references System.Reactive 4.0.0. What would be the process to either upgrade System.Reactive.Core in your project to the latest version that no longer has this conflict or for me to somehow deal with it in my solution. All of the solutions I've found so far are meant for people who reference the packages directly, not through a third party.

thanks!

**Comment by joemcbride** [comment]
It looks like 4.0.0 only supports netstandard2.0 and net46, so we may have to either target 4.0.0 for just nestandard2.0 or drop support for netstandard1.x and net45.  It is currently planned to drop support for netstandard1.x and net45 in version 3 of this project.

Have you tried manually adding a `PackageReference` for `System.Reactive.Core` to your project with the 4.0.0? version?

```
<PackageReference Include="System.Reactive.Core" Version="4.0.0" />
<PackageReference Include="System.Reactive.Linq" Version="4.0.0" />
```

**Comment by RPHEngineering** [comment]
What's the timeframe like on version 3? 

No dice with adding System.Reactive.Core. 

There's actually a System.Reactive.Compatibility package that the Reactive guys made for just this scenario but when I add it I get into another problem. 

Android give me this error: 

> Error XA2002: Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `System.Reactive`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `System.Reactive`. (XA2002)

iOS gives me this error: 

> Error MT2001: Could not link assemblies. Reason: Error while processing references of 'Lynkd.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (MT2001)

I have tried adding "System.Threading.Tasks.Extensions" directly and I get this when I try to add it: 

> Detected package downgrade: System.Threading.Tasks.Extensions from 4.5.1 to 4.5.0. Reference the package directly from the project to select a different version. 
>  Lynkd (>= 1.0.0) -> System.Reactive.Compatibility (>= 4.1.2) -> System.Reactive.Interfaces (>= 4.1.2) -> System.Threading.Tasks.Extensions (>= 4.5.1) 
>  Lynkd (>= 1.0.0) -> System.Threading.Tasks.Extensions (>= 4.5.0)
> Detected package downgrade: System.Threading.Tasks.Extensions from 4.5.1 to 4.5.0. Reference the package directly from the project to select a different version. 
>  Lynkd (>= 1.0.0) -> System.Reactive.Compatibility (>= 4.1.2) -> System.Reactive.Core (>= 4.1.2) -> System.Threading.Tasks.Extensions (>= 4.5.1) 
>  Lynkd (>= 1.0.0) -> System.Threading.Tasks.Extensions (>= 4.5.0)
> Detected package downgrade: System.Threading.Tasks.Extensions from 4.5.1 to 4.5.0. Reference the package directly from the project to select a different version. 
>  Lynkd (>= 1.0.0) -> System.Reactive.Compatibility (>= 4.1.2) -> System.Reactive.Linq (>= 4.1.2) -> System.Threading.Tasks.Extensions (>= 4.5.1) 
>  Lynkd (>= 1.0.0) -> System.Threading.Tasks.Extensions (>= 4.5.0)
> Detected package downgrade: System.Threading.Tasks.Extensions from 4.5.1 to 4.5.0. Reference the package directly from the project to select a different version. 
>  Lynkd (>= 1.0.0) -> System.Reactive.Compatibility (>= 4.1.2) -> System.Reactive.PlatformServices (>= 4.1.2) -> System.Threading.Tasks.Extensions (>= 4.5.1) 
>  Lynkd (>= 1.0.0) -> System.Threading.Tasks.Extensions (>= 4.5.0)
> Detected package downgrade: System.Threading.Tasks.Extensions from 4.5.1 to 4.5.0. Reference the package directly from the project to select a different version. 
>  Lynkd (>= 1.0.0) -> System.Reactive.Compatibility (>= 4.1.2) -> System.Reactive.Providers (>= 4.1.2) -> System.Threading.Tasks.Extensions (>= 4.5.1) 
>  Lynkd (>= 1.0.0) -> System.Threading.Tasks.Extensions (>= 4.5.0)

**Comment by joemcbride** [comment]
No timeframe for 3.0.

Looks like that's complaining about downgrading packages, so may have to pick a higher package version than what you chose?

**Comment by joemcbride** [comment]
Question though ... doesn't seem like you should be referencing this project from Android or iOS?  Are you using the [graqphl-client](https://github.com/graphql-dotnet/graphql-client) project?

**Comment by RPHEngineering** [comment]
ah, that was the real answer I needed :) Brand new to GraphQL so still fumbling around a bit

**Comment by joemcbride** [comment]
Gotcha - yes the GraphQL nugget is for building your own GraphQL server.  You’ll want that client project for calling an existing GraphQL server.

**Comment by joemcbride** [comment]
Going to close this, let us know if you have more questions.

**Comment by NZSmartie** [comment]
Hey @joemcbride 

Regarding your comment:
> It looks like 4.0.0 only supports netstandard2.0 and net46, so we may have to either target 4.0.0 for just nestandard2.0 or drop support for netstandard1.x and net45. It is currently planned to drop support for netstandard1.x and net45 in version 3 of this project.

With the recent move to .Net Standard 2.0 in #969, there is no-longer any need to be backwards compatible and can upgrade System.Reactive from `v3.1.1` to >= `v4.0.0`

Would you think it's now suitable to update to this version or is there other reasons to keep System.Reactive at `v3.1.1`?

**Comment by stephenlautier** [comment]
@joemcbride  Any updates on this one? It makes Rx quite problematic to use due to this

**Comment by joemcbride** [comment]
The latest 3.0 preview is now updated to 4.0.0.
