### ISSUE TITLE
How to deprecate a field?

### ISSUE THREAD

**Issue by ManuelDeLeon** [graphql-dotnet/graphql-dotnet#89]
I may be doing something wrong. I'm trying to deprecate a value the following way:

```
            var score = Field< IntGraphType>("Score", "Score.");
            score.DeprecationReason = "We don't need it";
```

But Score shows up in GraphiQL (docs say it should hide it by default) and no warning of any kind.

How do you deprecate a field and what should I expect to see in GraphiQL?

**Comment by joemcbride** [comment]
The `deprecatedReason` and `isDeprecated` values will be sent through introspection.  It currently appears that GraphiQL doesn't provide an error if a field is deprecated.

![image](https://cloud.githubusercontent.com/assets/255007/15846727/beb9da3c-2c34-11e6-94d2-1975a2506702.png)

Field spec: http://facebook.github.io/graphql/#sec-Object-Field-deprecation
> Fields in an object may be marked as deprecated as deemed necessary by the application. It is still legal to query for these fields (to ensure existing clients are not broken by the change), but the fields should be appropriately treated in documentation and tooling.

Introspection spec: http://facebook.github.io/graphql/#sec-Deprecation
> To support the management of backwards compatibility, GraphQL fields and enum values can indicate whether or not they are deprecated (isDeprecated: Boolean) and a description of why it is deprecated (deprecationReason: String).
> Tools built using GraphQL introspection should respect deprecation by discouraging deprecated use through information hiding or developer‐facing warnings.

**Comment by tlil87** [comment]
Interesting - has this changed in the latest version of GraphiQL? In the past, deprecated fields have been hidden to me in GraphiQL.

**Comment by joemcbride** [comment]
I'm not sure about in the past, though they're showing up currently for me.  Possibly related to https://github.com/graphql/graphiql/issues/34

**Comment by tlil87** [comment]
Yes, seems to have changed in later versions.

**Comment by ManuelDeLeon** [comment]
Seems like GraphiQL changed. Closing this one. Thanks.
