### ISSUE TITLE
Sample code using new IDocumentWriter.WriteAsync operation

### ISSUE THREAD

**Issue by SapphireBrand** [graphql-dotnet/graphql-dotnet#894]
## Summary
Sample code from https://github.com/graphql-dotnet/examples/blob/master/src/AspNetWebApi/Example/Controllers/GraphQLController.cs shows a call to WriteAsync that (IIRC) used to return string but now returns IByteResult. So the  old way to set response.Content no longer works.

## Relevant information
The snippet is here:

```
var json = await _writer.WriteAsync(result);

var response = request.CreateResponse(httpResult);
response.Content = new StringContent(json, Encoding.UTF8, "application/json");
```

json was declared as string, but is now IByteResult. The StringContent call is expecting string. The contents of an IByteResult contain a structure with an ArraySegment<byte>, and it is not obvious how to turn that into a string.

But in any case perhaps the right answer is to use the new API _writer.WriteAsync(Stream, T)?

Relevant PR: https://github.com/graphql-dotnet/graphql-dotnet/pull/809

**Comment by joemcbride** [comment]
> But in any case perhaps the right answer is to use the new API _writer.WriteAsync(Stream, T)?

Yes, that would be the route to take.  There is a `WriteToStringAsync` too if you still want the direct JSON.

**Comment by sungam3r** [comment]
Current version of `IDocumentWriter`: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/IDocumentWriter.cs
