### ISSUE TITLE
Complexity depth seem to ignore every level under interfaces and unions?

### ISSUE THREAD

**Issue by sommarlov** [graphql-dotnet/graphql-dotnet#895]
**complexity level of 2, working case**
```
level1 {
  level2 {
    level3{ ... }
  }
}
```
=> "Query is too nested to execute"

**complexity level of 2, case with interface or union**
```
level1 {
  ...on Level2 {
    level3 {
      level4 {
        level5 { this can go on forever }
      }
    }
  }
}
```
=> goes through, no errors

May or may not be related to #344 ?

Version 2.3.0

**Comment by sommarlov** [comment]
I'm closing this, it was fixed when I added IsTypeOf to my implementations and removed some registrations from my schema.

Maybe this is not strange, but if have any fields in the graph that resolves an implementation of an interface (Field<SomeImplementationOfAnInterface>) , the implementations should not be registered on the schema with RegisterType or middlewares will ignore it for whatever reason. If I on the other hand only use the interface on fields (Field<SomeInterface>) , and never the implementation, I need to Register it.

**Comment by joemcbride** [comment]
You CAN pre-register the type if you wish.  But you are required to register it if you only expose the interface/union in the Schema.  IsTypeOf or ResolveType is also required when working with interfaces and unions.

https://graphql-dotnet.github.io/docs/getting-started/interfaces

**Comment by joemcbride** [comment]
That should be impossible.  If you did not have IsTypeOf or ResolveType properly setup that would happen though.
