### ISSUE TITLE
Need Advice - How to extract request headers and pass it to the business logic in case of asp.net core 2 graphql endpoint?

### ISSUE THREAD

**Issue by santoshpatro** [graphql-dotnet/graphql-dotnet#896]
Hi Joe,

I need some help on what is the best method to how to read the request headers  and pass it to the resolve method .
I tried to follow the details mentioned in the link below and mentioned all the details that I have tried based on the inputs.
https://github.com/graphql-dotnet/graphql-dotnet/issues/287

I also posted the question at https://stackoverflow.com/questions/53177945/how-to-extract-request-headers-and-pass-it-to-the-business-logic-in-case-of-asp

Can you please provide your guidance with some code examples to fix this issue?

Thanks,
Santosh

**Comment by joemcbride** [comment]
Posted answer on StackOverflow.  Short answer:  use `IHttpContextAccessor`.

**Comment by santoshpatro** [comment]
Thanks a lot Joe for your help 👍
