### ISSUE TITLE
AutoRegisteringObjectGraphType Override AutoGenerated Fields

### ISSUE THREAD

**Issue by drowhunter** [graphql-dotnet/graphql-dotnet#897]
So I was digging around the code and noticed that there was a class called **AutoRegisteringObjectGraphType**

It automagically infers fields from my POCO's

I was shocked because I was doing this manually, and saw no mention of this feature in the documentation.

Question:  If using Auto Generation can I override the generated fields for the properties that I want to take control of?

**Comment by drowhunter** [comment]
also what if i want to remove one of the autogenerated fields

**Comment by joemcbride** [comment]
@drowhunter No, there is currently no way to customize its behavior.  If you need to customize the behavior I would copy the source into your own project and customize as needed.

**Comment by drowhunter** [comment]
it seems that when poco contains an enumeration it doesnt map correctly.  And without a way to override field you cant correct it.

**Comment by joemcbride** [comment]
Yes, it will only work for very niche cases.  You _may_ be able to get it to work with your specific enumeration type by registering it:

```csharp
GraphTypeTypeRegistry.Register(typeof(MyEnum), typeof(MyEnumGraphType));
```

**Comment by drowhunter** [comment]
I looked at the source code and realized that before you mentioned it.  Is this documented anywhere?

And I added generic versions of the register and get method and submitted a pull request

[Pull Request - Generic versions of Register and Get Methods](https://github.com/graphql-dotnet/graphql-dotnet/pull/908)

I put the following code into my project in the StartUp

`
GraphTypeTypeRegistry.Register<MyEnum,MyEnumGraphType>();
`

**Comment by drowhunter** [comment]
Are you aware of the GraphQL Library called [HotChocolate](https://hotchocolate.io/docs/code-first-resolvers)  ?

the way they handle overriding field is the following

- rather than configuring your fields in the constructor, you configure them by overriding the Configure() Method
- there is a property you can set which turns autogeneration on or off in the constructor
- any fields defined in override will use that implementation instead of being auto generated
- adding Ignore on to the field causes that property to be  skipped when auto generating

code sample
```
public class PersonType : ObjectType<Person>
{
    protected override void Configure(IObjectDescriptor<Person> desc)
    {
        desc.Field(t => t.FriendIds).Ignore();
        desc.Field<PersonResolver>(t => t.GetFriends(default, default));
    }
}
```
[Documentation](https://hotchocolate.io/docs/code-first-resolvers)

I may try to do something like this on my fork. Because as it is the autogeneration isn't very useful, as I do not want to expose every single field, or may need to override a field so that i can use a custom resolver

**Comment by joemcbride** [comment]
> I looked at the source code and realized that before you mentioned it. Is this documented anywhere?

I do not believe it is.

> Are you aware of the GraphQL Library called HotChocolate ?

I am aware of that project and yes the way they have designed the field registration has some perks that this project does currently not.

**Comment by drowhunter** [comment]
I am currently in the process of choosing which project to go with for my graphql server and it was a very close race between this and hot chocolate,  but this library won out because it is more streamlined with the way the resolvers are defined and handles asynchronous methods better.

The auto resolve is the only area in which Hot chocolate is better.

**Comment by drowhunter** [comment]
oh and i just noticed that you accepted my pull request? how long before it shows up on the nuget package ?

**Comment by sungam3r** [comment]
Now [AutoRegisteringObjectGraphType](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/AutoRegisteringObjectGraphType.cs) supports customizations. `RemoveField` method is no longer required.

Is this issue and PR still actual?

**Comment by ndglover** [comment]
I have tried using the very helpful AutoRegisteringObjectGraphType. One thing I've noticed though is it seems to break the introspection query. This means you can't use GraphiQL to discover the schema and types etc. Am I missing something here or is this an issue?

**Comment by sungam3r** [comment]
Could you please give an example of such a schema?

**Comment by sungam3r** [comment]
@drowhunter Is this issue still actual?

**Comment by ndglover** [comment]
Not for me. Feel free to close from my perspective

**Comment by sungam3r** [comment]
Closed as resolved. Feel free to reopen if not.
