### ISSUE TITLE
Need some help - How to wrap Graphql endpoint responses(in .net core) for consistency?

### ISSUE THREAD

**Issue by santoshpatro** [graphql-dotnet/graphql-dotnet#898]
Hi Joe,
Again I need your help on this issue. I need to return a consistent response with a similar structure returned for all requests. In the previous .NET web api, I was able to achieve this using DelegatingHandler (MessageHandlers). So basically the json response will be in this kind of structure :

Here locale {}, authorised, userMessage (in bold text) needs to be returned with every graphql endpoint response.
{
  "countries": [
    {
      "pngimagePath": "https://test.com/api/tax/v1/country/Country1/4/image/FlagPNG",
      "svgimagePath": "https://test.com/api/tax/v1/country/Country1/405/image/FlagSVG",
      "displayName": "Country1",
      "displayNameShort": "Country1",
      "providerName": "Testing",
      "providerTerms": null,
      "uuid": "1",
      "name": "Country1",
      "path": "Country1",
      "completeResponse": true
    },
    {
      "pngimagePath": "https://test.com/api/tax/v1/country/Country2/5/image/FlagPNG",
      "svgimagePath": "https://test.com/api/tax/v1/country/Country2/406/image/FlagSVG",
      "displayName": "Country2",
      "displayNameShort": "Country2",
      "providerName": "Testing one",
      "providerTerms": null,
      "uuid": "2",
      "name": "Country2",
      "path": "Country2",
      "completeResponse": true
    }
  ],
  **"locale": {
    "localisationIdentifier": "en",
    "enabled": true,
    "language": "en",
    "country": "",
    "description": "English",
    "uuid": "37",
    "name": "English",
    "path": "/locales/en",
    "rightToLeft": false,
    "completeResponse": true,
    "scriptDirection": "ltr"
  },
  "authorised": false,
  "userMessage": ""**
}

In the existing REST API code I have a Delegating handler used to extend the result of REST API call with additional data which in this case is add localization data to the response.Since Delegating handler are no more supported in asp.net core 2. I am trying to migrate the existing Delegating handler to Middleware component. How to migrate the existing Delegating handler to Middleware component in this case? Any code sample will help me here.

For reference purpose I followed the details mentioned at : Extending WebApi response using OWIN Middleware and https://www.devtrends.co.uk/blog/wrapping-asp.net-web-api-responses-for-consistency-and-to-provide-additional-information

On running the below code and navigating to the url:http://localhost:5000/graphql/ and trigger the below query, I see that control execution goes to the GraphQLController post method and never hits back to the middleware code present in the Startup.cs 

{
  result {
    countries {
      uuid
      displayName
      displayNameShort
      pNGImagePath
      sVGImagePath
      path
      completeResponse
      providerName
    }
    locale {
      localisationIdentifier
      enabled
      language
    }
    authorized
    userMessage
  }
}

// Code

```
[Route("[controller]")]
public class GraphQLController : Controller
{
	private readonly IDocumentExecuter _documentExecuter;
	private readonly ISchema _schema;
	public GraphQLController(ISchema schema, IDocumentExecuter documentExecuter)
	{
		_schema = schema;
		_documentExecuter = documentExecuter;
	}

	[HttpPost]
	public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
	{
		if (query == null)
		{
			throw new ArgumentNullException(nameof(query));
		}

		var inputs = query.Variables.ToInputs();
		var executionOptions = new ExecutionOptions{Schema = _schema, Query = query.Query, Inputs = inputs, UserContext = Request.Headers, //UserContext = new GraphQLUserContext { Headers = Request.Headers }
 };
		var result = await _documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);
		if (result.Errors?.Count > 0)
		{
			return BadRequest(result);
		}

		return Ok(result);
	}
}

public class TestSchema : GraphQL.Types.Schema
{
	public TestSchema(IDependencyResolver resolver): base (resolver)
	{
		Query = resolver.Resolve<TestQuery>();
	}
}

public class TestQuery : ObjectGraphType<object>
{
	public TestQuery(ITestService testService)
	{
		Field<TestResultType>("result", resolve: context =>
		{
			return testService.GetDetailsForLocation("en");
		}

		, description: "All location data");
	}
}

public class TestResultType : ObjectGraphType<TestResult>
{
	public TestResultType()
	{
		Field<ListGraphType<TestDTOType>>("countries", resolve: context =>
		{
			return context.Source.Countries;
		}

		);
		Field<LocaleType>("locale", resolve: context =>
		{
			return context.Source.Locale;
		}

		);
		Field(x => x.Authorized);
		Field(x => x.UserMessage, nullable: true);
	}
}

public class TestResult : APIResult
{
	publicTestResult()
	{
		Countries = new List<CountryDTO>();
	}

	public List<CountryDTO> Countries
	{
		get;
		set;
	}
}

public class APIResult
{
	public Locale Locale
	{
		get;
		set;
	}

	[JsonProperty("authorised")]
	public bool Authorized
	{
		get;
		set;
	}

	public string UserMessage
	{
		get;
		set;
	}

	= "";
}

public class Locale
{
	public string LocalisationIdentifier
	{
		get;
		set;
	}

	public bool Enabled
	{
		get;
		set;
	}

	public string Language
	{
		get;
		set;
	}

	public string country
	{
		get;
		set;
	}

	public string Description
	{
		get;
		set;
	}

	public string Uuid
	{
		get;
		set;
	}

	public string Name
	{
		get;
		set;
	}

	public string Path
	{
		get;
		set;
	}

	public bool RightToLeft
	{
		get;
		set;
	}

	public bool CompleteResponse
	{
		get;
		set;
	}

	public string ScriptDirection
	{
		get
		{
			return RightToLeft ? "rtl" : "ltr";
		}
	}

	public Locale(Language language)
	{
		var locale = !string.IsNullOrWhiteSpace(language.Locale) ? language.Locale : language.LocalisationIdentifier;
		LocalisationIdentifier = locale;
		Name = language.Name;
		Uuid = language.LanguageId.ToString();
		Enabled = true;
		Language = locale.Contains('-') ? locale.Split('-')[0] : locale;
		country = locale.Contains('-') ? locale.Split('-')[1] : string.Empty;
		CompleteResponse = true;
		Path = "/locales/" + locale;
		Description = language.Name;
		RightToLeft = language.RightToLeft;
	}

	public Locale()
	{
	}
}
```

I also posted the question at https://stackoverflow.com/questions/53214456/how-to-wrap-graphql-net-endpoint-response-using-asp-net-core-2-middleware
I have tried a lot but no success until now. Any help on this is much appreciated?

**Comment by santoshpatro** [comment]
Hi Joe,

Getting stuck  through some errors to get it half-working, but was wondering if we could get an example with some code sample on this issue.

I have been trying a lot but nothing working.
Any help is much appreciated. 

Thanks,
Santosh

**Comment by yoDon** [comment]
This seems like you're fighting hard against a core concept of GraphQL. If the client needs those fields, it should ask for them, which would I think make your problem go away. If you don't want to list those fields manually in all your requests, use a fragment or some other client side tool tool to add them automatically.

**Comment by santoshpatro** [comment]
Thanks for your response. Sorry I am not able to follow you here. Can you please help me with some code sample to understand it in better.

**Comment by SimonCropp** [comment]
@santoshpatro did u end up solving this?

**Comment by sungam3r** [comment]
Agree with @yoDon. It should be noted that you can use extensions to return arbitrary data in response. See https://graphql.github.io/graphql-spec/June2018/#sec-Response

**Comment by SimonCropp** [comment]
closing due to no respsone
