### ISSUE TITLE
Passing data down the tree

### ISSUE THREAD

**Issue by PascalSenn** [graphql-dotnet/graphql-dotnet#899]
I'm gonna open a new issues specifically for that. #637

What about this scenario. Our API is scoped. We have an array of customers that we'd like to resolve. 
Underneath the customer node we have a fairly deep graphql tree. 
As far as i know the only way to pass down properties is to drill them down the tree.
```csharp
           FooBarModel  Customer(string customer).getFooBar();
                    ->  FooBarModelDeep FooBarModel(string customer).GetFooBarModelDeep();
```
That leads to unnecessary models and a higher complexity over all. 

```graphql
query Sample($f: [String]){
    foo {
        customers(f: $f) {
            fooBar {
               fooBarDeep {
                      name
                   }
            }
        }
    }
}
``` 

input ["FirstEntry", "SecondEntry"]  
result:
```
{
   foo: {
       customers: [
          {
               fooBar: {
                    fooBarDeep: {
                          name:"FirstEntry"
                    }
               }
          },
             {
               fooBar: {
                    fooBarDeep: {
                          name:"SecondEntry"
                    }
               }
          }

        ]
    }
}
```

Is there a way around it?

**Comment by joemcbride** [comment]
Yes there is currently nothing in place to access the parent values multiple levels up.  This may be available in the Node structure that is used with DataLoader (if I’m remembering correctly) but that is currently not exposed to consumers of the API.

**Comment by sungam3r** [comment]
> As far as i know the only way to pass down properties is to drill them down the tree.

Or vice versa, climb up the tree. @PascalSenn please check out #2295

**Comment by sungam3r** [comment]
@PascalSenn Fixed after more then 2 years 😄 . #2295 was merged and will be published in the v4 release.
