### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#9]

**Comment by SaltyDH** [comment]
This is far from a complete solution but I've had an initial go at introducing mutations.
There's some hacks with how the Input object coercion works using JSON.NET.

I’d also add I haven’t spent a great deal of time looking at the GraphQL spec.

If anyone’s interested, the fork is here.
https://github.com/SaltyDH/graphql-dotnet

**Comment by srt0422** [comment]
Thanks for putting out this attempt.  I look forward to trying it out.

This would be a comment applicable to all of the forks, but if you could update the readme so that your roadmap represents the state of your fork, that would make it a lot easier to see what's different in each of the forks.

**Comment by srt0422** [comment]
I'm having a hard time finding the actual code that implements a mutation.  Could you include something in the readme, so I can know what I'm looking at please?

**Comment by joemcbride** [comment]
Thanks for taking a stab at this, I'll take a closer look.  Note that this project uses [Fixie for Unit testing](http://fixie.github.io/), so the references to NUnit would need to be removed and tests should follow [the defined conventions](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/CustomConvention.cs).

**Comment by SaltyDH** [comment]
@srt0422 Key changes are found in the DocumentExecutor, GraphType, InputObjectGraphType and ResolveFieldContext. The example implementation of a Mutation is found in the StarWarsMutations class in the Test project with (at this stage) a single accompanying test in the StarWarsBasicMutationTests class. I definitely thought about ticking the Mutations box on the roadmap but felt it was a little premature - I haven't validated that mutations produce the correct introspection responses or anything like that.

@joemcbride Appreciate the feedback on the unit testing side of things. I knew when I pulled in NUnit that I'd need to remove that. Really just a time saver with built in test runner support for NUnit in Resharper. I'll definitely take a look at the conventions more closely so I adhere to that with future tests.

**Comment by joemcbride** [comment]
I'm a resharper user as well - unfortunately the fixie runner only works with ~8.0.  I use a combo of the built-in testing and testdriven.net.

**Comment by joemcbride** [comment]
@SaltyDH Thanks for your initial work on this.  I'm going to close this issue as mutations themselves do work, as verified in 3760633.  I'm going to use some of your ideas for work on Input Objects #12
