### ISSUE TITLE
Different DI scope between controller and query?

### ISSUE THREAD

**Issue by wpatter6** [graphql-dotnet/graphql-dotnet#900]
## Summary
When I use standard dotnet core dependency injection to add a scoped class into my mvc controller class, a different object is passed into my query object.  It seems that a different scope is used to instantiate the Query than is used for Controller.

Is this expected behavior and/or is there some way to make these share the same scope?

Thank you.

### Environment (if relevant)
* v2.3.0
* dotnet core
* Windows 10

**Comment by wpatter6** [comment]
Ok good to know, thank you

**Comment by joemcbride** [comment]
Closing as this is related to #648
