### ISSUE TITLE
The role of Serialize in a ScalarGraphType

### ISSUE THREAD

**Issue by shoooe** [graphql-dotnet/graphql-dotnet#901]
## Summary

I don't understand the role of the method `Serialize` within a ScalarGraphType. In the original JS reference implementation there's the same distinction of `serialize`, `parseValue` and `parseLiteral`. As described there they make sense: `parseX` is used for parsing inputs, `serialize` is used to serialize as output.

Here instead we have `Serialize` which is often implemented as:

        public override object Serialize(object value)
        {
            return ParseValue(value);
        }

and apparently gets called both with the raw value of the input (string, double, whatever) and also with the built value that needs to be serialized as output.

I don't understand why would `Serialize` be called for reading the value of an argument. 
Also I don't understand why `Serialize` would be implemented exactly like `ParseValue`.

Can anybody help clarifying this?

**Comment by andrewtyped** [comment]
I'm still reviewing this part of the code myself but I'll give it a shot.

Starting with your second question: GraphQL.NET serialization happens in 2 stages
- Query fields are [resolved](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionStrategy.cs#L14). Assuming no errors occur, their results are aggregated into a .NET object which is assigned to `ExecutionResult.Data`.
- The `ExecutionResult` will eventually be passed to `IDocumentWriter.WriteAsync`, either by your own code or one of the [middleware](https://github.com/graphql-dotnet/server/blob/develop/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L126) implementations. The default implementation of `IDocumentWriter` just serializes `ExecutionResult.Data` to JSON.

`ScalarGraphType.Serialize` handles the first step. `Serialize` will be passed the output of a resolver, and I think usually `Serialize` will output the same type as the resolver. This is why most `Serialize` implementations call `ParseValue`, which in turn usually calls `ValueConverter.ConvertTo`. `ConvertTo` performs no action if the provided value is already of the requested type - so `Serialize` often returns very quickly. I think you would only serialize to a different type if you didn't want the client to see the default JSON representation of your scalar. [TimeSpanSecondsGraphType](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/TimeSpanSecondsGraphType.cs) gives an example of this sort of alternative serialization.

For your first question... I am not sure why `Serialize` is called when reading arguments either. Note that `Serialize` is only called for arguments passed in JSON query variables, and not for literals in the GraphQL query itself. The goal is clear - the library wants to convert the value from JSON to a .NET type to an AST (see [GraphQLExtensions.AstFromValue](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/GraphQLExtensions.cs#L362). But it does seem like using the same method call for input and output like this confuses the issue - In this context the operation seems more like deserialization than serialization to me.

**Comment by sungam3r** [comment]
@andrewtyped You're right. Everything is exactly as you say.
