### ISSUE TITLE
In graphql-dotnet, how we can get projected field names from ResolveFieldContext

### ISSUE THREAD

**Issue by hasibul2363** [graphql-dotnet/graphql-dotnet#903]
I am new in Graphql and using graphql-dotnet in my asp.net core project. Consider I have written a query like following.
```
restaurants {
    id
    name
}
```
Now I want to get this field names from `ResolveFieldContext`. Is there any way to get this filed names?
Expecting your valuable help.

Also posted a question on [stackoverflow](https://stackoverflow.com/questions/53249630/in-graphql-dot-net-how-we-can-get-projected-filed-names-from-resolvefieldcontext).

**Comment by joemcbride** [comment]
See SubFields on ResolveFieldContext.

**Comment by hasibul2363** [comment]
@joemcbride 
Thank you very much. It works for me.

**Comment by PieterjanDeClippel** [comment]
> @joemcbride Thank you very much. It works for me.

Good for you :thumbsup:
