### ISSUE TITLE
Only one argument is available in ResolveFieldContext when doing multiple mutations.

### ISSUE THREAD

**Issue by joelmandell** [graphql-dotnet/graphql-dotnet#904]
## Description
I have mutations from apollo-client like this:
```json
{
   "operationName":null,
   "variables":{
      "smk":{
         "id":1,
         "ar":2017,
         "period":1,
         "mdelt":3,
         "hdelt":30,
         "arregel":0,
         "frarman":7,
         "tiarman":25,
         "frarkvin":7,
         "tiarkvin":25
      },
      "reg":{
         "id":1,
         "ar":2017,
         "period":1,
         "mlen":60,
         "ledmial":13,
         "lednaral":0,
         "ledbid":0
      },
      "smkh":{
         "id":1,
         "ar":2017,
         "period":1,
         "mdelt":3,
         "hdelt":30,
         "arregel":0,
         "frarman":7,
         "tiarman":25,
         "frarkvin":7,
         "tiarkvin":25
      }
   },
   "query":"mutation ($reg: kfgenreginputtype, $smk: kfsmkinputtype, $smkh: kfsmkinputtype) {
 a: updateKommunfilGenerellaRegler(kfgenreg: $reg) {\n    year\n    __typename\n  }\n  
b: updateKommunfilSammankomstStandardRegler(kfsmk: $smk) {\n    year\n    __typename\n  }\n  
c: updateKommunfilSammankomstHandikappRegler(kfsmk: $smkh) {\n    year\n    __typename\n  }\n}\n"
}
```

The problem is that in the ResolveFieldContext there is only one of the arguments available in the Arguments-dictionary (always the first one). The other variables that is specified as kfsmk in the aliased mutations "b" and "c" is not available.

### Steps to reproduce
Make a mutation with aliased mutations, and with multiple variables for each of them. Only one argument is available in ResolveFieldContext.Arguments

### Expected result

Expect to see arguments to the mutations "updateKommunfilSammankomstStandardRegler" and "updateKommunfilSammankomstHandikappRegler" in the ResolveFieldContext.

### Actual result
There is only one of the arguments available in the Arguments-dictionary (always the first one).

### Environment

Graphql-dotnet v2.3.0, .NET 4.5.2 Windows 10.
I am using latest of apollo-stack with the vue-apollo plugin.

**Comment by joelmandell** [comment]
I am not sure if I describe it well... But I can see 3 variables in ResolveFieldContext.Variables, but not in ResolveFieldContext.Arguments.

**Comment by joemcbride** [comment]
If you need both, why not pass both to the field?

**Comment by joelmandell** [comment]
Excuse me but I don't follow

**Comment by joemcbride** [comment]
Create two arguments in the field so you can pass in two variables as inputs.

**Comment by joelmandell** [comment]
Okay. I don't know if I ever will have the possibility to explain why I am hitting this problem. But I solved it by grabbing the Variable name from FieldAst. And then do an LINQ on the Variables object for the variable with that name. That gives me everything I need :)
