### ISSUE TITLE
List Property Without Resolve

### ISSUE THREAD

**Issue by kmanev073** [graphql-dotnet/graphql-dotnet#905]
## Summary
Hi guys! I'll be direct. I have 2 classes. One of them has a list of instances of the other class.How do I make a query that returns list of objects of the first type? All the solutions I found online required adding a resolve method to the list property and I want to avoid a second call to the db for each item in my list.

## Relevant information

**My DeliveryItem class**
```
    public class DeliveryItem
    {
        public Guid NomenclatureId { get; set; }
        public string NomenclatureName { get; set; }
        public Guid NomenclatureSubtypeId { get; set; }
        public string NomenclatureSubtypeName { get; set; }
        public double Amount { get; set; }
        public double Price { get; set; }
        public double Value { get; set; }
    }
```

**My Delivery class (has a list of DeliveryItems)**
```
    public class Delivery
    {
        public Guid Id { get; set; }
        public int Number { get; set;}
        public Guid SupplierId { get; set; }
        public string SupplierName { get; set; }
        public DateTime DeliveryDate { get; set; }
        public bool IsPaid { get; set; }
        public double Value { get; set; }
        public List<DeliveryItem> Items { get; set; }
    }
```

**My DeliveryItemType constructor (GraphQL Type)**
```
public DeliveryItemType()
{
    Name = "DeliveryItem";
    Description = "DeliveryItem model.";
    
    Field(deliveryItem => deliveryItem.NomenclatureId, type: typeof(IdGraphType));       
    Field(deliveryItem => deliveryItem.NomenclatureName);           
    Field(deliveryItem => deliveryItem.NomenclatureSubtypeId, type: typeof(IdGraphType));
    Field(deliveryItem => deliveryItem.NomenclatureSubtypeName);          
    Field(deliveryItem => deliveryItem.Amount);
    Field(deliveryItem => deliveryItem.Price);
    Field(deliveryItem => deliveryItem.Value);
}
```

My DeliveryType constructor (again GraphQL Type)
```
public DeliveryType()
{
    Name = "Delivery";
    Description = "Delivery model.";
    
    Field(delivery => delivery.Id, type: typeof(IdGraphType));
    Field(delivery => delivery.Number, true);          
    Field(delivery => delivery.SupplierId, type: typeof (IdGraphType));        
    Field(delivery => delivery.SupplierName);
    Field(delivery => delivery.DeliveryDate);
    Field(delivery => delivery.IsPaid));         
    Field(delivery => delivery.Value);                           
    Field(delivery => delivery.Items, type: typeof(ListGraphType<DeliveryItemType>));
}
```

That last line: `Field(delivery => delivery.Items, type: typeof(ListGraphType<DeliveryItemType>));`

That's the part I can't get working. I use MongoDB and I have no problems storing a list of items in my model, so I expected that I won't have problems returning my object with the list inside as result of my query. However all I get is that error `No service for type 'DeliveryItemType' has been registered.`

I would be grateful if anyone could help return my Delivery list correctly.

Thank you in advance!
Regards

**Comment by joemcbride** [comment]
```
Field<ListGraphType<DeliveryItemType>>(“items”, resolve: context => context.Source.Items)
```


That should work, looking into the exact syntax for lists with expression syntax but yours looks fine to me.

Have you registered your DeliveryItemType with your container?

**Comment by kmanev073** [comment]
> Field<ListGraphType<DeliveryItemType>>(“items”, resolve: context => context.Source.Items)
THank

**Comment by kmanev073** [comment]
> ```
> Field<ListGraphType<DeliveryItemType>>(“items”, resolve: context => context.Source.Items)
> ```
> That should work, looking into the exact syntax for lists with expression syntax but yours looks fine to me.
> 
> Have you registered your DeliveryItemType with your container?

Thanks man! 

I had registered my type like: `services.AddSingleton<IMyInterface,DeliveryItemType>();`
Now I just changed it to  `services.AddSingleton<DeliveryItemType>();`

Both syntaxes work! Thank you once again!
