### ISSUE TITLE
Cannot see which field in GraphiQL that is failing (Introspection)

### ISSUE THREAD

**Issue by joelmandell** [graphql-dotnet/graphql-dotnet#906]
Hey!
Is it possible to find out which field is failing?
In Graphiql it says "Error: Introspection must provide input type for arguments". But I wonder which one?

**Comment by joelmandell** [comment]
I found out which field that was failing by inspecting the network tab in Graphiql and the types object on recieved data from introspection query. 

So I did som dirty stuff with the mutation resolver... I had it to expect a `List<ObjectGraphType>` as InputType
🤦‍♂️

**Comment by sungam3r** [comment]
Fixed. Now all input and output types are checked when the schema is built.
