### ISSUE TITLE
How to map input type to poco respecting declarations in schema?

### ISSUE THREAD

**Issue by featherbits** [graphql-dotnet/graphql-dotnet#907]
I have experienced mapping issues where input from mutation query is not mapped to POCO respecting field definitions.

I have simple POCO
```
public class UpdateMyCompanyInput
{
    public string Name { get; set; }
    public string RegistrationNo { get; set; }
}
```

Which then is used in input type declaration like so
```
public class UpdateMyCompanyInputType : InputObjectGraphType<UpdateMyCompanyInput>
{
    public UpdateMyCompanyInputType()
    {
        Name = "CompanyInput";
        Field("customName", input => input.Name, nullable: true);
        Field(input => input.RegistrationNo, nullable: true);
    }
}
```

Mutation declaration that uses this input type is declared like this
```
public class AppMutation : ObjectGraphType
{
    public AppMutation()
    {
        Field<CompanyType>(
            "updateMyCompany",
            arguments: new QueryArguments(
                new QueryArgument<NonNullGraphType<UpdateMyCompanyInputType>> {
                    Name = "company"
                }
            ),
            resolve: context =>
            {
                var companyInput = context.GetArgument<UpdateMyCompanyInput>("company");

                ...
            }
        );
    }
}
```
And request is made with this JSON
```
{
  "query": "mutation ($company:CompanyInput!){ updateMyCompany(company: $company) { name } }",
  "variables": {
    "company": {
    	"customName": "something"
    }
  }
}
```

At the end, `companyInput` variable contains `UpdateMyCompanyInput` object with `Name` property set to null.

What is the correct way of mapping inputs to POCOs using input type declarations?

From what I have observed, I could ask context to get argument that is of any type, regardless what's defined in query argument. I would like to achieve mapping that respects declarations.

**Comment by joemcbride** [comment]
At this time there is no built-in way provided by this project to do custom mappings as you describe.  You will have to use a third-party library to do that.

See #864 for more discussion on the topic.
