### ISSUE TITLE
Querying Interface Type Property and Interface Property in Input Type

### ISSUE THREAD

**Issue by kmanev073** [graphql-dotnet/graphql-dotnet#910]
Hi guys! 

I have 2 questions. Here is the setup: **I have an IMessageBehaviour interface, 2 classes that implement it and a 3rd class that has a property of type IMessageBehaviour.** Questions:

1. As you can see, my MessageBehaviour classes have different properties, I have a query that returns a list of Messages. As every message has an IMessageBehaviour property how can I list all of my messages with all of their properties? When I register a graphql interface I can only access the properties that are shared between my 2 classes (I am talking about the string Message property) ?

2. How do I make a input type for the Message class? I want to be able to create messages with different behaviors. How do I create a mutation for such type of property? I want to have only one mutation for creating new messages. It will be uncomfortable having a mutation for every type of MessageBehaviour.

```
public interface IMessageBehaviour
{
    public string Message {get; set;}
}

public class PrivateMessageBehaviour : IMessageBehaviour
{
    public string Message {get; set;}
    public string Sender {get; set;}
}

public class BotMessageBehaviour : IMessageBehaviour
{
    public string Message {get; set;}
}

public class Message
{
    IMessageBehaviour MessageBehaviour {get; set;}
}
```

Thank you in advance!

**Comment by joemcbride** [comment]
1. You can use fragments for this.

https://graphql.org/learn/queries/#fragments
https://graphql.org/learn/queries/#inline-fragments
https://graphql-dotnet.github.io/docs/getting-started/fragments

2. There is not an easy way to do this at present.  Since GraphQL is a type system, you will have to have different types for each input that varies.  You could perhaps make this a little easier by using an abstract base GraphType that included the fields from your interface.

**Comment by kmanev073** [comment]
Thanks for the answer! Where can I find more information on "abstract base GraphType"?

**Comment by sungam3r** [comment]
It is just your own class with a bunch of fields:
```c#
 public abstract class MessageBaseGraphType: InputObjectGraphType<IMessageBehaviour>
{
        public MessageBase()
        {
            Field(o => o.Message);
            Field(o => o.SomeOtherProperty1);
            Field(o => o.SomeOtherProperty2);
        }
}

public class CustomMessageGraphType : MessageBaseGraphType
{ 
        public CustomMessageGraphType ()
        {
            // custom configuration if any
        }
}
```

**Comment by kmanev073** [comment]
@sungam3r Thanks!

I will try this someday when I have time. I already started the project and changed my classes so I can use them with simple query/mutations.

**Comment by sungam3r** [comment]
@kmanev073 Is this issue still actual?

**Comment by sungam3r** [comment]
Closed due to inactivity.
