### ISSUE TITLE
How to add metadata fields in the in the final response of every GraphQL query?

### ISSUE THREAD

**Issue by santoshpatro** [graphql-dotnet/graphql-dotnet#912]
I have the following graphql query:
```
{
  orders {
    id
    description
    name
    status
  }
}
```

It responds with the following response:
```
{
  "data": {
    "orders": [
      {
        "id": "FAEBD971-CBA5-4CED-8AD5-CC0B8D4B7827",
        "description": "250 Conference brochures",
        "name": "1000",
        "status": "CREATED"
      }
    ]
  }
}
```
I am looking for a way to add another root property in this response say "meta"

```
{
  "data": {
    "orders": [
      {
        "id": "FAEBD971-CBA5-4CED-8AD5-CC0B8D4B7827",
        "description": "250 Conference brochures",
        "name": "1000",
        "status": "CREATED"
      }
    ]
  },
 "meta": {
       "page": 1,
       "count": 10,
       "totalCostValue": 1000
     }
}
```
I would like to know how can this be achieved using Graphql.NET. 
Can anyone help me here with some code sample to fix this issue?

**Comment by BenjaBobs** [comment]
You could probably achieve this with `extensions`.

**Comment by santoshpatro** [comment]
Thanks for your response. Can you please help me with any example or links as a reference

**Comment by BenjaBobs** [comment]
I haven't played with it myself, but as you can see [here](https://graphql-dotnet.github.io/docs/getting-started/metrics), the `extension` field is added. I *think* it's on the `ExecutionResult`.

**Comment by santoshpatro** [comment]
From the link, I see it is related to Field metrics which is supported by Graphql.net. I want to know how to add additional custom fields in this case.

**Comment by BenjaBobs** [comment]
A quick search revealed this:
[ExecutionResult#L26](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionResult.cs#L26)
```c#
public Dictionary<string, object> Extensions { get; set; }
```

Try adding your meta data to that dictionary.

**Comment by santoshpatro** [comment]
By the time I am trying to set the values for the metadata the graphql response is already returned and control goes to the middleware code. Is there anyway to access the fields and update their value. Here goes the field details:

In this case Field<LocaleType>,Field(x => x.Authorised),Field(x => x.UserMessage, nullable: true) should be returned with every endpoint response.

```
public class TestResultType: ObjectGraphType<TestResult>
    {
        public TestResultType()
        {
            Field<ListGraphType<TestDTOType>>(
                "details",
                resolve: context => {
                    return context.Source.Locations;
                }
            );
            **Field<LocaleType>(
                "locale",
                resolve: context => {
                    return context.Source.Locale;
                }
            );
            Field(x => x.Authorised);
            Field(x => x.UserMessage, nullable: true);**
        }
    }
```

Any help with some code sample is much appreciated

**Comment by joemcbride** [comment]
What you are wanting to do is not provided by the GraphQL spec.  So this is not supported.

**Comment by sungam3r** [comment]
> I am looking for a way to add another root property in this response say "meta"

Please look [Response Format Spec](https://graphql.github.io/graphql-spec/June2018/#sec-Response-Format):

> To ensure future changes to the protocol do not break existing servers and clients, the top level response map must not contain any entries other than the three described above.

You are free to use any data structure **inside** the `extensions` entry.

**Comment by joemcbride** [comment]
Thanks @sungam3r .  I'm going to close this issue.
