### ISSUE TITLE
Graphiql editor displayed but without schema using asp.net core 2

### ISSUE THREAD

**Issue by santoshpatro** [graphql-dotnet/graphql-dotnet#916]
I need some help on resolving the issue : https://stackoverflow.com/questions/53362038/http-localhost49915-api-graphql-not-working-on-updating-the-route-of-graphql

Any help on this is much appreciated?

**Comment by joemcbride** [comment]
That GraphiQL middleware you're using is not associated this project.  I suggest you read the documentation or source code of that project.
