### ISSUE TITLE
CancellationToken in async field resolver

### ISSUE THREAD

**Issue by Jefffrey** [graphql-dotnet/graphql-dotnet#919]
## Summary

Similarly to https://github.com/graphql-dotnet/graphql-dotnet/issues/16 would it be possible to add a CancellationToken parameter to an async field resolver?

### Basic example

```
Field<NonNullGraphType<XType>>()
    .Name("field")
    .ResolveAsync(async (context, ct) =>
    {
        connection.QueryAsync<LicenseCategory>("SELECT * FROM Xs");
    });
```

### Motivation

As far as I can see it's impossible to currently cancel a resolving field without using the data loader. The above example would be in the context for example of the root `Query` type where a data loader would not make much sense.

**Comment by desbrowne** [comment]
I'm using context.CancellationToken for this, does this pattern not work for your needs?

You of course need to set the CancellationToken as part of your executor for it to exist on the context, e.g.:
> 	var result = await _executor.ExecuteAsync(_ =>
> 	{
> 		_.CancellationToken = cancellationToken;
> ...

**Comment by Jefffrey** [comment]
Oh, I was unable to find that in the documentation. Thanks.
