### ISSUE TITLE
Better documentation on how to use field middleware

### ISSUE THREAD

**Issue by drowhunter** [graphql-dotnet/graphql-dotnet#923]
I am trying to figure out how to use the field middle ware and the documentation is not very helpful. 
docs say 
You register Field Middleware in the ExecutionOptions.
```
schema.Execute(_ =>
{
  _.Query = "...";
  _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
});
```
Im using GraphQL.Authorization and here is my code

Startup.cs 
```
public void ConfigureServices(IServiceCollection services)
{
       services.AddGraphQL(new GraphQLOptions()
      {
            EnableMetrics = true,
            ExposeExceptions = true,
            SetFieldMiddleware = true  // <-- what does this actually do ???
       })
       .AddGraphTypes()
        .AddUserContextBuilder(context => new GraphQLUserContext() {User = context.User})
        .AddDataLoader();

}
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
       app.UseGraphQLWithAuth<ISchema>();
}
```
MySchema.cs
```
public class MySchema : GraphQL.Types.Schema
    {
        public MySchema(IDependencyResolver resolver)  : base(resolver)
        {
            Query = resolver.Resolve<MyQuery>();           
            this.RegisterDirective(new MyDirectiveType("myDirective", DirectiveLocation.Field));            
        }        
    }
```
I cant figure out where i'm supposed to register it.  Any help would be kindly appreciated.

**Comment by RehanSaeed** [comment]
You can see a full example of it's usage in the [ASP.NET Core GraphQL Boxed](https://github.com/Dotnet-Boxed/Templates/blob/master/Docs/GraphQL.md) project template. You can see how to use it in the [InstrumentingGraphQLExecutor.cs](https://github.com/Dotnet-Boxed/Templates/blob/a5c351a76248b7708c2d685c638cd483639cebaa/Source/Content/GraphQLTemplate/InstrumentingGraphQLExecutor.cs) file.

**Comment by drowhunter** [comment]
what is this dotnet boxed project for? looks interesting

**Comment by RehanSaeed** [comment]
Project templates that give you optional features to get you started quicker.

**Comment by sungam3r** [comment]
Relates to #492 and #1268

**Comment by sungam3r** [comment]
Also see graphql-dotnet/examples#25

**Comment by sungam3r** [comment]
`SetFieldMiddleware` was removed from options in #1268

**Comment by sungam3r** [comment]
@drowhunter Also documentation for Field Middleware was updated, see https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/field-middleware.md

Closing this as resolved.
