### ISSUE TITLE
ResolveFieldContext.GetArgument won't try to convert argument name to camelCase

### ISSUE THREAD

**Issue by branhill** [graphql-dotnet/graphql-dotnet#925]
## Description

QueryArgument will convert Name to camelCase automatically, but ResolveFieldContext.GetArgument won't do that. It only get argument by original name string.

### Steps to reproduce

Use a PascalCase string as the QueryArgument.Name, then use same string in ResolveFieldContext.GetArgument().

### Expected result

The value of the argument.

### Actual result

null

### Environment

GraphQL 2.4.0

**Comment by sungam3r** [comment]
Fixed in #1081
