### ISSUE TITLE
Error Message Change after updating from 2.0 to 2.4

### ISSUE THREAD

**Issue by Kunjahamed-P** [graphql-dotnet/graphql-dotnet#926]
The error message in 2.0 GraphQL as folllows,
"errors": [
  {
    "message": "not authorized",
    "extensions": {
      "code": "NOT_AUTHORIZED"
    }
  }
]

after updating graphql server to 2.04, then message error show as,

"errors": [
  {
    "message": "GraphQL.ExecutionError:  not authorized",
    "extensions": {
      "code": "NOT_AUTHORIZED"
    }
  }
]

the error message show with 'GraphQL.ExecutionError', how we can remove from there ?

**Comment by SimonCropp** [comment]
@Kunjahamed-P can u submit a PR for this

**Comment by sungam3r** [comment]
I think that this already is not the issue of this project. Authorization issues lie outside the specification and have been moved to https://github.com/graphql-dotnet/authorization. See [this rule](https://github.com/graphql-dotnet/authorization/blob/master/src/GraphQL.Authorization/AuthorizationValidationRule.cs#L83).

If the problem persists then feel free to open it in that repository.
