### ISSUE TITLE
How to generate dynamic path value for a graphql query response using GraphQL.NET?

### ISSUE THREAD

**Issue by santoshpatro** [graphql-dotnet/graphql-dotnet#929]
I have REST API (api/tax/v1/countries) with the following response. In the below the pngimagePath and svgimagePath properties are pointing to the image type endpoints(api/tax/v1/country/Country1/{FlagPNG or FlagSVG})

The paths are generated dynamically in this case.

```
{
  "countries": [
    {
      "pngimagePath": "https://test.com/api/tax/v1/country/Country1/4/image/FlagPNG",
      "svgimagePath": "https://test.com/api/tax/v1/country/Country1/405/image/FlagSVG",
      "displayName": "Country1",
      "displayNameShort": "Country1",
      "providerName": "Testing",
      "providerTerms": null,
      "uuid": "1",
      "name": "Country1",
      "path": "Country1",
      "completeResponse": true
    },
    {
      "pngimagePath": "https://test.com/api/tax/v1/country/Country2/5/image/FlagPNG",
      "svgimagePath": "https://test.com/api/tax/v1/country/Country2/406/image/FlagSVG",
      "displayName": "Country2",
      "displayNameShort": "Country2",
      "providerName": "Testing one",
      "providerTerms": null,
      "uuid": "2",
      "name": "Country2",
      "path": "Country2",
      "completeResponse": true
    }
  ]  
}
```
```
// Code to generate the image path
var apiPath = _appSettings.Value.ApiPath + "country/";
result.Countries.AddRange(rawCountries.Select(country  =>  new DTO.CountryDTO {
PNGImagePath =  $"{apiPath}{Helper.ReplaceChars(country.DefaultDisplayName)}/{country.PngImageId}/image/{country.PngImageType}" ,  SVGImagePath =  $"{apiPath}{Helper.ReplaceChars(country.DefaultDisplayName)}/{country.SvgImageId}/image/{country.SvgImageType}" ,  } ) ) ;


```

I want to generate the image path using GraphQL.NET.

How can I achieve this using GraphQL.NET?

Any help on this is much appreciated.

**Comment by joemcbride** [comment]
Hey, so this is not really an issue with this project.  You would continue to generate those urls as you were previously.  GraphQL.NET can't do anything to help or hinder you here.

**Comment by santoshpatro** [comment]
Hi Joe,

Thanks for your quick response. In my case I need to create a graphql endpoint containing the image path, which in this case is dynamic one. I would like to know how we can create with some code sample.
In short an analogous graphql query to the REST API endpoint.

Any help on this is much appreciated.

Thanks,
Santosh

**Comment by santoshpatro** [comment]
Hi Joe,

Thanks for your quick response. In my case I need to create a graphql endpoint containing the image path, which in this case is dynamic one. I would like to know how we can create with some code sample.
In short an analogous graphql query to the REST API endpoint.

Any help on this is much appreciated.

Thanks,
Santosh

**Comment by joemcbride** [comment]
This project cannot help you accomplish that task.  There are no classes provided by this framework that generates urls.  That is a generic task that you can accomplish with just plain .NET Code or ASP.NET.  I suggest you post your question on Stackoverflow.

**Comment by santoshpatro** [comment]
I have posted the question with all the details at https://stackoverflow.com/questions/53506345/how-to-generate-dynamic-path-value-for-a-graphql-query-response-using-graphql-ne

**Comment by joemcbride** [comment]
Anything I can think of related to this that I can help you with is in the documentation for this project:

https://graphql-dotnet.github.io/docs/getting-started/introduction

I cannot write this code for you or provide code examples.  You are going to have to solve this problem in your own project as it is specific to your project and is not related to GraphQL.  This framework helps you map your existing C# class to a GraphQL response.  It does not help you populate those classes with data.  If you need to dynamically generate a URL then you need to use classes provided in .NET or ASP.NET to do so.

I strongly suggest that you do some learning about how GraphQL works and what it is trying to solve.  The issues you've been opening are not issues that GraphQL itself can help you solve.  They have been generic programming issues that you as a developer are expected to solve.  Here are some resources and tutorials:

https://www.youtube.com/watch?v=F_M8v6MK0Sc
https://graphql.org/learn/
https://www.howtographql.com/
