### ISSUE TITLE
The type: Byte cannot be coerced effectively to a GraphQL type

### ISSUE THREAD

**Issue by santoshpatro** [graphql-dotnet/graphql-dotnet#940]
Here is the code that I am using to fetch ByteArrayContent  type:
```
// Code:
public class ImageDTO : APIResult
{
	public byte[] ImageData
	{
		get;
		set;
	}

	public string ImageFormat
	{
		get;
		set;
	}

	public ImageDTO()
	{
		ImageData = new byte[]{};
	}
}

public class ImageType : ObjectGraphType<ImageDTO>, IGraphQLType
{
	public ImageType()
	{
		Field(img => img.ImageData);
		Field(img => img.ImageFormat);
	}
}

public class ImageResolver : Resolver, IImageResolver
{
	private readonly ICommonService _commonService;
	public ImageResolver(ICommonService commonService)
	{
		_commonService = commonService;
	}

	public void Resolve(GraphQLQuery graphQLQuery)
	{
		graphQLQuery.Field<ResponseGraphType<ImageType>>("imageresponse", arguments: new QueryArguments(new QueryArgument<NonNullGraphType<StringGraphType>>{Name = "imageId", Description = "id of the project"}), resolve: context =>
		{
			var imageId = context.GetArgument<string>("imageId");
			var imageResult = _commonService.GetImage(imageId);
			if (imageResult == null)
			{
				return NotFoundError(imageId);
			}

			return Response(imageResult);
		}

		);
	}
}
```
On executing the above code I am getting the below mentioned error.
The type: Byte cannot be coerced effectively to a GraphQL type\r\nParameter name: type\r\n   at Type GraphQL.

From the link : https://github.com/graphql-dotnet/graphql-dotnet/issues/458 , it is mentioned that ByteGraphType is supported. I am using GraphQL.net nuget package with version:2.3.0 . So I believe it should support the ByteGraphType.

Can you please help me here to know how to fix this issue.

**Comment by joemcbride** [comment]
That issue provides the ability to make it easier to write your own custom scalar.  This project does not currently provide a `ByteGraphType` that you can consume, you will have to write your own as demonstrated on that issue.

**Comment by santoshpatro** [comment]
Thanks Joe for your response. But can you please help me how to deal with image responses. In short how to deal with Fields having image type response. Does it mean that we cannot have anything inbuilt support for providing image response to the client application. Can you please help me to get some code samples as reference.

Any help on this is much appreciated.

**Comment by sungam3r** [comment]
See #1091. Over time, different numeric scalars were added. I hope that this PR will be accepted and finally there will be support for `ByteGraphType`.

> In short how to deal with Fields having image type response.

byte[] field now works fine. You can use it. In truth, this method is not very suitable for transferring large binary data.
