### ISSUE TITLE
Option to be less strict with NonNullGraphType returning null?

### ISSUE THREAD

**Issue by steviemcg** [graphql-dotnet/graphql-dotnet#943]
In our case, a property is set as a NonNullGraphType because it should be filled, and that's what we want to communicate to the consumers of our API.

Sometimes there is a problem in the source data and the data is missing. This causes `new ExecutionError($"Cannot return null for non-null type. Field: {node.Name}, Type: {type.Name}!.");` to be thrown and it is included in the list of errors.

In our API controller, we set status 500 if any errors exist. This serves us well mostly, but in this case it is far too strict. I suppose we can check for this specific text and ignore it, which is probably what I'll do.

Am I thinking about this the right way, and/or do you think it'd be better to have the option to be less strict with NonNullGraphType returning null?

**Comment by joemcbride** [comment]
Unfortunately no - that is part of the GraphQL spec so I don't see that being budged on.  If that is an actual problem with your data I would suggest to instead do that check yourself and throw your own custom error vs. letting that bubble up to the null check.

**Comment by steviemcg** [comment]
OK, thanks. It's a gigantic number of properties so I'm not sure how to do that in a workable way. I'll stick with my hack of ignoring this text when choosing the status code. 😄 As the error text is definitely useful, but it's not necessarily big enough of a problem for the entire request to fail. Feel free to close and thanks for your time.
