### ISSUE TITLE
[Error][Server] Sequence contains no matching element in EnrichWithApolloTracing

### ISSUE THREAD

**Issue by JaeWangL** [graphql-dotnet/graphql-dotnet#944]
```
                var result = await base.ExecuteAsync(operationName, query, variables, context, cancellationToken);

                if (options.EnableMetrics)
                {
                    result.EnrichWithApolloTracing(DateTime.UtcNow);
                }

                return result;
```

Here is my code
and it says exception "System.InvalidOperationException: Sequence contains no matching element"

But works well

**Comment by jumpinjackie** [comment]
This happens because the apollo tracing enrichment blindly assumes the perf records on the execution result have all the required categories present: operation/document/field

If one of these categories is not present in the perf records, you get the aforementioned error.

We've worked around this by adding this simple check and enrich with apollo tracing only if the check returns true:

```
        static bool CanEnrich(ExecutionResult result)
        {
            var hasOp = result?.Perf?.Any(x => x.Category == "operation");
            var hasDoc = result?.Perf?.Any(x => x.Category == "document");
            var hasField = result?.Perf?.Any(x => x.Category == "field");
            return hasOp == true && hasDoc == true && hasField == true;
        }
```

**Comment by OpenSpacesAndPlaces** [comment]
Did either of you figure out where "field" gets populated?

The docs make it look like it should just be automatic:
https://graphql-dotnet.github.io/docs/getting-started/metrics

**Comment by OpenSpacesAndPlaces** [comment]
I think the issue for me was running in Framework - the middleware not actually resolving.

I added some manual calls:
```
public static ResolveFieldContext Resolve(ResolveFieldContext rfc)
	{
		var metadata = new Dictionary<string, object>
		{
			{"typeName",  rfc.ParentType.Name},
			{"fieldName",  rfc.FieldName},
			{"returnTypeName", SchemaPrinter.ResolveName( rfc.ReturnType)},
			{"path",  rfc.Path},
		};

		using ( rfc.Metrics.Subject("field",  rfc.FieldName, metadata))
		{
			return  rfc;
		}
	}
```

The only horsey thing is that it doesn't seem you can check the execution options from that context - so have a global set to see if it should run.

**Comment by mjarlund** [comment]
Just came across this issue, and wound up doing as @jumpinjackie. 
```
if (
   result.Perf != null &&
   result.Perf.Any(x => x.Category == "operation") &&
   result.Perf.Any(x => x.Category == "document") &&
   result.Perf.Any(x => x.Category == "field"))
{
   result.EnrichWithApolloTracing(DateTime.UtcNow);
}
```
Obviously it would be nice to have `EnrichWithApolloTracing` do the check instead, but this works for now. Thank you.

**Comment by joemcbride** [comment]
A couple things here.

The `field` in metrics is populated by `InstrumentFieldsMiddleware` field middleware.

```csharp
_.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
```

This:

```csharp
result.EnrichWithApolloTracing(DateTime.UtcNow);
```

Is a bit incorrect.  You need to capture the time _before_ execution and pass that to the `EnrichWithApolloTracing` method.  Otherwise you're labeling the start time _after_ it actually happened, which could cause some confusion if trying to match with other logs.

```csharp
var start = DateTime.UtcNow;

var executor = new DocumentExecutor();
var result = await executor.ExecuteAsync(_ =>
{
  _.Schema = schema;
  _.Query = "...";
  _.EnableMetrics = true; // this is true by default
  _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
});

result.EnrichWithApolloTracing(start);
```

**Comment by mjarlund** [comment]
Oh yea, that makes sense, thank you for bringing that up. It probably wouldn't hurt to add an exception tag to `EnrichWithApolloTracing` to inform developers of the potential `InvalidOperationException`.

**Comment by sungam3r** [comment]
You can try the latest preview version from [myget](https://myget.org/F/graphql-dotnet/api/v3/index.json) to make sure the error is gone.
