### ISSUE TITLE
Cannot get arguments for input types wrapping System.* types

### ISSUE THREAD

**Issue by andrewtyped** [graphql-dotnet/graphql-dotnet#947]
## Description

`ResolveFieldContext.GetArgument<>` cannot be used for complex types from System namespaces - it fails with an `InvalidCastException`. 

This appears to be due to the implementation of `GetArgument`, which attempts to cast the argument directly from `Dictionary<string, object>` to the target type when the requested type's namespace starts with `System`.

In our case, we're trying to use some types from System.Numerics (types like Vector2/3/4) as arguments to mutations. There's a secondary blocker to using types like this as arguments - `ObjectExtensions.ToObjects` only supports properties, not fields, but that's out of scope for this issue.

### Steps to reproduce

Create and register an `InputObjectGraphType<T>` implementation, where T is a class or struct from a namespace beginning with "System". Example:

```
    using System.Numerics;
    public class Vector3InputType : InputObjectGraphType<Vector3>
    {
        public Vector3InputType()
        {
            this.Name = $"Vector3Input";
            this.Field(vector => vector.X);
            this.Field(vector => vector.Y);
            this.Field(vector => vector.Z);
        }
    }
```

Create a query / mutation which accepts the input type as an argument. The resolver for the type should attempt to get the argument using `ResolveFieldContext.GetArgument<T>`.

```
public class TestMutation : ObjectGraphType<object>
{
    this.Field<StringGraphType>(name: "SomeField",
        arguments: new QueryArguments(
            new QueryArgument<Vector3InputType>
            {
                 Name = "vector3"
            }),
       resolve: context =>
          {
              var vector3 = context.GetArgument<Vector3>(name: "vector3"); //InvalidCastException
              return "";
          });
}
```

Execute a query which uses the argument. The argument may be expressed as a variable or query literal. 

```
mutation {
    someField(vector3: {x: 1.0 y: 2.0 z: 3.0}) 
}
```

### Expected result

The resolver's call to `context.GetArgument<Vector3>` should succeed and be populated with the values from the query (or a default instance of Vector3 since ToObject won't handle its fields for now).

### Actual result

`ResolveFieldContext.GetArgument<>` fails with `System.InvalidCastException`.

### Environment

GraphQL v 2.3.0
Windows 10.0.17134
x64

**Comment by nigel-sampson** [comment]
Ran into this one myself where an input type had a namespace of `SystemOfRecord.CompaniesService` etc.

**Comment by joemcbride** [comment]
I think that check was put in for scalar types, which is a little hackish and there is probably a better way to do it.  You can get the argument directly by using context.Arguments[“vector3”]

**Comment by sungam3r** [comment]
> I think that check was put in for scalar types.

I think that this behavior makes sense only for the `object` type - when calling side do something like this: 
```c#
var result = JsonConvert.SerializeObject(context.GetArgument<object>("input"));
```
It makes sense to give the object as is. What other "primitive" type can be represented by a dictionary? I dont know. Theoretically, we can change the condition to `if (type.Assembly == typeof(object).Assembly` but I don't like it.

**Comment by joemcbride** [comment]
I believe the intent was if you end up with a `Dictionary<string, object>`, but the requested type is scalar, then just return the `Dictionary<string, object>`.  So maybe we can use `type.IsPrimitive` as well as check for `string`?

```csharp
    public static class TypeExtensions
    {
        public static bool IsPrimitive(this Type type)
        {
            return type.IsPrimitive || type == typeof(string);
        }
    }
```

https://docs.microsoft.com/en-us/dotnet/api/system.type.isprimitive?redirectedfrom=MSDN&view=netframework-4.8

**Comment by sungam3r** [comment]
> I believe the intent was if you end up with a Dictionary<string, object>, but the requested type is scalar, then just return the Dictionary<string, object>

let's say, but why do that? What's the point of this? The caller with a probability close to 1 will receive a invalid cast error, because he will try to make a type conversion to the type he knows/wants. Method `public TType GetArgument<TType>(string name, TType defaultValue = default)` does that.

There is some kind of logical gap.

**Comment by joemcbride** [comment]
It’s been years since that was added so maybe it’s not even needed any longer?  If we don’t do a scalar check it will call the ToObject method and throw an error with Activator.CreateInstance.  Could catch that error and provide a better error to describe the situation.

**Comment by sungam3r** [comment]
>  If we don’t do a scalar check it will call the ToObject method and throw an error with Activator.CreateInstance

Not really :) `Activator.CreateInstance<int>()` and `Activator.CreateInstance<DateTime>()` works fine,
`Activator.CreateInstance<string>()` gives `MissingMethodException: 'No parameterless constructor defined for this object.'
`

**Comment by sungam3r** [comment]
In any case, I added checks and made the behavior more or less expected.
