### ISSUE TITLE
Is there a simpler way to enumerate mutation fields in validations?

### ISSUE THREAD

**Issue by wmarshdev** [graphql-dotnet/graphql-dotnet#948]
## Summary
Using the [pattern of reading metadata in a field to see if a validation should be applied](https://graphql-dotnet.github.io/docs/getting-started/authorization), it seems overly difficult or just broken to validate fields in mutation parameters. This seems like the place most validation should occur, as it's taking input from outside of the system. Also, authorization validations as they are currently written in the library don't seem to work on mutation parameter fields at all.

## Relevant information

Here's what I came up with to achieve this. There must be a better way:

```c#
public INodeVisitor Validate(ValidationContext context)
{
    return new EnterLeaveListener(_ =>
    {
        _.Match<Argument>(f =>
        {
            var it = context.TypeInfo.GetInputType();

            if (it != null)
            {
                // Unwrap NonNullGraphTypes
                while (it is NonNullGraphType)
                {
                    it = ((NonNullGraphType)it).ResolvedType;
                }

                var complex = it as IComplexGraphType;
                if (null != complex)
                {
                    foreach (var field in complex.Fields)
                    {
                        // Read metadata and validate field
                    }
                }
            }
        });
    });
}
```

**Comment by joemcbride** [comment]
You _should_ be able to use `Field`, as in the example.  Did you try that?

```csharp
_.Match<Field>(fieldAst =>
{
 ....
}
```

**Comment by thegroke** [comment]
> You _should_ be able to use `Field`, as in the example. Did you try that?
> 
> ```cs
> _.Match<Field>(fieldAst =>
> {
>  ....
> }
> ```

That was my first assumption, but (in 2.4.0 at least) it doesn't match. I'll put together an example.

**Comment by thegroke** [comment]
Okay, I created an example at: https://github.com/thegroke/scratch-GraphQLDotNet-ValidationMatchingExample

I understand this could be a terminology issue, but the field "pleaseValidateMe" that is part of the ExampleInputType passed as an argument to the mutation is not matched. Check the output of the program and the code in ValidationRuleA and ValidationRuleB:

```
ValidationRuleA matched exampleMutation
ValidationRuleB matched field pleaseValidateMe
```

**Comment by joemcbride** [comment]
My apologies, I should have looked closer at this.  In this case we’re matching on the AST types, which for an Argument is going to be an IValue.  That maps to ObjectValue which has ObjectField.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Language/AST/Argument.cs#L18

The AST is walked based on the Children of the Node.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Language/AST/ValueNodes/ObjectValue.cs#L30

So you should be able to use ObjectValue and ObjectField in conjunction with the Argument.

**Comment by thegroke** [comment]
Thanks Joe, that makes sense and I appreciate the time you took to help me out here.

I'm still not quite at the point where I've got a clean system for "this field on input types passed as mutation arguments should run with <some generic string length checker>"*, but you've pointed me in the right direction for walking the graph.

* My validators instead look more like the NonNullGraphType wrapper, which isn't the architecture I want to go with

**Comment by joemcbride** [comment]
There is an extension method to help unwrap types btw, called `GraphQLExtensions.GetNamedType`.

```csharp
var it = context.TypeInfo.GetInputType()?.GetNamedType();
```

I think this is closer to what it can look like:

```csharp
public INodeVisitor Validate(ValidationContext context)
{
    return new EnterLeaveListener(_ =>
    {
        InputObjectGraphType inputType;

        _.Match<Argument>(f =>
        {
            inputType = context.TypeInfo.GetInputType().GetNamedType();
        });

        _.Match<ObjectField>(f =>
        {
            var field = inputType.GetField(f.Name);
            field.Metadata...
        });
    });
}
```

**Comment by beatsm** [comment]
C gf uggiuif I was hi a hi guyspj ibp

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
