### ISSUE TITLE
UriGraphType does not convert Uri

### ISSUE THREAD

**Issue by cgatian** [graphql-dotnet/graphql-dotnet#949]
## Description
`UriGraphType` does not properly convert

### Steps to reproduce
Attempt to add a field to a type with `Uri` to `UriGraphType`
```
Field("url", context => new Uri("https://google.com"), type: typeof(UriGraphType));
```

### Expected result
Conversion should take place, just like `DateGraphType`
### Actual result
Schema isnt created, and no exceptions are raised

### Environment
.net core 2.2

**Comment by SimonCropp** [comment]
@cgatian want to have a go at submitting a fix for this via a PR?

**Comment by cgatian** [comment]
Hell mutha fawkin yes

**Comment by KoditkarVedant** [comment]
@cgatian I have created the PR for the issue. Please let me know if you had completed the changes and want to raise the PR. I would be happy to close my PR.
