### ISSUE TITLE
Question about Queryable, input Validations,  authorization and authentication

### ISSUE THREAD

**Issue by aammfe** [graphql-dotnet/graphql-dotnet#951]
Hello!!
After seeing some examples its still unclear how graph query is handling these situations

- Queryable (graph query closely integrated with entity frame work (no repository or better solution))
optimize database queries
- Input Validations (validation for user input )
- Authentication (user Authentication)
- Authorization (resource Authorization)

Please shed light on them and if possible please provide links for examples repositories.
Thanx

**Comment by SimonCropp** [comment]
Re ef and queryable https://github.com/SimonCropp/GraphQL.EntityFramework

**Comment by SimonCropp** [comment]
Re validation https://github.com/SimonCropp/GraphQL.Validation

**Comment by SimonCropp** [comment]
Re auth https://graphql-dotnet.github.io/docs/getting-started/authorization

**Comment by SimonCropp** [comment]
Also re validation https://graphql-dotnet.github.io/docs/getting-started/query-validation

**Comment by tomesendam** [comment]
@aammfe did you manage to get auth to work with grapql.entityframwork?

**Comment by aammfe** [comment]
I was just inspecting how things work in Graphql.
