### ISSUE TITLE
Remote schema

### ISSUE THREAD

**Issue by thivy** [graphql-dotnet/graphql-dotnet#955]
Hi Guys,

Is there a feature similar to schema stitching?

Apollo has a feature to Remote schemas and linking them together. This is handy when developing micro services.
https://www.apollographql.com/docs/graphql-tools/remote-schemas.html

This is a good talk on stitching https://www.youtube.com/watch?v=90JWZnuf7xQ

**Comment by AmbroiseCouissin** [comment]
This would be very useful for us as well. Right now, we are stitching things manually from the root mutation resolver.

**Comment by thivy** [comment]
@joemcbride thanks!

Hopefully this will get merged into master soon.

**Comment by Shane32** [comment]
Per @joemcbride in #592 

> this won’t be pulled in. Schema stiching has been superseded by Apollo Federation.

**Comment by sungam3r** [comment]
50 cents from me. It's true that stiching has been superseded many years ago but I heard that new developers team gave the second life to stiching technology and now it's not so obvious what to prefer.
