### ISSUE TITLE
Ability to short circuit ienum conversions to be able to handle b64 => byte[]

### ISSUE THREAD

**Issue by Tarig0** [graphql-dotnet/graphql-dotnet#956]
## Summary

Brief explanation of the feature.

I would like to have a simple way to have a conversion of type string => byte[]

currently this will decompose to an attempt to convert char => byte.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

Allow for passing binary information as arguments

**Comment by Tarig0** [comment]
Design wise this would need to change the work flow to.

1. Check if type conversion exists for the raw types
2. If so use that conversion .. stop
3. If not continue old logic
4. Continue recursive calls for nested ienum types

**Comment by sungam3r** [comment]
@Tarig0 Is this issue still actual for you? If I undestand you correctly you can solve this problem by custom scalar type.

**Comment by Tarig0** [comment]
I got around it by using MemoryStream as the target type since it didn't implement IEnumerable`1
```c#
ValueConverter.Register(typeof(string), typeof(MemoryStream), (s) => new MemoryStream(Convert.FromBase64String((string)s)));
//-------------------------------
using (var stream = ctx.GetArgument<MemoryStream>("arg"))
```
Though I feel like there should be a way to control the conversion from type IEnum<A> to type IEnum<B> when conversion from A => B is not desired.

Can you show me the sample scalar type? I haven't touch my graphql project in a while so I'm a bit rusty

**Comment by sungam3r** [comment]
@Tarig0 At first I did not understand what you were achieving,  now it is clear.

**Comment by sungam3r** [comment]
@Tarig0 Could you check if current behavior suits you?

**Comment by Shane32** [comment]
See #2274 for an example of how to implement this conversion.
