### ISSUE TITLE
Are reusable fragments supported?

### ISSUE THREAD

**Issue by troydalldorf** [graphql-dotnet/graphql-dotnet#957]
Is it possible to define reusable fragments which many users can use?
It looks like [Apollo supports this capability](https://www.apollographql.com/docs/react/advanced/fragments.html#reusing-fragments).

Many of our users use the same queries based on a particular use case. What I am hoping to be able to do is to store predefined fragments and allow users to use those as they would any other fragment, including graphiql code completion.

It looks like it's pretty easy to modify the query prior to processing and insert predefined templates, but this would not support code completion.

Thank you for your help.

**Comment by joemcbride** [comment]
Fragments are part of the GraphQL spec and this framework supports them.  As long as you follow the patterns described in those articles then they would be “reusable”.  Fragments are used within the query/mutation and there is nothing special you need to do on the server to support them.
