### ISSUE TITLE
Change default serializer

### ISSUE THREAD

**Issue by arsmn** [graphql-dotnet/graphql-dotnet#959]
Is it possible to change default JSON serializer (Json.Net)?
I want to use Utf8Json instead of Json.Net for example.

**Comment by DSilence** [comment]
It's possible to do that for responses - you have to implement a custom IDocumentWriter for that. Once https://github.com/graphql-dotnet/server/pull/174 is merged, I'm planning to provide a nuget package for that. It's not possible for requests for now - I've been looking for ways of changing that, but the implementation is too JToken dependent for now, and it's probably required to build and extra abstraction to workaround that - someone from maintainers should confirm that.

**Comment by DSilence** [comment]
Here is a sample DocumentWriter using Utf8Json
```csharp
public class Utf8JsonDocumentWriter : IDocumentWriter
    {
        private readonly IJsonFormatterResolver _jsonFormatterResolver;

        public Utf8JsonDocumentWriter()
        {
            _jsonFormatterResolver = CompositeResolver.Create(new IJsonFormatter[] {new ExecutionResultJsonFormatter()},
                new[] { StandardResolver.CamelCase });
        }

        public Task WriteAsync<T>(Stream stream, T value)
        {
            return JsonSerializer.SerializeAsync(stream, value);
        }

        public Task<IByteResult> WriteAsync<T>(T value)
        {
            var result = JsonSerializer.SerializeUnsafe(value);
            return Task.FromResult<IByteResult>(new Utf8ByteResult(result));
        }

        public string Write(object value)
        {
            return JsonSerializer.NonGeneric.ToJsonString(value, _jsonFormatterResolver);
        }

        private class Utf8ByteResult : IByteResult
        {
            public Utf8ByteResult(ArraySegment<byte> result)
            {
                Result = result;
            }

            public void Dispose()
            {
            }

            public ArraySegment<byte> Result { get; }
        }
    }
```

**Comment by joemcbride** [comment]
Just to comment on this.

JSON.NET is used in 2 places, once on input to convert from JSON.NET values to .NET Values, and once on output in the DocumentWriter. There should be no other uses of it (if there are then we failed!), as it was a very purposeful decision to enable this exact request to use a different serializer.

That said, I think there can be work done to create a smarter DocumentWriter so you wouldn't have to do so much work to replace it. You should be able to use another serializer with only those two things in mind.

**Comment by DSilence** [comment]
Thanks for your comment @joemcbride! I was wondering if there is demand for replacing JsonNet for the process of reading values. For our project we're OK with using JsonNet for that, but others might need that functionality. If that is the case, there is a point in creating an abstraction for that (and I do realize that the task is far from trivial due to dynamic nature of variables).

**Comment by sungam3r** [comment]
Done with the latest changes. See README and new packages : GraphQL.NewtonsoftJson and GraphQL.SystemTextJson.
