### ISSUE TITLE
SourceLink support

### ISSUE THREAD

**Issue by DSilence** [graphql-dotnet/graphql-dotnet#963]
## Summary

It would be cool if GraphQL libraries supported SourceLink (https://github.com/dotnet/sourcelink). SourceLink enable better step through third party code from within VisualStudio or Rider. 

### Motivation

Better dev experience.

**Comment by abarger-bss** [comment]
I noticed #870 implemented this but the PR author closed it. We would also find this valuable

**Comment by SimonCropp** [comment]
Do one if u want to submit a new PR?

**Comment by abarger-bss** [comment]
@SimonCropp  Not sure what you're asking... Your were the author of the closed PR. I noticed it sat idle for 2 months before it was closed. I'm happy to make a new PR for this, but does this one stand any better chance of getting merged?

**Comment by sungam3r** [comment]
Done in #1475
