### ISSUE TITLE
MutationResolver return data to ExecutionResult is null

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/graphql-dotnet#964]
I have a MutationResolver like:
`public class MutationResolver<T> : IFieldResolver where T : DbContext`

I can see with a debug point that there is data at the time "return" is called for:
`public object Resolve(ResolveFieldContext rfc)`

But when I get to:
`ExecutionResult result = await _executer.ExecuteAsync`

And look at:
`result.Data`

It's defined with the one KeyValuePair (correctly), but then the value is null.

I then get the error:
```
{
  "data": {
    "MyObject": null
  },
  "errors": [
    {
      "message": "GraphQL.ExecutionError: Error trying to resolve MyObject. ---> System.InvalidOperationException: Unexpected type: \r\n   at GraphQL.Execution.ExecutionStrategy.BuildExecutionNode(ExecutionNode parent, IGraphType graphType, Field field, FieldType fieldDefinition, String[] path)\r\n   at GraphQL.Execution.ExecutionStrategy.SetSubFieldNodes(ExecutionContext context, ObjectExecutionNode parent, Dictionary`2 fields)\r\n   at GraphQL.Execution.ExecutionStrategy.SetSubFieldNodes(ExecutionContext context, ObjectExecutionNode parent)\r\n   at GraphQL.Execution.ExecutionStrategy.<ExecuteNodeAsync>d__7.MoveNext()\r\n   --- End of inner exception stack trace ---",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "MyObject"
      ],
      "extensions": {
        "code": "INVALID_OPERATION"
      }
    }
  ]
}
```
The even stranger part is I don't have any problems returning query data running through the exact same controller.

Any ideas what would be happening between:
`public object Resolve(ResolveFieldContext rfc)`
and
`ExecutionResult result = await _executer.ExecuteAsync`
That would eat the return value?

Thanks for the help!

**Comment by joemcbride** [comment]
That error appears to be from here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/952b4ef6950e51bbfe009354f0520180c343e8d4/src/GraphQL/Execution/ExecutionStrategy.cs#L157

You would get that error when the `GraphType` is not one of: `ListGraphType`, `IObjectGraphType`, `IAbstractGraphType `, `ScalarGraphType`.

What does the `GraphType` are you using look like?

**Comment by OpenSpacesAndPlaces** [comment]
> What does the GraphType are you using look like?

`public object Resolve(ResolveFieldContext rfc)`
Would just be returning an Entity Framework Core object.

For the GraphType definition I've been using like this for "Mutation" on "Schema":
` public class GraphQLMutation<T> : ObjectGraphType<object> where T : DbContext`

And then like the following for each of the "ResolvedType" on the  "FieldType" definition
`public class MutationTableType<T> : ObjectGraphType<object> where T : DbContext`

As mentioned, the part that confusing me is that queries work fine, and the resulting definitions represented in GraphIQL look good. It's just something is nulling the DB object for "Resolve" in the mutation case, but not for queries.

**Comment by OpenSpacesAndPlaces** [comment]
@joemcbride Any other suggestions or additional details I can provide?

**Comment by joemcbride** [comment]
Can you provide the code for what your `GraphType`'s looks like?  Are you providing a unique GraphType Name for each permutation of `GraphQLMutation<T>` and `MutationTable<T>`?  Can you print your schema and post that using `SchemaPrinter`?

**Comment by OpenSpacesAndPlaces** [comment]
@joemcbride 

SchemaPrinter + "unique GraphType Name " were very helpful hints - I was able to trace it further.

The underlying problem seems to be that I used the same name for the Query objects and the Mutation objects. 

If I comment out the QueryResolver - Mutations then work fine:
```
 new Schema
			{
				//Query = new GraphQLQuery<T>(
```
Is there a way for me to maintain the same naming between the two resolvers or is the expectation that I have to have three separate namings:
```
MyObjectQuery
MyObjectMutation
MyObjectMutationInput
```

I ask, because the underlying definition is the same for all three cases - at the moment there is no DTO needed for the use case.

**Comment by joemcbride** [comment]
If they are different classes, they need to have a unique name.  `Input` objects also need to inherit from `InputObjectGraphType`, so they would also need to be separate.  Re-using the same GraphType with a mutation is common, as in returning that GraphType from the mutation, though typically the parent GraphTypes are separate.

A schema has only one root `Query` and one root `Mutation` object.  Your Query objects should not have mutation functions on them and your Mutation objects should not have Query functions on them.  Part of that is because Query objects get ran in parallel whereas Mutation objects get ran serially.

`hero` on `Query` returns a `Droid`
`add` on `Mutation` returns a `Droid`

```gql
type Droid {
  id: String!
  name: String!
}

input DroidInput {
  name: String!
}

type Query {
  hero: Droid
}

type Mutation {
  add(input: DroidInput!): Droid!
}

schema {
  query: Query
  mutation: Mutation
}
```

**Comment by joemcbride** [comment]
My only guess is that somehow the `GraphType` is null.  The most likely candidate would be that the name of the type is not being treated as unique and one type is overriding the other.  Your type names look very similar.  Have you tried drastically different type names?

What I described above is a known issue:  #827

**Comment by OpenSpacesAndPlaces** [comment]
A simple suffix pattern on the FieldType names didn't improve anything:
```
type Mutation {
  tblTemplate_m(data: TblTemplate_i, key: TblTemplate_key): tblTemplate
  tblTemplate_m_list(data: TblTemplate_i, key: TblTemplate_key): [tblTemplate]
}

type Query {
 tblTemplate_q(tId: String, ctId: String, tCtIds: String, tDesc: String, tDisplayPage: String, tName: String, pageSize: Int, pageNumber: Int, filters: String, orderBy: String, includes: String): tblTemplate
  tblTemplate_q_list(tId: String, ctId: String, tCtIds: String, tDesc: String, tDisplayPage: String, tName: String, , pageSize: Int, pageNumber: Int, filters: String, orderBy: String, includes: String): [tblTemplate]
}

type tblTemplate {
  tId: Int
  ctId: Int
  tCtIds: String
  tDesc: String
  tDisplayPage: String
  tName: String
}

input TblTemplate_i {
  tId: Int
  ctId: Int
  tCtIds: String
  tDesc: String
  tDisplayPage: String
  tName: String
}

input TblTemplate_key {
  tId: Int!
}

```

But it led me to try changing the name of the "Resolved Type" - that solved the problem:
```
type Mutation {
  tblTemplate(data: tblTemplate, key: tblTemplate_key): tblTemplate_m
  tblTemplate_list(data: tblTemplate, key: tblTemplate_key): [tblTemplate_m]
}

type Query {
 tblTemplate(tId: String, ctId: String, tCtIds: String, tDesc: String, tDisplayPage: String, tName: String, ct: String, pageSize: Int, pageNumber: Int, filters: String, orderBy: String, includes: String): tblTemplate_q
  tblTemplate_list(tId: String, ctId: String, tCtIds: String, tDesc: String, tDisplayPage: String, tName: String, ct: String, pageSize: Int, pageNumber: Int, filters: String, orderBy: String, includes: String): [tblTemplate_q]
}

input tblTemplate {
  tId: Int
  ctId: Int
  tCtIds: String
  tDesc: String
  tDisplayPage: String
  tName: String
}

input tblTemplate_key {
  tId: Int!
}

type tblTemplate_m {
  tId: Int
  ctId: Int
  tCtIds: String
  tDesc: String
  tDisplayPage: String
  tName: String
}

type tblTemplate_q {
  tId: Int
  ctId: Int
  tCtIds: String
  tDesc: String
  tDisplayPage: String
  tName: String
}

```

So it seems that you can share the CLR type, but the GraphQL ResolvedType name needs to be different between Query/Mutation (ultimately creating a dupe definition in the schema). It's odd that the underlying schema seems to need a name variation and separate object definitions, but that said, now that I know what the trick, the end result is nearly exactly what I was looking for. Even though the schema has the "_q" and "_m" in the ResolvedType name, the FieldType names are all almost the same. Thus when using GraphiQL or coding out front-end code, developers aren't needing to remember a naming pattern.

Thanks for the help in tracking down a fix.

**Comment by sungam3r** [comment]
@OpenSpacesAndPlaces could you check again with the latest preview? #1284 is likely will indicate the cause of the error.

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
