### ISSUE TITLE
Querying for a matrix.

### ISSUE THREAD

**Issue by MirceaMatei** [graphql-dotnet/graphql-dotnet#966]
Hello,

I have an issue with the way GraphQL returns values in a query. I am trying to return a matrix (List of Lists of decimals) and I am getting a weird output. This is weird because before updating to the latest version I was able to return a matrix. I am using the latest GraphQL library. I also tried rolling back to a previous version but it seems it stopped working. How should I declare the field so that I can return a matrix?

This is the way I declared the field.
```
Field<ListGraphType<ListGraphType<DecimalGraphType>>>()
                .Name("someRandomName")
                .Resolve(context =>
                {
                     var newList = new List<List<decimal>>();
                    var newItem = new List<decimal>();
                    var newItem2 = new List<decimal>();

                    newItem.Add(10.0m);
                    newItem.Add(10.0m);
                    newItem.Add(10.0m);

                    newItem2.Add(10.0m);
                    newItem2.Add(10.0m);
                    newItem2.Add(10.0m);

                    newList.Add(newItem);
                    newList.Add(newItem2);

                    return newList;
                });
```

This is the output:
```
	 "someRandomName": [
		null,
		null
	],
```

**Comment by joemcbride** [comment]
That should certainly work and looks like correct syntax at first glance.  What specific versions are you referring to?  Can you provide a failing test?

**Comment by MirceaMatei** [comment]
> That should certainly work and looks like correct syntax at first glance. What specific versions are you referring to? Can you provide a failing test?

I am currently using the 2.4.0 version but previously I used the 0.16.0. I only have the test I provided where on the query I receive the two null values instead of the matrix.

**Comment by MirceaMatei** [comment]
After some testing these are the results that I gathered:

When using this definition for the field:
```
**Field<ListGraphType<ListGraphType<DecimalGraphType>>>()**
	.Name("someRandomName")
	.Resolve(context =>
		{
			var newList = new List<List<decimal>>();
			var newItem = new List<decimal>();
			newItem.Add(10.0m);
			newList.Add(newItem);
			
			var secnNewItem = new List<decimal>();
			secnNewItem.Add(10.0m);
			newList.Add(secnNewItem);
			
			return newList;
        });
```
The result is:		
` "someRandomName":[ null,null ]`

 Changing the configuration to:
```
 **Field<ListGraphType<DecimalGraphType>>()**
	.Name("someRandomName")
	.Resolve(context =>
		{
			var newList = new List<List<decimal>>();
			var newItem = new List<decimal>();
			newItem.Add(10.0m);
			newList.Add(newItem);
			
			var secnNewItem = new List<decimal>();
			secnNewItem.Add(10.0m);
			newList.Add(secnNewItem);
			
			return newList;
        });
```
I get an error:
`"Could not find conversion from System.Collections.Generic.List`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] to System.Decimal",
`
Changing the GraphType:
```
 **Field<ListGraphType<ListGraphType<StringGraphType>>>()**
	.Name("someRandomName")
	.Resolve(context =>
		{
			var newList = new List<List<string>>();
			var newItem = new List<string>();
			newItem.Add("10.0m");
			newList.Add(newItem);
			
			var secnNewItem = new List<string>();
			secnNewItem.Add("10.0m");
			newList.Add(secnNewItem);
			
			return newList;
        });
```
Same result:
`"someRandomName":[ null,null ]`

The fun part is here:
 ```
**Field<ListGraphType<StringGraphType>>()**
	.Name("someRandomName")
	.Resolve(context =>
		{
			var newList = new List<List<string>>();
			var newItem = new List<string>();
			newItem.Add("10.0m");
			newList.Add(newItem);
			
			var secnNewItem = new List<string>();
			secnNewItem.Add("10.0m");
			newList.Add(secnNewItem);
			
			return newList;
        });
```
I get the correct result:
`"someRandomName": [ [ "10.0m" ], ["10.0m" ] ]`
