### ISSUE TITLE
Can I add a QueryArgument than can accept either string or List<string> for incoming values?

### ISSUE THREAD

**Issue by pravinhabbu4u** [graphql-dotnet/graphql-dotnet#988]
Can I add a QueryArgument than can accept either string or List<string> for incoming values?

new QueryArgument< StringGraphType   > { Name = "fType"},
new QueryArgument<  ListGraphType  <  StringGraphType  >> { Name = "fType"},

An input data type which is more as IEnumerable

Use case: To make something backward compatible during data type change for an incoming QueryArgument
query UseCaseExample {
 QueryField(fType:"ValueA" fType__AsList:["Value1" "Value2"] ) {

can be handled as either
query UseCaseExample {
 QueryField(fType:"ValueA") {

OR
query UseCaseExample {
 QueryField(fType:["Value1" "Value2"] ) {

**Comment by joemcbride** [comment]
No, that is not possible due to the strong type safety that is defined in the GraphQL specification.  You will need to deprecate the old argument and provide a new one.

**Comment by pravinhabbu4u** [comment]
Thanks for the clarification. I have instead provided 2 separate arguments (with a pre-defined naming standards to handle this scenario)

new QueryArgument< StringGraphType > { Name = "fType"},
new QueryArgument< ListGraphType < StringGraphType >> { Name = "fType__AsList"},
