### ISSUE TITLE
List Graph Type and Non Nulls

### ISSUE THREAD

**Issue by KoditkarVedant** [graphql-dotnet/graphql-dotnet#994]
I was going through `graphql` spec for `List and NonNull` and noticed that as of now we do not handle it in our library.
```
myField: [String!]
```
This means that the list itself can be null, but it can't have any null members. For example, in JSON:
```
myField: null // valid
myField: [] // valid
myField: ['a', 'b'] // valid
myField: ['a', null, 'b'] // error
```
Now, let's say we defined a Non-Null List of Strings:
```
myField: [String]!
```
This means that the list itself cannot be null, but it can contain null values:
```
myField: null // error
myField: [] // valid
myField: ['a', 'b'] // valid
myField: ['a', null, 'b'] // valid
```
[ref](https://graphql.github.io/learn/schema/#lists-and-non-null)

I have already added the failing test cases while working on #424 enhancement.

**Comment by KoditkarVedant** [comment]
@joemcbride I have completed the changes, shall I create separate PR or should I push my changes in #980 PR itself?

**Comment by joemcbride** [comment]
We can keep them to the same PR, since I can't merge the one with failing tests.
