### ISSUE TITLE
For graph types using Field( c => c.something) always makes string types required. Is that intended?

### ISSUE THREAD

**Issue by nportelli** [graphql-dotnet/graphql-dotnet#996]
I recently switched our  graph types from a format for fields like
`Field<StringGraphType>().Name("name").Description("Description")`

to

`Field(p => p.name).Description("Description");`

Now all string types are declared as non-null and will return execution errors.  Even though it returns results.  Is this working as intended?  Is there any advantage in using the expression way vs the extension method way?  I know with the extension method it starts everything off as an object.

**Comment by joemcbride** [comment]
The expression helps when you have that data model and you rename fields.  There is a parameter to the expression method to make it nullable (`nullable = true`).  Behind the scenes they both do the exact same thing.
